### ISSUE TITLE
Remove instance from Eureka

### ISSUE THREAD

**Issue by Zenithonnet** [spring-cloud/spring-cloud-netflix#1000]
We need a configuration in Eureka(currently am using non Cloud environment) to remove a particular instance from Eureka as there are issues when there are wrong service getting registered with Eureka and as a admin i want to manually kick out that particular service instance as they result in error when routed to it.

**Comment by spencergibb** [comment]
Sorry, can you explain your use case a little more?

**Comment by Zenithonnet** [comment]
Say for a service there are two instance which got registered with Eureka from two different machine as shown below. 
And one of the service is not responding/not working as expected(business functionality) but got registered with Eureka by mistake and i want to manually kick that service instance out(10.120.18.160:payments:8888). Is there any option available for that as when Zuul routes the request to this instance it fails?

Application	        AMIs	Availability Zones	Status
PAYMENTS              n/a (1)	(1)	                        UP (2) - 10.120.18.160:payments:8888, 169.120.18.12:payments:8888

**Comment by spencergibb** [comment]
Is shutting down the offending service an option?

**Comment by Zenithonnet** [comment]
Yes we can do that but say we have many services registered and turn around time for requesting the individual user to shutdown the service and make it happen is lengthy. So as a administrator if i receive request that a particular instance isn't working as expected, is there any way to kill it from eureka itself instead of requesting that service owner to shutdown the service?

**Comment by spencergibb** [comment]
See "Take instance out of service" here https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by Zenithonnet** [comment]
How do we use it? As am using spring eureka dependency, and the Eureka is hosted in http://localhost:8761/

**Comment by dsyer** [comment]
From the wiki link:

> De-register application instance |	DELETE /eureka/v2/apps/appID/instanceID	| HTTP Code: 200 on success
