### ISSUE TITLE
Improve documentation for the server configuration in the yml file.

### ISSUE THREAD

**Issue by agomezcafeto** [spring-cloud/spring-cloud-netflix#1002]
I can not find any documentation about how to configure the eureka server, specifically, documentation related with the yml file.

**Comment by sfat** [comment]
Maybe [here](http://cloud.spring.io/spring-cloud-static/docs/1.0.x/spring-cloud.html#_standalone_mode ?)?

**Comment by agomezcafeto** [comment]
Thanks.
