### ISSUE TITLE
Eureka metrics are not exposed to jmx or rest endpoint /metrics

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-netflix#1015]
Hi all!
Recently I was investigating metrics for Eureka server and have found class EurekaMonitors. I also found that metrics stated in this class should be in /metrics endpoint, because ServoMetricsAutoConfiguration has ServoMetricCollector which collects all metrics from DefaultMonitorRegistry singleton. I was not able to find any of the metrics from EurekaMonitors class neither in jmx nor in /metrics. I checked /autoconfig -- ServoMetricsAutoConfiguration is in positive matches, metricsCollector as well. Could you please help where the following metrics can be found or enabled? Or how should be current case investigated? Thanks.

We are currently using the following versions:
eureka-core 1.1.147
spring-cloud-netflix-core 1.0.4.RELEASE

**Comment by vasilievip** [comment]
Did you try to update to latest spring-cloud?

**Comment by Aloren** [comment]
I have upgraded to spring-cloud 1.1.0.RELEASE and still not able to see metrics from `EurekaMonitors`. Maybe it is an issue that these metrics get registered into another `MetricRegistry`?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
