### ISSUE TITLE
Missing PATCH request while calling service using RestTemplate

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#1018]
Hi,

I am using Rest Template (@LoadBalanced) to send PATCH request from one of my service to a Spring Data rest service.

Exception detail
No enum constant com.netflix.client.http.HttpRequest.Verb.PATCH

I am seeing some workarounds/fixes for the same when using FeignClient. Is there any way I can get this to work with RestTemplate?

Thanks

**Comment by spencergibb** [comment]
What version of spring-cloud are you using?

**Comment by rbkumar88** [comment]
Brixton.RC1 

From maven dependency tree
 [INFO] |  |  +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.1.0.M5
:compile

**Comment by spencergibb** [comment]
If you're using Brixton.RC1, the -core.jar should be 1.1.0.RC1. Either way, upgrade to the latest RC2 should fix your problem. You'll need to create a `RestTemplate` for your app though. https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#spring-resttemplate-as-a-load-balancer-client
