### ISSUE TITLE
java.lang.ClassNotFoundException: rx.Single on upgrading from 1.1.0.M5 to 1.1.0.RC2

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#1019]
Hi,

I was using Brixton.RC1 as spring-cloud-dependencies  but with the following dependency
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-hystrix</artifactId>
    <version>1.1.0.M5</version> 
</dependency>
```
When I upgrade to Brixton.RC2 and comment out the 1.1.0.M5 on the spring-cloud-starter-hystrix dependency. Am getting following error.
```Caused by: java.lang.ClassNotFoundException: rx.Single```

**Comment by spencergibb** [comment]
Are you using the BOM as it shows in the [docs](http://projects.spring.io/spring-cloud/)?
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>1.3.3.RELEASE</version>
</parent>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Brixton.RC2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-eureka</artifactId>
    </dependency>
</dependencies><repositories>
    <repository>
        <id>spring-milestones</id>
        <name>Spring Milestones</name>
        <url>https://repo.spring.io/libs-milestone</url>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by rbkumar88** [comment]
Hi,

I earlier had the following in my pom.xml

spring-boot-starter-parent is in my local repo.

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.3.RELEASE</version>
		<relativePath /> 
	</parent>
<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

But when I simply removed the above snippets and replace with the ones you gave, it couldnt download the spring-cloud-starter-parent-1.3.3.RELEASE.pom from any repo.

**Comment by spencergibb** [comment]
Actually that should come from maven central. Maybe your company has a proxy?

**Comment by rbkumar88** [comment]
Hi,

My company has proxy and able to pull from maven central but am getting confused here.

When I search for "spring-cloud-starter-parent" in search.maven.org, I see the latest/last version only at 1.0.0.RELEASE and group id is org.springframework.cloud or org.springframework.boot.

Seems like Brixton just got pushed.

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>Brixton.RELEASE</version>
</dependency>

group id is org.springframework.cloud or org.springframework.boot? If so where can I find 1.3.3.RELEASE? It is surely not in maven central nor in https://repo.spring.io/libs-milestone

**Comment by spencergibb** [comment]
Without showing your whole pom, it's very confusing.

**Comment by rbkumar88** [comment]
[pom-BrixtonRC2.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/259833/pom-BrixtonRC2.zip)

From my Maven settings.xml

<repository>
					<id>maven2-repository.dev.java.net</id>
					<name>Java.net Repository for Maven 2</name>
					<url>http://repo.maven.apache.org/maven2/</url>
				</repository>

**Comment by spencergibb** [comment]
please use triple backticks for code blocks (like xml). I've had to reformat all of your comments to read them.

**Comment by spencergibb** [comment]
That pom looks correct.

**Comment by rbkumar88** [comment]
But still am not able to download this from central maven
Do you see the below in maven central repo.
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>1.3.3.RELEASE</version>
</parent>
```
O/p of mvn clean install

```
Downloading: http://lvdma541.phx.aexp.com/maven-repo/org/springframework/boot/sp
ring-cloud-starter-parent/1.3.3.RELEASE/spring-cloud-starter-parent-1.3.3.RELEAS
E.pom
Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring
-cloud-starter-parent/1.3.3.RELEASE/spring-cloud-starter-parent-1.3.3.RELEASE.po
m
Downloading: http://repo.XXX.extra.XXX.com/archiva/repository/third-party/org/
springframework/boot/spring-cloud-starter-parent/1.3.3.RELEASE/spring-cloud-star
ter-parent-1.3.3.RELEASE.pom
Downloading: https://repo.spring.io/libs-milestone/org/springframework/boot/spri
ng-cloud-starter-parent/1.3.3.RELEASE/spring-cloud-starter-parent-1.3.3.RELEASE.
pom
Downloading: https://repo.maven.apache.org/maven2/org/springframework/boot/sprin
g-cloud-starter-parent/1.3.3.RELEASE/spring-cloud-starter-parent-1.3.3.RELEASE.p
om
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
................. Return code is: 502 , R
easonPhrase:notresolvable. and 'parent.relativePath' points at wrong local POM @
 line 14, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException
```

**Comment by spencergibb** [comment]
I see it should be `org.springframework.boot:spring-boot-starter-parent`

**Comment by rbkumar88** [comment]
Hi,

Got this issue resolved. Please close it. But still seeing Invalid HTTP method: PATCH method issue with the new RELEASE jars.Opening new issue

Thanks for the support.

**Comment by andreasevers** [comment]
I also experienced this issue upon upgrading.

Simply bumping the `io.reactive.rxjava` dependency version fixed it.

From:
```xml
<dependency>
        <groupId>io.reactivex</groupId>
        <artifactId>rxjava</artifactId>
        <version>1.0.10</version>
</dependency>
```
To:
```xml
<dependency>
        <groupId>io.reactivex</groupId>
        <artifactId>rxjava</artifactId>
        <version>1.1.5</version>
</dependency>
```
