### ISSUE TITLE
Using WebMvcConfigurerAdapter.addCorsMappings fails to enable CORS processing on ZuulHandlerMapping

### ISSUE THREAD

**Issue by ahawtho** [spring-cloud/spring-cloud-netflix#1021]
In a `@Configuration` class I have a WebMvcConfigurerAdapter with the following method:

``` java
public void addCorsMappings(final CorsRegistry registry) {
    registry.addMapping("/**");
}
```

I also have `@EnableZuulProxy`, but I don't see any Access-Control-Allow-Origin headers and the org.springframework.web.servlet.handler.AbstractHandlerMapping.setCorsConfigurations(Map<String, CorsConfiguration>) is never invoked on the ZuulHandlerMapping .

Is this expected? Is there a different way I should be enabling CORS handling for proxy paths?

**Comment by dsyer** [comment]
I think it's expected. The code that configures the `ZuulHandlerMapping` knows nothing about CORS. You'd have to inject the configurations yourself for now. If you can figure out how to do that you can probably propose a fix.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
