### ISSUE TITLE
SpringMvcContract does not support path parameters defined in interface's @RequestMapping annotation

### ISSUE THREAD

**Issue by jebeaudet** [spring-cloud/spring-cloud-netflix#1023]
In `SpringMvcContract`, the path defined in the interface's class `@RequestMapping` annotation is prepended at the end of the `parseAndValidateMetadata(Class<?> targetType, Method method)` method. While this works fine for most cases, it does not support path parameters defined there that apply to all methods. This is because the `PathVariableParameterProcessor` expect it to be in the `MethodMetadata` at the time or it adds it as a form param as a fallback.

Example of a non working interface at the moment: 
```
	@RequestMapping("/prepend/{anotherId}")
	public interface Example {
		@RequestMapping(value = "/test/{id}", method = RequestMethod.GET)
		ResponseEntity<TestObject> getTest(@PathVariable String anotherId, 
                                           @PathVariable String id);

		@RequestMapping(method = RequestMethod.POST)
		TestObject postTest(@PathVariable String anotherId, 
                            @RequestBody TestObject object);
	}
```
I'll submit a PR shortly! Thanks again for the great lib.

**Comment by spencergibb** [comment]
Using @RequestMapping on an interface level is not supported because of the way spring MVC works. It assumes they are real controllers. There is a path attribute on @FeignClient.

**Comment by jebeaudet** [comment]
Hmm, we're not using `@FeignClient` here because we're generating clients with the Feign.Builder() to use in some functional tests. 

We're using the pattern defined in the documentation with one interface defining the resource and a controller implementing it and a client extending the interface in separate projects. AFAIK, using annotation on the interface worked properly when implementing it in our controller but I'll have to verify that with my colleague tomorrow. You're saying that this shouldn't work in the first place is that it?

**Comment by jebeaudet** [comment]
We're implementing the pattern defined here http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-inheritance

It's working well having all the @RequestMapping annotations on the shared interface with the client extending the interface and the resource implementing the interface. The only thing not working is the support for query param on the class lever @RequestMapping annotation which this PR provides a fix.
