### ISSUE TITLE
EurekaClient Bean initialization timing error

### ISSUE THREAD

**Issue by sunnykaka** [spring-cloud/spring-cloud-netflix#1026]
I'm using Eureka Client and RestTemplate to discover service.

The service name is ACCOUNT.

When I invoke `restTemplate.getForObject`, I encountered this Exception:

```
java.lang.IllegalStateException: No instances available for ACCOUNT

    at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.execute(RibbonLoadBalancerClient.java:79)
    at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor.intercept(LoadBalancerInterceptor.java:46)
    at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:85)
...
```

Here is my configuration:

```
@EnableDiscoveryClient
@SpringBootApplication
public class BaseApplication {

    @LoadBalanced
    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }
}
```

So I tried to debug the source code, I found when `DiscoveryEnabledNIWSServerList.obtainServersViaDiscovery` invoked,  `DiscoveryManager.getInstance()
                .getDiscoveryClient();` return null. The initialization code in `EurekaClientAutoConfiguration` was executed at last. It seems that the execution order was wrong.

After I put this code in my BaseApplication, everything goes well.

```
    @Bean(destroyMethod = "shutdown")
    @org.springframework.cloud.context.config.annotation.RefreshScope
    public EurekaClient eurekaClient(ApplicationInfoManager manager,
                                     EurekaClientConfig config,
                                     DiscoveryClient.DiscoveryClientOptionalArgs optionalArgs,
                                     ApplicationContext context) {
        manager.getInfo(); // force initialization
        return new CloudEurekaClient(manager, config, optionalArgs, context);
    }
```

spring-cloud-netflix version: 1.1.0.RELEASE

**Comment by spencergibb** [comment]
Can you provide a sample project that recreates the problem?

**Comment by sunnykaka** [comment]
Hi @spencergibb .
I have created a [project](https://github.com/sunnykaka/spring-cloud-issue) to reproduce the problem.
Please refer to the README.

**Comment by dsyer** [comment]
Thanks for the sample. Unfortunately it isn't valid (yet):

```
$ mvn validate
No wrapper found, running native Maven
[INFO] Scanning for projects...
Downloading: http://repo.spring.io/repo/org/springframework/cloud/spring-cloud-starter-parent/Brixton.RELEASE/spring-cloud-starter-parent-Brixton.RELEASE.pom
Downloaded: http://repo.spring.io/repo/org/springframework/cloud/spring-cloud-starter-parent/Brixton.RELEASE/spring-cloud-starter-parent-Brixton.RELEASE.pom (5 KB at 7.5 KB/sec)
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.akkafun.mysteam:order-service:1.0-SNAPSHOT (/home/dsyer/dev/cloud/workspace/sunnykaka/order/pom.xml) has 1 error
[ERROR]     Child module /home/dsyer/dev/cloud/workspace/sunnykaka/order/api of /home/dsyer/dev/cloud/workspace/sunnykaka/order/pom.xml does not exist
[ERROR] 
...
```

Do you think you could fix it and ping us back?

**Comment by sunnykaka** [comment]
Hi @dsyer .
I have fix it. Please update and try again.

**Comment by dsyer** [comment]
Sorry. I still can't build on the command line. Your "common" library has some issues with its pom I think.

**Comment by sunnykaka** [comment]
@dsyer 
Sorry I forget to remove the maven plugin in pom.xml.
It can build now.

**Comment by cer** [comment]
I've just upgraded [this example application](https://github.com/cer/microservices-examples) to use BRIXTON and have started seeing this problem. 
I get the impression that the error occurs the first time the RestTemplate is invoked.
Subsequent calls generally succeed although sometimes I see Hystrix timeouts.

The steps to reproduce (on Mac OSX with Docker compose installed) are:

1. Run `./build-and-test-all.sh`
2. Run `./run-e2e-test.sh` - this step should reproduce the problem

If you then run `(cd e2e-test ; ./gradlew cleanTest test)` directly it should succeed.

**Comment by dsyer** [comment]
@sunnykaka I added an `OrderApplication` to your "order/core" (mirroring the `AccountApplication`) and ran all three apps. The /orders/place endpoint worked fine (the one that uses the ACCOUNT service in a load balanced rest template).

@cer the first time can always be too soon for the caches to have equalized (by default the heartbeat is only sent every 30sec and you need to register first and then get a heartbeat before the catalog cache is initialized). I don't think anything changed in Brixton, other than the eureka version (big changes internally, but the same basic protocol on the surface). I'll have a dig into your app as well if I can get past the platform issues.

**Comment by cer** [comment]
@dsyer Perhaps what has changed is as well as upgrading to Brixton that I've added an automated test that runs the application (configured to use Eureka) and then immediately tests the UI.  The script waits for the target service to be registered with Eureka. The test also waits for  HealthIndicator that returns OK if and only if the EurekaClient in the web application can lookup the service. What are the platform issues that you refer to? Windows?!

**Comment by dsyer** [comment]
Maybe the test should wait a bit longer. I'd have thought if the eureka client can see your service it should be fine though (you can dig that out of the standard /health endpoint BTW). It would be good to know if it works anyway.

By "platform" I meant MacOS, Docker, Scala, Gradle (all of which slow me down -- MacOS is the only one I don't have). That's not a complaint -- you can use whatever platforms you like, and the more the merrier, it's just friction for me trying it out. I did spend an hour with it today, but there's a step where Gradle says it might take "30 seconds" to launch a docker container and it never came back. I noticed a lot of files created by root, so I wondered if there were permission issues.

**Comment by sunnykaka** [comment]
@dsyer 
Yes, the `placeOrder` works fine in `OrderApplication`, but it can't work in junit test.

If you just run `RegistrationServer` and `AccountApplication`, then start `OrderServiceTest`, 
you can see the exception.

**Comment by dsyer** [comment]
It's not a unit test then. You are running a full end to end test with eureka from junit. I don't think that's really a good pattern to encourage. If you need to do that, then you should work out a way to wait for the service catalog caches to equalize before starting the test, I guess.

**Comment by sunnykaka** [comment]
Yes, it's a integration test.
So, it's a service catalog cache problem because junit test run too fast?
I'll try it, thanks.

**Comment by marcingrzejszczak** [comment]
@sunnykaka is it still a problem with the latest release?

**Comment by sunnykaka** [comment]
@marcingrzejszczak 
It's work fine in F.release
