### ISSUE TITLE
Question: does zuul support longest prefix matching?

### ISSUE THREAD

**Issue by WeipingGuo** [spring-cloud/spring-cloud-netflix#1028]
Hi ,

I have two routes like:
/api/v0/ ---> sever 1
/api/v0/user ---> server 2

last time i checked, zuul did not support this kind of routes, it always routed to server 1. Is this added now?

**Comment by spencergibb** [comment]
No, it routes to the first match.

**Comment by WeipingGuo** [comment]
oh, thanks. I wished it could.

**Comment by spencergibb** [comment]
In your example, just flipping the order would accomplish what you want.

**Comment by WeipingGuo** [comment]
thank you, will try it out.
