### ISSUE TITLE
Spring Config Server with SVN | Certifcate and JSON

### ISSUE THREAD

**Issue by Zenithonnet** [spring-cloud/spring-cloud-netflix#1029]
Hi Team,

Have configured the Spring Config Server in PCF environment.(Have not used the config Server available in Marketplace of PCF but have used the Spring Config Server as it doesn't support SVN)

1. Am able to retrieve the application specific yml file from config Server but am not able to retrieve JSON file hosted in SVN. How do we invoke JSON(like string literal as defined in JSON) from SVN through ConfigServer?

2. Can we host certificates in SVN, if so how i can refer that in application specific yml file for defining any certificate path. Earlier when using the filepath in ConfigServer have referred like below. But can i configure if hosted in SVN?
ssl_trusted_certs: C:/JMS_Certs/entrust.ca1.nonprod.root.cert.pem

**Comment by spencergibb** [comment]
Probably should file this issue in https://github.com/spring-cloud/spring-cloud-config, not spring-cloud-netflix.
