### ISSUE TITLE
Zuul Proxy: Custom RouteLocator must inherit from DiscoveryClientRouteLocator

### ISSUE THREAD

**Issue by droy314** [spring-cloud/spring-cloud-netflix#1030]
When trying to inject a custom RouteLocator, the ZuulProxyConfiguration requires the instance to be a DiscoveryClientRouteLocator.

The logged error message is:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'zuulEndpoint' defined in class path resource [org/springframework/cloud/netflix/zuul/ZuulProxyConfiguration$RoutesEndpointConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.cloud.netflix.zuul.filters.discovery.DiscoveryClientRouteLocator]: No qualifying bean of type [org.springframework.cloud.netflix.zuul.filters.discovery.DiscoveryClientRouteLocator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.netflix.zuul.filters.discovery.DiscoveryClientRouteLocator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
```
```
ZuulProxyConfiguration.RoutesEndpointConfiguration expects a DiscoveryClientRouteLocator to inject the zuul RoutesEndpoint. 
```
Changing the hierarchy to use DiscoveryClientRouteLocator works. Do we really need a DiscoveryClientRouteLocator instead of a RouteLocator?

**Comment by dsyer** [comment]
I guess we do (or did you change it and it still worked?). Is that a problem?

**Comment by droy314** [comment]
Okay... I realize now I should have given more information.The request here is to change the argument type in <code>RoutesEndpointConfiguration</code>, where the <code>RoutesEndpoint</code> is setup, from <code>DiscoveryClientRouteLocator</code> to <code>RouteLocator</code>. [source code](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyConfiguration.java#L135-L142)

The RoutesEndpoint takes a RouteLocator and doesn't need a DiscoveryClientRouteLocator. So if this change is made, when someone needed to use a custom RouteLocator, they don't have to subclass from DiscoveryClientRouteLocator and they can continue to get the benefits the actuator. It isn't difficult to subclass the DiscoveryClientRouteLocator and override all the methods, but it seems like an unnecessary restriction.

This is certainly not a common usecase for the zuul proxy so wouldn't be high on the list, but if it could be done, it would be cleaner.

I haven't tried to change the ZuulProxyConfiguration to test. I'll give it a go this weekend.
