### ISSUE TITLE
Seeing Weird Behavior with Cloud Config, Eureka and Ribbon

### ISSUE THREAD

**Issue by carnellj** [spring-cloud/spring-cloud-netflix#1035]
I have two services (licensing and organization service) coming up and reading their configuration from Spring Cloud Config server(running inside containers).  One service, the licensing service is trying to calling the organization service via RestTemplate (and tried DiscoveryClient).

Even though all the services come up and register with Eureka, the licensing service only appears to ever see the Spring Cloud Configuration service.  I can hit all of the endpoints and see all of the services are there and are registered, but I am just puzzled as to why the licensing service can never "see" organization service for Eureka.

I have a git repo with all of the code:  https://github.com/carnellj/native_cloud_apps.  I am at a loss.  I would be surprised if this were a bug, but I have scoured dozens of examples and can not see what I am doing wrong.

**Comment by dsyer** [comment]
I can't see anywhere in the "chapter4" code that has a `RestTemplate` (is that where you mean). How is the license service supposed to be calling the organization service?

Also you have commented out `@EnableDiscoveryClient` in both services, so I'm not sure I'm really looking at the same code as you are.

P.S. don't put `@RefreshScope` on `@Configuration` classes.

P.S.S. You don't need `@EnableAutoConfiguration` if you also have `@SpringBootApplication`

**Comment by carnellj** [comment]
Hi Dave,

Thank you so much for responding so quick.  I forgot to push my code after
my commit.  I have pushed it.  Thanks again for the help.

    - John

**Comment by carnellj** [comment]
Hi Dave,

I just wanted to let you know that the issue was I was being impatient.  I
had to wait for the ribbon to realize the org service was there.  I was
trying to call the service too quickly.  Sorry about opening an issue.
Would love any feedback you can give on the code.  I am working on a Cloud
Applications patterns with Manning press and have been using Spring Cloud
as a great example of how to implement the pattens used for cloud-based
apps.

   Thanks again for the help
      John
