### ISSUE TITLE
Wrong port returned just after app registration

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#1036]
I'm using Eureka in following scenario:

1. Eureka starts
2. Spring Boot Admin Server registers itself in Eureka. Admin uses non standard port 8602. Default is probably 8080.
3. I see in sniffer that proper 8602 port is passed from Admin to Eureka 
4. Admin gets application list from Eureka using `GET /eureka/apps/delta` and Eureka returns port 8080 not 8602 for registered Admin instance!
5. Admin try to connect to this instance but it fails (wrong port) and logs error message about problem with connection.
6. After few seconds Eureka starts returning proper port number.

Related Admin issue: https://github.com/codecentric/spring-boot-admin/issues/196

**Comment by spencergibb** [comment]
Can you please share your configuration?

**Comment by tjuchniewicz** [comment]
It is little bit complicated to send configuration. Before I do it and take your time I want to do more test on my side. I'm confused about my last observations...

To disable error log problems on Admin side I set: `eureka.client.registerWithEureka = false` and Admin stopped to send POST messages to Eureka. Confirmed by sniffer. But... and this is something I don't know how is possible... Eureka sends for some time information about Admin in `/eureka/apps/` XML. Few seconds later this XML is again empty. Sniffer shows that Admin sends only GET requests. I sniff communication from Admin to Eureka only. I'm very confused. Seems impossible... I'm sure that I'm not running another instance of Admin in background accidentally.

Is there any possibility that Eureka gets information about Admin in different way than send by Admin?
Any ideas how to debug this? Where should I put the breakpoint?
Admin bug? Eureka client bug? My misunderstanding of how it works? I would be grateful for any suggestions.

**Comment by tjuchniewicz** [comment]
It is little bit complicated to send configuration. Before I do it and take your time I want to do more test on my side. I'm confused about my last observations...

To disable error log problems on Admin side I set: `eureka.client.registerWithEureka = false` and Admin stopped to send POST messages to Eureka. Confirmed by sniffer. But... and this is something I don't know how is possible... Eureka sends for some time information about Admin in `/eureka/apps/` XML. Few seconds later this XML is again empty. Sniffer shows that Admin sends only GET requests. I sniff communication from Admin to Eureka only. I'm very confused. Seems impossible... I'm sure that I'm not running another instance of Admin in background accidentally.

Is there any possibility that Eureka gets information about Admin in different way than send by Admin?
Any ideas how to debug this? Where should I put the breakpoint?
Admin bug? Eureka client bug? My misunderstanding of how it works? I would be grateful for any suggestions.

**Comment by tjuchniewicz** [comment]
It is little bit complicated to send configuration. Before I do it and take your time I want to do more test on my side. I'm confused about my last observations...

To disable error log problems on Admin side I set: `eureka.client.registerWithEureka = false` and Admin stopped to send POST messages to Eureka. Confirmed by sniffer. But... and this is something I don't know how is possible... Eureka sends for some time information about Admin in `/eureka/apps/` XML. Few seconds later this XML is again empty. Sniffer shows that Admin sends only GET requests. I sniff communication from Admin to Eureka only. I'm very confused. Seems impossible... I'm sure that I'm not running another instance of Admin in background accidentally.

Is there any possibility that Eureka gets information about Admin in different way than send by Admin?
Any ideas how to debug this? Where should I put the breakpoint?
Admin bug? Eureka client bug? My misunderstanding of how it works? I would be grateful for any suggestions.

**Comment by tjuchniewicz** [comment]
I had configured sniffing only for this param: `eureka.client.serviceUrl.defaultZone: http://localhost:2000/eureka/` Now also configured this: `eureka.client.eurekaServerPort: 2000` and now I see more communication. 

This is probably Admin bug or our services misconfiguration. Closing this issue. Sorry for taking up your time.

**Comment by tjuchniewicz** [comment]
The reason of my problem was `server.port` configuration property. I put it in `application.yml` not `bootstrap.yml`. 

If it is in `application.yml` Admin works as follows:

1. Admin starts and has 8080 port (default) in its context.
2. Admin registers itself using 8080 in Eureka at startup (uses Eureka Client).
3. Admin tries to monitor itself using wrong port 8080. This fails.
4. During Admin initialization `server.port` is switched to 8602.
5. Admin binds on 8602.
6. Admin registers 8602 in Eureka again using proper port 8602.
7. Admin tries to monitor itself using wrong port 8602. This works fine.

Problem will be resolved also by fix in Admin: https://github.com/codecentric/spring-boot-admin/issues/201.
