### ISSUE TITLE
Question: Is there a way to set connection timeout and socket timeout for only specific endpoints?

### ISSUE THREAD

**Issue by maxiplay** [spring-cloud/spring-cloud-netflix#1039]
https://github.com/Netflix/zuul/issues/135#issuecomment-220765149

Do you have a spring specific solution to avoid to set long timeout for all the service rather set to unique endpoint ?

**Comment by dsyer** [comment]
If you are using service discovery then each endpoint is a ribbon client with its own configuration settings (check the Spring Cloud user guide for details). Would that help?

**Comment by maxiplay** [comment]
OK thank you, Il will check the Spring Cloud user guide asap.

**Comment by merdogan** [comment]
Hi @maxiplay,

Have you found any solution in Spring Cloud user guide for setting timeout for specific endpoints?

I have a service which has many endpoints. However, there is 1 endpoint for uploading a file. I want to set a higher timeout for this endpoint and lower timeout for the other endpoints. 

How can we achieve this in Zuul?

**Comment by ryanjbaxter** [comment]
If you are using Ribbon you can set the timeouts via Ribbon properties.  For example `service.ribbon.ReadTimeout` and `service.ribbon.ConnectTimeout`.
