### ISSUE TITLE
Upgrade to ribbon v2.2.0

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1045]
https://github.com/Netflix/ribbon/releases/tag/v2.2.0

**Comment by aivans** [comment]
@spencergibb do you have some reference for using this new feature? 
```
7eef72f33e3585ba052c35429a96539afaffe66b: (take 2 of) Adding eureka aware Loadbalancers that make use of new notification mechanism from eurekClient
```
Does it help in faster propagation of Eureka information from Eureka Client to Ribbon? My understanding now is that Ribbon will poll Eureka client every 30s.

**Comment by spencergibb** [comment]
@aivans no I don't
