### ISSUE TITLE
Expose security context to any Hystrix command.

### ISSUE THREAD

**Issue by daniellavoie** [spring-cloud/spring-cloud-netflix#1053]
This issue is a follow up from Spring Cloud Security issue [#87](https://github.com/spring-cloud/spring-cloud-security/issues/87#issuecomment-220549541). I came to the conclusion that the request feature was Hystrix focused rather than Spring Cloud Security. Spring Cloud Security is aimed towards OAuth2 support.

Hystrix commands are actually unable to access the security context if executed with an isolation strategy set to `THREAD`. Only workaround available consists in setup the execution isolation to SEMAPHORE. 

Using Hystrix command hooks, we could build an infrastructure to transfert the Security Context from the main thread to the one executing the Hystrix command.

**Comment by spencergibb** [comment]
Closed via 36fec07a17de7e54894bb343ff97c009b48a5320
