### ISSUE TITLE
How to register the SpringMVC project to spring cloud netflix server?

### ISSUE THREAD

**Issue by zjw186** [spring-cloud/spring-cloud-netflix#1062]
The frameworker of client is using spring mvc, how can i register the clinet to spring cloud netflix server?

**Comment by spencergibb** [comment]
I suggest reading the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_spring_cloud_netflix) and looking at [this guide](https://spring.io/guides/gs/service-registration-and-discovery/)
