### ISSUE TITLE
Feign or Ribbon Configuration based on HTTP request method

### ISSUE THREAD

**Issue by arminbalalaie** [spring-cloud/spring-cloud-netflix#1063]
It would be great if it was possible to config Feign clients or Ribbon to use different retry and timeout policies based on the request methods. For example, for GET requests it is acceptable to have short timeouts and retry on multiple servers. However, for POST, PUT and DELETE requests that are not idempotent it is not acceptable to retry on next servers since it may lead to undesirable states. Also, timeouts for this types of requests can normally be higher that GET ones. 
I don't know if it is possible to do this kind of configuration right now. If it is possible, I appreciate it if someone share the configuration with me. If not, it can be a good feature.

**Comment by spencergibb** [comment]
It's not currently possible. Feature requests would need to be made in each project.
