### ISSUE TITLE
Bearer token is lost in Zuul Brixton.M5 -> Brixton.Release

### ISSUE THREAD

**Issue by jiujiu** [spring-cloud/spring-cloud-netflix#1066]
While migrating Zuul from Brixton.M5 to Brixton.RELEASE the bearer token is lost and not forwarded to remote service.
 
    <parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>Brixton.RELEASE</version>
    </parent>

**Comment by dsyer** [comment]
Can you share a project or something? The filter is still there and it works for me (e.g. see https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/oauth2-vanilla).

**Comment by stefanocke** [comment]
I had the same issue and it was due to the new sensitive headers property. When you unset it in the config it works again.

**Comment by stefanocke** [comment]
Like this in your .yaml :

zuul.sensitiveHeaders:

**Comment by 01sas** [comment]
I have the some problem and I tryed to use zuul.sensitiveHeaders, but it does not work for me. I checked the code (ProxyRequestHelper, Route, ZuulProperties and ZuulProperties$ZuulRoute) and did not found any usage of corresponding properties.

**Comment by jiujiu** [comment]
Many thanks
Now it works for me with `Brixton.RELEASE` and this yaml:

    zuul:
      ignoredServices: "*"
      prefix: /api
      routes:
        productapi:
          path: /product/**
          sensitiveHeaders:
        resource:
          path: /resource/**
          sensitiveHeaders:

**Comment by jiujiu** [comment]
Many thanks
Now it works for me with `Brixton.RELEASE` and this yaml:

    zuul:
      ignoredServices: "*"
      prefix: /api
      routes:
        productapi:
          path: /product/**
          sensitiveHeaders:
        resource:
          path: /resource/**
          sensitiveHeaders:
