### ISSUE TITLE
spring-session does not work with Spring Cloud Brixton.RELEASE

### ISSUE THREAD

**Issue by maxiplay** [spring-cloud/spring-cloud-netflix#1068]
https://github.com/spring-projects/spring-session/issues/534

I used Brixton.M4 before, I wanted to migrate to Brixton.RELEASE but the session seems to not be shared anymore. When I return to Brixton.M4 it work.

**Comment by spencergibb** [comment]
Please try with Brixton.RELEASE, the latest. Also, please provide steps to reproduce or a project that demonstrates the problem.

**Comment by maxiplay** [comment]
Oups. I wanted to say BRIXTON.RELEASE . I provide you a project very soon (wednesday)

**Comment by maxiplay** [comment]
You can test with this project. https://github.com/maxiplay/SpringCloudRedisSessionExample

The project use BRIXTON.M4. Try it before switch version to understand the workflow.

**Comment by dsyer** [comment]
You haven't set up the `sensitiveHeaders` in your zuul routes. By default in Brixton we block cookies. You probably want to set it to the old default (empty). Should be covered in the user guide.

**Comment by dsyer** [comment]
It's documented in the user guide. Maybe it would be worth updating the announcement blog to remind people.

**Comment by maxiplay** [comment]
Indeed it works now. Thank you.
