### ISSUE TITLE
Purpose of ZonePreferenceServerListFilter compared to ZoneAffinityServerListFilter

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-netflix#1072]
Hello,

it's more a question than a bug:

The default configuration of Ribbon in Spring Cloud Netflix uses ZonePreferenceServerListFilter which always preferes Servers from the same zone if there are any.

ZonePreferenceServerListFilter extends ZoneAffinityServerListFilter.

As far as I understand, ZoneAffinityServerListFilter is much more flexible than ZonePreferenceServerListFilter:

- It can behave like ZonePreferenceServerListFilter, when zoneExclusive is set to true.

- But if zoneExclusive is set to false, it will also consider things like server load or how many servers of the zone are "CircuitBreaker open". 
This seems to be quite useful. For example, Ribbon will not wait until all servers of the zone disappear in Eureka before switching to another zone (after 30s ?), but it will already switch, if there are too many errors in the zone.

So by having ZonePreferenceServerListFilter as default, this extended capabilities get lost somehow...

Could you please explain what the intention behind ZonePreferenceServerListFilter is and what things I have to consider if I try to switch to ZoneAffinityServerListFilter ?

Best Regards,
Stefan.

**Comment by spencergibb** [comment]
From the javadocs
> A filter that actively prefers the local zone (as defined by the deployment context, or the Eureka instance metadata).

I think it was just meant to be simpler (you don't have to enable it, it just is enabled). @dsyer can give you a better idea.

Seems like you understand pretty well what happens with `ZoneAffinityServerListFilter`.
