### ISSUE TITLE
Customize the @FeignClient bean name

### ISSUE THREAD

**Issue by yidongnan** [spring-cloud/spring-cloud-netflix#1073]
``` java
package net.devh.feign;

import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@FeignClient("service-b")
public interface ServiceBClient {

    @RequestMapping(value = "/", method = RequestMethod.GET)
    String printServiceB();
}
```

![image](https://cloud.githubusercontent.com/assets/3163314/15774351/78cf56a6-29ae-11e6-807f-4522fd90a587.png)

I see this bean name is **net.devh.feign.ServiceBClient**
Is there any way I can set a bean name replace default bean name

**Comment by spencergibb** [comment]
#790 is the reason why. Can you tell me why you need to set the bean name?

**Comment by yidongnan** [comment]
@spencergibb thanks.
Use full packge name + class name in every autowired.
```
@Autowired
@Qualifier("net.devh.feign.ServiceBClient")
```
I think it is unfriendly.
I think class name to the default bean name better, and @FeignClient provide a property to override the bean name.
like 
```
@FeignClient(beanName="****")
```

**Comment by spencergibb** [comment]
Why don't you autowire by type?

**Comment by yidongnan** [comment]
use autowire by type, it  @work.

class name is bean name in spring.
but package name + class name is bean name in spring-cloud-netflix

Use org.springframework.beans.factory.support.BeanNameGenerator to change bean name generator way like spring.

Can you think about it?

**Comment by nick-pww** [comment]
Another use case that is going to stop us from upgrading is in integration with Camel. It references beans by name, and it will be really annoying to not have control over the names of our own beans.

**Comment by spencergibb** [comment]
This is a duplicate, though I don't have time to find the other issue.

**Comment by spencergibb** [comment]
Never mind

**Comment by nick-pww** [comment]
Just going through this issue, and I think this can be closed, but the docs need to be updated I think (at least from my current test). I was able to change the name of the bean in version 1.2.4.RELEASE with specifying the 'qualifier' value of the FeignClient annotation. 

The docs however, make no mention of this and they still say the alias is generated from the name value you provided which does not seem to be the case.

**Comment by ryanjbaxter** [comment]
@nick-pww want to submit a PR for the documentation and then we can close out this issue?

**Comment by nick-pww** [comment]
@ryanjbaxter Will take a stab at it.

**Comment by nick-pww** [comment]
Actually, reading the docs again, I guess it does mention it, just managed to gloss over it. It still seems it should be updated though as this part no longer appeared to be true:

> . An alias is also created which is the 'name' attribute plus 'FeignClient'. For the example above, @Qualifier("storesFeignClient") could be used to reference the bean.

Will change PR...

**Comment by nick-pww** [comment]
Ooo...gets weirder, some have them and some don't. It appears I may getting hit by this: #1079 

Not sure where to go for now. Clients that do not have `@RequestMapping` at the top level have the alias, where the others do not....

**Comment by spencergibb** [comment]
We don't support feign clients with top level request mapping

**Comment by nick-pww** [comment]
@spencergibb Well they seem to work ok otherwise...perhaps an exception should be thrown or something logged if you find this at startup as it's not officially supported and behavior is undefined? (realize thats what the other story is kind of covers, but would think more then just a documentation change should be done if it's truly not supported)
