### ISSUE TITLE
How work the overridding by application-specific configuration file ?

### ISSUE THREAD

**Issue by maxiplay** [spring-cloud/spring-cloud-netflix#1075]
In documentation about config server there is 

> Sharing Configuration With All Applications
> 
>  With file-based (i.e. git, svn and native) repositories, resources with file names in application* are shared between all client applications (so application.properties, application.yml, application-*.properties etc.). You can use resources with these file names to configure global defaults and have them overridden by application-specific files as necessary.

I put zuul.sensitiveHeaders: '' to application.properties to share the same config in all services. 
I also created a gateway-dev.properties to set specific configuration on my zuul proxy. The zuul.sensitiveHeaders: '' is not taken in account in this case. Is it a the good behavior ? The gateway-dev.properties overrides the application.properties even with value not explicitly set ?

**Comment by dsyer** [comment]
> even with value not explicitly set

I thought you said you set it to '' (empty)? Can you explain a bit more, and/or provide a simple sample project?

**Comment by maxiplay** [comment]
Sorry for the trouble I was not read correctly the documentation. No problem now
