### ISSUE TITLE
Include Hystrix Logo with Hystrix Dashboard

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#1076]
Would it be possible to include the Hystrix logo with the webapp? If running on an intranet without Internet (or restrictive) access the image is not available.

**Comment by dsyer** [comment]
I think we had some issues with licenses for some of the other images but the logo looks like it should be Apache 2.0 (per the Netflix repo). Added local copies in 1c7c96a.

**Comment by steve-oakey** [comment]
Thanks, much appreciated.

-Steve
