### ISSUE TITLE
FeignClient marked @Primary has broken Mocking since 1.1.0 Release

### ISSUE THREAD

**Issue by sdcuthbertson** [spring-cloud/spring-cloud-netflix#1078]
I have configured JUnit Integration testing with Feign Clients by creating an implementation of a @FeignClient and ina test configuration class, mark that bean as @Primary. This enabled me to mock the calls to Feign.

Since the 1.1.0 Release this has broken. I found the following and is obviously the reason: http://bit.ly/1su1DZg

Is there a work around for this? Or anyway of mocking @FeignClients?

**Comment by dsyer** [comment]
Duplicates #1016
