### ISSUE TITLE
Zuul query parameter duplicated 3 times

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-netflix#1080]
If POST request has query parameter -- its value gets duplicated 3 times.
I have written small test case in `FormZuulProxyApplicationTests` that can reproduce an issue:

```
@Test
	public void postWithUrlParams() throws Exception {
		MultiValueMap<String, String> form = new LinkedMultiValueMap<String, String>();
		form.set("foo", "bar");
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.valueOf(
				MediaType.APPLICATION_FORM_URLENCODED_VALUE + "; charset=UTF-8"));
		ResponseEntity<String> result = new TestRestTemplate().exchange(
				"http://localhost:" + this.port + "/simple/form?uriParam=uriValue", HttpMethod.POST,
				new HttpEntity<MultiValueMap<String, String>>(form, headers),
				String.class);

		assertEquals(HttpStatus.OK, result.getStatusCode());
		assertEquals("Posted! {uriParam=[uriValue], foo=[bar]}", result.getBody());
	}
```
The last assert fails with the following message:
```
org.junit.ComparisonFailure: 
Expected :Posted! {uriParam=[uriValue], foo=[bar]}
Actual   :Posted! {uriParam=[uriValue, uriValue, uriValue], foo=[bar]}
```

I understand that post request with query params is not quite usual thing, but I suppose that it still should be handled correctly (spring without zuul proxying handles this case nicely).

I suppose my issue relates to: [ZUUL query parameter issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/191)

Thanks!

**Comment by Aloren** [comment]
I have found that `FormBodyRequestWrapper` in `getInputStream` returns all parameters for the request (both query and body params). That is not correct since getInputStream should return only body of the request. In `com.netflix.zuul.http.HttpServletRequestWrapper` method `parseRequest` gets all body params via `getInputStream` and merges them with query params. And since `getInputStream` returns query params as well -- they get duplicated.

**Comment by dsyer** [comment]
Hmm. I guess we can please some of the people some of the time then. You can't easily tell the difference between a form-encoded body and a query string, but you can maybe omit the form-encoded values that are also provided as query strings.

**Comment by Aloren** [comment]
Thank you for the quick reply and fix!
