### ISSUE TITLE
upgrade feign to v8.17.0

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1081]
https://github.com/Netflix/feign/releases/tag/v8.17.0

**Comment by spencergibb** [comment]
wait for Camden as this changes okhttp dep to 3.0

**Comment by SaikiranDaripelli** [comment]
What version for spring-cloud is this targeted to?

**Comment by spencergibb** [comment]
Sometime after spring boot 1.4 is released. August possibly.
