### ISSUE TITLE
Obsolete routes are kept in DiscoveryClientRouteLocator

### ISSUE THREAD

**Issue by anvo1115** [spring-cloud/spring-cloud-netflix#1084]
I couldn't find any methods to clear routes in
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/discovery/DiscoveryClientRouteLocator.java

Sometimes, if configuration is changed, there are obsolete routes which should be removed.
But there isn't any possibility in the interface. Why so?

**Comment by dsyer** [comment]
There's a `refresh()` method on the routes locator and a "dirty" flag on the handler mapping. It should refresh if there is an event of type `RoutesRefreshedEvent` or `RefreshScopeRefreshedEvent` (so for example if you ping /refresh or /routes).
