### ISSUE TITLE
eureka client instanceId not unique 

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#1089]
We changed the spring-cloud version from 1.0.0.RELEASE to the BRIXTON version. Now we experience that the instanceId format has changed. 
Old format was: "hostname-spring.application.name-server.port"
Now only "spring.application.name-server.port" is used so that services running on different hosts with the same name and port cannot be discriminated by eureka.
Is there any option to configure the hostname of the service to be used together with the instanceId?
We would like to avoid to use a random id, because it has no information.

**Comment by dsyer** [comment]
There is a new property `eureka.instance.instanceId`. The old property `eureka.instance.metadataMap.instanceId` still works. I wasn't aware the default had changed. Maybe we should add back the hostname if we know it.

**Comment by dsyer** [comment]
It works for me as expected (the host is prepended in the instanceId, as reported by the Eureka dashboard). Where are you seeing the value without the hostname?

**Comment by LutzStrobel** [comment]
In the old version of the EurekaInstanceConfigBean the id shown within the eureka dashboard was built by a call to IdentifyingDataCenterInfo.getId() which contained additional to the configured instanceID the hostname. 
This "IdentifyingDataCenterInfo" was removed in the new version of that bean.

**Comment by shanman190** [comment]
To me this sounds awfully like gh-978.

Are both eureka server and client running the same spring cloud versions?

**Comment by LutzStrobel** [comment]
Yes, both are freshly built with BRIXTON

**Comment by spencergibb** [comment]
In Brixton we add `spring.cloud.client.hostname` and `spring.cloud.client.ipAddress` to the environment that you can use in your `instanceId` definitions.

**Comment by dsyer** [comment]
And they are used by default. So it seems like maybe the client and server are not built from master (or 1.1.2 equivalently at this point).

**Comment by LutzStrobel** [comment]
Sorry for that, I only updated the dependencies, but not the sources.

Now I cloned the 1.1.2 tag and tried to build, but I get always error claiming:
 **Executing command line: [c:\portable\mingw\msys\1.0\bin\egrep.exe, -rm, 1, ^import com.google, --include=*.java, C:\dev\prj\smartlaw\spring-cloud-netflix-1.1.2]**
When I try cygwin in front of the path - the same happens. What is this good for?
What do I wrong?

**Comment by dsyer** [comment]
1.1.0 is not the latest (so we should update the samples).

**Comment by spencergibb** [comment]
@LutzStrobel what sample are you looking at?

**Comment by LutzStrobel** [comment]
Our eureka-server comes from https://github.com/spring-cloud-samples/eureka.

To reproduce the problems I rebuilt this morning eureka-server and some of our micro-services. Now the provlems described above vanished. Using the property spring.cloud.client.hostname the names of the instanceIds are discernible for the eyes too.
So I think we can close it for now.
