### ISSUE TITLE
Request Body Of A POST With The Content-Type application/x-www-form-urlencoded Not Proxied

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#109]
I have an POST request I want to proxy through the Zuul proxy, however it looks like the Zuul proxy is not forwarding on the request body.  This seems to be specific to requests with the content type application/x-www-form-urlencoded because my requests with JSON request bodies works fine.  

Here is the request that is going through the proxy

```
POST /api/questions/text HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cookie: JSESSIONID=7820ABB7043F3E95D64A2E515C683510
Host: localhost:8282
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.10.1) GCDHTTPRequest
Content-Length: 91

MessageSid=123&AccountSid=456&From=%2B16174354714&To=%2B16179414658&Body=this+is+a+question
```

I getting a 400 back from the request because the service it is proxying too is not getting any of the parameters.

I am also noting a warning coming from the Zuul proxy

```
2014-12-17 16:52:31.646  WARN 11358 --- [nio-8282-exec-2] c.n.zuul.http.HttpServletRequestWrapper  : Content-length different from byte array length! cl=91, array=0
```

**Comment by gajendraupadhyay1991** [comment]
Hi,
I have implemented eureka server, eureka client and zuul API in my project.
When I am trying to request a non JSON body from Zuul API, It is showing response.
But I am trying to request a JSON body from Zuul API, It is showing nothing nor any error.
Please help me out.

**Comment by dsyer** [comment]
@gajendraupadhyay1991 this issue was closed, and it is unlikely to be related to your difficulty. Please post usage questions on Stackoverflow, and raise verifiable issues here, providing full details (e.g. a sample project that shows the problem).
