### ISSUE TITLE
Register a HystrixConcurrencyStrategy that returns thread pools that propagate the SecurityContext

### ISSUE THREAD

**Issue by william-tran** [spring-cloud/spring-cloud-netflix#1092]
Should be able to take advantage of the plugins mechanism https://github.com/Netflix/Hystrix/wiki/Plugins#concurrency-strategy to `HystrixPlugins.getInstance().registerConcurrencyStrategy()` and override `com.netflix.hystrix.strategy.concurrency.HystrixConcurrencyStrategy.getThreadPool()` in that strategy. We'll need to return a subclass of ThreadPoolExecutor and:

```
@Override
public void execute(Runnable command) {
    super.execute(DelegatingSecurityContextRunnable.create(command, null));
}
```

This would allow you to use an Oauth2RestTemplate inside a `@HystrixCommand` without needing to use semaphore isolation

**Comment by daniellavoie** [comment]
Hi @william-tran 

I suggest you have a look to #1054. This PR transparently propagate the Security Context inside an Hystrix thread pool. Please have a look and tell me if it fits your need. @dsyer is waiting for further requestors to this feature before considering merging it.

**Comment by william-tran** [comment]
I don't think that'll work for my use case. Actually, the original solution I proposed isn't sufficient for the OAuth2RestTemplate use case either. In an app that has `@EnableOAuth2Sso` you get a session scoped `DefaultOAuth2ClientContext` that is used by OAuth2RestTemplate to pass the current user's token along. To ensure a Hystrix command can access the session scopes bean, the RequestContext would need to be propagated. For good measure, I would propagate both, in case you might have an `@PreAuthorize` annotation inside a Hystrix command. But I realize the title is now incorrect for the original use case I wanted to support.

**Comment by dsyer** [comment]
I guess the change for the request context should be easy, now that #1053 is closed?

**Comment by daniellavoie** [comment]
I'll take a shot at it. Should not be complicated. I'll try to come up with something by the end of the week. @william-tran Any PR based on #1053 would be welcome if you are in a hurry.

**Comment by daniellavoie** [comment]
Also, could you please provide a unit test as a seperate project which I could test my upcoming contribution against ? That would ensure that I understood your test case properly.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
