### ISSUE TITLE
zuul.ignoredHeaders too restrictive regarding cache control headers

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-netflix#1096]
With https://github.com/spring-cloud/spring-cloud-netflix/commit/48913cbb64fde1a4103e4227c97eb4efd53ca684 a new feature was introduced to configure which headers to ignore in Zuul.
This is certainly necessary, especially to avoid problems with "double" headers from the service and from the gateway.
However, if Spring Security is on the classpath, a bunch of headers is always added to this list of ignored headers, amongst them is Cache-Control. The idea behind this is - as far as I understood- that Spring Security in the gateway wil add those headers anyway (and set some default values here).
For the following case, this approach is IMHO too restrictive:

- There are some static resources provided by a resource server. 
- The resource server would set their cache headers, since it knows best ...
- The gateway would then either remove those headers and replace them by "no-cache" or (if the resources match security.ignored ) remove those headers at all.

Both behaviors are not acceptable, since the cache headers get lost.  The only way to avoid this currenly is to remove spring security completely from the gateway, which might not be acceptable as well.

I think the two concerns "spring security" and "caching" are somehow separate issues and by mixing both in the logic for zuul.ignoredHeaders it gets too restrictive...

At least, there should be a configuration option whether to automatically add the security headers to the ignored headers or not.

**Comment by dsyer** [comment]
Thanks for the analysis. If you'd like to propose a solution, that would be great. Even if it's just the flag to skip adding security headers.

**Comment by mduesterhoeft** [comment]
Is there currently a known workaround for this problem. 

In spring-security I can just disable the default behaviour. 
https://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html#headers-cache-control

I think we need sth. similar here as well.
