### ISSUE TITLE
FeignClient configuration being applied to all clients

### ISSUE THREAD

**Issue by NanditaRao** [spring-cloud/spring-cloud-netflix#1100]
I have 2 FeignClients configured in my code with 2 different configuration classes.
They look something like this: 

    @FeignClient(name = "service-a", configuration = ServiceAFeignConfiguration.class, url = "${service.a.baseurl}")
    @FeignClient(name = "service-b", configuration = ServiceBFeignConfiguration.class, url = "${service.b.baseurl}")

Each of these configuration classes has a request interceptor which adds a value to the Accept header in the request.

I have excluded both the Configuration classes from @ComponentScan.

The problem is that when a request is made to service A, it first applies the interceptor in ServiceAFeignConfiguration but then overwrites it with the configuration in ServiceBFeignConfiguration.
Inspite of both of them being excluded from @ComponentScan.

Shouldn't the default configuration be overridden just by the configuration class mentioned in the FeignClient?

**Comment by spencergibb** [comment]
It should. Do you have a project that can reproduce the problem?

**Comment by NanditaRao** [comment]
So I tried replicating the issue in a smaller sample project and it worked fine. So it is definitely something in my project. I'll look into it.
Thank you!

**Comment by NanditaRao** [comment]
I'll close the issue.

**Comment by cbornet** [comment]
I have the same issue on a simple project.

**Comment by cbornet** [comment]
False alert : this is me being silly and creating two clients with the same name and different config...
