### ISSUE TITLE
Why doesn't EurekaClientAutoConfiguration include @EnableDiscoveryClient or @EnableEurekaClient?

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#1103]
When upgrading from Angel to Brixton I found that all of my applications stopped registering with Eureka once I deployed them. The reason being is the client applications did not include `@EnableDiscoveryClient`. With Angel, I had just assumed it was a feature of the auto-configuration that `@EnableDiscoveryClient` was not required if Eureka was found on the classpath. Looking at the code in Brixton it appears this may have been considered a bug or an unintended feature?

I am wondering why `@EnableEurekaClient` is not included with `EurekaClientAutoConfiguration`? I can see by looking at the code it is probably because the auto-configuration is used for both `BootstrapConfiguration` and `EnableAutoConfiguration` selectors, but could these be separated? 

I feel like since the `EurekaClientAutoConfiguration` is `@ConditionalOnProperty(value = "eureka.client.enabled", matchIfMissing=true)` that if I really didn't want the discovery client then I would turn it off. Otherwise, the auto-configuration is doing a lot of work for nothing.

Am I missing something? Does it make sense to have all of these beans wired but not use them? Is there another use-case I am not seeing?

Thanks.

**Comment by spencergibb** [comment]
It was never an intended feature and I'm actually surprised it worked. We have always required `@EnableDiscoverClient`. Some folks use that config key to disable it for tests.

**Comment by steve-oakey** [comment]
In what instance would you want the auto-configuration to create all of the beans, but not use `@EnableDiscoveryClient`? I'm not trying to be facetious, I just cannot think of a case.

**Comment by spencergibb** [comment]
It is imported [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/config/EurekaDiscoveryClientConfigServiceBootstrapConfiguration.java#L35) for discovery first bootstrap.

**Comment by steve-oakey** [comment]
Right, but it is also included in the `EnableAutoConfiguration` import selector so the auto-configuration is triggered again after the bootstrap and all of the beans are created again so  these beans are all available in the main application context. It appears in both the bootstrap and main auto configuration reports with positive matches.

**Comment by spencergibb** [comment]
OK, I believe we've moved past whether `@EnableDiscoveryClient` is required or not, correct? Your concern is about unused beans if one doesn't use `@EnableDiscoveryClient`?

**Comment by steve-oakey** [comment]
Yes. It was more of a question of if the auto-configuration could be enhanced to include `@EnableDiscoveryClient`. I am aware now that it is required. My question more or less was if the auto-configuration can/should do it for you.

**Comment by spencergibb** [comment]
I'd lean to not having the beans created if `@EnableDiscoveryClient` isn't used.  We also want to be able to separate service registration with service discovery in the future. @jkschneider or @twicksell, did you guys use `EurekaClientAutoConfiguration` outside of an `@EnableDiscoveryClient` scenario?

**Comment by jkschneider** [comment]
@spencergibb I've only used it in the context of `@EnableDiscoveryClient`.

**Comment by spencergibb** [comment]
@dsyer any thoughts?

**Comment by dsyer** [comment]
It's a matter of taste I think, whether to require an `@Enable*` annotation or not to switch on a feature. We have chosen in most cases in Spring Cloud to require the annotation.

**Comment by steve-oakey** [comment]
@dsyer @spencergibb for the record, I have no issues requiring the use of `@EnableDiscoveryClient`, but I feel that using that annotation should put the application in a state to trigger the auto-configurations. For example, in Spring Boot using `@EnableCache` will create the necessary beans to trigger `CacheAutoConfiguration`. Other auto configurations that don't require an `@Enable*` annotation (class/property enablement conditions) will add or import the necessary annotations for you (e.g. `SecurityAutoConfiguration` transitively uses `@EnableWebSecurity`). Having an auto-configuration that matches and creates beans but then the functionality only partially works unless the annotation is present, is confusing in my opinion.

**Comment by dsyer** [comment]
Fair enough, but it's necessary, otherwise the conditions in the autoconfiguration don't fire in the right place.
