### ISSUE TITLE
Proxy creation problems when starter-eureka 1.1.0 is in the classpath

### ISSUE THREAD

**Issue by willianconsta** [spring-cloud/spring-cloud-netflix#1105]
When trying to update spring-cloud-starter-eureka from 1.0.6.RELEASE to 1.1.0.RELEASE in a SpringBoot project the startup began to throw the following exception:

```
 Caused by: java.lang.IllegalArgumentException: Cannot subclass final class tests.ServiceImpl
 	at org.springframework.cglib.proxy.Enhancer.generateClass(Enhancer.java:518) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
 	at org.springframework.cglib.transform.TransformingClassGenerator.generateClass(TransformingClassGenerator.java:33) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
```

When spring-cloud-starter-eureka is not in the classpath (or the version is 1.0.6.RELEASE or less) everything starts smoothly. Seems like the proxy creation strategy is changed somehow with the new version but I couldn't track the cause

The [attached maven project](https://github.com/spring-cloud/spring-cloud-netflix/files/317206/proxy_creation.zip) reproduces the problem.

**Comment by daniellavoie** [comment]
You have declared `ServiceImpl` as a final class. Changing it to a classic public class fixes the behavior. This is a Spring issue, not related to Spring Cloud Netflix. The bean factory is trying to proxy you bean with cglib but fails due to you final class.

Also, I would recommend you to import the Spring Cloud BOM pom.

Checkout the starting guides in [spring cloud homepage](http://projects.spring.io/spring-cloud/).

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Brixton.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by willianconsta** [comment]
Thanks for the fast reply.
Digging deeper into the code I found [this commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/8375e3b4442dbdac345f12f87515dd5faf16ac41). Take a look at the line 40.
That property changes the default proxy configuration to use CGLib instead of the [default JDK proxies](http://docs.spring.io/spring/docs/3.0.x/spring-framework-reference/html/aop.html#aop-introduction-proxies). 
That explains the error I'm getting when I just add the lib to the classpath because `com.netflix.servo.monitor.Monitors` will be present and then the default proxy configuration will be changed.
Does it makes sense or I missed something?

**Comment by spencergibb** [comment]
> Make spring AOP default to target class so RestTemplates can be customized

I'll let @dsyer comment on the need.

**Comment by spencergibb** [comment]
IIRC it is because of [RestTemplateUrlTemplateCapturingAspect](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics/RestTemplateUrlTemplateCapturingAspect.java). You can set `spring.cloud.netflix.metrics.enabled=false`.

**Comment by dsyer** [comment]
See https://jira.spring.io/browse/SPR-3665 for an old Spring Framework issue. It's hard for us to do more than workarounds until there is support for more fine-grained configuration in Spring.

**Comment by StephenDillon** [comment]
Thanks for raising this, really helped track down what introduced this for me and find a fix.

This is a pretty hard issue to find as the addition of these properties are not logged on debug logging, so tracking down the offender was fairly tricky. 
Also just using 'spring.aop.proxyTargetClass:false' will result in a exception with 'restTemplate to com.sun.proxy.$Proxy132'  until the netflix metrics property is added as well.

**Comment by spencergibb** [comment]
Added a debug log statement.

**Comment by StephenDillon** [comment]
Thanks, that should help a lot tracking down what enables the cglib proxying
