### ISSUE TITLE
Build status image broken in README

### ISSUE THREAD

**Issue by venilnoronha** [spring-cloud/spring-cloud-netflix#1109]
Looks like more of an issue on Github side.

**Comment by dsyer** [comment]
What is it that is broken? It looks OK to me.

**Comment by venilnoronha** [comment]
![Uploading Screenshot_20160616-224607_20160616224918187.jpg…]()

**Comment by venilnoronha** [comment]
![screenshot_20160616-224607_20160616224918187](https://cloud.githubusercontent.com/assets/1722758/16126218/d0bdb194-3414-11e6-8dfe-2ce33c8f9b3f.jpg)

**Comment by spencergibb** [comment]
I don't know what to say, can you see what error is in your browser dev tools? It works fine for both of us.

**Comment by venilnoronha** [comment]
I'd get a "Not Found" error when directly accessing the image, however, it has automatically started to appear again.

![screenshot_20160617-035440](https://cloud.githubusercontent.com/assets/1722758/16135244/c1c5892a-343f-11e6-9d91-2282970cca17.jpg)

**Comment by spencergibb** [comment]
Must have been a travis hiccup.

**Comment by venilnoronha** [comment]
Just for records. The Travis image link was working fine, the Github CDN link proxying the Travis one wasn't.
