### ISSUE TITLE
Configuring context root of hystrix.stream

### ISSUE THREAD

**Issue by wooder79** [spring-cloud/spring-cloud-netflix#1116]
Hi,

The docs mention that if actuator is installed, then `/hystrix.stream` is available along with the other actuator endpoints. In my case, I've moved the actuator endpoints to another context root, but would like to move the hystrix stream endpoint back to `/` to make it follow the expected convention of my other apps. Is there a way to configure this?

Was looking through the history of #487 but couldn't find much to go on. Thanks!

**Comment by spencergibb** [comment]
There isn't an automated way to do that. You can disable that actuator then install the hystrix stream servlet yourself.

**Comment by wooder79** [comment]
That's unfortunate, because we use actuator for other things. We'll figure out how to reconfigure our turbine environment to use other paths. Thanks!
