### ISSUE TITLE
Example to use regexMapper

### ISSUE THREAD

**Issue by anukiransolur** [spring-cloud/spring-cloud-netflix#1118]
I'm trying to use regexMapper in my config file but not able to get it working. It says the following  
 "No routes found from RouteLocator" when I see the logs. 

Can anyone point me to an example or some resources?

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/blob/243c13b7eeaa39023bcd55caa17a814fbf4ef9ff/docs/src/main/asciidoc/spring-cloud-netflix.adoc#embedded-zuul-reverse-proxy

Search for `regexMapper`.

Also see https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/zuul/filters/discovery/DiscoveryClientRouteLocatorTests.java
