### ISSUE TITLE
Turbine seems to get lost when inside Docker

### ISSUE THREAD

**Issue by luizkowalski** [spring-cloud/spring-cloud-netflix#1121]
I have 3 projects: A Hystrix dashboard, a turbine server (using AMQP) and an API

When I start in development env, I set up 2 instances of the API (using port 8080 and 8081). To test the turbine aggregation, I make calls and in the dashboard I can see 2 hosts
Although when I use Docker, even when the load balancer (in this case, HAProxy) hits the 2 server, I only see one Host on the hystrix dashboard, and also, seems like that Hystrix dashboard keeps alternating between 2 different RabbitMQ connections, like that:

![](http://i.stack.imgur.com/fLuW9.gif)

I asked about that on [Stackoverflow](http://stackoverflow.com/questions/37928016/turbine-can-only-find-one-host-when-using-docker/37929734?noredirect=1#comment63312489_37929734) but seems like a bug.

The whole info and config so far are in the question, I didn't wanted to crosspost

**Comment by spencergibb** [comment]
Do you have a project you can share that recreates the problem?

**Comment by luizkowalski** [comment]
yes, just pushed

https://github.com/luizkowalski/spring-turbine-playground

**Comment by luizkowalski** [comment]
any follow up, Spencer?

**Comment by luizkowalski** [comment]
Any news with this?

**Comment by mukteshkrmishra** [comment]
It happens as turbine is a pull model and in docker ips keeps changing.

**Comment by luizkowalski** [comment]
@mukteshkrmishra sorry, can you elaborate more? what do you mean "ips keeps changing"?

**Comment by spencergibb** [comment]
Can you try with the latest Brixton.SR6 or Camden.SR1?

**Comment by luizkowalski** [comment]
So, I changed to `<version>Camden.SR1</version>` and now I get 

```
[INFO] --- spring-boot-maven-plugin:1.3.5.RELEASE:run (default-cli) @ turbine_server ---
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:191)
	at com.inkdrop.TurbineApplication.main(TurbineApplication.java:12)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

**Comment by luizkowalski** [comment]
also, I created this app with start.spring.io initializer...but I'm really confused about when to use `spring-cloud-starter` and `spring-boot-starter`

**Comment by spencergibb** [comment]
@luizkowalski are you using commons logging? You probably need to add the dependency. What are you confused about?

**Comment by luizkowalski** [comment]
I changed to `Camden.SR1` and upgrade the parent to spring boot 1.4.1 and made it work.
I'm not using commons logging, probably some other starter is using it. I'm confused about the starters. 
![screen shot 2016-10-19 at 11 52 06 pm](https://cloud.githubusercontent.com/assets/112706/19538978/153e7a8e-9657-11e6-9983-f8daf4325934.png)

here you can see `spring-cloud-netflix-turbine` and `spring-cloud-starter-turbine`. I'm not really sure when to use one or another or what is the difference between then

**Comment by luizkowalski** [comment]
Even updating to Camden.SR1 or Camden.RELEASE, I see the same problem

![oct-20-2016 09-59-02](https://cloud.githubusercontent.com/assets/112706/19551554/fb0dcc64-96ab-11e6-8718-3ec5c5df3bd1.gif)

**Comment by luizkowalski** [comment]
I think one of them did solve the issue but I don't remember what...I'll double check today and update this issue accordingly

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
