### ISSUE TITLE
Add OkHttpClient support for zuul RibbonCommand

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1125]
Add an alternative to the now default `HttpClientRibbonCommandFactory` and  `RestClientRibbonCommandFactory` that are both based apache http client (the former directly, the latter based on jersey client which depends on apache).

**Comment by aivans** [comment]
@spencergibb I am very interested to know what is the difference in using Apache, Jersey or OkHttp Clients in Spring Cloud? Are there any docs i can read?

Thanks

**Comment by spencergibb** [comment]
@aivans not really. `zuul.ribbon.okhttp.enabled` plus okhttp3 on the classpath activates it. Apache is not the default in master. ``zuul.ribbon.restclient.enabled` enables the deprecated netflix restclient based on jersey. RestClient has limitations like not supporting `PATCH` and other bugs that are fixed with Apache.

**Comment by aivans** [comment]
Thanks.

Does this have any effect on the request buffering before sending downstream?

**Comment by spencergibb** [comment]
As far as I know, the buffering in zuul is determined whether or not the request is wrapped by zuul.

**Comment by aivans** [comment]
Thank you. i'll dig the older threads to better understand and make a decision for switching to the new mechanisms.
