### ISSUE TITLE
Validation of Apache HttpClient use by Feign

### ISSUE THREAD

**Issue by singram** [spring-cloud/spring-cloud-netflix#1133]
I'm attempting to coerce Feign to use the Apache HttpClient library.

This looks possible via the following commit.
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsConfiguration.java

I've included feign-httpclient via the following, matching the feign version used in Spring-Cloud Brixton.RELEASE
`    compile('com.netflix.feign:feign-httpclient:8.16.2')`

At present I see no evidence that this is being picked up and auto-configured at runtime.  Any thoughts on what I might be doing wrong or how to validate?  Thanks!

**Comment by spencergibb** [comment]
Look at the auto configuration report. Using the cli option `--debug` or look at `/autoconfig`. Search for `HttpClientConfiguration`.

**Comment by singram** [comment]
@spencergibb Thanks! I was looking at /beans previously and was not seeing what I was expecting.
