### ISSUE TITLE
skip all filters except route filter 

### ISSUE THREAD

**Issue by techkoka** [spring-cloud/spring-cloud-netflix#1136]
Can we skip all the filters except route filter for a particular request ?

Lets say, I have 5 routes defined and 5 pre-filters. I want to skip these pre-filters(I **don't even want to execute shouldFilter()**) for one of the routes. Can I achieve this by any configuration ?

**Comment by spencergibb** [comment]
No. Can you help my understand why you want to skip all the prefilters?

**Comment by techkoka** [comment]
We have a legacy app(on tomcat(not embedded)) sitting behind zuul where deployed health service(a war file ) along with legacy app. LTM(Load Traffic Mngt) ping this health service every second to get the status of the app. For this particular health request (/legacy/healthMonitor) - I simply need to route without even going through any pre filters configured. 

Yes, agreed - I can return false on all pre filters  shouldFilter() method in order to skip but like I said thought to see any configuration available.

**Comment by spencergibb** [comment]
how will it know where to route if the pre filters are skipped?

**Comment by techkoka** [comment]
Agreed.
My intension(may be too much to ask) is - give an configurable option(along with shouldFilter) per route on which filters to exclude per route (except PreDecoration filter)


Like,

zuul:
  prefix: /app/
  servletPath: /
  routes:
   easeHealth:
      path: /health
      url:  ${new.login.endpoint}
      **_exclude: MyPreFilter1, MyPreFilter2_**
   traffic-control:
         path: /abc/**
         url: ${abc.endpoint}
         stripPrefix: false
      **_exclude: MyPreFilter4, MyPreFilter5_**

**Comment by spencergibb** [comment]
Not sure this is something we want to support, seems very specific.

**Comment by talk2debendra** [comment]
@spencergibb is it supported ?

**Comment by spencergibb** [comment]
Based on my previous comment and not seeing a commit or pr to close this issue, no.
