### ISSUE TITLE
Zuul modifying original response from Service

### ISSUE THREAD

**Issue by gondor** [spring-cloud/spring-cloud-netflix#1137]
If I directly post to a micro-service I get back the expected 412 with reason/error explaining the validation reason.  If I do the same exact POST with Zuul it responds with the same error code but the original body is missing leaving no reason explaining the validation failure.  I'm using Brixton.SR1

Are there any configuration properties I need to change to fix this in Zuul?  First screenshot is the direct Service call, 2nd is the same but going through Zuul.

<img width="698" alt="service-direct-call" src="https://cloud.githubusercontent.com/assets/148656/16361079/73b91f2c-3b37-11e6-989d-7b4351176dc6.png">

<img width="647" alt="zuul-to-service-call" src="https://cloud.githubusercontent.com/assets/148656/16361081/7ba123f6-3b37-11e6-9af9-f7076d67c68f.png">

**Comment by spencergibb** [comment]
I believed this was fixed here 20db8685928077f4950adcf194149028bc42d030

**Comment by gondor** [comment]
Verified and this appears to be the cause.   How often are things updated in the Maven SR1 snapshots?

**Comment by spencergibb** [comment]
It should be in snapshots now.
