### ISSUE TITLE
Eureka dashboard static resources not loading

### ISSUE THREAD

**Issue by 12010994** [spring-cloud/spring-cloud-netflix#1142]
Hi,
When the path to the Eureka Dashboard is modified (e.g. eureka.dashboard.path: /eureka-dashboard), the static content fails to be fetch (css, js...).
http://localhost:8761/eureka/css/wro.css -> 404 Not Found

**Comment by spencergibb** [comment]
I'm not seeing the problem. When I set `eureka.dashboard.path: /eureka-dashboard` it doesn't actually change the location of the static resources. They are still at `/eureka/*`.

![eurekadashboard](https://cloud.githubusercontent.com/assets/594085/16422842/0945002a-3d17-11e6-9cb2-c7196a979ef4.png)

**Comment by 12010994** [comment]
Damn. Actually I moved the dashboard default location to make room for the Spring Boot Admin dashboard. Do you think it could be related ?
![eureka-issue](https://cloud.githubusercontent.com/assets/5603199/16480585/3cf875f0-3ea7-11e6-81ae-9793d0db2433.png)

**Comment by spencergibb** [comment]
Unsure without seeing your project.

**Comment by twest72** [comment]
I have the same error (run as spring boot jar).

![auswahl_003](https://cloud.githubusercontent.com/assets/731077/16516507/bf4a2b4e-3f78-11e6-8bf2-cd0e225e2c71.png)

**Comment by spencergibb** [comment]
@twest72 like I told the reporter, I'm unable to duplicate. Do you have a project to share?

**Comment by vigohe** [comment]
@spencergibb I do have the same issue but running it in a docker container. Runs fine in my local machine.

I did also upload the code to [https://github.com/vigohe/eureka-test](https://github.com/vigohe/eureka-test), and you can check the docker image in [https://hub.docker.com/r/vigohe/eureka/](https://hub.docker.com/r/vigohe/eureka/).

`docker run --rm --name eureka -p 8761:8761 vigohe/eureka:issue`

Hope this will help.

**Comment by vigohe** [comment]
Sorry I miss the "touch /app.jar" command in the Dockerfile. That did the magic..

from [https://spring.io/guides/gs/spring-boot-docker/](https://spring.io/guides/gs/spring-boot-docker/)
> 
You can use a RUN command to "touch" the jar file so that it has a file modification time (Docker creates all container files in an "unmodified" state by default). This actually isn’t important for the simple app that we wrote, but any static content (e.g. "index.html") would require the file to have a modification time.

**Comment by 12010994** [comment]
Here is a sample project :
https://github.com/vpetit35/eureka-dashboard-css-issue

**Comment by daniellavoie** [comment]
If you are interested into a proper eureka dashboard for Spring Cloud, I would recommend you trying out the spring-cloud-dashboard from @VanRoy 

https://github.com/VanRoy/spring-cloud-dashboard

With this one you can disable eureka and spring boot admin dashboards.

**Comment by spencergibb** [comment]
> Well, I figured that this issue is not a bug from Eureka.

**Comment by just3019** [comment]
Hi, Where did I make a mistake？

![image](https://user-images.githubusercontent.com/5235712/64589875-cf8c8400-d3d8-11e9-878b-077717fc5f5f.png)
![image](https://user-images.githubusercontent.com/5235712/64589888-d915ec00-d3d8-11e9-9765-a478e43db63d.png)
![image](https://user-images.githubusercontent.com/5235712/64589954-fba80500-d3d8-11e9-92df-bb9073f608a0.png)
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/5235712/64590022-272aef80-d3d9-11e9-8840-62eeb22ceb0e.png">

**Comment by foxivolunteer** [comment]
Hello. 
I configure eureka server as default configuration on my local machine with spring boot. when I deploy it into kubernetes, UI is not loading.

![Capture1](https://user-images.githubusercontent.com/35287258/96229366-77429100-0f9f-11eb-9daa-b1eea0d842cc.JPG)
![Capture2](https://user-images.githubusercontent.com/35287258/96229371-7ad61800-0f9f-11eb-8e27-67d9b1be07ab.JPG)

![Capture3](https://user-images.githubusercontent.com/35287258/96229490-a8bb5c80-0f9f-11eb-8cd6-1687c511921b.JPG)

**Comment by vikramnagaraju31** [comment]
@foxivolunteer 

Hi, Were you able to resolve above issue, if yes can you please share us what needs to be done.

**Comment by ViliusS** [comment]
Not sure why this ever get closed but it IS a bug in how static CSS and JS resources are served.
Here https://github.com/spring-cloud/spring-cloud-netflix/blob/9e1f7f6aad9becbfdb42af4bd1960e87f1ee897c/spring-cloud-netflix-eureka-server/pom.xml#L172 generated static resources are copied to /static/eureka/ folder which is then served via HTTP server from /static/ folder. Since HTTP server serves these resources statically without modifying path you will always get them served under /eureka/ prefix.
So currently eureka.dashboard.path is useless.

**Comment by heowc** [comment]
hello,

I found out about this problem while using an embedded config server.

So, I simply thought that if we change the base-path, it would be good if the static resource path changes along with it. What do you think? 🤔

**Comment by ViliusS** [comment]
If you are using Ingress or any other HTTP load balancer above Eureka there is a workaround for this issues. Just map both /eureka/ and /yourcustomdashboard/ paths to Eureka service. In Kubernetes it looks like this:
```
      - backend:
          service:
            name: registry
            port:
              number: 8761
        path: /eureka
        pathType: Prefix
      - backend:
          service:
            name: registry
            port:
              number: 8761
        path: /eurekawebui
        pathType: Prefix
```
