### ISSUE TITLE
Zuul, Missing Set-Cookie header in response

### ISSUE THREAD

**Issue by qza** [spring-cloud/spring-cloud-netflix#1146]
Greetings,

We are using Spring Cloud Netflix Core 1.1.2.RELEASE to proxy calls with Zuul to downstream service. The service is setting couple of cookies with Set-Cookie header, but they are missing in response.

Noticed that there is a option for sensitive headers, but this is used to exclude headers from downstream requests, opposite way.

Wondering if I'm missing some configuration here. Any help is appreciated. 
Thanks!

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#cookies-and-sensitive-headers
