### ISSUE TITLE
eureka client, documentation broken links

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-netflix#1148]
http://projects.spring.io/spring-cloud/spring-cloud.html#_service_discovery_eureka_clients

The 2 links in this text are broken

```
See EurekaInstanceConfigBean and EurekaClientConfigBean for more details of the configurable options.
```

**Comment by spencergibb** [comment]
The new documentation is located [here](http://cloud.spring.io/spring-cloud-static/spring-cloud.html) and this is fixed.
