### ISSUE TITLE
MetricsRestTemplateConfiguration not applied in time for @LoadBalanced RestTemplate

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1153]
`MetricsRestTemplateConfiguration` is guarded by an `@ConditonalOnBean(RestTemplate.class)` annotation. However it seems no bean of type `RestTemplate` exists yet in the context when the configuration class is evaluated.

That configuration is supposed to register a `BeanPostProcessor` looking for `RestTemplate` instances to register an interceptor to record metric information. My understanding is that post processor must be registered as early as possible, and certainly _before_ any RestTemplate instance is created (otherwise it has not chance to post-process it). The guard on the existence of a RestTemplate bean in the context is therefore pretty odd.

According to me, the condition should rather be `@ConditionalOnClass(RestTemplate.class)`.

We could not get it work with @LoadBalanced RestTemplate (Brixton.M3)

**Comment by spencergibb** [comment]
Have you tried lately with Brixton.SR6 or Camden.SR1?

**Comment by brenuart** [comment]
(not yet I'm afraid)

**Comment by ryanjbaxter** [comment]
If you try against the latest releases (Brixton.SR7 or Camden.SR3) and it doesnt work than we can better assist you.

**Comment by brenuart** [comment]
Just tried with `Brixton.SR7` and `Camden.SR3`but could not get it work with the attached sample application unless I apply the fix proposed above.

Sample app: [gh1153.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/639173/gh1153.zip)

**Comment by ryanjbaxter** [comment]
I agree, I think it should be `@ConditionalOnClass`.  Want to submit a PR?
