### ISSUE TITLE
ServoMetricServices not created if not Counter/Gauge services exist

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1154]
According to `ServoMetricsAutoConfiguration.spectatorMetricServices()` a `ServoMetricServices` should be created if no other SpringBoot Counter/Gauge service instances exist in the context (same strategy as for when Dropwizard is on the classpath).

However, it doesn't happen to be the case - a default SpringBoot implementation is used instead.

**Comment by spencergibb** [comment]
This has been moved to `SpectatorMetricsAutoConfiguration` and it looks properly guarded. Is this still a problem?
```
	@Bean
	@ConditionalOnMissingBean({ CounterService.class, GaugeService.class })
	public SpectatorMetricServices spectatorMetricServices(Registry metricRegistry) {
		return new SpectatorMetricServices(metricRegistry);
	}
```

**Comment by brenuart** [comment]
The missing guard was `@AutoConfigureBefore(MetricRepositoryAutoConfiguration.class)`.
But as far as I can tell, it has been introduced on `SpectatorMetricsAutoConfiguration` so everything should be ok now.

**Comment by spencergibb** [comment]
Thanks for the update!
