### ISSUE TITLE
display issue when using auto-generated port in eureka client

### ISSUE THREAD

**Issue by aximo** [spring-cloud/spring-cloud-netflix#1160]
When i use server.port=0 in eureka client,and not assign eureka.client.instance-id
then  this client register to eureka server, it will display application status like hostname:product:0

when i run two instance of this client ,the server dashboard will display only one instance.

I think is an issue. or anybody can tell me
1. how to get the real port in application.yml 
2. how to customize the instance-id using codes?

**Comment by spencergibb** [comment]
The instanceid needs to be unique and the default (which uses server.port) can't if the server.port=0. See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#changing-the-eureka-instance-id
