### ISSUE TITLE
Error when updating to Brixton SR2

### ISSUE THREAD

**Issue by gerar2** [spring-cloud/spring-cloud-netflix#1162]
Hello,
I have a gateway microservice implementation in a Spring Boot Application using Zuul that redirects Oauth2 authenticated requests to other microservices using Eureka.
I'm using the resource server token relay how is indicated in the [documentation](http://cloud.spring.io/spring-cloud-security/spring-cloud-security.html#_resource_server_token_relay) with the only difference of using Ribbon load balancer:

    @LoadBalanced
    @Autowired
    private OAuth2RestOperations restTemplate;
    
    @RequestMapping("/relay")
    public String relay() {
        ResponseEntity<String> response = restTemplate.getForEntity("http://OTHER-SERVICE-REGISTERED-IN-EUREKA/bar", String.class);
        return "Success! (" + response.getBody() + ")";
    }

It was working properly in Spring Cloud Brixton M5 but when updating to Spring Cloud Brixton SR2 I'm getting the following exception:

    java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.setTraces(Lorg/springframework/boot/actuate/trace/TraceRepository;) 

I could check that the `setTraces` method has been [recently removed](https://github.com/spring-cloud/spring-cloud-netflix/commit/8a7e165214fa4e97b881de0e0e90edf57d2c86ab#diff-89fb167ed1d4fc57df527a263a1612ceL88) and to reproduce the error only is required to include the `spring-cloud-starter-oauth2` dependency:

    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-oauth2</artifactId>
    </dependency>

Is this a bug? a kind of breaking compatibility? or I'm missing something?

Thanks

**Comment by spencergibb** [comment]
could you post the full stack trace?

**Comment by dsyer** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-security/issues/97

**Comment by gerar2** [comment]
Yes, It's the same issue. Sorry I couldn't find it.
Thank you guys.
