### ISSUE TITLE
Wrong port and context path in Eureka with war deployments

### ISSUE THREAD

**Issue by victorherraiz** [spring-cloud/spring-cloud-netflix#1165]
When we pack an app as war, eureka client register the app with the port in application.yml instead of tomcat one and it does not set the context path of the application.

Using 0 (random) as server port in application.yml prevents the application to be registered at all.

are we missing something?

**Comment by spencergibb** [comment]
you can't use a random port with a war based deployment can you?

**Comment by victorherraiz** [comment]
We use 8090 in tomcat, we only configured 0 to do a simple test.
I seems that the port configured has greater priority than the real one when the Eureka client registers the application.
Another problem is the context path, eureka client is not aware of the context path in war deployment.

These problems registration problems are quite importan when we use Zuul. It is picking wrong endpoinds.

At the moment, deploying with war is not recommend or not completely supported?

**Comment by spencergibb** [comment]
eureka doesn't know about contexts. when running in a war, IIRC, boot doesn't know the port it's running on, so you have to tell eureka using server.port (or eureka.instance.nonSecurePort).

**Comment by tietang** [comment]
after Container started, get http port by MBeanServer.

you can add the follow code:

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.ConfigurableEnvironment;
import org.springframework.stereotype.Component;

import javax.management.MBeanServer;
import javax.management.MBeanServerFactory;
import javax.management.ObjectName;
import java.util.Iterator;
import java.util.Set;


/**
 * @author Tietang Wang 铁汤
 * @Date: 16/7/19 09:27
 * @blog http://tietang.wang
 */

@Component
public class ServletContainerHttpPortResolver implements InitializingBean {

    public static final Logger LOGGER = LoggerFactory.getLogger(ServletContainerHttpPortResolver.class);
    @Autowired
    private ConfigurableEnvironment environment;


    @Override
    public void afterPropertiesSet() throws Exception {
        String serverPortKey = "server.port";
        int port = getHttpPort();
        if (port > 0) {
            environment.getSystemProperties().put(serverPortKey, port);
        }
    }

    public static int getHttpPort() {
        try {
            MBeanServer server = null;
            if (MBeanServerFactory.findMBeanServer(null).size() > 0) {
                server = MBeanServerFactory.findMBeanServer(null).get(0);
            }

            Set names = server.queryNames(new ObjectName("Catalina:type=Connector,*"), null);

            Iterator iterator = names.iterator();
            ObjectName name = null;
            while (iterator.hasNext()) {
                name = (ObjectName) iterator.next();

                String protocol = server.getAttribute(name, "protocol").toString();
                //                String scheme = server.getAttribute(name, "scheme").toString();
                String port = server.getAttribute(name, "port").toString();
                //                System.out.println(protocol + " : " + scheme + " : " + port);
                if (protocol.toUpperCase().contains("HTTP")) {
                    return Integer.parseInt(port);
                }

            }
        } catch (Exception e) {
            LOGGER.error("get http port ",e);
        }
        return 0;

    }
}

```

**Comment by spencergibb** [comment]
Just at a glance that look like it only works with tomcat, we'd need something that would work for all containers.

**Comment by tietang** [comment]
@spencergibb yes, for tomcat

**Comment by marcingrzejszczak** [comment]
> eureka doesn't know about contexts. when running in a war, IIRC, boot doesn't know the port it's running on, so you have to tell eureka using server.port (or eureka.instance.nonSecurePort).

As @spencergibb suggested, you have to set the port explicitly.
