### ISSUE TITLE
zuul multipart/form-data duplicate params

### ISSUE THREAD

**Issue by qihaiyan** [spring-cloud/spring-cloud-netflix#1171]
when tests with: 
curl -v -H "Transfer-Encoding: chunked" -F "file=@./test.txt" -F "foo=A" http://localhost:8080/simple/upload

FormBodyWrapperFilter will generates two "foo" params,the one is parts[0] and another one in pars[1]'s value.
the parts[0]: "foo" -> " size = 1"
the parts[1] has two value: 
<code>
\<InputStream resource [resource loaded through InputStream],{Content-Disposition=[form-data; name="file"; filename="test.txt"], Content-Type=[text/plain]}>
<p>
\<InputStream resource [resource loaded through InputStream],{Content-Disposition=[form-data; name="foo"]}>
</code>

so when get the "foo" param in Controller using RequestParam("foo"),will get foo=A,A.
Is this a bug or i can't use it this way?

**Comment by rozhok** [comment]
It's a bug introduced in #1067, I described my case which is basically same as yours there.

I've workarounded it with following piece of code in `FormBodyWrapperFilter`:
```java
for (Entry<String, List<MultipartFile>> parts : multi
        .getMultiFileMap().entrySet()) {
    for (Part part : this.request.getParts()) {
        if (part.getContentType() == null) { // form-data doesn't have content-type afaik
            continue;
        }
        HttpHeaders headers = new HttpHeaders();
        headers.setContentDispositionFormData(part.getName(),
                part.getSubmittedFileName());
        if (part.getContentType() != null) {
            headers.setContentType(
                    MediaType.valueOf(part.getContentType()));
        }
        HttpEntity<Resource> entity = new HttpEntity<Resource>(
                new InputStreamResource(part.getInputStream()),
                headers);
        builder.add(parts.getKey(), entity);
    }
}
```

**Comment by VanRoy** [comment]
Hi @qihaiyan, @rozhok ,

It seems that this is fixed by this commit on 1.2.0.RC : https://github.com/spring-cloud/spring-cloud-netflix/commit/0095ba89843cdc5d85a1d1f8703d2ca5249e9aa0

@spencergibb @dsyer, do you think it's possible to backport on 1.1.x next release ? 

Thanks.
Julien.

**Comment by spencergibb** [comment]
@VanRoy sure, I'd like to hear if it fixes @qihaiyan, @rozhok's problem.

**Comment by spencergibb** [comment]
@VanRoy see 7e493ea3e54d87ade5f44a216c98805fbe8857e5 on 1.1.x

**Comment by VanRoy** [comment]
Thanks @spencergibb , It's ok for me.
I have written a small integration test ( on the class FormZuulProxyApplicationTests )  for validate this fix and avoid regression. Do you want that I create a PR with this ?

**Comment by spencergibb** [comment]
@VanRoy PR yes!

**Comment by qihaiyan** [comment]
It's ok.
