### ISSUE TITLE
Can Eureka server be peer of self?

### ISSUE THREAD

**Issue by abhijitsarkar** [spring-cloud/spring-cloud-netflix#1172]
According to [Spring Cloud doc](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_peer_awareness), the following configuration in `bootstrap.yml` sets up Eureka on host `peer1` with a peer running on host `peer2`

    eureka:
      instance:
        hostname: peer1
      client:
        serviceUrl:
          defaultZone: http://peer2/eureka/

What I'm trying to do is define a dynamic list of peers that changes in each environment. While Dev environment may have only 2 Eureka instances, Pre-Prod may have 5. So I make the `defaultZone` an environment variable:

    client:
      serviceUrl:
        defaultZone: ${DISCOVERY_PEERS}

and then define environment variable `DISCOVERY_PEERS=http://peer1/eureka/,http://peer2/eureka/`

So far so good. So if an environment has hosts `peer1` and `peer2`, the `DISCOVERY_PEERS` for them should look as follows:
Host `peer1`:
`DISCOVERY_PEERS=http://peer2/eureka/`
Host `peer2`:
`DISCOVERY_PEERS=http://peer1/eureka/`

Problem is that the `DISCOVERY_PEERS` environment variable is predefined for each environment (we use Docker Compose), so for each server in that environment, there's no way to exclude the localhost. Thus, we can only do the following in `docker-compose.yml`:

    environment:
      DISCOVERY_PEERS: http://peer1/eureka/,http://peer2/eureka/

Is this an issue that host `peer1` is given itself as a peer? If yes, how to avoid this issue?

**Comment by spencergibb** [comment]
It's probably not a good thing.

**Comment by spencergibb** [comment]
Please don't post this in multiple places http://stackoverflow.com/questions/38256986/can-eureka-server-be-peer-of-self

**Comment by abhijitsarkar** [comment]
Can't blame a guy for trying, considering that SO response these days is abysmal. :)
So, if I shouldn't use the same hostname as a peer, what do you recommend?

**Comment by spencergibb** [comment]
You get what you pay for. Different configuration for each eureka server.

**Comment by abhijitsarkar** [comment]
Ok, thanks for your response. I'll close the SO thread.

**Comment by spencergibb** [comment]
I don't have any thoughts on what might happen if you use the same hostname.
