### ISSUE TITLE
Feign: setting header in feign RequestInterceptor does not work in BRIXTON.SR3

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#1191]
We want to switch from spring-cloud-1.0.0-RELEASE to spring-cloud-Brixton.SR3 and and find that calls to  @FeignClient annotated services interfaces are executed in an async manner (hystrix command). 
This way our registred feign ReceptInterceptors which uses ThreadLocal bound headers to be forwarded to the receiver does not work as expected.

Is there a way to avoid the async execution or to put the required heders into a ThreadLocal within the Thread which executes the hystrix command.

**Comment by dsyer** [comment]
That was a nasty shock then? Feign uses Hystrix if it's available since s-c-netflix 1.1. From the user guide:

> To disable Hystrix support for Feign, set feign.hystrix.enabled=false.

You could also set the isolation strategy to SEMAPHORE globally (that's a regular Hystrix feature).

**Comment by LutzStrobel** [comment]
Thank you for your answer.
Normally we dont want to change the default behavior. But we have to transfer tenant specific headers. So, the call have to stay in the same thread if there is no implementation to transfer the header into a bean reachable from within the executing thread. 
Is there any option to do it by configuration or implementation?

**Comment by dsyer** [comment]
Both the solutions I mentioned above will work. If you are migrating from 1.0.0 the first one is the one that keeps the behaviour the same.

**Comment by LutzStrobel** [comment]
Thanx, now it works. A missing piece was the correct timeout.
