### ISSUE TITLE
Make FeignClientRegistrar Spring 4.2 backwards compatible

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1192]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsRegistrar.java#L193-L194

See https://pivotal.slack.com/archives/spring-cloud/p1468684522000002

Thanks @snicoll

**Comment by spencergibb** [comment]
@dsyer, @marcingrzejszczak or @ryanjbaxter

**Comment by ryanjbaxter** [comment]
@spencergibb sorry just getting to this notification, did you need something? looks like you already committed the fix...

**Comment by spencergibb** [comment]
The fix I did only works for spring 4.3.x, @snicoll shared a backwards compatible fix for 4.2.x in the linked conversation
