### ISSUE TITLE
[feign client] special query character cause returned http status code 400

### ISSUE THREAD

**Issue by Coramo** [spring-cloud/spring-cloud-netflix#1194]
This is my feign client def.

```

@FeignClient("food-service")
public interface FoodService {
  @RequestMapping(
    value = {"/food"},
    method = {RequestMethod.GET}
  )
  List<Food> find(@RequestParam("name") String name);
}
```

`foodService.find("cookie");`
This is working fine;

`foodService.find("co%");`
the `%` is a special character , this call will be returned status code 400 .

**Comment by Coramo** [comment]
I track the code.
Final ,feign using the default client implement `feign.Default` to send the request.

But, `execute` method parameter `request.url` value is `http://192.168.1.102:8080/food?name=co%`,

This url cannot to send from `HttpURLConnection` , because `%` need to encode to be `%25`

**Comment by dsyer** [comment]
Feign does encode request parameters, and it works fine for me (the receiver sees "co%" if it is a Spring MVC handler). I suspect that the problem might be on the server (it is sending the 400 after all, not the client).

**Comment by Dreampie** [comment]
![](https://static.dingtalk.com/media/lALOXqkfKc0DH80GMQ_1585_799.png_620x10000q90.jpg)
![](https://static.dingtalk.com/media/lALOXqjwns0Da80GdQ_1653_875.png_620x10000q90.jpg)

**Comment by Dreampie** [comment]
![laloxqyapmz3zqj4_632_247](https://cloud.githubusercontent.com/assets/3667080/16979408/8819658e-4e93-11e6-8ebb-1326b8c8c8c4.png)
![laloxqyfi80bn80b3g_478_415](https://cloud.githubusercontent.com/assets/3667080/16979410/8a612f48-4e93-11e6-9e12-1f7dc052b9ac.png)

**Comment by Coramo** [comment]
@dsyer  

Thank for your remind , `FoodService` creating by my suspect , `foodService.find("co%");` is also.

Then i review the code again , i found this code  in `RequestTemplate` class  : 
```
private String encodeIfNotVariable(String in) {
    if (in == null || in.indexOf('{') == 0) {
      return in;
    }
    return urlEncode(in);
  }
```

`encodeIfNotVariable` called in `query(String name, String... values)` .

This means if the value containing `{` and in the first , the value cannot to be encode.

you can try it this :  `foodService.find("{co%%");`


PS: my `spring-cloud-feign-client` usage is complex and cannot show in here .

**Comment by dsyer** [comment]
`RequestTemplate` is part of Feign. If it isn't meeting your needs you probably need to open an issue there (https://github.com/OpenFeign/feign).

**Comment by adriancole** [comment]
recent versions of feign allow custom contracts to skip encoding, but I'm not sure if it is a good idea or not to change `@RequestParam` to permit this.

If this was desired, the below could be specify an initial boolean parameter indicating the user wants this to be interpreted as-is.

https://github.com/spring-cloud/spring-cloud-netflix/blob/ff46a7dc509e6f5b129282f83b6b347825690bba/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/annotation/RequestParamParameterProcessor.java#L58

the function used is here:
https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/RequestTemplate.java#L318
