### ISSUE TITLE
EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#1195]
EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.

**Comment by spencergibb** [comment]
Reopen if you have details or anything more than what you pasted.

**Comment by Dreampie** [comment]
Why get this warning ? when restart eureka server this disappear，but  restart service it reappear。

**Comment by ccit-spence** [comment]
If there are no instances present it is normal for that message to appear.  It is saying that the expected number of service instances are lesser than expected.  When you restart a service the condition is created.

**Comment by Dreampie** [comment]
![image](https://cloud.githubusercontent.com/assets/3667080/16977690/4012a920-4e8a-11e6-852d-9e1692f31c13.png)

**Comment by ccit-spence** [comment]
Is the number of services listed less than normal?

**Comment by Dreampie** [comment]
now ，two peer of eureka instance，you mean add eureka instance？

**Comment by Keets2016** [comment]
I got the same problem.

**Comment by antenehrepos** [comment]
Looks like it appears when there's no instance registered for quite some time, if you start one instance and keep refreshing, the message goes away.

**Comment by ryanjbaxter** [comment]
Take a look at the conversation in #1322 for more details about why this message appears.

**Comment by rajkiit116** [comment]
restart the server
