### ISSUE TITLE
Feign: support @GetMapping and other annotations

### ISSUE THREAD

**Issue by chrylis** [spring-cloud/spring-cloud-netflix#1201]
Spring 4.3 introduced composite annotations such as `@GetMapping` that allow for simpler specification of mappings. The Spring Cloud extensions to Feign enable `@RequestMapping` but do not yet understand the composite annotations.

**Comment by spencergibb** [comment]
Yet another reason to not support them by default :-(

**Comment by Infrag** [comment]
Its quiet easy fix, modifiction of just one condition. I will add pull-request.

**Comment by Infrag** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/pull/1586

**Comment by bandanag1** [comment]
New annotation @GetMapping / @PostMapping ... not supported in spring-cloud in a @FeignClient, Is there any further update?

**Comment by ryanjbaxter** [comment]
The right place for this question is in the Spring Cloud OpenFeign project

**Comment by bandanag1** [comment]
I couldn't make it working for @GetMapping or @PostMapping. But it works with @RequestLine and @Param in openfeign client.

**Comment by spencergibb** [comment]
@bandanag1 please join us on gitter for questions. Looks like you are not using the spring cloud integration, otherwise `@RequestLine` wouldn't work.
