### ISSUE TITLE
use FormBodyWrapperFilter  will result in a multi-threaded blocked 

### ISSUE THREAD

**Issue by demochen** [spring-cloud/spring-cloud-netflix#1203]
FormBodyWrapperFilter   137line  use AllEncompassingFormHttpMessageConverter，it final will use 
![image](https://cloud.githubusercontent.com/assets/5051511/17022278/a4232124-4f7f-11e6-9b8f-984d8be2131a.png)
when enable FormBodyWrapperFilter    tps in 4core8G server only have 400+tps 
![image](https://cloud.githubusercontent.com/assets/5051511/17022342/fe218d6e-4f7f-11e6-81d1-706ba7ebd5b2.png)

when i disable FormBodyWrapperFilter    tps  increase to 4900+ 
![image](https://cloud.githubusercontent.com/assets/5051511/17022352/0dcc48b2-4f80-11e6-96ac-518196d3bcfc.png)

**Comment by spencergibb** [comment]
@dsyer any particular reason `synchronized` is used here?

**Comment by spencergibb** [comment]
I ran our local integration tests without failures. @demochen any chance you could compile without the `synchronized` keyword and verify your tests?

**Comment by dsyer** [comment]
There's one instance of the converter per request, so I don't see how a synchronized block there could be a bottleneck. Also it's in Spring (not Cloud) so we can't do anything about it.

**Comment by marcingrzejszczak** [comment]
@demochen is it still an issue with the latest release trains?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
