### ISSUE TITLE
FormBodyWrapperFilter frequently new MappingJackson2HttpMessageConverter instance, cause  performance issue

### ISSUE THREAD

**Issue by tietang** [spring-cloud/spring-cloud-netflix#1207]
in org.springframework.cloud.netflix.zuul.filters.pre.FormBodyWrapperFilter#run line 114/118, per request will new FormBodyRequestWrapper instance, class FormBodyRequestWrapper again create AllEncompassingFormHttpMessageConverter instance,so this will frequently create MappingJackson2HttpMessageConverter instance, and finally, will call java.lang.ClassLoader#loadClass(java.lang.String, boolean):

1. java.lang.ClassLoader#loadClass(java.lang.String, boolean) is synchronized method, the method will block thread
2. will search class by name in thousands classes

that's all.

**Comment by ryanjbaxter** [comment]
Not sure I am following, what exactly is the problem you are seeing?

**Comment by dsyer** [comment]
Duplicates #1203?
