### ISSUE TITLE
JNDI lookup fails with key spring.cloud.bootstrap.location: in IBM Liberty

### ISSUE THREAD

**Issue by remesh22** [spring-cloud/spring-cloud-netflix#1208]
I am facing a weird issue with containers other than Tomcat.The issue is with StandardServletEnvironment 
which includes JNDIDatasource as one of the property source.

@Override
	protected void customizePropertySources(MutablePropertySources propertySources) {
		propertySources.addLast(new StubPropertySource(SERVLET_CONFIG_PROPERTY_SOURCE_NAME));
		propertySources.addLast(new StubPropertySource(SERVLET_CONTEXT_PROPERTY_SOURCE_NAME));
		if (JndiLocatorDelegate.isDefaultJndiEnvironmentAvailable()) {
			propertySources.addLast(new JndiPropertySource(JNDI_PROPERTY_SOURCE_NAME));
		}
		super.customizePropertySources(propertySources);
	}
Spring is by default  looking for some jndi properties ending with ":" at the end of the property.The lookup is failing for the following properties 
spring.cloud.bootstrap.name:
SPRING_APPLICATION_JSON: 
spring.cloud.bootstrap.location: etc

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces the problem?

**Comment by remesh22** [comment]
Here is the sample project.
[demo_ibm.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/379770/demo_ibm.zip)

**Comment by ryanjbaxter** [comment]
The project does not have any dependencies on Spring Cloud I think you should open the issue against the [Spring Framework project](https://github.com/spring-projects/spring-framework)
