### ISSUE TITLE
Use a variable in @HystrixProperty to set value field

### ISSUE THREAD

**Issue by jabrena** [spring-cloud/spring-cloud-netflix#1209]
Good morning,

I am using Hyxtrix to implement the Circuit Breaker design pattern.  I would like to know how to pass the value using a variable or reading from Config Server

``` java
    @HystrixCommand(
        commandProperties = {
            @HystrixProperty(
name="execution.isolation.thread.timeoutInMilliseconds", 
value="500")
    })
```

**Idea 1:**

``` java

    @Value("${system1.timeout}")
    String system1Timeout;

    @HystrixCommand(
        commandProperties = {
            @HystrixProperty(
name="execution.isolation.thread.timeoutInMilliseconds", 
value="system1Timeout")
    })
```

This idea doesn't work.

**Idea 2:**

``` java

    @HystrixCommand(
        commandProperties = {
            @HystrixProperty(
name="execution.isolation.thread.timeoutInMilliseconds", 
value="${system1.timeout}")
    })
```
This idea doesn't work.

Many thanks in advance.

Juan Antonio

**Comment by spencergibb** [comment]
HystrixCommand is third party code. It will never work. You should be able to put those properties in application.yml.

**Comment by jabrena** [comment]
Hi @spencergibb,

If I set the Hyxtrix configuration on application.yml, how to set different values for different Hyxtrix commands?

Juan Antonio

**Comment by daniellavoie** [comment]
Hystrix properties cannot be dynamic. It's part of the philosophy of Hystrix. Myself was interested in having a dynamic timeout value depending on the content of my processing, but Hystrix does not permit this feature.

**Comment by jabrena** [comment]
The idea of issue was, how to configure parameters of a HyxtrixCommand outside of the usage.

I found a way:

``` java
hystrix:
  command:
    beanMethodInteractingWithSystem1:
      execution:
        timeout:
          enabled: true
        isolation:     
          thread:
            timeoutInMilliseconds: 20000 
```

**Comment by cforce** [comment]
And what happens if i have two classes with the same name "
beanMethodInteractingWithSystem1" ??

Juan Antonio Breña Moral <notifications@github.com> schrieb am Fr., 22.
Juli 2016 um 12:59 Uhr:

**Comment by cforce** [comment]
http://stackoverflow.com/questions/31211685/configuring-hystrix-command-properties-using-application-yaml-in-spring-boot-app

cforce <cforce@gmx.de> schrieb am Fr., 22. Juli 2016 um 15:05 Uhr:
