### ISSUE TITLE
SpringMvcContract is using existing ConversionService bean

### ISSUE THREAD

**Issue by ouaibsky** [spring-cloud/spring-cloud-netflix#1210]
Default FeinContract bean has a dependency on a ConversionService bean.
The issue is my project already define a ConversionService for internal usage.

So my bean is used in place of the one provided by autoconf, and it generates 2 pb:
 * I'm not sure feigncontract is supposed to support something that is not implementing FormatterRegistry 
 * Our own ConversionService need FeignClient bean that generate a circular bean instantiation error in spring

We have 2 option:
* make the require bean more specific (like in PR #1200 )
* Name this bean.

Christophe

**Comment by ryanjbaxter** [comment]
@ouaibsky maybe I am missing something here, but I don't see a bean called `FeignContract` in the repository....

**Comment by ouaibsky** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsConfiguration.java#L79
 line 79

Sorry it's a Contract and implementation by default: SpringMvcContract

**Comment by ryanjbaxter** [comment]
Have you looked at using `FeignFormatterRegistrar` and registering your `ConversionService` with that?

**Comment by ouaibsky** [comment]
The issue is I have an existing ConversionService in my legacy code, and I don't want it to be used by SpringMvcContract. 
It's legacy code that is absolutely not related to feign client and I would like to keep default configuration provided by FeignClientConfiguration

**Comment by ryanjbaxter** [comment]
I am confused now because in your description and the pull request you pointed to it looks like you wanted to use your own ConversionService.  Is the issue that your ConversionService is a bean and that FeignClientConfiguration is using that Bean instead of the default?

**Comment by ouaibsky** [comment]
Yes, that's the issue.

**Comment by spencergibb** [comment]
Not sure there's anything we can do on our side. If you want to continue using our feign integration you'll need to provide a `ConversionService` annotated with `@Primary` and your legacy one with some other qualifier (since there will be two `ConversionService` beans).

**Comment by ouaibsky** [comment]
looks like the expected bean required by SpringMvcContract is more than a basic ConversionService,

Is PR #1200 not a valid option, or give a name to the expected bean ?

I'm not a big fan of @Primary spring annotation. It works more or less with boot 1.2 (specially for unit test) but after boot 1.3 a lot of things broken (don't know if was due to spring core or feign upgrade)
I also remember an article saying @Primary should be the last solution to override beans.

Christophe.

**Comment by spencergibb** [comment]
I don't know if I want to do that.  Your case seems pretty specific. Though your PR can be your work around:
```
	public Contract feignContract(FormattingConversionService feignConversionService) {
		return new SpringMvcContract(this.parameterProcessors, feignConversionService);
	}
```

**Comment by spencergibb** [comment]
I suppose if more people have this problem we could look at it again.

**Comment by ouaibsky** [comment]
fair enough, in fact it's my current workaround.
I just pointed out that the default feign autoconfig was not working if you already have another ConversionService bean in your context. 

at least you need the proposed hack, maybe to be added to the doc because I spent time to understand why it was not working as expected.

Regards
Christophe
