### ISSUE TITLE
XHRStreaming connection never closed when heartbeat smaller than zuul.host.socket-timeout-millis

### ISSUE THREAD

**Issue by sirjasiu** [spring-cloud/spring-cloud-netflix#1215]
Hi,

we're using zuul and spring cloud to forward xhr streaming requests. Unfortunately after a while the whole connection pool is blocked since despite xhr streaming connection is closed between client side and server which uses zuul forwarding, this connection is remained one the other side of forwarding side.
We believe it might be caused by the heartbeat generated on server side of our connection. We had to set up socket-timeout on zuul's side to be bigger than the heartbeat interval, otherwise connection to server was broken since there was no response (heartbeat) withing the timeout.
Unfortunately when this heartbeat is smaller than timeout connection is always remained despite the fact there is not client attached to the zuul server. 
We believe it is caused by the ignoring of the PipeBroken exception in the SendResponseFilter.writeRsponse:
```
private void writeResponse(InputStream zin, OutputStream out) throws Exception {
		byte[] bytes = new byte[INITIAL_STREAM_BUFFER_SIZE.get()];
		int bytesRead = -1;
		while ((bytesRead = zin.read(bytes)) != -1) {
			try {
				out.write(bytes, 0, bytesRead);
				out.flush();
			}
			catch (IOException ex) {
				// ignore
			}
			// doubles buffer size if previous read filled it
			if (bytesRead == bytes.length) {
				bytes = new byte[bytes.length * 2];
			}
		}
	}
```
When you read from zuul input stream (heartbeat) and try to pass this information to the output stream (which is already closed) and get PipeBroken exception, we believe you should close zin InputStream, the whole connection, otherwise it will block this connection (since the heartbeat is going to be passed there all the time).

This is our first idea we came up with trying to solve this problem with blocked all of those connections in zuul. Maybe we are wrong. If yes, sorry for causing any troubles. ;)

**Comment by spencergibb** [comment]
zuul 1.x isn't built for streaming/websockets.
