### ISSUE TITLE
Throw exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper while using the version after Brixton.M5 of  spring-cloud-starter-parent (as the dependency eureka-core exclude the jackson-dataformat-xml after 1.1.0.RELEASE )

### ISSUE THREAD

**Issue by summitxf** [spring-cloud/spring-cloud-netflix#1216]
eureka-core exclude the jackson-dataformat-xml after 1.1.0.RELEASE 
RUN a spring cloud project got  java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.xml.XmlMapper

full log:
```
Error creating bean with name 'org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration.eurekaServerBootstrap; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaServerBootstrap' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.registry.PeerAwareInstanceRegistry]: Error creating bean with name 'peerAwareInstanceRegistry' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.resources.ServerCodecs]: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'peerAwareInstanceRegistry' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.resources.ServerCodecs]: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper
```
the maven pom
```
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.SR4</version>
		<relativePath />
	</parent>
```

if use the version Brixton.M5 that will run successful as it was dependented version of eureka-core was 1.1.0.M5 doesn't exclude the jackson-dataformat-xml

**Comment by ryanjbaxter** [comment]
I am not sure I follow.  Brixton.SR4, Brixton-SNAPSHOT, and Camden-SNAPSHOT all depend on Eureka 1.4.10.  We upgraded the Eureka dependencies between Brixton.SR3 (Eureka 1.4.8) and SR4.  Do you have a sample project you can share?

**Comment by summitxf** [comment]
I'm tring to write a demo of spring cloud with eureka.

Here is the full maven pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.springcloud.demo</groupId>
	<artifactId>springcloud-demo-eureka</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.SR4</version>
		<relativePath />
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

the application java file: 

package com.springcloud.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@SpringBootApplication
// same as @Configuration @EnableAutoConfiguration @ComponentScan
@EnableEurekaServer
public class Application  {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}

I got the error msg:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.netflix.eureka.server.EurekaServerBootstrap org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration.eurekaServerBootstrap; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'eurekaServerBootstrap' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.registry.PeerAwareInstanceRegistry]: Error creating bean with name 'peerAwareInstanceRegistry' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.resources.ServerCodecs]: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'peerAwareInstanceRegistry' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.netflix.eureka.resources.ServerCodecs]: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverCodecs' defined in class org.springframework.cloud.netflix.eureka.server.EurekaServerConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.eureka.resources.ServerCodecs]: Factory method 'serverCodecs' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/xml/XmlMapper

it will run successful if I change the pom.xml as below, and I noticed that the difference between these two version is eureka-core exclude the jackson-dataformat-xml after 1.1.0.RELEASE 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.springcloud.demo</groupId>
	<artifactId>springcloud-demo-eureka</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.M5</version>
		<relativePath />
	</parent>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/libs-snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by summitxf** [comment]
@ryanjbaxter 
refer your demo : [spring-cloud-demo](https://github.com/ryanjbaxter/spring-cloud-demo)
if you change the version to the latest you will got the same exception as mentioned above

CHANGE pom.xml from :

```
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.2.0.RC2</version>
  </parent>
  
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>1.0.0.M3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

to:
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
	</parent>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-parent</artifactId>
				<version>Brixton.SR4</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by ryanjbaxter** [comment]
@summitxf I am still not able to reproduce this.  Can you try and reproduce it with the [Eureka sample](https://github.com/spring-cloud-samples/eureka) from Spring Cloud Samples?

**Comment by summitxf** [comment]
@ryanjbaxter [Eureka sample](https://github.com/spring-cloud-samples/eureka) was run successful!
And I change the **spring-boot-starter-parent version** of [spring-cloud-demo](https://github.com/ryanjbaxter/spring-cloud-demo)(yes, as mentioned above), ran well too.

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.3.6.RELEASE</version>
    </parent>
```
it was 1.3.5 last time, that means this version would got exception.

It's amazing!

Anyway, it can be work now, thanks very much!

BTW, if the pom like this as below without spring-boot-starter-parent version's declaration would got the exception too, as the defalt version is 1.3.5.RELEASE

```
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.SR4</version>
		<relativePath />
	</parent>
```
