### ISSUE TITLE
how can the default IRule be prototyping with no explicit prototyping declaration in RibbonClientConfiguration class

### ISSUE THREAD

**Issue by wumushanshui** [spring-cloud/spring-cloud-netflix#1218]
Hi,
```
@Bean
@ConditionalOnMissingBean
public IRule ribbonRule(IClientConfig config) {
		if (this.propertiesFactory.isSet(IRule.class, name)) {
			return this.propertiesFactory.get(IRule.class, config, name);
		}
		ZoneAvoidanceRule rule = new ZoneAvoidanceRule();
		rule.initWithNiwsConfig(config);
		return rule;
}
```
above is the source code, I can not understand why ZoneAvoidanceRule is prototyping when I debug into my zuul apigateway application.  Is there anything else I missed ? I've got stuck in this problem for a whole day. I'd appreciate it if somebody could help me?

**Comment by spencergibb** [comment]
One is created for each ribbon client.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
