### ISSUE TITLE
register only one rest/method/class to Eureka server

### ISSUE THREAD

**Issue by killjason** [spring-cloud/spring-cloud-netflix#1222]
In the Eureka client application, we defined 'spring.application.name' in the file 'application.properties'.
so this application will register to Eureka server, If I just want to register one rest/method/class of this Eureka client application, How should I do?

**Comment by ryanjbaxter** [comment]
Eureka is used for service discovery, it does not care really what that service does.  Whether your service has one REST API, 1000, or none, the only purpose Eureka serves is to provide the IP/URL to your service to other apps.  From there the other apps can call whatever APIs that service may offer.  If you would like to learn more about this you can take a look at the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_service_discovery_eureka_clients) and sample applications
https://github.com/spring-cloud-samples/eureka
https://github.com/spring-cloud-samples/customers-stores
