### ISSUE TITLE
Content-length not properly set when using the FormBodyWrapperFilter

### ISSUE THREAD

**Issue by jebeaudet** [spring-cloud/spring-cloud-netflix#1223]
When using the `FormBodyWrapperFilter`, the form parameters gets encoded in the `FormHttpMessageConverter`. The problem arises when you get a form param that was encoded with the javascript `encodeURIComponent` method or `curl` which do not have the same rules as `URLEncoder` (for example, '(' doesn't get encoded in `encodeURIComponent` but will be in `URLEncoder`). 

This causes the body to be larger than the original body. While this is not necessarily a problem, the content-length of the request is not properly set in `HttpClientRibbonCommand` on Brixton and in `AbstractRibbonCommand` on the master branch. Result : the form param get stripped on the backend or in the case where the body is shorter than the original, the backend server will wait for the missing bytes and will most likely trigger a timeout.

I'll submit a PR shortly for discussion.

**Comment by jebeaudet** [comment]
Thx for merging the PR. Would it be possible to merge the PR for the brixton branch as well for the 1.1.6 release?

**Comment by ryanjbaxter** [comment]
#1224?

**Comment by jebeaudet** [comment]
Yes exactly

**Comment by ryanjbaxter** [comment]
Done

**Comment by jebeaudet** [comment]
Thanks a bunch!
