### ISSUE TITLE
does ribbon/Eureka only supports round-robin load-balancing?

### ISSUE THREAD

**Issue by killjason** [spring-cloud/spring-cloud-netflix#1226]
What other load-balancing types does ribbon/Eureka support?

**Comment by spencergibb** [comment]
no, you can plug in different rules: See the [ribbon javadocs](http://netflix.github.io/ribbon/ribbon-core-javadoc/com/netflix/loadbalancer/IRule.html) for the kinds of rules available. See the [docs](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#customizing-the-ribbon-client) for how to customize ribbon. Might look like something below.

```
@Configuration
@RibbonClient(name = "foo", configuration = FooConfiguration.class)
public class TestConfiguration {
}
@Configuration
public class FooConfiguration {
    @Bean
    public IRule ribbonRule(IClientConfig config) {
        return new RandomRule();
    }
}
```
