### ISSUE TITLE
Can I relay request headers by feignClient?

### ISSUE THREAD

**Issue by steventong** [spring-cloud/spring-cloud-netflix#1229]
I want to relay my request headers to every microservice. How to do it ?

**Comment by spencergibb** [comment]
What does "my request headers to every microservice" mean? There are multiple ways to pass headers to feign, but it depends on what you want to do.

**Comment by steventong** [comment]
api-service receive requests with header "Authorization", I want to realy this Authorization to A-service,B-service,etc.

**Comment by daniellavoie** [comment]
Feign interceptors are the way to go. Check out the reference doc. There is some info about that.

**Comment by Alok86JavaPro** [comment]
how to pass dynamic header through Feign interceptors ?
