### ISSUE TITLE
Zuul Pre Filter Not Invoked

### ISSUE THREAD

**Issue by freedombird9** [spring-cloud/spring-cloud-netflix#1230]
I wonder what might cause the requests to skip the Zuul pre filter? My Zuul server has always been working well until I updated a dependent library.  Then the requests no longer go through the Zuul pre filter. I checked the log during Zuul startup, the ZuulFilterInitializer is contextInitialized and I don't get any additional warnings.

I don't think it's due to Zuul config or Zuul code, since it worked well before.  For the library update, I just added a Spring Security filter that's not actually meant for Zuul. Zuul just happen to share the library with other apps. SO Zuul doesn't use any of the added functionality.

**Comment by spencergibb** [comment]
The `PreDecorationFilter` only filters if the following condition is met:
```
	@Override
	public boolean shouldFilter() {
		RequestContext ctx = RequestContext.getCurrentContext();
		return !ctx.containsKey("forward.to") // a filter has already forwarded
				&& !ctx.containsKey("serviceId"); // a filter has already determined serviceId
	}
```

Otherwise we'd need a sample that reproduces the problem.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by MarcoCeccotti** [comment]
I dont'k know if this question is still open, but i have the same problem. I mean, when the request sent from zuul is founded on its routes the PreFilter class is invoked, otherwise not. Is there a possibility to invoke the zuul PreFilter in every case?

**Comment by ryanjbaxter** [comment]
There needs to be a route found before a Zuul pre filter is run

**Comment by MarcoCeccotti** [comment]
Really thank you Ryan! so isn't there a possibility to filter every kind of request?

**Comment by spencergibb** [comment]
Filters can only be run on routes. To filter everything regardless of if it matches in zuul create a servlet filter

**Comment by MarcoCeccotti** [comment]
Ok perfect! Thank you very much.
