### ISSUE TITLE
Make FeignClientFactoryBean class public?

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-netflix#1231]
Can the `FeignClientFactoryBean` class be declared as public? I have a need to dynamically create Feign client beans on the fly (after startup) and did so in a way similar to the below, but in order for this to work, my class that runs the code below has to be declared in the same package as `FeignClientFactoryBean` rather than my own. Not a huge deal, but would be nice if my class that manages this code below could just live in my own package

```
...
       BeanDefinitionBuilder definition = BeanDefinitionBuilder
                .genericBeanDefinition(FeignClientFactoryBean.class);

        String className = clientClass.getName();

        definition.addPropertyValue("url", "");
        definition.addPropertyValue("path", "");
        definition.addPropertyValue("name", serviceName);
        definition.addPropertyValue("type", className);
        definition.addPropertyValue("decode404", false);
        definition.addPropertyValue("fallback", fallbackClass);
        definition.setAutowireMode(AbstractBeanDefinition.AUTOWIRE_BY_TYPE);

        String alias = serviceName + "FeignClient";
        AbstractBeanDefinition beanDefinition = definition.getBeanDefinition();
        beanDefinition.setPrimary(true);
        BeanDefinitionHolder holder = new BeanDefinitionHolder(beanDefinition, className, new String[] { alias });

        GenericApplicationContext tmpContext = new GenericApplicationContext(appContext);
        BeanDefinitionReaderUtils.registerBeanDefinition(holder, tmpContext);
        tmpContext.refresh();

        Object client = tmpContext.getBean(alias);

...
```

**Comment by spencergibb** [comment]
@bitsofinfo I don't think I want this to be a public class. If you want to go outside of the `@FeignClient` way of creating feign clients you should use the `Feign.Builder` directly.

**Comment by bitsofinfo** [comment]
Just so you understand, the point of me wanting to do this is that if someone would like to create FeignClients dynamically that are configured in the exact same way as all other @FeignClients are at startup by spring-cloud... there is no simple way of doing this without reading all the code, which someone should not have to do. 

Using this method above, permits dynamic creation while ensuring you are leveraging all the great stuff spring-cloud is doing under the covers on making that feign client fully integrated w/ the hystrix/ribbon/eureka setup out of the box.

If someone wants to do that, without just using similar code to what is in this factory, its just a lot of hours of research (at least for me it was)

**Comment by sdoeringNew** [comment]
Yes. This makes it almost impossible to recreate the behaviour of creating FeignClients if you can't set the Annotation, e.g. on generated Feign interfaces.

For example we let swagger-codegen generate the Feign Interface from our OpenAPI schema.

It would be so much easier to have a factory method with the same input parameters as the ```@FeignClient``` annotation has and just build a FeignClient bean in a ```@Configuration``` class.
