### ISSUE TITLE
zuul routing with same name for endpoint(path) but different services

### ISSUE THREAD

**Issue by anukiransolur** [spring-cloud/spring-cloud-netflix#1234]
I want to have routes as shown below :

 ```
  zuul:
     prefix:/a
     stripPrefix:true
     routes:    
       route1:
          path:/v1
          serviceId: service1
          stripPrefix:false 

       route2:
          path:/v1
          serviceId: service2
          stripPrefix:false 
```

But every time I request the endpoint v1 on service2 I get results from service1. How to set the properties such that I can have same end point on two different services?

**Comment by spencergibb** [comment]
Unfortunately you have two routes that are identical (`/a/v1`), we don't handle that case. If you wanted `/a/route1/v1` and `/a/route2/v1`, then you have to explicitly put `/route1/v1`, etc... as part of the path.

**Comment by anukiransolur** [comment]
@spencergibb Thanks for the reply. Do you mean I can still get to work with these two endpoints by having the routes configured in the following way ?

 zuul:
     prefix:/a
     stripPrefix:true
     routes:    
       route1:
          path:/r1/v1
          serviceId: service1
          stripPrefix:true

       route2:
          path:/r2/v1
          serviceId: service2
          stripPrefix:true
