### ISSUE TITLE
Zuul filters not being replaced from ApplicationContext between tests

### ISSUE THREAD

**Issue by ShawnTuatara** [spring-cloud/spring-cloud-netflix#1236]
http://stackoverflow.com/questions/38622886/spring-boot-test-with-zuul-filters-is-not-picking-up-new-instance-of-bean

As the stackoverflow states I was able to resolve the issue temporarily by adding a @DirtiesContext to each test class and that allowed my tests to pass. The overall concern is that between test classes where Zuul filter beans were being recreated that the Zuul processing didn't pickup those new filters and instead continued to used the first instantiated versions of the filters.

**Comment by spencergibb** [comment]
We use `@DirtiesContext` regularly. That's how the spring context works in it's testing framework.

**Comment by ShawnTuatara** [comment]
The concern I have is that there is no indication that I should have used `@DirtiesContext` until I spend a few hours diving into the fact that multiple instances of my Filter bean were being created and that the Zuul processing wasn't picking up that new instance in subsequent test classes. in talking with @philwebb he was concerned about having to use `@DirtiesContext` to get around my problem. What are the guidelines on this in relation to `@SpringBootTest`. The information I was given is that, where possible, the application context is cached between separate test classes. It would seem that in this situation the caching of the Zuul processing beans is what caused the issue as the underlying Filters that those beans used have been replaced with new instances in the context.

**Comment by philwebb** [comment]
Without looking at a sample that shows the issue it's very hard to offer advice. My gut instinct is that the `@Before`/`@After` rules that change `LiveMigrationRoutes` somehow confuse Zuul. Perhaps it has some caching and isn't aware that the world has shifted beneath its feed? 

@spencergibb  I'm not familiar enough with Zuul to say what's going on here but you might be able to use a `TestExecutionListener` if some state in the bean needs to get removed after each test.

**Comment by steve-stogner** [comment]
I ran into this issue in Spring Boot 1.5.13.  In short, an application context refresh does not refresh the filter registry in the com.netflix.zuul code.

FilterProcessor.runFilters gets its filter list from the FilterLoader singleton, which in turn pulls from the FilterRegistry singleton.  Note that FilterRegistry.put uses Map.putIfAbsent to add filters.  So even though the ZuulRefreshListener executes when the test framework refreshes the Spring application context (see ZuulServerAutoConfiguration.java) and ultimately calls FilterRegistry.put with new filter instances, FilterRegistry.put does not replace the old filters with the new ones.

Applying `@DirtiesContext` did not work for me.  Instead, I worked around this issue by manually removing the old filter from the registry before running my Zuul tests:
```
    @BeforeClass
    public static void beforeClass() {
        FilterRegistry filterRegistry = FilterRegistry.instance();
        // note that you may need to purge additional filters for your tests
        filterRegistry.remove("preDecorationFilter");
    }
```

**Comment by marcingrzejszczak** [comment]
The recommended approach is to use the workaround suggested by @steve-stogner

**Comment by grommitz** [comment]
I find even this does not work because another singleton, FilterLoader, keeps its own cache of filters in a ConcurrentHashMap called hashFiltersByType. On the first call, when this is empty, it gets the filter from FilterRegistry, but on subsequent calls it takes it from this cache, so even removing and re-putting the filter to the FilterRegistry does not work.
