### ISSUE TITLE
eureka-client to Eureka-servers load-balance?

### ISSUE THREAD

**Issue by killjason** [spring-cloud/spring-cloud-netflix#1237]
1.There are 3 Eureka-Servers for the eureka-clients to register.  
   In the eureka-client properties, how to set the properties, to make the 3 Eureka-servers all available for the eureka-client.(or make the eureka-client use load-balance to register to the 3 Eureka-servers)
2. I know that set 'eureka.shouldUseDns=true' is one of the solution, what is the best practice in production environment(NOT AWS environment)?

**Comment by marcosbarbero** [comment]
Add a comma separated list of the eureka servers to make the clients.

**Comment by killjason** [comment]
@marcosbarbero, If add a comma separated list, what kind of load-balance strategy does the eureka-client will use to communicate with the eureka-servers?

**Comment by marcosbarbero** [comment]
They won't load balance because the eureka servers are peers so the client will pickup the first available server, if the first is down then it will pickup the next to the list

**Comment by killjason** [comment]
@marcosbarbero, Thank you for answer,  What is the best practice in production environment? Use 'eureka.shouldUseDns=true' OR comma separated list?

**Comment by marcosbarbero** [comment]
It depends on your environment, if you have an DNS available use it. If not, the comma separated list will work fine.

**Comment by killjason** [comment]
@marcosbarbero , Got it, thank you.

**Comment by marcosbarbero** [comment]
Np
