### ISSUE TITLE
zuul dynamic filter  doubt

### ISSUE THREAD

**Issue by cgb2** [spring-cloud/spring-cloud-netflix#1238]
how can i use spring-cloud-netflix like https://github.com/Netflix/zuul/tree/1.x/zuul-netflix-webapp ?

**Comment by ryanjbaxter** [comment]
You need to provide more details about what you would like to do.  There is also a sample of how to use Zuul from spring-cloud-netflix in our samples repo.  https://github.com/spring-cloud-samples/zuul-server

**Comment by cgb2** [comment]
I can use it with .java  filter but not .groovy filter witch can dynamic reload

**Comment by spencergibb** [comment]
we don't currently support the groovy filter loader at the moment. See #223

**Comment by cgb2** [comment]
ok
