### ISSUE TITLE
Dynamically chosen hystrix circuit breaker fallback method based upon observed exception

### ISSUE THREAD

**Issue by ashwgupt** [spring-cloud/spring-cloud-netflix#1239]
Posting this question here, as it may appeal to be an enhancement if not available already.

Is it possible to declare and use a strategy around which fallback method to use for a HystrixCommand protected method?

The need is such that, I can decide what fallback method to be used based upon exception been observed.

If the `@HystrixCommand` can take a map of 'exception:fallback' method as set of rules for deciding fallback point, it can solve the purpose.

**Comment by ryanjbaxter** [comment]
There is discussion of something similar when using Feign and Hystrix in #1117

**Comment by ashwgupt** [comment]
Thanks @ryanjbaxter for pointing this out. 

However is there no possibility to have similar capability for a non-feign client app?

**Comment by ryanjbaxter** [comment]
I guess that question should be posed in the Netflix OSS Hystrix repo.  I would suppose something similar would be possible though.

**Comment by ashwgupt** [comment]
Sure, I've posted it there as well.

**Comment by ryanjbaxter** [comment]
Great would be nice to provide a link to the issue here as well
