### ISSUE TITLE
MetricsInterceptorConfiguration modifies an object outside his world

### ISSUE THREAD

**Issue by libetl** [spring-cloud/spring-cloud-netflix#1240]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics/MetricsInterceptorConfiguration.java#L100

when the config post processes the bean creation, it modifies the state of my interceptors list.
In my case, I have made a `restTemplate.setInterceptors(Arrays.asList(myInterceptor))`

In that case, it does not work,  because `Arrays.asList` builds an unmodifiable list.

As a result, I get an `UnsupportedOperationException`, because the stackTrace tries to call `AbstractList.add`

How can I deal with that ?

Thank you for your help.

**Comment by libetl** [comment]
I would recommend to recreate the list completely and to append the new interceptor to the newly built list.

**Comment by spencergibb** [comment]
Pull requests welcome.

**Comment by libetl** [comment]
mmmh. Not at work. Later.

**Comment by libetl** [comment]
Not sure if the quality is enough for your project. Haven't read the guidelines yet.

**Comment by shanman190** [comment]
1.1.x also suffers from this issue
