### ISSUE TITLE
Zuul Route Retry Logic with Eureka Instance

### ISSUE THREAD

**Issue by huhuhong** [spring-cloud/spring-cloud-netflix#1248]
I just curious scenario as below:
1. A Eureka Server with 1 App- X with 2 Instance 
2. A Zuul Gateway route request to App- X 

What if one of the App- X instance was terminate/down, but Eureka Server is only remove the failed instance after 1 minutes. 

1. During this 1 minute period, 
will Eureka Server return the Failed Instance to Zuul Gateway? 

2. If yes, the request will be failed and a retry mechanism will kick in. 
Will Zuul Gateway continue retry with the Failed Instance or Active Instance?

**Comment by ryanjbaxter** [comment]
1. The Eureka client caches the list of services and instances, the down instance will only be removed once the client refreshes the list (and that service is still down when that happens)
2.  It is actually the Ribbon integration which in Zuul which is performing the retries.  I did not see anything in the way of documentation on what the default retry logic is, only that you can customize it. I believe however it will continue to try to reach the down service until that service is no longer in the list from Eureka.

**Comment by huhuhong** [comment]
Thanks.


1. Does "ribbon.ServerListRefreshInterval" determine the time for client to refresh its cache list/instance?
2.  What's the different between "MaxAutoRetries" vs "MaxAutoRetriesNextServer"?

```
ribbon:
    ReadTimeout: 100000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
```

**Comment by ryanjbaxter** [comment]
See https://github.com/Netflix/ribbon/wiki/Getting-Started for descriptions

**Comment by huhuhong** [comment]
Thanks for the link, but does Server mean another instance under the same application or another eureka server?

**Comment by ryanjbaxter** [comment]
Another application instance
