### ISSUE TITLE
Add ability to configure Hystrix command name in Feign (@FeignClient interface) like in @HystrixCommand(commandKey="...")

### ISSUE THREAD

**Issue by apischan** [spring-cloud/spring-cloud-netflix#1256]
The case:
I have `@FeignCommand` interface like this:

```
@FeignClient("adjective-generator")
public interface AdjectiveClient extends WordClient {
    @RequestMapping(method = RequestMethod.GET, value = "/")
    Word getWord();
}
```

It registers in HystrixDashboard with `getWord` name. But I would like to change and that's why:

Suppose that near `AdjectiveClient` inteface (above) I have another interface (or even 4 more similar interfaces (5 in total) which will be needed in further explanation of problem):
```
@FeignClient("noun-generator")
public interface NounClient extends WordClient {
    @RequestMapping(method = RequestMethod.GET, value = "/")
    Word getWord();
}
```

Now as you see all of them inherits common `WordClient` inteface with the method `getWord`.

So and here is the problem: Hystrix think that this is the same command with name `getWord` (even if not to inherit from common interface). Actually we have 5 commands but Hystrix think that it is only 1 `getWord`.

Now suppose that 4 services are down and just one of them is working. Percentage of failure will be ~80% in case if we calling all 5 services in one request. So Hystrix will think that command is dead and will open "circuit breaker".

What we have now: we have 1 live service and 4 dead. But Hystrix think that all of them are dead!

**Comment by spencergibb** [comment]
Already working on it upstream https://github.com/OpenFeign/feign/issues/434

**Comment by asarkar** [comment]
@spencergibb @ryanjbaxter https://github.com/OpenFeign/feign/issues/434 is now closed. What's the group key and command key used by default by Feign now? I suppose it would be a good thing to add to the docs, which I'll be happy to do.

**Comment by yair-segal** [comment]
To add to @asarkar comment - if the method takes parameters, then the key will include the parameters types. For example, for a method that takes two String parameters, the key would be `SimpleClassName#methodName(String,String)`
