### ISSUE TITLE
Eureka status change events

### ISSUE THREAD

**Issue by idobarash** [spring-cloud/spring-cloud-netflix#1258]
Lets say I have 5 instances registered to one application. Now, I kill one instance. Eureka removes it form the list.

Now I'd like to invoke a listener in all other 4 servers - I want them to perform logic and handle the fifth server roles.

Is it possible?

Tried  @EventListener with EurekaEvent or with StatusChangeEvent. didn't work.

I use spring-cloud-eureka.

**Comment by spencergibb** [comment]
What kind of logic are you wanting to do? This is where ribbon is very useful. When the local cache is updated a `HeartbeatEvent` is published, but not much information is there. Eureka doesn't provide a push model.

**Comment by daniellavoie** [comment]
I personally think Spring Cloud Cluster with leader election would be a good candidate for this kind of use case. In case of a leader going down, the newest elected leader would received a notification allowing you to launch some special processing.

**Comment by spencergibb** [comment]
Spring Cloud Cluster is being deprecated. The functionality there was moved to Spring Integration. Besides that, what event would the leader listen for? Eureka doesn't provide events like that.

**Comment by daniellavoie** [comment]
Ah, thanks for the info ! I am on the same page than you about Eureka not providing events. I consider that the leader election event provided by Spring Cloud Cluster could be an answer to isolating some specific logic that other instances should not run.

**Comment by spencergibb** [comment]
Closing in favor of SI leader election functionality.
