### ISSUE TITLE
Appendix with common properties 

### ISSUE THREAD

**Issue by jansyk13** [spring-cloud/spring-cloud-netflix#1263]
Classic spring boot has [this](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html). It would be cool if there was something like this for spring cloud or just spring cloud netflix.

I know that there is a lot of 3rd party stuff and it should be documented by them, but some common stuff at one place would be nice. Many issues and threads on Stackoverflow are duplicates, having one place could help.

**Comment by dsyer** [comment]
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_appendix_compendium_of_configuration_properties

**Comment by dsyer** [comment]
The third party stuff is impossible to document completely. If you want to add some common ones, go ahead and send pull requests.
