### ISSUE TITLE
Zuul proxy didn't forward header

### ISSUE THREAD

**Issue by mgorka92** [spring-cloud/spring-cloud-netflix#1264]
Hi, 

Why zuul proxy didn't forward header: Authorization. One of my micro services need this? My proxy doesn't have included spring-security.

**Comment by spencergibb** [comment]
Please see the documentation on sensitive headers https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#cookies-and-sensitive-headers

**Comment by mgorka92** [comment]
Thx, it's working.
