### ISSUE TITLE
Does eureka server support server-side load balance strategy?

### ISSUE THREAD

**Issue by killjason** [spring-cloud/spring-cloud-netflix#1265]
As I know, Ribbon supports client-side load balance strategy,Does eureka server support server-side load balance strategy?

**Comment by daniellavoie** [comment]
Eureka is a service registry. It is simple phone book. It doesn't involve any load balancing at all. If you want to avoid clients to implement a load balancing strategy (like Ribbon does) you can proxy your services will Zuul who would act as a Load Balancing (using Ribbon and a Eureka Client).
