### ISSUE TITLE
Zuul routing config - it didn't work to override !

### ISSUE THREAD

**Issue by panshaobinSB** [spring-cloud/spring-cloud-netflix#1266]
I tried to config this , but it didn't work to override , when i visit 'http://localhost:5555/xxx/third/add' i want the config `/xxx/third/**` will override `/xxx/**`,
but it always routes to 'http://localhost:2221/'

```
zuul.routes.third.path=/xxx/third/**
zuul.routes.third.url=http://localhost:3333/

zuul.routes.legacy.path=/xxx/**
zuul.routes.legacy.url=http://localhost:2221/
```

but if i change to the config below , it's ok . I don't know how to config now.

```
zuul.routes.third.path=/third/**
zuul.routes.third.url=http://localhost:3333/

zuul.routes.legacy.path=/**
zuul.routes.legacy.url=http://localhost:2221/
```

**Comment by dsyer** [comment]
That should work. Can you create a simple sample (e.g. with loop back to the local server) that shows the problem?

**Comment by panshaobinSB** [comment]
my sample is:
Application.java
`import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.cloud.client.SpringCloudApplication;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@EnableZuulProxy
@SpringCloudApplication
@RestController
public class Application{
	
	@RequestMapping("/secondLocal")
	public String second(@RequestParam(required = false) String value) {
		return "SECOND" + (value == null ? "" : " " + value) + "!";
	}
	
	@RequestMapping("/legacyLocal")
	public String legacy(@RequestParam(required = false) String value) {
		return "LEGACY" + (value == null ? "" : " " + value) + "!";
	}

	public static void main(String[] args) {
		new SpringApplicationBuilder(Application.class).web(true).run(args);
	}
	
}
`
application.properties

`spring.application.name=cloud-api-gateway
server.port=5555

ribbon.eureka.enabled=false

zuul.routes.second.path=/legacy/second/**
zuul.routes.second.url=forward:/secondLocal

zuul.routes.legacy.path=/legacy/**
zuul.routes.legacy.url=http://projects.spring.io/spring-cloud/

`
pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.didispace</groupId>
	<artifactId>cloud-api-gateway-B</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>cloud-api-gateway-B</name>
	<description>Spring Cloud project</description>

	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-starter-parent</artifactId>
		<version>Brixton.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
		<defaultGoal>compile</defaultGoal>
	</build>

</project>`

@dsyer 
when i visit url like 'http://localhost:5555/legacy' ,it routes to 'http://projects.spring.io/spring-cloud/';
when i visit url like 'http://localhost:5555/legacy/second', it's 404, but i have config the 'forward:/secondLocal',  it didn't forward.
when i visit url like 'http://localhost:5555/legacy/second/add',it's 404 too. Where is the problem? Did i config something wrong?

**Comment by spencergibb** [comment]
@panshaobinSB triple backticks are what you use for codeblocks

**Comment by spencergibb** [comment]
the 404 is actually sent by spring.io. If you look at actuator `/routes` I see
```
{
    "/legacy/**": "http://projects.spring.io/spring-cloud/",
    "/legacy/second/**": "forward:/secondLocal"
}
```
Which is putting the base route first, so `/legacy/second/**` is never getting reached. Investigating why.

**Comment by spencergibb** [comment]
I believe map ordering with properties files isn't observed (@dsyer or @wilkinsona can you confirm?)

Using a yml file fixed this for me:
```
spring.application.name: cloud-api-gateway
server.port: 5555

ribbon.eureka.enabled: false

zuul.routes:
  second:
    path: legacy/second/**
    url: forward:/secondLocal

  legacy:
    path: legacy/**
    url: http://projects.spring.io/spring-cloud/
```

**Comment by panshaobinSB** [comment]
thanks @spencergibb , @dsyer, it's work!
