### ISSUE TITLE
Servo: commons-lang:commons-lang required but not listed in pom.xml dependencies

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1268]
`org.springframework.cloud.netflix.metrics.servo.DimensionalServoMetricNaming` requires `commons-lang:commons-lang` but that dependency is not listed in pom.xml

This is causing issue when using the Servo integration features only.

**Comment by dsyer** [comment]
What is the issue exactly?

**Comment by jkschneider** [comment]
`commons-lang` was only on the classpath as a result of an optional dependency on `commons-configuration` and so this class is a potential runtime problem. Thanks for pointing that out @brenuart.
