### ISSUE TITLE
Support for org.springframework.web.multipart.MultipartFile in @FeingClient

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#1274]
Does `@FeignClient` support `org.springframework.web.multipart.MultipartFile` as method parameter?

**Comment by spencergibb** [comment]
No it does not.

**Comment by tjuchniewicz** [comment]
OK. Can't implement everything but my teammates expect to have all functions when moving from old approach (`RestTemplate` probably) to Spring Cloud. 

My suggestion will be to use in specified cases `RestTemplate` + `@HystrixCommand` + `LoadBalancerClient`

Any other features from `@FeignClient` to remember?

**Comment by spencergibb** [comment]
>  my teammates expect to have all functions when moving from old approach (RestTemplate probably) to Spring Cloud

This is why I regret using spring annotations for feign clients.

**Comment by tjuchniewicz** [comment]
There is special encoder for `multipart/form-data` content-type prepared by @xxlabaza here: [feign-form](https://github.com/xxlabaza/feign-form). 

I will try to use it with `@FeignClient`.

**Comment by tjuchniewicz** [comment]
[feign-form](https://github.com/xxlabaza/feign-form) does not support @FeignClient but my fork does: https://github.com/ebjwc/feign-form/tree/spring-cloud-netflix-1274

**Comment by tjuchniewicz** [comment]
Feature is more related to [OpenFeign](https://github.com/OpenFeign/feign) project.

Closing.
