### ISSUE TITLE
About header of using FeignClient

### ISSUE THREAD

**Issue by wangdh1** [spring-cloud/spring-cloud-netflix#1279]
When I use FeignClient to call other server,how can I set the header?

**Comment by daniellavoie** [comment]
Go for a Feign Interceptor. Checkout the reference doc. It works quite simply.

**Comment by ryanjbaxter** [comment]
More specifically see the section on [RequestInterceptors](https://github.com/OpenFeign/feign#request-interceptors) in Feign and the section on [Feign configuration](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#spring-cloud-feign-overriding-defaults) in Spring Cloud.
