### ISSUE TITLE
Turbine stream with consul service discovery doesn't aggregate service

### ISSUE THREAD

**Issue by sokie** [spring-cloud/spring-cloud-netflix#1280]
When using consul as a service discovery, the turbine stream doesn't aggregate services and instead shows the services separated by ID.
Example **correct**: 
Here we have the a service reporting 318 hosts.
[correct](https://raw.githubusercontent.com/wiki/Netflix/Hystrix/images/dashboard-example-open-circuit-640.png)
With consul, we have the same service separated by instanceId:
[wrong](https://i.imgur.com/inPsYwJ.png) ( this 2 should be aggregated )

The problem might be that turbine flattens by instanceId, but you can't have instead of service name?

**Comment by sokie** [comment]
So I don't know where the problem actually is,
if it's the rabbit stream from hystrix or if it is hystrix.
After debugging a little more turbine, this is the instance data I receive to the StreamAggregator.
```
type" -> "HystrixCommand"
name" -> "ping-client-aaecb19b04e00dc9b6c6c18cd919214e.ping"
group" -> "PingController"
instanceId" -> "ping-client:0"
InstanceKey" -> "InstanceKey=>ping-client:0"
TypeAndName" -> "TypeAndName=>HystrixCommand_ping-client-aaecb19b04e00dc9b6c6c18cd919214e.ping"
reportingHosts" -> "1"
```

So the problem here is the name! It uses the spring instance id + hystrix command as the name!

**Comment by ryanjbaxter** [comment]
The answer might depend on how the `HystrixCommands` are being created in your application, are they created using `@HystrixCommand`, are they from `FeignClients`, are they from Zuul routes?

**Comment by sokie** [comment]
For now they're @HystrixCommand annotations

**Comment by ryanjbaxter** [comment]
Try setting `commandKey` as shown in the example here https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-javanica#hystrix-command

**Comment by spencergibb** [comment]
Have you followed the documentation? https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc#hystrix-metrics-aggregation-with-turbine-and-consul

What does your configuration look like?

**Comment by sokie** [comment]
@ryanjbaxter I already investigated that, and commandKey does not change anything.
@spencergibb My services use consul for discovery, but hystrix stream( rabbitmq) for turbine aggregation. 
@spencergibb setting hystrix.stream.queue.prefixMetricName=false removes the id part from the name, which is good, but since **id**("id":"ping-client:0" for both instead of correct id like"ping-client-592138fc403ce0368e7aeb1d77782869" )  is wrong turbine just flickers through the metrics.

**Comment by spencergibb** [comment]
The context id is set by boot see https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/ContextIdApplicationContextInitializer.java

**Comment by sokie** [comment]
I see. 
I will close this since i got my answers.
