### ISSUE TITLE
zuul does not respect the ribbon configuration of OkToRetryOnAllOperations and MaxAutoRetriesNextServer

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#1283]
We are now at brixton.sr4 and facing a new special unwanted effect.
A client issues one get request to an micro-service proxied by zuul. This micro-service calls (by post) another micro-service  which is a bit slow, so that the readtimeout will be reached. The result is that the micro-service in the middle gets about 10 get requests, much more then expected. And the service in the middle doubles the amount of requests. Expected were no retries at all because these secondary requests are posts.
Our configuration:
-     ribbon.MaxAutoRetries=0
-     ribbon.MaxAutoRetriesNextServer=2
-     ribbon.OkToRetryOnAllOperations=false
-     feign.hystrix.enabled=false
-     hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=15000
Are any ideas out there, what can we do to get it back working?
Thanx

**Comment by ryanjbaxter** [comment]
This sounds like you were not seeing this issue in previous Brixton releases?  Exactly what are you expecting to happen?  You are disabling Hystrix so the circuit breakers that Zuul would normally provide around the proxied requests are not there and won't open.

**Comment by LutzStrobel** [comment]
Sorry, but what iisue do you mean. Usally I use google to find solutions for problems. But if I try to find something for zuul and ribbon loadbalancing - I´m not successful.
So it would be nice if you could open my eyes;).

**Comment by ryanjbaxter** [comment]
From your original comment

> We are now at brixton.sr4 and facing a new special unwanted effect.

Does this mean you were using an earlier version of Brixton and not seeing this issue?

**Comment by LutzStrobel** [comment]
Shortly we upgraded from 1.0.0.RELEASE to brixton.sr4 and we didn´t see this issue before.
We had to disable hystrix for the feign clients because we have to transfer custom http headers by feign RequestInterceptors.
But I think not the issue is interesting but the solution for that.  Do you mean there is a solution for that? The I would appreciate any help.
Thanx

**Comment by ryanjbaxter** [comment]
Can you provide a set of projects and instructions on how to reproduce the problem?

**Comment by LutzStrobel** [comment]
No currently  I dont have sample projects to reproduce. I analyze the behavior in our test environment.
What I expect is that zuul and the other feignclients repect the ribbon configuration given above. This means in case of an error:

- For get requests do not retry the same server and two times the next server . 

- For post requests do not retry at all.

Are theese properties valid for the configuration (feign.hystrix=false)? Within the stacktraces I saw no ribbon classes at all, but a lot of hystrix stuff.

**Comment by LutzStrobel** [comment]
At least for the wrong retries between the micro-services I have a first result:
The class com.netflix.loadbalancer.reactive.LoadBalancerCommand contains a method

      private Func2<Integer, Throwable, Boolean> retryPolicy(final int maxRetrys, final boolean same).
...
                if (**tryCount** > maxRetrys) {
                    return false;
                }
                
The value of tryCount is always one and so the retrying does not end.
I think this should be a bug, shouldnt it?

**Comment by LutzStrobel** [comment]
## Steps to reproduce

* zuul + eureka-server + 2 simple spring boot apps<br />
one (the last service in the call chain) has a method like this:

```
    @RequestMapping(
            method = {RequestMethod.POST},
            value = {"/hello"}
    )
    public String hello()  {
        System.out.println("alive");
        try {
            Thread.currentThread().sleep(40000);// just to simulate the slow method
        } catch (InterruptedException e) {
        }
        return "hello example";
    }

```
the first service has a method like this:
```
    @RequestMapping(value = "/hello")
    public String hello(){
        System.out.println("alive");
        return exampleService.hello();
    }

```
This first service gets a ribbon.ReadTimeout=35000
Zuul has a ribbon.ReadTimeout=30000
Other ribbon and hystrix properties are:
ribbon.MaxAutoRetries=0
ribbon.MaxAutoRetriesNextServer=1
ribbon.OkToRetryOnAllOperations=false
feign.hystrix.enabled=false # required because we have to supply custom http headers to the following serices
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=15000
hystrix.command.default.fallback.enabled=false
hystrix.command.default.circuitBreaker.enabled=false

## What I expect:
Zuul does not retry because there is only one instance of the first service with the get operation and ribbon.MaxAutoRetries=0,
The first service calls the second one with the post request only once because ribbon.OkToRetryOnAllOperations=false.
What I get with the timeout configuration is:  
three requests from zuul to the first service and 15 requests from the first to the second service.

I assume that the count of the retry attempt is the cause for this behavior.

**Comment by ryanjbaxter** [comment]
@LutzStrobel thanks for all the additional details, I will look into this more and report back!

**Comment by ryanjbaxter** [comment]
@LutzStrobel can you provide more details on how `exampleService` is implemented in your second code snippet?  Is that a `FeignClient`, is it using an `@LoadBalanced` `RestTemplate`?

**Comment by LutzStrobel** [comment]
Sorry, I forgot: here is the ExampleService interface definition.
```
@FeignClient("example")
public interface ExampleService {
    @RequestMapping(
            method = {RequestMethod.POST},
            value = {"/hello"}
    )
    String hello();
}

```

**Comment by ryanjbaxter** [comment]
OK after some investigation and trying to reproduce the problem it is safe to say our retry logic is anything but simple to understand.  Everything I am about to say applies when you are using Spring Cloud Brixton....

In the scenario you describe we have several layers of retry logic happening.

The first layer of retry logic is occuring at the `FeignClient` level.  `FeignClients` have their own retry logic which is separate from the Ribbon retry logic.  The default retry logic for FeignClients is implemented in [Retryer.Default](https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Retryer.java#L45).  The default retryer will retry the request 5 times.  That is why for each request made to this mid-tier service causes 5 retries to the service at the end of the chain.  Since `FeignClients` have their own retry logic none of the `ribbon.*` properties you set will have any effect on the feign client.  The `ribbon.OkToRetryOnAllOperations` property may have some impact on FeignClients but only for GET requests made by the `FeignClient` and only on non-connection related exceptions.  (see https://github.com/spring-cloud/spring-cloud-netflix/blob/1.1.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/ribbon/FeignLoadBalancer.java#L83)

In order to customize the retry logic for FeignClients you need to override the configuration of the client and provide your own `Retryer`bean.  More information on how to override the configuration for FeignClients can be found [here](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-overriding-defaults).

The second layer of retry logic is at the Zuul proxy.  The Zuul proxy will retry requests if configured to do so

```
zuul:
  routes:
    middle:
      retryable: true
```
The Zuul proxy does use the ribbon retry logic, so if `retryable` is set to true than the various `ribbon.*` properties will effect the Zuul retry logic.

If you have other questions, let me know.

**Comment by LutzStrobel** [comment]
Sorry for the delay, but I´m wasd ill with a broken leg.

Related to the FeignClient loadbalancing, I think your are not right.  The given properties
```
example.ribbon.MaxAutoRetries=4
example.ribbon.MaxAutoRetriesNextServer=1
example.ribbon.OkToRetryOnAllOperations=false

```
will be used within the LoadBalancerCommand as described above, because there is a RequestSpecificRetryHandler. I had a debugging session on this topic with breakpoint at:
```
1) LoadBalancerCommand:retryPolicy:240
2) LoadBalancerCommand:submit:271
3) LoadBalancerCommand:submit:336
4) LoadBalancerCommand:submit:342

```
At the first breakpoint you can see that the tryCount variable will never be incremented. And I think this should not be right.
It looks like that the OperatorRetryWithPredicate will any time created new  within the call:
```
LoadBalancerCommand:submit:343 -->  o = o.retry(retryPolicy(maxRetrysNext, false));

Observable:7459 -->   public final Observable<T> retry(Func2<Integer, Throwable, Boolean> predicate) {
        return nest().lift(new OperatorRetryWithPredicate<T>(predicate));
    }

```
This way the AtomicInteger "attempts" of the "OperatorRetryWithPredicate" starts any time at zero.

Related to the zuul loadbalancing I haven´t debugged so far, but I´m sure that we tested it at the time we introduced zuul. I´m relatively sure the the restclient of zuul uses a RequestSpecificRetryHandler and should consider the ribbon loadbalancing properties

Maybe you can have a look  at this.

**Comment by ryanjbaxter** [comment]
Yes you are correct.  What I am trying to convey is that when you have a request that goes through Zuul to a service that is using Feign to call another service there are several levels of retry logic involved.  Feign clients specifying a service id will use ribbon.  Ribbon has some retry logic built into it.  Feign also has retry logic as part of its feature set.  So in the case of a timeout exception Riboon will retry the request and one it gives up the timeout exception will be propagated up to Feign which will also retry the request, starting the whole process over again.  

If the request is going through Zuul than Zuul's use of Ribbon can also cause a number of retries.

What I would suggest is to only use one set of retry logic, so you need to disable the other 2.  You can disable retry logic at the Zuul layer by setting `zuul.retryable` to `false`.  You can disable retry logic with ribbon by setting `ribbon.okToRetryOnAllErrors` to false.  For Feign you can use Retryer.NEVER_RETRY in your Feign configuration.  

For further details you probably want to follow #1290 and #1295.  We will simplify things in #1295.

**Comment by spencergibb** [comment]
@LutzStrobel All of your breakpoints (as far as I can tell) are in upstream Netflix classes. Do you have a suggestion that we can take action on?

**Comment by LutzStrobel** [comment]
@spencergibb Sorry, but until now I had the imagination, that the spring-cloud team also maintains the netflix stuff.
If not,  I have to open an issue in the netflix ribbon project? What to do? I dont know, but maybe it is a good idea to ask @elandau or Allan Wang from that team. All the changes in LoadBalancerCommand  were made by @elandau. And a lot of them had to do with the retry logic. He could be the best oneto fix the issue.
I think it is a very good idea to unify the load balancing logic. I had always the feeling: it is "kraut und rüben". But I think we should not wait until the discussion is ready and fix the bug in the meantime.
Thanx

**Comment by ryanjbaxter** [comment]
No we do not maintain the Netflix projects (we do contribute at times).  Just open an issue in https://github.com/Netflix/ribbon.
