### ISSUE TITLE
Zuul behind a proxy over HTTPS/SSL sends incorrect headers

### ISSUE THREAD

**Issue by cesartl** [spring-cloud/spring-cloud-netflix#1286]
I have an AWS `Elastic Load Balancer` with the certificates for my domain and which terminates the `SSL` traffic. The `ELB` has a listener on the `https` port and forwards it as `http` to `Zuul`.

When I use `Spring Boot HATEOAS`, Zuul will replace the links with the correct address but with `http` instead of `https`:

    "_links": {
      "self": {
        "href": "http://my.domain.com:80/rest/foo/bar"
      }
    }

but what I want is:

    "_links": {
      "self": {
        "href": "https://my.domain.com/rest/foo/bar"
      }
    }

The request that generates this response is made over `https`

Because `Zuul` is behind the ELB I'm guessing it cannot know that it should receive traffic through https.

Is there a way to tell `Zuul` to replace links with `https` even though it receives un-encrypted traffic through `http`?

I guess an alternative is to deploy `Zuul` with `https` with a self-signed certificate but I'd rather ovoid this complication if I can.

I checked the headers forwarded by my ELB:

    'host': 'my.domain.com'
    'x-forwarded-proto': 'https'

Shouldn't the HATEOAS module pick these headers up to reconstruct the request?

PS: Tried with Spring Cloud BRIXTON.SR4

**Comment by spencergibb** [comment]
Zuul doesn't replace any links. Zuul is aware of proxy headers that it passes downstream. Does zuul pass `host` and `x-forwarded-proto` on correctly downstream?

**Comment by cesartl** [comment]
From Zuul I'm getting the following headers:

    x-forwarded-proto: http
    x-forwarded-port: 80
    x-forwarded-for: x.x.x.x, x.x.x.x
    x-forwarded-host: my.domain.com

My ELB is receiving `https` traffic but serving `http` traffic to Zuul. I did some research and it seems to be a common practice. That encrypted traffic is not really necessary within a private network. 

Here Zuul is rightly receiving traffic from http, but it does receive a `'x-forwarded-proto': 'https'` header.

Is it a flaw in Zuul or Spring or a flaw in the architecture?

**Comment by ryanjbaxter** [comment]
What are the other headers Zuul is receiving from the ELB?

**Comment by cesartl** [comment]
Zuul receives:
 
    'host': 'my.domain.com, '
    'authorization': 'Bearer xxx'
    'content-type': 'application/json'
    'cookie': 'JSESSIONID.xxx=yyy; JSESSIONID.xxx=yyy'
    'x-forwarded-for': 'x.x.x.x'
    'x-forwarded-port': '443'
    'x-forwarded-proto': 'https'
    'connection': 'keep-alive'

and Zuul sends:

    x-forwarded-proto: http
    x-forwarded-port: 80
    x-forwarded-for: x.x.x.x, x.x.x.x
    x-forwarded-host: my.domain.com

**Comment by spencergibb** [comment]
@cesartl you can certainly write a filter that fixes the `x-forwarded-*` headers as a workaround. It would need to be a `pre` filter and run after `PreDecorationFilter`.

**Comment by spencergibb** [comment]
So if a proxy already sends `x-forwarded-proto` and `x-forwarded-port` we should use those. Also @cesartl when you say `x-forwarded-for: x.x.x.x, x.x.x.x` is `x.x.x.x` really duplicated? If so, that should be fixed as well.

**Comment by cesartl** [comment]
ok that makes sense.

No they are not duplicated sorry. So that looks good.

**Comment by cesartl** [comment]
@spencergibb I followed your suggestion and added the following filter:

    new ZuulFilter() {
            @Override
            public String filterType() {
                return "pre";
            }

            @Override
            public int filterOrder() {
                return 6; //PreDecorationFilter=5 + 1
            }

            @Override
            public boolean shouldFilter() {
                return true;
            }

            @Override
            public Object run() {
                RequestContext ctx = RequestContext.getCurrentContext();
                log.info(String.format("Before filter ['%s': '%s', '%s': '%s']",
                        ZuulHeaders.X_FORWARDED_PROTO.toLowerCase(),
                        ctx.getZuulRequestHeaders().get(ZuulHeaders.X_FORWARDED_PROTO.toLowerCase()),
                        "X-Forwarded-Port",
                        ctx.getZuulRequestHeaders().get("x-forwarded-port")));


                final String originalXForwardedProto = ctx.getRequest().getHeader(ZuulHeaders.X_FORWARDED_PROTO.toLowerCase());
                final String originalXForwardedPort = ctx.getRequest().getHeader("x-forwarded-port");

                if (!StringUtils.isEmpty(originalXForwardedProto)) {
                    ctx.addZuulRequestHeader(ZuulHeaders.X_FORWARDED_PROTO.toLowerCase(), originalXForwardedProto);
                }

                if (!StringUtils.isEmpty(originalXForwardedPort)) {
                    ctx.addZuulRequestHeader("x-forwarded-port", originalXForwardedPort);
                }

                log.info(String.format("After filter ['%s': '%s', '%s': '%s']",
                        ZuulHeaders.X_FORWARDED_PROTO.toLowerCase(),
                        ctx.getZuulRequestHeaders().get(ZuulHeaders.X_FORWARDED_PROTO.toLowerCase()),
                        "X-Forwarded-Port",
                        ctx.getZuulRequestHeaders().get("x-forwarded-port")));

                return null;
            }
        };
    }

It seems to work for me, does it make sense though?

**Comment by spencergibb** [comment]
yes

**Comment by cesartl** [comment]
great thanks!

**Comment by dsyer** [comment]
Duplicates #959

**Comment by sbley** [comment]
I had a similar issue and while the custom filter work-around above works I think the PreDecorationFilter should handle these cases itself. I filed a pull request to fix this: #1656
