### ISSUE TITLE
Feign issue in combination with Data REST

### ISSUE THREAD

**Issue by sebastian-sch** [spring-cloud/spring-cloud-netflix#129]
I am using DATA Rest for some of my Controller. Now I include FeignClient and afterwards the DATA Rest Controller doesn’t work anymore.

 This happens only under specific condition. The id must be specified in a superclass (DomainObject) of the domain class (Product) and one variable field from domain class must represent another class (Address).  I create an example to reproduce the problem: https://github.com/sebastian-sch/Demo

When the system starts to refresh the application context with the method AnnotationConfigEmbeddedWebApplicationContext.refresh() the beans for DATA Rest are processed during the registerBeanPostProcessors(beanFactory); while when Feign is not used, the beans are processed during finishBeanFactoryInitialization(beanFactory);

    AbstractApplicationContext
    ...
                    try {
        // Allows post-processing of the bean factory in context subclasses.
        postProcessBeanFactory(beanFactory);

        // Invoke factory processors registered as beans in the context.
        invokeBeanFactoryPostProcessors(beanFactory);

        // Register bean processors that intercept bean creation.
        registerBeanPostProcessors(beanFactory);

        // Initialize message source for this context.
        initMessageSource();

        // Initialize event multicaster for this context.
        initApplicationEventMulticaster();

        // Initialize other special beans in specific context subclasses.
        onRefresh();

        // Check for listener beans and register them.
        registerListeners();

        // Instantiate all remaining (non-lazy-init) singletons.
        finishBeanFactoryInitialization(beanFactory);

        // Last step: publish corresponding event.
        finishRefresh();
      }
        

The MongoMappingContext require the ApplicationEventMulticaster which is not available during registerBeanPostProcessors and the creation of the bean productRepository fails. If the id is directly in the domain object or no field use a class as variable the bean creation for productRepository fails also but the system find the id and it is working.

    MongoMappingContext
        protected E addPersistentEntity(TypeInformation<?> typeInformation) {
     {
     ...
           ReflectionUtils.doWithFields(type, persistentPropertyCreator, PersistentPropertyFilter.INSTANCE);
        ...        
            applicationEventPublisher.publishEvent(new MappingContextEvent<E, P>(this, entity));
        ...        
       }
  
    
    ApplicationEventMulticaster getApplicationEventMulticaster() throws IllegalStateException {
    if (this.applicationEventMulticaster == null) {
      throw new IllegalStateException("ApplicationEventMulticaster not initialized - " +
          "call 'refresh' before multicasting events via the context: " + this);
        }
        return this.applicationEventMulticaster;
      }

I think this is the important line from the stack trace:

    WARN 34253 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Bean creation exception on FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restClient': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: feign.codec.Decoder org.springframework.cloud.netflix.feign.FeignConfiguration.decoder; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignDecoder': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.springframework.boot.autoconfigure.web.HttpMessageConverters org.springframework.cloud.netflix.feign.SpringDecoder.messageConverters; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private final java.util.List org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration.converters; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mappingJackson2HttpMessageConverter' defined in class path resource [org/springframework/boot/autoconfigure/web/HttpMessageConvertersAutoConfiguration$MappingJackson2HttpMessageConverterConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.fasterxml.jackson.databind.ObjectMapper]: : Error creating bean with name 'objectMapper' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.fasterxml.jackson.databind.ObjectMapper]: Factory method 'objectMapper' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceMappings' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.mapping.ResourceMappings]: Factory method 'resourceMappings' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositories' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.repository.support.Repositories]: Factory method 'repositories' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productRepository': Invocation of init method failed; nested exception is java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@49bd54f7: startup date [Fri Jan 02 14:09:46 CET 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@645aa696; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'objectMapper' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.fasterxml.jackson.databind.ObjectMapper]: Factory method 'objectMapper' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceMappings' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.rest.core.mapping.ResourceMappings]: Factory method 'resourceMappings' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repositories' defined in class path resource [org/springframework/boot/autoconfigure/data/rest/RepositoryRestMvcAutoConfiguration$RepositoryRestMvcBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.repository.support.Repositories]: Factory method 'repositories' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productRepository': Invocation of init method failed; nested exception is java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@49bd54f7: startup date [Fri Jan 02 14:09:46 CET 2015]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@645aa696

Sebastian

**Comment by flo-f** [comment]
Thanks for posting and fixing this issue. 
Changing from RC1 to the current build snapshot fixed it for me.

**Comment by sebastian-sch** [comment]
Thanks for the fix, work fine now.
