### ISSUE TITLE
IllegalArgumentException thrown when a + is in a query param and the uri is rewritten to https

### ISSUE THREAD

**Issue by jebeaudet** [spring-cloud/spring-cloud-netflix#1291]
I mentioned the issue in https://github.com/spring-cloud/spring-cloud-netflix/issues/1241 but I was asked to open another issue so here we go.

If your service register with https in eureka, the uri will get rewritten in `RibbonUtils` with `UriComponentsBuilder`.  The problem is this longstanding issue : https://jira.spring.io/browse/SPR-10172 where the `+` sign is somehow not allowed even if it's widely used in the field. I'm not looking to start a debate whether this should be allowed or not but I think we should use another class, or at least give the option to select the URI reconstruction class. We fixed it in https://github.com/coveord/spring-cloud-netflix/commit/a0ac405ac81c0e7d0b7369f8565c8a835a1ce3c9 by using the plain old `URI` class this way : 

```
new URI("https", original.getUserInfo(), original.getHost(),
 				original.getPort(), original.getPath(), original.getQuery(),
 				original.getFragment());
```
Thanks!

**Comment by jebeaudet** [comment]
I forgot to add that I have a fork with a failing test https://github.com/coveord/spring-cloud-netflix/tree/uricomponent-bug

**Comment by spencergibb** [comment]
PR?

**Comment by jebeaudet** [comment]
Yes I'll work on one soon, actually I ran into some problem with the snippet I gave and I think I found a graceful solution.

**Comment by bitsofinfo** [comment]
@jebeaudet related: https://github.com/spring-cloud/spring-cloud-netflix/issues/1245

**Comment by jebeaudet** [comment]
I'm loaded at work and couldn't pull this PR yet, https://github.com/coveord/spring-cloud-netflix/commit/2840e26ee106ad2d43041fe42780f6e3922da5af#diff-088d48f01fc444a884dac6a52674f904R111 should solve it, that's the version we're using internally. I'll try to do this next week.

**Comment by bitsofinfo** [comment]
Looks like this in the latest code might already do it?

https://github.com/spring-cloud/spring-cloud-netflix/blob/43adc84dfdfc33f3be0268e09b193afc82f9bf9a/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/ribbon/FeignLoadBalancer.java#L101

https://github.com/spring-cloud/spring-cloud-netflix/blob/43adc84dfdfc33f3be0268e09b193afc82f9bf9a/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/RibbonUtils.java#L70

**Comment by jebeaudet** [comment]
Yes, this should fix your problem AFAIK. I didn't look at your issue before replying, it's not the same. The problem here is even with the `build(true)`, `UriComponentsBuilder` validates the characters in the coded URI and doesn't like `+` in query params.
