### ISSUE TITLE
Standardize on Spring Retry to replace retry from deprecated ribbon client.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1295]
https://github.com/spring-projects/spring-retry

We could use `RetryTemplate` and standardize across zuul, feign and rest template.

We could probably be backwards compatible with the ribbon configuration for retry.

**Comment by LutzStrobel** [comment]
Sorry, but why do you think opening a new Story is better than fixing the bug in #1283. Not fixing means that we have only "nice weather loadbalancing" and no failover in situations where connect error occurs. The loadbalancing and failover feature was a decision critical feature to select netflix components.
The fact is that at least the loadbalancer command used in for FeignClient respects the ribbon properties, but does not count the retry attempts in the right way. To fix this is possibly lesser effort than a discussion how to change to Spring retry.

**Comment by ryanjbaxter** [comment]
@LutzStrobel the idea is to make retry logic consistent across the various Spring Cloud Netflix components (Feign, Zuul, and Ribbon).  Yes, we could fix each component so they behave correctly, but then we have to maintain them all separately.  Our goal is to have retry logic centralized in Ribbon.

**Comment by spencergibb** [comment]
@LutzStrobel we can do both. We will standardise on Spring Retry. If you think we've closed #1283 prematurely we can talk about it there.

**Comment by Sunrry** [comment]
Is this enhancement merged to Spring Cloud new version ( Camden SR2 currently )?
If not, when can we get this ?
Thanks

**Comment by ryanjbaxter** [comment]
@Sunrry load balanced `RestTemplate`s now use [Spring Retry in Camden SR2](_retrying_failed_requests).  We are working on changes for Feign and Zuul.

**Comment by thofte** [comment]
Hi,

Any update about the support for connection retry in Zuul in Camden release? I am currently evaluating Zuul, integrated with Eureka for service dicovery, for a new spring boot project. However, I discovered that connection retry somehow got broken in Camden Release and I wonder how I can configure connection retry in Zuul...I understand, after reading #1290 that Camden does not support Ribbon retry properties anymore. But does this mean that Zuul integrated with Eureka in Camden doesn't provide connection failover at all???

- Tom

**Comment by spencergibb** [comment]
@thofte you can create a bean of type `RestClientRibbonCommandFactory`, which does have retry, but it has limitations as well (no PATCH support for example).

**Comment by thofte** [comment]
@spencergibb Thanks for the response I will have a look at it. Do you know when Zuul gets proper support for retry? It looks to me if something crucial (retry on connection failures) has been removed, or am I wrong?

**Comment by ryanjbaxter** [comment]
I have a PR I am working on which should be submitted soon.  I am on vacation this week so I am hoping to submit it sometime next week when I get back

**Comment by thofte** [comment]
@ryanjbaxter Can you tell what this PR contains and how it facilitates retry logic in Zuul Camden?

**Comment by thofte** [comment]
@ryanjbaxter I believe I found the answer on my last question in this thread #1633...

**Comment by ryanjbaxter** [comment]
Right that is similar.  Basically by changing the default HTTP client used by Zuul from Brixton to Camden we eliminated the retry logic that was available by default.  My PR will reintroduce this again to Camden.
