### ISSUE TITLE
Feign: Make fallback configurable at runtime

### ISSUE THREAD

**Issue by C-Otto** [spring-cloud/spring-cloud-netflix#1298]
Possibly related to #1117 

Currently, when adding a fallback using `@FeignClient(..., fallback = SomeFallback.class)` I cannot make use of the call context in the actual `SomeFallback` instance which is used when it is called to work as a fallback. As such, I can only specify a fallback with context-insensitive code (most likely returning a constant).

As a motiviation, in my reasoning the client itself should only serve as a technical helper, but it is not concerned with business logic. However, the class making use of the client knows best what a valid fallback could look like - and different usages of the same client most likely have different ideas of suitable fallbacks. As such, this fallback information should be provided to the client (or the framework dealing with fallbacks, e.g. Hystrix/Feign/...).

I tried adding the necessary data as an argument to the method:

```
@RequestMapping("/X/{id}")
X getById(@PathVariable("id") String id, Object dataForFallback);
```

Then, in the implementation of the fallback, I could make use of the `dataForFallback` (which could be a Java 8 `Supplier<X>`).

However, after debugging the `ParameterProcessor` implementations and Feign itself, I realized that each argument either

 - ends up as the body (done by Feign if no HTTP annotation is encountered, as shown above),
 - is put into the path (`PathVariableParameterProcessor` if annotated with `@PathVariable`)
 - is put into a header (`RequestHeaderParameterProcessor` if annotated with `@RequestHeader`)
 - is added as an parameter to the URL (`RequestParamParameterProcessor` if annotated with `@RequestParam`)
 - is a value provided in a form in the body (see below)

The form result is rather surprising. Spring Cloud Netflix implicitly puts everything annotated with `@PathVariable("key")` into a form "key=..." (into the body of the request), if the key does not match any path/header/parameter in the template. This is somewhat reasonable, but causing me troubles in the scenario outlined above.

**Comment by C-Otto** [comment]
For completeness, I figured out a 95% ugly workaround. Sadly, I think this approach is not thread-safe (i.e. causing problems if the setter is invoked twice at nearly the same time for different usages).

```
// usage
@Autowired XClient client;
client.setFallback(X::new);
X x = client.getById("1");
```

```
// definition
@FeignClient(..., fallback = XFallback.class)
public interface XClient {
    @RequestMapping(method = GET, value = "/X/{id}")
    X getById(@PathVariable("id") String id);

    default void setFallback(Supplier<X> fallback) {
        throw null; // trigger fallback execution, i.e. the actual setter in the subclass
    }
}

@Component
public class XFallback implements XClient {
    // TODO multithreading issue?
    private Supplier<X> fallback;

    @Override
    public X getById(String id) {
        return fallback.get();
    }

    public void setFallback(Supplier<X> fallback) {
        this.fallback = fallback;
    }
}
```

 Of course, one could also directly deal with the `XFallback` singleton instance at the cost of having a direct reference to this class.

**Comment by spencergibb** [comment]
I'm still a bit unsure what your asking for. If you don't have full context for a dynamic fallback, maybe the dynamic fallback combined with feign isn't the right thing to be doing. #1117 talks of giving access to the exception, but that is a function of hystrix, just exposing it to the feign client.

**Comment by C-Otto** [comment]
Basically, I want the feign client to behave in various ways (defined by the caller) in case of an error (triggering the fallback).

If this is against the concept of Hystrix' fallback functionality, it's not a thing Feign should fix - especially the Spring part we're dealing with here. But if it should work, I'd love to use it using Spring and Feign.

I agree that #1117 is not that extremely related.

**Comment by spencergibb** [comment]
Not sure how this would fit with feign. All it's parameters are directly related to the http call. Anything beyond using the parameters and exception I think is beyond feign. Building a `HystrixCommand` on your own would be the route I would take. We're also discussing making feign/hystrix integration opt-in rather than opt-out #1277.

**Comment by C-Otto** [comment]
OK, that's fair. Thanks!
