### ISSUE TITLE
When an upstream microservice is unavailable (ex. no servers are up) Zuul sends a 500 Internal Server Error instead of 503 Service Unavailable

### ISSUE THREAD

**Issue by yohanliyanage** [spring-cloud/spring-cloud-netflix#1300]
This is a special case of https://github.com/spring-cloud/spring-cloud-netflix/issues/406. The fix for 406 addresses situations where the upstream microservice sends a 503. However, if the upstream service is completely unavailable, Zuul sends back a 500 error where as ideally it should be a 503 service unavailable. 

In such cases, Ribbon throws a ClientException exception of type 'GENERAL' with the message 'Load balancer does not have available servers for client: XXX', which gets converted to 500 by RibbonRoutingFilter. 

IMO, this should be mapped to more specific 503 service unavailable instead of a generic 500 error so that the downstream services can handle this scenario gracefully. 

[I am using Brixton SR3]

**Comment by FelipeAdorno** [comment]
I'll help in this issue ok @spencergibb?

**Comment by FelipeAdorno** [comment]
I create the issue and PR in Ribbon project to return the SERVICE_UNAVAILABLE when no servers are up. When the PR merged I update the version on spring-netflix project.

**Comment by ryanjbaxter** [comment]
The changes in Ribbon LGTM, but I am not too familiar with that project either.

**Comment by vision-ken** [comment]
@FelipeAdorno 
Is the PR merged?
Could you please tell me about the issue's url in Ribbon project?

**Comment by vision-ken** [comment]
Sorry, I found it above.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
