### ISSUE TITLE
Zuul adds "RibbonCommand" suffix to HystrixCommand

### ISSUE THREAD

**Issue by garciafl** [spring-cloud/spring-cloud-netflix#1308]
According to #329 it seems that a regression occured in [RibbonCommand.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/support/AbstractRibbonCommand.java#L77)

This is annoying when we retrieve command information in the hystrix-dashboard for example or for setting properties.

**Comment by spencergibb** [comment]
Fix on the 1.1.x branch first.
