### ISSUE TITLE
Turbine AMQP aggregator fails to group instance metrics correctly from Hystrix stream

### ISSUE THREAD

**Issue by ogunheper** [spring-cloud/spring-cloud-netflix#131]
__Issue Description & Root Cause:__
When started multiple instances of the same application (either on different hosts with all having the same ${server.port} value, or on a single host with all having different ${server.port} values), Turbine AMQP aggregator aggregates these multiple different Hystrix streams from all instances, however reports them as a single host.

__Root Cause__
Nothing is wrong with the Hystrix stream sender task, or with the turbine aggregator logic. The problem is with the "id" value which is sent by [HystrixStreamTask](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-hystrix-amqp/src/main/java/org/springframework/netflix/hystrix/amqp/HystrixStreamTask.java#L224) class. id is sent by default as the application context id;

    private void addServiceData(JsonGenerator json) throws IOException {
        ServiceInstance localService = discoveryClient.getLocalServiceInstance();
        json.writeObjectFieldStart("origin");
        json.writeStringField("host", localService.getHost());
        json.writeNumberField("port", localService.getPort());
        json.writeStringField("serviceId", localService.getServiceId());
        json.writeStringField("id", context.getId());
        json.writeEndObject();
    }

Multiple instances of an application will have the same id, as default application context id is coming from [ContextIdApplicationContextInitializer](https://github.com/spring-projects/spring-boot/blob/master/spring-boot/src/main/java/org/springframework/boot/context/ContextIdApplicationContextInitializer.java#L91) class, which is ignoring host.

__How to reproduce:__
1. Start up a Rabbit MQ, Eureka server, Hystrix dashboard and a Turbine server.
2. Start two instances of an application on two different hosts, having same ${server.port} values.
3. Open the Turbine stream on the Hystrix dashboard.
4. See that Turbine stream reports hosts as 1 on the dashboard, even if two application instances exists...

__Suggested solution:__
I think there is no need to send application context id in the Hystrix stream, as this is never used except for metrics aggregation. To tell the truth, aggregator is grouping metrics based on instanceId key. If a key named id exists in the stream, this is used as the instanceId. Otherwise, instanceId is derived from serviceId, host and port. This logic resides in the [Aggregator](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine-amqp/src/main/java/org/springframework/cloud/netflix/turbine/amqp/Aggregator.java#L44) class;

    public static Map<String, Object> getPayloadData(Map<String, Object> jsonMap) {
        @SuppressWarnings("unchecked")
		Map<String, Object> origin = (Map<String, Object>) jsonMap.get("origin");

        String instanceId = null;
        if (origin.containsKey("id")) {
            instanceId = origin.get("id").toString();
        }

        if (!StringUtils.hasText(instanceId)) {
            //TODO: instanceid template
            instanceId = origin.get("serviceId")+":"+origin.get("host")+":"+origin.get("port");
        }

        @SuppressWarnings("unchecked")
		Map<String, Object> data = (Map<String, Object>) jsonMap.get("data");

        data.put("instanceId", instanceId);
        return data;
    }

So, removing id will from the stream will have no effect on the aggregation except making it right by using serviceId, host and port.

Suggested solution is tested and approved as working.

Regards,
Ogün

**Comment by ogunheper** [comment]
Pull request is below;
https://github.com/spring-cloud/spring-cloud-netflix/pull/132

Travis build is failing for some reason, but not because of me :)
Ogün

**Comment by spencergibb** [comment]
hmm, I think it's a matter of setting unique id's for each service.  This works in cloud foundry because spring-boot uses the `${vcap.application.instance_id}` as the context id.  I'll take a look.  I'm not convinced I want to merge your pull request.

**Comment by ogunheper** [comment]
Hi Spencer,

Yes, this is definitely a matter of unique id setting for each instance.

This may work well in cloud foundry, but in standalone environment like ours, we have no such settings as ${vcap.application.instance_id} in the environment.

What we went through is the following;
- We got a single Spring Boot application; having ${spring.application.name} & ${spring.profiles.active} configured in the bootstrap.yml file. Let's say these properties have "finance-core-module" and "test" as values respectively.
- We got application properties configured in the application.yml file, located at the Spring configuration server. ${server.port} property resides in this location. This property has 8080 as the value.
- When application starts, context id is initialized as "finance-core-module:test". server.port value is ignored for some reason. It doesn't matter however, as it would make no difference has it not been ignored. This is because the context id doesn't take hostname into consideration. Assume that we have more than one instance of this Spring Boot application running in such an environment. Each will have "finance-core-module:test" as their context ids.
- This result in wrong aggregation results on Turbine, as each instance puts their metrics on the bus with the same id.

I don't know your motivation behind using context id for uniquely identifying an instance. Isn't it more suitable to use a combination of application_name, hostname and port values as the instance id. As an example, this is what Eureka does for identifying an instance uniquely in the first place.

Best regards,
Ogün

**Comment by spencergibb** [comment]
@ogunheper what I'd like is for the sending application to decide what to send.  It's currently hard coded to the application context id.  Would some configuration here work?  Maybe a property that allows you to set that to send and it won't send an id if it's empty.

**Comment by ogunheper** [comment]
@spencergibb 
@dsilahcilar
I would rather have it solved in another way. I think it is the context id that is being generated incorrectly in the first place by Boot, when the application is not running on CloudFoundry. Anyway, I will let Boot guys know about this. 

Thanks and regards.
Ogün
