### ISSUE TITLE
spring-cloud-starter-feign @RequestMapping bug

### ISSUE THREAD

**Issue by tietang** [spring-cloud/spring-cloud-netflix#1316]
**follow code:**

**have a Controller**

```
@RestController
@RequestMapping("/v1/card")
public class IndexApi {

    @PostMapping("balance")
    @ResponseBody
    public Info index() {
        Info.Builder builder = new Info.Builder();
        builder.withDetail("x", 2);
        builder.withDetail("y", 2);
        return builder.build();
    }
}

```

**and have feign client：**

```
@FeignClient(
        name = "card",
        url = "http://localhost:7913",
        fallback = CardFeignClientFallback.class,
        configuration = FeignClientConfiguration.class
)
**@RequestMapping(value = "/v1/card")**
public interface CardFeignClient {

    **@RequestMapping(value = "/balance", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)**
    Info info();

}
```

if @RequestMapping is used on class, when invoke http /v1/card/balance, like this :

```
Content-Type:application/json
**Accept:application/json**

POST http://localhost:7913/v1/card/balance
```
return 404

**but like this:**

```
Content-Type:application/json
POST http://localhost:7913/v1/card/balance
```
It's OK!

**or like this use feign client:**

```

@FeignClient(
        name = "card",
        url = "http://localhost:7913",
        fallback = CardFeignClientFallback.class,
        configuration = FeignClientConfiguration.class
)

public interface CardFeignClient {

    **@RequestMapping(value = "/v1/card/balance", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)**
    Info info();

}

```
and also it's OK.

so, can't use @RequestMapping on class, only used to method.

**Comment by ryanjbaxter** [comment]
So when the `accept` header is sent you get a 404 returned?  Or is there another difference I am missing?

**Comment by tietang** [comment]
Can't exists the follow conditions:

-  spring controller has endpoint /v1/card/balance
-  FeignClient has endpoint /v1/card/balance
-  to use @RequestMapping on `FeignClient` class

**Comment by ryanjbaxter** [comment]
@tietang that does not answer my question

> So when the accept header is sent you get a 404 returned?

**Comment by tietang** [comment]
yes, when the `accept` header is sent you get a 404 returned, if not header`accept`, it's ok.

 the follow 4 conditions is cause to happen 404:
- spring controller has endpoint /v1/card/balance
- FeignClient has endpoint /v1/card/balance
- to use @RequestMapping on FeignClient class
- the `accept` header is sent

**Comment by ryanjbaxter** [comment]
Sounds like your API may be rejecting the the request do to either the presence of the `accept` header or the value of the `accept` header.   You might want to look at making some changes to the API.  It does not sound like there is a problem from a Spring Cloud perspective.

**Comment by tietang** [comment]
if don't use `@RequestMapping` on  `@FeignClient` class , that's ok, whether has `accept` header.

**Comment by ryanjbaxter** [comment]
You said 

> yes, when the accept header is sent you get a 404 returned, if not header accept, it's ok.

If you use a REST Client to make a request to your API including the `accept` header does it return a 404?  Maybe a sample project will help make the problem clearer.
