### ISSUE TITLE
When client have been down (process kill or server down), still not removed from the Eureka

### ISSUE THREAD

**Issue by heyjang** [spring-cloud/spring-cloud-netflix#1322]
client server have been down by disk fault.
but still not removed from eureka server.
It was removed after about seven minutes.

When I killed process in local, the result was same
(for example "kill -9 pid")

How can I check this?

thank you.

#Version Information
spring cloud netflix 1.0.7

#EUREKA Server Properties
<pre><code>
eureka:
  server:
    enableSelfPreservation: true
  instance:
    appname: 3MP-AGW-REGISTRY
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
</code></pre>

#Client Properties
<pre><code>
eureka:
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
</code>
</pre>

**Comment by spencergibb** [comment]
`enableSelfPreservation: true` is the key. Eureka, by default, if 85% of registered instances are no longer sending heartbeats it will not evict them. You should see a warning on the eureka dashboard.

**Comment by spencergibb** [comment]
`enableSelfPreservation: true` is the key. Eureka, by default, if 85% of registered instances are no longer sending heartbeats it will not evict them. You should see a warning on the eureka dashboard.

**Comment by ryanjbaxter** [comment]
Here is a screenshot of what you will see 
<img width="1401" alt="screen shot 2016-09-07 at 2 38 58 pm" src="https://cloud.githubusercontent.com/assets/524254/18324140/dfc2f822-7508-11e6-85a8-090bc559d722.png">

**Comment by heyjang** [comment]
thank you for your answer.

I found "eviction-interval-timer-in-ms"

I set property
<pre><code>
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
</code></pre>

when client server has been down, expired instance was evicted immediately.

Is it okay with this setting? are there any risks?
"eviction-interval-timer-in-ms: 1000"

**Comment by ryanjbaxter** [comment]
I think it is a matter of preference.  It depends on whether you want to see those instances in your dashboard or not.
