### ISSUE TITLE
Turn Off Hystrix functinality

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1326]
I am integrating Hystrix in an application. That application is already in production and we will be testing out hystrix integration work in sandbox before we will push it to production. My question is that is there any way to turn on/off hystrix functionality using some configuration setting?

I mean we have used HystrixCommand and wrapped our api method with this. So we want to turn off this functionality in case any issue occur in production due to this as recently it got some issues due to ThreadPoolSize or maxConcurrentConnections related failure . Which we could find out after major debugging of issue on production. so we want to have feature to disable this in case of such issues so that we do not have any prod down time.

**Comment by spencergibb** [comment]
Yes, see https://github.com/Netflix/Hystrix/wiki/Configuration#circuitBreaker.enabled

**Comment by JagmohanSharma** [comment]
doesn't look like it's  disabling it totally - perhaps just turning off the main features (threadpools, etc etc).

**Comment by spencergibb** [comment]
I can't help with general statements that it doesn't work. Can you share a project that demonstrates the problem?

**Comment by JagmohanSharma** [comment]
This could be achieved using property "spring.cloud.circuit.breaker.enabled". which disabled circuit breaker when we set to false.

it is defined in - 

@Order(Ordered.LOWEST_PRECEDENCE - 100)
public class EnableCircuitBreakerImportSelector extends
              SpringFactoryImportSelector<EnableCircuitBreaker> {
 
       @Override
       protected boolean isEnabled() {
              return new RelaxedPropertyResolver(getEnvironment()).getProperty(
                           "spring.cloud.circuit.breaker.enabled", Boolean.class, Boolean.TRUE);
       }
 
}


But only with property hystrix.command.default.circuitBreaker.enabled to false , it does not disable totally.

**Comment by spencergibb** [comment]
Again `it does not disable totally` isn't very helpful. What is still happening? `spring.cloud.circuit.breaker.enabled` would work further up the stack by not importing the hystrix configuration.

**Comment by wangcanfengxs** [comment]
I integrated feign (using spring-cloud-feign) in my application, but i don't import spring-cloud-hystrix in my application. If I want to disable circuitBreaker, how should I config? using spring.cloud.circuit.breaker.enabled=false or hystrix.command.default.circuitBreaker.enabled=false

**Comment by ryanjbaxter** [comment]
@wangcanfengxs 
```
feign:
  hystrix:
    enabled: false
```
