### ISSUE TITLE
Zuul ignores DELETE request body when SimpleHostRoutingFilter is used

### ISSUE THREAD

**Issue by alenavorozhbieva** [spring-cloud/spring-cloud-netflix#1329]
HttpEntityEnclosingRequestBase class is used only for PUT, PATCH and POST methods, not for DELETE. Please use it for DELETE method too

**Comment by spencergibb** [comment]
Duplicate of #949

**Comment by spencergibb** [comment]
I missed `SimpleHostRoutingFilter` which is different.

**Comment by spencergibb** [comment]
Unfortunately `HttpDelete` does not extend `HttpEntityEnclosingRequestBase`. The only way to do this is similar to #949 which is to provide alternative clients for `SimpleHostRoutingFilter`.

**Comment by spencergibb** [comment]
See #1219

**Comment by alenavorozhbieva** [comment]
> Unfortunately HttpDelete does not extend HttpEntityEnclosingRequestBase. The only way to do this is similar to #949 which is to provide alternative clients for SimpleHostRoutingFilter.

Can you do something like this in forward method:

```
case "DELETE":
                BasicHttpEntityEnclosingRequest entityRequest = new BasicHttpEntityEnclosingRequest(verb, uri + this.helper.getQueryString(params));
                httpRequest = entityRequest;
                entityRequest.setEntity(entity);
                break;
``` 
?

PS: I don't undestand how alternative clients for SimpleHostRoutingFilter can solve my problem

**Comment by spencergibb** [comment]
@alenavorozhbieva in the long run, providing an option other than apache is a goal since we provide it for the load balanced routes. The apache client should also not use deprecated APIs. How about a PR?

**Comment by spencergibb** [comment]
whoops

**Comment by alenavorozhbieva** [comment]
I have created PR: https://github.com/spring-cloud/spring-cloud-netflix/pull/1339
