### ISSUE TITLE
Default maxSemaphores for all routes

### ISSUE THREAD

**Issue by dshin192** [spring-cloud/spring-cloud-netflix#1332]
I see from a previous issue that the way to set `maxSemaphores` for spring-cloud-netflix is to set `zuul.eureka.<serviceId>.semaphore.maxSemaphores` but I am using consul instead of eureka. I've tried setting this with `zuul.eureka.default.semaphore.maxSemaphores: 500` but this didn't work. What is the correct property to set default `maxSemaphores` for all commands? Will it still work even if I am using consul?

**Comment by ryanjbaxter** [comment]
Just looking at the code, it doesn't look like `maxSemaphores` would be used outside Zuul.  Maybe @spencergibb can comment if there is something equivalent when using Consul.

**Comment by spencergibb** [comment]
The property `zuul.semaphore.maxSemaphores` was added in 7929dfec0f1db34cc91785e9d8f4690f2cd143d7 but never used, fixing.
