### ISSUE TITLE
Add ability to discover zuul proxy routes in Eureka

### ISSUE THREAD

**Issue by mingfang** [spring-cloud/spring-cloud-netflix#134]
Normal Netflix routes client request via Zuul and service to service requests are routed directly to each other.  My use case requires that all service requests, both from clients and from other services, be routed to a central ZuulProxy.

Currently I can do that by having each service discover the ZuulProxy from Eureka and then send all REST calls via Zuul by adding the service prefix.  This works but it feels wrong that to call service "foo" I would actually do a discovery on "zuul".

Another approach would be to whenever ZuulProxy discover a new service to route, it would in turn register another "proxy" service with Eureka. e.g. service "foo" would result registering "zuul-foo" with Eureka.  The "zuul-foo" registration would have the ZuulProxy info in it.  That way other services will be able to discover "zulu-foo" from Eureka but all calls will go thru the ZuulProxy.

**Comment by dsyer** [comment]
You can already discover the routes from the proxy (with "/routes"). Is that not enough? Why does it need to be via Eureka?
