### ISSUE TITLE
Upgrade to Eureka 1.6.0

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1345]
Hold off until after 1.2.0.RELEASE
- https://github.com/Netflix/eureka/releases/tag/v1.5.1
- https://github.com/Netflix/eureka/releases/tag/v1.5.0
- https://github.com/Netflix/eureka/releases/tag/v1.5.0-rc.4
- https://github.com/Netflix/eureka/releases/tag/v1.5.0-rc.3
  Contains https://github.com/Netflix/eureka/pull/843 which will help with AWS refresh #1321
- https://github.com/Netflix/eureka/releases/tag/v1.5.0-rc.2
- https://github.com/Netflix/eureka/releases/tag/v1.5.0-rc.1

**Comment by spencergibb** [comment]
https://github.com/Netflix/eureka/releases/tag/v1.5.6
https://github.com/Netflix/eureka/releases/tag/v1.5.5
https://github.com/Netflix/eureka/releases/tag/v1.5.4
https://github.com/Netflix/eureka/releases/tag/v1.5.3
https://github.com/Netflix/eureka/releases/tag/v1.5.2

**Comment by voor** [comment]
@spencergibb Any chance on upgrading to 1.6 to resolve https://github.com/Netflix/eureka/issues/600

**Comment by dziadeusz** [comment]
Yes, 1.6 upgrade is critical for jersey based projects

**Comment by MaiGhoneim** [comment]
latest application servers , weblogic v12.2.1 and Websphere V9.0 both removed JAX-RS1.1 support
Spring cloud netflix deployments to both servers fails.

upgrade to 1.6 is painfully needed.

**Comment by adoura** [comment]
@spencergibb : spencer kindly tell us your opinion about this ?

**Comment by ryanjbaxter** [comment]
I dont see why we couldnt go to 1.6

**Comment by spencergibb** [comment]
Since this is targeted for Dalston, I'm ok with it. Also, just upgrading to 1.6.0 won't automatically mean that jersey 2 is supported. There is work that needs to be done.

**Comment by adoura** [comment]
@spencergibb  : question please , Dalstone will be compatible with spring boot 1.4.1 or it targeting 1.5 ?

**Comment by spencergibb** [comment]
Dalston will be compatible with 1.4.x and 1.5.x

**Comment by ErikLundJensen** [comment]
While testing this I do not see how I tell DiscoveryClient to Jersey 2. The DiscoveryClient constructors taking  DiscoveryClientOptionalArgs are deprecated.

I get this error:

> 
Caused by: java.lang.NoClassDefFoundError: com/sun/jersey/api/client/Client
	at com.netflix.discovery.shared.transport.jersey.Jersey1TransportClientFactories.newTransportClientFactory(Jersey1TransportClientFactories.java:48)
	at com.netflix.discovery.DiscoveryClient.scheduleServerEndpointTask(DiscoveryClient.java:454)
	at com.netflix.discovery.DiscoveryClient.<init>(DiscoveryClient.java:392)
	... 51 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.api.client.Client
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

> 

I have excluded Jersey 1.x as the project already included Jersey 2. Excludes:
    jsr311-api
    jersey-core
    jersey-client
    jersey-apache-client4

Does Eureka have a property where I can set the client?

**Comment by spencergibb** [comment]
> Also, just upgrading to 1.6.0 won't automatically mean that jersey 2 is supported. There is work that needs to be done.

**Comment by adoura** [comment]
@spencergibb  : by work needs to be done you mean dependencies management our side or what ?

**Comment by spencergibb** [comment]
@adoura Unknown. I just know that without doing some work on our side, it will not work. Follow #846 for updates
