### ISSUE TITLE
ZUUL seeing lot of 400 bad request with Brixton RC5

### ISSUE THREAD

**Issue by pradeepsingh1234** [spring-cloud/spring-cloud-netflix#1353]
Getting lot of 400 bad request error  and retry is getting success. 

responseHeaders": {
                                "Content-Type": ["application/json;charset=UTF-8"],
                                "Date": ["Tue, 20 Sep 2016 04:07:04 GMT"],
                                "Server": ["Apache-Coyote/1.1"],
                                "X-Application-Context": ["Appname"],
                                "X-Cf-Requestid": ["329bb2cb-82e2-469c-",
                                "901d247e-214f-40d5-483f-9c94c798f188"],
                                "Content-Length": ["327"]
                },
                "responseCharset": "UTF-8",
                "detailMessage": "400 Bad Request",

 

responseBody": {
                                "$binary": "eyJ0aW1lc3RhbXA",
                                "$type": "00"
                },

**Comment by ryanjbaxter** [comment]
This is not very helpful.  Please provide more details on the problem and how to reproduce and reopen the issue.
