### ISSUE TITLE
Classes in Spring-boot-autoconfigure jar can't load properties from configure server like @EnableConfigServer

### ISSUE THREAD

**Issue by lizhaosheng** [spring-cloud/spring-cloud-netflix#1355]
For example:
I have a configure server which load configure from git.
And there is a file name application.yml at git repos, like below:
![image_20160921102802](https://cloud.githubusercontent.com/assets/9860553/18695689/1fa6611c-7fe6-11e6-9c06-03309e00e46d.png)
run application, and it does't work. Default configurations were apply.
host=localhost
port=6379
...

If I put properties for redis to loal file application.yml, then it works.
![image_20160921103540](https://cloud.githubusercontent.com/assets/9860553/18695848/2ee170f8-7fe7-11e6-828e-2e07313dd1c3.png)

Of course, if I declear a @ConfigurationProperties bean, spring boot will load properties form remote config server
![image_20160921104247](https://cloud.githubusercontent.com/assets/9860553/18695981/2ef1d140-7fe8-11e6-83c8-e20fec4c2b5e.png)

So, why spring boot autoconfigure bean (e.x org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration) will not load properties from config server.

**Comment by spencergibb** [comment]
This is the wrong repo for a spring cloud config issue https://github.com/spring-cloud/spring-cloud-config/issues.

If you can provide a sample project that recreates the problem, open a new issue there.
