### ISSUE TITLE
`ZuulController` should be a bit more configurable

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-netflix#1356]
`ZuulController` might be do with some configuration. for example, it could support a property in `ZuulProperties` allowing us to limit the supported methods. At least, the bean for `ZuulController` could be replaceable using `@ConditionalOnMissingBean`

**Comment by spencergibb** [comment]
@joshlong what problems are you seeing? `ZuulController` just delegates to the `ZuulServlet`.

**Comment by spencergibb** [comment]
Why would you not use a zuul filter?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
