### ISSUE TITLE
Provide ability to get the full interface type in a custom logger

### ISSUE THREAD

**Issue by rfalke** [spring-cloud/spring-cloud-netflix#1363]
FeignClientFactoryBean has a special treatment for the default Slf4jLogger:

```
	protected Feign.Builder feign(FeignContext context) {
		Logger logger = getOptional(context, Logger.class);

		if (logger == null) {
			logger = new Slf4jLogger(this.type);
		}
...
```

While other loggers are apparently constructed without the information about the full name of the feign interface (`this.type`).

Is is possible to get `this.type` also in a custom logger? If yes, how?

**Comment by spencergibb** [comment]
Not currently.

**Comment by rfalke** [comment]
What is a good idea to support this? I can think of:

1. adding a method Logger.setType(Class<?> type) which is called after the creation of the Logger instance. Problem: will always be a new bean created?
2. adding "Object ...args" to org.springframework.cloud.netflix.feign.FeignClientFactoryBean#getOptional and org.springframework.cloud.context.named.NamedContextFactory#getInstance. Problem: NamedContextFactory is in another git repo/maven project
3. adding a new parameter "Class<?> type" feign.Logger#logRequest, logRetry, logAndRebufferResponse and logIOException. The information is available in the only caller (SynchronousMethodHandler). Problem 1: one logger for all feign clients and therefore no log level filtering. Problem 2: feels unclean.

Any recommendations?

**Comment by spencergibb** [comment]
Hmm... I'd think an interface like `FeignLoggerFactory` with a `create(Class)` method would be better.

**Comment by spencergibb** [comment]
See https://twitter.com/starbuxman/status/785194631956828160

**Comment by rfalke** [comment]
@venilnoronha: Thanks for the patch.
