### ISSUE TITLE
about FeignContext custom

### ISSUE THREAD

**Issue by x-jay** [spring-cloud/spring-cloud-netflix#1368]
i want custom feignContext.because i wanna change defaultConfigType to my custom config...
If I custom feignContext, then I have to change FeignClientFactoryBean.it's so bad.
i need make my default feign config is my custom config..i can override retry or decode or encode.
if don't use defaultConfig i can import use @FeignClient configuration attribute config.
sry.i hope you understand what i mean

**Comment by spencergibb** [comment]
I'm sorry, I don't understand what you mean properly. `@EnableFeignClients` has a `defaultConfiguration` attribute that might do what you want.

**Comment by x-jay** [comment]
oh,sry,i forgot
