### ISSUE TITLE
Typo in Eureka documentation

### ISSUE THREAD

**Issue by brianlaframboise** [spring-cloud/spring-cloud-netflix#137]
The 2nd property in this **Registering with Eureka** excerpt looks like it was accidentally copy/pasted:

> The default application name (service ID), virtual host and non-secure port, taken from the Environment, are ${spring.application.name}, ${spring.application.name} and ${server.port} respectively.

**Comment by dsyer** [comment]
Nope, that is correct. The second list is respective of the first one (the default just happens to be the same for the first two entries).

**Comment by brianlaframboise** [comment]
Ah, my mistake. Looking at it again I see how that could make sense. Sorry 'bout that.
