### ISSUE TITLE
EurekaInstanceRegisteredEvent not dispatching as intended

### ISSUE THREAD

**Issue by raiRaiyan** [spring-cloud/spring-cloud-netflix#1376]
I went through the source code and figured out that eureka dispatches the following 3 events from springs `ApplicationContext`

1. `EurekaInstanceRenewedEvent`
1. `EurekaInstanceRegisteredEvent`
1. `EurekaInstanceCancelledEvent`  
  

Of these only the EurekaInstanceRenewedEvent works and the listener is triggered when the server receives a heartbeat. Other events are not dispatched when a new instance is registered or canceled from eureka.

I think `InstanceRegistry` is overriding the wrong `register` method.  

The `ApplicationResource` controller calls the `register` method in the  `InstanceRegistry` when a new instance is registered. But the call goes to the super class of `InstanceRegistry`, bypassing the event dispatch. Not sure if this is intended and this is how it is supposed to work. If it is then what is the use of the event and how can it be used?

**Comment by bslota** [comment]
You are right. `org.springframework.cloud.netflix.eureka.server.InstanceRegi‌​stry` class extends PeerAwareInstanceRegistryImpl which has `register(final InstanceInfo info, final boolean isReplication)` which is not overridden in `InstanceRegistry` (so it does not have any event producing). This method is being called `addInstance` method from `com.netflix.eureka.resources.ApplicationResource` class. I think this method should be overriden.

**Comment by bslota** [comment]
I almost have a working solution. I will make a pull request soon.

**Comment by yangzhilin-tech** [comment]
good
