### ISSUE TITLE
Spring Boot Required?

### ISSUE THREAD

**Issue by Quantas** [spring-cloud/spring-cloud-netflix#138]
This is more of a question; After looking through all the POMs and dependency trees for the spring-cloud projects you will see that they all depend on spring-boot.  Is that the only way to use spring-cloud dependencies? I'm sure there are many out there that want to integrate things like Hystrix into "standard" Spring applications but don't want to get Spring Boot JARs in the classpath.  Any insight into this would be great! Thanks!

**Comment by spencergibb** [comment]
Many features of spring-cloud are built around spring-boot features like auto-configuration.  If you look [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCircuitBreakerConfiguration.java#L53-L56), you can see that to get hystrix work you need a `HystrixCommandAspect` from the [hystrix-javanica](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-javanica) project.

**Comment by Quantas** [comment]
I understand that you can use hystrix-javanica to get Hystrix going, but I would like to use spring-cloud-security-oauth2 and other spring-cloud-* projects outside of a Boot environment, is that going to be considered or is Spring Boot always going to be required? (And will I just have to "give in" and use Boot?).

**Comment by ccit-spence** [comment]
Curious why you don't want Spring Boot?  Maybe I have gotten lazy but couldn't imagine not using it.  Is it causing some sort of an issue?

**Comment by Quantas** [comment]
I guess I still prefer the "Standard" Spring WAR project setup, the Auto Configuration seems scary in a production/enterprise environment, but maybe that's because I haven't looked too closely at it.

**Comment by ccit-spence** [comment]
Ok, was concerned I might have some sort of a problem I didn't know about.  We do use it for both JAR and WAR deployments and have no problems.  I don't normally jump right on the latest version until tested.  Spring Cloud being a bit of an exception to that rule :-)

**Comment by Quantas** [comment]
Does this boil down to me just needing to "give in" and embrace Spring Boot??

**Comment by ccit-spence** [comment]
Assuming you don't have some sort of corp mandate in place forcing a standard, I would at least suggest giving it a shot.  Should be a breath of fresh air after using Spring Boot for a while.  Totally understand where you are coming from though.  I still use only Maven, don't like the newness of Gradle.

**Comment by Quantas** [comment]
I'll give it a shot, thanks for the feedback.
