### ISSUE TITLE
Using hystrix with spring @Transactional annotation

### ISSUE THREAD

**Issue by linead** [spring-cloud/spring-cloud-netflix#1381]
I've got a few cases where we're suing hystrix to wrap each DB call.

```
@Transactional
public void doMultipleCalls {
  Entity entity = repo.findOne(1l);
  // do something with entity
  repo.save(entity);
}
```

Using the hystrix annotations on the repo (or manually creating commands to wrap these methods) the repo calls to be executed on separate connections, with the transaction created by transactional not passed down into hystrix. 

This behaviour can also cause the fetching of a lazy-loaded jpa relationship to fail due to it being fetched in a transaction existing only within the hystrix command wrapping findOne.

I experimented with trying to pass the transaction down to the hystrix thread - 

```
public class TransactionalHystrixConcurrencyStrategy extends HystrixConcurrencyStrategy {

  public class TransactionAwareCallableDecorator<T> implements Callable<T> {

    private final Callable<T> callable;
    private final Map<Object, Object> resourceMap;
    private final String txnName;
    private final Integer txnIsolationLevel;
    private final boolean txnSyncActive;

    public TransactionAwareCallableDecorator(Callable<T> callable) {
      this.resourceMap = TransactionSynchronizationManager.getResourceMap();
      this.txnName = TransactionSynchronizationManager.getCurrentTransactionName();
      this.txnIsolationLevel = TransactionSynchronizationManager.getCurrentTransactionIsolationLevel();
      this.txnSyncActive = TransactionSynchronizationManager.isSynchronizationActive();
      this.callable = callable;
    }

    @Override
    public T call() throws Exception {
      if(txnSyncActive) {
        TransactionSynchronizationManager.setCurrentTransactionName(txnName);
        TransactionSynchronizationManager.setCurrentTransactionIsolationLevel(txnIsolationLevel);
        this.resourceMap.entrySet()
            .forEach((entry) -> TransactionSynchronizationManager.bindResource(entry.getKey(), entry.getValue()));
        TransactionSynchronizationManager.initSynchronization();
      }
      try {
        return callable.call();
      } finally {
        if(txnSyncActive) {
          TransactionSynchronizationManager.clear();
        }
      }
    }
  }

  public <T> Callable<T> wrapCallable(Callable<T> callable) {
    return new TransactionAwareCallableDecorator<T>(super.wrapCallable(callable));
  }
}
```

But I'm cautious because I'm feeling in the dark a bit with regard to how the transactions are handled in spring and also if this could causes issues with two threads potentially holding the transaction concurrently. 

Should a solution to this behavior be built or is it better to have the entire transaction operate within a single hystrix command?

**Comment by spencergibb** [comment]
By default, hystrix runs in a separate thread, hence your symptoms. IMO, it doesn't make much sense to have multiple calls to the same database guarded by multiple circuits.

**Comment by linead** [comment]
It is very easy to re-use the one circuit for the db and suffer this problem.

1. Call to fetch from DB [DB Circuit]
2. Request/Response to an external service [Rest Circuit]
3. Call to update DB [DB Circuit]

It's not currently possible to keep the same transaction for 1 & 3, and pulling them all into a single command that includes call 2 risks the Rest circuit from also taking down the DB circuit.

**Comment by spencergibb** [comment]
Nope.

**Comment by jayanderson** [comment]
We recently have run into a similar issue. One thought I had was to disallow transactions crossing hystrix thread boundaries and throw an exception when this happens. This way we we'll get understandable errors with this occurs instead of subtle errors. Here's what I was attempting:

```java
package test;

import com.netflix.hystrix.strategy.HystrixPlugins;
import com.netflix.hystrix.strategy.concurrency.HystrixConcurrencyStrategy;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.util.concurrent.Callable;

/**
 * A strategy which copies request context data to the thread running the
 * command. This allows request scoped bean access in the thread running the
 * Callable.
 */
public class SimpleTransactionHystrixConcurrencyStrategy extends HystrixConcurrencyStrategy {
    public static SimpleTransactionHystrixConcurrencyStrategy buildAndRegister() {
        final SimpleTransactionHystrixConcurrencyStrategy instance =
                new SimpleTransactionHystrixConcurrencyStrategy();
        HystrixPlugins.getInstance().registerConcurrencyStrategy(instance);
        return instance;
    }

    @Override
    public <T> Callable<T> wrapCallable(final Callable<T> callable) {
        // [Option 1] The goal here would be to avoid the call as early as
        // possible. This works fine, but also fails for semaphore based hystrix
        // commands.
        //if (TransactionSynchronizationManager.isSynchronizationActive()) {
        //    throw new IllegalStateException(
        //            "Transaction already exists on hystrix thread [" + Thread.currentThread().getName() + "]");
        //}
        return new RejectTransactionsCallable<>(callable);
    }

    private static class RejectTransactionsCallable<T> implements Callable<T> {
        private final Callable<T> callable;
        private final Thread originatingThread;
        private final boolean inTransaction;

        public RejectTransactionsCallable(final Callable<T> callable) {
            this.callable = callable;
            this.originatingThread = Thread.currentThread();
            this.inTransaction = TransactionSynchronizationManager.isSynchronizationActive();
        }

        private void before() {
            // [Option 2] Causes the hystrix command call to hang.
            //if (this.originatingThread != Thread.currentThread() && this.inTransaction) {
            //    throw new IllegalStateException(
            //            "Transaction already exists on hystrix thread [" + Thread.currentThread().getName() + "]");
            //}
        }

        private void after() {
            // [Option 3] Exception doesn't seem to be propagated.
            //if (this.originatingThread != Thread.currentThread() && this.inTransaction) {
            //    throw new IllegalStateException(
            //            "Transaction already exists on hystrix thread [" + Thread.currentThread().getName() + "]");
            //}
        }

        @Override
        public T call() throws Exception {
            try {
                before();
                return callable.call();
            } finally {
                after();
            }
        }
    }
}
```

Difficulties inline above. Is there an alternate mechanism to force an error in this case? Or is there a way to detect if it is a threaded hystrix command vs a semaphore hystrix command?

**Comment by spencergibb** [comment]
The difficulty is hystrix, by default runs in a separate thread. In this case, I recommend only using a semaphore.

**Comment by jayanderson** [comment]
> The difficulty is hystrix, by default runs in a separate thread. In this case, I recommend only using a semaphore.

Quite right. Think of what I was attempting as a way to enforce this design rule. For that reason I was trying to prevent non-semaphore hystrix calls when within a transaction. We had an issue where a team didn't use semaphore hystrix calls within a spring transaction causing some subtle issues which were a bit harder to track down. If the hystrix call errored out at the very beginning we could have prevented this issue earlier.

In my previous comment I showed some of the difficulties in accomplishing this through a `HystrixConcurrencyStrategy`. Are there ways around these difficulties? Is there another mechanism we can hook into for doing this?

**Comment by spencergibb** [comment]
There's really no other way to hook into Hystrix.

**Comment by gaoagong** [comment]
Is the only solution to using transactions and Hystrix together still to force Hystrix to use a semaphore? This eliminates some of the benefits that Hystrix thread pools give. Has anyone found a solution to keep the Hystrix thread pools, but still support transactions?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
