### ISSUE TITLE
Query gets double URIencoded for @LoadBalanced RestTemplate

### ISSUE THREAD

**Issue by ishchenko** [spring-cloud/spring-cloud-netflix#1382]
spring-cloud-dependencies Camden.BUILD-SNAPSHOT 

I'm using Consul for service discovery 

My service registration is like 
```json
{
  "service": {
    "name": "example",
    "address": "example.com",
    "port":443
  }
}
```

When I create `@LoadBalanced RestTemplate` and make `restOperations.getForObject("https://example/?foo=|", String.class)` my pipe symbol gets encoded twice, first on URI expansion in `RestTemplate#execute`, then in `RibbonLoadBalancerClient#reconstructURI:`
```java
if (secure) {
    uri = UriComponentsBuilder.fromUri(uri).scheme("https").build().toUri();
}
```

Final form is `https://example.com:443/?foo=%257C`, instead of expected `https://example.com:443/?foo=%7C`

**Comment by spencergibb** [comment]
@ishchenko we've had a number of fixes for things like this. What version are you using?

**Comment by ishchenko** [comment]
Updated initial description as you wrote your question. This is latest snapshot.

**Comment by ishchenko** [comment]
Testcase for `org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClientTests`

```java
	@Test
	@SneakyThrows
	public void testReconstructUriWithUrlEncoded() {
		RibbonServer server = getRibbonServer();
		IClientConfig config = mock(IClientConfig.class);
		when(config.get(CommonClientConfigKey.IsSecure)).thenReturn(true);
		when(clientFactory.getClientConfig(server.getServiceId())).thenReturn(config);

		RibbonLoadBalancerClient client = getRibbonLoadBalancerClient(server);
		ServiceInstance serviceInstance = client.choose(server.getServiceId());

		URI expanded = new DefaultUriTemplateHandler().expand("https://" + server.getServiceId() + "/dash=|");
		URI reonstructed = client.reconstructURI(serviceInstance, expanded);
		assertEquals(expanded.getPath(), reonstructed.getPath());
	}
```

```
Results :

Failed tests:   testReconstructUriWithUrlEncoded(org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClientTests): expected:</dash=[|]> but was:</dash=[%7C]>
```
