### ISSUE TITLE
eureka.dashboard properties are not used in spring-cloud-netflix-eureka-server

### ISSUE THREAD

**Issue by bslota** [spring-cloud/spring-cloud-netflix#1386]
Setting `eureka.dashboard` properties does not take effect. In source code I can't find any usage of `org.springframework.cloud.netflix.eureka.server.EurekaDashboardProperties`. There are two fields: `enabled` and `path`. Do you think if they should be used or deleted? Dashboard path is now defined by `server.contextPath` property and in my opinion it is sufficient, but I'm not sure about `enabled` property. What are your thoughts?

**Comment by spencergibb** [comment]
Actually, they are used, just not via the properties object https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java#L57
