### ISSUE TITLE
Is it possible to access FailedExecutionException in Feign fallback?

### ISSUE THREAD

**Issue by starlight36** [spring-cloud/spring-cloud-netflix#1391]
Is it possible to access FailedExecutionException in Feign fallback? I have to build the fallback result with the exception details. According to [OpenFeign's documents](https://github.com/OpenFeign/feign/tree/master/hystrix#considering-the-cause), I found some tips to do this. How to access the exception in the fallback method with `@FeignClient` configured fallback class?

**Comment by ryanjbaxter** [comment]
I believe this is possible in the latest Camden Snapshots.  There is some code that went in a couple days ago, take a look at 8e18c3d.

**Comment by starlight36** [comment]
@ryanjbaxter Thanks for your help
