### ISSUE TITLE
Eureka not updating instances status when enabled for transparent fallback to other region

### ISSUE THREAD

**Issue by meetankit** [spring-cloud/spring-cloud-netflix#1393]
We have enabled transparent fallback to other region (`disableTransparentFallbackToOtherRegion: false`). Currently we have deployed eureka across 2 regions (2 zones per region) (us east and us west). We have defined `eureka.server.remoteRegionUrlsWithName` for each region (east pointing to west URL and viceversa).
With this set up, each instance starts seeing the services across all regions, all zones. However, if any of the service instance goes down, eureka is not updated for the same and we continue to see the instance which is down.
I think, this used to be different with previous versions of eureka, when we used to see only local regions instances and failover to other region only when needed. Seeing all the nodes across all regions sounds better, however, not sure what is causing the instances to unregister when being down. May be some misconfiguration from our side. Please note we have not set self preservation and all looks good when we disable transparent fallback (of course we don't get region failover then).
Can someone please help. Please let me know if any other info is needed

**Comment by ryanjbaxter** [comment]
I think you might be running into the same issue as described in #1322.

**Comment by spencergibb** [comment]
Can you clarify what you mean by "we have not set self preservation"? Does that mean you left the default to true?

**Comment by meetankit** [comment]
I meant We are using the default value of self preservation.

**Comment by ryanjbaxter** [comment]
I guess I am not understanding what regions and fallback has to do with the instances not be evicted.

Have you set self preservation to false to see if they are evicted?

**Comment by meetankit** [comment]
I just tried setting self preservation to be false manually, along with setting eviction Interval Timer to be 10 seconds, still the same

**Comment by meetankit** [comment]
"I guess I am not understanding what regions and fallback has to do with the instances not be evicted." -- instances get evicted if i set disableTransparentFallbackToOtherRegion as true (we dont see the other region instances and if any of the local region instance is down, it get evicted). However, if I set disableTransparentFallbackToOtherRegion as false, I see other region instances too and they do not get evicted when down. I have set enableSelfPreservation as false in either of the cases

**Comment by spencergibb** [comment]
I'm unsure that any of us have experience with `disableTransparentFallbackToOtherRegion=true`.

**Comment by meetankit** [comment]
I looked further, this is what is happening:
1) Service starts in two regions and registers themselves with eureka in their regions
2) eureka replicates the instances info with peers (hence all region eureka sees all instances),
3) Service instance in one of the region goes down
4) Eureka of the same region, cancels the registration for those instances (all good till now)
5) However, same region eureka receives api call to register the down instances (very likely from peer nodes), and registers them back. This is what is causing the issue, not letting the instances to be evicted as they are getting registered again in case of cross region replication is enabled.

I wonder how to stop instances of its own region to be replicated from other regions

**Comment by meetankit** [comment]
2016-10-20 03:21:23.655  INFO 7537 --- [http-nio-8080-exec-2] c.n.e.registry.AbstractInstanceRegistry  : Cancelled instance MEMEBOOTSERVICE/i-6aa11372-a81bbaf1e426 (replication=true)
2016-10-20 03:21:23.655 DEBUG 7537 --- [http-nio-8080-exec-2] c.n.eureka.resources.InstanceResource    : Found (Cancel): MEMEBOOTSERVICE - i-6aa11372-a81bbaf1e426
2016-10-20 03:21:23.655 DEBUG 7537 --- [http-nio-8080-exec-2] c.n.e.resources.ApplicationResource      : Registering instance i-6aa11372-a81bbaf1e426 (replication=true)
2016-10-20 03:21:23.656 DEBUG 7537 --- [http-nio-8080-exec-2] c.n.e.registry.AbstractInstanceRegistry  : No previous lease information found; it is new registration
2016-10-20 03:21:23.656 DEBUG 7537 --- [http-nio-8080-exec-2] c.n.e.r.PeerAwareInstanceRegistryImpl    : Trusting the instance status DOWN from replica or instance for instance i-6aa11372-a81bbaf1e426

**Comment by ryanjbaxter** [comment]
So are you saying that since the peer in the other region still thinks the service is up and it is replicating data to the peer in the region where the service is down, the replication is causing the service to be marked up again?

**Comment by meetankit** [comment]
Yes, that seems to be the case

**Comment by meetankit** [comment]
@ryanjbaxter could you look into it?

**Comment by spencergibb** [comment]
Why do you need transparent failover?

**Comment by meetankit** [comment]
What is the other proposal to failover in case a region is down?

**Comment by spencergibb** [comment]
Explicit failover

**Comment by meetankit** [comment]
how to do that?

**Comment by meetankit** [comment]
does that need manual intervention?

**Comment by meetankit** [comment]
@spencergibb @ryanjbaxter 
I looked further and figured out the following problem:
- we have 4 instances of eureka running, 2 per region, 2 zones in each region with 1 instance per zone (say region 1 -> zone 1, zone 2 & region 2 -> zone 3, zone4)
- we had set region 1 instances to use zone 3 of region 2 as remote region URL, 
- we also set region 2 instances to use zone 1 of region 1 as remote region URL
- Now, this was causing cyclic dependency causing /apps/delta call to fail always. for e.g., when delta call was made to zone 1 of region 1, it tried to fetch delta of its remote region (zone 3 of region 2). However, application delta is null for remote registry in zone3 -region2, since that depends on zone 1- region 1 itself (look at above config).
Refer line no 911 in AbstractInstanceRegistry:
 for (RemoteRegionRegistry remoteRegistry : this.regionNameVSRemoteRegistry.values()) {
                    Applications applications = remoteRegistry.getApplicationDeltas();
                    for (Application application : **applications.getRegisteredApplications()**) {
                        Application appInLocalRegistry =
                                allAppsInLocalRegion.getRegisteredApplications(application.getName());
                        if (appInLocalRegistry == null) {
                            apps.addApplication(application);
                        }
                    }
                }

**We are seeing Null pointer exception here, causing delta to fail and hence falling over to ALL_APPS. This is causing the evicted instances to be re registered from the cross region replication.** 

To work around, i tried following configuration:
zone 1-region1 -> zone 3 - region 2
zone 3-region2 -> zone 2 - region 1
zone 2-region1 -> zone 4 - region 2
zone 4-region2 -> zone 1 - region 1

however, this again remains cyclic eventually. To terminate the cycle, i deleted zone 4-region2 -> zone 1 - region 1 link and made zone4-region2 as disableTransparentfallback as true. That fixed the issue and all started working, except that transparent failover is disabled on one instance (zone 4-region2). 
This seems like a bug to me or may be I am missing some configuration to get around this cyclic dependency.

**Comment by meetankit** [comment]
ok, looks getApplicationDeltasFromMultipleRegions implementation has the null check already. We are triggering the deprecated flow (having bug) due to our configuration. This looks to be controlled through fetchRemoteRegionsRegistry property. Any more documentation for the same?

**Comment by spencergibb** [comment]
Any documentation on those would be on the eureka wiki and source.

**Comment by ryanjbaxter** [comment]
From the Eureka [documentation](https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance#multiple-regions), it sounds like Eureka instances in a given region should only know about services within that region.  They should not know about services residing outside of that region.

**Comment by spencergibb** [comment]
> Deploying Eureka in multiple AWS regions is a fairly straightforward task. Eureka clusters between regions do not communicate with one another.

**Comment by ryanjbaxter** [comment]
> Eureka clusters between regions do not communicate with one another.

^^^ This is specifically what I was referring to.  From the description of the configuration it sounded to me like the instances were communicating across regions.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
