### ISSUE TITLE
Can we provide different command and thread pool properties?

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1394]
In our requirement , we want to wrap a certain code which have calls to different resources from a single point of entry. For which we want to configure different command and threadpool properties. as far as I understood , we can set all these parameter while creating hystrix command as for example - 

```
              super(HystrixCommand.Setter.withGroupKey(HystrixCommandGroupKey.Factory.asKey(COMMAND_GROUP))
				.andCommandKey(HystrixCommandKey.Factory.asKey("demo"))
                .andCommandPropertiesDefaults(
                        HystrixCommandProperties.Setter()
                                .withCircuitBreakerEnabled(true)
                                .withExecutionTimeoutInMilliseconds(10000)
                                .withCircuitBreakerRequestVolumeThreshold(10)
                                .withCircuitBreakerSleepWindowInMilliseconds(10000)
                ));
```

But can we provide different properties for code being executed and wrapped inside run() method for this command. as can we provide different thread pool size later on , might be if we can update this later on based on requirement ?

**Comment by spencergibb** [comment]
All of the configuration options work as defined in the wiki: https://github.com/Netflix/Hystrix/wiki/Configuration

Also see the readme for Javanica (`@HystrixCommand`): https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-javanica#configuration

**Comment by spencergibb** [comment]
Have you tried either of those methods?

**Comment by spencergibb** [comment]
Why would you want to change the name of the command after it was created?

**Comment by JagmohanSharma** [comment]
It was asked by our client if this is possible as multiple resources is being called from the single hystrix command execution. So they were expecting if we can update the command name and property based on resource getting called. But I have conveyed that this needs to be done at the time of Hystrix command creation only.  this should be considered as clear doubt. Thanks for feedback.
