### ISSUE TITLE
Turbine does not create correct service url if context-path set

### ISSUE THREAD

**Issue by CobraFlow** [spring-cloud/spring-cloud-netflix#1402]
We use Eureka discovery and have multiple services running inside docker behind Zuul.

Our Turbine service, also behind Zuul, is unable to connect to the service Instance if the service has a context-path set.

The url path is created in SpringClusterMonitor using the host and port but without any context-path.

Is it possible to add this functionality or override the SpringClusterMonitor as a bean?

**Comment by spencergibb** [comment]
`turbine.instanceUrlSuffix.<clustername>` is used to change this.

**Comment by AnkushNakaskar** [comment]
Hi @spencergibb ,
What if i have same cluster as default cluster and all my application in same cluster.
My config looks like below:

turbine:
  appConfig: content-context
  aggregator:
    cluster-config:  default
  instanceUrlSuffix:
      default: /api/contextService/hystrix.stream
  clusterNameExpression: new String("default")

Now,I have other application,with different context path,What should i do ?
Is there any way to solve this problem
