### ISSUE TITLE
How to customize un certain number of @FeignClient with overiding configuration

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-netflix#1403]
How to customize un certain number of @FeignClient with overiding configuration attribute on each configuration.

My usecase is
- for n FeignClient, I want one specific RequestInterceptor (like add a token)
- for m another FeignClient, I want one another specific RequestInterceptor (like add a another token)
....

I want to do something like
```
@EnableFeignClients(basePackageClasses = {
        Resource1App1.class, Resource2App1.class,  }, defaultConfiguration = App1Config.class)
@EnableFeignClients(basePackageClasses = {
        Resource3App2.class, Resource3App2.class,  }, defaultConfiguration = App2Config.class)
```
And in another microservice, I want todo 
```
@EnableFeignClients(basePackageClasses = {
        Resource1App1.class, Resource2App1.class,  }, defaultConfiguration = App1CustomConfig.class)
```
It is the reason why I don't want to see the configuration in the interface.

Tell me if it is not clear.

**Comment by ryanjbaxter** [comment]
If I understand you correctly, you want specific configuration for individual Feign Clients.  This can be done via the `@FeignClient` annotation.  http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-overriding-defaults

**Comment by spencergibb** [comment]
He wants to configure more than one at once. We currently only support a default and per client configuration.

**Comment by ryanjbaxter** [comment]
OK I see.  But you can reuse the same configuration class in your `@FeignClient` annotations to accomplish that as well.  I guess it is a little more verbose, but doesn't seem too painful to do.

**Comment by alexandrenavarro** [comment]
@ryanjbaxter  The problem with your approach is : I notably want to use the same Feign interface but with different RequestIntercepter depending of the usecase. I can't do that without copy/paste my feign interface with different configuration what I really don't want to do. I'm not sure I'm clear.

**Comment by ryanjbaxter** [comment]
How are you reusing the Feign client?  Are you sharing an interface across multiple projects?

**Comment by alexandrenavarro** [comment]
Are you sharing an interface across multiple projects?
Yes, I have a dozen of micro services. Each microservice propose a client jar with @FeignClient.
But depending of the micro service, some need special interceptors.
Ex : Some micro services is called from gui, in this case I forward the oauth token, some are like batches, they need to use another interceptor to add their own oaut2 token.
More I used @EnableFeignClients, more I think it should be more flexible un real life with a lot of micro service.
You can't pass classes (not package), you can't have multiple EnableFeignClients, you can't configure  easily without changing interface  FeignClient configuration.
Personnaly, I prefer FeignBuider if you need custom conf, the problem is you can't use eureka discovery. name.
Maybe you should just add helper on feign builder or propose better customisation on EnableFeignClient or FeignClient.

**Comment by spencergibb** [comment]
Packaging different interfaces per client seems beyond feign's use case.

Why not use java configuration with profiles or include?

```
@Configuration
@FeignClient(name="resource1", configuration=App1Config.class)
@FeignClient(name="resource2", configuration=App1Config.class)
@FeignClient(name="resource3", configuration=App2Config.class)
public class MyGroupAConfig {}

// later
@Import(MyGroupAConfig.class)
```

**Comment by spencergibb** [comment]
Also see https://github.com/spring-cloud/spring-cloud-netflix/issues/1211#issuecomment-239234285 for how to use the builder but retain enhanced feign functionality like converters.

**Comment by alexandrenavarro** [comment]
@spencergibb 

1) On your first comment, I though that FeignClient can be used only on interface not on Configuration, isn't? Do you made a mistake?
If not, I don't really understand what it can mean. Regardless the signification, the name is use to retrieve service in eureka must match my microservice, so I can't have different name as you proposed.

2) On your second comment, it seems great alternative for my specific usecase but if the urls retrieved via the EurekaDiscover at the creation of the feign client disappear (you shutdown your microservices and restart on other machines), it will not work anymore, isn't?

It should be cool to have mulitiple @EnableFeignClients and possiblity to have (not only  basePackageClasses).

**Comment by spencergibb** [comment]
@alexandrenavarro yes, RE #1 this is why I shouldn't work when not feeling well. Re #2 you can use the `LoadBalancerFeignClient` for eureka support.

I don't think this is a feature many people want.

**Comment by alexandrenavarro** [comment]
You should add the way to create a Feign client like in #1211 (comment) in your documentation at the end of the Feign : Overriding Feign Defaults . Thanks for all your answers.

**Comment by spencergibb** [comment]
Yeah, I think that is going to be the outcome of #1211.

**Comment by ryanjbaxter** [comment]
@alexandrenavarro are you referring to [this comment](https://github.com/spring-cloud/spring-cloud-netflix/issues/1211#issuecomment-239234285)?

**Comment by alexandrenavarro** [comment]
Yes

**Comment by ryanjbaxter** [comment]
@alexandrenavarro can we close this issue in favor of the documentation being added in #1211?

**Comment by alexandrenavarro** [comment]
Yes
