### ISSUE TITLE
In @FeignClient, configuration does not work when you have 2 or more @FeignClient with the same name but different configuration

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-netflix#1404]
In @FeignClient, configuration does not work when you have 2 or more @FeignClient with the same name but different configuration

The workaround is to use name with name="http://microservice" it on FeignClient and and name="microservice" in the other when you have only 2.

Tell me if it is not clear.

**Comment by spencergibb** [comment]
This is a duplicate, will find issue # later.

**Comment by spencergibb** [comment]
Duplicates #1211
