### ISSUE TITLE
Can we combine instance discovery by any client(Consul) and configPropertyBasedDiscovery to have composite service instance discovery?

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1406]
We have requirement where in our architecture , currently we do not have all the services registered at consul. So all consul registered services we are getting from consulDiscoveryClient and dynamically registering their cluster monitor as well. 

But now services which are not registered at consul, also needs to be used inside our aggregator application so we think to configure them in config.properties as hard coded. can we combine both these service discovery to have composite list of services getting aggregated?

**Comment by spencergibb** [comment]
Should this be in spring cloud netflix when it is about consul?

**Comment by JagmohanSharma** [comment]
This is actually related to composite instance discovery approach. Like currently we have implemented this using consul discovery client and this is working fine. But now we also want to add those services which are not registered at consul. I think this question is not related to just consul , it is like composite instance discovery which includes consul and ConfigPropertyBasedDiscovery. So I asked here. Still if you find this inappropriate then I will close this and raise in consul.

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/140 since this is above netflix/consul
