### ISSUE TITLE
A @FeignClient will generate an error when we add a regex on the @RequestMapping

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-netflix#1407]
A @FeignClient will generate an error when we add a regex on the @RequestMapping

Ex : 
@RequestMapping(value = "/{id:.+}" , method = RequestMethod.GET)
public OUser getUser(@PathVariable("id") String userId);

The {id:.+} is not well parsed by FeignClient.
My point is not to validate on the client side but just not have a parser error in order to use potentially the same interface between the server and the client (even if I agree, I play with fire).

**Comment by ryanjbaxter** [comment]
Can you provide the error?

**Comment by spencergibb** [comment]
Duplicates #816
