### ISSUE TITLE
Clarification of zuul routing behavior when using a default route ("/")

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-netflix#141]
If I add a request mapping to the api-gateway server found here:
https://github.com/wgorder/api-gateway

```
    @RequestMapping(value ="Hello")
    String sayHello() {
        return "Hello World"
    }
```

I can see it is registered on startup:
```
2015-01-12 14:00:03.128  INFO 10972 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/Hello],methods=[],params=[],headers=[],consumes=[],produces=[],custom=[]}" onto public java.lang.String com.acme.demo.gateway.ApiGatewayApplication.sayHello()

```

However if I hit localhost:8080/hello (this is where the api-gateway runs) it attempts to proxy that request to the acme-ui application and returns a 404

The zuul routes in the api-gateway look like this
https://github.com/wgorder/api-gateway/blob/master/src/main/resources/application.yml

so you can see that the acme-ui is set as a catch all, however I expected it to match against its own @RequestMappings before attempting a zuul route.  Is this expected behavior?  How would I tell zuul to route to myself if so?

**Comment by spencergibb** [comment]
@wgorder The order of the handler mappings is what is important here.  It looks like the `ZuulHandlerMapping` is ahead of the `RequestMappingHandlerMapping`.

You could use something like:
```
zuul:
  routes:
    hello: 
      url: http://localhost:${server.port}
      path: /Hello/**
```

**Comment by wgorder** [comment]
Fair enough I guess. Can I provide multiple paths?

**Comment by spencergibb** [comment]
sibling entries to `hello` would work, but that seems a bit cumbersome.  Why do you need a default route of `/**`?  Couldn't you put it `/somewhereelse` and have a controller that does a forward from `/` to `/somewhereelse`?

**Comment by wgorder** [comment]
Well I don't have the @ZuulProxy on my UI service.  I have it on the api gateway service.  So routing for any static resources css/js/fonts/images or in the case of local dev bower_comonents, /.tmp etc all need to be routed to acme-ui.  Also if  a user bookmarks a page like /#products/1  that also has to be routed.  So I don't think a simple / with a 'forward' would work.  Plus I don't think you can forward from one container to another.  It would have be a redirect or a framework like zuul to do the routing.. Or am I missing your point entirely?

**Comment by spencergibb** [comment]
You're missing it a little bit.  Instead of having `/**` forward (not redirect) to acme-ui have `/ui/** forward to acme-ui and have a local controller forward `/` to `/ui`.  The downside to that is that your bookmarks would have `/ui` in the path.  Another option would be to put whatever functionality you are implementing in `/Hello` into another service.  I also have seen what it would take to reorder the mappers.

**Comment by spencergibb** [comment]
After thinking a bit, I think you could have the forward of `/` to `/ui` work and not see `/ui` in the url.

**Comment by wgorder** [comment]
I can play with this.  I think re-ordering the mappers might also be painful as spring auto maps /css /js etc for you and often times you may not want those matched before zuul routing kicks in (if your static resources are not on the zuul proxy app)
