### ISSUE TITLE
Make servo optional (again?)

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#1415]
I'm pretty sure we did this once but it seems to have crept back in.

**Comment by dsyer** [comment]
See also spring-projects/spring-boot#7165.

**Comment by spencergibb** [comment]
It's also part of `com.netflix.loadbalancer.BaseLoadBalancer`. So it's not optional in Ribbon either. It would be an effort to make PR's against ribbon. Pretty simple for zuul, but it depends on ribbon.

**Comment by OlgaMaciaszek** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
