### ISSUE TITLE
DiscoveryClient fails to execute "cacheRefresh" task when application context is refreshed

### ISSUE THREAD

**Issue by qza** [spring-cloud/spring-cloud-netflix#1416]
When Eureka client is configured to fetch registry and application context refresh event occurs, already scheduled "cacheRefresh" task gets rejected.

Error: com.netflix.discovery.TimedSupervisorTask  : task supervisor rejected the task.

This causes local cache to have invalid IP addresses of services registered in Eureka.

Using Spring Cloud Camden.RELEASE and eureka-client:1.4.11.

**Comment by spencergibb** [comment]
Can you explain a bit more? Why does it cause invalid IP addresses?

**Comment by marcingrzejszczak** [comment]
Hey @qza , is it still an issue with the latest release train?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
