### ISSUE TITLE
Does zuul support http2?

### ISSUE THREAD

**Issue by killjason** [spring-cloud/spring-cloud-netflix#1419]
Does zuul support http2?

**Comment by ryanjbaxter** [comment]
If you have questions about Zuul you should ask them here https://github.com/Netflix/zuul

**Comment by spencergibb** [comment]
Also see the last paragraph of http://techblog.netflix.com/2016/09/zuul-2-netflix-journey-to-asynchronous.html

> We are in the process of releasing Zuul 2 as open source. Once it is released, we’d love to hear from you about your experiences with it and hope you will share your contributions! We plan on adding new features such as http/2 and websocket support to Zuul 2 so that the community can also benefit from these innovations.
