### ISSUE TITLE
Unkown host exceptions running locally

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-netflix#142]
On my macbook pro I constantly get unknown host exceptions in zuul forwarding.  It usually involves me having to rebuild restart serveral times until it magically starts working again.  Has anyone else run into this and figured out a way to prevent it from happening?  I cant imagine my host name is in a state of flux.

**Comment by spencergibb** [comment]
@wgorder I've seen it happening, it usually involves changing wi-fi networks and eureka.  Eureka registers a service with the hostname, switch wifi's and that hostname is no longer valid and eureka pukes because it's no longer a valid hostname.

**Comment by spencergibb** [comment]
can you ping the hostname it says it can't find?

**Comment by wgorder** [comment]
I had it burred in another issue somewhere but its always the same its like Williams-MBP or something along those lines.

**Comment by spencergibb** [comment]
Ok, I've seen it with `sgibb-mbp.local` or `sgibb-mbp.otherdomain`

**Comment by spencergibb** [comment]
Closed for lack of feedback. Please, reopen if there is something new to add.

**Comment by wgorder** [comment]
I have not seen this one in awhile. I am not sure what changed
