### ISSUE TITLE
Non-deterministic configuration for RibbonCommandFactory in Zuul

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#1421]
The `ZuulProxyConfiguration` has a bunch of nested configuration classes that eventually choose an implementation of `RibbonCommandFactory`. I was seeing test failures because the wrong type was being selected, and it's easy to see that if `HttpClientRibbonConfiguration` is registered first it always wins because its conditions have `matchIfMissing=true`. So we need to control the order (or stop using 3 mutually dependent booleans to control one feature).

**Comment by dsyer** [comment]
Fixed in c4e2466

**Comment by spencergibb** [comment]
Thanks dave
