### ISSUE TITLE
Add Cors handling to Zuul proxy

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#1423]
Each route could have its own Cors configuration in application.yml instead of having to look in the `ZuulHandlerMapping`. If `ZuulController` was itself an implementation of `CorsConfigurationSource` and looked up configs from the route information it would just work.

**Comment by thofte** [comment]
Hi,

Any idea when CORS configuration would be possible per route in application.yml file?

**Comment by dsyer** [comment]
It's marked for 1.3.0.RC1 but no-one is working on it, so unless you have some code you want to contribute, my guess is it will slip to 1.3.1.

**Comment by rnavarropiris** [comment]
What's the status of this issue? Is it still open?

If so, what is the current target release version?

**Comment by spencergibb** [comment]
It's still open and not targeted for any release.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
