### ISSUE TITLE
Turbine available at actuator/management endpoint

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-netflix#1426]
Hmm just figured out that the turbine.stream is no a regular actuator endpoint - so it doesn't run on the management port. Please make available at actuator/management endpoint

**Comment by spencergibb** [comment]
Not sure that this makes sense. It's an application in its own right.

**Comment by cforce** [comment]
Isn't there a wanted and used concept of plugability for Netflix components
to spring boot actutaor registration.

Spencer Gibb <notifications@github.com> schrieb am Mi., 26. Okt. 2016 um
19:47 Uhr:

**Comment by spencergibb** [comment]
It doesn't make sense to me that, in deploying turbine, the only functionality would be a single actuator endpoint.

**Comment by joshiste** [comment]
@spencergibb imho you're absolutely right. I found a solution for spring boot admin. In my opinion you can close this issue.
