### ISSUE TITLE
How can I call a registred Service in Eureka Server from external API????

### ISSUE THREAD

**Issue by LucasHCruz** [spring-cloud/spring-cloud-netflix#1427]
I created an Eureka server and two Service Appications that are my Eureka Clients.

Okay, all is wired and working.

How can I call the Eureka Server from an external API to call my Service Applications??

I don't know how to do it... I think it's like:

`http://myeurekaserver/my-service/test`

The question could be:

How can I call my service from angularJS client, php, etc... passing through Eureka Server..

**Comment by spencergibb** [comment]
Eureka is not a proxy. See zuul https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#router-and-filter-zuul
