### ISSUE TITLE
Is it possible to use zuul proxy with hystrix without service discovery?

### ISSUE THREAD

**Issue by ahmednasir91** [spring-cloud/spring-cloud-netflix#1431]
Question, is it possible to use zuul proxy with hystrix without service discovery? I've seen on other threads that hystrix works with ribbon and ribbon works when `service-id` is specified and if we specify URL it defaults to simple route filter. 

Is there a way we can use hystrix when specifying URL instead of service-id?

**Comment by ryanjbaxter** [comment]
We don't support this by default.  I don't see why you couldn't provide your own filter which did use Hystrix though.

**Comment by spencergibb** [comment]
Or configure ribbon for the specific service to use a static list of servers

**Comment by ahmednasir91** [comment]
@spencergibb thanks, will try it out.
