### ISSUE TITLE
Document zuul filters for developers

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1435]

**Comment by spencergibb** [comment]
@markfisher please add any specifics you'd like (like the lack of constants that are documented for map keys that you mentioned.)

**Comment by markfisher** [comment]
I think a detailed description of the `RequestContext` would be very useful. That should include any map keys that contribute to pre-established behavior as well as a thorough explanation of the way various methods on the context can influence response generation (for example, I seem to notice different behavior based on whether `ctx.setResponseBody(..)` has been called even if `ctx.setResponseStatusCode(..)` has been called with a status code that doesn't typically accompany a response body).

**Comment by spencergibb** [comment]
> Mark Fisher [1:20 PM]  
> I think the most important thing would be to understand exactly what influences the request/response as well as the actual routing.... e.g. the "forward.to" key in the `RequestContext` and how that path resolves within the context of the current request

> Mark Fisher [1:34 PM]  
> also would be good to have an overview of what's provided by `ZuulProxyConfiguration`
> which I believe is what determines most of the details I just mentioned in the last comment

**Comment by spencergibb** [comment]
Document different clients (OkHttp3, apache http client and ribbon rest client). Note which ribbon properties are only for ribbon restclient. SSL examples as well. See #1446

**Comment by spencergibb** [comment]
Here is my outline that I'm working on now:
- See https://github.com/Netflix/zuul/wiki/How-it-Works for a general zuul overview
- Describe how installed
  - Controller
  - Plain Servlet (for large files)
- Describe different ribbon http clients
- howto disable filters
- Describe RequestContext
  - link to https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/support/FilterConstants.java[FilterConstants]
- Describe difference between `@EnableZuulProxy` and `@EnableZuulServer`
  - Describe installed filters
  - Proxy
    - DiscoveryClient + Properties route locator
      - Refreshed routes
    - PreDecorationFilter
    - RibbonRoutingFilter
    - SimpleHostRoutingFilter
  - Server (no routing)
    - Properties route locator
    - ServletDetectionFilter
    - FormBodyWrapperFilter
    - DebugFilter
    - SendResponseFilter
    - SendForwardFilter
    - SendErrorFilter
- Describe howto write a general pre route determining filter
- Describe howto write a general routing filter
- Describe howto write a general post response manipulation filter
- Describe how errors work

**Comment by spencergibb** [comment]
Closed via d21d03b7387cdf481304806dd32927ac0b9cc4b1 and 675e4c1031b275af877938c02d5950c91f7fe660
