### ISSUE TITLE
Add/edit a LoadBalancerRule at runtime via Archaius

### ISSUE THREAD

**Issue by alfre86** [spring-cloud/spring-cloud-netflix#1438]
My goal is to be able to add/edit a Ribbon LoadBalancerRule at runtime via Archaius.

`myService.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.WeightedResponseTimeRule`

I'm trying to change the property NFLoadBalancerRuleClassName at runtime via Archaius. I see the archaius log that notifies me that the property was changed, but ribbon doesn't refresh with the new rule and still use the old rule.

> [pollingConfigurationSource] | DEBUG | com.netflix.config.DynamicPropertyUpdater | addOrChangeProperty | adding property key [myService.ribbon.NFLoadBalancerRuleClassName], value [com.netflix.loadbalancer.WeightedResponseTimeRule]

Am I missing something?

I am using the 1.2.1.RELEASE version of spring cloud.

**Comment by spencergibb** [comment]
@alfre86 spring-cloud-netflix uses the spring environment as the source of configuration. We add an adapter to archaius to read from the spring environment. We don't support the opposite.
