### ISSUE TITLE
Support runtime Hystrix changes via dynamic Archaius properties

### ISSUE THREAD

**Issue by brianlaframboise** [spring-cloud/spring-cloud-netflix#144]
I would like to be able to change the state of Hystrix commands, circuit breakers, etc at runtime based on configuration changes picked up via Spring Cloud Config `EnvironmentChangeEvent`s.

I can see that the current `HystrixAutoConfiguration` implementation bridges Archaius into the Spring environment by creating a Spring-based `ConfigurableEnvironmentConfiguration` that delegates Archaius property reads down to the current Spring Environment.

This works well with Spring Cloud Config for making Archaius configuration aware of Spring Environment properties at startup. Unfortunately, this appears to be a one-time binding, and does not change at runtime. That is to say I have changed the value of a Hystrix property in a Spring Cloud Config git repo, notified the application, and seen the `EnvironmentChangeEvent` fire - but the `HystrixCommandProperties` object remains the same. Upon application restart, the new property does take effect.

Specifically, I think Spring Cloud's `EnvironmentChangeEvent` and/or the `ConfigurableEnvironmentConfiguration` is not integrated with Archaius' configuration system which I believe requires events to be fired so that Archaius' `DynamicProperty`s can be notified of the configuration changes.

I tried implementing this integration myself using a Spring bean below to no avail:

```
  @Autowired
  private Environment env;

  @Autowired
  private ConfigurableEnvironmentConfiguration config;

  @Override
  public void onApplicationEvent(EnvironmentChangeEvent event) {
    Map<String, Object> changed = Maps.newHashMap();
    for (String key : event.getKeys()) {
      changed.put(key, env.getProperty(key));
    }
    ImmutableMap<String, Object> added = ImmutableMap.<String, Object> of();
    ImmutableMap<String, Object> deleted = ImmutableMap.<String, Object> of();
    WatchedUpdateResult result = WatchedUpdateResult.createIncremental(added,
      changed, deleted);
    DynamicPropertyUpdater updater = new DynamicPropertyUpdater();
    boolean ignoreDeletes = true;
    updater.updateProperties(result, config, ignoreDeletes);
  }
```

The [Archaius Users Guide wiki](https://github.com/Netflix/archaius/wiki/Users-Guide#provide-your-own-configuration-source-or-polling-scheduler) documents a way to achieve runtime configuration changes and so I believe this should be possible.

If it is in fact possible to pull off this integration with a little integration code (like what I have above, but working), documentation on how to do that would work instead. I don't strictly need the support implemented in the spring-cloud-netflix project.

**Comment by dsyer** [comment]
It should suffice to make your `@HystrixCommand` beans `@RefreshScope` and fire a /refresh when you want them to update. I agree that `@RefreshScope` probably isn't ideally necessary in this case (it should behave just like `@ConfigurationProperties`), so we can leave this open as an enhancement.

**Comment by brianlaframboise** [comment]
I made my `@HystrixCommand` beans `@RefreshScope` and POSTed to `/refresh` to no effect. I believe I can explain this, but Archaius is a little complicated in this regard so please bear with me as I walk through how I think this works.

The state of the property is not stored in the generated proxy of the `@HystrixCommand`-annotated method, so even though it was properly re-created it did not get the new property value.

The problem, I believe, is with the `HystrixPropertiesFactory`. It contains a static `ConcurrentHashMap` that appears to permanently cache the `HystrixCommandProperties` for a given `HystrixCommand` the first time it is executed. Short of disabling this caching via a custom `HystrixPropertiesStrategy` (which is [explicitly discouraged](https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/strategy/properties/HystrixPropertiesStrategy.html#getCommandPropertiesCacheKey%28com.netflix.hystrix.HystrixCommandKey,%20com.netflix.hystrix.HystrixCommandProperties.Setter%29) by the docs) there is no way to invalidate the cache.

That, however, is fine because the `HystrixCommandProperties` object is ultimately composed of `DynamicProperty` objects - and those objects are mutable. I believe mutating those `DynamicProperty`s in a similar way to Archaius' [AbstractPollingScheduler](https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/AbstractPollingScheduler.java) is ultimately what the solution will look like. But, instead of polling, the property mutation needs to be driven from an `EnvironmentChangeEvent` to be fully and seamlessly integrated with Spring Cloud Config.

The only problem with my theory is that's roughly what I tried to do with my code snippet above - which did not work. Perhaps you can see what I'm doing wrong? Whatever the solution I just hope we can figure something out here because being able to change Hystrix behaviour at runtime is one of its big selling points.

**Comment by brianlaframboise** [comment]
So I tried disabling the caching implicit in the `HystrixPropertiesStrategy` by substituting in my own strategy that bypassed the caching and the properties *still* were not updated.

This led me to discover a 2nd cache of `DynamicProperty` objects in the static `ALL_PROPS` map inside the `DynamicProperty` class itself. So not only does the `HystrixPropertiesFactory` cache the overall `HystrixCommandProperties` object, but the individual `DynamicProperty` objects that make up said `HystrixCommandProperties` object are also cached and retrieved "flyweight pattern"-style. This is another reason why `@RefreshScope` unfortunately won't cut it.

That led me to try again at connecting the `EnvironmentChangeEvent` with the Apache Commons Config way of propagating property change events, and this time I got it working with the following bean snippet:

```
  @Autowired
  private Environment env;

  @Override
  public void onApplicationEvent(EnvironmentChangeEvent event) {
    AbstractConfiguration manager = ConfigurationManager.getConfigInstance();
    for (String key : event.getKeys()) {
      for (ConfigurationListener listener : manager.getConfigurationListeners()) {
        Object source = event.getSource();
        // TODO: Handle add vs set vs delete?
        int type = AbstractConfiguration.EVENT_SET_PROPERTY;
        String value = env.getProperty(key);
        boolean beforeUpdate = false;
        listener.configurationChanged(new ConfigurationEvent(source,
          type, key, value, beforeUpdate));
      }
    }
  }
```

Through this event mechanism the statically cached `DynamicProperty` objects get mutated at runtime and the change takes effect at the next `HystrixCommand` execution as desired.

There's more work to be done to ensure that the `type` parameter is set to the right value for each possible state change (add, change, delete?) but at least it shows that the dynamic update problem can be solved. In fact, given that the `EnvironmentChangeEvent` is received after the environment is changed, I'm not even sure if is possible to handle the add vs. set cases correctly. Do you have any ideas there? And, overall, do you think a polished version of this could make its way into `ArchaiusAutoConfiguration` as default behaviour?

**Comment by spencergibb** [comment]
So, basically, your propagating change events down to Archaius, correct?  We currently don't have a way to tell if it was added or updated.  I think it's a good idea.

**Comment by brianlaframboise** [comment]
Correct. The current Spring-Archaius configuration bridge implemented by the `ConfigurableEnvironmentConfiguration` allows Archaius to read property values from the Spring `Environment`.

It works as expected ... but only at startup.  As I note above, once Archaius reads those property values they are cached in static variables in perpetuity. Once that happens you can put `@RefreshScope` wherever you want but it won't have any effect. Archaius will simply never read from the Spring `Environment` ever again.

Therefore to see a runtime change you need to push the change to those statically cached `DynamicProperty` objects. In practice that means publishing an Apache Commons-based `ConfigurationEvent` through the `ConfigurationManager`. By doing so those long-lived `DynamicProperty`s are able to update themselves in-place at runtime - the way Archaius expects. Only then are Archaius' caches and the Spring `Environment` back in sync.
