### ISSUE TITLE
Spring Cloud Netflix Not Compatible for Tomcat 7.0.X (Servlet API 3.0.1)

### ISSUE THREAD

**Issue by vasandharaj** [spring-cloud/spring-cloud-netflix#1447]
Dear Team, 

I have found that the RibbonRoutingFilter.java, FormBodyWrapperFilter.java etc. are using the **getContentLengthLong ()** from **servlet 3.1 API**.  So we are not able to deploy our application to Tomcat 7.0.65 which has Servlet API 3.0.1

We are using the Spring cloud netflix **1.2.0.RELEASE** version in our application

It would be great if you make it compatible for Servler 3.0.1 API too.

**Comment by ryanjbaxter** [comment]
@vasandharaj thans for pointing this out.  We are working on a solution.

**Comment by vasandharaj** [comment]
@ryanjbaxter I have tested the compatibility issue with the latest build (1.2.3. it working fine 

Thanks a lot Mr. Ryan Baxter.
