### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by zhupengcheng** [spring-cloud/spring-cloud-netflix#1453]
When using Eureka Server, I shutdown a Eureka Instance, I know Ribbon\Feign\Turbin can know this thing through Time Tick Query, but I want to know can I notify them immediately through push notification or some other ways? thx very much

**Comment by ryanjbaxter** [comment]
I don't think anything like this is built into Spring Cloud currently.

**Comment by zhupengcheng** [comment]
Thank you! But I know when application config is changed, Spring Cloud Config Server use Spring Cloud Bus  push notify application, do you have a plan like this?

**Comment by spencergibb** [comment]
We own config server, but eureka is upstream.

**Comment by zhupengcheng** [comment]
I mean is when Eureka Instance updated, Eureka Server can use MQ notify Eureka Client immediately, like Eureka Config Server do that.

**Comment by ryanjbaxter** [comment]
I think what @spencergibb is saying is if you want an enhancement like that you should open an issue in Netflix Eureka.
