### ISSUE TITLE
Calling backend services from zuul api gateway results in internal HATEOAS link addresses

### ISSUE THREAD

**Issue by maxvader** [spring-cloud/spring-cloud-netflix#1454]
Hi, we are struggling with this problem:
we have a spring boot application which has "@EnableZuulProxy" annotation & routes configuration acting as a gateway and as an api proxy.
As a gateway the usual "x-forward-*" headers are added to requests for backend services wich return resources with correct (aka proxed) HATEOAS links.

But Controllers registerend on the proxy do some calls to the same services (they aggregate data from different services) and the resources they get (and return to caller) all have internal HATEOAS links.

What can we do to have those links with the right addresses?
Can we call manually some zuul filter or util ?
We would like to avoid having to manually add headers wich is very error prone.

We tried with eureka + ribbon logical name and without them using phisical addresses but nothing changed.
Thank you.

**Comment by maxvader** [comment]
wanted to mark as question but didn't find the option...

**Comment by ryanjbaxter** [comment]
shouldn't the (aggregation) service which is making the requests to the other services also forward on the 'x-forward-*' headers as well?  That would cause the downstream services to return links with the correct URL (to the proxy) in them.

**Comment by maxvader** [comment]
Yes sure, but since those headers are exactly the same that zuul creates
for proxed requests, and since they partially depend on it's internal
configuration , I hoped that there was a way to let it handle them...
I'm already working on a procedure to add headers manually, but is a code
duplication and I will have to keep it up to date with zuul routes.
It would have been cool to autowire something and call it passing url and
getting headers...

Il 08 nov 2016 8:27 PM, "Ryan Baxter" <notifications@github.com> ha scritto:

**Comment by ryanjbaxter** [comment]
I guess I am not understanding the problem then...

The request comes through Zuul to the aggregation service.  This request should have the `x-forward-*` headers one it.  The aggregration service will then make requests to other downstream services.  The requests to the downstream services should have the same `x-forward-*` headers on it pointing to the Zuul proxy.  Why don't the URLs returned not point to the proxy?

**Comment by maxvader** [comment]
I created a small example :

`
@SpringBootApplication
@EnableZuulProxy
public class ApiGateway {
    public static void main(String[] args) {
        SpringApplication.run(ApiGateway.class, args);
    }

    @Bean
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }

    @RestController
    @RequestMapping("/api-gateway")
    public class ApiGatewayController {
        private RestTemplate restTemplate;

        @Autowired
        public ApiGatewayController(RestTemplate restTemplate) {
            this.restTemplate = restTemplate;
        }

        @RequestMapping(value = "/{examId}",
                produces = MediaType.APPLICATION_JSON_VALUE,
                method = RequestMethod.GET)
        public HttpEntity<Resource<SomeData>> exam(@PathVariable Long examId) {

            ParameterizedTypeReference<Resource<SomeData>> parameterizedTypeReference
                    = new ParameterizedTypeReference<Resource<SomeData>>() {
            };

            ResponseEntity<Resource<SomeData>> parsed = restTemplate.exchange(
                    "http://someFirewalledBackendService/{examId}?projection=whatever",
                    HttpMethod.GET,
                    null,
                    parameterizedTypeReference, examId);

            Resource<SomeData> someDataResource = parsed.getBody();

            return new HttpEntity<>(someDataResource);
        }
    }

    private class SomeData {
        //Something...
    }
}`

In someDataResource the HATEOAS links have an "internal" address, because the request to the controller is not intercepted and enriched by Zuul.

**Comment by ryanjbaxter** [comment]
So where is the request coming from then?  The incoming request is not coming through Zuul?

**Comment by maxvader** [comment]
The request comes from the web -> zuul gateway on "/api-gateway" endpoint -> back-end services
Is the architecture proposed by Josh Long in the videos...  https://youtu.be/SFDYdslOvu8?t=2493 
So there is an active instance of Zuul in the application BUT it doesn't intercept this kind of request and doesn't add any header.
I was trying to find a way to use that active instance methods to create headers on demand.

**Comment by ryanjbaxter** [comment]
If the requests are not going through the proxy nothing special will happen.  It if going to be up to you to get those headers added.  You could use a `ClientHttpRequestInterceptor` in your `RestTemplate` to add the proper headers to every request sent via the `RestTemplate`.
