### ISSUE TITLE
Sidecar app root url shows three static links.

### ISSUE THREAD

**Issue by slindenberg** [spring-cloud/spring-cloud-netflix#1456]
The Spring app having @EnableSidecar as an annotation displays a list of three static links. It would be nice to have a possibility to overwrite this page/mapping. That way it could host a non-Jvm app itself.

![threelinks](https://cloud.githubusercontent.com/assets/2778907/20170819/21adc7d8-a72e-11e6-82ad-151b5a5c3730.PNG)

**Comment by ryanjbaxter** [comment]
I imagine you can do this by providing your own `SidecarController` bean
https://github.com/spring-cloud/spring-cloud-netflix/blob/758ff920fc71d9a2aaf41d1250d3cc5ddd46b870/spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarController.java

**Comment by slindenberg** [comment]
Ah, I tried adding another RestController and got "already mapped" exception, or so.

Now that I put a new SidecarController into package "org.springframework.cloud.netflix.sidecar" and removed the "home()" method, it worked. Thank you!
