### ISSUE TITLE
Can I make url and path of feign client dynamic?

### ISSUE THREAD

**Issue by LucasHCruz** [spring-cloud/spring-cloud-netflix#1458]
Like:
```
@FeignClient(url=''somethindynamic')
public class MyClient{

    @RequestMapping(path="somethingDynamic")//someway to put url here? <<
    void call()
}
```

**Comment by spencergibb** [comment]
putting a full url in the `@RequestMapping` doesn't make much sense. I believe that they both support placeholders as well (ie `${my.prop}`).

**Comment by LucasHCruz** [comment]
I want to use with quartz.. so my basejob will call an Url for real job
service...

The job data contain the Url that I want to pass do Feign

Em Sex, 11 de nov de 2016 18:02, Spencer Gibb <notifications@github.com>
escreveu:

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by mikehfaber** [comment]
Is there a way to do this?

One use case is if I want to call a Spring actuator endpoint, but I want to call it for multiple services. Each service sits at its own hostname, and eg. we want to make a health check call to each one.

My use case isn't that exactly, but there's an endpoint that's the same for multiple services, and I want to decide which one I want to call at runtime. Each service has its own hostname.

**Comment by spencergibb** [comment]
@mikehfaber not with `@FeignClient`. That's not really the use case for feign. It's generally tied to a single host (or a group of hosts that are the instances of the same service). You'd have to write a bunch of custom code (I'm sure it could be done), but it would be simpler and more straight forward to use `RestTemplate` or `WebClient` in that case.

**Comment by tkruse** [comment]
The obvious reason to want to do this in normal cases is to use local/dynamic ports generated in integration tests e.g. using a wiremock server, with ports having to be dynamic because the environment where the tests run may not be able to provide any fixed port number all the time.

**Comment by kinggggg** [comment]
now i can use placeholder ie ${my.prop} That‘s cool！
