### ISSUE TITLE
Consider delombok before GA

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#146]
Lombok is pretty sweet but it does add an extra layer that users need if they want to contribute. It might be worth considering if it should be removed before GA.

**Comment by dsyer** [comment]
It only means they have to add an agent to the IDE if they use one, and the build works out of the box (no-one complained yet). I'm not sure I want to do this to be honest (look at how many properties there are in `EurekaClientConfigBean`).
