### ISSUE TITLE
Allow passing OPTIONS through 

### ISSUE THREAD

**Issue by maczikasz** [spring-cloud/spring-cloud-netflix#1460]
Hi,

we need OPTIONS request to forwarded to the target host, but spring mvc will handle them no matter what I set with ANY of the CORS settings.

The reason for this is that ZuulController actually extends AbstractController which will handle OPTIONS in a hardcoded way

`if (HttpMethod.OPTIONS.matches(request.getMethod())) {
			response.setHeader("Allow", getAllowHeader());
			return null;
 }`

I could circumvent this by putting a new AbstractController on the classpath, but that's not a nice solution. I could raise the issue on the webmvc tracker but I believe it would get rejected

**Comment by ryanjbaxter** [comment]
There were some recent changes in `ZuulController` that I think solve the problem 
https://github.com/spring-cloud/spring-cloud-netflix/commit/7f075d11ee56d57fa1a38a7d02555f9b8c3ed95e
Can you try the latest Camden SNAPSHOTS?

**Comment by danielclasen** [comment]
Camden.SR2 (Spring Cloud Netflix 1.2.2.RELEASE) fixed the issue for me

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
