### ISSUE TITLE
help:maven project,zuul rout url, url param be changed

### ISSUE THREAD

**Issue by krowkrow** [spring-cloud/spring-cloud-netflix#1467]
maven project
 `<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zuul</artifactId>
            <version>1.2.2.RELEASE</version>
        </dependency>`

after route,  url param be changed, encoding not uft8.
how can i do

**Comment by spencergibb** [comment]
I'm afraid there isn't enough information provided for us to help

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
