### ISSUE TITLE
[Question] Netflix Eureka, REST Clients, and Thrift Services production deployment

### ISSUE THREAD

**Issue by filpano** [spring-cloud/spring-cloud-netflix#1469]
I am using Spring Cloud's Netflix `Eureka`, together with Ribbon and Zuul for a microservice architecture. Currently, the services look similar to the following:

    Books
    |
    |- Books REST API
    |- Books Backend
    |- Books Datastore

The REST API  and the Backend are both `Eureka Client`s - they should both be able to consume *and* produce registrations to the `Eureka Server`.

The REST API uses `Spring Boot`, `Ribbon` and a `LoadBalancingTcpClient` to speak to the Backend (which is a `Thrift` server).

I currently have a single `Eureka Server` that also uses `Zuul` for routing in front of the services. So, whenever a user hits e.g. `api.mystuff.com/books` the request would actually get proxied by `Zuul` to wherever the `books` service is running (e.g. `api.mystuff.com/books/titles` -> `internal.bookhost/titles`).

I had the following few questions here:

1. In production, how would I expose the API publicly? Would I have yet *another* layer before the `Eureka Server`? Would I have something like `HAProxy` that forwards the requests to any number of synchronized `Eureka Server`s?

2. How does a typical multi-datacenter deployment of Eureka look like? Is there any synchronization and routing possible between data centers? How does Netflix do it? Do they simply use the various AWS regions as closed entities? If so, how do they synchronize their datastores?

**Comment by ryanjbaxter** [comment]
1.  Why are you concerned about having another layer infront of Eureka?  Do you mean Zuul?
2.  I suggest you read this wiki page https://github.com/Netflix/eureka/wiki/Eureka-at-a-glance.  Eureka can use peer replication to replicate instance data between zones.  I dont think Netflix recommends replicating information between regions though.

**Comment by filpano** [comment]
Hi, Thanks for the reply. As for your comments and questions:

1. It's not really a concern. I was only trying to figure out what parts would ideally be publicly exposed (i.e. Eureka Server? Just Zuul? Both?).

2. Very iInteresting information, thanks for the link!

I had an additional question, if I may:

For my Backend service (using Thrift), I was initially using Spring Boot and a `Bean` that starts a Thrift server at some port and registers it in a local cache for lookup. Ideally now, I would want the Thrift server to be registered to the `Eureka Server` so that I can open TCP connections to it directly instead of having two apps running.

However, something odd happens when I switch to a standalone Eureka Client discovery mechanism (i.e., no Spring Boot):

`Injector injector = Guice.createInjector(Modules.override(new EurekaModule()).with(new MyEurekaModule()));  // override with non-AWS config` 
`DiscoveryClient backendEurekaClient = injector.getInstance(DiscoveryClient.class);`

In my `eureka-client.properties`, I have the following hostname setting: 

`eureka.instance.hostname=srv-dev.domain.local`

However, the Eureka Client seems to register itself with **just** `srv-dev`. My REST API, which is a `@SpringBootApplication`, correctly registers itself with `srv-dev.domain.local:${port}`.

Some other settings as well, like `eureka.instance.lease-renewal-interval-in-seconds=10`, do not seem to be taken into consideration at all. Have you encountered this behaviour before?

**Comment by ryanjbaxter** [comment]
1.  I dont see any reason to expose Eureka.  If Zuul is serving as an API gateway than that would make sense to expose publicly.

Please open a separate issue for your other question.  However if the app is not using Spring Cloud and just using vanilla Eureka, I suggest you open an issue in the Eureka repo.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
