### ISSUE TITLE
Switch to commons-logging

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#147]
If you're not using many features of SLF4J you might want to consider switching to commons-logging since that's what Spring Framework and Spring Boot already use.

**Comment by dsyer** [comment]
Spring Data uses SLF4J. I'd be happier with Commons Logging too though, since we build on Boot. Can you take care of that @spencergibb ?

**Comment by spencergibb** [comment]
Does commons logging support string interpolation? 
```
log.info("Removing application {} from eureka", this.instanceConfig.getAppname());
```

**Comment by dsyer** [comment]
No. You have to build the string with concatenation.

**Comment by aheusingfeld** [comment]
> I'd be happier with Commons Logging too

@dsyer that's interesting to me: Is it because you're used to CL or are there advantages over slf4j which I didn't notice, yet?

**Comment by dsyer** [comment]
There are no advantages I know of technically speaking. It's just a question of aligning the dependencies. Of course it users can still take advantage of slf4j features in their code.
