### ISSUE TITLE
Single<RedirectView> is not supported

### ISSUE THREAD

**Issue by piotrturski** [spring-cloud/spring-cloud-netflix#1472]
in spring mvc, one can return `RedirectView` that will cause redirect. however when returning `Single<RedirectView>` no redirect is triggered. instead `RedirectView` object is simply serialized using json and status 200 is returned

**Comment by piotrturski** [comment]
same with string "redirect:http://some.address.com"

**Comment by spencergibb** [comment]
I'm going to say that spring-cloud-netflix will not be implementing this, but we will let spring-framework 5 and the reactive web story there.
