### ISSUE TITLE
how to use spring-cloud without spring-boot?

### ISSUE THREAD

**Issue by PowerBin** [spring-cloud/spring-cloud-netflix#1476]
I have many older spring-mvc projects which use spring.xml config,and how can I use spring-cloud without spring-boot?

Thank you very much!!!

**Comment by spencergibb** [comment]
Unfortunately, Spring Cloud was built on Spring Boot deliberately. You can use different Netflix components on your own, but you would need to set it all up yourself. See the Netflix GitHub org.
