### ISSUE TITLE
When should I use @EnableZuulServer?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1477]
I've learned that the @EnableZuulServer annotation is used to  set up the application to act as a generic Zuul server without any built-in reverse proxy features.
And I've seen the document [http://cloud.spring.io/spring-cloud-static/Camden.SR2/#_plain_embedded_zuul](http://cloud.spring.io/spring-cloud-static/Camden.SR2/#_plain_embedded_zuul) .

But I'm still confusing when should I use this annotation. 
In my opinion, we should always use the @EnableZuulProxy annotation.
But When I come to this page [https://github.com/spring-cloud/spring-cloud-netflix/issues/104](https://github.com/spring-cloud/spring-cloud-netflix/issues/104) , I know there may have some use case for  @EnableZuulServer annotation.

But what's it? What's the use case of @EnableZuulServer?

**Comment by spencergibb** [comment]
It is blank zuul with no filters installed.

**Comment by eacdy** [comment]
@spencergibb I know it, but I cannot figure out when to use a blank zuul.

**Comment by wwwlll2001** [comment]
@spencergibb could you kindly explain that what is the meaning of "blank zuul", does it means that the server mode of zuul could not be used for routing? Per my test, it does so, I have read some source code , and found that in ZuulHandlerMapping.java, it only register the ZuulController as the handler of routes which I configured in the bootstrap.yml.But the request is not sent to my service, so, could you kindly provide some help, thanks very much

**Comment by spencergibb** [comment]
There are no routing filters installed. Routing is left to the user.  See [ZuulServerAutoConfiguration](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration.java) vs [ZuulProxyAutoConfiguration](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyAutoConfiguration.java)

**Comment by 1011178l** [comment]
404 for the two links. Can you kindly short explain what's the difference of them? The name itself is hard to understand and there is not too much documents to explain this
