### ISSUE TITLE
Replace @ConditionalOnExpression with @ConditionalOnProperty

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#148]
`@ConditionalOnExpression` can be expensive to evaluate, you might want to consider `@ConditionalOnProperty` instead.

Here's a Spring Boot commit that did the same https://github.com/spring-projects/spring-boot/commit/dca637f51fa3d1ff99a03590b1ed232a92a72888.

**Comment by dsyer** [comment]
Done (commit 0e4eb9e).
