### ISSUE TITLE
Ribbon timeout not dynamically changed with Zuul

### ISSUE THREAD

**Issue by ImFlog** [spring-cloud/spring-cloud-netflix#1481]
Hello,
While configuring a config-server, I noticed a bug with Ribbon timeouts. I am trying to change the timeouts but It doesn't work. The property clearly changes (as seen in /env) but the values are not used during http calls. I tried with ribbon only and everything works fine, when I add Zuul, the reloading doesn't work anymore.

How to reproduce:
An example is available here: https://github.com/garciafl/spring-cloud-timeouts
1. Load the client app while config app is working
2. The timeout configuration is correctly set, a GET on /test /sleep on the client should be OK if timeout < 1s KO else.
3. Change the value in gitConfig/client.yml and push
4. POST on localhost:8080/refresh
5. If you hit the /test/sleep again, the new timeout configuration is not used (but /env shows the correct settings).

I browsed the code around the ribbon's clients `execute` method but It seems that timeout configurations are always set when building the http client. I can't find where the issue is.

If someone could explain me where to look, I am willing to help to fix this as quick as possible :)
Thank you

**Comment by ryanjbaxter** [comment]
I have not looked into this yet, but my guess is that the bean containing the configuration value does not have `@RefreshScope` set on it so it will not refresh the value.

**Comment by garciafl** [comment]
Also what I was looking but the Refresh mecanism is still obsucre for me ...

**Comment by ImFlog** [comment]
@ryanjbaxter I think I found where the issue is, in RibbonClientConfiguration.java : 
```
@Configuration
@ConditionalOnProperty(name = "ribbon.httpclient.enabled", matchIfMissing = true)
protected static class HttpClientRibbonConfiguration {
	@Value("${ribbon.client.name}")
	private String name = "client";

	@Bean
	@ConditionalOnMissingBean(AbstractLoadBalancerAwareClient.class)
	public RibbonLoadBalancingHttpClient ribbonLoadBalancingHttpClient(
			IClientConfig config, ServerIntrospector serverIntrospector,
			ILoadBalancer loadBalancer, RetryHandler retryHandler) {
		RibbonLoadBalancingHttpClient client = new RibbonLoadBalancingHttpClient(
				config, serverIntrospector);
		client.setLoadBalancer(loadBalancer);
		client.setRetryHandler(retryHandler);
		Monitors.registerObject("Client_" + this.name, client);
		return client;
	}
}
```
When the bean is created, ```initWithNiwsConfig```is called which sets the timeouts but the values are never updated. I naively tried to add ```@Refreshscope``` on the bean but I get the following error :
```java.lang.IllegalStateException: No Scope registered for scope name 'refresh'``` and I don't know what to do to fix that. Any help ?

**Comment by ryanjbaxter** [comment]
I was actually looking into this today.  I think I have a potential solution to the problem.  I should have an update tomorrow.

**Comment by ImFlog** [comment]
Thank you @ryanjbaxter !
