### ISSUE TITLE
PreDecorationFilter brokes ControllerLinkBuilder

### ISSUE THREAD

**Issue by 01sas** [spring-cloud/spring-cloud-netflix#1489]
After [this](https://github.com/spring-cloud/spring-cloud-netflix/commit/a38b7b71ac8be9608ac2530dac41cd6298d696cf#diff-8a3a3948fd59a02ea4234d960437c3a0l) change in *PreDecorationFilter* **ControllerLinkBuilder** from Spring Hateoas project starts to fail with exception:
```
java.lang.NumberFormatException: For input string: "443,443"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_102]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_102]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_102]
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.getBuilder(ControllerLinkBuilder.java:261) ~[spring-hateoas-0.20.0.RELEASE.jar!/:na]
	at org.springframework.hateoas.mvc.ControllerLinkBuilderFactory.linkTo(ControllerLinkBuilderFactory.java:132) ~[spring-hateoas-0.20.0.RELEASE.jar!/:na]
	at org.springframework.hateoas.mvc.ControllerLinkBuilder.linkTo(ControllerLinkBuilder.java:172) ~[spring-hateoas-0.20.0.RELEASE.jar!/:na]
```

And the reason for this is that now *PreDecorationFilter* always adds a pair of ports which is not expected by **ControllerLinkBuilder**. I expect that many more components can fail because of this change and it need to be reverted.

Actually current implementation of *PreDecorationFilter* looks very weird as it is expected that Servlet Container should properly handle this header (RemoteIpValve in Tomcat, for example) and provide a valid value in ctx.getRequest().getServerPort(). So it is only required to configure Servlet Container.

**Comment by 01sas** [comment]
And it is not secure to use X-Forwared-* headers like this. RemoveIpValve for Tomcat for example only accept these headers only if request came from trusted client, otherwise anybody from outside can set this header to affect system behavior.

**Comment by ryanjbaxter** [comment]
The `NumberFormatException` sounds like a bug in `ControllerLinBuilder`.  It is valid to have a comma separated list of ports as the value of `X-Forwarded-Port`.

As for the security concern, I am not sure I understand, can you elaborate?

**Comment by 01sas** [comment]
Yes, I can agree that it can be a bug in ControllerLinkBuilder. It is allowed to have a several values (it still looks very weird to me, but it is legal, you are right).

The security concern is (at least in the way how I understand it looking at RemoteIpValve from Tomcat) is that header can be sent by anybody. It can be not your proxy, but some over one which tries to use your service illegally (for example to overcome cross-origin problem while you does not allow to receive request from another origin). So it is required to check that you receive these headers from trusted server/proxy.

**Comment by spencergibb** [comment]
We have to send `X-Forwarded-*` ports to downstream services. How would `RemoteIpValve` help with that?

**Comment by ryanjbaxter** [comment]
@01sas I suggest you open an issue in the HATEOS project for the `ControllerLinkBinder` issue https://github.com/spring-projects/spring-hateoas

**Comment by 01sas** [comment]
@spencergibb it will not help you with sending headers. It will only help with detection of correct port, host, proto and so on. So the logic which was originaly in this class is enough from my point of view.

@ryanjbaxter, ok I will open a ticket in HATEOS project. Thanks.

**Comment by 01sas** [comment]
This issue already exist: https://github.com/spring-projects/spring-hateoas/issues/509
