### ISSUE TITLE
Consider dropping protected or package fields

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#149]
Several classes (e.g. `AbstractDiscoveryLifecycle` & `ServletWrappingEndpoint`) have protected or package scope fields. It's worth considering if these should be switch to private with a protected setter if necessary.

The problem with protected fields is very difficult to change them in the future where as the implementation of protected methods can be changed.

**Comment by dsyer** [comment]
Agree. Can you have a look at thise @spencergibb ?
