### ISSUE TITLE
why the response header of my app miss the content-length when it pass the gateway layer

### ISSUE THREAD

**Issue by jelen56** [spring-cloud/spring-cloud-netflix#1497]
I have used spring cloud to build a multiple microservice,and i use a API-Gateway implemented using Spring Cloud Netfix's Zuul Server to route the requests to our micro services ,the gateway config like this(learn from https://gist.github.com/tiarebalbi/062a814d063ee694bbf6):

https://gist.github.com/jelen56/e70663b1b88d9ae16f6d69f7fa4048b7

when i passing througth the gateway layer,the response header is missing content-length,but it has the content-length when i directly invoke backend service.

**Comment by spencergibb** [comment]
Why do you have `sensitiveHeaders: "*"`?

**Comment by jelen56** [comment]
Does't it mean to pass all the response headers from other inner service?ps:sorry,i am late to respond you.

**Comment by spencergibb** [comment]
IIRC it means don't pass *any* headers.

**Comment by jelen56** [comment]
I have no idea for this issue,what do you think I should do?

**Comment by spencergibb** [comment]
have you tried removing the sensitiveHeaders config entry, or setting it to ''.

**Comment by ryanjbaxter** [comment]
closing do to lack of feedback
