### ISSUE TITLE
Concurrency level

### ISSUE THREAD

**Issue by dschroe** [spring-cloud/spring-cloud-netflix#1499]
Is there any existing and useful documentation how to increase the concurrency level properly for components such as Zuul, Ribbon, Feign, Hystrix...?

In the official netflix docu i found out that the embedded hystrix component for zuul and hystrix per default only supports 10 concurrent requests...all other concurrent requests on top will be rejected...

On stackoverflow i found the following question:
http://stackoverflow.com/questions/38368431/couldnt-acquire-semaphore-zuul-configuration

In this example he tries to increase the concurrency level for zuul. But i am not sure if it is necessary to change a whole bunch of ribbon, hystrix and zuul properties...i mean there is no official spring documentation of what this properties are doing...there is no code completion in my yaml file...so i do not even know if these properties still exist in the current spring parent version 1.4.2 & Brixton SR6...

Any help is appreciated.

**Comment by ryanjbaxter** [comment]
I believe most of those ribbon and hystrix properties should work in Brixton.SR6.  I am unsure about the Zuul ones.  I think we need more specifics on if something is not working in order to try and address any potential issues.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
