### ISSUE TITLE
Ensure `prefix` is used with `@ConfigurationProperties`

### ISSUE THREAD

**Issue by philwebb** [spring-cloud/spring-cloud-netflix#150]
I noticed some `@ConfigurationProperties` annotations that don't use the prefix attribute (`@ConfigurationProperties("hystrix.stream.amqp")` for example). You should use prefix to ensure that flexible binding will work.

**Comment by dsyer** [comment]
Why? Isn't "prefix" a synonym of "value" (the Javadocs of `@ConfigurationProperties` say so)?

**Comment by philwebb** [comment]
Whoops. My mistake. I was getting confused with `@ConditionalOnProperty`.
