### ISSUE TITLE
Deprecated Ribbon Clarification

### ISSUE THREAD

**Issue by yukatan** [spring-cloud/spring-cloud-netflix#1501]
Hi

I'm looking at some issues and I need some clarification about ribbon in camden release. Is it deprecated?? I mean, I rode that ribbon is not the default in camden but I don't know if is ribbon or just the http client used by riboon.

I still see ribbon in the documentation and don't see any reference about ribbon deprecation. Are ribbon config properties working in the same way???

Thanks in advance

**Comment by spencergibb** [comment]
The ribbon http client in zuul is no longer the default.

**Comment by yukatan** [comment]
So ribbon is still there with other http client?? right??

**Comment by spencergibb** [comment]
Yes, only the http client default has changed.
