### ISSUE TITLE
How can I use groovy zuul filters?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1502]
How can I use groovy dynamic zuul filters?

I've seen a issue here [https://github.com/spring-cloud/spring-cloud-netflix/issues/223](https://github.com/spring-cloud/spring-cloud-netflix/issues/223) 
Is there any sample for reloading groovy filters?

**Comment by spencergibb** [comment]
issue #223 means it hasn't happened yet. Closing as duplicate.

**Comment by eacdy** [comment]
@spencergibb 
Do you mean that Spring Cloud does not support reloading zuul filters dynamicly?

**Comment by spencergibb** [comment]
That's what I'm saying. #223 is an open issue to implement it as an enhancement.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by eacdy** [comment]
@spencergibb
I've found this :
[https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java](https://github.com/spencergibb/halfpipe/blob/master/halfpipe-router/src/main/java/halfpipe/router/FilterIntializer.java)

```
private void initGroovyFilterManager() {

        //TODO: pluggable filter initialzer
        FilterLoader.getInstance().setCompiler(new GroovyCompiler());

        final String scriptRoot = props.getFilterRoot();
        LOGGER.info("Using file system script: " + scriptRoot);

        try {
            FilterFileManager.setFilenameFilter(new GroovyFileFilter());
            FilterFileManager.init(5,
                    scriptRoot + "/pre",
                    scriptRoot + "/route",
                    scriptRoot + "/post"
            );
        }
        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```
It seems that we can reload zuul filters per 10s.
==
So, I'm getting confused.

**Comment by spencergibb** [comment]
I'm not saying we can't in the future, just that we haven't.

**Comment by spencergibb** [comment]
Please direct any comments to #223

**Comment by eacdy** [comment]
@spencergibb OK, I've comment to #223
