### ISSUE TITLE
Eureka server register some services with wrong IPs

### ISSUE THREAD

**Issue by LucasHCruz** [spring-cloud/spring-cloud-netflix#1503]
A have an eureka server that register some services with Jenkins IP but the config is the same in wrong cases and right cases.

Like:

```
application.yml of project A and B:
info:
  name: @project.name@
  version: @project.version@

banner:
  location: classpath:banner.txt

server:
    port: 7400 #7300 for project-b
    display-name: project-a #project-b too
eureka:  
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7700/eureka/
  instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
      preferIpAddress: true 
```

In Eureka server interface I'm clicking in STATUS link and the project A redirects to `{project-a}/info` but project-b redirects to `{Jenkins IP}/info`

I searched for something different in Jenkins config or project config but I didn't found anything...

Could someone tell me or help me to know where eureka gets the service ID?

I just need a light to debug or something like this...

Edit:

All the projects are in the same machine.

**Comment by spencergibb** [comment]
Spring Cloud tries to make a guess as the the IP that should be used. There are some configuration options for this http://cloud.spring.io/spring-cloud-static/Camden.SR2/#ignore-network-interfaces.

Otherwise you need to set `eureka.instance.ip-address` specifically.

**Comment by LucasHCruz** [comment]
That is it... Thank you!!
