### ISSUE TITLE
Ribbon: use "DummyPing" instead of "NoOpPing"

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1504]
`com.netflix.loadbalancer.NoOpPing` is used by default if no other `IPing` instance is created in the context.

However, `com.netflix.loadbalancer.BaseLoadBalancer` uses the following heuristics to determine if it should schedule a period Ping of the registered servers:
```
    private boolean canSkipPing() {
        if (ping == null
                || ping.getClass().getName().equals(DummyPing.class.getName())) {
            // default ping, no need to set up timer
            return true;
        } else {
            return false;
        }
    }
```

As you notice, no ping will be scheduled when a `DummyPing` is used. Since `DummyPing` and `NoOpPing` are actually doing exactly the same thing - it would be nice if SpringCloud's default were changed - this would save a couple extra threads, especially when used with Zuul.

**Comment by brenuart** [comment]
Small question: is _help wanted_ means a PR is welcome - or does it mean you need more information ?

**Comment by spencergibb** [comment]
PR Welcome
