### ISSUE TITLE
Ribbon is not honoring ribbon.ServerListRefreshInterval attribute

### ISSUE THREAD

**Issue by surajrrao** [spring-cloud/spring-cloud-netflix#1508]
On debugging found that in PollingServerListUpdater class the first constructor gets called where the refresh interval is hard coded to 30 sec. Is it a bug? or am i missing something in my configuration?.

*****************FIRST Constructor******************
    public PollingServerListUpdater() {
        this(LISTOFSERVERS_CACHE_UPDATE_DELAY, LISTOFSERVERS_CACHE_REPEAT_INTERVAL);
    }

*****************SECOND Constructor******************
    public PollingServerListUpdater(IClientConfig clientConfig) {
        this(LISTOFSERVERS_CACHE_UPDATE_DELAY, getRefreshIntervalMs(clientConfig));
    }

**Comment by lowzj** [comment]
I think it's duplicate with https://github.com/spring-cloud/spring-cloud-netflix/issues/1304
