### ISSUE TITLE
spring-cloud-feign not support POST request entity

### ISSUE THREAD

**Issue by 924060929** [spring-cloud/spring-cloud-netflix#1509]
@FeignClient(name="adhoc", url = "http://localhost:8288/adhoc/rest")
    ...
    @RequestMapping(value = "sql", method = RequestMethod.POST)
    JSONArray query(@RequestParam("sql") String sql) { ... }

I expect the request uri is 'http://localhost:8288/adhoc/rest/sql', and 'sql' param in the http entity.
But spring-cloud-feign change the uri to 'POST /sql?sql=select+count%28*%29+from+city'.

**Comment by lowzj** [comment]
I think you should use '@RequestBody' instead of '@RequestParam'.
