### ISSUE TITLE
update hystrix command properties dynamically

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1512]
@spencergibb Need urgent help.
Here I have few doubts regarding hystrix command properties.

1) We need to update hystrix command properties at run time. we are providing hystrix command properties in our config.properties:

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=10000

now at run time we are updating this hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds property using 

ConfigurationManager.getConfigInstance().setProperty("hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds", "20000");

But it does not work for default property , I need to provide command key to set timeout as 

ConfigurationManager.getConfigInstance().setProperty("hystrix.command.MyCommandKey.execution.isolation.thread.timeoutInMilliseconds", "20000");

So is there any way to update default property as well at run time?

2) I wanted to check for order of precedence while defining hystrix command properties using properties files(for example config.properties) AND @DefaultProperties Annotation at class level AND @HystrixCommand annotation . As if We define same property at all three places then which value will get precedence. as per my finding , value from @HystrixCommand properties is getting used but in that case how will we define environment based hystrix command properties if default property is being set at @HystrixCommand.

**Comment by spencergibb** [comment]
We use the Spring `Environment` as the source of truth. Have you tried that then calling `/refresh`?

**Comment by JagmohanSharma** [comment]
Actually I did not tried in this way.  Did your comment related to my second point? 

And by this , can we deregister the hystrixCommandAspect Bean as well at run time ?? as we are also integrating hystrix with application using normal Spring MVC but not spring boot where we are not able to make use of @ConditionalOnProperty to control hystrixCommandAspect bean registration.
