### ISSUE TITLE
Dynamic Zuul url using spring cloud netflix

### ISSUE THREAD

**Issue by reddynr** [spring-cloud/spring-cloud-netflix#1513]
Dear All,
I have a Zuul url which is working fine as of now, how ever based on a query parameter from the front end i need to change the url, could you please suggest how can i acheive that??

For example zuul.routes.myapplication.url=http://myserver:myport/myapplication/{**_queryparameterfromfrontend_**}/forms

**Comment by spencergibb** [comment]
You'd have to write a custom filter.

**Comment by reddynr** [comment]
I am trying to write the  same. Thank you.


Narendra...!

**Comment by ryanjbaxter** [comment]
@reddynr please reopen if you need additional help
