### ISSUE TITLE
NullPointerException in FeignContentGzipEncodingInterceptor

### ISSUE THREAD

**Issue by stp72** [spring-cloud/spring-cloud-netflix#1515]
The issue is with line 74.  If no content is in the request, i.e. a request has just PathParams, this causes a java.lang.NullPoinerException since nothing validates that contentLength is not null before checking its size.

**Comment by ryanjbaxter** [comment]
I guess I see how this could be possible, but in what scenario would you want to compress the content if there is no request body to compress?

**Comment by stp72** [comment]
There aren't any but how can you prevent the code from executing when you add it as a requestInterceptor in the Feign builder?

**Comment by spencergibb** [comment]
Closed via ec80797694d24db863122ceb25032a4efb2e3fe8
