### ISSUE TITLE
Excluded aws jars from eureka client

### ISSUE THREAD

**Issue by cpelka** [spring-cloud/spring-cloud-netflix#1518]
Hi,

while working on a new project I realised that upgrading from spring-cloud-netflix 1.2.0-RELEASE to 1.2.2-RELEASE broke the Eureka server with a class not found exception for `AWSCredentials`. After some research traversing the dependencies I saw that there was a commit removing all AWS specific dependencies from the Eureka core to save 5 MB.

The commit in question is: https://github.com/spring-cloud/spring-cloud-netflix/commit/e94c35d331cdbf6f71b4eae2fde9b62779d0553b#diff-cd92aa5b8506c477d5d024d91aa8dfb3

As I already commented on the commit, it makes things more complicated for projects using AWS services within a project that was designed to run in AWS.

I think there's a difference in excluding dependencies that are managed/replaced by the spring project(s) like Jackson, logging, httpclient etc. and the removal of dependencies without any replacement just to save some MB in the mid-tier-layer. I'd say that should be up to the concrete project implementation outside the scope of Spring Cloud (Netflix). 

Another point: I'm not sure if there is any documentation about the removal or hint which dependencies have to be explicitly included again to have it working in AWS. But for now the Eureka service does not work as described in the Netflix wiki.

Is there any chance to get this in again?

**Comment by spencergibb** [comment]
We've decided it should be optional. If you need it, just add the dependency.

**Comment by spencergibb** [comment]
Closed via e94c35d
