### ISSUE TITLE
Question on configuring ZuulFallbackProvider

### ISSUE THREAD

**Issue by madheshr** [spring-cloud/spring-cloud-netflix#1521]
Hi

  I was able to configure fallbacks for Microservices at Zuul level so that they are invoked whenever a service is down or not responding within a time period of 1sec.  I was able to implement the ZullFallback Provider and add custom logic for returning fallback response.  However my question is  how do i override parameters such as the default SLA time for each microservice?  Where to specify the options and what are the options available?

  For the Hystrix fallback, i can specify a set of properties using the commandKey.  Is there a equivalent way to do this for ZuulFallback?

Thanks
Vasanth

**Comment by ryanjbaxter** [comment]
A `ZuulFallbackProvider` is just a way of providing a Hystrix fallback for a given route in Zuul.  The Hystrix Command wrapping the route in Zuul should act like any other Hystrix Command and should be able to be configured the same way.  Were there configuration parameters you tried that did not work?  If you have something specifically that is not working please provide a sample that reproduces the problem so we can look into it.

**Comment by madheshr** [comment]
Hi Ryan
  There is no issue as such..  I am wondering where to specify the fallback options when we use a ZuulFallbackProvider.  Here's my scenario

-- Gateway configuration
zuul:
  routes:
    hello:
       path: /Hello/**
       serviceId: hello
       stripPrefix: false
       sensitiveHeaders: Cookie,Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false
  restclient:
    enabled: false
hello:
  ribbon:
    listOfServers: localhost:8096

-- End Gateway configuration

-- Microservice configuration
spring:
    application:
        name: helloworld-service
security:
    basic:
        enabled: false

server:
    port: 8096
    address: localhost
    use-forward-headers: true
tomcat:
    accessLogEnabled: true
    accessLogPattern: "%h %m"

springfox.documentation.swagger.v2.path: /Hello/api-docs
spring.cloud.config.discovery.serviceId: hello

-- End Microservice configuration

My ZuulFallback code at the gateway application level is referencing the route like this:
@Component
class HelloServiceFallbackProvider implements ZuulFallbackProvider {

	@Override
	public String getRoute() {
		return "hello";
	}

The fallback is triggered as expected when:
 1) The microservice is fully down
 2) The microservice takes more than 1s (default).  I tested by having a Thread.sleep for just below 1s and just above 1s

I have tried adding this in the microservice application.yml but it does not have any effect.  My expectation was that if the microservice takes longer than 500mS then it should fall back.

hystrix:
   command.hello.execution.isolation.thread.timeoutInMilliseconds: 500

**Comment by spencergibb** [comment]
What version are you using?

**Comment by madheshr** [comment]
spring-cloud version 1.2.4.BUILD-20161130
hystrix-core 1.5.6

**Comment by spencergibb** [comment]
it should go in zuul

**Comment by ryanjbaxter** [comment]
> Now, I am trying to reduce the Microservice SLA to 500mS instead of the default 1S. I am not sure where this setting should go. I have tried adding this in the microservice application.yml like this:

hystrix:
   command.hello.execution.isolation.thread.timeoutInMilliseconds: 500

Is that the proper YAML format, shouldn't it be 

```
hystrix:
  command:
    hello:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
```

You could also try setting the timeout for all Hystrix commands using 

```
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
```

**Comment by madheshr** [comment]
Thanks.  The YAML format was fine.  I agree the one you provided is more standardized.  I will try the default setting.

My main confusion was whether the Zuul serviceID  (as returned in the Fallback provider) corresponds to the Hystrix command key.  It looks like it does.
