### ISSUE TITLE
Feign client for external service adds addition protocol to url

### ISSUE THREAD

**Issue by m190** [spring-cloud/spring-cloud-netflix#1522]
I noticed, that Feign client for external service adds addition protocol to url, when using EL.

For that configuration:
```
@Configuration
@EnableAutoConfiguration
@EnableFeignClients(basePackages = "com.example.connector")
public class ApplicationConfig {
    @Bean(name = "EXAMPLE_URL")
    public String prUrl() {
        return "http://example.com/api";
    }
}
```
And using that client
```
@FeignClient(name = "exampleClient", url = "#{EXAMPLE_URL}" )
public interface ExampleClient{
    @RequestMapping(value = "/example", method = RequestMethod.GET)
    String getExampleValue();
}
```
The service URL is set to `http://http://example.com/api/example` instead of `http://example.com/api/example`.

**Comment by ryanjbaxter** [comment]
I believe you found a bug here :)

The problem is in `FeignClientsRegistrar`
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsRegistrar.java#L245
