### ISSUE TITLE
Question: Hystrix dashboard and HTTPS API

### ISSUE THREAD

**Issue by berge616** [spring-cloud/spring-cloud-netflix#1523]
How would I be able to connect to an API that is only listening on HTTPS rather than HTTP?

**Comment by spencergibb** [comment]
Can you give a little more description?

**Comment by berge616** [comment]
Sure, so we have an API that is emitting the hystrix.stream endpoint, but it is over https not http. When I stand up the hystrix dashboard, and put in the endpoint(https://...hystrix.stream) it throws an unable to connect error because the certificate is not in place for the SSL connection. Does the hystrix dashboard connect to API's that are listening on HTTPS or only http? If https, where would i put the certificate to enable the connection.

**Comment by ryanjbaxter** [comment]
You might want to read through https://github.com/spring-cloud/spring-cloud-netflix/issues/1254.  At a high level the certificate needs to be trusted by the JVM, so it needs to be installed in the JVM.
