### ISSUE TITLE
how to set zuul.debug.host

### ISSUE THREAD

**Issue by AlexWei2013** [spring-cloud/spring-cloud-netflix#1524]
I create a filter which extended SurgicalDebugFilter to route some request to another service for gray deployment.
I set the zuul.debug.host or zuul.debug.vip  like  "zuul.debug.host=http://localhost:9900".
But I can't get any response even the status is OK(200).

where is wrong. I don't konw.  How to set the config.

**Comment by ryanjbaxter** [comment]
> But I can't get any response even the status is OK(200).

Does this mean a `200` from the debug host or from the original request?

Have you debugged the filter?  Is it being invoked?

**Comment by AlexWei2013** [comment]
the filter is invokded, but the response is not expected. it seem the setting of zuul.debug.host is not valid.
how do it should be configed.  actually, I want to use it as the blue/green deployment.

**Comment by AlexWei2013** [comment]
sorry, I tried to remove the config(zuul.debug.host),the filter is invoked too. the request is routed the old 
service. so it look the config( zuul.debug.host) is valid. but the response is not my expected.
I just want to let the request is routed the new service(for debug and test). how should I  config it?

Thank you!

**Comment by AlexWei2013** [comment]
I tried to trace the source code for zuulfilter。 it truely throw a exception  like（org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'localhost:8090' with class 'java.lang.String' to class 'java.net.URL'）。 it look like  the config（zuul.debug.host=localhost:8090） can't be converted to url. 

the flowing is the code where throw exception.
```
try {
                    Object res = run();
                    zr = new ZuulFilterResult(res, ExecutionStatus.SUCCESS);
                } catch (Throwable e) {
                    t.setName("ZUUL::" + this.getClass().getSimpleName() + " failed");
                    zr = new ZuulFilterResult(ExecutionStatus.FAILED);
                    zr.setException(e);
                } finally {
                    t.stopAndLog();
                }
```

**Comment by spencergibb** [comment]
@AlexWei2013 what filter are you using? We don't have any explicit support for a property named `zuul.debug.host`.

**Comment by ryanjbaxter** [comment]
@spencergibb I believe @AlexWei2013 is extending https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/groovy/com/netflix/zuul/filters/SurgicalDebugFilter.groovy

**Comment by AlexWei2013** [comment]
@ryanjbaxter @royclarkson Yeah, I extended the SurgicalDebugFilter.groovy by java and only override the "patternMatches" menthod.

**Comment by ryanjbaxter** [comment]
In your original post you said `zuul.debug.host=http://localhost:9900` but then you said when you were debugging that `zuul.debug.host=localhost:8090` (without the protocol).  Where did the protocol go?  Maybe you can provide a sample project that reproduces the issue?

**Comment by AlexWei2013** [comment]
I tried the both config(with http://  and without http://). same exception was throwed.

**Comment by AlexWei2013** [comment]
I uploaded the project to github. please see it by [(https://github.com/AlexWei2013/mytest/tree/master/apigateway)].

thank you.

**Comment by spencergibb** [comment]
I wonder what we can do about it since we don't own that filter.

**Comment by ryanjbaxter** [comment]
I agree with @spencergibb seems like you might want to open an issue with Netflix.

**Comment by AlexWei2013** [comment]
I see. thank you for your support。
By the way， I want to create the function for blue/green test with spring cloud(zuul or others).  Could you give me some idea or example.

**Comment by ryanjbaxter** [comment]
You might want to look at https://github.com/spring-cloud/spring-cloud-netflix/issues/1290.  If you have further questions please open another issue.
