### ISSUE TITLE
No way to format List<java.util.Date> in Feign client

### ISSUE THREAD

**Issue by m190** [spring-cloud/spring-cloud-netflix#1526]
Are there any way how to make custom date format now? I saw a bit similar issue https://github.com/spring-cloud/spring-cloud-netflix/issues/1178, but I think that it's rather a bug than an enhancement.

I tried to use the list of date and neither suggested approach is working for me. I have such a client
```
@FeignClient(name = "exampleClient", url = "#{EXAMPLE_URL}" )
public interface ExampleClient{
    @RequestMapping(value = "/example", method = RequestMethod.GET)
    String getExampleValue(@RequestParam(name = "date") List<Date> dates);
}
```
And I couldn't find any way how to format the date. I think it's partially because of the https://github.com/spring-cloud/spring-cloud-netflix/issues/1115 fix. The extender is not appends, and no formatter is used,

**Comment by ryanjbaxter** [comment]
Can you say more about how you expect this work?  How are you expecting the dates to be formatted?

**Comment by m190** [comment]
I am expecting it to accept `@DateTimeFormat` or at least to use any `Formatter<Date>` registered with `FeignFormatterRegistrar`. But in case of registered formatter, it is not used.

**Comment by ryanjbaxter** [comment]
So are you providing a bean of type `FeignFormatterRegistrar` that is supposed to format the Date and it is not working?  If so please provide an example reproducing the issue so we can take a look.

**Comment by m190** [comment]
Yes. I have such configuration

```
@Configuration
@EnableFeignClients
public class ExampleConfig {

    @Bean
    public FeignFormatterRegistrar localDateFeignFormatterRegistrar() {
        return formatterRegistry -> formatterRegistry.addFormatter(new Formatter<Date>() {
            SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd");

            @Override
            public Date parse(String text, Locale locale) throws ParseException {
                return formatter.parse(text);
            }

            @Override
            public String print(Date object, Locale locale) {
                return formatter.format(object);
            }
        });
    }
}
```
and such client
```
@FeignClient(name = "exampleClient", url = "#{EXAMPLE_URL}" )
public interface ExampleClient{
    @RequestMapping(value = "/example", method = RequestMethod.GET)
    String getExampleValue(@RequestParam(name = "date") List<Date> dates);
}
```
But the date in the request path is not formatted accordingly to defined format `yyyyMMdd`.

**Comment by ryanjbaxter** [comment]
Can you provide the complete app?

**Comment by m190** [comment]
It's the complete app, the rest is jist main Spring Boot class:
```
@SpringBootApplication
public class ExampleApplication {
	public static void main(String[] args) {
		ConfigurableApplicationContext ctx = SpringApplication.run(ExampleApplication.class, args);
		ExampleClient bean = ctx.getBean(ExampleClient.class);
		bean.getExampleValue(Collections.singletonList(new Date()));
	}
}
```
And you need to define `EXAMPLE_URL` property somewhere.

**Comment by spencergibb** [comment]
@m190 he means, not as comments, but as a repo or zip file.

**Comment by m190** [comment]
@spencergibb @ryanjbaxter Sorry :) Please look at this mvn project [feign.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/696098/feign.zip). There is a `FeignClientTest` Unit test there, which  should normally pass, but now it fails due to formatting problem.

**Comment by ryanjbaxter** [comment]
Sorry for the slow response, it took some time for me to wrap my head around how Formatters work.

Turns out we don't support applying Formatters to `Collections`.  There is a [check in SpringMvcContract](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/support/SpringMvcContract.java#L243) which makes sure we don't include the `Expander` if the parameter is a `Collection.  The history as to why is in https://github.com/spring-cloud/spring-cloud-netflix/issues/1115.

I guess we need to come up with a way to apply the `Expander` to each item in the collection.  I am unsure of where best to do that at this point.  It will take some more investigation.
