### ISSUE TITLE
Multiple query string parameters

### ISSUE THREAD

**Issue by jeremieca** [spring-cloud/spring-cloud-netflix#1527]
Hello,

I try to call Google API with multiple query string parameters. And curiously, I can't find a way to do that.

This is my FeignClient : 

```
@FeignClient(name="googleMatrix", url="https://maps.googleapis.com/maps/api/distancematrix/json")
public interface GoogleMatrixClient {

    @RequestMapping(method=RequestMethod.GET, value="?key={key}&origins={origins}&destinations={destinations}")
    GoogleMatrixResult process(@PathVariable(value="key") String key,
                               @PathVariable(value="origins") String origins,
                               @PathVariable(value="destinations") String destinations);

}
```

The problem is that '&' character of the ```RequestMapping value``` is replace by ```&amp;```

How to avoid this ?

Thanks !

**Comment by spencergibb** [comment]
Feign expects query parameters to be handled separately than path parameters.

```
@FeignClient(name="googleMatrix", url="https://maps.googleapis.com")
public interface GoogleMatrixClient {

    @RequestMapping(method=RequestMethod.GET, value="/maps/api/distancematrix/json")
    GoogleMatrixResult process(@RequestParam("key") String key,
                               @RequestParam("origins") String origins,
                               @RequestParam("destinations") String destinations);

}
```

**Comment by shangal** [comment]
Like the @QueryMap annotation on open-feign is there an annotation which can take in an object for RequestParams

**Comment by ryanjbaxter** [comment]
This is a separate issue.  Please open an issue at https://github.com/spring-cloud/spring-cloud-openfeign

**Comment by niteshnawada** [comment]
Do we have any solution to use an object for request parameters - Similar to @QueryMap.
Or is there a way that I can extend some classes to achieve this?

Passing a long list of request parameters as separate arguments isn't a good idea.
