### ISSUE TITLE
custom fallback's return type when using FeignClient

### ISSUE THREAD

**Issue by WanqingLee** [spring-cloud/spring-cloud-netflix#1529]
```
@FeignClient(value = "compute-service", fallback = ComputeClientHystrix.class, configuration = ComputeConfiguration.class)
    public interface IComputeClient {
        @RequestMapping(method = RequestMethod.GET, value = "/add")
        Integer add(@RequestParam(value = "a") Integer a, @RequestParam(value = "b") Integer b);
 }
```
ComputeClientHystrix:
```
@Component
public class ComputeClientHystrix implements IComputeClient {
    @Override
    public Integer add(@RequestParam(value = "a") Integer a, @RequestParam(value = "b") Integer b) {
        return -9999;
    }
}
```
if i can return string like "error" rather than an integer(-9999)

**Comment by ryanjbaxter** [comment]
The point of the fallback is to return something rather than return any type of error.  I suppose your fallback could throw some type of exception if you wanted to, but I don't see the point of using a fallback then.

**Comment by WanqingLee** [comment]
@ryanjbaxter 
The point of fallback you say helps me a lot, thanks.
But if I want to throw some exception in add method of ComputeClientHystrix, "add short-circuited and fallback failed." error occurred. am i wrong, or is there another way to do this.

**Comment by ryanjbaxter** [comment]
Like I said you can do this, I just don't see the point of doing that in the fallback, why not do it in the Hystrix wrapped method?

**Comment by WanqingLee** [comment]
@ryanjbaxter Thanks for your help.
