### ISSUE TITLE
AbstractRibbonCommand   executeWithLoadBalancer

### ISSUE THREAD

**Issue by haroldjiang** [spring-cloud/spring-cloud-netflix#1530]
i'm using zuul as my api gateway with spring-cloud-netflix-core-1.2.3.RELEASE.
there is one thing caught my attention:why  does the run methond in class AbstractRibbonCommand  call executeWithLoadBalancer(final S request) instead of executeWithLoadBalancer(final S request, final IClientConfig requestConfig),with the later one,i can easily get the convenience of dynamically properties by using archaius.
Tks.

**Comment by ryanjbaxter** [comment]
I just fixed an issue that deals with some of these problems https://github.com/spring-cloud/spring-cloud-netflix/pull/1519.

In fact the command objects do have a reference to the client config and can pull values from it.  Are there specific properties you are changing that are not being updated?

**Comment by haroldjiang** [comment]
hi ryanjbaxter,thanks for your reply.
when i use the HttpClientRibbonCommand object to send a request,it defaults invoke the "run" method of it's super class(AbstractLoadBalancerAwareClient).the below is the run method:
@Override
	protected ClientHttpResponse run() throws Exception {
1)		final RequestContext context = RequestContext.getCurrentContext();

2)		RQ request = createRequest();
3)		RS response = this.client.executeWithLoadBalancer(request);

		context.set("ribbonResponse", response);

		// Explicitly close the HttpResponse if the Hystrix command timed out to
		// release the underlying HTTP connection held by the response.
		//
		if (this.isResponseTimedOut()) {
			if (response != null) {
				response.close();
			}
		}

		return new RibbonHttpResponse(response);
	}

In line 3),the code does not use the parameter "IClientConfig requestConfig",
so i can't get the dynamic props.this is the question i was wondering.why dont just invoke this method
executeWithLoadBalancer(final S request, final IClientConfig requestConfig).

to solve my problem,i implemeted my own HttpClientRibbonCommand class,override the default run method of the super class by directly invoke the method executeWithLoadBalancer(final S request, final IClientConfig requestConfig) in the method of my own HttpClientRibbonCommand class.

want to make sure that is there any side affects or something i need to notice.

Thanks again ,ryanjbaxter

**Comment by haroldjiang** [comment]
annother question about these two class:RibbonLoadBalancerClient and RibbonLoadBalancingHttpClient.
they both have similar execute method.what's the difference between them.
seems the default one is RibbonLoadBalancingHttpClient.
when and how should use RibbonLoadBalancerClient?

thanks very much

**Comment by spencergibb** [comment]
The difference between the two `RibbonLoadBalancingHttpClient` and `RibbonLoadBalancerClient` is the actual http client underneath. The ribbon http client is deprecated. @ryanjbaxter I don't think it would be a huge deal to use the other method do you?

**Comment by ryanjbaxter** [comment]
@spencergibb no I don't think so, if my memory serves me correctly `executeWithLoadBalancer(request)` just calls `executeWithLoadBalancer(request, config)` with `null`.  I can look into it.

**Comment by haroldjiang** [comment]
@spencergibb @ryanjbaxter thanks you two guys very much.
@spencergibb i looked into the code found the deprecated client class is RestClient,not the RibbonLoadBalancingHttpClient,when i used the ceprcated RestClient ,it sometimes will forward my http reuqest  to https request(it created ssl socket ,while i did not enable any ssl request on server side),so the request failed with message "Unrecognized SSL message, plaintext connection?"(because server side does not support ssl request).that's why i changed the deprecated RestClient to RibbonLoadBalancingHttpClient(RibbonLoadBalancingHttpClient can use dynamic prop config to control the forward behavior whether to use https or http)

**Comment by lowzj** [comment]
same problem. Looking forward to using `AbstractLoadBalancerAwareClient#executeWithLoadBalancer(final S request, final IClientConfig requestConfig)`.
