### ISSUE TITLE
returning HTTP1.1/200 instead of HTTP1.1/200 OK

### ISSUE THREAD

**Issue by gangakrishh** [spring-cloud/spring-cloud-netflix#1531]
returning HTTP1.1/200 instead of HTTP1.1/200 OK. 

i'm using zuul, zuul returning status as HTTP1.1/200 instead of HTTP1.1/200 ok, i'm asserting this in soap ui tests

please let me know what should be changed in zuul configuration to returning HTTP1.1/200 OK

**Comment by gangakrishh** [comment]
@mstine

**Comment by spencergibb** [comment]
Can you please provide any more details, version configuration, steps to reproduce?

**Comment by gangakrishh** [comment]
@spencergibb thanks for quick response! i've ran one more tests, i've found the issue

If we run the zuul with tomcat will get HTTP1.1/200 
If we run the zuul with jetty will get HTTP1.1/200 OK

seems not related to zuul, container related

Let me know if you want me to attach example source code for this

**Comment by spencergibb** [comment]
an example would be helpful

**Comment by gangakrishh** [comment]
[eureka_zuul_service.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/642589/eureka_zuul_service.zip)


attached 3 applications

ServiceOne registers with Eureka
Zuul not registers with Eureka but gets information
Eureka server

run 3 services (gradle bootRun)

access : http://localhost:8082/ServiceOne/service/welcome

**Comment by spencergibb** [comment]
Hmm, this happens even without zuul going direct to `ServiceOne`. I don't think it's a problem with zuul or spring cloud netflix at all. @dsyer or @philwebb I can't remember the name of the tomcat guy at pivotal, do you?

**Comment by gangakrishh** [comment]
that is correct @spencergibb that is what i've mentioned in my previous comment

**Comment by gangakrishh** [comment]
you can close this one!!
