### ISSUE TITLE
Does a "post" filter's shouldFilter() method run before or after a Response exists?

### ISSUE THREAD

**Issue by KeiichiTheOtaku** [spring-cloud/spring-cloud-netflix#1533]
I haven't found any documentation on this subject...

I'm designing a "post" filter to handle error responses from calls to AWS S3 for Static Content (log the error, manipulate the headers and such before the response goes back to the browser).

I'd like to know whether the Response exists before the shouldFilter() method gets executed, such that I can use the response status code to determine whether my "post" filter should run.

Thanks in advance.
Matt

**Comment by spencergibb** [comment]
It should, but necessarily. What is guaranteed is that 'route' filters run after 'pre' filters and 'post' filters run after 'route' filters. See [here](https://github.com/Netflix/zuul/blob/1.x/zuul-core/src/main/java/com/netflix/zuul/http/ZuulServlet.java#L64-L99) for the lifecycle.

**Comment by KeiichiTheOtaku** [comment]
Much appreciated.
