### ISSUE TITLE
Eureka: EurekaDiscoveryClient stopped when *any* Spring ApplicationContext is closed

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1534]
`org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration` listens for `ContextClosedEvent` and stops the discovery client when such event is received, even if the context being closed is not the primary context.

The `onApplicationEvent()` method should be modified as follows:
```

	@EventListener(ContextClosedEvent.class)
	public void onApplicationEvent(ContextClosedEvent event) {
		if( event.getApplicationContext() == this.applicationContext ) {
		   // register in case meta data changed
		   stop();
		}
	}
```

**Comment by brenuart** [comment]
Problem still there in `Dalston.SR1`. See PR above for a fix.

**Comment by spencergibb** [comment]
Closed via #2087

**Comment by brenuart** [comment]
This fix doesn't seem to be part of `1.3.2.RELEASE` but `2.0.0.M2` - see https://github.com/spring-cloud/spring-cloud-netflix/pull/2087

**Comment by ryanjbaxter** [comment]
It was merged into master so it will be part of the 1.4.0.M1 release and yes part of the 2.0.0.M2 release.  Do you need it in the 1.3.x stream as well?  If so we can consider backporting it.

**Comment by brenuart** [comment]
That's ok for us - we already have a workaround in place. I was just checking for when it could be removed. We can wait for `1.4` to be released. thx

**Comment by dlts26** [comment]
1.5.6依然有这个问题？

**Comment by changyangyo** [comment]
This problem still exists in version 1.4.12
