### ISSUE TITLE
Zuul: potential high memory consumption in SendResponseFilter

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1536]
`SendResponseFilter` copies data from the origin input stream to the client's request output stream.
The copy operation uses a buffer whose size is doubled each time it can be filled with data obtained from a single read operation. In other words, the faster you can read data from origin, the bigger becomes the buffer.

A couple of remarks:
- We had a case where the response sent by the Origin server was highly compressible (ratio above 1/5000) - this lead to a very fast read and the copy buffer ended to a size of several megabytes.

- This growing strategy implies a new buffer is allocated every time it is grown and the old buffer is discarded. This strategy is not GC friendly.

- There is no real added value in writing data in the request's output stream in chunk larger than the request buffer. Tomcat for instances uses a buffer of 8192 bytes behind the request output stream. Any attempt to write more than this size results in a flush and the writing thread has to wait for the data being transferred to the client. The SendResponseFilter could therefore make use of a fixed size buffer for its copy operation without any performance lost. This copy buffer could even be reused (ThreadLocal).

These changes could help to keep reduce the memory usage required to process requests.

**Comment by tkvangorder** [comment]
We can confirm that the changes outlined by @brenuart work great. 

We disabled the default send response filter in our sidecar application and then applied a new filter which essentially included @brenuart pull request. We then deployed it to one of our nodes in our production environment: 

![beforepatch](https://cloud.githubusercontent.com/assets/1878529/21736705/7f77dba8-d427-11e6-97dc-93e2590fcd84.png)
![afterpatch](https://cloud.githubusercontent.com/assets/1878529/21736706/8298a470-d427-11e6-988b-07c6b8ab7440.png)


Big difference in Memory usage, big thank you to Bertrand!

@ryanjbaxter or @spencergibb Any idea when this might approved/merged?

**Comment by brenuart** [comment]
@tkvangorder glad it works for you ;-)

**Comment by spencergibb** [comment]
@brenuart I merged your PR, can this be closed?

**Comment by brenuart** [comment]
Can be closed. Thx.
