### ISSUE TITLE
Zuul: SendResponseFilter keeps reading data from Origin even when unable to write it to the client

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1537]
In `SendResponseFilter`:
```
	private void writeResponse(InputStream zin, OutputStream out) throws Exception {
		byte[] bytes = new byte[INITIAL_STREAM_BUFFER_SIZE.get()];
		int bytesRead = -1;
		while ((bytesRead = zin.read(bytes)) != -1) {
			try {
				out.write(bytes, 0, bytesRead);
				out.flush();
			}
			catch (IOException ex) {
				// ignore
			}
			// doubles buffer size if previous read filled it
			if (bytesRead == bytes.length) {
				bytes = new byte[bytes.length * 2];
			}
		}
	}
```

As you can see, failures to write in the request output stream are silently ignored and the method keeps reading data from origin until the stream is fully drained.

A typical scenario is when the client disconnects from Zuul without reading its response. In this case, the Zuul handling thread (a Tomcat/Jetty worker thread) stays busy until the response if fully read from Origin. The only reason I can think of is to fully drain the origin stream before it is closed.

If there is no actual need to drain the input stream before closing it (which is odd imho) - then we probably had better to exit the writeResponse() operation on the first IOException received when writing back to the client.

**Comment by spencergibb** [comment]
@brenuart I merged your PR, can this be closed?

**Comment by brenuart** [comment]
Looks good to me.
Thx.
