### ISSUE TITLE
Application registers to Eureka with port 0(zero) if EurekaClient is used on startup and do not update to Eureka registry after successful start up of the application

### ISSUE THREAD

**Issue by varunnmiglani** [spring-cloud/spring-cloud-netflix#1541]
Application registers to Eureka with port 0(zero) if a FeignClient is called at start up of the application.

1. I have a centralised logging Service which pushes the logs from all the microservice application into a DB.

2. In one of my application I call the my LoggingService via FeignClient at the time of start up.
3. The order of registration to Eureka is : 
   a. Eureka
   b. Logging
   c. Application.

4. The Application calls the Eureka to find information abt logging service and registers itself with port no zero with Eureka and even after the successfull Startup, the port no is not updated to Eureka.

[issue.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/639383/issue.zip)

PFA  the start up logs of the application and application.yml for Eureka, and my application.
[app.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/639356/app.txt)

**Comment by varunnmiglani** [comment]
Can someone help me on this?

**Comment by spencergibb** [comment]
I'm afraid you'll need to provide a sample application that reproduces the behaviour you are seeing.

**Comment by varunnmiglani** [comment]
[App.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/645205/App.zip)

Hi ,

I have uploaded the required .java files and PFB a brief description about the classes.

1. Application.java : Spring Boot Application file consisting of various configurations.
2. LocalStorage.java : This class is annotated with @Component and in the "init()" method which is annotated with @PostConstruct calls the Logging API, which internally uses LoggingClient(FeignClient).
3. ILoggingService.java : Logging API Interface.
4. DBLoggingService.java : ILoggingService Implementation which uses DBLogger object to delegate the call to FeignClient.
5. DBLogger.java : Uses Feign Client to call the Logging API.

Please let me know if you need any other information.

**Comment by varunnmiglani** [comment]
Hi,

I hope this is what you need to understand the issue, please let me know if I have missed something.

**Comment by varunnmiglani** [comment]
Hi Team,

Looks like I have found the root cause but need some help on this issue please find my application ode base : https://github.com/varunnmiglani/Micro-Services-Demo 

RCA : If we use EurekaClient during startup of the application to find some information about an instance and log it via a FeignCLient, the application itselfs registers with Eureka with port 0 and do not update.

In the Storage Application, there is Initialiser class which calls Feign Client in@postConstruct method.

Varun

**Comment by spencergibb** [comment]
@varunnmiglani there's a chicken and egg problem. By using the eureka client before is has all of the information it will register with port 0. You may try with the latest Brixton.SR3 as well.

**Comment by varunnmiglani** [comment]
Hi @spencergibb ,

Yes nut there must be an API to update the port no to Eureka Registry or some event we can do it.
I tried with the Brixton.SR3 no luch, getting the same issue. 
Please suggest.

**Comment by ryanjbaxter** [comment]
I think @spencergibb meant Brixton.SR7.

**Comment by varunnmiglani** [comment]
Hi,

Bad luck, upgrading to SR7 din't work. Please suggest.

**Comment by ryanjbaxter** [comment]
Thanks for giving that a try.  Another question, does the app eventually update the port with Eureka, or is the port continuously `0`?

**Comment by varunnmiglani** [comment]
No, it does not and if it does it solves my problem , due to this eureka has dirty data about my app(Incorrect port no of my App)

**Comment by varunnmiglani** [comment]
Hi Team,

Is there any workaround for this problem?

**Comment by varunnmiglani** [comment]
Hi Team, 
I tried not using EurekaClient at startup but use a Feign Client to call a service, still it fails because the application has no information abt the eureka registry and Feign Client fails.

**Comment by varunnmiglani** [comment]
Sure, you can view the full apllication on github by clicking on the following link.

https://github.com/varunnmiglani/Micro-Services-Demo

**Comment by spencergibb** [comment]
@varunnmiglani you should wait to use eureka until the client is registered by listening for an `InstanceRegisteredEvent`.
