### ISSUE TITLE
Get InstanceInfo in EurekaInstanceRenewedEvent is always Null

### ISSUE THREAD

**Issue by darren-fu** [spring-cloud/spring-cloud-netflix#1546]
Try to get InstanceInfo in Listener<EurekaInstanceRenewedEvent>, but it's always null,  debug the code,  find out there is a bug here.
```java
//org.springframework.cloud.netflix.eureka.server.InstanceRegistry#renew 
// line 117
if (input.getName().equals(appName)) {
				InstanceInfo instance = null;
				for (InstanceInfo info : input.getInstances()) {
					if (info.getHostName().equals(serverId)) {
						instance = info;
						break;
					}
				}
				this.ctxt.publishEvent(new EurekaInstanceRenewedEvent(this, appName,
						serverId, instance, isReplication));
				break;
			}
```
**if (info.getHostName().equals(serverId))**
serverId contains HostName and Port, so it won't equal to info.getHostName() forever.

Hope it's helpful!

**Comment by darren-fu** [comment]
Version : Brixton.SR7

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces this?  Or better yet a PR with a fix and a test case.
