### ISSUE TITLE
Brixton.Sr1 - Unable to send heartbeat error on startup

### ISSUE THREAD

**Issue by Milesy** [spring-cloud/spring-cloud-netflix#1550]
When I startup my Eureka server node I get exceptions at startup.

I have turned on Jersey logging to give an idea of the data in transit.

[error.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/651502/error.txt)

The JSON returned seems to be a server error rather than the expected instance JSON.
```
{"timestamp":1481713238850,"status":500,"error":"Internal Server Error","exception":"java.lang.NullPointerException","message":"No message available","path":"/eureka/apps/FOO.COM.SERVICE.EUREKA/foo.com:com.foo.service.eureka:8761"}
```
After this error happens, It doesnt happen again and I can access the URL fine:
```
http://foo.com:8761/eureka/apps/FOO.COM.SERVICE.EUREKA/foo.com:com.foo.service.eureka:8761?status=UP&lastDirtyTimestamp=1481713210390
```
and I can see a valid JSON response.

So it looks like the heart beat is possibly attempting to happen before the server has fully initialised? (Just my thought) 

My POM looks like - [pom.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/651508/pom.txt)
* Note I have had to force spring-cloud-starter-eureka-server to 1.1.4.RELEASE as we don't have 1.1.2.RELEASE in our internal repo yet (but it was working last week fine)

My configuration looks like:

```java
@Configuration
@EnableProperties
@EnableAutoConfiguration
@EnableEurekaServer
public class ApplicationConfig {
    @Bean
    public DiscoveryClient.DiscoveryClientOptionalArgs discoveryClientOptionalArgs() {
        DiscoveryClient.DiscoveryClientOptionalArgs args = new DiscoveryClient.DiscoveryClientOptionalArgs();
        List<ClientFilter> filters = new ArrayList<>();
        filters.add(new HTTPBasicAuthFilter("eureka", "default"));
        filters.add(new LoggingFilter());
        args.setAdditionalFilters(filters);

        return args;
    }    
}
```

**Comment by Milesy** [comment]
My YML looks like the following - note we provide -Dserver.name to the process as a VM argument which corresponds to the DNS name of the service, not the server name - we dont want anything to do with the server name within the application.

spring:
  application:
    name: com.foo.service.eureka

server:
  port: ${eureka.server.port:8761}

security:
  basic:
    enabled: true
  user:
      name: ${eureka.username:eureka}
      password: ${eureka.password:default}

eureka:
  instance:
    hostname: ${server.name:localhost}
  metadataMap:
        hostname: ${server.name:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka.defaultZone}

**Comment by spencergibb** [comment]
Can you please try with the latest Brixton.SR7 or Camden.SR3?

**Comment by Milesy** [comment]
Not possible Spencer, our internal Governance process to get new applications / components onboarded is lengthy. SR1 is all we have at present, I understand that is a limitation.

**Comment by spencergibb** [comment]
The eureka library has changed since Brixton.SR1. It's at 1.4.12 in SR7. If you can create a sample that recreates the problem using the latest brixton, go ahead and reopen this.
