### ISSUE TITLE
Blue/Green Deployment - Eureka Client De-registration Cycle

### ISSUE THREAD

**Issue by huhuhong** [spring-cloud/spring-cloud-netflix#1551]
I'm currently working on Blue/Green Deployment with Spring Boot + Spring Cloud Eureka in AWS 

What is the best practise to de-registration old client from Eureka Server withoutinterrupt existing requests in progress? 

My objective was to have the ability of Connection Draining provided by AWS's ELB
https://aws.amazon.com/blogs/aws/elb-connection-draining-remove-instances-from-service-with-care/

**Comment by kakawait** [comment]
May related to #1290 if you not already read it you may find some part of solution.

**Comment by ryanjbaxter** [comment]
@huhuhong can you provide specifics around how the requests are being made and how they are failing?

**Comment by huhuhong** [comment]
I was using AWS ASG (Auto scaling group) Swap behind AWS ELB as Blue/Green Deployment Strategy
Imagine below is my Eureka client list : 
before deployment:
- Service_A_BLUE
during deployment:
- Service_A_BLUE
**- Service_A_Green** -- added 
after deployment
**- Service_A_BLUE**  -- removed
- Service_B_Green

During the process of removing Service_A_Blue, how can i safely remove it by allowing in progress request to completed before i actually shut it down? 
My current plan was to mark all Service with Blue Tag as OUT_OF_SERVICE [Take instance out of service](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations),
 then wait for x seconds to make sure existing request was served completely.

Any comment on this?

**Comment by ryanjbaxter** [comment]
I think your approach is correct, although I don't think you need to wait x seconds before shutting down the service.  I don't think you will be able to guarantee that a request is not in progress when you shut it down.  For that reason the service should be able to retry failed requests on the next available instance.  There is retry logic available in various components of Spring Cloud (Ribbon, Feign, and Zuul).  We have been overhauling the logic used by these components in the Camden release train to centralize on using Spring Retry.  Ribbon should already be using Spring Retry.  There is a PR for Feign (https://github.com/spring-cloud/spring-cloud-netflix/pull/1457), and I will be working on Zuul next.

**Comment by huhuhong** [comment]
i found an alternative way by using /pause, /resume actuator endpoint.
I will /pause all the Service_A_BLUE as "DOWN" after up all the Service_B_Green as "UP"
Once everything work well, then only i shut down Service_A_Blue.
In the case of rollback, i will /resume all the Service_A_Blue and /pause then shut down all the Service_B_Green 

Any thought?

**Comment by ryanjbaxter** [comment]
I think that might work well.

**Comment by brenuart** [comment]
@huhuhong beware of https://github.com/spring-cloud/spring-cloud-netflix/issues/1443 if you are running Brixtion.SR7 or earlier
