### ISSUE TITLE
Feign logger - no sleuth headers attached

### ISSUE THREAD

**Issue by tzebrowski** [spring-cloud/spring-cloud-netflix#1553]
Hi,

I provided own implementation of  **feign.Logger** and set log level on **feign.Logger.Level.FULL**.
In the method **logRequest** I read **Request.headers** and don't get there sleuth headers like X-B3-,... .
I know for sure that TraceFignClient  is executed. When turn log level on DEBUG for **org.springframework.cloud.sleuth.instrument.web.client.feign**  I see  statements like 
o.s.c.s.i.w.c.feign.TraceFeignClient     : The modified request equals POST. 
with missing headers included. 

/Tomek

**Comment by spencergibb** [comment]
Should go in https://github.com/spring-cloud/spring-cloud-sleuth/issues
