### ISSUE TITLE
can @FeignClient configuration override @EnableFeignClients defaultConfiguration?

### ISSUE THREAD

**Issue by WanqingLee** [spring-cloud/spring-cloud-netflix#1555]
See code below,
```
@EnableFeignClients(defaultConfiguration = MyFeignConfiguration.class)
public class Application { }
```

```
@FeignClient(value = "compute-service", configuration = PluConfiguration.class)
public interface IPluService { }
```

but the result is, "compute-service" still use MyFeignConfiguration, so can @FeignClient configuration override @EnableFeignClients defaultConfiguration?

by the way, how to define different loadbalance strategy in different FeignClient?

**Comment by spencergibb** [comment]
They should. If they are not, can you provide a sample that duplicates the problem?

**Comment by eacdy** [comment]
@WangqingLee
Maybe these words below can help you:
> The FooConfiguration has to be @Configuration but take care that it is not in a @ComponentScan for the main application context, otherwise it will be used for every @FeignClient. If you use @ComponentScan (or @SpringBootApplication) you need to take steps to avoid it being included (for instance put it in a separate, non-overlapping package, or specify the packages to scan explicitly in the @ComponentScan).

**Comment by xj198806** [comment]
i get the same problem. i use different load balance IRule but aways default RoundRobinRule please help !! my code https://github.com/xj198806/feign-test.git

**Comment by ryanjbaxter** [comment]
@xj198806 i took a quick look at your app and it does not seem to be the same problem, please open a separate issue.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
