### ISSUE TITLE
Unable to set eureka.instance.virtualHostName

### ISSUE THREAD

**Issue by springfang** [spring-cloud/spring-cloud-netflix#1559]
After [this commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/b3f1a30027a2866f044258f62e78bf924a502e29) it is no longer possible to specify either `eureka.instance.virtualHostName` or `eureka.instance.secureVirtualHostName`. Those values are now forced to `spring.application.name` (if one has been provided).

Perhaps this is intentional, but it broke my Zuul configuration that relies on a custom VIP. I am currently working around this by having the following configuration class:

    /**
     * This is copied almost verbatim from EurekaClientAutoConfiguration, with the only difference
     * being that it creates an instance of VipHackEurekaInstanceConfigBean instead of
     * EurekaInstanceConfigBean.
     */
    @Configuration
    public class VipHackEurekaClientConfig {

        @Value( "${server.port:${SERVER_PORT:${PORT:8080}}}" )
        int nonSecurePort;

        @Value( "${management.port:${MANAGEMENT_PORT:${server.port:${SERVER_PORT:${PORT:8080}}}}}" )
        int managementPort;

        @Value( "${eureka.instance.hostname:${EUREKA_INSTANCE_HOSTNAME:}}" )
        String hostname;

        @Autowired
        ConfigurableEnvironment env;

        @Bean
        @ConditionalOnMissingBean( value = EurekaInstanceConfig.class, search = SearchStrategy.CURRENT )
        public EurekaInstanceConfigBean eurekaInstanceConfigBean( InetUtils inetUtils ) {
            //////////======= This first line is the only change made to the original code. =======//////////
            final EurekaInstanceConfigBean instance = new VipHackEurekaInstanceConfigBean( inetUtils );
            instance.setNonSecurePort( this.nonSecurePort );
            instance.setInstanceId( getDefaultInstanceId( this.env ) );

            if ( this.managementPort != this.nonSecurePort && this.managementPort != 0 ) {
                if ( StringUtils.hasText( this.hostname ) ) {
                    instance.setHostname( this.hostname );
                }

                final RelaxedPropertyResolver relaxedPropertyResolver = new RelaxedPropertyResolver( env, "eureka.instance." );
                final String statusPageUrlPath = relaxedPropertyResolver.getProperty( "statusPageUrlPath" );
                final String healthCheckUrlPath = relaxedPropertyResolver.getProperty( "healthCheckUrlPath" );
                if ( StringUtils.hasText( statusPageUrlPath ) ) {
                    instance.setStatusPageUrlPath( statusPageUrlPath );
                }
                if ( StringUtils.hasText( healthCheckUrlPath ) ) {
                    instance.setHealthCheckUrlPath( healthCheckUrlPath );
                }

                final String scheme = instance.getSecurePortEnabled( ) ? "https" : "http";
                instance.setStatusPageUrl( scheme + "://" + instance.getHostname( ) + ":" + this.managementPort + instance.getStatusPageUrlPath( ) );
                instance.setHealthCheckUrl( scheme + "://" + instance.getHostname( ) + ":" + this.managementPort + instance.getHealthCheckUrlPath( ) );
            }

            return instance;
        }

        /**
         * This is copied directly from EurekaInstanceConfigBean but modified to only update the virtualHostName and secureVirtualHostName properties if they haven't already been
         * set to something other than "unknown" (their default value)
         */
        private class VipHackEurekaInstanceConfigBean extends EurekaInstanceConfigBean {
            public VipHackEurekaInstanceConfigBean( final InetUtils inetUtils ) {
                super( inetUtils );
            }

            @Override
            public void afterPropertiesSet( ) throws Exception {
                final RelaxedPropertyResolver springPropertyResolver = new RelaxedPropertyResolver( this.getEnvironment( ), "spring.application." );
                final String springAppName = springPropertyResolver.getProperty( "name" );

                if ( StringUtils.hasText( springAppName ) ) {
                    setAppname( springAppName );

                    //////////======= Added if clause =======//////////
                    if ( getVirtualHostName( ).equals( "unknown" ) ) {
                        setVirtualHostName( springAppName );
                    }
                    //////////======= Added if clause =======//////////
                    if ( getSecureVirtualHostName( ).equals( "unknown" ) ) {
                        setSecureVirtualHostName( springAppName );
                    }
                }
            }
        }

**Comment by spencergibb** [comment]
And this commit 1fe1ea58f6c518ca71787569b2e6b278e9cdd42e updated it to move it out of `afterPropertiesSet`. Are you running off of master?

**Comment by spencergibb** [comment]
Added test here c380039b3ecf264799b8e46180febe2df3fb3861

**Comment by springfang** [comment]
Looks like I'm running 1.2.3.RELEASE, via Spring Cloud Camden.SR3. If this has already been fixed, then I apologize for the noise. I will eagerly await whenever this fix makes its way into the Spring Cloud release train. :)

**Comment by spencergibb** [comment]
reopening to double check that the fix is in camden (which isn't on master anymore).

**Comment by spencergibb** [comment]
Looks like it's there in 7fdd86e69caf3d9eed34c6ea67b9f61f666db615

**Comment by spencergibb** [comment]
So, just needs a release
