### ISSUE TITLE
Configure for OIDC

### ISSUE THREAD

**Issue by bryantp** [spring-cloud/spring-cloud-netflix#1560]
Hello All,

I was wondering if there was a way to configure Spring Cloud Netflix to use OpenID Connect and pull down user information. I was told that I could change the url for the access token request `/oauth/token` to include `response_type=token id_token` as a URL param. If I did that, UAA would send me the user information along with the rest of the token. 

How would I configure Spring Cloud Netflix to do this?

**Comment by spencergibb** [comment]
You'll have to be more specific about which part of spring cloud Netflix you want to configure.

**Comment by bryantp** [comment]
Sorry,

I believe this would be `spring-cloud-starter-oauth2`. Specifically, I am trying to configure a resource (`@EnableResourceServer`) to retrieve detailed user information from UAA. I currently have it retrieving the auth token and parsing out the stuff I need with a custom `JwtAccessTokenConverter`

Config Class:

 ```
    @Autowired
    public void setJwtAccessTokenConverter(JwtAccessTokenConverter jwtAccessTokenConverter) {
        jwtAccessTokenConverter.setAccessTokenConverter(createTokenAwareTokenConverter());
    }

    @Bean
    DefaultAccessTokenConverter createTokenAwareTokenConverter() {
        return new TenantAwareTokenConverter();
    }
```

TokenConverter Implementation:

```
public class TenantAwareTokenConverter extends DefaultAccessTokenConverter {

    private final String TENANT_KEY = "zid";
    private final String USER_ID_KEY = "user_id";

    @Override
    public OAuth2Authentication extractAuthentication(Map<String, ?> map) {
        OAuth2Authentication auth2Authentication = super.extractAuthentication(map);
        String tenant = (String)map.get(TENANT_KEY);
        String userId = (String)map.get(USER_ID_KEY);
        TenantAwareRequest request = new TenantAwareRequest(auth2Authentication.getOAuth2Request(), tenant, userId);
        return new TenantAwareAuthentication(request, auth2Authentication.getUserAuthentication(), tenant, userId);
    }
}
```

TenantAwareAuthentication Impl:

```
public class TenantAwareAuthentication extends OAuth2Authentication {

    private String tenant;
    private String userId;

    /**
     * Construct an OAuth 2 authentication. Since some grant types don't require user authentication, the user
     * authentication may be null.
     *
     * @param storedRequest      The authorization request (must not be null).
     * @param userAuthentication The user authentication (possibly null).
     */
    public TenantAwareAuthentication(OAuth2Request storedRequest, Authentication userAuthentication, String tenant, String userId) {
        super(storedRequest, userAuthentication);
        this.tenant = tenant;
        this.userId = userId;
    }
}
```

I was hoping I could do something similar (Or use the same token converter) to retrieve more detailed user info

**Comment by ryanjbaxter** [comment]
Sounds like you want to ask the question over here https://github.com/spring-cloud/spring-cloud-security
