### ISSUE TITLE
Zuul "hangs" while proxying a 205 response

### ISSUE THREAD

**Issue by derekwyatt** [spring-cloud/spring-cloud-netflix#1562]
I have a test server that behaves like the following when responding with a `205`:

    ~> curl -v http://localhost:50001/respond/1?status=205
    
    * Connected to localhost (127.0.0.1) port 50001 (#0)
    > GET /respond/1?status=205 HTTP/1.1
    > Host: localhost:50001
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 205
    < Date: Sun, 18 Dec 2016 17:36:52 GMT
    < Content-Length: 0
    <
    * Connection #0 to host localhost left intact

When proxying this same request through Zuul I get the following:

    ~> curl -v http://localhost:9200/respond/1?status=205
    *   Trying ::1...
    * Connected to localhost (::1) port 9200 (#0)
    > GET /respond/1?status=205 HTTP/1.1
    > Host: localhost:9200
    > User-Agent: curl/7.43.0
    > Accept: */*
    >
    < HTTP/1.1 205
    < X-Application-Context: application:9200
    < Date: Sun, 18 Dec 2016 17:37:02 GMT
    * no chunk, no close, no size. Assume close to signal end
    
    ^^^ "Hangs" here... eventually either curl or Zuul closes the connection

This is:

- springBootVersion: `1.4.0.RELEASE`
- javaVersion: `1.8`
- releaseTrain: `Brixton.SR5`

**Comment by ryanjbaxter** [comment]
Can you provide the app?  Also can you try with the latest release, Camden.SR3?

**Comment by derekwyatt** [comment]
This oughta do it: https://github.com/derekwyatt/zuul-proxy-205.  It's just a rip off of the basic example app with a dead-stupid node server in the background.

Just run `./run`

**Comment by Sangdol** [comment]
I'm not a maintainer of this project but tried some experiment as it looked interesting.

First of all, the hanging is happening on the `cUrl` side not on the Zuul side. It's caused because the server doesn't add `Content-Length` in the response header. (You can get a hint from this message `no chunk, no close, no size. Assume close to signal end`).


When I changed the embedded server from Tomcat to Jetty, it worked fine. But Tomcat without Spring is also setting the `Content-Length` properly. The result of my experiment looks like this

```
Environment             | Setting Content-Length
------------------------------------------------
Tomcat + Spring + Zuul  | X
Jetty + Spring + Zuul   | O
Tomcat + Zuul           | O
Jetty + Zuul            | O
```

I'm not sure if Spring is influencing Tomcat not to add `Content-Length` or not.

**Comment by ryanjbaxter** [comment]
Thanks for your analysis @Sangdol!  I am curious if this is an issue when Zuul is not involved.  Has anyone tried that?

**Comment by Sangdol** [comment]
Yes, it's still reproducible without Zuul. I've tested it with this simple controller.

```
@RestController
public class SimpleController {

    @RequestMapping("205")
    ResponseEntity get205() {
        return ResponseEntity.status(HttpStatus.RESET_CONTENT).body("");
    }

}
```

So I guess this issue should not related to Spring Cloud. 

FWIW, I've also tested 202 and 204 code, but only 205 response doesn't return `Content-Lenghth`. Interesting.

```
    @RequestMapping("204")
    ResponseEntity get204() {
        return ResponseEntity.status(HttpStatus.NO_CONTENT).body("");
    }

    @RequestMapping("202")
    ResponseEntity get202() {
        return ResponseEntity.status(HttpStatus.ACCEPTED).body("");
    }
```

**Comment by ryanjbaxter** [comment]
Great thanks @Sangdol.  @derekwyatt given @Sangdol's analysis I suggest you perhaps open an issue with [Spring MVC](https://github.com/spring-projects/spring-framework).
