### ISSUE TITLE
Zuul does not proxy TRACE and OPTIONS

### ISSUE THREAD

**Issue by derekwyatt** [spring-cloud/spring-cloud-netflix#1563]
I'm trying to use Zuul as a (reasonably) raw reverse proxy. As such, I need to
be able to proxy `TRACE` and `OPTIONS` requests (since it's very possible that
the server to which I will be proxying has implementations for these methods).

`OPTIONS` returns from within Spring, without proxying the request. It simply
returns Spring's internal default of `Allow:
GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS`.

`TRACE` returns a `405`. I expect this also is the default implementation for
Spring but it's not clear to me how to pass this through the proxy; every
document I can find talks about using `@RequestMapping` but Zuul does not seem
to have explicit `@RequestMapping` entries.

This is:

- springBootVersion: `1.4.0.RELEASE`
- javaVersion: `1.8`
- releaseTrain: `Brixton.SR5`

**Comment by ryanjbaxter** [comment]
Are you saying that the request never makes it through the proxy to the downstream service and that the Zuul app is returning these values?

**Comment by derekwyatt** [comment]
Yes, the requests never seem to make it to Zuul at all; I don't see them in my `route` or `pre` filters.  I think this is reasonably normal behaviour for Spring itself and can be overridden with specific `@RequestMapping`s but it's not clear how Zuul is supposed to do it.

**Comment by spencergibb** [comment]
http://stackoverflow.com/questions/33331042/how-to-handle-http-options-requests-in-spring-boot

**Comment by derekwyatt** [comment]
Thanks @spencergibb, that works for `OPTIONS`.  I also found https://github.com/spring-projects/spring-boot/commit/88cf65427f9a9dae203e5967803d3c3e97fcdc7e that shows the change for `TRACE` was added to `1.4.2.RELEASE`.  That works too. 

Thanks guys.
