### ISSUE TITLE
Support Spring Boot 2.0 & Spring 5.0

### ISSUE THREAD

**Issue by tangyouwo** [spring-cloud/spring-cloud-netflix#1565]
i make the project through the web  spring boot initializer ,
and i selected spring boot 2.0 and cloud .
i want to implement the function that using eureka to run some demo 
like register demo, productor demo, consumer demo .
i make a demo with a  example ,
and using Feign in consumer demo.
some code :
``` @SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
public class FeignApplication {
	public static void main(String[] args) {
		SpringApplication.run(FeignApplication.class, args);
	}
}
```
then i run it , console show errors :
no such method : org.springframework.core.annotation.AnnotationAttributes.getAliasedString

then i open the jar that spring-core -5.0.0 build and the same package,  and  can't open the class file
. so i try to download  spring-core-4.3.5 ,and i can open the class file --org.springframework.core.annotation.AnnotationAttributes ,   so i replace the class in 5.0 with the 4.3.5

and the demo can runs .
and i still try run with  4.3.5 jar , but make other errors , some method the 5.0 has but 4.3.5

so  i want to know why , spring core 5 jar is not well ? spring boot 2.0 is not well？ 
which version of spring boot  i can use

**Comment by spencergibb** [comment]
It is not currently supported. We will start working on this at the new year. We'll keep this issue open to track.

**Comment by fmonsalvo** [comment]
Hi, do you guys have any update on adding support for Spring 5.0? I'm looking to update my projects to use it but I have a dependency on spring-cloud-starter-feign.
Thanks!

**Comment by spencergibb** [comment]
See https://spring.io/blog/2017/08/30/spring-cloud-finchley-m2-is-available

M3 is in progress

**Comment by n0mer** [comment]
@spencergibb are there any updates regarding M3?

spring-boot 2.0.0.RC1 is available now

**Comment by spencergibb** [comment]
M6 was just released. In the future, please ask questions like this on gitter

**Comment by mayras** [comment]
I'm migrating big project already 1 week from Spring 4 to 5 and has next problem as last issue.
Method getAliasedString() is not available in org.springframework.cloud.netflix.feign.FeignClientsRegistrar:

	private void validate(Map<String, Object> attributes) {
		AnnotationAttributes annotation = AnnotationAttributes.fromMap(attributes);
		// This blows up if an aliased property is overspecified
---->		annotation.getAliasedString("name", FeignClient.class, null);
	}

do u have some snapshot or fix for that? :(

**Comment by spencergibb** [comment]
@mayras please use Finchley.RC1 where that code no longer is there. If you continue to have problems, please open an issue here https://github.com/spring-cloud/spring-cloud-openfeign/issues
