### ISSUE TITLE
Placeholders in @EnableFeignClients annotation couldn't be resolved

### ISSUE THREAD

**Issue by CD-HH** [spring-cloud/spring-cloud-netflix#1568]
Good day !
Currently I have need to specify base packages in `@EnableFeignClients` annotation using spring placeholders, that it should automatically resolve. But I've been a little bit confused when those placeholder haven't been resolved properly.

I've got a deep dive into this problem and have discovered further facts:

- client registration is performed using **org.springframework.cloud.netflix.feign.FeignClientsRegistrar**

- scanning for the feign clients is performed using bean, that is constructed using **getScanner()** method, which returns an anonymous impl of the **ClassPathScanningCandidateComponentProvider**,  which have been constructed using further constructor **ClassPathScanningCandidateComponentProvider(boolean useDefaultFilters)**

- this constructor reduces the scope of the available properties (it creates **new StandardEnvironment()**, instead of using **Environment** from context), and scanner operates only using system properties, and ignores user defined properties, that breaks resolving process 

For this reason my placeholder couldn't be resolved, could you please explain, is this a proper behaviour, or maybe you know any workarounds to solve my pain ))

The version of the spring-cloud-starter-feign is provided by version of spring-cloud-bom (**Brixton.SR6**)

Thx !

**Comment by ryanjbaxter** [comment]
I think the solution here is to make `FeignClientsRegistrar` implement `EnvironmentAware`.  I will try to take a look at this today and see if I can come up with a reproducible scenario and a fix.
