### ISSUE TITLE
@EnableFeignClients does not work in Spring Boot CLI applications

### ISSUE THREAD

**Issue by mstine** [spring-cloud/spring-cloud-netflix#157]
Reference broken app: https://github.com/mstine/nfjs_2015/tree/master/DistributedSystemsWithSpringCloud/code/consumerFeignBootCli

@Autowire fails - no autowire candidate available.

When commented out, checking /beans endpoint shows that ProducerClient bean is not created.

**Comment by dsyer** [comment]
Did it work when you run from a jar? I don't think there's anything we can do here (JPA doesn't work for the same reason).

**Comment by spencergibb** [comment]
Do we think there is something to be done about this at some point?  If not, I'll close it.

**Comment by dsyer** [comment]
Probably worth leaving it open. If JPA gets fixed this will, and we can use this to track it for Sprin Cloud users.

**Comment by ryanjbaxter** [comment]
Please comment if this is still an issue and we can reopen it.
