### ISSUE TITLE
could i unregister a service instance from eureka with spring cloud eureka annotation?

### ISSUE THREAD

**Issue by xiaoerlyl** [spring-cloud/spring-cloud-netflix#1570]
could i unregister a service instance from eureka with spring cloud eureka annotation?

**Comment by ryanjbaxter** [comment]
I am not sure how an annotation would be able to do that, annotations are static.  Can you elaborate more?

**Comment by xiaoerlyl** [comment]
I am trying to implement service discovery and registry with spring cloud commons 'Discovery' interface,  so that i can replace my underlying implementations flexibly just by replacing the jar file on the classpath. could I do it with Discovery interface ?

**Comment by spencergibb** [comment]
By default, closing the application context unregisters the application in Camden and prior. Starting in Dalston, you'll have more programmatic control. See https://github.com/spring-cloud/spring-cloud-commons/issues/9
