### ISSUE TITLE
Turbine AMQP with health endpoint

### ISSUE THREAD

**Issue by diegobmd** [spring-cloud/spring-cloud-netflix#1579]
Hi i'm using turbine AMQP for aggregate the streams for hystrix, but with i will use this on load balance,  i need create a endpoint for health, like actuator or if possible the the actuator, but how i can add this on RXNetty server created on TurbineStreamConfiguration?

**Comment by spencergibb** [comment]
You can use tomcat or jetty if you set `management.port`. Then spring boots normal actuator will work. Otherwise you are on your own (at least untill spring boot 2.0).
