### ISSUE TITLE
Hystrix Dashboard Doesn't Load

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#158]
I started the customer-stores sample and started the hystrix-dashboard sample.  I went to http://localhost:7979/hystrix/ and entered http://localhost:9000/hystrix.stream but the dashboard never loads, the Loading messages never go away.

**Comment by spencergibb** [comment]
did you hit the `/customers` endpoint first?  No data is sent until the circuit breaker is hit once.

**Comment by spencergibb** [comment]
if not, any errors in the browser console or logs from either server?  Unable to replicate on my side.

**Comment by ryanjbaxter** [comment]
My bad @spencergibb didn't realize you needed to hit the endpoint first.  Thanks for pointing that out!

**Comment by ryanjbaxter** [comment]
If nothing executes the code wrapped in the hystrix command then there is no data to show in the dashboard.  In the case about the `/customers` endpoint executed the code wrapped in the hystrix command so once that endpoint was hit data began showing in the dashboard.
