### ISSUE TITLE
Zuul Proxy change Content-Type headers for data parts in multipart requests

### ISSUE THREAD

**Issue by eloipoch** [spring-cloud/spring-cloud-netflix#1581]
Nowadays the actual Zuul Proxy changes a multipart request like:
```
POST /some-url HTTP/1.1

Content-Type: multipart/form-data; boundary=5057f79b-d299-4665-af15-067a58f18ced
Content-Length: 122309
Host: someserver

--5057f79b-d299-4665-af15-067a58f18ced
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg
Content-Length: 121566
Content-Transfer-Encoding: binary

#binary data#

--5057f79b-d299-4665-af15-067a58f18ced
Content-Disposition: form-data; name="info"
Content-Type: application/json; charset=UTF-8
Content-Length: 10

{"key": "value"}
--5057f79b-d299-4665-af15-067a58f18ced--
```

to something like:
```
POST /some-url HTTP/1.1

Content-Type: multipart/form-data; boundary=fv0sfELIXUDbZrrgB_UUQ2LOU6P4t_BnWMHCUXSG
Content-Length: 122309
Host: someserver

--fv0sfELIXUDbZrrgB_UUQ2LOU6P4t_BnWMHCUXSG
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/jpeg
Content-Length: 121566

#binary data#

--fv0sfELIXUDbZrrgB_UUQ2LOU6P4t_BnWMHCUXSG
Content-Disposition: form-data; name="info"
Content-Type: text/plain; charset=UTF-8
Content-Length: 10

{"key": "value"}
--fv0sfELIXUDbZrrgB_UUQ2LOU6P4t_BnWMHCUXSG--
```

The major impact in my case is that the `Content-Type` in the second part of the request is changed from "application/json" to "text/html" but __the code what actually does is lose all the headers from the original request data parts__, maintaining only the `Content-Disposition` and `Content-Type` of the file parts.

I can try to do a PR just maintaining the `Content-Type` for data parts or trying to maintain all the headers. What do you think would be the best approach? Or do you have any other idea?

Thanks!

**Comment by ryanjbaxter** [comment]
Can you point us at the code that is not maintaining the headers?

**Comment by eloipoch** [comment]
Of course.

There is a class that extracts the information of original request and stores it for later processing, the `FormBodyRequestWrapper` and when it extracts the information only pick the `key` and the `value`. You can see it [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/FormBodyWrapperFilter.java#L193).

For a normal request with this is enough, but it seems that for a multipart request we need to extract more information and build an `HttpEntity` as we are doing with the file parts.

**Comment by ryanjbaxter** [comment]
OK that makes sense, looking forward to the PR.

**Comment by eloipoch** [comment]
Thank you all!
