### ISSUE TITLE
Zuul routing : One endpoint with multiple microservices

### ISSUE THREAD

**Issue by rami-deltoro** [spring-cloud/spring-cloud-netflix#1584]
Hi,

I would like to setup zuul and the underlying microservices in a way that all services will be under the '/gateway' context.

For example:

Microservice 1 has : http://localhost:8080/api/hello
Microservice 2 has : http://localhost:8080/api/bye

I would want to be able to access the microservices via zuul as follows:

Microservice 1 : http://localhost:8080/gateway/microservice1/api/hello
Microservice 2:  http://localhost:8080/gateway/microservice2/api/bye

I have tried to set this up, although it seems the requests are not getting routed correctly.

The reason I would like the front end to route all client side REST calls to server that begin with '/gateway' is that it provides simpler maintenance to the front end.

My application.yml:
zuul:
    prefix: /gateway
    routes:
        microservice1:
          path: /microservice1/**
          serviceId: microservice1
          strip-prefix: true
        microservice2:
          path: /microservice2/**
          serviceId: microservice2
          strip-prefix: true

Thank you

**Comment by ryanjbaxter** [comment]
I am not able to reproduce the problem locally, could you provide a sample set of apps?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
