### ISSUE TITLE
Request Interceptors can't be add to the Feign builder 

### ISSUE THREAD

**Issue by sebastian-sch** [spring-cloud/spring-cloud-netflix#159]
I want to use Feign together with spring cloud security especially with @EnableOAuth2Resource.

When I request a resource with feign I got a 401. The reason is, that feign didn't include a token in the header.

I created a request interceptor  
```
@Component
public class OAuthRequestInterceptor implements RequestInterceptor {

	private final HttpServletRequest request;

	@Autowired
	public OAuthRequestInterceptor(HttpServletRequest request) {
		this.request = request;
	}

	@Override
	public void apply(RequestTemplate template) {
		String header = request.getHeader("authorization");

		template.header("Authorization", header);
	}
}
```
addition I must enhance the FeignConfiguration to include the interceptor.   

```
	@Autowired
	private RequestInterceptor requestInterceptor;

	protected Feign.Builder feign() {
		Feign.Builder builder = Feign.builder()
				// required values
				.logger(logger).encoder(encoder).decoder(decoder)
				.contract(contract);
		if (requestInterceptor != null) {
			builder.requestInterceptor(requestInterceptor);
		}
```
1. Did I miss something or is Feign with @EnableOAuth2Resource not working?

2. It would be good to allow custom request interceptors.

**Comment by dsyer** [comment]
`Feign` is on the client side and `@EnableOAuth2Resource` is a sever side feature so they are not really connected in any way.

In your interceptor where would the token come from exactly?

**Comment by sebastian-sch** [comment]
I understand, that ```@EnableOAuth2Resource``` is a security feature and is not direct connected with ```Feign```. I have several microservices and the communication to outside and also between the services is done via Rest. I want to use ```Feign``` as an easy way, to get or post data from one service to another. It was my understanding, that this is one reason to include ```Feign``` in Spring Cloud.

The problem starts with, that all my services are secured by ```@EnableOAuth2Resource``` and currently there is no way to easy setup ```Feign``` to request secured services. Also for external services it is not possible to include authorizations into the Feign request.

My interceptor use the token from the header the service gets from the proxy. This is only a first try, not sure if my interceptor will cover all my cases. 

How would you handle the communication between services, when ```Feign``` is not aware of the ```@EnableOAuth2Resource```?

**Comment by dsyer** [comment]
I don't quite follow. Why would `Feign` ever be aware of the `@EnableOAuth2Resource`. And I didn't understand where the access token comes from. If you *do* have an access token though, then you can plug it into your interceptor I suppose? I'm just not quite sure where you want to start.

**Comment by sebastian-sch** [comment]
You are right. I saw it to small. My assumption was, that you have several microservices, each is secured with ```@EnableOAuth2Resource``` and all use the same OAuth provider. Now you can access all services with the same token. 
When a client sends a request to service A and service A need information from service B, service A can use the same token which it received from the client, to request the data from service B with ```Feign```.

Perhaps a general question. If you have the service secured with ```@EnableOAuth2Resource``` what is the recommendation for Rest communication between the services?

**Comment by dsyer** [comment]
> Now you can access all services with the same token

I don't think that's a valid assumption generally, although it *is* quite useful as a quick way to get something working, assuming you control all the services. We could also make every service responsible for its own authentication and require it to obtain an access token on its own, rather than just relaying the value that it was called with.

There are probably several ways we might implement the token relay (your suggestion). The best might be to grab the access token from the incoming request or `Authentication` (like the `OAuth2TokenRelayFilter` does in spring-cloud-security) and wire it up to the Feign client in an interceptor.

**Comment by sebastian-sch** [comment]
My assumption was that I control all the services and it is currently really to get something up quick.

As a first step, it would be enough, to add the possibility to use custom ```requestInterceptor```.

**Comment by spencergibb** [comment]
Regardless of @sebastian-sch use of adding a feign `requestInterceptor`, being able to add one is valid.
