### ISSUE TITLE
Memory Usage In Spring Cloud Sidecar

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-netflix#1595]
We are using a sidecar with a node.js application in our production environment. We are seeing approximately 130 request per second to the sidecar (via the hystrix dashboard) and looking at the heap usage via the actuator.

While the VM seems "healthy" the heap size is larger than we expected: 

The allocated heap is 2GB and we are seeing the in-use heap fluctuate between 700Mb to 1.5G. This seems excessive for what that process is doing. 

Since the Sidecar is using Zuul underneath the covers, I am wondering if we are suffering from the issue #1536 reported by @brenuart? It appears he already has a pull request #1538 for this issue and we would be interested on where this sits in the priority list. 

Thanks

**Comment by spencergibb** [comment]
Closing as #1538 has been merged.
