### ISSUE TITLE
Clearly document the order of various PropertySource in Spring Cloud

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1596]
Unlike [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html), which clearly states the order of various `PropertySource`, Spring Cloud choose to be vague. A non-exhaustive list contains `application.yml`, and `bootstrap.yml` and their profile-specific versions, config service `application.yml` and service specific files and their profile-specific versions, and perhaps [Kubernetes PropertySource](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes#kubernetes-propertysource). Can it get more confusing if not documented?

**Comment by spencergibb** [comment]
That's fine, but it should be opened in a different repository, probably Spring Cloud commons.

**Comment by asarkar** [comment]
Ok. https://github.com/spring-cloud/spring-cloud-commons/issues/165
