### ISSUE TITLE
SimpleRouteLocator: Change fields from private to protected to support extension

### ISSUE THREAD

**Issue by nafiux** [spring-cloud/spring-cloud-netflix#1598]
Hi team, I want to implement my own `public Route getMatchingRoute(final String path)` method, and I would like to extend the functionality from **SimpleRouteLocator**, the problem is that the fields are **privated** and I should implement all the code again.

I think that changing **private** to **protected** will do the trick. I don't want to redo all the code since that implies more responsibility to maintain a healthily code.

Please let me know if it's suitable. Thanks.

**Comment by spencergibb** [comment]
Pull requests welcome, though I'd prefer protected getters rather than protected fields.
