### ISSUE TITLE
Add possibility to disable zuul.prefix for a specific route

### ISSUE THREAD

**Issue by martinreus** [spring-cloud/spring-cloud-netflix#1605]
Hello all,

I am currently working on a project where I am using ZuulProxy along with Eureka in order to automatically discover micro services and reroute calls. I have set the following property in application.yml:

```
zuul:
  prefix: /api
```
so that all routes are prepended with "/api" before every microservice name. This works great! However, I also want the root path ("/") to point to a webserver with static content, without hosting it directly in the zuul proxy server. The problem is that I cannot define a "/" zuul route without the "/api" prefix for the static content, since "/api" is appended to all routes.

Does it make sense to add the property "useCommonPrefix", with default value=true, under defined routes, so that the prefix may be disabled on demand?
Example:

```
zuul:
  routes:
    client:
      path: /**
      serviceId: web-frontend
      ---> useCommonPrefix: false  <---
  prefix: /api
```

Best regards,
Martin

**Comment by spencergibb** [comment]
The route definitions are already complicated enough. What you want can be achieved without a common prefix by manually adding the prefix to each route. You might be able to use a mvc controller that is registered at `/` and forward to the static content.

**Comment by martinreus** [comment]
yes, I could declare each route in application.yml, but then zuul proxy + eureka wouldn't make much sense, since I would then need to programatically declare each route I am creating, instead of relying on automatic proxying with service discovery.

**Comment by ryanjbaxter** [comment]
I think @spencergibb means to define the prefix as part of the `path` property.

**Comment by martinreus** [comment]
@ryanjbaxter I know about the `path` property, but what I am trying to achieve is something a little bit different.

I have following microservices (all spring boot apps with `@EnableEurekaClient`, registered under an Eureka server):
users
ratings
movies
web-frontend

And a gateway server, also a spring boot app with the main class annotated with `@EnableZuulProxy`. In this gateway application, the only thing I would declare in application.yml, would be
```
zuul:
  prefix: /api
```
and when accessing http://gatewayUrl:8080/api/ratings I would be automatically rerouted to the ratings micro-service behind my zuul proxy, without me having to declare this route specifically in the gateway app. This all works fine, like I already said, but the problem is that I cannot declare a `path: /` because it would still have the `/api` prepended onto it. So I would never be able to declare a "/" path pointing to a microservice if I already used the `prefix` property. Hope this example is a little bit more clear :)

**Comment by ryanjbaxter** [comment]
I think we understand what you are saying, its just that what you want to do is already possible with the available configuration today.  The only downside is that your configuration needs to be more verbose.

**Comment by martinreus** [comment]
Yep.. well I can also have an additional proxy + load balancer (nginx for instance) in front of the zuul proxy server.. this would also do the trick.. but thanks for the feedback! Should I close this issue?

**Comment by ryanjbaxter** [comment]
Yes I don't think we have any plans to make this enhancement.  Thanks!
