### ISSUE TITLE
Question : custom eureka registration

### ISSUE THREAD

**Issue by gangakrishh** [spring-cloud/spring-cloud-netflix#1607]
Hi,

My application connects to elasticsearch while starting up. want to delay the eureka registration. how to achieve this one?

i've found this https://jmnarloch.wordpress.com/2015/09/02/spring-cloud-fixing-eureka-application-status/ bit confusing

**Comment by spencergibb** [comment]
I'd say set the initial status to out of service 
```
eureka.instance.initialStatus=OUT_OF_SERVICE
```

You'd need to write code to change it once you determined the app is available (event listener, actuator endpoint) or the health check handler as described in the blog post.

**Comment by gangakrishh** [comment]
how to do with Actuator ? accessing actuator endpoint inside same app

**Comment by spencergibb** [comment]
It would be similar to code that is in main and will be released after boot 1.5

https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistry.java#L76-L88

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
