### ISSUE TITLE
PropertiesFactory doesn't instanciate ServerListFilter if the target class is not aware of IClientConfig

### ISSUE THREAD

**Issue by gronono** [spring-cloud/spring-cloud-netflix#1608]
Hello,
I try to override the default `ServerListFilter`. So I added `<my-remote-service>.ribbon.NIWSServerListFilterClassName: <my-class>` in the client's configuration.
The class only implements ServerListFilter and have a default constructor (it doesn't implement `IClientConfigAware` neither has a constructor with `IClientConfig` argument).

My case isn't handled by the `org.springframework.cloud.netflix.ribbon.SpringClientFactory#instantiateWithConfig` method. It caught by the catch.

I think this a bug. Anyway, the method `Class.getConstructor()` cannot return null. In this case, a `NoSuchMethodException` will be thrown. So the code should be more like that:

```
try {
  Constructor<C> constructor = clazz.getConstructor(IClientConfig.class);
  result = constructor.newInstance(config);
} catch (NoSuchMethodException e) {
  result = BeanUtils.instantiate(clazz);
}
```

And I don't understand why the method doesn't throw an Exception if the class cannot be instantiated.

Anyway, thank you a lot for your hard work.

**Comment by spencergibb** [comment]
Any particular reason you are using properties and not `@Beans` like [this](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#customizing-the-ribbon-client)?

**Comment by spencergibb** [comment]
Pull Requests welcome!

**Comment by gronono** [comment]
There is no actual reason. In my mind, the properties based method was more comprehensible. I will try the method with `@Beans`.

And yes, I will try to make a PR. 
Should I keep the fact, if the class cannot be instanciate, the method returns `null `?

**Comment by spencergibb** [comment]
Yes, keeping existing semantics would be ideal.

**Comment by gronono** [comment]
Thanks
