### ISSUE TITLE
Documentation for adding custom Zuul filters

### ISSUE THREAD

**Issue by ivarulz** [spring-cloud/spring-cloud-netflix#161]
Hi,

It would be good to have clear documentation on how to add a custom filter for Zuul.

Right now it is not clear for me where should I drop my class to be picked up by Zuul.

Thanks

**Comment by ivarulz** [comment]
So far I managed to register a filter like this:
@Component
public class DummyPostFilter extends ZuulFilter {
...

**Comment by dsyer** [comment]
I tsays here: http://projects.spring.io/spring-cloud/spring-cloud.html#_plain_embedded_zuul

> Any beans that you add to the application of type `ZuulFilter` will be installed automatically.

If that's not clear enough maybe you could propose a change, e.g. a small example?

**Comment by ivarulz** [comment]
My initial mistake was that I did not annotate the bean with @Component. Without the annotation I could not spot the filter execution
