### ISSUE TITLE
Can't forward media types 

### ISSUE THREAD

**Issue by aaadipop** [spring-cloud/spring-cloud-netflix#1610]
I can't forward jpg/pdf files ...

Upload works good.

If I try to get the file from api I got it but if i try to get the file through proxy i got a white page ( white page for pdf files and broken image icon for images) and Content-Length and X-Application-Context headers are missing 

The controller method:

```
@RequestMapping(value = "/file/{filename:.+}", method = RequestMethod.GET)
	public ResponseEntity<?> getFile(@PathVariable("filename") String filename) {

              ........

        HttpHeaders headers = new HttpHeaders();
        //headers.add("content-disposition", "attachment; filename=" + fileUpload.getFilename());
        headers.add("content-disposition", "inline; filename=" + fileUpload.getFilename());

        String primaryType, subType;
        try {
            primaryType = fileUpload.getMimeType().split("/")[0];
            subType = fileUpload.getMimeType().split("/")[1];
        }
        catch (IndexOutOfBoundsException | NullPointerException ex) {
            return new ResponseEntity<>("{}", HttpStatus.INTERNAL_SERVER_ERROR);
        }

        headers.setContentType( new MediaType(primaryType, subType) );

         return new ResponseEntity<>(fileUpload.getFile(), headers, HttpStatus.OK);
```

and Zuul version : 1.1.3.RELEASE

**Comment by ryanjbaxter** [comment]
Can you provide the complete source code via a GitHub project or zip?

**Comment by aaadipop** [comment]
here : https://github.com/aaadipop/zuul-test

and one endpoint (without zuul) : https://media.naturspot.ro/public/images/deserturi-craciun-blog.jpg

**Comment by spencergibb** [comment]
With mapping 
```
zuul:
  routes:
    resource:
      path: /resource/**
      url: https://media.naturspot.ro
```

And trying to access http://localhost:8080/resources/public/images/deserturi-craciun-blog.jpg I get a 404 because it's trying to access  https://media.naturspot.ro/resources/public/images/deserturi-craciun-blog.jpg

**Comment by spencergibb** [comment]
hmm, needing more testing

**Comment by aaadipop** [comment]
resource is mapped without s 

So the url is : http://localhost:8080/resource/public/images/deserturi-craciun-blog.jpg

**Comment by spencergibb** [comment]
can you try with curl rather than a browser? your post filter if throwing a NPE exception BTW. Change catch to Exception rather than IOException

**Comment by aaadipop** [comment]
I try this : curl -O http://localhost:8080/resource/public/images/deserturi-craciun-blog.jpg 

but the image has empty size and i can't see it 

and if i comment all lines from run() function in PostZuulFilter it's working but if i try this

```
            final InputStream is = ctx.getResponseDataStream();
            String responseBody = IOUtils.toString(is, "UTF-8");
//            if (responseBody.contains("refresh_token")) {
//            		//                action 1
//            }
//            if(ctx.getRequest().getRequestURI().contains("/logout")){
//            		//            	action 2
//            }
            ctx.setResponseBody(responseBody);
```

isn't working ... so i think the problem is at this 3 lines ... and i don't get it ...

**Comment by aaadipop** [comment]
... ??

**Comment by spencergibb** [comment]
??

**Comment by aaadipop** [comment]
about last comment ... 3 days ago

**Comment by aaadipop** [comment]
why with 
```

@Override
    public Object run() {
        return null;
    }
```

I got the image and with 

```
    @Override
    public Object run() {
        final RequestContext ctx = RequestContext.getCurrentContext();
        logger.info("in zuul filter " + ctx.getRequest().getRequestURI());

        try {
            final InputStream is = ctx.getResponseDataStream();
            String responseBody = IOUtils.toString(is, "UTF-8");
//            if (responseBody.contains("refresh_token")) {
//            		//                action 1
//            }
//            if(ctx.getRequest().getRequestURI().contains("/logout")){
//            		//            	action 2
//            }
//            	ctx.setResponseBody(responseBody); 

        } catch (final Exception e) {
        	System.out.println("into error "+ e);
            logger.error("Error occured in zuul post filter", e);
        } 
        return null;
    }
```

the image isn't forwarded

**Comment by aaadipop** [comment]
hmm ... if I comment 

`String responseBody = IOUtils.toString(is, "UTF-8");`

is working so the problem is here ...

and I tried with all alternatives from this answer except those for java 8 : http://stackoverflow.com/a/35446009/3610959
and didn't work

and the code didn't reach the catch clause 

any ideas??

thanks

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
