### ISSUE TITLE
@FeignClient does not support @GetMapping and the other new @RequestMapping annotations

### ISSUE THREAD

**Issue by Petitt88** [spring-cloud/spring-cloud-netflix#1615]
I get a BeanCreationException saying "FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: Method XXX not annotated with HTTP method type (ex. GET, POST)" when I try to use the new @GetMapping annotation on a @FeignClient. I assume the situation is the with the rest (@PutMapping, @PostMapping, @DeleteMapping).

This is my client:
```java
@FeignClient("book-service")
public interface BookServiceClient {

	@GetMapping("")
	Collection<List<Book>> getBooks();

}
```

**Comment by spencergibb** [comment]
Duplicates #1201

**Comment by shenjiazhiyuan** [comment]
Yes.Please use @RequestMapping or use RestTemplate to do it.
