### ISSUE TITLE
zuul with undertow "stop the world"  

### ISSUE THREAD

**Issue by kanouken** [spring-cloud/spring-cloud-netflix#1618]
my apiGateway  is worked on the spring cloud zuul and  undertow ,
every one week , all the request will be hangs  on,
i use the jmap to check the mem  everything is ok;

**Comment by kanouken** [comment]
the config below

`server.port=8888
spring.application.name=apiGateway


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

zuul
zuul.ignoredServices=*
ribbon.eureka.enabled=true


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=60000
ribbon.ConnectTimeout=3000
ribbon.ReadTimeout=60000`

**Comment by marcosbarbero** [comment]
@kanouken could you elaborate a little more? I still don't follow what is the issue

**Comment by kanouken** [comment]
All the request to ApiGateway (Zuul) without response but the process is still work on and no any other information have warned .
I suppose there is something wrong with Undertow .
Please advise what caused this problem.
Thanks

**Comment by ryanjbaxter** [comment]
If you think it is a problem with Undertow than I suggest you open an issue with them.  If you can narrow down the problem to something in Spring Cloud Netflix than reopen this issue and provide a reproducible sample.  We would be happy to look into it.

**Comment by chenjpu** [comment]
That's what happened to me. 
In some cases, undertow will not be able to provide services, like zombies
