### ISSUE TITLE
FeignAutoConfiguration doesn't allow to externalise feign client configuration 

### ISSUE THREAD

**Issue by mpryahin** [spring-cloud/spring-cloud-netflix#1619]
Hi guys!

I'm using FeignAutoConfiguration to instantiate the feign client which is located in the separate jar and implemented with no custom Configuration defined in its annotation.

In my app I need to add extra configuration to this client (e.g add extra Interceptors), and I thought that I had successfully accomplished the task by creating a FeignClientSpecification bean for that client. But this won't work due to the following:

Clients are registered in the spring context with FeignClientsRegistrar. FeignClientsRegistrar associates FeignClientSpecification for every client, in case the particular client has no default configuration specified the a FeignClientSpecification instance with an empty array of configurations is created.

Finally in the FeignAutoConfiguration I've got a collection of two FeignClientSpecifications one of which contains no configurations as I described above and another one contains configuration class. Both of them have the same name because they were specified for the same client. And when these FeignClientSpecifications are being set to the FeignContext class the last  FeignClientSpecifications (with empty config classes) overrides the instance with configuration... 

From my perspective it would be great if  FeignClientSpecifications with empty configuration aren't included into the FeignContext or another approach is that external Configurations override configuration specified within the feign client annotation.

**Comment by ryanjbaxter** [comment]
Can you deal with this by specifying the packages to scan in `@ComponentScan`?

**Comment by spencergibb** [comment]
@mpryahin `FeignClientsRegistrar` and `FeignClientSpecification` were not really meant to be used outside of `@EnableFeignClients`. `@EnableFeignClients` has `basePackages` and `basePackageClasses` attributes to let you scan for clients outside of the package where the annotation is used. You can also use the `clients` attribute to specify specific clients without scanning.

**Comment by spencergibb** [comment]
Outside of those, I'd recommend using the feign api directly to create the clients. See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#creating-feign-clients-manually

**Comment by mpryahin** [comment]
Thanks a lot for all your replies!! will try all your suggestions 
and just to make things clear, I'd like to clarify things
I've got the following configuration:

    @EnableAutoConfiguration
	@EnableFeignClients(clients = CloudClient.class)
	@Configuration
	public class Application {

        @Bean
	    public FeignClientSpecification feignClientSpecification() {
	        return new FeignClientSpecification(
	            "mySericeId", new Class<?>[] {MyCloudClientConfig.class}
	        );
	    }

	    public static void main(String[] args) {
	        SpringApplication.run(Application.class, args);
	    }
	}

and in a separate jar I've got the client defined:

    @FeignClient("myServiceId")
    public interface CloudClient extends Client {
    }

Finally in the FeignAutoConfiguration class I've got the following property List<FeignClientSpecification> configurations set with two FeignClientSpecification instances:
one that is instantiated by FeignClientsRegistrar that has the following properties:

    name = "myServiceId"
    configuration = empty array
another one that is defined by myself with properties set:

    name = "myServiceId"
    configuration = [MyCloudClientConfig.class]

and finally the FeignContext is instantiated in the FeignAutoConfiguration with those configurations like the following:

    @Bean
	public FeignContext feignContext() {
		FeignContext context = new FeignContext();
		context.setConfigurations(this.configurations);
		return context;
	}

where #context.setConfigurations(this.configurations) looks like the following:

	public void setConfigurations(List<C> configurations) {
		for (C client : configurations) {
			this.configurations.put(client.getName(), client);
		}
	}

these leads to that one FeignClientSpecification that has no configuration overrides another FeignClientSpecification because both of them have the same names.

**Comment by spencergibb** [comment]
Don't scan for `CloudClient.class` the one in the external jar, just scan the one locally.

**Comment by mpryahin** [comment]
spencergibb thanks a lot!

Do you mean that Configuration is meant to be specified in the CloudClient class directly in the annotation like this?

    @FeignClient(name= "myServiceId", configuration = MyCloudClientConfig.class)
    public interface CloudClient extends Client {
    }
and not elsewhere in the spring context by means of specifying custom FeignClientSpecification?

thank you!

**Comment by spencergibb** [comment]
yes it is.
