### ISSUE TITLE
Support for Spring Web Reactive

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1621]
Are their any problems/gotchas in using Spring Cloud with Spring Web Reactive that early adopters need to be aware of? I see [1554](https://github.com/spring-cloud/spring-cloud-netflix/issues/1554) open, but it is specific to Feign. [Here](https://github.com/sdeleuze/spring-reactive-playground) is a project that uses Boot with Web Reactive.
If currently Spring Cloud won't work with Web Reactive, what is the plan to support it in the future?

**Comment by spencergibb** [comment]
Duplicates #1377
