### ISSUE TITLE
Relationship among various Eureka properties and how those affect Eureka clustering and failover

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1627]
Please explain the relationship among the following, and how these affect Eureka clustering and failover. Is this documented someplace? [Netflix Wiki](https://github.com/Netflix/eureka/wiki) doesn't go into details about these.

```
eureka.instance.metadataMap.instanceId
eureka.instance.hostname
eureka.instance.virtualHostName
eureka.instance.appName
spring.application.name
```

**Comment by ryanjbaxter** [comment]
Are you referring to Eureka client clustering and failover or Eureka server clustering and failover?  Are you experiencing some kind of problem that you think is related to these properties?

**Comment by asarkar** [comment]
I'm trying to understand how Eureka clustering and failover works. The doc has a section "Peer Awareness" that hooks up 2 Eureka instances with unique `eureka.instance.hostname` and then manipulates the hosts file to point both hostnames to localhost. There is no explanation given for why this approach was taken. I can run 2 instances of Eureka on the same host with different ports, and be able to cluster them. Why is it necessary to define unique `eureka.instance.hostname`?

Also, in [EurekaInstanceConfigBean](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java), I see the following:
```
@Override
public void setEnvironment(Environment environment) {
	this.environment = environment;
	// set some defaults from the environment, but allow the defaults to use relaxed binding
	RelaxedPropertyResolver springPropertyResolver = new RelaxedPropertyResolver(this.environment, "spring.application.");
	String springAppName = springPropertyResolver.getProperty("name");
	if(StringUtils.hasText(springAppName)) {
		setAppname(springAppName);
		setVirtualHostName(springAppName);
		setSecureVirtualHostName(springAppName);
	}
}
```

Why is `virtualHostName` and set to `springAppName`? How is the `virtualHostName` related to `springAppName` and `eureka.instance.hostname`?

The problem I see is that Spring Cloud builds on top of Netflix OSS but no explanation of the internals is given. So the users of the framework can't utilize it to the fullest because they simply don't understand it. I'm looking into code now, but so have many others who have similar questions. Here are 2 tickets that are open for **years** now without answers.

https://github.com/spring-cloud/spring-cloud-netflix/issues/373

http://stackoverflow.com/questions/33921557/understanding-spring-cloud-eureka-server-self-preservation-and-renew-threshold

**Comment by spencergibb** [comment]
The code you linked to in `EurekaInstanceConfigBean.setEnvironment()` is just to set some defaults. They are all required, there for we want to provide a default which is `spring.application.name`.

Eureka was built to run on AWS and, in many cases, used hostname as the unique identifier.

- `eureka.instance.metadataMap.instanceId`: the unique id for the instance
- `eureka.instance.hostname`: the hostname eureka advertises
- `eureka.instance.virtualHostName`: sort of like an alias, can be used to query in eureka api (we don't use it)
- `eureka.instance.appName`: The 'application' this instance belongs to.
- `spring.application.name`: The name of the application.

**Comment by asarkar** [comment]
@spencergibb Thanks for your response. I've some follow up questions:

> `eureka.instance.hostname`: the hostname eureka advertises

Considering the example in the doc, if this is set to `localhost`, both Eureka peer instances will advertise as running on localhost, which will be true. They'll be running on separate ports though. However, that doesn't seem to work. Why not?

> `eureka.instance.appName`: The 'application' this instance belongs to.

An Eureka instance doesn't belong to any particular Eureka client so is this only relevant if different apps use different Eureka instances? I believe Netflix also has a concept of app group (not sure in Spring); wouldn't that be the same thing as this?

**Comment by spencergibb** [comment]
> However, that doesn't seem to work. Why not?

> Eureka was built to run on AWS and, in many cases, used hostname as the unique identifier.

Application is a eureka concept. I haven't used or seen anything about app group besides the field in  the config bean.

**Comment by asarkar** [comment]
> Eureka was built to run on AWS and, in many cases, used hostname as the unique identifier.

Even if `eureka.instance.metadataMap.instanceId` is defined and unique? Sorry for the back and forth, but these is information is extremely useful. I'll be glad to contribute to the docs once I gain a somewhat fuller understand.

**Comment by spencergibb** [comment]
In some cases, yes.

**Comment by asarkar** [comment]
After more digging, appears that `eureka.instance.instanceId` is defaulted to `hostname:port` so it is unique even on the same host. However, `com.netflix.eureka.cluster.PeerEurekaNodes.isThisMyUrl` filters out the peer URLs that are on the same host. This may have been done to prevent the instance registering as it's own peer, but I think they should've included the port considering the possibility of running multiple instance on the same host.
I'm thinking of filing a bug against Netflix Eureka. @spencergibb What's your thought on that?
