### ISSUE TITLE
Question about turbine version.

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1629]
I use Spring Cloud Camden SR4 and I find that the version of tuebine in these dependencies are different.

* `spring-cloud-starter-turbine`  uses turbine-core-1.0.0

```xml
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-turbine</artifactId>
</dependency>
```

* `spring-cloud-starter-turbine-stream` uses turbine-2.0.0-DP.2

```xml
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-turbine-stream</artifactId>
</dependency>
```

**Is it a bug?** OR is there any thought storm?

**Comment by ryanjbaxter** [comment]
Are different from what?  You say you are using `Camden.SR4`, what are you comparing it against?

**Comment by spencergibb** [comment]
Those are the correct versions. Unsure what "OR is there any thought storm?" means.

**Comment by eacdy** [comment]
@ryanjbaxter @spencergibb 
I mean `spring-cloud-starter-turbine` 1.2.4 uses turbine-1.0.0, `spring-cloud-starter-turbine-stream` 1.2.4 uses turbine-2.0.0-DP2.
[https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine-stream/pom.xml](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine-stream/pom.xml)

**Comment by spencergibb** [comment]
> Those are the correct versions

It's on purpose.

**Comment by tjuchniewicz** [comment]
So this is a bug. Please see differences between 1.0 and 2.0.
See: https://github.com/Netflix/Turbine/issues/100, https://github.com/spring-cloud/spring-cloud-netflix/issues/1113, https://github.com/spring-cloud/spring-cloud-netflix/issues/2387

**Comment by tjuchniewicz** [comment]
We need to align Turbine version in both poms or introduce switch in dashboard to select Turbine version backend.

**Comment by login2014** [comment]
what is the mean "introduce switch in dashboard to select Turbine version backend."?how can I do? Could you cut the picture or show me the url?I'm a newbie.

**Comment by login2014** [comment]
what is the mean "introduce switch in dashboard to select Turbine version backend."?how can I do? Could you cut the picture or show me the url?I'm a newbie.

**Comment by tjuchniewicz** [comment]
@login2014 There is no such feature for now.

**Comment by taasjord** [comment]
We are having trouble now with the wrong TPS calculation from Turbine stream. Is the situation in Spring Cloud that there is turbine version 1.0 but a dashboard that is only compatible with turbine 2? 

It seems Netflix has basically abandoned the Hystrix Dashboard and it is now moved to https://github.com/Netflix-Skunkworks/hystrix-dashboard. There is a pull request there: https://github.com/Netflix-Skunkworks/hystrix-dashboard/pull/6, that looks like will fix the issue.

**Comment by tjuchniewicz** [comment]
Hi @taasjord .

This is little bit more complicated. After this change: https://github.com/Netflix/Hystrix/issues/1251, copied also do Spring Cloud Netflix, Dashboard does not work correctly with both versions. In details:

| Dashboard Feature | Turbine 1.0 | Turbine 2.0 |
| :---                           |     :---:        |      :---:         |
| Command Charts    |  WRONG VALUES     |   OK  |
|  Thread pools    | OK       |   WRONG VALUES    |

We should wait for https://github.com/Netflix-Skunkworks/hystrix-dashboard/pull/6 to be integrated and integrate this into Spring Cloud Netflix. This will fix issue for Turbine 1.0 only.

**Comment by spencergibb** [comment]
We don't need to wait since we forked the dashboard. We should provide an option or parameter depending on which version of turbine is used

**Comment by tjuchniewicz** [comment]
Right. To quickly make Dashboard compatible with Turbine 1.0 we can revert https://github.com/spring-cloud/spring-cloud-netflix/pull/2388 and create new ticket to make it compatible with Turbine 2.0.

**Comment by taasjord** [comment]
If anyone else needs to fix it themselves, I simply applied the change in https://github.com/Netflix-Skunkworks/hystrix-dashboard/pull/6 (a revert of  https://github.com/spring-cloud/spring-cloud-netflix/pull/2388) on a hystrixCommand.js copied from Spring Cloud source into the same path in static folder of my @EnableHystrixDashboard application, and it did work for me. It is now showing correct requests per second.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
