### ISSUE TITLE
Zuul - Websocket proxy

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#163]
We currently have a direct Websocket connection that goes to a backend webservice (via a load balancer F5).

If we get F5 out of the picture in what regards webservices, and F5 will only talk to Zuul (let's say), can we proxy a websocket connection from browser to webservice via Zuul?

**Comment by dsyer** [comment]
Zuul 1.x is pretty much limited to HTTP as far as I know (@spencergibb correct me if I'm wrong), and the current Spring Cloud proxy filter is probably not well suited to non-REST payloads (e.g. streaming). If we move to Zuul 2.0 at some point it opens up other possibilities.

**Comment by ivarulz** [comment]
Hi Dave,

Is there a 2.0 for Netflix Zuul?

**Comment by dsyer** [comment]
I believe it hasn't been released yet.

**Comment by ivarulz** [comment]
Ok, Thanks

**Comment by paskos** [comment]
we're starting websocket development. Very very very interested in websocket support in zuul. Any news or ETA ?

**Comment by spencergibb** [comment]
See this comment from zuul issues: https://github.com/Netflix/zuul/issues/112#issuecomment-146578671. The short is zuul can _terminate_ websockets in v2, but full duplex channels will come after a stable v2 and they integrate http://reactivesocket.io.

**Comment by aivans** [comment]
Thanks. By scenario 1 they mean to support terminating websockets natively, ie do not plugin another 3rd party support like Spring Websockets?

**Comment by tur-ing** [comment]
Is there already an update of Zuul that supports the full duplex channels on websockets?

**Comment by dsyer** [comment]
AFAIK there is no Zuul 2.x yet (they got to a release candidate and then stalled). Just keep tracking the Netflix issue.

**Comment by cforce** [comment]
See also this alterntive: https://jmnarloch.wordpress.com/2015/11/11/spring-cloud-sock-js-stomp-zuul-no-websockets/

**Comment by vladislav-sidorovich** [comment]
позорище

**Comment by kongslund** [comment]
Zuul 2 is just right around the corner but although websocket support is planned it will not be part of the first release.

[Zuul 2 : The Netflix Journey to Asynchronous, Non-Blocking Systems ](techblog.netflix.com/2016/09/zuul-2-netflix-journey-to-asynchronous.html?m=1)

> We are in the process of releasing Zuul 2 as open source. Once it is released, we’d love to hear from you about your experiences with it and hope you will share your contributions! We plan on adding new features such as http/2 and websocket support to Zuul 2 so that the community can also benefit from these innovations.

**Comment by mthizo247** [comment]
We have created a web socket support feature to resolve this issue. I will be creating a pull request in spring cloud netflix soon. The library and demo are currently hosted in github.

**Comment by spencergibb** [comment]
@mthizo247 I assume these https://github.com/mthizo247/spring-cloud-netflix-zuul-websocket https://github.com/mthizo247/zuul-websocket-support-demo

**Comment by spencergibb** [comment]
It's not really zuul websocket support, it's a standalone websocket proxy that happens to sit next to zuul, correct @mthizo247?

**Comment by mthizo247** [comment]
@spencergibb yes that's correct.

**Comment by heypaulmcgrath** [comment]
I'm assuming there's been no movement on Zuul 2 or Websocket support so?

**Comment by ExtremeYu** [comment]
@spencergibb https://github.com/mthizo247/spring-cloud-netflix-zuul-websocket https://github.com/mthizo247/zuul-websocket-support-demo not work with zookeeper

**Comment by ExtremeYu** [comment]
@spencergibb the demo of zuul&websocket is not work with service-id,the demo ust support url based service dicsovery

**Comment by spencergibb** [comment]
@ExtremeYu you'll have to speak to the author of the demo.

**Comment by barrett-rob** [comment]
Have been looking at this issue, we have a similar requirement, to proxy websocket connections through a zuul server. The requirement is slightly different though because the websocket connections will be 'special' and won't need to be handled in the same way as other requests that come through zuul. 

Previously this was really easy to achieve with nodejs and http-proxy. This is an example of how to start in java and Spring Boot: [https://github.com/barrett-rob/java-websocket-reverse-proxy](https://github.com/barrett-rob/java-websocket-reverse-proxy)

**Comment by jonfreedman** [comment]
What's the status of Zuul 2.0?  Is 2.0.0-rc.2 suitable for production use or is ["the process of releasing Zuul 2 as open source"](https://medium.com/netflix-techblog/zuul-2-the-netflix-journey-to-asynchronous-non-blocking-systems-45947377fb5c) still ongoing?

**Comment by spencergibb** [comment]
You'll have to ask Netflix

**Comment by tsmgodoi** [comment]
@jonfreedman I think spring cloud now has a new gateway solution (namely, http://cloud.spring.io/spring-cloud-gateway/) which already supports Websockets.

**Comment by ExtremeYu** [comment]
@tsmgodoi what different between the zuul and  spring cloud gateway????????????????????????????????

**Comment by tsmgodoi** [comment]
@ExtremeYu I don't know. I haven't used it yet. I think it is based on spring boot 2.0 and spring framework 5.

**Comment by jonfreedman** [comment]
I spent several hours yesterday looking at the alternatives, none of which I could make work with [netty-socketio](https://github.com/mrniko/netty-socketio).

For reference these include:
 - zuul 1.0 (does not support async)
 - zuul 2.0 (no integration with Spring Boot)
 - spring-cloud-gateway 2.0.0.M1 (requires upgrade on entire Spring stack)
 - https://github.com/mkopylec/charon-spring-boot-starter (always returns HTTP 202 so socket-io does not work)
 - https://github.com/mitre/HTTP-Proxy-Servlet (does not support async)
 - https://github.com/barrett-rob/java-websocket-reverse-proxy (works with sockjs/stomp not socket-io)

Given what I'm trying to achieve I'm just putting this on hold until December.  Currently the Spring release milestones are:
 - Spring 5.0 GA - [2017-09-21](https://jira.spring.io/browse/SPR/?selectedTab=com.atlassian.jira.jira-projects-plugin:roadmap-panel)
 - Spring Boot 2.0.0 - [2017-11-20](https://github.com/spring-projects/spring-boot/milestones)
 - Spring Cloud Finchley.RELEASE - [2017-12-18](https://github.com/spring-projects/spring-boot/milestones)

**Comment by berndgoetz** [comment]
@jonfreedman any new insights since December?

**Comment by spencergibb** [comment]
Zuul 2 will not be incorporated into Spring Cloud. See spring cloud gateway for websockets support
