### ISSUE TITLE
Instance monitor init() giving response code other then 200 without response message

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#1631]
When below line is executed and it does not get response within some fraction of second then it gives response with status code other then 200 and get logged with error message as "Could not initiate connection to host, giving up: "  this does not have any response message with it.

HttpResponse response = gatewayHttpClient.getHttpClient().execute(httpget);

I am not sure about this functionality as it is as expected behaviour but just for knowledge I wanted to know bit more about this feature.

"As we expect a 'ping' at least every 3 seconds even if no data is coming so 4 seconds means something is wrong", This might be related to this.

**Comment by ryanjbaxter** [comment]
Can you provide more details about where this code is, what problems it is causing?

**Comment by JagmohanSharma** [comment]
This code is present in InstanceMonitor as 
/code 
private void init() throws Exception {

        HttpGet httpget = new HttpGet(url);

        HttpResponse response = gatewayHttpClient.getHttpClient().execute(httpget);

        HttpEntity entity = response.getEntity();
        InputStream is = entity.getContent();
        reader = new BufferedReader(new InputStreamReader(is));

        int statusCode = response.getStatusLine().getStatusCode();
        if (statusCode != 200) {
            // this is unexpected. We probably have the wrong endpoint. Print the response out for debugging and give up here.
            List<String> responseMessage = IOUtils.readLines(reader);
            logger.error("Could not initiate connection to host, giving up: " + responseMessage);
            throw new MisconfiguredHostException(responseMessage.toString());
        }
    }


Here when response comes with other then 200 it comes inside the last if condition block and logs error message as 

[2017-01-19T16:52:21,757+0000][E][InstanceMonitor][] - Could not initiate connection to host, giving up: []

Root Cause:

which does not have any error message.

**Comment by JagmohanSharma** [comment]
It happened when it did not get stream data for sometime and was simply getting ping: message without stream specific data. 

I got this statement from the same class

"As we expect a 'ping' at least every 3 seconds even if no data is coming so 4 seconds means something is wrong",

**Comment by spencergibb** [comment]
`InstanceMonitor` is from upstream turbine BTW.

**Comment by JagmohanSharma** [comment]
Sorry again to ask question at a wrong place in a hurry. I sincerely apologise for this. I have opened another issue at that place. Please provide your inputs on that. Thanks.

https://github.com/Netflix/Turbine/issues/117
