### ISSUE TITLE
Multiple Instances of the Non JVM application

### ISSUE THREAD

**Issue by kaushikNode** [spring-cloud/spring-cloud-netflix#1632]
I have created a Node Application in Cloud Foundry with 1 instance and a side car app. The application status is showing fine in the Eureka Service registry.

I increased the number of instances of the Non JVM application to two. But Side Car and Eureka was not able to recognize it.

Could you please suggest some solution?

**Comment by spencergibb** [comment]
The instance id for each needs to be unique. Have you tried setting `eureka.instance.instanceId`?

**Comment by kaushikNode** [comment]
Instance ID is separate for each SideCar instance. But how does it recognize the instances of the Non JVM application ?

**Comment by spencergibb** [comment]
What does "But Side Car and Eureka was not able to recognize it." mean? Please provide more details, configuration, etc.... The sidecar tells eureka where the non-jvm app is located.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
