### ISSUE TITLE
Add Feign AnnotatedMethodProcessor and AnnotatedClassProcessor

### ISSUE THREAD

**Issue by jvz** [spring-cloud/spring-cloud-netflix#1643]
In the Feign support, there is an `AnnotatedParameterProcessor` customization available. I'd like similar support for method and class annotations. This would also make it simpler to support `@GetMapping`, `@PostMapping`, etc., along with non-MVC annotations (e.g., JAX-RS, Feign's annotations).

**Comment by spencergibb** [comment]
JAX-RS and other are already supported by feign.

**Comment by jvz** [comment]
What can I do when one class is using MVC annotations while another is using Feign annotations? It's not always feasible to remain consistent with the annotations depending on which developers create the interface.

**Comment by spencergibb** [comment]
See the documentation here http://cloud.spring.io/spring-cloud-static/Camden.SR4/#spring-cloud-feign-overriding-defaults

```
@FeignClient(name = "stores", configuration = FooConfiguration.class)
public interface StoreClient {
    //..
}

public class FooConfiguration {
    @Bean
    public Contract feignContract() {
        return new JAXRSContract();
    }
}

```

`JAXRSContract` is from https://github.com/OpenFeign/feign#jax-rs

**Comment by jvz** [comment]
Oh wow, can't believe I missed that. Thanks! I may end up making a PR to clarify the docs then.

**Comment by jvz** [comment]
After trying it out, this solution seems rather hacky itself. This requires every single `@ComponentScan` or `@SpringBootApplication` or similar to add a filter for either a list of configuration classes used only by this library, or a custom annotation which still needs to be manually filtered by every `@ComponentScan`. I guess that's a separate issue, though.

**Comment by spencergibb** [comment]
They don't need the `@Configuration` annotation.

**Comment by jvz** [comment]
Then what does this mean?

>The FooConfiguration has to be @Configuration but take care that it is not in a @ComponentScan for the main application context, otherwise it will be used for every @FeignClient. If you use @ComponentScan (or @SpringBootApplication) you need to take steps to avoid it being included (for instance put it in a separate, non-overlapping package, or specify the packages to scan explicitly in the @ComponentScan).

It has to be `@Configuration` but doesn't need the annotation?

**Comment by jvz** [comment]
Basically, are you saying that I can do something like this?

```java
public class UseFeignAnnotations {
    @Bean
    public Contract contract() {
        return new Contract.Default();
    }
}
```

```java
@FeignClient(name = "foo", path = "/api/v1", configuration = UseFeignAnnotations.class)
public interface FooClient {
}
```

And then I don't need to add `@Configuration` to `UseFeignAnnotations`?

**Comment by spencergibb** [comment]
Docs are wrong :-) https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/feign/FeignClientOverrideDefaultsTests.java#L160-L225

**Comment by jvz** [comment]
Oh that simplifies things quite a bit! Thanks
