### ISSUE TITLE
Replace @RequestMapping variable at runtime

### ISSUE THREAD

**Issue by anshchauhan** [spring-cloud/spring-cloud-netflix#1645]
Hi,

I want to replace a string in requestMapping URL at runtime. It's not a key-value pair. It's just an encrypted string. 
```
@FeignClient(name = "base-service", url = "http://demo.india.com")
public interface BaseService {
	@RequestMapping(value = "/ClientOrderPayment.aspx?{q}", method = RequestMethod.POST)
	public Response getPaymentUrl(@QueryParam("q") String q, @RequestParam("clientCode") String clientCode);
}
```

I've tried @Param, @PathVariable and @QueryParam but it did not work. I'm getting the following exception:
```
Caused by: java.lang.NullPointerException: null
	at feign.RequestTemplate.replaceQueryValues(RequestTemplate.java:605) ~[feign-core-9.3.1.jar:na]
```

**Comment by spencergibb** [comment]
So your example is odd. `q` is a request parameter, but you've put it as a `@PathVariable`. We have tests that use these [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/feign/support/SpringMvcContractTests.java#L503-L506).

Looks like this
```
		@RequestMapping(path = "/test2", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE)
		ResponseEntity<TestObject> getTest2(
				@RequestHeader(name = "Authorization") String auth,
				@RequestParam(name = "amount") Integer amount);
```

**Comment by anshchauhan** [comment]
@spencergibb  Thanks for your reply.

But I want `q` to be appended to the URL in a post request. `q` does not have key value pairs, it's just a large encrypted string. What you are suggesting will send it as in body as x-www-form-urlencoded I guess.

**Comment by spencergibb** [comment]
I don't think that is supported. You could try a `ReqestInterceptor`

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
