### ISSUE TITLE
eureka instance won't use IP address in docker container

### ISSUE THREAD

**Issue by codecitizen** [spring-cloud/spring-cloud-netflix#1646]
Hi,

I'm working on a small spring boot web service which has to register against an eureka server (also written as Spring Boot application). This is my configuration:

```yml
spring:
  application.name: awesomeservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.0.3:8761/eureka/
---
spring:
  profiles: docker
eureka.instance.preferIpAddress: true
```

When running as docker container my service should prefer to register with its IP address instead of the hostname ... **but** it will always use the docker container id (which is the hostname i guess) when I start it using docker-compose.

Neither setting the `euereka.instance.hostname` nor `ipAddress` attribute helps. The `docker` profile is loaded correctly ... looking forward for tips, hints and answers here.

Kind regards,
codecitizen

**Comment by ryanjbaxter** [comment]
How are you determining that it is using the hostname rather than the IP address?

**Comment by codecitizen** [comment]
Hi @ryanjbaxter 

![screen shot 2017-01-25 at 15 16 25](https://cloud.githubusercontent.com/assets/23283603/22293835/6ab21884-e311-11e6-9bbc-0065a1053b1e.png)

In the Web Interface of my Eureka Server it links the hostname

**Comment by ryanjbaxter** [comment]
Those are just instance ids.  If you hover over the links in the browser, or inspect them using the browser developer tools, what do they link to?

**Comment by codecitizen** [comment]
The instance with the id `54814d8e4a23` links to `http://54814d8e4a23:8080/info`

**Comment by ryanjbaxter** [comment]
Ah I think you have the wrong property, I think it should be 'eureka.client.instance.preferIpAddress'

**Comment by codecitizen** [comment]
The [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.2.4.RELEASE/) says `eureka.instance.preferIpAddress`

**Comment by ryanjbaxter** [comment]
You are right, it is hard to read YAML on your phone sometimes :)

It is not obvious to me why it is not working, can you provide a sample that reproduces the problem?

**Comment by spencergibb** [comment]
What does `/eureka/apps` say?

**Comment by spencergibb** [comment]
Also, what does `/env` say? To make sure your property was applied.

**Comment by codecitizen** [comment]
Works now. This morning I rebuilt the the library and docker image and redeployed it to a newly initialized dev system. It registered against the eureka server with the IP Address, everything is fine. I did some testing, pulled up more services, each registered correctly. So there was probably some issue in my build pipeline. 
@spencergibb sorry I can't check the old service for `/eureka/apps` or `/env` ... but yesterday I was debugging through `EurekaInstanceConfigBean#getHostname(boolean)` and it was showing the right values for `preferIpAddress` and `ipAddress`.

**Comment by kimjuny** [comment]
@codecitizen Hi, could you please pin your `application.yml` here (only the essential part) of your eureka server and client? I am facing exactly same problem, and I've tried many times not succeeded yet.

**Comment by eacdy** [comment]
I think you should use `eureka.instance.instance-id`

**Comment by makdeniss** [comment]
I also have this problem. Tried a lot of things, but everything failed.

**Comment by radhey7** [comment]
@codecitizen Hi, Please share your application.yml file

**Comment by makdeniss** [comment]
IF anybody is interested I found the solution. Client services need to have this in their application.properties (or similiar .yml structure):

```
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=IP_OF_MACHINE_ON_WHICH_RUNNING
eureka.instance.instance-id=eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
```

**Comment by radhey7** [comment]
@makdeniss ..can you please share your facebook id

**Comment by radhey7** [comment]
i want to communicate with you ....i am facing the same problem ..but everything failed

**Comment by makdeniss** [comment]
my nick is my skypeid.

**Comment by radhey7** [comment]
@makdeniss i am unable to understand your last line 
eureka.instance.instance-id=eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

**Comment by makdeniss** [comment]
fixed it. had duplicate `eureka.instance.instance-id=`

**Comment by radhey7** [comment]
sent skype request ..please accept

**Comment by kimjuny** [comment]
Hi, it seems network inside docker is rather complex, I can't explain why by this perfectly fixes my problem.

```yml
spring:
  application:
    name: stock-service
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo

```

**Comment by abhilashgopal** [comment]
Hi,

I'm facing the same issue. My service is getting registered with Eureka with Docker container IP. I want it to get registered with the host machine IP address. I tried [ignoring network interfaces](https://cloud.spring.io/spring-cloud-static/Dalston.SR5/multi/multi__spring_cloud_commons_common_abstractions.html#ignore-network-interfaces) too. It is still not working.
Any help would be appreciated.

Thanks.

**Comment by AJ198081** [comment]
Try defining the property - eureka.instance.hostname=http://${server.address}:${server.port}
where server. address and server. port are defined separately.

It may work for you.
