### ISSUE TITLE
Brixton.SR7 Multiple Eureka Nodes not replicating to each other.

### ISSUE THREAD

**Issue by Milesy** [spring-cloud/spring-cloud-netflix#1647]
We have now managed to get SR7 onboarded into our organisation, but we are still experiencing issues with multi node set up.

We have fired up two instances on the same host, but each instance is only showing the other and not itself as well which it always did before.

https://host1:8761/

Application	AMIs	Availability Zones	Status
EUREKA 	n/a (1) 	(1) 	UP (1) - host1:eureka:8762

https://host1:8762/

Application	AMIs	Availability Zones	Status
EUREKA 	n/a (1) 	(1) 	UP (1) - host1:eureka:8761

Our zone property is:

eureka.defaultZone=https://host1:8761/eureka/,https://host1:8762/eureka/

On another occasion, we see two on instance one and nothing on instance two 

Our YML looks like:

```
server:
  port: ${eureka.server.port:8761}
  ssl:
    key-store: ${services.keyStore}
    key-store-password: ${services.keyStorePassword}
    trust-store: ${services.trustStore}
    trust-store-password: ${services.trustStorePassword}
    keyStoreType: jks

security:
  basic:
    enabled: true
  user:
      name: ${eureka.username:eureka}
      password: ${eureka.password:default}

eureka:
  instance:
    hostname: ${server.name:localhost}
    securePort: ${eureka.server.port:8761}
    securePortEnabled: true
    nonSecurePortEnabled: false
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka.defaultZone}
```

And our Spring Boot config looks like:

```
@Configuration
@EnableAutoConfiguration(exclude = {
        RepositoryRestMvcAutoConfiguration.class
})
@EnableDiscoveryClient
public class ApplicationConfig {
    @Value("${eureka.username:eureka}")
    private String eurekaUsername;

    @Value("${eureka.password:default}")
    private String eurekaPassword;

    @Value("${eureka.logging:false}")
    private String eurekaLogging;

    @Bean
    public DiscoveryClient.DiscoveryClientOptionalArgs discoveryClientOptionalArgs() {
        DiscoveryClient.DiscoveryClientOptionalArgs args = new DiscoveryClient.DiscoveryClientOptionalArgs();
        List<ClientFilter> filters = new ArrayList<>();
        filters.add(new HTTPBasicAuthFilter(eurekaUsername, eurekaPassword));

        if ("true".equals(eurekaLogging)) {
            filters.add(new LoggingFilter());
        }

        args.setAdditionalFilters(filters);

        return args;
    }
}
```

And our POM defines simply.

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Brixton.SR7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
```

When I start up the second instance the log output is as follows - nothing strange, and nothing strange in instance 1 either, that's the same

```
25-01-2017 15:23:06 [main] INFO  c.n.d.p.DiscoveryJerseyProvider - Using JSON encoding codec LegacyJacksonJson
25-01-2017 15:23:06 [main] INFO  c.n.d.p.DiscoveryJerseyProvider - Using JSON decoding codec LegacyJacksonJson
25-01-2017 15:23:06 [main] INFO  c.n.d.p.DiscoveryJerseyProvider - Using XML encoding codec XStreamXml
25-01-2017 15:23:06 [main] INFO  c.n.d.p.DiscoveryJerseyProvider - Using XML decoding codec XStreamXml
25-01-2017 15:23:06 [main] INFO  c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
25-01-2017 15:23:06 [main] INFO  c.n.d.DiscoveryClient - Starting heartbeat executor: renew interval is: 30
25-01-2017 15:23:06 [main] INFO  c.n.d.InstanceInfoReplicator - InstanceInfoReplicator onDemand update allowed rate per min is 4
25-01-2017 15:23:06 [main] INFO  c.n.d.DiscoveryClient - Discovery Client initialized at timestamp 1485357786753 with initial instances count: 0
25-01-2017 15:23:06 [main] INFO  c.n.e.DefaultEurekaServerContext - Initializing ...
25-01-2017 15:23:06 [main] WARN  c.n.e.c.PeerEurekaNodes - The replica size seems to be empty. Check the route 53 DNS Registry
25-01-2017 15:23:06 [main] INFO  c.n.e.r.AbstractInstanceRegistry - Finished initializing remote region registries. All known remote regions: []
25-01-2017 15:23:06 [main] INFO  c.n.e.DefaultEurekaServerContext - Initialized
25-01-2017 15:23:08 [main] WARN  c.n.c.s.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
25-01-2017 15:23:08 [main] INFO  c.n.c.s.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
25-01-2017 15:23:08 [main] WARN  c.n.c.s.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
25-01-2017 15:23:08 [main] INFO  c.n.c.s.URLConfigurationSource - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
25-01-2017 15:23:09 [main] INFO  c.n.d.DiscoveryClient - Saw local status change event StatusChangeEvent [timestamp=1485357789399, current=UP, previous=STARTING]
25-01-2017 15:23:09 [DiscoveryClient-InstanceInfoReplicator-0] INFO  c.n.d.DiscoveryClient - DiscoveryClient_EUREKA/host1:eureka:8762: registering service...
25-01-2017 15:23:09 [main] INFO  o.a.c.h.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8762"]
25-01-2017 15:23:09 [main] INFO  o.a.c.h.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8762"]
25-01-2017 15:23:09 [main] INFO  o.a.t.u.n.NioSelectorPool - Using a shared selector for servlet write/read
25-01-2017 15:23:09 [main] INFO  c.j.i.c.t.j.j.Main - Started Main in 10.668 seconds (JVM running for 11.301)
25-01-2017 15:23:09 [DiscoveryClient-InstanceInfoReplicator-0] INFO  c.n.d.DiscoveryClient - DiscoveryClient_EUREKA/host1:eureka:8762 - registration status: 204
25-01-2017 15:23:20 [http-nio-8762-exec-4] INFO  o.a.c.c.C.[.[.[/] - Initializing Spring FrameworkServlet 'dispatcherServlet'
25-01-2017 15:25:09 [Thread-10] INFO  c.n.e.r.PeerAwareInstanceRegistryImpl - Got 1 instances from neighboring DS node
25-01-2017 15:25:09 [Thread-10] INFO  c.n.e.r.PeerAwareInstanceRegistryImpl - Renew threshold is: 1
25-01-2017 15:25:09 [Thread-10] INFO  c.n.e.r.PeerAwareInstanceRegistryImpl - Changing status to UP
```

When I access: https://host1:8761/eureka/apps/EUREKA/ it shows ok - and I can see all the application information, but when I access: https://host1:8762/eureka/apps/EUREKA/ I get get an error ' no element found '

Any help would be greatly appreciated

Thanks

Chris

**Comment by Milesy** [comment]
Ive also tried the following properties:

spring:
  application:
    name: eureka

server:
  port: ${eureka.server.port:8761}

security:
  basic:
    enabled: true
  user:
      name: ${eureka.username:eureka}
      password: ${eureka.password:default}

eureka:
  instance:
    hostname: ${server.name:localhost}
  server:
    enable-self-preservation: false
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${eureka.defaultZone}

There appears no default configuration I can get which gets both instances to see each other. Is there a limitation here because they are both on the same box?

Additionally, the reason we pass the following as a parameter: server.name is because we need to be able to manually set the public FQDN of the host within our internal network as this is how our nodes communicate with each other with SSL. 

eureka:
  instance:
    hostname: ${server.name:localhost}

**Comment by Milesy** [comment]
I also brought up two instances of one of our services on the same host, with the same defaultZone with both eureka instances, and only one of them is showing the correct state of things.

****

**Comment by spencergibb** [comment]
@Milesy stick to one issue please. Eureka was built for AWS and sometimes can get confused about hostnames. See this blog post http://blog.abhijitsarkar.org/technical/netflix-eureka/ with the section on Eureka Server peering. Hostname makes a difference.

**Comment by Milesy** [comment]
Spencer, it's one issue. We have a cluster on a much older version which is stable but the configuration is not working on the newer version as expected. 

I'm just trying to provide you with as much information as possible.

**Comment by spencergibb** [comment]
Eureka won't peer on the same host.

**Comment by Milesy** [comment]
Ok, with that limitation in mind, I have span up a second Eureka on another host on the network (my own machine).

One our dev box (host1) I see:

```
DS Replicas

   host2

Instances currently registered with Eureka

Application	AMIs	Availability Zones	Status

EUREKA 	n/a (1) 	(1) 	UP (1) - host2:eureka:8761
```

and on my machine (host2) I see:

```
DS Replicas

    host1

Instances currently registered with Eureka

Application	AMIs	Availability Zones	Status

SERVICE.ACCOUNT 	n/a (1) 	(1) 	UP (1) - host1:service.account:8090

EUREKA 	n/a (2) 	(2) 	UP (2) - host2:eureka:8761 , host1:eureka:8761
```

Eureka on my local machine can see both instances, yet on the dev box it only sees my machine and not itself.

The account service is only registered with my machine even though it sits on the same host as the account service.

**Comment by Milesy** [comment]
Host 2 logs (my machine) complains with the follows exception:

```
26-01-2017 15:04:39 [TaskBatchingWorker-target_host1-18] ERROR c.n.e.c.ReplicationTaskProcessor - Batch update failure with HTTP status code 401; discarding 1 replication tasks
26-01-2017 15:04:39 [TaskBatchingWorker-target_host1-18] WARN  c.n.e.u.b.TaskExecutors - Discarding 1 tasks of TaskBatchingWorker-target_host1-18 due to permanent error
26-01-2017 15:04:50 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Running the evict task with compensationTime 0ms
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Evicting 1 items (expired=1, evictionLimit=1)
26-01-2017 15:04:50 [Eureka-EvictionTimer] WARN  c.n.e.r.AbstractInstanceRegistry - DS: Registry: expired lease for EUREKA/host2:eureka:8761
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Cancelled instance EUREKA/host2:eureka:8761 (replication=false)
```

Host 1 logs files are basically reversed - complaining seems specific to this error 401 - authentication.

The servers are both secured with spring security and the same credentials, I can access both servers through HTTP with those same credentials on both successfully. The discovery client bean is seeded as it should be as above @Bean

**Comment by Milesy** [comment]
From what I can see in JerseyReplicationClient at the following method the jersey client does not appear to using any HTTP credentials.

```
@Override
    public EurekaHttpResponse<ReplicationListResponse> submitBatchUpdates(ReplicationList replicationList) {
        ClientResponse response = null;
        try {
            response = jerseyApacheClient.resource(serviceUrl)
                    .path(PeerEurekaNode.BATCH_URL_PATH)
                    .accept(MediaType.APPLICATION_JSON_TYPE)
                    .type(MediaType.APPLICATION_JSON_TYPE)
                    .post(ClientResponse.class, replicationList);
            if (!isSuccess(response.getStatus())) {
                return anEurekaHttpResponse(response.getStatus(), ReplicationListResponse.class).build();
            }
            ReplicationListResponse batchResponse = response.getEntity(ReplicationListResponse.class);
            return anEurekaHttpResponse(response.getStatus(), batchResponse).type(MediaType.APPLICATION_JSON_TYPE).build();
        } finally {
            if (response != null) {
                response.close();
            }
        }
    }
```

![jerseyclient](https://cloud.githubusercontent.com/assets/996021/22337982/295e0820-e3de-11e6-8c5f-1769789f627a.png)

**Comment by spencergibb** [comment]
Looks like an upstream fix is needed then?

**Comment by Milesy** [comment]
Some additional information.

The Jersey client as used for discovery looks like this - and has the HTTPBasicAuthFilter that we configured in the config bean before.

![jerseyclient](https://cloud.githubusercontent.com/assets/996021/22341956/b9261f36-e3ea-11e6-9f77-642d10902d6b.png)

The Jersey client used in the replication process looks like this: It doesnt have any knowledge of what credentials to use.

![jerseyclient2](https://cloud.githubusercontent.com/assets/996021/22341958/b928f346-e3ea-11e6-9641-d148d0dccb5c.png)

When I break point within the JerseyReplicationClient I can run the following and see a 401

![jerseyclient3](https://cloud.githubusercontent.com/assets/996021/22341959/b929ee4a-e3ea-11e6-8c3c-12a1cb20ad26.png)

However when I fudge the service URL here to contain the credentials in the URL, the response is 200

![jerseyclient4](https://cloud.githubusercontent.com/assets/996021/22341957/b9278ac4-e3ea-11e6-8f84-64ced6d6db58.png)

I am however not sure whether this is related to the issue of what is visible within the Eureka registration table, or another issue altogether.

I can put in credentials into the defaultZone we use across our cluster, but it defeats the point of needing anything in the discovery client at all then, as credentials in the URL there would also I expect be used by default by that associated jersey client.

**Comment by spencergibb** [comment]
So it looks like either put credentials in the URL or submit a PR to eureka. Does that sound about right?

**Comment by Milesy** [comment]
@spencergibb - is there agreement that the current code does not support peering over http basic authentication without them being in the URL? 

We can live with it in the URL at the moment but the issue we have with that is it means log files are polluted with passwords and log files can be read with developers with lower security than those in which the production application is running. Production passwords we aren't comfortable exposing as it would compromise our whole cluster. 

I'll need to see about the PR side as I am not allowed to just contribute to open source without all sorts of approval so I'll need to seek that authorisation.

**Comment by spencergibb** [comment]
@Milesy yes, it appears peering doesn't support http basic via the filter, only with creds in url.

Log an issue if you can't do the PR right away. Link to this issue. I have good relations with the maintainers, I can ask them, or do a PR myself.

**Comment by shivamgoel** [comment]
@spencergibb Is there any update or work around ?

**Comment by spencergibb** [comment]
@shivamgoel no. It's an upstream eureka problem, see the issue linked above your comment.

**Comment by spencergibb** [comment]
Close in favor of https://github.com/Netflix/eureka/issues/893
