### ISSUE TITLE
SSE not streaming to hystrix dashboard when turbine running in a docker container

### ISSUE THREAD

**Issue by jwconway** [spring-cloud/spring-cloud-netflix#1648]
I have an extremely simple turbine server enabled spring boot app configured to connect to RabbitMQ. When I run this app from my IDE i see the SSE streaming in my browser on localhost:8989 (just ping events as expected). 

When i deploy this application using docker the browser hangs forever, I don't even see any ping messages. I can however hit the /health endpoint on 8080 successfully and see that the status is "UP". I do see the following in the output:
```
SSE Request Received
Starting aggregation
```
And when i eventually close my browser tab:
```
Unsubscribing RxNetty server connection
```

What makes this even more confusing is that if i open fiddler and try to connect again (to dockerised turbine) it works!

This issue happens when using docker toolbox for windows and AWS ECS to deploy the container. All browsers.

When using Docker for Mac Chrome works safari doesnt.

**Comment by spencergibb** [comment]
We've had a few mentions of docker and turbine. See #1121. Can you share a project (including a docker-compose) that recreates the problem?

**Comment by jwconway** [comment]
Just pushed this https://github.com/jwconway/spring-turbine-docker

**Comment by spencergibb** [comment]
```
docker build -t turbine .                                 (10065)[12:10:54]
Sending build context to Docker daemon 44.21 MB
Step 1/8 : FROM anapsix/alpine-java:8_jdk
Get https://registry-1.docker.io/v2/anapsix/alpine-java/manifests/8_jdk: unauthorized: incorrect username or password
```

**Comment by jwconway** [comment]
Weird, the base image is from the public docker registry. Could it be related to this? https://github.com/docker/hub-feedback/issues/711

**Comment by jwconway** [comment]
@spencergibb FYI this issue is reproducible when running the non spring netflix turbine app form the netflix repository, ive raised an issue there.

**Comment by ryanjbaxter** [comment]
Since it is not specific to Spring Cloud I am going to close this issue then.  Can you provide the link to the issue in the Netflix repo for reference?

**Comment by jwconway** [comment]
@ryanjbaxter it seems the issue is with the version of RxNetty that turbine uses. However i dont see how this can be resolved as turbine isnt an actively developed project anymore?

**Comment by ryanjbaxter** [comment]
Yes I know turbine is not in active development anymore, but I am sure if you submit a PR they will work with you to get it merged.
