### ISSUE TITLE
Turbine Dashboard issue

### ISSUE THREAD

**Issue by ivarulz** [spring-cloud/spring-cloud-netflix#165]
Hi,

I have a weird problem.

I am trying to view the Turbine Stream for Zuul.

Hystrix stream works:
Hystrix Stream: http://localhost:8765/hystrix.stream
I can see storesRibbonCommand and customersRibbonCommand statistics.

For Turbine does not work:
Hystrix Stream: http://localhost:8989/turbine.stream?cluster=ZUULSERVER
I can see cust...StoresByLocationLink statistics.

Information in Eureka is:
<application><name>ZUULSERVER</name><instance><hostName>CLUJPC100</hostName><app>ZUULSERVER</app><ipAddr>192.168.0.101</ipAddr><status>UP</status><overriddenstatus>UNKNOWN</overriddenstatus><port enabled="true">8765</port>

I remember this was working yesterday.

**Comment by spencergibb** [comment]
A little more information would be useful (error messages, logs, configuration etc...).  Turbine can only be used to view one service's instances: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#turbine

**Comment by ccit-spence** [comment]
Out of curiosity, are there any thoughts on some sort of interface to read the data from multiple turbine feeds into a single interface?  Realizing depending on the deployment size it could become possibly unmanageable.

**Comment by spencergibb** [comment]
[spring-cloud-netflix-hystrix-amqp](https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-hystrix-amqp) and [spring-cloud-netflix-turbine-amqp](https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-turbine-amqp) use rabbitmq rather than an http stream and you can see all services circuit breakers in one.

**Comment by ivarulz** [comment]
Hi Spencer,

Eureka: Zuul appears like this:
<application><name>ZUULSERVER</name><instance><hostName>CLUJPC100</hostName><app>ZUULSERVER</app><ipAddr>192.168.0.101</ipAddr><status>UP</status><overriddenstatus>UNKNOWN</overriddenstatus><port enabled="true">8765</port><securePort enabled="false">443</securePort><countryId>1</countryId><dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo"><name>MyOwn</name></dataCenterInfo>

![hystrix-zuul](https://cloud.githubusercontent.com/assets/2026928/5807997/45802986-a031-11e4-8c93-d62ca61a4218.png)
![turbine-zuul](https://cloud.githubusercontent.com/assets/2026928/5807998/4581d42a-a031-11e4-8e57-a74d7a6d68b5.png)

**Comment by ivarulz** [comment]
I am pretty sure this was working, meaning seeing the exact info from Zuul single instance (hystrix url) or aggregated (Turbine url)

**Comment by ivarulz** [comment]
is it possible that this commit broke it?
https://github.com/spring-cloud/spring-cloud-netflix/commit/c31f700bae88b2c41d6b738ade56616cc878ec5b

(related to https://github.com/spring-cloud/spring-cloud-netflix/issues/160)

**Comment by spencergibb** [comment]
What is your turbine configuration? ie:

```
turbine:
  aggregator:
    clusterConfig: CUSTOMERS
  appConfig: customers
```

**Comment by spencergibb** [comment]
I don't think c31f700bae88b2c41d6b738ade56616cc878ec5b broke it, otherwise the reading the `hystrix.stream` directly wouldn't work.

**Comment by ivarulz** [comment]
i have the default application.yml:
https://github.com/spring-cloud-samples/turbine/blob/master/src/main/resources/application.yml

let my try configure it

**Comment by spencergibb** [comment]
That sample uses:
```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-turbine-amqp</artifactId>
</dependency>
```
Not the http based turbine from `spring-cloud-netflix-turbine`

**Comment by ivarulz** [comment]
Hi Spencer,

I am a bit lost.

I have this config now:
turbine:
  amqp:
    port: 8989
  aggregator:
    clusterConfig: ZUULSERVER
  appConfig: zuulserver

But I still get the CUSTOMERS default stream.

**Comment by spencergibb** [comment]
That config I showed you was wrong if you are using the `spring-cloud-samples/turbine`.  It pulls from rabbitmq not the http streams.  I'm sure you thought this worked yesterday, but it probably didn't.

**Comment by ivarulz** [comment]
:) Either I was very tired, either it worked.

**Comment by ivarulz** [comment]
Indeed, I checked RabbitMQ queues and the message only come from Customers app.

Is there a way to publish from Zuul also?

**Comment by spencergibb** [comment]
yes, see https://github.com/spring-cloud-samples/customers-stores for an example.
You add this starter:
```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-netflix-hystrix-amqp</artifactId>
</dependency>
```

**Comment by ivarulz** [comment]
had to add 2:

        <dependency>
         <groupId>org.springframework.cloud</groupId>
         <artifactId>spring-cloud-netflix-hystrix-amqp</artifactId>
        </dependency>
        <dependency>
         <groupId>org.springframework.cloud</groupId>
         <artifactId>spring-cloud-starter-bus-amqp</artifactId>         
        </dependency>

**Comment by dinkarthakur** [comment]
Update:-
with springboot 1.3.1 and spring cloud brixton add following depedency.
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-hystrix-stream</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```
