### ISSUE TITLE
healthCheckUrl - what is it needed for?

### ISSUE THREAD

**Issue by Pinny3** [spring-cloud/spring-cloud-netflix#1658]
Hi there,

using the [...]/apps view on the eureka-server I can see entries like 

`<healthCheckUrl>[...]</healthCheckUrl>`

in the overview of my services in eureka. 

I wonder what this is for, since the url with is provided there is never called by anyone. I assume this url is called by the eureka server to check if the service is still there and healthy. 

Do I understood something wrong? Can anyone enlight me?

**Comment by spencergibb** [comment]
Eureka does not make health check calls. It is metadata for external systems.

**Comment by Pinny3** [comment]
Dear Spencer, thank you for your fast reply and clarification.
