### ISSUE TITLE
Question: Zuul Filter - Given a serviceId how do i get service's data from eureka

### ISSUE THREAD

**Issue by tiny-dancer** [spring-cloud/spring-cloud-netflix#1659]
Struggling to find a clean way to gather the eureka data for a given service id in the context of a zuul filter. 

Example Use Case:

Within Zuul, we're looking to write a filter that given a service in eureka, the request is manipulated based on data that the service registered with to eureka. Such as, the url or metadataMap.

Arbitrary Example:
for a service in eureka with urls of: appa-datacenter-a.com and appa-datacenter-b.com,
if url contains "datacenter-a", set host to appa-datacenter-a.com and rewrite url domain as public-datacenter-a.com
 
Dug deep enough to find a somewhat relevant:
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/SpringClientFactory.java#L114

But got to the point where I thought i'd ask the question as I'm guessing there's a simpler way i'm missing in the docs and googlesphere.

Thanks

**Comment by spencergibb** [comment]
Zuul already uses Ribbon and Eureka to perfrom just that. Are you wanting somthing different than the current functionality?

**Comment by tiny-dancer** [comment]
It's the rewrite url portion of the above example that I think is beyond the current implementation, or reading data from the instances metadatamap to drive behavior. It occured to me after writing the above that I'm likely at the wrong level though. I'm guessing this would be more of a custom load balancer for ribbon, similar to the zone aware load balancer?

**Comment by spencergibb** [comment]
Load balancers only know about host and port. No where in spring cloud do they manipulate the path. My gut feeling is a "pre" filter that is run after `PreDecorationFilter`.

**Comment by tiny-dancer** [comment]
good to know, brings me back to original question: given a serviceId is there a streamlined way for grabbing the relevant data from eureka? 

was looking at the `PreDecorationFilter` as reference and appears `routeLocater` didn't have any of the eureka app and instance data, only location (service id) and request path data.  

Found the `SpringClientFactory` and the getInstance method that takes a serviceId and can return a `IClientConfig` but not sure if that's on the right path.

**Comment by ryanjbaxter** [comment]
Have you looked into using `DiscoveryClient`? http://cloud.spring.io/spring-cloud-static/Camden.SR4/#_using_the_eurekaclient

**Comment by tiny-dancer** [comment]
yes perfect! ran into that shortly after as well, that looks like it's housing the data we need.  Strongly appreciate the help in guiding me playing catch up on the architecture here, one more clarification with the updated knowledge:

Let's say we have application Apples registered in eureka with two instances. 

registered hosts within eureka for each instance:
- instance 1: apples-datacentera.internal.com
- instance 2: apples-datacenterb.internal.com

ideal code:
```
if (instance.host.contains('datacenterb.internal.com)) {
    req.host = 'apps-datacenterb.internal.com'
    req.headers.host = instance.host
}
```
because we need to analyze each instance specifically, that leads me to believe this would need to be at a ribbon level and a filter is to high level?

1) is this possible and if so, is code being at a ribbon level correct?

2) potential missing other thoughts on achieving the pseudo code thought?

**Comment by ryanjbaxter** [comment]
I dont see why you couldnt do that in a filter as long as you had the service id.

**Comment by tiny-dancer** [comment]
My take on not being a filter is that it conditionally applies to a service id's instances (not a universal change).  If i'm understanding correctly, If the change occurs in a filter you'd need to conditionally re-set the host values stored in `DiscoveryClient` so when picked up later by Ribbon it would have the correct values.  
Is that what your thinking?

**Comment by spencergibb** [comment]
At that point I would think you would use url routing rather than discovery client.

**Comment by silentFred** [comment]
@tiny-dancer did you manage to do what you needed to do? I need something similar
