### ISSUE TITLE
Unable to use ZuulFallbackProvider

### ISSUE THREAD

**Issue by saibalghosh1980** [spring-cloud/spring-cloud-netflix#1661]
Hi,
I was trying to use ZuulFallbackProvider to enable fallback for my ZuulApi Server. But even after make all the changes I keep getting the following exception.

com.netflix.zuul.exception.ZuulException: Forwarding error.....

The source code of the project is located in the following location in GitHub

_https://github.com/saibalghosh1980/MicroServices/tree/master/CTS-MS-Zuul-API-Server_

Please let me know if I am using an incorrect version or if the implementation is incorrect.

I am trying to call a get api under the route sampleapi which I have intentionally put delay in order to get a timeout.

Saibal

**Comment by spencergibb** [comment]
Why is this commented out https://github.com/saibalghosh1980/MicroServices/blob/master/CTS-MS-Zuul-API-Server/src/main/java/com/cts/fallback/FDCZuulCustomFallbackProviderConfig.java#L18-L21

**Comment by saibalghosh1980** [comment]
Hi ,
     I commented them out as it was not  working even with the annotation on. I have put them back again and uploaded the stack trace in the following location.

https://github.com/saibalghosh1980/MicroServices/blob/master/CTS-MS-Zuul-API-Server/StackTrace.txt




Saibal

**Comment by saibalghosh1980** [comment]
Any update on the issue guys

**Comment by spencergibb** [comment]
no

**Comment by spencergibb** [comment]
The stack trace shows a timeout exception.

**Comment by spencergibb** [comment]
In `FDCZuulCustomFallbackProviderConfig`, the route needs to be the serviceId, so:
```
            public String getRoute() {
                return "SAMPLE-CONFIG-CLIENT";
            }
```
