### ISSUE TITLE
Release to go with spring-boot 1.5.x?

### ISSUE THREAD

**Issue by erikkemperman** [spring-cloud/spring-cloud-netflix#1662]
Apologies if I am just being too impatient -- but I am wondering if I can use spring-cloud-netflix already with spring-boot 1.5.x? Without resorting to snapshot / milestone releases, I mean?

The issue, or at least the one I'm running into, seems to be that  `org.springframework.boot.context.embedded.ServletRegistrationBean` was deprecated in favour of 
`org.springframework.boot.web.servlet.ServletRegistrationBean` -- and now in 1.5 it's been removed.

However the corresponding change here,
https://github.com/spring-cloud/spring-cloud-netflix/blame/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulConfiguration.java#L29

Seems to have been reverted for the latest (1.2.4) release of spring-cloud-netflix:
https://github.com/spring-cloud/spring-cloud-netflix/blame/v1.2.4.RELEASE/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulConfiguration.java#L27

**Comment by erikkemperman** [comment]
So I guess I am just looking for a resolution of [PR #1640](https://github.com/spring-cloud/spring-cloud-netflix/pull/1640) :-)

**Comment by spencergibb** [comment]
Done in 8e6b64382995eab85d2275bc57eb279e23b746aa. #1640 adds 1.3 compatibility

**Comment by erikkemperman** [comment]
Thanks for the quick response, but I'm not sure I understand. The current 1.2.4 release is compatible with spring-boot 1.3 but it fails with spring-boot 1.5, because the commit you cite was reverted for the 1.2.4 release.

The PR 1640 looks like it detects dynamically in which package it finds ServletRegistrationBean and thus would be compatible with 1.{3,4,5} -- which would solve my issue (and still satisfy whatever the motivation for the revert was).

Sorry if I'm missing something obvious...

**Comment by spencergibb** [comment]
It is on master and will be part of 1.2.5. It currently supports 1.4,1.5. We're debating if we should support 1.3 (likely not).

**Comment by erikkemperman** [comment]
Right, I see, so what I'll want is 1.2.5 when it gets released. All right, thanks a lot!

**Comment by GontseNtshegi** [comment]
I'm having the same issue now on Zuul(1.3.0) with spring boot 1.5.4. Its complaining about the ServletRegistrationBean issue. Was this resolved in 1.3.0?

**Comment by spencergibb** [comment]
@GontseNtshegi please try with the latest 1.3.5.
