### ISSUE TITLE
Any multipart request with a boundary in the content type raises an exception

### ISSUE THREAD

**Issue by eloipoch** [spring-cloud/spring-cloud-netflix#1663]
In 1.3.0.M1 seems that a bug has been introduced.

Any multipart request that in his `Content-Type` adds the `boundary` parameter (in theory a required parameter, see [RFC](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html)) raises an exception with the message "MIME type may not contain reserved characters".

I think it has been introduced in the [commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/d76bd84466616f53e5eee6879fee9a823d767841)  which tries to handle well a content-type with a charset due to the upgrade of the `httpclient` library.

I will try to open a PR with a fix in order to have it for this release.

**Comment by hartmut-pq** [comment]
Hi, I've got same issues with 1.2.5.RELEASE

**Comment by spencergibb** [comment]
Reopening to apply to Camden branch 1.2.x

**Comment by hartmut-pq** [comment]
Thanks a lot!
Note: broke upgrade to spring boot `1.5.1.RELEASE` & `org.springframework.cloud:spring-cloud-dependencies:Camden.SR5`

**Comment by spencergibb** [comment]
We're a workaround with Camden.SR5 and Spring Boot 1.5 https://gist.github.com/spencergibb/80a134b4738c78ca64e4d0c77214fcb6

**Comment by spencergibb** [comment]
Cherry picked to 1.2.x ee953bef07034f88e352a7ebf938cbd345e2535e

**Comment by prantan7** [comment]
We tried after upgrading the boot dependencies to 1.5.1.RELEASE & spring-cloud-dependencies to Camden.SR5, it still didn't work for us.

With what versions the fix for  "-MIME type may not contain reserved characters" is supposed to work

**Comment by ryanjbaxter** [comment]
It looks like this was cherry picked after the release occurred, can your try `Camden.BUILD-SNAPSHOT`?

**Comment by prantan7** [comment]
Thanks Ryan, I will check with the SNAPSHOT version and let you know.

Is there any other to resolve this besides updating the dependency. I saw some messages regarding using the RibbonRoutingFilter instead of the SimpleHostRoutingFilter.

**Comment by spencergibb** [comment]
Yes, it will be in Dalston RC1. The gist above is a workaround.

**Comment by hartmut-pq** [comment]
So there is no other Camden Release lined up including the fix? 
I generally don't feel comfortable to work on a BUILD-SNAPSHOT...

**Comment by ryanjbaxter** [comment]
There will be another Camden release coming soon.

**Comment by hartmut-pq** [comment]
Hi @ryanjbaxter - how soon is _soon_ going to be? :-)
> 21 days ago

**Comment by ryanjbaxter** [comment]
@hartmut-pq most likely this week, sorry for the delay

**Comment by asarkar** [comment]
@ryanjbaxter We hit this issue today, and as a result, a multipart upload feature is busted. Do you have a definitive timeline for this to be released? I'd like to avoid upgrading to SNAPSHOT, if I can, only to upgrade to a release couple days later.

**Comment by ryanjbaxter** [comment]
Camden.SR6 will hopefully be released today, if not Monday I would think at the latest.  The Netflix 1.2.6.RELEASE which will be included in Camden.SR6 is already in Maven Central if you would like to try it out.

**Comment by asarkar** [comment]
@ryanjbaxter Thanks for the info. Please provide an update here when the release is available and I'll go grab it.

**Comment by ryanjbaxter** [comment]
The release is now available.

**Comment by asarkar** [comment]
Confirmed working. Thanks @ryanjbaxter
