### ISSUE TITLE
inter services communication not working via zuul routes

### ISSUE THREAD

**Issue by ajayaks** [spring-cloud/spring-cloud-netflix#1666]
I am trying to call service A from service B via application name and below is the setup.

Setup Eureka server and register other services and conductor server.
conductor server is registered in eureka services list.
Setup zuul gateway and defining routing for conductor like below:- Zuul is running on 1113 port.
users:
path: /apis/users/**
serviceId: users-service
stripPrefix: false
tasks:
path: /apis/tasks/**
serviceId: tasks-service
stripPrefix: false

Both the services are working fine if i call them via zuul gateway in browser, meaning routing is fine.
http://localhost:1113/apis/users
http://localhost:1113/apis/tasks

Problem i am having is its not working user service is calling task service as below:-

Not working
restTemplate.getForObject(String.format("http://tasks-service/apis/tasks/") [Not working]

Below is working if i use server and port
restTemplate.getForObject(String.format("http://localhost:8380/apis/tasks/") [working]

Its showing the correct name in services listed in eureka and working if i call that routes directly in browser but communication b/w the services is not working.

Please suggest.

**Comment by spencergibb** [comment]
Please format the yaml between triple backticks `

Define "Not working".

Have you created a `@LoadBalanced` `RestTemplate`? Have you included `@EnableDiscoveryClient`? Do you have the right starters?

Please provide more information.

**Comment by ajayaks** [comment]
Hi Spencer, 

Thanks, Its(ServiceA -> ServiceB via appname) working just by doing below, .

1. Adding @LoadBalanced
2. Defined below in ServiceA for ServiceB. By 

service-b:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8380
    ServerListRefreshInterval: 15000

Or making it dynamic by 

service-b:
  ribbon:
    eureka:
      enabled: true

I have one more questions 
1. Dont we have use @RibbonClient on serviceA. As per 
@RibbonClient(name = "comments-server", configuration = CommentsServiceConfiguration.class)

As per https://spring.io/guides/gs/client-side-load-balancing/ its required to define @RibbonClient annotation.


Please suggest.
Regards
Ajay

**Comment by ryanjbaxter** [comment]
You only need to provide additional configuration if you want to override the defaults provided by Spring Cloud, it is not a requirement.
