### ISSUE TITLE
Multi Part File Uploads Fail With MIME type may not contain reserved characters

### ISSUE THREAD

**Issue by dioode** [spring-cloud/spring-cloud-netflix#1667]
As I have mentioned in my [SO Question](http://stackoverflow.com/q/41998807/892788). I am getting the the following error on my gateway service. Interesting thing is, this is not happening in the local environment where both the servers run on localhost.

```
{timestamp: 1486073324028, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"java.lang.IllegalArgumentException"
message
:
"MIME type may not contain reserved characters"
status
:
500
timestamp
:
1486073324028
```

**General**
```
Request URL:http://xxx.compute.com/product/file/uploadFile
Request Method:POST
Status Code:500 
Remote Address:xx.1xx.xxx.36:80
Response Headers
view source
Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:close
Content-Type:application/json;charset=UTF-8
Date:Thu, 02 Feb 2017 22:08:44 GMT
Expires:0
Pragma:no-cache
Transfer-Encoding:chunked
X-Application-Context:application:prod:8080
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
```

**Request Headers**

```
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Content-Length:2024535
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarynAMBxBwfTkARrYCQ
Cookie:auth=Z3Vlc3Q6Z3Vlc3Q%3D; m=34e2:|ca3:t|4a01:t|77cb:t|1d98:t; JSESSIONID=4097F327CF522649D0B28A0A005A7242
DNT:1
Host:xxx.compute.com
Origin:http://xxx.compute.com
Referer:http://xxx.compute.com/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

**Request Payload**

```
------WebKitFormBoundarynAMBxBwfTkARrYCQ
Content-Disposition: form-data; name="file"; filename="Souxxx.csv"
Content-Type: text/csv


------WebKitFormBoundarynAMBxBwfTkARrYCQ--
```

**Comment by spencergibb** [comment]
Duplicates #1663 which has been fixed

**Comment by dioode** [comment]
Tried Spring boot version 1.5.1.RELEASE, 2.0.0.BUILD-SNAPSHOT, 1.4.4.RELEASE and the managed version for spring-cloud-starter-zuul .2.5.BUILD-SNAPSHOT, spring-cloud-starter-zuul .2.4.BUILD-SNAPSHOT. what version should I introduce to get rid of this issue.  Thanks

**Comment by ryanjbaxter** [comment]
It was merged into master.  The Boot version will not effect anything it is the Spring Cloud version you need to change.  Right now the fix is only in our `SNAPSHOT` builds you will want to use `Dalston.BUILD-SNAPSHOT`.

**Comment by sgrillon14** [comment]
I have the same probem,
spring-boot-starter-parent 1.5.4.RELEASE so spring-cloud-starter-zuul 1.3.0.M1

**Comment by ryanjbaxter** [comment]
@sgrillon14 open a new issue with an app that reproduces the problem
