### ISSUE TITLE
Question: How to handle client-generated base URLs?

### ISSUE THREAD

**Issue by kwblue** [spring-cloud/spring-cloud-netflix#1668]
Hi, we're going to be using Feign in our project at work and one of our downstream clients in their authentication processing sends back a token along with an endpoint that is supposed to be used for further API processing.  In base Feign, I presume that creating a custom Target to handle both the authentication and the URL injection of the endpoint from the token response would accomplish this task.  But how would one do the same using Spring Cloud Netflix defined clients since the Targeter doesn't appear to be able to be something that can be overridden/defined per client configuration?

**Comment by kwblue** [comment]
Note that at the moment we are not planning on using Eureka or Zuul, with Ribbon only maybe a possibility (still in planning/initial development).

**Comment by spencergibb** [comment]
Don't use `@FeignClient`. Use the feign API directly. The are examples in the docs (on Mobile right now or I'd link to it.)

**Comment by ryanjbaxter** [comment]
Here is the link to the documentation I believe @spencergibb is referencing
http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_creating_feign_clients_manually

**Comment by kwblue** [comment]
Thank you for confirming.  That is the approach we are pursuing of building the client manually.
