### ISSUE TITLE
Eureka in docker container - broken url's

### ISSUE THREAD

**Issue by mbonski** [spring-cloud/spring-cloud-netflix#167]
Hi
I have eureka and a bunch of other spring microservices running inside docker containers. All docker containers are linked with eureka using docker linking system. The whole solution works well but I've realized that some links are broken, for example, response from http://localhost:8761/eureka/apps contains 

    \<hostName>0bbc3ff1f459\</hostName>
    \<ipAddr>172.17.0.119\</ipAddr>
    \<status>UP\</status>
    ...
    \<homePageUrl>http://0bbc3ff1f459:8888/\</homePageUrl>
    \<statusPageUrl>http://0bbc3ff1f459:8888/info\</statusPageUrl>
    \<healthCheckUrl>http://0bbc3ff1f459:8888/health\</healthCheckUrl>

the problem is with the following part of the url "0bbc3ff1f459" which is a container hostname randomly created by the docker. When I replace "0bbc3ff1f459" with the IP address link it works fine.
The link on the eureka dashboard in the status column is broken too.

I'm wondering if you know of any way to avoid this problem.

**Comment by spencergibb** [comment]
`eureka.instance.preferIpAddress=true`

**Comment by mbonski** [comment]
Thank you works as it should now :]
