### ISSUE TITLE
Eureka heartbeat fails due to extra slash in heartbeat request

### ISSUE THREAD

**Issue by whboyd** [spring-cloud/spring-cloud-netflix#1675]
When a client attempts to send a heartbeat to eureka, the heartbeat request always returns a 404. Initial registration and other operations work, it appears to be just the heartbeat that is affected. This leads to the client initially having a status of UP, but quickly changing to UNKNOWN.

Turning logging up to debug, I get this output:
```
2017-02-07 11:53:13,544 | DEBUG | spring-boot-admin | com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient:110 - Jersey HTTP PUT https://eurekaclient:eureka@tc1dev.liberty.edu:6007/eureka/eureka//apps/SPRING-BOOT-ADMIN/10.66.160.81:spring-boot-admin:6034; statusCode=404
2017-02-07 11:53:13,544 | DEBUG | spring-boot-admin | com.netflix.discovery.DiscoveryClient:833 - DiscoveryClient_SPRING-BOOT-ADMIN/10.66.160.81:spring-boot-admin:6034 - Heartbeat status: 404
```

I believe the double slash in the url used to perform the heartbeat is the culprit. Performing a GET against the eureka server using that url returns a 404. Removing the extra slash causes the GET to return the instance info as expected.

I verified that this occurs when the eureka server is on Camden.SR3, Camden.SR5, and Brixton.SR7 but NOT on Brixton.SR6. It stopped happening when I rolled my eureka server back to Brixton, so this may be a question of whether or not the eureka server is willing to accept the extra slash.

Edit: I changed this based on further research. Initially, I had stated that this occurred when an extra slash was included in the eureka.client.serviceUrl.defaultZone, but that is incorrect. This occurs regardless of whether eureka.client.serviceUrl.defaultZone has a trailing slash.

**Comment by spencergibb** [comment]
The change we made between Brixton.SR6 and SR7 is we upgraded from eureka 1.4.10 to 1.4.12. So no code changed in s-c-netflix. What do you propose we do?

**Comment by spencergibb** [comment]
So, how does the extra slash get in there?

**Comment by whboyd** [comment]
I'm not sure how the slash gets in there, and with eureka server Brixton.SR6 and earlier the slash is present but everything works anyway. To be honest as I continue looking into this I'm not sure the slash is really to blame.

Should I just close this until I have more info?

**Comment by spencergibb** [comment]
Sure, if you find the cause or can give us a sample that recreates the problem, that would be helpful.
