### ISSUE TITLE
Support for Wildcard types in Feign client 

### ISSUE THREAD

**Issue by Infrag** [spring-cloud/spring-cloud-netflix#1676]
When using rest interface like this:

```
@RequestMapping(API_PATH)
public interface Accounts {

    /**
     * POST /register : register the user.
     */
    @PostMapping(path = "/register",
            produces = APPLICATION_JSON_VALUE,
            consumes = APPLICATION_JSON_VALUE)
    ResponseEntity<?> registerAccount(@RequestBody ManagedUserDto managedUserDTO)
            throws EmailAlreadyInUseException, UsernameAlreadyInUseException, URISyntaxException;
}
```

Feign client throws exception:

`feign.codec.DecodeException: type is not an instance of Class or ParameterizedType: java.lang.reflect.WildcardType`

**Comment by ryanjbaxter** [comment]
What version are you using?  I believe support for `@PostMapping` was added in #1201.

**Comment by Infrag** [comment]
Yes I use patch for `@PostMapping` support.

**Comment by Infrag** [comment]
I'am prepareing merge request for this bug with `WildcarType`.

**Comment by spencergibb** [comment]
@Infrag what class is giving you a problem with `WildcardType`? I'd rather determine the problem before working on a pull request.

**Comment by spencergibb** [comment]
is it `ResponseEntity<?>`?

**Comment by Infrag** [comment]
Yes exactly. Its caused by `SpringDecoder.decode()`. There is missing test
for `WildcardType` in first `if`. I will post code snippet tomorrow.

Dne 8. 2. 2017 8:42 odpoledne napsal uživatel "Spencer Gibb" <
notifications@github.com>:

**Comment by Infrag** [comment]
In `org.springframework.cloud.netflix.feign.support.SpringDecoder` there is:

```
...
@Override
	public Object decode(final Response response, Type type) throws IOException,
			FeignException {
		if (type instanceof Class || type instanceof ParameterizedType) {
...
```

Should be:

```
...
@Override
	public Object decode(final Response response, Type type) throws IOException,
			FeignException {
		if (type instanceof Class || type instanceof ParameterizedType || type instanceof WildcardType) {
...
```

**Comment by spencergibb** [comment]
How about a pull request?

**Comment by Infrag** [comment]
Yes, I will create it today or tommorow.

**Comment by jobinvjohn** [comment]
Hi, 
I am getting following error when i use ResponseEntity<R> where R is a generic type for return type.
Any   solution for this?
type is not an instance of Class or ParameterizedType: R

**Comment by spencergibb** [comment]
@jobinvjohn please ask questions on gitter or stackoverflow, not on old closed issues.

**Comment by digows** [comment]
It must consider java.lang.reflect.TypeVariable too. So I suggest consider change that if statement to check an instanceof java.lang.reflect.Type.
