### ISSUE TITLE
ArchaiusAutoConfiguration should be setup on bootstrap phase?

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-netflix#1677]
If I have following bean in my Spring configuration:
```
    @Bean
    public String property2() {
        return DynamicPropertyFactory
                .getInstance()
                .getStringProperty("my.super.property", "default").get();
    }
```
and I also have `bootstrap.properties` with the needed setting:
```
my.super.property=My super value!
```
in tests I get this property equal to `default`, not `My super value!`.

If I add `spring.factories` file to my application with the following content:
```
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration
```
everything works correctly. I wonder is it an appropriate fix for this issue?

I have setup sample application with this issue: https://github.com/Aloren/archaius-sample-test

**Comment by ryanjbaxter** [comment]
Do you mean in JUnit tests?  Did you try setting the property in `@SpringBootTest`?

**Comment by Aloren** [comment]
This doesn't work neither in tests, nor in production (when running application via main method).
Adding for tests:
```
@SpringBootTest(classes = {SampleTest.TestConfiguration.class, SampleContext.class}, 
properties = "my.super.property=My super value!")
```
doesn't help.

**Comment by spencergibb** [comment]
why are you putting this properties in bootrap.yml?

**Comment by Aloren** [comment]
I've tried loading these settings via spring-cloud-config-client, but these settings resolve to default values. I looked into `DiscoveryClientConfigServiceBootstrapConfiguration`, it is setup on bootstrap phase, so I tried to put these settings into `bootstrap.properties`, but this also didn't help. As I understand this is due to `ArchaiusAutoConfiguration` gets autoconfigured after `property2 ` bean.

**Comment by Aloren** [comment]
`EnableAutoConfiguration` annotation clearly states that:
```
Auto-configuration is always applied after user-defined beans have been registered.
```
I suppose, that there are 2 solutions to the issue:
1. Update Spring cloud documentation (Archaius properties from Spring Cloud Config are not available when user beans are setup).
2. `ArchaiusAutoConfiguration` should be moved to bootstrap phase (it should be setup after: PropertySourceBootstrapConfiguration, *ConfigServiceBootstrapConfiguration)

As a temporary workaround we have found that adding:
```
@Import(ArchaiusAutoConfiguration.class)
```
to the class that uses:
```
    @Bean
    public String property2() {
        return DynamicPropertyFactory
                .getInstance()
                .getStringProperty("my.super.property", "default").get();
    }
```
actually helps with resolving correct settings.

@spencergibb could you please advise what should be done?

Thanks.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
