### ISSUE TITLE
Configuring Eureka-Client for Cloudfoundry

### ISSUE THREAD

**Issue by elgohr** [spring-cloud/spring-cloud-netflix#1683]
In many examples (even on http://cloud.spring.io/spring-cloud-netflix/1.0.x/) I found 

eureka.instance.hostname: ${vcap.application.uris[0]}

Isn't this working against Ribbon?
In my understanding the address of the cf-loadbalancer is set as the hostname.
So Ribbon would have multiple instances with the same address (which is actually a server-side loadbalancer in a client-side loadbalancing context).
Wouldn´t it make more sense to use 

eureka.instance.hostname: ${vcap.application.instance.hostname}:${vcap.application.port}

I was also searching for an equivalent for CF_INSTANCE_ADDR (https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#CF-INSTANCE-ADDR), but I didn't find any.

**Comment by spencergibb** [comment]
@elgohr in the early days of Spring Cloud, direct addressing of CF instances wasn't possible. The cf route was the only way, and yes that is redundant. Now, with the right version of CF and the right settings, you can address the instances directly. I'm not CF guru, someone else would have to help there.

**Comment by bijukunjummen** [comment]
@spencergibb, @elgohr, just to add a little more information based on my understanding - if two app instances are on the same diego cell in CF, they **cannot** reach other directly using the ip/port. If they happen to be on different diego cell's then this will work. That is the reason why the direct call is discouraged in CF/PCF and instead the call is routed via the go routers. @scottfrederick will have a better answer based on his experience with Spring Cloud Services.

This likely will be mitigated when [Container networking](https://github.com/cloudfoundry-incubator/cf-networking-release) is implemented in CF/PCF

**Comment by spencergibb** [comment]
Thanks @bijukunjummen 

This:
> This likely will be mitigated when Container networking is implemented in CF/PCF

is what I meant when I said 

> with the right version of CF and the right settings, you can address the instances directly. I'm not CF guru

**Comment by LGohr** [comment]
Thank you very much, sounds promising.
By the way, is there any overview of the ${vcap.* - variables? I tried to guess some from the documented cf-variables.
I was a bit confused because the instance ID is configured as hostname by default.

**Comment by elgohr** [comment]
Thank you very much, sounds promising.
By the way, is there any overview of the ${vcap.* - variables? I tried to guess some from the documented cf-variables.
I was a bit confused because the instance ID is configured as hostname by default.

**Comment by spencergibb** [comment]
I'm sure there is, but I'm not sure where to find it.
