### ISSUE TITLE
Questions regarding Eureka client cache behavior

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1685]
1. Eureka client cache gets refreshed every 30 sec (`eureka.client.registryFetchIntervalSeconds`). If the server doesn't protect the registry in the event of a network outage, does the client cache gets wiped out on the next registry fetch?  I do know that the client only attempts to fetch the delta from the last retrieval, so if there's nothing to compare to, I'd think that the aforementioned statement would be correct, but want to confirm.

2. When the client is given multiple Eureka server URLs, and it registers with the first one, but later can't connect to it, does it purge the cache before going to the second Eureka server in the list?

**Comment by spencergibb** [comment]
The cache won't get wiped if it cannot connect via the network. For #2 AFAIK, no.

**Comment by asarkar** [comment]
> The cache won't get wiped if it cannot connect via the network
@spencergibb Please confirm that "it" means Eureka server. Just so that we're on the same page, The scenario I described is that Eureka server is running in peer-peer mode and self-preservation is off, so during a network outage between peers (**not** between client and server), the registry got wiped out.

**Comment by spencergibb** [comment]
"It" is the eureka client.

**Comment by asarkar** [comment]
@spencergibb In that case, my 1st question remains. If client loses connectivity with server, it makes sense to not purge the cache. But if client can connect to server, and finds an empty registry, or otherwise changed if not empty, what does it do? Since it fetches delta every time, does the delta also consist of deletions?

**Comment by spencergibb** [comment]
If the version doesn't match to get a delta it will do full refresh. Otherwise, the deltas handle deletions.

**Comment by asarkar** [comment]
Can you explain the concept of the version? I don't remember seeing it mentioned in Spring docs or Netflix Wiki. From your response, it sounds like the server returns a version with the registry, but even if that's true, I'm not clear how the version might change.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
