### ISSUE TITLE
Override ribbon NIWSServerListFilterClassName issue

### ISSUE THREAD

**Issue by seno5979** [spring-cloud/spring-cloud-netflix#169]
Overriding ribbon `NIWSServerListFilterClass` using `<clientname>.ribbon.NIWSServerListFilterClassName` does not override default `Filter <ZonePreferenceServerListFilter>` in `RibbonClientConfiguration`.

**Comment by dsyer** [comment]
That's not the way it works (the server list filter is a `@Bean` as you can see). What did you need to do exactly?

**Comment by seno5979** [comment]
I'd like to use DiscoveryEnabledNIWSServerList + ZoneAffinityServerListFilter as my loadbalancing solution. 

Each server will be wrapped as DiscoveryEnabledServer while obtaining Server List from 'obtainServersViaDiscovery' method in DiscoveryEnabledNIWSServerList.

DiscoveryEnabledServer has an 'zone' attribute which value be resolved from DiscoveryClient.getZone(InstanceInfo).

But if we looking at DiscoveryClient.getZone(InstanceInfo), only 'Amazon' datacenter type we can have different zone for each services we registered on Eureka Server.

So for workaround, I would like to use metadataMap in InstanceInfo to define zone in each services.

So I created own ZoneAffinityServerListerFilter and filter only serviceList on zone I want.

**Comment by dsyer** [comment]
So I guess you need to define  a `@Bean` of type `ServerListFilter` in your `@RibbonClient` configuration?

**Comment by seno5979** [comment]
The @Bean works for me. Thanks.

So the <serviceName>.ribbon.NIWSServerListFilterClassName property is not recommended to use ?

Also is there any best practice to use 'MyOwn' datacenter, but also have zone/region feature like 'Amazon' does ?

**Comment by dsyer** [comment]
The `<serviceName>.ribbon.NIWSServerListFilterClassName` will only work if you use native Netflix APIs to create the `ILoadBalancer`. The point of `@RibbonClient` is to make it more of a flexible and strongly typed dependency injection (i.e. not just using class names in configuration).

Load balancing decisions are made on `Servers` (not eureka instance data), so the hard bit is getting your head round that and implementing a `ServerList` that can provide the data to the load balancer.

As far as best practice goes, I think we can develop those ideas as people (like you) start to use this stuff in anger. What we have done so far makes it easy to use the DNS domain name as a proxy for zone/region (via `ZonePreferenceServerListFilter`). Beyond that you would need to add the information you need to the instance metadata, pass it on to the `ServerList`, and then make load balancing decisions on that (either in a `ServerListFilter` like you do, or in a `IRule` or something else, maybe).

If we start to see some patterns emerging we can reify them in the framework. Spring Cloud's `ZonePreferenceServerListFilter` and `DomainExtractingServerList` show a useful example of one such pattern.

**Comment by seno5979** [comment]
Thanks for the reply.

**Comment by vibhaanshu** [comment]
I am using Ribbon with eureka server and planning to use resttemplate as a ribbon client. I want to use Zone Aware load balancer.

Can you please share how this can be achieved?

**Comment by dsyer** [comment]
`@RibbonClient` is the main configuration entry point. Look at the docs for that and define your own `@Bean` for the `ServerListFilter` in the client config.

**Comment by vibhaanshu** [comment]
To give you a background of issue -

I'm using spring cloud verion 1.0.0.RC1. As basic authentication is part of this, for the time being I'm using the default password (which is 'password'). The services got registered successfully to eureka server and synchronization is also happening between two eureka servers.

Now, when I try to consume a service using ribbon with RestTemplate, I get 401 (Unauthorized). In the logs,  the client name is not getting replaced by hostname and port. I can see the server details in list of servers. 
 
Currently, I'm running service consumer as an embedded tomcat and the services to be consumed are deployed on Tomcat container. The reason for this is, getting below error when I deploy two services on the same container.
avax.management.InstanceAlreadyExistsException: org.springframework.cloud.context.env
ironment:name=environmentManager,type=EnvironmentManager

**Comment by dsyer** [comment]
Is this related to the original issue (seems not to me)?

Anyway `RestTemplate` doesn't know how to authenticate your request from the `user:password@<host>` curl-like form of the URL. You have to add an Auhtorization header yourself (e.g. see the `TestRestTemplate` in Spring Boot for an example of how to do it).

**Comment by vibhaanshu** [comment]
Thanks..TestRestTemplate sample solved the issue..

Now facing 'Unable to locate ILoadBalancer for service' errror but since its not linked to this issue, have raised it in stackoverflow.

**Comment by seno5979** [comment]
Hi Dave,

According to my current test, Both of <serviceName>.ribbon.NIWSServerListFilterClassName and @RibbonClient need to be configured if we want to override ServerListFilter with our own.

If we don't override <serviceName>.ribbon.NIWSServerListFilterClassName & NIWSServerListClassName, the result will not be correct untill the next refresh.

Please correct me if I'm wrong.

Thanks.

**Comment by dsyer** [comment]
What do you mean by "next refresh"? It works for me so maybe you could post your code and we can see what is confusing.

**Comment by seno5979** [comment]
This is my bootstrap.yml looks like:

```
BLUEPRINT-SPRING-CLOUD-REST-DEMO:
server:
  port: 8070

spring:
  application:
    name: greeting-app
  cloud:
    config:
      discovery:
        enabled: true

eureka:
  instance:
    hostName: greeting_app.c032.digitalriverws.net
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      availability-zone: dc3
  client:
    region: dataCenters
    availabilityZones:
      dataCenters: dc3
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NIWSServerListFilterClassName : test.MyOwnServerListFilter
    ServerListRefreshInterval: 30000
    DeploymentContextBasedVipAddresses: BLUEPRINT-SPRING-CLOUD-REST-DEMO
```
I copy the ZoneAffinityServerListFilter class  below :

https://github.com/Netflix/ribbon/blob/master/ribbon-loadbalancer/src/main/java/com/netflix/loadbalancer/ZoneAffinityServerListFilter.java

And do zome changes on  ZoneAffinityPredicate with my own :

With this way I can make sure the system will only give me the serviceList I want based on availability-zone in my metadataMap.

```java
public class MyOwnZoneAffinityServerPredicate extends AbstractServerPredicate {

        public MyOwnZoneAffinityServerPredicate() {
        }

        @Override
        public boolean apply(PredicateKey input) {
            final Server server = input.getServer();
            if(!(server instanceof DiscoveryEnabledServer)) {
                return false;
            }

            DiscoveryEnabledServer des = (DiscoveryEnabledServer)server;
            final String az = des.getInstanceInfo().getMetadata().get("availability-zone");

            if (az != null && MyOwnServerListFilter.this.zone != null && az.toLowerCase().equals(MyOwnServerListFilter.this.zone.toLowerCase())) {
                return true;
            }
            return false;

        }
    }
```
This is my RibbonClient Configuration class :

```Java
@Configuration
@EnableConfigurationProperties
@RibbonClient(name = "BLUEPRINT-SPRING-CLOUD-REST-DEMO", configuration = BluePrintConfiguration.class)
public class BluePrintConfiguration {

    private String name = "BLUEPRINT-SPRING-CLOUD-REST-DEMO";

    @Bean
    public IClientConfig ribbonClientConfig() {
        DefaultClientConfigImpl config = new DefaultClientConfigImpl();
        config.loadProperties(this.name);
        return config;
    }

    @Bean
    public ServerListFilter<Server> ribbonServerListFilter(IClientConfig config) {
        MyOwnServerListFilter filter = new MyOwnServerListFilter();
        filter.initWithNiwsConfig(config);
        return filter;
    }
}
```

If I don't do the below override :

```
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    NIWSServerListFilterClassName : test.MyOwnServerListFilter
    ServerListRefreshInterval: 30000
    DeploymentContextBasedVipAddresses: BLUEPRINT-SPRING-CLOUD-REST-DEMO
```

I will get the whole server list that registered on Eureka. But the next 30 second (which the server list refresh happened) will got the server list that I want.

**Comment by seno5979** [comment]
Hi Dave,

Not sure if my explanation above clear enough to you

**Comment by spencergibb** [comment]
@seno5979 if you are still having problems, please open a new issue
