### ISSUE TITLE
How to use the Zuul DebugFilter?

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1691]
How to use the Zuul DebugFilter?
According to the code in DebugFilter, I  set `zuul.debug.request=true` . But nothing happens.
Could you help me ?
Thanks a lot!

**Comment by lowzj** [comment]
set `zuul.include-debug-header=true`, and the debug information will be added into response header, see: [SendResponseFilter#addResponseHeaders](https://github.com/spring-cloud/spring-cloud-netflix/blob/3e7b196950c5f1aec6899fc35089b7c7be7bc72d/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java#L221)

**Comment by eacdy** [comment]
@lowzj Thanks a lot.
When I add the property `zuul.include-debug-header=true` , It works. I can see the DEBUG info in `/trace` endpoint .
When I debug deep into the code, I find that those two properties needs to work together:
```
zuul.include-debug-header: true
zuul.debug.request: true
```
Am I right? I mean if I set one of these two properties to false, zuul never works.

**Comment by lowzj** [comment]
@eacdy you can only set `zuul.include-debug-header: true`, and add request parameter`debug=true` when you want to debug a request, like `/api/example?debug=true`

**Comment by eacdy** [comment]
@lowzj Thanks a lot. It works.
