### ISSUE TITLE
Support for NFLoadBalancerPingClassName is not usable with default implementations

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-netflix#1693]
Because none of the `IPing` implementations `NoOpPing`, `PingConstant` or `PingUrl` implement `IClientConfigAware` nor have an `IClientConfig` constructor, none of them can be constructed by the `SpringClientFactory`.

I have no idea why they don't extend `AbstractLoadBalancerPing`. Is there anything that can be done other than raise an issue upstream?

**Comment by ryanjbaxter** [comment]
Can your explain why you want them to be constructed by `SpringClientFactory`?  What is your use case?

**Comment by OrangeDog** [comment]
See #927

**Comment by spencergibb** [comment]
What version are you using? I believe this was fixed with b27ba0434afe9abf4f1d4f17e40c6b44e0371b7c. I think it's a duplicate of #1608.

**Comment by OrangeDog** [comment]
Ah, 1.2.5.RELEASE.
