### ISSUE TITLE
eureka incorrect Renews (last min) 

### ISSUE THREAD

**Issue by hsj1606** [spring-cloud/spring-cloud-netflix#1696]
![default](https://cloud.githubusercontent.com/assets/12151317/22963078/cc4bf864-f38b-11e6-9005-828726211bf6.png)

I have one registered service and the renews(last min) should be 2 instead of 4 (1 heartbeat per 30 seconds), this will cause the self-preservation feature error if there're more than two services,  is my configuration wrong?

eureka server config:
```
spring.application.name=versa-eureka
server.port=8761
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
```

eureka client config:
```
spring.application.name=versa-backend
server.port=8101
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
```

**Comment by spencergibb** [comment]
I don't think this is a problem. Less renewals would be.

**Comment by hsj1606** [comment]
Actulally the renews(last min) always be 4
