### ISSUE TITLE
Host vs Origin headers for CORS preflight request

### ISSUE THREAD

**Issue by cesartl** [spring-cloud/spring-cloud-netflix#1697]
I'm using Zuul with `Spring Cloud Camden SR5` and `Spring Boot 1.4.4.RELEASE`

My frontend is `React.js` application served by a `Node Express` server. My API is behind zuul.

The frontend can be accessed via `https://test.mydomain.com` and the API (Zuul) via `https://api-test.mydomain.com`

In `Zuul` I do have a `CORS` filter that sets the CORS header (properly?):

    if(corsAllowedOrigin.contains(host)){
            log.debug("{} is allowed", origin);
            response.setHeader("Access-Control-Allow-Origin", origin);
        }
    response.setHeader("Access-Control-Allow-Credentials", "true");
    response.setHeader("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE");
    response.setHeader("Access-Control-Max-Age", "3600");
    response.setHeader("Access-Control-Allow-Headers", allowHeaders);
    response.setHeader("Access-Control-Expose-Headers", exposeHeaders);
    chain.doFilter(req, res);

With React.js I use Fetch to make HTTP calls to the API.

Before each `GET` or `POST` request, the browser does an `OPTIONS` request with the following headers:

* Host: `api-test.mydomain.com`
* Origin: `https://test.mydomain.com`

When I was using `Spring Cloud Brixton.SR6` and `Spring Boot 1.3.4.RELEASE` that worked fine.

Now however I'm getting a `403` and the error message is `Invalid CORS request`.

Using a REST client I noticed that if I change the headers so that `Host == Origin` then I'm getting a `200 OK`

From the `CORS` [spec](https://www.w3.org/TR/cors/#resource-security) I could find:

> In addition to checking the Origin header, resource authors are strongly encouraged to also check the Host header. That is, make sure that the host name provided by that header matches the host name of the server on which the resource resides. This will provide protection against DNS rebinding attacks.

Is that the reason why I'm now getting a `403`? How can I have my API running on a different host without failing the `OPTIONS` requests?

**Comment by cesartl** [comment]
note: It only happens if the header `Access-Control-Request-Method` is set

**Comment by cesartl** [comment]
It seems I can solve the problem if I add CORS filter to each individual service behind the edge service. That is if I make sure the `Access-Control-Allow-Origin` header is populated by each service.

Before the update I only had a CORS filter on my edge service (Zuul) and I thought it was the way to go. Surely it seems wasteful if I need to configure CORS for each service? Is that the way to go?

**Comment by ryanjbaxter** [comment]
Could you provide a sample that reproduces the problem?

**Comment by cesartl** [comment]
If you create a simple rest controller:

```java
@RestController
@RequestMapping("/foo")
public class FooController {
     @GetMapping(path = "/hello")
     public String hello(){
        return "hello"
     }
}
```

If you do an `OPTIONS` request with the following headers:

- Access-Control-Request-Method=GET
- Host: api-test.mydomain.com
- Origin: https://test.mydomain.com

You get a `403 - Invalid CORS request`

Now I see how this is perhaps the desired behaviour (although it wasn't like that with Spring Boot 1.3.4).

Now let's say I want to have this service behind a `Zuul` proxy:

```java
@SpringBootApplication
@EnableZuulProxy
@EnableCircuitBreaker
public class EdgeServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(EdgeServiceApplication.class, args);
	}

	@Bean
	public WebMvcConfigurer corsConfigurer() {
		return new WebMvcConfigurerAdapter() {
			@Override
			public void addCorsMappings(CorsRegistry registry) {
				registry.addMapping("/**").allowedOrigins("https://test.mydomain.com");
			}
		};
	}
```

I was hopping that the CORS configuration in Zuul is enough. However I am still getting `403` if query the controller through Zuul. The only way I could fix it was to add the CORS mapping config to all my microservices.

Is that the desired behaviour?

**Comment by ryanjbaxter** [comment]
This is slightly confusing to me since CORS should not come into play when Zuul is making the request to the service.  Maybe Zuul is forwarding on some headers from the browser request that it perhaps shouldn't since it is not making a cross domain request?

**Comment by cesartl** [comment]
yes I am talking about a cross domain request.

My front-end is running on `https://test.mydomain.com` and the browser is making a request to `https://test-api.mydomain.com`.

`https://test-api.mydomain.com` points to an AWS ELB that connects to Zuul (I observe the same problem when running locally)

Before doing a `GET` or `POST` the browser makes a preflight request `OPTIONS` to Zuul. Then I don't know what is the expected behaviour.

Should Zuul forward the `OPTIONS` request to the downstream service? Should Zuul respond to the `OPTIONS` request on behalf of the service (my gut tells me that this is wrong. How can ZUUL know what to reply without talking to the service?)

I'm not saying there is a bug in Spring or Zuul; I'd like to understand what is happening since this is a change a behaviour compared to a previous version. I am expected to add CORS configuration to all my downstream services or is there a way to do it centrally in Zuul?

**Comment by ysjiang4869** [comment]
@cesartl  I have the same problem, I add a ZuulFilter and find out the request doesn't reach the ZuulFilter. I also try to add CORS  configuration to  my downstream services but it still give 403 response.

**Comment by cesartl** [comment]
@ryanjbaxter I understand what you mean about Zuul not making a CORS request but how should Zuul respond to an `OPTIONS` preflight request? Should it forward it without the CORS? headers to the downstream services?

@ysjiang4869 Not sure this is the same issue. If add CORS configuration to my downstream services it works perfectly. My point is that I was hoping to configure CORS only once in Zuul, rather than on every single service.

**Comment by ryanjbaxter** [comment]
@cesartl I need to look into this some more

**Comment by ysjiang4869** [comment]
I solved the problem by add the following code in my edge service
` 
@Bean

    public FilterRegistrationBean corsFilter() { 
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
`

Referred to [Filter based CORS support](https://spring.io/blog/2015/06/08/cors-support-in-spring-framework#filter-based-cors-support)

**Comment by ryanjbaxter** [comment]
@cesartl does @ysjiang4869's suggestion work?  If not I can maybe spend some time today.

**Comment by cesartl** [comment]
yes it does. Before I was using my own implementation of a CORS filter instead of `org.springframework.web.filter.CorsFilter.CorsFilter`. That could explain why it didn't work.

**Comment by ryanjbaxter** [comment]
Great, is it ok to close this then?

**Comment by cesartl** [comment]
Sure, thanks for your help

**Comment by jayaprakash-altimetrik** [comment]
Having a CORS filter in zuul doesn't work. It works when every edge service has a CORS filter.

**Comment by cesartl** [comment]
both @ysjiang4869 and I managed to have CORS working with a single filter on the Zuul (i.e. **the** edge service)

**Comment by suciuandrei94** [comment]
Solution suggested by @ysjiang4869 works fine, thank you!

**Comment by zekeoptimo** [comment]
I had a similar problem and thought I had configured CORS correctly for Spring, but the line I was missing was `config.addAllowedHeader("*");` - without that, adding the Access-Control-Request-Method caused the issue noted here.

Thanks for the help!
