### ISSUE TITLE
Fix encoding issue in SpringEncoder

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#1698]
Fix  "// TODO: set charset" in [SpringEncoder](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/support/SpringEncoder.java#L99)

Current code sends invalid request when Feign ApacheHttpClient is used. When byte array is encoded it is encoded as `StringEntity` not `ByteArrayEntity`. See [ApacheHttpClient](https://github.com/OpenFeign/feign/blob/master/httpclient/src/main/java/feign/httpclient/ApacheHttpClient.java#L139)

My dummy fix is:

```java
// do not use charset for binary data!
if (requestContentType.isCompatibleWith(MediaType.APPLICATION_OCTET_STREAM)) {
   request.body(outputMessage.getOutputStream().toByteArray(), null);
} else {
   request.body(outputMessage.getOutputStream().toByteArray(), Charset.forName("UTF-8"));
}
```

**Comment by spencergibb** [comment]
@tjuchniewicz are you willing to submit a PR?

**Comment by tjuchniewicz** [comment]
@spencergibb Yes. I will create PR.

**Comment by spencergibb** [comment]
Thanks @tjuchniewicz!
