### ISSUE TITLE
Hystrix Dash behind a Zuul Proxy 

### ISSUE THREAD

**Issue by NickPadilla** [spring-cloud/spring-cloud-netflix#170]
Currently we have a Zuul proxy in front of a Hystrix Dashboard (later we'll move to Turbine).  As it stands right now, you can get to the Hystrix Dashboard but the static resources it requires from the HTML do not play well with a proxied url.  It wants to change from say /hystrixproxied/ to /hystrix/... That requires another round of authentication as the zuul server finds a new "service".  It should be fairly simple to update the html so that it uses relative urls, I am just guessing that this is the problem.  I might have time to look at this next week, but no sooner. I wanted to get this out there so that if anyone else is having the same problem they can chime in. 

One work around is to have Zuul hand out the static resources, but there isn't an easy way to get just the needed resources for Hystrix Dashboard - unless you make Zuul a HystrixDash as well (which is overkill in my mind). 

Thanks again for everyones hard work on this project!

**Comment by dsyer** [comment]
You still need the dashboard (or something with a UI) if you use Turbine. Why do you need to proxy it though?

Anyway, the static resources in the dashboard are already referenced via relative URLs (and it works if you change the servlet or context path), so that might not be the problem. Maybe you just need to set `stripPrefix=false` for that route?

**Comment by NickPadilla** [comment]
The reason why it is going to be behind the proxy is for authentication and role access.  I had the Hystrix Dash running with no `server.contextPath` specified, since the default for Zuul is to remove the "prefix" this seemed to make sense.  Until it needed to serve up these types of resources.  So i added this to the Hystrix application.yml `contextPath: /${spring.application.name:}` which is also its service id. I also added this to the Zuul application.yml 
```
   zuul:
     routes:
       cloudhystrix:
         path: /cloudhystrix/**
         stripPrefix: false
```
I also have the Zuul Proxy using `@EnableOAuth2Sso` and the Hystrix Dash is defined with `@EnableOAuth2Resource`.  With this configuration when i go to http://localhost:8765/cloudhystrix it does the redirection but I get this from the Hystrix Dash App 
```
An Authentication object was not found in the SecurityContext
```
Any ideas?

**Comment by NickPadilla** [comment]
Also i comment out both of those additions and I get to the dash, no authorization errors, but the webjars/ and custom js can't load b/c its looking for them at / not cloudhystrix/.

**Comment by NickPadilla** [comment]
I figured out what the problem was.  The Oauth2 client didn't have all the claims that were required by the app.   Giving the Hystrix app `contextPath: /${spring.application.name:}` and setting the `stripPrefix` in the zuul application settings. Thanks!
