### ISSUE TITLE
library source does not match the bytecode for class

### ISSUE THREAD

**Issue by qct** [spring-cloud/spring-cloud-netflix#1700]
org.springframework.cloud.netflix.eureka.EurekaClientConfigBean

version: 1.2.5.RELEASE

please rebuild sources.jar

**Comment by spencergibb** [comment]
I'm unsure what this means? Whatever is in maven central is there and can't be replaced.

**Comment by qct** [comment]
![image](https://cloud.githubusercontent.com/assets/2283288/23026849/89016086-f49d-11e6-9a8e-2af83805e807.png)

it means source code recreated from a .class file by IntelliJ IDEA does not match the source code from spring-cloud-netflix-eureka-client-1.2.5.RELEASE-sources.jar

**Comment by Koizumi85** [comment]
@qct This is absolutely normal. As you can see for example, in this class the Lombok Framework is used. Lombok is a pre-compiler, which generates code out of Annotations (And then removes the annotations). This code is then compiled to your class file, but the Lombok-Annotations are not contained in it. So IntelliJ can't reproduce the code with the Annotations, but will contain the code auto-generated by Lombok.

**Comment by qct** [comment]
Thank  you @Koizumi85 , your explanation is very clear. I made a mistake and I'll close this issue.
