### ISSUE TITLE
Unable do set virtualHostName

### ISSUE THREAD

**Issue by flaviocordova** [spring-cloud/spring-cloud-netflix#1701]
Hello...

I'm having the same error reported on issue #1559 (at least, looks the same behavior) but I'm already using Camden.SR5 (where, I supposed, shouldn't be an issue anymore, right?).

I've tried to set both eureka.instance.virtual-host-name and eureka.instance.virtualHostName and the service is always registered as

com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GATEWAY/192.168.0.19:gateway: registering service...

I've checked and the properties are set but just doesn't seems to take any effect.

Locally it's not a problem but I want to run it on Heroku than I can't rely on internal addresses (both IP or host name)

**Comment by spencergibb** [comment]
Have you checked /eureka/apps? Apps have to be registered with a hostname and/or IP address.

**Comment by flaviocordova** [comment]
Yeah, and it seems to be ok (what means my theory about the parameter has failed...

<instanceId>192.168.0.19:gateway</instanceId>
<hostName>localhost</hostName>

What's happening: I've used a heroku tutorial (https://blog.heroku.com/managing_your_microservices_on_heroku_with_netflix_s_eureka)  to start eureka and a client and it works fine. The only difference is that, in this case, the service is registered using the host name and not the IP (that's why I supposed this was the problem).

The code and settings I'm using are mostly the same but the example uses Angel.SR6 and I'm using Camden.SR5. The example runs smoothly but when I start it (on heroku) I get an error:

DiscoveryClient_GATEWAY/192.168.0.19:gateway - was unable to refresh its cache! status = Cannot execute request on any known server
[tbeatExecutor-0] c.sun.jersey.api.client.ClientResponse   : A message body reader for Java class com.netflix.appinfo.InstanceInfo, and Java type class com.netflix.appinfo.InstanceInfo, and MIME media type text/html; charset=utf-8 was not found

When I run locally (and without setting the host) it works fine.

It looks like the (eureka) server is returning an invalid content but I can't see what it could be. is there any way to log it?

**Comment by flaviocordova** [comment]
Sorry, I mistyped the eureka server name and now it seems to be connected but I still get some errors:

2017-02-16T19:28:15.155342+00:00 app[web.1]: 2017-02-16 19:28:15.155  WARN 4 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : There was a problem with the instance info replicator

I'll do my research to find what it means and if I get stuck I'll open another issue..

thanks for the attention.. :)
