### ISSUE TITLE
How to unregister a service via eureka homepage

### ISSUE THREAD

**Issue by hsj1606** [spring-cloud/spring-cloud-netflix#1704]
Is it possible to do this? I think it will be more easiler when doing the service deploy.

**Comment by ryanjbaxter** [comment]
You mean you want to unregister a service via the Eureka dashboard?  You cannot do this at the moment.  You can unregister a service using the Eureka REST API https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by alirezakhtm** [comment]
> You mean you want to unregister a service via the Eureka dashboard? You cannot do this at the moment. You can unregister a service using the Eureka REST API https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

I am developing library for specific usage. I want to register and unregister service on eureka via HTTP API. I have not found any document for unregistering service. according to [this link](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations) I have found some information but how to unregister service has not been mentioned. would you please help me how to unregister service on eureka via HTTP API ?

**Comment by spencergibb** [comment]
> De-register application instance	DELETE /eureka/apps

**Comment by sachi110** [comment]
Hi,  I started the service after some time my service is down but in eureka server dashboard page showing service is up.
please suggest me how to make perfect dashboard with instance count.
