### ISSUE TITLE
Trubine euraka application auto discovery

### ISSUE THREAD

**Issue by muratkarakas** [spring-cloud/spring-cloud-netflix#1706]
Is it possible to auto configure turbine for all applications in eureka( Or with regex)? Currently I use a configuration like this
...
turbine
  appConfig: SC-SERVICE ,SC-SERVICE-CLIENT  
....

Thanks

**Comment by ryanjbaxter** [comment]
Not that I know of, I think you need to explicitly list the services

**Comment by muratkarakas** [comment]
Thank you very much for your answer.
