### ISSUE TITLE
how make eureka server url data save to redis

### ISSUE THREAD

**Issue by hsoftxl** [spring-cloud/spring-cloud-netflix#1712]
how to make eureka-server' url data save in redis from memery.
is it supported?

**Comment by spencergibb** [comment]
Please clarify your question. It's hard to understand.

**Comment by stiyyagura** [comment]
I am just guessing the question is about how to cache the registry information in Redis cache.

**Comment by hsoftxl** [comment]
i want to run 2 instance eureka server  in docker, but has a problem, when one instance down, maybe registed instances not same in this moment, i want the 2 eureka_server instances's registry information always be same.

**Comment by hsoftxl** [comment]
yes ,  the question is about how to cache the registry information in Redis cache.

**Comment by spencergibb** [comment]
It is not supported

**Comment by stiyyagura** [comment]
It is currently not supported I think :-) but i guess it is important to have this info save in secondary memory when registry is down. @spencergibb please let us know your comment.

**Comment by hsoftxl** [comment]
does support in future?

**Comment by spencergibb** [comment]
No, eureka supports clustering

**Comment by hsoftxl** [comment]
clustering can not make always be same  , in my mind

**Comment by stiyyagura** [comment]
Right, I am sure registry is very dynamic and having a registry info in external memory may help but it may deviate to realtime synching issues.

**Comment by hsoftxl** [comment]
how could i do ? can you give me a hand?
