### ISSUE TITLE
RibbonLoadBalancingHttpClient RequestConfig not completely customizable

### ISSUE THREAD

**Issue by andysworkshop** [spring-cloud/spring-cloud-netflix#1714]
[Here's where RequestConfig](https://github.com/spring-cloud/spring-cloud-netflix/blob/384c9b9725dac5200f2ffb2b1e31270bc5afffff/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RibbonLoadBalancingHttpClient.java#L80-L87
) is created. Some values are taken from the Netflix config class but there are some more important parameters in the request config that are left uncustomizable unless we subclass the whole thing and override the execute method which leaves us open to forward-compatibility issues when we upgrade.

One particularly important parameter in the request config is the amount of time to block when waiting for a connection to become available from a fully leased connection pool. The default is infinite blocking.

**Comment by holy12345** [comment]
Hello @andysworkshop 
This modification can solve the problem you said?
I made the contents of the create RequestConfig as a method  and set the method's type to protected
```
protected RequestConfig getRequestConfig(final IClientConfig configOverride) {
	final RequestConfig.Builder builder = RequestConfig.custom();
	IClientConfig config = configOverride != null ? configOverride : this.config;
	builder.setConnectTimeout(
		config.get(CommonClientConfigKey.ConnectTimeout, this.connectTimeout));
	builder.setSocketTimeout(
		config.get(CommonClientConfigKey.ReadTimeout, this.readTimeout));
	builder.setRedirectsEnabled(
		config.get(CommonClientConfigKey.FollowRedirects, this.followRedirects));
	return builder.build();
}
```

**Comment by holy12345** [comment]
Hi @spencergibb 
What do you think of the amendment I made above? I am willing to listen to your opinion. thank you very much.

**Comment by andysworkshop** [comment]
I don't think that this is the 'spring way' of doing it. Ideally all values in the `RequestConfig.Builder` would be customizable using the Netflix `IClientConfig` but that leaves the solution open to future problems if the Apache client changes its properties and the spring team don't notice. Better I think for spring to allow users to provide an optional bean that, if present, gets to supply the Apache builder.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
