### ISSUE TITLE
Customize Request.Options per Feign client using configuration

### ISSUE THREAD

**Issue by tanmaybinaykiya** [spring-cloud/spring-cloud-netflix#1716]
I have use case to customize request timeouts per client interface. 

As per the [Overriding Feign defaults section](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#overriding-feign-defaults) in the documentation, I gather that it is possible to  do so by defining the configuration and passing it to the @FeignClient annotation. However it does not work as expected. I see the same timeout values being applied to all clients. I am using this with ribbon and okhttp. Am I doing something wrong here? 

ServiceALongRunningClient.java: 

	@FeignClient(name = "test-service", decode404 = true, configuration = LongRunningClientConfiguration.class)
	public interface ServiceALongRunningClient extends ServiceA {

ServiceAClient.java:

	@FeignClient(name="test-service", decode404=true, configuration=ClientConfiguration.class)
	public interface ServiceAClient extends ServiceA{

LongRunningClientConfiguration.java:

	public class LongRunningClientConfiguration extends ClientConfiguration {
		private Logger logger = LogManager.getLogger(this.getClass());

		@Bean
		public Request.Options options() {
			return new Request.Options(5000, 60000);
		}

	}

ClientConfiguration.java: 

	@Configuration
	public class ClientConfiguration {
		
		@Bean
		public Contract feignContract() {
			return new JAXRSContract();
		} 

		... and other custom configs

		@Bean
		public Request.Options options() {
			return new Request.Options(5000, 10000);
		}

	}

**Comment by spencergibb** [comment]
Can you expand on "However it does not work as expected. I see the same timeout values being applied to all clients"?

**Comment by tanmaybinaykiya** [comment]
I tested ServiceALongRunningClient using a backend service which takes longer than 60s to respond. The client fails with `Socket Exception: Read Timed out`.

**Comment by spencergibb** [comment]
According to your configuration, you've configured a 60s timeout. What is the issue?

**Comment by tanmaybinaykiya** [comment]
The ServiceALongRunningClient method times out after 10 seconds(this is in the ClientConfiguration) instead of 60s.

**Comment by spencergibb** [comment]
`@FeignClient` doesn't support multiple clients with the same name. See #1211. See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#creating-feign-clients-manually for howto create one of the clients manually

**Comment by tanmaybinaykiya** [comment]
Thanks. Is there any plan to support such a setup?

**Comment by spencergibb** [comment]
Not currently, the way forward is to manually configure the conflicting client.
