### ISSUE TITLE
Spring Boot Security Basic authentication failed to protect the hystrix.stream

### ISSUE THREAD

**Issue by kavinduraisamy91** [spring-cloud/spring-cloud-netflix#1719]
We have configured the Basic Authentication for the end points with the below application.properties configuration.

```
management.security.enabled=true
security.basic.realm=Baisc Realm
security.basic.enabled=true
security.user.name=<username>
security.user.password=<password>
security.ignored=/test/**,
```

It enables the authentication for all the end points except "hystrix.stream". It can be accessible without any authentication.

How to protect the Hystrix stream URL (http://localhost:8080/hystrix.stream) with basic authentication ?

**Comment by ryanjbaxter** [comment]
Have you tried this? http://stackoverflow.com/questions/42383989/how-to-enable-the-spring-boot-security-basic-authentication-to-hystrix-stream

**Comment by kavinduraisamy91** [comment]
@ryanjbaxter Thank you for the reply. The answer which is available in the stackoverflow (http://stackoverflow.com/questions/42383989/how-to-enable-the-spring-boot-security-basic-authentication-to-hystrix-stream) is working for us.
But why it requires the addition Java configuration instead of application.properties config?

**Comment by ryanjbaxter** [comment]
Sorry for the delay in responding....

I just tried this and just by adding spring-security to my classpath the `/hystrix.stream` endpoint returned a `403`, is that not what you were seeing?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
