### ISSUE TITLE
Dependency tangles (eureka/ribbon and feign/ribbon)

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#172]
These should be easy to eliminate in a simple way (by re-organising packages), but it might be better to attack the real problem (if there is one). I suspect there is an opportunity to lift some of the mixed concerns out into abstractions that will help us with the spring-cloud-commons project as well.

**Comment by spencergibb** [comment]
Are you talking about the s.c.n.ribbon.eureka package and the s.c.n.feign.ribbon package?

**Comment by dsyer** [comment]
s.c.n.ribbon.eureka, s.c.n.feign.ribbon, s.c.n.ribbon are tangled, as are s.c.n.zuul and its subpackages. It's the ribbon ones that I think maybe show us an opportunity for a spring-cloud-commons abstraction.
