### ISSUE TITLE
Zuul: Configuring PoolingHttpClientConnectionManager with Time to Live?

### ISSUE THREAD

**Issue by GJL** [spring-cloud/spring-cloud-netflix#1720]
Hi all,

I am using zuul to route requests to statically configured services according to the request path. 
The services behind zuul are addressed using DNS names. The DNS records can change rather frequently (e.g., daily). 

I have seen in `SimpleHostRoutingFilter` that zuul uses `PoolingHttpClientConnectionManager` from Apache HttpComponents without configuring the _time to live_ for the connections in the pool 
(see https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L238). Even if the DNS records change, the connection pool in zuul is keeping the connections to the old instances open. Depending on the load, it can take many hours until all the old connections are evicted from the connection pool. 

I could subclass `SimpleHostRoutingFilter` and override the method `newConnectionManager()` to return my own instance of `PoolingHttpClientConnectionManager` with a configured TTL. Is there any other way to solve my problem, and  does it make sense to add this feature to zuul?

Best,
Gary

**Comment by ryanjbaxter** [comment]
I believe the you are right the only way to do this is to subclass `SimpleHostRoutingFilter`.  Feel free to provide a PR with a better solution.  Or we could try and address this issue along with fixing the issue in #1684.

**Comment by asarkar** [comment]
@ryanjbaxter `SimpleHostRoutingFilter` is not conditional in `ZuulProxyConfiguration`. Even if it's subclassed, how'd I replace the existing one without doing bean post processing?

**Comment by asarkar** [comment]
@GJL There is no property called TTL in the `PoolingHttpClientConnectionManager`. What methods would you call to get the behavior you're asking for?

**Comment by ryanjbaxter** [comment]
Use `@Primary`

**Comment by asarkar** [comment]
@ryanjbaxter This doesn't apply?
http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#_disable_zuul_filters

**Comment by ryanjbaxter** [comment]
You can try that as well, I haven't tried it myself.  I dont see why it wouldnt work

**Comment by lalib** [comment]
Hey there, I have the same problem like @GJL . Is there any updates or improvements?
