### ISSUE TITLE
Zuul: How to override route configuration for service registered in Eureka

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-netflix#1722]
In Eureka I have registered service with name: `service-frontend`.
In Zuul I have route:
```
"service-frontend": {
"id": "service-frontend",
"fullPath": "/service-frontend/**",
"path": "/**",
"location": "service-frontend",
"prefix": "/service-frontend",
"retryable": null,
"sensitiveHeaders": [],
"customSensitiveHeaders": false
}
```
I need to specify custom properties for this route:
```
zuul.routes.service-frontend.path="/CustomContextPath/**"
zuul.routes.service-frontend.stripPrefix="false"
```
After adding these properties to e.g. bootstrap.properties nothing changes. Location still points to "service-frontend".
Looks like `DiscoveryClientRouteLocator` doesn't support such feature. As a workaround I add new route with different id, like that:
```
zuul.routes.service-frontend1.path="/CustomContextPath/**"
zuul.routes.service-frontend1.serviceId="service-frontend"
zuul.routes.service-frontend1.stripPrefix="false"
```
but this leads to duplication in routes, which I want to remove.

**Comment by ryanjbaxter** [comment]
Did you just put those properties in `bootstrap.properties`?  Did you try `application.properties`?

**Comment by Aloren** [comment]
As I understand bootstrap.properties is added to propertysources earlier than application.properties, so it should not be an issue with it. But I will try, thanks.

**Comment by spencergibb** [comment]
there is a zuul.ignoredServices property which you can ignore the discovery client route

**Comment by Aloren** [comment]
I've just checked. This is not an issue neither with `application.properties`, nor with `bootstrap.properties`. I was using custom info contributor for routes, that was adding routes the following way:
```
    @Override
    public void contribute(Info.Builder builder) {
        routeLocator.getRoutes().forEach(r -> builder.withDetail(r.getId(), r));
    }
```
Both routes have the same id, so the one from Eureka was overwriting custom configuration and I was not able to see it.
Still I wonder is that correct behavior to create absolutely new route if I want to override settings for already existing?
What I see now:
```
"Route 2": {
"id": "service-frontend",
"fullPath": "/CustomContextPath/**",
"path": "/CustomContextPath/**",
"location": "service-frontend",
"prefix": "",
"retryable": null,
"sensitiveHeaders": [],
"customSensitiveHeaders": false
},
"Route 5": {
"id": "service-frontend",
"fullPath": "/service-frontend/**",
"path": "/**",
"location": "service-frontend",
"prefix": "/service-frontend",
"retryable": null,
"sensitiveHeaders": [],
"customSensitiveHeaders": false
}
```
Shouldn't I have only one route?

**Comment by spencergibb** [comment]
Did you try `zuul.ignoredServices`?

**Comment by Aloren** [comment]
Thanks, @spencergibb. I've resolved my initial issue (please see my previous comment) without using `zuul.ignoredServices` property.
I was wondering if this is a correct behaviour for zuul to create 2 routes when configuration for eureka route is set in `application.properties`?

**Comment by ryanjbaxter** [comment]
I guess whether it is "correct" is open for debate.  I can certainly see an argument for augmenting an existing route if the ids match.

**Comment by spencergibb** [comment]
The key into the routes map is the only thing that provides uniqueness.

**Comment by ryanjbaxter** [comment]
@spencergibb I guess I would need to look into it some more but it sounded like even though the ids for the routes were the same (from a config perspective) there was an additional route created.  Again I have not tested it but if that is the case I could see why it would be confusing.

**Comment by pchlebda** [comment]
Can you have many properties files with zuul route configuration ? E.g:

- /resources/routes/a-category-service.properties
- /resources/routes/b-category-service.properties
- /resources/routes/c-category-service.properties

I've tried to load all these fields using @Bean PropertyPlaceholderConfigurer, but it does not work. It looks like zuul load configuration files at the very early stage.

Is there any way to change routing paths in runtime ? E.g

- zuul.routes.a.path=/a/**
- zuul.routes.a.url=http://host/service

change to:

- zuul.routes.a.path=/a/**
- zuul.routes.a.url=http://host/a-service

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
