### ISSUE TITLE
Question: What's the listener of EurekaRegistryAvailableEvent?

### ISSUE THREAD

**Issue by qct** [spring-cloud/spring-cloud-netflix#1726]
in `EurekaServerInitializerConfiguration` ,  after context initialized, I see these code:
```
publish(new EurekaRegistryAvailableEvent(getEurekaServerConfig()));
EurekaServerInitializerConfiguration.this.running = true;
publish(new EurekaServerStartedEvent(getEurekaServerConfig()));
```
but I can't find any listener to these two event: `EurekaRegistryAvailableEvent` and `EurekaServerStartedEvent`

**Comment by ryanjbaxter** [comment]
I believe you would just register an `ApplicationListener` just like you would for any other spring event you wanted to listen for. Have you tried doing something like 
```
@Component
public class MyListener {
  
    @EventListener
    public void handleEurekaRegistryAvailableEvent(EurekaRegistryAvailableEvent event) {
        ...
    }
}
```

**Comment by spencergibb** [comment]
They are provided in case a user needs them.
