### ISSUE TITLE
Why @EnableFeignClients can't be annotated on super class?

### ISSUE THREAD

**Issue by importsource** [spring-cloud/spring-cloud-netflix#1737]
For abstraction, I wrote a BaseApplication which contains all needed annotation as follow:
```java
@SpringBootApplication
@EnableDiscoveryClient
@EnableEurekaClient
@EnableHystrix
@EnableAutoConfiguration
@EnableSwagger2
@EnableFeignClients
@EnableZuulProxy
public class BaseApplication {
    public BaseApplication() {
    }
}
```

All worked well except @EnableFeignClients.

I must re-annotated `@EnableFeignClients` on the sub-class:
```java
@EnableFeignClients
public class ConsumerApplication extends BaseApplication {...}
``` 

Does this cute hole should  be fixed or updated in the future?

**Comment by spencergibb** [comment]
`@EnableFeignClients` does classpath scanning from the package of the class it is annotated on. In this case you actual feign clients are not located at or under `BaseApplication`s package.

**Comment by cHullaert** [comment]
thanks that really help me today.  Just to be sure. Is it possible to specify another classpath scanning base?

**Comment by spencergibb** [comment]
There is an attribute on the annotation

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
