### ISSUE TITLE
Spring Eureka  Accessing all clients

### ISSUE THREAD

**Issue by ranjith1976** [spring-cloud/spring-cloud-netflix#1739]
Is it possible for Spring Eureka to ping all the client urls registered to it? I have a need where i need to flush of all the cached information in clients at a point of time. And for that, i was thinking whether i could use some Eureka feature to inform clients to start refresh. 

thanks n regards,
Ranjith M.

**Comment by ranjith1976** [comment]
Thanks for response and sorry for the way i wrote the question.
The question was, i have a scenario where i started say 5 worker servers using Spring boot. And loadbalanced them using Spring Cloud Eureka. Now there is a scenario where i have to inform all servers to do a common procedure, and was checking whether it is possible using Spring Cloud Eureka. I.e. the client ask Eureka to provide all the listed server and port details and client will ping server's url to execute that process. Is this possible to get list of all the published server IPs and ports from Eureka? 

Thanks in advance

**Comment by ryanjbaxter** [comment]
Yes, as @spencergibb said above the `DiscoveryClient` API can give you the information you need. See http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_using_the_discoveryclient.
