### ISSUE TITLE
Eureka peer loses remote registrations after a couple of minutes

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#174]
This is probably just normal behaviour, but I want to understand it in case someone else gets confused the same way I am. I have a "local,cloud" profile in the "eureka" sample that registers with a remote peer (in PWS). It successfully fetches the remote catalog at first, which is quite useful as it lets me test things locally that depend on services in the remote location without having to run them locally. But then after a minute or two the remote catalog entries disappear and I'm left with only the locally registered servers. I imagine this is something to do with the configuration of the remote eureka (which is the same app running in "cloud" profile).

**Comment by dsyer** [comment]
I can't reproduce this one today. Will keep an eye open for it since I like this pattern.

**Comment by aivans** [comment]
I can reproduce this:
I have 2 eureka instances all having this configuration:
client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/,http://user:${eureka.password}@localhost:8762/eureka/,http://user:${eureka.password}@localhost:8763/eureka/

On peer1(8761) I can see all 3 instances: EUREKA 	n/a (3) 	(3) 	UP (3) 
On peer2 and peer3: No instances available.

At startup the instances were available on peer2 and peer3.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
