### ISSUE TITLE
Ribbon config without clientName not applies to all clients.

### ISSUE THREAD

**Issue by charlesvhe** [spring-cloud/spring-cloud-netflix#1741]
I wanna change default load banlancer rule with below configuration
> ribbon.NFLoadBalancerRuleClassName=charles.sc.consumer.WeightedMetadataRule

but it not work, I must assign serviceId like below
> someService.ribbon.NFLoadBalancerRuleClassName=charles.sc.consumer.WeightedMetadataRule

I can register WeightedMetadataRule as a spring bean, but it will disable all client's customization config.

org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration code sniper below:

 	@Bean
 	@ConditionalOnMissingBean
 	public IRule ribbonRule(IClientConfig config) {
 		if (this.propertiesFactory.isSet(IRule.class, name)) {
 			return this.propertiesFactory.get(IRule.class, config, name);
 		}
 		ZoneAvoidanceRule rule = new ZoneAvoidanceRule();
 		rule.initWithNiwsConfig(config);
 		return rule;
 	}

for this purpose: config default setting, and clients can have it's own setting replace default.

I extends org.springframework.cloud.netflix.ribbon.PropertiesFactory, and change below method:

 	public String getClassName(Class clazz, String name) {
		if (this.classToProperty.containsKey(clazz)) {
			String classNameProperty = this.classToProperty.get(clazz);
			String className = environment.getProperty(name + "." + NAMESPACE + "." + classNameProperty);
			if(!StringUtil.hasText(className )){
				className = environment.getProperty(NAMESPACE + "." + classNameProperty);
			}
			return className;
		}
		return null;
	}

It works fine for me. But PropertiesFactory fields are all private, it seems not want we extend this class, have there any other grace way?

**Comment by spencergibb** [comment]
Both updating the docs and his change are both reasonable.

**Comment by charlesvhe** [comment]
Thanks, I will try it.
