### ISSUE TITLE
upgrade spectator version

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-netflix#1742]
Hi, currently you use 0.0.30 version of spectator which is 1.5 year old.
The new versions include percentile timers and more very strong stuff.

Is it possible to upgrade to a newer version?

**Comment by spencergibb** [comment]
The new version is java 8 minimum. Spring Cloud won't go to java 8 until later this year.

**Comment by ezraroi** [comment]
thanks..

**Comment by ryanjbaxter** [comment]
I think we can leave this open so once we can support Java 8 we can upgrade

**Comment by spencergibb** [comment]
we no longer include spectator as a dependency.
