### ISSUE TITLE
@FeignClient does not support @GetMapping & co

### ISSUE THREAD

**Issue by christophe-f** [spring-cloud/spring-cloud-netflix#1750]
Hi,

In a FeignClient, I can only use the @RequestMapping annotation. @GetMapping & co will fail with this error message: Method destinations not annotated with HTTP method type (ex. GET, POST)

**Comment by ryanjbaxter** [comment]
We do actually.  The `Dalston.M1` release supports it.  See #1201.

**Comment by christophe-f** [comment]
Thanks @ryanjbaxter, I guess it's time to upgrade to Dalston :)
