### ISSUE TITLE
PUT requests with multipart are not proxied correctly through Zuul (the multipart data is removed)

### ISSUE THREAD

**Issue by trcodestore** [spring-cloud/spring-cloud-netflix#1751]
I previously reported this issue to the [Zuul repository](https://github.com/Netflix/zuul/issues/308) but was informed that this Spring Cloud Netflix repository is actually the correct place to report it. 

We are using Zuul to forward requests to our "file upload service". Our service has 2 endpoints:

1) A POST endpoint used to upload files. It consumes multipart ("multipart/form-data"). 
2) A PUT endpoint used to upload files (to Update existing files). It also consumes multipart ("multipart/form-data").

Zuul does not forward the multipart data correctly to the PUT endpoint. It seems to strip out the multipart data and results in a "MIMEParsingException". 

If we hit the PUT endpoint directly with cURL, the request is received correctly and looks like this:

`curl -v -X PUT -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" "http://localhost:8081/file/put"`

> Headers: {user-agent=[curl/7.35.0], host=[localhost:8082], accept=[/], content-length=[203], expect=[100-continue], content-type=[multipart/form-data; boundary=------------------------c1efb86a9054e387]}
> Entity: --------------------------c1efb86a9054e387 Content-Disposition: form-data; name="file"; filename="helloworld.txt" Content-Type: text/plain
>
> this is my file content
>
>--------------------------c1efb86a9054e387--

However, if we try to hit the PUT endpoint with cURL via Zuul, the HTTP request looks like this:

`curl -X PUT -H "Content-Type: multipart/form-data" -F "file=@/path/to/file.txt" "http://localhost:8082/file/put"`

> Header: {user-agent=[curl/7.35.0], accept=[*/*], expect=[100-continue], content-type=[multipart/form-data;boundary=hkBnDNXOcDTwkuL1qLhglF6i4NA2YREd], x-forwarded-host=[localhost:8081], x-forwarded-proto=[http], x-forwarded-prefix=[/file], x-forwarded-port=[8081], x-forwarded-for=[127.0.0.1], accept-encoding=[gzip], content-length=[38], host=[localhost:8082], connection=[Keep-Alive]}
> Entity: --hkBnDNXOcDTwkuL1qLhglF6i4NA2YREd--

Notice that the Entity is incomplete.

I have uploaded example code to this repository: https://github.com/trcodestore/zuul-put-demo. The repository contains 2 small projects used to demonstrate this issue. The readme contains build and run instructions. 

Any advice is appreciated. Thank you for your time.

**Comment by trcodestore** [comment]
Okay, I have the solution ([credit: Mohammad Zolmajd](http://i-proving.com/2015/05/14/submitting-a-multipart-request-multipartform-data-using-put-and-spring-boot/)). It's actually a Spring Boot issue, not a Zuul problem.

Spring Boot uses `StandardServletMultipartResolver` to handle multipart - which assumes that all multipart requests will be submitted with POST. 

To allow StandardServletMultipartResolver to handle PUT requests, we have to override the `isMultiPart` method. I ended up using the following configuration:

    @Bean
    public MultipartResolver multipartResolver() {
       return new StandardServletMultipartResolver() {
         @Override
         public boolean isMultipart(HttpServletRequest request) {
            String method = request.getMethod().toLowerCase();
            if (!Arrays.asList("put", "post").contains(method)) {
               return false;
            }
            String contentType = request.getContentType();
            return (contentType != null &&contentType.toLowerCase().startsWith("multipart/"));
         }
       };
    }

**Comment by priyaselladurai** [comment]
Able to upload the multipart via Zuul Proxy using HTTP Post Method. as mentioned above, its not forwarding the multipart for Put/Patch methods

**Comment by kaushikmeduri** [comment]
thank you , its a great find .  Wish there is a documentation on this .
