### ISSUE TITLE
Have Zuul Hystrix Ribbon Command throw exception when service returns 500

### ISSUE THREAD

**Issue by Jacuo** [spring-cloud/spring-cloud-netflix#1753]
Is possible to configure Zuul in such a way, that when called service return 500 error, there is exception which is registered in Hystrix as error. 
Now 500 error in called service is visible in Hystrix as succesfull execution. I want to have the same behaviour for 500 errors as for timeouts

**Comment by spencergibb** [comment]
What version are you using? Which http client are you using?

**Comment by Jacuo** [comment]
Camden.SR5, Apache Client

**Comment by Jacuo** [comment]
But also tested with ribbon http client

**Comment by spencergibb** [comment]
Zuul is a proxy. If it receives a response from a downstream service, it returns it to the client, even errors. This would be an enhancement that should be opt-in, not the default behavior.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
