### ISSUE TITLE
how can i add post body in zuul filter?

### ISSUE THREAD

**Issue by dragontree101** [spring-cloud/spring-cloud-netflix#1756]
my request is 
```
curl -XPOST '127.0.0.1:8080/zuul-example -d 'abc=123'
```
to zuul gateway

and i want to add some post params (like xxx=666) in zuul's filter

and i want to backend app can get both of param abc=123 and xxx=666

how can i do?  thanks

**Comment by ryanjbaxter** [comment]
You want to add the parameter `xxx=666` in a Zuul filter?

**Comment by spencergibb** [comment]
He wants to modify the body.

**Comment by lowzj** [comment]
I think that `FormBodyWrapperFilter` may be an example to modify request body. Wrapping the request and building a new contend data. These should be in the `pre` filter.

**Comment by lhchingit** [comment]
Hi,
@spencergibb has provided many good examples about Zuul filter, I think you can find what you want, please refer to this [LINK](https://github.com/spring-cloud-samples/sample-zuul-filters/tree/master/src/main/java/org/springframework/cloud/samplezuulfilters).

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
