### ISSUE TITLE
Delegating ribbonServerList to DiscoveryClient 

### ISSUE THREAD

**Issue by hswee** [spring-cloud/spring-cloud-netflix#1758]
This is related to 
[#564 Ribbon listOfServers configuration appears to be getting ignored Issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/564)

I am trying to have the return of ribbonServerList be delegated to a DiscoveryClient for all ribbon clients, where the ribbon client name will be the name of the service, and so I have the following class:
```
@Configuration
public class DiscoveryEnabledRibbonConfiguration {

    @Autowired
    private DiscoveryClient discoveryClient;

    @Bean
    public ServerList<Server> ribbonServerList(IClientConfig config) {
        Server[] servers = discoveryClient.getInstances(config.getClientName()).stream()
                .map(i -> new Server(i.getHost(), i.getPort()))
                .toArray(Server[]::new);
        return new StaticServerList(servers);
    }
}
```
Missing from the above is the @RibbonClient annotation, without which seems to cause ribbon to ignore the above class entirely.
From issue #564, I learned the @RibbonClient annotation seems to limit the configuration to just one client name, and I could probably get around this by defining having a @RibbonClient annotated class for every service I want, but I'm hoping there would be a nicer way to do this.

I'd appreciate any help you could give.

**Comment by spencergibb** [comment]
Why are you trying to do this? This is already built in?

**Comment by spencergibb** [comment]
You use `@RibbonClients(defaultConfiguration=DiscoveryEnabledRibbonConfiguration.class)` though I don't know why you would want the above class.

**Comment by hswee** [comment]
The overall goal is to have ribbon load balance through a list of servers returned from DiscoveryClient (which switches between consul and kubernetes implementations)

Perhaps it's my misunderstanding of how ribbon works. I was doing this because I was stepping through the No instances available IllegalStateException, and I found that it was because 
loadBalancer.choose(serviceName) in RetryLoadBalancerInterceptor was returning null 

Tracing further led to RibbonClientConfiguration's ribbonServerList, and when I tried evaluating serverList.getUpdatedListOfServers(), it was returning an empty array, and I assumed this was where the discoveryClient would return the actual list of servers.

**Comment by spencergibb** [comment]
Both consul & kubernetes have `ServerList` implementations if you are using the right starters. If you are using the eureka client starter, that won't work with consul & k8s.

**Comment by hswee** [comment]
I'm not using the eureka client starter, and I have a custom implementation of DiscoveryClient that I use for developing locally and in a docker environment without having to run any other services like consul.
@RibbonClients is just what I was looking, thank you for your help!

However, I am now getting a 
Parameter 0 of method ribbonServerList in DiscoveryEnabledRibbonConfiguration required a bean of type 'com.netflix.client.config.IClientConfig' etc.. error
From [stackoverflow](http://stackoverflow.com/questions/34799918/how-can-i-override-ribbonserverlistfilter), this seems like a problem with excluding the class containing the @RibbonClients annotation from @ComponentScan. Unfortunately I am still getting the same issue.

In addition to the above class, I now have:
```
@Configuration
@RibbonClients(defaultConfiguration = DiscoveryEnabledRibbonConfiguration.class)
public class LocalRibbonConfiguration {
}
```
Am I still missing something?

**Comment by hswee** [comment]
My bad, it was an error in the @ComponentScan exclude syntax, everything's working great.
Thank you again!

**Comment by andriosr** [comment]
Just to make sure anybody that come across this error get it solved: as stated in the docs, you need to make sure the config does not go through Spring`s ComponentScan. One way to do it is:

`@ComponentScan(excludeFilters = [@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = RibbonConfig.class)])`

**Comment by evaDave** [comment]
d

**Comment by evaDave** [comment]
This thread helped me, but was still facing issues, so here is my working example:

// ExampleGatewayApplication.java

@EnableDiscoveryClient
@EnableHystrix
@SpringBootApplication
@RibbonClients(defaultConfiguration = ExampleRibbonClientConfiguration.class)
@ComponentScan(excludeFilters = @Filter(type = FilterType.ASSIGNABLE_TYPE, classes = ExampleRibbonClientConfiguration.class))
public class ExampleGatewayApplication{ ...


// ExampleRibbonAutoConfiguration.java

@Configuration
@EnableConfigurationProperties
@ConditionalOnBean(SpringClientFactory.class)
@ConditionalOnProperty(value = "spring.cloud.portal.ribbon.enabled", matchIfMissing = true)
@AutoConfigureAfter(RibbonAutoConfiguration.class)
@RibbonClients(defaultConfiguration = ExampleRibbonClientConfiguration.class)
public class ExampleRibbonAutoConfiguration {

}


// ExampleRibbonClientConfiguration.java

@Configuration
public class ExampleRibbonClientConfiguration {
	
	@Autowired
	private DiscoveryClient discoveryClient;	

	private String serviceId = "client";
	protected static final String VALUE_NOT_SET = "__not__set__";
	protected static final String DEFAULT_NAMESPACE = "ribbon";

	public ExampleRibbonClientConfiguration () {
	}

	public ExampleRibbonClientConfiguration (String serviceId) {
		this.serviceId = serviceId;
	}

	@Bean
	@ConditionalOnMissingBean
	public ServerList<?> ribbonServerList(IClientConfig config) {
		
        Server[] servers = discoveryClient.getInstances(config.getClientName()).stream()
                .map(i -> new Server(i.getHost(), i.getPort()))
                .toArray(Server[]::new);
        
        return new StaticServerList(servers);
	}
