### ISSUE TITLE
how to create multiple instances of eureka application service

### ISSUE THREAD

**Issue by Snehal001** [spring-cloud/spring-cloud-netflix#1759]
I am using eureka in java using spring boot. How to create multiple instances of the same service? I am using it on standalone machine

**Comment by ryanjbaxter** [comment]
Your question is lacking details.  You can start multiple instances of the same application on the same machine by starting each instance on a different port.

**Comment by spencergibb** [comment]
This project won't launch instances for you.

**Comment by Snehal001** [comment]
@spencergibb then how to create instances?

**Comment by Snehal001** [comment]
@ryanjbaxter can you plz explain a bit more how to do this

**Comment by spencergibb** [comment]
@Snehal001 it's not the job of spring cloud to create instances. You can by running multiple `java -jar` applications with a different `--server.port` argument.
