### ISSUE TITLE
Zuul seems to rewrite routes after REST call

### ISSUE THREAD

**Issue by srehker** [spring-cloud/spring-cloud-netflix#1763]
Hello everyone,

I have encountered a strange behaviour with our Zuul-Proxy in our Microservice-Project. My Setup consists of a Discovery-Service (Eureka), an API-Gateway (Zuul) and two Microservices "A" & "B".
After starting the setup, the following routes are shown via "localhost:10000/routes":
```
{
  "/api-gateway/**": "api-gateway",
  "/a-service/**": "a-service",
  "/b-service/**": "b-service"
}
```
My Zuul Config looks like this:
```
zuul:
  ignored-services: ''
  add-proxy-headers: true
  sensitiveHeaders: 'Cookie,Set-Cookie'
```

Now I access the services via the gateway and make some REST calls:

http://localhost:10000/a-service/sayHello --> OK
http://localhost:10000/b-service/sayBye   --> OK
http://localhost:10000/a-service/sayHello --> ERROR 404

I can see that the last request is mistakenly routed to Service B, even though I am using the "/a-service/**" route. How can this happen? Did the second REST call to service B somehow rewrite the routing? However "localhost:10000/routes" is still returning the same as above. This also works with calling the services in opposite order B-A-B -> 404 and mistakenly routed to service A.

I attached a minimal project with the 4 components, which should let you easily replicate this behaviour:
[MinimalZuulRouteBugProject.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/827997/MinimalZuulRouteBugProject.zip)

Thank you, for any insights regarding this issue.

**Comment by spencergibb** [comment]
Can you please try with the latest code, `Camden.SR5`?

**Comment by srehker** [comment]
I updated to `Camden.SR5` and `spring-boot-starter-parent 1.4.3-RELEASE` but the problem persists. Here is my updated minimal project:
[MinimalZuulRouteBugProject - SR5.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/828090/MinimalZuulRouteBugProject.-.SR5.zip)

**Comment by spencergibb** [comment]
This is a documented issue here http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_customizing_the_ribbon_client

> The FooConfiguration has to be @Configuration but take care that it is not in a @ComponentScan for the main application context, otherwise it will be shared by all the @RibbonClients. If you use @ComponentScan (or @SpringBootApplication) you need to take steps to avoid it being included (for instance put it in a separate, non-overlapping package, or specify the packages to scan explicitly in the @ComponentScan).

In your case `RibbonConfigAvailability` is picked up by the component scan and **shared** between all ribbon clients (which is bad). Either remove the `@Configuration` (it doesn't have to be annotated as such, this is how I tested) or exclude it from component scanning.

**Comment by srehker** [comment]
Thank you, this worked also in our big project! :)
