### ISSUE TITLE
Using Feign to get Response Headers

### ISSUE THREAD

**Issue by matheus208** [spring-cloud/spring-cloud-netflix#1764]
Hi!

I'm using Spring Cloud (v Brixton.SR7) with Hystrix + Feign for my requests. (v 1.2.3.RELEASE).

According to [this](https://github.com/spring-cloud/spring-cloud-netflix/issues/668), I should be able to use `ResponseEntity` as the method return, to retrieve the headers in a response.

However, if I use that that, I get the following error:

`feign.FeignException: Can not deserialize instance of org.springframework.http.ResponseEntity out of START_ARRAY token
 at [Source: java.io.BufferedReader@45f2337a; line: 1, column: 1] reading GET <<<URL>>>`

I'm using `ResponseEntity<MyObject>` as I get this error. If I replace it with `MyObject`, the deserialisation is successful. So apparently it's not a problem with the model, but something with Feign not able to build a ResponseEntity?

I couldn't find any of this in the [Spring Cloud documentation](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html) nor the [Feign documentation](https://github.com/OpenFeign/feign). I assume this is a common use case (reading headers), so maybe it'd be nice to include something to that extend there.

Am I doing something wrong? Any info I failed to provide? What's the proper way of getting the response headers with Spring Cloud + Hystrix + Feign?

Thank you in advance

**Comment by ryanjbaxter** [comment]
Could you perhaps provide your Feign client implementation for reference?

**Comment by matheus208** [comment]
The guys over OpenFeign gitter helped me out and I kind of solved it. 

The correct object to return is Response (feign.Response). With that, you can access the headers. The only downside is that now the request body is an input stream and won't be deserialised for you anymore.

Ideally we would be able to use Response<MyObject> and Feign would do that job for for us.

But for now using it solves my problem of getting the headers.

**Comment by spencergibb** [comment]
He's not using the Spring response entity decoder
