### ISSUE TITLE
Ribbon Timeout not working in FeignClient

### ISSUE THREAD

**Issue by khannedy** [spring-cloud/spring-cloud-netflix#1773]
I create ribbon client in application.properties 

```
ribbon.ConnectTimeout=10
ribbon.ReadTimeout=10
```

And create feign client 

```java
@FeignClient(name = "authFeign", url = "${service.auth.endpoint}",
    fallbackFactory = AuthFeignFallbackFactory.class)
public interface AuthFeign {
```

But even the response 1000 miliseconds from the service, feign client still using default ribbon connect timeout 2000 miliseconds and read timeout 5000 miliseconds

**Comment by ryanjbaxter** [comment]
When you use the URL parameter in the feign client it will not use Ribbon so those Ribbon parameters will not apply.

**Comment by khannedy** [comment]
Hi @ryanjbaxter thanks for the answer, so if I'm using URL, how to set connection timeout? There is no documentation in spring cloud netflix page

**Comment by khannedy** [comment]
I try using configuration attribute, and it works

```java
@FeignClient(name = "authFeign", url = "${service.auth.endpoint}",
    fallbackFactory = AuthFeignFallbackFactory.class, configuration = AuthConfiguration.class)
public interface AuthFeign {
```

```java
@Configuration
public class AuthConfiguration {

  @Bean
  public Request.Options options() {
    Request.Options options = new Request.Options(
        10, 10
    );
    return options;
  }

}
```

**Comment by dingzhongfa** [comment]
it's real a bug
