### ISSUE TITLE
turbine-stream doesn't register with eureka ootb

### ISSUE THREAD

**Issue by joshiste** [spring-cloud/spring-cloud-netflix#1774]
When using the sample from https://github.com/spring-cloud-samples/turbine the turbine application fails to register itself as eureka client. You need to add `eureka.instance.non-secure-port` to make it work. 

Issue raised as suggested here: https://gitter.im/spring-cloud/spring-cloud?at=58c68386dd08b4b859c38c1c

**Comment by eacdy** [comment]
same issue. awesome answer.
Save me a lot.

**Comment by gdong42** [comment]
@dsyer can you please suggest which property to set if I'm using spring-cloud-consul-discovery. Have same issue here with consul.

**Comment by gdong42** [comment]
Never mind. Setting `spring.cloud.consul.discovery.port` did the trick.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
