### ISSUE TITLE
Zuul, Spring Session & Spring Security corner case

### ISSUE THREAD

**Issue by dmikusa-pivotal** [spring-cloud/spring-cloud-netflix#1775]
Scenario:

1. You have two applications:  a Zuul proxy which is operating as a gateway and a backend service (there could be other backend services, but it's not necessary for this scenario).  The operator controls both the gateway and all backend services.

2. Authentication happens on the Zuul proxy.  Spring Session is used to share the session with the backend services.

3. Spring Security is used to perform form based login on the Zuul proxy.  Spring Security is used to perform authorization on the backend services.

Attaching two applications which can be used to simulate this scenario:  gateway & books.

[book.tar.gz](https://github.com/spring-cloud/spring-cloud-netflix/files/839600/book.tar.gz)
[gateway.tar.gz](https://github.com/spring-cloud/spring-cloud-netflix/files/839601/gateway.tar.gz)

Steps to replicate:

0.) Start redis on localhost.  Docker is an easy way to do this.
1.) Start `book` app.  It's listening on 8090.
2.) Start `gateway` app.  It's listening on 8080.

Success scenario / confirm apps are working:

1.) Open an incognito window and go to http://localhost:8080/trace
2.) You'll be redirect to login.  Enter `user` & `password` as the creds.
3.) The login will succeed, and you'll see the trace output
4.) Navigate to http://localhost:8080/books/available.  This should now succeed.

Failure Scenario:

1.) Open an incognito window and go to http://localhost:8080/books/available
2.) You'll be redirect to login.  Enter `user` & `password` as the creds.
3.) The login will succeed, but access to resource is denied with a 403.

The issue is triggered in the gateway app by Spring Security's RequestCacheAwareFilter.  RequestCacheAwareFilter is invoked in the failure scenario to replay the initial request (i.e. http://localhost:8080/books/available) after the login has completed.  The problem is that the replayed request doesn't have a cookie header, so when Zuul proxies the replayed request the proxied request does not set a cookie header either.  This is despite a session & session cookie being accessible through the HttpServletRequest object; Zuul doesn't look at those, just headers.  Since there's no cookie header sent, the backend app doesn't know about the session, which it expects to exist and returns a 403.

The success scenario works because the request to the backend app is no longer being replayed.  Authentication has already happened and a cookie header exists on that request.  Thus when Zuul proxies the request to the backend application, it sends along the cookie header, the backend app sees the cookie and is able to authorize the user.

It's not too difficult to workaround this issue:

1.) Stop `gateway` app.
2.) Open SessionHeaderLoadingZuulPreFilter.java.  Uncomment line #14, with `@Component`.  Save.
3.) Start `gateway` app.
4.) Repeat Failure Scenario:
     a.) Start `book` app.  It's listening on 8090.
     b.) Start `gateway` app.  It's listening on 8080.
     c.) Open an incognito window and go to http://localhost:8080/books/available
     d.) You'll be redirect to login.  Enter `user` & `password` as the creds.
     e.) The login will succeed and be displayed.

The workaround is a filter for Zuul.  The filter looks at incoming requests to see if there is a session, but no session cookie header.  When that happens, it adds a session cookie header to the request that Zuul is going to make to the backend service and injects the session id from the current session.

```
    @Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();
        HttpServletRequest request = context.getRequest();      
        List<String> cookies = Collections.list(request.getHeaders("cookie"));
        HttpSession session = request.getSession(false);
        if (session != null && cookies.stream().noneMatch(c -> c.startsWith("SESSION="))) {
            context.addZuulRequestHeader("cookie", "SESSION=" + session.getId());
        }

        return null;
    }
```

This would seem to be a corner case when these three technologies are used together, not necessarily an issue with Spring Cloud Netflix, but I thought I would start here.  If it would make more sense to take this to Spring Security / Spring Session project instead, let me know.

The request here is to make this scenario work out-of-the-box.

**Comment by dsyer** [comment]
We could add a filter like this if we detect Spring Session I suppose. We'd need a way to synchronize the cookie name with the session filter (e.g. by sharing the Spring Boot autoconfig properties).

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
