### ISSUE TITLE
Zuul default behaviour

### ISSUE THREAD

**Issue by rterentiev** [spring-cloud/spring-cloud-netflix#1779]
Lets say I have zuul, eureka and two instances of same microservice.
```
zuul.routes.my-microservice.path=/my-microservice/**
zuul.routes.my-microservice.serviceId=my-microservice
zuul.routes.my-microservice.stripPrefix=true
```
Zuul will be using Ribbon for routing.

Default configuration contains following values for hystrix and ribbon:
```
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=1000
ribbon.ReadTimeout=5000
ribbon.MaxAutoRetriesNextServer=1
```

This may cause following behaviour:

Lets say first call to my-microservice is failed by read timeout. Ribbon uses second instance of my-microservice and call is returned in 100ms. But hystrix throws timeout exception, because total time that was spent is 5100ms (5 seconds for first call plus 100 milliseconds for second call).

This is confusing.
I think, Zuul should not do another call, if there is no time for it and it will be failed in any case.

**Comment by ryanjbaxter** [comment]
@rterentiev seems similar to #1772.  Can we perhaps close this issue and work the problem through #1772?

**Comment by rterentiev** [comment]
@ryanjbaxter yes. thanks!
