### ISSUE TITLE
DOWN Health status does not lead to instance being removed from Eureka

### ISSUE THREAD

**Issue by jmart1** [spring-cloud/spring-cloud-netflix#1780]
Similar to issue #1051.  

We notice that when systems that come with health checks already, like MongoDB and Rabbit, go down, then Eureka reports them as DOWN.  But for our custom HealthIndicators, when they report DOWN, Eureka keeps the instance UP, even though /health does in fact show DOWN.

Is there something we need to do to trigger the update to Eureka with DOWN status so that the instance is reported as DOWN in Eureka?  We also use Spring Boot Admin, and that shows DOWN for our custom HealthIndiciators; I think that's because it is actively polling.

We are using "spring-cloud-netflix-core-1.2.5.RELEASE" and "spring-cloud-netflix-eureka-client-1.2.5.RELEASE" with "spring-cloud-dependencies Camden.SR5" and "spring-boot-starter-parent 1.4.4.RELEASE".

**Comment by spencergibb** [comment]
Eureka does not do a healthcheck. Have you set `eureka.client.healthcheck.enabled=true`? This will locally determine the health and send an updated status to eureka during a heartbeat.

**Comment by jmart1** [comment]
Thanks for the response.  We do have the property set to true.

/env
...
"eureka.client.healthcheck.enabled": "true",
...

Please note that when MongoDB or Rabbit goes down that Eureka does in fact set the status to DOWN.  So far we only notice this for our custom HealthIndicators.  I have looked over the code for how the MongoHealthIndicator works, on our custom HealthIndicators do the same thing, create a Health object using the Builder and return it.

**Comment by spencergibb** [comment]
Are you using discovery to bootstrap configuration (ie #1158)?

**Comment by jmart1** [comment]
Thank you.  We are looking into this.  Will respond soon.

**Comment by MartinFuerstenau** [comment]
We discovered the same issue with Camden.SR6 and Spring-Boot 1.5.2. We have set `eureka.client.healthcheck.enabled: true`
Eureka registers instances with status UP although the instance health endpoint returns the following:
```
{
	"status":"DOWN",
	"discoveryComposite":{
		"description":"Spring Cloud Eureka Discovery Client",
		"status":"UP",
		"discoveryClient":{
			"description":"Spring Cloud Eureka Discovery Client",
			"status":"UP",
			"services":[...]},
			"eureka":{
				"description":"Remote status from Eureka server",
				"status":"UP",
				"applications":{...}
			}
		},
	"db":{
		"status":"DOWN",
		"error":"java.lang.IllegalStateException: Cannot determine target DataSource for lookup key []"
	}
}
```

**Comment by spencergibb** [comment]
@MartinFuerstenau Are you using discovery to bootstrap configuration?

**Comment by MartinFuerstenau** [comment]
@spencergibb No, I use the Config-First-Bootstrap approach.

**Comment by spencergibb** [comment]
@MartinFuerstenau that is what I asked, so yes.

**Comment by qsLI** [comment]
we have the same issue, sometimes

**Comment by spencergibb** [comment]
Is this still an issue?

**Comment by hugadams** [comment]
Sorry - should `eureka.client.healthcheck.enabled=true` be set in the eureka server configuration or in the eureka client config?

**Comment by spencergibb** [comment]
client

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
