### ISSUE TITLE
Zuul Exceptions are being logged with log level WARN

### ISSUE THREAD

**Issue by mpryahin** [spring-cloud/spring-cloud-netflix#1781]
When exception occurs during zuul routing it is then handled by the `org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter` which logs the error with log level `WARN`. I think it's worth changing it to `ERROR` because everyone expects exceptions to be logged with the `ERROR` log level and logging with `WARN` log level might lead to exceptions loss as it was in my case.

**Comment by ryanjbaxter** [comment]
I am not sure all exceptions that occur in the course of proxying a request would warrant an `ERROR` level.  What kind of exceptions where you seeing?

**Comment by mpryahin** [comment]
I'm sorry... I happen to use outdated version of spring-cloud-netflix, will close the issue. 
Sorry for that.

**Comment by mpryahin** [comment]
used outdated version
