### ISSUE TITLE
hystrix-javanica-ctw artifact

### ISSUE THREAD

**Issue by tol** [spring-cloud/spring-cloud-netflix#1782]
Hi!

How can I get the hystrix-javanica-ctw?
I am trying this, but it didn't work...

    <dependency>
        <groupId>com.netflix.hystrix</groupId>
        <artifactId>hystrix-javanica-ctw</artifactId>
        <version>1.5.10</version>
    </dependency>

**Comment by ryanjbaxter** [comment]
Not a question for Spring Cloud, try https://github.com/Netflix/Hystrix
