### ISSUE TITLE
Zuul not honoring proxy settings

### ISSUE THREAD

**Issue by vasyaivanov** [spring-cloud/spring-cloud-netflix#1791]
Hi. I know there is/was a bug where Zuul does now honor proxy setting set in Java.
We tried couple of things.

1) Upgrading to "org.springframework.cloud:spring-cloud-dependencies:Brixton.SR5"
2) Changing RoutingFilter to inherit not from ZuulFilter but from SimpleHostRoutingFilter.

We are using JVM args like this:
bootRun {
systemProperty "spring.profiles.active", "dev,orcl"
jvmArgs "-Dhttps.proxySet=true", "-Dhttp.proxySet=true", "-Dhttp.proxyHost=http://proxy.ourcompanyname.com", "-Dhttp.proxyPort=8080", "-Dhttps.proxyHost=http://proxy.ourcompanyname.com", "-Dhttp.proxyPort=8080", "-Dhttp.nonProxyHosts=localhost|*.ourcompanyname.com"
}

Is this a still known issue?

**Comment by ryanjbaxter** [comment]
This change went into `1.2.0.RELEASE` https://github.com/spring-cloud/spring-cloud-netflix/commit/f094ecfd889be7c22d26e939fa0650b6b6b3642e.  This would be in the Camden release train.  Can you try Camden.SR6?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
