### ISSUE TITLE
Disable routes endpoint

### ISSUE THREAD

**Issue by alenavorozhbieva** [spring-cloud/spring-cloud-netflix#1797]
I expect that routes endpoint could be closed by endpoints.routes.enabled: false property like other endpoints. But it's not working. So how can I close this endpoint? I'v seen https://github.com/spring-cloud/spring-cloud-netflix/issues/547 issue. But if I set management.port=-1 the health endpoint will be unavailable too. 

spring-cloud-netflix version: 1.2.0.RELEASE

**Comment by ryanjbaxter** [comment]
I dont think there is really a good way to do this currently.  You could maybe provide your own Endpoint that does something similar but uses the correct super classes to allow you to enable/disable it.  The PR I just created should fix the issue.

**Comment by alenavorozhbieva** [comment]
I don't need this endpoint at all. So I need to close it for security reasons. So providing my own Endpoint doesn't make sence. Thank you for PR

**Comment by ryanjbaxter** [comment]
OK makes sense.  Since the routes endpoint configuration has a conditional on `Environment` you can provide your `Environment` bean which does nothing to basically override our `routes` endpoint.
