### ISSUE TITLE
Zuul with OkHttp3 fails to proxy requests to recent Spring Boot (with Tomcat) applications with certain encoded query parameters

### ISSUE THREAD

**Issue by arakelian** [spring-cloud/spring-cloud-netflix#1800]
I recently began to see errors like this in our Spring Boot-based microservice applications:

```
Mar 20, 2017 2:47:59 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:471)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

This error occurs when Tomcat 7.0.73+, 8.0.39+, and 8.5.7+ receive requests with URL parameters that  are not "properly encoded".  Note that Tomcat has recently become more strict about RFC compliance. 

This was confusing because our client had worked for a long time, and had always URL encoded the request parameters.  The request we were sending contained a small snippet of JSON, and looked like this, e.g. http://mycompany.com/query?json=%7B%7D, 

Eventually, we realized the that error occurred only when running against a Spring Zuul server that forwarded the request to the microservice.  We had configured Zuul to use OkHttp3 as the HTTP proxy (instead of the default, HttpClient) and when OkHttp3 forwarded the request to the microservice, the parameters were decoded, the URL rebuild, and the curly brace characters were no longer escaped.

I filed a bug report with OkHttp3 here:
See https://github.com/square/okhttp/issues/3235

There are no issues when these request are sent directly to the microservice.

I do not know if HttpClient experiences the same issue -- perhaps changes to HttpClient were coordinated with Tomcat, or perhaps the Tomcat author tested with HttpClient and everything worked fine.  

To resolve this issue temporarily, we plan to add a RibbonRequestCustomizer to re-encode the URL build by OkHttpRibbonRequest.toRequest().  I will post that when I know it's working.

**Comment by garakelian** [comment]
Here is my workaround.  In my ZuulConfiguration, I have this static inner class:

```
	public static final class StrictUrlEscaping implements RibbonRequestCustomizer<Request.Builder> {
		@Override
		public boolean accepts(Class builderClass) {
			return builderClass == Request.Builder.class;
		}

		/**
		 * Returns a Tomcat-friendly URL with strict URL escaping
		 *
		 * @param url
		 *            OkHttp3 URL
		 * @return Tomcat-friendly URL with strict URL escaping
		 */
		public static String buildUrl(HttpUrl url) {
			URIBuilder builder = new URIBuilder();
			String scheme = url.scheme();
			builder.setScheme(scheme);

			StringBuilder userInfo = new StringBuilder();
			String username = url.username();
			String password = url.password();
			if (!username.isEmpty() || !password.isEmpty()) {
				userInfo.append(username);
				if (!password.isEmpty()) {
					userInfo.append(':');
					userInfo.append(password);
				}
			}

			if (userInfo.length() != 0) {
				builder.setUserInfo(userInfo.toString());
			}

			builder.setHost(url.host());
			int port = url.port();
			if (port != HttpUrl.defaultPort(scheme)) {
				builder.setPort(port);
			}

			builder.setPath(Joiner.on('/').join(url.pathSegments()));
			for (String name : url.queryParameterNames()) {
				for (String value : url.queryParameterValues(name)) {
					builder.addParameter(name, value);
				}
			}

			builder.setFragment(url.fragment());

			return builder.toString();
		}

		@Override
		public void customize(Request.Builder builder) {
			HttpUrl laxUrl = builder.build().url();
			String strictUrl = buildUrl(laxUrl);
			builder.url(strictUrl);
		}
	}
```

I then register the RibbonRequestCustomizer:

```

	@Bean
	public RibbonRequestCustomizer fixEscapingCustomizer() {
		// OkHttp3 escaper is not strict enough
		return new StrictUrlEscaping();
	}
```

This fixes the issue for me.

**Comment by garakelian** [comment]
Here's the unit test that I wrote to verify my fix:

```
import org.junit.Assert;
import org.junit.Test;

import com.mycompany.conf.ZuulConfiguration.StrictUrlEscaping;
import okhttp3.HttpUrl;

public class StrictUrlEscapingTest {
	@Test
	public void testEscaping() {
		verifyStrictReencoding( //
				"http://mycompany.com:80/path/query.html?json={}#fragment", //
				"http://mycompany.com/path/query.html?json=%7B%7D#fragment");

		verifyStrictReencoding( //
				"http://user:secret@mycompany.com/path/query.html?json={}#fragment", //
				"http://user:secret@mycompany.com/path/query.html?json=%7B%7D#fragment");

		verifyStrictReencoding( //
				"http://user@mycompany.com/path/query.html?json={}#fragment", //
				"http://user@mycompany.com/path/query.html?json=%7B%7D#fragment");
	}

	private void verifyStrictReencoding(String lax, String strict) {
		// OkHttp3 is more forgiving than HttpClient
		// note: if this fails, OkHttp3 has probably been updated to work like
		// HttpClient and this code is probably no longer needed
		HttpUrl laxUrl = HttpUrl.parse(lax);

		// use HttpClient to build stricter URL
		String strictUrl = StrictUrlEscaping.buildUrl(laxUrl);
		Assert.assertEquals(strict, strictUrl);

		// verify OkHttp3 retains escaping
		HttpUrl parsedUrl = HttpUrl.parse(strictUrl);
		Assert.assertEquals(strict, parsedUrl.toString());
		Assert.assertEquals(strict, parsedUrl.url().toString());
	}
}
```

**Comment by spencergibb** [comment]
According to https://bz.apache.org/bugzilla/show_bug.cgi?id=60594 (via the square issue)

> Fixed in:
> 
> - 8.5.x for 8.5.12 onwards
> - 8.0.x for 8.0.42 onwards
> - 7.0.x for 7.0.76 onwards

I'm not sure we want to do anything here. You have a workaround.

**Comment by garakelian** [comment]
Respectfully, I wouldn't describe their change as a 'fix'.  

If you look at the PR (https://bz.apache.org/bugzilla/attachment.cgi?id=34698), Tomcat requires you to set the system property `tomcat.util.http.parser.HttpParser.requestTargetAllow`, which enable _more forgiving_ parsing of what it is _correctly_ identifying as an invalid URL (according to the RFCs referenced).

If Spring Boot configured this property automatically, I'd argue it would make our apps less secure by default.  If it doesn't, others will run into this issue.

**Comment by spencergibb** [comment]
It's a very specific problem: okhttp3, tomcat AND specific characters in query parameters.

**Comment by garakelian** [comment]
Tomcat is the default servlet container used by Spring Boot. Future versions of Tomcat will continue to reject malformed URLs parameters (and should, by default).  In fact, the patch you referenced is titled, "RFC 7230/3986 url requirement that prevents unencoded curly braces _should be optional_ [emphasis added], since it breaks existing sites".  Hopefully, Spring Boot does not intend to 'fix' the problem by enabling this option by default.

With respect to the use of OkHttp3, that is supported by Spring Cloud, is it not? (via ribbon.okhttp.enabled=true)? You're listed in the @author comments for some of that code. If that's fringe/experimental/non-supported, then I guess I'd like to know that.

Today, strictly speaking, OkHttpRibbonRequest is broken.  It is decoding and rebuilding a URL, and on line 63, it calls HttpUrl.Builder.addQueryParameter(name, value), which fails to encode the new URL parameter according to the RFC specs.

**Comment by garakelian** [comment]
@spencergibb For what it's worth, I do recognize that the fix really belongs in OkHttp3's HttpUtil.Builder code, which is not maintained here.  If a change was made to OkHttpRibbonRequest, it would really be a workaround to that class, which is not desirable.

**Comment by spencergibb** [comment]
So if the bug is in OkHttp, can we close this issue?

**Comment by arakelian** [comment]
@spencergibb Go ahead and close. If/when OkHttp is patched, I'll reopen this ticket and request a upgrade to that version. If other people encounter issue in the meantime, they'll have a workaround. Thanks.
