### ISSUE TITLE
Zipkin requires service name

### ISSUE THREAD

**Issue by elgohr** [spring-cloud/spring-cloud-netflix#1801]
Since updating to Spring Boot 1.5.2 (Camden.SR6) Zipkin needs a configured service name. Otherwise the application is shown as "unknown" in traces. Setting spring.zipkin.service.name: ${spring.application.name} in application.yml is a workaround.

**Comment by spencergibb** [comment]
I'm assuming you are using spring-cloud-sleuth. Please open the issue there: https://github.com/spring-cloud/spring-cloud-sleuth/issues
