### ISSUE TITLE
@FeignClient Retryer.NEVER_RETRY is not effect

### ISSUE THREAD

**Issue by wangfeishsh** [spring-cloud/spring-cloud-netflix#1803]
I have micro-service ms-a and ma-b , ms-a read timeout is 20s while a method of ms-b needs 40s . when i use @FeignClient for ms-a to call ms-b , it always call twice even use Retryer.NEVER_RETRY. the version is Camden.SR5 . LoadBalancedRetryPolicyFactory was set to LoadBalancedRetryPolicyFactory.NeverRetryFactory() that did also .
Please give a help.

**Comment by wangfeishsh** [comment]
I have solve it . just config the ribbon properties.

**Comment by sjqwork** [comment]
How to solve it?I have the same question!

**Comment by ryanjbaxter** [comment]
See http://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#_configuration

**Comment by sjqwork** [comment]
I have solve it,thank you!
