### ISSUE TITLE
Can Eureka-Server dashboard  show registered services list?

### ISSUE THREAD

**Issue by andChow** [spring-cloud/spring-cloud-netflix#1806]
I can't get any register services infomation In Eureka-Server dashboard 
The same to Spring Cloud Dashboard 。

####  picture
[pic link](https://raw.githubusercontent.com/paulc4/microservices-demo/master/dashboard.png)

**Comment by ryanjbaxter** [comment]
Please provide more information about the problem.  The picture shows one service, `accounts-service` registered with Eureka.

**Comment by andChow** [comment]
@ryanjbaxter I think accounts-service as a service provider，We want to know the specific interface defined in the provider.

**Comment by ryanjbaxter** [comment]
This is still not enough information to help you.  Provide more information including errors and sample code that reproduces the issue you are seeing.

**Comment by andChow** [comment]
@ryanjbaxter 
# Service Register
I registered _springcloud-register_ service  At Eureka Server. The code such as
```
@SpringBootApplication
@EnableDiscoveryClient
public class SpringcloudRegisterApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringcloudRegisterApplication.class, args);
	}
}

@RestController
public class ComputeController {
    private final Logger logger = LoggerFactory.getLogger(ComputeController.class);

    @Autowired
    private DiscoveryClient discoveryClient;

    @RequestMapping(value = "/add")
    public Integer add(Integer a, Integer b) {
        ServiceInstance instance = discoveryClient.getLocalServiceInstance();
        Integer r = a + b;
        logger.info("/add, host:" + instance.getHost() + ", service_id:" + instance.getServiceId() + ", result:" + r);
        return r;
    }
}
````
# Requirement
I hope get _add_ action infomation in Eureka dashboard.

**Comment by spencergibb** [comment]
That's not supported.
