### ISSUE TITLE
Upgrade eureka to version 2

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#181]
This is a non-trivial upgrade

**Comment by krosangit** [comment]
+1

This could potentially solve Jboss-integration issues.

[Tomasz from Netflix commented on such an integration issue that Eureka v2 might have a lot of fixes.](https://groups.google.com/d/msg/eureka_netflix/4wXYSVDbvzs/Du4xJmfYT0EJ)

**Comment by abaculus** [comment]
+1

New REST endoint for deleting 'overridestatus' https://github.com/Netflix/eureka/issues/717
