### ISSUE TITLE
[Zuul] Custom RequestContext

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-netflix#1812]
I have encountered multiple times that custom properties are put into RequestContext by spring-cloud-netflix-core. For example, PreDecorationFilter:
```
ctx.put("requestURI", route.getPath());
ctx.put("proxy", route.getId());
ctx.put("retryable", route.getRetryable());
```
and so on. 
RequestContext class gives an ability to extend it and add custom methods, so that API of this class would be more readable.
We could create something like:
```
public class CustomRequestContext extends RequestContext {

    protected static Class<? extends RequestContext> contextClass = SmartRequestContext.class;
    private static final String PROXY = "proxy";// This attribute is set in PreDecorationFilter and is equal to routeId
    private static final String SERVICE_ID = "serviceId";

    public String getProxy() {
        return (String) get(PROXY);
    }
    
    public void setProxy(String proxy) {
        set(PROXY, proxy);
    }

    public String getServiceId() {
        return (String) get(SERVICE_ID);
    }
...
}
```
What do you think? Thanks.

**Comment by tmack8001** [comment]
I would like to see this as well as we ourselves are extending the context to get similar API like structure to our extended context internally.

**Comment by spencergibb** [comment]
In Dalston I put all of the keys in one class.

**Comment by Aloren** [comment]
@spencergibb could you please point to commit? Thanks

**Comment by spencergibb** [comment]
6df7190472e1e56890351134164dd1336f4da411

**Comment by Aloren** [comment]
@spencergibb Still it doesn't give a nice API of `RequestContext`. I think that keeping such keys (that is actually a part of requestContext) in external class is of course better than having magic words all over the code, but is still lacking typing and nice interface.

**Comment by holy12345** [comment]
I have been concerned about this issue, there are updates?

**Comment by ryanjbaxter** [comment]
If there were updates they would be posted here

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
