### ISSUE TITLE
New annotation @GetMapping / @PostMapping ... not supported in spring-cloud in a @FeignClient

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-netflix#1813]
New annotation @GetMapping / @PostMapping ... not supported in spring-cloud in a @FeignClient

Don't hesitate if it is not clear?

**Comment by spencergibb** [comment]
This is a duplicate, search for get mapping in the closed issues to find.

**Comment by ryanjbaxter** [comment]
#1201

**Comment by alexandrenavarro** [comment]
Sorry for duplicate.
