### ISSUE TITLE
Question : What is the integration of Feign / spring-cloud-* with spring-reactive planned?

### ISSUE THREAD

**Issue by alexandrenavarro** [spring-cloud/spring-cloud-netflix#1814]
Question : What is the integration of Feign / spring-cloud-* with spring-reactive planned?

It should be great to use the Mono<MyObject> findMyObject(); or Flux<MyObject> findMyObject(); in my @FeignClient (or equivale like @FeignReactiveClient) as we use today my feign client.
Is it planned or there is some reflexion on it?

Thanks in advance, it is just a question but there is a lot of buzz around spring-reactive in spring 5.0, I want to know what is your plan. Don't hesitate if the question is not clear.

**Comment by spencergibb** [comment]
Feign would need a redesign since it is currently synchronous.

**Comment by spencergibb** [comment]
See below for a retrofit client https://github.com/spring-cloud-incubator/spring-cloud-square/blob/master/spring-cloud-square-retrofit/src/test/java/org/springframework/cloud/retrofit/RetrofitClientReactorTests.java

**Comment by alexandrenavarro** [comment]
Thanks for your quick answer as always. The retrofit does support yet eureka or/and ribbon to find url from name in a eureka server?

**Comment by spencergibb** [comment]
Yes it does. The is also the new Spring WebClient.

**Comment by alexandrenavarro** [comment]
Thanks for tour answer.
