### ISSUE TITLE
where is project spring-cloud-build

### ISSUE THREAD

**Issue by pichengchao** [spring-cloud/spring-cloud-netflix#1819]
Master project spring-cloud-netfix has dependency parent spring-cloud-netfix in pom.xml,but can not find it in all of them

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-build and builds go here https://repo.spring.io/

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
