### ISSUE TITLE
Use a Virtual Eureka Address when registering the services

### ISSUE THREAD

**Issue by sri420** [spring-cloud/spring-cloud-netflix#1821]
We want use more than one Eureka Instances for high availability.

As per the docs, I see we need to provide the Eureka URL of the instances to every service on startup.
The service will register on the first available eureka instance only but the registration info will be replicated from one eureka instance to the peer eureka instance.

This seems to be a dependency on the number of eureka instances with every service. 

Is there any mechanism to provide a virtual eureka address to every service, instead of restarting every service by providing the updated eureka server list, whenever we want to add one more eureka peer instance. The virtual eureka address should map to one or more actual eureka urls.

**Comment by spencergibb** [comment]
No there isn't. See https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2 for examples of configuring for EC2.

**Comment by sri420** [comment]
Is there a way to simulate the behavior for non-cloud environment.

**Comment by spencergibb** [comment]
Simulate what behavior? Eureka isn't built to run behind a load balancer. Each client needs to know about the whole cluster.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
