### ISSUE TITLE
Service is not getting unregistered in eureka peer instance when it is down

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-netflix#1822]
We have 2 peer instances of eureka running our environment.

At Startup,we are registering the service by providing only one of the eureka peer instance.

The service registration in the first eureka peer is also getting replicated to second eureka peer.

When the first eureka peer is down, the service is throwing exceptions because it cannot connect to the eureka instance.

Now, when the service is down, the service is not getting unregistered in the second eureka peer.

Can you please let us know how we can have it unregistered in eureka peer.

**Comment by spencergibb** [comment]
In normal configurations, eureka clients know about the cluster and connect to other configured eureka servers. https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2

**Comment by bsridhar123** [comment]
Thanks for your response. Just wanted to confirm if the solution is only for EC2 or even for non-cloud environments.

We currently, have a non-cloud environment with eureka instance peers, so wanted to know if its applicable there too.

**Comment by spencergibb** [comment]
The point of that link is an example. But clients need to know about the whole cluster.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
