### ISSUE TITLE
Support multiple urls in @RequestMapping on FeingClient

### ISSUE THREAD

**Issue by leonardovillela** [spring-cloud/spring-cloud-netflix#1826]
I am using Feign for requesting a MicroService route, but some params of the path variable are optional,  i'm trying to define, multiple values for path value to handle with optional parameters, but when I do this I get an exception described below, i think this is a great and helpful feature when interfaces have optional parameters in path.

Spring Cloud Version: `org.springframework.cloud:spring-cloud-dependencies:Brixton.SR6`

Exception Recived with Mutiple paths: 
```
Caused by: java.lang.IllegalStateException: Method createDocument can only contain at most 1 value field. Found: [/fields/{fieldName}/documents/create, grids/{gridIdentifier}/fields/{fieldName}/documents/create]
```

Feign client method definition:  
```java
@RequestMapping(
    method = POST,
    path = { "/fields/{fieldName}/documents/create", "grids/{gridIdentifier}/fields/{fieldName}/documents/create"},
    produces = APPLICATION_JSON_UTF8_VALUE,
    consumes = APPLICATION_JSON_UTF8_VALUE
  )
  ResponseEntity<ResourceContent<Document>> createDocument(
    @PathVariable("fieldName") String fieldName,
    @PathVariable(value = "gridIdentifier", required = false) String gridIdentifier,
    @RequestBody CreateDocument createDocument
  );
```

**Comment by spencergibb** [comment]
Feign is a client. It can only use one path. We discourage sharing interfaces between server and client. What would be the use for having two values for `path`?

**Comment by leonardovillela** [comment]
Because in server this route have an optional param `gridIdentifier`, and the rest of its parameters are the same.

**Comment by spencergibb** [comment]
Again:

> We discourage sharing interfaces between server and client.

Which one would the client choose?

**Comment by leonardovillela** [comment]
In case the optional parameter was sent, the path that makes use of it would be chosen, which is defined in @PathVariable, in the example above that I placed if the `gridIdentfier` parameter was sent the route that makes use of it would be chosen.

**Comment by spencergibb** [comment]
There could be multiple urls with `gridIdentfier` in them, which to choose? This is a client, not a server. You need to make two separate methods in your feign interface.

**Comment by leonardovillela** [comment]
Why you discourage sharing interfaces between server and client?

**Comment by zsalab** [comment]
> There could be multiple urls with `gridIdentfier` in them, which to choose? This is a client, not a server. You need to make two separate methods in your feign interface.

I do not get your point, I think this is a really wise idea to map and use same controller / client for multiple URLs like if a resource mapped to multiple owners (yes I know many people thinks that bad design, but nobody had a good reason).
