### ISSUE TITLE
Investigate lowering timeout values in AbstractLoadBalancingClient

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#1827]
When used with zuul/hystrix this can lead to undesired behaviour. See #1772

**Comment by ryanjbaxter** [comment]
Is it better to lower the timeouts for Ribbon or increase the timeouts for Hystrix?  I am sure an argument can be made for both.

**Comment by spencergibb** [comment]
A few comments (https://github.com/spring-cloud/spring-cloud-netflix/issues/1772#issuecomment-290522259) suggest the read timeout was 5 seconds. Seems highish.

**Comment by ryanjbaxter** [comment]
The total timeout we are looking at is probably the connect timeout and read timeout, agree?  If so then we would need to lower those to both 500ms (maybe less?) to match the default hystrix timeout of 1000ms

**Comment by ryanjbaxter** [comment]
@spencergibb ping^^^

**Comment by spencergibb** [comment]
It probably makes sense to have sane defaults (whatever they are). What would it look like?

**Comment by ryanjbaxter** [comment]
I guess that depends on your definition of "sane".  I would saw 1 sec for both the connect and read timeouts is reasonable.  But then that exceeds the default Hystrix timeout of 1 second.

**Comment by spencergibb** [comment]
SGTM
