### ISSUE TITLE
FeignClient how to use SEMAPHORE as strategy of hystrix 

### ISSUE THREAD

**Issue by mrvon2015** [spring-cloud/spring-cloud-netflix#1833]
if ribbon can do it 
@HystrixCommand(fallbackMethod = "getFallback", commandProperties = @HystrixProperty(name = HystrixPropertiesManager.EXECUTION_ISOLATION_STRATEGY, value = "SEMAPHORE"))
	
if FeignClient  how to do?

**Comment by spencergibb** [comment]
Using `application.properties` file.

**Comment by mrvon2015** [comment]
i try to do like this 
hystrix.command.notificationstatusmessagereceiver.execution.isolation.strategy=SEMAPHORE
 
Seems to have no effect

**Comment by spencergibb** [comment]
Likely you have the wrong name.

**Comment by mrvon2015** [comment]
thanks，it is ok
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
In view of the global configuration
but，if I want to set up separately for FeignClient ，how to do it？

**Comment by spencergibb** [comment]
you need the name generated by feign. https://github.com/OpenFeign/feign/tree/master/hystrix#group-and-command-keys

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
