### ISSUE TITLE
[Question] Is there a roadmap for Spring Cloud?

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#184]
I am wondering if there is a roadmap for this project.
Phil Webb mentioned in an interview on infoq.com that Spring Cloud  will be suported heavily by Pivotal. 

What are the plans?

**Comment by spencergibb** [comment]
There is currently no public road map beyond github issues and milestones.  I don't think we're opposed to one.  I'll bring it up with the team.

**Comment by aivans** [comment]
Thanks Spencer

It would be good to have something public such that I can point it to the management.
