### ISSUE TITLE
Allow option to customize pathMatcher in SimpleRouteLocator

### ISSUE THREAD

**Issue by zhangxiudong** [spring-cloud/spring-cloud-netflix#1853]
`SimpleRouteLocator` `pathMatcher(defalut AntPathMatcher)` why did not provide the get method, I want to set `caseSensitive` false, but I  can not get `pathMatcher`

**Comment by ryanjbaxter** [comment]
Sorry I am not understanding what the issue is, can you perhaps elaborate a bit more on what you are trying to do and what is not working?

**Comment by spencergibb** [comment]
It would probably be by a setter not a getter.

**Comment by zhangxiudong** [comment]
I would like `zuul routing zuul.routes.*.path` not case sensitive.

So set the `ZuulHandlerMapping` `PathMatcher` (`AntPathMatcher` extend form `AbstractHandlerMapping`)  `caseSensitive`  `false`,  `ZuulHandlerMapping` can maping to `ZuulController`.
 `PreDecorationFilter` `RouteLocator` (`SimpleRouteLocator`) `getMatchingRoute` method to get the `Route` set `PathMatcher` (`AntPathMatcher` ) ` caseSensitive` false too, 
but `SimpleRouteLocator` no getter or setter

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
