### ISSUE TITLE
Matrix Parameters are being removed(stripped) from the request url in zuul

### ISSUE THREAD

**Issue by rameshsunkara** [spring-cloud/spring-cloud-netflix#1856]
I am using Matrix  Parameters in my request, but they are being stripped before being forwarded.

URL: http://localhost:8080/api/global/account;login=testme/localAcc

Expected:http://localhost:8080/api/account;login=testme/localAcc
Actual:     http://localhost:8080/api/account/localAcc

**Comment by spencergibb** [comment]
I assume you are using zuul? What version are you using?

**Comment by rameshsunkara** [comment]
Yes I am using Zuul (sping-cloud-starter-zuul-1.2.2)

zuul:
    debug:
        request: true

    routes:
        local:
            path: /local/**
            url: forward:/
        apiGlobal:
            path: /api/global/**
            url: ${app.global.baseUrl}/api
        default:
            path: /**
            url: ${app.remote.baseUrl}

**Comment by spencergibb** [comment]
Matrix params are opt-in. Try setting `zuul.removeSemicolonContent=true`

**Comment by rameshsunkara** [comment]
Thanks it helped.
I couldn't find the docs for the properties listed in the below java file. Please point me if its documented.
[https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ZuulProperties.java](url)

**Comment by spencergibb** [comment]
It is missing.

**Comment by spencergibb** [comment]
Actually it is here http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_appendix_compendium_of_configuration_properties

`zuul.remove-semicolon-content`

**Comment by rameshsunkara** [comment]
After the changes mentioned above in my Zuul configuration, I see in the logs that request sent does have the Matrix Parameters :
```
org.apache.http.wire: http-outgoing-20 >> "DELETE /api/account;login=testme/localAcc HTTP/1.1[\r][\n]"
```
**But by the time it reaches the forwarded component (ie., global in this example) the request doesn't have them.**

I ruled out the case where forwarded component (global) might be stripping the Matrix Parameters before serving it by sending the request directly to global component using REST client. (Sending request directly to global component worked)

I am using tomcat embedded as container.

**Comment by spencergibb** [comment]
@rameshsunkara at that point it is no longer a spring cloud issue, is it?

**Comment by rameshsunkara** [comment]
I couldn't rule out it being a spring cloud issue because, the request sent directly to my global component works.

I am still investigating and will update here, but the probable reason is because of the request being wrapped in ForwardedHeaderFilter (https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java)

Do you know if I can configure anything in zuul to exclude x-forwarded-host, Forwarded etc fields in the header of the request being forwarded(routed) by zuul

**Comment by spencergibb** [comment]
The `X-Forwarded-*` headers are standard behavior for proxies and can be disabled by setting `zuul.addProxyHeaders=false`.

**Comment by rameshsunkara** [comment]
Yup that solved this issue. Now I can go figure out how to make it work with proxy headers.
Thanks a lot @spencergibb

**Comment by sirianni** [comment]
To wrap up this thread...

We noticed that Spring's `ForwardedHeaderFilter` was stripping the semicolons via its use of `UrlPathHelper`. We worked around it by setting `UrlPathHelper.removeSemicolonContent` to `false`.

Since `ForwardedHeaderFilter.pathHelper` is a private field we needed to use reflection to access it.

**Comment by tjuchniewicz** [comment]
`zuul.remove-semicolon-content: false` does not work for `jsessionid` because it's removed always. See [UrlPathHelper.removeSemicolonContent()](https://github.com/spring-projects/spring-framework/blob/79d30d8c8a5a2a5725d22a0e63bdefef522df8ca/spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java#L486)
