### ISSUE TITLE
Making POST on 'refresh' permamently deregisters the service from Eureka

### ISSUE THREAD

**Issue by AmberHuang05** [spring-cloud/spring-cloud-netflix#1857]
I have config-server registered as a eureka-server client, another config-client also registered as a eureka-server client, config-server using native call to load the local file config properties. Each time, when I POST a /bus/refresh call to config-server, the config-client get the updated properties but immediately they both get permanently unregistered with Eureka-server unless we restarted them.  by the way, the config-server and config-client both listened a local rabbitmq server. 

I see this issue in almost the latest version which have the dependency management like below

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
					<version>Dalston.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

Also tried the version Dalston.RC1, no luck
I also see a lot of people talked about this issue before, like 
https://github.com/spring-cloud/spring-cloud-netflix/issues/1652
or spring-cloud/spring-cloud-netflix#421
They all marked as fixed. Which version has the fix in it?

**Comment by AmberHuang05** [comment]
Eureka-server config:
server.port=1111
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/

Config-server config:
spring.application.name=config-server
server.port=7001
eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/
spring.profiles.active=native
management.security.enabled=false
security.basic.enabled=false

config-client config: in bootstrap.properties
spring.application.name=ahspace
server.port=7002

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.serviceId=config-server
spring.cloud.config.profile=dev
spring.cloud.config.failFast=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.security.enabled=false
security.basic.enabled=false

Three of apps used the basic and only necessary dependencies. used the same dependency management as above.

**Comment by AmberHuang05** [comment]
Three apps used the parent as below:
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath /> 
	</parent>

For Eureka server: only one dependency:
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
</dependency>

For Config server: only has these three dependencies
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>

For Config client: only has these three dependencies
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-amqp</artifactId>
		</dependency>
	</dependencies>

**Comment by spencergibb** [comment]
@AmberHuang05 if you'd like us to look further, please provide a project on github or zipped up, not a partial project in badly formatted comments.

**Comment by AmberHuang05** [comment]
https://github.com/AmberHuang05/config-setting
have 3 zip files. Are they enough? Also I set up a local rabbitmq server, all default installation and setting
step1: start the rabbitmq server
step2: start the discovery-server
step3: start the config-server
step4: start the config-client
step5: check the http://localhost:1111, eureka monitor page, we can see both config-server and config-client instances were registered. 
step6: send a POST request to config-server, like curl -X POST http://localhost:7001/bus/refresh
step7: go back to http://localhost:1111 page, see config-server and config client instances were deregistered permanently from eureka server.

**Comment by ryanjbaxter** [comment]
My guess is this is some kind of weird timing issue.  If I start setting breakpoints and debugging through the code, I will notice the server will successfully reregister with the server.  However without the breakpoint the reregistration does not happen correctly.

**Comment by ryanjbaxter** [comment]
The problem appears to be that during the refresh event the `CloudDiscoveryClient` is destroyed and the `shutdown` method in Eureka client is called.  This unregisters the client from Eureka but since the `EurekaClient` bean is used anywhere after the refresh event the `EurekaClient` bean is not recreated so we do not reregister the client.  We need to force the `EurekaClient` to be recreated in order to make sure the client is reregistered.

**Comment by AmberHuang05** [comment]
I just uploaded a new zip in https://github.com/AmberHuang05/config-setting
This sample did not use rabbitmq or message bus. It only contains Eureka server, config server and config client, both config-server and config-client registered to Eureka server and after we send out a refresh post message to config client instance, the config-client instance was deregistered to Eureka server permanently

**Comment by taoyingqi** [comment]
Waiting for fix

**Comment by spencergibb** [comment]
There's currently no timeline for Dalston.SR1

**Comment by abc549825** [comment]
got the same issue, waiting for the fix

**Comment by yangy608** [comment]
Waiting for fix

**Comment by spencergibb** [comment]
Should be this week (if not, next).

**Comment by brahim-ghazi** [comment]
Waiting for fix

**Comment by GerardMasip** [comment]
Waiting for fix too. Any update or release date?

**Comment by GerardMasip** [comment]
@ryanjbaxter Thanks for the info

**Comment by z07cj013** [comment]
@ryanjbaxter Thanks, it's fixed.

**Comment by ityouknow** [comment]
yes! Thanks alll, it's fixed, i used recent pom.

`<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Dalston.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>`

**Comment by sunnykaka** [comment]
I'm still use Dalston.Release version. 
How to fix it in my project? Upgrade is not an option .

**Comment by spencergibb** [comment]
Then you won't get the fix

**Comment by sunnykaka** [comment]
@spencergibb 
You are right, I'll try to upgrade version to SR4.

**Comment by ryanjbaxter** [comment]
If you think there is a bug, please open another issue
