### ISSUE TITLE
@FeignClient configuration do not take effect

### ISSUE THREAD

**Issue by xj198806** [spring-cloud/spring-cloud-netflix#1862]
i use different load balance IRule but aways default RoundRobinRule 
my code  https://github.com/xj198806/feign-test.git

Help me see what the problem thks

**Comment by ryanjbaxter** [comment]
`IRule` is a Ribbon routing configuration for a Feign Client configuration.
http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_customizing_the_ribbon_client

You can also customize the load balancer rule using properties.
http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_customizing_the_ribbon_client_using_properties

**Comment by xj198806** [comment]
actually i want to know why configuration do not take effect in the @FeignClient
![default](https://cloud.githubusercontent.com/assets/12165694/25076031/f20edd52-234f-11e7-99bd-e373d116f0fd.png)
i  put the configuration  in a separate, non-overlapping package, or specify the packages to scan explicitly in the @ComponentScan but it do not take effect.
https://github.com/xj198806/feign-test

![default](https://cloud.githubusercontent.com/assets/12165694/25076602/dfbf60ae-2354-11e7-8abf-4179f597618d.png)
the Contract  do not take effect. i am confused

**Comment by ryanjbaxter** [comment]
Try adding `@ComponentScan( basePackageClasses = {RemoteAddConfiguration.class})` to your application class.

**Comment by xj198806** [comment]
![default](https://cloud.githubusercontent.com/assets/12165694/25111360/1c47276e-241d-11e7-9df8-c2672426e4dc.png)
you mean like this?

if i do so, It does not work. if i add @ComponentScan( basePackageClasses = {RemoteAddConfiguration.class}) ,i only get one component with type RemoteAddConfiguration. and my @RestController does not work too.

**Comment by ryanjbaxter** [comment]
When I did this I at least saw `RemoteAddConfiguration.feignContract` being called.  What do you mean you only get one component with type `RemoteAddConfiguration`?  Can you perhaps simplify the sample application you provided so it does not require Consul etc?  That would make it much easier for me to run and investigate the problem.

**Comment by xj198806** [comment]
i find it work if it does not require Consul etc, so i guess it is something wrong with consul.

**Comment by spencergibb** [comment]
You're using an old version of spring cloud, can you try with `Dalston.RELEASE` or `Camden.SR6`?

**Comment by xj198806** [comment]
i tried this two version but seems like the same with Brixton.SR5.

**Comment by ryanjbaxter** [comment]
I think I narrowed down the problem now.  It has to do that both `RemoteMultiplyService` and `RemoteAddService` are using the same value for `name` in their Feign Client annotations.  When we register the Feign Clients we register the bean definition with the same name for both clients.
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsRegistrar.java#L376

Combining the two clients can solve the problem.  If you need them to be separate you can try defining the clients [manually](http://cloud.spring.io/spring-cloud-static/Camden.SR6/#_creating_feign_clients_manually).

**Comment by xj198806** [comment]
ok i think i know. tks~ : )

**Comment by tonyfarney** [comment]
I was with the same problem: configuration not taking effect. Thanks to @ryanjbaxter I figured out there was other clients using the same name. That was causing the problem.
