### ISSUE TITLE
Zuul: filters registered in FilterRegistry under the wrong name

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#1866]
`ZuulFilterInitializer` registers `ZuulFilters` in Netflix's `FilterRegistry` under their *bean name* whereas Netflix uses their *simple classname*.

This is causing issues/incompatibilities at various places where Netflix code refers to filters by their name like in `com.netflix.zuul.context.RequestContext.addFilterExecutionSummary(String,String,long)`. The name given as argument is the classname, and cannot be used to lookup the corresponding filter instance in the registry.

**Comment by spencergibb** [comment]
Can you provide a concrete example of where this causes problems? `addFilterExecutionSummary` just appends information to a `StringBuilder`.

**Comment by brenuart** [comment]
The current implementation of `RequestContext.addFilterExecutionSummary()` construct a summary of the filter execution. That summary refers to filters with a name different than what the rest of the application uses.

Another example is `BasicFilterUsageNotifier` recording filter execution count. Again the filter are identified by their class name instead of bean name.

These are the two examples I can think of atm but I'm pretty confident there are others.

At the end with have two distinct naming strategy to refer to the same filters - which is rather confusing.

I don't have any concrete example of these two naming strategies causing issue in the current code base except in our own code base. To avoid the confusion we overwrote the filter registration.

**Comment by spencergibb** [comment]
Bean name is unique where simple class name is not.

**Comment by brenuart** [comment]
Correct.
The bottom line is simply _don't expect `RequestContext` or `BasicFilterUsageNotifier` to report filter information using the name you used to register the filter_. Instead, Zuul infrastructure will always use the filter class name.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
