### ISSUE TITLE
Zuul: Support for ";jsessionid=ID" in URL

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#1868]
I'm trying to access legacy service through Zuul proxy but it looks like `;jsessionid=<ID>` is removed from URL when forwarding to the target service. This is removed in [PreDecorationFilter](https://github.com/spring-cloud/spring-cloud-netflix/blob/d412df5883ad8bdbe18def674d4af550e54338c0/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java#L112) by calling `this.urlPathHelper.getPathWithinApplication(ctx.getRequest());` which calls `UrlPathHelper.getRequestUri()` that cuts off strings like ";jsessionid".

Bug? Any possible workarounds? I know that jsessionid parameter is legacy stuff but how to support this case for legacy apps?

**Comment by ryanjbaxter** [comment]
@tjuchniewicz could this possibly be a duplicate of #1856?

**Comment by tjuchniewicz** [comment]
Thanks for pointing this issue and probably the solution! Closing as duplicate.

**Comment by tjuchniewicz** [comment]
`zuul.remove-semicolon-content: false` does not work for `jsessionid` because it's removed always. See [UrlPathHelper.removeSemicolonContent()](https://github.com/spring-projects/spring-framework/blob/79d30d8c8a5a2a5725d22a0e63bdefef522df8ca/spring-web/src/main/java/org/springframework/web/util/UrlPathHelper.java#L486)

My workaround for `jsessionid` is:
1. disable default filter: `zuul.PreDecorationFilter.pre.disable: true`
2. create extension of `UrlPathHelper`:
```java
/**
 * Like {@link UrlPathHelper} but with disabled code that removes ;jsessionid matrix parameter.
 */
public class MyUrlPathHelper extends UrlPathHelper {

    /**
     * Remove ";" (semicolon) content from the given request URI if the
     * {@linkplain #setRemoveSemicolonContent(boolean) removeSemicolonContent}
     * property is set to "true". Note that "jssessionid" is not removed as in {@link UrlPathHelper}.
     * @param requestUri the request URI string to remove ";" content from
     * @return the updated URI string
     */
    @Override
    public String removeSemicolonContent(String requestUri) {
        return shouldRemoveSemicolonContent() ? super.removeSemicolonContent(requestUri) : requestUri;
    }
}
```
3. use `PreDecorationFilter` source code and create new filter that uses `MyUrlPathHelper` instead of `UrlPathHelper`
4. Register new filter:
```java
@Bean
public MyPreDecorationFilter myPreDecorationFilter(RouteLocator routeLocator, ServerProperties server,
            ZuulProperties properties, ProxyRequestHelper proxyRequestHelper) {
      return new MyPreDecorationFilter(routeLocator, server.getServletPrefix(),
              properties, proxyRequestHelper);
}
```
