### ISSUE TITLE
Sidecar configuration for https

### ISSUE THREAD

**Issue by sureshkrishnamoorthy** [spring-cloud/spring-cloud-netflix#1869]
We were trying to secure the communication between sidecar and node js. While registering sidecar with eureka we have passed the below properties
```
--server.port=23456
--sidecar.port=12345
--eureka.instance.nonSecurePortEnabled=false 
--eureka.instance.securePortEnabled=true 
--eureka.instance.securePort=12345
```
When we pass the **eureka.instance.securePort** values as server.port (similar to all other service registration with eureka) zuul  is not forwarding the request to node js (via sidecar), but when we changed that to sidecar.port(ie node js port) it is working. Please let us know if this is a correct configuration.

**Comment by sureshkrishnamoorthy** [comment]
We are having Eureka, Zuul, Sidecar and Node JS in our environment. Node JS and Sidecar are running in the same machine and all the communication are secured(SSL) .
We are using spring boot version 1.4.5 and spring cloud version camden SR6.
We are trying to access the Node JS resources via zuul and Sidecar. 

When we try to access the sidecar from zuul, sidecar is not forwarding the request to Node JS (eureka.instance.securePort value for sidecar as server.port ie Sidecar service port )

After changing this eureka.instance.securePort value to Node JS server port (7071), it is working fine. 

We are seeking your inputs to confirm if this configuration is correct for production environment.

**Comment by spencergibb** [comment]
Any external client of your nodejs service should contact it directly. Sidecar doesn't proxy traffic TO the nodejs app. So the securePort should be the port of the nodejs server.
