### ISSUE TITLE
/hystrix.stream not discoverable by turbine if management.context-path is not /

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#187]
Probably a problem if management port is set as well.

http://stackoverflow.com/questions/28201779/hystrix-stream-and-management-context

**Comment by spencergibb** [comment]
I was thinking of using eureka metadata

**Comment by dsyer** [comment]
Is there any reason /hystrix.stream needs to be an `MvcEndpoint`? There is still the same problem on the server if it is a normal `Servlet` or `@RequestMapping` with a variable path, but if it was a plain `Servlet` we could at least make the path always the same.

**Comment by spencergibb** [comment]
I guess it doesn't need to be an mvc endpoint.  If they change the `servletContext` from `/` it breaks too.

**Comment by dsyer** [comment]
If it was a `Servlet` though then the path only depends on the application context path ("/" by default also). That's the best we can do without making any changes to the sever, I guess?

**Comment by spencergibb** [comment]
that minimizes the changes
