### ISSUE TITLE
Bug fix in Netflix / zuul not in spring-cloud-starter-zuul... hoping it can be added.

### ISSUE THREAD

**Issue by KeiichiTheOtaku** [spring-cloud/spring-cloud-netflix#1871]
Hello

There is a bug fix in Netflix / zuul that I'm interested in, but it doesn't appear to be available in spring-cloud-netflix (at least, not in the version we use or any other more recent version that I can find). 

The version of spring-cloud-starter-zuul we use is:
`org.springframework.cloud:spring-cloud-starter-zuul:1.2.6.RELEASE`
... which uses:
`com.netflix.zuul:zuul-core:1.3.0`

Secifically, [#127](https://github.com/Netflix/zuul/issues/127) and [#327](https://github.com/spring-cloud/spring-cloud-netflix/issues/327) discuss the issue, and the fix was added to zuul-netflix as part of [this change](https://github.com/Netflix/zuul/commit/73d86bf3a13455ea48650bcf8bc793b34e5033e6). It was not added to zuul-core, however.

It looks like the fix was present in [this version of RibbonCommand.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/2ba5c4b9ecd6659791fdfb19ab51a86b9670797c/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/RibbonCommand.java) in spring-cloud-netflix, but that file is not present in the version we use. It also looks like the RibbonCommand.java file was replaced with [RestClientRibbonCommand.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/v1.2.6.RELEASE/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/RestClientRibbonCommand.java) in the `1.2.6-RELEASE` version, which is missing the fix.

Please let me know if anything I've said is inaccurate.

Is there a current version of spring-cloud-starter-zuul which contains the fix?
If not, can it be added?

**Comment by ryanjbaxter** [comment]
It looks like the fix is present in `AbstractRibbonCommand`
https://github.com/spring-cloud/spring-cloud-netflix/blob/f3deb04521c8c0a0b6d9923b0b37d8673cb7fa0b/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/support/AbstractRibbonCommand.java#L112

**Comment by KeiichiTheOtaku** [comment]
Hm... so it is. Thanks for finding that, ryanjbaxter.

Which begs the question, then: Why are we still seeing the CLOSE_WAIT connection leak issue using a version of Zuul which has the fix.

We'll pursue further investigation on our side for now, having verified where we stand re: the fix.

Thanks again for your help.

**Comment by spencergibb** [comment]
So #1372 deals with that and is in the Dalston release (1.3.0.RELEASE) and 1.2.7.BUILD-SNAPSHOT

**Comment by KeiichiTheOtaku** [comment]
Thanks much Spencer.

Time to try another upgrade, then.

**Comment by spencergibb** [comment]
if you try the 1.2.7 snapshots and that works, we could work on prioritizing releasing 1.2.7

**Comment by KeiichiTheOtaku** [comment]
Cool, I appreciate that.

I'll respond again when we've tested the snapshot version and know more.

Thanks again.

**Comment by KeiichiTheOtaku** [comment]
No luck.

Running Zuul with Dalston and spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT did not resolve the problem with CLOSE_WAIT connections eventually tipping over the app instance, for us.

**Comment by ryanjbaxter** [comment]
> Running Zuul with Dalston and spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT did not resolve the problem with CLOSE_WAIT connections eventually tipping over the app instance, for us.

It sounds like you used both `Dalston` and `spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT`, is that correct?  `spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT` is part of the `Camden` release train.  It should be either or.  You can try Dalston.RELEASE or Camden.BUILD-SNAPSHOT.

**Comment by KeiichiTheOtaku** [comment]
My mistake.

Thank you for clarifying.  I'll give it another shot.

**Comment by KeiichiTheOtaku** [comment]
One more update:

Running with `Camden.SR6` and `spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT`, we still encountered the problem where the instance became unresponsive after some time.

The number of long-running CLOSE_WAIT connections the instance accumulated before becoming unresponsive increased significantly, as did the amount of time it took to get there, but the problem reoccurred. On an instance using our previous configuration, it usually takes around 50 connections and about an hour to tip over; the updated test instance plateaued around 230 long-running connections, and took most of the weekend to see the issue.

**Comment by ryanjbaxter** [comment]
Can you show us your `gradle.build` file?

**Comment by KeiichiTheOtaku** [comment]
Is there a specific subsection I can post?
We have some intellectual property concern posting the whole thing...

**Comment by ryanjbaxter** [comment]
I just want to see how you have setup your dependencies.

**Comment by KeiichiTheOtaku** [comment]
ok

Let me know if this isn't sufficient info...

<details><summary>build.gradle</summary><p>
buildscript {<br>
  ext {<br>
    springBootVersion = '1.4.5.RELEASE'<br>
  }<br>
<br>
  repositories {<br>
    maven { maven url }<br>
    maven { maven url }<br>
  }<br>
<br>
  dependencies {<br>
    classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"<br>
    classpath "io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE"<br>
    classpath 'com.netflix.nebula:gradle-ospackage-plugin:3.5.0'<br>
    classpath 'pl.allegro.tech.build:axion-release-plugin:1.4.1'<br>
  }<br>
}<br>
<br>
apply plugin: 'java'<br>
apply plugin: 'eclipse'<br>
apply plugin: 'org.springframework.boot'<br>
apply plugin: 'maven'<br>
apply plugin: "io.spring.dependency-management"<br>
apply plugin: 'nebula.ospackage'<br>
apply plugin: 'pl.allegro.tech.build.axion-release'<br>
<br>
dependencyManagement {<br>
     imports {<br>
       mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Camden.SR6"<br>
     }<br>
}<br>
<br>
sourceCompatibility = 1.8<br>
<br>
repositories {<br>
  maven { url 'http://repo.spring.io/milestone' }<br>
  maven { url 'http://repo.spring.io/snapshot' }<br>
  maven { maven url }<br>
  maven { maven url }<br>
  maven { maven url }<br>
}<br>
<br>
dependencies {<br>
  compile 'org.springframework.cloud:spring-cloud-starter-eureka'<br>
  compile 'org.springframework.cloud:spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT'<br>
  compile 'org.springframework.cloud:spring-cloud-starter-config'<br>
  compile 'org.springframework.boot:spring-boot-configuration-processor'<br>
  compile("org.springframework.boot:spring-boot-starter-web") { exclude module: "spring-boot-starter-tomcat" }<br>
  compile("org.springframework.boot:spring-boot-starter-jetty")<br>
  compile("org.springframework.boot:spring-boot-starter-actuator")<br>
<br>
  compile group: 'org.jolokia', name: 'jolokia-core', version: '1.3.3'<br>
  compile 'com.amazonaws:aws-xray-recorder-sdk-core:1.0.3-beta'<br>
  <br>
  compile "com.amazonaws:aws-java-sdk-s3:1.11.54"<br>
  compile "com.amazonaws:aws-java-sdk-core:1.11.54"<br>
<br>
  compile 'org.eclipse.jetty:jetty-jmx'  <br>
<br>
  compile group: 'commons-logging', name: 'commons-logging', version: '1.2'<br>
<br>
  testCompile group: "junit", name: "junit-dep", version: "4.10"<br>
  testCompile group: "org.mockito", name: "mockito-core", version: "1.10.19"<br>
  testCompile 'org.springframework:spring-test'<br>
}<br>
</p></details>

**Comment by ryanjbaxter** [comment]
I have little hope this will actually make a difference but I meant to use `Camden.BUILD-SNAPSHOT`.
```
imports {
mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Camden.BUILD-SNAPSHOT"
}
```

Then you wouldnt need to do 
`compile 'org.springframework.cloud:spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT'`

you should just need 
`compile 'org.springframework.cloud:spring-cloud-starter-zuul`

The BOM will pull in `1.2.7.BUILD-SNAPSHOT`.

**Comment by KeiichiTheOtaku** [comment]
Gotcha, I'll give that a shot.
Thanks again.

**Comment by KeiichiTheOtaku** [comment]
Ah, I do see a change in the zuul portion of the dependency tree after that change...

<details><summary>before</summary><p>
+--- org.springframework.cloud:spring-cloud-starter-zuul:1.2.7.BUILD-SNAPSHOT<br>
|    +--- org.springframework.cloud:spring-cloud-starter:1.1.9.BUILD-SNAPSHOT -> 1.1.8.RELEASE (*)<br>
|    +--- org.springframework.boot:spring-boot-starter-web:1.4.6.RELEASE -> 1.4.5.RELEASE (*)<br>
|    +--- org.springframework.boot:spring-boot-starter-actuator:1.4.6.RELEASE -> 1.4.5.RELEASE<br>
|    |    +--- org.springframework.boot:spring-boot-starter:1.4.5.RELEASE (*)<br>
|    |    \--- org.springframework.boot:spring-boot-actuator:1.4.5.RELEASE<br>
|    |         +--- org.springframework.boot:spring-boot:1.4.5.RELEASE (*)<br>
|    |         +--- org.springframework.boot:spring-boot-autoconfigure:1.4.5.RELEASE (*)<br>
|    |         +--- com.fasterxml.jackson.core:jackson-databind:2.8.7 (*)<br>
|    |         +--- org.springframework:spring-core:4.3.7.RELEASE (*)<br>
|    |         \--- org.springframework:spring-context:4.3.7.RELEASE (*)<br>
|    +--- org.springframework.cloud:spring-cloud-starter-hystrix:1.2.7.BUILD-SNAPSHOT -> 1.2.6.RELEASE<br>
|    |    +--- org.springframework.cloud:spring-cloud-starter:1.1.8.RELEASE (*)<br>
|    |    +--- org.springframework.cloud:spring-cloud-netflix-core:1.2.6.RELEASE (*)<br>
|    |    +--- org.springframework.cloud:spring-cloud-starter-archaius:1.2.6.RELEASE (*)<br>
|    |    +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    +--- com.netflix.hystrix:hystrix-metrics-event-stream:1.5.6<br>
|    |    |    +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    |    \--- com.netflix.hystrix:hystrix-serialization:1.5.6<br>
|    |    |         +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.7.5 -> 2.8.7<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.7.5 -> 2.8.7 (*)<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.7.5 -> 2.8.7<br>
|    |    |         +--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.7.5 -> 2.8.7<br>
|    |    |         |    \--- com.fasterxml.jackson.core:jackson-core:2.8.7<br>
|    |    |         \--- com.fasterxml.jackson.module:jackson-module-afterburner:2.7.5<br>
|    |    |              +--- com.fasterxml.jackson.core:jackson-core:2.7.5 -> 2.8.7<br>
|    |    |              \--- com.fasterxml.jackson.core:jackson-databind:2.7.5 -> 2.8.7 (*)<br>
|    |    \--- com.netflix.hystrix:hystrix-javanica:1.5.6<br>
|    |         +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |         +--- org.aspectj:aspectjweaver:1.8.6 -> 1.8.9<br>
|    |         +--- com.google.guava:guava:15.0 -> 18.0<br>
|    |         +--- commons-collections:commons-collections:3.2.2<br>
|    |         +--- org.apache.commons:commons-lang3:3.1 -> 3.4<br>
|    |         \--- org.ow2.asm:asm:5.0.4<br>
|    +--- org.springframework.cloud:spring-cloud-starter-ribbon:1.2.7.BUILD-SNAPSHOT -> 1.2.6.RELEASE (*)<br>
|    +--- org.springframework.cloud:spring-cloud-starter-archaius:1.2.7.BUILD-SNAPSHOT -> 1.2.6.RELEASE (*)<br>
|    \--- com.netflix.zuul:zuul-core:1.3.0<br>
|         +--- commons-io:commons-io:2.4<br>
|         +--- org.slf4j:slf4j-api:1.7.6 -> 1.7.24<br>
|         +--- com.netflix.archaius:archaius-core:0.6.0 -> 0.7.4 (*)<br>
|         +--- com.netflix.servo:servo-core:0.7.2 -> 0.10.1 (*)<br>
|         \--- com.netflix.netflix-commons:netflix-commons-util:0.1.1 (*)<br>
</p></details>

<details><summary>after</summary><p>
+--- org.springframework.cloud:spring-cloud-starter-zuul: -> 1.2.7.BUILD-SNAPSHOT<br>
|    +--- org.springframework.cloud:spring-cloud-starter:1.1.9.BUILD-SNAPSHOT (*)<br>
|    +--- org.springframework.boot:spring-boot-starter-web:1.4.6.RELEASE -> 1.4.6.BUILD-SNAPSHOT (*)<br>
|    +--- org.springframework.boot:spring-boot-starter-actuator:1.4.6.RELEASE -> 1.4.6.BUILD-SNAPSHOT<br>
|    |    +--- org.springframework.boot:spring-boot-starter:1.4.6.BUILD-SNAPSHOT (*)<br>
|    |    \--- org.springframework.boot:spring-boot-actuator:1.4.6.BUILD-SNAPSHOT<br>
|    |         +--- org.springframework.boot:spring-boot:1.4.6.BUILD-SNAPSHOT (*)<br>
|    |         +--- org.springframework.boot:spring-boot-autoconfigure:1.4.6.BUILD-SNAPSHOT (*)<br>
|    |         +--- com.fasterxml.jackson.core:jackson-databind:2.8.8 (*)<br>
|    |         +--- org.springframework:spring-core:4.3.8.RELEASE (*)<br>
|    |         \--- org.springframework:spring-context:4.3.8.RELEASE (*)<br>
|    +--- org.springframework.cloud:spring-cloud-starter-hystrix:1.2.7.BUILD-SNAPSHOT<br>
|    |    +--- org.springframework.cloud:spring-cloud-starter:1.1.9.BUILD-SNAPSHOT (*)<br>
|    |    +--- org.springframework.cloud:spring-cloud-netflix-core:1.2.7.BUILD-SNAPSHOT (*)<br>
|    |    +--- org.springframework.cloud:spring-cloud-starter-archaius:1.2.7.BUILD-SNAPSHOT (*)<br>
|    |    +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    +--- com.netflix.hystrix:hystrix-metrics-event-stream:1.5.6<br>
|    |    |    +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    |    \--- com.netflix.hystrix:hystrix-serialization:1.5.6<br>
|    |    |         +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.7.5 -> 2.8.8<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.7.5 -> 2.8.8 (*)<br>
|    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.7.5 -> 2.8.8<br>
|    |    |         +--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.7.5 -> 2.8.8<br>
|    |    |         |    \--- com.fasterxml.jackson.core:jackson-core:2.8.8<br>
|    |    |         \--- com.fasterxml.jackson.module:jackson-module-afterburner:2.7.5<br>
|    |    |              +--- com.fasterxml.jackson.core:jackson-core:2.7.5 -> 2.8.8<br>
|    |    |              \--- com.fasterxml.jackson.core:jackson-databind:2.7.5 -> 2.8.8 (*)<br>
|    |    \--- com.netflix.hystrix:hystrix-javanica:1.5.6<br>
|    |         +--- com.netflix.hystrix:hystrix-core:1.5.6 (*)<br>
|    |         +--- org.aspectj:aspectjweaver:1.8.6 -> 1.8.10<br>
|    |         +--- com.google.guava:guava:15.0 -> 18.0<br>
|    |         +--- commons-collections:commons-collections:3.2.2<br>
|    |         +--- org.apache.commons:commons-lang3:3.1 -> 3.4<br>
|    |         \--- org.ow2.asm:asm:5.0.4<br>
|    +--- org.springframework.cloud:spring-cloud-starter-ribbon:1.2.7.BUILD-SNAPSHOT (*)<br>
|    +--- org.springframework.cloud:spring-cloud-starter-archaius:1.2.7.BUILD-SNAPSHOT (*)<br>
|    \--- com.netflix.zuul:zuul-core:1.3.0<br>
|         +--- commons-io:commons-io:2.4<br>
|         +--- org.slf4j:slf4j-api:1.7.6 -> 1.7.25<br>
|         +--- com.netflix.archaius:archaius-core:0.6.0 -> 0.7.4 (*)<br>
|         +--- com.netflix.servo:servo-core:0.7.2 -> 0.10.1 (*)<br>
|         \--- com.netflix.netflix-commons:netflix-commons-util:0.1.1 (*)<br>
</p></details>

**Comment by KeiichiTheOtaku** [comment]
Once again, unfortunately, we saw the issue reoccur when using the `Camden.BUILD-SNAPSHOT` from 5/1/17.

The behavior of the long-running CLOSE_WAIT connections changed somewhat, with regard to the rate at which the number of such connections increased, but the app still ended up unresponsive after about a day running in our environment.

Any other suggestions would be appreciated.

Is there debug or trace logging around the bug fix code in Zuul that we can use to verify that our requests are actually using the fixed logic?

**Comment by ryanjbaxter** [comment]
I dont see any logging around it.  You are using Ribbon in your Zuul proxy and not specifying URLs for the routes, correct?

**Comment by KeiichiTheOtaku** [comment]
There's a mix... We use ribbon for the majority of routes, but we do have a few that forward requests to AWS S3 for static content.

**Comment by ryanjbaxter** [comment]
So the fix above would only apply to those requests using Ribbon, not the ones using URL routes.  Maybe it is the URL routes that is causing the issue.....

**Comment by KeiichiTheOtaku** [comment]
It's possible... We'll try to determine whether the connections with the issue when running the snapshot version of Camden are all non-ribbon connections.

In the mean time, any word on an ETA for the Camden SR7 release (containing the fix)?

**Comment by spencergibb** [comment]
SR7 went live a day or two ago

**Comment by KeiichiTheOtaku** [comment]
Thanks Spencer

**Comment by KeiichiTheOtaku** [comment]
@ryanjbaxter Based on the reporting of long-running CLOSE_WAIT connections we have on our Zuul instances, running with the Camden.BUILD-SNAPSHOT version still resulted in connections to EC2 instances (via Ribbon) in the long-running CLOSE_WAIT state, and the Zuul instance becoming unresponsive.

We'll continue our testing with the Camden.SR7 release and see if anything changes... I'll respond again if/when we have more information that might be helpful.
