### ISSUE TITLE
Customizing the retry strategy could be simpler

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-netflix#1872]
With the changes to retry logic in spring cloud's ribbon libraries, it has become more difficult to change the strategy used to determine if a request should be retried. Previously, we were able to define our own RetryHandler and define exceptions that are eligible for retry. 

Now that Spring Retry is being used, it appears that the Netflix RetryHandler is not used. After some digging, it appears we need to introduce a custom RetryPolicy into the ribbon logic but doing so was not straightforward. 

The RibbonAutoConfiguration class does not have a `@ConditionalOnMissingBean` on the follow bean: 

```java
	@Bean
	@ConditionalOnClass(name = "org.springframework.retry.support.RetryTemplate")
	public LoadBalancedRetryPolicyFactory loadBalancedRetryPolicyFactory(SpringClientFactory clientFactory) {
		return new RibbonLoadBalancedRetryPolicyFactory(clientFactory);
	}
```

You have to create an alternate LoadBalancedRetryPolicyFactory and then serve up a custom instance of the RetryPolicy. And the only way I could figure out how to do this was to annotate my factory with a `@Primary` flag. 

It would be very helpful to have a way to customize (Maybe a customizer?) the RetryPolicy instances being served from the RibbonLoadBalancedRetryPolicyFactory.

At the very least, adding a "@ConditionalOnMissingBean" to this bean, allows it to be replaced with a custom factory in your Ribbon Configuration.

**Comment by spencergibb** [comment]
`@Primary` is perfectly valid. Also, using the same bean name `loadBalancedRetryPolicyFactory`.

**Comment by ryanjbaxter** [comment]
I have been thinking about this as well and it certainly crossed my mind while implementing the functionality.  Thanks for the feedback!

**Comment by ryanjbaxter** [comment]
In Dalston there is now a class called `RibbonLoadBalancedRetryPolicy` which you could extend and then override the necessary methods, that might make this cleaner.  But point taken none the less.

**Comment by hchangAtDigitalRiver** [comment]
A side note for overriding retryPolicyFactroy, to make @Primary work, you need to have a factory method name other than "loadBalancedRetryPolicyFactory". So that your bean won't be overridden by RibbonAutoConfiguration#loadBalancedRetryPolicyFactory().

**Comment by ryanjbaxter** [comment]
@tkvangorder I believe this is fixed in Edgware, would you agree? https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/RibbonAutoConfiguration.java#L93

**Comment by tkvangorder** [comment]
@ryanjbaxter Yep, looks good!
