### ISSUE TITLE
Eureka Client Health status update to Eureka

### ISSUE THREAD

**Issue by sureshkrishnamoorthy** [spring-cloud/spring-cloud-netflix#1875]
We are using Spring cloud netflix version 1.2.6 (Camden SR6) and Spring boot version 1.4.5 in our environment.

When the service is closed abruptly (VM crash),  
- with the default eureka client settings, service health status is always displayed as UP in eureka until the lease expiration time and after the the instance is removed from registry
- when we update the eureka client property eureka.client.healthcheck.enabled=true, we could not see any difference 

Please let us know how to update the down status to eureka when the service is not available

**Comment by spencergibb** [comment]
Sounds like Eureka working as designed. Eureka waits up to 3 heartbeat cycles before removing an instance in case of network hiccups.

`eureka.client.healthcheck.enabled=true` only works if the client is up and sends a different status with the heartbeat. Eureka doesn't ping instances.

**Comment by saiyedzaidi** [comment]
@sureshkrishnamoorthy  eureka.instance.leaseExpirationDurationInSeconds is the property that you need to tune if you want Eureka to clean away the dead instances faster. The default value is 90.
