### ISSUE TITLE
RibbonLoadBalancingHttpClient#getRequestSpecificRetryHandler does not create the RequestSpecificRetryHandler with the provided IClientConfig 

### ISSUE THREAD

**Issue by nithril** [spring-cloud/spring-cloud-netflix#1879]
`RibbonLoadBalancingHttpClient#getRequestSpecificRetryHandler` pass null to the `RequestSpecificRetryHandler` and not the provided `IClientConfig requestConfig`:

	@Override
	public RequestSpecificRetryHandler getRequestSpecificRetryHandler(RibbonApacheHttpRequest request, IClientConfig requestConfig) {
		return new RequestSpecificRetryHandler(false, false, RetryHandler.DEFAULT, null);
	}

Is it the expected behaviour?

Thanks

**Comment by nithril** [comment]
I wonder why the `RibbonLoadBalancingHttpClient#getRequestSpecificRetryHandler` method is different from the`org.springframework.cloud.netflix.ribbon.support.AbstractLoadBalancingClient#getRequestSpecificRetryHandler` one ?

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?  We no longer use the `RetryHandler` in Dalston and the latest SR releases of Camden.

**Comment by ishchenko** [comment]
Hey, @ryanjbaxter, we're facing same issue, no retries for our ConnectExceptions in ZuulFilter, using Ribbon as LB. We are using Camden.SR6, and implementation is same, looks like it does not allow for any retries by default, and this is a problem.

**Comment by nithril** [comment]
I'm using Dalston version and I have tried to use `RetryableRibbonLoadBalancingHttpClient`.

**Comment by ryanjbaxter** [comment]
@ishchenko please open a separate issue

@nithril so what is the problem specifically?  You talk about trying to pass `IConfig` but since we are not using `RetryHandler` it doesnt really matter.

**Comment by nithril** [comment]
I rely on ribbon native retry support (mainly because of #1878). Thus because `IClientConfig requestConfig` is not set, the fields `retrySameServer` and `retryNextServer` are not set.

**Comment by ryanjbaxter** [comment]
OK I dont see any harm in passing the config.

**Comment by nithril** [comment]
Have you look at my question?

> I wonder why the RibbonLoadBalancingHttpClient#getRequestSpecificRetryHandler method is different from the org.springframework.cloud.netflix.ribbon.support.AbstractLoadBalancingClient#getRequestSpecificRetryHandler one ?

Especially why the `okToRetryOnConnectErrors` and `okToRetryOnAllErrors` are set to false and not set according to the `IClientConfig requestConfig` ? 

Thanks

**Comment by ryanjbaxter** [comment]
I believe I did this because we wanted all retry operations to use spring retry and not Ribbon.

**Comment by nithril** [comment]
I understand for `RetryableRibbonLoadBalancingHttpClient` but does it make sense for `RibbonLoadBalancingHttpClient` ?

**Comment by ryanjbaxter** [comment]
If my memory serves me correctly that code was added because when using Feign there was two levels or retries happening, one through Feign and the other through Ribbon.  This eliminates the Ribbon retry so only Feign is retrying requests.

**Comment by nithril** [comment]
Thanks for this explanation.  I have create my owns RibbonClient which override `getRequestSpecificRetryHandler` to enable ribbon native retry.
