### ISSUE TITLE
InetUtils extracts wrong hostname

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-netflix#1882]
We had a strange issue where the eureka client always sent their IP as the hostname. Prefer IP-Adress was set to false in the config.
After some debugging I found out that the problem is located somewhere in the InetUtils.
EurekaInstanceConfigBean calls findFirstNonLoopbackHostInfo and get's back a HostInfo with the wrong Hostname. We're on Spring Cloud Dalston.RELEASE

If you need any further information feel free to ask anytime.

Kind regards,
Jan

**Comment by ryanjbaxter** [comment]
Can you show us your `application.poperties`?  We will try and get the IP address of the machine and then lookup the hostname from that IP address using `InetAddress`.  Can you lookup the hostname from the machines IP?

**Comment by spencergibb** [comment]
@JWThewes sometimes it is unable to obtain a hostname. This should actually go in spring-cloud-commons where `InetUtils` lives.

**Comment by JWThewes** [comment]
@spencergibb Ok I've moved this one over to commons: https://github.com/spring-cloud/spring-cloud-commons/issues/203
