### ISSUE TITLE
Redirect call to another service with Eureka - question

### ISSUE THREAD

**Issue by rodrigorodrigues** [spring-cloud/spring-cloud-netflix#1898]
Hi everyone,

I have one question regarding how to redirect a call to another service with eureka, I believe it is possible to do it by filter but I am not quite sure which type(pre, route) should I use and also which order.

My filter is like this.
```java
 @Autowired
  private DiscoveryClient discoveryClient;

 @Override
  public String filterType() {return "route";}

  @Override
  public int filterOrder() {return 6;}

 @Override
  public Object run() {
    RequestContext ctx = RequestContext.getCurrentContext();
    HttpServletRequest request = ctx.getRequest();
    redirect(ctx, request);

    return null;
  }

  private void redirect(RequestContext ctx, HttpServletRequest request) {
    if (StringUtils.equals(request.getQueryString(), "redirect=author")) {
      List<ServiceInstance> instances = discoveryClient.getInstances("AUTHOR");
      if (CollectionUtils.isEmpty(instances))
        return;
      int index = new Random().nextInt(instances.size());
      ServiceInstance serviceInstance = instances.get(index);
      try {
        String routeHost = new StringBuffer(serviceInstance.getUri().toString())
                .append(request.getRequestURI()
                .substring(request.getRequestURI().indexOf("/", 1)))
                .toString();
        ctx.setRouteHost(new URL(routeHost)); // Here is the issue
      } catch (MalformedURLException e) {
        log.error("Error malformed url", e);
      }
    }
  }
```
application.properties
```
zuul.ignoredServices=*
zuul.routes.books.path=/books/**
zuul.routes.books.serviceId=BOOK
debug=true
```
I have two services(book and author) and only the first one is mapped to Zuul and both have the same rest path.

The idea is when call any url with query string "?redirect=author" should redirect to author service, i.e.:
http://localhost:8080/books/available - Call Book Service - OK
http://localhost:8080/books/available?redirect=author - Call author Service - NOT WORKING

I've tried ```ctx.setRouteHost(new URL(routeHost))``` and ```ctx.set("requestURI", routeHost)``` without luck always return ```404 - Not Found```.

Any one has some idea how to implement this please?

Thank you

**Comment by ryanjbaxter** [comment]
I think you might want to make this a `pre` filter since it is not actually routing the request.  I cannot really say what the order should be, that depends on your specific app and other filters you might have.

**Comment by spencergibb** [comment]
I do something similar here https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/QueryParamServiceIdPreFilter.java

**Comment by rodrigorodrigues** [comment]
Hi @spencergibb,

You are absolutely write it works with ```ctx.put("serviceId", "SERVICENAME")``` instead of ```ctx.setRouteHost(new URL(routeHost))```.

Thanks a million!
