### ISSUE TITLE
Zuul routing to blank url

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#190]
I am trying to route requests to feign client, below is my zuul configuration.

```
zuul:
  routes:
    helloclient: /test/**   
```

http://localhost:8765/test - POST with parameter name=test
i was getting 405 errordue to URL. missing URI, i think the below lines are causing the issue.

In `RibbonRoutingFilter` class

```
String uri = request.getRequestURI(); // -- is returning "/test"
		if (context.get("requestURI") != null) {  // -- is true as it is blank
			uri = (String) context.get("requestURI"); //-- resetting the uri to blank
		}
```

either i am missing some configuration so the `context.get("requestURI")` is blank or the above code is missing blank check.

**Comment by spencergibb** [comment]
did you not complete your report?

**Comment by ctatineni** [comment]
Sorry, yes i completed the report, let me know if i missed any configuration

**Comment by dsyer** [comment]
Blank is allowed as a URI path, and I think that's the correct value in your case (you sent a request to /test and /test is the route prefix, which is stripped by default). I'm a bit confused about what you mean by "route requests to a feign client" since this is a gateway (serverside) feature. What actually happened when the backend request was sent, and why do you think that it's wrong (stack trace maybe)?

P.S. If you don't want the prefix to be stripped to have to say so in the route spec.

**Comment by ctatineni** [comment]
I think the use case that i am testing is a weird one, i am not sure if it is a valid one.
I have an application helloclient1 with url http://localhost:8886/test1
another application helloclient2 with url http://localhost:8886/test2
i am trying to set the routes as 
zuul:
  routes:
    helloclient1: /test1/** 
    helloclient2: /test2/** 

if i do this , /test1 and /test2 are replaced with blank.

i am not sure if i can do the below.

zuul:
  routes:
    helloclient1: /** 
    helloclient2: /** 

BTW, i tested with lot of other use cases and all of them are working fine.

**Comment by ctatineni** [comment]
One more thing, if i use 1.0.0.RC2 and if i do not have eureka URL configuration with credentials, i am not getting any error and it was not able to find the helloclient1, even if i add the URL i do not see any change, may be i am missing something here, i need to do little more debugging here.

where as if i use 1.0.0-BUILD-SNAPSHOT , i am getting 401 error as it is by default trying to connect to eureka instance, after adding the credentials in the URL it is working fine.i am not sure why it is not happening for 1.0.0.RC2.

**Comment by dsyer** [comment]
I'm not quite sure I follow (those 2 clients have the same host and port, are they 1 client). Try

```
zuul:
  routes:
    helloclient1:
      serviceId: helloclient
      path: /test1/**
      stripPrefix: false
```

Or replace the `serviceId` with `url` if you want the physical URL.

**Comment by ctatineni** [comment]
It worked after using stripPrefix option, Thanks for the help.
