### ISSUE TITLE
Zuul not routing any request after some time

### ISSUE THREAD

**Issue by evidal** [spring-cloud/spring-cloud-netflix#1901]
I'm using Zuul inside a Spring Boot application to add authentication and authorization to an external  micro-service.

After a 1-2 days (<1 million Requests) Zuul does not route any request: on SimpleHostRoutingFilter the execution stops on the method forwardRequest, as if the http client was not able to make a new request.

I've tried several Zuul version from to 1.1.6.RELEASE to 1.2.6.RELEASE, I can reproduce each time when injecting enough traffic (between 5-40 request/s during several hours). I think that the problem is not linked to the system as it's happening on 2 different environments : a Linux Red Hat OS and Mac OS.

My Zuul configuration is the following one :
```
zuul:
  routes:
    drs:
      path: /drs/**
      url: http://localhost:8080/drs

```
I have have 1 pre filter (to remove swagger), 2 post filters (to count requests and log).
Spring Security is plugged on "routed" services.

Please note that the Spring application running Zuul continues to serve request even if Zuul is blocked.

Any idea how to resolve this problem ?

**Comment by ryanjbaxter** [comment]
Wondering if this could be related to #1372.  Could you try `Dalston.RELEASE` or `Camden.BUILD-SNAPSHOT`?

**Comment by evidal** [comment]
Ok so I've updated to the latest version of Zuul to 1.3.0.RELEASE and it seems to be ok. My application is running now since several days without problem. I can't reproduce the old problem.
