### ISSUE TITLE
Turbine's CommonsInstanceDiscovery throws NullPointerException if used with SimpleDiscoveryClient

### ISSUE THREAD

**Issue by maxromanovsky** [spring-cloud/spring-cloud-netflix#1908]
Turbine's `CommonsInstanceDiscovery` throws `NullPointerException` if used with `SimpleDiscoveryClient` as `SimpleDiscoveryProperties.SimpleServiceInstance#getMetadata` returns `null`, while `CommonsInstanceDiscovery#marshall` does not verify that it's not null: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine/src/main/java/org/springframework/cloud/netflix/turbine/CommonsInstanceDiscovery.java#L161

`ServiceInstance#getMetadata` says nothing about returning `null`, so IMHO it's up to `CommonsInstanceDiscovery#marshall` to ensure that it's not `null`.

I'm willing to implement a PR for that, but need your decision whether to implement it in Turbine discovery (check for nulls) or in `SimpleDiscoveryProperties` (return empty map instead of `null`).
Ideally, Spring should allow configuring these properties with metadata though (IMHO).

**Comment by e-zhydzetski** [comment]
HystrixStream's `HystrixStreamTask` has the same problem with `SimpleDiscoveryClient`: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-hystrix-stream/src/main/java/org/springframework/cloud/netflix/hystrix/stream/HystrixStreamTask.java#L375

**Comment by maxromanovsky** [comment]
@e-zhydzetski Host should work fine, as it's filled from the `uri`: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/discovery/simple/SimpleDiscoveryProperties.java#L41-L43

**Comment by e-zhydzetski** [comment]
@maxromanovsky Sorry! My mistake: problem that I described differs from yours.
`HystrixStreamTask` has issue with `SimpleDiscoveryClient#getLocalServiceInstance` which always returns `null`. This method was deprecated in `DiscoveryClient` interface, but `HystrixStreamTask` still use it without null checks.
I will create a separate issue for this.

**Comment by ryanjbaxter** [comment]
@maxromanovsky I think I agree that `CommonsInstanceDiscvery#marshall` should check for null

**Comment by maxromanovsky** [comment]
Spring Cloud Team, I understand that it's minor, but any thoughts? I'm willing to contribute :)

**Comment by ryanjbaxter** [comment]
@maxromanovsky submit a PR an we will review

**Comment by dsyer** [comment]
Fixed here: https://github.com/spring-cloud/spring-cloud-commons/commit/fc2355b9853a4d0164a6c9287b36668fd5844ba7
