### ISSUE TITLE
HystrixStream throws NPE if used with SimpleDiscoveryClient

### ISSUE THREAD

**Issue by e-zhydzetski** [spring-cloud/spring-cloud-netflix#1909]
Spring Boot: 1.5.2.RELEASE
Spring Cloud: Dalston.RELEASE

HystrixStream's `HystrixStreamTask` throws `NullPointerException` if used with `SimpleDiscoveryClient`.
`SimpleDiscoveryClient#getLocalServiceInstance` always returns `null`, while`HystrixStreamTask` doesn't check it on `null`.

I think, `HystrixStreamTask` should use other source of self-service information, as `DiscoveryClient#getLocalServiceInstance` was deprecated.

**Comment by dsyer** [comment]
Actually the bug is in spring-cloud-commons (https://github.com/spring-cloud/spring-cloud-commons/commit/fc2355b9).
