### ISSUE TITLE
ZUUL query parameter issue

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#191]
when i try to post to zuul url with query parameters as below

http://localhost:8765/test?name=test

i am getting the below output in `RibbonRoutingFilter` class when it executes 

```
MultiValueMap<String, String> params = this.helper
				.buildZuulRequestQueryParams(request);
```

output - `{name=[test, test]}`

also i see that same parameter is added to requestentity

so when i print the paramvalue it is printing three times.

please suggest.

**Comment by dsyer** [comment]
I guess you aren't supposed to use query params in a POST (at least the `Filter` wasn't expecting it). It does work if you use the body for the request parameters?

**Comment by dsyer** [comment]
Actually I just tried this with the `SampleZuulProxyApplication` (from the tests) and it only has a single valued parameter as far as I can tell (`curl localhost:9999/testing123?foo=bar` and set a break point in `RibbonRoutingFilter`). Where exactly did you see that double (and triple) value?

**Comment by ctatineni** [comment]
MultiValueMap<String, String> params = this.helper
                .buildZuulRequestQueryParams(request);

after executing the above line, params value is having three values, actually it is my bad, i should only use body for post, i was testing GET and POST simultaneously.

**Comment by dsyer** [comment]
I still can't reproduce. What did you do exactly on the client?

P.S. please use markdown for code and logs.

**Comment by ctatineni** [comment]
closing this as it works fine with request body on POST.
