### ISSUE TITLE
Generic Way to Update Metadata

### ISSUE THREAD

**Issue by sofiaguyang** [spring-cloud/spring-cloud-netflix#1912]
Is there a generic way of updating metadata instead of invoking the Netflix/Eureka-specific `applicationInfoManager.registerAppMetadata(metadata)`?

I am using spring-cloud-dependencies:Camden.SR6.

**Comment by spencergibb** [comment]
`ServiceInstance` has a metadata method, but it's not for updating the metadata. Why do you want to update the metadata?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
