### ISSUE TITLE
How to configure turbine to have more than one cluster but more than one apps in each cluster

### ISSUE THREAD

**Issue by vireshwali** [spring-cloud/spring-cloud-netflix#1913]
Is something like this possible?

turbine.aggregator.clusterConfig=apis,services
turbine.InstanceMonitor.eventStream.skipLineLogic.enabled=false

turbine.appConfig._apis_=edge-gateway-server
turbine.appConfig._services_=product-details-service,product-details-microservice

**Comment by vireshwali** [comment]
Or anyother way to do the same thing? Basically what I want is to have a way so that one cluster stream can monitor more than one microservice.

**Comment by ryanjbaxter** [comment]
I dont believe so, I think the `clusterConfig` service names need to match the service names in your discovery service.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
