### ISSUE TITLE
Veracode testing identifies RibbonLoadBalancingHttpClient.java 95 has cross-site scripting (XSS) flaw

### ISSUE THREAD

**Issue by rajaks257** [spring-cloud/spring-cloud-netflix#1914]
Hi,

We are using spring-cloud-netflix-core-1.2.6.RELEASE.jar

We got the below issue when we ran Veracode testing for our code.

**Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS) (CWE ID 80)**

Class : RibbonLoadBalancingHttpClient.java 
line no: 95

As per the issue, the call contains a cross-site scripting (XSS) flaw at line number 95 in RibbonLoadBalancingHttpClient.java class.

If you believe this is a false positive from Veracode, please do let us know the same and also the reasons for the same. We can submit the same to mitigate the issue accordingly.

Thank you,
Raja

**Comment by spencergibb** [comment]
I think this is a false positive
