### ISSUE TITLE
Move ZuulConfiguration use of @ConditonalOnMissionBean to auto-config, ala eureka client.

### ISSUE THREAD

**Issue by helpermethod** [spring-cloud/spring-cloud-netflix#1916]
So it seems that `ZuulConfiguration.java` is no AutoConfiguration Bean but still uses `@ConditionOnMissingBean` for checking for the absence of certain beans.

But `@ConditionalOnMissionBean`s seems to be discouraged for non-AutoConfiguration Beans according to the docs:

> The condition can only match the bean definitions that have been processed by the application context so far and, as such, it is strongly recommended to use this condition on auto-configuration classes only. If a candidate bean may be created by another auto-configuration, make sure that the one using this condition runs after.

**Comment by spencergibb** [comment]
It's a bug
