### ISSUE TITLE
Support the Netflix hystrix SSE heartbeat stream for Spring Retry's circuit breaker

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-netflix#1917]
Please support the Netflix hystrix SSE heartbeat stream for Spring Retry's circuit breaker. Would be nice if  `@EnableCircuitBreaker` worked here, too. While you're at it, would you please also bring in spring-boot-starter-aop by default since Spring retry doesn't by default and it's needed in common use-cases.

**Comment by spencergibb** [comment]
I'm pretty sure @dsyer took a shot at the hystrix metrix with [spring retry](https://github.com/spring-projects/spring-retry). `@EnableCircuitBreaker` would be responsibility of https://github.com/spring-cloud/spring-cloud-commons/issues/21. Maybe a spring-cloud-starter-spring-retry could have the aop starter?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
