### ISSUE TITLE
Spring FeignClient: Error writing to server with long query string

### ISSUE THREAD

**Issue by jeffczaplewski** [spring-cloud/spring-cloud-netflix#1919]
I have 2 spring boot microservices and i'm trying to make a call from service A to service B using FeignClients. Service A client looks like more or less like this:

`@FeignClient(name = "svcb")
public interface SvcBClient {

    @RequestMapping(value = "/svcb", method = RequestMethod.GET)
    List<DTO> getCustomFieldsSettings(@RequestParam("ids") List<Integer> ids);

}`

with a corresponding spring controller on the other end in service B.

If the list of Integers that i pass from service A to service B exceeds roughly 2000 ids, i get an error "java.io.Exception Error writing to server".

understandly this can easily be changed to use a POST with a body, but my understanding was that there aren't limits to the size of the query string, technically speaking.

so why the error? i'm seeing the error thrown from here in the com.netflix.client.AbstractLoadBalancerAwareClient. Maybe this is a netflix question?

`public T executeWithLoadBalancer(final S request, final IClientConfig requestConfig) throws ClientException {
        RequestSpecificRetryHandler handler = this.getRequestSpecificRetryHandler(request, requestConfig);
        LoadBalancerCommand command = LoadBalancerCommand.builder().withLoadBalancerContext(this).withRetryHandler(handler).withLoadBalancerURI(request.getUri()).build();

        try {
            return (IResponse)command.submit(new ServerOperation() {
                public Observable<T> call(Server server) {
                    URI finalUri = AbstractLoadBalancerAwareClient.this.reconstructURIWithServer(server, request.getUri());
                    ClientRequest requestForServer = request.replaceUri(finalUri);

                    try {
                        return Observable.just(AbstractLoadBalancerAwareClient.this.execute(requestForServer, requestConfig));
                    } catch (Exception var5) {
                        return Observable.error(var5);
                    }
                }
            }).toBlocking().single();
        } catch (Exception var7) {
            Throwable t = var7.getCause();
            if(t instanceof ClientException) {
                throw (ClientException)t;
            } else {
                throw new ClientException(var7);
            }
        }
    }
`
Thanks

**Comment by ryanjbaxter** [comment]
If there error is coming from a class in Netflix than it sounds like a Netflix issue.  I believe there is a limit to how big a `GET` request can be.
http://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request

**Comment by Spark4J** [comment]
> I have 2 spring boot microservices and i'm trying to make a call from service A to service B using FeignClients. Service A client looks like more or less like this:
> 
> `@FeignClient(name = "svcb")
> public interface SvcBClient {
> 
> ```
> @RequestMapping(value = "/svcb", method = RequestMethod.GET)
> List<DTO> getCustomFieldsSettings(@RequestParam("ids") List<Integer> ids);
> ```
> }`
> 
> with a corresponding spring controller on the other end in service B.
> 
> If the list of Integers that i pass from service A to service B exceeds roughly 2000 ids, i get an error "java.io.Exception Error writing to server".
> 
> understandly this can easily be changed to use a POST with a body, but my understanding was that there aren't limits to the size of the query string, technically speaking.
> 
> so why the error? i'm seeing the error thrown from here in the com.netflix.client.AbstractLoadBalancerAwareClient. Maybe this is a netflix question?
> 
> `public T executeWithLoadBalancer(final S request, final IClientConfig requestConfig) throws ClientException {
> RequestSpecificRetryHandler handler = this.getRequestSpecificRetryHandler(request, requestConfig);
> LoadBalancerCommand command = LoadBalancerCommand.builder().withLoadBalancerContext(this).withRetryHandler(handler).withLoadBalancerURI(request.getUri()).build();
> 
> ```
>     try {
>         return (IResponse)command.submit(new ServerOperation() {
>             public Observable<T> call(Server server) {
>                 URI finalUri = AbstractLoadBalancerAwareClient.this.reconstructURIWithServer(server, request.getUri());
>                 ClientRequest requestForServer = request.replaceUri(finalUri);
> 
>                 try {
>                     return Observable.just(AbstractLoadBalancerAwareClient.this.execute(requestForServer, requestConfig));
>                 } catch (Exception var5) {
>                     return Observable.error(var5);
>                 }
>             }
>         }).toBlocking().single();
>     } catch (Exception var7) {
>         Throwable t = var7.getCause();
>         if(t instanceof ClientException) {
>             throw (ClientException)t;
>         } else {
>             throw new ClientException(var7);
>         }
>     }
> }
> ```
> `
> Thanks

Have you resolved this problem? I need help, thanks!

**Comment by spencergibb** [comment]
GET has a maximum limit.

**Comment by Spark4J** [comment]
> GET has a maximum limit.

Not the reason.We have set "method = RequestMethod.POST".

**Comment by spencergibb** [comment]
Then you have a different problem. Please open a new issue if you can provide a project that recreates the problem.
