### ISSUE TITLE
Provide a health indicator for the circuit breaker metrics stream

### ISSUE THREAD

**Issue by glyn** [spring-cloud/spring-cloud-netflix#1920]
Currently, applications can fail to provide circuit breaker metrics and yet report health as `UP`.

For example, [bug 1909](https://github.com/spring-cloud/spring-cloud-netflix/issues/1909) caused metrics logging to NPE and yet the application reported health as `UP`.

It would be helpful if failures in providing metrics were included in the health of the application.

**Comment by spencergibb** [comment]
What would the indicator look like? Call `HystrixStreamTask.gatherMetrics()`?

**Comment by glyn** [comment]
@spencergibb The health indicator required by this story would record whether or not the circuit breaker metrics stream is being read successfully. So in the successful case, I would expect the health indicator to be `UP` and in the failure case, I guess it should be `DOWN` and ideally include some diagnostic information about the failure (if that's the done thing for health indicators). I'm not sure which hystrix APIs are involved as I'm not familiar with the implementation.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
