### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins

### ISSUE THREAD

**Issue by shree007** [spring-cloud/spring-cloud-netflix#1923]
Hi guys i have following error when I am trying to execute $mvn package  I tried in several ways but i could not fix it. I am newbie in spring  
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project eureka-client: There are test failures.

My pom.xml

[pom.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/980787/pom.txt)

**Comment by ryanjbaxter** [comment]
There are junit tests in your project.  This doesn't appear to be related to Spring Cloud.
