### ISSUE TITLE
StripPrefix conflict with server.contextPath

### ISSUE THREAD

**Issue by vrmsreddy** [spring-cloud/spring-cloud-netflix#1929]
i added stripPrefix = false under zull configuration, like this
```
zuul:
  prefix: /api
  stripPrefix: false
  ignored-services: "*"
  routes:
    customer: 
      path: /customer/**
      stripPrefix: false
```
my requirement is i want to black all downstream calls
e.g
1)http://localhost:9999/api/customer/orders      {need to allow all calls and validate request using zuulfilter}
2)http://localhost:9999/customer/orders   need to block direct access
even i tried to add server.contextpath =/api/customer after that zuul got disabled

**Comment by ryanjbaxter** [comment]
Please format code according to https://help.github.com/articles/creating-and-highlighting-code-blocks/

What do you mean you need to block all downstream calls?  Can you describe what is happening with the configuration above and what you are trying to achieve?

**Comment by vrmsreddy** [comment]
Hi ryanjbaxter,
Thanks for quick replay,
Here thing is i want to block all downstream calls without spring security or any other interceptors
my controller looks like this
@RestController
@RequestMapping("/customer")
public class customer{
    RequestMapping("/orders")
   public Respnse getOrders(....){
        return x;
    }
}

and Configured zuul in yml like below
zuul:
prefix: /api
stripPrefix: false
ignored-services: "*"
routes:
customer:
path: /shop/**
stripPrefix: false
 not added any server.contextPath
so URL looks like 

DownStream Direct Access http://localhost:9999/customer/orders
Zuul routing URL   http://localhost:9999/api/shop/customer/orders

even throughi added strip prefix ,still i can access downstream API directly,
here thing is i want to validate a token using zuul proxy,without security downstream calls diverted

**Comment by ryanjbaxter** [comment]
Again please read the github documenation on how to format code in your issues, see the link in my previous comment.

I don't see how setting `stripPrefix` to false would cause you not to be able to access the downstream API.  `zuul.stripPrefix` will make sure `/api` is added to the request to the downstream service and `zuul.routes.customer.stripPrefix` will make sure `/customers` is added to the request to the downstream service.  

Now if you are trying to validate some kind of security token before the request is forwarded on you might be able to do that in a `ZuulFilter` but that did not seem to be what you are asking originally so I am still confused on what the issue is.

**Comment by vrmsreddy** [comment]
Hi @ryanjbaxter below config used

Sample Zuul Config used
``` yml

zuul:
prefix: /api
stripPrefix: false
ignored-services: "*"
routes:
  customer:
      path: /shop/**
      stripPrefix: false

```
Sample ZuulFilter for validating token
```java

  public class SecurityFilter extends ZuulFilter {
        @Override
	public boolean shouldFilter() {
		return true;
	}
        @Override
	public Object run() {
                RequestContext context = RequestContext.getCurrentContext();
		HttpServletRequest request = context.getRequest();
                String token = request.getHeader("token");
                //-----validation of token -----
        }
        @Override
	public String filterType() {
		return "pre";
	}
        @Override
	public int filterOrder() {
		return 1;
	}
  } 
```

Sample Restful API /controller
```java

   @RestController
   @RequestMapping("/customer")
   public class customer{
         RequestMapping("/orders")
         public Respnse getOrders(....){
              return x;
         }
    }
```
# Case1:
   If i use http://localhost:9999/api/shop/customer/orders
   then call is landed to zuulfilter and i can check token
# Case2:
  if i use http://localhost:9999/customer/orders
  then call landed to controller rather then zuulfilter,so any one can access APIs without token

can i block Case2 with stripPrefix  using zuulfilter?

**Comment by spencergibb** [comment]
`/customer/orders` shouldn't be mapped in zuul. Why is it? Can you show `/routes`?

**Comment by vrmsreddy** [comment]
Hi 
All zuul configuration and APIs in the same app,
I configured only one route to access customer orders i.e.  /api/shop

**Comment by vrmsreddy** [comment]
```yml
zuul:
prefix: /api
stripPrefix: false
ignored-services: "*"
routes:
   gateway-app:
      path: /shop/**
      stripPrefix: false
```
I just modified to gateway-app, so final URL looks like below

**case 1**
 http://localhost:9999/api/shop/customer/order
**case 2**
 http://localhost:9999/customer/order

case 2 can't block  ,even through if i use context-path no use

**Comment by ryanjbaxter** [comment]
See @spencergibb question above, can you show us what the `/routes` endpoint produces from Zuul?

**Comment by vrmsreddy** [comment]
There is no mapping like /routes in Controller

**Comment by ryanjbaxter** [comment]
`/routes` is added automatically for when you use `@EnableZuulProxy` http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#_the_routes_endpoint

**Comment by spencergibb** [comment]
And you have `spring-boot-starter-actuator` on the classpath.

**Comment by vrmsreddy** [comment]
Hi I added spring actuator to class path and tried, below is the response
```
**Response for /routes**
   /api/shop/** 
**Response for /mappings**
   /api/shop/**
   /customer/orders

**Comment by ryanjbaxter** [comment]
The behavior seems to make sense to me.  Since `/api/shop/**` is route created by Zuul than the Zuul filter will intercept the request.  Since `/customer/orders` is not it won't and there fore you wont be able to validate the token.

**Comment by vrmsreddy** [comment]
is it possible to block direct access to downstream API i.e. /customer/orders using **stripPrefix** ?,

Temporarily i am using plain old Filter and validating token, rather then overriding **ZuulFilter**

**Comment by spencergibb** [comment]
I don't understand what it means to "block direct access to downstream API".

**Comment by vrmsreddy** [comment]
i mean Case 2 as mentioned above

**Comment by ryanjbaxter** [comment]
How do you envision Zuul blocking access to that API?

**Comment by vrmsreddy** [comment]
Used different filter and working,Thanks

**Comment by vrmsreddy** [comment]
Used different filter and working,Thanks
