### ISSUE TITLE
Feign clients not appearing at Hystrix dashboard

### ISSUE THREAD

**Issue by CleitonCardoso** [spring-cloud/spring-cloud-netflix#1930]
I have an interface, all the methods are declared using feign `@RequestLine` annotation.

As I need the clients to be custom for every logged user (request scoped), I've created a bean producer for different qualifiers, inside the producer method I use `Feign.Builder` to generate the client instance.

In my application class I have these three annotations to enable those features:

```Java
@EnableHystrix
@EnableHystrixDashboard
@EnableFeignClients
```

In the application.properties I have the hystrix property set to true `feign.hystrix.enabled=true`;

I tried to add `@HystrixCommand` in all the client methods, tried also to annotate the client with `@FeignClient`

But nothing works, there is no commands for my client at hystrix dashboard.

As an alternative I've changed the `@RequestLine` to `@RequestMapping`, but now I have an exception saying that my methods have so many parameters to be build.

**Comment by ryanjbaxter** [comment]
Can you provide a sample?  To be honest I am having a hard time following your description above.  If you are using `Feign.Builder` than Spring Cloud wont automatically wrap client methods in hystrix commands.  We also disabled Hystrix when using Feign by default beginning in `Dalston.RELEASE`.

**Comment by CleitonCardoso** [comment]
@ryanjbaxter maybe I choose the wrong words.

I'm doing this:

```Java
@Headers({ "Content-Type: application/json" })
public interface MyClient {
	@RequestLine("GET /items/create_account")
	@HystrixCommand // This method is not being wrapped
	public String getInfo(@Param("itemId")  String itemId) throws IuguException;
}
	
// Client producer
@Bean
public MyClient getWithBasicAuth(@Value("${user}") String httpUser, @Value("${pass}") String httpPassword, @Value("${host}") String hostBaseUrl) {
	return Feign.builder()
			.requestInterceptor( new BasicAuthRequestInterceptor( httpUser,
					httpPassword ) )
			.logLevel( Logger.Level.FULL )
			.logger( new Slf4jLogger() )
			.errorDecoder( new MyErrorDecoder() )
			.encoder( new GsonEncoder() )
			.decoder( new GsonDecoder() )
			.target( MyClient.class, hostBaseUrl );
}
```

And what you saying is this not gonna work, right?

**Comment by eacdy** [comment]
Are you using Dalston?
If so, I'm afraid that you forget to set `feign.hystrix.enabled=true`.

**Comment by CleitonCardoso** [comment]
Simple like that.

@ryanjbaxter, @eacdy  Tks for your help guys, sorry for time wasted.
