### ISSUE TITLE
short way to configure feign client

### ISSUE THREAD

**Issue by khannedy** [spring-cloud/spring-cloud-netflix#1931]
Hi all, I have problem with current Feign Client configuration via Configuration Class.

Currently I create feign client using this way : 

```java
@FeignClient(name = "authFeign",
    url = "${service.auth.endpoint}",
    fallbackFactory = AuthFeignFallbackFactory.class,
    configuration = AuthConfiguration.class)
public interface AuthFeign {

}
```

and every time I create feign client, I create configuration class.

```java
@Configuration
public class AuthConfiguration {

  @Autowired
  private FeignAuthProperties properties;

  @Bean
  public Request.Options options() {
    return new Request.Options(
        (int) properties.getTimeUnit().toMillis(properties.getConnectTimeout()),
        (int) properties.getTimeUnit().toMillis(properties.getReadTimeout())
    );
  }

  @Bean
  public Logger.Level level(){
    return properties.getLevel();
  }

}
```

Is there any short way to configure feign client just via configuration properties? example : 

```properties
feign.authFeign.connect-timeout=2000
feign.authFeign.read-timeout=2000
feign.authFeign.log-level=basic
```

If there is no way to configure feign client via configuration properties, I will happy to contribute to this repository

Best Regards.

**Comment by ryanjbaxter** [comment]
I dont believe there are properties for this, but instead of specifying the `configuration` property for each client, if you want those values to apply to all Feign clients you can just create those beans as part of your applications configuration.

**Comment by khannedy** [comment]
hi @ryanjbaxter , I think it is very helpful if we can also configure default feign client configuration via properties, like : 

```properties
feign.client.default.connect-timeout=10000
feign.client.default.read-timeout=10000
feign.client.default.logging-level=basic
feign.client.default.retryer=...
feign.client.default.error-decoder=...
feign.client.default.request-interceptors=...
```

and if we need to create configuration per feign client, we can also override the values

```properties
feign.client.default.connect-timeout=10000
feign.client.default.read-timeout=10000
feign.client.default.logging-level=basic
feign.client.default.retryer=...
feign.client.default.error-decoder=...
feign.client.default.request-interceptors=...

feign.client.feignName.connect-timeout=2000
feign.client.feignName.read-timeout=2000
feign.client.feignName.logging-level=headers
```

**Comment by ryanjbaxter** [comment]
this would be an enhancement as far as i know

**Comment by RodrigoKobayashi** [comment]
maybe
