### ISSUE TITLE
Does Zuul Support Static Content (Angular2 js+css files) running in backend Node.js server

### ISSUE THREAD

**Issue by stiyyagura** [spring-cloud/spring-cloud-netflix#1932]
Hi 

I have requirement where I need to serve static content  (as a Resource hosted by back-end node.js server) through Zuul proxy. Is this possible at all with Zuul?
I just added `zuul.routes.static.url=http://host:port/staticresource` in the Zuul's application configuration.
But when i inspect the browser i am seeing 304 (this because zuul reidrected to /signin page where static content is available) with html is downloaded but the js and css files are not.

Please let me know whether spring cloud netflix supports static content delivery or is there any customization needs to be done.

Regards,
Satish

**Comment by stiyyagura** [comment]
This was got resolved after i have put all my css, js, images under /static folder of backend angular service.

**Comment by stiyyagura** [comment]
But i am still not clear if this is right approach. Please let me know if any correct ways of doing this.

**Comment by ryanjbaxter** [comment]
Sounds right.  There is no limitation to what Zuul serves.
