### ISSUE TITLE
Documentation refers to deprecated annotation EnableEurekaClient

### ISSUE THREAD

**Issue by yohanliyanage** [spring-cloud/spring-cloud-netflix#194]
The official documentation example for Eureka (Registering with Eureka) under URL http://projects.spring.io/spring-cloud/spring-cloud.html still refers to the @EnableEurekaClient annotation, which was changed to @EnableDiscoveryClient few revisions back.

**Comment by dsyer** [comment]
It was re-introduced (in RC1 I think) as a way for the user to say he wants Eureka discovery specifically. I added a sentence to the docs.
