### ISSUE TITLE
Canary deployment via Zuul

### ISSUE THREAD

**Issue by dmitry-naumovich** [spring-cloud/spring-cloud-netflix#1944]
Hello, everyone.
How can we implement the `canary deployment` via Zuul? 
Is it possible to retrieve some user-specific information somewhere and route users to the different versions of one microservice depending on this info?

And, please, also consider the next situation: we've got `microservice-a` and `Zuul` with route to it, both running. After we deploy a new version of this microservice, Zuul still routes to the old one. So, is it possible to dynamically route users to different versions of one microservice and how can we support the whole this `versioning` process?

**Comment by lowzj** [comment]
Spring cloud zuul and feign both use ribbon to route request to backend services. I think we can implement the `canary deployment` by implementing a customized `IRule`. This would do some work with the `ribbon` and `sc-zuul`. see issue: #1272 , just my opinion, hope helpful for you.

**Comment by spencergibb** [comment]
Here is an issue about blue/green deploys #1290
Here is an issue about versioning #1891

Currently, there is not a built-in way to route to a different service based on some request metadata.

**Comment by dmitry-naumovich** [comment]
Ok, thank you for the answer!
