### ISSUE TITLE
Add ability to replace ALL route locators

### ISSUE THREAD

**Issue by lowzj** [spring-cloud/spring-cloud-netflix#1945]
After version `1.3.0.M1`, spring-cloud provides a convenient way to add route locators into the existings: just create an another `RouteLocator` bean. But it's not very elegant if I want to **replace all the existing route locators**.

Before this commit, I can just override the method `routeLocator ` of `ZuulProxyConfiguration`:

```java
    @Bean
    @Override
    public RouteLocator routeLocator() {
         return new MyCustomRoutesLocator(this.server.getServletPrefix(), this.zuulProperties);
     }
```

After this commit, because it can't disable the existing route locators via properties, so I have to do like this:

```java
    @Bean
    @Primary
    @Override
    public CompositeRouteLocator primaryRouteLocator(Collection<RouteLocator> routeLocators) {
        routeLocators.removeIf(Objects::isNull);
        return super.primaryRouteLocator(routeLocators);
    }

    @Bean
    @Override
    public SimpleRouteLocator simpleRouteLocator() {
        return null;
    }

    @Bean
    @Override
    public DiscoveryClientRouteLocator discoveryRouteLocator() {
        return null;
    }

    @Bean
    public MyCustomRouteLocator myCustomRouteLocator() {
         return new MyCustomRoutesLocator(this.server.getServletPrefix(), this.zuulProperties);
    }
```

It seems a little weird and I can't find a better solution to do this.

And the complete feature(composed route locators) contains 2 PRs:
1. #1448 Add composed route locators
2. #1617 Compose Simple- and DiscoveryClientRouteLocator

I think that some code changes of the 1st PR should move to the 2nd PR:
* The 1st PR should just add `CompositeRouteLocator`, and add the method `primaryRouteLocator` to create the primary `RouteLocator` bean. And we maybe should consider the duplicate cases in the `get[xxx]` method of `CompositeRouteLocator`.
* Don't change the method `routeLocator` of `ZuulConfiguration` and `ZuulProxyConfiguration`; I think these changes should be moved to the 2nd PR, because that:
    1. the 1st PR provide an easy way to add additional route locators;
    2. and don't change the status quo;
    3. and also very convenient to replace existing route locator.

That's all my opinions, please correct me if anything I understand wrong.

**Comment by spencergibb** [comment]
It's a bit clunky, but you should be able to create a bean `public CompositeRouteLocator primaryRouteLocator` marked primary and it should replace the created one. The 1st PS is already merged, there's no changing it, so "the 1sst PR should just add" doesn't make sense.

I do think we need to do this:
> [make it] convenient to replace existing route locator

**Comment by spencergibb** [comment]
Maybe a simple `zuul.composite-route-locator.enabled=false`.

**Comment by lowzj** [comment]
A simple property(like `zuul.composite-route-locator.enabled=false`) might not work very well. This property means to disable `CompositeRouteLocator`, and it should not disable the other route locators: `DiscoveryClientRouteLocator`, `SimpleRouteLocator`. And `CompositeRouteLocator` doesn't do any work actually, it just delegates to other route locators.

So I think that it maybe a better way to recover `ZuulProxyConfiguration` and method `routeLocator` of `ZuulConfiguration`. This will achieve the 3 points I commented above.

If possible, I'm glad to submit a PR to do this.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
