### ISSUE TITLE
Harmonize turbine and hystrix stream destinations

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#1948]
We have a little hack in `TurbineStreamAutoConfiguration` where we set the input destination to match the hystrix output. But it would be neater, and would require fewer contortions in testing the turbine server, if they just matched out of the box. Probably a good change to make in 2.0.

**Comment by fdimauro** [comment]
Any update on this issue? I can not get this to work still.

**Comment by spencergibb** [comment]
This was never a problem, but a work around. AFAIK, it still works. Please open a new issue and supply as much information as possible.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
