### ISSUE TITLE
hystrix - best practise for logging exceptions

### ISSUE THREAD

**Issue by jkirsch** [spring-cloud/spring-cloud-netflix#195]
I'm trying to log the "potential" exception of longRunning within fallback

```java
@Component
public class MyService {

  @HystrixCommand(fallbackMethod = "fallback")
  public void longRunning() {
     // this could fail
  }

  public void fallback() {
    // fallback code
  }
}
```

Trying to access `HystrixRequestLog.getCurrentRequest()` within the fallback method throws

> java.lang.IllegalStateException: HystrixRequestContext.initializeContext() must be called at the beginning of each request before RequestVariable functionality can be used.

Is there any documented best practise?

Could the fallback method additionally offer access to the `HystrixCommand` object, which has the exception trace if any ...?

**Comment by dsyer** [comment]
> Could the fallback method additionally offer access to the HystrixCommand object,

I don't think that is possible with the current implementation of Javanica. I'm not a huge fan of Javanica though so there is a good chance we'll replace or enhance it at some point.

You can log the exceptions using `logging.level.com.netflix.hystrix.AbstractCommand: DEBUG`. Or you can set up the `HystrixRequestLog` in the caller of `MyService`, but it isn't done for you.

**Comment by jkirsch** [comment]
Thanks for the information - setting the logging level at least logs it now - although it looks quite serious as the complete stack trace is logged.

**Comment by joshuawhite929** [comment]
Dave,

Replacing javanica sounds like an interesting idea.  Out of curiosity, what do you see as javanica shortcomings?  Whats on the wish list?

**Comment by dsyer** [comment]
@joshuawhite929 I think the async and `Observable` support was an afterthought (the programming model is ugly anyway). It will also be difficult (I think) to re-use javanica for other circuit breaker libraries. I don't have any concrete ideas about how to replace it, so nothing will happen in the short term anyway.

**Comment by pcornelissen** [comment]
I ran into the same problem and solved it by switching from javanica to an anonymous class. Then I can access the exception:

```java
    private HystrixCommand<Collection<Resource<ZipCodeData>>> getZipCodeDataCommand(String location) {
        return new HystrixCommand<Collection<Resource<ZipCodeData>>>(
                HystrixCommand.Setter
                        .withGroupKey(HystrixCommandGroupKey.Factory.asKey("geodata"))
                        .andCommandKey(HystrixCommandKey.Factory.asKey("getZipCodeData"))
                        .andCommandPropertiesDefaults(
                                HystrixCommandProperties.Setter()
                                        .withExecutionTimeoutInMilliseconds(TIMEOUT)
                        )
        ) {
            @Override
            protected Collection<Resource<ZipCodeData>> run() throws Exception {
                HashMap<String, Object> arguments = new HashMap<>();
                arguments.put("searchterm", location);
                ParameterizedTypeReference<PagedResources<Resource<ZipCodeData>>> responseType = new ParameterizedTypeReference<PagedResources<Resource<ZipCodeData>>>() {
                };
                String href = homeResourceRepository.getHomeLink("search", "geodata").expand(arguments).getHref();
                URI uri = new URI(href);
                ResponseEntity<PagedResources<Resource<ZipCodeData>>> byZip = restTemplate.exchange(uri, HttpMethod.GET, null, responseType);
                return byZip.getBody().getContent();
            }

            @Override
            protected Collection<Resource<ZipCodeData>> getFallback() {
                Exception exception = executionResult.getException();
                if(exception==null){
                    LOG.warn("geodata fetch fallback! ZipCodeData for: '{}' NO EXCEPTION", location);
                }else {
                    LOG.warn("geodata fetch fallback! ZipCodeData for: '{}' Error:{}", location, exception.getMessage());
                    LOG.debug("Stacktrace: ", exception);
                }
                return new ArrayList<>();
            }
        };
    }
```

**Comment by spencergibb** [comment]
Closed for lack of feedback. Please, reopen if there is something new to add.
