### ISSUE TITLE
Enable EurekaClient in AutoConfiguration

### ISSUE THREAD

**Issue by helpermethod** [spring-cloud/spring-cloud-netflix#1959]
Hi,

I'm currently writing an integration for Spring Cloud Eureka Client where I want to do the following:

* create a bean which requires a EurekaClient instance
* enable the Eureka Client autoconfiguration

something like this:

```
@Configuration
@EnableEurekaClient
public class MembraneEurekaAutoConfiguration {
    @Bean
    public EurekaInterceptor eurekaInterceptor(EurekaClient eurekaClient) {
        return new EurekaInterceptor(eurekaClient);
    }
}
```

The problem is that my autoconfiguration probably need to run after the Eureka Client autoconfiguration, which I suppose is possible with `@AutoConfigureAfter` but the questions remains how I can enable the Eureka Client autoconfiguration (if at all)?

**Comment by spencergibb** [comment]
Are you having an actual problem or anticipating a problem? Seems like it should be ok.

**Comment by helpermethod** [comment]
Thanks for having a look at it!

You're correct, the problem was something else. Closing the issue.
