### ISSUE TITLE
Content-Type: multipart/form-data; boundary has `/` 

### ISSUE THREAD

**Issue by fudali113** [spring-cloud/spring-cloud-netflix#1961]
[https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/FormBodyWrapperFilter.java#L100](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/FormBodyWrapperFilter.java#L100)
```java
MediaType mediaType = MediaType.valueOf(contentType);
```
[https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/MimeType.java#L189-L202](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/MimeType.java#L189-L202)

```java
        /**
	 * Checks the given token string for illegal characters, as defined in RFC 2616,
	 * section 2.2.
	 * @throws IllegalArgumentException in case of illegal characters
	 * @see <a href="http://tools.ietf.org/html/rfc2616#section-2.2">HTTP 1.1, section 2.2</a>
	 */
	private void checkToken(String token) {
		for (int i = 0; i < token.length(); i++ ) {
			char ch = token.charAt(i);
			if (!TOKEN.get(ch)) {
				throw new IllegalArgumentException("Invalid token character '" + ch + "' in token \"" + token + "\"");
			}
		}
	}
```
my content-type is `multipart/form-data; boundary=jOO76.g5pHFw2qNN6SMWTDb4O8fK.aCMyTLxF4iqwYLI_xNRMV_-VC1/D532GIRamhNyW_`

because  `MediaType mediaType = MediaType.valueOf(contentType);` throw Exception, so FormBodyWrapperFilter shouldFilter() return false;   This leads to the forwarding requests  throw 
 SocketTimeoutException:read time out exception 

But I didn't see the agreement expressly prohibit using ` / ` instructions in a boundary field

**Comment by stiyyagura** [comment]
If you have an issue with multi-form type it could be because you are using a release which is having a bug. Please upgrade to latest you will not see that issue.
