### ISSUE TITLE
Loadbalancing with Zuul and Ribbon without discovery

### ISSUE THREAD

**Issue by oterrien** [spring-cloud/spring-cloud-netflix#1966]
Hi,
I have two instances of a same service (URL are different). Let's call them "homeService"
I have a client which wants to call one of these services (but it doesn't care which one).
I would like to configure a zuul gateway to perform the routing AND the load balancing between both homeServices. 
Is it possible?

**Comment by spencergibb** [comment]
Yes, if you don't have eureka as a dependency, or you turn it off, or if you explicitly configure a configuration based server list.

**Comment by oterrien** [comment]
Thanks Spencer. 
I would like to do this without discovering my services (eureka or consul). Where can I find any example ?

**Comment by stiyyagura** [comment]
You can have configuration like 
`zuul.routes.serviceid.url=Host` where the services are running
here serviceid is nothing but route name configured for that host. Ex: serviceid can be `abc`
in this case the route becomes `abc` like `zuul.routes.abc.url=Host`

**Comment by stiyyagura** [comment]
```
 users:
  ribbon:
    listOfServers: example.com,google.com
```

**Comment by ryanjbaxter** [comment]
http://cloud.spring.io/spring-cloud-static/Dalston.RELEASE/#spring-cloud-ribbon-without-eureka

**Comment by oterrien** [comment]
Ok it runs. Thx.
Now, when I started two servers, load balancing is done in my zuul gateway.
**But**, assuming one of my loadbalanced service is shutdown (kill -9), the loadbalancing fails with a error=500 when it tries to ping the killed server. 
Is it possible to fix?
