### ISSUE TITLE
feign.hystrix.enabled=true

### ISSUE THREAD

**Issue by dicanoza** [spring-cloud/spring-cloud-netflix#1968]
I can't use Yaml or even set this property on a application.properties, it must be on the **bootstrap.properties**, is the only way to turn on the fallback. Took me some hours to figure this out. 

Is this a bug or a expected behavior?

**Comment by spencergibb** [comment]
It doesn't sound like it should be a problem. It is not expected behavior.

**Comment by spencergibb** [comment]
I am unable to duplicate the problem (it works fine in application.properties). Can you provide a sample that recreates the problem?

**Comment by dicanoza** [comment]
You're right, it works on application.properties, I should have done something wrong. But still does not work on yml files.

**Comment by spencergibb** [comment]
Works fine in application.yml for me as well.

**Comment by dicanoza** [comment]
Oh God! I feel stupid. The error was a space character...
Thanks for being patient and my apologies for wasting your time.
