### ISSUE TITLE
Bug - SecurityContext passed through to Hystrix thread

### ISSUE THREAD

**Issue by chrisdadej** [spring-cloud/spring-cloud-netflix#1969]
Reading the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.3.0.RELEASE/), assuming the default and recommended use of Thread Isolation for Hystrix, it appears that in order to have the SecurityContext propagated through to the Hystrix thread all one needs to do is set `hystix.shareSecurityContext = true`.

However this does not work and looking at the code (`HystrixSecurityAutoConfiguration.java`), if I've understood the following bit correctly then `hystrix.shareSecurityContext` on it's own will do nothing unless you also have `feign.hystrix.enabled = true` set, regardless of your usage of Feign - this is because of the `AllNestedConditions`.

```
	static class HystrixSecurityCondition extends AllNestedConditions {
		public HystrixSecurityCondition() {
			super(ConfigurationPhase.REGISTER_BEAN);
		}

		@ConditionalOnProperty(name = "feign.hystrix.enabled", matchIfMissing = false)
		static class HystrixEnabled {}

		@ConditionalOnProperty(name = "hystrix.shareSecurityContext")
		static class ShareSecurityContext {}
	}
```

I've been able to confirm that adding in the additional parameter (i.e. `feign.hystrix.enabled = true`) does indeed resolve the issue on my end but I figured it was best to confirm. Simplest solution is to simply update the documentation to state that both parameters need to be set to true. Ideally, it would be better to separate the two if at all possible - although my assumption would be that if you need the SecurityContext propagated then you'll want it for both non-feign and feign calls.

For reference, my REST API's all use `@HystrixCommand(fallbackMethod="xxx")` which is where I noticed this issue. Inside the API call you don't always get the correct SecurityContext.

**Comment by spencergibb** [comment]
Yeah, that is odd. @ryanjbaxter can you comment on why you added that?
