### ISSUE TITLE
Connection leaked in zuul

### ISSUE THREAD

**Issue by lly5044** [spring-cloud/spring-cloud-netflix#1970]
This happens When zuul run with HttpClient and retry policy is ribbon.retryableStatusCodes=404,500
If zuul get a response with status code 500, it will throw a RetryableStatusCodeException and cause a connection CLOSE_WAIT. This is not going to happen when I use OkHttp. But I am not able to change the ribbon.MaxTotalConnections when using OkHttp. Is there any solution?
the spring cloud version is Dalston.RELEASE
thank you

**Comment by lly5044** [comment]
Now I found that happened when using okhttp too.

**Comment by ryanjbaxter** [comment]
You mean the connection is never closed for each retry?

**Comment by lly5044** [comment]
yes, And in my test, this may help solve the problem @ryanjbaxter 
<pre><code>  
        RetryCallback<OkHttpRibbonResponse, Exception> retryCallback  = new RetryCallback<OkHttpRibbonResponse, Exception>() {
        @Override
        public OkHttpRibbonResponse doWithRetry(RetryContext context) throws Exception {
            //on retries the policy will choose the server and set it in the context
            //extract the server and update the request being made
            OkHttpRibbonRequest newRequest = ribbonRequest;
            if(context instanceof LoadBalancedRetryContext) {
                ServiceInstance service = ((LoadBalancedRetryContext)context).getServiceInstance();
                if(service != null) {
                    //Reconstruct the request URI using the host and port set in the retry context
                    newRequest = newRequest.withNewUri(new URI(service.getUri().getScheme(),
                            newRequest.getURI().getUserInfo(), service.getHost(), service.getPort(),
                            newRequest.getURI().getPath(), newRequest.getURI().getQuery(),
                            newRequest.getURI().getFragment()));
                }
            }
            if (isSecure(configOverride)) {
                final URI secureUri = UriComponentsBuilder.fromUri(newRequest.getUri())
                        .scheme("https").build().toUri();
                newRequest = newRequest.withNewUri(secureUri);
            }
            OkHttpClient httpClient = getOkHttpClient(configOverride, secure);

            final Request request = newRequest.toRequest();
            Response response = httpClient.newCall(request).execute();
            if(retryPolicy.retryableStatusCode(response.code())) {
                response.close(); //close here
                throw new RetryableStatusCodeException(RetryableOkHttpLoadBalancingClient.this.clientName, response.code());
            }
            return new OkHttpRibbonResponse(response, newRequest.getUri());
        }
    };
</code></pre>

**Comment by lly5044** [comment]
if use apache httpclient we can add httpUriRequest.abort(); before throw new RetryableStatusCodeException

**Comment by ryanjbaxter** [comment]
Thanks for the suggestion, I will take a look at this when I get some time

**Comment by lly5044** [comment]
ok i will have a look, i find feign may have the same problem now in RetryableFeignLoadBalancer.

**Comment by lly5044** [comment]
it works well in my environment ^_^ @ryanjbaxter

**Comment by ryanjbaxter** [comment]
@lly5044 thanks.  I made the change in `RetryableFeignLoadBalancer` as well if you want to try that as well.

**Comment by KeiichiTheOtaku** [comment]
@ryanjbaxter Will this fix be wrapped back into a Camden release, or only be included in a forthcoming Dalston.SR1?

**Comment by ryanjbaxter** [comment]
Right now we have no plans on doing another Camden release.
