### ISSUE TITLE
Is spring-cloud-netflix-turbine ONLY support eureka????????

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-netflix#1975]
i need turbine to combine the data from cluster ,but i failed to setup via zookeeper,i see that spring-cloud-netflix-turbine invoke a eureka-client via maven but i cant see other framework like zookeeper client ,so Is spring-cloud-netflix-turbine ONLY support eureka

**Comment by yangzii0920** [comment]
any update?

**Comment by spencergibb** [comment]
This was closed and it should work with zookeeper and consul

**Comment by yangzii0920** [comment]
thanks. @spencergibb
