### ISSUE TITLE
Decompress Zuul Request

### ISSUE THREAD

**Issue by indrabasak** [spring-cloud/spring-cloud-netflix#1976]
I am using Zuul server with different types of filters - pre, route, post, etc. Some of these filters checks or manipulates a request body. I am running into issues while trying to handle  compressed request bodies. 

To solve this problem, I tried decompressing the request body at the filter level. I think the strategy of decompression at the filter level is very inefficient. Is there an in-built strategy or property which turns on decompression at the Zuul server level?

**Comment by spencergibb** [comment]
zuul is just a servlet in a spring-boot application.

**Comment by OlgaMaciaszek** [comment]
Closing as the answer has been provided.
