### ISSUE TITLE
how to enable turbine https?

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-netflix#1978]
![image](https://cloud.githubusercontent.com/assets/16620268/26385954/cd4eaed2-4075-11e7-9994-596c29a3bcd6.png)

**Comment by ExtremeYu** [comment]
turbie want to get attrbuits to make sure use https or not ,but how to configure it?

**Comment by ryanjbaxter** [comment]
Are you using Eureka?  I believe if the service instance has the secure port property set in Eureka than that should enable `https`.  I could be wrong though.

**Comment by ExtremeYu** [comment]
no ,but zookeeper,the code showing in the picture is some of source code  of the spring-cloud-netfilx-turbine,it indicate that turbine need some attributes of Instance via Map<String,Object>, if attributes  contains **securePort** it will construct https url,but i dont know where to set that attributes called **securePort**  can you tell me?

**Comment by ExtremeYu** [comment]
some people aske the same questions in stackoverflow ,but no response

**Comment by spencergibb** [comment]
I don't think it's a problem with turbine, but with spring-cloud-zookeeper and support for secure port.

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-zookeeper/issues/132
