### ISSUE TITLE
how to route request using both domain&url

### ISSUE THREAD

**Issue by surlymo** [spring-cloud/spring-cloud-netflix#1980]
when i use spring cloud zuul, I wanna route request using **both domain & url** just like what nginx's upstream config can do.
example: route http://www.google.com/helloWorld to foo serviceId.

but now i only found that i can route by url.
so, how to deal with it?

**Comment by ryanjbaxter** [comment]
Is the request to `http://www.google.com/helloWorld` being made by another service in your application?  Zuul is a reverse proxy, it will route requests to other services.  It is not going to intercept requests made by services and route them accordingly.

**Comment by surlymo** [comment]
@ryanjbaxter 
for example, i have two domain that point to the same zuul address 172.1.1.1
www.google.com  -> 172.1.1.1
www.yahoo.com -> 172.1.1.1

i wanna use zuul to route www.google.com/movie/3 to serviceA application
while www.yahoo.com/movie/3 to serviceB service application

but i found that the zuul reverse proxy's **DiscoveryClientRouteLocator** only using path to find the serviceId, if i meet the above case, the route result maybe wrong

**Comment by ryanjbaxter** [comment]
Yes Zuul will only proxy request by routes not by host name.

**Comment by surlymo** [comment]
@ryanjbaxter 
we need this feature, may spring-cloud support this ?

**Comment by ryanjbaxter** [comment]
If you would like to get together a PR for this feature that would be welcome.  If not there would need to be sufficient community demand for something like this for us to have to implement it.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

Check out spring cloud gateway.
