### ISSUE TITLE
route request to a different serviceId for debug

### ISSUE THREAD

**Issue by mind-kdas** [spring-cloud/spring-cloud-netflix#1981]
I read many places that zuul can be used to route to a different cluster using filters. But I was not able to get any example filter(saw 1 which dint work https://scs.cfapps.io/zuul.html). If something is there already , please point me to it. Else , please provide a filter.
I am trying to do something similar in that, I want to route to another ServiceId(clientHelloBackup) based on a criteria. 

Sorry for bothering for a very simple problem, but believe me I have spent more than an hour on stackoverflow and google already.  Thanks in advance . 

zuul:
  prefix: /api
  routes:
    my-service:
      path: /clientHello/**
      serviceId: clientHello
    my-backup:
      path: /clientHelloBackup/**
      serviceId: clientHelloBackup

**Comment by ryanjbaxter** [comment]
Have you looked at the filters in https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters?

**Comment by spencergibb** [comment]
Also see https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/QueryParamServiceIdPreFilter.java

**Comment by mind-kdas** [comment]
Thanks for such quick response. Really appreciate that. 
I was actually making a mistake in ordering the filter before PreDecoration, so it was not routing to the serviceId I was setting in filter. Once I changed the order to 100 , it routed properly. 
I have just started exploring zuul-filter, which seem to be very powerful feature. But there are few resources available. _If you could point me to some cookbook or resources which would help me use it properly, it would be awesome._
