### ISSUE TITLE
Support the new OptionalDecoder

### ISSUE THREAD

**Issue by afillatre** [spring-cloud/spring-cloud-netflix#1982]
Feign released a new `OptionalDecoder` with it's version 9.5.0 (in the feign-java8 module). It would be nice be be able to configure it in an easy way.

Since the actual decoder bean is annotated with `@OnMissingBean`, we either:
- need to create the whole decoder chain in a custom configuration class (not very resilient to updates)
- need to create a custom configuration class that will auto-configure after the `FeignClientsConfiguration` one, and inject the existing Decoder bean into a new `OptionalDecoder` bean

Both solutions do not seem very good for maintenance. Do you see how this could be done in a more seamless way ?

**Comment by spencergibb** [comment]
This would target 2.0.0.x since java 8 will be the baseline then.

**Comment by LtTempletonPeck** [comment]
We were looking at the exact same thing the other day and hit the same issue. Other Spring projects use the pattern of a Customizer (such as ClusterBuilderCustomizer in Boot for Cassandra) as an extension point to allow user configuration to be added to beans created as part of autoconfig. Would be an enhancement that fits now and for future requirements.

**Comment by spencergibb** [comment]
You can already declare custom decoders as beans using `@FeignClient(configuration)`.

**Comment by spencergibb** [comment]
Closed via c544f4aef63ce00ccd2122cde33d2b0fef2361d4
