### ISSUE TITLE
issue : setting random port for eureka client within a scope

### ISSUE THREAD

**Issue by Ikki-Dai** [spring-cloud/spring-cloud-netflix#1986]
when i try to set eureka client port like below
server:
  port: ${random.int[9090,9099]}

but eureka sever get error registered ports

**Comment by ryanjbaxter** [comment]
I just created a Eureka client app and set `server.port` to `${random.int[9090,9099]}` and the client started up fine.  Can you provide more details on how to reproduce the problem or provide a sample application?

**Comment by Ikki-Dai** [comment]
used version as below :
springBootVersion = '1.5.2.RELEASE'
mavenBom ':spring-cloud-dependencies:Dalston.RELEASE'
compile ':spring-cloud-starter-eureka'

From the console screenshot, we can find that it used different ports, but only the server ports is used actually, and also eureka server got an error registered port.

![ss](https://cloud.githubusercontent.com/assets/16415439/26491205/3521b30c-4241-11e7-97b6-8ead18b195e7.png)

**Comment by spencergibb** [comment]
`random.int` issues a new value every time it is read (or every time a property with a placeholder is read. It is not something we plan to support. setting the port to 0 lets the container/os determine the port.
