### ISSUE TITLE
SurgicalDebugFilter class cast issue for zuul.debug.vip/host

### ISSUE THREAD

**Issue by mind-kdas** [spring-cloud/spring-cloud-netflix#1987]
I am trying to use SurgicalDebugFilter. Implemented the patternMatches() with simple return true.
**Sample zuul/application.yaml:**
```
zuul:
  debug:
    vip: http://localhost:9010
    host: http://localhost:9010
```
I have another zuul instance running on  http://localhost:9010 backed by a eureka server/client.
Once filter is invoked , I get class cast error:

> Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'http://localhost:9010' with class 'java.lang.String' to class 'java.net.URL'
>         at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405) ~[groovy-2.4.10.jar!/:2.4.10]
>         at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319) ~[groovy-2.4.10.jar!/:2.4.10]

As per the code of  SurgicalDebugFilter(https://github.com/Netflix/zuul/blob/v1.3.0/zuul-core/src/main/groovy/com/netflix/zuul/filters/SurgicalDebugFilter.groovy):
 ```
 RequestContext.currentContext.routeHost = routeHost.get();
       RequestContext.currentContext.routeVIP = routeVip.get();
```
This would result in error anyway since RequestContext.currentContext.routeHost is URL type but routeHost.get() would return string. So, the class cast exception seems fine. Let me know if I am using it wrongly or my understanding is incorrect. 

Thanks in advance !

**Comment by ryanjbaxter** [comment]
This seems like a Netflix issue and not a Spring Cloud Netflix issue.

**Comment by mind-kdas** [comment]
Thanks for your input Ryan. 
But since this feature (zuul to zuul debug routing) so popular and is already being used by others as I could see on the net, I was wondering if I am doing some silly mistake. It would be great if you could point me to a working surgicalFilter instance on github (if you have it working) . 
Also, I tried this with version 'Dalston.SR1'.

**Comment by ryanjbaxter** [comment]
Your question is better asked in the Netflix Zuul project, it doesnt seem to have anything to do with Spring Cloud.
