### ISSUE TITLE
HystrixCommand doesn't work in Zuul Filters

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1988]
`@HystrixCommand` doesn't work on a `ZuulFilter.run` method. The attached Gradle project demonstrates the issue. There are 2 tests, all you've to do is run the `HystrixTimeoutTest`.

It seems to be an issue with bean proxy, because if I extract the content of the method in another `public` method and use the following trick to call it, Hystrix kicks in.

```
public class AuthFilter extends ZuulFilter {
    @Autowired
    private ApplicationContext ctx;

    @Override
    // HystrixCommand doesn't work here
    public Object run() {
        AuthFilter af = ctx.getBean(AuthFilter.class);
        af.runInternal();
    }

    // HystrixCommand works here
    public Object runInternal() {
    }
}
```

[demo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1030638/demo.zip)

**Comment by asarkar** [comment]
I think I know why this issue is happening. `ZuulFilter.runFilter` method calls `run` from the same class, thus the proxying doesn't work.

Is there anything that can be done, other than what I showed above?

**Comment by spencergibb** [comment]
Not that I know of. In general, we don't use javanica (`@HystrixCommand`) in zuul filters.

**Comment by asarkar** [comment]
@spencergibb I was forced too, because `@FeignClient` doesn't yet support ignoring exceptions. I believe I've a ticket opened for it.
