### ISSUE TITLE
Not able to register a service as Eureka Client when using Custom autoconfiguration class

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-netflix#1989]
Hi,

I had an issue when trying to make a service as eureka client using spring profile and a custom autoconfiguration class which makes applies the @EnableEurekaClient annotation.

I raised the issue because I got an exception and also the service was not registered as Eureka Client during startup. I used Spring Boot 1.5.3 and Dalston.RELEASE for the service and spring cloud.

I raised the issue earlier for it. **Spring Boot Service fails on startup when using custom autoconfiguration class for enabling/disabling eurekaclient #1933**

The issue now seems closed which a fix in Dalston.SR1. I used Dalston.SR1 along with Spring Boot 1.5.3 and when I tested the exception is gone but the service is not getting registered as eureka client.

I made a comment about this in my original issue. I thought it would be better to track it as a separate issue even tho' my original issue still exists.

Anyway, the updated code used to reproduce the problem is as below.
https://github.com/bsridhar123/demo-code

Can you please help me with this.

**Comment by bsridhar123** [comment]
Any updates on this issue.

**Comment by spencergibb** [comment]
Add
```
@AutoConfigureBefore(EurekaClientAutoConfiguration.class)
public class ServiceRegistryConfiguration {
    //...
}
```

**Comment by jberk** [comment]
+1 on this.  we had the same issue.  The jump from camden to dalston broke service discovery auto config until we added the above annotation.

**Comment by spencergibb** [comment]
@jberk did you see my solution above?

**Comment by jberk** [comment]
@spencergibb - yes, that's what I was +1'ing :-)
