### ISSUE TITLE
Hystrix doesn't work with version Dalston 

### ISSUE THREAD

**Issue by devkerby** [spring-cloud/spring-cloud-netflix#1991]
it works fine with Camden

**Comment by spencergibb** [comment]
I'm afraid "doesn't work" isn't enough information. What is your configuration? How are you using it? What are you expecting and what is actually happening?

**Comment by asarkar** [comment]
@devkerby If you're seeing a change that Feign client doesn't come with Hystrix wrapping anymore, that is indeed a change from Camden and you need to explicitly enable using `feign.hystrix.enabled=true`

**Comment by alwaysc** [comment]
@asarkar is right, feign.hystrix.enabled set default value is false in Dalston

**Comment by ryanjbaxter** [comment]
Yes but as @spencergibb said "doesn't work" is pretty broad.  I will close this for now if setting `feign.hystrix.enabled` to `true` does not fix the issue than please reopen this.
