### ISSUE TITLE
Registering single client as multiple applications in Spring Eureka

### ISSUE THREAD

**Issue by thirunar** [spring-cloud/spring-cloud-netflix#1992]
We are using Spring Eureka for service registry in our project. There are 12 microservices and each microservices serves 4-5 functionality.

For example a microservice called "MathOperations" serves functions like addition, subtraction, multiplication. With the help of Eureka, if I want to call one of the method, I will be invoking a REST call "http://MathOperations/addition". Now, the problem is, I dont want "MathOperations" to be there in url. I just want to call "http://addition", it should invoke the mathoperations addition method and respond with the result. It is ensured that, all the functionalities will have a unique name across microservices.

This is my thought process (correct me if I'm wrong), Can I register each functionality as a service to Eureka?

**Comment by ryanjbaxter** [comment]
No I dont think so.

**Comment by spencergibb** [comment]
How would the service know what it was performing `addition` without the `/addition` path?

**Comment by thirunar** [comment]
Can we register an application as multiple service like "addition", "subtraction" etc.,? Then, when we hit http://addition, it has to be routed to addition method.

**Comment by spencergibb** [comment]
No. Service Discovery is limited to, essentially, the host and port the service is running on.
