### ISSUE TITLE
Decouple hystrix.shareSecurityContext and feign.hystrix.enabled

### ISSUE THREAD

**Issue by marcoschulte** [spring-cloud/spring-cloud-netflix#1993]
`hystrix.shareSecurityContext`is only working if also `feign.hystrix.enabled` is set.
We don't see any reason why this should be coupled, as we are not using feign at all but still need access to the SecurityContext in our Hystrix commands.

We would suggest to remove the `org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration.HystrixSecurityCondition.HystrixEnabled` condition.

**Comment by ryanjbaxter** [comment]
I think this was fixed as part of #1969.

**Comment by marcoschulte** [comment]
Sorry, you're right. Didn't find that issue. Good news it's already fixed.
