### ISSUE TITLE
mixed eureka/non-eureka based service usage

### ISSUE THREAD

**Issue by dpy1123** [spring-cloud/spring-cloud-netflix#1995]
It works well when I just set `ribbon.eureka.enabled=false` and config all my service using `xxx.ribbon.listOfServers` .

And I want eureka based services can be auto discovered. So when I comment out `ribbon.eureka.enabled=false` and config non-eureka based service using `xxx.ribbon.eureka.enabled=false` and `xxx.ribbon.listOfServers`, it won`t work as expected.

Is there any references on how to use @feginclient when some of yours services are eureka based and others are static url based services?  

thx~

**Comment by ryanjbaxter** [comment]
I dont think `xxx.ribbon.eureka.enabled=false` is valid.  You can specify a URL in your `@FeignClient` annotation.

**Comment by spencergibb** [comment]
You can set `xxx.ribbon.NIWSServerListClassName=com.netflix.loadbalancerConfigurationBasedServerList` then for `xxx`, `listOfServers` will work.

**Comment by dpy1123** [comment]
Ok, it works well 👍
Thanks @spencergibb

**Comment by eacdy** [comment]
@spencergibb 
I think it's 
`xxx.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList`.
Did you missed a point?

**Comment by dpy1123** [comment]
@eacdy yes, a point is missing, but I get the point. Thx~
