### ISSUE TITLE
eurekaAutoServiceRegistration No Scope registered for scope name 'refresh'

### ISSUE THREAD

**Issue by yongsudehanzi** [spring-cloud/spring-cloud-netflix#1996]
spring boot:1.5.3.RELEASE
spring cloud:Dalston.RELEASE

eureka client code:

![qq 20170530162622](https://cloud.githubusercontent.com/assets/14308649/26574694/e533f258-4554-11e7-997f-d139f1cb2db1.png)

when i start external tomcat，No Scope registered for scope name 'refresh'

![qq 20170530162708](https://cloud.githubusercontent.com/assets/14308649/26574693/e53311bc-4554-11e7-9f43-c73b6fc0afe9.png)
![qq 20170530162725](https://cloud.githubusercontent.com/assets/14308649/26574692/e53209fc-4554-11e7-8a67-b6b6ed6840d9.png)

can your help me?thank

**Comment by ryanjbaxter** [comment]
Can you provide a sample project that reproduces the problem?

**Comment by yongsudehanzi** [comment]
sorry,i kown the error,it is include other spring boot maven module,two loading spring boot project

**Comment by yongsudehanzi** [comment]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)

xxxxxxxxxxxxxxxxx..................
xxxxxxxxxxxxxxx................

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)



two load Spring Boot，second loading time appear exception。
