### ISSUE TITLE
Feign Retryer doesn't work with Hystrix

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1998]
It appears that with Hystrix enabled, I can't use Feign Retryer. Hystrix intercepts and throws an exception before the retryer gets it's chance. Demo project attached with failing test.

[demo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1040391/demo.zip)

**Comment by ryanjbaxter** [comment]
One problem here is that the `Retryer` is not passed to the Feign client builder when [using Hystrix](https://github.com/spring-cloud/spring-cloud-netflix/blob/c89645e0699342c55314e3ef7a2c6eb8b6ac90de/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsConfiguration.java#L103) like it is when [Hystrix is not used](https://github.com/spring-cloud/spring-cloud-netflix/blob/c89645e0699342c55314e3ef7a2c6eb8b6ac90de/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientsConfiguration.java#L117).

Then there is complication of the Ribbon `RetryHandler` ontop of this.

This is one of the reasons why we chose to centralize on Spring Retry.  Is there a reason why you wouldn't want to just put Spring Retry on the classpath and go down that path?

**Comment by asarkar** [comment]
> Is there a reason why you wouldn't want to just put Spring Retry on the classpath and go down that path?

There isn't, except the fact that the more I learn about the Hystrix-Feign-Ribbon stack, it seems to be that the support in Spring Cloud is not as well-thought as I normally find elsewhere. There are gotchas, and loopholes, and "oh, that use case doesn't work". In the minimum, I think it should be clearly documented what works and what doesn't, otherwise people like me are trying to use components from core Netflix stack and being thrown off when those don't work.

**Comment by ryanjbaxter** [comment]
We have documented the [correct way to retry requests](http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#retrying-failed-requests).  We do not document using the Feign `Retryer` or the Ribbon `RetryHandler` because we have done work to support Spring Retry across Ribbon, Feign, and Zuul as a way to make it easier for users to consistently retry failed requests.  We are not going to support any other method going forward, so if using Spring Retry does not meet your needs please open an issue so we can address them.

**Comment by fiunchinho** [comment]
Do I need to do anything besides adding spring-retry to my classpath? Like adding an annotation? I don't see my Feign client retrying on failures :/

**Comment by spencergibb** [comment]
@fiunchinho please open a new issue, with much more information than you are currently supplying.

**Comment by khushbuv** [comment]
Does this retryer now work with Hystrix. Feign FallBack gets called and then retryer doesnt work. I am trying to make configurable retry work in my project. I am warpping @FeignClient with hystrix by the use of fallbackmethod. But on error it goes straight to fallback and then no retry is attempted. Can any one help in this regard?

**Comment by ryanjbaxter** [comment]
It will retry requests if you configure it correctly.  Once hystrix kicks in no retries will occur.

**Comment by kroka** [comment]
It may be worth mentioning that retries are only triggered for exceptions of type `feign.RetryableException` (but not for `feign.FeignException`). You might have to adjust your `feign.codec.ErrorDecoder` to return exceptions of the proper type.
