### ISSUE TITLE
Delegate to a common Ribbon client for load balancing and retring instead of replicating the logic

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#1999]
Following up on https://github.com/spring-cloud/spring-cloud-netflix/issues/1967#issuecomment-304901701

@asarkar said:

> There are load balancing clients in Ribbon general, `org.springframework.cloud.netflix.feign.ribbon.LoadBalancerFeignClient`, for example, and third-party specific, `org.springframework.cloud.netflix.ribbon.okhttp.OkHttpLoadBalancingClient`, without any apparent link between them. I'd think that a load balancing Feign client would delegate to one of the third-party specific Ribbon client, like OkHttp, but that doesn't seem to be the case.

@ryanjbaxter said:

> There are currently 3 ways HTTP requests can be made in Spring Cloud Netflix. Feign, Zuul (via a proxy) and `LoadBalanced` `RestTemplate`s. I understand your confusion since all 3 use Ribbon so it would seem logical that there would be a common "client" that is used by all. Unfortunately that is not the case as the moment so there different retryable versions of each as well. I am not sure of the history as to why there isn't a single client implementation that is used but it might be something to look into in the future.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
