### ISSUE TITLE
NoopDiscoveryClientAutoConfiguration has a dependency on running in Web environment

### ISSUE THREAD

**Issue by gmucha** [spring-cloud/spring-cloud-netflix#200]
Trying to run with eureka.client.enabled=false in a non-servlet environment (ie. a HTTP server running on Netty), context initialization crashes. This seems to be offending section, as `EmbeddedWebApplicationContext` inherits from `GenericWebApplicationContext` - which will not be present if spring-web is not a dependency (granted, Boot may be equally at fault, as `EmbeddedWebApplicationContext` is a core Boot class).

```java
 if(this.context instanceof EmbeddedWebApplicationContext) {
            EmbeddedServletContainer container = ((EmbeddedWebApplicationContext)this.context).getEmbeddedServletContainer();
            if(container != null) {
                port = container.getPort();
            }
        }
````

**Comment by gmucha** [comment]
Just thinking, if making `NoopDiscoveryClientAutoConfiguration` annotated with  `@ConditionalOnWebApplication` wouldn't resolve the issue

**Comment by dsyer** [comment]
It's definitely a bug, but why do you have eureka on the classpath if you have `eureka.client.enabled=false` and `@EnableDiscoveryClient` (given that we only support Eureka right now anyway)?

**Comment by gmucha** [comment]
Mainly a fallback scenario - we don't want to run this in certain development profiles - relying on manually provided instance addresses - and switch to Eureka once we go into integration/certification.

**Comment by dsyer** [comment]
You need `spring-web` for `RestTemplate` so it's common enough that, while we can maybe tidy up the exception a bit, I don't expect a lot of Spring apps to ever encounter the problem.

**Comment by dsyer** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/issues/10 (this is not a Netflix issue).
