### ISSUE TITLE
Issue Zuul integration with wildlfy

### ISSUE THREAD

**Issue by abdulrazak-mumms** [spring-cloud/spring-cloud-netflix#2001]
I have added profile for wildfly and it is deploying without any issues. When I tried to access zuul prt, I am getting 404 error.

I have jboss-deployment-structure.xml and jboss-web.xml in webapp folder.

Snippet of pom.xml enhanced for wildlfy. I am able to deploy and run as a spring boot application and routing also works fine as I expected.

```
 <profile>
			<id>wildfly</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<properties>
				<java.version>1.7</java.version>
				<packaging.type>war</packaging.type>
			</properties>

			<dependencies>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-web</artifactId>
					<exclusions>
						<exclusion>
							<groupId>org.springframework.boot</groupId>
							<artifactId>spring-boot-starter-tomcat</artifactId>
						</exclusion>
					</exclusions>
				</dependency>
				<dependency>
					<groupId>javax.servlet</groupId>
					<artifactId>javax.servlet-api</artifactId>
					<scope>provided</scope>
				</dependency>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-undertow</artifactId>
				</dependency>
			</dependencies>
		</profile>
```

Snippet of log post deployment : 

gatewayApplication is my zuul application.

```
15:10:23,608 INFO  [org.springframework.context.support.DefaultLifecycleProcessor] (MSC service thread 1-1) Starting beans in phase 2147483647
15:10:23,615 INFO  [org.springframework.cloud.netflix.hystrix.HystrixCircuitBreakerConfiguration$HystrixMetricsPollerConfiguration] (MSC service thread 1-1) Starting poller
**15:10:23,698 INFO  [com.hummingbird.gateway.HbgatewayApplication] (MSC service thread 1-1) Started HbgatewayApplication in 15.949 seconds (JVM running for 27.295)**
15:10:23,812 INFO  [org.springframework.cloud.netflix.zuul.ZuulFilterInitializer] (MSC service thread 1-1) Starting filter initializer context listener
15:10:23,822 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) JBAS017534: Registered web context: /
15:10:23,861 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 29) JBAS018559: Deployed "postgresql-9.2-1003-jdbc4.jar" (runtime-name : "postgresql-9.2-1003-jdbc4.jar")
15:10:23,861 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 29) JBAS018559: **Deployed "gateway.war" (runtime-name : "gateway.war")**
15:10:23,875 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://127.0.0.1:9990/management
15:10:23,875 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:9990
15:10:23,875 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.1.0.Final "Kenny" started in 27390ms - Started 509 of 570 services (113 services are lazy, passive or on-demand)
15:10:27,387 INFO  [io.undertow.servlet] (default task-1) Initializing Spring FrameworkServlet 'dispatcherServlet'
15:10:27,388 INFO  [org.springframework.web.servlet.DispatcherServlet] (default task-1) FrameworkServlet 'dispatcherServlet': initialization started
15:10:27,427 INFO  [org.springframework.web.servlet.DispatcherServlet] (default task-1) FrameworkServlet 'dispatcherServlet': initialization completed in 39 ms
15:10:27,441 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/microservice-redis-example/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
15:10:27,442 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/microservice-jwt-auth/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
15:10:27,442 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
```

How do we enable debug for zuul route tracing ?

is there any other configuration required for wildfly compatibility ?

**Comment by spencergibb** [comment]
I see it mapped three routes 
```
15:10:27,441 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/microservice-redis-example/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
15:10:27,442 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/microservice-jwt-auth/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
15:10:27,442 INFO  [org.springframework.cloud.netflix.zuul.web.ZuulHandlerMapping] (default task-1) Mapped URL path [/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
```

Do those not work?

**Comment by spencergibb** [comment]
What url are you trying to access?

**Comment by abdulrazak-mumms** [comment]
Hi, this is my application.yml. It's working when I ran as a spring boot application but not when I deployed war in wildfly server.
server:
  #port: 8083
zuul:
  routes:
    pim:
      path: /**
      #url: http://localhost:8080/
      url: http://hbdev.mumms.com:28080/
      sensitive-headers:
    microservice-redis-example:
      path: /microservice-redis-example/**
      url: http://localhost:8082
      sensitive-headers:

    microservice-jwt-auth:
      path: /microservice-jwt-auth/**
      url: http://localhost:8081
      sensitive-headers:
          

  add-host-header: true

**Comment by spencergibb** [comment]
You didn't answer either of my questions. What url are you trying to hit that doesn't work?

**Comment by abdulrazak-mumms** [comment]
I tried to hit localhost:8080 and it is redirecting to http://localhost:8080/login.jsp with WhiteLabel error page on body.

**Comment by abdulrazak-mumms** [comment]
I am not using these two url inside my application /microservice-redis-example/** and /microservice-jwt-auth/** for now as I was not able to login itself. So commented out for now and I didn't spin up microservice too.

**Comment by spencergibb** [comment]
You have spring security?

**Comment by abdulrazak-mumms** [comment]
Yes. We have spring security. 
It works when I removed port [28080] from url.

```
server:
  #port: 8083
zuul:
  routes:
    pim:
      path: /**
      #url: http://localhost:8080/
      url: http://hbdev.mumms.com/
      sensitive-headers:
```

**Comment by abdulrazak-mumms** [comment]
Hi @spencergibb,

I have one more question on this.

In Spring Applicaiton,

```
  routes:
    pim:
      path: /**
      #url: http://localhost:8080/
      url: http://hbdev.mumms.com:28080/
      sensitive-headers:
```
When I route from localhost:8083 -> http://hbdev.mumms.com/. Browser taking me to localhost:8083/login.jsp

This is my expectation as I have some other routes too.

Because normally when I hit hbdev.mumms.com, it will take me to hbdev.mumms.com/login.jsp

In JBoss Wildfly server,

```
  routes:
    pim:
      path: /**
      #url: http://localhost:8080/
      url: http://hbdev.mumms.com:28080/
      sensitive-headers:
```
I am getting error page If I have port [28080] on it.

Zuul taking me to hbdev.mumms.com directly If I have not mentioned port number on it like this
`url: http://hbdev.mumms.com/`

Routing happened like this localhost:8083 -> http://hbdev.mumms.com/login.jsp.

Do you have any idea why this is happening ?

**Comment by spencergibb** [comment]
It http://hbdev.mumms.com listening on port 28080? How could it if  http://hbdev.mumms.com/login.jsp works on port 80?

**Comment by abdulrazak-mumms** [comment]
Usual routing was going like this.
WebServer --> AJP Proxy -> Spring security

28080 is Application server port inside that host

**Comment by spencergibb** [comment]
What is the error?

**Comment by abdulrazak-mumms** [comment]
[server.log.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1045409/server.log.zip)

No exception in the server log. I had changed log level of Jboss to debug and attached the same

**Comment by spencergibb** [comment]
The logs show `Location: http://localhost:8080/login.jsp` it's trying to redirect there.

**Comment by abdulrazak-mumms** [comment]
Yes. When I deployed as spring application. It does the same and working fine. But not with wildfly server

**Comment by abdulrazak-mumms** [comment]
Am I missing any specific header or any other config required for wildfly ?

**Comment by spencergibb** [comment]
I honestly don't know why it doesn't work in wildfly.

**Comment by abdulrazak-mumms** [comment]
Thank you very much for your time
