### ISSUE TITLE
wats the usage of debug step in routingFilter?

### ISSUE THREAD

**Issue by surlymo** [spring-cloud/spring-cloud-netflix#2008]
i found the routingFilter will keep debug info when in forward step. 
like the code below:
```
Map<String, Object> info = this.helper.debug(verb, uri, headers, params,
				requestEntity);
```
but i could not find the debug info's usage.
can anyone tell me?

**Comment by lowzj** [comment]
The debug info will be added into `TraceRepository`, you could query the `${management.context-path}/trace` endpoint to get the debug infos. The default value of trace endpoint is `/trace`.

**Comment by surlymo** [comment]
@lowzj 
got it. thx~
