### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by pchlebda** [spring-cloud/spring-cloud-netflix#2010]
Is there any way to add dynamic path variable routing. Scenario:
application.properties
zuul.routes.books.url=http://localhost:8090
zuul.routes.books.path=/mybook/*

Zuul proxy is running on localhost:8080.
For incoming request http://localhost:8080/mybook/avaiable
I'd like to send it to url http://localhost:8090/avaiable/123

All I need is to add path variable(123) at the end of url based on http header.

**Comment by spencergibb** [comment]
Where does 123 come from?

**Comment by pchlebda** [comment]
It doesn't matter. Let's say that 123 is just book id and it needs to be add to context path. It's retrieved from JWT.
Is there any way to change dynamically routing by adding extra part of uri at the end of existing uri  ?

**Comment by spencergibb** [comment]
I does matter. If it comes from the request url there is one way to answer. Where do you put `ctx.getRequest().getRequestURL().append("123")`? It needs to run after `PreDecorationFilter`.

**Comment by pchlebda** [comment]
Finally I've fixed that. I've changed my filter type to `"route"`. The zuul proxy consumes get request at some endpoint and http header `Authorization -> Bearer token`. It calls service to decode `token` and read customer number from token claims. Afterwards proper downstream service i called with customer number as a part of url.
