### ISSUE TITLE
Administration of a Zuul cluster

### ISSUE THREAD

**Issue by benitocm** [spring-cloud/spring-cloud-netflix#2011]
Hi,

We are planning to use Zuul as a proxy for our back-end system. We have seen that filters and routing functionalities can provide a very flexible environment. We can enable active and disable filters as well as add and remove routes by modifying the configuration file and calling the "refresh" in Zuul without no reboot. That works.  The problem comes when you have a cluster of Zuuls that you want to operate, e.g., activate a filter at the same time in all the instances. 

My question is how other people is managing a cluster of Zuuls (i.e. activate a filter in all the instances) ?  Is there any facilities in Zuul to help with this? 

Thanks in advance.

**Comment by spencergibb** [comment]
spring-cloud-bus supports a `/bus/refresh` that can target multiple instances via a message broker such as rabbit or kafka.

**Comment by benitocm** [comment]
Hi,

That is an option but I would need another component high available (the broker) that currently I dont have.  The problem that I have is that if I have three Zuuls that do not share anything and I need to active a filter in all of them, I need to "script" the edition of three properties files plus the corresponding calls to the /refresh method.  I was thinking about using something like Ansible may help but I wanted to know how other people was facing this problem because I assume that most of deployments will have to use more than one Zuul instance and given the flexibility that it provides, the next problem that arises is to provide some kind of administration tool/console.

**Comment by master2501** [comment]
Hi @spencergibb 

Is there a way to update routes dinamically (add/update/remove) on-the-fly? Without the need to restart the service.

**Comment by spencergibb** [comment]
Our recommended approach is to use `/bus/refresh`

**Comment by JoshuaAndrew** [comment]
@master2501    reference https://jmnarloch.wordpress.com/2015/12/09/spring-cloud-zuul-cassandra-route-storage/
