### ISSUE TITLE
Routing to Multiple UI with Zuul

### ISSUE THREAD

**Issue by ksatish0101** [spring-cloud/spring-cloud-netflix#2012]
I would like to setup zuul  in a way to authicate SSO and redirect to different UI application based on path. It is working fine for single UI but not able to redirect to multiple ui . Please find the below routing configuration . i am accessing  thru http://localhost:8899/seedapp/
zuul:
  routes:   
    seedApp:
      path: /seedapp/**
      url:  https://goto.website.com/
    main:
      path: /collection/**
      url:  https://goto.anotherwebsite.com/

Please let me know if there a way to redirect to multiple UIs

Thank you in Advance

**Comment by ryanjbaxter** [comment]
You configuration seems OK as long as requests come into `/seedapp/` they will go to `https://goto.website.com/`.  If they come into `/collection/` they will go to `https://goto.anotherwebsite.com/`.  Where are the requests being redirected to after the authentication happens?

**Comment by ksatish0101** [comment]
we are doing  pre authorization using OAuth SSO filter, After authorisation,it is redirecting to the mentioned routes. Both websites are in angular2.

 i just found that, routing is done  to the corresponding site but none of js or assets are not getting loaded.  i am seeing 404 error in browser console for all assets and js files.

**Comment by ryanjbaxter** [comment]
Are the requests for the asserts going through zuul?  What do the URLs look like?

**Comment by ksatish0101** [comment]
yes. The requests are going through zuul. The url is zuul service url .

**Comment by ryanjbaxter** [comment]
Can you provide an example URL?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
