### ISSUE TITLE
Customize RetryHandler in Zuul

### ISSUE THREAD

**Issue by chazhung** [spring-cloud/spring-cloud-netflix#2013]
We are using Camden SR4. I have enabled ribbon.httpclient.enabled: true

Digging into the code, the retry handler is instantiating the RequestSpecificRetryHandler directly. Is there a way to override the retry handler? I tried to create a decorator and creating a BeanPostProcessor which would wrap the RibbonLoadBalancingHttpClient to return the retry handler that I wanted, but my bean post processor was not included as a post processor for that bean.

**Comment by ryanjbaxter** [comment]
Is there any chance you can upgrade to `Camden.SR7`?  The logic to retry requests has completely changed in later releases.  What functionality are you trying to customize?

**Comment by chazhung** [comment]
I wanted to only retry on ConnectTimeout or ConnectionRefused errors.

**Comment by ryanjbaxter** [comment]
Let me know what you see after upgrading.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
