### ISSUE TITLE
call /restart from eureka registry on if application status down

### ISSUE THREAD

**Issue by harry-rathor** [spring-cloud/spring-cloud-netflix#2017]
Is there(can have) any feature by Eureka registry calls **/restart** endpoint similar like to **/health** endpoint from eureka registry on if application status # DOWN # for some threshold time

**Comment by ryanjbaxter** [comment]
Not currently, I dont think there is anything preventing you from doing it yourself though.

**Comment by harry-rathor** [comment]
Thank you for your response, I'll work on it.
application.yml should have following configuration 

`eureka:
  client:
    healthcheck:
      enabled: true
    restart-if-down: false
    restart-threshold-time: 18000`

Can I contribute this to eureka ?

**Comment by ryanjbaxter** [comment]
PRs are always welcome, but I am not sure this functionality would belong in spring cloud netflix.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
