### ISSUE TITLE
Eureka null pointer exception on Cloud foundry

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#2023]
getting below exception while trying to connect Eureka in cloud foundry
ava.lang.NullPointerException
	at org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry.maybeInitializeClient(EurekaServiceRegistry.java:56)
while pushing the app i see the below logs
warning [/tmp/staged/app/lib/spring-expression-4.3.7.RELEASE.jar]:  263286 extra bytes at beginning or within zipfile

**Comment by ryanjbaxter** [comment]
You are going to have to provide more details for us to help.
You should also read the section on Eureka and CF in our documentation.  http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#_using_eureka_on_cloudfoundry

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
