### ISSUE TITLE
Is there a way to intercept client registration request to server

### ISSUE THREAD

**Issue by kavinash-athena** [spring-cloud/spring-cloud-netflix#2027]
I would like to filter out the clients that can connect to my eureka server based on certain conditions, ie I would like to have some validation on the metadata and then approve or disapprove the client registration requests. Can you please let me know if there are any way we can achieve this?

**Comment by spencergibb** [comment]
@kavinash-athena I know it is not trivial and requires custom development.

@scottfrederick any pointers on adding security to the eureka server?

**Comment by 992572179** [comment]
Zuul can,and define your Filter at your project.

**Comment by spencergibb** [comment]
@992572179 doesn't have anything to do with zuul.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
