### ISSUE TITLE
zuul ribbon retry post  body is null

### ISSUE THREAD

**Issue by CQLiuhuan** [spring-cloud/spring-cloud-netflix#2032]
I have a question, when i use the zuul and configure ribbon retry like this : 

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  MaxAutoRetries: 1
  ServerListRefreshInterval: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1

one of the controller which the serviceid register in Eureka ,below

@Controller
public class TestController{
 
@RequestMapping("test")
 public TestResponse querySmsFaultHistory(HttpServletRequest request) {
    String body = request.getParameter("XXXXX");
  }
}

version:

spring.boot.version : 1.4.4.RELEASE
spring.cloud.version: Camden.SR6

The request method get is all right, But i use the request method post, first the body is not null , when retry  the body is null ,why ?
.

**Comment by ryanjbaxter** [comment]
Please format code according to the GitHub documentation to make it easier to read https://help.github.com/articles/creating-and-highlighting-code-blocks/

Your controller does not handle `POST` methods so I am not sure how this would even work.

**Comment by 992572179** [comment]
use @ResponseBody annotation at your method,and try again please.

**Comment by lhchingit** [comment]
You can also use `@RequestBody` to get the payload directly, such as
@requestmapping("test")
```
public TestResponse querySmsFaultHistory(**@RequestBody String body**) {
    ...
}
```

**Comment by ryanjbaxter** [comment]
Please reopen if you are still having issues

**Comment by CQLiuhuan** [comment]
I have solved the problem , I have override the method named getRequestBody of RibbonRoutingFilter.

**Comment by ezraroi** [comment]
Hi, we also saw this issue. When doing retry of post requests, the body of the retry request is empty
