### ISSUE TITLE
SecurityContextConcurrencyStrategy does not delegate getThreadPool to existing strategy

### ISSUE THREAD

**Issue by miensol** [spring-cloud/spring-cloud-netflix#2035]
[HystrixConcurrencyStrategy](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java) has 2 `getThreadPool` overloads. `SecurityContextConcurrencyStrategy` does not override [`public ThreadPoolExecutor getThreadPool(final HystrixThreadPoolKey threadPoolKey, HystrixThreadPoolProperties threadPoolProperties)`](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java#L94) and thus calls to this method will use default hystrix impementation.

**Comment by ryanjbaxter** [comment]
So what does this have to do with Spring Cloud Netflix?

**Comment by miensol** [comment]
I'm sorry, perhaps I should have been more descriptive.

[`SecurityContextConcurrencyStrategy`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/SecurityContextConcurrencyStrategy.java) which is _auto configured_ using [`HystrixSecurityAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java) overrides only a single `getTreadPool` overload from `HystrixConcurrencyStrategy`. 

When the `SecurityContextConcurrencyStrategy` is being registered inside [`HystrixSecurityAutoConfiguration.init`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java) method it first fetches existing `HystrixConcurrencyStrategy`. The existing `HystrixConcurrencyStrategy` is used by `SecurityContextConcurrencyStrategy` as delegate. 

The delegation is done for all methods of `HystrixConcurrencyStrategy` except for [`public ThreadPoolExecutor getThreadPool(final HystrixThreadPoolKey threadPoolKey, HystrixThreadPoolProperties threadPoolProperties)`](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/strategy/concurrency/HystrixConcurrencyStrategy.java#L94). This means that when there already is **a non default** `HystrixConcurrencyStrategy` registered before `HystrixSecurityAutoConfiguration.init` invocation `SecurityContextConcurrencyStrategy` will cause the (possibly customized) `getThreadPool` overload to be ignored and instead use **default implementation** provided by `HystrixConcurrencyStrategy`. 

This behavior is unexpected to me to say the least. I think `HystrixSecurityAutoConfiguration.init` should either throw if it encounters **a non default** `HystrixConcurrencyStrategy`  or properly **delegate all methods calls** to already registered `HystrixConcurrencyStrategy`.

**Comment by ryanjbaxter** [comment]
OK that makes sense, thanks for the more detailed explanation.  If you want to get this fixed faster please feel free to submit a PR (against the 1.3.x branch if possible).  If not we will try to get to it as soon as we can.
