### ISSUE TITLE
eureka client - registration issue

### ISSUE THREAD

**Issue by brookliu123** [spring-cloud/spring-cloud-netflix#2038]
Why every 5 minutes to print the log INFO 2854 --- [ restartedMain] c.n.d.s.r.aws.ConfigClusterResolver : Resolving eureka endpoints via configuration

**Comment by ryanjbaxter** [comment]
The Eureka client sends a heartbeat every so often to the Eureka server, I believe that is where that is coming from.

**Comment by brookliu123** [comment]
@ryanjbaxter thanks,Is there a parameter that can set the heartbeat time?

**Comment by ryanjbaxter** [comment]
Yes, `eureka.instance.leaseRenewalIntervalInSeconds`.  Although it should be more frequent than every 5 minutes by default.

**Comment by spencergibb** [comment]
I think that particular class has to do with eureka clustering

**Comment by brookliu123** [comment]
@ryanjbaxter  I am somewhat confused why I set leaseRenewalIntervalInSeconds: 10 However the app still prints the following log every 5 minutes

**Comment by spencergibb** [comment]
I don't think they are related

**Comment by brookliu123** [comment]
@spencergibb What do you think is caused by every five minutes to print the following log

INFO 2854 --- [ restartedMain] c.n.d.s.r.aws.ConfigClusterResolver : Resolving eureka endpoints via configuration

**Comment by ryanjbaxter** [comment]
It is coming from here 
https://github.com/Netflix/eureka/blob/4f24d9dcf90713b421f6c092fa63e707cbf74df3/eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaHttpClients.java#L133

You should be able to control the interval by setting `eureka.client.eurekaServiceUrlPollIntervalSeconds`.

**Comment by brookliu123** [comment]
ok,thanks

**Comment by Fiala-CN** [comment]
But when is logged "Resolving eureka endpoints via configuration", the service cannot work, how is that happen?

**Comment by Leehom23** [comment]
@spencergibb i also meet this problem in my  project,while i set eureka.client.eurekaServiceUrlPollIntervalSeconds = 10  and eureka.instance.leaseRenewalIntervalInSeconds = 10 ，it doesn't work. server still prints the following log every 5 minutes;
  com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration

**Comment by spencergibb** [comment]
@Leehom23 those configuration items don't relate to that log statement.

**Comment by Leehom23** [comment]
> @Leehom23 those configuration items don't relate to that log statement.

so how should i adjust parameters?

**Comment by bwl-bwl** [comment]
OOM?

**Comment by ryanjbaxter** [comment]
I dont think the logging would cause the service to become unresponsive.  Please open a separate issue including a sample to reproduce the problem
