### ISSUE TITLE
Support for multiple hystrix metrics per message in turbine stream

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#2039]
The turbine stream aggregator could anticipate future changes in the client to batch metrics together for efficient streaming.

**Comment by dsyer** [comment]
Fix in 4783b07

**Comment by spencergibb** [comment]
Thanks, that's been a TODO in code for a while now.

**Comment by dsyer** [comment]
I noticed the TODO in the producer. This only covers the consumer, but we have to get that released first so users have a migration path.

**Comment by spencergibb** [comment]
yup
