### ISSUE TITLE
When closing a Eureka Clients, the RestTemplate with @LoadBalanced will continue call the closing service, how fixed it?

### ISSUE THREAD

**Issue by EzrealKing** [spring-cloud/spring-cloud-netflix#2041]
I use Eureka and Spring Cloud;

Start 2 Eureka Clients;

When closing a Eureka Clients, the Eureka Client unregister from Eureka Server need a little time (3-5 minutes);

the RestTemplate with @LoadBalanced will continue call the closing service, how fixed it?

**Comment by ryanjbaxter** [comment]
When you saying "closing a Eureka Client", do you mean shutting down the app?

I assume you are talking about other Eureka Clients calling a service that has been shutdown.  The other clients won't know the service is no longer available until it refreshes the service list from the Eureka server.  You can control this period using `eureka.instance.leaseRenewalIntervalInSeconds`.  However it is better to put into place methods to deal with failures.  For example, if there are multiple instances of the service being shutdown than you can retry failed requests to fail over to an instance that is available.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
