### ISSUE TITLE
Cannot register to the service center

### ISSUE THREAD

**Issue by xjtushilei** [spring-cloud/spring-cloud-netflix#2043]
when use ` application.yml `，and write ` eureka.client.service-url.defaultZone`  ,it works

but  `application-simple.yml`  ，it do not work. 

so the  ` eureka.client.service-url.defaultZone`  must be in  ` application.yml ` or `bootstrap.yml`  ?

so i think it's a bug

**Comment by xjtushilei** [comment]
i want to use `eureka.client.service-url.defaultZone` in `application-simple.yml` .what can i do

**Comment by ryanjbaxter** [comment]
Is `simple` the name of a profile in your application?

**Comment by xjtushilei** [comment]
yes

if I have only one profile, such as `application-simple.yml`, and I define  `eureka.client.service-url.defaultZone` in it, it do not work.

so I think there's a problem in starting order.

**Comment by ryanjbaxter** [comment]
I just tried to reproduce this and it worked fine.  I was able to define `eureka.client.service-url.defaultZone` in `application-simple.properties` and enable the `simple` profile and it worked.
