### ISSUE TITLE
about spring cloud feign how to support springmvc @requestmapping annotation

### ISSUE THREAD

**Issue by hao0111** [spring-cloud/spring-cloud-netflix#2050]
hi,guys, spring cloud feign component support springmvc annotation @requestMapping with method ,and auto generate rest style http template,that is amazing!How it do,would you tell me the resolution how it work.
p.s: where is source code,pleasure!thank you

**Comment by ryanjbaxter** [comment]
The source code is in this repo, I believe the class is `SpringMvcContract`.
