### ISSUE TITLE
Why Dalston.SR1 version won't execute fallbackFactory method  when the server which is called  return status 500

### ISSUE THREAD

**Issue by maoyunfei** [spring-cloud/spring-cloud-netflix#2055]
In service call with feignClient , I use a consume servce named "A" to call a producer service named "B" , if  "B" occur an internal exception and return http status 500 ,  "A" won't trigger fallback.
I used Dalston.SR1 version meanwhile set `feign.hystrix.enable: true` in my .yml file.

But when I change version to Camden.SR6 , the situation I described  above won't occur and It will  trigger fallback as expected.

I tested , if `@FeignClient(value = "service-name", url = "http://127.0.0.1:2222", fallback = ComputeClientFallback.class, configuration = CustomerFeignConfiguration.class)
` use fallback props , both version is ok , only `@FeignClient(value = "service-name", url = "http://127.0.0.1:2222", fallbackFactory = ComputeClientFallbackFactory.class, configuration = CustomerFeignConfiguration.class)
` use fallbackFactory pros and version Dalston.SR1 will be bad.

I fell puzzled , thanks for feedback in advance.

**Comment by spencergibb** [comment]
I'm afraid you'll need to be more detailed explaination, I'm having a hard time following. Maybe a full sample would be nice.

**Comment by maoyunfei** [comment]
It's my bad.  `feign.hystrix.enabled: true` is right. I write the wrong properties name. sorry. orz
