### ISSUE TITLE
Eureka- Server and Client Communication.

### ISSUE THREAD

**Issue by harishkadamudi** [spring-cloud/spring-cloud-netflix#2058]
This is not an Issue, but a question/clarification rather on server-client communication.

I am running 3 services
	1. customer service
	2. order service
	3. customer-order service, which is an aggregator, pulls result from Customer & Order service

Have configured Eureka cluster with 3 servers running
Assume, Eureka-1,Eureka-2 & Eureka-3

All three of My Eureka servers are up.

During testing, I registered all my services(Customer, Order and Order Services) to only 1 Eureka Server which is Eureka-1.

Observations:
	1. All 3 Eureka servers will have Customer, Order and Customer-Order services information in the respective their Dashboards.
	2. Intentionally, stop Eureka-1(Note: All 3 services are registered with this only).
	3. When I hit customer-order service, somehow Eureka supplied customer & order instances/registry and I am able to hit customer and order url's.

Question:
Even my services are registered to only one Eureka Instance, how I am able to fetch information from Eureka Cluster.
i was thinking since I am registered with only one Eureka Server, I shouldn't be getting customer & order information from Eureka Server.

I waited for close to 30 minutes thinking, Eureka will not supply customer & order instances.

**Comment by harishkadamudi** [comment]
When setup in cluster, somehow Eureka will share registered services information with each other,
even if services are registered with only one Eureka Instance.

**Comment by ryanjbaxter** [comment]
I assume you have the Eureka servers setup as peers of each other, and the Eureka clients know about all the Eureka servers?

**Comment by spencergibb** [comment]
Please don't cross post https://github.com/Netflix/eureka/issues/958

**Comment by harishkadamudi** [comment]
@ryanjbaxter ,

Clients do not know about all the Eureka Severs, It knows about only one server, and if that server goes down, still I am able to access my clients details from other Eureka Server.

**Comment by ryanjbaxter** [comment]
The Eureka client will cache the registry information locally so it will have the service details even if the Eureka server goes down.

**Comment by harishkadamudi** [comment]
@ryanjbaxter ,

Thanks. But in this case client knows only about one server, not all servers. and same server was down.

**Comment by ryanjbaxter** [comment]
Yes I understand the client knows only about one server.  If the server is up and the client is able to fetch the registry and then at some point in the future the server goes down the client will have a cache of the registry before the server went down.

**Comment by AtahAhmed** [comment]
Can we configure client cache?

**Comment by ryanjbaxter** [comment]
@AtahAhmed in what way?

**Comment by AtahAhmed** [comment]
@ryanjbaxter, the eureka clients are caching the eureka server information, thus avoiding dependency with eureka server, now let say if we want to increase/decrease the duration of caching at eureka client, How we are going to do it? Is it possible at first place?

**Comment by ryanjbaxter** [comment]
I think you want to use `eureka.client.registry-fetch-interval-seconds`.

**Comment by ryanjbaxter** [comment]
> What is the default duration of this client side cache?

Based on this issue, the service registry information in client should be cached indefinitely (or at least until the client is able to successfully connect to the server again) https://github.com/Netflix/eureka/issues/804

> How can we configure this cache interval?

There doesnt appear to be a way to do this, and I am not sure why you would want to clear the cache if there is no connection to the Eureka server.

> In the above case I want to know when will my services start failing the request in case of eureka is down?

They shouldnt start failing as long as there are no changes to the location of the downstream services

**Comment by amit-jadhav** [comment]
Thank you @ryanjbaxter for clarifying my queries.
