### ISSUE TITLE
Feign Security Session Not Propogated

### ISSUE THREAD

**Issue by tschiman** [spring-cloud/spring-cloud-netflix#2065]
I've got a cloud application set up with zuul, eureka, and some backing services. I'm using spring security (not oauth) with spring session to secure everything. I want to use feign on the zuul gateway to make http requests to multiple backing services to condense the data to one request. To do this I want to pass the user's session to the services through feign. This essentially invovles sending a sessionId, but for some reason it is not working. Here is my feign client:

`@FeignClient(value = "rating-service")\
public interface RatingsClient {
    @RequestMapping(method = RequestMethod.GET, value="/ratings")
    List<Rating> getRatingsByBookId(@RequestParam("bookId") Long bookId, @RequestHeader("Set-Cookie") String sessionCookie);
}`

What am I missing or doing wrong here?

**Comment by ryanjbaxter** [comment]
Can you describe what exactly is not working?  It seems odd that you are adding the session in the `Set-Cookie` header.  Wouldn't the downstream service be expecting the session token in a different header?

**Comment by tschiman** [comment]
Spacing on http spec. Once I changed the header to "Cookie" it works.

**Comment by tschiman** [comment]
This is resolved or was a non-issue.
