### ISSUE TITLE
When running in Eureka in Cluster, why registerWithEureka should be true.

### ISSUE THREAD

**Issue by harishkadamudi** [spring-cloud/spring-cloud-netflix#2070]
Have set up Eureka in cluster with 3 instances, something like below.

```xml
spring:
  profiles: dev1_profile
eureka:
  client:
    serviceUrl:
      defaultZone: https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v1199.net:${config.server.port}/eureka, 	   https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v0852.net:${config.server.port}/eureka,				   https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v1377.net:${config.server.port}/eureka
```

with this configuration, when I login to Eureka Dashboard, I do see these 3 servers listed in registered-replicas & available-replicas.

But when I modify to disable registerwitheureka (_by setting it to false_), I see no servers in available-replicas and I see it in unavailable-replicas

```xml
spring:
  profiles: dev1_profile
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v1199.net:${config.server.port}/eureka, 	   https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v0852.net:${config.server.port}/eureka,				   https://${spring.cloud.eureka.user.name}:${spring.cloud.eureka.user.password}@v1377.net:${config.server.port}/eureka
```

using below configuration

```xml
<artifactId>spring-cloud-dependencies</artifactId>
<version>Brixton.SR7</version>
and 
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.4.2.RELEASE</version>
```

**Comment by harishkadamudi** [comment]
We do not want to Register Eureka Instances when running in cluster.

**Comment by ryanjbaxter** [comment]
So you are setting `registerWithEureka` to `false` on each Eureka server in the cluster?

**Comment by harishkadamudi** [comment]
Sorry I didn't understand, this is how I am working on it. build using profile in this case dev1_profile.
Run that jar file in different boxes.

**Comment by harishkadamudi** [comment]
I tested setting that property out profile configuration something like below
eureka:
  client:
    register-with-eureka: false

**Comment by ryanjbaxter** [comment]
`register-with-eureka` must be true to have each server in the cluster replicate information with each other.  You can imagine each server being a client as well, so it is just like I client talking to another Eureka server.

**Comment by harishkadamudi** [comment]
Thanks @ryanjbaxter . Closing this thread.
