### ISSUE TITLE
Dynamic Replication

### ISSUE THREAD

**Issue by Lovett1991** [spring-cloud/spring-cloud-netflix#2071]
Is it possible to have eureka nodes pick up new peers added to the group?

If in my config I have nodes 1 & 2 up and running, and the are aware of each other but not the third, and then I bring up a third, which has knowledge of the first two nodes, is it possible to get node 1 & 2 to start replicating to the third without having to do a config refresh and manually adding the third?

From looking at the source it seems the replica instances are stuck to a hard coded config, whereas if the "composite" option is enabled in transport config then clients can use the registry of registered eureka nodes rather than being limited to their original config (Which I've had running).

I ask as it would be good to be able to scale up the number of eureka nodes as and when the load increases.

**Comment by spencergibb** [comment]
Not that I'm aware of. Generally, eureka clusters need to know about every other node in the cluster.

**Comment by Lovett1991** [comment]
Would there be any issue in the nodes being able to resolve peers from registry?

(Not a feature request!) happy to modify code for our use case.

**Comment by spencergibb** [comment]
That's all upstream in eureka, which is where a change would need to be made.
