### ISSUE TITLE
Zuul error on kubernetes

### ISSUE THREAD

**Issue by mrapolli** [spring-cloud/spring-cloud-netflix#2072]
When i call a service from minikube Ip in kubernetes, i receive the follow error form Zuul:

com.netflix.zuul.exception.ZuulException: Forwarding error	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.handleException(RibbonRoutingFilter.java:157)

my zuul yml config:

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${KUBERNETES_SERVICE:http://localhost:8761}/eureka/

zuul:

  prefix: /api

  routes:
    test:
      path: /redirect/**
      url: http://google.com
    customer-by-service:
      path: /customer-by-service/**
      serviceId: CUSTOMER-SERVICE

spring:
  config:
    name: zuul
  application:
    name: zuul-server
  cloud:
    config:
       failFast: true
       discovery:
          enabled: true

ribbon:
  eureka:
    enabled: true

**Comment by ryanjbaxter** [comment]
More the stack trace would be useful

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
