### ISSUE TITLE
Eureka server not evicting on  leaseExpirationDurationInSeconds

### ISSUE THREAD

**Issue by sunilnarsipura** [spring-cloud/spring-cloud-netflix#2075]
This is more of a question than a issue
Eureka server not evicting the instance on given leaseExpirationDurationInSeconds.
Ex: if i have leaseExpirationDurationInSeconds as 10 seconds its evicting around the 20th second
 if i have leaseExpirationDurationInSeconds  as 30 seconds its evicting around the 60th second.
i pasted my server and instance details.. Is there something i missed?
eureka:
 server:
  waitTimeInMsWhenSyncEmpty : 0
  enableSelfPreservation : false
  evictionIntervalTimerInMs : 5000
  responseCacheUpdateIntervalMs : 10000
 client:
  registerWithEureka: false
  fetchRegistry: false
  eurekaServiceUrlPollIntervalSeconds: 10

Service;;
eureka:
 client:
  enabled: true
  registryFetchIntervalSeconds: 10 
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 instance:
  leaseRenewalIntervalInSeconds: 5
  leaseExpirationDurationInSeconds: 30

**Comment by spencergibb** [comment]
Have you read https://github.com/Netflix/eureka/wiki/Understanding-eureka-client-server-communication#renew?

**Comment by sunilnarsipura** [comment]
i have read it, expected that its gonna override the default.
Will it be good practice for demo to disable the self preservation? or change the renewalPercentThreshold
