### ISSUE TITLE
eureka  instance name include "_"

### ISSUE THREAD

**Issue by 3792274** [spring-cloud/spring-cloud-netflix#2077]
I know the eureka instance name don't want a name like include "_",eg: Hello_Serv_A
but i have one .and this one from big man ,he don't want change his eureka instance name,

```yml
eureka:
    instance:
        instance-id: Hello_Serv_A
```

what can i do ,
i have the one way,
```java
  
    @Bean
    @Qualifier("normalRestTemplate")
    RestTemplate normalRestTemplate() {
        return new RestTemplate();

    }

     @Autowired
      private LoadBalancerClient loadBalancerClient;
 
    private URI getErrorEurekaInsId() throws PayException {
        try {
            return loadBalancerClient.choose("Hello_Serv_A").getUri();
        } catch (Exception e) {
            e.out();
        }



String result =  normalRestTemplate.exchange(getErrorEurekaInsId(), HttpMethod.POST,formEntity,String.class,orderId).getBody();
 

```

but i want use like this 

```java
    @Bean
    @LoadBalanced
    @Qualifier("polledLoadBalancedRestTemplate")
    RestTemplate polledLoadBalancedRestTemplate() {
        return RestTemplateUtil.getRestTemplate();
    }

 

String result = polledLoadBalancedRestTemplate.postForObject("Http://Hello_Serv_A/param1={param1}", formEntity, String.class,param1);
```

i think it neek to rewrite  In Spring 
in the sources ,the problem is here
```java
File:org.springframework.cloud.client.loadbalancer.*BalancerInterceptor
eg:  RetryLoadBalancerInterceptor.intercept(RetryLoadBalancerInterceptor.java:70)
 
@Override
public ClientHttpResponse intercept(final HttpRequest request, final byte[] body,final ClientHttpRequestExecution execution) throws IOException {
  final URI originalUri = request.getURI();                  //http://Hello_Serv_A/param?a={a} 
  final String serviceName = originalUri.getHost();    //it's null !
Assert.state(serviceName != null, "Request URI does not contain a valid hostname: " + originalUri);
```
 
-----------------------------------------------------------------------
My Question is  :
 How can i overWrite method In   *BalancerInterceptor.intercept()  
 
thank you！

**Comment by ryanjbaxter** [comment]
Please read how to properly format code in GitHub issues
https://help.github.com/articles/creating-and-highlighting-code-blocks/

Underscores are not valid in hostnames, it is not a restriction from Spring Cloud.  I am not sure why `originalUri` has a `null` host property, it is hard to tell from what you have supplied above.

**Comment by eacdy** [comment]
Maybe this post helps : <https://github.com/spring-cloud/spring-cloud-netflix/issues/1582>
The `Hello_Serv_A` and `abc_d` is so called "virtual hostname", and hostname can not contain underline.
