### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by LeonardLaszlo** [spring-cloud/spring-cloud-netflix#2079]
I have the same problem as the guy in this post:

https://stackoverflow.com/questions/38730091/spring-zuul-route-connection-reset

"The problem is that when i try to reach out to my microservice first time after being idle for sometime, I see a connection reset error logged into api gateway. I don't see anything logged in my client service. But the same call is successful if i refresh my browser, or calling again."

Please help me figure out how can I solve this problem!

This is what I see in my browser:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jun 28 14:55:17 UTC 2017
There was an unexpected error (type=Internal Server Error, status=500).
Connection reset
```

Here is a stacktrace from the Zuul application:

https://gist.github.com/LeonardLaszlo/7bbc6bc0e15807b39986e70f7a7aae62

**Comment by ryanjbaxter** [comment]
The SO post specifically calls out that the applications are running in Cloud Foundry, are your apps also running in Cloud Foundry?  And if so do you see the same problem when the applications are running outside of Cloud Foundry?

**Comment by LeonardLaszlo** [comment]
Yes, my apps are running in Cloud Foundry.

If I got it right connection reset means that the TCP package received by the server is damaged and the client should retry to open the connection. However, if Zuul gets a connection reset it should retry to establish the connection.

Setting the following properties didn't help me:
```
zuul:
  host:
    socket-timeout-millis: 60000
  retryable: true
```

**Comment by ryanjbaxter** [comment]
Its kind of strange that this only happens on Cloud Foundry
Is Zuul using service discovery or have you specified the routes via URL?

**Comment by LeonardLaszlo** [comment]
I have two use cases in the Zuul service. In one of them Zuul uses service descovery and in the other one the routes are provided via URLs.

However I noticed this exception only in the second case.

I know that the source of the problem is in the low-level networking, because my network is very unreliable lately, but I think these sporadical errors might be handled in application level if Zuul retries to establish the connection when receives `connection reset` from the service.

**Comment by spencergibb** [comment]
It might be in the different way those particular http clients are configured.

**Comment by LeonardLaszlo** [comment]
We figured out that the problem was caused by the F5 load balancer. I will close the issue. Thank you for your help!

**Comment by papajuans** [comment]
@LeonardLaszlo mind sharing? I'm seeing a very similar behavior and was wondering if you could help point others in a general direction.

**Comment by LeonardLaszlo** [comment]
In my case the load balancer was closing the connections sporadically.

I notified my CF provider about the network issues and asked them to measure the round-trip time of packages and the ratio of lost packages to delivered packages.
They increased some timeout in the F5 load balancer, which solved the problems.

I don't have more information about the F5 configuration which was modified unluckily.

**Comment by AhmedRiahi** [comment]
Hello,

Im encountering the same issue with the "Connection Reset" exception, is there any update ?

Thanks
