### ISSUE TITLE
FeignRibbonClient ignores retryhandler retry configuration

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#208]
I use spring cloud and the FeignRibbonClient to access remote services. The problem is, that this client ignores the retry configuration given by the properties:

 example-client.ribbon.MaxAutoRetries=5
 example-client.ribbon.MaxAutoRetriesNextServer=5
 example-client.ribbon.OkToRetryOnAllOperations=true.

This behavior results from this code line:
return lbClient(clientName).executeWithLoadBalancer(ribbonRequest)	.toResponse();

The lbClient creates the loadbalancer with the client configuration, but it will not be used to create the requestSpecificRetryHandlers.
What should I do to solve this problem?
Thanx Lutz

**Comment by spencergibb** [comment]
Not sure I'm following?  Can you explain a bit more?

**Comment by LutzStrobel** [comment]
We use sppring-cloud netflix 1.0.0.RC2
and have a FeignClient like  this:
@FeignClient("example-client")
public interface ExampleService {
...
}
with a configuration like this:
example-client.ribbon.NIWSServerListClassName=com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
example-client.ribbon.ServerListRefreshInterval=20000
example-client.ribbon.DeploymentContextBasedVipAddresses=example
example-client.ribbon.MaxAutoRetries=5
example-client.ribbon.MaxAutoRetriesNextServer=5
example-client.ribbon.OkToRetryOnAllOperations=true.

This client is called from a second service using the @FeignClientScan annotation.
During call execution the Method execute(....) of the class FeinRibbonClient is executed:
...
return lbClient(clientName).executeWithLoadBalancer(ribbonRequest) .toResponse();

which calls "executeWithLoadBalancer(request, null)"
This call tries to get a RequestSpecificRetryHandler like this:
        RequestSpecificRetryHandler handler = getRequestSpecificRetryHandler(request, requestConfig);
where the clientconfig is null and so it gets no RetryHandler.
I think this is a bug. The requestConfig is used to create the loadbalancer, so it should be used to get the retry handler.
I hope now it is a bit more clear.
Thank you for your help
Lutz

**Comment by spencergibb** [comment]
@LutzStrobel thanks, that clears it up for me

**Comment by spencergibb** [comment]
fixed with f49d99ef5b8e144ccd709b69aa9fc1da226a9766
