### ISSUE TITLE
OpenFeign with Custom Dynamic Headers

### ISSUE THREAD

**Issue by kameshsampath** [spring-cloud/spring-cloud-netflix#2088]
I came across this question http://bit.ly/2uEr8rY and I am having similar issue when using Open Feign starter with my Spring Boot application:

my client code:

```
@FeignClient("hello")
public interface HelloClient {
   @RequestMapping(path="/hello", method=RequestMetho.GET)
   public String hello(@HeaderMap headers);
}
```

the whole point is that I want to add some extra dynamic headers which is coming form original request to this new request, since I don't know what will be key and value I thought to add it via Map. The moment i do this I get 405 from the server saying I cant use `POST`, like the StackOverflow question posted above.

I am not sure I can add dynamic headers like this with Spring Cloud- Feign ? Ref: https://github.com/OpenFeign/feign#headers

**Comment by spencergibb** [comment]
`@HeaderMap` is a feign annotation, which, by default in spring cloud, are not used. I'm not sure we have equivalent functionality. (I wish we didn't support spring mvc annotations by default in feign).

**Comment by kameshsampath** [comment]
ok thanks @spencergibb - right now i have implemented it with standard rest template
