### ISSUE TITLE
spring cloud zuul when I access /routes,I get Full authentication is required to access this resource.

### ISSUE THREAD

**Issue by Rick-ye** [spring-cloud/spring-cloud-netflix#2089]
I follow the spring cloud official document,and write a demo about spring cloud zuul. I can access the other microservice through the zuul. but when I can access /routes,I get the result

**Comment by eacdy** [comment]
spring boot 1.5 secure actoator's endpoint by default.
You Can set management.security.enabled=false to disable this feature.
Or, You Can add dependency spring-boot-starter-security into your project.
