### ISSUE TITLE
setting custom http header on FeignRibbonClient

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#209]
We use the FeignRibbonClient to send to call to remote services and need to set custom http headers. But I cant find any option to do this.
In an earlier version this could be done by setting a Requestinterceptor at the Feign.Builder.
Is there any option to get this working?

Thanx Lutz

**Comment by spencergibb** [comment]
@LutzStrobel create a `@Bean` of type `RequestInterceptor`.
