### ISSUE TITLE
Monitoring and troubleshooting issues with Eureka ,Zuul and downstream services

### ISSUE THREAD

**Issue by volijaadu** [spring-cloud/spring-cloud-netflix#2093]
We are using Eureka , Zuul and a set of downstream services in our environment.

But, we are seeing frequent issues of failure like,

-   Unresponsive node instances not being removed from Eureka registry
-   Requests being routed to unhealthy instances ( Either down or Unresponsive)

I want to know ,if Spring Cloud Netflix provides a mechanism/tools  to monitor,

- the communication/events between the Eureka and downstream services to ensure the heartbeats are sent and received periodically and also validate instance removal from registry happens whenever a node is down/unresponsive.

- the communication/events between Zuul  and Eureka to ensure that healthy instances are returned from registry when doing a lookup in registry

- Routing in Zuul  to ensure only healthy instances/nodes are being selected by configured load balancing algorithm in Ribbon and routed accordingly after Eureka returns the instance list after lookup to zuul.

I know most of these could be mined from the logs. 

But, I am looking for some pointers to help me  out in monitoring and troubleshooting issues like 

- Recommended configuration for Zuul/Eureka and related downstream services in production, 
- Standard best practices/guidelines etc 

so  as to look in right direction to help me resolve the issues I am facing  in my environment.

Can you guys please help me on this.

**Comment by spencergibb** [comment]
zuul doesn't have anything specific to eureka, it's just the ribbon eureka client. Depending on your configuration, eureka may not evict instances if self preservation mode is enabled and the criteria reached. Logs are currently the best way to see this information.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
