### ISSUE TITLE
Should we add circuit breaker/hystrix to each service or only to ZUUL

### ISSUE THREAD

**Issue by columbo143** [spring-cloud/spring-cloud-netflix#2094]
We want to implement circuit breaker/hystrix  feature for the services in our environment.

We are using Eureka as Service Registry and Zuul as api gateway.

My question is , should we implement circuit breaker/hystrix for each of the downstream services to prevent cascading failures (OR) can we just have it implemented it at one place in the gateway level(zuul) .
I feel ZUUL would be better but not sure how, because we may have different configuration per service like time period the circuit should open/closed/half-open and also the fallback mechanism might be different for each service. This is all specific to each service. 

Is there a way to centralize  this in Zuul level or should we do it at each downstream level.

Another query , not sure if I am right,  zuul by default has hystrix enabled, If that is the case should we still add hystrix to each downstream service.

Can you please  help me on this.

**Comment by spencergibb** [comment]
zuul is an edge gateway and will only help with requests from outside. You should protect internal calls with hystrix wherever you think there could be a cascading failure.

**Comment by spencergibb** [comment]
Hystrix is added at the client level, not the downstream service.

**Comment by bsushant-athena** [comment]
@spencergibb  Similar question ::: >> I've a api-gateway and suppose 2 services(A and B) are connected to it. A contacts B and the call is going through api-gateway . I've enabled circuit breaker at api-gateway level. so Is it possible that if service B goes down service A will get some fallback response instead of 500/timeouts ? or service A has to enable circuitbreaker at its level ?

**Comment by ryanjbaxter** [comment]
@bsushant-athena please dont ask your question in multiple places, it is just causing noise.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
