### ISSUE TITLE
Eureka: client does not unregister on application shutdown (stays with status DOWN)

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2101]
This issue is an attempt at reopening https://github.com/spring-cloud/spring-cloud-netflix/issues/1543

The problem is still there in Dalston.SR1.
Although the code has been refactored since this issue is created, the same root causes are still present: the replication of the DOWN status hits the server after the unregistration.

There is not much that can be done to have 100% guarantee: the Eureka client itself does not take guarantee there is no in-flight requests when unregister is invoked.

To (temporarily) solve that issue, we used to register a custom Jersey ClientFilter in the Eureka client to intercept outgoing requests. When it is time to shutdown the client, our filter blocks all requests except the unregister. If needed I can share the workaround.

**Comment by ryanjbaxter** [comment]
Closing this so we can continue to use #1543

**Comment by brenuart** [comment]
So I can keep posting on the old issue even if closed ?
Did not know. Sorry about the noise caused by this one.

**Comment by JavaHelper** [comment]
https://stackoverflow.com/questions/53955613/working-with-eureka-clients-programmatically-issue-completed-shut-down-of-disc- please guide here
