### ISSUE TITLE
Gzipped response not written as Gzipped but normal unGzipped string instead.

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2110]
In line 180 -> 182 here: [SendResponseFilter.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java)
How is the response supposed to be like when it is written back if that if statement is executed?
Well, in my code (which is adapted from yours) this the case, so the client requests the response to be Gzipped, and it is Gzipped (the if statement), but the response is written as a normal string in the api!
I am also logging that response in a file, and to do so, I have to unzip it using:

> GZIPInputStream then BufferReader with UTF-8 encoder

and without that I get a GZIPPED response logged in the file
Do you have any idea what may have happened behind the scenes? 
Thank you in advance.

**Comment by ryanjbaxter** [comment]
So the response coming back from the server is not gzipped but the content logged to the file is?

**Comment by mirak94** [comment]
No, it is Gzipped, and if I log it without trying to unzip it using the GZIPInputStream then BufferReader with UTF-8, it is logged as something very bad you can't understand. However, when writing the response back to the api, the if condition I've pointed to is executed and that line: `servletResponse.setHeader(ZuulHeaders.CONTENT_ENCODING, "gzip");` but I just appears as a normal string.

**Comment by mirak94** [comment]
The if condition says that `context.getResponseGZipped() && isGzipRequested`, so it is gzipped and client wants it like so. However, when writing the response to the api back, it is written as normal string.

**Comment by ryanjbaxter** [comment]
I dont understand what you mean when you say "writing the response to the api", what is the API?

**Comment by mirak94** [comment]
I mean you open your chrome browser, and type any get request, obviously you wait for some response to be written in the screen, don't you? OK. That response we capture in the SendResponseFilter and we would like to write it into some file.
But it is Gzipped, so If we write it like this, it will print something like this 
> $ٰI�R�w�#���*�� 

So, I had to use the:
> GZIPInputStream then BufferReader with UTF-8 encoder

to get it unzipped. However, when you look at the chrome page now seeing the response, you see it normal String, unzipped one, not a zipped as the flow logic of the [SendResponseFilter.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java) says.
So I was expecting to see it like that in the chrome page:

> $ٰI�R�w�#���*�� 

That's what I am asking of, why has appeared unzipped?

**Comment by ryanjbaxter** [comment]
OK now I understand what you are saying.  I believe browsers will automatically decompress the response from what I have read online anyways.

**Comment by mirak94** [comment]
That's great, Thank you very much!
