### ISSUE TITLE
Configure zuul failover for eureka discovered services

### ISSUE THREAD

**Issue by repos-jmp** [spring-cloud/spring-cloud-netflix#2116]
Hi,

I have  a bunch of [services ](https://github.com/repos-jmp/springcloud-microservices-kotlin/tree/master/categories-service/src/main/kotlin/net/jayanth/msdp)registering with Eureka via [Config Server](https://github.com/repos-jmp/msdp-config-repo), these are accessed via a [client application](https://github.com/repos-jmp/springcloud-microservices-kotlin/blob/master/order-management/src/main/kotlin/net/jayanth/msdp/OrderManagementApplication.kt) on which I have enabled Zuul proxy, I have a single[ failover service](https://github.com/repos-jmp/springcloud-microservices-kotlin/tree/master/failover-service/src/main/kotlin/net/jayanth/msdp) for all my services which needs to be called in case one of them is down. I went thought the Hystrix and Zuul documentation but wasn't able to figure out if I need to wire-in this failover by manually configuring each service in zuul, or if it can be used in conjunction with eureka discovery.

Could you please guide me on how I can configure zuul to redirect to this one default failover service ?

**Comment by spencergibb** [comment]
So your services and failover service are separate logical services, not just more instances of the same service, correct?

**Comment by repos-jmp** [comment]
Yes, they are separate logical services. The failover has same internal code at the moment for ease of scaffolding, but will be completely different in future.

**Comment by repos-jmp** [comment]
Request some guidance on this..

**Comment by ryanjbaxter** [comment]
This is not something I have seen anyone do but you can configure a fallback response for Hystrix when using Zuul, http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#hystrix-fallbacks-for-routes.  I wonder if you could then try and call your failover service from that fallback.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
