### ISSUE TITLE
Console log is flooded by strange message

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2124]
I have been running an application using zuul for a week, and today is the first time that console log is flooded by this message:

```
INFO [zuul-edge-service,de4097179fd9c9ed,de4097179fd9c9ed,false] 1581 --- [pool-6-thread-1] s.m.s.d.i.HystrixLogCollectorServiceImpl : Command Metrics count empty: 0
```

and it is kept to be generated continuously. This might cause a degraded application, has anyone sees this message before?
Thank you in advance.

**Comment by spencergibb** [comment]
Where is `HystrixLogCollectorServiceImpl` from?

**Comment by mirak94** [comment]
Well, I have been searching to know that, but I still can't recognize it as well. I can't recognize where it comes from, I don't use hystrix even in my project!

**Comment by spencergibb** [comment]
Please reopen if you find it and think it is a problem related to this repo.
