### ISSUE TITLE
Disabling Zuul filter not working

### ISSUE THREAD

**Issue by DiogoRibeiroTalkdesk** [spring-cloud/spring-cloud-netflix#2126]
We're trying to disable `SimpleHostRoutingFilter` by following http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#_disable_zuul_filters

In `application.properties` we set `zuul.SimpleHostRoutingFilter.route.disable=true` and our app is using annotations `@EnableZuulProxy` and `@SpringBootApplication`, however the filter is still being added.

Any help?

**Comment by ryanjbaxter** [comment]
This works fine for me using Dalston.SR1

**Comment by DiogoRibeiroTalkdesk** [comment]
Thanks for the quick feedback @ryanjbaxter.

We thought that by disabling the filter it wouldn't be added to `FilterProcessor`. A clear case of pbkac...

All working as expected.
