### ISSUE TITLE
Listen for Service Registration/DeRegistration Events and add/remove custom Zuul Rule

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-netflix#2130]
We are using Zuul as the gateway and Eureka as Service Registry in our system.

We have a custom rule in zuul configuration as below, For each new service in our system we add the below rule.

 zuul:
  routes:
    users:
      path: /api/myusers/**
      serviceId: users_service

My query is there a simpler and better way to automate adding this custom rule to zuul routes whenever a service gets registered to Service Registry.

What I mean Is, Is  there is a way to listen for service registration events and whenever registration is successful add a rule to zuul route config (if not already configured ) at run-time and similarly remove the rule when service is unregistered.
Assuming, of course, that the path info for the rule  is available as a configuration when the service starts up.

**Comment by spencergibb** [comment]
By default services registered in discovery are added to zuul as routes if not ignored. If you want to do something similar, see https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/discovery/DiscoveryClientRouteLocator.java

**Comment by bsridhar123** [comment]
@spencergibb  Thanks for your response. Let me check if I can do something similar. But, I am still now clear on how can I listen for service registration/de-registration events so that I can plug-in my custom code accordingly.

**Comment by spencergibb** [comment]
@bsridhar123 eureka doesn't publish events like that that I'm aware of.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
