### ISSUE TITLE
Zuul throws HystrixRuntimeException 

### ISSUE THREAD

**Issue by kasibkismath** [spring-cloud/spring-cloud-netflix#2133]
Faced similar issue as [this one](https://github.com/spring-cloud/spring-cloud-netflix/issues/1432). 

When the microservice is accessed directly it works as expected and Hystrix too works properly. The issue is when accessing the microservice through Zuul which uses Eureka and Ribbon.

Solution 1 : Added hystrix.command.default.execution.timeout.enabled=false to Zuul's application property solved the issue.

However, I need to have the hystrix timeout property per microservice API by using the command key in the microservice's application property file.

Solution 2 : For the above to work together with Zuul, I added hystrix.command.**Eureka_Client_Service_ID**.execution.isolation.thread.timeoutInMilliseconds=10000 to Zuul's application property which some what solved the issue.

My questions are : 
1. How adding timeout per microservice in Zuul's application property solved my issue?
2. Relationship between Zuul, Hystrix and Eureka in relationship to timeouts?
3. Is there any way that the timeout is picked from the command key instead of the microservice service id when accessing the microservice through Zuul?

**Comment by spencergibb** [comment]
There is no timeout for eureka, it is simply registration and discovery. Setting the timeout how you did is correct. I don't understand the 3rd question.

**Comment by kasibkismath** [comment]
Hi Spencer Gibb,

Solution 1 worked for me, by completely disabling hystrix timeout from Zuul's application property while having the hystrix timeout only in the microservices application property. Thereby, resolving the HystrixRuntimeException while accessing the microservice through Zuul.

My third question was some what related to my solution 2, instead of having hystrix.command.**Eureka_Client_Service_ID**.execution.isolation.thread.timeoutInMilliseconds=10000 replace it with this hystrix.command.**CommandKey**.execution.isolation.thread.timeoutInMilliseconds=10000, in Zuu'ls application property. 

However, solution 2 isn't feasible, therefore went forward with solution 1.

**Comment by spencergibb** [comment]
The serviceid is the command key.
