### ISSUE TITLE
Service Log Aggregation

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#214]
This may already exist within the Spring Cloud project.  Are there any existing implementations for aggregated logging for services?  

Preferably something utilizing the existing Bus.  Using Logstash seems to be popular. The problem I have is installing the Logstash agent takes almost as much RAM on the service as the service itself.

**Comment by dsyer** [comment]
Cloudfoundry already has aggregated logging, so it's not going to be a high priority for Spring Cloud. If you have an implementation in mind feel free to suggest something though (Spring AMQP has log4j and logback support already, so you can probably just use that).

**Comment by ccit-spence** [comment]
What are your thoughts on using something like example as a basis?

https://github.com/spring-projects/spring-amqp-samples/tree/master/log4j

**Comment by dsyer** [comment]
That's what I meant in my last comment (but we would prefer to use autoconfig to detect the logging system in use and switch to logback if it is available).
