### ISSUE TITLE
Eureka: Can I get the  service's name which is DOWN from Eureka Server?

### ISSUE THREAD

**Issue by asdfs1** [spring-cloud/spring-cloud-netflix#2140]
I want to know which service is down, but I don't know how. Is there any API provide such data?

**Comment by Aloren** [comment]
Try:
http://host:8761/eureka/apps
It will return all registered apps with details.
Or use `EurekaClient` which provides method `getApplications`.

**Comment by spencergibb** [comment]
👍 to what @Aloren said
