### ISSUE TITLE
Eureka static resource seems to not loading sometimes

### ISSUE THREAD

**Issue by mikymike95** [spring-cloud/spring-cloud-netflix#2141]
Sometimes eureka dashboard is displayed without any design: it looks basic and ugly I mean, no spring logo or image etc... 
With chrome developer tools i have this error : 

- GET http://my_ip:8761/eureka/css/wro.css 404 not found
-  GET http://my_ip:8761/eureka/css/wro.js 404 not found

For the records, this problem happens randomly. Which complicates to find the origin.
**What could be the problem?**

Looking quickly spring-cloud-netflix-eureka-server i found how wro.css and wro.js are generating (with wro4j-maven-plugin) but don't really know what's the problem. 

**My configuration** : 

- Spring cloud version : _Camden.SR5_
- Java 8
- Use eureka with config client

(Just use @EnableEurekaServer to enable discovery server)

Could someone help me please ?

**Comment by spencergibb** [comment]
config server and eureka have conflicting paths. Did you change the root of config server?

**Comment by mikymike95** [comment]
I updated the description, i use eureka with the config client part because eureka config server is an other service in our application.

**Comment by spencergibb** [comment]
We have tests in the codebase for this, so you'd need to provide a small sample that recreates the problem.

**Comment by mikymike95** [comment]
Like i said in the description it's seems to occur randomly. I'll try. 
FYI, we have no customization. We use 
`@EnableEurekaServer`
`@SpringBootApplication`
`public class OurApplication`

with

```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
</dependency>
```
for spring cloud config.
and 
```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-eureka-server</artifactId>
</dependency>
```
for eureka.

**Comment by spencergibb** [comment]
OK, let me know if you can provide something that consistently recreates the problem.

**Comment by mikymike95** [comment]
A little sample to reproduce this issue. 
Please note it occurs randomly.
Please notice, we use the jar under a docker environement. I mean we build a docker image with and entrypoint which look like "java -jar server.jar"

[discovery-sample.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1169806/discovery-sample.zip)

**Comment by spencergibb** [comment]
Please try with the latest Camden.SR7 or Dalston.SR2. Also, can you capture some logs when it does happen?

**Comment by mikymike95** [comment]
After some research we found the problem. It was a conflict on spring properties . We use in our application spring.resources.add-mappings=false. That prevents eureka to retrieve static resoures. 
I close the issue
