### ISSUE TITLE
hystrix.stream

### ISSUE THREAD

**Issue by sdjnzjl** [spring-cloud/spring-cloud-netflix#2150]
Why latencyExecute only 0th, 25th, 50th, 75th, 90th, 95th, 99th, 99.5th?
What is the probability of significance between such a small data interval 99th and 99.5th do

**Comment by spencergibb** [comment]
That's a question for the Netflix/Hystrix issue tracker.

**Comment by sdjnzjl** [comment]
Is this a probabilistic question?

**Comment by spencergibb** [comment]
We don't maintain Hystrix
