### ISSUE TITLE
The method of saving and updating does not require retry. Can feign control such an operation

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [spring-cloud/spring-cloud-netflix#2152]
Feign's retry mechanism by default is a retry of all request methods, how to control a method not retry, such as modifying or saving methods in a service

**Comment by spencergibb** [comment]
What version are you using? I think in the latest versions, retry only happens by default on `GET` and a property needs to be set to retry other HTTP methods.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pasinski** [comment]
Hey. I am using currently version 9.5.1, but unfortunately also newest version of feign will try a retry even on POST or PUT methods. See feing.SynchronousMethodHandler and feign.FeignException#errorExecuting. When there is an IOExeption, a RetryableException gets always thrown, no matter what request method

**Comment by ryanjbaxter** [comment]
Can you please open a separate issue with a sample that reproduces the problem?
