### ISSUE TITLE
Merge request RibbonCommand thread pool related PR into 1.3.x branch

### ISSUE THREAD

**Issue by yongsungyoon** [spring-cloud/spring-cloud-netflix#2153]
@spencergibb @ryanjbaxter, Could you merge PR https://github.com/spring-cloud/spring-cloud-netflix/pull/2107 and PR https://github.com/spring-cloud/spring-cloud-netflix/pull/2074 into `1.3.x` branch ? 
Those were merged into `master` and `2.0.x` branch now. I think that it would be good to be provided in Dalston release and the changes are compatible with Dalston.

**Comment by spencergibb** [comment]
I think I'm ok with #2107, but I'd have to be convinced for #2704

**Comment by yongsungyoon** [comment]
@spencergibb https://github.com/spring-cloud/spring-cloud-netflix/pull/2074 is just providing additional options for thread isolation strategy. There is no changes for default behavior of zuul unless if user set the option. 

#2074 provides the option that the user can choose more specific thread pool strategy. Without this option, all routing request will be executed on single `RibbonCommand` thread pool and it might not be an expected behavior of zuul for some environment like us. The option could provide more options for user who is using thread isolation strategy, so user can choose the thread pool that requests are executed on  - all requests are executed on a single thread pool OR on each routing specific thread pool.
