### ISSUE TITLE
Customize Ribbon Load Balancing Strategy with Zuul/Eureka

### ISSUE THREAD

**Issue by volijaadu** [spring-cloud/spring-cloud-netflix#2154]
We are facing issues with requests being routed to down services from Zuul.

I understand that Zuul uses Ribbon to load balance and route requests after fetching instance info from Eureka using the serviceId.

I want to know what is the default load balancing strategy used when using Ribbon with Zuul/Eureka.

Also,Is there any way we can fine tune/change to a different ribbon strategy in Zuul to route requests.

We are currently using Spring Cloud Dalston.SR1 release and Spring Boot 1.5.4.

**Comment by bijukunjummen** [comment]
Ribbon client name used with Zuul is the service id that you have set. You can customize Ribbon using this client name - http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#spring-cloud-ribbon

**Comment by volijaadu** [comment]
@bijukunjummen Thanks for your response. Let me check on them.

What is the default ribbon load balancing strategy when using with Zuul/Eureka.

Is there a way to set customize rules , using spring boot , application properties rather than writing custom configuration classes and customising the loadbalancing rules.

**Comment by spencergibb** [comment]
It is round robin by default

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
