### ISSUE TITLE
Eureka client interferes with spring-kafka retrying consumer 

### ISSUE THREAD

**Issue by dndanoff** [spring-cloud/spring-cloud-netflix#2161]
Hi,
I am raising this issue as suggested from my issue in spring-kafka projet:
https://github.com/spring-projects/spring-kafka/issues/377

The issue happened with spring-cloud version Camden.SR5 if it matters.
The Beans defined in my application were overriden. The fix was to change the name of the following Beans that I have defined in my kafka consumer configuration: retryPolicy, backOffPolicy and retryTemplate. These beans are used to retry failed messages in the consumer.

Do you see it as real problem that needs to be fixed?

**Comment by spencergibb** [comment]
I don't think it's an issue. Bean names are always subject to clashes. The `retryTemplate` is defined in the spring-cloud-commons project.
