### ISSUE TITLE
What is the simplest way to achieve zero downtime deploy ?

### ISSUE THREAD

**Issue by dndanoff** [spring-cloud/spring-cloud-netflix#2162]
Hi,
this is more of a question than a real issue.
Currently our setup uses spring-cloud Camden.SR5 and has Eureka server where we have registered one Spring Boot microservice in it. We have API Gateway that uses Zuul with its default settings registered as discovery client, that way it creates route mappings based on the services in the Eureka. How can we achieve zero downtime deploy of a new version of microservice.
I think it is possible if we deploy the new instance and /pause the old one from the actuator and manage to finish both actions in 30 sec. That way if Zuul receives request to the miscroservice it will fetch the available services from Eureka and will route the request to the newly deployed one.
Is this approach valid? Do you have better practical solutions on how to achieve zero downtime deploy or blue green deploy ?

**Comment by bijukunjummen** [comment]
Also add in a configuration to retry at the level of zuul - this way even if old servers are retrieved by the client, a retry may fix it - see discussion here https://github.com/spring-cloud/spring-cloud-netflix/issues/1290

**Comment by dndanoff** [comment]
@bijukunjummen do you have example of these properties because I have read that discussion and didn't manage to write working retry code.

**Comment by ryanjbaxter** [comment]
Take a look at http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#retrying-failed-requests

**Comment by dndanoff** [comment]
Ok I checked the docs. Our ZuulProxy uses Dalston.SR2, we have spring-retry in our dependencies and this is application.properties content:
```
zuul.retryable=true

# Max number of retries on the same server (excluding the first try)
client.ribbon.MaxAutoRetries=0
# Max number of next servers to retry (excluding the first server)
client.ribbon.MaxAutoRetriesNextServer=1
# Whether all operations can be retried for this client
client.ribbon.OkToRetryOnAllOperations=true
# Interval to refresh the server list from the source
client.ribbon.ServerListRefreshInterval=2000
# Connect timeout used by Apache HttpClient
client.ribbon.ConnectTimeout=3000
# Read timeout used by Apache HttpClient
client.ribbon.ReadTimeout=3000
```
However if we have 2 instances of a microservice in Eureka and we kill one of them. The ZuulProxy still routes the requests to it but they fail and they are not retried to the other instance.

**Comment by ryanjbaxter** [comment]
What is the status code that is being returned when the request fails?

**Comment by dndanoff** [comment]
HTTP 500
Body
{
"timestamp": 1501658336572,
"status": 500,
"error": "Internal Server Error",
"exception": "com.netflix.zuul.exception.ZuulException",
"message": "TIMEOUT"
}

**Comment by ryanjbaxter** [comment]
Hystrix looks to be timing out before the request can be retried.  Try to adjust the hystrix timeout so it is longer.

**Comment by dndanoff** [comment]
Ok I finally managed to make it work and I want to write how I made it for future reference. The effect that was achieved is when I kill one of the instances the request is retried to the other one. What I changed are the dependencies and the application property file.  Also if you do not specify client name in the ribbon properties they are threated globally, also I have increased the hystrix timeout.

The needed dependencies are:

```
               <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-ribbon</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-hystrix</artifactId> 
		</dependency>
```

The application property is:

```
zuul.retryable=true

# Increase the Hystrix timeout to 6.5s (globally)
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6500

# Ribbon global settings
ribbon.retryable=true
# Max number of retries on the same server (excluding the first try)
ribbon.MaxAutoRetries=0
# Max number of next servers to retry (excluding the first server)
ribbon.MaxAutoRetriesNextServer=1
# Whether all operations can be retried for this client
ribbon.OkToRetryOnAllOperations=true
# Connect timeout used by Apache HttpClient
ribbon.ConnectTimeout=3000
# Read timeout used by Apache HttpClient
ribbon.ReadTimeout=3000
```
