### ISSUE TITLE
Build breaking on master

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-netflix#2164]
Adding this issue for tracking purpose: build is failing on master(when executed via circleci) with the following message:

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.0:jar (default-jar) on project spring-cloud-starter-eureka: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1] ```

**Comment by bijukunjummen** [comment]
This could be something very specific to circleci, the build completes cleanly on local, on an isolated concourse ci

**Comment by ryanjbaxter** [comment]
I was able to reproduce this locally by running the same mvn command that is used on CircleCI
`./mvnw -s .settings.xml clean install org.jacoco:jacoco-maven-plugin:prepare-agent install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn`

**Comment by ryanjbaxter** [comment]
Specifically it seems to be the installation of `org.jacoco:jacoco-maven-plugin:prepare-agent install` that is causing the problem.

**Comment by spencergibb** [comment]
Should that even run on circle?

**Comment by ryanjbaxter** [comment]
Ah we had to install goals specified.  It should be working now.

**Comment by bijukunjummen** [comment]
:-), awesome, nice catch!
