### ISSUE TITLE
Performance Metrics for Zuul/Eureka

### ISSUE THREAD

**Issue by volijaadu** [spring-cloud/spring-cloud-netflix#2165]
Is there a way to collect performance metric for Zuul and Eureka related to : throughput, response time, overhead (chaining requests) and error rate.

**Comment by spencergibb** [comment]
Do the registered routes not show up in `/metrics`?

**Comment by volijaadu** [comment]
I do not see the registered routes showing up in /metrics.

I do see metrics information on the hystrix ribbon commands which wraps the calls to downstream clients from zuul, on /metrics endpoint of zuul.

For Example,,
gauge.servo.hystrix.hystrixcommand.ribboncommand.<serviceId>.rollingcountfallbackemit:
gauge.servo.hystrix.hystrixcommand.ribboncommand.<serviceId>.requestcount:

But, I do not see any info on throughput, responsetime or errorrate.

Do we have to add any beans to generate the metrics info accordingly

**Comment by Aloren** [comment]
We have the following metrics registered by default for any route:
[route metrics](https://gist.github.com/Aloren/eb85d79722133b8c538e41638cc79600).
We also enabled hystrix and are using Turbine for aggregating hystix streams:
<img width="1122" alt="screen shot 2017-08-16 at 6 52 27 pm" src="https://user-images.githubusercontent.com/1207414/29372688-8470a644-82b4-11e7-9da7-099becdd8f1e.png">

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
