### ISSUE TITLE
Zuul needs to provide CORS configurability through Settings.

### ISSUE THREAD

**Issue by Webdesics** [spring-cloud/spring-cloud-netflix#2167]
Just the way zuul allows us to specify:

 ignoredServices: '*'
 prefix: /myapp
 routes: ...

etc.. It needs to allow us to specify **Cors** specifications, at global level and individual route level.

(If this feature is already present, kindly point me to the right resource to learn more about it. From what I know it isn't available yet.)

**Comment by ryanjbaxter** [comment]
Can you elaborate?  Zuul is proxing the request so making a request to a downstream service does not require CORS.

**Comment by orange00** [comment]
I believe it does. For example, if you have an Angular Web UI running on a different port than Zuul, than it would require CORS for the Angular Web UI to call any service exposed by Zuul. Wouldn't it?

**Comment by spencergibb** [comment]
@Webdesics can you describe exactly what you are imagining?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by richardbarabe** [comment]
Hello.   I'm trying to use zuul with @EnableOauth2Sso.  My client application is made with angluar.  When that application tries to make a request to a service behind zuul, it first make a OPTION request.

The zull server answer with a 302 for a login page.  I already have the keycloak token in my angular app.  I just want to pass it to my service.  How can I make zuul simply return 401 when the token is not included and when it is, just forward it to the underlying service ?

I'm sorry if it's not the right place to ask, I tough it was related with the original question.

**Comment by ryanjbaxter** [comment]
It might be better to ask you question in the spring cloud security repo
