### ISSUE TITLE
Spring cloud consul with Feign Client

### ISSUE THREAD

**Issue by sunaina-ishi** [spring-cloud/spring-cloud-netflix#2168]
I am trying to use @FeignClient annotation with consul agent to discover a service. I have a spring boot application which is trying to invoke another spring boot application using RestTemplate. I want to replace resttemplate with Feign Client implementation. Below is the Feign client having consul url.

@FeignClient(value= "service-name", url = "http://localhost:8500")
public interface InterceptTargetStoreFeignClient {

    @RequestMapping(value = "/abc", method = RequestMethod.GET)
    ResponseEntity<gpb object> getAbc();
}

Invoking the URL is giving 404 error. Any help will be appreciated

**Comment by spencergibb** [comment]
Is your service running on `http://localhost:8500`? I suspect it's not and you just put the consul api url there. Remove the url attribute.

**Comment by sunaina-ishi** [comment]
Thanks for the reply. It seems I made some progress. Yes the consul service is running. Removed the "url" attribute and added dependencies for "consul" and added annotation "@EnableDiscoveryClient". Making a call to health URL works but I have an API that returns GPB and some accept GPB. In rest template, I usually set the content type in the headers. Can it be done with Feign as well ?

**Comment by ryanjbaxter** [comment]
You will want to use Spring MVC annotations to set the appropriate headers.

**Comment by sunaina-ishi** [comment]
Thanks all worked !
