### ISSUE TITLE
Modifying request body in Zuul pre filter not working

### ISSUE THREAD

**Issue by varunkr** [spring-cloud/spring-cloud-netflix#2171]
In my app I am using `netflix zuul` to route a request from a microservice (gateway) to another. The requests are being routed fine but I also want to introduce some parameters in the request body before it is routed to the appropriate microservice. For this I am using Zuul pre filter like this.

```
public class SimpleFilter extends ZuulFilter {
    
    	private static Logger log = LoggerFactory.getLogger(SimpleFilter.class);
    
    	@Override
    	public String filterType() {
    		return "pre";
    	}
    
    	@Override
    	public int filterOrder() {
    		return 1;
    	}
    
    	@Override
    	public boolean shouldFilter() {
    		return true;
    	}
    
    	@Override
    	public Object run() {
    
    		try {
    			RequestContext context = RequestContext.getCurrentContext();
    
    			InputStream in = (InputStream) context.get("requestEntity");
    			if (in == null) {
    				in = context.getRequest().getInputStream();
    			}
    			
    			String body = StreamUtils.copyToString(in, Charset.forName("UTF-8"));
    			
    			// body = "request body modified via set('requestEntity'): "+ body;
    			body = body.toUpperCase();
    			context.set("requestEntity", new ByteArrayInputStream(body.getBytes("UTF-8")));
    
    		} catch (IOException e) {
    			log.error(e.getMessage(), e);
    		}
    
    		return null;
    	}
    
    }
```

For now I am just trying to change the body to upper case but the microservice to which this request is routed doesn't receive the modified body (upper case). Instead it receives the original one. Am I doing something wrong. Any help would be appreciated. Thanks !!

**Comment by ryanjbaxter** [comment]
Please don't post your question in multiple places.  We will use SO. https://stackoverflow.com/questions/45412149/modifying-request-body-in-zuul-pre-filter-not-working

**Comment by rashad-farajullayev** [comment]
I need to change request body as well. I tried this case, and this doesn't work me either. 
Please give a hint how to alter real request body so that the receiver node could handle only the modified body

**Comment by ryanjbaxter** [comment]
Please open a separate issue with an example of what you have tried and what exactly is not working.

**Comment by rashad-farajullayev** [comment]
@ryanjbaxter, I created the issue here:
https://github.com/spring-cloud/spring-cloud-netflix/issues/2693
Thanks for fast response.
