### ISSUE TITLE
Is "Active/Active traffic management" should be "Active/Un Active traffic management"?

### ISSUE THREAD

**Issue by cloudhuang** [spring-cloud/spring-cloud-netflix#2174]
In the spring cloud documentation Zuul part, 

> Router and Filter: Zuul
> Routing in an integral part of a microservice architecture. For example, / may be mapped to your web application, /api/users is mapped to the user service and /api/shop is mapped to the shop service. Zuul is a JVM based router and server side load balancer by Netflix.

> Netflix uses Zuul for the following:
> ......
> Active/Active traffic management

**Comment by spencergibb** [comment]
No, that's a quote from Netflix.
