### ISSUE TITLE
PreDecorationFilter doesn't allow to switch off URL-decoding in its UrlPathHelper instance

### ISSUE THREAD

**Issue by robz23** [spring-cloud/spring-cloud-netflix#2178]
`PreDecorationFilter` is responsible for resolving the route for the received `requestURI` obtained via `HttpServletRequest#getRequestURI()` method.

The first problem I'm facing is that my request URI contains URL-encoded forward slashes among other URL-encoded characters (originating from Base64 alphabet), e.g.
**'/context/a%2Fb/c/d'**. When the URI gets decoded in `PreDecorationFilter `and the corresponding route exists, the `RequestContext.put("requestURI", requestURI)` method sets the `requestURI  `property to **'/context/a/b/c/d'**. Then, the altered URI value is used by `ProxyRequestHelper#buildZuulRequestURI(HttpServletRequest)` method resulting in an invalid forward further down the line.

The problem can be mitigated by allowing access to the ProxyRequestHelper instance as follows:
- By a getter method in PreDecorationFilter class, providing it never return null.
- By a setter method in PreDecorationFilter class so it can be overridden with a new instance.
- Possibly via the constructor of PreDecoratorFilter although this option might result in a more complex configuration.

The second issue affecting my use case is related to `ProxyRequestHelper#buildZuulRequestURI(HttpServletRequest)` method, which executes URI path encoding of the `RequestContext.put("requestURI")` value before returning it. The side effect of this is that every **%** character will turn into **%25** and will also alter the original URI. Is this step absolutely necessary or could be made configurable?

Although I have successfully managed to work around both problems, I had to implement a number of custom enhancements and wire them into my service configuration to make it work as expected.

**Comment by spencergibb** [comment]
One issue at a time please.

We customize the `UrlPathHelper` with properties, so that is one option. A setter could also work.

**Comment by robz23** [comment]
Let's focus on `UrlPathHelper `first. Just looking int the current master branch, I can see that the only property being customised at the moment is `this.urlPathHelper.setRemoveSemicolonContent(properties.isRemoveSemicolonContent());` set in the constructor.

If a new setter method is what you agree with me as an enhancement, I would be more than happy to support it.

**Comment by spencergibb** [comment]
That's fine, PR welcome

**Comment by ryanjbaxter** [comment]
Fixed via a1f7bab
