### ISSUE TITLE
DOWN status of application  still show the UP status in eureka page?

### ISSUE THREAD

**Issue by kentTanL** [spring-cloud/spring-cloud-netflix#2179]
Hi ,

I encountered a problem, the eureka page is shown like this:  

Application | AMIs | Availability Zones | Status
-- | -- | -- | --
GATEWAY | n/a (2) | (2) | UP (2) - WCMIS208:GateWay:10020 , WCMIS209:GateWay:10020

but 'GATEWAY' has been closed on 'WCMIS208', so its status should be 'DOWN' or not displayed.

Although this does not affect the normal use, but I still want to where is the problem? thank you all

**Comment by ryanjbaxter** [comment]
What do you mean it has been closed?  Is Eureka in "self-preservation mode"?  If it is it won't evict any down instances.

**Comment by kentTanL** [comment]
Thanks, you are right, and I saw this:

> EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
> [https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication](https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication)
> [http://www.itmuch.com/spring-cloud-sum/understanding-eureka-self-preservation/](http://www.itmuch.com/spring-cloud-sum/understanding-eureka-self-preservation/)

So, can I manually remove it? Thanks  again

**Comment by ryanjbaxter** [comment]
It is not recommended but you can disable self preservation mode by setting `eureka.server.enableSelfPreservation` to `false`

**Comment by kentTanL** [comment]
I got it, Thanks very much,
