### ISSUE TITLE
Zuul - Support of Asynchronus request forward mechanism

### ISSUE THREAD

**Issue by stiyyagura** [spring-cloud/spring-cloud-netflix#2181]
Currently we are using Camden.SR6 release of Spring Cloud Netflix Zuul components. Recently we have requirement to see if Zuul framework can achieve Asynchronous way of calling back-end services??

Is this something not there in current Zuul?? If Not available then what are the other alternatives?
We are in AWS and not sure if SQS supports retry mechanism if the back-end service is not available at that point of time? Also SQS has payload limitation.

**Comment by ryanjbaxter** [comment]
Could you perhaps describe your use case some more?

**Comment by stiyyagura** [comment]
Here is the use case:

We have Third party SOAP services, which are on-boarding to Zuul API Gateway. The additional use case is Client wanted to have asynchronous call of submitting the request to third party SOAP service provider but client is expecting the response from API gateway to tell the request from the client is submitted successfully to third part SOAP service provider.

Please let me know if i need to add any more to the above information.

Best Regards

**Comment by ryanjbaxter** [comment]
I dont think we have any plans to support anything like that at the moment.

**Comment by stiyyagura** [comment]
In that case i am thinking to achieve this in 2 ways -
**1. Submitting Client Request asynchronously**
what if I can write a specific @Service in Zuul Gateway and create a method with @Async annotation and which will intern calls the third party service and also this method can respond client that it submitted the request to the 3'rd party service successfully. 
2. Having a Queue to push the request and calling the third party service and reading the results from the Queue later by polling.

Can you comment on this please.

**Comment by spencergibb** [comment]
At that point, wouldn't it be easier to just write it as a Spring MVC `@Controller`?

**Comment by stiyyagura** [comment]
@spencergibb I am assuming you are saying have a controller which will post the original request to the 3'rd party service? and call the controller from the Zuul having @EnableAsynch and where the componnent has @Async method which actually invokes this controller??

**Comment by spencergibb** [comment]
No, I think doing it in zuul might be overkill when you could just do spring mvc in the zuul application.
