### ISSUE TITLE
@ConfigurationProperties bean created twice when Bootstrapping with Eureka

### ISSUE THREAD

**Issue by joonhaeng** [spring-cloud/spring-cloud-netflix#2186]
here is my code

```java
package com.example.demo.config;

import javax.annotation.PostConstruct;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConfigurationProperties
public class DemoConfigurationProperties {

	private String demo;

	@PostConstruct
	private void init() {

		System.out.println("call init()");

	}

}
```

when i not add eureka library, all beans are create once.
but when apply eureka library, beans with @ConfigurationProperties create twice. and "call init()" appeared two times in console.

is this intentional operation? or bug?

attached my demo project here. 
[demo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1207013/demo.zip)

**Comment by spencergibb** [comment]
That is because of the bootstrap context (from spring-cloud-commons, not here). Another application context is created. Besides it getting created twice are you experiencing any problems?

Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by joonhaeng** [comment]
fix my code highlight. thx.
Should I move this issue here to spring-cloud-commons?

**Comment by spencergibb** [comment]
I'll repeat my question
> Besides it getting created twice are you experiencing any problems?

**Comment by joonhaeng** [comment]
sorry for my poor english...


in tracking, not create bean twice, but create bean once and call PostConstruct twice

example code
```java
package com.example.demo;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConfigurationProperties
public class DemoConfig {

	private List<String> test = new ArrayList<String>();

	@PostConstruct
	private void init() {

		test.add("for-test");
		System.out.println(this); // print object hashcode
		System.out.println(test); // print List [test]

	}

}
```

expect result is ArrayList<String> test with contains one "for-test" string.

but actual result is ArrayList<String> test with contains two "for-test" string because call PostConstruct twice.

![image](https://user-images.githubusercontent.com/7742563/29666739-8f0f85a0-8914-11e7-8680-bfbdd6f25b9e.png)


usually think PostConstruct is call only once per bean. finally, i move my bean initialization logic from PostConstruct to ApplicationReadyEvent.

is my think(PostConstruct is call only once per bean) is wrong?

**Comment by spencergibb** [comment]
Please, no screenshots.

Please open an issue in spring-cloud-commons.

**Comment by dongxingong** [comment]
I have the same problem
