### ISSUE TITLE
Health endpoint description

### ISSUE THREAD

**Issue by wgorder** [spring-cloud/spring-cloud-netflix#219]
On my API gateway when I hit the /health endpoint as an unauthenticated user I get this description
`Spring Cloud Eureka Discovery Client`

The only place I see this is in EurekaDiscoveryClient -
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClient.java

Any idea why my health endpoint feels the need to spit that out?

**Comment by dsyer** [comment]
It's probably the only `HealthIndicator` that bothers to provide a description. Otherwise you'd see them all I think.

**Comment by wgorder** [comment]
Hmm.  From what I see that description is part of the DiscoveryClient interface, not the HealthIndicator.  Looking at the health indicator I see a call to getInstanceRemoteStatus() which I don't even see exposed by the interface.  I must be missing something.  The weird thing is when you hit the health endpoint as an unauthenticated user you see the UP,DOWN etc (as you would expect) and a description saying `Spring Cloud Eureka Discovery Client`.  There is nothing else.  When you are authenticated things look like more how I would expect.  I just thought that description seemed out of place since it in know way describes the application I am checking the health on.

https://github.com/spring-cloud/spring-cloud-netflix/blob/6435b73f40257b23b5d5a076d5856aaee148b39c/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/eureka/EurekaHealthIndicator.java

**Comment by dsyer** [comment]
The description is added here: https://github.com/spring-cloud/spring-cloud-commons/blob/master/src/main/java/org/springframework/cloud/client/discovery/health/DiscoveryClientHealthIndicator.java#L47. I'm pretty sure it's just that the other indicators don't have one.

**Comment by wgorder** [comment]
I guess I was in the wrong HealthIndicator.  Thanks.

**Comment by rubesMN** [comment]
I've just walked through the code myself.  Looks like this is the Status description which the EurekaDiscoveryClient hard codes that description "Spring Cloud Eureka Discovery Client" and we are unable to set.   At the minimum, either the DiscoveryClientHealthIndicator or EurekaDiscoveryClient should allow this to be based off of a property.   A health indicator status description of "Spring Cloud Eureka Discovery Client" is non-sensical.   This issue should be reopened.

**Comment by spencergibb** [comment]
@rubesMN this is how spring-boot health indicator descriptions work, they bubble up (see @dsyer's comments above).  If you don't like that, create a health indicator for your app and add a description.

**Comment by rubesMN** [comment]
@spencergibb perhaps its the bubbling up that makes it non-sensical.  The status description of "UP" shouldn't be "Spring Cloud Eureka Discovery Client".. unless the description is supposed to be the noun that the "UP" is referring to.  In the latter case, description should be called 'principal' or something better.  

I do still think Health.Builder IMHO should specify better default status descriptions and/or make that textual description property overridable.

**Comment by spencergibb** [comment]
@rubesMN bubbling up is happens in spring boot, not spring cloud, bring it up there.
