### ISSUE TITLE
ZUUL doesn't work with with Mutual SSL configuration

### ISSUE THREAD

**Issue by bhupendraji** [spring-cloud/spring-cloud-netflix#2193]
I have configured a simple ZUUL proxying to a vendor API. There is a need to configure a mutual SSL in between. For this I've configured below JVM argument
-Djavax.net.ssl.keyStore=<JKS file >
-Djavax.net.ssl.keyStorePassword=<password>
-Djavax.net.debug=ssl

However ZUUL router doesn't present the client certs to the endpoint URL. This works if I use a simple Jersey Client ( no additional coding required")

**Comment by ryanjbaxter** [comment]
It all might depend on your Zuul configuration so I can't say for sure how to make this work without more information.  But in general you need to import the SSL certificate into the JVM in order for the HTTP client used by Zuul to trust it.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by flenzi** [comment]
I have the exact same problem. Created a spring-boot application and make it use ssl with a self-signed certificate(been following mostly this very good guide https://www.baeldung.com/x-509-authentication-in-spring-security). I could achieve the client verification in the server side using a simple RestTemplate call having "javax.net.ssl.keyStore" "javax.net.ssl.keyStorePassword". 

My next step was add the entry for that dummy service, like this:
```
zuul:
  ignoredServices: "*"
  routes:
    secure-service:
      path: /services/secure
      url: https://myhostname:8443/services/secure
      stripPrefix: false
```

Unfortunately Zuul is throwing `javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate`
So @ryanjbaxter is this somthing that should work just providing this properties, or it is needed a custom bean overriding the config (https://stackoverflow.com/questions/48334463/tls-mutual-authentication-between-zuul-and-microservice-with-certificates).

**Comment by flenzi** [comment]
Yes, I did that and it's working with a RestTemplate call. But seems the http client on zuul is not using those properties "javax.net.ssl.keyStore" "javax.net.ssl.keyStorePassword".

**Comment by ryanjbaxter** [comment]
you are right it doesnt use properties at all, you need to import the certificate into the JVM, which does not involve any configuration properties in
