### ISSUE TITLE
Support for retry-backoffs

### ISSUE THREAD

**Issue by joetalos-newsuk** [spring-cloud/spring-cloud-netflix#2195]
While Spring Retry integrated into Ribbon provide a retry-mechanism that even works in a load-balanced scenario ("ribbon.MaxAutoRetries", "ribbon.MaxAutoRetriesNextServer" properties), back-offs are not supported (the "ribbon.BackoffTimeout" property does not work)

Would it be possible to implement the backoff-feature? Apparently Netflix-Ribbon provides two backoff strategies out-of-the-box (exponential and bounded). It would be nice to have either (or both) in Spring Cloud Netflix.

**Comment by spencergibb** [comment]
So we don't support ribbon backoff, but spring retry has a backoff mechanism that I think can be taken advantage off now. Hove you tried anything with spring retry?

**Comment by ryanjbaxter** [comment]
Right.  The problem at the moment is that it would be pretty hard to change the backoff policy.  I think we can make it easier.

**Comment by spencergibb** [comment]
👍 I'd rather not add support for the ribbon backoff properties.

**Comment by thetrishachatterjee** [comment]
Hey @ryanjbaxter @spencergibb, is there any update on this?
What is the working solution for introducing backoff policies that know to have been used successfully?

**Comment by ryanjbaxter** [comment]
The only way to do it currently is to provide your own `RetryableRibbonLoadBalancingHttpClient` and configure the `RetryTemplate` in that class correctly.  Unfortunately that is a little ugly.  

PRs are welcome if you are interested.
