### ISSUE TITLE
Content-Length not in response header when content length exceeds MAX int value

### ISSUE THREAD

**Issue by cbos** [spring-cloud/spring-cloud-netflix#2196]
There is a bug in pull request #1450 , useServlet31 is always false.
Which results in the fact that the max content-length is always checked whether it fits in an int value, only then it is returned. So for small response it is working well, for bigger file downloads it fails.

See my comment on the pull request:
https://github.com/spring-cloud/spring-cloud-netflix/pull/1450#pullrequestreview-55545301

According to the pull request, the code construction is used twice, so it has to be fixed at both locations.

**Comment by spencergibb** [comment]
Only needed in one place that checks `set` with the param vs. get, no param

**Comment by spencergibb** [comment]
Closed via c2aa60f29246a860653a2b8c04ed1bc844759025

**Comment by cbos** [comment]
Thanks for the quick fix. The other place is indeed a get, so need to change.
