### ISSUE TITLE
turbine failed to start:   Address already in use

### ISSUE THREAD

**Issue by junneyang** [spring-cloud/spring-cloud-netflix#2197]
1. server.port = 8989
if server.port =8989 or any other 8080,8888,18080....etc. all starts failed
log says:
`The Tomcat connector configured to listen on port 8989 failed to start. The port may already be in use or the connector may be misconfigured.`

but netstat -anop|grep 8989 shows nothing

if server.port = 0, it starts ok

2.pom.xml
`<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
        <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-turbine-amqp</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>`

3. code
`@SpringBootApplication
@EnableDiscoveryClient
@EnableTurbineStream
public class Application {

	private static final Logger LOGGER = LoggerFactory.getLogger(Application.class);
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//SpringApplication.run(Application.class, args);
		new SpringApplicationBuilder(Application.class).web(true).run(args);
	}`

thanks for your help!

**Comment by ryanjbaxter** [comment]
There is something using that port on your machine, there is not much we can do to help debugging environment issue.

Please dont paste application code in the issue, its much easier if you provide a zip or a github repo with the code.

Also please learn how to format code properly https://help.github.com/articles/creating-and-highlighting-code-blocks/
