### ISSUE TITLE
Custom handling of "no route" scenario

### ISSUE THREAD

**Issue by madheshr** [spring-cloud/spring-cloud-netflix#2200]
Hi

  Is there a way to intercept and handle requests when there is no route present in Eureka.  For eg.
/key/something.... If there is no "key" route, then expectedly the control does not come to any of my filters.  I am looking a way to intercept such requests and return a fallback response to certain URLs.  For others, the 404 error works well.  
  
  I have tried the ZuulFallbackProvider approach, but that works only for configured routes and not for dynamic ones.  

Thanks

**Comment by spencergibb** [comment]
The best you could do is a default route `/**` that forwarded to a spring mvc controller I think. Otherwise it will never match the zuul handler mapping.

**Comment by madheshr** [comment]
Thanks.  Do you mean a route in Zuul ?  If yes,  can i have a generic filter to handle it.

**Comment by spencergibb** [comment]
Yes a zuul route.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
