### ISSUE TITLE
a question of zuul upload file

### ISSUE THREAD

**Issue by lexburner** [spring-cloud/spring-cloud-netflix#2202]
i want to upload a file through zuul which contians chinese characters in the file name. but in the server application I got garbled.i have tried to use this way,suggested by (http://projects.spring.io/spring-cloud/spring-cloud.html#_uploading_files_through_zuul) add the prefix (/zuul) it works. but i want to standardize the code for the entire project,i can not change the access path because the interface is used to upload files.

about the chinese characters garbled ,is that a bug?

**Comment by ryanjbaxter** [comment]
You can change the path using the `zuul.servletPath` property, but that appears to be the only way to upload large files.

**Comment by spencergibb** [comment]
Closing as answered
