### ISSUE TITLE
Problem with ribbon and https

### ISSUE THREAD

**Issue by mariusznet** [spring-cloud/spring-cloud-netflix#221]
I'm trying to configure feign and ribbon without eureka on https. Unfortunately, despite setting https in `ribbon.listOfServers`, `LoadBalancerContext` still is choosing http protocol. 
It's not surprising though, because Server class from ribbon ignores protocol and stores url with host and port only. On the other hand, `FeignClientFactoryBean` is always appending http protocol to name, which finally is excluded in `FeignRibbonClient` class.
In result in method `reconstructURIWithServer()` both arguments are without protocol.
It looks slightly messy. Am I missing something? Is there any option to use feign and ribbon without eureka on https? And finally, is it working properly with eureka?

**Comment by dsyer** [comment]
It works without ribbon (e.g. if you use `@FeignClient(url = "https://foo.com")`), but the protocol (URL scheme) is lost if Ribbon enters the picture.
