### ISSUE TITLE
How to get eureka replicas server via REST API?

### ISSUE THREAD

**Issue by hsj1606** [spring-cloud/spring-cloud-netflix#2210]
How to get eureka replicas server information via REST API?

**Comment by ryanjbaxter** [comment]
Eureka REST APIs are documented here https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by hsj1606** [comment]
Seems not mentioned in this doc. Is there a wayt to know how many eureka replica server?

**Comment by ryanjbaxter** [comment]
you want to know the number which servers the Eureka server is replicating with?

**Comment by spencergibb** [comment]
If it's not documented, the next place to look is at the actual operation source code. https://github.com/Netflix/eureka/tree/master/eureka-core/src/main/java/com/netflix/eureka/resources
