### ISSUE TITLE
I can't found turbine for zookeeper，so it just suport for eruke?

### ISSUE THREAD

**Issue by rainplus** [spring-cloud/spring-cloud-netflix#2211]
and i found have a another issue ask too?why just close when haven't answer it ?

**Comment by ryanjbaxter** [comment]
Turbine is used to aggregate Hystrix streams, what does that have to do with Zookeeper?

**Comment by spencergibb** [comment]
Turbine should use DiscoveryClient via [CommonsInstanceDiscovery](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine/src/main/java/org/springframework/cloud/netflix/turbine/CommonsInstanceDiscovery.java)

I'm unsure what your other question means:
> why just close when haven't answer it ?
