### ISSUE TITLE
Upgrade archaius to v2.2.2

### ISSUE THREAD

**Issue by xiaoerlyl** [spring-cloud/spring-cloud-netflix#2212]
Do you have any plans  to upgrade archaius to v2.2.2?

**Comment by ryanjbaxter** [comment]
This required Java 8, we will have to do it in the 2.0.0 stream.

**Comment by spencergibb** [comment]
This is not going to happen in 2.0.0 since it is such a big change (removing ribbon is attached to this).

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
