### ISSUE TITLE
The wrong server port was found on the eureka server when use random server.port

### ISSUE THREAD

**Issue by SPRINGJICHUN** [spring-cloud/spring-cloud-netflix#2215]
`application.yml:`
```
server:
  port: ${random.int[1024,65535]}
```
the server start on one random port, but the eureka server's dashboard's instances list show another random port number. Then the zuul server cann't get the right port and work correctly!
I think it is a bug. Do you think so?

我用了上述的配置来生成随机的端口号，但是我发现eureka获取的到端口号也是随机的，这样整个网络就无法正常工作，我认为这是一个bug，它存在不止一个版本中。

**Comment by SPRINGJICHUN** [comment]
A definite port number like 80, 8080 is ok. But I want to use a random port when I run my project on my local machine.

**Comment by ryanjbaxter** [comment]
See #1986.
