### ISSUE TITLE
Upgrade Eureka to v1.8.2

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-netflix#2216]
There is https://github.com/Netflix/Eureka/releases/tag/v1.8.0 published on Aug. 8.

**Comment by spencergibb** [comment]
This can only happen on the 2.0.x branch, as 1.8.0 requires Java 8

**Comment by spencergibb** [comment]
Closed via ec25771453dc078686e0936b634ba6501e3379a3
