### ISSUE TITLE
Remove starters deprecated in 1.4.x

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#2220]
In 1.4.x we deprecated several starters, they need to removed post 1.4.x.

See #665

**Comment by spencergibb** [comment]
Closed via 6775e76e5f16de521285c77e68a3cf7c445c2c96

**Comment by jameyg42** [comment]
suggest to update the (Camden-based) example projects which use the old starter names.  Also, is there a spot where the renames are documented (similar to Boot's "renamed starters" section in the release notes?)

**Comment by ryanjbaxter** [comment]
Can you be specific about what examples need to be updated?  We would be happy to do that.  
https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Edgware-Release-Notes#renamed-starters

**Comment by jameyg42** [comment]
i'm embarrassed i didn't check the wiki for the release notes...
minimally, the samples listed on the spring cloud project page (service registry and circuit breaker dashboard), but basically all the netflix examples in https://github.com/spring-cloud-samples
- https://github.com/spring-cloud-samples/eureka/blob/master/pom.xml
- https://github.com/spring-cloud-samples/github-eureka/blob/master/pom.xml
- https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/pom.xml
- https://github.com/spring-cloud-samples/zuul-server/blob/master/pom.xml
- https://github.com/spring-cloud-samples/hystrix-dashboard/blob/master/pom.xml

**Comment by ryanjbaxter** [comment]
@jameyg42 feel free to open PRs against those projects to update them.  If not we will get to them as soon as we can

**Comment by erikkemperman** [comment]
Just noticed I lost `spectator` in between milestones and the RCs. I'm wondering if there is a recommended replacement / alternative? Or should I just import spectator directly? Sorry if this question is out of place here -- I guess I might have to wait for the notes of `Finchley.RELEASE`.

**Comment by ryanjbaxter** [comment]
Yes we removed spectator in Finchley.
