### ISSUE TITLE
Remove turbine-amqp starter

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#2221]
From #665, specifically https://github.com/spring-cloud/spring-cloud-netflix/issues/665#issuecomment-318024125.  The `turbine-amqp` starter was kept around for backwards compatibility.  Do we want to remove it in the 1.4.x, stream?

**Comment by spencergibb** [comment]
Deprecate in edgware, remove in finchley

**Comment by spencergibb** [comment]
Closed via c511440ed9e87b2195f447e3dfd4201a4d8f8dca
