### ISSUE TITLE
Remove hystrix-amqp starter

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#2222]
From #665, specifically https://github.com/spring-cloud/spring-cloud-netflix/issues/665#issuecomment-318024125

**Comment by spencergibb** [comment]
Deprecate with log warning in edgware and remove in finchley.

**Comment by spencergibb** [comment]
Closed via 6775e76e5f16de521285c77e68a3cf7c445c2c96
