### ISSUE TITLE
Feign Hystrix Configuration property

### ISSUE THREAD

**Issue by mr-rajeshrathod** [spring-cloud/spring-cloud-netflix#2231]
I understand that if we want to enable hystrix to use with feign, we need to set following property in our yml.

feign:
  hystrix:
    enabled: true

However setting above property to false still keep same behavior. I can only disable use of hystrix if I remove this property which is weird.

Can we do like if developer set this property to false then also we should disable hystrix ?

**Comment by indrabasak** [comment]
Which spring cloud version are you using? You can disable Hystrix in Feign in Brixton.SR3 build (1.1.4.RELEASE) using the flag you mentioned.

```yaml
feign:
  hystrix:
    enabled: false
```

**Comment by spencergibb** [comment]
`feign.hystrix.enabled=false` is the default now. What version are you using?

**Comment by indrabasak** [comment]
Yes, it's default in **Dalston.SR3** but not in **Brixton.SR3**.

**Comment by spencergibb** [comment]
Brixton is EOL https://spring.io/blog/2017/07/21/spring-cloud-dalston-sr2-is-available-now#end-of-life-for-angel-and-brixton-release-trains

**Comment by mr-rajeshrathod** [comment]
I was using Camden.SR7 release however switching to Daltston.RELEASE fix this issue. Closing this issue.

Thanks for your response.
