### ISSUE TITLE
Not able to access service deployed in private container through zuul proxy

### ISSUE THREAD

**Issue by angsdey2** [spring-cloud/spring-cloud-netflix#2238]
I have a micro service deployed in private container with no public ip and another two service (Zuul and eureka) with public container with public ip. I can see my zull and micro service is registered in eureka dashboard. But when I tries to access my private microservice through zuul public ip it is giving "com.netflix.zuul.exception.ZuulException". Seems that zuul is not able to discover private container microservice through eureka.

Zuul configuration
---------------------
zuul:
  #Service will be mapped under the /api URI
  prefix: /proxy
  routes:
    test-service:
      path: /test/**
      serviceId: TEST-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie

server:
  port: 80
  
eureka:
  client:
    service-url:
      defaultZone: http://xx.xx.xx.xx/eureka
      
spring:
  application:
    name: REVERSE-PROXY

Eureka Configuration
-------------------------
server:
  port: 80

Microservice Configuration
-----------------------------
server.port=80
eureka.client.serviceUrl.defaultZone= http://xx.xx.xx.xx/eureka
spring.application.name= TEST-SERVICE

**Comment by ryanjbaxter** [comment]
It is pretty hard for us to diagnose connection issues.  You need to make sure the container running zuul can reach the container running the microservice.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
