### ISSUE TITLE
(Question) eureka.client.eurekaServiceUrlPollIntervalSeconds

### ISSUE THREAD

**Issue by jhelbling** [spring-cloud/spring-cloud-netflix#2251]
Am I right when saying that eureka.client.eurekaServiceUrlPollIntervalSeconds property allows a service to update the list of available services which are located in same zone as itself?

The polling interval is by default set to 300 seconds.

Assuming a service doesn't need to be aware of any service in its zone. Is there a property which exists in order to completely disable this polling mechanism? Or as a workaround should we just increase the above property so that it occurs once per day (for example).

**Comment by kylewu** [comment]
@jhelbling According to code comment:
```
	/**
	 * Indicates how often(in seconds) to poll for changes to eureka server information.
	 * Eureka servers could be added or removed and this setting controls how soon the
	 * eureka clients should know about it.
	 */
	private int eurekaServiceUrlPollIntervalSeconds = 5 * MINUTES;
```
as i understand, it means the refresh interval of fetching eureka server information, not service.

**Comment by ryanjbaxter** [comment]
I think the property you are looking for is `eureka.client.registryFetchIntervalSeconds`.

**Comment by jhelbling** [comment]
Thanks ryanjbaxter. Yep this one also make sense in our situation.
