### ISSUE TITLE
Does Feign Client uses Hystrix Request Cache?

### ISSUE THREAD

**Issue by mr-rajeshrathod** [spring-cloud/spring-cloud-netflix#2253]
Hi,
Hystrix default command configuration set requestCache to true and if command is implementing getCacheKey() method then we will able to cache hystrix command output.

For me hystrix integration with feign client is not caching Hystrix command response. Is that safe to conclude that feign does not use requestCache feature of Hystrix even though feign is set to use hystrix using property `feign.hystrix.enabled=true.`

If above statement is true then do we have any alternate to cache request with feign client?

**Comment by ryanjbaxter** [comment]
I have not tried this myself, but I poked around and I would try something similar to what is done here https://github.com/spring-cloud/spring-cloud-netflix/blob/a8d40afd587e060e013dcfae1c761e5b0a85f72a/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/feign/valid/FeignClientTests.java#L317

In the `HystrixCommand.Setter` class there is a method called `andCommandPropertiesDefaults` which takes a `com.netflix.hystrix.HystrixCommandProperties.Setter` instance as a parameter.  This class has a method called `withRequestCacheEnabled` which will let you enable request caching.  You might try that.

**Comment by mr-rajeshrathod** [comment]
Thanks ryanjbaxter. I will try with given option and let you know updates.

**Comment by tjuchniewicz** [comment]
@mr-rajeshrathod Any interesting results to share?

**Comment by sergey-karazhenets** [comment]
To enable caching you should:
* set property `com.netflix.hystrix.HystrixCommandProperties.Setter.withRequestCacheEnabled(true)`
* override method `getCacheKey()` for each `HystrixCommand`

**Comment by domingoxx** [comment]
Hey guys !!

About this issues have any solution?

I'm using `feign client` and `hystrix` with spring cloud, and I want apply distributed cache to hystrix. spring-cloud have any api to support this?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by ConnorLH** [comment]
feign-hystrix used `HystrixInvocationHandler` wrapped feign-client as HystrixCommand , could you consider add some feature to this HystrixCommand to use hystrix cache?
