### ISSUE TITLE
Zuul Routes not correctly refreshed under heavy traffic

### ISSUE THREAD

**Issue by jcarvalho** [spring-cloud/spring-cloud-netflix#2258]
In an application using a custom `RefreshableRouteLocator` implementation, publishing a `RoutesRefreshedEvent` during a period of heavy traffic can cause new Routes to not be correctly applied.

This is caused by a race-condition in [ZuulHandlerMapping](https://github.com/spring-cloud/spring-cloud-netflix/blob/v1.3.4.RELEASE/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/web/ZuulHandlerMapping.java#L70-L75), in which the mapping is recorded as `dirty` prior to refreshing the routes.

This means that if a new request comes in prior to the `RefreshableRouteLocator.refresh()` method finishing, the `dirty` flag is seen as `true` [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/v1.3.4.RELEASE/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/web/ZuulHandlerMapping.java#L90-L97), the old routes are retrieved from the `RouteLocator`, and the `dirty` flag is set back to `false`, meaning that the new routes will not be picked-up.

I am able to work around this by manually invoking my `RefreshableRouteLocator.refresh()` method prior to publishing the event, which will ensure that `ZuulHandlerMapping` will already see the new route configuration. This works, but is rather wasteful.

Within Spring Cloud Netflix, this can be fixed by only setting the `dirty` flag after refreshing the Route Locator.

Note: This behavior is only triggered when the `refresh()` method takes longer than the 'next' request to come in, hence this only happening in heavy traffic situations.

**Comment by ryanjbaxter** [comment]
@jcarvalho sine you have already done the analysis of the problem would you be willing to submit a PR with your proposed changes?

**Comment by jcarvalho** [comment]
@ryanjbaxter Yes, I'm just sorting things out regarding the Contribution Agreement. Or is it OK to open the PR first?

**Comment by ryanjbaxter** [comment]
Whatever works for you.  You can submit the PR and then accept the contribution agreement after you sort that out.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
