### ISSUE TITLE
Doubt on SidecarProperties.java

### ISSUE THREAD

**Issue by chenkunyun** [spring-cloud/spring-cloud-netflix#2260]
Hi, guys
I'm currently doing some stuffs using sidecar, and I found something really puzzling. In SidecarProperties.java, there's no comment on the following code:
```
private String hostname;
private String ipAddress;
```
Since the "hostname" and "ipAddress" and be guessed, why is this two field presented here?

Regards,
Chen

**Comment by eacdy** [comment]
When Sidecar uses IP1 and hostname1  and the polyglot app uses IP2 and hostname2.
In this case ,you Can use
```
sidecar.ip-address =IP2
sidecar.hostname=hostname2
```
to specify the IP/HOSTNAME for the polyglot app.

Maybe this doc helps: <http://cloud.spring.io/spring-cloud-static/Dalston.SR3/#_polyglot_support_with_sidecar> .

**Comment by chenkunyun** [comment]
Thanks for your reply, buddy. 
I've found another scenario where ```hostname``` and ```ipAddress``` can't be guessed: If your spring cloud service is deployed in docker, the hostname and ipAddress guessed is the address of the gateway of the docker container, not the host's address. In such scenario, you should explicitly specify the hostname and ipAddress in your .yml file
