### ISSUE TITLE
How to use Hystrix in Feign?

### ISSUE THREAD

**Issue by CHERRISHGRY** [spring-cloud/spring-cloud-netflix#2263]

**Comment by CHERRISHGRY** [comment]
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Sep 11 11:08:12 CST 2017
There was an unexpected error (type=Internal Server Error, status=500).
Connection refused: connect executing GET http://service-test/hello?name=Chrome

**Comment by eacdy** [comment]
If you're using Spring Cloud Daslston or above.
Maybe you missed configuration `feign.hystrix.enabled=true`.

**Comment by CHERRISHGRY** [comment]
The version is Dalston.SR3.But it does not contain configuration :feign.hystrix.enabled=true.

**Comment by ryanjbaxter** [comment]
Please provide more information about what the issue is and a sample project the reproduces the issue.

**Comment by indrabasak** [comment]
@CHERRISHGRY It does. Please check the class file `FeignClientsConfiguration` in an IDE of your choice.

**Comment by YrlixJoe** [comment]
I've had the same problem as you, but I've solved it now.
## First 
Add the configuration below to your application.properties
@eacdy 
> If you're using Spring Cloud Daslston or above.
Maybe you missed configuration `feign.hystrix.enabled=true`

## Second
just do first is not enough, you need also add Hystrix dependence to the pom.xml
```xml
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-hystrix</artifactId>
</dependency>
```


you can find this in the Spring Cloud Netflix official document at [http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#spring-cloud-feign-hystrix](http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#spring-cloud-feign-hystrix)


----------------------
I see your profile and i knew you are a Chinese, So i recommend this article for you, it is maybe helpful.

**Comment by SwinBlackSea** [comment]
I use <spring-cloud.version>Finchley.RELEASE</spring-cloud.version>;
the **### solution** is
**### first**
in application.yml
feign:
  hystrix:
    enabled: true

### **second**:
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
</dependency>

although the application.yml can not automatic discover feign.hystrix.enabled,but it doesn't matter.

**Comment by SwinBlackSea** [comment]
I use <spring-cloud.version>Finchley.RELEASE</spring-cloud.version>;
the ### solution is
### first
in application.yml
feign:
hystrix:
enabled: true

second:
`<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
        </dependency>`

although the application.yml can not automatic discover feign.hystrix.enabled,but it doesn't matter.

**Comment by SwinBlackSea** [comment]
I use <spring-cloud.version>Finchley.RELEASE</spring-cloud.version>;
the ### solution is

first
in application.yml
`feign:
hystrix:
enabled: true`

second:
<dependency> <groupId>org.springframework.cloud</groupId> <artifactId>spring-cloud-starter-hystrix</artifactId> </dependency>

although the application.yml can not automatic discover feign.hystrix.enabled,but it doesn't matter.

**Comment by SwinBlackSea** [comment]
@YrlixJoe you are right,but confused.If you're using Spring Cloud Daslston or above. you also can use `feign.hystrix.enabled=true`,although the application.yml can't automatic discovery it

**Comment by CoderTnT** [comment]
Add the configuration to application.properties。 it work
