### ISSUE TITLE
How to capture the host name of a request routed from Zuul?

### ISSUE THREAD

**Issue by indrabasak** [spring-cloud/spring-cloud-netflix#2271]
I am using `Dalston.SR3` for my Zuul server. The requests are routed using a `Ribbon Client` with `Hystrix`.  Noticed that a server is allocated in `LoadBalancerContext` class for a given request. Is there a way to capture this **host information**? I am trying to keep track of **in-flight requests per service ID and host**.

**Comment by ryanjbaxter** [comment]
What do you want to do with the hostname?

**Comment by indrabasak** [comment]
We have the following requirements:

- keep track of in-flight requests per service ID and per host in Zuul.
- publish this information as metrics

It will ensure that no in-flight transactions are lost while a host is being rebooted.

**Comment by ryanjbaxter** [comment]
You might want to look into using a `ZuulFilter` to capture the information you need.

**Comment by indrabasak** [comment]
I have looked at `ZuulFilter`. I have a `route` and a `post` filter to keep track of the number of _requests_ and _responses_ per service ID respectively. However, I have no way of retrieving the _host_ information since the HTTP client request takes places inside the `RibbonRoutingFilter`.

**Comment by ryanjbaxter** [comment]
Have you tried something like this? https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L232

**Comment by indrabasak** [comment]
@ryanjbaxter Thanks, I will take a look at it.
