### ISSUE TITLE
DS: Registry: expired lease

### ISSUE THREAD

**Issue by jkjunior** [spring-cloud/spring-cloud-netflix#2275]
Hi.

I have a non-jvm service that register in the Eureka Server through a json. But about a minute, it cancels the registration. How can I solve this?

Here is the logs:
`15/09/2017 10:12:492017-09-15 13:12:49.647  INFO 8 --- [nio-8761-exec-6] c.n.e.registry.AbstractInstanceRegistry  : Registered instance COMISSIONAMENTO-API/10.2.11.132:comissionamento-api:8104 with status UP (replication=true)
15/09/2017 10:13:322017-09-15 13:13:32.442  INFO 8 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
15/09/2017 10:14:322017-09-15 13:14:32.442  INFO 8 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms
15/09/2017 10:14:322017-09-15 13:14:32.442  INFO 8 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Evicting 1 items (expired=1, evictionLimit=1)
15/09/2017 10:14:322017-09-15 13:14:32.442  WARN 8 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: expired lease for COMISSIONAMENTO-API/10.2.11.132:comissionamento-api:8104
15/09/2017 10:14:322017-09-15 13:14:32.442  INFO 8 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Cancelled instance COMISSIONAMENTO-API/10.2.11.132:comissionamento-api:8104 (replication=false)`

And here is my JSON:
`data = {
      "instance": {
        "hostName":str(s.getsockname()[0]),
        "app":"comissionamento-api",
        "ipAddr":str(s.getsockname()[0]),
        "vipAddress":"comissionamento-api",
        "status":"UP",
        "port": {"$": "8104", "@enabled": "true"},
        "securePort": {"$": "443", "@enabled": "false"},
        "homePageUrl" : "http://"+ str(s.getsockname()[0]) + ":8104",
        "statusPageUrl": "http://"+str(s.getsockname()[0])+":8104/info",
        "healthCheckUrl": "http://"+str(s.getsockname()[0])+":8104/health",
        "dataCenterInfo": {
                "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                "name": "MyOwn"
         },
        "metadata": {
          "instanceId" : str(s.getsockname()[0])+":comissionamento-api:8104"
        }
      }
    }`

Thanks to advance.

**Comment by spencergibb** [comment]
Eureka requires a heartbeat. Are you using spring cloud?

**Comment by jkjunior** [comment]
No. I have a python app just sending a request with this JSON: 
`data = {
      "instance": {
        "hostName":str(s.getsockname()[0]),
        "app":"comissionamento-api",
        "ipAddr":str(s.getsockname()[0]),
        "vipAddress":"comissionamento-api",
        "status":"UP",
        "port": {"$": "8104", "@enabled": "true"},
        "securePort": {"$": "443", "@enabled": "false"},
        "homePageUrl" : "http://"+ str(s.getsockname()[0]) + ":8104/",
        "statusPageUrl": "http://"+str(s.getsockname()[0])+":8104/info/",
        "healthCheckUrl": "http://"+str(s.getsockname()[0])+":8104/health/",
        "dataCenterInfo": {
                "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
                "name": "MyOwn"
         },
        "metadata": {
          "instanceId" : str(s.getsockname()[0])+":comissionamento-api:8104"
        }
      }
    }`

How can I implement a heartbeat? Do i have to register every 30s?

**Comment by spencergibb** [comment]
You'll have to look at the eureka docs wiki in the eureka repo, or look at the spring cloud Netflix sidecar to manage the registration and heartbeat.
