### ISSUE TITLE
Circuit breaker not getting opened in Hystrix Ciruit Breaker

### ISSUE THREAD

**Issue by YaminiJose** [spring-cloud/spring-cloud-netflix#2276]
Hi, I am new to Hystrix. 

I have written a program to open the circuit by setting the properties as

	HystrixCommandProperties.Setter properties = HystrixCommandProperties.Setter().withCircuitBreakerEnabled(true)
				.withCircuitBreakerSleepWindowInMilliseconds(10000).withCircuitBreakerRequestVolumeThreshold(1)
				.withCircuitBreakerErrorThresholdPercentage(1).withMetricsRollingStatisticalWindowInMilliseconds(1000)
				.withMetricsRollingStatisticalWindowBuckets(1);
		HystrixCommandGroupKey groupKey = HystrixCommandGroupKey.Factory.asKey("Test");

I am running junit test and I have mocked the backendservice which throws exception. 

When I run the junit in debug mode(debug point after setting the properties via super()), it works else the ciruit will not get opened. Can you check what is the issue

**Comment by YaminiJose** [comment]
I got this working when I added hystrix.command.default.metrics.healthSnapshot.intervalInMilliseconds(10).
I think it is because the junit test runs within milliseconds so healthsnapshot needs to be taken within fraction of a second. Can anyone confirm if my understanding is correct

**Comment by kptfh** [comment]
Faced the same issue in tests. And this workaround helped me. Thanks.

**Comment by spencergibb** [comment]
Closing question as answered
