### ISSUE TITLE
Improper validation of certificate with Host MisMatch (CWE ID 297)

### ISSUE THREAD

**Issue by DineshLal** [spring-cloud/spring-cloud-netflix#2279]
I have my file name as OTP sender, in my file I have X509certificate since I returned null and it shows this error in vercode. My code is 
                @Override
                public java.security.cert.X509Certificate[] getAcceptedIssuers()
                {
                    return null;
                }

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you please describe how this relates to spring-cloud-netflix.
