### ISSUE TITLE
Zuul DebugFilter [Question]

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#228]
I read on Zuul wiki page about a DebugFilter:
https://github.com/Netflix/zuul/wiki/How-To-Use#debug-logging

Until now I failed to see in the console information similar to the one presented on the Zuul wiki,
I used the http param to enable debug: ?debug=true

Thanks

**Comment by dsyer** [comment]
We don't include that filter in Spring Cloud by default (I guess you can add it). We add request traces to the /trace endpoint, so look there instead.

**Comment by aivans** [comment]
Thanks Dave

**Comment by Aloren** [comment]
I'm using spring-cloud 1.1.0.RELEASE and DebugFilter is already included in ZuulConfiguration with order 1, but it seems to me that setting on `RequestContext` `debugRouting` at that point is already too late. I would like to see logs from com.netflix.zuul.FilterProcessor. It checks for the `debugRouting` and does not add debug info to Debug class. So as I understand DebugFilter does nothing right now. Am I correct?

**Comment by spencergibb** [comment]
@Aloren doesn't look like it will help for the FilterProcessor does it. Not sure how we could go about making it useful to `FilterProcessor`.

**Comment by Aloren** [comment]
@spencergibb this is what I'm talking about. Is there any sense right now in `DebugFilter`? As I see it does nothing.

**Comment by spencergibb** [comment]
yup, not much.
