### ISSUE TITLE
Is it possible to set a timeout policy in zuul filter

### ISSUE THREAD

**Issue by cenggel** [spring-cloud/spring-cloud-netflix#2282]
I want to set time out policy in zuul filter according to request data. Is it possible to dynamic change ribbon command timeout ?

**Comment by ryanjbaxter** [comment]
Are you using Dalston?  If so see my comment [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/1684#issuecomment-281377368) on how to provide your own HTTP Client.

In Edgware this will be much simpler http://cloud.spring.io/spring-cloud-static/Edgware.M1/#http-clients

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
