### ISSUE TITLE
Zuul redirects not being propagated to the browser

### ISSUE THREAD

**Issue by tomerc** [spring-cloud/spring-cloud-netflix#2287]
Hi everyone,

I have an application which uses spring-webflow in order to start a conversation between the client and the server. The client sends a POST message and spring webflow in return sends an HTTP 302 redirect with an execution query parameter which continuously queries the server. I see the request coming back from the server to Zuul with the proper 302 redirect. However, that 302 never makes it back the browser, and what effectively happens is that Zuul makes the redirect call back to the server with the query parameter and it goes into a loop with the browser hanging until the loop actually completes when the server returns a 200 status (I've tried forcibly to set the response for example to 200 during the POST and it is making it back the browser but the spring-webflow conversation never actually gets started).

Is there a way to force Zuul to propagate the 302 redirect back to the browser?

**Comment by ryanjbaxter** [comment]
I guess I dont understand why Zuul following the redirect is causing any issues?

**Comment by spencergibb** [comment]
The http client is likely the culprit, not zuul itself

**Comment by rsby** [comment]
We faced this issue after updating our Spring Cloud bom recently. We resolved the issue by adding the following to our configuration:

```
        @Bean
	public ApacheHttpClientFactory apacheHttpClientFactory() {
		return () -> HttpClientBuilder.create()
                .disableContentCompression()
                .disableCookieManagement()
                .useSystemProperties()
		.disableRedirectHandling();
	}
```

**Comment by spencergibb** [comment]
@rsby are you using ribbon (ie `serviceId` in zuul config)?

**Comment by rsby** [comment]
@spencergibb no, we are routing to URLs exclusively at this time, pending a future migration to Kubernetes, and we use the Zuul servlet set to the default path with `zuul.servlet-path:  /` and `server.servlet-path: /some-other-path`

**Comment by sundysd** [comment]
@rsby 
hi, i want to ask more about solution you mentioned, so you solve this issue by doing following steps? 

1, modify zuul config xml application.properties by adding two lines:
     zuul.servlet-path: /
     server.servlet-path: /some-other-path

2, you also modify post filter by adding this function? as you mentioned "adding the following to our configuration", so maybe you are not talking about filter but main class or some other class?
        @Bean
	public ApacheHttpClientFactory apacheHttpClientFactory() {
		return () -> HttpClientBuilder.create()
                .disableContentCompression()
                .disableCookieManagement()
                .useSystemProperties()
		.disableRedirectHandling();
	}

so for the original question of this thread, above two steps solution should also applies to fix it?

**Comment by spencergibb** [comment]
ping @tomerc

**Comment by tomerc** [comment]
@spencergibb This can be closed now, thanks!
