### ISSUE TITLE
How to return error response from FeignClient to caller

### ISSUE THREAD

**Issue by reenolesigues** [spring-cloud/spring-cloud-netflix#2289]
Hi Guys,

Relatively new in using spring-cloud-netflix :)

Just wanna ask how can I forward the error response from my feign client service to the calling service?

Below is a snapshot of the error if I perform a direct call to the feign client microservice:

![exception - direct call to microservice](https://user-images.githubusercontent.com/1477158/30684460-d1eb96e0-9ee3-11e7-9b38-3165c9e1aee5.jpg)

And below is a snapshot if I call the service as a feign client:

![exception - indirect call to microservice](https://user-images.githubusercontent.com/1477158/30684480-e6068e32-9ee3-11e7-909e-57cbe09ac7e6.jpg)

Is there a way that my calling service just return the error response(including http status and headers) from my feign client without catching it as a HystrixRuntimeException?

Appreciate any help. Again, sorry, just a newbie with spring cloud :)
Thanks!

**Comment by ryanjbaxter** [comment]
Sounds like this might be a limitation of Feign https://github.com/spring-cloud/spring-cloud-netflix/issues/1346

**Comment by reenolesigues** [comment]
Seems like i was able to 'rethrow' the same exception through the combination of errordecoder and controller advice.

errordecoder - return a custom exception (customEx) for all errors. Contains https status, headers, and body.
controller advice - reconstruct the actual error response from feign client by catching custom exception (customEx).

Thanks for your input!
Closing this issue now.
