### ISSUE TITLE
Unknown host exception

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#229]
I deployed feign-eureka example to cloud foundry and i am getting unknown host exception in client, are there any changes i need to make in the configuration for cloud, it is working fine in local, also in cloud i do see the registrations for both client and server in eureka.

**Comment by dsyer** [comment]
There's a section on "Using Eureka in Cloudfoundry" here: http://projects.spring.io/spring-cloud/spring-cloud.html#_eureka_metadata_for_instances_and_clients. Does that answer the question?

**Comment by ctatineni** [comment]
perferIPAddress: true fixed the issue, i am not sure why host name was not working.Thanks.

**Comment by dsyer** [comment]
I wouldn't recommend preferIpAddress in general for Cloudfoundry, unless your platform is set up to allow it it probably won't work. If it works for you though that's great.
