### ISSUE TITLE
No Support for Sentinels

### ISSUE THREAD

**Issue by vipinvkmenon** [spring-cloud/spring-cloud-netflix#2295]
When I deploy a Spring Application on CF. the java buildpack tries to reconfigure spring to work with its 'cloud' profile.

https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration

As a result, the application picks up this configuration/profile.Due to this, the application fails when a Redis Multinode/HA instance is used.

I feel this is something to do with the way the HA/ Multinode Redis Service is deployed/ provided.

Our fix for the timebeing was to disable autoconfiguration through the manifest file.

JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'  

Does Spring cloud not support  Sentinels. Or is this due to some other issue?

**Comment by spencergibb** [comment]
This has nothing to do with spring cloud Netflix
