### ISSUE TITLE
Retrieve Hystrix metrics directly from HystrixCommandMetrics

### ISSUE THREAD

**Issue by wjam** [spring-cloud/spring-cloud-netflix#23]
Rather than retrieving the Hystrix metrics from the `HystrixMetricsPoller`, the metrics should be retrieved directly from the `HystrixCommandMetrics`. By using the poller, it means that the data is having to go from `HystrixCommandMetrics` -> JSON -> parsing JSON in `HystrixMetricsPollerConfiguration` -> `GaugeService`.

**Comment by spencergibb** [comment]
Closing due to age and inactivity.
