### ISSUE TITLE
Allow init params to be set on ProxyStreamServlet

### ISSUE THREAD

**Issue by fahimfarookme** [spring-cloud/spring-cloud-netflix#2301]
I'm facing [this ](https://github.com/Netflix/Hystrix/issues/1543) issues in spring-cloud-netflix and trying to address the same. Since I cannot disable stuck-thread max-time for my managed-servers, I'm trying to assign a work-manager with stuck-thread max-time disabled to HystrixMetricsStreamServlet. This is the approach I though of.

-  Introduce a new auto-configuration (since I have over 20 microservices) which sets [hystrix.stream.endpoint.enabled to false](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCircuitBreakerConfiguration.java#L74). So that HystrixStreamEndpoint will not be constructed. 
- Then in my auto-configuration, create a `ServletWrappingEndpoint` bean wrapping the `HystrixMetricsStreamServlet`. 
- Now for this servlet I must pass the name of the work-manager as an init-param.

1. Do you see a better approach to solve this issue?
2. I would suggest the `ServletWrappingEndpoint` class to accept `ServletWrappingController` in it's constructor since  `ServletWrappingEndpoint` does not allow setting init params. (Calling the getController() getter would cause _invoking overridable methods from constructors_).

**Comment by spencergibb** [comment]
That class is going to go away in 2.0.0. I'd suggest you just copy it and make whatever changes you need. I doesn't do much.

**Comment by fahimfarookme** [comment]
Thanks @spencergibb. I found the same issue with `ProxyStreamServlet` as well and the workaround is not straight-forward since `ProxyStreamServlet` bean construction is not conditional on any property. The workaround is to sub-class `HystrixDashboardConfiguration` and introduce a new _Enable_ annotation. i.e.

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Import(HystrixWebLogicDashboardConfiguration.class)
public @interface EnableWebLogicHystrixDashboard {

}
```

```
@Configuration
public class HystrixWebLogicDashboardConfiguration extends HystrixDashboardConfiguration {
	
	@Autowired
	private HystrixDashboardProperties dashboardProperties;

	@Bean
	public ServletRegistrationBean proxyStreamServlet() {
		ProxyStreamServlet proxyStreamServlet = new ProxyStreamServlet();
		proxyStreamServlet.setEnableIgnoreConnectionCloseHeader(dashboardProperties.isEnableIgnoreConnectionCloseHeader());
		ServletRegistrationBean bean = new ServletRegistrationBean(proxyStreamServlet, "/proxy.stream");
		bean.addInitParameter("wl-dispatch-policy", "WorkManager-Hystrix");
		return bean;	
	}
}
```
<br/>

However, in order to avoid such workarounds for WebLogic users, it would be nicer to have the following configurations
1. The registration of `ProxyStreamServlet` to accept some init parameters - same as above.
```
hystrix.proxy-servlet.init.parameter.name=
hystrix.proxy-servlet.init.parameter.value=
```
May be an array of such params...

2. Register the `HystrixMetricsStreamServlet` through ServletRegistrationBean, rather than exposing it as an Endpoint. Also to accept some init parameters from properties.

**Comment by spencergibb** [comment]
`HystrixDashboardProperties` could be enhanced to have a map of init parameters. Hystrix has already been changed to accept init params in 2.0.x see 61513287ce078f7ef57ca480b8a75ae0ce27b2bb

**Comment by fahimfarookme** [comment]
That's great! Would like to file a pull request for HystrixDashboardProperties .

**Comment by spencergibb** [comment]
@fahimfarookme absolutely!

**Comment by fahimfarookme** [comment]
@spencergibb Hope the target branch should be 2.0.x?

**Comment by spencergibb** [comment]
Can be master if done promptly.

**Comment by fahimfarookme** [comment]
For WebLogic users, until spring-cloud-netflix 2.0.x is released - [here's the workaround](https://github.com/fahimfarookme/hystrix-stuck-thread-issue/tree/master/hystrix-stuck-thread-workaround) as a library which was discussed [above](https://github.com/spring-cloud/spring-cloud-netflix/issues/2301#issuecomment-333215602).
