### ISSUE TITLE
How to use LoadBalanced RestTemplate during bean creation time

### ISSUE THREAD

**Issue by kylewu** [spring-cloud/spring-cloud-netflix#2304]
I'm trying to use RestTemplate with LoadBalanced annotation (instead of Feign) in my project.

One bean (let me call it client bean) uses this RestTemplate and make some requests durning init (inside @Bean annotation). The problem of this is that LoadBalancerInterceptor has not been added to this RestTemplate. So the call to http://service-name fails because of unknown host.

So in the same configuration file as where this client bean is, I add autowired LoadBalancerInterceptor, and add this interceptor manually to RestTemplate. But then I get another error `EurekaClient has not been initialized yet, returning an empty list` from DiscoveryEnabledNIWSServerList.

How to use LoadBalanced RestTemplate during creating beans? Any idea?

spring-cloud version 1.1.7.RELEASE

**Comment by spencergibb** [comment]
I'm not sure it's possible. We use `SmartLifecycle` beans where we need that in spring cloud.

**Comment by kylewu** [comment]
@spencergibb do you mean `EurekaDiscoveryClientConfiguration`?

**Comment by spencergibb** [comment]
no, I don't. We don't use eureka client during bean creation.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
