### ISSUE TITLE
`preferIpAddress` doesn't work in docker container.

### ISSUE THREAD

**Issue by kimjuny** [spring-cloud/spring-cloud-netflix#2305]
Hi, does `preferIpAddress` work in docker container?

## An example configuration

I've tried to set `preferIpAddress` and `ipAddress` for all my eureka clients and server.

```
eureka:
  instance:
    preferIpAddress: true
    ipAddress: 172.16.12.155
  client:
    serviceUrl:
      defaultZone: http://pitbull:j1n3v9z9j3nc@${server.remote}:8888/eureka/
```

## What happens

In eureka dashboard, it is container id(not `ipAddress`) is marked as my instance id. And when I'm clicking it, it jumps to `ipAddress/info` page.  I can see `hostName`、`homePageUrl`、`statusPageUrl`、`healthCheckUrl` all pointed to `ipAddress` in `/eureka/apps`. And it is always `status=UP` even I killed my client instances.

👇in my eureka server dashboard

![screenshot01](https://i.imgur.com/4bl7XbO.jpg)

👇in my `/eureka/apps`

```
<application>
<name>STOCK-SERVICE</name>
<instance>
<instanceId>5d43d4d2b08d:stock-service:8889</instanceId>
<hostName>172.16.12.155</hostName>
<app>STOCK-SERVICE</app>
<ipAddr>172.16.12.155</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8889</port>
<securePort enabled="false">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1506528094209</registrationTimestamp>
<lastRenewalTimestamp>1506528094209</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1506521817351</serviceUpTimestamp>
</leaseInfo>
<metadata class="java.util.Collections$EmptyMap"/>
<homePageUrl>http://172.16.12.155:8889/</homePageUrl>
<statusPageUrl>http://172.16.12.155:8889/info</statusPageUrl>
<healthCheckUrl>http://172.16.12.155:8889/health</healthCheckUrl>
<vipAddress>stock-service</vipAddress>
<secureVipAddress>stock-service</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1506528094209</lastUpdatedTimestamp>
<lastDirtyTimestamp>1506528094110</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
```

👇in my `spring-boot-admin` dashboard

![screenshot02](https://i.imgur.com/9vptxmR.jpg)

By the way I'm using Dalston.SR3(1.5.6.RELEASE)

**Comment by spencergibb** [comment]
`preferIpAddress` doesn't have anything to do with docker. `/eureka/apps` is correct. What you are seeing on the dashboards is `instanceId`

**Comment by kimjuny** [comment]
@spencergibb How can I change `instanceId` from something like `2c030675a9b9:api:8890` to `172.16.12.155:api:8890`? I've also tried to set hostname to ip address it doesn't work either.

**Comment by spencergibb** [comment]
set `eureka.instance.instanceId=whatever you want`
