### ISSUE TITLE
Return Observable from a Spring MVC Controller

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#231]
See https://github.com/spencergibb/myfeed/commit/a301aba6139fce7a87a1aab1d1311e6ceb8adfb7 for an example implementation.

In short: create a `ObservableReturnValueHandler` that returns a `DeferredResult` that delegates to the `Observable`.

**Comment by dsyer** [comment]
Can we do the same thing for a Stream (reactor)?
