### ISSUE TITLE
RibbonAutoConfigurationIntegrationTests.serverListIsConfigured() fails

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#2313]
timeout isn't set right.

**Comment by ryanjbaxter** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-commons/commit/1829d370bad904ef59185d938367641e6c8c4513

**Comment by spencergibb** [comment]
This test still fails for me locally

**Comment by spencergibb** [comment]
It runs fine individually from the IDE.

**Comment by spencergibb** [comment]
Maybe it only happens for me? Circle and jenkins seem to behave.

**Comment by ryanjbaxter** [comment]
Yeah that is weird.  My maven build is working fine.  Did you try pulling down the commons jar?
