### ISSUE TITLE
TurbineStreamTests fails()

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#2315]
spring-cloud-stream Elmhurst.SNAPSHOT references old boot classes.

/cc @viniciusccarvalho or @garyrussell

**Comment by viniciusccarvalho** [comment]
@spencergibb Yes, we have not had the time to update to latest boot (that is breaking metrics and actuator endpoints)

**Comment by spencergibb** [comment]
No longer an issue
