### ISSUE TITLE
It is a bad idea for Hystrix dashborad use same port with application

### ISSUE THREAD

**Issue by wyzssw** [spring-cloud/spring-cloud-netflix#2322]
The hystrix Dashboard url /hystrix and /hystrix/path
with support by org.springframework.cloud.netflix.hystrix.dashboard.HystrixDashboardController

apply the same port with application embed server，it can expose security information to the internet，please fix it！

**Comment by wyzssw** [comment]
```java       
      @Bean
	public HystrixDashboardController **hsytrixDashboardController**() {
		return new HystrixDashboardController();
	}
```

**Comment by ryanjbaxter** [comment]
I am not sure what the problem is, but we recommend you have a dedicated app that serves as the Hystrix Dashboard.
