### ISSUE TITLE
Multiple Eureka Zones on the same machine

### ISSUE THREAD

**Issue by Milesy** [spring-cloud/spring-cloud-netflix#2328]
I have set up a scenario where I am running two single node cloud environments under the one server (SIT1 & SIT2).

Both of the Eureka nodes are running on different ports, and each defaultZone is unique and refers only to the one instance within that cloud.

eureka.defaultZone=https://dev.foo.com:8761/eureka/

and

eureka.defaultZone=https://dev.foo.com:8762/eureka/

The problem I have is that when I bring up a service I have written pointing to the first zone, the service is somehow detecting the registering itself on the second Eureka as well even though it has not been explicitly made aware of it. 

I am using Brixton.SR7

Is this a limitation of the software that you are aware of regarding running on the same host?

**Comment by ryanjbaxter** [comment]
First I suggest you upgrade the version of Spring Cloud you are using.  The latest versions are `Camden.SR7` and Dalston.SR4`.  

If you have configured the Eureka servers to be peers of each other they will replicate service instance data between each other.

**Comment by spencergibb** [comment]
Eureka does have a limitation with peers with the same hostname. You will need entries in your hosts file.

**Comment by christianf2029** [comment]
I solved this a while ago in the way @spencergibb mentioned it, had seen somewhere.

**Comment by Milesy** [comment]
Thanks @spencergibb - Our host names are managed on a corporate DNS server, and both of our DNS names resolve to the same host. 

By hosts file do you mean as in /etc/hosts ? Is there any documentation on how this changes the behavior in some way?

@christianf2029 - are you able to share the problem with me please?

**Comment by christianf2029** [comment]
Yes, adding new hostnames in `/etc/hosts/`. I also wanted to run more than one Eureka Server on the same machine, but it gave errors when using the same hostname, which is plausible. Add other hostnames pointing to some address and make one instance of Eureka Server point to the other, it will work fine.

**Comment by christianf2029** [comment]
Yes @Milesy, adding new hostnames in / etc / hosts /. I also wanted to run more than one Eureka Server on the same machine, but it gave errors when using the same hostname, which is plausible. Add other hostnames pointing to some address and make one instance of Eureka Server point to the other, it will work fine.
