### ISSUE TITLE
eureka server not removing instance when instance down 

### ISSUE THREAD

**Issue by lihaoHuawei** [spring-cloud/spring-cloud-netflix#2329]
instance and eureka server are in same docker VM。

I have a VM ,installed docker:IP1

I run a container for Eureka Server port :38000

A container for instance1 38001,another container for instance2  38002

both instances registerd to Eureka Server.They have same IP,but different port

when I down one instance ,Eureka Server frontpage shows，no instance down, 

after long time ,still shows both two instance is good

**Comment by ryanjbaxter** [comment]
Is there a warning about "self preservation" on the Eureka dashboard?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
