### ISSUE TITLE
Support Ribbon in AsyncRestTemplate

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#233]
see [MyfeedAutoConfig.java#L68-L83](https://github.com/spencergibb/myfeed/blob/master/myfeed-core/src/main/java/myfeed/MyfeedAutoConfig.java#L68-L83) and [RibbonAsyncClientHttpRequestFactory](https://github.com/spencergibb/myfeed/blob/master/myfeed-core/src/main/java/myfeed/RibbonAsyncClientHttpRequestFactory.java)

Not as straight forward as the standard synchronous `RestTemplate` because there is no concept of interceptors and URI resolution happens in various implementations of `AsyncClientHttpRequestFactory`

**Comment by olasundell** [comment]
I'd be very happy if this was implemented properly, so we wouldn't have to recreate it on our own.

**Comment by spencergibb** [comment]
closing in favor of https://github.com/spring-cloud/spring-cloud-commons/issues/36
