### ISSUE TITLE
FallbackProvider.java not found in Spring Cloud Dalston SR3

### ISSUE THREAD

**Issue by christianf2029** [spring-cloud/spring-cloud-netflix#2331]
I have created a generic handling for crashes that may occur on my Zuul Server with `ZuulFallbackProvider`, however I wanted to create custom responses according to the error that occurred. According to the [documentation](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc), there is the FallbackProvider interface which gives me which exception was thrown so I can do the right treatment. however it is not present in the Spring Cloud Dalston SR3 version. What do I do?

**Comment by spencergibb** [comment]
It is here https://github.com/spring-cloud/spring-cloud-netflix/blob/1.3.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/ZuulFallbackProvider.java

Maybe you have a corrupt library?

**Comment by christianf2029** [comment]
No, it's not the ZuulFallbackProvider, it's the FallbackProvider - by [this](https://github.com/spring-cloud/spring-cloud-netflix/commit/4c53fd2bf67626bae6822a2d2acc07e48dbe028c) commit merged. I want just what this class receives, the cause of failure.

**Comment by spencergibb** [comment]
That's not in Dalston. It's in Edgware that had only had a milestone

**Comment by christianf2029** [comment]
There have been some errors here in the version change, is there incompatibility if the services are in the Dalston SR3?

**Comment by spencergibb** [comment]
There is no incompatibility that I'm aware of.

What do you mean by 
> There have been some errors here in the version change

**Comment by christianf2029** [comment]
Sorry, it was setup errors here. When will you publish an GA with this feature? Are there any deadlines? Does Finchley also have this feature? I ask this because I need to put this into production.

**Comment by ryanjbaxter** [comment]
It wasn't merged into master before we released Edgware.M1.  It will be included in the Edgware.RELEASE, once that happens.

**Comment by christianf2029** [comment]
Is there a forecast for this?

**Comment by ryanjbaxter** [comment]
Yes it will be in Finchley as well.

You can find tentative release dates here, of course they are all subject to change https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by christianf2029** [comment]
Ok, thanks.
