### ISSUE TITLE
Request Collapsing in Zuul

### ISSUE THREAD

**Issue by marcelalburg** [spring-cloud/spring-cloud-netflix#2333]
Hello,

i've a question. We use zuul and route to our microservices. Inside the services there is request collapsing implemented and it works well. But in the last time, we see, that request collapsing in the microservice makes not much sence, if it comes to scaling.

An example:

Zuul Proxy (route /catalog/) -> 2 catalog instances -> database (elasticsearch)

if we request /catalog/article/product1 for 100 times in n milliseconds, the 2 instances handle 50 requests each and query the elasticsearch 2 times. 

but if we scale the catalog instances, we increase the connections to the elasticseach for the same query.

My question is, if it possible to implement request collapsing inside the proxy and is this a good approach ?

Thanks a lot
Marcel

**Comment by spencergibb** [comment]
Can you explain how request collapsing would work in this case? Hystrix has requests collapsing (IIRC), but we have no explicit support for it.

**Comment by marcelalburg** [comment]
My idea is that (if it possible) to create a filter with request collapsing inside the proxy (of course, there should be a more advanced kind of configuration).

For that configured routes p.e. /catalog/articles/{key} we could enable request Collapsing. And key is the RequestCollapsing key. 

From my point of view the proxyserver handle the requests (from my example above) - all 100 requests and just call the catalog microservice one time.

This allow us to scale up the catalog microservices and the request collapsing makes more sence.

Marcel

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
