### ISSUE TITLE
Health Status of Eureka and Zuul Services

### ISSUE THREAD

**Issue by hellouserchn** [spring-cloud/spring-cloud-netflix#2339]
We have Spring Cloud Netflix Eureka , Zuul and Config Server in our environment.

When we access the /health endpoint on them, we see the below information which includes "**discoveryComposite**",  "**discoveryClient**" and also "**configServer**"

```
discoveryComposite: {
    description: "Spring Cloud Eureka Discovery Client",
    status: "UP",
discoveryClient: {
   description: "Spring Cloud Eureka Discovery Client",
   status: "UP",
  services: [
       "config-server",
      "eureka-service",
      "zuul-service"
]
},
eureka: {
description: "Remote status from Eureka server",
   status: "UP",
applications: {
     ZUUL-SERVICE: 1,
     CONFIG-SERVER: 1,
     EUREKA-SERVICE: 1
}
}
},
```

What does the discoveryComposite and discoveryClient statuses mean?

Is there any documentation on them.

Also, we see the status information on **Config Server** too. We see this in all the 3 services, eureka , zuul and config when we access their /health endpoint.

We also , want to know why the config server status is being shown in the **/health** status of all the 3 services.

**Comment by hellouserchn** [comment]
We are using Spring Cloud Netflix Dalston.SR2 and Spring Boot 1.5.4 in our env.

**Comment by christianf2029** [comment]
At least speaking of the configuration server (if I'm not mistaken), it's known to everyone, in fact it needs to be, because it shares properties and settings to all services.

**Comment by ryanjbaxter** [comment]
The discoveryComposite is an aggregate of the health of all the discovery clients.

The discoveryClient is the health of your discovery client (you only have one in this case).

The config client also has a health indicator for the config server https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerHealthIndicator.java

**Comment by spencergibb** [comment]
Closing as answered
