### ISSUE TITLE
When request containing query param with the same name as a form param, the form param is ignored

### ISSUE THREAD

**Issue by benoit-lateltin** [spring-cloud/spring-cloud-netflix#2345]
Hello,

I have reproduce the issue by adding a test in `FormZuulProxyApplicationTests` :

```java
@Test
public void postWithMultipartFileAndFormAndQueryParam() {
	MultiValueMap<String, Object> form = new LinkedMultiValueMap<>();

	HttpHeaders part = new HttpHeaders();
	part.setContentType(MediaType.TEXT_PLAIN);
	part.setContentDispositionFormData("file", "foo.txt");
	form.set("foo", new HttpEntity<>("bar".getBytes(), part));

	form.set("field", "data");

	HttpHeaders headers = new HttpHeaders();
	headers.setContentType(MediaType.MULTIPART_FORM_DATA);

	ResponseEntity result = sendPost("/simple/fileandform?field=extra", form, headers);

	assertEquals(HttpStatus.OK, result.getStatusCode());
	assertEquals("Posted! bar!field!data", result.getBody());
}
```

Here I have two request params with the same name `field` :
- A query param in the URL
- A form param in the multipart

This test is failing as the form param is ignored and overriden by the query param.

I would expect this result 
`assertEquals("Posted! bar!field!data,extra", result.getBody());`
or this one
`assertEquals("Posted! bar!field!extra", result.getBody());`
thinking that a form param would have priority in a multipart POST over a query param.

I have facing this issue because I am using Jersey and the `@FormDataParam` annotation is not working like the Spring `@RequestParam`

```java
    @POST
    @Path("/simple/fileandform")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
    public Response uploadImport(
            @FormDataParam("file") FormDataContentDisposition fileContentDisposition,
            @FormDataParam("file") InputStream fileInputStream,
            @FormDataParam("field") String field,
            @Context UriInfo uriInfo) {

        return ResponseHelper.ok(String.format("field:%s", field));
    }
```

**Comment by benoit-lateltin** [comment]
I think this behavior has been introduced by https://github.com/spring-cloud/spring-cloud-netflix/issues/1080

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
