### ISSUE TITLE
How to distinguish connect-timeout and socket-timeout in ZuulFallbackProvider?

### ISSUE THREAD

**Issue by cyu021** [spring-cloud/spring-cloud-netflix#2347]
Hi all,

I am using ZuulFallbackProvider to handle fallback and would like to know how to distinguish one root cause from another, such as connect-timeout and socket-timeout. However, I am unable to find a lead by only examing the RequestContext in getBody(). Any advice is appreciated.

**Comment by spencergibb** [comment]
Closing in favor of https://stackoverflow.com/questions/46594379/how-to-distinguish-connect-timeout-and-socket-timeout-in-zuulfallbackprovider
