### ISSUE TITLE
Zuul lost spring mvc legacy app logged in user session data after successful login redirect

### ISSUE THREAD

**Issue by fr33land** [spring-cloud/spring-cloud-netflix#2350]
I have a legacy system with spring security login. My zuul server is running on a local machine and my legacy spring MVC system with spring security runs on local machine but 8084 port (ex. http://localhost:8084/legacySystem). When I enter a local proxy server URL with some path (ex. http://localhost:8080/legacySystem) zuul transparently proxyfies me to legacy server. That's ok. But when I try to login, legacy app authenticates me and stores SecurityContext (populated with logged user data) to HttpSession object. However before redirecting me to successful secured profile landing page (index or home) I got an 403 error and exception in log: _Access is denied (user is anonymous); redirecting to authentication entry point._ I analyzed logs and. It looks like legacy app somehow after a successful login redirect, lost or clears SPRING_SECURITY_CONTEXT session data and then tries to authenticate user with AnonymousAuthenticationToken data.  I've tried setting cookies header and etc but with no luck. If i try to login directly not trough zuul proxy everything works fine. Can someone explain me if this is a zuul problem, my legacy app issues or tomcat mis-configuration? Maybe I have to use spring-session with redis DB to share session data across services? I am attaching log debug file generated during login process. 

[login.log](https://github.com/spring-cloud/spring-cloud-netflix/files/1368127/login.log)

**Comment by spencergibb** [comment]
Have you looked at http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#_cookies_and_sensitive_headers? Zuul doesn't send cookie headers by default.

**Comment by fr33land** [comment]
Big Thanks for you. Worked like a charm. I read that part of documentation but had no idea that such simple trick could do the job. I added empty sensitiveHeaders directive.
