### ISSUE TITLE
Pass pre-compressed content via Zuul

### ISSUE THREAD

**Issue by hellouserchn** [spring-cloud/spring-cloud-netflix#2356]
We are using a non-jvm based service (nodejs) and routing the request via spring cloud zuul and sidecar.

We are using a middleware component in non-jvm service which compresses the content in gzip type.

But, when routed via Zuul we are only getting uncompressed content.

Not sure why Zuul uncompresses and passes the content?

If I add `server.compression.enabled=true` in zuul service we see the content being compressed and received in the client.

But,I am not sure ,
 if Zuul is uncompressing the already compressed content received from downstream service , then compressing it using its own algorithm and then sending the response.
(OR) If Zuul is checking for  pre-compressed content and just passing it through it in the response accordingly.

We want to avoid double compression scenario which might impact performance.

Can you please confirm the behavior of Zuul in this scenario.

We are using spring cloud Dalston.SR2 and spring boot 1.5.4.

**Comment by hellouserchn** [comment]
We are also using jetty as the embedded server.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
