### ISSUE TITLE
Zuul does not distinct services switch it's name in eureka

### ISSUE THREAD

**Issue by Meherzi** [spring-cloud/spring-cloud-netflix#2357]
We want to maintain two version of same service simultanely in the same stack.
So we think about making the distinction by adding the major version in eureka.instance.appname for the V2 
`eureka.instance.hostname = ${spring.application.name}v${project.artifact.selectedVersion.majorVersion}
eureka.instance.appname = ${spring.application.name}v${project.artifact.selectedVersion.majorVersion}
eureka.instance.preferIpAddress = false`

The services are seperated in eureka dashboard:
![eureka](https://user-images.githubusercontent.com/30697588/31452273-5a4382ec-aea6-11e7-920e-35a915203bcc.png)

This is the routes in gateway application.properties
`zuul.routes.iban.path = /iban/v1/**
zuul.routes.iban.serviceId = iban
gateway.authorized-endpoints.iban = /document, /process

zuul.routes.iban2.path = /iban/v2/**
zuul.routes.iban2.serviceId = iban-v2
gateway.authorized-endpoints.iban2 = /extract`

but my calling api/iban/v1/document , it failed sometimes because it routes the request to iban-v2.
This is the gateway log that shows that it does not make distinction between iban and iban-v2
![gatewaylog](https://user-images.githubusercontent.com/30697588/31452514-0c79fcac-aea7-11e7-9a5e-0b77f6208324.png)

**Comment by spencergibb** [comment]
it shouldn't do that. Can you create a sample project that recreates the problem?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
