### ISSUE TITLE
Make spring-boot-starter-web optional

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#2359]

**Comment by mbenson** [comment]
Does this change apply only to the 2.x line? If so, could someone explain why? Thanks!

**Comment by ryanjbaxter** [comment]
I believe this was fixed via https://github.com/spring-cloud/spring-cloud-netflix/commit/fc9d4425990484c5c40152b643dba0a0b14cef19

**Comment by ryanjbaxter** [comment]
@mbenson I think this was only make in the 2.x branch because we now have WebFlux as well.
