### ISSUE TITLE
Feign Request Compression doesn't work with ApacheClient with Hystrix and Ribbon Disabled

### ISSUE THREAD

**Issue by vinodhkanna** [spring-cloud/spring-cloud-netflix#2360]
I am unable to get the Feign request compression enabled with Apache client and feign request compression properties. I am able to get the compression working alternatively without ApacheClient by adding the request header in the RequestInterceptor with Content-Encoding as "gzip". The same however doesn't work with ApacheClient.

I am using Spring cloud Release - Dalston SR4 with spring-cloud-netflix-core-1.3.4

Sample Test case shown below.
```
@RunWith(SpringRunner.class)
@SpringBootTest(classes=FeignCompressionUnitTest.Application.class,  value={
    "feign.compression.request.enabled=true",
    "feign.compression.response.enabled=false",
    "feign.hystrix.enabled=false",
    "ribbon.eureka.enabled=false",
    "opencpu.url=http://localhost:4444/ocpu/library/lib1/R/",
    "feign.compression.request.min-request-size=100"
})
public class FeignCompressionUnitTest {

    @Autowired
    private OpenCPUClient openCPUClient;

    @Test
    public void testFeign(){
        openCPUClient.calculateReward(input());
    }

    @Configuration
    @SpringBootApplication(scanBasePackages = "mw.analytics", exclude = {
        LiquibaseAutoConfiguration.class
    })
    @EnableFeignClients(clients = OpenCPUClient.class)
    public static class Application {
    }
}
```

**Comment by vinodhkanna** [comment]
When i add the feign-httpclient dependency, the ApacheHttpClient automatically adds the Accept-Encoding: gzip, default even when feign.compression.response.enabled is set to false.

**Comment by vinodhkanna** [comment]
As a workaround, I was able to disable response compression by creating following beans and request compression by extending ApacheHttpClient and enabling the compression.
`
  @Bean
    public HttpClient httpClient(){
       return HttpClientBuilder.create()
           .setMaxConnPerRoute(10)
           .setMaxConnTotal(20)
           .disableContentCompression()
           .build();
    }

    @Bean
    public ApacheHttpClient apacheHttpClient(HttpClient client) {
        return new ApacheHttpClient(client);
    }
`

**Comment by spencergibb** [comment]
Closing as answered
