### ISSUE TITLE
[zuul.Hystrix] How to change zuul hystrix commandkey/group/threadpool?

### ISSUE THREAD

**Issue by Ryan-Git** [spring-cloud/spring-cloud-netflix#2361]
Hi, 
We'd like to employ a different hystrix command key(which is a client id from request parameter) and command group(we'd like to use serviceId) strategy rather than the default one. 

To accomplish this, we've extended a whole bunch of RibbonRoutingFiter/Context/Command/CommandFactory. Is there any convenient way?

Thanks in advance.

**Comment by ryanjbaxter** [comment]
Closing due to age and inactivity.
