### ISSUE TITLE
Clear documentation of @LoadBalanced RestTemplate with Ribbon

### ISSUE THREAD

**Issue by odedia** [spring-cloud/spring-cloud-netflix#2364]
Following this [issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/1873), I think a clearer documentation is warranted when using @LoadBalanced RestTemplate with Ribbon.

After reviewing the RestTemplate source code, it appears that any @LoadBalanced RestTemplate will use RibbonClient internally, however I could not see which properties are taken into consideration and which aren't.

For example, we already see from the issue above that ConnectTimeout and ReadTimeout values need to be set manually.

What about other Ribbon properties? For example, can I select a different load balancing rule, such as Weighted vs default Round Robin? IS the default a Round Robin load balancing? I can't find this in the documentation.

Will a @LoadBalanced RestTemplate honor Ribbon retry properties (MaxAutoRetries, MaxAutoRetriesNextServer), or should I define something else to achieve this functionality?

What other differences should I take into account when using a @LoadBalanced RestTemplate compared to Zuul proxy or Feign client?

Thank you for your help.

**Comment by odedia** [comment]
Apologies, I have now noticed that implementing retry is described adequetly in the docs. 

However, ribbon load balancing rule selection is still missing (if at all possible). 

Thanks.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
