### ISSUE TITLE
Webservice failure When execution strategy is thread and not semaphore

### ISSUE THREAD

**Issue by YaminiJose** [spring-cloud/spring-cloud-netflix#2368]
Hi,

I am trying to find out the root cause of an issue. From the hystrix run method, I am calling a SOAP webservice via spring webservice template. This fails with an error 'SOAPFAULTCLientException: Technical error with service" when the execution strategy is Thread. When I made it Semaphore, it worked.  Has anyone faced this issue before?

Thanks,
Yamini

**Comment by spencergibb** [comment]
You likely have some data in a threadlocal that is not available when using the thread strategy.

**Comment by YaminiJose** [comment]
Thanks Spencer for the quick reply ! . From the first look, I could not see any but I will have a look at it again.

**Comment by YaminiJose** [comment]
I could find out some thread local values being used. Thanks for the support!
