### ISSUE TITLE
Upgrade from [Camden.SR7] to [Dalston.SR3]:HystrixDashboard hystrix.stream shows ping message only and no data

### ISSUE THREAD

**Issue by MadeInChina** [spring-cloud/spring-cloud-netflix#2369]
HystrixDashboard shows that Unable to connect to Command Metric Stream.

Project structure
```
  -monitoring
    -pom.xml
  -application-service
    -pom.xml

```
Core codes:
```
application-service
@SpringBootApplication
@EnableResourceServer
@EnableDiscoveryClient
@EnableOAuth2Client
@EnableFeignClients
@EnableGlobalMethodSecurity(prePostEnabled = true)
@EnableConfigurationProperties
@Configuration
public class AccountApplication extends ResourceServerConfigurerAdapter {
}
With pom
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.7.RELEASE</version>
    </parent>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Dalston.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
```
monitoring
@SpringBootApplication
@EnableTurbineStream
@EnableHystrixDashboard
public class MonitoringApplication {

	public static void main(String[] args) {
		SpringApplication.run(MonitoringApplication.class, args);
	}
}

With pom
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.7.RELEASE</version>
    </parent>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Dalston.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

Resolved by replace application-service pom only
  Dalston.SR3 to Camden.RELEASE 
And also working with Camden.SR7
 ```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Camden.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by MadeInChina** [comment]
Does the issue related "rabbitMQ queue renamed from springCloudHystrixStream to turbineStreamInput"? 
[https://stackoverflow.com/questions/42379802/spring-cloud-turbine-no-data-returned-from-turbine-stream](url)

**Comment by MadeInChina** [comment]
Tested with Dalston.SR3
Add @EnableCircuitBreaker to the ServiceApplication and add @HystrixCommand to the service method will fixed that issue.
```
@SpringBootApplication
@EnableResourceServer
@EnableDiscoveryClient
@EnableOAuth2Client
@EnableFeignClients
@EnableCircuitBreaker
@EnableGlobalMethodSecurity(prePostEnabled = true)
@EnableConfigurationProperties
@Configuration
public class ServiceApplication extends ResourceServerConfigurerAdapter {
}
```
Question is that why it's working with version Camden.RELEASE even with out annotations EnableCircuitBreaker and HystrixCommand?But after upgrade the version to the Dalston we need that?

**Comment by eacdy** [comment]
Maybe you've missed the configuration `feign.hystrix.enabled = true` .

**Comment by MadeInChina** [comment]
@eacdy Thanks for that. it's solved my problem.
The problem is that the docs not updated also which confusing me.....
[http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.3.5.RELEASE/single/spring-cloud-netflix.html#netflix-hystrix-starter](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.3.5.RELEASE/single/spring-cloud-netflix.html#netflix-hystrix-starter)
 ```
Which means it's should be enable:true as default.
If you need to use ThreadLocal bound variables in your RequestInterceptor`s you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.

application.yml

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

```
