### ISSUE TITLE
How to distinguish ZuulFallback and circuit fallback?

### ISSUE THREAD

**Issue by seanlei** [spring-cloud/spring-cloud-netflix#2370]
Hi
I was able to configure fallbacks for Microservices at Zuul level so that they are invoked whenever a service is down or circuitBreaker trips.
Here is my fallback provider code.
```java
@Component
public class FallBackProvider implements ZuulFallbackProvider {
    private ObjectMapper objectMapper = new ObjectMapper();
    @Override
    public String getRoute() {
        return "*";
    }
    @Override
    public ClientHttpResponse fallbackResponse() {
        return new ClientHttpResponse() {
            @Override
            public HttpStatus getStatusCode() throws IOException {
                return HttpStatus.SERVICE_UNAVAILABLE;
            }
            @Override
            public int getRawStatusCode() throws IOException {
                return HttpStatus.SERVICE_UNAVAIABLE.value();
            }
            @Override
            public String getStatusText() throws IOException {
                return "OVERLOAD";
            }
            @Override
            public void close() {
            }
            @Override
            public InputStream getBody() throws IOException {
                OmsResponse res = new OmsResponse();
                res.setRetCode(ErrorCode.MICRO_SERVICE_OVERLOAD);
                res.setTimestamp(System.currentTimeMillis());
               //TODO return different result when sub service error and circuitBreaker trips
                res.setErrMsg("fallback");
                String jsonStr = objectMapper.writeValueAsString(res);
                return new ByteArrayInputStream(jsonStr.getBytes(StandardCharsets.UTF_8));
            }
            @Override
            public HttpHeaders getHeaders() {
                HttpHeaders headers = new HttpHeaders();
                headers.setContentType(MediaType.APPLICATION_JSON);
                return headers;
            }
        };
    }
}
```
When request route to sub service socket timeout error, the fallbackProvider was called,I'd like to return timeout error message to caller client.
After many request to the same service,the circuitBreaker may trips,the fallbackProvider was called again,I'd like to return fallback error message to caller client instead,but i can't distinguish two type of errors.
Is there other way to solve this problem? Thanks!

**Comment by holy12345** [comment]
I think if you implement zuulFallbackProvider interface, then it will not take Hystrix fallback, if you do not achieve zuulFallbackProvider, then will be directly called Hystrix fallback method.
Corresponding source content

	@Override
	protected ClientHttpResponse getFallback() {
		if(zuulFallbackProvider != null) {
			return zuulFallbackProvider.fallbackResponse();
		}
		return super.getFallback();
	}
This is my idea, hoping to help you. Thank you! ：）

**Comment by ryanjbaxter** [comment]
If you are using `Edgware.RC1` you should implement the `FallbackProvider` interface instead which will give you the ability to provide a response based on the failure. https://github.com/spring-cloud/spring-cloud-netflix/pull/2255/files

**Comment by seanlei** [comment]
Thanks for your reply! @ryanjbaxter 
htt[ps://github.com/spring-cloud/spring-cloud-netflix/pull/2255/files](https://github.com/spring-cloud/spring-cloud-netflix/pull/2255/files) It seems to work for my demand.
I'm using Dalston.SR4 version now and I'll consider about Edgware.RC1 later.
I prefer to use more stable version in production env.

**Comment by ryanjbaxter** [comment]
Understand, we are working towards a stable Edgware release.
