### ISSUE TITLE
`SpringClusterMonitor` does not handle `management.context-path` value for generating turbine  instance url

### ISSUE THREAD

**Issue by awesomelg** [spring-cloud/spring-cloud-netflix#2371]
Hi, @spencergibb We used spring-cloud-netflix-turbine(1.3.5.RELEASE) to configure Turbine (HTTP) aggregating our microservices hystrix streams in our spring cloud apps. The issue we found is:  By default, the correct hystrix HTTP endpoint is `<instance.ip>:${management.port}/${management.context-path}/hystrix.stream`, but the Turbine app did not retrieve hystrix streams using that endpoint but `:${management.port}/hystrix.stream`, then it got a 404 message. After some debugging efforts, I found `SpringClusterMonitor` uses self-implemented `InstanceUrlClosure`, and it never check management context path even `EurekaInstanceDiscovery` already puts eureka instances' metadata (including management info) into turbine instances' attributes. 

So, is there any approaching to make Turbine use `management.context-path` variable. thanks

**Comment by litzuhsien** [comment]
ping @spencergibb

**Comment by fengjx** [comment]
+1

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
