### ISSUE TITLE
Ports missing with InstanceInfo serialisation using 1.4.0-M1 (Edgware.M1) and RestTemplate

### ISSUE THREAD

**Issue by ssozonoff** [spring-cloud/spring-cloud-netflix#2372]
Hi,

It seems that port information is not serialised properly when using Edgware.M1 and RestTemplate.
Attached is a dump of what the Eureka server receives and the port information is missing.
However a breakpoint in RestTemplateEurekaHttpClient at line 65, register() method shows the port information present.

Thanks,
Serge

<img width="1187" alt="serge_ _ec2-user_ip-10-10-1-166___ _bash_ _ttys004_and_amazon_ec2_container_service_and_eurekaconfig_java_-_ape_-____projects_ikentoo_ape_" src="https://user-images.githubusercontent.com/610904/31626218-37faed90-b2a9-11e7-82b5-a47ad98fafb3.png">

**Comment by ssozonoff** [comment]
Hmmmm never mind. The get for port is flagged as @JsonIgnore....

Which confuses me even more .... how does the port related information get communicated to the Eurka Server ???

**Comment by spencergibb** [comment]
Are you seeing an issue? Secure port and non secure port are the sources of Truth for eureka

**Comment by ssozonoff** [comment]
Well I am not sure. I would expect both ports to get sent from the Eureka client to the Eureka server. As seen in the tcpdump above neither are getting transmitted when the Eureka client registers!

Looking at the source for InstanceInfo it seems these fields are marked as JSON ignore so now I am confused and possibly overlooking something. How does Eureka client transmit port related information to the Eureka server ?

**Comment by ssozonoff** [comment]
The way I understand it is that deserialisation was working before with Jersey and XStream and @JsonIgnore had no impact. With RestTemplate we are using Jackson which cant serialise a private field and the getter is marked as @JsonIgnore. 

All this is just a guess at the moment.

**Comment by spencergibb** [comment]
This is only an issue if you are excluding Jersey.

**Comment by ssozonoff** [comment]
Which is the case. We are using Spotify Docker Client which also uses Jersey but not the same version. After spending several hours trying to sort out the version hell around Jersey I thought it best to try and eliminate Jersey 1.x requirements... and here we are :-)

**Comment by spencergibb** [comment]
Glad you caught it on a milestone and not a release.

**Comment by spencergibb** [comment]
@ssozonoff can you try the new snapshots?

**Comment by ssozonoff** [comment]
Hi,

We are trying the snapshot and it seems to be working as it is supposed to.
Thanks for the reactivity!
