### ISSUE TITLE
Is ZULL retry will work in Gaia environment only ? 

### ISSUE THREAD

**Issue by manohar427** [spring-cloud/spring-cloud-netflix#2376]
Hi I have a question related to zuul retry .. i am trying to do zuul retry changes related an application which is lying under non- gai environment,retry mechanism is not working and same code is working in Gaia environment.My ZUUl application is pointing to gaia environment urls.

Is zuul retry will work only from Gaia environment ?

**Comment by spencergibb** [comment]
What is Gaia? I don't know what that is.

**Comment by manohar427** [comment]
Gaia means it is one of the Cloud environment .. it is from Spring Pivotal

**Comment by manohar427** [comment]
To make it more clear : My Zuul-gate way application is running under out side cloud environment and trying to call Spring boot cloud services.In this case Can zuul retry will work ?because i have done any service registry for zuul-gate way application

**Comment by spencergibb** [comment]
zuul retry should work regardless of environment. Can you provide more details about your application (versions, dependencies, etc...)

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
