### ISSUE TITLE
Zuul: Malformed route mapping if service ID starts with zuul prefix

### ISSUE THREAD

**Issue by doernbrackandre** [spring-cloud/spring-cloud-netflix#2377]
We are currently facing an issue with the zuul route mapping:

zuul application.yml
```
zuul:
  prefix: /test
  strip-prefix: true
```

Test-App application.yml
```
spring:
  application:
    name: testserviceA
```

Now something happens and zuul creates a malformed routing. If I request the routes endpoint I see this:

HTTP/1.1 200 
Content-Type: application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
Date: Wed, 18 Oct 2017 09:04:34 GMT
Transfer-Encoding: chunked

{
    "/test/**testserviceaservicea**/**": "testservicea"
}

**Comment by holy12345** [comment]
Hello, according to your description I did not reproduce the problem (probably because I understand is not very clear). Can you provide the corresponding complete code? Thanks again : )

**Comment by doernbrackandre** [comment]
Hey,

there is no corresponding code at all. Just use a plain spring boot 1.5.x spring boot zuul application and a plain spring boot example app.

Configure the zuul like shown (prefix, stripPrefix) and name the example app "**test**something"
Of course, you need a eureka instance as well.

Once everything is up and running you should see the problem if you hit zuul's /routes endpoint.
It should be something like:
`{
"/test/testsomethingsomething/**": "testsomething"
}`

This duplication in the route mapping makes the downstream route invalid.

I hope this helps.

Best regards

**Comment by holy12345** [comment]
Indeed as you said, there is this problem.I think the question code should be here:
`SimpleRouteLocator`
```
protected Route getRoute(ZuulRoute route, String path) {
	if (route == null) {
		return null;
	}
	if (log.isDebugEnabled()) {
		log.debug("route matched=" + route);
	}
	String targetPath = path;
	String prefix = this.properties.getPrefix();
	if (path.startsWith(prefix) && this.properties.isStripPrefix()) {
		targetPath = path.substring(prefix.length());
	}
	if (route.isStripPrefix()) {
		int index = route.getPath().indexOf("*") - 1;
		if (index > 0) {
			String routePrefix = route.getPath().substring(0, index);
			targetPath = targetPath.replaceFirst(routePrefix, "");
			prefix = prefix + routePrefix;
		}
	}
}
```
Looking forward to your reply，Best regards ：)

**Comment by doernbrackandre** [comment]
@holy12345 thx for your time you spent to investigate this issue :)
@ryanjbaxter thx for your fix. Unfortunately I had no time to do this

Best regards,
A
