### ISSUE TITLE
Ribbon Consistent Hash Loadbalace

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [spring-cloud/spring-cloud-netflix#2380]
spring cloud ribbon can achieve consistent Hash load balancing?

**Comment by ryanjbaxter** [comment]
Can you provide a better description of the problem you are trying to solve?

**Comment by Wang-Jun-Chao** [comment]
I have a url like http://host:port/a/b/c/{pathValue}，pathValue is a path variable，Suppose there are n services. For a pathValue, it fixed request to a server X, assuming X downtime, it will request to the server Y, if the server X has been good, the request will go to the server X.

Because pathValue is a random variable, on the whole, n servers are load balanced, for a specific request, it will request to the specified server, the consistent hash algorithm can achive this goal. But I can not find in Spring Cloud

**Comment by spencergibb** [comment]
You would need to write a custom zuul filter that translated `{pathValue}` to a service id that could be used to loadbalance.

**Comment by fudali113** [comment]
@spencergibb Is there a way to implement the ribbon to do this?

**Comment by spencergibb** [comment]
@fudali113 ribbons job is to map a service id to a host and port. The zuul filter would need to map the `pathValue` to a service id.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
