### ISSUE TITLE
Hystrix Dashboard path Compatible with springboot2 actuator path

### ISSUE THREAD

**Issue by An0nymous0** [spring-cloud/spring-cloud-netflix#2381]
http://hystrix-app:port/hystrix.stream -> http://hystrix-app:port/application/hystrix.stream

**Comment by An0nymous0** [comment]
If the turbine can dynamically obtain：
management:
  context-path:

**Comment by spencergibb** [comment]
Can you please be more specific? If you're asking to move it to the new actuator path, it already has.

**Comment by An0nymous0** [comment]
@spencergibb Is the new actuator routing,If you have had to close the issues.
