### ISSUE TITLE
Should method  org.springframework.cloud.netflix.eureka.CloudEurekaClient.onCacheRefreshed()  first call super.onCacheRefreshed()?

### ISSUE THREAD

**Issue by riyueshiwang** [spring-cloud/spring-cloud-netflix#2382]
hi, i am using _com.netflix.niws.loadbalancer.EurekaNotificationServerListUpdater_ rather than the default _com.netflix.niws.loadbalancer.PollingServerListUpdater_. I found that the _updateListener_ in  _EurekaNotificationServerListUpdater_ could not listen the _CacheRefreshedEvent_(see code as bellow).
`this.updateListener = new EurekaEventListener() {
                @Override
                public void onEvent(EurekaEvent event) {
                    if (event instanceof CacheRefreshedEvent) {
                        if (!updateQueued.compareAndSet(false, true)) {  // if an update is already queued
                            logger.info("an update action is already queued, returning as no-op");
                            return;
                        }
...
`

I found, that is because _org.springframework.cloud.netflix.eureka.CloudEurekaClient_ overrode _EurekaClient_'s method _onCacheRefreshed_ which fire  `CacheRefreshedEvent`(see code as bellowl). so Should method  `org.springframework.cloud.netflix.eureka.CloudEurekaClient.onCacheRefreshed()`  first call `super.onCacheRefreshed()`?
#CloudEurekaClient' method
`@Override
	protected void onCacheRefreshed() {
		if (this.cacheRefreshedCount != null) { //might be called during construction and will be null
			long newCount = this.cacheRefreshedCount.incrementAndGet();
			log.trace("onCacheRefreshed called with count: " + newCount);
			this.publisher.publishEvent(new HeartbeatEvent(this, newCount));
		}
	}`
#EurekaClient' method
`protected void onCacheRefreshed() {
        fireEvent(new CacheRefreshedEvent());
    }`

the version i used is _spring-cloud-netflix-eureka-client-1.3.4.RELEASE.jar_

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

This seems to make sense to me.  @spencergibb what do you think?

**Comment by ryanjbaxter** [comment]
Thanks, want to submit a PR with the changes?

**Comment by To-da** [comment]
already fixed for 2.0 in #2603

**Comment by ryanjbaxter** [comment]
I cherry picked #2604 on top of the 1.4.x branch in  cb0a1d6
