### ISSUE TITLE
Eureka client does not use eureka.instance.hostname.

### ISSUE THREAD

**Issue by hakkibagci** [spring-cloud/spring-cloud-netflix#2384]
Hello,

I have the following config in my Eureka client. The server has a public hostname and a private one (a0bs1.hh.kk.local). But it always gets registered with public hostname. I know some other people experienced a similar problem and I have seen the related issues. I tried almost all suggestions but none helped. I am using 1.4.0.BUILD-SNAPSHOT version.   

```
eureka.client.service-url.defaultZone=http://a0dslb.hh.kk.local:8761/eureka/
eureka.instance.preferIpAddress=false
eureka.instance.hostname=a0bs1.hh.kk.local
eureka.client.healthcheck.enabled=true
```

**Comment by spencergibb** [comment]
I am unable to reproduce. When setting
```
eureka.instance.hostname=spencer-dell
```
I see the following from `<eureka>/eureka/apps
```
<applications>
  <versions__delta>1</versions__delta>
  <apps__hashcode>UP_1_</apps__hashcode>
  <application>
    <name>DEMOEUREKACLIENTEDGWARE</name>
    <instance>
      <instanceId>192.168.2.113:demoeurekaclientedgware</instanceId>
      <hostName>spencer-dell</hostName>
      <app>DEMOEUREKACLIENTEDGWARE</app>
      <ipAddr>192.168.2.113</ipAddr>
      <status>UP</status>
      <overriddenstatus>UNKNOWN</overriddenstatus>
      <port enabled="true">8080</port>
      <securePort enabled="false">443</securePort>
      <countryId>1</countryId>
      <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
        <name>MyOwn</name>
      </dataCenterInfo>
      <leaseInfo>
        <renewalIntervalInSecs>30</renewalIntervalInSecs>
        <durationInSecs>90</durationInSecs>
        <registrationTimestamp>1508520205520</registrationTimestamp>
        <lastRenewalTimestamp>1508520205520</lastRenewalTimestamp>
        <evictionTimestamp>0</evictionTimestamp>
        <serviceUpTimestamp>1508520204881</serviceUpTimestamp>
      </leaseInfo>
      <metadata class="java.util.Collections$EmptyMap"/>
      <homePageUrl>http://spencer-dell:8080/</homePageUrl>
      <statusPageUrl>http://spencer-dell:8080/info</statusPageUrl>
      <healthCheckUrl>http://spencer-dell:8080/health</healthCheckUrl>
      <vipAddress>demoeurekaclientedgware</vipAddress>
      <secureVipAddress>demoeurekaclientedgware</secureVipAddress>
      <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
      <lastUpdatedTimestamp>1508520205520</lastUpdatedTimestamp>
      <lastDirtyTimestamp>1508520204829</lastDirtyTimestamp>
      <actionType>ADDED</actionType>
    </instance>
  </application>
</applications>
```

The hostname field is correct. The instanceId still uses the ipaddress, but that can be set to whatever you want as well.

**Comment by hakkibagci** [comment]
Ok, thanks. Perhaps I misinterpret these properties. I do not want to specify a new hostname or instanceId for my service for registration. I want to refer to the local Ip address of the server and want my service (Eureka client) register to discovery using that local IP. I thought I can use `eureka.instance.hostname` property for that purpose.

**Comment by hakkibagci** [comment]
I solved my problem using `spring.cloud.inetutils.preferredNetworks`. I think we can close this.

**Comment by msalmanST** [comment]
Hey guys,

I am facing the same issue when running eureka server and eureka client on two different domains, in this case eureka server always use its own domain name for the registered instance and not using the client hostname. I also try to set the client domain name by setting inside  bootstrap.properties i.e 
eureka.instance.hostname=my.domain.com but it is not reflecting inside "/eureka/apps"

My eureka version is 0.0.1.

Any help is much appreciated.

**Comment by ryanjbaxter** [comment]
@msalmanST please open a separate issue, include the domain names of the client and server as well as the output of `/eureka/apps`.
