### ISSUE TITLE
HystrixDashboard -threadpool box does not display right TPS

### ISSUE THREAD

**Issue by JagmohanSharma** [spring-cloud/spring-cloud-netflix#2387]
This is regarding issue https://github.com/Netflix/Hystrix/issues/1697. 

any help would be appreciated?

**Comment by spencergibb** [comment]
@JagmohanSharma, we have a fork of the .js file here. If you're consuming the dashboard via spring-cloud-netflix, we can fix it here.

**Comment by JagmohanSharma** [comment]
Please review changes https://github.com/spring-cloud/spring-cloud-netflix/pull/2388.

**Comment by tjuchniewicz** [comment]
Please see my comments in https://github.com/spring-cloud/spring-cloud-netflix/issues/1113.
In my opinion this feature is broken.

**Comment by JagmohanSharma** [comment]
@tjuchniewicz I think we should not keep this in broken state at least with latest version of turbine which would provide us TPS values in sync for both hystrixCommand and hystrixThreadPool in dashboard.

**Comment by tjuchniewicz** [comment]
@JagmohanSharma I agree. But in Spring Cloud Netflix we still use Turbine 1.0. In my opinion we should revert all changes made in https://github.com/spring-cloud/spring-cloud-netflix/issues/1113

**Comment by tjuchniewicz** [comment]
@JagmohanSharma  are you using spring-cloud-starter-turbine or spring-cloud-starter-turbine-stream?
According to this ticket: https://github.com/spring-cloud/spring-cloud-netflix/issues/1629 current solution will work correctly for spring-cloud-starter-turbine-stream only.
