### ISSUE TITLE
Is it worth investigating how to support running an Eureka server on Weblogic?

### ISSUE THREAD

**Issue by theonlyguills** [spring-cloud/spring-cloud-netflix#239]
I have a couple Eureka clients running on our Weblogic infrastructure talking to a standalone embedded Eureka server for now. I'd like to move the Eureka server on weblogic also to benefit from the rest of our infrastructure.

I haven't had success with that so far and I was wondering if it's even worth considering or is the Eureka server not meant to be run on Full EE containers at all? I won't spend too much time on it if you think it's near-impossible due to something obvious in the code base.

From the little debugging I've done so far, it seems the init method of the jersey ServletContainer never gets called and this results in NPE's everywhere down the line.

**Comment by aivans** [comment]
Might be similar to Jboss?
https://github.com/spring-cloud/spring-cloud-netflix/issues/205

**Comment by theonlyguills** [comment]
Oh thanks, I looked around but I missed that one with regards to JBoss. If they got it to work on the JBoss train wreck there is hope!

I'll post a solution if we find one.

**Comment by silentFred** [comment]
@theonlyguills did you manage to find a solution? Quite a few years later but it's still quite tricky deploying eureka on weblogic and if you wound anything useful to share it would be great.
