### ISSUE TITLE
ClassNotFound exception when using Spring Cloud Starter Turbine AMQP

### ISSUE THREAD

**Issue by caingocduong** [spring-cloud/spring-cloud-netflix#2392]
- I used these dependencies:
`<dependency>`
`            ` `<groupId>org.springframework.cloud</groupId>`
`            ` `<artifactId>spring-cloud-netflix-turbine-amqp</artifactId>`
`           ` `<version>1.0.7.RELEASE</version>`
        `</dependency>`
`<dependency>`
`            ` `<groupId>com.netflix.turbine</groupId>`
`            ` `<artifactId>turbine-core</artifactId>`
`            ` `<version>2.0.0-DP.2</version>`
        `</dependency>`
And spring cloud version is Brixton.SR7

- Exception:
`   ` Caused by: java.lang.ClassNotFoundException: com.netflix.turbine.aggregator.InstanceKey

**Comment by ryanjbaxter** [comment]
Brixton is no longer supported please upgrade to Camden.SR7 or Dalston.SR4

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
