### ISSUE TITLE
why not spring cloud hystrix dashboard and turbine provide data persistent storage

### ISSUE THREAD

**Issue by 13567436138** [spring-cloud/spring-cloud-netflix#2393]
why not spring cloud hystrix dashboard and turbine provide data persistent storage

**Comment by spencergibb** [comment]
Netflix built them without that capability. They are stateless. You can publish the Hystrix metrics to some other system for persistent storage, see https://github.com/Netflix/Hystrix/wiki/Metrics-and-Monitoring#metrics-publisher
