### ISSUE TITLE
what's wrong with my zuul

### ISSUE THREAD

**Issue by 13567436138** [spring-cloud/spring-cloud-netflix#2394]
![image](https://user-images.githubusercontent.com/31508490/32055118-61bc3b9c-ba93-11e7-8d87-b07805157b45.png)
zuul with spring boot admin displays nothing . when I use client to invoke services with zuul it return's null.
the eureka can discovery zuul,but the health url return 's 200 ,but display's nothing too.

**Comment by spencergibb** [comment]
We don't maintain spring boot admin. Can you supply a minimal sample that reproduces the problem?

**Comment by 13567436138** [comment]
what do you mean of a minimal sample? the sample code?

**Comment by 13567436138** [comment]
`server.context-path=/
server.port=9999

spring.application.name=zuul

management.security.enabled=false

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#spring.zipkin.base-url=http://localhost:7777
spring.zipkin.service.name=zipkin-server
spring.zipkin.compression.enabled=true
spring.zipkin.enabled=true
spring.zipkin.locator.discovery.enabled=true
spring.sleuth.sampler.percentage=1.0`


`package com.mark.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.cloud.client.SpringCloudApplication;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;

/*
*hxp(hxpwangyi@126.com)
*2017年10月24日
*
*/
@SpringCloudApplication
@EnableAutoConfiguration
@EnableZuulProxy
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}

**Comment by 13567436138** [comment]
it seams that when there is a request like /health zuul will find a route。but this kind of request is generated by actuator。this do not need redirect to services。how can zuul itself response this kind of request for monitoring。

**Comment by 13567436138** [comment]
I have solved this problem.the reason is zuul.servlet-path=/zuul  this configuration can not be / .
