### ISSUE TITLE
why  request is null

### ISSUE THREAD

**Issue by 13567436138** [spring-cloud/spring-cloud-netflix#2397]
![image](https://user-images.githubusercontent.com/31508490/32096354-cfc364d0-bb38-11e7-8b6b-b5e57ae8475e.png)

**Comment by ryanjbaxter** [comment]
Please dont create issues with just a screenshot.  Please provide a description of what you are doing, what is not working, and a sample project that reproduces the problem.  Please reopen this issue with that information.
