### ISSUE TITLE
zuul was not register to eureka???

### ISSUE THREAD

**Issue by CARRYME0820** [spring-cloud/spring-cloud-netflix#2399]
error: com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server 
my code was right i think,it was a simple example

**Comment by spencergibb** [comment]
Can you share your application or configuration?

**Comment by CARRYME0820** [comment]
zuul configuration code  
server:
   port: 9000
   context-path: /
spring:
  application:
    name: supermarket-gateway-zuul
eureka:
  client:
    service-url:
       defauleZone: http://root:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
