### ISSUE TITLE
Feign : Reuse RibbonLoadBalancer

### ISSUE THREAD

**Issue by stephaneLeroy** [spring-cloud/spring-cloud-netflix#240]
A bug was pointed on Feign Ribbon integration https://github.com/Netflix/feign/issues/182
Ribbon does not expect multiple [RibbonLoadBalancer](http://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/ribbon/RibbonLoadBalancer.java) (IClient/AbstractLoadBalancerAwareClient) instances for the same client.

spring-cloud-netflix seems to have the same bug (WARN  c.n.servo.jmx.JmxMonitorRegistry - Unable to register Monitor::MonitorConfig{name= ...). 
Feign Ribbon integration was first corrected [by adding cache on FeignRibbonClient.lbclient() method](https://github.com/bstick12/feign/commit/cd93277f5e843f1c0965f9d1dea79a40fad17c3c) to check if a client exists before creating a new one.

**Comment by ivelkov** [comment]
Even with the implemented fix issue is observable if two threads simultaneously try to access a LBClient for a missing client name.

**Comment by spencergibb** [comment]
@ivelkov if there is a problem can you open a new issue with what you're seeing and how to reproduce?
