### ISSUE TITLE
Zuul Removes 'br' from accept-encoding header before forwarding  request to downstream service

### ISSUE THREAD

**Issue by bsridhar123** [spring-cloud/spring-cloud-netflix#2400]
When a request is sent to Zuul from browser with accept-encoding of 'br', zuul removes the encoding when it forwards the request to downstream service. My downstream service is written to compress static content at build time with brotli compression format if 'accept-encoding' includes that.

It seems like Zuul does not support '**br**' compression.

Can you please let us know why  Zuul does not support it  and is there any plans to add support for it in coming releases.

**Comment by voronaam** [comment]
Zuul does not really support HTTP RFC. See, for example, issue 2343

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
