### ISSUE TITLE
can we use eureka discovery in eureka project to get config from config server

### ISSUE THREAD

**Issue by 13567436138** [spring-cloud/spring-cloud-netflix#2403]
can we use eureka discovery in eureka project to get config from config server.
it seams when eureka server starting the config service instance can not found in eureka.throws Exceptions.

**Comment by spencergibb** [comment]
Have you read http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#discovery-first-bootstrap?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
