### ISSUE TITLE
After upgrading from Brixton to Dalston SR3, feign client not converting Collection to CSVs

### ISSUE THREAD

**Issue by aman9bits** [spring-cloud/spring-cloud-netflix#2416]
In Brixton, for the following request mapping:
```
@RequestMapping(value = "/foo/{ids}", method = RequestMethod.GET, produces = "application/json; charset=utf-8")
public String getFoo(@PathVariable("ids") final List<String> ids);
```

The request generated would have a comma separated list of ids. Example:
`/foo/1,2,3,4`

But after upgrade to Dalston, the request being generated is `/foo/[1,2,3,4]`
On the server side, spring would not be mapping [1,2,3,4] as a list. It is treated as a string.

**Comment by ryanjbaxter** [comment]
Can you show us the controller for the service that is receiving the request?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
