### ISSUE TITLE
Slice testing of Zuul along the lines of @WebMvcTest

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-netflix#2419]
Just a proposal for a feature -

I am working with a customer who has a normal web-app which has a zuul proxy added in to proxy certain uri paths.

Now to test the Zuul parts of the application, loading up the entire Spring Boot context using `@SpringBootTest` leads to a lot of wiring issues. If in some form only the Zuul slice can be loaded up along the lines of say `@WebMvcTest` in Spring Boot that can really help with such tests, this way only the Zuul Configuration along with the configuration to load up the embedded server can be started up and wired in. 

This can potentially be added for other features in spring-cloud-netflix also.

**Comment by j2ali** [comment]
@bijukunjummen How did you work around the wiring issues. I am experiencing the same thing

**Comment by spencergibb** [comment]
> leads to a lot of wiring issues

I'd like to know what those are.

**Comment by bijukunjummen** [comment]
Not zuul wiring issues @spencergibb, customer also has a bunch of auto-configurations which gets in the way. So I would ideally like to prevent customer configurations and auto-configurations from coming in the way. @j2ali I have got this set of configurations (with auto-configuration turned off) which appear to work well for me, these can potentially be added to the slice test.

```
   @Configuration
    @EnableZuulProxy
    @Import({
            DispatcherServletAutoConfiguration.class,
            ZuulProxyAutoConfiguration.class,
            EmbeddedServletContainerAutoConfiguration.class,
            SimpleDiscoveryClientAutoConfiguration.class,
            UtilAutoConfiguration.class,
            PropertyPlaceholderAutoConfiguration.class,
            RibbonAutoConfiguration.class,
            ArchaiusAutoConfiguration.class
    })
    public static class SpringConfig...
```

**Comment by spencergibb** [comment]
Ah, makes sense.

**Comment by bijukunjummen** [comment]
I have a strawman implementation here - https://github.com/bijukunjummen/spring-cloud-netflix/blob/GH-2419/spring-cloud-netflix-core-test/src/test/java/org/springframework/cloud/netflix/zuul/slice/ZuulProxySliceTest.java, still quite rough though, will clean up and send a PR.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
