### ISSUE TITLE
Many route configuration files

### ISSUE THREAD

**Issue by pchlebda** [spring-cloud/spring-cloud-netflix#2422]
Is there anyway to have many route config files ?

- resources/routes/a-category-service.properties
- resources/routes/b-category-service.properties
- resources/routes/c-category-service.properties

How to let know Zuul to load all these files when it starts up ? 
I've tried load files using bean annotation and PropertyPlaceholderConfigurer, but it does not work.

What's the nest approach to change routing during application runtime ?

**Comment by ryanjbaxter** [comment]
I am not really clear on the use case you have.  Maybe you can elaborate.

The only way I could think of doing this is using profile specific configuration files and placing the configuration the given routes in those.

**Comment by pchlebda** [comment]
I 'd like to have muliple properties file that stores zuul routes config instead of one(application.properties). 
1.  a-category-service.properties contais 50 routes configuration like:
    - zuul.routes.books.url=http://localhost:8090 (49 more such config)

2. b-category-service.properties contains 60 routes config

3. b-category-service.properties contains 30 routes config

How can I load these properties files during app start up ?
By default routes config is load from application.properties, but I'd like to split it up to make routes config more readable.

What's the best approach to change routing during application runtime ?

**Comment by ryanjbaxter** [comment]
Like I said the only way I can think of to do this is to use profile specific properties files.
For example
```
application-acategory.properties
application-bcategory.properties
application-ccategory.properties
```
And then activate these profiles when running the app.

**Comment by pchlebda** [comment]
Finally I found out solution:
`@PropertySource(value = { "classpath:routes/a-category-service.properties", "classpath:routes/b-category-service.properties", "classpath:routes/c-category-service.properties" })
`
For some reason it does not work with PropertyPlaceholderConfigurer.
I don't need to use profiles in my app.
