### ISSUE TITLE
Customizing Zuul's socket-timeout

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2424]
I am in the situation that I have requests that are configured to have different timeouts in backend services. As a default we have 10 seconds in `socket timeout`, having a large global timeout will cause problems, so can't we customize the socket timeout for different requests from zuul side instead of just setting `zuul.host.socket-timeout-millis` to some high value?

Any help is appreciated!

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud are you using?  How are you configuring Zuul to route requests?  Are you using service discovery or specifying a URL?

**Comment by mirak94** [comment]
Thank you @ryanjbaxter for your help!
I'm using `1.3.4.RELEASE` as `spring-cloud-starter-zuul` version.
I'm setting route host at runtime based on domain (as if we are defining `zuul.routes._.url`={..}).

**Comment by spencergibb** [comment]
I don't think we have a way using the `SimpleHostRoutingFilter` to set timeouts independently. You could move to using a uri with a static url defined in ribbon, that would allow for this I think.

**Comment by mirak94** [comment]
Thank you very much @ryanjbaxter @spencergibb for your help!

**Comment by mirak94** [comment]
@ryanjbaxter @spencergibb 
I've moved to using ribbon as it enables me to customize timeouts per route/service.
I need to modify the server/host to which I am routing the request based on some configurations, do you think that is possible? If yes, could you please share some insights that may help?
Thank you in advance for your help!

**Comment by ryanjbaxter** [comment]
Sounds like a different issue, please open a separate issue.
