### ISSUE TITLE
Redirect from controller behind zuul proxy

### ISSUE THREAD

**Issue by modestukasai** [spring-cloud/spring-cloud-netflix#2425]
Could you please check this issue. This is a problem till now, even with latest spring versions.
https://stackoverflow.com/questions/35453939/spring-redirect-url-issue-when-behind-zuul-proxy

**Comment by ryanjbaxter** [comment]
I dont see this being a Spring Cloud issue.

**Comment by modestukasai** [comment]
Ok, Should it be assigned to Spring MVC bug tracker directly?

**Comment by spencergibb** [comment]
I would move the discussion there.

**Comment by bijukunjummen** [comment]
Just a quick point, there is a `ZuulFilter` available which can potentially rewrite the `Location` header for cases just like this - `org.springframework.cloud.netflix.zuul.filters.post.LocationRewriteFilter`, may be worth a try also.
