### ISSUE TITLE
Eureka replicas unavailable

### ISSUE THREAD

**Issue by holy12345** [spring-cloud/spring-cloud-netflix#2430]
Hi, we now have 3 eureka, each of eureka defaultZone is the remaining two，the example is this
eurekaA
eureka.client.serviceUrl.defaultZone = eurekaB, eurekaC

eurekaB
eureka.client.serviceUrl.defaultZone = eurekaA, eurekaC

eurekaC
eureka.client.serviceUrl.defaultZone = eurekaA, eurekaB

spring.application.name is the same

This configuration after the test environment is started, unavailable-replicas is empty, available-replicas are the other two eureka. This is correct, but when we put this configuration directly into the production environment, available-replicas is empty and unavailable-replicas are the other two eureka, what is this?

In addition, under, unavailable-replicas parameters will affect what eureka function？

Can a brief introduction to the principle of unavailable-replicas and available-replicas?

Thank you！

**Comment by GhaTMA** [comment]
@holy12345 did you find a solution for your problem? I'm facing the same problem and can't figure out what am I doing wrong

**Comment by holy12345** [comment]
@GhaTMA I have solved this problem, if I remember it because the configuration file is wrong

**Comment by karthikrajakandasamy** [comment]
@holy12345  could you please share the resolved steps?
