### ISSUE TITLE
Not able to see the trace immediately in zipkin UI for the latest request.

### ISSUE THREAD

**Issue by jayaprakash524** [spring-cloud/spring-cloud-netflix#2433]
I have configured sleuth sampler percentage to 1.0 in all the microservices.
I have configured Zipkin Server with Elasticsearch storage.

I performed REST call which internally calls few microservices. After I get the response I want to see the traces for it. I am not able to see the trace for the latest request.
Could some one help me with this.

**Comment by ryanjbaxter** [comment]
Sounds like this belongs in the Spring Cloud Sleuth project. https://github.com/spring-cloud/spring-cloud-sleuth
