### ISSUE TITLE
spring-cloud-starter-netflix-zuul does not work on Finchley.M3

### ISSUE THREAD

**Issue by danyflorez** [spring-cloud/spring-cloud-netflix#2444]
I'm trying to make an api gateway but I'm getting an error with following configuration:

`buildscript {
ext {
springBootVersion = '2.0.0.M6'
}
repositories {
mavenCentral()
maven { url "https://repo.spring.io/snapshot" }
maven { url "https://repo.spring.io/milestone" }
}
dependencies {
classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.mastering.spring.zuul'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
mavenCentral()
maven { url "https://repo.spring.io/snapshot" }
maven { url "https://repo.spring.io/milestone" }
}

ext {
springCloudVersion = 'Finchley.M3'
}

dependencies {
compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
compile('org.springframework.cloud:spring-cloud-starter-netflix-zuul')
testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
imports {
mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
}
}`

This is the error:

`Caused by: java.lang.NoSuchMethodError: org.springframework.boot.actuate.autoconfigure.web.servlet.ManagementServletContext.getContextPath()Ljava/lang/String; at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration.hystrixMetricsStreamServlet(HystrixManagementContextConfiguration.java:58) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3] at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f.CGLIB$hystrixMetricsStreamServlet$1(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3] at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f$$FastClassBySpringCGLIB$$42305d21.invoke(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3] at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.1.RELEASE.jar:5.0.1.RELEASE] at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE] at org.springframework.cloud.netflix.hystrix.HystrixManagementContextConfiguration$$EnhancerBySpringCGLIB$$5678a89f.hystrixMetricsStreamServlet(<generated>) ~[spring-cloud-netflix-core-2.0.0.M3.jar:2.0.0.M3] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144] at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:155) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE] ... 24 common frames omitted
`
Am I missing something?

**Comment by spencergibb** [comment]
Does it work with M5? We have not done a release against m6.

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment]
Closed via 388ec98087f5152bc0d255520a0001402a5cfe6e

**Comment by deveth0** [comment]
I had the same issue, moving from Finchley.M3 to Finchley.BUILD-SNAPSHOT solved this.

fyi: i'm working with M6
