### ISSUE TITLE
Spring Cloud,Zuul,Eurekh server

### ISSUE THREAD

**Issue by Anupama28** [spring-cloud/spring-cloud-netflix#2445]
Hi,
I am new to spring cloud netflix,zuul,Eureka server.i developed my microservice using this spring boot,spring cloud,zuul,,Eureka.For perfomance testing i m using blazemeter.I am getting 50 % error in blaze meter.I am 500(Internal server error).
Can u please help this to figure out.

Thanks

**Comment by spencergibb** [comment]
Please provide more information. Stating that there are errors is very vague

**Comment by Anupama28** [comment]
There are three application.
1.My service
2.Eureka Service
3.Zuul Sever

My API are deployed in 8 server. For single request it is fine and response time also good.but if i send more then 200 request some of the request are failing(not reach to my api(500)).
Same api developed in nodejs they are not getting any error.Why in java it is 500 error.i m not getting the root caused.

Thanks
Anupama

**Comment by ryanjbaxter** [comment]
That is still not enough information.  A stacktrace would be a good starting point for us to help you.

**Comment by harishkadamudi** [comment]
@Anupama28 , even I am in the same boat, did you resolve this?

**Comment by Anupama28** [comment]
Hi Harish,

No,I am able to fixed it.

Thanks,
Anupama

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
