### ISSUE TITLE
Feign inheritance @PostBody issue

### ISSUE THREAD

**Issue by jonashartwig** [spring-cloud/spring-cloud-netflix#2447]
Hi, I want to create a Feign client to a service using inheritance. I have my interface:

```java
@FeignClient(name = "statistical-postal", url = "${se.inoviagroup.pii.postal.url}")
public interface PostalService {
    @RequestMapping(method = RequestMethod.POST, path = "/parse")
    PostalDto parse(@RequestBody final String address);

    @RequestMapping(method = RequestMethod.POST, path = "/expand")
    Collection<String> expand(@RequestBody final String address);
}
```

And a rest controller:

```java
@RestController
public class PostalController implements PostalService {
    private final PostalExtractionService _postalExtractionService;

    @Override
    public PostalDto parse(@RequestBody final String address) {
        return _postalExtractionService.parse(address);
    }

    @Override
    public Collection<String> expand(@RequestBody final String address) {
        return _postalExtractionService.expand(address);
    }
}

```

The paths are correctly mapped but my parameter address is not parsed (i get null only). It does not work with @PathVariable either. However it works if I add @RequestBody to the controller method. Is that expected or a bug?

This is observed Edgware.RC1 and Dalston.SR4.

regards

**Comment by spencergibb** [comment]
I don't know, my guess is that's how Spring MVC works. We don't recommend sharing a client interface with the server.

**Comment by jonashartwig** [comment]
I see, the documentation states that it is possible if I read and understood it right.

**Comment by spencergibb** [comment]
Then it might be a problem with Spring MVC not feign?

**Comment by jonashartwig** [comment]
Possibly, I do not know :(

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
