### ISSUE TITLE
Deploy Eureka on AWS with EIP - Use Public or Private Subnet?

### ISSUE THREAD

**Issue by george24601** [spring-cloud/spring-cloud-netflix#2449]
I am deploying Spring Cloud Eureka on AWS with the [DNS + EIP approach](https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2#configuring-eips-using-dns). I am not so sure if I should put Eureka in my public subnet or private subnet, because

1. All my services and service consumers are within the the same VPC. Therefore, I want to shield Eureka from the internet. This suggests deploying it in the private subnet
2. Associating EIP, which is a public accessible IP, to an instance inside the private subnet is possible, but it feels odd.

I am leaning toward the public subnet approach, and I will protect Eureka with traffic rules so that only traffic from the same VPC is allowed, but I am really interested in other people's thoughts on this problem. 

Any feedback is highly appreciated!

**Comment by felixoldenburg** [comment]
Hi,
what about putting your services in different VPC grouped by internal, and internet facing services?
We do this in our back end where our service discovery also lies in the internal VPC.
The API gateway is obviously in the external VPC (and has a public IP) with the subnets configured so that we can route the desired traffic between those two VPCs.

**Comment by george24601** [comment]
Thanks for your reply @felixoldenburg! We will definitely explore in that direction. 

But considering that EIP is a public IP address, associating EIP with internal VPC instances (I presume you don't assign public IPs to the internal VPC) may introduce some dynamic routing. My understanding is that dynamic routing might confuse certain firewall/security rules. Did you run into such problem in your deployment?

**Comment by felixoldenburg** [comment]
I don't understand which instance you want to give a public IP to.
You could have a public IP for the API gateway in the public VPC (or rather a load balancer for the gateway instances) and the gateway would access the service discovery and all your other service which lie within a private VPC.
After all it's just two subnets with the following configuration:
- VPCA can be accessed from the outside
- VPCB blocks all traffic except from and to VPCA
This wouldn't involve giving a public IP to any instance within the private network.

**Comment by george24601** [comment]
Hi @felixoldenburg, my EIP/public IP is related to Eureka. When I follow  [DNS + EIP approach](https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2#configuring-eips-using-dns). Upon start, Eureka will bind the EIP to the EC2 instance it's on. This also means the instance will now have a public IP.

For now, I leave Eureka in the public subset and give it security rules so that only traffics from within the VPC is allowed.
