### ISSUE TITLE
[Question] Reverse proxy behaviour

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#247]
Hi guys,

Can please share how the proxy content rewriting happens?

For Stores example, I saw that the response from http://localhost:8081/stores is already processed if I send the header x-forwarded-host.

Then I found this documentation:
http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-behind-a-proxy-server

I tried to change the settings in yaml:
```
tomcat:
  remote_ip_header: zzz  
```
But it still used the x-forwarded-host header.

Thanks

**Comment by spencergibb** [comment]
zuul doesn't rewrite content per-se.  It sends "X-Forwarded-Host" and "X-Forwarded-Prefix" (a custom prefix that spring understands.

**Comment by aivans** [comment]
Thanks Spencer,

Good to know.

I am trying to play a bit with this and I want to make these changes:
```
server:
  port: 8081
  tomcat:
    remote_ip_header: x-custom-stuff
```
But it still works with   "X-Forwarded-Host"

**Comment by spencergibb** [comment]
We also strip the prefix configured in zuul (you can opt in not strip the prefix to the url this as we do in stores).

**Comment by spencergibb** [comment]
our zuul filter currently hard-codes `X-Forwarded-Host`

**Comment by aivans** [comment]
Thanks Spencer,

I was trying to understand the mechanism. 
The above yml config is for the Stores sample project, and was trying to change it during experiments, but seems to have no effect.

**Comment by aivans** [comment]
Guys,

Maybe this question belongs to Spring Boot, but in the customers-stores sample, who does the replacing using ```X-Forwarded-Host```? Tomcat or Spring?

**Comment by dsyer** [comment]
Spring: https://github.com/spring-projects/spring-framework/blob/d64c48ff5f06aa444c199ae0cfa0d86f1b36af00/spring-web/src/main/java/org/springframework/web/util/UriComponentsBuilder.java#L283
