### ISSUE TITLE
Hystrix network agent with Springboot

### ISSUE THREAD

**Issue by preetigupta25** [spring-cloud/spring-cloud-netflix#2473]
Hello,

I need to use Hystrix network agent. I added 
	`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-hystrix-network-auditor-agent</artifactId>
			<version>2.0.0.M2</version>
		</dependency>`

Here is the error I get

`Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-starter-hystrix-network-auditor-agent:jar:2.0.0.M2 in spring-releases (https://repo.spring.io/libs-release)`. 

This is happening for many other versions of hystrix network agent I tried for. Also I looked at http://start.spring.io/ to see the dependency version but http://start.spring.io/ does not have Hystrix network agent for Spring. Please suggest.

**Comment by spencergibb** [comment]
I have no knowledge of an artifact named `spring-cloud-starter-hystrix-network-auditor-agent`. Where did you get that name?

**Comment by preetigupta25** [comment]
It is the jar to implement Hystrix Network Agent. I got the name from maven's site

`
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-hystrix</artifactId>
    <version>2.0.0.M2</version>
</dependency>`


https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-network-auditor-agent

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

We don't own or manage that dependency. You should use
```
<dependency>    
  <groupId>com.netflix.hystrix</groupId>
  <artifactId>hystrix-network-auditor-agent</artifactId>
  <version>1.5.12</version>
</dependency>
```
See http://search.maven.org/#artifactdetails%7Ccom.netflix.hystrix%7Chystrix-network-auditor-agent%7C1.5.12%7Cjar
