### ISSUE TITLE
Zuul double encoding

### ISSUE THREAD

**Issue by raiRaiyan** [spring-cloud/spring-cloud-netflix#2478]
This issue is very similar to #1241. An encoded url is encoded twice by zuul.

> When a request passes through either RibbonRoutingFilter or SimpleHostRoutingFilter, ProxyRequestHelper::buildZuulRequestURI is called, encoding the request.

The second encoding now happens in https://github.com/spring-cloud/spring-cloud-netflix/blob/c1fc987d9669b1d8eb127fe6a1b97b734988c962/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RetryableRibbonLoadBalancingHttpClient.java#L89

I am using spring-cloud-netflix-1.3.5.RELEASE.  
I tried to upgrade to spring-cloud-netflix-1.4.0.RELEASE, but then I get #2375.  

I am guessing the upgrade won't help, because the encoding is still happening in `RetryableRibbonLoadBalancingHttpClient` of v1.4.0.RELEASE

**Comment by ryanjbaxter** [comment]
@raiRaiyan Have you experienced the same issue without using Spring Retry? I would think that `RibbonLoadBalancingHttpClient` would also have the same issue.
https://github.com/spring-cloud/spring-cloud-netflix/blob/c1fc987d9669b1d8eb127fe6a1b97b734988c962/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RibbonLoadBalancingHttpClient.java#L90

**Comment by ryanjbaxter** [comment]
ping @raiRaiyan

**Comment by raiRaiyan** [comment]
Let me check and get back on this. @ryanjbaxter

**Comment by raiRaiyan** [comment]
> Have you experienced the same issue without using Spring Retry? I would think that RibbonLoadBalancingHttpClient would also have the same issue.

Yes. I disabled retry and I have the same issue, there as well.
