### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#248]
Has there been any thought put to API documentation? Tried playing around with HAL Browser at a service level.  Works, ok I guess.  The main problem is that if installed locally per service it will try to pull the port number if accessing via Zuul.  

Second thought is to add it to Zuul and that would solve the port problem.  

Would the second option make sense?  

Another/third option, would be a bit heavier.  Make a Spring app/service designed to read from Eureka and be dedicated to API documentation across all of the services.  

Thoughts?  Does something like this exist?  Does it need to exist?

**Comment by dsyer** [comment]
Nice as it is, I'm not sure I count the HAL Browser as "documentation". Are you asking about a recommended solution for user apps, or something provided by the framework for APIs that we wrap, like Eureka?

Did you see @wilkinsona's API documentation from unit test approach: https://github.com/spring-projects/spring-restdocs?

**Comment by ccit-spence** [comment]
Probably something closer to the restdocs example.  Our typical dev cycle is create a service and then move on to the next.  Maintaining docs via something like Confluence is to me a nightmare.  It creates another thing to be maintained.  Just looking at ways to quickly look at a service and be able to tell its purpose and API.  

Doesn't seem to me like the kind of thing that would need to be in Spring Cloud. Given the volume of different services in a polyglot environment that could be implemented.

That being said some sort of standard metadata service to read information from the various services might not be a bad idea.
