### ISSUE TITLE
FallbackFactory logging throwable at init spring application

### ISSUE THREAD

**Issue by cyejing** [spring-cloud/spring-cloud-netflix#2482]
https://github.com/spring-cloud/spring-cloud-netflix/blob/b8a357b685d1ccb3f8b48f0fe9dbb1e6d9bac9b9/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/HystrixTargeter.java#L67

this "new RuntimeException()" to FallbackFactory,but logging error Can not work normally
please pass parameters "null" is better

**Comment by ryanjbaxter** [comment]
Please provide a better description of the problem.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
