### ISSUE TITLE
spring-cloud feign with hystrix

### ISSUE THREAD

**Issue by qq86865810** [spring-cloud/spring-cloud-netflix#2486]
In spring cloud project
I use feign with hystrix
but when the microserver provider had the error , the feign cannot find the fallback method
so i test the code
this is the sample test code
UserFeignClient.class
@FeignClient(name = "yyf-provider-user", fallback = UserFeignClientImpl.class)
public interface UserFeignClient {

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public User findById(@PathVariable("id") Long id);

}
UserFeignClientImpl.class
@Component
public class UserFeignClientImpl implements UserFeignClient {
    @Override
    public User findById(Long id) {
        User user = new User();
        user.setId(-1L);
        user.setUserName("default user");
        return user;
    }
}
in the spring cloud Camden version , the feign can find the fallback method 
but the newer version cannot find the fallback method such as dalston 
i check the doc bewteen camden and dalston
cannot find the diffrent

**Comment by spencergibb** [comment]
You need to set `feign.hystrix.enabled=true`.

See the docs http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#spring-cloud-feign-hystrix

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by qq86865810** [comment]
thank for your advice .

**Comment by holy12345** [comment]
@qq86865810 Hello, to open feign the fallback function is required to set the `feign.hystrix.enabled = true` , because the default value of this parameter is `false`.
