### ISSUE TITLE
[Ribbon] Route request to an shutdown server when disable Eureka and use listOfServers

### ISSUE THREAD

**Issue by chanjarster** [spring-cloud/spring-cloud-netflix#2491]
Hello, I follow the official [guide](https://github.com/spring-guides/gs-client-side-load-balancing) and found a problem:

If I configure 3 servers and only 1 server started, the Ribbon client(with Eureka disabled) will probably route a request to shutdown server even if `PingUrl` failed.

I reported a https://github.com/spring-guides/gs-client-side-load-balancing/issues/4 (has detailed information) to the [guide project](https://github.com/spring-guides/gs-client-side-load-balancing) and @ryanjbaxter  said it's belong to here and gave a reasonable guess.

**Comment by Gunny133** [comment]
i hava the same question #2485 ,ribbon route to a shutdown server  DynamicServerListLoadBalancer updateAllServerList allway set all server status isAlive is true
