### ISSUE TITLE
Zuul's dynamic routing

### ISSUE THREAD

**Issue by holy12345** [spring-cloud/spring-cloud-netflix#2496]
I think dynamic routing is one of the features of spring cloud zuul. If you modify the routing rules in the properties file, for the moment we can only update the rules by restarting zuul's service. This may be unfriendly to the gateway. By reading the source code I found that spring cloud has been prepared for the dynamic routing function, but the default `SimpleRouteLocator` does not implement `RefreshableRouteLocator` interface, which can not be completed dynamic routing capabilities. If you want to achieve dynamic routing function, we need to read the source code of zuul, and have some understanding of the source code to complete this function. The specific way to do dynamic routing is to extend the `SimpleRouteLocator` class and override the `locateRoutes()` method. This is difficult for the average user.

**Comment by holy12345** [comment]
@ryanjbaxter Hello, maybe I am wrong, but if you agree with me, I am willing to submit a PR to improve this function, looking forward to your reply, the best wishes！

**Comment by Lovnx** [comment]
I have a solution according to your way. Do you need the source code?

**Comment by holy12345** [comment]
@Lovnx Thank you for your answer, is this solutionis to inherit SimpleRouteLocator and rewrite the locateRoutes () method? :)

**Comment by Lovnx** [comment]
sure

**Comment by holy12345** [comment]
@Lovnx Thank you, I know this method. As described in the same, I hope that spring cloud originally provided this feature. :)

**Comment by Lovnx** [comment]
hope too

**Comment by ryanjbaxter** [comment]
I guess it depends on how you are using Zuul.  Sees like if you are using service discovery with Zuul your routes should be refreshable if not than it seems unlikely.

**Comment by holy12345** [comment]
@ryanjbaxter  Thank you for your reply, I think you are right. I temporarily closed the issue for now :)
