### ISSUE TITLE
A zuul's configuration option goes wrong

### ISSUE THREAD

**Issue by Lovnx** [spring-cloud/spring-cloud-netflix#2497]
The version is Dalston.SR3, my zuul project added a configuration option:

zuul.SendErrorFilter.post.disable=true

After deploying, I found log file still print error stack trace info. But my pre-version(Camden.SR5) is functioning well (no error stack trace info in log file).

Is this a bug or a new feature?

**Comment by spencergibb** [comment]
Change post to error

**Comment by Lovnx** [comment]
Thanks, It's resolved my problem.
