### ISSUE TITLE
Zuul - specify fallback per route

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#250]
Since it is possible to specify Hystrix and Ribbon parameters for each route in Zuul, it would be nice to specify the Hystrix fallback method per route also.

The solution  I have in mind right now:
- programmatic configuration of Hystrix by extending RibbonCommand, where ```getFallback()``` would be overridden
- application.yml: specify the custom class in the ```zuul.<<route>>.hystrix``` configuration
- use the default RibbonCommand if nothing configured

What do you think?

**Comment by spencergibb** [comment]
If you're going to extend `RibbonCommand` I wouldn't put that class in a config file.  We would want it as a Spring Bean ala `@RibbonClient`.

**Comment by aivans** [comment]
Sounds good

**Comment by codependent** [comment]
@spencergibb @aivans +1 for this functionality.

**Comment by tiarebalbi** [comment]
@spencergibb @aivans +1 for this functionality.

**Comment by shall11672** [comment]
@spencergibb @aivans +1 for this functionality

**Comment by vasandharaj** [comment]
@spencergibb:

 is there any workaround available to achieve this feature ??

**Comment by spencergibb** [comment]
No. I suppose you could write your own post or error filter.

**Comment by ryanjbaxter** [comment]
So are folks thinking of having something like `@ZuulRoute` which contains all the configuration you can do via properties plus the ability to specify a custom `RibbonCommand`?  Or would we just specify the `RibbonCommand`?

**Comment by spencergibb** [comment]
I don't think it would be a custom `RibbonCommand`, but a bean that implements a fallback that we plug into the `AbstractRibbonCommand` in s-c-netflix.

**Comment by ryanjbaxter** [comment]
Something like...

```
@ZuulFallback(route="id", method="fallbackMethod")
public class MyFallback {
  public String fallbackMethod() {
    return "fallback method";
  }
}
```

**Comment by spencergibb** [comment]
The signature of the fallback looks like `org.springframework.http.client.ClientHttpResponse getFallback()` where we could plug in to `AbstractRibbonCommand`. I'm sure we could do some transformation.

**Comment by ryanjbaxter** [comment]
OK I guess it makes sense to put the burden of returning the `ClientHttpResponse` on the developer instead of trying to create the response as well.  That gives them more flexibility with formatting the response.  Let me play around with this and see if I can get something working.

**Comment by ryanjbaxter** [comment]
@spencergibb @aivans do you think it not only makes sense to have a fallback for a route but also be able to specify fallbacks that apply to certain paths for that route?  I can imagine situations where paths will correspond to different service APIs and you will most certainly want different fallbacks for different APIs.

**Comment by spencergibb** [comment]
Possibly, but I think that would complicate things considerably

**Comment by ryanjbaxter** [comment]
OK I will leave that functionality out for now.

**Comment by aivans** [comment]
@ryanjbaxter for me a route corresponds to any single path.
If you need a more specific behavior for a path, you need to declare a new route/path.

So it makes sense to keep things simple and have a fallback per route.
