### ISSUE TITLE
sslHostnameValidationEnabled property is miss-leading

### ISSUE THREAD

**Issue by qcastel** [spring-cloud/spring-cloud-netflix#2505]
The property sslHostnameValidationEnabled suggest that we are only disabling the hostname validation.

However, after investigate the code, it seems that this option is disabling the ssl validation completely.

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/httpclient/ApacheHttpClientConnectionManagerFactory.java

This property should be rename enableSslValidation.

**Comment by ryanjbaxter** [comment]
I think you have submitted other issues around this already.  I dont think changing the name is necessary.
