### ISSUE TITLE
Ribbon is still enabling hostname validation, even if sslHostnameValidationEnabled is set

### ISSUE THREAD

**Issue by qcastel** [spring-cloud/spring-cloud-netflix#2506]
I noticed that Zuul offers an option to disable ssl, which is what I wanted for now.
However, Ribbon is not offering the same kind of option and re-enable the hostname validation anyway.

This prevent zuul to be used in front of https services, with eureka. As Eureka is returning IPs instead of hostnames, I needed to disable the hostname validation.

The only way I found to really disable the hostname validation (SSL validation actually), is to override the following bean:

```
  @Bean
    @ConditionalOnMissingBean(HttpClientConnectionManager.class)
    public HttpClientConnectionManager connectionManager(
            ApacheHttpClientConnectionManagerFactory connectionManagerFactory,
            ZuulProperties zuulProperties) {
        /**
         * If we don't set this HttpClientConnectionManager bean, then Ribbon will instance it later but will enable
         * ssl validation.
         */
        ZuulProperties.Host hostProperties = zuulProperties.getHost();
        final HttpClientConnectionManager connectionManager = connectionManagerFactory
                .newConnectionManager(!zuulProperties.isSslHostnameValidationEnabled(),
                        hostProperties.getMaxTotalConnections(),
                        hostProperties.getMaxPerRouteConnections(),
                        hostProperties.getTimeToLive(), hostProperties.getTimeUnit(),
                        null);
       return connectionManager;
    }
```

(note: because of #2503, I had for the moment to do `.newConnectionManager(zuulProperties.isSslHostnameValidationEnabled(),`)

I created a sample project https://github.com/qcastel/forgerockmtlswithzuul which can be used as an example for this issue.

**Comment by ryanjbaxter** [comment]
I believe this was taken care of here https://github.com/spring-cloud/spring-cloud-commons/issues/251 right?  I just applied the fix to the 1.3.x branch as well

**Comment by qcastel** [comment]
@ryanjbaxter I don't think it will. The way I found to fix this issue in my test env is to implement a custom DefaultApacheHttpClientConnectionManagerFactory

https://github.com/qcastel/forgerockmtlswithzuul/blob/master/forgerock-zuul/src/main/java/com/forgerock/example/mtls/zuul/ssl/ZuulApacheHttpClientConnectionManagerFactory.java

**Comment by ryanjbaxter** [comment]
OK so its just the fact there is no property you can set to do this with Ribbon (not using Zuul)?

**Comment by qcastel** [comment]
yes, Ribbon is instantiating a new SSL connection and as it doesn't have this disable option, therefore, it overrides the hostname validation and re-enables it.

**Comment by ryanjbaxter** [comment]
OK I will mark this as an enhancement, we never had this functionality before.  If you feel up to it, you can submit a PR for this.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
