### ISSUE TITLE
Eureka thinks non-jvm process is up when sidecar is up and non-jvm process is down

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#251]
The sidecar properties contains:
```health-uri: http://localhost:8000/health.json```.

I would like to know what is the mechanism that I need to implement such that the sidecar reports to Eureka Server that the main process is down based on ```health-uri```.

Thanks

**Comment by spencergibb** [comment]
It follows the [spring-boot health indicators](http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-health) format.

In short `{"status":"UP"}` is up and {"status":"DOWN"} is down.

Available statuses: `DOWN, OUT_OF_SERVICE, UNKNOWN, UP`.

Health indicators can contain much more information as well, but those should get you started.

**Comment by aivans** [comment]
Ok, so we have to write a custom Health Indicator in the sidecar that checks whether the host service is up/down and use this in the Eureka InstanceStatus

**Comment by spencergibb** [comment]
@aivans no, the `health-uri` should point to a url in the non-jvm app that provides the json I mentioned.  The sidecar then takes care of that.

**Comment by aivans** [comment]
I am a bit confused.
So here is what we have:
- .Net service that implements the health endpoint (json you mentioned)
- Spring Cloud sidecar, which registers the .Net service in Eureka, takes care of heartbeats, etc

Problem:
- .Net service is stopped, but after a while, it still appears as UP in Eureka Discovery Server.

This is why we considered that the Sidecar would also use the ```health-uri``` to update the heartbeat info it sends to Eureka server.

Am I missing something?

**Comment by spencergibb** [comment]
no, thanks for the additional information.  Looks like a legitimate issue, that if the non-jvm service is down and the sidecar is up, eureka thinks the non-jvm service is up.  Does that sound like a good description of what is going on?

**Comment by aivans** [comment]
yes

**Comment by aivans** [comment]
maybe as an additional clarification for me: does Eureka Server ever use the ```healthCheckUrl``` available in the instance information? or is it just for making that url available for external monitoring tools?

**Comment by spencergibb** [comment]
@aivans I'm not positive, will need to investigate.

**Comment by aivans** [comment]
Ok, Thank you. I couldn't find any use, but I may be wrong.
