### ISSUE TITLE
[question] zuul.FormBodyWrapperFilter.pre.disable=true,can not get  POST parameters(application/x-www-form-urlencoded)

### ISSUE THREAD

**Issue by ZT5250** [spring-cloud/spring-cloud-netflix#2510]
hi,sorry to bother,but i got a problem , when i set `zuul.FormBodyWrapperFilter.pre.disable=true` in bootstrap.properties , and i can not get the parametres which content-type is application/x-www-form-urlencoded, how can i get the parameters, please help me out ,thank you very much

**Comment by ryanjbaxter** [comment]
Please provide more information including what exaclty is not working and a sample that reproduces the problem.

**Comment by ZT5250** [comment]
I set this `zuul.FormBodyWrapperFilter.pre.disable=true`  in my 
![image](https://user-images.githubusercontent.com/7928558/33639080-a4823daa-da64-11e7-8c6d-57d08b1cd61f.png)

send parameter like this 
![wx_20171206091047](https://user-images.githubusercontent.com/7928558/33639320-b1d77226-da65-11e7-97e6-f1e46c4fa0b9.png)

accept parameter like this 
![image](https://user-images.githubusercontent.com/7928558/33639245-4b01e270-da65-11e7-98b1-f2c006a2dd8e.png)
or this 
![20171206091509](https://user-images.githubusercontent.com/7928558/33639434-3664c4bc-da66-11e7-96fd-a9238573a376.PNG)
both can not get the request parameter,i don't know what's wrong with this,i just set  `zuul.FormBodyWrapperFilter.pre.disable=true`  this,because this set can optimize my program （find on the internet）, this is all the information about that, and i want to say thanks to you first

**Comment by ryanjbaxter** [comment]
Why does `zuul.FormBodyWrapperFilter.pre.disable=true` optimize your application?

**Comment by ZT5250** [comment]
because when i start pressure test on my application,and the result  not up to my expectations,then i try to  find out , what  cause this ,suddenly i fund an artile on the internet said  `zuul.FormBodyWrapperFilter.pre`   will contain synchrolock perform and this will reduce program performance
![image](http://udn.yyuap.com/data/attachment/forum/201607/21/202332eth6xmm7j62hp6wx.jpg)

**Comment by ryanjbaxter** [comment]
Can you provide the article and maybe more details on what type of performance issues you were seeing in your test?

**Comment by ZT5250** [comment]
the article is here ,but it's wrote by chinese, 
[this is the article link](https://github.com/spring-cloud/spring-cloud-netflix/issues/2510)
howerver , i think this is not the point about my question ,i just want to know why this set  `zuul.FormBodyWrapperFilter.pre.disable=true` would have effect on application/x-www-form-urlencoded params(send by post request),Or there has some other set that i should pay attention to ,thank you for your help.

**Comment by ryanjbaxter** [comment]
FormBodyWrapperFilter is responsible to encoding and forwarding on the form encoded parameters.  By disabling the filter those parameters wont be forwarded on.

**Comment by ZT5250** [comment]
okay,thank you for your help,this is means ,if i set `zuul.FormBodyWrapperFilter.pre.disable=true` ,then i should change send parameters type witch i used in my restful api instead of others ，for example ,json data

**Comment by ryanjbaxter** [comment]
yup
