### ISSUE TITLE
Edgware.RELEASE  turbine（not use mq）Can not use .yml configuration file

### ISSUE THREAD

**Issue by 13935429293** [spring-cloud/spring-cloud-netflix#2511]
when i study spring-cloud-turbine, if i use .yml configuration file, the project couldn't use hystrix-dashboard, but when i change .properties configuration file, every thing is ok.

**Comment by ryanjbaxter** [comment]
Please provide more details.  Maybe a sample project that reproduces the problem.  Is the Hystrix Dashboard not visible in the browser?

**Comment by 13935429293** [comment]
![image](https://user-images.githubusercontent.com/17083742/33640794-9efbaa52-da6d-11e7-9345-1212242680f3.png)
Already handled, I just deleted the closteNameExpression, because it throws an exception and  I found a way to solve the problem. Thank you
