### ISSUE TITLE
OpenFeign does not work with ComponentScan

### ISSUE THREAD

**Issue by fljmayer** [spring-cloud/spring-cloud-netflix#2512]
OpenFeign is a great tools, but unfortunately I cannot get it to work with a Spring Boot application that has a `@ComponentScan` on it; please run the attached project [feign-client.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1531286/feign-client.zip).

`ServiceBTest` runs fine because it uses `com.domain.Application` and is not underneath a `com.example` package. `ServiceATest` always fails with the exception below if the referenced application has the `@ComponentScan` annotation.

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.service.ServiceA' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1493)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
```

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment]
Please try `@EnableFeignClients(basePackages = "com.example")`

**Comment by fljmayer** [comment]
Thanks, that should fix it. Somehow I didn't expect a separate configuration for scanning packages.
