### ISSUE TITLE
SimpleHostRoutingFilter does not respect requestEntity

### ISSUE THREAD

**Issue by foverzar** [spring-cloud/spring-cloud-netflix#2513]
Checkout getRequestBody() methods of SimpleHostRoutingFilter and RibbonRoutingFilter:

RibbonRoutingRoutingFilter:
```
protected InputStream getRequestBody(HttpServletRequest request) {
    InputStream requestEntity = null;

    try {

        requestEntity = (InputStream) RequestContext.getCurrentContext().get(REQUEST_ENTITY_KEY);

	if (requestEntity == null) {

	    requestEntity = request.getInputStream();

        }
    }
    catch (IOException ex) {

        log.error("Error during getRequestBody", ex);

    }

    return requestEntity;

}
```

And SimpleHostRoutingFilter:

```
private InputStream getRequestBody(HttpServletRequest request) {
    InputStream requestEntity = null;

    try {
        requestEntity = request.getInputStream();
    }
    catch (IOException ex) {
		// no requestBody is ok.
    }
    return requestEntity;
}
```

So, if one tires to implement one of the examples of modifying the request body by setting requestEntity in Zuul context, it will have no effect when using SimpleHostRoutingFilter as it takes body directly from request, ignoring the value set in context. Also, SimpleHostRoutingFilter.getRequestBody is private (opposed to RibbonRoutingFilter.getRequestBody() which is protected), so one can't even override it.

**Comment by spencergibb** [comment]
How about a PR?

**Comment by holy12345** [comment]
@spencergibb @ryanjbaxter  Hello, I submitted a PR to fix this problem, looking forward to your reply, best wishes!
