### ISSUE TITLE
I have implemented circuit breaker pattern in spring mvc application, All of the functionality working fine but circuit always shows closed.

### ISSUE THREAD

**Issue by alsrk666** [spring-cloud/spring-cloud-netflix#2517]
I have implemented circuit breaker pattern in spring mvc. All of the functionality working fine but the dashboard shows circuit always closed even the fallback is invoked. 

I have added the following dependencies in my pom.xml file
`
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
            <version>1.3.1.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-javanica</artifactId>
            <version>1.4.0-RC1</version>
        </dependency>
        
        <dependency>
            <groupId>com.netflix.hystrix</groupId>
            <artifactId>hystrix-metrics-event-stream</artifactId>
            <version>1.5.12</version>
        </dependency>`

And after that I used @EnableCircuitBreaker and @HystrixCommand annotations for the implementation. Other than this I didn't configure anything. 

Can anyone please help me regarding this.... Thanks  in advance

FYI @spencergibb

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

According to https://github.com/Netflix/Hystrix/wiki#how-does-hystrix-accomplish-its-goals
> Tripping a circuit-breaker to stop all requests to a particular service for a period of time, either manually or automatically if the error percentage for the service passes a threshold.

Getting the fallback doesn't mean the circuit will open. How are you trying to open the circuit.

**Comment by alsrk666** [comment]
I have opened circuit using hystrix properties here is my code
` @HystrixCommand(commandProperties = {
            @HystrixProperty(name = "execution.timeout.enabled", value = "true"),
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "2")
    }, fallbackMethod = "methodFallback()")`
In logs I'm getting data from the methodFallback() method. Error percentage and all the other functionality working as expected. But in the dashboard the circuit is always closed...

**Comment by spencergibb** [comment]
@alsrk666 I'm still confused. Can you provide a project that recreates the problem.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
