### ISSUE TITLE
i extends ZuulFilter,and begin with the post req.how to change the post req body?

### ISSUE THREAD

**Issue by wxz1211** [spring-cloud/spring-cloud-netflix#2520]
sorry to bother,i extends ZuulFilter,and begin with the post req.
now ,i can get the request.getInputStream, but i dont want some of the data i received,not send all the data to eureka client.plz help me out ,thx.
java code example  is the best.

**Comment by ryanjbaxter** [comment]
There are some examples of post filters here https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post

**Comment by spencergibb** [comment]
Closing as answered.
