### ISSUE TITLE
Gradle + Spring Boot + Spring Cloud Edgeware.RELEASE result in dependency error

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-netflix#2521]
Hi,
not sure whether this issue fits to this project, because I guess it's a problem with the "Edgeware.RELEASE" release itself.

I'm using Gradle 4.x and Spring Boot 1.5.9.
I've included the BOM of Spring Cloud via the "mavenBom" functionality of the "Spring Dependency Management Plugin" (basically the same setup that is mentioned on the Spring Cloud homepage).
There is only one dependency declared in my script via `compile "org.springframework.boot:spring-boot-starter-web"`.

When I try to resolve this dependencies, Gradle will fail and complain about the missing dependency "org.springframework.boot:spring-boot-starter-web". For some unknown reason the Spring dependency management plugin will fail on using the mentioned Spring Boot version 1.5.9 during resolution.
As soon as I comment out the "mavenBom" line, the resolution works without a problem.

By the way: This is working properly when using the "Dalston.SR4" release.

**Comment by ryanjbaxter** [comment]
To make sure I can reproduce this properly would you mind providing a project that reproduces the problem?

**Comment by GFriedrich** [comment]
Argh ... seems this is completely my fault: The release is called "Edgware" not "Edgeware".
And trying to import a non existing bom doesn't throw an error but instead simply breaks the dependency resolution. :-/
Sorry for bothering you.

**Comment by ryanjbaxter** [comment]
NP, lots of people assume it is "Edgeware" :)
