### ISSUE TITLE
eureka console,Instance jump address not consistent

### ISSUE THREAD

**Issue by An0nymous0** [spring-cloud/spring-cloud-netflix#2524]
Spring Cloud Version:2.0 M5
Spring boot Version:Finchley.M7
-------
question:
Instance.url jump address is not [eureka.instance.ip-address] + [server.port]?
-------
![image](https://user-images.githubusercontent.com/6836030/33710190-c44fb682-db7a-11e7-8e83-37ae8727a578.png)
![image](https://user-images.githubusercontent.com/6836030/33749878-6cd5c7fc-dc0b-11e7-89b2-5350a925dc8f.png)

client config
-------
eureka.instance.ip-address=127.0.0.1 

prefer-ip-address= true 

instance-id=${eureka.instance.ip-address}:${spring.application.name}:${server.port}

**Comment by ryanjbaxter** [comment]
Seems like it is behaving the way you configured it.  You could put any ip you wanted in instance-id and that will not necessarily match the URL to the actual service.

**Comment by An0nymous0** [comment]
@ryanjbaxter StatusPageUrl IP and port acquiescence value is what I did not find in the source

**Comment by ryanjbaxter** [comment]
What do you mean you didnt find it in the source?

**Comment by An0nymous0** [comment]
@ryanjbaxter yes,I want to know his sources.

**Comment by ryanjbaxter** [comment]
Are you saying 62a8f72 caused the issue?

The code you pointed to in `EurekaInstanceConfigBean` did not change between Finchley.M4 and Finchley.M5.
https://github.com/spring-cloud/spring-cloud-netflix/blob/v2.0.0.M4/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java#L286
https://github.com/spring-cloud/spring-cloud-netflix/blob/v2.0.0.M5/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java#L286

**Comment by An0nymous0** [comment]
They changed a lot

https://github.com/spring-cloud/spring-cloud-netflix/blob/v2.0.0.M4/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java

https://github.com/spring-cloud/spring-cloud-netflix/blob/v2.0.0.M5/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java

**Comment by ryanjbaxter** [comment]
You mentioned the failure is in EurekaInstanceConfig bean not EurekaClientAutoConfiguration, hence why I was comparing the two.  You also are seem to blame 62a8f72 for the regression but I dont see anywhere in that change that alters the way the ip address is set.  Could you please be more clear about where you think the problem is because I am lost.

**Comment by An0nymous0** [comment]
@ryanjbaxter Sorry, my English is not particularly good

I only know that in the case of no code changes, just upgrade from M4 to M5 (statusPageUrl, healthCheckUrl, statusPageExplicitUrl) is not the same with the original, and my understanding is that they failed after the update

**Comment by ryanjbaxter** [comment]
No problem.  It was probably my fault as well ;)  I just sat down an looked at this. I think it was @Aloren's change that caused the functionality change you are observing.  And I think you are right in that if you set `prefer-ip-address` and set `ip-address` that it should be used consistently for the status page url and health check url.

@Aloren do you think we can add some extra checks in `DefaultManagementMetadataProvider` to check these settings and create the appropriate URLs?

**Comment by Aloren** [comment]
Sorry, I was not aware of that feature and no tests were there for it :(( 
I will change `DefaultManagementMetadataProvider` to set `ip-address` instead of hostname if `prefer-ip-address` is used.

**Comment by Aloren** [comment]
I just looked into `EurekaInstanceConfigBean` and the method I'm using for url construction:
```
	public String getHostName(boolean refresh) {
		if (refresh && !this.hostInfo.override) {
			this.ipAddress = this.hostInfo.getIpAddress();
			this.hostname = this.hostInfo.getHostname();
		}
		return this.preferIpAddress ? this.ipAddress : this.hostname;
	}
```
is already using the property `preferIpAddress`. And it is set as in previous version in `EurekaClientAutoConfiguration`:
```
instance.setPreferIpAddress(preferIpAddress);
```
I don't understand how and where it can be broken...

**Comment by An0nymous0** [comment]
@ryanjbaxter @Aloren Thank you for your helpful help
