### ISSUE TITLE
Health Status from Eureka via /admin/health

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#253]
What are the settings to get the url `/admin/health` to show a result if the `contextPath` is set to admin?  The other admin endpoints work fine.  `env`, `metrics` etc...

**Comment by dsyer** [comment]
You mean how do you configure a Eureka client to advertise its health endpoint at /admin/health? If that's the question, the answer is probably `eureka.instance.healthCheckUrlPath`.

**Comment by ccit-spence** [comment]
That was the question, I had something going on within the configuration setup with Spring Cloud Config.  Used the opportunity to completely rewrite the config setup for our system.  That fixed the problem. (Not sure what was wrong)
