### ISSUE TITLE
customer feign configuration for different method in the same FeignClient

### ISSUE THREAD

**Issue by maoyunfei** [spring-cloud/spring-cloud-netflix#2539]
Hi, I hava encounter a situation, I want to configuration different behaviors(such as timeout or retry strategy) for different methods in the same FeignClient.
```
@FeignClient(name = "user-service", url = "http://127.0.0.1:8080", configuration = MyFeignConfiguration.class)
public interface UserServiceClient {

    @RequestMapping(method = RequestMethod.GET, value = "/users")
    List<User> getAllUser();

    @RequestMapping(method = RequestMethod.GET, value = "/user/{id}")
    User  getUser(@PathVariable("id") long id);
}
----------------------------------------------------------------------------------------
@Configuration
public class MyFeignConfiguration {
    @Bean
    public Request.Options options() {
        return new Request.Options(500, 1500);
    }
}
```
For examples, If I want the method `getAllUser` timeout is 2s, and the method `getUser` timeout is 1s, but I can't achieve it in `MyFeignConfiguration`.

I know I can separated the two method into two Feignclient, and config them respectively.

But I want to know are there any other good suggestions to do it?

Thank you in advance.

**Comment by ryanjbaxter** [comment]
Not that I know of

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
