### ISSUE TITLE
how to get current request in feign interceptor

### ISSUE THREAD

**Issue by ileler** [spring-cloud/spring-cloud-netflix#2549]
```
   public class FeignRequestInterceptor  implements RequestInterceptor {

        @Override
        public void apply(feign.RequestTemplate requestTemplate) {
                System.out.println(RequestContextHolder.getRequestAttributes());
        }

    }
```
`RequestContextHolder.getRequestAttributes()` always return null,and i set `hystrix.command.default.execution.isolation.strategy: SEMAPHORE` in bootstrap.yml already.

**Comment by ryanjbaxter** [comment]
Your app is not handling a request when using Feign so it is not surprising that `RequestContextHolder.getRequestAttributes()` returns `null`.  If you are trying to modify the request Feign is making than use the `RequestTemplate` object.

**Comment by ileler** [comment]
but,how to hand request? I want to get some information from the request, but not in feign RequestTemplate，eg，getRemotePath，forward request header.so i  want  to get HttpServletRequest from current context.What should I do

**Comment by spencergibb** [comment]
I'd suggest to not use feign for that work.

**Comment by ileler** [comment]
emmm...Demand is always changing, we can not be 100% satisfied, but at least provide a custom interface

**Comment by spencergibb** [comment]
There is a Request Interceptor interface, but no way to pass it the request, only option is thread locals

**Comment by ileler** [comment]
but @ryanjbaxter say:
>Your app is not handling a request when using Feign so it is not surprising that RequestContextHolder.getRequestAttributes() returns null. If you are trying to modify the request Feign is making than use the RequestTemplate object.

i can't use `ReqiestContextHolder` do this,So I want you to provide the entrance

**Comment by ryanjbaxter** [comment]
@ileler Feign is used for making requests to other services not receiving and handling requests.  It is similar to using something like a `RestTemplate`.

**Comment by ileler** [comment]
I simply ask you, if I want to forward request header how do I handle?

**Comment by ryanjbaxter** [comment]
Using `RequestTemplate.header` you can add a header to a request made by Feign.

**Comment by ileler** [comment]
i know,,but i wan't get header info from my `HttpServletRequest`..then set in `RequestTemplate`

**Comment by spencergibb** [comment]
It's not a problem with feign. You don't have a request to use. Please reopen if you can provide a project that replicates the problem and you think there is a bug.
