### ISSUE TITLE
Modifying request body in Zuul filter not working

### ISSUE THREAD

**Issue by dakon1987** [spring-cloud/spring-cloud-netflix#2556]
Spring-Boot version: 1.5.9.RELEASE
Spring-cloud version: Edgware.RELEASE

In my app I am using netflix zuul to route a request from a microservice (gateway) to another. The requests are being routed fine but I also want to introduce some parameters in the request body before it is routed to the appropriate microservice. For this I am using Zuul pre filter like this.

```Java
public class SimpleFilter extends ZuulFilter {

    private static Logger log = LoggerFactory.getLogger(SimpleFilter.class);

    @Override
    public String filterType() {
        return "pre";
    }

    @Override
    public int filterOrder() {
        return 1;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() {

        try {
            RequestContext context = RequestContext.getCurrentContext();

            InputStream in = (InputStream) context.get("requestEntity");
            if (in == null) {
                in = context.getRequest().getInputStream();
            }

            String body = StreamUtils.copyToString(in, Charset.forName("UTF-8"));
            body = body.toUpperCase();
            context.set("requestEntity", new ByteArrayInputStream(body.getBytes("UTF-8")));

        } catch (IOException e) {
            log.error(e.getMessage(), e);
        }

        return null;
    }
} 
```

I've also tried to replace context.set with context.put like this:
```Java 
context.put("requestEntity", new ByteArrayInputStream(body.getBytes("UTF-8")));
```
but the routed request is not working anyway

Any suggestions is appreciated
Thanks!

**Comment by ryanjbaxter** [comment]
Can you elaborate on what is "not working"?

**Comment by dakon1987** [comment]
For now I am just trying to change the body to upper case but the microservice to which this request is routed doesn't receive the modified body (upper case). Instead it receives the original one. 

Thanks!

**Comment by ryanjbaxter** [comment]
It is hard for me to tell what is wrong just from that code.  This filter does the same thing
https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/UppercaseRequestEntityFilter.java

I ran the app using Edgware.RELEASe and it worked as expected.

**Comment by spencergibb** [comment]
Check the order

**Comment by dakon1987** [comment]
This is the project demo, for you to download
https://github.com/dakon1987/spring-zuul

It contains
- api-gateway -> zuul 
	filter:
	- UppercaseRequestEntityFilter -> this works only for service-one and gets the json values and converts them in uppercase
	- AddParameterRequestEntityFilter -> this is only for service-two, adds the field "createdBy" and sets it to "paperino"
- service-one -> returns the received json
- service-two -> returns the received json

When I log the information on the api-gateway, they seem to be fine, but the services receive the old information, without any modification


Those are the requests to test the project:
- ```curl -d '{ "firstname": "pippo", "lastname": "pluto" }' -H "Content-Type: application/json" -X POST http://localhost:8080/service-one/api/customer```
- ```curl -d '{ "firstname": "pippo", "lastname": "pluto" }' -H "Content-Type: application/json" -X POST http://localhost:8080/service-two/api/customer```

Thanks!

**Comment by spencergibb** [comment]
What debugging have you done?

**Comment by dakon1987** [comment]
I started my projects.

1- I sent the first call
```
curl -d '{ "firstname": "pippo", "lastname": "pluto" }' -H "Content-Type: application/json" -X POST http://localhost:8080/service-one/api/customer
```

The service response
```
{"firstname":"pippo","lastname":"pluto"}
```

The expected answer
```
{"firstname":"PIPPO","lastname":"PLUTO"}
```

Because the "UppercaseRequestEntityFilter" filter modifies the request. The values are converted to uppercase.

What's wrong?


2- I sent the Second call
```
curl -d '{ "firstname": "pippo", "lastname": "pluto" }' -H "Content-Type: application/json" -X POST http://localhost:8080/service-two/api/customer
```

The service response
```
{"firstname":"pippo","lastname":"pluto","createdBy":null}
```

The expected answer
```
{"firstname":"pippo","lastname":"pluto","createdBy":"paperino"}
```

Because the "AddParameterRequestEntityFilter" filter add a field ("createdBy") to the request with the value "paperino".

What's wrong?

Thanks!

**Comment by spencergibb** [comment]
Have you stepped through a debugger?

**Comment by dakon1987** [comment]
Now is working.

The project demo: https://github.com/dakon1987/spring-zuul

Thanks!

**Comment by Cool007dude** [comment]
@spencergibb  i also downloaded  your project  and ran it, but it is not giving request body in UPPER case, i am getting the same request body which i am sending for postman. 
so what should i do?

**Comment by Cool007dude** [comment]
@dakon1987  is your issue resolved? because  but it is not giving request body in UPPER case, i am getting the same request body which i am sending for postman

**Comment by weblogichub** [comment]
same problem.
