### ISSUE TITLE
ribbon retry problem

### ISSUE THREAD

**Issue by geniuslg** [spring-cloud/spring-cloud-netflix#2558]
Ribbon retry multiple times, I want to get the exception message corresponding to each failed retry.
But I did not find out how to get it. Can you help me?

**Comment by spencergibb** [comment]
What have you tried? Where have you looked? What does your code look like? What versions are you using?

**Comment by geniuslg** [comment]
@spencergibb 
Thank you for your prompt reply,I elaborate next
I use the version is `Edgware.RELEASE`
My application code is 
```
    @Bean
    @LoadBalanced
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }
```
```
@RestController
public class RibbonController {

    @Autowired
    private RestTemplate restTemplate;

    @HystrixCommand(
        fallbackMethod = "hystrixFallback",
        commandProperties = {@HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds",value = "10000")}
    )
    @RequestMapping(value = "/ribbon-a")
    public String ribbonA() {
        return this.restTemplate.getForObject("http://user/ribbon-a", String.class);
    }

    private String hystrixFallback(Throwable throwable) {
        return throwable.getMessage();
    }
}
```

```
user.ribbon.MaxAutoRetries=3
user.ribbon.listOfServers=localhost:8082
user.ribbon.eureka.enable=false
```
Through the parameters you can see I configure the number of failed retries is 2，I can get the last failure information via `hystrix` ,But I can not get the failure information every time (for example, the first time and the second time)

Look forward to your reply, thanks again.

**Comment by holy12345** [comment]
Hi @spencergibb  @geniuslg 
We know that ribbon retries use `spring-retry` , and I want to get information for every retry process (For example, failure information).At the moment we do not seem to support it, for the moment we just use hystrix to get the final error message.I think we can use the `spring-retry` listener mechanism to complete this request.I submitted this PR before to improve this function, the specific information is #293 .
I hope you can refer to the next, if you think this PR have a problem please correct me, very grateful. Each time your reply is my greatest encouragement, best wishes
