### ISSUE TITLE
Support for websockets (stomp) in Zuul proxy

### ISSUE THREAD

**Issue by hohwille** [spring-cloud/spring-cloud-netflix#256]
compared to apache mod_proxy and mod_proxy_wstunnel the spring-cloud-netflix with zuul does not seem to support websockets. Do you plan to support websocket forwarding as well? Would be very helpful to use this cool solution widely.

**Comment by spencergibb** [comment]
closed, duplicate of #163

**Comment by ExtremeYu** [comment]
zuul starter 1.3.0 release stil not support websocke yet￣へ￣!!!

**Comment by spencergibb** [comment]
zuul 1 will never support websockets.

**Comment by Boonearbear** [comment]
> zuul 1将永远不支持websockets。

spring could zuul how to supper .mr.spencergibb

**Comment by spencergibb** [comment]
No it will not
