### ISSUE TITLE
use requestContext.addZuulRequestHeader to set chinese value, then get the header is messy code 

### ISSUE THREAD

**Issue by fangzi0813** [spring-cloud/spring-cloud-netflix#2573]
ctx.addZuulRequestHeader("userName",claims.get("userName").toString());

userName is chinese

@RequestMapping(value = "/count", method = { RequestMethod.GET, RequestMethod.POST })
	public RSResult count(@RequestHeader("userName") String name, @RequestBody AdminPo cond) {
//name is messy code;
}
how can i resolve it?

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header

Maybe use base64 encoding?

**Comment by fangzi0813** [comment]
@spencergibb thank you ,I have resolve it according to your guidance!
