### ISSUE TITLE
logging filtering 

### ISSUE THREAD

**Issue by JackLehman** [spring-cloud/spring-cloud-netflix#2577]
In application.yml of my spring-boot application, I have the following code:

    logging:
      file: test.log
      pattern:
        file: "%d %-5level [%thread] %logger : %msg%n"

I would write something like

     logging:
       level:
        org.hibernate: *

I would to filter and gather all log messages of all levels (ERROR, DEBUG, INFO, etc) ifrom only one specific package (org.hibernate) in "test.log". It is possible?

**Comment by spencergibb** [comment]
You should ask in the spring boot gitter
