### ISSUE TITLE
Hint in documentation how manual feign client can use spring mvc annotations

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-netflix#2584]
Just like in #1834 a third party provider returns a dynamic url to us that we have to call using a Feign client. This client needs to be described using spring mvc annotations (shared with the provider part, actually [spring-cloud-cloudfoundry-service-broker](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/blob/420f903e897af71cf7f6ec2d14478e8ef9c0a3ad/spring-cloud-open-service-broker/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L76-L85))

 Following, the [documentation](https://github.com/spring-cloud/spring-cloud-netflix/blob/085935071558668a77f4c625454de6f90fb72be3/docs/src/main/asciidoc/spring-cloud-netflix.adoc#creating-feign-clients-manually), I have built the client with the Feign.Builder.

However, both documentation and some samples such as https://github.com/ryanjbaxter/manual-feign-demo/blob/f211837799ffa908d0bf660843dba10a6ec5db41/src/main/java/com/example/FooClient.java#L23 imply that this approach requires using native feign annotations and not springmvc annotations.

It took me some time before I found out that I could reuse some of the FeignClientFactoryBean logic to preserve springMVC annotation support

https://github.com/spring-cloud/spring-cloud-netflix/blob/64ad2ba20c1fc2b5556cb94386fecd0f4f65a816/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientFactoryBean.java#L93

I would suggest hinting in documentation users about getting inspiration FeignClientFactoryBean in the "7.3 Creating Feign Clients Manually" section.

If this can help other users, here is the resulting code in my project along with associated end to end integration test:
https://github.com/orange-cloudfoundry/cf-ops-automation-broker/blob/af2609b5fad79138b1bfcc2e40fe50ad7f8e2a27/cf-ops-automation-broker-core/src/main/java/com/orange/oss/cloudfoundry/broker/opsautomation/ondemandbroker/osbclient/OsbClientFactory.java
https://github.com/orange-cloudfoundry/cf-ops-automation-broker/blob/af2609b5fad79138b1bfcc2e40fe50ad7f8e2a27/cf-ops-automation-cassandra-broker/src/test/java/com/orange/oss/cloudfoundry/broker/opsautomation/ondemandbroker/osbclient/OsbClientTestApplicationTest.java#L43-L48

ps: also cross-referencing related issues #1458 and #990 as to help discovery.

**Comment by ryanjbaxter** [comment]
@gberche-orange would you like to submit a PR?

**Comment by gberche-orange** [comment]
@ryanjbaxter sure will do, thanks.
