### ISSUE TITLE
Ribbon: `java.net.UnknownHostException` should be considered as connection failure error

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2586]
My feeling is a `UnknownHostException` should be treated as a connection failure (no connection occurred after all...).

This could be handled by adding `java.net.UnknownHostException` to the list of _connectionRelated_ exceptions in `RequestSpecificRetryHandler`.

**Comment by holy12345** [comment]
Hi @brenuart 
My understanding spring cloud retry mechanism is the use of `spring-retry` completed `RequestSpecificRetryHandler`  this class will be used in retry?

**Comment by brenuart** [comment]
SpringRetry is opt-in and not suitable for those using Netflix's legacy `RestClient` (retry is then handled by Ribbon itself).

**Comment by holy12345** [comment]
@brenuart 
Thank you for your reply, I just read the source code. I think what you mean is that you want to make the following changes:
In the `RequestSpecificRetryHandler ` class
```
  protected List<Class<? extends Throwable>> connectionRelated = 
            Lists.<Class<? extends Throwable>>newArrayList(SocketException.class, UnknownHostException.class);
```
This is right?
In addition, I would like to say `RequestSpecificRetryHandler ` is a `ribbon ` project, if we need to add we should submit PR in `Netflix/Ribbon` ?

**Comment by spencergibb** [comment]
PR welcome @brenuart. Since we're not focusing on RestClient much

**Comment by brenuart** [comment]
@spencergibb I'll prepare the PR. Should we understand the _RestClient approach_ is deprecated and the new "official" setup is HttpClient + SpringRetry?

**Comment by spencergibb** [comment]
Those are the defaults now.

**Comment by spencergibb** [comment]
`RibbonClient` has been deprecated by Netflix since we started integration

**Comment by brenuart** [comment]
@spencergibb No idea why some checks failed - the "unknown classes" issue does not seem to be related at all to my changes...
Anyway, could you please have a look at my PR comments?

**Comment by spencergibb** [comment]
I'm off this week and next, so I will later, or maybe someone else will review prior

**Comment by brenuart** [comment]
Happy New Year then… and see ya next year ;-)

**Comment by spencergibb** [comment]
Closing in favor of #2614
