### ISSUE TITLE
Zuul simple routing whether to supplement the fallback feature

### ISSUE THREAD

**Issue by holy12345** [spring-cloud/spring-cloud-netflix#2589]
Hi @spencergibb @ryanjbaxter 

I know that zuul integration eureka default support hystrix function. When the route fails, we can get the reason of the failure by `FallbackProvider` , at the same time allow users to customize the return information

But zuul is routed through `SimpleHostRoutingFilter ` when we do not integrate eureka. `FallbackProvider ` is not provided in this case.

Finally, I would like to say：
whether or not zuul integrates with eureka, should we all provide `FallbackProvider ` feature?

If you think I made sense, I'm willing to submit PR. look forward to your reply, thanks again : )

**Comment by spencergibb** [comment]
No. Because the integration is actually with ribbon which can be configured without eureka using static URLs

**Comment by holy12345** [comment]
@spencergibb 
Thank you for your reply, I think I still do not quite understand.
When we route static URLs, I know that we are using `SimpleHostRoutingFilter ` instead of `RibbonRoutingFilter`. (Because the conditions to determine whether `RibbonRoutingFilter ` is executed `ctx.get(SERVICE_ID_KEY) != null` ) Processing failed in `SimpleHostRoutingFilter ` is returned as a `ZuulRuntimeException` . I did not see any logic related to `FallbackProvider ` in `SimpleHostRoutingFilter`.

Finally, thank you again for your reply to my question during the holidays

**Comment by spencergibb** [comment]
You would go thru ribbon routing filter using static configuration server list rather than eureka server list

**Comment by holy12345** [comment]
@spencergibb 

Thank you very much, I think I got it. Like you said when using the ribbon is the default integrated `FallbackProvider` . But I would like to ask another question is why we do not provide `FallbackProvider ` features when using `SimpleHostRoutingFilter` ?

**Comment by spencergibb** [comment]
Because the fallback mechanism is part of Hystrix which is not part of simple host routing filter

**Comment by holy12345** [comment]
@spencergibb 
I try to understand what you mean:
Zuul is default integrated hystrix and provides the fallback mechanism when using ribbons. When we do a simple host routing we do not need to provide a fallback mechanism (get the error directly back to the user will be better)
I understand this right? :)
