### ISSUE TITLE
Global RabbitAdmin picks up Queues and Exchanges intended for hystrix

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#259]
See also https://github.com/spring-cloud/spring-cloud-bus/issues/14

**Comment by scottfrederick** [comment]
I've tested this with my configuration and it works as expected. 

With this configuration, the Hystrix AMQP exchange and queue are bound to the `ConnectionFactory` returned from the `@HystrixConnectionFactory`-annotated method. 
~~~
  @Bean
  @Primary
  public ConnectionFactory rabbitConnectionFactory() {
    // create a connectionFactory
    return connectionFactory;
  }

  @Bean
  @HystrixConnectionFactory
  public ConnectionFactory hystrixConnectionFactory() {
    // create a different connectionFactory
    return connectionFactory;
  }
~~~

This still results in a `spring.cloud.bus` exchange and anonymous queue being created on the `@Primary`-annotated `ConnectionFactory`. This appears to be a side-effect of using Hystrix AMQP, as the app I'm using doesn't explicitly use Spring Cloud Bus. 

Providing a second `@Bean` method annotated with `@BusConnectionFactory` that returns the same `ConnectionFactory` as the `@HystrixConnectionFactory` will cause the `spring.cloud.bus` exchange and queue to be created on the Hystrix `ConnectionFactory`. 

Alternatively, the `spring.cloud.bus.amqp.enabled` property can be set to `false` to prevent the `spring.cloud.bus` exchange and queue from being created.
