### ISSUE TITLE
Bug report  com.netflix.loadbalancer.AbstractServerPredicate

### ISSUE THREAD

**Issue by wangfuguo** [spring-cloud/spring-cloud-netflix#2590]
public Optional<Server> chooseRoundRobinAfterFiltering(List<Server> servers, Object loadBalancerKey){
        List<Server> eligible = getEligibleServers(servers, loadBalancerKey);
        if (eligible.size() == 0) {
            return Optional.absent();
        }
        return Optional.of(eligible.get(nextIndex.getAndIncrement() % eligible.size()));
    }

when nextIndex beyond the range of integers,  the method will throw a ArrayIndexOutOfBoundsException. eligible.get(-1).

**Comment by holy12345** [comment]
Hi @wangfuguo 
I think what you said makes sense, we can use `math.abs ((nextIndex.getAndIncrement())` to avoid this situation.
But the `AbstractServerPredicate ` class is in the `Netflix/ribbon` project, is it better to submit this issues to `Netflix/ribbon` ?

**Comment by wangfuguo** [comment]
Hi@holy12345
Thanks. The new version of Netflix/ribbon has solved the problem.

**Comment by wangfuguo** [comment]
Hi@holy12345 
Thanks. The new version of Netflix/ribbon has solved the problem.

**Comment by wangfuguo** [comment]
Hi @holy12345 
Thanks. The new version of Netflix/ribbon has solved the problem.
