### ISSUE TITLE
Ribbon: make `@ConditionalOnRibbonAndEurekaEnabled` public

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2594]
It would be nice if `@org.springframework.cloud.netflix.ribbon.eureka.RibbonEurekaAutoConfiguration.ConditionalOnRibbonAndEurekaEnabled` was made _public_ so users could also rely on the same exact condition when building their own platform.

**Comment by ryanjbaxter** [comment]
What are you doing that you need this condition?

**Comment by brenuart** [comment]
We need to setup additional `@RibbonClients` configuration for our clients. The exact configuration depends on whether Eureka is used or not. We are currently using `@ConditionalOnProperty` guards with basically the same conditions as the one expressed by your `@ConditionalOnRibbonAndEurekaEnabled`. Instead of duplicating the same logic - with the risk it changes over time - we have the impression it would be safer to use "yours"...

**Comment by ryanjbaxter** [comment]
Seems reasonable.  Want to submit a PR?

**Comment by holy12345** [comment]
Modify like this?
```
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnRibbonAndEurekaEnabledCondition.class)
public @interface ConditionalOnRibbonAndEurekaEnabled {
	
}
```

**Comment by igorKryvenko** [comment]
See my [PR#2611](https://github.com/spring-cloud/spring-cloud-netflix/pull/2611)
