### ISSUE TITLE
Access spring actuator endpoints of backend services through zuul.

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2597]
Question

I am trying to access backend services' spring actuator endpoints through zuul, here is an explanation about how I do this:

1. I don't use `zuul routes` for routing, instead, I am depending on the host itself for routing to a backend service. For example if I have 2 backend services, we can have `zuul.routes.service1.url=service1_url` and `zuul.routes.service2.url=service2_url`, so requests for service1 would be like: `zuul-endpoint/service1/{}`.

I am not following this, instead, I have 2 route53s both are pointing to zuul, and zuul routes based on these host names. For example, I have a route53 for service1: `zuul-service1.com` points to `zuul-endpoint.com`, same for service2. And when zuul receives a request like `zuul-service1.com/api/user/....`, it maps `zuul-service1.com` (the route53) to the backend service's url. etc.

And I have to add the actuator endpoints to `zuul.ignored-patterns`, so that when I want to hit the `/info`, or `/health` endpoints for zuul itself, these requests aren't routed to a backend service, and rather mapped to a spring actuator endpoint.

This raises a problem, when I hit `zuul-service1.com/info`, trying to get the `/info` of service1, zuul will just send this request to zuul's actuator `/info` endpoint (because it will be matched to an `ignored-pattern`.

Any idea how to do this? (I am thinking that extending the `SimpleRouteLocator` could be the solution, but this would make me change the entire implementation of routing through zuul + I believe sticking to filter-based features is better than extending/implementing something like `SimpleRouteLocator`)

Thank you very much in advance!

**Comment by ryanjbaxter** [comment]
Maybe you could set `management.context-path` in the Zuul app and set `zuul.ignore-patterns` to that context path so you can hit all the Zuul actuator points while still forwarding on requests to the service actuator endpoints.

**Comment by spencergibb** [comment]
Or the management context port

**Comment by mirak94** [comment]
Thank you very much for your response!
Going to try this out and close/follow up if needed.

**Comment by spencergibb** [comment]
Closing as answered.
