### ISSUE TITLE
Spring Cloud FeignClient bean is registered incorrectly as REST controller

### ISSUE THREAD

**Issue by LukasSmrcka** [spring-cloud/spring-cloud-netflix#2599]
Hi,
I am currently on spring platform version "Brussels-SR6" and springcloud version Edgware.RELEASE" and I have found following issue. 
I have an interface annotated as @FeignClient that inherits from another interface that is REST controller interface from "server" microservice. 
When this REST controller interface uses class level annotation RequestMapping for some common segment of url path then spring based microservice that has available this interface as dependency to allow implementation of FeignClients starts to behave wrong way. It wrongly registers all the path mappings from this interface as it would be a RestController (it is visible in log in mappings). As a secondary effect when I create FeignClient interface implementation to override dynamically generated FeignClient beans (I use it to create stubs for automated tests) then spring tries to register the mapping path mapping one more time (also for the mock bean). The result is that spring fails to start because of ambiguous mapping.

As a workaround it is possible to use RequestMapping annotations only on method level.  Then I have some duplicates in path but it does not cause the false request mapping registration.

Best regards,
Lukas

**Comment by spencergibb** [comment]
This is a documented limitation

**Comment by LukasSmrcka** [comment]
Ah, ok... Haven't noticed that. Thanks
