### ISSUE TITLE
Zuul not passing all headers

### ISSUE THREAD

**Issue by larry13767** [spring-cloud/spring-cloud-netflix#260]
We discovered this yesterday quite by accident.  A customer sent to Authorization headers (one with Basic xxx and one with a Bearer xxx.  The Basic auth one was intended for another destination.  They had been doing this for months and the system worked (funny that).

However, we put in a zuul proxy server to replace a lot for he HAProxy manipulations that were happening and as well to hold some custom filters we were writing.
So suddenly none of the OAuth2 authorization worked for them any more.
We tracked the problem down to the zuul proxy removing the second Authorization header (the one with the bearer token).

I managed to follow the processing into the RibbonRouting filter and saw the source of the issue
In run() it calls MultiValueMap<String, String> headers = this.helper.buildZuulRequestHeaders(request); which copies the headers into a multi map

Inside the buildZuulRequestHeaders the logo is such that even though it is a multi map (key followed by a sequence of values), it only gets the first value of each header.

Since this was a high priority item I checkout out a local copy and made the change so that it adds all the values into the multi-map for each key.

While the example I had was odd, there are certainly other more valid instances where multiple header with the same name can occur.  This code is the same in both 1.0.0 RC3 and the 1.0.0 release.

**Comment by spencergibb** [comment]
@larry13767 thanks for the report!
