### ISSUE TITLE
Spring-boot-actuator TraceRepository getting called twice

### ISSUE THREAD

**Issue by tcawley** [spring-cloud/spring-cloud-netflix#2601]
Hi,

I have implemented a [TraceRepository](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/TraceRepository.java) that logs request/response info for every invoked endpoint in my service.  It works great with the default [WebRequestTraceFilter](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/trace/WebRequestTraceFilter.java).  I like that it filters out sensitive headers, too, by default, such as `authorization` so that user tokens don't get logged.

A problem arises when I make use of zuul to proxy to other microservices in my infrastructure whereby zuul's [TraceProxyRequestHelper](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/TraceProxyRequestHelper.java) discovers and _also_ logs to my TraceRepository, but contains all the headers of the request, including the sensitive `authorization` token.   I'd like to disable zuul's `TraceProxyRequestHelper` so I'm not getting double entries for proxied requests, but it doesn't look like there's a way to disable it nor configure it to be able to include/exclude certain headers, like you can with `WebRequestTraceFilter`.

Would you be open to a PR, that, at the very minimum would allow a property to disable `TraceProxyRequestHelper`, and maybe more tenaciously does something akin to the more configurable `WebRequestTraceFilter`?

To enable/disable, what do you think about a property like: `zuul.trace-request-enabled`?  Enabled by default or if property is missing.

**Comment by ryanjbaxter** [comment]
I think we can add a property to disable it.  However it is an instance of `ProxyRequestHelper`, so maybe the property should be `zuul.proxy-request-helper.enabled`.  Enabled by default or if property missing.

**Comment by tcawley** [comment]
Hi Ryan,

In looking through `ZuulProxyAutoConfiguration`, other beans require an instance of `ProxyRequestHelper`.  The change I'm proposing would still require an instantiation of `ProxyRequestHelper`, just not the derived `TraceProxyRequestHelper`.  Therefore, I think `zuul.proxy-request-helper.enabled` may be misleading.  Maybe `zuul.trace-proxy-request-helper.enabled`?

**Comment by ryanjbaxter** [comment]
OK sure

**Comment by tcawley** [comment]
#2605

**Comment by spencergibb** [comment]
@tcawley can you explain why you think this is an issue with our code?

**Comment by tcawley** [comment]
I was able to override the bean with your suggestion:

```
@Bean
public ProxyRequestHelper proxyRequestHelper() {
   return new ProxyRequestHelper();
}
```

Thanks heaps!
