### ISSUE TITLE
CloudEurekaClient#onCacheRefreshed breaks Netflix's legacy event mechanism

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2603]
`CloudEurekaClient` overrides the method `onCacheRefreshed` to publish the SpringCloud `HeartBeat` event through the application context. 

Unfortunately, the method does not delegate to the original implementation and as such breaks the legacy _listener_ mechanism provided by the vanilla DiscoveryClient - at least for the Netflix `CacheRefreshedEvent` event.

Would it be possible to call `super.onCacheRefreshed()` to restore the original behaviour for those who rely on it ?

**Comment by ryanjbaxter** [comment]
I dont see why not, want to submit a PR?
