### ISSUE TITLE
Filters execution times logging through zuul

### ISSUE THREAD

**Issue by mirak94** [spring-cloud/spring-cloud-netflix#2607]
I wanted to log for each request the `executedFilters` key saved in `RequestContext`.
I can see that whenever a filter executes this line appends the time to the `executedFilters` key through this line of code:
`ctx.addFilterExecutionSummary(filterName, ExecutionStatus.SUCCESS.name(), execTime);`

So may be something like just before destroying the request context for each request? (can't do within a filter because I will need the execution time of this filter itself).

Any help is appreciated!

**Comment by ryanjbaxter** [comment]
Maybe could do something in the controller that handles the request.  Or maybe in a post filter.  Not really sure though would need to investigate that.

**Comment by mirak94** [comment]
@ryanjbaxter 
Thank you very much for responding!

I am not sure what you meant by `the controller that handles the request`, if this means a `@RestController`: I don't have any controllers in zuul currently.

**Comment by holy12345** [comment]
@mirak94 
Hello, I may not fully understand your meaning (Forgive me English is not good.) Trouble you can say more in detail? 
`So may be something like just before destroying the request context for each request?`  What does this sentence mean?
Look forward to your reply, thanks again. best wishes

**Comment by ryanjbaxter** [comment]
Sorry I meant in `ZuulController`

**Comment by jadetang** [comment]
you can have an implementation of `com.netflix.zuul.monitoring.TracerFactory` in Spring Context which will replace  the default dummy one. Before every running of each filter, the TracerFactory will be asked to generate a `Trace`. So you can have your own trace as well when the `stopAndLog` is called, it is the time for you to log the running time of this filter. 
`public ZuulFilterResult runFilter() {
        ZuulFilterResult zr = new ZuulFilterResult();
        if (!isFilterDisabled()) {
            if (shouldFilter()) {
                Tracer t = TracerFactory.instance().startMicroTracer("ZUUL::" + this.getClass().getSimpleName());
                try {
                    Object res = run();
                    zr = new ZuulFilterResult(res, ExecutionStatus.SUCCESS);
                } catch (Throwable e) {
                    t.setName("ZUUL::" + this.getClass().getSimpleName() + " failed");
                    zr = new ZuulFilterResult(ExecutionStatus.FAILED);
                    zr.setException(e);
                } finally {
                    t.stopAndLog();
                }
            } else {
                zr = new ZuulFilterResult(ExecutionStatus.SKIPPED);
            }
        }
        return zr;
    }`

**Comment by ryanjbaxter** [comment]
@jadetang thanks for the info.  I went back and looked at the code and it look like you are right!  @mirak94 give @jadetang's suggestion a shot, and let us know.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
