### ISSUE TITLE
how can I use the  custom RetryListener?

### ISSUE THREAD

**Issue by xjr100419** [spring-cloud/spring-cloud-netflix#2617]
in zull  dependency  spring-retry

I would to  listen the Retry, but the sources was not register any listener
RetryTemplate retryTemplate = new RetryTemplate();

**Comment by holy12345** [comment]
Hi @xjr100419 
I've already submitted PR to supplement this feature, which you can see in `spring-cloud-netflix-1.4.1.RELEASE milestone`.

**Comment by xjr100419** [comment]
@holy12345
thanks
