### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by terancet** [spring-cloud/spring-cloud-netflix#2621]
Please fix the links to the GitHub repos in the documentation [Spring cloud netflix](http://projects.spring.io/spring-cloud/spring-cloud.html#_spring_cloud_netflix)

Broken links are located in the following paragraph

> See **EurekaInstanceConfigBean** and EurekaClientConfigBean for more details of the configurable options.

**Comment by ryanjbaxter** [comment]
I clicked both links in http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html and they appeared to work.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
