### ISSUE TITLE
discoveryComposite health indicator reports UP when one of underlying indicators reports UNKNOWN

### ISSUE THREAD

**Issue by jimirocks** [spring-cloud/spring-cloud-netflix#2638]
for example, this basically happens when eureka server is unreachable:
```json
 "discoveryComposite":{  
      "description":"Composite Discovery Client",
      "status":"UP",
      "discoveryClient":{  
         "description":"Composite Discovery Client",
         "status":"UP",
         "services":[]
      },
      "eureka":{  
         "description":"Remote status from Eureka server",
         "status":"UNKNOWN",
         "applications":{}
      }
   }
```

The cause is probably usage of `OrderedHealthAggregator` which by default aggregates statuses this way. That in general makes sense, however in this particular case, I believe, the UNKNOWN status should win.

**Comment by ryanjbaxter** [comment]
So all you did to reproduce this was bring down the eureka server?

**Comment by jimirocks** [comment]
To be exact:
* turn off eurekad
* start the app which registers to eureka

In case the eurekad is brought down later (so the app had chance to register), the both checks result as UP (which is correct).

**Comment by spencergibb** [comment]
The precedence of status in a health indicator is a function of spring boot and is out of our control

**Comment by jimirocks** [comment]
@spencergibb it's not true the precedence is out of control. Namely you define the precedence in [your codebase](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClientConfiguration.java#L87). Since that `OrderedHealthAggregator` has a setter, it can be modified for your needs.

Additionally are you sure it's valid report UP when part of check is UNKNOWN? If you don't want to tweak the aggregator, the other possibility is not to use the composite.

**Comment by spencergibb** [comment]
We don't determine if unknown or up takes precedence

**Comment by spencergibb** [comment]
It has nothing to do with order

**Comment by jimirocks** [comment]
when I register
```java
@Bean
    public HealthAggregator healthAggregator() {
        final OrderedHealthAggregator aggregator = new OrderedHealthAggregator();
        aggregator.setStatusOrder(Status.DOWN, Status.OUT_OF_SERVICE, Status.UNKNOWN, Status.UP);
        return aggregator;
    }
```

The discoveryComposite indicator results to UNKNOWN. So yes the precedence in your composite indicator has something to do with order. I am happy with my fix, I reported this issue cause I thing the default behaviour is not very correct.

If you tell me it's correct and the reason why, that's fine. But you are telling me that you can't change it, which is simply not true ;-)

Regards

**Comment by spencergibb** [comment]
Ok, sorry I was wrong there. I don't think changing boot defaults (which can be set by properties I believe) is there right thing to do. The user can do it, but it would affect more than this indicator.

**Comment by spencergibb** [comment]
Eureka was built such that if it wasn't available, the service still should be. There should also be more than one eureka the service is connected to
