### ISSUE TITLE
Zuul/Ribbon causes UrlEncoded Parameter

### ISSUE THREAD

**Issue by PatrikSteuer** [spring-cloud/spring-cloud-netflix#2641]
We are using spring.boot 1.5.9 and Spring Dalston.SR5. While using zuul as a proxy we face the issue that url parameter get encoded by the proxy. 
As it seems 
`RibbonLoadBalancingHttpClient.execute` 
calls `RibbonApacheHttpRequest.toRequest` 
calls `RequestBuilder.build` 
calls `URIBuilder.build` on the parameters, so they get encoded

Is it intedend to be this way and do you have an idea on how to prevent this?

**Comment by ryanjbaxter** [comment]
Are you saying the parameters are double encoded?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by PatrikSteuer** [comment]
The problem was that the backend server did not expect an encoded value, but zuul, did do an automated encoding, since it uses the underlying apache libaries. 

We were able to explain to the manufacturer of the backend server that it makes sense to stick to the http standards and accept parameters in an encoded fashion. 

=> Thanks for closing this issue!
