### ISSUE TITLE
load balancer does not have available server for client zuul: com.netflix.zuul.exception.zuulexception: forwarding error

### ISSUE THREAD

**Issue by ranjan-das** [spring-cloud/spring-cloud-netflix#2642]
My gateway service is not working with Eureka server, and i am getting the forwarding exception  from zuul. I have attached my sample project,
[project.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/1628322/project.zip)
 where it is reproduced. Could you please help me on this?

**Comment by cleversonledur** [comment]
I am facing the same issue. Zuul + Eureka produces the error "load balancer does not have available server for client zuul". If I point directly to the micro-service (using url), it works. I tested changing spring cloud versions but the problem remains.

**Comment by ryanjbaxter** [comment]
closing in favor of #2530
