### ISSUE TITLE
mutual authentication between zuul and microservice with certificates

### ISSUE THREAD

**Issue by abhishekamte** [spring-cloud/spring-cloud-netflix#2643]
I have a zuul proxy acting as an edge server and my microservices are non jvm applications and I dont use ribbon or eureka. These microservices are accessible over https only and require client certs to communicate with them. Does zuul support mutual auth with certs for downstream? If so how do i set it up on my zuul server.

**Comment by ryanjbaxter** [comment]
Sounds like you should be using Netflix Zuul not Spring Cloud Zuul.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
