### ISSUE TITLE
Missing values in calculation of Zuul Hystrix Timeouts

### ISSUE THREAD

**Issue by rphlmr** [spring-cloud/spring-cloud-netflix#2644]
After reading the merged PR #2633 I have some questions.

1/ Is it normal to not multiply Ribbon connect and read timeouts by MaxAutoRetries and MaxAutoRetriesNextServer (if they are set in configuration file) ?

Or maybe the` hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds` is for each request, independently of the number of retries ?

2/ For specific commandKey (service ?), if we have specific Ribbon connect and read timeouts, I think we are ignoring them and setting the default Ribbon properties instead.

Exemple : 
I have a service named `sample-client` and the given configuration :

**No** `hystrix.command.sample-client.execution.isolation.thread.timeoutInMilliseconds`

`sample-client.ribbon.ReadTimeout=3000` 

`sample-client.ribbon.ConnectTimeout=3000`

`ribbon.ReadTimeout=2000` 

`ribbon.ConnectTimeout=2000`

By default, the hystrix timeout for ma sample-client will be 6000ms and not 4000ms ?

**Comment by holy12345** [comment]
Hi @rphlmr 
I submitted a PR to solve your second question.
In addition, as far as I know, the `hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds` parameter represents the time of all retries.

Thanks again : )

**Comment by rphlmr** [comment]
You are welcome, thanks for your reactivity ;)
I am currently working on configurations of µ service, it take me some time to understand the relation between ribbon timeouts and hystrix tiemouts.

For my 1st question, see the code in the #2633 :  
Extract :

```
int ribbonTimeout = ribbonConnectTimeout + ribbonReadTimeout;
int hystrixTimeout;
if(commandHystrixTimeout > 0) {
	hystrixTimeout = commandHystrixTimeout;
}
else if( defaultHystrixTimeout > 0) {
	hystrixTimeout = defaultHystrixTimeout;
} else {
	hystrixTimeout = ribbonTimeout;
}
if(hystrixTimeout < ribbonTimeout) {
	LOGGER.warn("The Hystrix timeout of " + hystrixTimeout + "ms for the command " + commandKey +
			" is set lower than the combination of the Ribbon read and connect timeout, " + ribbonTimeout + "ms.");
}
```

ribbonTimeout doesn't include retries (auto and next servers) and this value is set as hystrixTimeout if no hystrixTimeout is set in an application.yml (or whatever config file).
According to this [documentation](https://cloud.spring.io/spring-cloud-netflix/multi/multi__hystrix_timeouts_and_ribbon_clients.html#_hystrix_timeouts_and_ribbon_clients), to define hystrixTimeout we should apply the formula : 
hystrixTimeout = (ribbonConnectTimeout + ribbonReadTimeout) x ribbonMaxAutoRetries x ribbonMaxAutoRetriesNextServer
What do you think about that ?

And for the case, when commandHystrixTimeout is not > 0 (not set in config file) and has specific ribbon config, we should apply : 
hystrixTimeout = (commandRibbonConnectTimeout + commandRibbonReadTimeout) x commandRibbonMaxAutoRetries x commandRibbonMaxAutoRetriesNextServer
where commandRibbon* are what we can find in config files (`sample-client.ribbon.ReadTimeout=3000`)

If no ribbon specific config exist for the command (commandRibbon*), nothing to do, hystrix take the hystrixTimeout (already in the code)

**Comment by holy12345** [comment]
Hi @rphlmr 
Yeah! Thank you for your reply, I think I understand what you mean, according to official documents, Hystrix timeout should include all retries time. so I think what you say makes sense : )

In addition, I want to discuss with you is to set the priority of the timeout,I think the logic to set the timeout is this
- If `hystrix.command.commandKey.execution.isolation.thread.timeoutInMilliseconds` is set use that timeout

- Else if `hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds` is set use that timeout

- Else if `clientName.nameSpace.ReadTimeout` and `clientName.nameSpace.ConnectTimeout` is set use that timeout(Including all retries the same and next server times)
    Note:
    If the `commndKey.nameSpace.MaxAutoRetriesNextServer`  and `commndKey.nameSpace.MaxAutoRetries` parameter does not exist we use `ribbon.MaxAutoRetries` and  `ribbon.MaxAutoRetriesNextServer` , if `ribbon.MaxAutoRetries` and `ribbon.MaxAutoRetriesNextServer` does not exist we use the default number of times

- Else if the Ribbon connect(`ribbon.ConnectTimeout`) and read timeouts(`ribbon.ReadTimeout`) are set use the combination of those(Including all retries the same and next server times)
    Note:
     if `ribbon.MaxAutoRetries` and `ribbon.MaxAutoRetriesNextServer` does not exist we use the default number of times
- Else use the default Ribbon connect and read timeouts

What do you think?

**Comment by rphlmr** [comment]
Maybe i'm pernickety :) but I want to dig deeper for the 3rd and 4th cases.

> Else if `clientName.nameSpace.ReadTimeout` and `clientName.nameSpace.ConnectTimeout` is set ...

I mean deeper becasue if there is, for exemple, only a `commndKey.nameSpace.MaxAutoRetries` set, I would like it for the calculation.

So, to help, I made a decision diagram.
With it, I hope every one can check if we are not missing a case.
I made it with draw.io, and [shared the source xml on my github](https://github.com/rphlmr/spring-cloud-netflix-contrib/tree/master/hystrix/configuration) if you want to easly modify it ;)

I hope I didn't miss something.

![hystrixtimeoutspriority](https://user-images.githubusercontent.com/20722140/34918339-47719b86-f951-11e7-97aa-927350d97820.png)

**Comment by holy12345** [comment]
@rphlmr 
Thank you very much for the diagram, I think he will help everyone who wants to know about this issue. Although it is 1 am Beijing time, but I did not drowse, I think I will fix this issue. Thanks again ：)

**Comment by rphlmr** [comment]
I have 2 other questions.

1/ I experienced a case that could be concerned by the PR, when using a feign client (that use ribbon logic for timeouts).
If I set hystrix timeout strictly equals to ribbon values (with retries etc), sometimes I come in hystrix timeout instead of feign retry exception due to few ms of thread operation.
According to the previous official documentation, it's said 

> [...]than your Hystrix timeout should be **slightly more** than three seconds

Now that we are setting hystrix timeout automatically according to ribbon values, should we not add some extra ms (maybe +100ms ?) ? 
Maybe it's possible to test that but I don't reproduce the case 100% times.

2/ In case that we use custom ribbon timeouts with a feign client, we should never fall in default hystrix timeout.
So, is it safe to disable it ? (on my config file and only in the case that i'm using ribbon for timeouts).
Or maybe, hystrix timeout is use for a mecanism somewhere else ?

@ryanjbaxter what do you think ?

**Comment by holy12345** [comment]
Hi @rphlmr 
Based on the results we discussed yesterday, I modified the PR code. I ran the test code, it was successful. I hope you review the PR code (to see if meet your requirements).
Thanks again ：）

**Comment by rphlmr** [comment]
Hi @holy12345

I didn't yet review your PR but after thinking of it again, there is a mistake in the formula of hystrix timeout calculation.

We multiply max retries but we forgot that a value of 1 means : do it once after ce 1st. So, 1 means 2.

hystrixTimeout = (commandRibbonConnectTimeout + commandRibbonReadTimeout) x (commandRibbonMaxAutoRetries + 1) x (commandRibbonMaxAutoRetriesNextServer + 1)

**Comment by holy12345** [comment]
@rphlmr 
Yes, you're right. I forgot to say, but in the code I've followed the right way
