### ISSUE TITLE
[Question]The registered Service URL always are http ?

### ISSUE THREAD

**Issue by MasterColor** [spring-cloud/spring-cloud-netflix#2647]
Question: the registered service is always http , even I made it https.
here is my configuration file
for eureka:
`server.port=8761`
`server.ssl.enabled=true`
`server.ssl.key-store=config/server.keystore`
`server.ssl.key-store-password=something`
`server.ssl.trust-store=config/resttruststore.keystore`
`server.ssl.trust-store-password=something`
`eureka.instance.hostname=localhost`
`eureka.client.registerWithEureka=false`
`eureka.client.fetchRegistry=false`
`eureka.client.serviceUrl.defaultZone=https://${eureka.instance.hostname}:${server.port}/eureka/`
`eureka.server.enableSelfPreservation=false`

for client:
`server.port=8443`
`server.ssl.enabled=true`
`server.ssl.key-store=config/server.keystore`
`server.ssl.key-store-password=something`
`server.ssl.trust-store=config/resttruststore.keystore`
`server.ssl.trust-store-password=something`
`spring.application.name=service-hi`
`eureka.client.serviceUrl.defaultZone=https://localhost:8761/eureka/`

this problem makes my zuul always failed to route the rest request.
BTW , https is a must for my project.

please help me to solve this.

**Comment by ryanjbaxter** [comment]
Read the section here in our documentation http://cloud.spring.io/spring-cloud-static/Edgware.RELEASE/single/spring-cloud.html#_registering_a_secure_application

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
