### ISSUE TITLE
eurekaAutoServiceRegistration 

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-netflix#2649]
My API Gateway keep shutting down for the below error.

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)

**Comment by spencergibb** [comment]
Can you please describe more? Versions? Did you perform some action that caused the error?

**Comment by dulimitta** [comment]
I am using Edgeware.release. Upgraded my pom dependencies to spring-cloud-starter-netflix-eureka-client, spring-cloud-starter-netflix-eureka-server and spring-cloud-starter-netflix-zuul.

My requirement is to have spring cloud setup on ECS. I am trying to register API Gateway with Eureka and use service id based routing.

**Comment by ryanjbaxter** [comment]
> Did you perform some action that caused the error?

**Comment by dulimitta** [comment]
The error has gone After removing the EnableFeignClient annotation in my API Gateway. I am stuck on other issue but we can close this thread. Thank you for your responses.
