### ISSUE TITLE
how to change zuul http client pool size 

### ISSUE THREAD

**Issue by hsj1606** [spring-cloud/spring-cloud-netflix#2650]
How to change zuul apache http client connection pool size ?

Spring Cloud version: Dalston.RELEASE

these properties not working:
ribbon.maxTotalConnections=1000
ribbon.maxPerRouteConnections=300

logging:
PoolingHttpClientConnectionManager - Connection request: [route: {}->http://127.0.0.1:8300][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 200]

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud?  How are you configuring your routes?

**Comment by hsj1606** [comment]
Spring Cloud version: Dalston.RELEASE
it works with
ribbon.MaxTotalConnections=2000
ribbon.MaxConnectionsPerHost=200

**Comment by spencergibb** [comment]
@hsj1606 that is correct, ribbon properties are care sensitive.
