### ISSUE TITLE
Ribbon client always initialize Hystrix command with default timeout values

### ISSUE THREAD

**Issue by mjeanroy** [spring-cloud/spring-cloud-netflix#2651]
Hi,

We recently upgrade spring-cloud-netfix from version 1.1.2 to 1.4.0 and we are seeing a strange behavior. The first time the Ribbon client try to execute an Hystrix command, the first call fail with a timeout. We tried to increase Hystrix and ribbon timeout values but it has no effect.

We tried to debug what really happens and we found that the the `HystrixCommandProperties` instance is always initialized with a timeout value based on default ribbon timeouts (`RibbonClientConfiguration.DEFAULT_CONNECT_TIMEOUT + RibbonClientConfiguration.DEFAULT_READ_TIMEOUT`) so our properties are completely useless here.

You can see the code here: https://github.com/spring-cloud/spring-cloud-netflix/blob/ef755f3ad3b938c2cddea0d18a3cd7e731c88a82/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/support/AbstractRibbonCommand.java#L93-L95

My question is: why the ribbon properties overrided by our configuration are not used here? Is that a bug or something that is wanted (and if so, how can I increase this timeout)?

Note that setting the `hystrix.command.default.execution.timeout.enabled` property to `false` solved the issue (logical since no `HystrixObservableTimeoutOperator` is created in this case).

**Comment by holy12345** [comment]
See PR #2645
This is a bug, I think the logic should be modified so (more information can see this PR).
I hope my answer can help you, thank you

**Comment by mjeanroy** [comment]
Hi @holy12345,
Thanks for your answer!
This PR seems to fix the problem, I'll test it once available on maven repo ;)

**Comment by mjeanroy** [comment]
Just tested with 1.4.3.BUILD-SNAPSHOT and it seems to be fixed (at least for my use case).

**Comment by ryanjbaxter** [comment]
Reopening since the PR was not merged

**Comment by mjeanroy** [comment]
Ok, let me know once a new snapshot is available, I'll be happy to test it!

**Comment by ryanjbaxter** [comment]
@mjeanroy I think #2633 probably fixed the issue you were seeing.  @holy12345 has some improvements on that fix in #2645.  Follow that PR to see how the logic evolves.
