### ISSUE TITLE
Spring Cloud on ECS

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-netflix#2653]
I deployed Spring cloud on AWS ECS. I updated EurekaInstanceConfigBean for getting the AWS EC2 information in my Eureka client. If I do not pass the nonsecure port, the client is getting registered with port 80 in Eureka.
Having the port 80 open on EC2 server, the eureka client is accessible to the API Gateway.
But if I pass my application port 8000 as the nonsecure port in EurekaInstanceConfigBean, even though the 8000 port is open, the API Gateway is failing to reach the Eureka client service.

The security settings for 80 and 8000 are same. 

Having this issue, I cannot run any other Eureka client, as it will also try to get registered on port 80, which is already occupied by the first service.

**Comment by spencergibb** [comment]
What port is the service actually running on?

**Comment by dulimitta** [comment]
It is 8000.

**Comment by spencergibb** [comment]
This doesn't sound like a eureka problem, but configuration of ECS

**Comment by dulimitta** [comment]
@Value("${server.port:8000}") 
   private int port;

	@Bean
	public EurekaInstanceConfigBean eurekaInstanceConfig(InetUtils inetUtils) {
		  EurekaInstanceConfigBean b = new EurekaInstanceConfigBean(inetUtils);
		  AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
		  b.setDataCenterInfo(info);
		  info.getMetadata().put(AmazonInfo.MetaDataKey.publicHostname.getName(), info.get(AmazonInfo.MetaDataKey.publicIpv4));
		  b.setHostname(info.get(AmazonInfo.MetaDataKey.publicHostname));
		  b.setIpAddress(info.get(AmazonInfo.MetaDataKey.publicIpv4));
		  b.setNonSecurePort(port);
		  return b;
	}

**Comment by spencergibb** [comment]
I don't understand how port 80 has to do with anything

**Comment by dulimitta** [comment]
Thanks for the quick responses.
If I comment b.setNonSecurePort(port) line alone, the service is getting registered with port 80. I can see the change in EUREKA_URL/eureka/apps. I have the same settings for 80 and 8000 port.

**Comment by spencergibb** [comment]
But how would it work on port 80if it's not actually listening it being forwarded?

**Comment by dulimitta** [comment]
Yes, the container port is 8000, but the host port is 80. I am updating my configuration to host port 8000.

**Comment by spencergibb** [comment]
If port 80 is what is visible, that is what should be registered

**Comment by dulimitta** [comment]
Thanks spencergibb. It is working!!!
