### ISSUE TITLE
Eureka with AWS ECS Fargate

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-netflix#2660]
I am deploying spring cloud application onto AWS ECS.
I updated my eureka client with overriding EurekaInstanceConfigBean as to register with IP address.
It is working well with launch type EC2 but failing with Fargate.
Here is my configuration. I can see null values in the system logs.
```
	@Bean
	public EurekaInstanceConfigBean eurekaInstanceConfig(InetUtils inetUtils) {
		  EurekaInstanceConfigBean b = new EurekaInstanceConfigBean(inetUtils);
		  AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
		  b.setDataCenterInfo(info);
		  info.getMetadata().put(AmazonInfo.MetaDataKey.publicHostname.getName(), info.get(AmazonInfo.MetaDataKey.publicIpv4));
		  System.out.println("*********************Public Host Name*******************************   " + info.get(AmazonInfo.MetaDataKey.publicHostname));
		  System.out.println("*********************Public IPV4 *******************************   " + info.get(AmazonInfo.MetaDataKey.publicIpv4));
		  System.out.println("*********************Local IPV4*******************************   " + info.get(AmazonInfo.MetaDataKey.localIpv4));
		  b.setHostname(info.get(AmazonInfo.MetaDataKey.publicHostname));
		  b.setIpAddress(info.get(AmazonInfo.MetaDataKey.publicIpv4));
		  b.setNonSecurePort(port);
		  return b;
	}
```

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment]
I'm unsure what we can do about this. `AmazonInfo` is from eureka client (not maintained here) using amazon APIs to get information. You should probably open an issue there. https://github.com/Netflix/eureka

**Comment by dulimitta** [comment]
Sure @spencergibb. Thank you. Thanks for letting me know the code format trick.

**Comment by jussiseppala** [comment]
Here is[ a small sample ](https://github.com/jussiseppala/eurekafargatesample)how you can solve this issue by using ECS Task Metadata Endpoint.

**Comment by bhanu0684** [comment]
That's because of incorrect ip address during startup by Eureka. Please follow [this ](https://medium.com/@bhanu.pratap/service-discovery-in-spring-cloud-using-netflix-eureka-in-aws-fargate-2c5c294fee5c), I have solved that using getting metadata during startup
