### ISSUE TITLE
Spring Feign client :client truststore & keystore conf

### ISSUE THREAD

**Issue by sbogadhi** [spring-cloud/spring-cloud-netflix#2663]
Not able to request https Web Service with client truststore and keystore confuguration.

Failing with the Unable to find valid certificate on requested target.

**Comment by spencergibb** [comment]
You need to configure the http client that feign is using. Which are you using?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
