### ISSUE TITLE
Ribbon cannot connect to EC2 private IP.

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-netflix#2666]
I am setting Spring cloud on AWS ECS.

I am registering eureka clients with overriding EurekaInstanceConfigBean. 
The client is reachable to APIGateway with Ribbon when I register the client with public IP.  But it is not working with private IP. If it works with private IP, I don't need to open the application ports.

I have eureka.instance.preferIpAddress=true and my EurekaInstanceConfigBean is below.

```	java
@Bean
	public EurekaInstanceConfigBean eurekaInstanceConfig(InetUtils inetUtils) {
		  EurekaInstanceConfigBean b = new EurekaInstanceConfigBean(inetUtils);
		  AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
		  b.setDataCenterInfo(info);
		  info.getMetadata().put(AmazonInfo.MetaDataKey.localHostname.getName(), info.get(AmazonInfo.MetaDataKey.localIpv4));
		  b.setHostname(info.get(AmazonInfo.MetaDataKey.localHostname));
		  b.setIpAddress(info.get(AmazonInfo.MetaDataKey.localIpv4));
		  b.setNonSecurePort(port);
		  return b;
	}

```

**Comment by spencergibb** [comment]
@dulimitta I'm unsure what to do about it. This looks almost identical to #2660 that you opened the other day. What does this mean?
> it is not working with private IP.

If gateway can't reach it via private ip, isn't that a network problem? What does ribbon have to do with any of it?

**Comment by dulimitta** [comment]
@spencergibb 

Though they seem to be similar, #2660 is about Fargate instance and #2666 is about EC2. 
My concern is if I am missing any eureka, ribbon or EurekaInstanceConfigBean configuration.

**Comment by spencergibb** [comment]
If one instance can't see the private ip of another, what configuration on spring cloud would fix that?

>  isn't that a network problem?

**Comment by dulimitta** [comment]
Before implementing the EurekaInstanceConfigBean, I was having issues connecting with public IP as well. 
EurekaInstanceConfigBean configuration helped me. 

Please close the issue if spring configuration cannot help.
