### ISSUE TITLE
Ribbon RetryableRibbonLoadBalancingHttpClient AutoRetriesNextServer is not working

### ISSUE THREAD

**Issue by MasterSlave** [spring-cloud/spring-cloud-netflix#2667]
Hi @ryanjbaxter,

We are using Egdware.SR1 release and we noticed that when you were fixing #2526, RetryableRibbonLoadBalancingHttpClient:134
```
newRequest = getSecureRequest(request, configOverride);
```
has wrong parameter, first parameter should be newRequest.

In RetryCallback.doWithRetry method, after the first attempt if it fails, according to retry policy it sets next service instance to load balanced retry context. When second iteration of doWithRetry method,  it creates newRequest variable with new serverInstance uri but after that it overrides newRequest with getSecureRequest method call. 

Could you please check it?

**Comment by ryanjbaxter** [comment]
Ugh yes you are right!

**Comment by ryanjbaxter** [comment]
@MasterSlave see the above PR
