### ISSUE TITLE
HttpClientRibbonConfiguration create disableContentCompression HttpClient

### ISSUE THREAD

**Issue by zhouze1992** [spring-cloud/spring-cloud-netflix#2668]
Preconditions:
version info:
spring-cloud-dependencies.version:Edgware.RELEASE
spring-cloud-netfilix-core:1.4.0.RELEASE
My tomcat container has gzip enabled.

Description:
When I upgrade the spring-cloud-dependencies.version D to E, in my code
` String copyToString = StreamUtils
                            .copyToString(RequestContext.getCurrentContext().getResponseDataStream(), Charset.forName("UTF-8"));`
there was an exception,I resolved to the content is a messy.

I found the HttpClient definition in the `HttpClientRibbonConfiguration class`, which uses the ApacheHttpClientFactory to generate `HttpClient.ApacheHttpClientFactory` by default executes the disableContentCompression method, causing my stream obtained in RibbonHttpClient to be uncompressed.
And I see `org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient # createDelegate`, using `HttpClientBuilder` to create HttpClient, whether the two should be unified?

**Comment by ryanjbaxter** [comment]
The `createDelegate` method is only kept there for backward compatibility at the moment.  

We had several places in spring cloud netflix where we were creating http clients of different kinds.  Each one was configured differently.  We needed to unify the creation of these clients so the various ways of making http requests behaved consistenly.  This meant creating a default http client configuration.  Yes by default compression is disabled but you can override this by creating your own bean of type `HttpClient` or providing your own instance of `ApacheHttpClientFactory`.

**Comment by zhouze1992** [comment]
Thank you for your reply. This is an effective way to solve this problem.
