### ISSUE TITLE
FeignClient: How to use Pageable?

### ISSUE THREAD

**Issue by sj853** [spring-cloud/spring-cloud-netflix#2672]
I have been depressed for a few days.
I am build  a MicroService who support Spring Data Pageable functionnality.
like this:

> @PostMapping("search")
@Override
    public Result<Page<CategoryDTO>> getList(@RequestBody CategoryDTO tDto, Pageable pageable) {
        return Result.<Page<CategoryDTO>>builder().data(service.getList(tDto, pageable)).build();
    }

so i request(POST) with body like : 

> POST /search?page=1&size=20&sort=id,desc  
{
"test":"aaa"
}

works perfect!

and now i use @FeignClient to request like this:

>  @PostMapping(value = "search")
    Result<Page<CategoryDTO>> getList(@RequestBody CategoryDTO t, Pageable pageable);

it throws exception :Method has too many Body parameters

if i request like this:

> @PostMapping(value = "page")
    Result<Page<CategoryDTO>> getList(@RequestBody CategoryDTO t,@RequestParam("pageable") Pageable pageable);

but it did not work. so  how can i use @FeignClient to do pageable request with customer body at the same time??

**Comment by spencergibb** [comment]
Duplicates #556

**Comment by teten-nugraha** [comment]
I solve this issue
[https://medium.com/backend-habit/using-pagination-on-open-feign-4fc500747b70](url)
