### ISSUE TITLE
[Edgware.SR1]Hystrix Dashboard Cannot display anything for Turbine Stream

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#2674]
I update my samples to Edgware.SR1 then I find that Hystrix Dashboard Cannot display anything for Turbine Stream.

Turbine Stream：http://localhost:8989 , When I call it, I Can get data like below:

data: {"rollingCountFallbackFailure":0,"rollingCountFallbackSuccess":0,"propertyValue_circuitBreakerRequestVolumeThreshold":"20","propertyValue_circuitBreakerForceOpen":false,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":"10000","latencyTotal_mean":0,"type":"HystrixCommand","rollingCountResponsesFromCache":0,"TypeAndName":"TypeAndName=>HystrixCommand_zuul-server.microservice-provider-user","rollingCountTimeout":0,"propertyValue_executionIsolationStrategy":"SEMAPHORE","instanceId":"zuul-server:-3102666220667402369","rollingCountFailure":0,"rollingCountExceptionsThrown":0,"latencyExecute_mean":0,"isCircuitBreakerOpen":false,"errorCount":0,"group":"RibbonCommand","rollingCountSemaphoreRejected":0,"latencyTotal":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"requestCount":0,"rollingCountCollapsedRequests":0,"rollingCountShortCircuited":0,"latencyExecute":{"0":0,"25":0,"50":0,"75":0,"90":0,"95":0,"99":0,"99.5":0,"100":0},"propertyValue_circuitBreakerSleepWindowInMilliseconds":"5000","currentConcurrentExecutionCount":0,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":"100","errorPercentage":0,"rollingCountThreadPoolRejected":0,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_requestCacheEnabled":true,"rollingCountFallbackRejection":0,"propertyValue_requestLogEnabled":true,"rollingCountSuccess":0,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":"10","InstanceKey":"InstanceKey=>zuul-server:-3102666220667402369","propertyValue_circuitBreakerErrorThresholdPercentage":"50","propertyValue_circuitBreakerForceClosed":false,"name":"zuul-server.microservice-provider-user","reportingHosts":1,"propertyValue_executionIsolationThreadPoolKeyOverride":"null","propertyValue_executionIsolationThreadTimeoutInMilliseconds":"2000"}
But When I put this URL into Hystrix Dashboard, I Will never get the graph!
hystrix-dashboard

Then I downgrade my Code to Dalston.SR4 , everything works! I think it's a Turbine Server bug of Edgware.RELEASE .

CODE IS HERE: https://gitee.com/itmuch/spring-cloud-yes . Hope you Can help me.

**Comment by ryanjbaxter** [comment]
@eacdy no reason to command on multiple issues about the same problem.  Closing in favor of #2637
