### ISSUE TITLE
[Question] Does Zuul with oAuth2 relay the Principal (as an authorization header) ?

### ISSUE THREAD

**Issue by samfrach** [spring-cloud/spring-cloud-netflix#2676]
Dear all,

what I want : I want a single entry to all my applications and a single sign on

I've spent my time googling "zuul authorization not forwarded/relayed"... then I think I understood, it talks about a request header Authorization that would arrive with the user request.. whereas I don't have any

I have spring boot applications : 
- an oAuth2 authorization server (named : AS)
- a zuul server that acts as a oAuth2 client (i.e. the user is redirected to the authorization server to login and comes back authenticated = authorization_code mode)
- a few services (ResourceServer)

When I call my few services from the zuul server using a feign client (i.e. via RestTemplate), then my resources servers receive the Authorization header .. they get the JWT and the life goes on...
But through a zuul route, the authorization is always empty whereas I have a principal in the zuul server .. (I have added a "sensitiveHeaders" to all my routes.. )

**Question** : I can add a Zuul Pre-filter to add this authorization header from the principal. But isn't supposed to be supported by Zuul ?

thanks a lot for your answers

**Comment by ryanjbaxter** [comment]
Is this what you need? https://cloud.spring.io/spring-cloud-security/single/spring-cloud-security.html#_client_token_relay_in_zuul_proxy

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
