### ISSUE TITLE
[Question] Zuul+oAuth2 and HttpSession ?

### ISSUE THREAD

**Issue by samfrach** [spring-cloud/spring-cloud-netflix#2678]
Hello,

on my zuul server, I want to enable HttpSession to store the oauth2 tokens (authorization_code mode).
on my proxied application, some of them are stateless, others needs to have a session (they are already developed with sessions)

Instead of persisting sessions in Redis for example, I would like to keep having sessions in each application.
I don't want to spam the user with cookies for each application (JSESSIONID1, JSESSIONID2, etc..)

My idea is to store the JSESSIONID from the app A1 in the session in Zuul and every time a request is forwarded to A1, then I would add the cookie with JSESSIONID of A1 (pre-filter) and after (post-filter), I would ready the JSESSIONID to store it in the session of Zuul.

Note that I use oAuth2 JWT, so I get the user profile from it but I need to persist a few objects depending on the application.

What do you think about this ?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
