### ISSUE TITLE
Bind Eureka metadata from ConfigServer in discovery-first mode

### ISSUE THREAD

**Issue by kkalmbach** [spring-cloud/spring-cloud-netflix#268]
I want to add in the metadata for a service into the config server and have the metadata show up in  Eureka.

I can add in eureka.instance. metadataMap.xxx in my bootstrap or application.yml file and it gets put into Eureka, no problem, but it those properties are in a yml file that gets pulled down from the config server, nothing gets put into eureka .
Even if I do a "curl -X DELETE ..."  and delete the service from eureka, it re-registers without the new metadata.

I also tried writing an applicationListener for EnvironmentChangeEvent's adn that works fine for configserver changes, but not the initial property that got pulled in from the config server.

I also tried using a @PostConstruct to register the metadata when the server starts up, but it fails since the service has not been registered yet.

**Comment by dsyer** [comment]
Works for me. Are you using `spring.cloud.config.discovery.enabled=true` (in which case all your Eureka config has to go in `bootstrap.yml`)?

**Comment by kkalmbach** [comment]
Yeah, that's what we are doing.  My bootstrap.yml looks like:
```
spring:
  application:
    name: XXXX-service

  cloud:
    config:
      discovery:
        enabled: true
      failFast: true
        
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
```

It looks like it might be an issue with the eurekaInstanceConfigBean.
If I run "curl -s localhost:8080/env | json_pp | grep metadataMap", I get
```
    "eureka.instance.metadataMap.sla" : 500
```

But, if I run "curl localhost:8080/configprops | json_pp", The metadata map is empty.
```
 "eurekaInstanceConfigBean" : {
         "properties" : {
            "appGroupName" : null,
            "homePageUrl" : null,
            "securePort" : 443,
            "virtualHostName" : "XXXX-service",
            "instanceEnabledOnit" : false,
            "nonSecurePortEnabled" : true,
            "preferIpAddress" : false,
            "appname" : "XXXX-service",
            "nonSecurePort" : 8080,
            "statusPageUrlPath" : "/info",
            "namespace" : "eureka",
            "securePortEnabled" : false,
            "healthCheckUrl" : null,
            "dataCenterInfo" : {
               "name" : "MyOwn"
            },
            "homePageUrlPath" : "/",
            "leaseRenewalIntervalInSeconds" : 30,
            "ipAddress" : "127.0.1.1",
            "statusPageUrl" : null,
            "hostname" : "kkalmbac",
            "healthCheckUrlPath" : "/health",
            "initialStatus" : "UP",
            "secureHealthCheckUrl" : null,
            "metadataMap" : {},
            "leaseExpirationDurationInSeconds" : 90,
            "secureVirtualHostName" : null
         },
         "prefix" : "eureka.instance"
      }
   },
```

**Comment by dsyer** [comment]
Your `bootstrap.yml` contains no `eureka.instance.*` data at all (including no metadata). Isn't it just defined in the wrong place?

**Comment by kkalmbach** [comment]
The bootstrap.yml file contains no eureka.instance info, but the config that my app pulls down from the config-server does have eureka.instance values.

I want to specify the metadata values on the config-server.  Is that a supported way of doing things or do the metadataMap values need to be in bootstrap.yml?

**Comment by dsyer** [comment]
Right, I get it now. It doesn't work because the Eureka instance data is baked in before the config client has a chance to do anything. So I guess it is only supported right now if you have `spring.cloud.config.discovery.enabled=false` (the default). I'll have a look at what we can do (the Netflix code is kind of ugly and inflexible in this sort of area, but who knows we might be able to hack something). Feel fee to investigate independently (I won't do anything before Monday for sure).

**Comment by kkalmbach** [comment]
Thanks!
I have a workaround that listens for an EnvironmentChangeEvent, and makes a eureka rest call.  
It also does some weird stuff at startup so that it makes the Eureka rest call at the right time. 

It's pretty ugly. I would love to get rid of it, but it's working for us.
I can pass the code along if you want.

**Comment by kkalmbach** [comment]
Thanks so much for the quick resolution.

I can't wait to try it out (hopefully today or tomorrow).

Thanks again
-Kevin

**Comment by kkalmbach** [comment]
Looks good.  Thanks for the quick turn around.

All data from the config server is loaded into eureka.

One thing I did notice.  If I change the data on the config server after the server is running and run a /refresh, the new data is not reflected in eureka.  Not a big deal for us, but it might be for someone else.

Thanks again.
-Kevin
