### ISSUE TITLE
Default ZuulFallbackProvider is not working

### ISSUE THREAD

**Issue by pp010** [spring-cloud/spring-cloud-netflix#2683]
ZuulFallbackProvider is working absolutely fine for a single route however fails to execute when i try make a common fallback for all routes. Here is the sample repository which reproduces the same issue: [https://github.com/pp010/ZuulApp](url)

working code:
`@Override
	public String getRoute() {
		return "helloapp";
	}`
Not working:
`@Override
	public String getRoute() {
		return "*";
	}`

**Comment by ryanjbaxter** [comment]
It is hard to test your app without the corresponding "helloapp".  I see you are using Camden.SR7, would you mind upgrading to either Dalston.SR4 or Edgware.SR1 and trying again?

**Comment by pp010** [comment]
"helloapp" is a simple spring boot app with an endpoint "/checkzuul" which returns a plain string "zuul working". Let me test with Dalston.SR4 or Edgware.SR1

**Comment by pp010** [comment]
@ryanjbaxter : after upgrading to Edgware.SR1, the "*" route works fine. thank you very much!!. however, there is a  small confusion. the FallbackProvider has two ClientHttpResponse methods: ClientHttpResponse fallbackResponse() and  ClientHttpResponse fallbackResponse(Throwable cause). whats the difference between these two? the later is getting executed for all fallbacks.

**Comment by ryanjbaxter** [comment]
Take a look at the documentation http://cloud.spring.io/spring-cloud-static/Edgware.SR1/single/spring-cloud.html#hystrix-fallbacks-for-routes.

`fallbackResponse(Throwable cause)` allows you to choose the fallback response based on the `Throwable` that caused the circuit to be tripped.

**Comment by pp010** [comment]
@ryanjbaxter : great!! thanks for the support.
