### ISSUE TITLE
SimpleHostRoutingFilter uses zuul.sslHostnameValidationEnabled incorrectly in Spring Cloud 1.4.2.RELEASE

### ISSUE THREAD

**Issue by cjsteele** [spring-cloud/spring-cloud-netflix#2689]
Hi,

I have been setting up a Spring Boot application to act as a Gateway to a proprietary distributed system. 
I am using

```
@EnableZuulProxy
@EnableAsync
@SpringBootApplication
```
to configure my application, and have a route set up to activate Zuul Filters on a specific URL. I have
zuul.sslHostnameValidationEnabled=false in my application.properties. I have verified that it is being set correctly with the debugger. My requests continued to fail with th SSL Hostname validation errors, so I had another look at the framework code.
```
{"timestamp":1516974588344,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"Certificate for <localhost> doesn't match any of the subject alternative names: []"}
```

The SimpleHostRoutingFilter appears to have a logical error that I discovered while debugging:

```
@PostConstruct
	private void initialize() {
		if(!customHttpClient) {
			this.connectionManager = connectionManagerFactory.newConnectionManager(
					this.sslHostnameValidationEnabled,
					this.hostProperties.getMaxTotalConnections(),
					this.hostProperties.getMaxPerRouteConnections(),
					this.hostProperties.getTimeToLive(), this.hostProperties.getTimeUnit(),
					null);
```

Debugging in IntelliJ shows that the default ConnectionManagerFactory (DefaultApacheHttpClientConnectionManagerFactory in spring-cloud-commons-1.3.1.RELEASE) defines the boolean as "disableSslValidation". So the "sslHostNameValidationEnabled" parameter which is set as false actually enables SSL Host name validation in the HttpClient instead of disabling it.

```
public HttpClientConnectionManager newConnectionManager(boolean disableSslValidation,
			int maxTotalConnections, int maxConnectionsPerRoute, long timeToLive,
			TimeUnit timeUnit, RegistryBuilder registryBuilder) {
		if (registryBuilder == null) {
			registryBuilder = RegistryBuilder.<ConnectionSocketFactory> create()
					.register(HTTP_SCHEME, PlainConnectionSocketFactory.INSTANCE);
		}
		if (disableSslValidation) {
			try {
				final SSLContext sslContext = SSLContext.getInstance("SSL");
				sslContext.init(null,
					new TrustManager[] { new DisabledValidationTrustManager()},
					new SecureRandom());
				registryBuilder.register(HTTPS_SCHEME, new SSLConnectionSocketFactory(
					sslContext, NoopHostnameVerifier.INSTANCE));
			}
```

I was in fact able to get a response by setting the property to true, something it never occurred to me to try before.

My pom.xml uses these versions:
```
 <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.9.RELEASE</version>
  </parent>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Edgware.SR1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/2503.  It is fixed in snapshots and will be included in the next SR.

**Comment by cjsteele** [comment]
Alright, thanks. I didn't find the other issue, my bad.
