### ISSUE TITLE
FallbackProvider (zuul without eureka) is not getting triggered for 404 response code

### ISSUE THREAD

**Issue by ppanigrahi02** [spring-cloud/spring-cloud-netflix#2692]
ZuulFallbackProvider is working fine for localhost servers but not for domain urls. Here is the sample repository which reproduces the same issue: [https://github.com/ppanigrahi02/ZuulApp](url)

i am using zuul without eureka.
`helloapp:
  ribbon:
    listOfServers: http://localhost:8080/, http://helloapp.<company>.<domain>.net/`

When localhost is down, i am able to fetch the fallback response however when the latter is down, i am receiving 404:
> 404 Not Found: Requested route ('helloapp.<company>.<domain>.net/') does not exist.

**Comment by ryanjbaxter** [comment]
What is the exception you are getting when hitting `http://localhost:8080/`?  Are you actually using a real valid domain in  `http://helloapp.<company>.<domain>.net/` or is this the exact domain you are testing with?

**Comment by ppanigrahi02** [comment]
Case 1: When i stop the helloapp running at `localhost:8080` i am getting `Could not get any response` from server and inside zuul fallback `Throwable ` cause is `com.netflix.client.ClientException`. So basically the fallback class is getting triggered for this. 
Case 2: Now i pushed the same helloapp to cloud with a real route and i can access it through my zuulapp. When i stop helloapp running on cloud and try to hit it from the same zuulapp, fallback class is not getting invoked at all. when i hit the valid url of helloapp from postman, i am receiving 404.

**Comment by ryanjbaxter** [comment]
So what happens when you hit `localhost:8080` via postman when it is not running?  What is returned?  

Typically HTTP Clients dont consider a 404 an error so no exception will be thrown, hence the circuit will not be tripped.

**Comment by spencergibb** [comment]
The gateway for `http://helloapp.<company>.<domain>.net/` is providing the 404 (is it Cloud Foundry). Not much we can do there.

**Comment by ppanigrahi02** [comment]
@ryanjbaxter when i stop `localhost:8080` and hit from postman, i get the below response:

![image](https://user-images.githubusercontent.com/19723439/35554629-6b09fab6-05c2-11e8-92df-d6c5e97411aa.png)

it does not contain any response code or other things which is absolutely normal.

@spencergibb yes the 404 is returning from cloud foundry and gateway is simply passing the same response to me.

![image](https://user-images.githubusercontent.com/19723439/35555085-0aa85e04-05c4-11e8-94ae-7a2fa8190d73.png)

404 is a typical exception which can occur very frequently like when the app get crashed or failed to start or the app is starting or in stopped condition etc etc. So this must cause the circuit to trip. Zuul is using Hystrix underneath and hystrix does entertain 404 as an exception and trips the circuit, so the same is expected from zuul as well.

**Comment by ppanigrahi02** [comment]
As per my understanding, the circuitbreaker comes into action when either the external service is down or the external service throws an exception. Under both the scenarios hystrix trips the circuit and triggers the fallback. However, zuul failed to do the same in either case. Even if i directly throw an exception, zuul does not trigger fallback. This is my helloapp repo [https://github.com/ppanigrahi02/HelloApp](url). when i run this helloapp at `localhost:8080` and hit `localhost:8080/checkerror`, i am getting the excetion:
 
![image](https://user-images.githubusercontent.com/19723439/35557208-7162f6e4-05ca-11e8-8aab-479c3894ac82.png)

when i run my zuulapp at `localhost:8765` and hit `localhost:8765/helloapp/checkerror`, i am receiving the same response. Its not triggering the fallback:

![image](https://user-images.githubusercontent.com/19723439/35557286-ab2a237a-05ca-11e8-9c07-7befc809477c.png)

So my question is when do we expect the fallback to trigger in Zuul? As per my observation, its triggering fallback only and only if it does not receive any response or if there is a hystrix timeout.

**Comment by ryanjbaxter** [comment]
So your test isnt exactly accurate.  In https://github.com/ppanigrahi02/HystrixApp you are using `RestClient`.  While in Zuul (by default) we are using the Apache HTTP Client.  If the http client you are using doesnt throw an exception than Hystrix wont come into play.  The Apache Http Client will not throw an exception when it receives a 500 so the fallback is not invoked.

**Comment by ppanigrahi02** [comment]
I get it. Also realized that 500 is not a valid exception for circuit to trip. However, exceptions like 404, 408, 502, 503, 504 must trip the circuit. I tested with 404, not sure how zuul behaves with others. So i think its a **bug** in zuul fallback.

Please provide clarifications on below two doubts:
1. What is the purpose of zuul fallback? **OR** Under which condition fallback comes into action? **OR** What are the expected exceptions for which fallback will be triggered?
2. Is there any way by which i can trigger fallback as per the response from downstream? If no, please let me know where to raise this bug against zuul :p

**Comment by ryanjbaxter** [comment]
> What is the purpose of zuul fallback? OR Under which condition fallback comes into action? OR What are the expected exceptions for which fallback will be triggered?
There is no such thing as a Zuul fallback there is a Hystrix fallback.  The purpose of the fallback is to  provide some kind of response to the client when the circuit gets tripped.  The circuit gets tripped when the code wrapped by the Hystrix command throws an exception or takes longer than the Hystrix timeout to complete.

>Is there any way by which i can trigger fallback as per the response from downstream? If no, please let me know where to raise this bug against zuul :p
No.  If that is what you are asking for, the ability to cause the circuit to trip based on a HTTP response code, than we can use this issue and mark it as an enhancement.

**Comment by ppanigrahi02** [comment]
Great. We can close this issue now. I strongly suggest to take this as an enhancement as the business logic for gateway demands the feature of tripping the circuit as per the response. The use case is like If one downstream service is down, then the gateway should be smart enough to reroute the subsequent requests to another available service. This functionality can be achieved with zuul-eureka combo, so the same is expected for standalone zuul server as well.

**Comment by liolay** [comment]
@ryanjbaxter @spencergibb  i think that we should provide a fallback strategy like hystrix itself, normal exception can also trigger fallback, besides hystrix circuit is tripped.  that maybe much useful

**Comment by spencergibb** [comment]
@liolay please don't comment on old closed issues. This is a Hystrix fallback
