### ISSUE TITLE
SOAP or HTTP request body encryption between two Zuul proxies

### ISSUE THREAD

**Issue by rashad-farajullayev** [spring-cloud/spring-cloud-netflix#2693]
Hello. I am facing a problem with Zuul "pre" filter. 
In my solution I have two proxies. One proxy runs at the client side, and another inside of our data-center. The client issues SOAP messages in their own server to the first Zuul proxy, and that proxy forwards the request to the second Zuul proxy which is in our data center. The second Zuul proxy forwards these SOAP requests to the real Spring-WS node. 

Everything works fine until some point. I can forward all SOAP and HTTP requests, and have written good "post" filters to alter response body so that everything fits the architecture design and request flows.  

The only problem is, I want to encrypt the body of the SOAP requests between these two Zuul proxies. Whatever I have done today doesn't work. 
I created two "pre" filters at both of the proxies. The client side "pre" filter encrypts the body, and the server side proxy must decrypt it and forward to the service registry for proper handling.

I tried example from this URL:
https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/UppercaseRequestEntityFilter.java

I handle the request at the server side Zuul proxy and see that actually body is not changed in the first proxy.

I this this code for altering request body at the first proxy:
```
@Override
    public Object run() {

        try {
            RequestContext context = getCurrentContext();
            InputStream in = (InputStream) context.get("requestEntity");
            if (in == null) {
                in = context.getRequest().getInputStream();
            }
            String body = StreamUtils.copyToString(in, Charset.forName("UTF-8"));
            // body = "request body modified via set('requestEntity'): "+ body;
            body = body.toUpperCase();
            context.set("requestEntity", new ByteArrayInputStream(body.getBytes("UTF-8")));
        }
        catch (IOException e) {
            rethrowRuntimeException(e);
        }
        return null;
    }
```

And this code for handling the request at the second proxy:
```
@Override
    public Object run() {
        RequestContext ctx = RequestContext.getCurrentContext();

        try (final InputStream inputStream = ctx.getRequest().getInputStream()) {
            //BufferedReader reader = ctx.getRequest().getReader();

            if (inputStream != null) {
                final String requestData = CharStreams.toString(new InputStreamReader(inputStream, "UTF-8"));
                System.out.println(requestData);                
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
```

The server side Zuul proxy handles the initial - unchanged body. 

I tried ctx.setRequest and push in my own HttpServletRequest, didn't work either.

**Comment by rashad-farajullayev** [comment]
This solution seems to be working in my case
Comment from this guy: https://github.com/denisoliveira

On this issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/2204

Please let me know if there is another way.

P.S.  setting requestEntity in my case works only if Zuul forwards requests to Eureka. In my case the first proxy is not registered at Eureka. That might be the reason why this didn't work out:
 context.set("requestEntity", new ByteArrayInputStream(body.getBytes("UTF-8")));

**Comment by ryanjbaxter** [comment]
Not that I know of

**Comment by locactus** [comment]
No one really answered this question, I had the same issue and found this through a Google search.

This worked for me
RequestContext context = getCurrentContext();
			InputStream in = (InputStream) context.get("requestEntity");
			if (in == null) {
				in = context.getRequest().getInputStream();
			}
			String body = StreamUtils.copyToString(in, Charset.forName("UTF-8"));
			body = "request body modified via request wrapper: "+ body;
			byte[] bytes = body.getBytes("UTF-8");
			context.setRequest(new HttpServletRequestWrapper(getCurrentContext().getRequest()) {
				@Override
				public ServletInputStream getInputStream() throws IOException {
					return new ServletInputStreamWrapper(bytes);
				}

				@Override
				public int getContentLength() {
					return bytes.length;
				}

				@Override
				public long getContentLengthLong() {
					return bytes.length;
				}
			});
