### ISSUE TITLE
Spring Boot Application not getting started in PCF because of 'feign-httpclient' dependency

### ISSUE THREAD

**Issue by chetak-team** [spring-cloud/spring-cloud-netflix#2697]
Hi, I'm facing the similar issue. Below is the stack trace while deploying to Cloud Foundry. Locally i could able to start the app. Can some one please help me to understand the issue?

I have included feign-httpclient dependency to support 'PATCH' requests in my application.
When I run with this in my local server it's working fine, but in PCF it's throwing below exception.

I can reference https://github.com/spring-cloud/spring-cloud-netflix/issues/226 for this issue.

2018-01-28T23:02:40.228+05:30 [APP/PROC/WEB/0] [OUT] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'DynamicsContactClient': FactoryBean threw exception on object creation; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'feignRetryer' defined in org.springframework.cloud.netflix.feign.FeignClientsConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [feign.Retryer]: Factory method 'feignRetryer' threw exception; nested exception is java.lang.NoSuchFieldError: NEVER_RETRY

**Comment by ryanjbaxter** [comment]
Can you provide a sample that reproduces the problem?

**Comment by chetak-team** [comment]
the app looks like this:

@SpringBootApplication
@ComponentScan
@EnableAsync
@EnableFeignClients
@EnableDiscoveryClient

public class Application  {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public CommonsRequestLoggingFilter requestLoggingFilter() {
        CommonsRequestLoggingFilter crlf = new CommonsRequestLoggingFilter();
        crlf.setIncludeClientInfo(true);
        crlf.setIncludeQueryString(true);
        crlf.setIncludePayload(true);
        return crlf;
    }

    @Bean
    public AsyncRestTemplate asyncRestTemplate(){
        return new AsyncRestTemplate();
    }
}


Feign Client:
-------------
@FeignClient(value = "test-proxy", url = "${test.proxy.uri}")
public interface DynamicsContactClient {
    @RequestMapping(method = RequestMethod.GET, value = "xyz/{xyz}")
    ResponseEntity<Object> getRequest(@PathVariable("xyz") String xyz);
}

build.gradle:
-------------
apply from: "gradle/script/io.gradle"
buildscript {
    repositories {
        maven{
            url 'https://indegene.jfrog.io/indegene/libs-release'
            credentials {
                username = "iodeploy"
                password = "AP8VWX1Nem4s5ySLKpQgr1CSc7g"
            }
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.4.2.RELEASE")
        classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.3")
        classpath "io.spring.gradle:dependency-management-plugin"
        classpath 'net.researchgate:gradle-release:2.4.0'
        classpath ("org.jfrog.buildinfo:build-info-extractor-gradle:4.4.0")

    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'com.jfrog.artifactory'
apply plugin: 'net.researchgate.release'
apply plugin: "org.sonarqube"
apply plugin: "jacoco"
version = "2.0"

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-config:1.2.2.RELEASE'
    }
}

//create a single Jar with all dependencies
repositories {
    maven{
        url '******************'
        credentials {
            username = "*******"
            password = "*******"
        }
    }
}

dependencies {
    [
            "org.springframework.boot:spring-boot-starter-web",

    ].each { dep ->
        compile(dep) {
            exclude module: "log4j-over-slf4j"
            exclude module: "slf4j-log4j12"
        }
    }

    compile 'org.springframework.cloud:spring-cloud-starter-config'
    compile 'org.springframework.cloud:spring-cloud-starter-eureka-server:1.2.3.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-test', version: '1.4.3.RELEASE'
    compile("org.springframework.boot:spring-boot-starter-data-rest")
    compile("org.springframework.boot:spring-boot-starter-data-jpa")
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-feign', version: '1.2.4.RELEASE'
    compile group: 'com.netflix.feign', name: 'feign-httpclient', version: '8.5.0'
    compile group: 'com.microsoft.azure', name: 'adal4j', version: '1.2.0'
    compile group: 'org.apache.olingo', name: 'odata-client-core', version: '4.0.0-beta-01'

    compile group: 'org.apache.logging.log4j', name: 'log4j-web', version: '2.7'
    compile group: 'com.notnoop.apns', name: 'apns', version: '1.0.0.Beta6'

    compile 'com.auth0:java-jwt:3.1.0'
}

**Comment by chetak-team** [comment]
and bootstrap.yml has below feign setup:

feign:
  okhttp.enabled: true
  hystrix:
    enabled: false
  readtimeout: 1200000
  connectiontimeout: 1200000
  httpclient.enabled: true

**Comment by chetak-team** [comment]
my service impl, uses feign client as follows.

@Autowired
private DynamicsContactClient dynamicsContactClient;

**Comment by chetak-team** [comment]
@ryanjbaxter have any update on this?

**Comment by chetak-team** [comment]
I found the root cause. seems to be `name: 'feign-httpclient', version: '8.5.0' ` having some issues with this version, i have upgraded the version to latest and added few supporting dependencies from 'com.netflix.feign' baseline. Now app is booting normally but still its logging above mention error in the trace.
