### ISSUE TITLE
Remove guava from spring-cloud-starter-netflix-archaius

### ISSUE THREAD

**Issue by dmarkhas** [spring-cloud/spring-cloud-netflix#2701]
I've noticed this issue: https://github.com/spring-cloud/spring-cloud-netflix/issues/154
Which was supposed to exclude the usage of Guava to allow users to use their own, but it is still in the POM file of spring-cloud-starter-netflix-archaius:
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-starter-netflix/spring-cloud-starter-netflix-archaius/pom.xml

Can it be removed from there as well?

**Comment by spencergibb** [comment]
> AFAIK we don't use guava, but Netflix does internally so we are forced to include it as a dependency

**Comment by brenuart** [comment]
`com.netflix.archaius:archaius-core` pulls it already - why do you need to repeat it in the starter?
