### ISSUE TITLE
Is it possible to filter services by instance-zone tag without custom queries?

### ISSUE THREAD

**Issue by raffian** [spring-cloud/spring-cloud-netflix#2707]
Posted my [question on stackoverflow](https://stackoverflow.com/questions/48571600/filtering-services-using-zone-tags-with-spring-cloud-consul-discovery-and-feig) after reading project guidelines, was hoping for a response to help shed light on this subject.

Are we misunderstanding the use instance-zone? The assumption is new services registered in Consul can be tagged using `spring.cloud.consul.discovery.instance-zone`, we assign spring active profile to this key.  SCC clients use FeignClient to disscover and call REST endpoints in this service. Since we have one physical COnsul cluster for all operational environments, we want to ensure Springboot clients discovering services see only those services with `instance-zone=client active runtime profile`, to avoid a "dev" client discovering QA or Prod services.  Are we on the right path? We're trying to avoid building custom querys to do our own filtering using tags, though I suppose if that's a last resort we'll do it.

```
# for registered service
spring:
  cloud:
    consul:
      discovery:
        instance-zone: dev
        tags: dev
```

**Comment by spencergibb** [comment]
Please open https://github.com/spring-cloud/spring-cloud-consul/issues

**Comment by raffian** [comment]
My bad, was not paying attention to where I was posting
