### ISSUE TITLE
Error after upgrading from Spring Boot 2.0.0.M7 to 2.0.0.RC1

### ISSUE THREAD

**Issue by rubensa** [spring-cloud/spring-cloud-netflix#2709]
After upgrading from Spring Boot 2.0.0.M7 to 2.0.0.RC1, the following error arise and application does not boot:

`Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration$EndpointConfiguration': Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration$EndpointConfiguration] from ClassLoader [sun.misc.Launcher$AppClassLoader@764c12b6]`

Using Maven dependency spring-cloud-dependencies version Finchley.M5, aka spring-cloud-netflix-zuul 2.0.0.M5.

**Comment by ryanjbaxter** [comment]
We have not released a milestone that is compatible with 2.0.0.RC1 yet

**Comment by rubensa** [comment]
Ok.

For reference:
It seems that the problem is the change from org.springframework.boot.actuate.trace.TraceRepository to org.springframework.boot.actuate.web.trace.HttpTraceRepository in Spring Boot 2.0.0.RC1.
This should be fixed by: https://github.com/spring-cloud/spring-cloud-netflix/commit/a81eb771e5974a8c0bff22a4101306054550fe4f#diff-bc2984bc4532c27479fbd621b6cb21e4
