### ISSUE TITLE
Zuul  - ProxyRouteLocator does not use ZuulProperties servletPath

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#271]
This related to the big files transfer scenario where the DispatcherServlet is bypassed.
Basically, although the unit tests pass for Spring Cloud Zuul, the routing does not work in real scenarios because the ```servletPath``` is not set to the value held in ```ZuulProperties.getServletPath()```.

I will provide a pull request.

**Comment by dsyer** [comment]
I didn't follow that sorry. What is a "real scenario"? The pull request appears to just break a test.

**Comment by aivans** [comment]
Please see the comment on the pull request.
