### ISSUE TITLE
how to integrate hystrix and sleuth together with rabbitmq?

### ISSUE THREAD

**Issue by FlyRabit** [spring-cloud/spring-cloud-netflix#2713]
when hystrix and sleuth use rabbitmq,they all need to config spring.rabbitmq.*,but I want to config double rabbitmq,one for hystrix,the other for sleuth,what should I config ?

**Comment by ryanjbaxter** [comment]
I am not seeing where Hystrix uses rabbitmq, maybe you can provide an example of what you are referring to?

**Comment by spencergibb** [comment]
Hystrix Stream could use rabbit. @scottfrederick probably knows off the top of his head how to do this.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
