### ISSUE TITLE
spring cloud zuul garbled

### ISSUE THREAD

**Issue by dzncloud** [spring-cloud/spring-cloud-netflix#2714]
By external request through the spring cloud zuul then forwarded to the service on the Chinese garbled.
I try to directly access the service not through zuul, the characters are normal.

My request data is:
Header information: Content-Type: application / x-www-form-urlencoded; charset = GBK
body information is: biz_content = <XML><EventType><![CDATA[unfollow]]></EventType><ActionParam><![CDATA[]]></ActionParam><FromAlipayUserId><![CDATA[2088202254220098]]></FromAlipayUserId><AppId><![CDATA[2015110400687512]]></AppId><MsgType><![CDATA[event]]></MsgType><CreateTime><![CDATA[1516005044464]]></CreateTime><FromUserId><![CDATA[20881038153482069401220400910309]]></FromUserId><MsgId><![CDATA[e04ea5d9ea044603b5e7222f7dcafd0d]]></MsgId><AccountNo><![CDATA[]]></AccountNo><AgreementId><![CDATA[]]></AgreementId><UserInfo><![CDATA[{"logon_id":"yan***@hotmail.com","user_name":"*俏"}]]></UserInfo></XML>

How can I deal with this problem?
spring cloud version is Camden.SR7

**Comment by ryanjbaxter** [comment]
Can you retry with Dalston.SR5 or Edgware.SR1 and if it still doesnt work provide a sample that reproduces it?

**Comment by dzncloud** [comment]
I have solved this problem
In zuul configuration spring.http.encoding.force-request: false

Service is also configured about:
spring.http.encoding.force-request: false

thank you very much. @ryanjbaxter
