### ISSUE TITLE
How to replace or  custom  SimpleHostRoutingFilter  with  okhttp3 ?

### ISSUE THREAD

**Issue by shengnian** [spring-cloud/spring-cloud-netflix#2716]
I  want  use okhttp3  without  eureka and robbin(only  use url, not  serviceid),  how should i  configure  or  custom SimplrHostRoutingFilter?  Thanks.

**Comment by shengnian** [comment]
Thank you for  your reply!  I have an another question, If  the  ZuulProperties changed, how to  inject  to  SimpleHostRoutingFilter,  eg: when i changed ZuulProerties's  Host  maxtotalconnections how to reload ?

**Comment by ryanjbaxter** [comment]
You can try using `@RefreshScope`
http://cloud.spring.io/spring-cloud-static/Edgware.SR2/single/spring-cloud.html#_refresh_scope

**Comment by shengnian** [comment]
thanks @ryanjbaxter i tried `@RefreshScope`  this only avaliable for static config file, i want initail `ZuulProperties` from database,  no solution yet found. but thanks again!

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
