### ISSUE TITLE
why zuul SendForwardFilter response immediately after forward completed

### ISSUE THREAD

**Issue by cai0329** [spring-cloud/spring-cloud-netflix#2720]
hello, I want change response body in POST type zuul filter, but when I useing SendForwardFilter to my zuul application rest api, it immediately flushBuffer after forward completed. What I need do to salve this problem? Thanks!

@Override
public Object run() {
    try {
        RequestContext ctx = RequestContext.getCurrentContext();
        String path = (String) ctx.get(FORWARD_TO_KEY);
        RequestDispatcher dispatcher = ctx.getRequest().getRequestDispatcher(path);
        if (dispatcher != null) {
            ctx.set(SEND_FORWARD_FILTER_RAN, true);
            if (!ctx.getResponse().isCommitted()) {
                dispatcher.forward(ctx.getRequest(), ctx.getResponse());
                **ctx.getResponse().flushBuffer();**
            }
        }
    }
    catch (Exception ex) {
        ReflectionUtils.rethrowRuntimeException(ex);
    }
    return null;
}

**Comment by spencergibb** [comment]
The forward filter is essentially saying, I've handed all responsibility to the local controller.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
