### ISSUE TITLE
No Zuul /routes endpoint in 2.0.0.RC1/Finchley.M6

### ISSUE THREAD

**Issue by elgohr** [spring-cloud/spring-cloud-netflix#2726]
Bug report

The /routes endpoint (https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html#_routes_endpoint) returns HTTP 404, when build with 2.0.0.RC1/Finchley.M6.
Steps to reproduce: 
- Visit start.spring.io, the one and only place on the internet (besides production).
- Add Zuul && Actuator
- @EnableZuulProxy and start up Zuul

When doing this with 1.5.10.RELEASE/Edgware.SR2 everything works as expected.
Doing this with 2.0.0.RC1/Finchley.M6 leads to the described 404.

**Comment by spencergibb** [comment]
It's `/actuator/routes` now

**Comment by elgohr** [comment]
Also thought so, but /actuator does not show it and /actuator/routes also returns 404.

**Comment by spencergibb** [comment]
They need to be exposed now. The property changed between RC1 and boot snapshots. Check the boot documentation

**Comment by elgohr** [comment]
Refering the docs: https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints
Thank you for the hint!

**Comment by yuvalbar84** [comment]
just encountered the same thing.
solved by adding:
```management.endpoints.web.exposure.include=*```

**Comment by vaishnav-piyush** [comment]
The documentation suggests to use `management.endpoints.web.expose`. But that doesn't work. This works though:
`management.endpoints.web.exposure.include`
