### ISSUE TITLE
[Question] MITM-attack with fake service possible?

### ISSUE THREAD

**Issue by jo2** [spring-cloud/spring-cloud-netflix#2728]
I read about a MITM-attack on Eureka. The situation was a fake eureka client with the same service name and the same eureka service instance as the original services. Is such an attack possible on a eureka standalone or are there any mechanisms against it? Do you maybe have some sources or documentation where this is mentioned?

**Comment by Koizumi85** [comment]
Possible actions to make this difficult I see:
- Secure your eureka instance with username/password
- Make your eureka instance not accessible from outside your own network (if possible in your architecture)

For sure such an "attack" is possible if your eureka server is reachable from the internet and not secured.

**Comment by jo2** [comment]
Thank you for that information

**Comment by spencergibb** [comment]
Eureka was initially built to run behind a firewall, no outside access. Sane network rules are helpful. SSL connections with certificates. You can use Spring Security to secure the app as well.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
