### ISSUE TITLE
Zuul - invalid response on Forwarding error

### ISSUE THREAD

**Issue by mariusznet** [spring-cloud/spring-cloud-netflix#273]
When zuul throws Forwarding error, for example because service is unavailable, invalid json response is returned: (on Accept:application/json header)

```
{"timestamp":1426886992816,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"Forwarding error"}{"timestamp":1426886992826,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"Forwarding error","path":"/billing-service/account"}
```

I'm not quite sure if this is more zuul or spring boot problem. 
I can send more logs or details if needed.

**Comment by dsyer** [comment]
I never saw that, so a simple project with steps to repeat would be most helpful.

**Comment by mariusznet** [comment]
No problem:
https://github.com/mariusznet/spring-cloud-bug
In readme is described how to reproduce. 

As it turns out spring boot 1.2.1 is to blame, after changing version to 1.2.2 everything works as expected, so example code is just for review if interested. 
Greetings,
Mariusz

**Comment by spencergibb** [comment]
@mariusznet thanks for the followup.

**Comment by vjykmsc** [comment]
@mariusznet  : I am using spring boot 1.2.3, and I get the same issue. Failing on 500 errors. Any idea ?

**Comment by sallampalli** [comment]
@mariusznet  : Hi, I am using 1.2.3, but still the same issue. Thoughts ?

**Comment by dsyer** [comment]
Probably unrelated. Open another issue with some sample code if you have a problem (this one is closed).

**Comment by yachika-ralhan** [comment]
> @mariusznet : Hi, I am using 1.2.3, but still the same issue. Thoughts ?

same issue, do you know the solution ?

**Comment by yachika-ralhan** [comment]
> Probably unrelated. Open another issue with some sample code if you have a problem (this one is closed).

what is the solution
