### ISSUE TITLE
Can't disable default Zuul filters

### ISSUE THREAD

**Issue by aartigao** [spring-cloud/spring-cloud-netflix#2731]
I'm trying to disable **SendErrorFilter** but seems it's not working as explained in documentation:

> If you want to disable one, simply set **zuul.\<SimpleClassName\>.\<filterType\>.disable=true**

I'm using the latest GA (1.4.3). Looking at the code in ZuulServerAutoConfiguration doesn't seem to use any **\@ConditionalOnProperty** in **SendErrorFilter** bean creation. Am I missing something?

Thanks!

**Comment by spencergibb** [comment]
What property are you setting?

**Comment by aartigao** [comment]
My mistake... I was setting zuul.SendErrorFilter.**post**.disable=true but now I've noticed that filterType=error... 

I'll try with zuul.SendErrorFilter.**error**.disable=true

Thank you!
