### ISSUE TITLE
@LoadBalancd can't be used with "prototype" for restTemplate?

### ISSUE THREAD

**Issue by melodica** [spring-cloud/spring-cloud-netflix#2735]
I'm following the spring ribbon guide from spring site. ([spring ribbon guide](https://spring.io/guides/gs/client-side-load-balancing/))

If restTemplate is being created in this way :

```
@LoadBalanced
@Bean
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)  ---- I added this line
RestTemplate restTemplate(){
    logger.warn("create a restTemplate bean..."); --- added this for debug
    return new RestTemplate();
}
```
Ribbon client will not be able to find server. (unable to parse client name with server IP address);
error log: 
`I/O error on GET request for "http://say-hello/greeting": say-hello; nested exception is java.net.UnknownHostException: say-hello] with root cause`

Ribbon client is defined as `@RibbonClient(name = "say-hello")`

The debug message has occurred twice in the log. 

1. The first time restTemplate is being created before RibbonAutoConfiguration, which has no ribbon info at all; 
2. the 2nd time it's being created after RibbonAutoConfiguration, but before LoadBalancerAutoConfiguration, which is being customized by LoadBalancerAutoConfiguration's customizer.

It seems weird to me as RestTemplate only being auto wired at one place, why it's being instanialized twice? 

and even worse, it's the first one being used by ribbon client, which causes this issue.

**Comment by ryanjbaxter** [comment]
The reason the bean is created twice is because you have added `@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)`.  The bean will be created eveytime it is requested from the context.  I a not sure why the Ribbon request interceptor isnt added the second time.

Why are you adding the `@Scope` annotation?

**Comment by melodica** [comment]
I realized that it might be the issue. 

Ribbon request interceptor is added the second time, but it is the first instance of restTemplate that is used by application. The 2nd instance is created when LoadBalancerAutoConfiguration starts and and is never actually used anywhere.

The reason why I add `@Scope` is because I have multiple ribbon clients to call separate APIs, and each client will have a its own ResponseErrorHandler to override spring's `DefaultResponseErrorHandler`

**Comment by ryanjbaxter** [comment]
@spencergibb what do you think?  I have not seen anyone else do this before.

**Comment by spencergibb** [comment]
Yeah, I don't know that this is a normal situation.

**Comment by ryanjbaxter** [comment]
@melodica would you like to submit a PR to update the documentation?

**Comment by melodica** [comment]
Certainly.
