### ISSUE TITLE
[Question]Eureka Client won't register correctly on the eureka server

### ISSUE THREAD

**Issue by MasterColor** [spring-cloud/spring-cloud-netflix#2738]
## **Background:**
I wish to run a spring cloud project in a tomcat not in an embedded tomcat. But all the eureka clients won't even **try** to register themselves on the eureka server, without any error or warn log.

**I did the following customization:**

1. Make the project able to run in a tomcat: exclude tomcat dependencies and overwrite the following method
 `@Override`
   ` protected SpringApplicationBuilder configure(SpringApplicationBuilder builder)`
    `{`
    `    return builder.sources(ZuulApplication.class);`
   ` }`
1. The annotations of main class ZuulApplication are as listed:
`@EnableZuulProxy`
`@SpringBootApplication`
`@EnableEurekaClient`
`@Import(value = {EurekaSslConfig.class, WebConfiguration.class})`
1. Yaml configuration
![image](https://user-images.githubusercontent.com/28705375/36582113-1ac404d8-18ab-11e8-9b40-42d9491de714.png)
1. The overwrited beans:
`OkHttpLoadBalancingClient` I overwrite this bean to load self-signed trust keystore
`DiscoveryClient.DiscoveryClientOptionalArgs`  I overwrite this bean to load self-signed trust keystore
1. Enable log4j and use customized logger and configuration. So I exclude the following dependencies.
`<exclusion>`
`					<groupId>org.springframework.boot</groupId>`
`					<artifactId>spring-boot-starter-logging</artifactId>`
`				</exclusion>`
`				<exclusion>`
`					<groupId>org.springframework.boot</groupId>`
`					<artifactId>spring-boot-starter-log4j2</artifactId>`
`				</exclusion>`
## **Question**
When I put the customized zuul project into a tomcat container and started the tomcat, I found that the zuul application could be started correctly and work well, but it won't try to register itself on eureka server. Because I did not run a eureka server, there supposed to be at least an error log about unable to register on eureka server. But as I said , there was no error log. Only leave logs as follows:
**in the start log**
`[2018-02-23 11:53:12][INFO][main][org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter][afterSingletonsInstantiated][431]-Registering beans for JMX exposure on startup`
`[2018-02-23 11:53:13][INFO][main][org.springframework.context.support.DefaultLifecycleProcessor][start][343]-Starting beans in phase 0`
`[2018-02-23 11:53:13][INFO][main][org.springframework.cloud.netflix.eureka.InstanceInfoFactory][create][71]-Setting initial instance status as: STARTING`
`[2018-02-23 11:53:13][INFO][main][org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry][register][40]-Registering application service-zuul with eureka with status UP`
**no more log about registering**
**the following debug logs kept being logged as long as the application still running**
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.MonitoredConnectionManager][getConnection][240]-Get connection: {s}->https://127.0.0.1:8761, timeout = 5000`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.MonitoredConnectionManager][getConnection][240]-Get connection: {s}->https://127.0.0.1:8761, timeout = 5000`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getEntryBlocking][347]-[{s}->https://127.0.0.1:8761] total kept alive: 0, total issued: 0, total allocated: 0 out of 200`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getFreeEntry][522]-No free connections [{s}->https://127.0.0.1:8761][null]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getEntryBlocking][366]-Available capacity: 50 out of 50 [{s}->https://127.0.0.1:8761][null]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][createEntry][548]-Creating new connection [{s}->https://127.0.0.1:8761]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getEntryBlocking][347]-[{s}->https://127.0.0.1:8761] total kept alive: 0, total issued: 1, total allocated: 1 out of 200`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][org.apache.http.impl.conn.DefaultClientConnectionOperator][openConnection][177]-Connecting to 127.0.0.1:8761`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getFreeEntry][522]-No free connections [{s}->https://127.0.0.1:8761][null]
[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][getEntryBlocking][366]-Available capacity: 49 out of 50 [{s}->https://127.0.0.1:8761][null]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][createEntry][548]-Creating new connection [{s}->https://127.0.0.1:8761]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][org.apache.http.impl.conn.DefaultClientConnectionOperator][openConnection][177]-Connecting to 127.0.0.1:8761`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][org.apache.http.impl.conn.DefaultClientConnection][close][180]-Connection org.apache.http.impl.conn.DefaultClientConnection@19376961 closed`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][org.apache.http.impl.conn.DefaultClientConnection][shutdown][164]-Connection org.apache.http.impl.conn.DefaultClientConnection@19376961 shut down`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.MonitoredConnectionManager][releaseConnection][288]-Released connection is not reusable.`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][freeEntry][431]-Releasing connection [{s}->https://127.0.0.1:8761][null]`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][org.apache.http.impl.conn.DefaultClientConnection][close][180]-Connection org.apache.http.impl.conn.DefaultClientConnection@19376961 closed`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-CacheRefreshExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][notifyWaitingThread][678]-Notifying no-one, there are no waiting threads`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][org.apache.http.impl.conn.DefaultClientConnection][close][180]-Connection org.apache.http.impl.conn.DefaultClientConnection@2a822eb6 closed`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][org.apache.http.impl.conn.DefaultClientConnection][shutdown][164]-Connection org.apache.http.impl.conn.DefaultClientConnection@2a822eb6 shut down`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.MonitoredConnectionManager][releaseConnection][288]-Released connection is not reusable.`
`[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.NamedConnectionPool][freeEntry][431]-Releasing connection [{s}->https://127.0.0.1:8761][null]`

**Comment by ryanjbaxter** [comment]
When providing code, please place it in a Git repo or in a zip file attached to the issue.

The below `DEBUG` message does indicate that the app is trying to (unsuccessfully) register with a Eureka server
```
[2018-02-23 15:20:12][DEBUG][DiscoveryClient-HeartbeatExecutor-0][com.netflix.discovery.shared.MonitoredConnectionManager][getConnection][240]-Get connection: {s}->https://127.0.0.1:8761, timeout = 5000
```

**Comment by MasterColor** [comment]
So why the error log is not reported? the eureka client must use `spring-boot-starter-log4j2` or `spring-boot-starter-logging` ?
Now I have made the registering process success, but still no success log found in the info level. The debug log only contains the connection life cycle.
Without these logs, it is really hard to debug when it goes wrong.

**Comment by MasterColor** [comment]
I have fixed this problem.
I guess some components of eureka-client rely on log4j2 or logback. So when I exclude log4j2 and logback, some log can be printed.
