### ISSUE TITLE
Application startup failure with Feign, Boot 2.0.0.RC2 & Finchley.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by legendjaks** [spring-cloud/spring-cloud-netflix#2739]
Create a new project in start.spring.io with following dependencies,

```
buildscript {
	ext {
		kotlinVersion = '1.2.21'
		springBootVersion = '2.0.0.RC2'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")
		classpath("org.jetbrains.kotlin:kotlin-allopen:${kotlinVersion}")
        classpath("org.jetbrains.kotlin:kotlin-noarg:${kotlinVersion}")
	}
}

apply plugin: 'kotlin'
apply plugin: 'kotlin-spring'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.jay'
version = ''
sourceCompatibility = 1.8
compileKotlin {
	kotlinOptions {
		freeCompilerArgs = ["-Xjsr305=strict"]
		jvmTarget = "1.8"
	}
}
compileTestKotlin {
	kotlinOptions {
		freeCompilerArgs = ["-Xjsr305=strict"]
		jvmTarget = "1.8"
	}
}

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}

ext {
	springCloudVersion = 'Finchley.BUILD-SNAPSHOT'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('com.fasterxml.jackson.module:jackson-module-kotlin')
	compile('org.springframework.cloud:spring-cloud-starter-config')
	compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
	compile('org.springframework.cloud:spring-cloud-starter-openfeign')
    compile('org.springframework.cloud:spring-cloud-starter-netflix-hystrix')
    //compile('org.springframework.retry:spring-retry:1.2.2.RELEASE')

    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	compile("org.jetbrains.kotlin:kotlin-reflect")
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

```

Create & Enable feign clients

```
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
class OrdersApplication

@FeignClient(value = "http://products")
interface ProductProxy {

    @RequestMapping("/products", method = [RequestMethod.GET],
        produces = [MediaType.APPLICATION_JSON_VALUE])
    fun products(): List<Product>
}
```

Now the application startup fails,

> Parameter 0 of method feignClient in org.springframework.cloud.netflix.feign.ribbon.DefaultFeignLoadBalancedConfiguration required a bean of type
>  'org.springframework.cloud.netflix.feign.ribbon.CachingSpringLoadBalancerFactory' that could not be found.
> 
> Bean method 'retryabeCachingLBClientFactory' in 'FeignRibbonClientAutoConfiguration' not loaded because @ConditionalOnClass
>  did not find required class 'org.springframework.retry.support.RetryTemplate'
> 
> Action:
> 
> Consider revisiting the conditions above or defining a bean of type 'org.springframework.cloud.netflix.feign.ribbon.CachingSpringLoadBalancerFactory' 
> in your configuration.

Now add `compile('org.springframework.retry:spring-retry:1.2.2.RELEASE')
`

> Parameter 0 of method feignClient in org.springframework.cloud.netflix.feign.ribbon.DefaultFeignLoadBalancedConfiguration required a bean of type 'org.springframework.cloud.netflix.feign.ribbon.CachingSpringLoadBalancerFactory' that could not be found.
> 
> Bean method 'cachingLBClientFactory' in 'FeignRibbonClientAutoConfiguration' not loaded because @ConditionalOnMissingClass found unwanted class 'org.springframework.retry.support.RetryTemplate'
> 
> Action:
> 
> Consider revisiting the conditions above or defining a bean of type 'org.springframework.cloud.netflix.feign.ribbon.CachingSpringLoadBalancerFactory' in your configuration.

Revert the Boot to 2.0.0.M3 & Finchley.M2 application starts fine. Is there any breaking change? Where can I find this change info and configuration?

**Comment by ryanjbaxter** [comment]
Feign has been recently moved to its own project
https://github.com/spring-cloud/spring-cloud-openfeign/

It sounds like there is just a conflict in jars maybe in your maven repo.  Can you try clearing your local maven repo and trying again?

**Comment by legendjaks** [comment]
My bad. I was using 2.0.0.M3 and Finchley.M2, want to try the RC2. So when I migrated got this error. After clearing .gradle & .m2 and a rebuild worked like a charm. Thanks a ton @ryanjbaxter 

Out of the context, I have read your article on the retry http://ryanjbaxter.com/cloud/spring%20cloud/spring/2017/03/15/retrying-http-requests-in-spring-cloud-netflix.html. Whether same configuration holds good for retry with openfeign?

**Comment by ryanjbaxter** [comment]
Yes it should
