### ISSUE TITLE
"core" should not declare "spring-cloud-commons" optional

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2740]
`spring-cloud-netflix-core` requires `spring-cloud-commons` but it is marked as _optional_ in the pom.xml

The dependency is required because of the following annotation on the `ZuulProxyAutoConfiguration` auto configuration (loaded via _spring.factories_):

```
@Import({ RibbonCommandFactoryConfiguration.RestClientRibbonConfiguration.class,
		RibbonCommandFactoryConfiguration.OkHttpRibbonConfiguration.class,
		RibbonCommandFactoryConfiguration.HttpClientRibbonConfiguration.class,
		HttpClientConfiguration.class })
```

--> `HttpClientConfiguration.class` belongs to `spring-cloud-commons`

**Comment by brenuart** [comment]
This case may apply only to versions `1.4.x`.
Most stuff have been moved in separate projects in `2.x`...

**Comment by ryanjbaxter** [comment]
Is there a case where commons will not be on the classpath?  Can you provide a sample POM?

**Comment by brenuart** [comment]
Our use case is a SpringBoot application with Actuator enabled.
We are currently using Servo for metrics and added `spring-cloud-netflix-core` as a dependency to benefit from the servo configuration and utilities. There is no `spring-cloud-starter` involved - probably the reason why `commons` is not pulled.

This may not be a "supported" use case but it highlights the fact that `commons` is actually required and `netflix-core` cannot be used without it. If optional (which it is not), then you have to repeat that dependency in every starter making use of `netflix-core`.

Just wanted to share...
