### ISSUE TITLE
eureka peer awareness, without knowing the host details in advance.

### ISSUE THREAD

**Issue by dulimitta** [spring-cloud/spring-cloud-netflix#2741]
I  could set up Eureka peer awareness on AWS ECS cluster by adding the following configuration.
eureka.client.serviceUrl.defaultZone=http://xxxx:8761/eureka,http://yyyy:8761/eureka 

It is all working well. But whenever I get new servers in ECS, the IPs are changing and forcing me to update the configuration.  Also, I want to rely on ENI or container IPs which are more dynamic. 
So I will not be able to know the server IPs to configure.

Is there a way in Eureka to do this.

**Comment by ryanjbaxter** [comment]
Only thing I can think of is to put the configuration in something like the config server so it can be updated outside of the app.

**Comment by dulimitta** [comment]
Thanks @ryanjbaxter I am on the same approach.
