### ISSUE TITLE
The JerseyReplicationClient of PeerEurekaNode is not a bean and can't be replaced

### ISSUE THREAD

**Issue by MasterColor** [spring-cloud/spring-cloud-netflix#2743]
In my own project, i enabled https with self-signed cert for eureka server.
After I solved the self-signed cert loading problem for dicovery client by overwrite DiscoveryClient.DiscoveryClientOptionalArgs , I found that the eureka servers can't replicate the instance info to each other. 
After checking the log and source code , I found that the JerseyReplicationClient of PeerEurekaNode is not a bean at all , and every instance object of JerseyReplicationClient Attributes is all created by `new` . And in the method `JerseyReplicationClient.createReplicationClient` I didn't see the self-signed cert loading code.
To solve this , I have to import the trust cert into JRE/JDK and add the right host configuration. If not the eureka cluster can only register to each other but can't replicate to each other.
If possible, make the `EurekaJerseyClientBuilder` a bean might make it easier to custumize, just like `DiscoveryClient` and `OkHttpLoadBalancingClient`.

**Comment by ryanjbaxter** [comment]
This all seems to be code within Eureka and not Spring Cloud Netflix.  Maybe I am missing something..

**Comment by MasterColor** [comment]
yes you are right , these classes are within eureka core

**Comment by ryanjbaxter** [comment]
Please open an issue with the Netflix Eureka project then
