### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by brianchan661** [spring-cloud/spring-cloud-netflix#2748]
There are 2 application in project, one is the mirco service application, and the other is the zuul application  

**Frist test case:**

 - Zuul Application run on localhost:8080
 - MyApplication run localhost:8081  

Send request by:  
browser -->  Zuul app --> MyApp  

Result:  
The cookie set correctly before redirect to login controller.  

**Second test case:**  

 - Zuul Application run on localhost:8080
 - MyApplication run AWS server

Send request by:  
browser -->  Zuul app --> MyApp  

Result:  
The cookie is not set , even I saw the cookie is in the response header  

I have tried to set 

    zuul.sensitiveHeader: Cookie,Set-Cookie,Authorization  
But is not working at all.

    // Spring boot application : MyApplication  
    // using spring session for handling login  
    // user post a request, after validation will redirect user to login page  
    @RequestMapping(path = "checkRequest", method = GET)
        public String login(@ModelAttribute("form") LoginForm form) {
            ... // do some validation
            ... // create session
            return "redirect:/login";
    }

    @RequestMapping(path = "login", method = GET)
        public String login(@ModelAttribute("form") LoginForm form) {
            if(!isSessionExist()) {
                return "redirect:/error"
            }
    }

    // Zuul Applcaition  
    // forward incoming request to MyApplication  
    public class ConductorRoutingFilter extends ZuulFilter {
        ...
        @Override
        public String filterType() {
            return "route";
        }
    
        @Override
        public Object run() {
            try {
                CommandContext context = prepareCommandContext();
                Future<HttpCommandResponse> responseFuture = executionManager.submit(context);
                HttpCommandResponse commandResponse = responseFuture.get();
                // update the Location header so the redirection will via the conductor, I set as 8080 / 8081 just for testing zuul on local
                if (commandResponse.getHeaders().get("Location") != null) {
                    commandResponse.getHeaders().set("Location", "http://localhost:8080" + commandResponse.getHeaders().get("Location").get(0).replace("http://localhost:8081", ""));
                }
    
                if (StringUtils.hasText(commandResponse.getResponseStr())) {  RequestContext.getCurrentContext().setResponseBody(commandResponse.getResponseStr());
                } else if (commandResponse.getDataStream() != null) {
                    byte[] data = commandResponse.getDataStream().toByteArray();
                    InputStream inputStream = new ByteArrayInputStream(data);  
                    RequestContext.getCurrentContext().set("zuulResponse", inputStream);
                    this.helper.setResponse(
                            commandResponse.getStatusLine().getStatusCode(),
                            (inputStream),
                            (commandResponse.getHeaders() == null ? new LinkedMultiValueMap<String, String>() : commandResponse.getHeaders())
                    );
                } else {
                    RequestContext.getCurrentContext().set("zuulResponse", commandResponse.getEntity());
                    this.helper.setResponse(
                            commandResponse.getStatusLine().getStatusCode(),
                            (commandResponse.getEntity()),
                            (commandResponse.getHeaders() == null ? new LinkedMultiValueMap<String, String>() : commandResponse.getHeaders())
                    );
                }
    
            } catch (Exception e) {
                ... // some fallback response
                }
            }
            return null;
        }
    }

**Comment by spencergibb** [comment]
You misunderstand zuul.sensitiveHeaders. it's headers that are NOT passed on. Set it to empty

**Comment by brianchan661** [comment]
Thanks for quick reply
Tried to set it as empty, but the cookie is still not set.  
But why the cookie is set if MyApplication is running on localhost?

**Comment by spencergibb** [comment]
That's http. Cookies are only set for a particular domain. Other domains can't see them
