### ISSUE TITLE
2 FeignClient custom configuration conflict

### ISSUE THREAD

**Issue by luny52** [spring-cloud/spring-cloud-netflix#2751]
I have two different feign client class but feign name is same(name = "service-feign")

```java
@FeignClient(name = "service-feign",configuration=ForwardFeignConfiguration.class)
public interface SchedualServiceInfo3 {
	
	@RequestMapping(value = "/info3", method = RequestMethod.GET)
	String info3();
	
	@RequestMapping(value = "/info3", method = RequestMethod.GET)
	String newinfo3(@RequestHeader("Authorization")String  Authorization);
}
```
``` java
@FeignClient(name = "service-feign",configuration=SelfFeignConfiguration.class)
public interface SchedualServiceInfo4 {
	
	@RequestMapping(value = "/info3", method = RequestMethod.GET)
	String info3();
	
	@RequestMapping(value = "/info3", method = RequestMethod.GET)
	String newinfo3(@RequestHeader("Authorization")String  Authorization);
}
```

SchedualServiceInfo3 use the ForwardFeignConfiguration and SchedualServiceInfo4 use the SelfFeignConfiguration,but two all call the same one service(service-feign)

Running results show,two all  use SelfFeignConfiguration

 I try to modify  SchedualServiceInfo3 FeignClient name ,call other service(service-feign2)

than  running results is right(SchedualServiceInfo3 use the ForwardFeignConfiguration and SchedualServiceInfo4 use the SelfFeignConfiguration )

so, Is it necessary to use the same configuration to invoke the same service, Even if the FeignClient class is different?

**Comment by spencergibb** [comment]
We don't support multiple `@FeignClient`s with the same name. See http://cloud.spring.io/spring-cloud-static/Edgware.SR2/single/spring-cloud.html#_creating_feign_clients_manually for creating the clients manually.

**Comment by luny52** [comment]
@spencergibb Thank you very much. I understand.

**Comment by ryanjbaxter** [comment]
No you would still have to create the Feign clients manually
