### ISSUE TITLE
How to mock RequestContext for junit test?

### ISSUE THREAD

**Issue by brianchan661** [spring-cloud/spring-cloud-netflix#2757]
For my PreFilter, I use RequestContext.getCurrentContext() for getting the HttpServletRequest.  
In order to do junit test (I am using JMockit), I need to Mock the RequestContext.  
While I tried with different ways (@Mock RequestContext, @Mockup(RequestContext), etc), but none of them can mock it successfully.  

```
    import com.netflix.zuul.context.RequestContext;


    @Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();
        HttpServletRequest request = context.getRequest();
        ...  doing something with HttpServletRequest  ...
        return null;
    }
```

**Comment by spencergibb** [comment]
Use [`MockHttpServletRequest`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/web/servlet/request/MockMvcRequestBuilders.html) from spring framework.
