### ISSUE TITLE
How to modify request body?

### ISSUE THREAD

**Issue by zhangxsh** [spring-cloud/spring-cloud-netflix#2758]
Question

I use zuul as gateway,in zuul filter I want to rewrite the value,for example;

//value="123"
String value=request.getParameter("keyName");
I want to replace the value into another value in zuul filter,so after the zuul routing,I can get the new changed value.But now I do not know how to do that,there is no way to do,thanks very much

**Comment by Lovnx** [comment]
how to solve this problem?

**Comment by zhangxsh** [comment]
please see https://github.com/spring-cloud-samples/sample-zuul-filters
