### ISSUE TITLE
Ref doc on DiscoveryClient appears out of date

### ISSUE THREAD

**Issue by kennyk65** [spring-cloud/spring-cloud-netflix#276]
This ref doc is slightly out of date:  http://projects.spring.io/spring-cloud/docs/1.0.0/spring-cloud.html#_using_the_discoveryclient

This code here looks like it is old:  

    @Autowired
    private DiscoveryClient discoveryClient;
    
    public String serviceUrl() {
        InstanceInfo instance = discoveryClient.getNextServerFromEureka("STORES", false);
        return instance.getHomePageUrl();
    }

Unless I'm somehow turned around on versions (I'm using spring-cloud-commons-1.0.0.RELEASE.jar), I believe the newer API would be more like this:

    @Autowired DiscoveryClient client;
    public URI serviceUrl() {
        List<ServiceInstance> list = client.getInstances("STORES");
        if (list != null && list.size() > 0 ) {
    	    return list.get(0).getUri();
        }
        return null;
    }

...except there is probably a more elegant way to code that.

**Comment by spencergibb** [comment]
@kennyk65 FYI, the above is the `com.netflix...DiscoveryClient` and below is the spring-cloud `DiscoveryClient`.  Regardless, we need to clean it up, thanks!
