### ISSUE TITLE
[QUESTION] Logging the details of call to downstream services

### ISSUE THREAD

**Issue by benitocm** [spring-cloud/spring-cloud-netflix#2762]
Question

Hi,

We are interested in logging all the requests that Zuul does to all downstream services. We are also interested in that log follows a particular format and its impact in performance is minimum. 
We have seen a class TraceProxyRequestHelper that does something that we are interested in but we dont know to how to change its behavior. An additonal question is if that class is the one that we should care about.

Please could  anybody help on this?

Regards

**Comment by ryanjbaxter** [comment]
You can extend the class.  But since its not conditionally created you would likely have to mark your instance as `@Primary`.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
