### ISSUE TITLE
FeignClientFactoryBean  could set Encoder/Decoder with name and type other than only with type from context ?

### ISSUE THREAD

**Issue by abnerbos** [spring-cloud/spring-cloud-netflix#2763]
Scenes：
     My project need fetch two RPC service from two system which  provide @Configuration class to auto import. Each @Configuration class already define itself  Encoder And Decoder , it's difference class.
Just as:
```
@Configuration
@EnableFeignClients({"xxx.client.spring"})
public class AClientSpringConfig {
    private MappingJackson2HttpMessageConverter jsonConverter;
    @Bean
    public Decoder feignDecoder() {
        ObjectFactory<HttpMessageConverters> objectFactory = () -> {
            return new HttpMessageConverters(false, Lists.newArrayList(new HttpMessageConverter[]{this.jsonConverter}));
        };
        return new ResponseEntityDecoder(new SpringDecoder(objectFactory));
    }
    @Bean
    public Encoder feignEncoder() {
        ObjectFactory<HttpMessageConverters> objectFactory = () -> {
            return new HttpMessageConverters(false, Lists.newArrayList(new HttpMessageConverter[]{this.jsonConverter}));
        };
        return new SpringEncoder(objectFactory);
    }
     @Bean
      public ErrorDecoder feignErrorDecoder() {
        return defaultFeignErrorDecoder();
      }
....
```

After import the two Configuration class, my project startup fail with the error says there is two Encoder bean AClientSpringConfig.feignEncoder and  BClientSpringConfig.feignEncoder .
```
Field XXService in XXX.XXService required a single bean, but 2 were found:
	- feignErrorDecoder: defined by method 'feignErrorDecoder' in XXX.AClientSpringConfig
	- feignErrorDecoder: defined by method 'feignErrorDecoder' in XXX.BClientSpringConfig
```

Matters:
Spent some time to read spring-cloud-netflix code, find the matter code in FeignClientFactoryBean.class:
```
protected Feign.Builder feign(FeignContext context) {
		FeignLoggerFactory loggerFactory = get(context, FeignLoggerFactory.class);
		Logger logger = loggerFactory.create(this.type);

		// @formatter:off
		Feign.Builder builder = get(context, Feign.Builder.class)
				// required values
				.logger(logger)
				.encoder(get(context, Encoder.class))
				.decoder(get(context, Decoder.class))
				.contract(get(context, Contract.class));
		// @formatter:on

		...

		return builder;
	}

	protected <T> T get(FeignContext context, Class<T> type) {
		T instance = context.getInstance(this.name, type);
		if (instance == null) {
			throw new IllegalStateException("No bean found of type " + type + " for "
					+ this.name);
		}
		return instance;
	}
```

in the code, obtain Encoder with the class type from context, cause error where there is more than one.

Suggestion:

According to my understanding, find Encoder should combine with feign name and Encoder.class,just call 
```
public <T> Map<String, T> getInstances(String name, Class<T> type) {
        AnnotationConfigApplicationContext context = this.getContext(name);
        return BeanFactoryUtils.beanNamesForTypeIncludingAncestors(context, type).length > 0?BeanFactoryUtils.beansOfTypeIncludingAncestors(context, type):null;
    }
```

So it can be flexible control by the user.

If due to other considerations do not want to do so, could Make FeignClientFactoryBean class public,so fegin user can override the method .

At last, why  FeignClientFactoryBean is package access ，contain protect method ，and without any son class?

Looking forward to your reply，thanks.

**Comment by ryanjbaxter** [comment]
Would you mind submitting a PR along with a test case for this?

**Comment by ryanjbaxter** [comment]
Also it is fine to submit the PR to this repo if you want it to be fixed in the 1.4.x stream.  However in the master branch the Feign code has been moved to https://github.com/spring-cloud/spring-cloud-openfeign

**Comment by abnerbos** [comment]
The problem has been solved because each feign client Encoder/Decoder is in web auto scan path, so while other feign client use the type get  Encoder/Decoder  will get wrong, thank you for your answer.

**Comment by spencergibb** [comment]
They shouldn't be in the auto scan path as documented

**Comment by abnerbos** [comment]
I ignored the document and chose to find in the code, anyway thank you very much.
