### ISSUE TITLE
eureka.client.eureka-connection-idle-timeout-seconds not correct

### ISSUE THREAD

**Issue by chendurex** [spring-cloud/spring-cloud-netflix#2764]
version：spring-cloud-netflix is 2.0.0.M7 and eureka client is 1.8.6
bug description eureka.client.eureka-connection-idle-timeout-seconds param default value is 30s，but actually is 30000s

**Comment by ryanjbaxter** [comment]
Seems like a bug in `EurekaClientFactoryBuilder` in netflix/eureka.  I think you should open an issue there. https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/shared/transport/EurekaClientFactoryBuilder.java#L53
