### ISSUE TITLE
duplicated create Eureka-JerseyClient-Con-Cleaner task and remove all JerseyClient-Connection

### ISSUE THREAD

**Issue by chendurex** [spring-cloud/spring-cloud-netflix#2765]
version：spring-cloud-netflix is 2.0.0.M7 and eureka-client is 1.8.6

duplicated Eureka-JerseyClient-Con-Cleaner task bug description:when create EurekaClient bean, eureka may create Eureka-JerseyClient-Con-Cleaner task at  com.netflix.discovery.shared.transport.jersey.JerseyEurekaHttpClientFactory class and buildLegacy method. (the code like bellow)And then create two cleaner task ,one at EurekaJerseyClient jerseyClient = clientBuilder.build(), and other at new JerseyEurekaHttpClientFactory(jerseyClient, additionalHeaders);

remove all JerseyClient-Connection bug description:like above bug description,the new JerseyEurekaHttpClientFactory(jerseyClient, additionalHeaders); should has connectionIdleTimeout param,but actually not,and then remove all jerseyClient-Connection when Eureka-JerseyClient-Con-Cleaner task begin running

private JerseyEurekaHttpClientFactory buildLegacy(Map<String, String> additionalHeaders, boolean systemSSL) {
            EurekaJerseyClientBuilder clientBuilder = new EurekaJerseyClientBuilder()
                    .withClientName(clientName)
                    .withUserAgent("Java-EurekaClient")
                    .withConnectionTimeout(connectionTimeout)
                    .withReadTimeout(readTimeout)
                    .withMaxConnectionsPerHost(maxConnectionsPerHost)
                    .withMaxTotalConnections(maxTotalConnections)
                    .withConnectionIdleTimeout((int) connectionIdleTimeout)
                    .withEncoderWrapper(encoderWrapper)
                    .withDecoderWrapper(decoderWrapper);

            if (systemSSL) {
                clientBuilder.withSystemSSLConfiguration();
            } else if (sslContext != null) {
                clientBuilder.withCustomSSL(sslContext);
            }
            
            if (hostnameVerifier != null) {
                clientBuilder.withHostnameVerifier(hostnameVerifier);
            }

            **EurekaJerseyClient jerseyClient = clientBuilder.build();**
            ApacheHttpClient4 discoveryApacheClient = jerseyClient.getClient();
            addFilters(discoveryApacheClient);

            **return new JerseyEurekaHttpClientFactory(jerseyClient, additionalHeaders);**
        }

**Comment by chendurex** [comment]
```
private JerseyEurekaHttpClientFactory buildLegacy(Map<String, String> additionalHeaders, boolean systemSSL) {
            EurekaJerseyClientBuilder clientBuilder = new EurekaJerseyClientBuilder()
                    .withClientName(clientName)
                    .withUserAgent("Java-EurekaClient")
                    .withConnectionTimeout(connectionTimeout)
                    .withReadTimeout(readTimeout)
                    .withMaxConnectionsPerHost(maxConnectionsPerHost)
                    .withMaxTotalConnections(maxTotalConnections)
                    .withConnectionIdleTimeout((int) connectionIdleTimeout)
                    .withEncoderWrapper(encoderWrapper)
                    .withDecoderWrapper(decoderWrapper);

            if (systemSSL) {
                clientBuilder.withSystemSSLConfiguration();
            } else if (sslContext != null) {
                clientBuilder.withCustomSSL(sslContext);
            }
            
            if (hostnameVerifier != null) {
                clientBuilder.withHostnameVerifier(hostnameVerifier);
            }

            EurekaJerseyClient jerseyClient = clientBuilder.build();
            ApacheHttpClient4 discoveryApacheClient = jerseyClient.getClient();
            addFilters(discoveryApacheClient);

            return new JerseyEurekaHttpClientFactory(jerseyClient, additionalHeaders);
        }
```
sorry, the code like above, and it all in netflix/eureka

**Comment by ryanjbaxter** [comment]
If it is all in netflix/eureka please opne an issue there.
