### ISSUE TITLE
Eureka in high-available mode throw exception when they come up.

### ISSUE THREAD

**Issue by thinksky-sourcecode** [spring-cloud/spring-cloud-netflix#2783]
I make it a spring-boot app and enable it as a service-discovery server with Spring-Cloud-Eureka-Server. My purpose is to make it be high-available in 2 instances on 2 different servers. I do it with configuration things and they work well regarding see and sync data. My issue is I always have an exception in the log in starting phase of apps that said me:

> ReplicationTaskProcessor - Network level connection to peer 10.1.69.110; retrying after delay com.sun.jersey.api.client.ClientHandlerException: org.apache.http.conn.ConnectTimeoutException: Connect to 10.2.69.72:12050 timed out

My configuration is:

> eureka.instance.hostname=10.1.50.114
> eureka.client.register-with-eureka=true
> eureka.client.fetch-registry=true
> eureka.client.eureka-connection-idle-timeout-seconds=60
> eureka.client.serviceUrl.defaultZone=10.1.69.110:8761/eureka/

After 2 instances come up and see each other, I don't have it. I think it should have some configurable items that motion to Eureka please wait for another instance based on millisecond.

**Comment by spencergibb** [comment]
I don't think there's much we can do here. The eureka servers are trying to contact each other before the other is up. This all lives in eureka code upstream at the eureka project. Feel free to open an issue there.
