### ISSUE TITLE
Cannot resolve configuration property

### ISSUE THREAD

**Issue by godpit** [spring-cloud/spring-cloud-netflix#2788]
Cannot resolve configuration property 'zuul.host.connect-timeout-millis' and so on, with spring cloud Finchley.M7, i saw the package of the class 'ZuulProperties' is org.springframework.cloud.netflix.zuul.filters, other such as eureka, the package org.springframework.cloud.netflix.eureka. I use development tool :intellij Idea 2018.1 release candidate.
<img width="446" alt="wx20180319-224723 2x" src="https://user-images.githubusercontent.com/34534331/37602799-2364a7c0-2bc8-11e8-8ff0-555fac581b1f.png">

**Comment by spencergibb** [comment]
Duplicates #2782
