### ISSUE TITLE
Configure HystrixContext automatically

### ISSUE THREAD

**Issue by rayenyang** [spring-cloud/spring-cloud-netflix#2791]
I am new to Spring cloud and I try to write a HystrixCollapser demo, but always fail and log:

    java.lang.NullPointerException: null
	at com.netflix.hystrix.HystrixCollapser$3.call(HystrixCollapser.java:398) ~[hystrix-core-1.5.12.jar:1.5.12]
	at com.netflix.hystrix.HystrixCollapser$3.call(HystrixCollapser.java:382) ~[hystrix-core-1.5.12.jar:1.5.12]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[rxjava-1.2.0.jar:1.2.0]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar:1.2.0]

I am using **Edgware.SR2**,my config:

    @EnableCircuitBreaker
    @EnableEurekaClient
    @SpringBootApplication
    public class EurekaClient1Application {
    	
    	@LoadBalanced
    	@Bean
    	public RestTemplate restTemplate() {
    		return new RestTemplate();
    	}
    
    	public static void main(String[] args) {
    		SpringApplication.run(EurekaClient1Application.class, args);
    	}
    }

and HystrixCollapser method:

    @HystrixCollapser(batchMethod = "getAll")
    public Integer get(Integer index) {
        logger.info("invoke getOne !!!!!!!!!!!!");
        return restTemplate.getForObject("http://eureka-client-2/getOne/{1}",Integer.class,index);
    }
    
    @HystrixCommand(fallbackMethod = "getAllError")
    public List<Integer> getAll(List<Integer> indices) {
        logger.info("invoke multi !!!!!!!!!!!!!!!");
        final String ids = indices.toString().replaceAll("\\[|\\]", "");
        return restTemplate.getForObject("http://eureka-client-2/getMulti?ids={1}", List.class, ids);
    }
    
    private List<Integer> getAllError(List<Integer> indices) {
        return Collections.emptyList();
    }

I find that the null value is returned here:

    public class HystrixLifecycleForwardingRequestVariable<T> extends HystrixRequestVariableDefault<T> {
        .....
        .....

        @Override
        public T get() {
            if (!HystrixRequestContext.isCurrentThreadInitialized()) {
                return null;
            }
            return super.get();
        }
    
so I call **HystrixRequestContext.initializeContext();** before my HystrixCollapser method and everything is ok. But I think it should be autoconfigured when I add this dependency: **spring-cloud-starter-netflix-hystrix**, or I am missing something?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
