### ISSUE TITLE
Zull adds the port 80 for Https

### ISSUE THREAD

**Issue by kavinduraisamy** [spring-cloud/spring-cloud-netflix#2794]
The zuul automatically adds the port 80 for https urls, If we add the port 443 in the list of server it execute the request with port 443.
But we required the URI without mentioning the port number. Could you please suggest how to achieve this? Is this possible to override the URI with any filters.

```
zuul.routes.test.path=/test/**
zuul.routes.test.serviceId=test
test.ribbon.listOfServers=https://test.com
```

**Comment by spencergibb** [comment]
This is what `ConfigurationBasedServerList` does by default. I think it's a ribbon problem

**Comment by oldbeee** [comment]
so ,if I don't want use the port 80,how can I do?

**Comment by ryanjbaxter** [comment]
The `listOfServers` should not include the protocol, it just takes the hostname and optionally the port.  If you dont include the port it will make the request on port 80.

**Comment by oldbeee** [comment]
Ok,that is useful
