### ISSUE TITLE
Make Eureka peer awareness work out of the box

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#28]
Eureka peer awareness seems heavily tied to AWS - it only considers apps for registering with peers if it thinks they are not-local, and the way it determines that is through data center info that can only come from AWS APIs.

**Comment by bsushant-athena** [comment]
@dsyer do you have any example repo eureka peer awareness on aws inside a vpc subnet ? 
I'm getting **"failed to bind EIP error".**
