### ISSUE TITLE
How to configure ribbon retries in zuul yml file in Edgeware.SR3 version

### ISSUE THREAD

**Issue by batarayappa** [spring-cloud/spring-cloud-netflix#2800]
Hi ,
I want to configure Ribbon retry logic in zuul config file(yml) with spring cloud Edgeware.SR3 version. Can you please kindly post some sample configuration properties?

Thanks in advance.

Harinath.

**Comment by batarayappa** [comment]
Thanks  you, Ryan. do i need to add below  spring spring retry dependency to enable ribbon retries with Edgeware.SR3 ?
<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
			<version>1.1.5.RELEASE</version>
		</dependency>

**Comment by ryanjbaxter** [comment]
Yes, but you shouldnt need the version as it is a managed dependency from spring boot

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
