### ISSUE TITLE
Eureka Edgware.SR3 exception

### ISSUE THREAD

**Issue by jang675953** [spring-cloud/spring-cloud-netflix#2802]
here is my pom
![default](https://user-images.githubusercontent.com/20883097/38099373-08577e52-33ad-11e8-8ebe-cd371158d757.png)

when I run my app, it occurs such a problem,it seems that is not work well.
![default](https://user-images.githubusercontent.com/20883097/38099248-ac48e312-33ac-11e8-99cb-5b56e982a420.png)

**Comment by jang675953** [comment]
Finchley.M9 and Dalston.SR5 alse do not work

**Comment by jang675953** [comment]
here is the page,it can startup successfully ![default](https://user-images.githubusercontent.com/20883097/38100221-5eb2f46e-33af-11e8-8116-61b04a1a0bce.png)

**Comment by spencergibb** [comment]
Please don't use screenshots. Please include your full pom

**Comment by jang675953** [comment]
[pom.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/1871735/pom.txt)
this is my pom file,but pom.xml is not supported to upload here,I copy it to text.

**Comment by ryanjbaxter** [comment]
This type of problem is almost always a problem in your own environment.  How are you running the app?  Have you tried refreshing the dependencies in your local maven repo?

**Comment by jang675953** [comment]
@ryanjbaxter I have chanded the repo and refresh the local denpendcies,it does not work.I will try again later

**Comment by jang675953** [comment]
when i update local repo,it does not work either.

**Comment by ryanjbaxter** [comment]
It works locally in all of our environments.  If it was an issue we would have seen a number of other people reporting the problem.

**Comment by jang675953** [comment]
All right,do you know which jar caused this? It can not initial the menthioned ftl file

**Comment by ryanjbaxter** [comment]
spring-cloud-netflix-eureka-server

**Comment by jang675953** [comment]
Ok,thank you

**Comment by jang675953** [comment]
@ryanjbaxter @royclarkson  I have solved this problem ,it is caused by the configuration by application.properties.
