### ISSUE TITLE
Zuul fails to forward gzipped response with an empty body when the client does not Accept-Encoding: gzip

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2805]
When the client does not accept gzip encoding, Zuul attempts to uncompress the response received from the downstream service (if compressed).

Unfortunately, it fails with a `500` if the compressed response does not have a body. The exception is thrown by the `SendResponseFilter#writeResponse()` method when it creates a new `GZipInputStream` on the response stream. Since the stream is empty, a `java.io.EOFException` is thrown instead of the only expected `ZipException`.

An easy way to reproduce the issue is to send a HEAD request for which there is no body in the response (as per the spec) as follows:

```
curl -i --head http://localhost:8888/service/info
```

Note there is no `Accept-Encoding: gzip` header in the request.

----
_Tested on Edgware.SR3_

**Comment by brenuart** [comment]
Please note that the problem would not appear if the response had a `Content-Length: 0` header - in this case the SendResponseFilter won't try to un compress the response stream.
Unfortunately, we cannot rely on this head being always present - it is not mandatory and certainly not for HEAD requests which are not expected to have a body in their response.

**Comment by spencergibb** [comment]
so the solution is, if empty response and no `Accept-Engoding: gzip`, don't create `GZipInputStream`?

**Comment by brenuart** [comment]
Yes, I think so. That’s what we did actually. 
To be 100% correct, we try to read a byte from the response stream using a PushbackStream and if fails we set the Content-Length to zero on the RequestContext. This way the current impl does not try to Gunzip it.

**Comment by spencergibb** [comment]
PR?

**Comment by brenuart** [comment]
Sure thing. But in a week when back from holiday if you don’t mind ;-)

**Comment by spencergibb** [comment]
NP, my holiday was last week :smile:.

**Comment by brenuart** [comment]
As written in the PR, I managed to keep the original  behaviour in an efficient way (a single copy of a few bytes only).
