### ISSUE TITLE
Heartbeat, status update, get service list what is the url of eureka server and eureka client object

### ISSUE THREAD

**Issue by yaoyuanyy** [spring-cloud/spring-cloud-netflix#2806]
我正在研究spring cloud eureka的源码，遇到了如下问题：
问题1.  
eureka client的通过周期性任务调用eureka server的信息。如心跳，具体为：eureka client每隔30秒通过AbstractJerseyEurekaHttpClient.sendHeartBeat()方法使用jerseyClient调用eureka server的某个restful接口获取信息，但是我找不到eureka client的heartBeat操作调用的eureka server的restful接口是哪个
问题2.   
eureka client和eureka server的交互通过很多的异步任务来沟通信息，每当我debug某些代码时，任务同时执行，造成我分不清某段代码时哪个任务执行的了，我的头快炸了。
请教各位

**Comment by spencergibb** [comment]
From Google translate

I am studying the source code of spring cloud eureka and encountered the following problems:
Question 1.
The eureka client invokes eureka server information through periodic tasks. For example, the heartbeat, specifically: eureka client uses the jerseyClient to call a restful interface of the eureka server every 30 seconds to obtain information via the AbstractJerseyEurekaHttpClient.sendHeartBeat() method, but I cannot find the restful interface of the eureka server called by the heartbeat operation of the eureka client. Which
Question 2.
The interaction between eureka client and eureka server communicates information through many asynchronous tasks. When I debug some code, the task is executed at the same time, which causes me to distinguish which task is executed when a certain piece of code is executed, and my head is blown up. .
Ask you

-

**Comment by yaoyuanyy** [comment]
对的，对的，我的重点是问题2，eureka client的Heartbeat调的eureka server的restful接口是什么

**Comment by yaoyuanyy** [comment]
我又尝试了一下，好像发现了点线索：AbstractJerseyEurekaHttpClient.sendHeartBeat()-->ApplicationResource.getApplicationResource. 这个调用关系是对的吧 @spencergibb

**Comment by spencergibb** [comment]
From google translate:

Right, right, my focus is question 2, what is the heartbeat of the eureka client and what is the restful interface of the eureka server?

**Comment by spencergibb** [comment]
From google translate:

I tried again, as if to find a clue: AbstractJerseyEurekaHttpClient.sendHeartBeat()-->ApplicationResource.getApplicationResource. This call relationsh
