### ISSUE TITLE
Zuul: HandlerMapping refreshed twice for every HeartbeatEvent

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2807]
When Zuul is running as a _proxy_ (`@EnableZuulProxy`), the`ZuulHandlerMapping` is set dirty twice for every single discovery heartbeat event.

It happens a first time because of `ZuulServerAutoConfiguration#ZuulRefreshListener` and a second time by `ZuulProxyAutoConfiguration#ZuulDiscoveryRefreshListener`.

Both seems to have the same trigger conditions and to serve the same purpose.
Is this expected ?

----
_Tested on Edgware.SR3_

**Comment by ryanjbaxter** [comment]
Nope, not as far as i know

**Comment by brenuart** [comment]
Is this something you’d like a PR for?

**Comment by spencergibb** [comment]
Yes!

**Comment by brenuart** [comment]
The `Server` configuration triggers a refresh for the following events:
- `ContextRefreshedEvent`
- `RefreshScopeRefreshedEvent`
- `RoutesRefreshedEvent`
- `HeartBeatEvent` (but forgot the `ParentHeartbeatEvent`)

The `Proxy` configuration adds support for:
- `ParentHeartbeatEvent`
- `InstanceRegisteredEvent`

According to me, a refresh should occur for all these events for both the _Server_ and _Proxy_ configurations. A single RefreshListener could be used and created by the _Server_ configuration - with nothing special in the _Proxy_ configuration.

Does it sounds correct?
