### ISSUE TITLE
Ribbon: EurekaRibbonClientConfiguration defaults IPing to NIWSDiscoveryPing instead of DummyPing

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2808]
The `EurekaRibbonClientConfiguration` defaults `IPing` to `NIWSDiscoveryPing` instead of `DummyPing` as does the "standard" `RibbonClientConfiguration`.

The later was updated a while ago for the reasons described in #1504. I wonder if the same reasons are applicable for the Eureka case as well...

`NIWSDiscoveryPing` does not perform an actual ping of the target server but instead assumes the server is up if the discovery client says so (UP status in InstanceInfo). Ribbon is already configured to filter instances and to keep only those that are UP - so the "ping" task appears to be useless.

Any reason why a `NIWSDiscoveryPing` is used with Eureka rather than a `DummyPing` ?

**Comment by spencergibb** [comment]
Probably because we were `NIWS`ing all the things :stuck_out_tongue_winking_eye:.

**Comment by spencergibb** [comment]
The impl is not a NOOP, it uses the status from eureka. Not sure we should change that.

**Comment by brenuart** [comment]
Correct. But since the default ServerList (all?) filters and keeps only UP instances it’s about the same as noop. 
Unless some other implementation behave differently of course... 
Changing the IPing may indeed break things in this case. I haven’t look any further I must say.

**Comment by brenuart** [comment]
What feedback would you expect from me ?

**Comment by spencergibb** [comment]
I'm going to close this. I don't think the default should change, because it is not a noop. You can certainly change the default locally.
