### ISSUE TITLE
zuul route rule 

### ISSUE THREAD

**Issue by kofwangshuai** [spring-cloud/spring-cloud-netflix#2809]
The default routing rule of zuul will cause the forwarding request to be in disorder. Incidental！

**Comment by ryanjbaxter** [comment]
Please reopen this issue with a better description of the problem and a sample that reproduces the issue.

**Comment by kofwangshuai** [comment]
thank you!



At 2018-04-02 19:09:23, "Ryan Baxter" <notifications@github.com> wrote:


Please reopen this issue with a better description of the problem and a sample that reproduces the issue.
