### ISSUE TITLE
RibbonClient configuration for one service overrides default configuration for other services

### ISSUE THREAD

**Issue by radubutnaru** [spring-cloud/spring-cloud-netflix#281]
I have run into the following the issue where the RibbonClient config for one client overrides default config for all clients. See below.

Main config class:

    @SpringBootApplication
    @EnableDiscoveryClient
    @EnableCircuitBreaker
    @RibbonClient(name = "products", configuration = ProductsRibbonConfiguration.class)
    public class ProductApp {
        public static void main(String[] args) throws Exception {
            SpringApplication.run(ProductApp.class, args);
        }
    }

'products' Ribbon client configuration class:

    @Configuration
    public class ProductsRibbonConfiguration {
        @Bean
        public IRule ribbonRule() {
            return new RoundRobinRule();
        }
    }

I have two Ribbon clients in the application, invoked via RestTemplate support: the 'products' client configured above, and another non-related 'bestprices' client. Snippets below:

     // Invoking the 'products' client via RestTemplate -> Ribbon       
     restTemplate.getForEntity("http://products/products", Product[].class);

     // Invoking the 'bestprices' client via RestTemplate -> Ribbon       
     restTemplate.getForObject("http://bestprices/bestprices/" + productSku, BestPrice.class);

**Expected behavior**: only 'products' Ribbon client should use a RoundRobinRule. 'bestprices' Ribbon client should use the default rule (ZoneAvoidanceRule).
**Actual behavior**: both 'products' and 'bestprices' Ribbon clients use a RoundRobinRule.

Any thoughts? Anything wrong with the configuration above?

Thank you.

**Comment by spencergibb** [comment]
Nothing looks wrong.  How do you know that they are using different rules?

**Comment by radubutnaru** [comment]
I noticed while debugging, checked the Ribbon LoadBalancer objects under the Spring LoadBalancerClients. Somehow, the same rule type got injected in both.  Should be easy to reproduce, I think.

-----Original Message-----

**Comment by spencergibb** [comment]
I am unable to reproduce.  Do you have something you can share?

**Comment by radubutnaru** [comment]
Uploaded a sample here: https://github.com/radubutnaru/spring-ribbon-config-issue

You would need to run it against an Eureka server with registered Spring Cloud Customers and Stores demo apps (2 instances of each). You may need to tweak the application.yml file. 

The RibbonClient for the 'customers' service is configured to use a RandomRule. The RibbonClient for the 'stores' services picks up the same RandomRule, although the intended behavior is for it to run with the default rule (ZoneAvoidanceRule). This is demonstrated by the stdout output which looks like this in my environment:

    ....
    Chose stores service instance clj-lcpdevsrv02:8081
    Chose stores service instance clj-lcpdevsrv02:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv02:8081
    ...

If I remove or comment out the RibbonClient 'customers' config, stdout output looks like this:

    ...
    Chose stores service instance clj-lcpdevsrv02:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv02:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    Chose stores service instance clj-lcpdevsrv02:8081
    Chose stores service instance clj-lcpdevsrv01:8081
    ...

Does this help?

**Comment by dsyer** [comment]
Yes. Your `CustomersRibbonConfiguration` is being `@ComponentScanned` into the parent context (so it is shared by all ribbon clients). You would need to ditch the `@ComponentScan` or tweak it so it doesn't include your ribbon client or switch the package so it doesn't automatically end up in there. Did I say `@ComponentScan` is evil?

**Comment by radubutnaru** [comment]
OK, that's kind of what I suspected as well. I pushed a fix (exclude filters in ```@ComponentScan```) to the sample repo, works now.

A bit confusing though, maybe this could be cleared up in the documentation somewhere. As you see fit...

Thank you for your help.
