### ISSUE TITLE
Zuul /routes actuator endpoint returning a 404

### ISSUE THREAD

**Issue by natebuwalda** [spring-cloud/spring-cloud-netflix#2813]
I am trying out Zuul along with Eureka.  The version is 2.0.0.M8 from the Finchley.M9 train.  Zuul is set to run on port 10002.  When running on my local machine, when I go to http://localhost:10002/routes, per the documentation, I get a 404 response.  This appears to be functional on the prior release train version Edgware.SR3.  Has there been a change to this functionality?  Is there any additional configuration needed to expose this endpoint beyond having Actuator on the classpath.  Below are my current configurations:

```
@SpringBootApplication
@EnableDiscoveryClient
@EnableZuulProxy
@RibbonClients(defaultConfiguration = RibbonConfiguration.class)
public class ZuulSandboxApplication {

	public static void main(String[] args) {
		SpringApplication.run(ZuulSandboxApplication.class, args);
	}

}
```
```
public class RibbonConfiguration {
    @Bean
    public IPing ribbonPing(final IClientConfig config) {
        return new PingUrl(false,"/health");
    }

    @Bean
    public IRule ribbonRule(final IClientConfig config) {
        return new AvailabilityFilteringRule();
    }
}
```
```
server.port=10002

spring.application.name=zuul-sandbox
spring.jackson.serialization.indent-output=true

eureka.client.service-url.defaultZone=http://localhost:10001/eureka
        
# ZUUL ROUTES GO HERE
zuul.strip-prefix=true
zuul.prefix=/api
zuul.routes.ping.serviceId=ping-microservice

# Logging if you need it
logging.level.com.netflix=DEBUG
```

Thanks for the assistance.

**Comment by spencergibb** [comment]
It's now at /actuator/routes and needs to be enabled. See the migration guide https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints

**Comment by natebuwalda** [comment]
Thanks for the guidance.

**Comment by ryanjbaxter** [comment]
Please open a separate issue.
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Chaitanya199102** [comment]
Think in spring 2.0 they changed the path to /actuator/routes.
The following configuration helped
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: info, health, routes

**Comment by claudio-ranieri** [comment]
You can view route details in Zuul 2 with:

/actuator/routes/details
