### ISSUE TITLE
RequestContentDataExtractor#extractFromMultipartRequest removes same named query param from form params 

### ISSUE THREAD

**Issue by ypg521** [spring-cloud/spring-cloud-netflix#2815]
[code sample ](https://github.com/ypg521/zuul)

I have a request that the request path and the post body both have a parameter named 'uid'; like this:
```shell
curl -X POST \
  'http://127.0.0.1:8089/test?uid=123456' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F uid=123456
  -F 'photo=@/test.jpg' 
```

But RequestContentDataExtractor#extractFromMultipartRequest (line 68) always remove one of the parameters named uid that in post body

**Comment by ryanjbaxter** [comment]
Please provide a sample that reproduces the issue.

**Comment by ypg521** [comment]
I updated commented

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

That is not a sample.  Put the complete working code in a GItHub repo or attach it to the issue as a zip.

**Comment by dev-priporov** [comment]
I've reproduced this issue [here](https://github.com/dev-priporov/spring-cloud-netflix-issue-2815)
