### ISSUE TITLE
prefer-ip-address and non-secure-port config is ignored when adding sidecar as a dependency

### ISSUE THREAD

**Issue by ImranAdan** [spring-cloud/spring-cloud-netflix#2817]
We have a sample Eureka server and two eureka clients. In one client we add the sidecar as an additional dependency. In both project we specify the following config:

-	eureka.instance.prefer-ip-address = true 
-	eureka.instance.non-secure-port = any_int (bounded)

When the instances are registered with Eureka, the non-sidecar instance registers using the IP address and the non-secure-port, this is the behaviour we expect and the behaviour we want. 

When the sidecar instance is registered it registers using the hostname and the server port. This is a default behaviour of a typical eureka client, we do not want this as we have specified the instance to prefer using IP address in addition the non-secure port. 

The question becomes, why is it when the sidecar is added as a dependency the eureka client ignores the  prefer-ip-address and the non-secure-port configuration? 

We have provided a sample application here, we are using the same pom across all the clients, except in one we provide the sidecar as an additional dependency: https://github.com/ImranAdan/SidecarIpPortIssue

Please do let us know if you need any further information

Additional information (Which may be useful):  

-	A similar question was asked but closed without no resolution: https://github.com/spring-cloud/spring-cloud-netflix/issues/2272
-	Seems that there is some work that has been done with setting sidecar.hostname but this doesnot solve the issue of perfering IP address and a non-secure-port: https://github.com/spring-cloud/spring-cloud-netflix/issues/981 

Seems that SidecarConfiguration sets the nonsecure port using an autowired SidecarProperties, it seems that this happens at `org.springframework.cloud.netflix.sidecar.SidecarConfiguration$EurekaInstanceConfigBeanConfiguration` but the `SidecarProperties` does not except non secure port also seems that there is no way to prefer IP address in there?

Many Thanks

**Comment by ImranAdan** [comment]
Seems that `SidecarConfiguration` sets the nonsecure port, it seems that this happens at ``org.springframework.cloud.netflix.sidecar.SidecarConfiguration$EurekaInstanceConfigBeanConfiguration``

**Comment by spencergibb** [comment]
you need to use `sidecar.port`, `sidecar.hostname` and `sidecar.ip-address`. Using those, `eureka.instance.prefer-ip-address` works.

**Comment by ImranAdan** [comment]
@spencergibb After upgrading the sidecar version to `1.4.4.RELEASE` We were able to access the config `sidecar.hostname` and the `sidecar.ip-address` and this works with `eureka.instance.prefer-ip-address` however it does not solve the issue of setting the non-secure port. 

**For example**, we have the following config:

```
eureka.instance.non-secure-port-enabled=true
eureka.instance.non-secure-port=8523
sidecar.ip-address=192.168.0.107
sidecar.hostname=192.168.0.107
sidecar.port=5000
```

The sidecar app always seems to default to 8080 which is the `server.port`. In the service registry the Eureka the client is advertised with IP Address `192.168.0.107:8080`. We would like this to be `192.168.0.107:8523` 

When we set the non-secure port as `eureka.instance.non-secure-port=8523`, when we look at the apps fro Eureka using `/eureka/app` we get the following XML which does not contain any mention of the non-secure port, it shows the port to be 1234 


```

<application>
--
  | <name>SIDECAR</name>
  | <instance>
  | <instanceId>ip-192-168-0-107.eu-west-1.compute.internal:Sidecar</instanceId>
  | <hostName>192.168.0.101</hostName>
  | <app>SIDECAR</app>
  | <ipAddr>192.168.0.101</ipAddr>
  | <status>DOWN</status>
  | <overriddenstatus>UNKNOWN</overriddenstatus>
  | <port enabled="true">1234</port>
  | <securePort enabled="false">443</securePort>
  | <countryId>1</countryId>
  | <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
  | <name>MyOwn</name>
  | </dataCenterInfo>
  | <leaseInfo>
  | <renewalIntervalInSecs>30</renewalIntervalInSecs>
  | <durationInSecs>90</durationInSecs>
  | <registrationTimestamp>1522923952871</registrationTimestamp>
  | <lastRenewalTimestamp>1522923952871</lastRenewalTimestamp>
  | <evictionTimestamp>0</evictionTimestamp>
  | <serviceUpTimestamp>0</serviceUpTimestamp>
  | </leaseInfo>
  | <metadata class="java.util.Collections$EmptyMap"/>
  | <homePageUrl>http://192.168.0.107:5000/</homePageUrl>
  | <statusPageUrl>http://192.168.0.107:8080/info</statusPageUrl>
  | <healthCheckUrl>http://192.168.0.107:8080/health</healthCheckUrl>
  | <vipAddress>Sidecar</vipAddress>
  | <secureVipAddress>Sidecar</secureVipAddress>
  | <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
  | <lastUpdatedTimestamp>1522923952871</lastUpdatedTimestamp>
  | <lastDirtyTimestamp>1522923952866</lastDirtyTimestamp>
  | <actionType>ADDED</actionType>
  | </instance>
  | </application>

```
