### ISSUE TITLE
Unable to access version.properties in spring cloud Finchley.M8 and springboot 2.0.0.RELEASE

### ISSUE THREAD

**Issue by batarayappa** [spring-cloud/spring-cloud-netflix#2818]
Hi All,

I'm not able to access properties of  version.properties with Finchley.M8 and springboot 2.0.0.RELEASE. This is working fine with all versions of Edageware and previous releases. I'm adding version.properties to @PropertySource Annotation.  Can please help me ?

@PropertySource("classpath:version.properties")

Thanks in advance.

**Comment by spencergibb** [comment]
Property source is not from spring cloud

**Comment by spencergibb** [comment]
It's a framework question. See http://jira.spring.io
