### ISSUE TITLE
Add eureka.client.healthcheck.enabled property to META-INF/additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-netflix#2819]
Enhancement

Currently `eureka.client.healthcheck.enabled` is a hidden property that can be known to be present only by looking at code.

It would much more helpful if this property is added to `META-INF/additional-spring-configuration-metadata.json`. This way, IDEs can show the suggestions by reading the metadata

**Comment by dheerajkulakarni** [comment]
Hey @thekalinga @ryanjbaxter , is this not solved already? I can see this property is already been added in clients additional-spring-configuration-metadata.json
 https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/resources/META-INF/additional-spring-configuration-metadata.json

**Comment by ryanjbaxter** [comment]
Yup thanks for pointing that out!
