### ISSUE TITLE
changing request URI in custom zuul route filter

### ISSUE THREAD

**Issue by momentum123** [spring-cloud/spring-cloud-netflix#2823]
hi @ryanjbaxter @spencergibb @Aloren 

im using follwing custom zuul filter for re routing my request to a new host and request uri but new request uri is not getting appended and using the original one .

`
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

import org.springframework.cloud.netflix.zuul.filters.support.FilterConstants;
import org.springframework.stereotype.Component;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;

@Component
public class VersionBasedFilter extends ZuulFilter {

	@Override
	public boolean shouldFilter() {
		return true;
	}

	@Override
	public Object run() {
		RequestContext ctx = RequestContext.getCurrentContext();
		HttpServletRequest request = ctx.getRequest();
		URL previousrouteHost = ctx.getRouteHost();
		Object serviceId=ctx.get("serviceId");
	    String previousUri = request.getRequestURI();
	    String contextUri=(String) ctx.get("requestURI");
	    
	 
	    
	    if (previousUri!=null && isFilterRequiredForIam(previousUri)) {
	    	 try {
	    		String newRequestUri = previousUri.replace("/iam/api/v2.0", "");
				ctx.setRouteHost(new URL("https://localhost:10091"));
				ctx.put("requestURI", newRequestUri);
			} catch (IOException e) {
				
			}
	    	 
	    	 System.out.println("url------------------------"+ctx.getRequest().getRequestURL().toString());
	      }
	    
	    else if(previousUri!=null && isFilterRequiredFor(previousUri)){
	    	
	    	ctx.set("serviceId", serviceId.toString()+"V2");
	    }
	      return null;
	}

	@Override
	public String filterType() {

		return "route";
	}

	@Override
	public int filterOrder() {
		return FilterConstants.PRE_DECORATION_FILTER_ORDER -100;
	}
	
	private boolean isFilterRequiredForIam(String uri){
		if(uri.contains("iam/api/v2.0"))
		return true;
		else
		return false;
	}
	
	private boolean isFilterRequiredFor(String uri){
		if(uri.contains("api/v2.0"))
		return true;
		else
		return false;
	}

}`

but in sysout URL still shows original one not the new one .I have tried setting request uri using
`	request.setAttribute("requestURI", newRequestUri);
	ctx.setRequest(request);`

but none of the things i have tried seem to be working

**Comment by aneira** [comment]
Has anyone worked on overwriting the requestURI?
I tried to remove /prepath 
Original Request to zuul
https://localhost:8081/prepath/customers/...

I need to
https://localhost:8081/customers/...

``
RequestContext ctx = RequestContext.getCurrentContext();
String newRequestURI = urlPathHelper.getPathWithinApplication(ctx.getRequest()).replaceFirst("/prepath", "");
ctx.set("requestURI", newRequestURI);

**Comment by indraneelb1903** [comment]
You don't need to overwrite. What are your zuul properties?

**Comment by indraneelb1903** [comment]
zuul strips prefix by default. So 
https://localhost:8081/prepath/customers/...
will be forwarded as 
https://localhost:8081/customers/...

**Comment by aneira** [comment]
I need the forwarded  in some environments
For example 

**DEV environment**
https://localhost:8081/customers/...   -> https://localhost:8081/customers/...  
https://localhost:8081/activation/...   -> https://localhost:8081/activation/...  
https://localhost:8081/checklist/...    -> https://localhost:8081/checklist/...  

**UAT environment**
https://localhost:8081/prepath/customers/...   -> https://localhost:8081/customers/...  
https://localhost:8081/prepath/activation/...   -> https://localhost:8081/activation/...  
https://localhost:8081/prepath/checklist/...    -> https://localhost:8081/checklist/...  

This is my zuul properties :
``
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:

    activation:
        path: /activation/**
        serviceId: activation-service
        stripPrefix: false

    customer:
        path: /customer/**
        serviceId: customer-service
        stripPrefix: false

    checklist:
        path: /checklist/**
        serviceId: checklist-service
        stripPrefix: false

    product:
        path: /product/**
        serviceId: product-service
        stripPrefix: false

**Comment by indraneelb1903** [comment]
You have different property files for dev and uat right? In dev, you can set stripPrefix to false, and in uat, stripPrefix is true.

**Comment by aneira** [comment]
Thank you @indraneelb1903 . It worked.

I attach the solution for others who need


**For dev**
application.properties
zuul.prefix=prePath

**For uat**
application.properties
zuul.prefix=

```
zuul:
sensitive-headers: Cookie,Set-Cookie
prefix: ${zuul.prefix}
routes:

activation:
    path: /activation/**
    serviceId: activation-service
    stripPrefix: false

customer:
    path: /customer/**
    serviceId: customer-service
    stripPrefix: false

checklist:
    path: /checklist/**
    serviceId: checklist-service
    stripPrefix: false

product:
    path: /product/**
    serviceId: product-service
    stripPrefix: false

```
