### ISSUE TITLE
Zuul: unexpected prefix and path merging

### ISSUE THREAD

**Issue by Toparvion** [spring-cloud/spring-cloud-netflix#2825]
#2625 (Normalize Zuul Prefix) introduced automatic `/` removal from the end of `zuul.prefix`. But it also introduced a side effect. When I used version 1.3.5 I had a configuration like this:
```
zuul.prefix=/api/
zuul.strip-prefix=false

zuul.routes.compass.path=v*/mcbp/**
zuul.routes.compass.strip-prefix=false
# and 10+ similar routes
```
which worked fine just as expected: simple concatenation of  `/api/` and `v*/mcbp/**` yielded 
    `/api/v*/mcbp/**` 
(correct) route. But after upgrading to 1.4.0 (which included #2625) this route turned to    
`/apiv*/mcbp/**`
(incorrect) route.

I found that stripping the `/` from the end of `zuul.prefix` (optionally) and adding it to beginning of each route:
```
zuul.prefix=/api
zuul.strip-prefix=false
zuul.routes.compass.path=/v*/mcbp/**
zuul.routes.compass.strip-prefix=false
```
solves the problem. But it seems not very convenient and straightforward solution.

Is this new behavior correct?

**Comment by ryanjbaxter** [comment]
I guess in 1.3.x you needed to be consistent.  For example if you did this it would break as well.

```
zuul.prefix=/api/
zuul.strip-prefix=false

zuul.routes.compass.path=/v*/mcbp/**
zuul.routes.compass.strip-prefix=false
```

#2625 now makes it consistent where that the routes path must always start with a `/`.

**Comment by Toparvion** [comment]
It appears that I caught a break with such a configuration that I used before. 
@ryanjbaxter, ok, I'll prepend all the routes with leading `/` and remove it from `zuul.prefix` ending.
Thank you!
