### ISSUE TITLE
使用Zuul  GET请求 中文参数 GBK 编码时乱码

### ISSUE THREAD

**Issue by andysofan** [spring-cloud/spring-cloud-netflix#2828]
Question

当使用spring zuul时，请求数据 GET方式 ，参数为中文，
系统在默认过滤器 Servlet30WrapperFilter、RibbonRoutingFilter 中

调用 ：HTTPRequestUtils.getQueryParams()  方法：
在getQueryParams 方法中会对GET请求参数解码处理 （URLDecoder.decode(value, "UTF-8")）
路由完成后，接收到参数无法解码。

Bug report

原始中文参数 ： 10012442782n你大爷的
GET请求 URLEncoder GBK 编码为 ： 10012442782n%C4%E3%B4%F3%D2%AF%B5%C4
spring接收到的参数值： 10012442782n%EF%BF%BD%EF%BF%BD%EF%BF%BD%D2%AF%EF%BF%BD%EF%BF%BD

**Comment by ryanjbaxter** [comment]
Via Google Translate

> Question
>
>When using spring zuul, request data GET mode, the parameter is Chinese,
>The system is in the default filter Servlet30WrapperFilter, RibbonRoutingFilter
>
>Call :HTTPRequestUtils.getQueryParams() method:
>Decode the GET request parameter in the getQueryParams method (URLDecoder.decode(value, "UTF-8"))
>After the route is completed, the received parameters cannot be decoded.
>
>Bug report
>
>Original Chinese Parameter : 10012442782n Your Uncle's
>The GET request URLEncoder GBK is encoded as: 10012442782n%C4%E3%B4%F3%D2%AF%B5%C4
>Parameters received by spring: 10012442782n%EF%BF%BD%EF%BF%BD%EF%BF%BD%D2%AF%EF%BF%BD%EF%BF%BD

**Comment by ryanjbaxter** [comment]
Can you provide the stacktrace?

**Comment by ryanjbaxter** [comment]
Closing due to lack or requested information
