### ISSUE TITLE
Config server with Eureka

### ISSUE THREAD

**Issue by ctatineni** [spring-cloud/spring-cloud-netflix#283]
When i run config server with Eureka, below logs are getting generated, is there any configuration i need to set to skip this logging.

10140 --- [pool-5-thread-1] arshallingStrategy$SetVersionInterceptor : Applications.setVersion() called with version: 108

**Comment by dsyer** [comment]
There's no obvious problem with 1 line of logs. Can you post a bit more and explain what the problem is? The config server samples in spring-cloud-samples all have eureka in them I think.

**Comment by spencergibb** [comment]
I know that log statement, it is just printed many times.  Looking at the source, though, it is `log.debug`.  Turn debugging off and that should go away.
