### ISSUE TITLE
Zuul: no Content-Length in client response when both request and upstream are gzip

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2832]
Zuul *never* includes the `Content-Length` header in the client response if upstream is gzipped.

See lines: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java#L243-L248

However, I see no reason not to forward the Content-Length header if present on a gzipped upstream response if the client accepts Gzip too.
What you think ?

**Comment by ryanjbaxter** [comment]
Yeah I agree not sure why we wouldnt include it

**Comment by brenuart** [comment]
Want a PR for it ?
