### ISSUE TITLE
Are there some examples to show how to use them?

### ISSUE THREAD

**Issue by kaifuluca2016** [spring-cloud/spring-cloud-netflix#2835]
I build them by ./mvnw clean install. It can generate executable jar. But it can not run, because they didn't include the main method in several projects. I want to know if it can become to the Samples or where I can find the samples about it. Or where are the entry points? I hope to reactive with the projects in the spring-cloud-netflix.
Thanks!
Alan
![how to run them](https://user-images.githubusercontent.com/22335946/38575868-736d8be8-3cca-11e8-85b9-66b9ca4f6e88.jpg)

**Comment by ryanjbaxter** [comment]
Right these are libraries not executable jobs.  If you are looking for samples check out https://github.com/spring-cloud-samples
