### ISSUE TITLE
Zuul - error page problem with default route

### ISSUE THREAD

**Issue by mariusznet** [spring-cloud/spring-cloud-netflix#284]
Configuring default route (i.e. zuul.route.home: /** ) breaks error page mechanism when exception is thrown from zuul application. 
For example, using spring security, if path /** requires auth exception is thrown, but processing /error page is forwarded to home service. There is no exception details in request attributes in home service, so as a result error page with response status 500 is returned.

As a workaround (not the best one I think) disabling ErrorMvcAutoConfiguration and fallback to default container method works.

**Comment by dsyer** [comment]
Sorry, I didn't quite understand the example you gave. Can you provide a test project (e.g. on github)?

**Comment by mariusznet** [comment]
Sure, sorry for being unclear. 
https://github.com/mariusznet/spring-cloud-zuul-error

To test this issue after running project just hit localhost without credentials. Instead of 403 error page you should see 404 page fetched from /** route.

**Comment by dsyer** [comment]
The 404 you are seeing is from "http://watchrabbit.com/error". It looks weird, but it makes some sense, since you have a default route and it is blocking the /error page in Spring Boot. I'll have a think about what the best approach is.
