### ISSUE TITLE
Zuul: close Ribbon client when corresponding route is discarded

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2840]
Recent versions of Zuul automatically remove auto-discovered routes when the corresponding service is no longer registered in the service registry.

However, the corresponding Ribbon client and its associated spring app context is not destroyed and remains alive forever. Each ribbon client maintains a couple of threads for their housekeeping and continue to produce useless metrics...

Hence the question: don't you think we should close the Ribbon client when the corresponding route is removed ?

**Comment by spencergibb** [comment]
Seems like a decent idea.

**Comment by brenuart** [comment]
This would require some changes on the SpringClientFactory to force a close of a named context or get access to it.
Any objection?

**Comment by spencergibb** [comment]
No objection. It would get auto created later if it comes back.

**Comment by brenuart** [comment]
The factory is in spring-cloud-commons AFAIK (i am on my phone atm and no access to source code).
How can I submit a single PR on two projects?
Or should I open another issue against common and a PR there?

**Comment by spencergibb** [comment]
just open a PR in commons and reference this issue.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
