### ISSUE TITLE
Zuul: warmup Ribbon client when a new service is discovered

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#2841]
(feature request)

What about warming up the Ribbon client automatically when a a new service is discovered and the corresponding route published ?
This way the client would be ready when the first request hits the route.

This feature is similar to the eager loading of ribbon clients but for Zuul discovered routes.

What you think ?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
