### ISSUE TITLE
Zuul /routes endpoint issue with consul registered services.

### ISSUE THREAD

**Issue by rajashekar2014** [spring-cloud/spring-cloud-netflix#2842]
Zuul's /routes endpoint, with the default configuration in application.yml, returns {}, for successfully registered services in consul.

Zuul Service
==========
@EnableZuulProxy
@SpringBootApplication
@EnableDiscoveryClient
public class GatewayApplication {

See this in Gateway logs, ``` 2018-04-12 22:25:04.700  WARN 41888 --- [nio-8080-exec-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator```

Sample Service Registering successfully to consul
=============================
@EnableDiscoveryClient
@RestController
@SpringBootApplication
public class BookApplication {

  @RequestMapping(value = "/available")
  public String available() {
    return "Spring in Action";
  }
<img width="804" alt="screen shot 2018-04-12 at 11 28 12 pm" src="https://user-images.githubusercontent.com/5948495/38719934-39334568-3ea9-11e8-8039-db2dce5d1195.png">

/routes is returning the data, only if the route is explicitly configured...

```
zuul:
  routes:
    book:
      path: /book/**
      serviceId: book
```

Any help would be appreciated... Thank you.

**Comment by spencergibb** [comment]
Can you check with the latest versions and see if this is still an issue?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
