### ISSUE TITLE
Ribbon okhttp: Naming convention error

### ISSUE THREAD

**Issue by radtriste** [spring-cloud/spring-cloud-netflix#2844]
Bug report
Impacted: Spring Cloud Netflix 1.4.x

There is a slight naming convention error into the class:
org.springframework.cloud.netflix.ribbon.okhttp.OkHttpRibbonConfiguration

okHttpLoadBalancingClient and retryableOkHttpLoadBalancingClient have been switch and are not consistent with the return type.

See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-ribbon/src/main/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpRibbonConfiguration.java

**Comment by holy12345** [comment]
@radtriste Yeah, I think it looks like just need to change the method name.
