### ISSUE TITLE
when I use STS develop a Feign-Service,the service is closing,throwing org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration

### ISSUE THREAD

**Issue by jiyong101** [spring-cloud/spring-cloud-netflix#2848]
when I use STS develop a Feign-Service,if I do what it is a run-as Spring-boot-App。the console will show a error this it is a exception:
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaAutoServiceRegistration': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
but I do what it is a run-as Java Application，the error is nothing.
I don't understand what the reason is.,please help me

**Comment by ryanjbaxter** [comment]
Please dont open issues in multiple repos.  (This is the correct repo by the way but see my answer here https://github.com/spring-cloud/spring-cloud-openfeign/issues/18 and here https://github.com/spring-cloud/spring-cloud-openfeign/issues/19)
