### ISSUE TITLE
[question]Is there no timeout for getting a HTTP connection in SimpleHostRoutingFilter?

### ISSUE THREAD

**Issue by jadetang** [spring-cloud/spring-cloud-netflix#2851]
I am using the `SimpleHostRoutingFilter`. 
I noticed that the default `connectionRequestTimeout` is -1 which means no timeout when application try to get a HTTP connection from the HTTP client pool. So if there is no available connection in the pool, the application will stuck?

**Comment by ryanjbaxter** [comment]
This all might depend on the app we need more information.  Are you providing an `HttpClient` bean in your app or are you just using the default spring cloud netflix communication.  As far as I can see all the timeouts have values.

**Comment by jadetang** [comment]
no, I just use the default SimpleHostRoutingFilter and the Apache HTTP Client.

**Comment by spencergibb** [comment]
Indeed that is missing configuration.

**Comment by spencergibb** [comment]
> A negative value is interpreted as undefined (system default).
