### ISSUE TITLE
Create a page with all properties of spring cloud

### ISSUE THREAD

**Issue by pochadri** [spring-cloud/spring-cloud-netflix#286]
it would be great help if all the properties that are used in spring cloud project are listed at one location like done for spring boot 

http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

**Comment by dsyer** [comment]
The data are available (http://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html). If anyone wants to autogenerate a docs appendix that would be awesome.

**Comment by kakawait** [comment]
@dsyer there is an existing tools for generating such documentation from configuration-metadata?

**Comment by dsyer** [comment]
The existing tools generate JSON (which is in the jar files). All we need is an extra step to turn it into docs.

**Comment by kakawait** [comment]
but should we extends existing tool (suppose to be `spring-boot-configuration-processor`) or create external tool to generate documentation?

**Comment by dsyer** [comment]
I would have thought it makes sense to post process the output of the existing tool. I believe @snicoll had something he was using.

**Comment by snicoll** [comment]
I do and I could contribute a PR if you like. There are two versions of that generator for now. Once that run as a Groovy script and can be integrated in the doc generation. I have also a [standalone boot app that can generate the appendix](https://github.com/snicoll-scratches/spring-boot-config/blob/master/spring-boot-config-diff/src/main/java/net/nicoll/boot/config/diff/AppendixGenerator.java). I also use that project to generate the [diffs on the wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-Configuration-Changelog)

**Comment by dsyer** [comment]
Yes, please.

**Comment by herau** [comment]
@snicoll @dsyer any news about this topic ?

**Comment by OrangeDog** [comment]
@dsyer Not all properties are listed there though.
For example, any ribbon/niws properties with the client name in the path, or properties read only via archaius.

**Comment by dsyer** [comment]
Sure, we can only list the `@ConfigurationProperties` automatically. The native Archaius ones remain buried in Netflix OSS (and documented in their wikis).
