### ISSUE TITLE
RibbonLoadBalancerClient.reconstructURI() cannot utilize EurekaServerIntrospector

### ISSUE THREAD

**Issue by sunruh** [spring-cloud/spring-cloud-netflix#2860]
`RibbonLoadBalancerClient.reconstructURI()` creates a new `Server` instance which is passed to `RibbonUtils.updateToSecureConnectionIfNeeded()` together with the `ServerIntrospector` instance.

When `updateToSecureConnectionIfNeeded()` tries to determine whether to secure an URI or not it calls the `ServerIntrospector.isSecure()` with the new `Server` object.

`EurekaServerIntrospector.isSecure()` would check a servers `InstanceInfo` whether the secure port is enabled or not only if the `Server` is an instance of `DiscoveryEnabledServer` which is not the case as `reconstructURI()` created a new "basic" instance. It therefore falls back to `DefaultServerIntrospector.isSecure()` which determines secureness based on property `ribbon.securePorts`.

`RibbonLoadBalancerClient.reconstructURI()` should be able to utilize the `EurekaServerIntrospector.isSecure()` functionality to be consistent with other calls to `RibbonUtils.updateToSecureConnectionIfNeeded()`

**Comment by spencergibb** [comment]
Good catch

**Comment by spencergibb** [comment]
hmm, we'll have to think about that. `RibbonLoadBalancerClient` doesn't know (and can't know) about any eureka classes.

**Comment by sunruh** [comment]
That's true, it must never be coupled to Eureka classes, but it should on the other hand let the introspector do it's work. `execute()` and `choose()` of `RibbonLoadBalancerClient` all work with or return instances of `RibbonServer` which carries a reference to the "original" `Server` object coming from a call to `ILoadBalancer.chooseServer()` that's of the correct type. Can't that "original" instance be used instead of creating a new `Server` or `ServiceInstance.isSecure()` be utilized instead?

**Comment by spencergibb** [comment]
a `EurekaServiceInstance` never has a `Server`

**Comment by sunruh** [comment]
But what is the reason for not using `ServiceInstance.isSecure()` which would carry the correct information, too, in case of a `RibbonServer`?

**Comment by spencergibb** [comment]
Yup, if using a `RibbonServer` all that logic has already been called.

**Comment by sunruh** [comment]
This fixes it.

I had a quick look at other locations in Spring Cloud that call `new Server(String, int)`. It looks to me as if `spring-cloud-openfeign`'s [`RetryableFeignLoadBalancer`](https://github.com/spring-cloud/spring-cloud-openfeign/blob/f4fc53185796a6286c9a1e377fdab7b0c1fb3c8d/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/ribbon/RetryableFeignLoadBalancer.java#L97) has the same issue. What is your opinion?
