### ISSUE TITLE
Zuul leaves connections in CLOSE_WAIT 

### ISSUE THREAD

**Issue by honnel** [spring-cloud/spring-cloud-netflix#2863]
## Bug report

Since we updated from Spring Cloud Edgware.SR1 to Edgware.SR3, our service gateway (zuul) leaves connection in CLOSE_WAIT state. These connections stays in CLOSE_WAIT for several hours and get cleaned randomly by something we actually don't know (looks like gc but strange time interval for gc). These symptoms take place one time a day without correlation of load.
The orphaned connections are between service gateway and service instances behind the gateway.

![bildschirmfoto 2018-04-18 um 13 37 21](https://user-images.githubusercontent.com/142107/38929797-d42caf88-430d-11e8-8ee4-f3d9f547a71d.png)

We are using Spring Cloud Edgware.SR3 which includes 
* org.springframework.cloud:spring-cloud-starter-zuul:jar:1.4.4.RELEASE
* org.springframework.cloud:spring-cloud-starter-netflix-zuul:jar:1.4.4.RELEASE
* com.netflix.zuul:zuul-core:jar:1.3.0

In addition we are using eureka for service discorvery, hystrix and ribbon are configured.

With `netstat | grep CLOSE_WAIT` we got hundreds of:
```
tcp6       1      0 gateway:54156 service1:http CLOSE_WAIT
tcp6       1      0 gateway:58621 service2:http CLOSE_WAIT
tcp6       1      0 gateway:47217 service3:http CLOSE_WAIT
tcp6       1      0 gateway:54130 service4:http CLOSE_WAIT
tcp6       1      0 gateway:58012 service5:http CLOSE_WAIT
tcp6       1      0 gateway:46395 service3:http CLOSE_WAIT
tcp6       1      0 gateway:36399 service1:http CLOSE_WAIT
tcp6       1      0 gateway:39363 service2:http CLOSE_WAIT
tcp6       1      0 gateway:46317 service3:http CLOSE_WAIT
tcp6       1      0 gateway:57752 service3:http CLOSE_WAIT
tcp6       1      0 gateway:39398 service1:http CLOSE_WAIT
...
```

**Comment by brenuart** [comment]
This looks similar to #2831
A PR has been submitted and a temporary workaround is mentioned at the bottom of the thread.

**Comment by spencergibb** [comment]
Closing as a duplicate
