### ISSUE TITLE
feign.RequestInterceptor  BasicAuthRequestInterceptor not working - Not setting the Authorization Header

### ISSUE THREAD

**Issue by nikhilabhiman** [spring-cloud/spring-cloud-netflix#2865]
Hi team,

I followed the below link to implement interceptor for Feign Client
https://stackoverflow.com/questions/40262132/how-to-add-a-request-interceptor-to-a-feign-client

I added even

@Bean
public RequestInterceptor basicAuthRequestInterceptor {
    return new BasicAuthRequestInterceptor("username", "password");
}

But Authorization Header is not being set for Feign Client end point call. I need your help / guidance to fix it.  Actually, after this I need a custom Hmac based Interceptor to be injected and Auth Header being set based on current time stamp at the time when end point will be hit

**Comment by ryanjbaxter** [comment]
There are some details on how to do this in our documentation
http://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#spring-cloud-feign-overriding-defaults

If you are still having issues please provide the code in a git repo or zip.

**Comment by nikhilabhiman** [comment]
Thanks Ryan. 5 min screen share will help us, how can I do that?

**Comment by ryanjbaxter** [comment]
No need for that, if you can provide a sample app that reproduces the problem we can probably figure out what is wrong.

**Comment by nikhilabhiman** [comment]
I have a debug point inside apply method below, but it's never called, @Bean code slice is working, going into the constructor as well.  want to make this overridden method work successfully

@Override
  public void apply(RequestTemplate template) {
    template.header("Authorization", headerValue);
  }

**Comment by ryanjbaxter** [comment]
> If you are still having issues please provide the code in a git repo or zip.

**Comment by nikhilabhiman** [comment]
Hi Ryan,

This was the base code I started with, did few experiments later, even had tried creating feign client manually as well. HmacAuthorizationInterceptor class is present

https://github.com/nikhilabhiman/rrs-bi-service

**Comment by ryanjbaxter** [comment]
Go to start.spring.io and generate a sample project with the dependencies you want.  You project is not using the spring cloud BOM and it should be.  It is also using a very old version of Spring Cloud, currently we only support Edgware.SR3 (preferred) or Dalston.SR5.

**Comment by nikhilabhiman** [comment]
Thanks for the help!!. Will let you know for any issue further
