### ISSUE TITLE
How to config different timeout periods for different url/route in Zuul?

### ISSUE THREAD

**Issue by hooverhe** [spring-cloud/spring-cloud-netflix#2867]
Now we are using Zuul as gateway, forwarding the requests to the downstream systems with SimpleHostRoutingFilter of Zuul. Some business cost time a lit more, so we plan to config different timeout periods for different url/route. How to do? Who can give me some guides?

**Comment by ryanjbaxter** [comment]
You can only do this using Ribbon, you cannot do it using url configuration.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
