### ISSUE TITLE
Does Zuul support IP hash load balance? 

### ISSUE THREAD

**Issue by biwugang** [spring-cloud/spring-cloud-netflix#2871]
Does Zuul support IP hash load balance? 
How to config?

**Comment by holy12345** [comment]
Zuul is integrated with the Ribbon to achieve load balancing. In my impression, the ribbon does not seem to have this load-balancing algorithm.But I think you can implement this algorithm yourself.

**Comment by ryanjbaxter** [comment]
Not that I know of.
