### ISSUE TITLE
Feign Client call using Eureka and Openshift/Kubernetes

### ISSUE THREAD

**Issue by mgmike100** [spring-cloud/spring-cloud-netflix#2874]
Hi,

I am currently ing problems when I call a microservice direct from a microservice using Feign and Eureka.  I can get this working locally on my machine but now that I have deployed the code to Openshift/Kubernetes my configuration seems to be incorrect.  The microservices are deployed to Eureka and I can call the externally facing rest service but when I call the Feign services I get and error - it seems Eureka is not discoverying the internal service.

The following is my setup and configuration.

**Feign client call and properties**
@FeignClient(name="CURRENCY-EXCHANGE-SERVICE")
//@FeignClient(name="netflix-zuul-api-gateway-server")
//@RibbonClient(name="currency-exchange-service")
public interface CurrencyExchangeServiceProxy {

	@GetMapping("/currency-exchange-service/currency-exchange/from/{from}/to/{to}")
	public CurrentConversionBean retrieveExchangeValue(@PathVariable("from") String from, 
                            @PathVariable("to") String to)

**Exchange Service Properties file**
spring.application.name=currency-exchange-service
server.port=8000

spring.jpa.show-sql=true
spring.h2.console.enabled=true

eureka.client.service-url.defaultZone=http://eureka-service-currency-conversion-service.apps.sodigital.io/eureka
eureka.instance.hostname=http://exchange-service-currency-conversion-service.apps.sodigital.io
			@PathVariable("to") String to)

This is the error I get:

018-04-24 10:37:45.108 ERROR [currency-conversion-service,6e6fc12239cf834b,6e6fc12239cf834b,true] 1 --- [nio-8100-exec-7] o.s.c.sleuth.instrument.web.TraceFilter  : Uncaught exception thrown
--
rg.springframework.web.util.NestedServletException: Request processing failed; nested exception is feign.RetryableException: http executing GET http://currency-exchange-service/currency-exchange-service/currency-exchange/from/USD/to/INR

This I believe is something to do with the conifguration and Openshift/Kubernetes.

Thanks

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

There is nothing I can suggest based on the information you provided.  More of the stacktrace might be useful though.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
