### ISSUE TITLE
Ability to configure feign.RequestInterceptor specific to a given feign client

### ISSUE THREAD

**Issue by xyloman** [spring-cloud/spring-cloud-netflix#288]
There is a few use cases where we need to add different headers or authentication mechanisms on a per client basis.  Currently the FeignClientFactoryBean appears to apply its configuration to all feign clients that it constructs.  This was problematic in that some services that we want to use feign for require a different set of RequestInterceptors to one set of clients verse another.  Is there a way to accomplish this today?  We were able to work around this issue by using the feign builder directly, with the only thing we are customizing is the list RequestInterceptor from the other FeignClients.

**Comment by spencergibb** [comment]
Good idea.  We have a similar mechanism for `@RibbonClient` we could reuse.

**Comment by joaoevangelista** [comment]
Maybe we could register the `RequestInterceptors` through a value in `@RibbonClient` ? So it's clear which client use which interceptor

**Comment by spencergibb** [comment]
@joaoevangelista we need to maintain separation between Feign and Ribbon.  I'm imagining the same type of facility that `@RibbonClient` uses for `@FeignClient`.  We could probably generalize it for use with other annotations.

**Comment by joaoevangelista** [comment]
@spencergibb Really sorry! I meant `@FeignClient`, I got confused a bit, but yea, a generalized way would be nice too

**Comment by marcosbarbero** [comment]
Hi everybody, how is this issue going?

**Comment by dwelch2344** [comment]
Just wanted to throw in my vote on this. We've got a mixture of some ribbon backed FeignClients and a few that are hard coded to 3rd party APIs, so this would be a major win.

**Comment by spencergibb** [comment]
Yeah, I see this as our biggest feature for feign.  I'm working on getting ready for a conference week after next, so it might not get started until after OSCON.

**Comment by sbuettner** [comment]
Same as @dwelch2344. Would really like to see support for that. Maybe by leveraging springs @Qualifier annotation.

**Comment by lpborges** [comment]
This is exactly what I need.
I need to setup a FeignClient that use Basic Authentication, and this feature can help to setup a Feign BasicAuthRequestInterceptor different for each client.
Maybe some options for authentication on the FeignClient annotation can help too.

I figured to setup Authentication using headers in the RequestMapping:
```
@FeignClient(url="${service.url}")
public interface ProductsClient {

    @RequestMapping(method = RequestMethod.GET, value = "/item/{idProduct}", consumes = "application/json",
            headers="Authorization: Basic ${service.auth}")
    public ProductDTO getProduct(@PathVariable("idProduct") long idProduct);
}
```
But the problem is that the headers parameter don't apply the Spring value properties ( ${service.auth} ), so you need to hard code the authentication value.

**Comment by joaoevangelista** [comment]
For now, uou can create a bean of `feign.RequestInterceptor` returning a `BasicAuthRequestInterceptor` or implement your own, like I did for OAuth2 [here](https://github.com/joaoevangelista/spring-cloud-security/blob/feature/feign-oauth2-interceptor/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/client/feign/OAuth2FeignRequestInterceptor.java). It will be applied to all requests using feign

**Comment by lpborges** [comment]
Yes, but the problem is that the same Interceptor is used for all FeignClient, and I have 3 differents clients each one with different authentication user and password.

**Comment by spencergibb** [comment]
@xyloman @lpborges @joaoevangelista @marcosbarbero @dwelch2344 @sbuettner I have submitted PR #572 for review.

**Comment by sbuettner** [comment]
I think there is still an issue. It seems that `RequestInterceptor`s are currently only retrieved from the application context but not from the `@Configuration` defined in the `@FeignClient` configuration property.

**Comment by spencergibb** [comment]
@sbuettner If you think there's an issue with the new functionality, please open a new issue, don't comment on an old one.

**Comment by choelea** [comment]
One page helped me here is: http://stackoverflow.com/questions/37066331/using-headers-with-dynamic-values-in-feign-client-spring-cloud-brixton-rc2. Even though RequestInterceptor works fine for me but it's hard to set the header dynamically. I
I am using spring boot 1.4.0

**Comment by subodhkarwa** [comment]
Is there any inbuild solution, if parameters in headers differ based on URL.
Let's say, one client only expects - autheticationToken while other excepts token along with "someSectetKey"

I am overriding interceptors but would welcome if there is something else which can support this

**Comment by ryanjbaxter** [comment]
@subodhkarwa not sure I understand your question.  In any case please open an issue in the Open Feign project https://github.com/spring-cloud/spring-cloud-openfeign

**Comment by damianw345** [comment]
Hello I found a way to configure two independent interceptors on two different feign clients. I just specified two configuration classes **without** spring @Configuration annotation. So I have:
`@RequiredArgsConstructor
public class FeignOauthClientConfiguration {

    private final UploadConfiguration uploadConfiguration;
    private final AuthorizationHeaderService authorizationHeaderService;

// my custom oauth interceptor
    @Bean
    public JiraOauthFeignClientInterceptor jiraOauthFeignClientInterceptor() {
        return new JiraOauthFeignClientInterceptor(uploadConfiguration, authorizationHeaderService);
    }
}`

and 

`public class FeignBasicAuthClientConfiguration {

    @Value("${jira.user}")
    private String user;

    @Value("${jira.password}")
    private String password;

    @Bean
    public RequestInterceptor basicAuthFeignClientInterceptor() {
        return new BasicAuthRequestInterceptor(user, password);
    }
}`
With @Configuration annotation two interceptors were applied. It is connected to @Bean Lite Mode 

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html

Configuration classes are then specified in @FeignClient configuration property

**Comment by mxmlnglt** [comment]
OK great @damianw345 but now how do you instantiate those configurations...?

I can see you have a Lombok-specific `@RequiredArgsConstructor` annotation on the first one, so how do you specify it in your `@FeignClient` configuration annotation?

**Comment by herrsorgenfrei** [comment]
@mxmlnglt Try the following steps:
1. Reference a configuration class on your client's interface:
```
@FeignClient(name = "clientOne", configuration = ConfigOne.class)
public interface ClientOne { ... }
```
2. Create your specific interceptor annotated with @Bean inside the configuration:
```
public class ConfigOne {
  @Bean
  public InterceptorOne interceptorOne(AdditionalDependency ad) {
    return new InterceptorOne(ad);
  }
}
```
3. Make sure your ConfigOne-class is not annotated with any @Component/... annotations or is found by component scan.

Does it work for you?

**Comment by ayoubgdah** [comment]
Thanks @mxmlnglt . It worked like a charm

**Comment by ethfun** [comment]
cause  `BasicAuthRequestInterceptor implements RequestInterceptor` ,  you can check all feign client by diff feign name，this is my solution:
`

    @Configuration
    public class FeignClientConfiguration {
    
        @Bean
        public RequestInterceptor requestInterceptor() {
            return requestTemplate -> {
                Target target = requestTemplate.feignTarget();
                String feignName = target.name();           
                if ("oneFeign".equals(feignName)) {
                       template.header("Authorization", headerValue);
                }  else if (!"twoFeign".equals(feignName)) {
                      template.header("Authorization", headerValue);
                }
               
            };
        }
    
    }
`
