### ISSUE TITLE
How to override default global timeout setting for @requestbody request parameter of feignClient

### ISSUE THREAD

**Issue by liyanj** [spring-cloud/spring-cloud-netflix#2882]
My client and @requestbody like this:
```java
@FeignClient(name = "delivery", url = "${client.delivery.url:}")
public interface DeliveryClient {
    @RequestMapping(method = {RequestMethod.POST}, value = {"/order/status"})
    String getDeliveryInfoByOrderNo(@RequestBody DeliveryInfoRequest deliveryInfoRequest);
}
```
```java
public class DeliveryInfoRequest {
    String orderId;
    String appCode;
    String platformCode;
}
```
Normally, the below sentence in config file is used to define global timeout time for all clients:
```jave
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 15000
```

**Comment by liyanj** [comment]
I try to write below sentence in config file continuously and these 3 solutions are NOT available: 
```
hystrix.command."DeliveryClient#getDeliveryInfoByOrderNo(Object)".execution.isolation.thread.timeoutInMilliseconds
```
```
hystrix.command."DeliveryClient#getDeliveryInfoByOrderNo(DeliveryInfoRequest)".execution.isolation.thread.timeoutInMilliseconds
```
hystrix.command."DeliveryClient#getDeliveryInfoByOrderNo(String,String,String)".execution.isolation.thread.timeoutInMilliseconds
```
```
hystrix.command."DeliveryClient#getDeliveryInfoByOrderNo(String)".execution.isolation.thread.timeoutInMilliseconds
```

**Comment by ryanjbaxter** [comment]
It should be
`hystrix.command."DeliveryClient#getDeliveryInfoByOrderNo(DeliveryInfoRequest)".execution.isolation.thread.timeoutInMilliseconds: 1000`

Did you try it without the `"`?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
