### ISSUE TITLE
Use ZuulServletFilter instead of ZuulServlet

### ISSUE THREAD

**Issue by candrews** [spring-cloud/spring-cloud-netflix#2887]
In my Spring Boot 2.0.1 / Spring Cloud Finchley.RC1 application using `@EnableZuulProxy`, I'd like to have some URLs handled by Spring MVC and others by Zuul, like this:
/actuator/** - > Spring Boot Actuator
/** -> Zuul

I also would like buffering to be disabled (as currently works with paths under `zuul.servlet-path`, which by default is `/zuul`) and a minimum of other things to be done before zuul to get the best performance and fewest compatibility problems (such as with large file uploads).

My initial approach was to set `zuul.servlet-path=/`, but then requests to `/actuator/health`, for example, would still get processed by zuul. Next, I also set `zuul.ignored-patterns=/actuator/**` but that results in a blank page being returned (status 200 with no body) - ZuulServlet ignores the request, but since it's a servlet not a filter, there's nothing else to process the request so nothing further happens (`No route found for uri: /actuator/health` is logged).

I don't think there is a way to do what I'm attempting to do right now.

One solution I found is to use ZuulServletFilter instead. Configure a bean like this:
```
@Bean
public FilterRegistrationBean<ZuulServletFilter> zuulServletFilter(){
	final FilterRegistrationBean<ZuulServletFilter> filterRegistration = new FilterRegistrationBean<>();
	filterRegistration.setFilter(new ZuulServletFilter());
	filterRegistration.setOrder(Ordered.HIGHEST_PRECEDENCE);
	filterRegistration.addInitParameter("buffer-requests", "false");
	return filterRegistration;
}
```
unset `zuul.servlet-path`  and set `zuul.ignored-patterns=/actuator/**` and it works as expected (requests to /actuator go to actuator, everything else is handled by the configured zuul routes).

I propose that ZuulServlet not be used, and ZuulServletFilter be used instead. I don't think there's a downside.

**Comment by ryanjbaxter** [comment]
Maybe I am missing something, with the following configuration I was able to have Zuul route the request to `/mypath` correctly and also still access all the actuator endpoints.
```
zuul.ignored-patterns=/actuator/**
zuul.routes.google.path=/mypath/**
zuul.routes.google.url=http://httpbin.org
management.endpoints.web.exposure.include=*
```

**Comment by spencergibb** [comment]
I think it specifically has to do with a default route `/**`

**Comment by candrews** [comment]
> I think it specifically has to do with a default route /**

Correct.

**Comment by ryanjbaxter** [comment]
So you are saying that I would need to add `zuul.servlet-path=/**` to the configuration above?

**Comment by candrews** [comment]
Correct. I set `zuul.servlet-path=/` in my testing.

**Comment by spencergibb** [comment]
Closing in favor of #2888
