### ISSUE TITLE
Cannot upload files with Zuul (gzip is handled incorrectly)

### ISSUE THREAD

**Issue by stheves** [spring-cloud/spring-cloud-netflix#2890]
My setup is as follows:

client -> zuul -> downstream service and back. When sending a file from client to the downstream service, the client compresses the request body and sets the "Content-Encoding: gzip" header correctly. Now Zuul just removes the "Content-Encoding" header and forwards the request to the downstream service. The downstream service is now unable to read the body from the request because it is gzipped but the "Content-Encoding" header is missing.

We are using Edgware.SR3 release of Spring Cloud Netflix and this behaviour can easily reproduced with any spring boot sample app and setup.

**Comment by ryanjbaxter** [comment]
I know @brenuart submitted some fixes to the 2.0.x stream around gzip compression.  Could you try Finchley.RC1 and see if you have the same issue?

**Comment by stheves** [comment]
I can confirm that this issue is fixed with Finchley.RC1 and Spring Boot 2.0.1 release. The difference is that the header is also removed but the request body gets decompressed before sending it to the downstream service.

Any chance to get a bugfix for Edgware release? Or is there a workaround that we can apply?

**Comment by ryanjbaxter** [comment]
I think we dont want to remove the `isIncludeHeader` check from `buildZuulRequestHeaders` completely because we still want to check for any headers the user wanted to ignore.  Maybe we can separate that out into a separate method though.  I dont see any reason why `Content-Encoding` shouldnt be proxied downstream.  @spencergibb what do you think?

**Comment by stheves** [comment]
@spencergibb You are right when removing the encoding header but keeping the length header the Apache HTTP client complains about it because the client wants to compute the content length by its own. But you can disable that if you want. 

I´ve implemented my workaround as @ryanjbaxter suggested and just kept the content encoding header. I don`t like my workaround because I had to copy most of the code from ProxyRequestHelper#buildZuulRequestHeaders because it is not easy for a client to override.

Here is my workaround:

```java
    private ProxyRequestHelper proxyRequestHelper(ZuulProperties zuulProperties) {
        TraceProxyRequestHelper helper = new TraceProxyRequestHelper() {
            @Override
            public MultiValueMap<String, String> buildZuulRequestHeaders(HttpServletRequest request) {
                RequestContext context = RequestContext.getCurrentContext();
                MultiValueMap<String, String> headers = new HttpHeaders();
                Enumeration<String> headerNames = request.getHeaderNames();
                if (headerNames != null) {
                    while (headerNames.hasMoreElements()) {
                        String name = headerNames.nextElement();
                        // this line is the bug fix
                        if (isIncludedRequestHeader(name)) {
                            Enumeration<String> values = request.getHeaders(name);
                            while (values.hasMoreElements()) {
                                String value = values.nextElement();
                                headers.add(name, value);
                            }
                        }
                    }
                }
                Map<String, String> zuulRequestHeaders = context.getZuulRequestHeaders();
                for (String header : zuulRequestHeaders.keySet()) {
                    headers.set(header, zuulRequestHeaders.get(header));
                }
                headers.set(HttpHeaders.ACCEPT_ENCODING, "gzip");
                return headers;
            }

            public boolean isIncludedRequestHeader(String headerName) {
                // forward the header to downstream services
                String name = headerName.toLowerCase();
                if ("content-encoding".equals(name)) {
                    return true;
                }
                return super.isIncludedHeader(headerName);
            }
        };
        if (this.traces != null) {
            helper.setTraces(this.traces);
        }
        helper.setIgnoredHeaders(zuulProperties.getIgnoredHeaders());
        helper.setTraceRequestBody(zuulProperties.isTraceRequestBody());
        return helper;
    }
```

**Comment by ryanjbaxter** [comment]
@stheves do you want to submit a PR with a change then?

**Comment by OlgaMaciaszek** [comment]
Closing the issue as Spring Cloud Netflix Zuul is no longer supported.
