### ISSUE TITLE
Finchley.RC1 /actuator/health only show the service status,no hystrix,redis....

### ISSUE THREAD

**Issue by keyantec** [spring-cloud/spring-cloud-netflix#2895]
When I use the healthcheck config, it only shows me {"status":"UP"} on the page, no hystrix status,my config like this:
eureka server:
`server:
  port: 8761
spring:
  security:
    user:
      name: server-eureka-pass
      password: 2lvoHcfXbXmTBvQm
  application:
    name: eureka-server-pass
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
`
service:
`server:
  port: 8013
spring:
  application:
    name: ribbon-client-hystrix
  security:
    user:
      name: ribbon-client-hystrix
      password: 2lvoHcfXbXmTBvQm
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone:  http://server-eureka-pass:2lvoHcfXbXmTBvQm@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ribbon-client-hystrix:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
`

 @ryanjbaxter How can I see the all status in healthcheck?Thank you !

**Comment by spencergibb** [comment]
https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/html/production-ready-endpoints.html#production-ready-health

**Comment by keyantec** [comment]
It works ,thank you!

**Comment by eacdy** [comment]
Maybe you should try `management.security.enabled=false` .
