### ISSUE TITLE
RestTemplate Ribbon loadbalance calls are occasionally forwarded from service B to service C

### ISSUE THREAD

**Issue by xiyelife** [spring-cloud/spring-cloud-netflix#2896]
Question：

use @Loadbalance on   RestTemplate  and use the SpringRetry
RestTemplate Ribbon loadbalance calls are occasionally forwarded from  service B to service C

A send to  B, but now  B was  forwarded to C  , here is the RestTemplate message 
request before:
Created GET request for "http://B/app/xxxx" 
request after：
GET request for "http://B/app/xxxx" resulted in 400 (null); invoking error handler

It appears that the service B is resolved to the real IP and PORT of service C
The reason for returning 400 here is that other service C was sent, service C was unable to recognize the request message.
The request should have been sent to the service B！！
		

Is there a problem with reconstructing URI here?
RibbonLoadBalancerClient.reconstructURI(ServiceInstance, URI)

In the production environment, this is an occasional situation anyway, about 10 times a day.
The SpringCloud version is Dalston.RELEASE and spring-cloud-netflix-core version is 1.3.0-RELEASE

**Comment by ryanjbaxter** [comment]
There is not enough information here to determine what is happening.

First thing I suggest trying is using Edgware.SR3 and see if the problem is reproducible there.  If it is please create a sample that reproduces the problem and attach it to the issue.

**Comment by spencergibb** [comment]
This can happen when a server list or load balancer is shared across services
