### ISSUE TITLE
Zuul - dynamically route each user to user specific service

### ISSUE THREAD

**Issue by yuvalbar84** [spring-cloud/spring-cloud-netflix#2899]
Hi, i'm struggling to figure out if the following is possible with Zuul:
each user has it's own bot behind zuul.
I'm trying to write some filter which extracts (from DB/configuration file/whatever) the specific bot URL for the specific user and then Zuul should acts as a proxy to the user's bot.
I've tried to use PRE_FILTER / ROUTE_FILTER with before/after PreDecFilter (all combinations) ```ctx.set(REQUEST_URI_KEY, "/userSpecificBotPath");``` or ```ctx.setRouteHost(urlOfUserSpecificBot);```
all failed to proxy so far. 
Any direction would be appreciated.

**Comment by spencergibb** [comment]
It is possible. See https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/QueryParamServiceIdPreFilter.java

Tho it is serviceId, not url, but it is similar.

**Comment by yuvalbar84** [comment]
Thanks @spencergibb , 
I tried it with eureka server and clients, and indeed it worked.
however, my bots are not configured with eureka clients, and each of them has a unique IP.
I'm trying for 3 days already to setup a filter that will proxy to the URL instead of serviceId, but it's not working.
I have 2 endpoints running:
http://192.168.1.14:8088/test
http://192.168.1.14:8089/test

This is my application.properties:
```
spring.application.name=zuul-server
server.port=8080
management.endpoints.web.exposure.include=*
zuul.routes.test.path=/test/**
```

And this is my filter:

```
  @Override
  public String filterType() {
    return PRE_TYPE;
  }
  @Override
  public int filterOrder() {
    return PRE_DECORATION_FILTER_ORDER - 1;
  }
  public boolean shouldFilter() {
   return true;
  }

 public Object run() {
   RequestContext ctx = getCurrentContext();
  try {
    ctx.put(REQUEST_URI_KEY, "http://192.168.1.14:8088/test/");
  } catch(MaformedURLException e) {
}
return null;
}
```

Tried to change the orderFilter from -1 to +1, from "pre" to "route",
use ```ctx.setRouteHost()``` , nothing works from me.
can you please suggest how to deal with it?
thanks

**Comment by yuvalbar84** [comment]
Finally got it working.
```java
  @Override
  public String filterType() {
    return PRE_TYPE;
  }

  @Override
  public int filterOrder() {
    return PRE_DECORATION_FILTER_ORDER + 1; // run before PreDecoration
  }

  public Object run() {
    RequestContext ctx = getCurrentContext();
    ctx.put(REQUEST_URI_KEY, "/test/");
    try {
      if (new Random().nextInt(10) > 5) {
        ctx.setRouteHost(new URL("http://192.168.1.14:8088"));
      } else {
        ctx.setRouteHost(new URL("http://192.168.1.14:8089"));
      }
    } catch (MalformedURLException e) {
      log.error("", e);
    }
  return null;
  }
```
