### ISSUE TITLE
Ability to annotate feign client interface with request mapping

### ISSUE THREAD

**Issue by xyloman** [spring-cloud/spring-cloud-netflix#290]
I was kicking around an idea where the feign client interface could be annotated with a RequestMapping annotation as well each method.  Below is an example:
```java
@FeignClient("some-service")
@RequestMapping("/parent")
interface Client {

@RequestMapping("/child")
findChildResource(@RequestParam("queryParam") String param)
}
```
The above example would allow for Spring MVC controllers to implement an interface that could be shared with the client.  Currently such an interface will not work on the feign client side and in looking at the SpringMvcContract that makes since because the class is not evaluated today.  This approach could also be used to limit the verbosity of the declarations on a methods.

**Comment by spencergibb** [comment]
already being looked at in #289

**Comment by xyloman** [comment]
Dang sorry about that totally missed that in my searching.  My apologizes.

**Comment by spencergibb** [comment]
np, I missed it review the PR, so no worries.
