### ISSUE TITLE
Zuul multipart upload big files lose Content-Disposition and Content-Type

### ISSUE THREAD

**Issue by yoransabern** [spring-cloud/spring-cloud-netflix#2903]
When uploading big files (>1GB, smaller files work fine when using the /zuul/* path), zuul seems to 'forget' to send the multipart data for 'file'. This results in a "Required request part 'file' is not present" in the service.

Both our Zuul application and the service are running spring boot 2.0.0.RELEASE with spring cloud Finchley.M8.

```
Received [POST /zuul/service/upload HTTP/1.1
cache-control: no-cache
User-Agent: PostmanRuntime/7.1.1
Accept: */*
accept-encoding: gzip, deflate
content-type: multipart/form-data; boundary=--------------------------527478988378162204669043
content-length: 1073742031
Connection: keep-alive

----------------------------527478988378162204669043
Content-Disposition: form-data; name="file"; filename="dummy.txt"
Content-Type: text/plain

]
```

Request as received in the service:

```
Received [POST /upload HTTP/1.1
postman-token: d9f84522-f1ff-4432-aec2-301a2e1244cb
user-agent: PostmanRuntime/7.1.1
accept: */*
content-type: multipart/form-data; boundary=--------------------------527478988378162204669043
x-forwarded-host: localhost:8765
x-forwarded-proto: http
x-forwarded-prefix: /service
x-forwarded-port: 8765
x-forwarded-for: 0:0:0:0:0:0:0:1
Accept-Encoding: gzip
Content-Length: 1073742031
Host: localhost:8090
Connection: Keep-Alive


----------------------------527478988378162204669043--
]
```

**Comment by liwenbo** [comment]
Hi, were you able to solve this issue?

**Comment by yoransabern** [comment]
No

**Comment by Marek1981-2** [comment]
Is there any workaround for this problem? I'm having exactly the same issue.

**Comment by ryanjbaxter** [comment]
@Marek1981-2 how big is the file you are sending?

**Comment by Marek1981-2** [comment]
When I sending files aroung 10-100MB everything is OK. The problem is when I'm sending 2GB (and more).

In logs there are no other information than simply:
"Required request part 'file' is not present". No other information.

**Comment by ryanjbaxter** [comment]
Has anyone tried this with Finchley.SR1?  What about Edgware.SR4?

**Comment by yoransabern** [comment]
Sorry for the late response, Finchley.SR1 and Finchley.RELEASE don't change anything, still get the same message. I cannot test with Edgware because my project has too much dependency on spring boot 2.0.

**Comment by yoransabern** [comment]
I also read something about big uploads here: https://www.anaplan.com/blog/using-zuul-in-production/
Though this hasn't solved the problem for me.

**Comment by QT001** [comment]
I'm having exactly the same issue.
project：
https://github.com/QT001/question2018_09_05_14.44.52

command
curl -v -F "file=@1.5G" -H "Transfer-Encoding: chunked"  http://10.10.1.66:8040/zuul/file-upload/

By the way，Camden.SR3 works fine

**Comment by QT001** [comment]
RibbonCommandContext.java +103 will cause exception when file size > 1G
 
   public InputStream getRequestEntity() {
        if (this.requestEntity == null) {
            return null;
        } else {
            try {
                if (!(this.requestEntity instanceof ResettableServletInputStreamWrapper)) {
                    this.requestEntity = new ResettableServletInputStreamWrapper(StreamUtils.copyToByteArray(this.requestEntity));
                }

                this.requestEntity.reset();
            } finally {
                return this.requestEntity;
            }
        }
    }

**Comment by QT001** [comment]
@ryanjbaxter

**Comment by ryanjbaxter** [comment]
@QT001 thanks for the sample, however it does not seem correct.  There is no route called `file-upload`.  Is the upload-files app supposed to register with Eureka?

**Comment by QT001** [comment]
Yes

**Comment by ryanjbaxter** [comment]
Can you please update your sample so it works then?

**Comment by QT001** [comment]
@ryanjbaxter  Ok, Eureka has uploaded

**Comment by ryanjbaxter** [comment]
Looks like the problem came from the PR https://github.com/spring-cloud/spring-cloud-netflix/pull/2209#issuecomment-324840277

And we actually talked about this issue https://github.com/spring-cloud/spring-cloud-netflix/pull/2209#issuecomment-324840277 ugh!

@doernbrackandre maybe we should revisit the idea of using a `BufferedReader`?

**Comment by doernbrackandre** [comment]
@ryanjbaxter I'm, on it. 
From what I remember, it is bound to the ribbon.OkToRetryOnAllOperations property but I'm not sure if the mentioned code is affected by this.

@QT001 do you have ribbon.OkToRetryOnAllOperations enabled?

**Comment by ryanjbaxter** [comment]
The code goes through this line regardless of a retry or not
https://github.com/spring-cloud/spring-cloud-netflix/pull/2209/files#diff-2fe6e36d440bdcd50f24cb3afa580574R138

**Comment by ryanjbaxter** [comment]
Lets try the `BufferedReader` approach sounds like that would keep the code cleaner.

**Comment by ryanjbaxter** [comment]
Fixed via edd24bc

**Comment by sheuertz** [comment]
Hi.
Just wondering if there was a plan to get this change into the 2.x line as well?
Thanks.

**Comment by spencergibb** [comment]
@ryanjbaxter did this get merged forward?

**Comment by ryanjbaxter** [comment]
Apparently not :(  I just merged it forward.
