### ISSUE TITLE
Need clarification regarding ignoredServices

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-netflix#2904]
I am referencing the documentation found here: http://cloud.spring.io/spring-cloud-static/Finchley.RC1/single/spring-cloud.html

In section 18.2...

> To skip having a service automatically added, set zuul.ignored-services to a list of service ID patterns. If a service matches a pattern that is ignored but is also included in the explicitly configured routes map, it is unignored, as shown in the following example:

>application.yml. 

> zuul:
>  ignoredServices: '*'
>  routes:
>    users: /myusers/**

>In the preceding example, all services are ignored, except for users.

It is unclear to me if I should be using zuul.ignoredServices or zuul.ignored-services in my properties file.

Also I don't understand what the expected functionality should be.

I have the following config:

```
zuul.ignoredServices='*'
zuul.routes.auth.service-id=AUTHENTICATION_SERVICE_DEV
zuul.routes.auth.path=/v1/auth/**
zuul.routes.auth.stripPrefix=false
```

Zuul is routing /v1/auth/** as well as /authentication_service_dev.

What I want is to route only /v1/auth. But the way the documentation is written, it is unclear if this is going to work. When the service is "unignored" does that mean a route for it's service id is automatically added?

**Comment by spencergibb** [comment]
I want to keep this open to track adding debug logging

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
