### ISSUE TITLE
Error uploading file thru zuul servlet as multipart form

### ISSUE THREAD

**Issue by Lovnx** [spring-cloud/spring-cloud-netflix#2907]
I used Finchley zuul server to upload file, occured a error.
'http://localhost:5555/upload' uploaded successfully.
'http://localhost:5555/zuul/upload' error, messages:
{
  "timestamp": "2018-05-03T10:37:54.104+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "Required request part 'file' is not present",
  "path": "/zuul/upload"
}

**Comment by ryanjbaxter** [comment]
Please provide more information, we can't help based on the information above

**Comment by Lovnx** [comment]
In order to solve Chinese garbled when I upload file by Zuul. I accorded #1385 to add /zuul to URL. But It didn't work well, error messages in issue description.

**Comment by ryanjbaxter** [comment]
Sounds like there is something wrong with the file you uploaded.  I would imagine there is a stacktrace produced by Zuul and/or the backend service.  Can you provide that?  Also could you provide the file you are uploading and the request you are making to Zuul?

**Comment by yoransabern** [comment]
This is the same error i'm getting, see this issue #2903

**Comment by ryanjbaxter** [comment]
@yoransabern if you believe this is the same error, can you please post the details of the error and your sample zuul app here?  No need to keep #2903 open if you think this is the same issue.

**Comment by ryanjbaxter** [comment]
@Lovnx ^^^ please provide more details

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
