### ISSUE TITLE
Getting started with spring-cloud-netflix-starter-atlas dependencies

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-netflix#2914]
I am having some trouble getting started with Atlas and Spectator.

All of the Spring-cloud-netflix starter dependencies are working for me like this:

	compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')

But when I have this in my gradle file:

        compile('org.springframework.cloud:spring-cloud-starter-netflix-spectator)
        compile('org.springframework.cloud:spring-cloud-starter-netflix-atlas)

I see errors like this:

 org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.springframework.cloud:spring-cloud-starter-netflix-spectator:.

When I add the version number manually like this:

        compile('org.springframework.cloud:spring-cloud-starter-netflix-spectator:1.4.4.RELEASE')
        compile('org.springframework.cloud:spring-cloud-starter-netflix-atlas:1.4.4.RELEASE')

The errors go away, but the @EnableAtlas annotation is not on my classpath.

Any suggestions on what I'm doing wrong?

**Comment by spencergibb** [comment]
Unsure, they are both in the project bom: https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-dependencies/pom.xml

**Comment by illingtonFlex** [comment]
Is there a working example somewhere I can clone? I just created a fresh Spring-Boot application and tried adding the dependencies and I see the same thing.

```
buildscript {
	ext {
		springBootVersion = '2.0.1.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'my.company'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
}


ext {
	springCloudVersion = 'Finchley.RC1'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.boot:spring-boot-starter-validation')
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-netflix-atlas')
	compile('org.springframework.cloud:spring-cloud-starter-netflix-eureka-client')
	runtime('org.springframework.boot:spring-boot-devtools')
	compileOnly('org.projectlombok:lombok')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```

> Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.springframework.cloud:spring-cloud-starter-netflix-atlas:.

When I remove the Atlas dependency, it builds.

**Comment by ryanjbaxter** [comment]
Looks like the atlas starter some how got removed from spring-cloud-netflix-dependencies

**Comment by ryanjbaxter** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-netflix/commit/6c71f9bba814a230ad965f1f85cd4037af1eda21

**Comment by illingtonFlex** [comment]
I also notice that file does not have a dependency for Spectator. Is that a bug also?

**Comment by ryanjbaxter** [comment]
Unsure, @spencergibb do you know?

**Comment by spencergibb** [comment]
No

**Comment by illingtonFlex** [comment]
The behavior when attempting to declare a Spectator dependency is the same as when trying to declare an Atlas dependency, so it seems if the Atlas thing was a bug, then so would this.

**Comment by ryanjbaxter** [comment]
We removed spectator in Finchley.

**Comment by illingtonFlex** [comment]
OK thanks. BTW the docs for Finchley RC1 still say Spectator is preferred: https://cloud.spring.io/spring-cloud-static/Finchley.RC1/multi/multi_netflix-metrics.html

**Comment by ryanjbaxter** [comment]
Thanks.  Can you create a separate issue for the docs?
