### ISSUE TITLE
Zuul Proxy microservice returns 404 for routes and trace

### ISSUE THREAD

**Issue by melardev** [spring-cloud/spring-cloud-netflix#2918]
Hi, it has been more than two hours now that I am trying to make a Zuul microservice return actually something when /routes is requested, without success, it returns Whitelabel 404 no messages available.
My pom.xml

<?xml version="1.0" encoding="UTF-8"?>

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.melardev.cloud</groupId>
    <artifactId>zuul</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>zuul</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
        <relativePath/> 
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-cloud-services.version>2.0.0.M1</spring-cloud-services.version>
        <spring-cloud.version>Finchley.RC1</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>

The ZuulApplication class

    @SpringBootApplication
    @EnableZuulProxy
    @EnableDiscoveryClient
    public class ZuulApplication {
        public static void main(String[] args) {
            SpringApplication.run(ZuulApplication.class, args);
        }
    }

application.yml

    server:
    port: 8762
    spring:
        application:
        name: zuul-server
    eureka:
    instance:
        preferIpAddress: true
    eureka:
    client:
        registerWithEureka: true
    eureka:
    client:
        fetchRegistry: true
    eureka:
    serviceurl:
        defaultzone: http://localhost:8761/eureka/

    management:
    endpoint:
        routes:
        enabled: true

I have tried to add spring-security to check if it was a problem of "insecure endpoint access protection" without success, I have tried to enable starter-web, replaced DiscoveryClient by EurekaClient and a lot more, nothing ...
It's weird because the application actually works, it registers to Eureka server, it recognizes other rest microservices and it load balance between them succesfully, in the console when I ran the zuul microservice jar it says that he has mapped succesfully the rest microservices to /rest-app/** and as said it actually works, but /routes and /trace return 404.

**Comment by dclar** [comment]
Hi  in springboot 2.0, we should configue the `exposure` like :

``` yml 
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
```

**Comment by dclar** [comment]
@melardev I think this could help u : ) 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints

**Comment by eacdy** [comment]
Maybe you should try endpoint `/actuator/routes` or `/actuator/trace`.
In Spring Boot 2.0, you must add prefix `/actuator`.

**Comment by dclar** [comment]
Hi @eacdy Mr Chou. I watched ur video of spring cloud. What I want to say is "Bravo".Thank you very much for that excellent videos.

**Comment by eacdy** [comment]
@dclar Thank you for your THANKS.
Those videos are thought as `TOTALLY HOLY SHIT` by many people. The review of those video are very bad.

**Comment by dclar** [comment]
@eacdy LoL~~ Never mind~ That is what we called "It takes all sorts"  : )

**Comment by eacdy** [comment]
@dclar haha.
