### ISSUE TITLE
FeignClient returing null client when hosting in docker

### ISSUE THREAD

**Issue by momentum123** [spring-cloud/spring-cloud-netflix#2919]
hi @spencergibb @ryanjbaxter running client application and service in docker which return null client although works fine when hosting both service and client in local but throws unknown host exception when hosting service in docker and client in local with container id as unknown host. 
all the suggestions are appreciated .

**Comment by ryanjbaxter** [comment]
Without more details there is nothing we can really help with.  Sample apps are the best.
