### ISSUE TITLE
Eureka and Turbine setup?

### ISSUE THREAD

**Issue by ewolff** [spring-cloud/spring-cloud-netflix#292]
I cannot get Eureka and Turbine to work. I have read http://stackoverflow.com/questions/28365202/spring-boot-eureka-server-hystrix-with-turbine-empty-turbine-stream - but I am not sure whether the new String('default') is still needed.

I am using

    server:
          port: 8989

    eureka:
      client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://eureka:8761/eureka/    
      server:
        waitTimeInMsWhenSyncEmpty: 0
      instance:
        preferIpAddress: true
    
    turbine:
      appConfig: ORDER
      clusterNameExpression: new String("default")

I see this output:

    2015-04-01 21:21:46.415  INFO 5 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Failed to retrieve instances from Eureka
    2015-04-01 21:21:46.416  INFO 5 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Retrieved hosts from InstanceDiscovery: 0
    2015-04-01 21:21:46.419  INFO 5 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Found hosts that have been previously terminated: 0
    2015-04-01 21:21:46.419  INFO 5 --- [        Timer-0] c.n.t.discovery.InstanceObservable       : Hosts up:0, hosts down: 0
    2015-04-01 21:22:46.410  INFO 5 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instance list for apps: [ORDER]
    2015-04-01 21:22:46.410  INFO 5 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  :     Fetching instances for app: ORDER
    2015-04-01 21:22:46.411  WARN 5 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Eureka returned null for app: ORDER

I see an empty stream with just pings (as expected) while the stream of the order app works i.e. contains data. The documentation at http://projects.spring.io/spring-cloud/docs/1.0.0/spring-cloud.html#_turbine didn't really help me either.

**Comment by spencergibb** [comment]
I think you need: assuming your service name is `order`
```
turbine:
  aggregator:
    clusterConfig: ORDER
  appConfig: order
```

**Comment by ewolff** [comment]
Hi Spencer,

thanks! That did not help: The result is the same, order is in small caps
in the log now. :(

    2015-04-01 21:46:10.152  INFO 5 --- [        Timer-0]
o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instance list for apps:
[order]

    2015-04-01 21:46:10.152  INFO 5 --- [        Timer-0]
o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instances for app: order

    2015-04-01 21:46:10.153  WARN 5 --- [        Timer-0]
o.s.c.n.turbine.EurekaInstanceDiscovery  : Eureka returned null for app:
order

    2015-04-01 21:46:10.155  INFO 5 --- [        Timer-0]
o.s.c.n.turbine.EurekaInstanceDiscovery  : Failed to retrieve instances
from Eureka

    2015-04-01 21:46:10.156  INFO 5 --- [        Timer-0]
c.n.t.discovery.InstanceObservable       : Retrieved hosts from
InstanceDiscovery: 0

    2015-04-01 21:46:10.157  INFO 5 --- [        Timer-0]
c.n.t.discovery.InstanceObservable       : Found hosts that have been
previously terminated: 0

    2015-04-01 21:46:10.158  INFO 5 --- [        Timer-0]
c.n.t.discovery.InstanceObservable       : Hosts up:0, hosts down: 0

**Comment by spencergibb** [comment]
can you see turbine registered with eureka?

**Comment by ewolff** [comment]
Yip.

On Wed, Apr 1, 2015 at 11:49 PM, Spencer Gibb <notifications@github.com>
wrote:

> can you see turbine registered with eureka?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-netflix/issues/292#issuecomment-88642211>
> .
>



-- 
Eberhard Wolff
Leobschützer Str. 22
13125 Berlin
+49 151 75004986

   http://ewolff.com    Twitter: @ewolff        Skype: ebr.wolff
                       Contradiction Is Balance

**Comment by spencergibb** [comment]
hmm, the logs say eureka client can't find order in eureka.  I'm assuming `order` is in eureka.  Do you have a project to share?

**Comment by ewolff** [comment]
Yes - see screenshot. Project is on github: https://github.com/ewolff/microservice
![eurekascreenshot](https://cloud.githubusercontent.com/assets/529318/6953667/3467005c-d8cb-11e4-8b92-d40eaa1db3af.png)

**Comment by spencergibb** [comment]
I'll take a look

**Comment by spencergibb** [comment]
@ewolff see https://github.com/ewolff/microservice/pull/1 `fetchRegistry: false` meant it couldn't find the order service.

**Comment by ewolff** [comment]
Excellent - it works. Thanks a lot for your help! And sorry, I should
probably have spotted that myself.

On Friday, April 3, 2015, Spencer Gibb <notifications@github.com> wrote:

> @ewolff <https://github.com/ewolff> see ewolff/microservice#1
> <https://github.com/ewolff/microservice/pull/1> fetchRegistry: false
> meant it couldn't find the order service.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-cloud/spring-cloud-netflix/issues/292#issuecomment-89344500>
> .
>


-- 
Eberhard Wolff
Leobschützer Str. 22
13125 Berlin
+49 151 75004986

   http://ewolff.com    Twitter: @ewolff        Skype: ebr.wolff
                       Contradiction Is Balance

**Comment by vskrahul** [comment]
I am also trying the same thing in case logs are looking good the only thing is hystrix dashboard is not showing anything there on turbine URL : http://localhost:8089/turbine.stream?cluster=ACCOUNT

Please suggest me something.

I have one name account (hystix is enabled) and hystrix dashboard application both are connected with eureka server.
No error, warnings found in the logs anywhere.
