### ISSUE TITLE
how to change service status?

### ISSUE THREAD

**Issue by Lovnx** [spring-cloud/spring-cloud-netflix#2921]
Is there a rest api that we can change service status in spring-cloud-netflix-eureka-client? 
For example: I have a service registering Eureka, status is UP. No I want to change it's status from UP to OUT_OF_SERVICE. How can I get this?

**Comment by eacdy** [comment]
Just send a POST request to the `/pasue` endpoint of your service instance.
Then, this instance will be marked as `DOWN`.

if you use `Finchley` or higher, just change `/pause` to `/actuator/pause`

**Comment by Lovnx** [comment]
I need change status from UP to OUT_OF_SERVICE.

**Comment by ryanjbaxter** [comment]
Yes there is, for example
```
curl -X "POST" "http://localhost:8181/service-registry/instance-status" \
   -H "Content-Type: text/plain; charset=utf-8" \
   -d "OUT_OF_SERVICE"
```

**Comment by Lovnx** [comment]
Thanks, this is it.

**Comment by Lovnx** [comment]
Where is this function implemented?

**Comment by Lovnx** [comment]
Thanks！You are so handsome.

**Comment by eacdy** [comment]
@ryanjbaxter The command in Spring Cloud Finchley and version above changes:
```shell
curl -X "POST" "http://localhost:8000/actuator/service-registry?status=DOWN" \
   -H "Content-Type: application/vnd.spring-boot.actuator.v2+json;charset=UTF-8" 
```
