### ISSUE TITLE
Zuul API GATEWAY URL FORMING 

### ISSUE THREAD

**Issue by Raj-MicroJavaAng** [spring-cloud/spring-cloud-netflix#2925]
Hi please check my yml file and tell the urls to access the services. please suggest me how to use zuul api gateway.

spring:
application:
  name: eureka-server

server:
  port: 8300

eureka:
  client:
registerWithEureka: false
fetchRegistry: false

serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
waitTimeInMsWhenSyncEmpty: 0
      
zuul:
   prefix:/api
routes:
 dbclient:
    path:/dbclient/**
    url:http://localhost:8301
    stripPrefix: false

 stock-service:
   path:/stock-service/**
   url:http://localhost:8302
   stripPrefix: false

**Comment by ryanjbaxter** [comment]
See documentation for the version you are using http://projects.spring.io/spring-cloud/

If you are having a specific issue, open an issue with the details of the issue and a project that reproduces it.
