### ISSUE TITLE
If ribbon support retry for the error of connection refused not all error?

### ISSUE THREAD

**Issue by lishengsam** [spring-cloud/spring-cloud-netflix#2927]
Consumer service call the provider service instance had downed due to the local cache and throw the error of connection refused when the provider service deployment or shutdown. I don't want to get the error because the provider services deployment or shutdown. Ribbon can support retry next server for this error? I don't want to retry for other error.

**Comment by ryanjbaxter** [comment]
You can try
```
clientName:
  ribbon:
    retryableStatusCodes: 404,502
```

See http://cloud.spring.io/spring-cloud-static/Edgware.SR3/single/spring-cloud.html#_configuration

**Comment by lishengsam** [comment]
The request of Read timeout  exception would retry when setting the 502 code. It was not I want. I see the 'okToRetryOnConnectErrors' variable in RequestSpecificRetryHandler class, but it is hard code with false in RetryableRibbonLoadBalancingHttpClient#getRequestSpecificRetryHandler. could it support in the form of configuration ?

**Comment by lishengsam** [comment]
👌

**Comment by lishengsam** [comment]
yes
