### ISSUE TITLE
2.0.0.RC1: Eureka Registration using WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by mayras** [spring-cloud/spring-cloud-netflix#2928]
My client tried to connect to eureka server and got everytime strange result which isn't related to real problem: 

com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'timestamp' does not match expected ('instance') for type [simple type, class com.netflix.appinfo.InstanceInfo]
 at [Source: (com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream); line: 1, column: 2]

Eureka client got response:
{"timestamp":1526038152661,"status":403,"error":"Forbidden","message":"Forbidden","path":"/eureka/apps/IMAGEBANK-CLOUD-SERVER/SibTeam-PC:imagebank-cloud-server:29088"}

It seems that problem in permissions, I started to debug from scratch and problem was related to CsrfFilter, which was chained in all sequence of filters, really not trivial way  to find real problem, 
may be some code notice about disabling of csrf or more right explanation of error?

Finally solution is in WebSecurityConfig:

@EnableWebSecurity
@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    public void configure(WebSecurity web) throws Exception {
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().disable();
    }
}

**Comment by spencergibb** [comment]
That is a documented work around
