### ISSUE TITLE
Support for triggering AWS lambda with zuul routes

### ISSUE THREAD

**Issue by SalmanKhan3991** [spring-cloud/spring-cloud-netflix#2947]
Hi,

I have come across a requirement in which I have to trigger an AWS lambda from zuul routing. Is this support available? If not, any suggestions on how we can achieve triggering the lambda with zuul routing?

Traditionally, we use
zuul.routes.MS1.path=/MS1/**
zuul.routes.MS1.url=http://server:8080/MS1
to redirect to an url when the path is hit via zuul. In a similar sense, is it possible to trigger the aws lambda function?

**Comment by ryanjbaxter** [comment]
If AWS Lambda can be triggered via an HTTP request than Zuul can proxy that request.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
