### ISSUE TITLE
EurekaAutoServiceRegistration issue with random port and WebFlux/Netty stack

### ISSUE THREAD

**Issue by howardem** [spring-cloud/spring-cloud-netflix#2948]
Hi, 

We are migrating our current set of microservices built on top of Spring Boot 1.5.x / Spring Cloud Edgeware to Spring Boot 2 / Spring Cloud Finchley. There is an issue with the Eureka registration when using WebFlux/Netty and a random port is specified (server.port=0). We realized the EurekaAutoServiceRegistration is listening to ServletWebServerInitializedEvent in order to update the instance registration port. ServletWebServerInitializedEvent is never triggered because is related to the Servlet stack and we are using Reactor/Netty. 

![image](https://user-images.githubusercontent.com/12344960/40313933-ffc6458c-5ce4-11e8-8b00-0ecf71db6151.png)

**Comment by howardem** [comment]
I think instead of listening to an event of type ServletWebServerInitializedEvent, the listener should be changed to events of type WebServerInitializedEvent in order to make it work for Servlet and Reactive environments. WebServerInitializedEvent is the base class for both ServletWebServerInitializedEvent  and ReactiveWebServerInitializedEvent.

**Comment by ryanjbaxter** [comment]
Care to submit a PR?
