### ISSUE TITLE
Turbine stream port and dependency problems

### ISSUE THREAD

**Issue by MadeInChina** [spring-cloud/spring-cloud-netflix#2955]
There are two issues with Finchley.BUILD-SNAPSHOT
1.according to the docs from https://cloud.spring.io/spring-cloud-netflix/single/spring-cloud-netflix.html#_turbine_stream
>Spring Cloud provides a spring-cloud-starter-netflix-turbine-stream that has all the dependencies you need to get a Turbine Stream server running
```
5.3 Turbine Stream
In some environments (such as in a PaaS setting), the classic Turbine model of pulling metrics from all the distributed Hystrix commands does not work. In that case, you might want to have your Hystrix commands push metrics to Turbine. Spring Cloud enables that with messaging. To do so on the client, add a dependency to spring-cloud-netflix-hystrix-stream and the spring-cloud-starter-stream-* of your choice. See the Spring Cloud Stream documentation for details on the brokers and how to configure the client credentials. It should work out of the box for a local broker.

On the server side, create a Spring Boot application and annotate it with @EnableTurbineStream. By default, it starts on port 8989 (point your Hystrix dashboard to that port on any path). You can customize the port by setting server.port. The Turbine Stream server requires the use of Spring Webflux, therefor spring-boot-starter-webflux needs to be included in your project.

You can then point the Hystrix Dashboard to the Turbine Stream Server instead of individual Hystrix streams. If Turbine Stream is running on port 8989 on myhost, then put http://myhost:8989 in the stream input field in the Hystrix Dashboard. Circuits are prefixed by their respective serviceId, followed by a dot (.), and then the circuit name.

Spring Cloud provides a spring-cloud-starter-netflix-turbine-stream that has all the dependencies you need to get a Turbine Stream server running. You can then add the Stream binder of your choice — such as spring-cloud-starter-stream-rabbit.
```
but it's needs one more dependency spring-cloud-starter-netflix-hystrix

2.No default port are exposed
>By default, it starts on port 8989 (point your Hystrix dashboard to that port on any path). You can customize the port by setting server.port. The Turbine Stream server requires the use of Spring Webflux, there for spring-boot-starter-webflux needs to be included in your project.

for spring-boot 2.0.2 there are no default port there 8080 and 8989
for spring-boot 2.0.1 there are no default port there 8989 but can access with 8080

**Comment by spencergibb** [comment]
If you look at the source of the docs, I believe those have been updated

**Comment by MadeInChina** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc 
<img width="982" alt="screen shot 2018-05-23 at 6 44 35 pm" src="https://user-images.githubusercontent.com/1201118/40419962-6c86c2e8-5eb9-11e8-8bf6-9515863a2b54.png">
Seems that not updated.

**Comment by ryanjbaxter** [comment]
I fixed these issues in the commit above.  BUILD-SNAPSHOTs should now be compatible with boot 2.0.2 and no additional dependencies should be required.  I also removed the statement in the documentation saying the default port is `8989`.

**Comment by MadeInChina** [comment]
@ryanjbaxter  should using 8080 replace 8989 in the docs as well?
```
You can then point the Hystrix Dashboard to the Turbine Stream Server instead of individual Hystrix streams.
 If Turbine Stream is running on port 8989 on myhost, then put `http://myhost:8989` in the stream input field in the Hystrix Dashboard.	 If Turbine Stream is running on port 8989 on myhost, then put `http://myhost:8989` in the stream input field in the Hystrix Dashboard.
```

<img width="1390" alt="screen shot 2018-05-24 at 10 46 21 am" src="https://user-images.githubusercontent.com/1201118/40461823-c1c4c256-5f3f-11e8-8ab1-146a2efc7777.png">

**Comment by ryanjbaxter** [comment]
No I removed the part of the docs saying that the server starts on port `8989` by default.

> If Turbine Stream is running on port 8989

This is just providing an example, not stating the server will run on port 8989.

**Comment by MadeInChina** [comment]
I see. thanks for that.
