### ISSUE TITLE
Zuul 2 support

### ISSUE THREAD

**Issue by Anthares** [spring-cloud/spring-cloud-netflix#2961]
Hi guys,

Netflix has just open sourced [Zuul 2](https://medium.com/netflix-techblog/open-sourcing-zuul-2-82ea476cb2b3) two days ago so I was wondering if there was any plan (or intent) to upgrade Spring Cloud Netflix to use it.
Since Spring Cloud Gateway has been created, it sounds logical to drop Zuul in a somewhat near future.

My interest is that I'm currently starting to write an api gateway and I was wondering if I should stick to Zuul or switch to Spring Cloud Gateway.

Thanks

**Comment by ryanjbaxter** [comment]
No we are going to move forward with Spring Cloud Gateway.
