### ISSUE TITLE
Zuul Proxy Returning 200 OK with 0 length data after service is shutdown and Eureka has taken it offline.

### ISSUE THREAD

**Issue by tmelhiser** [spring-cloud/spring-cloud-netflix#2963]
During normal operation, the application registers with Eureka.  Zuul subsequently auto registers the route.  The route forwarding works as expected.  However, when the application is stopped and Eureka marks it as down, Zuul still returns a 200 OK status with a content length of 0 for all requests to the route.  No amount of time appears to fix this state.  If the application is restarted and registers with Eureka, the route will become active again. While the app is still down, a restart of Zuul will correctly produce a 404.

The 200 OK behavior when the application is not running causes external applications to incorrectly report that calls to the service were successful. (unfortunately the 3rd party app does not look for any content messaging to validate the request, simply that a 200 event was returned)

Based on Edgware.SR3
Zuul: 1.4.4
Eureka Client: 1.7.2

**Comment by ryanjbaxter** [comment]
Are you using hystrix in Zuul?

**Comment by ryanjbaxter** [comment]
I was wondering if you had `spring-cloud-starter-netflix-hystrix` on the classpath.  This would wrap all routes in Zuul in Hystrix circuit breakers.  I was wondering if maybe the circuit break was possibly being tripped.

If you think the above problem is what you are experiencing it would be worth upgrading to at least 1.5.11, if not 1.5.13 and trying again.

**Comment by tmelhiser** [comment]
A custom ErrorPageFilter indeed fixes this, and I suspect 1.5.11/13 upgrade would as well.  We cannot complete our regression testing in time to make the move to 1.5.13, but it will be on our radar.
