### ISSUE TITLE
Issues with @EnableFeignClients(basePackages) scanning in Spring cloud version Finchley.RC1

### ISSUE THREAD

**Issue by ravireddy76** [spring-cloud/spring-cloud-netflix#2970]
Issues with @EnableFeignClients(basePackages) scanning in Spring cloud version Finchley.RC1;
 
Getting runtime issue saying that beans are not registered, Basically  @EnableFeignClients(basePackages = {"com.xxx.aa", "com.yyy.bb"}) are not scanning the packages and beans not getting registered.

I'm getting beans classes from dependency artifacts.

It will great help if you  guys provide a feasible solution or let us know in which version this issues can be solved.

The above issue used to work in spring cloud version 'Finchley.M5' before spring cmade have changes in feign client.

Thanks
Ravi

**Comment by spencergibb** [comment]
Unfortunately, we don't have enough information to determine if there is a bug or not. 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by spencergibb** [comment]
Actually, feign is no longer supported in the project. If you can provide a sample project, open a new issue here https://github.com/spring-cloud/spring-cloud-openfeign/issues
