### ISSUE TITLE
Eureka client permanently down after refresh

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-netflix#2972]
Issue most likely related to several, but I want emphasize the root problem here (IMHO).
The very last issue that I've found is https://github.com/spring-cloud/spring-cloud-netflix/issues/1857 .

**Pre-requirements:**
cloud version - `Edgware.SR3`
1. setup simplest eureka server
2. setup simplest boot app only with eureka-client dep 
with properties `eureka.instance.initialStatus=DOWN` and `eureka.client.healthcheck.enabled=true`

**Steps to reproduce:**
1. Start service 
- Service registers in eureka with `DOWN` status, since it is initial status.
- `InstanceInfoReplicator` updates status to `UP` as it now uses `EurekaHealthCheckHandler` which was registered by `EurekaAutoServiceRegistration`, but not going to `InstanceInfo` object to get current `DOWN` state
2. Calling /refresh endpoint
- `CloudEurekaClient` bean recreated and re-registers instance in Eureka with initial status `DOWN`
- `InstanceInfoReplicator` keeping re-registering instance with `DOWN` status as it uses empty `HealthCheckCallbackToHandlerBridge` which gets current `DOWN` state from  `InstanceInfo`, but not from `EurekaAutoServiceRegistration`, from which it should.

**Root cause:**
`EurekaHealthCheckHandler` uses `EurekaRegistration` bean as provider for `EurekaClient` object.
Since it's not being recreated it stores old `CloudEurekaClient` and `EurekaHealthCheckHandler` sets to inactive bean (which was dropped of spring context due to refresh scope) instead of newly created one.
It can be easily seen in debug mode, it shows different objects hashcodes in spring context and in `EurekaRegistration` bean.
It actually was the root cause of https://github.com/Netflix/eureka/issues/1025 since it tried to call `onDemandUpdate` on shut down client.

**Possible solutions:**
- Make `EurekaRegistration` bean refresh scoped and use bean `Provider` in `EurekaAutoServiceRegistration` to retrieve bean from context after refresh
- Rewrite `EurekaRegistration.getEurekaClient()` to get `CloudEurekaClient` bean from context, not cached one.

**Why does it actually that matter?**
This issue was possible to find only using `eureka.instance.initialStatus=DOWN` property, but in case of default `UP` you won't be able to see, that after refresh (manual/bus) service won't be `DOWN` anymore, even if some health indicators will go `DOWN`.

**Comment by ryanjbaxter** [comment]
@tdanylchuk interested in submitting a PR?

**Comment by tdanylchuk** [comment]
yes, I'm just trying to pick right approach, so I posted issue firstly.
I'm inclined to 1st and solution - making ```EurekaRegistration``` refresh-scoped and use ```Provider``` instead of direct link to bean.
What do you think?

**Comment by ryanjbaxter** [comment]
Seems like the most strait forward solution

**Comment by ryanjbaxter** [comment]
Closed via c181163
