### ISSUE TITLE
Metrics documentation needs updating.

### ISSUE THREAD

**Issue by illingtonFlex** [spring-cloud/spring-cloud-netflix#2973]
https://cloud.spring.io/spring-cloud-static/Finchley.RC1/multi/multi_netflix-metrics.html

Can we get the documentation clarified for metrics? This still suggests Spectator, which is not part of Finchley. Should I be using Servo instead? There are no details on how to use Servo. Is there another option?

**Comment by spencergibb** [comment]
Closed by bb446cb57972dc2770b8066dd19b6c8f3768bc88
