### ISSUE TITLE
Pass headers from proxy without modification in Zuul

### ISSUE THREAD

**Issue by prokopatti** [spring-cloud/spring-cloud-netflix#2978]
I am using Zuul as an API gateway between proxy and other services. I noticed that Zuul modifies headers coming from proxy. It modifies headers like `x-forwarded-...`, `accept-encoding` or `host`. It also sets `Cookie` header to sensitive and it adds `connection` header. Is it possible to pass all original headers from proxy to other services, without interference of Zuul?

**Comment by ryanjbaxter** [comment]
Are the modifications causing issues in some way?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
