### ISSUE TITLE
Eureka server Unavailable replicas issue

### ISSUE THREAD

**Issue by karthikrajakandasamy** [spring-cloud/spring-cloud-netflix#2986]
I am running 3 Eureka Servers, all three are up, but the Eureka Server's Dashboard displaying the replicas in the unavailable-replicas section. I don't know, why replicas displaying in the unavailable-replicas section?
I am using below configuration for Eureka Servers and Micro service.

Eureka Server1 (application.properties)

server.port=8761

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.health-check.enabled=true

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

eureka.server.eviction-interval-timer-in-ms: 25000
eureka.server.enableSelfPreservation=false

eureka.instance.hostname=localhost1
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/,http://localhost:8763/eureka/

eureka.shouldBatchReplication=true
eureka.instance.appname=eureka-cluster
eureka.instance.metadataMap.zone=Zone1
Eureka Server2 (application.properties)

server.port=8762

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.health-check.enabled=true

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

eureka.server.eviction-interval-timer-in-ms: 25000
eureka.server.enableSelfPreservation=false

eureka.instance.hostname=localhost2
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8763/eureka/

eureka.shouldBatchReplication=true
eureka.instance.appname=eureka-cluster
eureka.instance.metadataMap.zone=Zone1
Eureka Server3 (application.properties)

server.port=8763

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.health-check.enabled=true

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

eureka.server.eviction-interval-timer-in-ms: 25000
eureka.server.enableSelfPreservation=false

eureka.instance.hostname=localhost3
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

eureka.shouldBatchReplication=true
eureka.instance.appname=eureka-cluster
eureka.instance.metadataMap.zone=Zone1
Micro service configuration (appsettings.json)

{
  "Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Information",
      "Pivotal": "Debug",
      "Steeltoe": "Debug"
    }
  },
  "spring": {
    "application": {
      "name": "fortuneService"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": {
        "defaultZone": "http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/"
      },
      "shouldFetchRegistry": true,
      "ValidateCertificates": false,
      "registryFetchIntervalSeconds": 10
    },
    "instance": {
      "appName": "FortuneService",
      "hostName": "localhost",
      "port": 52701,
      "instanceId": "FortuneService2",
      "leaseRenewalIntervalInSeconds": 10,
      "leaseExpirationDurationInSeconds": 5,

      "metadataMap": {
        "zone": "Zone1"
      }
    }
  }
}
![39184880-ced946e8-47e2-11e8-9172-5b50d603354f](https://user-images.githubusercontent.com/34301126/40832899-0867f8ca-65aa-11e8-85cf-22e8c86df281.png)

**Comment by holy12345** [comment]
I think you can modify like this, and have a try.

```
spring.application.name=Eureka-cluster
server.port=8761

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.health-check.enabled=true

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

eureka.server.eviction-interval-timer-in-ms: 25000
eureka.server.enableSelfPreservation=false
eureka.shouldBatchReplication=true
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/,http://localhost:8763/eureka/
```

**Comment by karthikrajakandasamy** [comment]
@holy12345  thanks for your interest to help me. I used above properties, but still am facing the same issue

**Comment by illingtonFlex** [comment]
You have to have different host names for Eureka peers. Check out this post to see how I got it working: https://github.com/spring-cloud/spring-cloud-netflix/issues/2864#issuecomment-385761415

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
