### ISSUE TITLE
Config refresh skipped for some of the containers with  Edgware.SR3 and springboot=1.5.10.RELEASE

### ISSUE THREAD

**Issue by batarayappa** [spring-cloud/spring-cloud-netflix#2990]
Hi All,

When i do config refresh ( after updating properties), config refresh didn't happend for some of the containers for an application. for Example: My application is running in 6 containers(with scale 6) and only 3 containers are refreshed  out of 6. This  will not happen always but some times it is happening. Can you please help me suggest me to fix this issue. Please find below config refresh event code from config server. 

applicationEventPublisher
            .publishEvent(new RefreshRemoteApplicationEvent(
                this, applicationContextId, service))

Thanks in advance.

Harinath.

**Comment by ryanjbaxter** [comment]
You appeared to have opened this in the wrong repo.  It sounds like it might belong in Spring Cloud Config.
