### ISSUE TITLE
Zuul Service cant get the responseBody

### ISSUE THREAD

**Issue by wirechen** [spring-cloud/spring-cloud-netflix#2993]
Question

Hello, There's two service in my test, see this picture:
![zuul](https://github.com/wirechen/github-readme/blob/master/img/responseBody111.png?raw=true)

now, I want the Zuul Service get the `Some String` from A Service, so I debug the last post filter -> `SendResponseFilter` on Zuul Service to watch if there is the `Some String` . here is my debuging picture:
 ![filter](https://raw.githubusercontent.com/wirechen/github-readme/master/img/filter.png)

how can I get the responseBody please?

**Comment by ryanjbaxter** [comment]
Please provide a better description of the problem along with a sample app that reproduces it.

**Comment by wirechen** [comment]
ok~  in a word: I can't get the `responseBody` from another service in `Zuul Service`（see the red line in the picture, responseBody is null）

**Comment by spencergibb** [comment]
The `responseBody` attribute can be null. If it is, the body is read from `getResponseDataStream`

**Comment by Lovnx** [comment]
In order to get response body from original sevices, you should tryyyy: 
`InputStream stream = ctx.getResponseDataStream();`

**Comment by wirechen** [comment]
thanks! I got the body from `getResponseDataStream ` successfully, but I wish we cant get the `responseBody` in Zuul directly.
