### ISSUE TITLE
Upgrade hystrix to 1.4.4

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#300]
It includes changes to the dashboard and proxy servlet:
https://github.com/Netflix/Hystrix/blob/master/CHANGELOG.md

**Comment by spencergibb** [comment]
wait to merge a7658397718afefa8d25c0a039e03a6d03a44cf8 until we have something with an RC

**Comment by dsyer** [comment]
RC for what? Why do we need to wait?

**Comment by spencergibb** [comment]
just worried about changes to the dashboard that haven't really been tried out yet.  If you're ok, I'll merge.

**Comment by dsyer** [comment]
Let's ask @royclarkson or someone to try his dashboard. I assume our sample works because a user asked for this?

**Comment by spencergibb** [comment]
someone noted that 1.0.0 used an RC of hystrix, 1.0.1 snapshot already has hystrix 1.4.1.  I noted the latest was 1.4.4 and had dashboard changes that we should bring along.

**Comment by spencergibb** [comment]
one of the changes was to ignore a header, that was my big worry

**Comment by spencergibb** [comment]
From stackoverflow: http://stackoverflow.com/questions/29622871/spring-cloud-hystrix-dashboard-not-working-with-oauth

**Comment by royclarkson** [comment]
I'm working on testing my changes (using the latest snapshot) in PCF today. What's the issue with the transfer encoding header?

**Comment by spencergibb** [comment]
@royclarkson https://github.com/Netflix/Hystrix/pull/671
