### ISSUE TITLE
Expose Hystrix metrics to Actuator /metrics (and /prometheus)

### ISSUE THREAD

**Issue by alexanderabramov** [spring-cloud/spring-cloud-netflix#3004]
I would like to expose Hystrix metrics to Prometheus. It seems to me that the most natural way with spring-boot 2.0 is to use spring-boot-starter-actuator, spring-cloud-starter-netflix-hystrix and micrometer-registry-prometheus.

However with spring-cloud Finchley.RC2 this does not work. Hystrix stream is exposed to /actuator/hystrix.stream, but metrics are not exposed to /actuator/metrics 

In spring-boot 1.5 + spring-cloud Edgware.SR3 Hystrix metrics were exposed to Actuator /metrics endpoint like so: `gauge.servo.hystrix.hystrixcommand.*`

This might have something to do with `org.springframework.cloud.netflix.hystrix.HystrixMetricsPollerConfiguration` being commented out in 49fdcae with a comment "FIXME 2.0.0".

**Comment by spencergibb** [comment]
All metrics for Hystrix (besides hystrix.stream) and their export are being handled directly with micrometer

**Comment by alexanderabramov** [comment]
Sorry, could you expand on that a little bit?
Are you saying the metrics for Hystrix that spring-cloud-netflix configures are already being handled and I should see them in /actuator/metrics, or that they are not handled, by design, and micrometer is expected to somehow provide that?

**Comment by spencergibb** [comment]
They will be exported by micrometer directly, not thru /metrics

**Comment by spencergibb** [comment]
See https://github.com/micrometer-metrics/micrometer/pull/178
