### ISSUE TITLE
Netflix Turbine does not display cluster hystrix stream

### ISSUE THREAD

**Issue by anandmohan777** [spring-cloud/spring-cloud-netflix#3005]
Hi  @spencergibb 

I tried to use Netflix Turbine (1.X) to group hystrix (1.X) streams.

### Turbine App configuration:
turbine.aggregator.clusterConfig=res
turbine.appConfig=res
turbine.InstanceMonitor.eventStream.skipLineLogic.enabled=false
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
eureka.instance.preferIpAddress= true

### Res App which used hystrix and needs to be displayed in Turbine Dashboard :
Url: http://localhost:9090/hystrix.stream
data: {"type":"HystrixThreadPool","name":"FileController","currentTime":1528897452342,"currentActiveCount":0,"currentCompletedTaskCount":35,"currentCorePoolSize":10,"currentLargestPoolSize":10,"currentMaximumPoolSize":10,"currentPoolSize":10,"currentQueueSize":0,"currentTaskCount":35,"rollingCountThreadsExecuted":0,"rollingMaxActiveThreads":0,"rollingCountCommandRejections":0,"propertyValue_queueSizeRejectionThreshold":5,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"reportingHosts":1}
data: {"type":"HystrixThreadPool","name":"StatsController","currentTime":1528897452342,"currentActiveCount":0,"currentCompletedTaskCount":1,"currentCorePoolSize":10,"currentLargestPoolSize":1,"currentMaximumPoolSize":10,"currentPoolSize":1,"currentQueueSize":0,"currentTaskCount":1,"rollingCountThreadsExecuted":0,"rollingMaxActiveThreads":0,"rollingCountCommandRejections":0,"propertyValue_queueSizeRejectionThreshold":5,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"reportingHosts":1}

### However, I cannot use cluster in Turbine stream and it seems keep loading
![11](https://user-images.githubusercontent.com/10843886/41355388-4bff9fb6-6f19-11e8-96e7-ec3713d159b9.JPG)
![22](https://user-images.githubusercontent.com/10843886/41355392-4e0400b8-6f19-11e8-8539-49e1f52e2aea.JPG)

**Comment by ryanjbaxter** [comment]
If you are not using Spring Cloud this is the wrong repo for this question.

**Comment by ryanjbaxter** [comment]
If you are, please provide a sample that reproduces the problem.

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by anandmohan777** [comment]
@ryanjbaxter , Yes I am using the spring cloud. The code is as follows:

```
@SpringBootApplication
@EnableHystrixDashboard
@EnableTurbine
@EnableHystrix
@EnableEurekaClient
public class HystrixDashboardServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(HystrixDashboardServerApplication.class, args);
    }

    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(HystrixDashboardServerApplication.class);
    }
}
```

**Comment by spencergibb** [comment]
> please provide a sample that reproduces the problem.

Please provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by anandmohan777** [comment]
This is solved now. I just changed following properties:
turbine.app-config=keyservice,res
turbine.cluster-name-expression=new String('default')
