### ISSUE TITLE
How to extract serviceId from Eureka for given ipaddress/port.

### ISSUE THREAD

**Issue by harinathbk** [spring-cloud/spring-cloud-netflix#3006]
Hi ,
I want to find out destination container serviceId based on ip/port for  Feign and rest clients calls in my application. I can fetch from Eureka but it is taking time because i need read one by one from eureka using DiscoveryClient.getInstances( serviceName) method .

Ribbon client  is already fetching and storing in cache for load balancing. Is there any way to re-use this functionality out of the box(I mean using ribbon client code) ?

Harinath.

**Comment by spencergibb** [comment]
If you're asking to get a service id from a host and port that is not possible

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
