### ISSUE TITLE
Adding support for IRule key in RibbonLoadBalancerClient

### ISSUE THREAD

**Issue by andersenleo** [spring-cloud/spring-cloud-netflix#3009]
Hi -

As far as I can tell it should be pretty straight forward (code-wise) to add support in `RibbonLoadBalancerClient` for propagating "key" for an `IRule` implementation. Currently the "key" concept seems to be missing. I'm *guessing* one of the reason is that the cloud-common `LoadBalancerClient` doesn't want to tie itself too hard into any implementation?

Our scenario is that we're implementing stateful client-side load-balancing where certain entities are "bound" to certain service instances and we're using the "key" to tell an `IRule` to find the service that owns that specific entity. We've recently started porting some of our micro-services from a homegrown Spring framework (where we do a manual setup of Ribbon and uses the `LoadBalancedCommand` to propagate the "key") to a Spring-Boot based solution. We would like to leverage as much as possible on what spring-cloud provides (such as discovery against Consul, for example).

The "dream scenario" for us would be to be able to do something like:

```java
WebClient client = WebClient.builder().baseUrl("http://STORE")
  .filter(lbFilter)
  .build();
client.post()
  .uri("/update/ID")
  .body(BodyInserters.fromObject("foo"))
  // Specify the key for the IRule
  .attribute("load-balancer-key", "ID")
  .retrieve()
  .bodyToMono(String.class)
  .single().block();
```

Where it's possible to pass on the "key" through the `ExchangeFilterFunction` for a load-balanced WebClient, or to simply call `LoadBalancerClient#execute("myService", "theKey", instance -> callWithRestTemplate(...))` (which is what the exchange-filter-function would be using behind the scene). 

So - why no access to the "key" in the `RibbonLoadBalancerClient`? And - would it make sense to work on a pull-request to get it in there? If we'd like to keep the `LoadBalancerClient` free from hard dependencies on the Ribbon model we could call it "hint" in the `LoadBalancer` API (similar to how `org.springframework.messaging.converter.AbstractMessageConverter` is done).

**Comment by ryanjbaxter** [comment]
As far as the reason goes, you are probably right, we didnt want to tie `LoadBalancerClient` to Ribbon.  

Maybe instead of "hint" we can have a Map of metadata instead (allowing more flexibility).  Feel free to submit a PR with an idea of your proposal.

**Comment by andersenleo** [comment]
Cool - I'll get hacking on a PR. I'll start by flushing out something in `spring-cloud-netlix-ribbon` to get some feedback (the final solution would have to touch the `spring-cloud-commons` `LoadBalancerClient` API, and that's in another repo).

**Comment by andersenleo** [comment]
So, I did a quick and obvious hack. Notes are in the PR - the main question is really how this change can be allowed to affect the `spring-cloud-commons` `LoadBalancerClient` API? 

An initial version could maybe be scoped to the `spring-cloud-netflix` implementation only, and users can decide to autowire the sub-classed version of component to take advantage of "hint-support" until the concept is propagated up to `spring-cloud-commons`.

Anyhow - comments are welcome.

**Comment by spencergibb** [comment]
We'll see if this gets any use and if there is interest in updating commons.
