### ISSUE TITLE
Zuul proxy manages cookies badly in HTTP client

### ISSUE THREAD

**Issue by todda86** [spring-cloud/spring-cloud-netflix#301]
I have a standalone  Zuul proxy application using @EnableZuulProxy configured to proxy to a simple spring boot application.  This target application is configured with spring security and spring session, it has also registered with a Eureka instance.

Initially everything looked fine when proxied through Zuul.  Then I discovered the origin server's "SESSION" cookie was being stored in the proxy and passed on with subsequent requests from *different clients*.  Essentially causing the same session data to be used by multiple clients. 

Here are the Zuul routes, and "BootDemo" is registered in Eureka:

```
zuul:
  ignoredServices: '*'
  routes:
    BootDemo: '/**'
```

I have observed this with both 1.0.0-RELEASE as well as 1.0.1.BUILD-SNAPSHOT.  

This seems like a bug, but if not is there a way to easily configure Zuul to NOT hold these cookies.

**Comment by spencergibb** [comment]
Our zuul filters aren't designed to hold cookies, if they do, it is broken.  How did you "discover the origin server's SESSION cookie was being stored in the proxy"?  You're going to need to provide much more detail than you have given.  Perhaps a project to share and steps to replicate?  We have successfully used zuul with spring security and haven't observed what you are seeing.

**Comment by todda86** [comment]
I wanted to be sure I  wasn't chasing an expected behavior.   I'll try to create simple app that recreates this tonight.

**Comment by spencergibb** [comment]
no, it is definitely not expected.

**Comment by todda86** [comment]
I created some sample projects to illustrate what I'm seeing:  https://github.com/todda86/zuulCookies

In the original issue report it was mentioned that spring-session and spring-security were used in the origin service.  Those have been removed from this example as they weren't relevant to demonstrate this behaviour.


Reproducing the issue

start each component in a terminal window using: 
```
mvn spring-boot:run -Deureka.password=password
```

1. start a local Eureka at localhost:8761 (I used a fresh clone of spring-cloud-samples/eureka)
2. Start the zuul proxy contained in the "zuulProxy" directory, listens on 9080
3. Start the demo app in the "demoApp" directory, listens on 8080


Hit the origin server directly a few times (port 8080) using curl.  The HTTP session ID changes each time because curl is not sending a JSESSIONID cookie on subsequent request.  Exactly as I would expect.
```
$ curl localhost:8080/welcome
Your session ID is:415C1592AB6E6A985DF668799702C5C5~
$ curl localhost:8080/welcome
Your session ID is:45FB0577B6AC321AF6C28572FFA82335~
$ curl localhost:8080/welcome
Your session ID is:70C6913D4AC0BFAEB546EB9646A4AAD5~
$ curl localhost:8080/welcome
Your session ID is:80E676875F8C06FA60FD370C7033358B~
```

Then hit the Zuul proxy address on port 9080. Notice the sessionId never changes. To further illustrate it's possible to hit the proxy URL from Chrome, the same sessionId will be returned and dev tools will show that no JSESSIONID was sent in the request  

```
$ curl localhost:9080/welcome
Your session ID is:1DE380F4C4ACFDDDBA127AD07D612F44~
$ curl localhost:9080/welcome
Your session ID is:1DE380F4C4ACFDDDBA127AD07D612F44~
$ curl localhost:9080/welcome
Your session ID is:1DE380F4C4ACFDDDBA127AD07D612F44~
$ curl localhost:9080/welcome
Your session ID is:1DE380F4C4ACFDDDBA127AD07D612F44~
$ curl localhost:9080/welcome
Your session ID is:1DE380F4C4ACFDDDBA127AD07D612F44~
```

What I think is happening

SessionID never changes because the JSESSIONID cookie is being captured and re played.  I stepped around in the debugger quite a bit and found that the RestClient used by RibbonRoutingFilter ultimately delegates to an NFHttpClient instance.   That Netflix class extends the base DefaultHttpClient that by default configures the cookie processing interceptors.  

from DefaultHttpClient
```
        // HTTP state management interceptors
        httpproc.addInterceptor(new RequestAddCookies());
        httpproc.addInterceptor(new ResponseProcessCookies());
```

Evidence of these interceptors running is in the debug logs of the zuul server:

first request, captures the cookie:
```
2015-04-15 00:21:14.645 DEBUG 94103 --- [nio-9080-exec-1] o.a.h.c.protocol.ResponseProcessCookies  : Cookie accepted [JSESSIONID="1DE380F4C4ACFDDDBA127AD07D612F44", version:0, domain:localhost, path:/, expiry:null]
```

It gets added in subsequent requests:

```
2015-04-15 00:22:05.736 DEBUG 94103 --- [nio-9080-exec-3] o.a.h.client.protocol.RequestAddCookies  : Cookie [version: 0][name: JSESSIONID][value: 1DE380F4C4ACFDDDBA127AD07D612F44][domain: localhost][path: /][expiry: null] match [localhost:8080/welcome]
```

**Comment by spencergibb** [comment]
In practice, when I use spring security and set the JSESSIONID, this doesn't happen.  Your code does not set the cookie.  Maybe someone from spring-security or spring-mvc could comment (@dsyer, @rwinch or @rstoyanchev)?

**Comment by rwinch** [comment]
>  Maybe someone from spring-security or spring-mvc could comment 

@spencergibb In a [comment](https://github.com/spring-cloud/spring-cloud-netflix/issues/301#issuecomment-93409420) @todda86 mentions:

> In the original issue report it was mentioned that spring-session and spring-security were used in the origin service. Those have been removed from this example as they weren't relevant to demonstrate this behaviour.

I'm curious why you are looking for a comment from Spring Security. Am I missing something?

**Comment by spencergibb** [comment]
@rwinch I guess I'm looking for implications of this problem.  When I have spring security enabled, I don't see this behavior.

**Comment by todda86** [comment]
It seems this is specific to using Eureka service routing (RibbonRoutingFilter).  When I change the routing to be URL based I can no longer reproduce the issue. 

Reproduces the issue:
```
zuul:
  ignoredServices: '*'
  routes:
    DemoApp: '/**'
```

Works as expected:
```
zuul:
  ignoredServices: '*'
  routes:
    DemoApp:  
      path: '/**'
      url: http://localhost:8080
```

I also modified my sample to explicitly set a cookie just to make it clearer what exactly is going on.  It is still easily reproducible and produces the same debug log output from the interceptors (but now with 2 cookies)

**Comment by spencergibb** [comment]
@todda86 that makes sense, `RibbonRoutingFilter` uses ribbon's `RestClient`.  `SimpleHostRoutingFilter` use apache `HttpClient`.  I would expect they behave quite differently.

**Comment by spencergibb** [comment]
You could eliminate spring cloud completely and this behavior would still be there.

**Comment by todda86** [comment]
@spencergibb I agree groovy filters published in NF Zuul repo would likely produce similar results since I believe they also use ```RestClient``` but I haven't tested that.  ```RestClient``` ultimately uses ```HttpClient``` but it never modifies the cookie policy like ```SimpleHostRoutingFilter``` does:

```
private static HttpClient newClient() {
   ....
   
httpParams.setParameter(ClientPNames.COOKIE_POLICY,
					org.apache.http.client.params.CookiePolicy.IGNORE_COOKIES);
```

After more digging round it's pretty clear the root issue is in the Netflix ```RestClient``` class that ```RibbonRoutingFilter``` uses.   The issue is easily reproduced.  The filter itself isn't broken, it delegates to a library that is broken for this use case.  I haven't checked, but I bet ```RestClient``` is also used by Feign, and in that use case the cookie storage might make more sense (Unless your a REST purist of course).

Be that as it may, at best it makes```RibbonRoutingFilter``` unsuitable  for any use case involving cookies.  At worst it's a huge security breach waiting to happen.  I haven't been able to find any way to override the underlying cookie policy settings.  Is a completely new routing filter the only way out here (ughh)?  Have I missed something that is plainly obvious?

**Comment by dsyer** [comment]
It is a nasty bug and although it doesn't impact Spring Security at all, I know @rwinch likes to keep abreast of security issues in the rest of the Spring code base. It hasn't been an issue for any existing applications that we have written because they all use browser clients, which always send the right cookie (I believe). But this *is* potentially a nasty security vulnerability .  

Even the existing apps are vulnerable because once they have been used by any authenticated user, all other users, or even a curl with no authentication, will see the session of the original user (whose cookie would be in the Apache HTTP `CookieStore` in the Ribbon client).

The fix is just to set the `CookiePolicy` explicitly (the interceptor respects the policy, so you only need to change one and not the other).

**Comment by denyska** [comment]
@dsyer @spencergibb The same problem affects **RibbonLoadBalancingHttpClient**  with potentially easy fix:
`private final HttpClient delegate = HttpClientBuilder.create().disableCookieManagement().build();`

**Comment by spencergibb** [comment]
PR?

**Comment by denyska** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/pull/1173
