### ISSUE TITLE
When the load balancing forwarding request is forwarded to the wrong address

### ISSUE THREAD

**Issue by abysschendonghui** [spring-cloud/spring-cloud-netflix#3016]
hi
  I have two different services "a1:8080","a2:8088",which are integrated by swagger-ui. When I use zuul to access, the request is loaded into the wrong service. 
  eg: 
      http://zuulhost/a1/swagger-ui.html hope to http://a1:8080/swagger-ui.html
      but it go to http://a2:8088/swagger-ui.html 
  The error occurred only after two requests were accessed. like this way:
   fist access http://zuul/a2/swagger-ui.html ,second access http://zuul/a1/swagger-ui.html 
  now you access to 
   then you will see this bug! how to fix it?

**Comment by abysschendonghui** [comment]
Find the reason why you need to pay attention to custom rules.
添加Scope 
@Bean
    @Scope(scopeName = "prototype")
    public IRule getMyRule(){
        MyRule myRule= new MyRule();
        myRule.setServerBlackMap(serverBlackMap);
        return myRule;
    }

**Comment by ryanjbaxter** [comment]
Sounds like you found the reason why this is happening.  If not please reopen with a sample that reproduces it.

**Comment by abysschendonghui** [comment]
because the Spring bean default scope is singleton rule has lb could be overwite . 
I think 
Maybe change the way to define the rule in profiles will fix

**Comment by abysschendonghui** [comment]
I do custom rules by way of @bean injection, so the rules I rewrite are managed by spring. Spring bean is by default a singleton, so the LB in the rule will be reused. I don't know why LB has not been reassigned, which has led to this problem. I think we can avoid this problem by specifying custom rules in the YML file.
