### ISSUE TITLE
[QUESTION] Is there any way to use Feign client built with EDGWARE release in service with FINCHLEY (M7+) 

### ISSUE THREAD

**Issue by Fetsivalen** [spring-cloud/spring-cloud-netflix#3026]
Hi, 
Are you have any plans to simplify spring-cloud-netflix-core migration to Spring cloud FINCHLEY M7+?
We have a lot of microservices and each one produce its Feign client as a separate module.

I'm trying to migrate one of our services to Spring Cloud FINCHLEY SP2, from EDGWARE SP3 release. 
And I found out that Feign annotations moved to another package. (@FeignClient for example.) 
```
from
import org.springframework.cloud.netflix.feign.FeignClient;
to
import org.springframework.cloud.openfeign.FeignClient;
```
Also, I found out that HttpMessageConvertors and SpringEncoder/Decoder change their packages.
```
from
import org.springframework.boot.autoconfigure.web.HttpMessageConverters;
import org.springframework.cloud.netflix.feign.support.SpringEncoder;
to
import org.springframework.boot.autoconfigure.http.HttpMessageConverters;
import org.springframework.cloud.openfeign.support.SpringEncoder;
``` 
I've played with dependencies, but unable to find configuration when service is able to run with "old" client. 
I even tried to add both EDGWARE and FINCHLEY dependencies to the classpath, but during startup, I  found conflict in one of the spring-boot-autoconfigure autoconfiguration.
So far I found only one solution for the case:
Each service must produce 2 feign clients:
1. Based on FINCHLEY M7+ 
2. Based on EDGWARE. 
But this solution doesn't look good.
Will much appreciate for any advice regarding simplification migration.

**Comment by ryanjbaxter** [comment]
With Finchley it was our opportunity to reorganize things and introduce some breaking changes.  This was one of the breaking changes we introduced (moving OpenFeign from Netflix to its own project).  The only way is to update the packages.  (Which I imagine could be scripted fairly easily).
