### ISSUE TITLE
Q: server.port within container

### ISSUE THREAD

**Issue by torsten-liermann** [spring-cloud/spring-cloud-netflix#303]
Hi,

The use of @EnableEurekaServer within a container (e.g. Tomcat) is probably not intended, but nevertheless it is a valid usecase for us and we need it.
We have a problem with the definition of server.port in the default zone in the form that in the url

http://localhost:${server.port}/eureka/

the server.port is not being set via spring. Is there an elegant solution to this? Should this port be set from the container (tomcat, jetty, glassfish) or should the Eureka configuration be stored in the config service?

Thanks!
Torsten

**Comment by spencergibb** [comment]
So what symptoms are you seeing?  Eureka Server won't start?  It start's with port 0?

**Comment by torsten-liermann** [comment]
As said: the server.port is not set and so the Eureka server takes http://localhost:${server.port}/eureka/ (corresponding error messages in the log and the eureka ui shows the url string below "unavailable replica").

Setting server.port manualy to 0 the url is as expected http://localhost:0/eureka

**Comment by dsyer** [comment]
The only reason a eureka server needs the address of a eureka server is for peer replication. Is it registering itself with a peer? If so then you just need to set the instance metadata appropriately. You know the port, host and path, so you can set them in the `eureka.instance.*` properties, either locally or in the config server if you are using it.

**Comment by torsten-liermann** [comment]
Thanks, all that is clear. In short: it would be really nice if the value of server.port would also be set when running eureka within a container (without having to set in manually). Currently, server.port has no value if running within a container (e.g. tomcat)

**Comment by dsyer** [comment]
AFAIK there is no way for a non-embedded app to discover the port of its container. Do you know a way to get it?

**Comment by torsten-liermann** [comment]
There is no generic solution, unfortunately. It seems this only specific through container-specific implementations.
