### ISSUE TITLE
Issue when remove/shutdown a service instance

### ISSUE THREAD

**Issue by sunnyguohua** [spring-cloud/spring-cloud-netflix#3032]
Bug report

Not sure it's a Bug or not.
We are using:
        springBootVersion = '1.5.11.RELEASE'
	springCloudVersion = 'Edgware.RELEASE'
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8

When we remove/shutdown a service instance(say service A) from the eureka-server,  caller(say service B) will failed occasionally after removing happened for some time.

And, we found two issues:
1. Error in service B: java.lang.IndexOutOfBoundsException: index (3) must be less than size (2)
2. health information in service B show wrong number of service A instances, even the number is correct in eureka-server.

for Issue 1. we update ribbon-loadbalancer from 2.4.4 to 2.4.5, to resolved the issue.
for Issue 2. any help?

**Comment by ryanjbaxter** [comment]
Please retry with Edgware.SR3 or Finchley.RELEASE.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
