### ISSUE TITLE
Q: Zones, Regions, Ribbon and Eureka

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#304]
I have been looking into making my app using Spring Cloud highly available on Bluemix.  I started out deploying Eureka to our US datacenter and UK datacenter and set them up as peers.  This worked fine.  Instances of my services registering themselves in each region were being replicated between the peers. 

I then started reading some of the Eureka documentation and realized they do not recommend having Eureka instances across regions being peers.  However they are making an assumption you are running Eureka in AWS, and you have the extra redundancy of zones within a region.  In the Bluemix case, that is not the case (yet).  

What I would like to have happen is if a service in one Bluemix region is down that services flip over to use a service in another region.  So it sounds like in Eureka terminology I want to treat a Bluemix region as a zone instead.  Does that make sense?  

In addition I want to make sure services in the same region always use other services in that region if they are up.  Eureka sounds like it supports this, but again only with a "zone" and not across a region.

So I guess my question is what is the right way to configure Eureka clients and servers to accomplish this?  The documentation only shows how to leverage the default zone and from what I can tell by reading the Eureka documentation it makes a lot of assumptions that zones are referring to AWS zones and if you are running in another cloud environment those assumptions might break things.

**Comment by ryanjbaxter** [comment]
OK so i saw a small section about Zones and Ribbon in the [documentation](http://projects.spring.io/spring-cloud/spring-cloud.html#_using_ribbon_with_eureka).  Sounds like maybe `approximateZoneFromDomain` is something that might help me.  Each Bluemix region has a different domain (the use is mybluemix.net the UK is eu-gb.mybluemix.net).  Thoughts?

Also I looked through the code for `approximateZoneFromDomain` but only found a reference in to that string in the documentation.  In the code there is a property called `approximateZoneFromHostname`, is there a typo in the documentation?  What is the complete property name I should be setting?  Do I set it to true/false?

**Comment by ryanjbaxter** [comment]
Looks like the correct property value is `ribbon.eureka.approximateZoneFromHostname`.

**Comment by ryanjbaxter** [comment]
created issue #314 to track the above documentation issue

**Comment by ryanjbaxter** [comment]
Also see issue #315 which I think also is related to making my above scenario work

**Comment by ryanjbaxter** [comment]
I think I have resolved the problems I had in #314 and #315 so we can close this issue

**Comment by intecos** [comment]
meet the same question, thanks a lot
