### ISSUE TITLE
Misconfiguration in the docs - SC Finchley

### ISSUE THREAD

**Issue by marcosbarbero** [spring-cloud/spring-cloud-netflix#3044]
Looks like there's a misconfiguration in the [project page](http://projects.spring.io/spring-cloud/) for Spring Cloud `Finchley`.

It should be `spring-cloud-starter-netflix-eureka-server` instead of `spring-cloud-starter-eureka`.

**Comment by ryanjbaxter** [comment]
Fixed via https://github.com/spring-projects/spring-cloud/commit/bc790633acfdc7834ccb8a80b623b2fa5a0d5985
