### ISSUE TITLE
RibbonClient Constructing Invalid URLs

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#305]
I am trying to transition from 1.0.0-RC3 to 1.0.1-SNAPSHOT and have run into a problem with one of my service calls using Feign.  The problem appears to be in the Netflix RibbonClient code and looks like the Feign dependencies were upgraded from 7.1 to 8.1 between 1.0.0-RC3 and 1.0.1-SNAPSHOT.

Anyways here is the problem...

I am using Feign to call a service called questions.  The resource I am calling is at the path /questions/answered.  So when we get down to RibbonClient.execute the request URI looks like `http://questions/questions/answered`.  On [line 66](https://github.com/Netflix/feign/blob/master/ribbon/src/main/java/feign/ribbon/RibbonClient.java#L66) of RibbonClient.execute there is
`URI uriWithoutHost = URI.create(request.url().replace(asUri.getHost(), ""));`
which is replacing all instances of "questions" in the URI above causing the URI to end up looking like `http:////answered/2539e32d9dbe93cf7d992576a5000789` which is incorrect, it should be `http:///questions/answered/2539e32d9dbe93cf7d992576a5000789`.  This causes the request to my questions service to fail.

**Comment by spencergibb** [comment]
so the workaround is to not have service and uri parts be the same :-(

**Comment by spencergibb** [comment]
working on it https://github.com/Netflix/feign/pull/222

**Comment by spencergibb** [comment]
The fix is merged, waiting for release.

**Comment by ryanjbaxter** [comment]
Awesome, thanks!

**Comment by spencergibb** [comment]
fixed by 6dce075e991faa12e68be2e48cb4adbd462f18d3
