### ISSUE TITLE
How to dynamically ribbon.listOfserver without eureka

### ISSUE THREAD

**Issue by GreedyPirate** [spring-cloud/spring-cloud-netflix#3050]
I want to custom ServerList, here is my code 

`
@ConditionalOnProperty(value = "frame.qconf.enabled", matchIfMissing = true)
@Bean
     public ServerList<Server> ribbonServerList(Environment environment, PropertiesFactory propertiesFactory, IClientConfig config) {
        if (propertiesFactory.isSet(ServerList.class, name)) {
            return propertiesFactory.get(ServerList.class, config, name);
        }
        String qconfUrl = getQconfUrl(environment, name);
        if (StringUtils.isEmpty(qconfUrl)) {
            ConfigurationBasedServerList serverList = new ConfigurationBasedServerList();
            serverList.initWithNiwsConfig(config);
            return serverList;
        }
        return new QconfBasedServerList(qconfUrl, config);
    }

`

but I catch such a error 

`Could not resolve placeholder 'ribbon.client.name' in value "${ribbon.client.name}"`

I found that `ribbon.client.name` should be @FeignClien's name property, and ServerList bean should be initialized at the first service call

**Comment by spencergibb** [comment]
Have you read this section of the docs? http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/multi/multi_spring-cloud-ribbon.html#_customizing_the_default_for_all_ribbon_clients

**Comment by GreedyPirate** [comment]
@spencergibb I did it successfully follow the docs, but i still have such a question，how to make a test prove @Bean ServerList be created， because it's in a common project , i have to make sure ever release version is stable
