### ISSUE TITLE
How to test @Bean ServerList be created？

### ISSUE THREAD

**Issue by GreedyPirate** [spring-cloud/spring-cloud-netflix#3057]
I customed a Ribbon client config follow the docs, but i want to know how to make a test to prove @bean ServerList be created， because it's  a base project of my projects , i have to make sure every release version is stable.
This is the main part of my code：

```
@Configuration
@ConditionalOnClass(Ribbon.class)
public class RibbonConfig {
    @RibbonClientName
    private String name = "client";

    @ConditionalOnProperty(value = "xxx.xxx.enabled", matchIfMissing = true)
    @Bean
    public ServerList<Server> ribbonServerList(Environment environment, PropertiesFactory propertiesFactory, IClientConfig config) {
        if (propertiesFactory.isSet(ServerList.class, name)) {
            return propertiesFactory.get(ServerList.class, config, name);
        }
        String qconfUrl = getQconfUrl(environment, name);
        if (StringUtils.isEmpty(qconfUrl)) {
            ConfigurationBasedServerList serverList = new ConfigurationBasedServerList();
            serverList.initWithNiwsConfig(config);
            return serverList;
        }
        return new QconfBasedServerList(qconfUrl, config);
    }
}

@RibbonClients(defaultConfiguration = RibbonConfig.class)
public class GlobalRibbonConfig {}

@Configuration
@ConditionalOnClass(Feign.class)
@Import(GlobalRibbonConfig.class)
public class EarthFeignAutoConfiguration {}
```

finally,`EarthFeignAutoConfiguration` will be set in spring.factories, then I made this test

```
private ApplicationContextRunner contextRunner = new ApplicationContextRunner()
			.withConfiguration(AutoConfigurations.of(EarthFeignAutoConfiguration.class));
        @Test
	public void testBeanCreation() {
		Assert.assertNotNull(bean);
		this.contextRunner.run(context -> {
			assertThat(context).hasSingleBean(ServerList.class);
		});
	}
```

and test failed ,  I found that original bean `ServerList` be created once after a @FeignClient service called, so I add a service call in above unit test code， but also failed，`ServerList`  will be created after the test completed，so i really want to how to make a unit test to make sure `ServerList` bean will be created

**Comment by spencergibb** [comment]
It's not available in the parent context, each ribbon client gets its own context. See https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-ribbon/src/test/java/org/springframework/cloud/netflix/ribbon/RibbonClientsPreprocessorIntegrationTests.java for how to use the `SpringClientFactory` to get ribbon beans for a named ribbon client.
