### ISSUE TITLE
Content-Encoding header name is case-sensitive, can break gzipped responses

### ISSUE THREAD

**Issue by chornyi** [spring-cloud/spring-cloud-netflix#306]
The content-encoding header name is case-sensitive here: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java#L108-L116

If the case of the header is not as expected by the code, gzipped responses are not handled correctly and the header is not relayed to the caller.

One solution would be to lower-case all headers here and then treat them as such everywhere: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java#L230-L240

**Comment by jettro** [comment]
Not sure if I should comment on a closed Issue, but I still have this problem. I have a header with lowercase: "content-encoding". Therefore my responses are now handled as not being gzipped while they actually are and I get all crappy characters on my screen.

**Comment by dsyer** [comment]
This issue is marked as closed in 1.0.4. Which version are you using?

**Comment by jettro** [comment]
I am using 1.1.0.M3, also created a new issue to better explain what my problem is:
https://github.com/spring-cloud/spring-cloud-netflix/issues/662
