### ISSUE TITLE
Zuul Static Resources Not Found ..

### ISSUE THREAD

**Issue by Yvan0329** [spring-cloud/spring-cloud-netflix#3061]
I configured the hystrix dashboard forwarding with zuul, but found some problems, static resource files were not found.
This is my zuul configuration：
![image](https://user-images.githubusercontent.com/25361947/42378053-6f6b79a6-8158-11e8-9395-b18946ac0bc6.png)
This is my dashboard configurarion:
![image](https://user-images.githubusercontent.com/25361947/42378136-bd95b592-8158-11e8-97b7-a105d1a06a58.png)
When I visit the http://localhost:8080/dashboard/hystrix page, the image and js are not found, but the page can display normally.
![image](https://user-images.githubusercontent.com/25361947/42378189-f66aaa1c-8158-11e8-8cb7-e5bf4ea8f7a0.png)
The address of the picture and js access is:
![image](https://user-images.githubusercontent.com/25361947/42378256-3f78ed2c-8159-11e8-93f7-6badf9d4a1dc.png)
The reason they can't find it is because there is no prefix/dashboard~~
Can you help me solve this problem? thank u very much~~~

**Comment by dev-priporov** [comment]
could you please provide us with a simple project that will reproduce that?

**Comment by ryanjbaxter** [comment]
Its probably not going to honor the `X-Forwarded-Prefix` header and use paths through Zuul.

**Comment by Yvan0329** [comment]
@ryanjbaxter you right.

**Comment by ryanjbaxter** [comment]
I will leave this open as an enhancement.  If someone wants to submit a PR to fix it that would be welcome.

**Comment by looseend** [comment]
In our Application class we added the following config:

`    @Bean
    public ForwardedHeaderFilter forwardedHeaderFilter() {
        return new ForwardedHeaderFilter();
    }
`
And the static resources are now served correctly.

**Comment by rustamzh** [comment]
Issue #2046 is also related.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
