### ISSUE TITLE
status”:500,“error”:“Internal Server Error”,“exception”:“com.netflix.zuul.exception.ZuulException”,“message”:“REJECTED_THREAD_EXECUTION”}

### ISSUE THREAD

**Issue by rohitdec01** [spring-cloud/spring-cloud-netflix#3064]
{"timestamp":1531026130373,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"REJECTED_THREAD_EXECUTION"}

I am getting above exception while running stress testing on my one of the API redirecting from zull gateway.

Here is some of the more points which I want to mentioned here.

I am using netflix zull and eureka for discovery my microservices (spring boot).

Everything is working fine from my angular application, postman and swagger.

Now I am trying to do stress testing using Jmeter tool which is working fine for <=10 no. of thread usersload. But as soon as I am mentioning more than 10 no. of thread users. It is giving me above mentioned exception.

I also tried to test my API directly (without gateway -zull) and that is also working fine in case of more than 10+ no. of thread users and that is working fine too.

I tried to replicate same scenario on my local laptop and used the same jmeter. And this time rather giving the server host name I try to test with my laptop hostname (all code and services are same). I mentioned 10+ no. of thread users in jmeter and that is working fine with no above exception.

I read lot of stack-overflow posts, github links and other web search for this issue but none of solution seems to working. I tried and some other

ribbon: ReadTimeout: 60000 ConnectTimeout: 60000

hystrix: command: default: execution: isolation: strategy: THREAD thread: timeoutInMilliseconds: 60000

**Comment by holy12345** [comment]
HI @rohitdec01 

Could you please change `hystrix.threadpool.default.coreSize` the number, because in my mind it default value is `10`.

In addition i notice you have those parameter
```
ribbon. ReadTimeout: 60000
ribbon.ConnectTimeout: 60000
hystrix: command: default: execution: isolation: strategy: THREAD thread: timeoutInMilliseconds: 60000
```
Could you please change it like this 
```
ribbon. ReadTimeout: 60000
ribbon.ConnectTimeout: 60000
hystrix: command: default: execution: isolation: strategy: THREAD thread: timeoutInMilliseconds: 240000
```

In my mind Hystrix timeout should include all retry time(include retry same server and next server), because ribbon retry same server default is `0` and retry next server default is `1`. 

Hope it can help you

thanks

**Comment by rohitdec01** [comment]
thanks for your quick reply. I already tried below properties as well but getting some other Zull exception after this. (mentioned below)

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  

hystrix:
  threadpool:
      default:
        coreSize: 1000
        maximumSize: 2000
        maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          timeout:
            enabled: false
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 240000


{"timestamp":1531112495424,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"SHORTCIRCUIT"}

**Comment by rohitdec01** [comment]
![application-properties](https://user-images.githubusercontent.com/12552208/42431558-51dabb46-8314-11e8-9187-4afe3da4d363.PNG)

**Comment by rohitdec01** [comment]
No, still the same issue. Attached is the screenshot.

![error](https://user-images.githubusercontent.com/12552208/42454505-b30cbbbe-835d-11e8-8a14-bd43577b72d6.png)

**Comment by rohitdec01** [comment]
My manager told me to remove zull and do the load testing untill this issue get fixed. So, I will come back in a day or 2 on this. 

I will share the entire exception.

**Comment by jprateekvmware** [comment]
Any update here

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by sumanb21** [comment]
i also got same exception

**Comment by Lakshman54** [comment]
I also got the same exception

**Comment by ishrivasayush** [comment]
I also got the same Exception
