### ISSUE TITLE
unregister a eureka client from normal shutdown, and let zuul not longer proxy to this unregistered client imediately

### ISSUE THREAD

**Issue by s-mop** [spring-cloud/spring-cloud-netflix#3071]
I want zuul proxy user's http request to the others living eureka client instead of show 'timeout error' when I shutdown a eureka client by terminate signal (kill -15 or ctrl-c command etc)
I have tried the config 'eureka.client.should-unregister-on-shutdown=true'  but it seems not work.eureka console still show 'DOWN' status for a while
I know the 'DOWN' status node will be removed after a few seconds (by eureka.instance.lease-expiration-duration-in-seconds),but it's not a good user experience I think(in this time,some of the request will reponse by timeout error message)

**Comment by ryanjbaxter** [comment]
You would have to use Ribbon and use Spring Retry to make Zuul retry another instance in the case of a timeout.  http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#retrying-failed-requests

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
