### ISSUE TITLE
"loadBalancerKey" value is not accessble in subclass of IRule.java

### ISSUE THREAD

**Issue by harinathbk** [spring-cloud/spring-cloud-netflix#3072]
Hi All,

Im setting FilterConstants.LOAD_BALANCER_KEY in Zuul Pre Filter but not able to access in IRule sub classes. May i know what value we need to set for FilterConstants.LOAD_BALANCER_KEY? is it serviceId or route or etc..
Please find below spring cloud version ,pre-Filter and IRule sub-class.

Thanks in advance.
springCloudVersion=Edgware.SR4
springBootVersion=1.5.10.RELEASE
@slf4j
@component
class PreAddLoadBalanceKeyFilter extends AbstractZuulFilter {

PreAddLoadBalanceKeyFilter() {
super(PRE_ROUTING_HANDLING, 1111);
}

@override
public boolean shouldFilter() {

return true;
}

@override
protected void execute() {
final RequestContext requestContext = RequestContext.getCurrentContext();

RequestContext.getCurrentContext()
    .set(FilterConstants.LOAD_BALANCER_KEY, "service-v1");
}
}
@slf4j
@component
@primary
public class CusctomRoundRobbinRule extends RoundRobinRule {

@override
public Server choose(Object o) {
return choose(getLoadBalancer(), o);
}

public Server choose(ILoadBalancer lb, Object key) {

log.info("loadblancekey::"+(String)key);

return server;
}
}

**Comment by spencergibb** [comment]
Duplicates #1272
