### ISSUE TITLE
Weightedresponsetimerule and MaxAutoRetriesNextServer combine work

### ISSUE THREAD

**Issue by liyikai** [spring-cloud/spring-cloud-netflix#3077]
I have two server A and B。
The configuration ：
<clientName>.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.WeightedResponseTimeRule  
<clientName>.ribbon.MaxAutoRetriesNextSrver=1

when the server B down,  i think will retry another server A。 but because use WeightedResponseTimeRule  that sometimes will also select the down server B。

I want to when the server down it can choose another  available server。
This issue have any solutions?

**Comment by ryanjbaxter** [comment]
I think the algorithm is working as expected.  In theory if server B has the best response time before going down it will be given preference over server A.  So in the case that B is down and the retry occurs the load balancer could select B again despite it being down and selected previously.
