### ISSUE TITLE
"HystrixMetricsBinder" auto configured under the wrong property name

### ISSUE THREAD

**Issue by pobodysnerfect** [spring-cloud/spring-cloud-netflix#3078]
Version: latest (2.0.1.BUILD-SNAPSHOT)

The HystrixMetricsBinder class is autoconfigured to expose micrometer metrics for hystrix [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixAutoConfiguration.java)

This autoconfiguration is made conditional on the following property:

`"management.metrics.hystrix.enabled"`

This property seems wrong. All other metric binders use properties like:

`"management.metrics.binders.jvm.enabled"`

The "binders" is missing from the property. [Here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/MetricsAutoConfiguration.java) is the base metrics autoconfiguration class that you can use an an example for correct property names.

@spencergibb ^^

**Comment by ryanjbaxter** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-netflix/commit/eb87e49e46322c39e6a92d9ae838e25889dc5d0d
