### ISSUE TITLE
Feign cannot pass List<String> object, return 405 error

### ISSUE THREAD

**Issue by tyrantqiao** [spring-cloud/spring-cloud-netflix#3080]
In the below API, I configure some method to proxy service's method.
![image](https://user-images.githubusercontent.com/20833792/42810149-d16dc0ac-89e9-11e8-8961-c59b07b823c3.png)
The method needs to pass a List<String> object, and when I use postman to post the request param and request body, I can get the result.
![image](https://user-images.githubusercontent.com/20833792/42810266-1abf7926-89ea-11e8-8de8-6fce5467b773.png)
But when I change to use UserInfoFeign to pass the same request, It caused an error. The other feign methods can work successfully, only this method which passes List<String> cannot work.
![image](https://user-images.githubusercontent.com/20833792/42810431-7ab3341c-89ea-11e8-89a6-10ce56bb6b96.png)

I also try to use String[] to pass, or use wrapper class, but still not work.

Below photos are my configuration.
![image](https://user-images.githubusercontent.com/20833792/42809988-718e43c8-89e9-11e8-9c87-745d168f06c0.png)
![image](https://user-images.githubusercontent.com/20833792/42810028-8c343818-89e9-11e8-971d-bb3709221110.png)

![image](https://user-images.githubusercontent.com/20833792/42810064-9eeb5a40-89e9-11e8-93e4-cf702bca46ff.png)
![image](https://user-images.githubusercontent.com/20833792/42810088-acff8b56-89e9-11e8-8ab5-ff13443ba0fe.png)

**Comment by ryanjbaxter** [comment]
Please put this all in a git repo or zip so we have a way of reproducing the problem

**Comment by tyrantqiao** [comment]
sorry for the project is too big that I can't provide the sample.

**Comment by achrafsmlali** [comment]
I'm facing the same problem any solutions?

**Comment by OlgaMaciaszek** [comment]
@tyrantqiao you can put just **the bits necessary to reproduce the issue**, not your entire project. @achrafsmlali, equally if you would like us to work on an issue, please provide 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. 

@achrafsmlali do you also have problem with `@RequestBody` or `@RequestParams`?

**Comment by achrafsmlali** [comment]
I'm using RequestParams. when I request a web service (that i created) using postman it's working perfectly but when I request it through my code it gives this error : 
`feign.FeignException: status 405 reading TdbEntryApi#findByDocumentData_IdIn(List); content:
{"timestamp":"2019-04-19T09:36:58.483+0000","status":999,"error":"None","exception":"org.springframework.web.HttpRequestMethodNotSupportedException","message":"Request method 'GET' not supported"}`
the web service is added to my code as a dependency.

**Comment by ryanjbaxter** [comment]
We need a sample
