### ISSUE TITLE
Spring Boot 2.1.0: server.servlet.path moved

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#3090]
Currently Zuul apps are broken. There's a chance it will move back and be deprecated. Tracking in Boot: https://github.com/spring-projects/spring-boot/issues/12971.

**Comment by dsyer** [comment]
From @snicoll:

> We do have `DispatcherServletPathProvider` that we could reuse to offer the same logic

**Comment by snicoll** [comment]
This problem reveals a limitation with the current logic. Spring Boot can auto-configure a single `DispatcherServlet` with a configurable path but that's certainly not the only valid setup for an application.  A user may decide to have a custom `ServletRegistrationBean` in which case the property is completely ignored. Or a user may have a more complex setup that involves more than one `DispatcherServlet`. 

Reading properties directly takes into account only the "happy path" scenario. We've introduced `DispatcherServletPathProvider` for this very reason which, by default, will return the actual path of the single `DispatcherServlet` (use case 1 & 2). That method returns a set that accounts for 3. 

I don't know if that should be dealt as part of this issue. Certainly moving to `DispatcherServletPathProvider` is going to improve the situation (as it brings awareness there might be more than one `DispatcherServlet`).

**Comment by ryanjbaxter** [comment]
So is the new property `spring.mvc.path`?

**Comment by blacelle** [comment]
@ryanjbaxter it seems now to be: spring.mvc.servlet.path

**Comment by snicoll** [comment]
@blacelle thanks for trying to help but reading the property is not the proper course of action here. There is more details [in a comment above](https://github.com/spring-cloud/spring-cloud-netflix/issues/3090#issuecomment-406552772).

**Comment by ryanjbaxter** [comment]
@dsyer can you elaborate on what was broken?  I searched the code base but dont see any references to `server.servlet.path` even in the 1.4.x branch.  Also our master branch is building fine so I dont see anything broken.

**Comment by blacelle** [comment]
@ryanjbaxter I recently open https://github.com/spring-projects/spring-boot/issues/15373, where I start by reminding the history if this parameter

**Comment by spencergibb** [comment]
I'm going to close this as we aren't experiencing any issues with this.
