### ISSUE TITLE
Issue with Feign Client interface and Java 8

### ISSUE THREAD

**Issue by Amraneze** [spring-cloud/spring-cloud-netflix#3092]
I'm trying to send a request to another service, when I'm sending outside of map() function then it's working fine (I'm overriding the header authorization so I will send in Basic instead of Bearer) and in the auth-server I'm getting Basic authorization. But once I'm calling from inside of map then I'm getting Error because the request has Bearer Authorization instead of Basic.

I'm using **Braxton.Release** as version of spring cloud.

**Comment by spencergibb** [comment]
Brixton is no longer supported. Please update to Edgware

**Comment by ryanjbaxter** [comment]
Please reopen this issue if you upgrade and still experience the problem
