### ISSUE TITLE
Swagger UI for Zuul

### ISSUE THREAD

**Issue by vijaychd** [spring-cloud/spring-cloud-netflix#3103]
Most of the management endpoints swagger specs are showing request body as below.  Even for the GET requests.  So all these are not working from swagger ui.  Endpoints works outside of Swagger UI

{
  "additionalProp1": "string",
  "additionalProp2": "string",
  "additionalProp3": "string"
}

Using  Finchley.RELEASE

**Comment by ryanjbaxter** [comment]
Please provide a complete description of the problem including a sample project that reproduces the problem.
