### ISSUE TITLE
hystrix.shareSecurityContext property in 2.0.0 version

### ISSUE THREAD

**Issue by DenisKipchakbaev** [spring-cloud/spring-cloud-netflix#3105]
Documentation says:

> You also have the option to set the _hystrix.shareSecurityContext_ property to true. Doing so auto-configures a Hystrix concurrency strategy plugin hook to transfer the SecurityContext from your main thread to the one used by the Hystrix command.

[http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.0.RELEASE/single/spring-cloud-netflix.html#netflix-hystrix-starter](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.0.RELEASE/single/spring-cloud-netflix.html#netflix-hystrix-starter)

But is it still there in 2.0.0 release?
I can't make it work ~~and can't find where this property is defined in the source code of this release~
Found it: 
[https://github.com/spring-cloud/spring-cloud-netflix/blob/2728a73959a0fa7aed9ac2727d00584e5c3bc04c/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java#L77](https://github.com/spring-cloud/spring-cloud-netflix/blob/2728a73959a0fa7aed9ac2727d00584e5c3bc04c/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java#L77)

I'm struggling with this infamous problem of HystrixCommand with isolation strategy 'thread' and Oauth2ClientContext that is not available in the request scope in the current thread:

`BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'request' is not active for the current thread`

I saw various issues here back from 2016 regarding this problem but I'm not sure if different approach should be applied in 2.0.x release.

Thanks

**Comment by ryanjbaxter** [comment]
@daniellavoie do you have any insight?

**Comment by daniellavoie** [comment]
The shareSecurityContext will work with a classic spring security SecurityContext but is not adapted to Oauth2. I'm pretty sure it could be extended to Oauth2 without much effort.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
