### ISSUE TITLE
How to set context for instance specific in turbine 

### ISSUE THREAD

**Issue by AnkushNakaskar** [spring-cloud/spring-cloud-netflix#3106]
What if i have same cluster as default cluster and all my application in same cluster.
My config looks like below:

turbine:
appConfig: content-test
aggregator:
cluster-config: default
instanceUrlSuffix:
default: /api/test/hystrix.stream
clusterNameExpression: new String("default")

Now,I have other application(e.g : test2 with context path: /api/test2 and on same cluster),with different context path,What should i do ?

Is there any way to solve this problem
P.S : I am using consul for service registry.

**Comment by spencergibb** [comment]
There is not. That is considered a separate cluster.
