### ISSUE TITLE
Issue while building using maven

### ISSUE THREAD

**Issue by chetanin** [spring-cloud/spring-cloud-netflix#3110]
Hello , I am trying to build this code using maven. I am getting following exception.

[WARNING] The POM for org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.0.1.BUILD-SNAPSHOT is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.4.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.0.1.BUILD-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced @
[WARNING] 'build.plugins.plugin.version' for org.asciidoctor:asciidoctor-maven-plugin is missing. @ org.springframework.cloud:spring-cloud-netflix-eureka-server:[unknown-version], E:\springcloud\spring-cloud-netflix-master\spring-cloud-netflix-master\spring-cloud-netflix-eureka-server\pom.xml, line 216, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.springframework.cloud:spring-cloud-netflix-docs:[unknown-version], E:\springcloud\spring-cloud-netflix-master\spring-cloud-netflix-master\docs\pom.xml, line 20, column 12
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.springframework.cloud:spring-cloud-netflix-hystrix-stream:2.0.1.BUILD-SNAPSHOT (E:\springcloud\spring-cloud-netflix-master\spring-cloud-netflix-master\spring-cloud-netflix-hystrix-stream\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.4.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.0.1.BUILD-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

We can't really help with just an error message like that.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Once we have a sample we can try and see what may be wrong (most likely with the project itself).
