### ISSUE TITLE
Uneven load distribution in containers with Ribbon and Zuul

### ISSUE THREAD

**Issue by harinathbk** [spring-cloud/spring-cloud-netflix#3114]
Hi All,

Ribbon is doing unequal distribution in available containers with below configuration. Can you please help me to fix this issue? 

springCloudVersion=Edgware.SR3
springBootVersion=1.5.10.RELEASE

ribbon properties
============

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  retryableStatusCodes: 500,502,503
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  EnableZoneAffinity: false

**Comment by spencergibb** [comment]
You'll need to provide more information. What does "unequal distribution in available containers" mean? How can we replicate the problem? What do containers have to do with anything?

**Comment by harinathbk** [comment]
Thanks for your response, Spencer.
 
I have deployed my services 4 containers with RoundRobinRule load balance method.Please find no of transactions routed each container.1 and 2 containers has more traffic and 3&4 containers has more traffic.

container2=240354
container1=240121
container3=122565
container4=122231

Regards,
Harianth.

**Comment by ryanjbaxter** [comment]
How is ribbon getting the list of servers?

**Comment by harinathbk** [comment]
Thanks for your reply, Ryan.

I'm using Zuul with Ribbon and Eureka, so Ribbon will get list of servers from Eureka, but some how Ribbon is not load balancing traffic properly. My service is running in 4 containers but more traffic sent to 2 containers. Please find below total no of transactions routed to each container and ribbon properties.

container2=240354
container1=240121
container3=122565
container4=122231

ribbon:
ConnectTimeout: 1000
ReadTimeout: 10000
MaxAutoRetries: 0
MaxAutoRetriesNextServer: 1
OkToRetryOnAllOperations: false
retryableStatusCodes: 500,502,503
NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
EnableZoneAffinity: false
Harinath.

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

When using Eureka the list of servers is periodically updated.  In fact it is not a list at all it is a set, therefore the order is not guaranteed.  For that reason, even when using a round robin load balancing algorithm servers will not have equal distribution.

**Comment by spencergibb** [comment]
closing as answered
