### ISSUE TITLE
Adding Basic and Oauth2 in Zuul

### ISSUE THREAD

**Issue by Amraneze** [spring-cloud/spring-cloud-netflix#3116]
Is there a way to use Basic authentication for some urls and oauth2 for others ?

Thank you.

**Comment by spencergibb** [comment]
Since it's a normal spring boot application, you can do anything that normal spring security can do, so yes.

**Comment by xiaoyao9184** [comment]
@Amraneze i created a module for this, see [zuul-basic-authentication](https://github.com/xiaoyao9184/spring-cloud-expansion/tree/master/zuul-basic-authentication)

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
