### ISSUE TITLE
Zuul Routing to Microservice in Liberty Container - SSL Issue

### ISSUE THREAD

**Issue by ravisrin** [spring-cloud/spring-cloud-netflix#3117]
Hello, 

We have a setup where Zuul is running on an JVM and Eureka is running on an JVM and a Simple Microservice is running on an JVM. All the 3 JVM are in Liberty Container. The service is able to register and can see it in Eureka. All these 3 are setup to run using https/ssl - tls v2.0 protocol. 

The issue that we have is when a request is sent from browser to Zuul URL, which in turn supposed to forward to Microservice, it gives the SSL Handshake exception. On the other hand if you access the Microservice directly no issues and able to access it and get the response.

Any thoughts on what might be causing the SSL issue?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
