### ISSUE TITLE
Allow to disable response decompression

### ISSUE THREAD

**Issue by tjuchniewicz** [spring-cloud/spring-cloud-netflix#3122]
When using Apache Http Client, response received from backed service is always decompressed. This is feature of Apache Http Client. Content is decompressed and `Content-Encoding` header is removed from response: [ResponseContentEncoding](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/client/protocol/ResponseContentEncoding.java#L125). Zuul processes decompressed content.

This make no sense for Zuul in all cases because we forward response to Zuul client and there is no reason to decompress and compress again if Zuul client requested compression. Maybe one wants to do some content based filtering and decompressed content is expected.

After Apache Http Client removes  `Content-Encoding` header all Zuul calls like:  [context.getResponseGZipped()](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java#L138) will always return `false`.

My proposal is to disable automatic decompression in Apache in: [RetryableRibbonLoadBalancingHttpClient ](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-ribbon/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RetryableRibbonLoadBalancingHttpClient.java#L78):
using: 
```java
builder.setContentCompressionEnabled(false);
```
or use property to control this behavior.

**Comment by tjuchniewicz** [comment]
@brenuart I see you may be interested in gzip issues.

**Comment by ryanjbaxter** [comment]
I think this makes sense, I think having a property to control this makes sense.

**Comment by tjuchniewicz** [comment]
I will prepare PR for this.

**Comment by tmack8001** [comment]
This is similar to what I have done just wrapped up nicely in a property instead of a custom.http connection manager and related http clients.
