### ISSUE TITLE
Zuul spring retry on specfic exception

### ISSUE THREAD

**Issue by shubhanshushukla** [spring-cloud/spring-cloud-netflix#3124]
I want configure zuul so that I can retry request on specific exception. 

Just like option in charon-spring-boot-starter library.

`charon.retrying.retry-on.exceptions: <comma-separated list fo exceptions>`

 Enhancement

I want to retry only on specific exception which I will mention of application.yaml in zuul settings.

**Comment by ryanjbaxter** [comment]
You can only retry on specific status codes, not exceptions http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_configuration
