### ISSUE TITLE
RibbonLoadBalancerFeignClient not delegating to RibbonLoadBalancingHttpClient when using Apache HttpClient powered Ribbon

### ISSUE THREAD

**Issue by tmack8001** [spring-cloud/spring-cloud-netflix#3129]
We have Ribbon configured to use HttpClient for all http request processing and execution via the HttpClientRibbonConfiguration component (presence of HttpClient.java in classpath). We also are using FeignClients to be a easy and declarative way to create client interfaces for our downstream dependencies. We noticed in testing that the default behavior of Feign via `spring-cloud-starter-openfeign` is to create a single Client.Default FeignClient and when Ribbon is found on the classpath at the time of processing the http request grabs some client information from the "hostname" of the request to then use the `SpringClientFactory` to pull out client specific configuration and LoadBalancer information (to select a server to send the request to). However what wasn't obvious to start with was that this FeignClient wasn't delegating to the ribbon client that was also created within the ApplicationContext (in the ribbon child context).

According to the documentation there are 2 clients that can be configured (or injected) for use: OkHttp and ApacheHttpClient (a Netflix Feign wrapper around Apache's HttpClient bounded in feign-httpclient package). At this point we explored options around how to use either of these clients and both seem to have hooks only at AutoConfiguration time (application startup) to create clients for Feign and more specifically only 1 Feign `Client` was ever created and added into the ApplicationContext and shared across all `FeignContext` objects.

We have custom HttpClients and related HttpConnectionManagers that have additional instrumentation (logging and metrics for our needs and infrastructure). I looked in to how to configure our FeignClients to be powered by these same http clients (i.e. `ribbonLoadBalancingHttpClient.getDelegate()`). The problem however is the use of the delegate within the created FeignClient itself was always referring to the ones created by the imports in `FeignRibbonClientAutoConfiguration` which are explicitly created for the FeignClient and not ones that are shared and/or created by Ribbon.

Here is a slice of the configuration used to get this far:

```
feign.httpclient.enabled: false // this is disabled as we have ApacheHttpClient on our classpath but don't want FeignRibbonClientAutoConfiguration to select HttpClientFeignLoadBalancedConfiguration as the configuration component
 
ribbon:
  eager-load:
    enabled: true
    clients: foo-service, bar-service
 
foo-service:
  ribbon:
    listOfServers: http://foo-service:8080/
    ConnectTimeout: 100
    ReadTimeout: 700
 
bar-service:
  ribbon:
    listOfServers: http://bar-service:8080/
    ConnectTimeout: 500
    ReadTimeout: 5000
```

One gigantic hack I tested in my local environment (really dirty code, and better to be done in a fork if I truly want this behavior) to verify what I think should be done is the following:

```
@Configuration
@AutoConfigureBefore(FeignAutoConfiguration.class)
@EnableConfigurationProperties({FeignHttpClientProperties.class})
@Import({RibbonHttpClientFeignLoadBalancedConfiguration.class})
public class ExplicitFeignRibbonClientAutoConfiguration extends FeignRibbonClientAutoConfiguration {
}
```

```
@Component
@Order(Ordered.HIGHEST_PRECEDENCE) // needed as this needs to be the highest order Configuration defining a Feign Client
public class RibbonHttpClientFeignLoadBalancedConfiguration {
 
  @Bean
  @Primary // mark to override the potentially pre-existing one created in the package private HttpClientFeignLoadBalancedConfiguration class
  public Client feignClient(CachingSpringLoadBalancerFactory cachingFactory,
    SpringClientFactory clientFactory) {
    return new ExplicitRibbonLoadBalancerFeignClient(new Client.Default(null, null), cachingFactory, clientFactory);
  }
}
```

Yes, yes this is really bad code and not recommended to take the performance hit in doing any reflection at runtime.

```
public class ExplicitRibbonLoadBalancerFeignClient extends LoadBalancerFeignClient {
    private static final Logger LOG = LoggerFactory.getLogger(ExplicitRibbonLoadBalancerFeignClient.class);
 
    public ExplicitRibbonLoadBalancerFeignClient(Client delegate, CachingSpringLoadBalancerFactory lbClientFactory, SpringClientFactory clientFactory) {
        super(delegate, lbClientFactory, clientFactory);
    }
 
    @Override
    public Response execute(Request request, Request.Options options) throws IOException {
        URI asUri = URI.create(request.url());
        String clientName = asUri.getHost();
 
        reflectivelyOverrideFeignClient(clientName);
 
        return super.execute(request, options);
    }
 
    /**
     * In a real solution to spring-cloud-netflix a change to the following line https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/ribbon/LoadBalancerFeignClient.java#L59-L60
     * would look like the following (iff the LoadBalancerFeignClient is truly being powered by a RibbonClient in the clientFactory):
     *
     * ```
     * RibbonLoadBalancingHttpClient ribbonHttpClient = ((SpringClientFactory) clientFactory.get(this)).getClient(clientName, RibbonLoadBalancingHttpClient.class)
     * new FeignLoadBalancer.RibbonRequest(ribbonHttpClient.getDelegate(), request, uriWithoutHost);
     * ```
     *
     * @param clientName name of the feign/ribbon client
     */
    private void reflectivelyOverrideFeignClient(String clientName) {
        try {
            Field delegate = getClass().getSuperclass().getDeclaredField("delegate");
            delegate.setAccessible(true);
 
            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(delegate, delegate.getModifiers() & ~Modifier.FINAL);
 
            Field clientFactory = getClass().getSuperclass().getDeclaredField("clientFactory");
            clientFactory.setAccessible(true);
 
            RibbonLoadBalancingHttpClient ribbonLoadBalancingHttpClient = ((SpringClientFactory) clientFactory.get(this)).getClient(clientName, RibbonLoadBalancingHttpClient.class);
 
            // override the Feign Client delegate to be the delegate of the ribbon client
            delegate.set(this, new ApacheHttpClient(ribbonLoadBalancingHttpClient.getDelegate()));
        } catch (NoSuchFieldException | IllegalAccessException e) {
            LOG.error("failed to reflectively override feign.client for %s", clientName, e);
        }
    }
}
```

Example Project Repo: https://github.com/tmack8001/feign-ribbon-delegate-inconsistency

**Comment by spencergibb** [comment]
AFAIK `RibbonLoadBalancingHttpClient` is used only in zuul.

**Comment by spencergibb** [comment]
Why do you want the feign clients to use `RibbonLoadBalancingHttpClient`?

**Comment by tmack8001** [comment]
Ultimately we want the same HTTP Client which is powering our ribbon clients to also power our feign clients. Aka a single way to configure any http client and a single library configuration for any network requests to http based services.

When we configured feign with ribbon we assumed this would happen, but instead due to the time in which clients get created (single feign client at start up, several ribbon clients at run time / after application initialization multicast event).

**Comment by spencergibb** [comment]
I'm still a bit confused. The same Apache http client it okhttp client can be used by zuul or feign.

**Comment by tmack8001** [comment]
When `ApacheHttpClient` (the feign wrapper for Apache's `HttpClient`) is included on your classpath via the package `io.github.openfeign.feign-httpclient` `HttpClientFeignLoadBalancedConfiguration` (imported by `FeignRibbonClientAutoConfiguration`).

This class in 1.4.x release train at least has bean definitions for HttpClient and related ConnectionManager which are created during AutoConfiguration and not individually per ribbon service via the creation of a "child applicaiton context" through the `SpringClientFactory`.

**Comment by spencergibb** [comment]
None of this would change on the 1.4.x line.

**Comment by ryanjbaxter** [comment]
Is Feign using Ribbon?

**Comment by ryanjbaxter** [comment]
I still dont understand why `HttpClientFeignLoadBalancedConfiguration` doesnt do what you need.  It will use custom `ApacheHttpClientConnectionManagerFactory` and `ApacheHttpClientFactory` power the feign clients.

**Comment by tmack8001** [comment]
It defines the HttpClient and HttpClientConnectionManager seperately and not based on the ribbon properties set in the application.yml (or maybe I did something wrong?)


In our use case we are attempting to inject our own HttpClient and related connect manager to have specific metrics and logging for our http clients and all http requests' commonly. These injected clients aren't being picked up for fiegn, but are for ribbon when routing via zuul.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
