### ISSUE TITLE
How do I change user/password for Feign at runtime?

### ISSUE THREAD

**Issue by RayBausch** [spring-cloud/spring-cloud-netflix#3139]
Hi all,

I have the following problem with Feign / Spring Boot.

First I had built an page where the users are logged in. The logindata will send from Angular to my SpringBoot Tomcat.
With that logindata, I logged in a WebService and that WebService generate the needed data.

At the moment my servercode includes my credentials hardcodet. With this credentials I ask the Webservice and he answered me.
Thats ok. But my feign-client established the authorisation during he startet. And I cant set new credential during runtime.
So I always use the harcodet credentials. 

```
@Data
@Configuration
public class MyFeignClient {

  public String user = "name";
  public String password = "passwort";

  @Bean({"mybean"})
  public BasicAuthRequestInterceptor basicAuthRequestInterceptor() {
    return new BasicAuthRequestInterceptor( user, password );
  }
}
```
```
@Component
@FeignClient(name = "service", configuration = MyFeignClient.class, url = "http://middleware:8080/web/rest/")
public interface ArticleDataService {

  @GetMapping(path = "")
  List<ArticleData> getAllArticleData();
}
```

**Comment by ryanjbaxter** [comment]
So you want to change the credentials while the app is running?

**Comment by RayBausch** [comment]
Yes, I want it.

**Comment by RayBausch** [comment]
Hallo eacd,

thank you for answering. That's an intresting solution.
But unfortunatly the middleware where I asked didn't use keycloak.

Thanks
Ray

**Comment by ryanjbaxter** [comment]
Why doesnt using the configuration server and refresh work for you?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by rost5000** [comment]
Do you have any update on this issue?
