### ISSUE TITLE
The application group has no logical isolation when using eureka key[eureka.instance.app-group-name]

### ISSUE THREAD

**Issue by shituanjie** [spring-cloud/spring-cloud-netflix#3141]
In the case of using eureka, key[eureka.instance.app-group-name] is configured, the application group has no logical isolation.Details are as follows:
version: 
    Spring Boot : 2.0.4.RELEASE
    Spring Cloud : Finchley.RELEASE
I have three application, online, eureka, user ( user has two instances). 
Setting : 
`eureka` : 
~~~
server:
  port: 8761

spring:
  application:
    name: eureka-grid

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
~~~
`online` : 
~~~
server:
  port: 8764

spring:
  application:
    name: online

eureka:
  instance:
    app-group-name: bb
    namespace: group2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
~~~
`user` instance 1 (Referred to user1): 
~~~
server:
  port: 8765

spring:
  application:
    name: user

eureka:
  instance:
    app-group-name: bb
    namespace: group2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-u-r-l-context:
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true
~~~
`user` instance 2 (Referred to user2): 
~~~
server:
  port: 8763

spring:
  application:
    name: user

eureka:
  instance:
    app-group-name: aa
    namespace: group1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-u-r-l-context:
ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true
~~~
when I request url `http://localhost:8764/test1` (test1 is one rest api in online) several times, both user1 and user2 may receive the request. Total 4,maybe user1 receive one or two(user2 receive others).
According to the above configuration, why user2 can receive the request?
Or, if I have something wrong with the configuration, please indicate it.

**Comment by ryanjbaxter** [comment]
Its not the group name that is the issue, its the fact that `spring.application.name` for user1 and user2 are the same.  Therefore according the Eureka they are the same service.  Requests to a service with the name `user` will then be loadbalanced across all `user` instances.

**Comment by shituanjie** [comment]
Based on the scenario described above, is there any way to achieve logical separation? That is to say, whether Eureka also achieves logical separation, just like zookeeper's group.In the case of using the same eureka cluster, we need the function of business application logic separation. Is there any way?

**Comment by ryanjbaxter** [comment]
I don’t understand what you are trying to achieve.  If you want the user1 and user2 to be able to be addressed separately you need to give them different names

**Comment by shituanjie** [comment]
When `online` accesses`user`, I hope that some conditions can be used to filter out some instances of`user`. In consul, I can reach the goal with`tags`. For example, `user1` has tags `forOuter`, `user2` has tags `forInner`. When I configure the value of `spring.cloud.consul.discovery.default-query-tag` for online as `forOuter`,`online` will not be able to access `user2`.
Does eureka have a similar strategy?

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by dex268** [comment]
I had the same question, and I am confused about the app-group-name param is for what.  Is it just a tag to identify groups which does not contribute to any load balance logic in ribbon?
I intend to implement custom Ribbon com.netflix.loadbalancer.ServerListFilter which use such param to  achieve logical separation with the same application name.
