### ISSUE TITLE
Set Hystrix configuration properties by expression evaluation

### ISSUE THREAD

**Issue by LucasAndersson** [spring-cloud/spring-cloud-netflix#3143]
Hi

It would be great if you could set Hystrix configuration properties in externalized configuration (application.properties) using expression evaluation.

For example, I might want to set the hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds to the sum of my circuit breaker wrapped http clients different timeout properties (e.g. connection and socket timeouts) plus some breathing room.

I tried setting it like this in my application.properties file without success:
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=#{${httpClient.connectTimeout} + ${httpClient.socketTimeout} + 1000}

Best regards,
Lucas

**Comment by llgeill** [comment]
I also encounter this problem and I don't know how to solve it.

**Comment by spencergibb** [comment]
I'm afraid that this is unlikely to happen because Hystrix is a third party dependency

**Comment by llgeill** [comment]
Why do I see other people's tutorials can configure relevant properties on application.yml? Is it because of the reason of the version?

**Comment by ryanjbaxter** [comment]
Not sure what tutorials you are referring to, you also didnt provide the version you are using.  Regardless that is unrelated to this issue.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
