### ISSUE TITLE
Zuul gateway does not load the JS/CSS 

### ISSUE THREAD

**Issue by aswinde03032008** [spring-cloud/spring-cloud-netflix#3146]
I have created three micro-services and I am trying to route the student service using zuul api gatway:

1. my-gateway -> zuul api gateway ( it is running 8080)
2. student-service -> spring-boot-web (it is running 8090)
3. Eureka discovery server 

The my-gateway & student-service are registered in eureka discovery server.
----------------------------------------------------------------------------------------------
Configuration of my-gateway micro-service:
zuul:
routes:
student-service:
path: /students/**
serviceId: student-service
strip-prefix: false
serrver:
context-path:/mygateway
--------------------------------------------------------------------------------------------
I am hitting the url in browser 
http://localhost:8080/mygateway/students

we have controller in student-service web  like below:

@RestController
class HomeController{
  @RequestMapping("/students")
   public String getHomePage(){
       return "home"
   } 
  // home.jsp -> includes few JS/CSS files. 
}

home.jsp
<html>
<head>
<script src="ext/js/main-debug.all.js"></script> 
<script src="js/main-app.js"></script>
</head>
</html>

Issue:
http://localhost:8080/mygateway/students --> it successfully routes to "public String getHomePage()" and "home.jsp" is loaded in browser but JS/CSS files are not loaded

Observation:
To load the JS/CSS, following requests have been made:
http://localhost:8080/mygateway/js/main-app.js 

Instead of

http://localhost:8080/mygateway/students/js/main-app.js

Please help me how to resolve it, I believe this is very common requirement, we should retain the "students" in every requests after request is routed to down-stream micro-services by zuul. 

Note - I can not add "students" in each import lines like <script src="<c:url value="students/ext/ext-all-debug.js" />"></script> since I have it many pages.

**Comment by spencergibb** [comment]
Closing in favor of #3145

**Comment by aswinde03032008** [comment]
Hey, it was not resolved.
 I believe this is very common requirement, we should retain the "students" in every requests after request is routed to down-stream micro-services by zuul.

Please let me know what is wrong here

**Comment by aswinde03032008** [comment]
I am bit curious this is most common requirement it should work.

Note - I tried with Pre ZuulFilter to set the requestURI  in RequestContext but it did not work.

I noticed the request.getContext() -> is always /mygateway

**Comment by aswinde03032008** [comment]
I resolved it. 
Just we have to change 
From
http://localhost:8080/mygateway/students 
To
http://localhost:8080/mygateway/students/

All JS and CSS are loading correctly
