### ISSUE TITLE
SimpleRouteLocator prefix problem 

### ISSUE THREAD

**Issue by xiaoyao9184** [spring-cloud/spring-cloud-netflix#3147]
The `prefix` of the Route always contains the global prefix when not empty, not related to 'StripPrefix'.
But the `path` of the Route(in the code is `targetPath`) controlled by StripPrefix.

https://github.com/spring-cloud/spring-cloud-netflix/blob/c8c4dbd0503b66353e82dc72ca2cdc74b7476634/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/SimpleRouteLocator.java#L140-L155

Route use `path ` and `prefix` create `fullPath`

https://github.com/spring-cloud/spring-cloud-netflix/blob/c8c4dbd0503b66353e82dc72ca2cdc74b7476634/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/Route.java#L27-L42

This will be a problem.

If I am correct, i think LocationRewriteFilter have some prefix problem too.

https://github.com/spring-cloud/spring-cloud-netflix/blob/c8c4dbd0503b66353e82dc72ca2cdc74b7476634/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/LocationRewriteFilter.java#L115-L135

`route` from RouteLocator, so the `prefix` maybe contains any prefix of global prefix or route prefix.

If i use global prefix and route prefix, and enable 'StripPrefix' both,
`downstreamHasRoutePrefix(route)` is `false` and the `path` will be `global prefix` + `global prefix` + `route prefix`.

**Comment by ryanjbaxter** [comment]
Can you provide a sample that will demonstrate the problem?

**Comment by xiaoyao9184** [comment]
@ryanjbaxter sample in here https://github.com/xiaoyao9184/spring-cloud-expansion/tree/master/samples/zuul-redirect/zuul-redirect-issue

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
