### ISSUE TITLE
First feign request in Configuration file locks with Hystrix, Lazy bean + SEMAPHORE helps

### ISSUE THREAD

**Issue by alefr** [spring-cloud/spring-cloud-netflix#3148]
Hi,

We have a case where we need to make a rest request in a Spring Configuration. We do this with a Feign client with hystrix enabled. 
When performing the request it times out but after it times out the actual call is made.
If we raise the hystrix timeout all it does is wait longer and acts the same after that.

Error:
```
Failed to instantiate [com.example.error.MyComponent]: Factory method 'myComponent' threw exception; nested exception is com.netflix.hystrix.exception.HystrixRuntimeException: MyClient#getValue(String) timed-out and no fallback available.
```

As it's part of the setup of the service it fails to start but if we set the bean requiring the call as lazy initialized the initial rest request fail just as earlier but subsequent rest calls work and the bean is properly initialized.

If we use lazy initialization and semaphore (requires both) for the command everything works as intended: `hystrix.command.MyClient#getValue(String).execution.isolation.strategy=SEMAPHORE`

With this strategy we can get it to work but it's not prefered for a number of reasons.

We use the _Spring Cloud Dalston_ Release but I've been able to reproduce a really simple sample in Finchley as well which I will attach.

In the sample the Feign Client looks like:
```
@FeignClient(name = "myrespondingservice")
public interface MyClient {

    @RequestMapping(value = "/value/{value}", produces = "text/plain")
    String getValue(@PathVariable("value") String value);
}
```
And the configuration:
```
@Configuration
public class MyConfiguration {

    @Bean
    //@Lazy
    public MyComponent myComponent(MyClient myClient) {
        String value = myClient.getValue("thisismyvalue");
        return new MyComponent(value);
    }
}
```

Is this expected behaviour? I've been up and down the documentation but haven't been able to find anything regarding this.

I found these issues #384, #768 in my search for an answer. They might be related but #384 resulted in a PR not being made and #768 is closed for other reasons.

Thank you
[initializationlockdemo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2297187/initializationlockdemo.zip)

**Comment by spencergibb** [comment]
Using a feign client (or any http request) during bean initialization is probably not a good idea. This is all about timeouts here. Not sure there is anything we can do here.

**Comment by alefr** [comment]
You are probably correct about requests in initialization.
This is a rather special case where we need to connect applications running on a different (legacy) platform. We have existing functionality to find out where the applications are running.
It's possible to solve it through other means but that requires infrastructure change, which I'm afraid isn't possible right now.

Just wanted to see if there's anything we overlooked but will start looking into other ways of doing it.
Thank you for your help
