### ISSUE TITLE
Zuul dropping the added headers for few requests while making asynchronous requests from Angular

### ISSUE THREAD

**Issue by Arjun09** [spring-cloud/spring-cloud-netflix#3149]
I have Zuul gateway as proxy between Angular app and our micro services. I have created a zuul filter to add few headers for every request.

```
@Component
public class RoutesAuthenticationFilter extends ZuulFilter {
	@Override
	public String filterType() {
		return "route";
	}
	@Override
	public int filterOrder() {
		return 0;
	}
	@Override
	public boolean shouldFilter() {
		return true;
	}
	@Override
	public Object run() {
         ctx = RequestContext.getCurrentContext();				
		ctx.addZuulRequestHeader("principal", principal);
		ctx.addZuulRequestHeader("customerheader", String.valueOf("testheader"));

return null;
}
```
This has been working for every request I made from postman.

I started seeing it is not adding/dropping these headers for the requests made to services through gateway from Angular app.

When I look at the log for headers in the request after adding them I see request contains the added headers are present for all requests
`Headers from the requet after adding them all; { principal=john123, x-forwarded-host=localhost:8080, x-forwarded-proto=http, x-forwarded-prefix=/application-management, x-forwarded-port=8080, customerheader=testheader, x-forwarded-for=0:0:0:0:0:0:0:1}`

But when I print them in the service, they are missing for few requests
```
2018-08-17 11:23:47.709  INFO [application-management,56a2962a54770966,56a2962a54770966,false] 10952 --- [nio-9090-exec-9] c.f.c.v.d.c.i.RequestInterceptor         : Entered request interceptor
customer header from request: testheader
principal from req: john123
2018-08-17 11:23:47.713  INFO [application-management,058aad714328a61f,058aad714328a61f,false] 10952 --- [nio-9090-exec-2] c.f.c.v.d.c.i.RequestInterceptor         : Entered request interceptor
customer header from request: null
principal from req: null
```
In the above output, headers are missing for one request and present for one request.

These two requests are made asynchronously from Angular app.

I do not see this problem if I make these two calls one in another, means if I make one call and wait for the response and make the next one then it is not missing headers

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by Arjun09** [comment]
Pls find the sample projects for Angular UI, Zuul gateway and Backend service.

[https://github.com/arjunpunugupati/testzuului](url)
[zuul-gateway.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2354019/zuul-gateway.zip)
[compute-client.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2354020/compute-client.zip)

**Steps to reproduce the issue:**

- Run 'compute-client' backend micro service
- Run 'zuulgateway' gateway servuice
- Clone and run 'testzuului' angular app
- Angular app by default load compute-client component which sends two asynchronous requests to gateway which forward that request to backend service.
- While routing these requests, zuul gateway service has a filter that adds two headers to the current request in the context.
- In most of the cases, one of these request is missing the added headers when logged in service. If you do not see missing headers, refresh the angular page few times to resend the requests. Hope it will reproduce the issue.

@spencergibb let me know if you need more information

**Comment by spencergibb** [comment]
Please supply the web component built and runnable. I'm not going to try and replicate whatever you have to build and run it.

**Comment by Arjun09** [comment]
@spencergibb The problem occurs when requests made from angular app, which the gateway service routes to backend service. As these are three different apps I have provided all three with required setup. Pls run three apps and you can see the issue from the Angular logs/network tab or could you clarify what you meant by runnable web component? Thanks for your support

**Comment by Arjun09** [comment]
@spencergibb here is the running UI app [http://zuul-test-ui.apps.cl-east-dev02.cf.ford.com/](url)
I am sending two service calls to zuul gateway and one call is always failing because the added headers in zuul filters are missing by the time request reaches end service(not sure where those headers are dropped).
I have attached gateway project in this thread, please look into it if needed.

**Comment by Arjun09** [comment]
@spencergibb Could you look into this and add your feedback/comments

**Comment by spencergibb** [comment]
Why is your `AuthenticationFilter` is a `route` filter, should it be `pre`?

Can you reproduce the error without angular? I can't get it to run on my linux box. If you can't, I'm not sure what else I can do.

**Comment by Arjun09** [comment]
@spencergibb  I was able to reproduce the issue even with 'pre' filter. I also reproduced the issue without Angular by using a stress test extension from google chrome store. The extension is available in google chrome store and called 'RESTful stress'.

Below is the image that shows I am directly hitting two endpoints in through zuul-gateway on endpoints
http://zuul-gateway-dev.apps.cl-east-dev02.cf.ford.com/compute-client/calculate/test1
http://zuul-gateway-dev.apps.cl-east-dev02.cf.ford.com/compute-client/calculate/test2
![stresstest](https://user-images.githubusercontent.com/23248470/45696018-9fe1cd80-bb30-11e8-8730-c91d26c702ce.PNG)

And below is the logs from PCF showing headers for one request are missing
![issuewithheaders](https://user-images.githubusercontent.com/23248470/45696049-b556f780-bb30-11e8-9fa7-a12cdb70d33f.PNG)
Let me know if this helps

**Comment by stiyyagura** [comment]
@Arjun09 are you routing the request to the back-end service hosted in zuul itself?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
