### ISSUE TITLE
DataSourceAutoConfiguration  with eureka-server 

### ISSUE THREAD

**Issue by countree** [spring-cloud/spring-cloud-netflix#3151]
- spring-boot 2.0.4.RELEASE
- spring-cloud Finchley.SR1

DataSourceAutoConfiguration is configured too early before registering with eureka-server

**Comment by snicoll** [comment]
This was raised on the Spring Boot project as well https://github.com/spring-projects/spring-boot/issues/14141#issuecomment-414224612

@countree, as indicated over there, you need to provide more details if you want someone from the team to investigate. A sample would be ideal.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
