### ISSUE TITLE
Unexpected EOF read on the socket ZuulException occurred when Fowarding post request  with body 

### ISSUE THREAD

**Issue by wanglilong007** [spring-cloud/spring-cloud-netflix#3154]
Spring Cloud version: Edgware.SR4
Spring Boot version: 1.5.3.RELEASE

I have two service, one including Zuul use as a gateway, and another one as a micro service, all of them run as Spring Boot application, I found that Read timed out ZuulException alway occurred when Fowarding post request  with body, But other request is normal such as GET.

```
com.netflix.zuul.exception.ZuulException: Read timed out
	at org.springframework.cloud.netflix.zuul.util.ZuulRuntimeException.<init>(ZuulRuntimeException.java:33) ~[spring-cloud-netflix-core-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.run(SimpleHostRoutingFilter.java:212) ~[spring-cloud-netflix-core-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) ~[zuul-core-1.3.1.jar:1.3.1]
```

in addition, warning message appears at micro service as follow.

`.w.s.m.s.DefaultHandlerExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Unexpected EOF read on the socket; nested exception is java.io.EOFException: Unexpected EOF read on the socket`

```
zuul:
  sensitiveHeaders:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 5000
  routes:
    service:
      path: /**
      stripPrefix: false
      url: http://localhost:8081/
```

**Comment by spencergibb** [comment]
Zuul is receiving an end of file from your downstream service or a problem with the network. Please reopen if you can demonstrate otherwise.

**Comment by wanglilong007** [comment]
@spencergibb I found that the exception relates to `zuul.trace-request-body` configuration of zuul, if I set it  to false, the read timed out ZuulException is gone，but I do not add it，the exception appears absolutely.
