### ISSUE TITLE
Migration from Zuul1 to Gateway2

### ISSUE THREAD

**Issue by lwq030409** [spring-cloud/spring-cloud-netflix#3155]
Hi,
We have created a gateway on the base of cloud-zuul 1, but we found it doesn't support websocket, so we plan to upgrade cloud framework to latest.

We created a new gateway on the base of cloud gateway, but we found we need to rewrite this project. many thing are changed.

In the zuul version, we use ribbon com.netflix.loadbalancer.ZoneAvoidanceRule to route request according to request zone.

How to do this in new cloud gateway? Seems these isn't a existing config we can use.
What advice on this issue?

**Comment by ryanjbaxter** [comment]
Please open an issue in the Spring Cloud Gateway project.
