### ISSUE TITLE
Can't override Hystrix properties using @TestPropertySource with newer versions of Maven

### ISSUE THREAD

**Issue by LucasAndersson** [spring-cloud/spring-cloud-netflix#3158]
Hi

It doesn't seem possible to override configuration properties using the @TestPropertySource annotation with newer versions of maven. I have verified this by setting logging.level.com.netflix.hystrix to DEBUG and then trying to override hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds using @TestPropertySource. It works using the Maven 3 version that comes bundled with the latest version of IntelliJ IDEA (Maven version 3.3.9). It doesn't work using Maven version 3.5.3 or 3.5.4, the property seems to be set to the default value of 5000. That's all the different Maven versions I've tried. I've also tried to override hystrix.command.default.circuitBreaker.requestVolumeThreshold which also seems to be set to the default value using newer versions of maven.

Best regards,
Lucas

**Comment by spencergibb** [comment]
What does maven have to do with this? We require maven 3.5.x.

**Comment by LucasAndersson** [comment]
@spencergibb 
I just happened to notice that it works as expected when building with a older version of Maven. As to why this is, I don't know.

**Comment by spencergibb** [comment]
Even if there is a problem, `@TestPropertySource` is outside of spring cloud, there's nothing for us to do.
