### ISSUE TITLE
Is there any way to session replication between two zuul gate way api?

### ISSUE THREAD

**Issue by aswinde03032008** [spring-cloud/spring-cloud-netflix#3160]
Hi Team,

Our zuul-gateway application is running on two servers:
Like:
http://server1.8090/gateway/uiapp --> it will route to uiapp  which is running on server1
http://server2.8090/gateway/uiapp  --> it will route to uiapp  which is running on server2

Our Load balancing URL is : 
https://xyz.com/gateway/uiapp -> it routes the requests to below two gateway-urls, {sticky sessions is not implemented}
http://server1.8090/gateway/uiapp 
http://server2.8090/gateway/uiapp

So I am getting issue like:
Lets say:
While I am hitting https://xyz.com/gateway/uiapp url,  apache load-balancer routes to http://server1.8090/gateway/uiapp -> now server1 is doing the authentication and forward the request to ui-app of server1

Here uiapp returns a jsp page which includes several JS/CSS /Images files, so browser is making subsequent requests to download the JS/CSS/Images 
Like:
https://xyz.com/gateway/uiapp/js/app.js;jsessionid=37583210B45CA0C5824D157BE92334FB

Few subsequent requests (like: https://xyz.com/gateway/uiapp/js/app.js;jsessionid=37583210B45CA0C5824D157BE92334FB ) are routed to http://server2.8090/gateway/uiapp,
server2 is does have neither session or the access-token, so server2 is trying to re-authenticate.

Is there any to  append access-token which I have in server1 with jsession id? So server2 can identify it is is already authenticated.

**Comment by spencergibb** [comment]
I think this is something for https://spring.io/projects/spring-session and distributed sessions. @gregturn any comment?

**Comment by gregturn** [comment]
@aswinde03032008 If you use Spring Session (as mentioned above) and configure for HTTP headers (instead of cookies), your Gateway can transmit a SESSION header between microservices.
