### ISSUE TITLE
Not able to get proper URL while using Feign Interceptor.

### ISSUE THREAD

**Issue by abhishekhbd** [spring-cloud/spring-cloud-netflix#3162]
I want to get Feign URL, Host and schema. So I am using a Feign interceptor. But I am unable to get proper URL. URL does not have schema. instead of getting http://<SERVICE_NAME>/a1/a2.com I am getting /a1/a2.

Please suggest, what is the best way to get URL, Host and schema and response time?

**Comment by spencergibb** [comment]
Can you provide more information? Versions? Some code how you are configuring your client, etc...?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
