### ISSUE TITLE
Unable to start up a turbine server

### ISSUE THREAD

**Issue by magelon** [spring-cloud/spring-cloud-netflix#3163]
`
Error happed here:
`

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-08-27 14:54:32.908 ERROR 1298 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'turbineLifecycle'; nested exception is java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:184) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]

`
code:
`
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.hystrix.dashboard.EnableHystrixDashboard;
import org.springframework.cloud.netflix.ribbon.RibbonClient;
import org.springframework.cloud.netflix.turbine.EnableTurbine;
import org.springframework.cloud.openfeign.EnableFeignClients;
@SpringBootApplication
@EnableEurekaClient
@EnableCircuitBreaker
@EnableHystrixDashboard
@EnableFeignClients
@EnableTurbine
@RibbonClient(name="microservice-provider-user")
public class MicroserviceCusomerFeignApplication {	
	public static void main(String[] args) {
		SpringApplication.run(MicroserviceCusomerFeignApplication.class, args);
	}
}

`
application.yml
`
server:
  port: 5902  
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
spring:
  application:
    name: turbine       
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie
  clusterNameExpression: "'default'"      
  combine-host-port: false

`
pom.xml
`
<parent>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-parent</artifactId>
    		<version>2.0.1.RELEASE</version>
	</parent>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Finchley.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		
		<dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    		</dependency>

			<dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-openfeign</artifactId>
    		</dependency>
    		
    		 <dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
   			 </dependency>

			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-hystrix</artifactId> 
			</dependency>

			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-hystrix-dashboard</artifactId> 
			</dependency>
			
			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-turbine</artifactId>
			</dependency>
			
			<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-actuator</artifactId>
			</dependency>
			
			
    		
</dependencies>

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Jackson is not on the class path or the download has been corrupted.

**Comment by magelon** [comment]
when I add @EnableTurbine to main class it failed 
when I remove @EnableTurbine it can start up.

**Comment by spencergibb** [comment]
Show your pom.xml or build.gradle.

**Comment by magelon** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	
	<artifactId>cusomer-feign-ribbon-hystrix-turbine</artifactId>
	
	<packaging>jar</packaging>

	<name>cusomer-feign-ribbon-hystrix-turbine</name>
	<description>Demo project for Spring Boot</description>

	<parent>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-parent</artifactId>
    		<version>2.0.1.RELEASE</version>
	</parent>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Finchley.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		
		<dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
    		</dependency>

			<dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-openfeign</artifactId>
    		</dependency>
    		
    		 <dependency>
        		<groupId>org.springframework.cloud</groupId>
        		<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
   			 </dependency>

			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-hystrix</artifactId> 
			</dependency>

			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-hystrix-dashboard</artifactId> 
			</dependency>
			
			<dependency>
    			<groupId>org.springframework.cloud</groupId>
    			<artifactId>spring-cloud-starter-netflix-turbine</artifactId>
			</dependency>
			
			<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-actuator</artifactId>
			</dependency>
			
			
    		
</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by spencergibb** [comment]
Do you have spring boot starter web?

**Comment by magelon** [comment]
@spencergibb  yes

**Comment by spencergibb** [comment]
Then you have a corrupt download in .m2/repository

**Comment by magelon** [comment]
I am using eclipse (STS) on a mac book. 
How to redownload  .m2/repository

**Comment by magelon** [comment]
I delete .m2/repository and redownload in eclipse.
and it works now, you are right it was a corrupt download in .m2/repository, thanks.
