### ISSUE TITLE
Have you ever done a capacity evaluation or stress test on eureka

### ISSUE THREAD

**Issue by GraceYYJ** [spring-cloud/spring-cloud-netflix#3167]
Have you ever done a capacity evaluation or stress test on eureka？Is any report ？
It seems not good when the servicenum>3000 or instancenum>8000（8 core CPU）.

**Comment by spencergibb** [comment]
Eureka is meant to run as a cluster and scale horizontally

**Comment by GraceYYJ** [comment]
Indeed, eureka is a creation by Netflix.
I come to ask for help Because I have some doubts in Eureka performance.
I did a capacity evaluation of Eureka,I create so many Eureka clients to Initiate registration requests to a single node Eureka Server，when the servicenum>3000 or instancenum>8000 ，CPU utilization reached a bottleneck. If I adjust the "eureka.instance.lease-renewal-interval-in-seconds", CPU problems were mitigated, but there were many exceptions on the server side.
Oddly enough, Eureka performance in cluster mode seems to be worse.If I specify node1 as the primary node when I register, when the number of instances reaches 2000, the CPU of node1 will reach the bottleneck, resulting in the problem of unconnectable, while node2 is still quite normal.
All in all, I would very much like to know if Eureka has any official performance test or capacity evaluation report.Sorry to disturb you.

**Comment by twicksell** [comment]
For context, Netflix runs about 90k registered instances for our Eureka deployment of 12 nodes (which is probably over provisioned for our actual needs). This is with a renewal interval of 30 seconds. 

One important factor here is that we have separated our read and write clusters for eureka by setting the following client-side properties:
```
# the vipAddress for the readonly cluster
eureka.client.transport.readClusterVip=<someVipForReadOnlyCluster>

# the vipAddress for the write cluster
eureka.client.transport.writeClusterVip=<someVipForWriteOnlyCluster>
```

We found this to provide a dramatic performance increase for our traffic patterns.

**Comment by ryanjbaxter** [comment]
@GraceYYJ please follow up with the Netflix Eureka project is you have further questions on Eureka performance.
