### ISSUE TITLE
why spring.application.name can not tranfer to domain:port/context-path

### ISSUE THREAD

**Issue by EightMonth** [spring-cloud/spring-cloud-netflix#3169]
Hi spring cloud feign
  I think spring.application.name can tranfer to domain:port/context-path at @FeignClient("spring.application.name").
  If it can not, so this name is a server, not a service.

**Comment by ryanjbaxter** [comment]
I am not sure what you are asking.  In addition this is the wrong repo for this question, please open an issue here https://github.com/spring-cloud/spring-cloud-openfeign.
