### ISSUE TITLE
How to replace tomcat with netty

### ISSUE THREAD

**Issue by 3313204840** [spring-cloud/spring-cloud-netflix#3173]
spring cloud version :Finchley.SR1     spring boot version:2.0.4.RELEASE
use follow:

         <dependency>
                   <groupId>org.springframework.cloud</groupId>
                   <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
                   <exclusions>
                       <exclusion>
                             <groupId>org.springframework.boot</groupId>
                             <artifactId>spring-boot-starter-tomcat</artifactId>
                      </exclusion>
                  </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-reactor-netty</artifactId>
        </dependency>

the application start error!

**Comment by spencergibb** [comment]
Eureka server requires a servlet container, therefore will not work with Netty

**Comment by patpatpat123** [comment]
Hello,

Almost one year after this comment, with Webflux and reactive stack being more and more popular, any plan for a non-blocking/webflux/reactive eureka?

Thank you

**Comment by spencergibb** [comment]
Eureka server will never work with webflux unless it is redesigned.

**Comment by patpatpat123** [comment]
Hello Spencer,

Thank you for your confirmation
