### ISSUE TITLE
EurekaClient shutdown causing BeanCreationNotAllowedException which prevents unregistration of the client from the registry (RefreshScope)

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#3174]
`BeanCreationNotAllowedException` is thrown during application context shutdown by the `DiscoveryClient`. 

This is issue has already been reported since long in different scenarios and different (apparent) causes. There have been many attempts at solving the issue so far, but unfortunately, although each attempt solved one cause, there are still cases where the exception is thrown.

A short summary first before a more detailed description below:
- the problem occurs during shutdown of the application after the eureka client has successfully registered with the registry
- the problem does *NOT* occur if the SpringCloud RefreshScope feature is disabled via `spring.cloud.refresh.enabled=false`. **RefreshScope** is the root cause in this scenario.
- it can be easily reproduced with Boot `2.0.4` or `1.5.14` (ie Spring Cloud `Edgware.SR4` or `Finchley.SR1`)
- the exception prevents the client from being unregistered from the registry during shutdon

The problem can be easily reproduced with a simple Spring Initilizr bootstrap project with only the `Eureka Discovery` dependency selected. This is reproductible with Boot `2.0.4` or `1.5.14` (ie Spring Cloud `Edgware.SR4` or `Finchley.SR1`).
You need a running Eureka server so the sample client can be successfully registered. Start the application with the standard configuration (nothing special needed here) and make sure it is registered with the Eureka registry. Then stop the application properly so the shutdown sequence is executed (Ctrl-C should do it). You should see the following log lines during the shutdown:

```
2018-09-03 13:50:26.443  INFO 9494 --- [on(2)-127.0.0.1] inMXBeanRegistrar$SpringApplicationAdmin : Application shutdown requested.
2018-09-03 13:50:26.443  INFO 9494 --- [on(2)-127.0.0.1] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7a362b6b: startup date [Mon Sep 03 13:49:45 CEST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@5c30a9b0
2018-09-03 13:50:26.444  INFO 9494 --- [on(2)-127.0.0.1] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application unknown with eureka with status DOWN
2018-09-03 13:50:26.444  WARN 9494 --- [on(2)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1535975426444, current=DOWN, previous=UP]
2018-09-03 13:50:26.444  INFO 9494 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/macfury.lan: registering service...
2018-09-03 13:50:26.445  INFO 9494 --- [on(2)-127.0.0.1] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-09-03 13:50:26.446  INFO 9494 --- [on(2)-127.0.0.1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-09-03 13:50:26.446  INFO 9494 --- [on(2)-127.0.0.1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-09-03 13:50:26.448  INFO 9494 --- [on(2)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2018-09-03 13:50:26.450  WARN 9494 --- [on(2)-127.0.0.1] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
2018-09-03 13:50:26.455  INFO 9494 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/macfury.lan - registration status: 204
2018-09-03 13:50:26.505  INFO 9494 --- [on(2)-127.0.0.1] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
```

As you can see in the last few lines, a `BeanCreationNotAllowedException` exception is thrown when _destroying_ the bean `scopedTarget.eurekaClient`. The remaining part of the message gives us some hints about what's going on:
> Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)

The `DiscoveryClient#shutdown()` method starts with the following statements:
```
(1)    public synchronized void shutdown() {
(2)        if (isShutdown.compareAndSet(false, true)) {
(3)            logger.info("Shutting down DiscoveryClient ...");
(4)
(5)            if (statusChangeListener != null && applicationInfoManager != null) {
(6)                applicationInfoManager.unregisterStatusChangeListener(statusChangeListener.getId());
(7)            }
```

The exception is thrown when the execution hits line `(6)`.
You should remember both the `DiscoveryClient` and `ApplicationInfoManager` are `RefreshScope` beans (unless the Refresh feature is disabled with `spring.cloud.refresh.enabled=false`, it is enabled by default). Consequence is the `applicationInfoManager` is a refresh-scope proxy whose target must be resolved when the `unregisterStatusChangeListener` is invoked - this is done via a `getBean(..)` call on the application context.
The `shutdown` method is invoked by the application context during its shutdown procedure. At this point the underlying BeanFactory is in a _closing_ state and actively refuses any `getBean(...)` call made by other components, throwing `BeanCreationNotAllowedException` at any attempt. 

Let's recap: 
- DiscoveryClient.shutdown() is invoked during the application context shutdown/close process
- DiscoveryClient needs to unregister from the ApplicationInfoManager
- applicationInfoManager is refresh-scoped, its target must be resolved for every method invocation
- the resolution fails with a BeanCreationNotAllowedException because the BeanFactory is in closing state.

At the end, we do actually _request a bean from a BeanFactory in a destroy method implementation!_, which is, as per the exception message, not allowed.

The problem does **NOT** appear if the refresh feature is disabled with `spring.cloud.refresh.enabled=false`.

**Comment by brenuart** [comment]
I have no idea how to solve this issue (the RefreshScope mechanism is still a mystery to me)...

However, since the ApplicationInfoManager does not maintain any state on its own and all its dependencies are RequestScope too - I wonder if the ApplicationInfoManager itself could not be made a standard singleton instead (not refresh-scoped). I made on test and it seems to work...

**Comment by brenuart** [comment]
`ApplicationInfoManager` **IS** already initialized at the time shutdown is invoked - actually, its initialization is forced before the `EurekaClient` is created (see https://github.com/spring-cloud/spring-cloud-netflix/blob/1.4.x/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L271-L275 - same is true in master too).

So I don't think initialization is the cause...

**Comment by brenuart** [comment]
Hi @ryanjbaxter, here are some more news after further investigations...

The issue seems to take its roots inside how the `RefreshScope` is destroyed. It starts by clearing its local cache of target beans then proceed with their disposal. The problem arise when one of these beans makes a call to another refresh-scoped bean in its dispose method - that is the case of Netflix's DiscoveryClient. The cache being cleared, a new instance of the proxied reference must be created which leads to the BeanCreationNotAllowedException.

`RefreshScope` extends `GenericScope` whose shutdown method looks like this: https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/context/scope/GenericScope.java#L130-L134. As you can see it starts by clearing the local cache...

Furthermore, as far as I can tell, target beans (the ones that were cached) are disposed in _any order_ (the cache returns an unordered Collection) irrespective of their dependencies. This means that even if the cache wasn't cleared before the beans are disposed, the ApplicationInfoManager could have been disposed before the EurekaClient... and this is likely to cause other issues as well.

**Comment by ryanjbaxter** [comment]
@brenuart thanks for the detailed investigation
@dsyer @spencergibb any thoughts based on these findings?

**Comment by dsyer** [comment]
The cache returns an ordered collection, I think. The assumption is that if you destroy the beans in reverse order of their creation, they shouldn't create the kinds of issues described here (it's a very common pattern in Spring lifecycles). Maybe the collection needs to be reversed, and the logic is wrong for that? It would be a simple fix.

**Comment by brenuart** [comment]
> The cache returns an ordered collection, I think.
@dsyer This is not the case unfortunately. The `StandardScopeCache` uses a `ConcurrentHashMap` underneath whose keys and values are not ordered.

Changing the map implementation to preserve order will not be enough I'm afraid. Target beans get into the cache on first _use_ and not on their first _reference_. To be 100% correct, the exact moment a target bean gets into the cache depends on:
- `RefreshScope` is configured with `eager` initialization (true by default). In this case, target beans are created on `ContextRefreshedEvent` in the order given by `context.getBeanDefinitionNames()` (does it reflect the dependency order?). When `eager=false`, target beans are created at the very last moment on their first use.
- whether the bean definition is `@Lazy` or not

In addition to the shutdown ordering of target beans, we should also remember the RefreshScope cache is cleared *before* the target beans are disposed (see `GenericScope#destroy()`). Suppose the destroy method of a target bean makes a call to another scoped bean: since the cache is empty, a new instance of it will be created... and will never be disposed.

**Comment by brenuart** [comment]
> Beans are always created in dependency order

_Proxies_ are created in dependency order, but _targets_ are created when they are first invoked.
As I mentioned, if `RefreshScope.eager=false` the `StandardScopeCache` is empty after bootstrap and will be populated according to the execution paths at runtime. In your example, you may endup in having A before B (or the opposite) depending on which one got invoked first...
If `eager=true`, then targets are added in the order returned by `context.getBeanDefinitionNames()` which (afaik) is not guaranteed to be the dependency order.

I'll take some time to write a test case similar to those found in `RefreshScopeConfigurationTests` to illustrate the case. As I said, I'm not an expert at all of the RefreshScope stuff and I may be completely wrong... At least the test case would illustrate my point ;-)

**Comment by dsyer** [comment]
I see what you mean. The test case will be useful. The dependency order is the important one, but it *is* available, so we ought to be able to capture it if necessary. In the last resort we could probably control the ordering specifically for `ApplicationInfoManager` and `DiscoveryClient` by building them into a single factory and taking them out of the bean factory directly.

**Comment by brenuart** [comment]
@dsyer Please find some additional test cases to illustrate my findings while troubleshooting this issue. They are available in my own public fork at https://github.com/brenuart/spring-cloud-commons/tree/netflix_gh3174.

You may not find all tests relevant - certainly in the light of the changes you foresee to solve the current issue (if any). Hope they will be useful anyway ;-)

**Comment by brenuart** [comment]
ping @dsyer @ryanjbaxter @spencergibb any news on this ?

**Comment by ryanjbaxter** [comment]
Not yet, many of use are trying to prepare for a conference next week.  We will come back to this soon.

**Comment by brenuart** [comment]
ping @dsyer @ryanjbaxter @spencergibb any news on this ?

BTW, congrats for that nice conference! Lots of valuable information. Thx to all of you.

**Comment by ryanjbaxter** [comment]
Closed via c3fbc3

**Comment by brenuart** [comment]
@dsyer This issue is now closed, but don't you think another should be opened against spring-cloud-commons to cover the order beans are destructed when RefreshScope is disposed ?

**Comment by dsyer** [comment]
Indeed. Feel free to do so.

**Comment by ryanjbaxter** [comment]
Yes +1 thanks

**Comment by JavaHelper** [comment]
I'm experiencing this issue and posted question here: https://stackoverflow.com/questions/53955613/working-with-eureka-clients-programmatically-issue-completed-shut-down-of-disc. Kindly help
