### ISSUE TITLE
CloudEurekaClient not respecting manual status change

### ISSUE THREAD

**Issue by michael-pratt** [spring-cloud/spring-cloud-netflix#3176]
Not sure if this is expected behavior, but I am using `CloudEurekaClient` to periodically mark an instance as `OUT_OF_SERVICE` (the instance can perform a single, long running task so I don't want it to be used for some period of time):

    InstanceInfo instance = cloudEurekaClient.getNextServerFromEureka("service", false);
    cloudEurekaClient.setStatus(InstanceInfo.InstanceStatus.OUT_OF_SERVICE, instance);

However, if I then call `CloudEurekaClient.getNextServerFromEureka()` prior to the scheduled registry refresh task executing, it's possible for the client to return the `OUT_OF_SERVICE` instance when I call:

    InstanceInfo instance = cloudEurekaClient.getNextServerFromEureka("service", false);

It seems like the client should honor any status changes that it makes. Is this by design, or a possible enhancement to have the client force a refresh after it changes an instance status?

**Comment by spencergibb** [comment]
AFAIK, that's not the way to change the status however intuitive it might seem. See [`EurekaServiceRegistry.setStatus()`](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistry.java#L78)

**Comment by michael-pratt** [comment]
Thanks Spencer. I'm fairly new to the Eureka universe so I might be misunderstanding, but I thought `EurekaServiceRegistry.setStatus()` was used to set the status of the app from which it is called. It takes a `EurekaRegistration` as a parameter, which represents the registration information for the application in which the client is running, correct?

In my case I want one application to update the status of another application in Eureka. That doesn't seem doable using `EurekaServiceRegistry.setStatus()` since I would have to create a new `EurekaRegistration` object that represents the remote application.

**Comment by spencergibb** [comment]
I see. `CloudEurekaClient.setStatus()` just issue a remote call, there is nothing done locally. It's really just a convenience method. The `EurekaServiceRegistry` eventually ends up there, sorry for the misunderstanding. Marking something `OUT_OF_SERVICE` while it's running a long task is an unusual way of using status. Not much to do there I think, the normal refresh locally is still in play.

**Comment by michael-pratt** [comment]
I think it could a more general use case: one application that has responsibility for taking other applications in and out of service for any reason, in which case having the discovery client maintain accurate state would be very important.

I'm going to fork the `CloudEurekaClient` to keep its local instance status in sync when `setStatus()` is called. I'd be happy to submit as a PR if you think it'd be useful for others.

**Comment by brenuart** [comment]
If you want to change the status of the application, using `ApplicationInfoManager#setInstanceStatus(status)` is probably the way to go...

But as far as I understand, you are not looking to change the status of the _current_ application, but manipulate the status of other applications registered with the registry. If so, then you'd better to have a look at the Eureka REST API and use the corresponding endpoint. Check this link for more information https://github.com/Netflix/eureka/wiki/Eureka-REST-operations.

**Comment by michael-pratt** [comment]
@brenuart I considered using the Eureka REST API, but then I'd have to do all my lookups through the API as well. I'd prefer to use the client for everything since it already has the logic for handling updates/deltas from the server, round robin selection of next server, configuring Jersey client, etc.

**Comment by brenuart** [comment]
The EurekaClient is meant to handle the state of the application it is running in – it is not a general purpose EurekaServer client that can be used to manipulate the state of _other_ applications.

You may be able to perform some tasks by extending it yourself, but you are likely to have strange results soon or later.

Or maybe I didn’t understand your usecase correctly.

**Comment by michael-pratt** [comment]
I understand my use case probably isn't what the client was designed for, but it also does a lot of what I _do_ need, so I'd hate to start from scratch. I'll see how far I get with trying to extend it for my needs :)

I'll go ahead and close this issue as well, thanks for the help!
