### ISSUE TITLE
[Question] why returning RequestSpecificRetryHandler with both false of okToRetryOnConnectErrors and okToRetryOnAllErrors in RetryableFeignLoadBalancer?

### ISSUE THREAD

**Issue by 6Pker** [spring-cloud/spring-cloud-netflix#3179]
Hi @ryanjbaxter , would you pls help to explain this question?

Why returning RequestSpecificRetryHandler with both false of okToRetryOnConnectErrors and okToRetryOnAllErrors in org.springframework.cloud.netflix.feign.ribbon.RetryableFeignLoadBalancer?

@Override
public RequestSpecificRetryHandler getRequestSpecificRetryHandler(
			FeignLoadBalancer.RibbonRequest request, IClientConfig requestConfig) {
		return new RequestSpecificRetryHandler(false, false, this.getRetryHandler(), requestConfig);
}

I was wondering why here hard coding with okToRetryOnConnectErrors = false and okToRetryOnAllErrors = false, is it meaning that there won't be any retry when occurred connectErrors and some other errors?

**Comment by holy12345** [comment]
Hi @6Pker 
According to my understanding spring cloud use `spring-retry` do retry.
For example In `RetryableFeignLoadBalancer` you can see `execute` method make a `RetryTemplate`.

So if you use `spring-retry` do retry I think `okToRetryOnConnectErrors` and `okToRetryOnAllErrors` will not be affected .

**Comment by 6Pker** [comment]
thanks @holy12345
