### ISSUE TITLE
Bug: No SecurityContext in fallback method 

### ISSUE THREAD

**Issue by bvoss** [spring-cloud/spring-cloud-netflix#3183]
Hi,

I encounter a problem using the spring-cloud-netflix with hystrix, when using fallback methods.

I would expect the SecurityContext to be present in fallback methods when using @HystrixCommand as described in the [documentation](http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.0.1.RELEASE/single/spring-cloud-netflix.html#_how_to_include_hystrix) 
But in fallback methods the security context is never present, no matter if I use thread or semaphore isolation.

Attached a sample project and stripped log output from the test.
In the test output you can see there is no current user in fallback methods.

I think this related to an [issue in spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1073)

Versions:
Spring Boot: 2.0.4.RELEASE
Spring Cloud: Finchley.SR1
Spring Cloud Netflix: 2.0.1.RELEASE
Hystrix: 1.5.12

For any other dependency, please have a look in the pom of the sample app in the attached zip.
[spring-cloud-netflix-bug.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2361699/spring-cloud-netflix-bug.zip)
[spring-cloud-bug-stripped-test-uotput.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/2361700/spring-cloud-bug-stripped-test-uotput.txt)

**Comment by ryanjbaxter** [comment]
I am not seeing the problem when I run your sample.  The fallback gets executed and is able to pull the user from the security context.

**Comment by bvoss** [comment]
@ryanjbaxter Hmm, strange.
Every time I execute the test I get no user in the fallback. I also see this behavior in production.
Can you provide a log output of the test, please.

**Comment by ryanjbaxter** [comment]
Ah ok, I misinterpreted the logging, it isnt working for me either.

**Comment by ryanjbaxter** [comment]
@daniellavoie is going to take a look at this since he originally did the work to add `hystrix.shareSecurityContext`

**Comment by bvoss** [comment]
any update here?

**Comment by spencergibb** [comment]
@bvoss are you still having issues?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
