### ISSUE TITLE
Eureka instances are showing in available

### ISSUE THREAD

**Issue by sdsaini007** [spring-cloud/spring-cloud-netflix#3185]
Hi i have 3 instances of Eureka Server. I made the peer connection between these 3 instances by registering them to each other as a client. Initially my all instances are up and are showing in available-replicas. But when i down the other two instances yet they are showing in available-replicas. Please help me with the configuration.

peer1-
  server.port=7555
    eureka.instance.hostname=instance01
    spring.application.name=EurekaServerCluster
    eureka.client.serviceUrl.defaultZone:http://instance02:7555/eureka/,http://instance03:7555/eureka/
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    eureka.client.healthcheck.enabled=true
    eureka.instance.preferIpAddress=false

 peer2-
  server.port=7555
    eureka.instance.hostname=instance02
    spring.application.name=EurekaServerCluster
    eureka.client.serviceUrl.defaultZone:http://instance01:7555/eureka/,http://instance03:7555/eureka/
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    eureka.client.healthcheck.enabled=true
    eureka.instance.preferIpAddress=false

peer3-
  server.port=7555
    eureka.instance.hostname=instance03
    spring.application.name=EurekaServerCluster
    eureka.client.serviceUrl.defaultZone:http://instance01:7555/eureka/,http://instance02:7555/eureka/
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    eureka.client.healthcheck.enabled=true
    eureka.instance.preferIpAddress=false

**Comment by spencergibb** [comment]
Can you explain:

> But when i down the other two instances yet they are showing in available-replicas. 

Have two out of three eureka servers down is not a good state to be in and eureka will likely enter self-preservation mode.

**Comment by sdsaini007** [comment]
Hi @spencergibb, I intentionally made down the other two instances and yet they are showing in available replicas which is like opposite the case they should be in unavailable-replicas.

**Comment by ryanjbaxter** [comment]
How long are you waiting for them to be removed?

**Comment by sdsaini007** [comment]
Long enough @ryanjbaxter

**Comment by ryanjbaxter** [comment]
Sorry I dont know what that means, please be specific

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
