### ISSUE TITLE
build.sh fails with Dir not found

### ISSUE THREAD

**Issue by nBhati** [spring-cloud/spring-cloud-netflix#3191]
While building the project using build.sh i am getting below output.

/bin/bash /Users/nBhati/CodeBases/spring-cloud-netflix/scripts/build.sh
/Users/nBhati/CodeBases/spring-cloud-netflix/scripts/build.sh: line 3: _cd: spring-cloud-netflix-hystrix-contract: No such file or directory_
/Users/nBhati/CodeBases/spring-cloud-netflix/scripts/build.sh: line 4: ./mvnw: No such file or directory

To Fix this i have modified the script as below and now it works fine

#!/bin/bash

(cd ../spring-cloud-netflix-hystrix-contract && ../mvnw clean install -B -Pdocs ${@})
./mvnw clean install -B -Pdocs ${@}

please let me know if i can contribute this as a fix.

Thanks
Narayan

**Comment by spencergibb** [comment]
you need to run the script from `spring-cloud-netflix`.
