### ISSUE TITLE
Feign calls wrong : feign.RetryableException

### ISSUE THREAD

**Issue by Yvan0329** [spring-cloud/spring-cloud-netflix#3192]
I have two services A and B.When A service invokes B service, there is a probability that the invocation will fail, about 100 requests, two or three times.And there was a mistake:

Application.yml configuration of feign：

> feign:
>   hystrix:
>     enabled: true
>   okhttp:
>     enabled: true
>   httpclient:
>     enabled: false
>   client:
>     config:
>       feignName:
>         connectTimeout: 10000
>         readTimeout: 10000
>   compression:
>     request:
>       enabled: true
>     response:
>       enabled: true
> 
> hystrix:
>   command:
>     default:
>       execution:
>         isolation:
>           strategy: SEMAPHORE
>           thread:
>             timeoutInMilliseconds: 60000
>   shareSecurityContext: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

This is my fegin Interceptor：

> @Slf4j
> public class TcsfFeignClientInterceptor extends OAuth2FeignRequestInterceptor {
> 
>     private final OAuth2ClientContext oAuth2ClientContext;
> 
>     private final String AUTHORIZATION_HEADER = "Authorization";
>     private final String BEARER_TOKEN_TYPE = "Bearer";
> 
>     /**
>      * Default constructor which uses the provided OAuth2ClientContext and Bearer tokens
>      * within Authorization header
>      *
>      * @param oAuth2ClientContext provided context
>      * @param resource            type of resource to be accessed
>      */
>     public TcsfFeignClientInterceptor(OAuth2ClientContext oAuth2ClientContext
>             , OAuth2ProtectedResourceDetails resource) {
>         super(oAuth2ClientContext, resource);
>         this.oAuth2ClientContext = oAuth2ClientContext;
>     }
> 
> 
>     /**
>      * Create a template with the header of provided name and extracted extract
>      *
>      * @param template
>      */
>     @Override
>     public void apply(RequestTemplate template) {
>         SecurityContext securityContext = SecurityContextHolder.getContext();
>         Authentication authentication = securityContext.getAuthentication();
>         if (authentication != null && authentication.getDetails() instanceof OAuth2AuthenticationDetails) {
>             OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) authentication.getDetails();
>             template.header(AUTHORIZATION_HEADER, String.format("%s %s", BEARER_TOKEN_TYPE, details.getTokenValue()));
>         }
> 
>     }
> }

This is my exception message:

> 2018-09-15 19:58:59,130 [XNIO-2 task-45] ERROR [c.t.t.c.t.u.b.f.f.RemoteUserServiceFallbackImpl] RemoteUserServiceFallbackImpl.java:30 - feign 查询用户信息失败:elliot
> feign.RetryableException: unexpected end of stream on Connection{192.168.1.109:36006, proxy=DIRECT hostAddress=/192.168.1.109:36006 cipherSuite=none protocol=http/1.1} executing GET http://tcsf-upms/user/check-name?username=elliot
> 	at feign.FeignException.errorExecuting(FeignException.java:67)
> 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:104)
> 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
> 	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
> 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
> 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
> 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
> 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
> 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.subscribe(Observable.java:10423)
> 	at rx.Observable.subscribe(Observable.java:10390)
> 	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51)
> 	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:410)
> 	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378)
> 	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:344)
> 	at feign.hystrix.HystrixInvocationHandler.invoke(HystrixInvocationHandler.java:159)
> 	at com.sun.proxy.$Proxy249.info(Unknown Source)
> 	at cn.topcodes.tcsf.cloud.tcsf.common.security.service.TcsfUserDetailsServiceImpl.loadUserByUsername(TcsfUserDetailsServiceImpl.java:66)
> 	at org.springframework.security.oauth2.provider.token.DefaultUserAuthenticationConverter.extractAuthentication(DefaultUserAuthenticationConverter.java:76)
> 	at org.springframework.security.oauth2.provider.token.DefaultAccessTokenConverter.extractAuthentication(DefaultAccessTokenConverter.java:120)
> 	at org.springframework.security.oauth2.provider.token.RemoteTokenServices.loadAuthentication(RemoteTokenServices.java:119)
> 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83)
> 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
> 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:155)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:123)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
> 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
> 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
> 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
> 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
> 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
> 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
> 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
> 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
> 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
> 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
> 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
> 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
> 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
> 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
> 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
> 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
> 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
> 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
> 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
> 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
> 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
> 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
> 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
> 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
> 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
> 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
> 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.IOException: unexpected end of stream on Connection{192.168.1.109:36006, proxy=DIRECT hostAddress=/192.168.1.109:36006 cipherSuite=none protocol=http/1.1}
> 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
> 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
> 	at okhttp3.RealCall.execute(RealCall.java:69)
> 	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:161)
> 	at org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient.execute(TracingFeignClient.java:91)
> 	at org.springframework.cloud.sleuth.instrument.web.client.feign.LazyTracingFeignClient.execute(LazyTracingFeignClient.java:55)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:103)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:88)
> 	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
> 	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:88)
> 	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:54)
> 	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
> 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
> 	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286)
> 	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
> 	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
> 	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
> 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127)
> 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
> 	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79)
> 	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
> 	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
> 	at rx.Subscriber.setProducer(Subscriber.java:209)
> 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
> 	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.subscribe(Observable.java:10423)
> 	at rx.Observable.subscribe(Observable.java:10390)
> 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
> 	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
> 	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
> 	at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63)
> 	at org.springframework.cloud.sleuth.instrument.web.client.feign.TraceLoadBalancerFeignClient.execute(TraceLoadBalancerFeignClient.java:67)
> 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
> 	... 142 common frames omitted
> Caused by: java.io.EOFException: \n not found: limit=0 content=…
> 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
> 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
> 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
> 	... 203 common frames omitted

I don't know why this problem arises. Have you ever met this problem like me? Tell me how to solve it.

**Comment by ryanjbaxter** [comment]
I dont see how this is related to Spring Cloud Netflix.
