### ISSUE TITLE
How can i make zuul route some apis of one serviceId and not route some apis of this serviceId

### ISSUE THREAD

**Issue by zc1024** [spring-cloud/spring-cloud-netflix#3194]
I have a question:

I'm using spring cloud and zuul as api gateway.And what should i do to make some apis of one service to be opened to the public ,and other apis of this service are only opened to inner net.Both opened apis and closed apis are all in one service.

Please,Thanks!

**Comment by ryanjbaxter** [comment]
Sounds to me like its a matter of configuring spring security correctly, you just may have to be pretty specific in your configuration so certain apis require authentication and others do not.

**Comment by zc1024** [comment]
I considered about that way.But in this way did  it mean I have to add authentication info in my inner net service when I request the apis?

**Comment by zc1024** [comment]
sorry ,what I wan to express is my own other services.

**Comment by ryanjbaxter** [comment]
If you mean do you have to add spring security to your downsteam apps, then yes.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
