### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by xiaoyangzhang** [spring-cloud/spring-cloud-netflix#3200]
I clone the project ,but when I build it according to the doc,it failed and reported that "Unresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.1.RELEASE or one of its dependencies could not be resolved: Could not find artifact org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.1.0.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/libs-snapshot-local) @ 
[WARNING] 'build.plugins.plugin.version' for org.asciidoctor:asciidoctor-maven-plugin is missing. @ org.springframework.cloud:spring-cloud-netflix-eureka-server:[unknown-version], /Users/zhangxiaoyang/workspace/github/springCloud/spring-cloud-netflix/spring-cloud-netflix-eureka-server/pom.xml, line 216, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.springframework.cloud:spring-cloud-netflix-docs:[unknown-version], /Users/zhangxiaoyang/workspace/github/springCloud/spring-cloud-netflix/docs/pom.xml,".
I looked at the net address "https://repo.spring.io/libs-snapshot-local" and found that it indeed lack of the jar "org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.1.0.BUILD-SNAPSHOT".

**Comment by xiaoyangzhang** [comment]
thanks,it did works.

**Comment by 1067511899** [comment]
> 
> 
> I have some error,and my operation system is windows 10,it can not run sh script.
> what should I do ?
> 
> thanks.
> 
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [ERROR] Unresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:2.0.1.RELEASE or one of its dependencies could not be resolved: Could not find artifact org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.1.0.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/libs-snapshot-local) @

I have solved this problem.
D:\workspace\spring\spring-cloud-netflix>cd spring-cloud-netflix-hystrix-contract
D:\workspace\spring\spring-cloud-netflix>D:\workspace\spring\spring-cloud-netflix\mvnw clean install
D:\workspace\spring\spring-cloud-netflix>D:\workspace\spring\spring-cloud-netflix\mvnw install

And if someone use sts to import the spring cloud project,he may get some pom.xml error.
Can solve like this:
copy the contract jar files to the maven local directory.something like ：
C:\Users\lenovo\.m2\repository\org\springframework\cloud\spring-cloud-netflix-hystrix-contract\2.1.0.BUILD-SNAPSHOT

Thanks.

**Comment by wordsless** [comment]
When I try to build spring-cloud-netflix,  report

[INFO] Building jar: /Users/liqiang/Projects/spring-cloud-netflix/spring-cloud-netflix-hystrix-contract/target/spring-cloud-netflix-hystrix-contract-2.0.2.RELEASE-sources.jar
[INFO] 
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ spring-cloud-netflix-hystrix-contract ---
gpg: signing failed: Inappropriate ioctl for device

**Comment by ryanjbaxter** [comment]
@wordsless please dont comment on and open multiple issues
