### ISSUE TITLE
question: how do i use HystrixCommand at the spring-cloud-gateway

### ISSUE THREAD

**Issue by JangCool** [spring-cloud/spring-cloud-netflix#3204]
hi, i have a few question

i want to do the hystrix configuration in a yml file on the spring-cloud-gateway.

Is it possible?
how do i use HystrixCommand at the spring-cloud-gateway? 

I'll wait for your answer.
Thank your for interest in this question.

**Comment by rusbob** [comment]
Here it is not a right place. Please, see [spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway)
