### ISSUE TITLE
forward request to actual service id according to request params

### ISSUE THREAD

**Issue by huangqiuabc** [spring-cloud/spring-cloud-netflix#3205]
i’m using zuul as http reverse proxy.There are 4 backend servers providing services and one Api gateway which are all registing in eureka .

And on Api gateway ,I want to forward this request to one of the 4 backend servers according to the request params.like if bizType = 1 ,forward to the first servers ...etc.

Is it possible to implements this by RibbonRoutingFilter,pls help

**Comment by ryanjbaxter** [comment]
This is probably not going to be easily done, if it is even possible.  You are essentially wanting to create a specific load balancer thats logic is based on the request.  Unfortunately the current`ServiceInstanceChooser` interface (which `LoadBalancerClient` implements ) only gets passed the service id and not the request.  You might be able to try using the Zuul `RequestContext` to access the current request in your custom `LoadBalancerClient`.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
