### ISSUE TITLE
Zuul authorization is ignored when configured otherwise

### ISSUE THREAD

**Issue by dlvenable** [spring-cloud/spring-cloud-netflix#3207]
We have a Spring Boot Zuul gateway project which uses OAuth2 authentication. The basic principle is that AngularJS requests from a browser are redirected through Zuul, given the OAuth2 access token as a Bearer token in the `Authorization` header, and then routed to our backend services.

This was working on Spring Boot 1.5.9 / Edgware.RELEASE. However, in Spring Boot 2.0.5 / Finchley.SR1 the Authorization header was no longer being populated with the Bearer access token.

I traced the issue down to `SimpleHostRoutingFilter` and `ProxyRequestHelper`. The Zuul context had the desired `authentication` header with the Bearer token. However, it was in the list of ignored headers. So `ProxyRequestHelper::isIncludedHeader` was filtering it out.

I tried setting these properties which I found in the [documentation](https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html#_ignored_headers):

```
zuul.ignoreSecurityHeaders=false
zuul.ignoredHeaders=Cookie,Set-Cookie
```

However, `authentication` was still in the ignored headers.

I have worked around this issue by creating a pre Zuul filter that removes the `authorization` header. However, this shouldn't be necessary since there are already other configurations available for this.

Here is my work-around filter:
```
   @Override
    public String filterType()
    {
        return "pre";
    }

    @Override
    public int filterOrder()
    {
        return PRE_DECORATION_FILTER_ORDER + 1000;
    }

    @Override
    public boolean shouldFilter()
    {
        RequestContext context = RequestContext.getCurrentContext();
        Object ignoredHeadersObject = context.get(IGNORED_HEADERS);
        if (ignoredHeadersObject instanceof Collection)
        {
            return ((Collection) ignoredHeadersObject).contains("authorization");
        }
        return false;
    }

    @Override
    public Object run()
    {
        RequestContext context = RequestContext.getCurrentContext();
        Object ignoredHeadersObject = context.get(IGNORED_HEADERS);
        if (ignoredHeadersObject instanceof Collection)
        {
            ((Collection) ignoredHeadersObject).remove("authorization");
        }
        return null;
    }
```

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/3126
