### ISSUE TITLE
Could you please upgrade dependency to 2.0.4.RELEASE?

### ISSUE THREAD

**Issue by JavaHelper** [spring-cloud/spring-cloud-netflix#3208]
Could you please upgrade dependency to 2.0.4.RELEASE?

**Comment by spencergibb** [comment]
I don't know what that means. Care to elaborate?

**Comment by JavaHelper** [comment]
When I upgraded, Spring Boot version to 2.0.4.RELEASE, some modules are not working properly. So ask is just to upgrade dependency

**Comment by spencergibb** [comment]
Can you expound on
> some modules are not working properly

**Comment by spencergibb** [comment]
If you can clarify what you mean, I'll reopen
