### ISSUE TITLE
eureka.instance.nonSecurePort gets overriden by server.port

### ISSUE THREAD

**Issue by philippn** [spring-cloud/spring-cloud-netflix#3209]
Hello,
please pardon me if I have missed something. I can't quite believe that I am the first one to stumble across this...

With earlier versions of Spring Cloud netflix (from the Dalston release, I believe), the Port advertised to Eureka could be overriden with eureka.instance.nonSecurePort. With the current version (2.0.1), the port advertised to Eureka is _always_ the server.port.

This is quite a problem when working for example with Docker containers where internal and external ports differ.

Am I missing something or is this really a bug?

Thanks for your time and kind regards,
Philipp

**Comment by spencergibb** [comment]
I have not seen this before. We need more information from you to determine if it a big or not. Can you provide a project that recreates the problem?

**Comment by philippn** [comment]
Upon further inspection, it turns out the Eureka admin interface fooled me. 

When looking at `/eureka/apps`, the `homepageUrl` indeed is changed to the port number in `eureka.instance.nonSecurePort`. However, `statusPageUrl' and 'healthCheckUrl' don't seem affected. Is that a bug? Or how am I supposed to change those?

**Comment by spencergibb** [comment]
Duplicates #2144
