### ISSUE TITLE
zuul routing issue with prefix removing

### ISSUE THREAD

**Issue by vinothch** [spring-cloud/spring-cloud-netflix#3218]
I have and client registered in eureka server. This application restpoint can be hit with below url
http://localhost:8090/tt/name?name=vinoth
using zuul i can hit the same 
http://localhost:8762/api/ttapi/tt/name?name=vinoth

zuul application properties are:
server.port=8762
spring.application.name=zuul-service
zuul.prefix=/api
zuul.routes.tt.path=/ttapi/**

how to get rid of api and tt from the above url

**Comment by ryanjbaxter** [comment]
Please dont spam us with multiple comments and opening multiple issues.

Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Zuul by default will strip the prefix, what exactly is not getting stripped and what does the request zuul is making look like?

**Comment by vinothch** [comment]
Hi thanks for the reply,
my current url is http://localhost:8762/api/ttapi/tt/name?name=vinoth

i want my url to look like 
http://localhost:8762/tt/name?name=vinoth

zuul application properties are:
server.port=8762
spring.application.name=zuul-service
zuul.prefix=/api
zuul.routes.tt.path=/ttapi/**

**Comment by ryanjbaxter** [comment]
> what exactly is not getting stripped and what does the request zuul is making look like?

**Comment by vinothch** [comment]
how to strip 
zuul.prefix=/api
from the url
http://localhost:8762/api/ttapi/tt/name?name=vinoth

**Comment by vinothch** [comment]
if i give 
zuul.strip-prefix=false  OR
zuul.routes.tt.strip-prefix=false
it is not working

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

If you want the prefixes stripped why would you set those properties to `false`.
