### ISSUE TITLE
Ribbon with Eureka discovery - reverse communication - eureka call for services to refresh list

### ISSUE THREAD

**Issue by lukaszpy** [spring-cloud/spring-cloud-netflix#3220]
I don't know if it's possible but i want to make my spring boot up fully gracefull update on swarm.

What we have:
- service A - some servie, using D service
- service B - dome service, using D service
- service D - database service
Every service using Eureka to discover service D (all services are registered on eureka)

What I want to do :
- deploy new D service

What's happend on swarm sluster:
- swarm spawn new service version (as have option start-first)
- services refresh list in ribbon from current eureka state (have both D services) 
- docker call SIGINT to kill app D (old one)
- service D properly unregister from Eureka
- services calls D service but  instance which was killed

What will be best:
- eureka on any change on list of serives call every service to refresh lists

Is there any way to complete this is current version of Eureka ? 
As for now Ribbon has LISTOFSERVERS_CACHE_REPEAT_INTERVAL set to 30s but if i change this time to more often then i will cause heavy load of service discovery.

**Comment by ryanjbaxter** [comment]
This is what the retry functionality supported by Ribbon can be used for.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
