### ISSUE TITLE
How many Euraka-Server instances deployed in a cluster?What's the best number,2 or 3 or ....?

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-netflix#3222]

**Comment by holy12345** [comment]
I think it depends on how many clients you have. But one is that we guarantee that the `eureka server` can synchronize the client information with each other. 

I use three `eureka server` in cluster in our production before

**Comment by ryanjbaxter** [comment]
This question is better asked in the Netflix Eureka repo.

**Comment by andyzhaozhao** [comment]
> I think it depends on how many clients you have. But one is that we guarantee that the `eureka server` can synchronize the client information with each other.
> 
> I use three `eureka server` in cluster in our production before

Thanks for your replay.I have 21 clients. How can I make the decision about the Euraka server numbers?

**Comment by andyzhaozhao** [comment]
> This question is better asked in the Netflix Eureka repo.

Thank you . Do you Know the  Netflix Eureka repo URL ?

**Comment by spencergibb** [comment]
https://github.com/Netflix/eureka
