### ISSUE TITLE
when I  use refreshScope.refresh to refresh someconfig the DiscoveryClient ScheduledTasks  was canceled 

### ISSUE THREAD

**Issue by xjr100419** [spring-cloud/spring-cloud-netflix#3223]
Bug report

spring cloud version: `Dalston.SR4`
use: `org.springframework.cloud.context.scope.refresh.RefreshScope`

details:
when use `refreshScope.refresh("someconfig");` to refresh some config

process: `cache.remove(someconfig);` -> publish RefreshScopeRefreshedEvent -> EurekaDiscoveryClientConfiguration listen RefreshScopeRefreshedEvent ->
		 `autoRegistration.stop();` -> DiscoveryClient.shutdown -> `cancelScheduledTasks();` after this the scheduledTasks  was canceled ->
		 `autoRegistration.start();` -> after all I can not found any method to restart DiscoveryClient ScheduledTasks

so:after update refresh some config, DiscoveryClient was can not communicate the eureka server

**Comment by xjr100419** [comment]
when I replace to  use refreshScope.refreshAll();  everything work well
I found that  DiscoveryClient was refresh able too , then  DiscoveryClient instance  rebuild and  resume  initScheduledTasks()

**Comment by ryanjbaxter** [comment]
Can you please try Edgware.SR4 or Finchley.SR1?

**Comment by xjr100419** [comment]
Edgware.SR4 work well
`
public void deregister(EurekaRegistration reg) {
		if (reg.getApplicationInfoManager().getInfo() != null) {

			if (log.isInfoEnabled()) {
				log.info("Unregistering application " + reg.getInstanceConfig().getAppname()
						+ " with eureka with status DOWN");
			}

			reg.getApplicationInfoManager().setInstanceStatus(InstanceInfo.InstanceStatus.DOWN);

			//shutdown of eureka client should happen with EurekaRegistration.close()
			//auto registration will create a bean which will be properly disposed
			//manual registrations will need to call close()
		}
	}
`
`autoRegistration.stop();`  there is no trigger  `reg.getEurekaClient().shutdown();`

**Comment by ryanjbaxter** [comment]
If I remember correctly this was something that was fixed in a Eureka release that we incorporated in an Edgware service release.  I will close this for now.
