### ISSUE TITLE
question zuul RPS optimize 

### ISSUE THREAD

**Issue by pengzhiheng** [spring-cloud/spring-cloud-netflix#3226]
Zuul's RPS are small, not as big as the RPS for a single application. I've optimized a lot of parameters, but RPS is always around 170, and the RPS for a single application is around 2000. How do I optimize it
![222](https://user-images.githubusercontent.com/17924036/46779644-4cd3f280-cd4b-11e8-8350-a800a083dda5.png)

**Comment by ryanjbaxter** [comment]
As I said for the same issue you opened for the Spring Cloud Gateway, please provide a way to replicate your findings.

**Comment by pengzhiheng** [comment]
> As I said for the same issue you opened for the Spring Cloud Gateway, please provide a way to replicate your findings.
![image](https://user-images.githubusercontent.com/17924036/46850758-af022580-ce27-11e8-90a4-7701c0a2a9a1.png)



No matter how I adjust parameters.

**Comment by ryanjbaxter** [comment]
Again please provide a sample.

**Comment by dalegaspi** [comment]
take this fwiw, in my experience i cannot get things to scale with the default client (apache); i opted for okhttp and wrote my notes [here](https://gist.github.com/dalegaspi/e27981982bef9fe49defa145ba22dd2a)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
