### ISSUE TITLE
Feign timeout works but response is returned to the server after timeout + 60''

### ISSUE THREAD

**Issue by girionis** [spring-cloud/spring-cloud-netflix#3227]
Hello,

I am using Ribbon + Feign in a project

```
@FeignClient(name = "test-proxy")
@RibbonClient(name = "test-proxy")
public interface TestProxy ...
```

I have set the Feign timeout to 10'' using the following bit of code:

```
@Bean
public Request.Options options() {
	return new Request.Options(10000, 10000);
}
```

The timeout works, I get a 

`feign.RetryableException: Read timed out executing POST...`

but the response is not returned until 60'' afterwards (after about 70'' in total). The same thing happens if I set the timeout to 5'', the response is returned after about 65''.

It seems there is some thread that is running and stops the response from returning. I read that this might be due to Hystrix thread that waits to time out, but we do not use Hystrix (at least not explicitly).

I tried nevertheless to disable the Hystrix functionality using properties in the application.properties, but to no avail.

Any thoughts on this? Is this a bug or something I am missing?

These are the dependencies I use:

```
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-openfeign', version: '1.4.4.RELEASE'
	compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-netflix-ribbon', version: '1.4.5.RELEASE'
	compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-netflix-eureka-client', version: '1.4.4.RELEASE'
	compile group: 'org.springframework.cloud', name: 'spring-cloud-dependencies', version: 'Edgware.RELEASE', ext: 'pom'
	runtime('org.springframework.boot:spring-boot-devtools')
}
```

Thank you

**Comment by ryanjbaxter** [comment]
I would first suggest using the latest Edgware release SR4.

The `@RibbonClient(name = "test-proxy")` seems unnecessary. 

Since you are using Ribbon I would not set the Feign timeout but instead set the Ribbon timeout 

```
ribbon:
  ConnectTimeout: yyy
  ReadTimeout: xxx
```

**Comment by girionis** [comment]
Hello Ryan, thank you for your prompt reply.

I have used the latest Edgware release:

`compile group: 'org.springframework.cloud', name: 'spring-cloud-dependencies', version: 'Edgware.SR4', ext: 'pom'`

I have removed the `@RibbonClient` so now my interface only has the `@FeignClient` annotation.

I have added the following properties in application.properties

```
ribbon.ReadTimeout=5000
ribbon.ConnectTimeout=5000
ribbon.MaxAutoRetries=0
```

but unfortunately I still have the same problem. Ribbon does timeout after 5'' but Postman does not return a response until after 66419 ms have passed.

Any more ideas? This is the bit of code that throws the read timeout exception

```
@PostMapping(value= "/proxy", consumes = "application/json", produces = "text/plain")
public ResponseEntity<String> test(@RequestBody final Map<String, Object> parameters) {
	ResponseEntity<String> res = null;

	try {
		res = proxy.test(parameters);
	} catch (final FeignException e) {
		LOGGER.error(e.getMessage(), e);
		res = ResponseEntity.status(e.status()).build();
	}

	return res ;
}
```

If I put a break point I can see that the exception is caught, the error is logged, the line `return res ;` is executed, but Postman does not return it immediately. There must be something that keeps the response from returning but I have no idea what.

Any more thoughts?

Thank you

**Comment by girionis** [comment]
Hello Ryan, 

I have uploaded a stripped down version that indicates the problem: https://ufile.io/wq0fh

There are two projects in the rar. One is the actual service (with a 20'' delay), the other is the Ribbon balancer with a Feign client. I have set the timeout to 5'' (using `Request.Options`, the ribbon properties seem to be ignored) and although you can see the exception on the ribbon window, the request returns roughly after 60'' + the delay.

For building I used gradle 3.4.1 with Spring Boot 1.5.2 and Java 1.8.

Thank you

**Comment by OlgaMaciaszek** [comment]
Hello @girionis I have tried reproducing it and it did work the way you describe it in Postman, however, while using different http clients, I got the response straight away, which is why I would assume the issue is with Postman rather than with Feign/ Ribbon. Please try using a different http client, such as [httpie](https://httpie.org) and let me know if you still have any issues.

**Comment by girionis** [comment]
Hello Olga, thanks for looking into it.

You are right, the httpie works as expected whereas Postman fails. 

Can you shed some light on what's happening after a timeout occurs in Ribbon? This small app exhibits the same behaviour as Postman

```
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.Date;

public class Main {
    public static void main(String[] args) {
        try {
        	URL url = new URL("http://127.0.0.1:8100/proxy/test");
        	URLConnection connection = url.openConnection();
        	System.out.println("Sending request on: " + new Date());
		    BufferedReader in = new BufferedReader(
		                            new InputStreamReader(
		                            connection.getInputStream()));
		    String inputLine;
		    System.out.println("Will try to read from the stream on: " + new Date());
		    while ((inputLine = in.readLine()) != null) {
				System.out.println(inputLine);
			}
		    in.close();
		    System.out.println("Read everything from the stream on: " + new Date());
        } catch (Exception e) {
        	System.out.println("Exception occured on: " + new Date());
        	e.printStackTrace();
        }
    }
}
```
the `connection.getInputStream()` does return after 10'' because of a read timeout, so this is the expected behaviour. However the flow waits for 60'' at `while ((inputLine = in.readLine()) != null) {`. 

I manually need to check if there is data to read by using `in.ready()` in order to get the desired behaviour. I would have thought that `connection.getInputStream()` would have thrown an IOException if there was an error with Ribbon. 

Of course it still works as expected if I add the timeout on the connection

```
connection.setConnectTimeout(10000);
connection.setReadTimeout(10000);
```

Does Ribbon throw an exception on timeout or it just returns an empty stream?

**Comment by HaoChou** [comment]
> Hello @girionis I have tried reproducing it and it did work the way you describe it in Postman, however, while using different http clients, I got the response straight away, which is why I would assume the issue is with Postman rather than with Feign/ Ribbon. Please try using a different http client, such as [httpie](https://httpie.org) and let me know if you still have any issues.

I got the same problem . I set the test url  to return in 3s,and set the read-timeout value 2s.
the timeout mechanism is work but the exception will be thrown after about 10s.
So i think the reason is that feign have already retried a lot of times.
and the Exception will throw after 2s which i expected after I set the retryer Retryer.NEVER_RETRY.
![image](https://user-images.githubusercontent.com/12935700/67551145-ca8e5480-f73a-11e9-8b5d-136fc5dd050c.png)
