### ISSUE TITLE
Spring Cloud Eureka Cluster Setup in AWS using DNS based Elastic Network Interface (ENI)

### ISSUE THREAD

**Issue by asakchris** [spring-cloud/spring-cloud-netflix#3229]
Spring cloud eureka cluster setup in AWS using ENI is not working as expected. Available replica is always blank. Please refer [this](https://stackoverflow.com/questions/52749745/spring-cloud-eureka-cluster-setup-in-aws-using-dns-based-elastic-network-interfa) stackoverflow link for more details. Could you take a look and let me know if I am missing anything?
I expect eureka server to be attached against ENI by looking at DNS text record, but it always attach against local host name. I believe, this could be an issue in eureka server.

**Comment by ryanjbaxter** [comment]
Handling in SO

**Comment by asakchris** [comment]
@ryanjbaxter Ryan, sorry, I didn't get you, what do you mean by handling in SO?
