### ISSUE TITLE
ZuulProperties dynamiclly update problem

### ISSUE THREAD

**Issue by arebya** [spring-cloud/spring-cloud-netflix#3230]
In my case ,I want to dynamicly delete some zuul.routes config properties。
When I use the EnvironmentChangeEvent to trigger ZuulProperties rebinding,I  got the unexpected result .  The deleted routes are always there,which is shown by  requesting /admin/routes ，but the changes happen immediately when requesting /admin/env .

I wonder if DataBinder has some bug to process this "delete property "case .

Another problem:the registed handlermapping is always there even if  the related route is deleted.

Spring Boot version:1.5.7.REALEASE

Spring Cloud Netflix Core version :1.3.5.REALEASE

Spring Framework version: 4.3.11.REALEASE

**Comment by ryanjbaxter** [comment]
Duplicates #705
