### ISSUE TITLE
ReadTimeout on RibbonClient (spring boot application)

### ISSUE THREAD

**Issue by samo717** [spring-cloud/spring-cloud-netflix#3231]
Let's have a really simple demo application (say-hello) from ribbon tutorial:
https://spring.io/guides/gs/client-side-load-balancing/

I just want to ask how is it possible to specify request readTimeout (request takes longer than specified threshold)? According to the ribbon documentation it should be done in file application.properties using syntax:
`<clientName>.ribbon.ReadTimeout=3000`
or for all ribbon clients:
`<clientName>.ribbon.ReadTimeout=3000`
But it seems, that readTimeout threshold is not used.

As I tried to find any other solution I found, that readTimeout can be set during RestTemplate initialization, for example:
```java
@LoadBalanced
@Bean
RestTemplate restTemplate(RestTemplateBuilder restTemplateBuilder) {
    return restTemplateBuilder
        .setReadTimeout(2000)
        .build();
}
```
But I am still wondering why thresholds from application.properties were not taken into account. Is it a bug or the problem is somewhere else? It would be more comfortable and straightforward to be able to set in application.properties.

**Comment by ryanjbaxter** [comment]
That should work.  How are you testing the timeout?

**Comment by samo717** [comment]
I set readTimeout (in application.yml - user application) to 3000:
```
say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9999
    ServerListRefreshInterval: 15000
    ReadTimeout: 3000
```
After that I modified SayHelloApplication.java and put sleep(30000), to simulate long running query. And then just called /hi rest service of UserApplication. Requests were not timeouted, but took 30s.

**Comment by OlgaMaciaszek** [comment]
Hello @samo717 this property does not work for rest-template based client, as the Ribbon client is not used underneath. There are some ribbon properties that work, as described in the docs: https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html , but this is not one of them. So it does not work, but it's by desing.
