### ISSUE TITLE
ZuulRefreshListener triggers refresh for *every* ContextRefreshedEvent

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#3232]
`ZuulRefreshListener` triggers a route refresh for *every* `ContextRefreshedEvent` including when they come from Ribbon contexts when they are created.
My understanding is the routes need refreshing only when the _top level_ context is refreshed but is useless for child contexts (like Ribbon contexts).

See following code for more information: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration.java#L243-L250

**Comment by spencergibb** [comment]
I think this could be done by checking if the application context from the event is the same as the listener.

PRs welcome.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
