### ISSUE TITLE
Resin Zuul FormBodyWrapperFilter HttpServletRequestWrapper.req field not found

### ISSUE THREAD

**Issue by kailbin** [spring-cloud/spring-cloud-netflix#3233]
when [FormBodyWrapperFilter.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/FormBodyWrapperFilter.java) run in **Resin**，
`this.requestField = ReflectionUtils.findField(HttpServletRequestWrapper.class, "req", HttpServletRequest.class);` and `this.servletRequestField = ReflectionUtils.findField(ServletRequestWrapper.class,"request", ServletRequest.class);` will return `null`。

FormBodyWrapperFilter cannot be initialized。

How do I solve this problem?

Resin servlet-api
```
package javax.servlet;

public class ServletRequestWrapper implements ServletRequest {
    private ServletRequest _request;
  ...
}
```

**Comment by ryanjbaxter** [comment]
I have never used Resin before.  I have the server running and placed a war which uses zuul in the `/webapps` directory.  It appears to explode the war
```
[18-10-24 20:43:33.351] {resin-43} WebApp[production/webapp/default/demo-0.0.1-SNAPSHOT,STARTING] 1 Spring WebApplicationInitializers detected on classpath
[18-10-24 20:43:33.354] {resin-43} WebApp[production/webapp/default/demo-0.0.1-SNAPSHOT] active
```
but when I got to localhost:8080/demo-0.0.1-SNAPSHOT/httpbin/get I get
```
/demo-0.0.1-SNAPSHOT/httpbin/get was not found on this server.
```

Is there something I am missing?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by giantoneday** [comment]
Developers can fix this problem like this: https://github.com/spring-cloud/spring-cloud-netflix/issues/3412
