### ISSUE TITLE
different custom configurations for multiple feign clients support issue

### ISSUE THREAD

**Issue by zzusunwei** [spring-cloud/spring-cloud-netflix#3234]
**Question:** 
For  handler one content-type(txt/plain) with two kind of response body (xml and json), we build two configurations like below:
```java 
public class WeChatPayServiceFeignClientConfig {
	@Bean(name = "weChatPayDecoder")
	public Decoder weChatPayDecoder() {
		return new WeChatPayDecoder();
	}
}
```
and 
```java
public class WeChatMiniAppUserServiceFeignClientConfig {
	@Bean(name = "miniAppUserDecoder")
	public Decoder miniAppUserDecoder() {
		return new MiniAppUserDecoder();
	}
}
````
It works well after build runable jar in windows, but the HystrixRuntimeException will be happen after I build it in linux and Mac, core error message like below:

feign.codec.DecodeException: Could not extract response: no suitable HttpMessageConverter found for response type [class com.hehe.washTruck.wechat.miniapp.model.WxMiniAppJscode2SessionResult] and content type [text/plain]

we have the seem JDK and mvn like below:
JDK:
```shell
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

```
MAVEN：
'''shell
Maven home: D:\michael\dev_app\maven\apache-maven-3.5.4\bin..
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: D:\michael\dev_app\java\jdk1.8.0_181\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
'''
the spring-boot version is 1.5.10.RELEASE
and the spring-cloud version is Brixton.SR5

experiment:
The  issue also will be happen when I remove the configuration flag in @FeignClient in window

**Comment by ryanjbaxter** [comment]
Please open an issue in the correct repo https://github.com/spring-cloud/spring-cloud-openfeign

You should use either Edgware.SR5 or Finchley.SR1.

Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).
