### ISSUE TITLE
OutOfMemoryError when uploading binary files in quick succession

### ISSUE THREAD

**Issue by bericoberin** [spring-cloud/spring-cloud-netflix#3236]
We are using spring-cloud-starter-netflix-zuul Edgware.SR2 to build our gateway for our application, and ran in to a problem with Zuul between our Extract/Transform/Load (ETL) tool and our blob storage service.

The problem is that we are loading ~9000 files that are around 10-35 MB in size as quickly as our infrastructure will allow.  When we test direct against the blob storage service, we are able to handle a much larger volume.

The critical part of the stack trace is here (the actual service is on a disconnected network, so the line numbers might be off):

    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at com.netflix.zuul.http.HttpServletRequestWrapper.parseRequest(HttpServletRequestWrapper.java:151)

The disconcerting thing is that it appears that Zuul is reading in the full content of the request in memory before sending the request on to it's final destination.  Our work around for now is to communicate directly with our blob storage service, bypassing Zuul for the moment.  However, that should not be necessary, and is a short term solution.

Further compounding this, it appears the request is closed out before reaching the blob storage service, which has to deal with a slow file system as a temporary workaround until our client is cloud enabled.  Those requests take time to process, so the old request hasn't cleared from memory before we send our next request.

We have a system coming up that we have to support that will need to handle hundreds of files that are up to 500 MB in size.  That means we need the requests to be streamed from one end to the other.  Even a couple files can easily blow the memory ceiling for Zuul.  These are not multipart/form uploads, but straight binary uploads to a rest endpoint.

We need to have at least some of our requests to be forwarded in-line with all the slowness that's in the microservice behind the Zuul proxy, and simply stream those requests without reading them all the way in memory at once.

**Comment by spencergibb** [comment]
Are you following the suggestions here? http://cloud.spring.io/spring-cloud-static/Edgware.SR5/single/spring-cloud.html#_uploading_files_through_zuul

**Comment by bericoberin** [comment]
We will try that and respond hopefully by tomorrow.

**Comment by bericoberin** [comment]
OK, that did work.  It saved a lot of memory and it was about 12% faster to upload all the files we had.

My question back is why is Zuul still going through the Spring RequestDispatcher at all?  Zuul is a critical piece of infrastructure that proxies all kinds of requests.  If there's a known path that causes memory problems and is slower, then that's a good argument to not use that code.

**Comment by spencergibb** [comment]
There may be other controllers and actuator that might be swallowed depending on the zuul configuration. It's likely more about buffering than request dispatcher as the servlet one is not buffered and the other one is.
