### ISSUE TITLE
Does spring cloud operate under SSL with random ports, server.port:0

### ISSUE THREAD

**Issue by HeavenlyHost** [spring-cloud/spring-cloud-netflix#3243]
I am having a problem with a spring application registering with Eureka when it is configured to use SSL and random ports.

I have a config server, Eureka server, proxy server of which all are working with Eureka on SSL, although they are using fixed ports.

The fourth application is registered with Eureka but with port 0, even though I have set it with the standard random allocation method, i.e. Server.Port: 0.

When using this method on http it works and the port is randomly assigned, but using HTTPS not working, always assigns with port 0. Any ideas ?

**Comment by ryanjbaxter** [comment]
> but using HTTPS not working, always assigns with port 0.

Can you elaborate on what this means?

**Comment by HeavenlyHost** [comment]
Ok, so when I do not use HTTPS and set port to zero the application automatically assign the next available port. When I provide the options for secure port etc, enabling HTTPS and set port to 0 then it will register with Eureka on port 0 Not an auto assigned port.

**Comment by spencergibb** [comment]
I don't believe it gets registered with 0, but shows in the instanceid or url you see. But if you look at `/eureka/apps` the secure port is shown.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
