### ISSUE TITLE
Sleuth HeaderBasedMessagingInjector not getting called when zuul.routes configured in gateway

### ISSUE THREAD

**Issue by sbogadhi** [spring-cloud/spring-cloud-netflix#3248]
I have configured the Custom class implementing the HeaderBasedMessagingInjector  to customize the span to include username & proxying specific URL matching requests to external service. 

public class CustomSpanInjector extends HeaderBasedMessagingInjector {
	@Override
	public void inject(Span span, SpanTextMap carrier) {
           // Customize the span object
        }
}
The problem is custom HeaderBasedMessagingInjector  is not getting called before the request is forwared to zuul filter.

**Comment by ryanjbaxter** [comment]
I suggest you open the issue in Spring Cloud Sleuth https://github.com/spring-cloud/spring-cloud-sleuth
