### ISSUE TITLE
Documentation: using Ribbon without Eureka may require extra configuration (ribbon.eureka.enabled=false)

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#325]
The chapter in the documentation describing how to use Ribbon without Eureka makes the assumption Eureka is *NOT* on the classpath - hence the `RibbonEurekaAutoConfiguration` is not triggered. 

However, it might be interesting to say the Ribbon/Eureka integration can be explicitly disabled using the property:

    ribbon.eureka.enabled = false

The example given in the documentation won't work if that property is not specified and Eureka is available on the classpath (even if disabled by `eureka.instance.enabled=false`).

The same is true for people who want to configure Zuul with a static list of servers as described in the "Embedded Zuul Reverse Proxy'. The following example won't work out of the box:

    zuul:
      routes:
        users:
          path: /myusers/**
          serviceId: users
    
     users:
      ribbon:
        listOfServers: example.com,google.com

Since Eureka is included in the Zuul packaging, the integration with Ribbon must be disabled explicitly. The example should be:

     zuul:
      routes:
        users:
          path: /myusers/**
          serviceId: users
    
     ribbon:
       eureka:
        enabled: false
    
     users:
      ribbon:
        listOfServers: example.com,google.com

**Comment by spencergibb** [comment]
I don't want to disable ribbon completely, because there could be a situation where some paths use eureka, and others don't.

**Comment by spencergibb** [comment]
So it takes code, but it is possible
```
@SpringCloudApplication
@RibbonClients({
		@RibbonClient(name = "users", configuration = UserConfig.class)
})
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(SidecarApplication.class, args);
	}

	@Configuration
	static class UserConfig {

		private String name = "users";

		@Bean
		@ConditionalOnMissingBean
		public IClientConfig ribbonClientConfig() {
			DefaultClientConfigImpl config = new DefaultClientConfigImpl();
			config.loadProperties(this.name);
			return config;
		}

		@Bean
		ServerList<Server> ribbonServerList(IClientConfig config) {
			ConfigurationBasedServerList serverList = new ConfigurationBasedServerList();
			serverList.initWithNiwsConfig(config);
			return serverList;
		}

	}
}
```

**Comment by brenuart** [comment]
Indeed. Using the `ribbon.eureka.enabled=false` property would disable Eureka for every Ribbon instance - this is true. And currently, the only way to have it "per service" is using a custom configuration per-service as you described here above. I was even wondering if such configuration couldn't be triggered by the presence of the `ribbon.listOfServers` property... Do you think it is worth creating another issue to host that feature?

However, my point was that the examples given in the documentation are not complete enough and will not work out of the box - especially the last one for Zuul and the statically registered routes. Don't forget that Ribbon will be integrated with Eureka by default within Zuul - so a `DiscoveryEnabledNIWSServerList` server list will be used and not a `ConfigurationBasedServerList`. The former will not consume the `ribbon.listOfServers` property.

**Comment by spencergibb** [comment]
@brenuart Another issue for per service eureka or not would be nice.  I'll update the docs, since it doesn't work as it is.  I think it used to before we changed to `@RibbonClients`.

**Comment by matzegebbe** [comment]
can i create this part:

```
 users:
  ribbon:
    listOfServers: example.com,google.com
```
dynamically in my source code? The listOfServers depends on database configuration.

**Comment by ryanjbaxter** [comment]
@matzegebbe I believe you can return a bean of type `ServerList<Server` with the list of servers.

**Comment by shengnian** [comment]
@matzegebbe Have you solved this problem?  How to read listOfServers from database and can be dynamically to reload. thanks!

**Comment by ryanjbaxter** [comment]
@shengnian this issue was closed a while ago, if you are still having a problem open another issue with a description of your issue and a sample to reproduce it
