### ISSUE TITLE
Netflix/ zuul ignores DELETE request body

### ISSUE THREAD

**Issue by raju4392000** [spring-cloud/spring-cloud-netflix#3251]
Hello,
Does anyone faced the below error?
we are using Netflix/ Zuul versions
"com.netflix.zuul:zuul-core:1.3.1"
"com.netflix.zuul:zuul-netflix:1.3.1"

and the piece of backend code behind the zuul is

@RequestMapping(value = "/deletewithbodytest", method = DELETE)
@ResponseBody
public Response delete(@RequestBody String requestString) {
    return Response.ok(requestString).build();
}
Body I was passing : -d '{"someval":1}'

Below is the error I was getting:
{"errors":[],"statusCode":500,"header":null,"id":null,"status":"Failed","errorMessages":["Required request body is missing: public javax.ws.rs.core.Response

Is there any solution for zuul-netflix?
spring-cloud-netflix has this fix in 1.2.0 and below is the issue created
spring-cloud/spring-cloud-netflix#949

**Comment by spencergibb** [comment]
This is not the repo for upstream Netflix zuul. Only spring cloud Netflix zuul
