### ISSUE TITLE
zuul, ctx.setRouteHost to change my  full URL doesn‘t work

### ISSUE THREAD

**Issue by gyb123456** [spring-cloud/spring-cloud-netflix#3252]
Question-----------------
when i use zuul to change my  full URL, i used ctx.setRouteHost(url), but it doesn‘t work
No matter what is set, it is invalid.

its my version------------
 spring-boot-starter-parent
<version>2.0.6.RELEASE</version>
<spring-cloud.version>Finchley.SR2</spring-cloud.version>

mycode----------------------
```
package com.example.zuuldemo.zuul;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;
import com.netflix.zuul.exception.ZuulException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cloud.netflix.zuul.filters.support.FilterConstants;
import org.springframework.stereotype.Component;

import java.net.URL;

/**
 * zuul的过滤器，filterType设为PRE_TYPE了，可以更改转发的ip
 * 20181025
 */
@Component
public class MyPreZuulFilter extends ZuulFilter {
    private static Logger log = LoggerFactory.getLogger(MyPreZuulFilter.class);

    @Override
    public boolean shouldFilter() {
        return true;
    }

    /**
     * @return
     * @throws ZuulException
     */
    @Override
    public Object run() throws ZuulException {
        RequestContext ctx = RequestContext.getCurrentContext();
        try {
            ctx.setRouteHost(new URL("http://192.168.0.243"));
            System.out.println("url change to：" +ctx.getRouteHost().getHost());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public String filterType() {
        return FilterConstants.PRE_TYPE;
    }

    @Override
    public int filterOrder() {
        return FilterConstants.PRE_DECORATION_FILTER_ORDER - 1;
    }
}
```

**Comment by gyb123456** [comment]
Thank you for request!  
I want change the full URL, like this 
```localhost:8080/test/aaa  ---> http://192.168.0.243/test/aaa```
So i use  ``` ctx.setRouteHost(new URL("http://192.168.0.243"))```
and I had set filterType with  FilterConstants.PRE_TYPE 
but it doesn't work , it looks like useless and if i set <ctx.setRouteHost> to anything
such as
```ctx.setRouteHost(new URL("http://anything"))```
there‘s no any error report,this setting looks like useless, i don't know why?
My english is not good, can U understand my question?

**Comment by ryanjbaxter** [comment]
Have you tried a filter type of `route`?
