### ISSUE TITLE
HystrixConcurrencyStrategy not obtain from  HystrixPlugins#getConcurrencyStrategy()

### ISSUE THREAD

**Issue by ailinzhou** [spring-cloud/spring-cloud-netflix#3256]
https://github.com/spring-cloud/spring-cloud-netflix/blob/6859b7a83588f33c8a946de40cfbab0917de3d05/spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java#L45-L46

``HystrixConcurrencyStrategy`` has no relation with Spring Container, and if someone registered via HystrixPlugins, **the following rest in init method  will drop an existing strategy**.
I  also  confused ： if we should inject a ``HystrixConcurrencyStrategy``  in Spring Container。

**Comment by ryanjbaxter** [comment]
`SecurityContextConcurrencyStrategy` is what we configure

**Comment by ailinzhou** [comment]
It seems that Hystrix shared HystrixConcurrencyStrategy between all Hystrix Command. In our are application, we registed a ConcurrencyStrategy by HystrixPlugin wrapp the callable for Some purposes. the follow code made the wrapCallable logic lost. 
https://github.com/spring-cloud/spring-cloud-netflix/blob/6859b7a83588f33c8a946de40cfbab0917de3d05/spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java#L51-L68

So, is that possible in ``HystrixSecurityAutoConfiguration.java`` the HystrixConcurrencyStrategy in com.netflix.hystrix.strategy.HystrixPlugins#getConcurrencyStrategy**  also be considered.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ailinzhou** [comment]
Thank you for your reply @ryanjbaxter .
A demo.zip file was attached. 
When I run com.test.demo.DemoApplicationTests#whitShareSecurityContext  with **hystrix.shareSecurityContext=true** in application.properties the test failed, And if set **hystrix.shareSecurityContext=false** test will pass.
[demo.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/2541972/demo.zip)

**Comment by ryanjbaxter** [comment]
Why cant you create a bean for your `HystrixConcurrencyStategy`?

**Comment by ryanjbaxter** [comment]
I suppose you could do that.  But I am still not clear as to why you need to set it via `HystrixPlugins`.

**Comment by ailinzhou** [comment]
Thank you very much @ryanjbaxter  I will do it. 
We imported a Jar and it has the logic with set it via HystrixPlugins.

**Comment by ryanjbaxter** [comment]
If you want us to support it feel free to submit a PR

**Comment by ailinzhou** [comment]
PR #3276 was submitted.

**Comment by ryanjbaxter** [comment]
Closed via 6b74554
