### ISSUE TITLE
ClassNotFoundException: OAuth2RestOperations

### ISSUE THREAD

**Issue by maxiwu** [spring-cloud/spring-cloud-netflix#3265]
I have a Zuul gateway which just dispatch request to other services using Eureka.
With just application.yml
It works just fine. Then I want to add OAuth2 uaa to my Zuul gateway.

I add spring-cloud-security dependency to my project. version Edgware.SR4.
add annotation @EnableOAuth2Sso. Add OAuth settings to my application.yml.

It builds ok. but gives me ClassNotFoundException of the class  OAuth2RestOperations at runtime.
I think this may caused by incorrect dependency.

What dependency do I need to add OAuth ability to my Zuul on version Edgware SR4?

**Comment by ryanjbaxter** [comment]
This question should be asked in spring-cloud-security.
