### ISSUE TITLE
Failed to introspect Class [org.springframework.cloud.netflix.hystrix.HystrixAutoConfiguration] from ClassLoader 

### ISSUE THREAD

**Issue by bnmyni** [spring-cloud/spring-cloud-netflix#3272]
从maven repository上下载的spring-cloud-netflix-core-2.0.X.RELEASE.jar包反编译(decompiler)后org.springframework.cloud.netflix.hystrix.HystrixAutoConfiguration.class 文件内容为// INTERNAL ERROR // 
![default](https://user-images.githubusercontent.com/10651585/48340198-fab52280-e6a4-11e8-8424-0c3186578ede.png)

**Comment by ryanjbaxter** [comment]
Not sure what the problem is
