### ISSUE TITLE
Zuul: Hystrix prop names do not follow Ribbon conventions

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#329]
According to Netflix's documentation (https://github.com/Netflix/Hystrix/wiki/Configuration#intro), Hystrix properties can be specified a two levels:

````
# Global default
hystrix.command.default.<property name> =<value>

# Instance (or service) level
hystrix.command.<command key>.<property name> = <value>
```

One may think \<command key> should be replaced by the service name and is therefore tempted to write:
```
hystrix.command.myservice.execution.isolation.strategy = THREAD
````

Unfortunately, the \<command key> is actually composed of **\<service name>RibbonCommand**. The correct property should therefore be:
```
# Per service (name: myservice) 
hystrix.command.myserviceRibbonCommand.execution.isolation.strategy = THREAD
``` 

Having to add the *RibbonCommand* suffix to the service name is rather confusing especially if we consider that Ribbon (often used together with Hystrix) does follow a similar approach (although reversed) where properties can be set per service by simply adding the **service name** as prefix:
```
# Global
ribbon.MaxTotalHttpConnections = 200

# Per service
<service name>.ribbon.MaxTotalHttpConnections = 10
```

It would be nice if Zuul followed Netflix's recommendations wrt the Hystrix property names. It would also be more consistent wrt to how Ribbon is configured in the same environment.

As far as I can tell, this could be done by simply changing how the command name (key) is constructed in `org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand`.

**Comment by dsyer** [comment]
I don't see the problem really. Is it just documentation essentially?

**Comment by brenuart** [comment]
Suppose my *myservice* requires custom settings for both Hystrix and Ribbon. Here is how it would look like:

```
# Hystrix
hystrix.command.myserviceRibbonCommand.execution.isolation.strategy = THREAD

# Ribbon
myservice.ribbon.MaxTotalHttpConnections = 10
````

From a user point of view, it would be nice if the same convention is used everywhere. Currently, I have to remember to add *RibbonCommand* to the service name for the Hystrix property, but not for Ribbon. And this, only for Zuul, because when Hystrix is used elsewhere, like inside my own app, then the command key is the service name (without the *RibbonCommand* suffix) - so the same property should be written differently.

Now, if you look at the Zuul metrics, the refer to the service name (without the *RibbonCommand* suffix):
```
gauge.hystrix.HystrixCommand.RibbonCommand.myservice.0: 0,
gauge.hystrix.HystrixCommand.RibbonCommand.myservice.100: 0,
gauge.hystrix.HystrixCommand.RibbonCommand.myservice.25: 0,
```

See what I mean? To summarise:
- I propose to remove the *RibbonCommand* suffix from the Hystrix command key
- and yes, from a documentation point of view, it would be nice to say something about it.

(sorry for my english, it is sometimes hard for me to express things clearly ;-)
