### ISSUE TITLE
Eureka client no longer registers proper port when server.port set to random (ie 0)

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#3294]
See https://stackoverflow.com/questions/53491970/eureka-not-able-to-find-port-when-running-microservices-on-random-port

**Comment by spencergibb** [comment]
It's due to changes in initialization sequence caused by upstream changes, either in boot or framework. I have fixes here and in commons. Looking to create a test now.

**Comment by spencergibb** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-commons/issues/451

**Comment by amaykumar** [comment]
Hi, I am using spring-cloud-starter-netflix-eureka-client (v 2.1.0.RELEASE), but am still facing issue with Eureka registry when using random port.  What could be wrong?

**Comment by ryanjbaxter** [comment]
Please open a separate issue and provide a sample

**Comment by amao12580** [comment]
spring-cloud-starter-netflix-eureka-client (v 2.1.1.RELEASE)

the problem still there.

**Comment by Gorbush** [comment]
Same issue.  Spring-boot-starter-parent 2.1.10.release
Netflix-dependencies 2.1.4.release
Cloud-dependencies Greenwich.sr4

**Comment by jmglluch** [comment]
Same issue with these combinations:

Spring-boot-starter-parent 2.1.12.release
Netflix-dependencies 2.1.5.release
Cloud-dependencies Greenwich.SR5

Spring-boot-starter-parent 2.2.4.release
Netflix-dependencies 2.2.1.release
Cloud-dependencies Hoxton.SR1

**Comment by kleenxcoder** [comment]
Same issue with these combinations:

spring-boot-starter-parent: 2.3.1.RELEASE
spring-cloud-starter-netflix-eureka-server: 2.2.3.RELEASE
spring-cloud: Hoxton.SR6

spring-boot-starter-parent: 2.3.1.RELEASE
spring-cloud-netflix-eureka-client: 2.2.3.RELEASE.jar
spring-cloud.version: Hoxton.SR6

**Comment by kleenxcoder** [comment]
Seems like this is not an issue and works as designed. A newly created issue was closed https://github.com/spring-cloud/spring-cloud-netflix/issues/3833.  My solution/workaround is setting eureka instance-id manually
`
eureka.instance.instanceId=${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
`
