### ISSUE TITLE
Hystrix Dashboard javascript error

### ISSUE THREAD

**Issue by kmandeville** [spring-cloud/spring-cloud-netflix#330]
FYI I'm having a problem with the hystrix dashboard in my Spring Boot 1.2.3 app (using 1.0.1.RELEASE of hystrix dashboard. The page loads, but the Monitor Stream button doesn't actually do anything. If I open the javascript console I see the following error:

[Error] ReferenceError: Can't find variable: $
sendToMonitor (hystrix, line 14)
onclick (hystrix, line 50)

If I go direct to the hystrix.stream url, I see data and it's consistently streaming. Just seems like a javascript issue... please help!

**Comment by spencergibb** [comment]
@kmandeville I am unable to reproduce using [1.0.1.RELEASE of the sample hystrix dashboard](https://github.com/spring-cloud-samples/hystrix-dashboard/tree/1.0.1.RELEASE).  Can you provide a sample project that recreates the problem?

**Comment by kmandeville** [comment]
OK I will see if I can do that. I am using @EnableHystrixDashboard in
my Spring Boot app so I'm thinking that some mapping I have for my app
must be interfering. I ran the latest hystrix dashboard as a
standalone app and it works perfectly there. I will see if I can
reproduce it in a small sample app

**Comment by kmandeville** [comment]
Ok you can close this issue. I wasn't able to reproduce it with a sample app so I went back and looked at my app. I had created a customer Configuration class where I was trying to add in a custom mime type to the ContentNegotiationConfigurer. If I comment that out, it works as expected. Sorry for wasting your time.

**Comment by spencergibb** [comment]
@kmandeville no worries.  Not a waste of time.  We appreciate the feedback.  We can't anticipate all use cases.  Thanks for taking the time to go back and investigate.
