### ISSUE TITLE
Greenwich.M3 ribbon retry does not work ,but feign use ribbon retry works

### ISSUE THREAD

**Issue by lyplyp** [spring-cloud/spring-cloud-netflix#3303]
```
cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
  #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #RoundRobinRule 
  ConnectTimeout: 250
  ReadTimeout: 250
  OkToRetryOnAllOperations: true 
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1 

logging:
  level:
    org.springframework: debug
```
The log shows that retry is not triggered when the request response time is greater than the retry. ReadTimeout value. But when I use feign requests, configuring retry. ReadTimeout triggers retry

```
2018-12-04 16:37:31.216 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : Response 200 OK
2018-12-04 16:37:31.216 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : Reading to [com.lyp.consumer.pojo.User]
getUserById duration : 1788
getUser2方法异常，超时熔断!
2018-12-04 16:37:32.065 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : HTTP GET http://user-service/user-service/getUser?id=4
2018-12-04 16:37:32.065 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2018-12-04 16:37:32.065 DEBUG 338500 --- [nsumerService-9] o.s.retry.support.RetryTemplate          : Retry: count=0
2018-12-04 16:37:32.223 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : Response 200 OK
2018-12-04 16:37:32.223 DEBUG 338500 --- [nsumerService-9] o.s.web.client.RestTemplate              : Reading to [com.lyp.consumer.pojo.User]
```

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by lyplyp** [comment]
https://github.com/lyplyp/spring-cloud-demo/tree/master/springboot-user-consumer

**Comment by spencergibb** [comment]
You do not have `spring-retry` on the classpath. In fact, the sample you pointed to isn't a spring cloud sample at all.

**Comment by lyplyp** [comment]
<dependency>
	<groupId>org.springframework.retry</groupId>
	<artifactId>spring-retry</artifactId>
</dependency>

spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true

user-service:
  ribbon:
    ConnectTimeout: 250 
    ReadTimeout: 250 
    OkToRetryOnAllOperations: true 
    MaxAutoRetriesNextServer: 2 
    MaxAutoRetries: 1

The POM file introduces spring-retry, the configuration in YML opens retry, and configures the parameters related to ribbon（ConnectTimeout,ReadTimeout...）. Is there a problem with my configuration?

**Comment by lyplyp** [comment]
DefaultHttpRequestRetryHandler does not retry for connection timeouts and data acquisition timeouts. Do you need to customize the retry policy? Do you need to customize the retry policy to take effect when invoked?

Thank you for your busy reply.

**Comment by spencergibb** [comment]
DefaultHttpRequestRetryHandler is an Apache http client class. I'm afraid if you can't point us to the spot in your project where exactly you're having problems we won't be able to help you.

**Comment by lyplyp** [comment]
USER-CONSUMER
@SpringBootApplication
@EnableDiscoveryClient
@EnableHystrix
public class UserConsumerApplication {

    @Bean
    **@LoadBalanced**
    public RestTemplate restTemplate(){
        return new RestTemplate();
    }

    public static void main(String[] args) {
        SpringApplication.run(UserConsumerApplication.class, args);
    }
}

@Service
public class UserConsumerService {
    @Autowired
    private RestTemplate restTemplate;

    @HystrixCommand(fallbackMethod = "getUserByIdFallback")
    public User getUserById(Long id){
        String url = "http://user-service/user-service/getUser?id=" + id;
        Long start = System.currentTimeMillis();
        User user = **restTemplate**.getForObject(url,User.class);
        Long end = System.currentTimeMillis();
        System.out.println("getUserById duration : " + (end - start));
        return user;
    }
}
yml
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
user-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 250 
    OkToRetryOnAllOperations: true 
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000

USER-SERVICE

@RestController
@RequestMapping("/user-service")
public class UserController {
    @Autowired
    private UserService userService;

    @GetMapping("/getUser")
    public User getUser(Long id) {
        int sleep = new Random().nextInt(2000);
        System.out.println("user-service1 get /user-service/getUser......");
        System.out.println("sleep : " + sleep);
        try {
            TimeUnit.MILLISECONDS.sleep(sleep);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return this.userService.getById(id);
    }
}
The getUser interface in user-service sets a random timeout of 1-2000ms, and retry.ReadTimeout = 250 in user-consumer Using restTemplate(@LoadBalanced) to call the getUser method of user-service, you want to see retry when the delay exceeds 250ms, but the test effect is that retry is not triggered even if the delay exceeds 250ms.

**Comment by ryanjbaxter** [comment]
>  I'm afraid if you can't point us to the spot in your project where exactly you're having problems we won't be able to help you.

**Comment by spencergibb** [comment]
If you can provide instructions on how to recreate the problem with your project I will reopen.
