### ISSUE TITLE
Race condition with SimpleHostRoutingFilter.httpClient

### ISSUE THREAD

**Issue by jadetang** [spring-cloud/spring-cloud-netflix#3311]
Hello, we use Zuul in production. After reading the source code, I find that on the `onPropertyChange` method of `SimpleHostRoutingFilter`, the code will try to update the http client which will introduce a write/read race condition. Should be put a read lock before getting the client and put a write lock before updating the client?

```
@Deprecated
	public void onPropertyChange(EnvironmentChangeEvent event) {
		if(!customHttpClient) {
			boolean createNewClient = false;
			for (String key : event.getKeys()) {
				if (key.startsWith("zuul.host.")) {
					createNewClient = true;
					break;
				}
			}
			if (createNewClient) {
				try {
					SimpleHostRoutingFilter.this.httpClient.close();
				} catch (IOException ex) {
					log.error("error closing client", ex);
				}
				SimpleHostRoutingFilter.this.httpClient = newClient();
			}
		}
	}
```

**Comment by spencergibb** [comment]
Are you seeing a problem? How about a test that fails?

**Comment by jadetang** [comment]
didnt see a problem so far, but this read and write conflict is very easy
to reason about, isnt it?

best regards
Sicheng

Spencer Gibb <notifications@github.com> 于 2018年12月10日周一 03:30写道：

**Comment by ryanjbaxter** [comment]
Because the client might be in use?

**Comment by spencergibb** [comment]
Would be a simple change to use `AtomicReference`. Then I don't think there'd be any problems. PR?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by jadetang** [comment]
> Would be a simple change to use `AtomicReference`. Then I don't think there'd be any problems. PR?

I checked the Java document these days. I don't think this is a bug. Yes, I do know that the JVM memory model doesn't guarantee the read and write consistency on an object reference without `violate` key word, however this is fine in this case. After all, you don't have strict consistency when refreshing the spring context on multiple instances of Zuul and the code will close the old client before creating a new one. 
So, I think we can close this ticket.
