### ISSUE TITLE
Question: Why is the health check showing UP status when it cannot connect to the eureka server at all ?

### ISSUE THREAD

**Issue by radtriste** [spring-cloud/spring-cloud-netflix#3313]
Hello,

I would like to understand what was the reason to show an "UP" status when the eureka client cannot connect to the Eureka server. 
Was there any discussion about that I missed (could not find ...)?

In [EurekaHealthIndicator](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaHealthIndicator.java):
`if (lastFetch < 0) {
	status = new Status("UP","Eureka discovery client has not yet successfully connected to a Eureka server");
}`

For me the service should be down if we totally could not fetch anything from the server. The application cannot be used fully in that case...
Or is there a fail-fast option (no from Spring Cloud Config) that I am missing ?

I could still override it but maybe there is a good reason behind that piece of code.

**Comment by ryanjbaxter** [comment]
This is a matter of opinion I think.

One could make the argument that if the Eureka server is having problems, that does not indicate that the client application is not healthy.

**Comment by spencergibb** [comment]
I agree with Ryan. Maybe a case could be made for `UNKNOWN` since it doesn't know at that particular condition.

**Comment by radtriste** [comment]
ok. Thanks for the answers.
I will check with my guys to decide the behavior we should adopt on our systems.
