### ISSUE TITLE
Connection Refused on Linux but not in Windows

### ISSUE THREAD

**Issue by g4biru** [spring-cloud/spring-cloud-netflix#3316]
Hello all, 

So, I'm trying to display the EUREKA server as an instance, registering the EUREKA itself, but I only get a "CONNECTION REFUSED" The problem is: On Windows works fine, EUREKA is displayed as an instance in EUREKA dash, but Linux does not work. The same project.

SDK 1.8

![eureka-delivery](https://user-images.githubusercontent.com/36507028/49860558-31d03e00-fde1-11e8-9ee8-e555b3f5c3f6.PNG)

I have a config server running on localhost:9090.

bootstrap.yml

![bootstrap](https://user-images.githubusercontent.com/36507028/49861084-35b09000-fde2-11e8-88fb-129d9257b68d.PNG)

![pom](https://user-images.githubusercontent.com/36507028/49861161-64c70180-fde2-11e8-9e7b-6ebae649fd8d.PNG)

Does anyone have any idea to solve it?

**Comment by spencergibb** [comment]
I don't know. It's likely a local networking problem.

**Comment by g4biru** [comment]
Well, I created a local repository and changed the ports 9090/9091 to 8080/8167 and now it works.
