### ISSUE TITLE
Document deprecated modules

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#3319]
See https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now#spring-cloud-netflix-projects-entering-maintenance-mode

**Comment by ryanjbaxter** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-netflix/commit/e219783d40e90428ad8a3580d1ab3debf7b15725
