### ISSUE TITLE
Zuul: SimpleHostRoutingFilter does not allow SSL connections

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#332]
The HTTP client in SimpleHostRoutingFilter does not allow SSL connections to proxied entities if the keystore and truststore is set using the javax.net.ssl system properties. The SSLContext is built using a custom SSLSocketFactory which provided no key or trust store information. It also uses deprecated API to build the HttpClient.

**Comment by spencergibb** [comment]
closed via f094ecfd889be7c22d26e939fa0650b6b6b3642e
