### ISSUE TITLE
ErrorDecoder doesn't work

### ISSUE THREAD

**Issue by lclmichael** [spring-cloud/spring-cloud-netflix#3320]
Hello, I can customize these components in Feign, such as **Contract**, **RequestInterceptor** in docs.

> Decoder feignDecoder: ResponseEntityDecoder (which wraps a SpringDecoder)
Encoder feignEncoder: SpringEncoder
Logger feignLogger: Slf4jLogger
Contract feignContract: SpringMvcContract
Feign.Builder feignBuilder: HystrixFeign.Builder

>Logger.Level
Retryer
ErrorDecoder
Request.Options
Collection<RequestInterceptor>

Then I want to config **ErrorDecoder** so that I can throw MyException.
But these code doesn't work. There is still **feign.RetryableException** when http_status != 200~

```
@Component
public class MyErrorDecoder implements ErrorDecoder {
    @Override
    public Exception decode(String methodKey, Response response) {
        if (response.status() != HttpStatus.OK.value()) {
            return new MyException();
        }
        return null;
    }
}
```

**Comment by spencergibb** [comment]
If you think there is a problem in `feign.RetryableException` you should open an issue in https://github.com/OpenFeign/feign

**Comment by lclmichael** [comment]
Thanks for reply. The problem is about MyErrorDecoder won't work。But the other componets like Contract, which configured same as that, could work in spring context.

**Comment by lclmichael** [comment]
> If you think there is a problem in `feign.RetryableException` you should open an issue in https://github.com/OpenFeign/feign

**Comment by lclmichael** [comment]
Emm... How to cutomize ErrorDecoder in spring-cloud-openfeign?
