### ISSUE TITLE
how can zuul get request parameter when content type is multipart/form-data?

### ISSUE THREAD

**Issue by bigzuo** [spring-cloud/spring-cloud-netflix#3324]
I need to upload file through zuul to my application, the content type is multipart/form-data, but I have some other parameters in the request. So how can I get the parameters in the zuul? I want to get the token to check the request is valid or not. THX. I tried "request.getParameter("token");",but it does not work.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
