### ISSUE TITLE
Document Update

### ISSUE THREAD

**Issue by holy12345** [spring-cloud/spring-cloud-netflix#3329]
Hi

I found that some of the content of the document is not up to date.
For example https://spring.io/projects/spring-cloud-netflix#overview (Getting Started section is old)

Thanks

**Comment by spencergibb** [comment]
What in particular?

**Comment by holy12345** [comment]
@spencergibb  Thanks for your quick reply : )

First:

`To run your own server use the spring-cloud-starter-eureka-server dependency and @EnableEurekaServer.`

I think it should be changed to `spring-cloud-starter-netflix-eureka-server `

Second:

```
@Configuration
@EnableAutoConfiguration
@EnableEurekaClient
@RestController
public class Application {
```

I think it should be changed to 

```
@SpringBootApplication
@EnableEurekaClient
@RestController
public class Application {
```

Make sense?

Thanks

**Comment by ryanjbaxter** [comment]
@holy12345 want to submit a PR?

**Comment by spencergibb** [comment]
I don't think it's PR-able with the updated version of sagan.

**Comment by ryanjbaxter** [comment]
Yeah, I thought it was somewhere else, should be fixed now.
