### ISSUE TITLE
Question: how can I make ZUUL to translate the requests to microservice?

### ISSUE THREAD

**Issue by valerian-ti** [spring-cloud/spring-cloud-netflix#3330]
Good day.
I have a microservice with MTLS, if we're accessing it via postman directly (with attached certificates) it responses ok. Without certificates attached it responses error. That's good, that's normal.

I need to made the same but with the help of ZUUL to contact via Gateway. How can I make it possible? 
I've read tons of materials and tried many things but unfortunately. I've tried the ZUUL filter (maybe wrong), 
the https://github.com/spring-cloud/spring-cloud-netflix/issues/2498 approach, but with the parts of that code it doesn't matter if I attached certificate or not.

I just need to translate the request to microservice, how can I do that?  
Somehow tells we can attach the headers of an certificate, but there seems no headers in request, or am I wrong? 

I am new to this, so I truly may be wrong

That's what postman sends
```
Client Certificate:
keyPath:"somepath\service.key"
pemPath:"somepath\service.crt"
Request Headers:
Content-Type:"application/json"
cache-control:"no-cache"
Postman-Token:"1f34622e-7d5d-44bc-a101-5fbcadeeba1e"
User-Agent:"PostmanRuntime/7.4.0"
Accept:"*/*"
Host:"localhost:8088"
cookie:"JSESSIONID=F1D78C5E5E6D46E5CACD91154B61C3CA"
accept-encoding:"gzip, deflate"
content-length:304
```

**Comment by ryanjbaxter** [comment]
Zuul by default will use the Apache Http Client to proxy the request downstream.  It requires the certificate used by the downstream service is known by the JVM.  If it’s not known then you need to install it into the jvm.

**Comment by ryanjbaxter** [comment]
The obvious solution is to use a certificate from a trusted authority.  We dont have any control over how the Apache HTTP client behaves.  You can also customize the Apache HTTP Client to change its behavior (do not validate certificates)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
