### ISSUE TITLE
spring-cloud-starter-netflix-zuul

### ISSUE THREAD

**Issue by marquisXuan** [spring-cloud/spring-cloud-netflix#3331]
# Question

### SpringBoot Version
2.1.1.RELEASE

### Spring Cloud dependencies Version
Finchley.RELEASE

### spring-cloud-starter-netflix-zuul Version
2.0.2.RELEASE

in org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration class at line 91 & 99, there is called a method: this.server.getServlet().getServletPrefix(), but in Class org.springframework.boot.autoconfigure.web.ServerProperties.Servlet ,there is no this method that named  getServletPrefix

**Comment by spencergibb** [comment]
Finchley is not compatible with boot 2.1.x. Either use 2.0.x or upgrade to Greenwich.RC1
