### ISSUE TITLE
forceOriginalQueryStringEncoding should be true by default

### ISSUE THREAD

**Issue by asarkar** [spring-cloud/spring-cloud-netflix#3334]
Having upgraded from spring-cloud-netflix-core:1.3.0.RELEASE to spring-cloud-netflix-zuul:2.1.0.M3, I found a regression issue where a query parameter `query=%2Btest` (that's a URL encoded `+`) was getting decoded to a `+` in `SimpleHostRoutingFilter`, and hence, the target service was receiving a space instead of the intended `+`.  After several hours of debugging, I found the flag `forceOriginalQueryStringEncoding`, which is also documented [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#query-string-encoding). However, the flag is set to `false` by default, which means the URL encoding is going to be invariably messed up unless I set it to `true`. This seems backward to me, since there's no reason for Zuul to not preserve the URL encoding, as its purpose in life is to forward the request to the target service. The decision to set this obscure flag to `false` by default is causing hard-to-find bugs in places least expected.

Please consider setting `forceOriginalQueryStringEncoding` to true by default, or otherwise explain in the docs why that's not a good idea.

**Comment by asarkar** [comment]
@spencergibb I couldn't find a tag for RC2 (the latest is Greenwich.M1) on GitHub, but [ZuulProperties.forceOriginalQueryStringEncoding](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/ZuulProperties.java#L118) is still `false`. Why do you think upgrading will fix this issue, unless, of course, the flag has been flipped and I can't find the code.

**Comment by spencergibb** [comment]
Need to fix that erroneous tag. 2.1.0.RC3 is the latest.
