### ISSUE TITLE
Zuul Proxy: How to configure Ribbon/Hystrix on end-point/route level instead of service level

### ISSUE THREAD

**Issue by Mr-James** [spring-cloud/spring-cloud-netflix#3340]
I have an `ft-admin` microservive which exposes 2 endpoints `app-config` and `app-analytic`. In my `@EnableZuulProxy` gateway project, I can define the routing rules and specify other configurations for Ribbon and Hystrix on microservice-level using the `serviceId` as following.

    zuul:
      routes:
        admin-services:
          path: /admin/**
          serviceId: ft-admin
          stripPrefix: true
    
    ft-admin:
      ribbon:
        ActiveConnectionsLimit: 2
    
    hystrix:
      command:
        ft-admin:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 10000

I'm wondering if there's a way to bring the above configurations down to endpoint-level for each `app-config` and `app-analytic` individually. The goal is to be able to give a different setting for each endpoint as following.

    zuul:
      routes:
        app-config-endpoint:
          path: /app-config/**
          serviceId: ft-admin
          stripPrefix: false
        app-analytic-endpoint:
          path: /app-analytic/**
          serviceId: ft-admin
          stripPrefix: false
    
    app-config-endpoint:
      ribbon:
        ActiveConnectionsLimit: 5
    app-analytic-endpoint:
      ribbon:
        ActiveConnectionsLimit: 2

    ...

When I run my gateway project in Debug mode with `ft-admin.ribbon.ActiveConnectionsLimit: 2`, I can see the following lines in the log.

```
c.netflix.config.ChainedDynamicProperty  : Property changed: 'ft-admin.ribbon.ActiveConnectionsLimit = 2'
c.netflix.config.ChainedDynamicProperty  : Flipping property: ft-admin.ribbon.ActiveConnectionsLimit to use it's current value:2
```

However, when I run my project with `app-config-endpoint.ribbon.ActiveConnectionsLimit: 5`, I see the following lines.

```
c.netflix.config.ChainedDynamicProperty  : Property changed: 'ft-admin.ribbon.ActiveConnectionsLimit = -2147483648'
c.netflix.config.ChainedDynamicProperty  : Flipping property: ft-admin.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
```

I've tried to search through a ton of posts but it seems like the configurations always stop at the microservice-level. The endpoint/route level configurations are completely ignore. 

I'd be very grateful if you could point me in the right direction or tell me your story if you've tried this before.

**Comment by ryanjbaxter** [comment]
Are you using service discovery to configure the list of ribbon servers?

**Comment by Mr-James** [comment]
Yes I do @ryanjbaxter :). That's why I was using `serverId` to refer to my `ft-admin` microservice. I have a Eureka naming server running and all of my microservices including the gateway will register themselves to the naming server.

**Comment by ryanjbaxter** [comment]
In that case you cannot do what you are trying to accomplish.

If you were using the ribbon `listOfServers` property you could manually define the service names and the servers they point to and then apply separate configuration for those servers.  However since each service is registering automatically with eureka and ribbon is using eureka to define the service names you cannot customize that.

**Comment by spencergibb** [comment]
closing as answered
