### ISSUE TITLE
SpringBoot 2.1.0 compatibility issue with Spring Cloud 2.0.1.Release

### ISSUE THREAD

**Issue by satyam-guptha** [spring-cloud/spring-cloud-netflix#3341]
Hi,

we are getting the compatibility error, Spring Boot 2.1.0 with Spring Cloud 2.0.1:
error message:
An attempt was made to call the method org.springframework.boot.autoconfigure.web.ServerProperties$Servlet.getServletPrefix()Ljava/lang/String; but it does not exist. Its class, org.springframework.boot.autoconfigure.web.ServerProperties$Servlet, is available from the following locations:
could you please confirm the solution.
regards
satya.

**Comment by ryanjbaxter** [comment]
Spring Cloud Finchley is not compatible with Boot 2.1.0, you need to use Greenwich.
