### ISSUE TITLE
Netflix components in maintenance mode?

### ISSUE THREAD

**Issue by rao-pathangi** [spring-cloud/spring-cloud-netflix#3342]
Netflix recently [announced](https://github.com/Netflix/Hystrix/issues/1876#issuecomment-440065505) the following:

> Hystrix has now been transitioned into maintenance mode, and we have updated the Readme with the new details.

I think this isn't limited to Hystrix and could spread to other Netflix OSS too: it is confirmed that Ribbon too will follow suit. What does this mean for Spring Cloud Netflix?

**Comment by eacdy** [comment]
Maybe you should read this blog: <https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now#spring-cloud-netflix-projects-entering-maintenance-mode> . This post will answer your question.


If you'are a Chinese, you Can read my blog: <http://www.itmuch.com/spring-cloud-sum/spring-cloud-netflix-in-maintenance-mode/>

**Comment by rao-pathangi** [comment]
A new follow-up question, I saw these lines in the note.

> Placing a module in maintenance mode means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

> We intend to continue to support these modules for a period of at least a year from the general availability of the Greenwich release train. 

This places "support" till January 2020. Does this mean after January 2020, blocker bugs and security issues will not be addressed?

**Comment by eacdy** [comment]
@rao-pathangi In my opintion, This means the Finchley RELEASE EOF(end of life).

**Comment by ryanjbaxter** [comment]
These modules will be included in Greenwhich, so till the point of the Greenwhich EOL (at least)
