### ISSUE TITLE
@EnableZuulProxy fails on context load 

### ISSUE THREAD

**Issue by PriyaShetti** [spring-cloud/spring-cloud-netflix#3345]

**Comment by PriyaShetti** [comment]
Hi Team,

While upgrading  the spring boot 2.0.4 to spring boot 2.1.0 verison . I am getting below exception

**An attempt was made to call the method org.springframework.boot.autoconfigure.web.ServerProperties$Servlet.getServletPrefix()Ljava/lang/String; but it does not exist. Its class, org.springframework.boot.autoconfigure.web.ServerProperties$Servlet, is available from the following locations:

    jar:file:/homedircotry/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.0.RELEASE/spring-boot-autoconfigure-2.1.0.RELEASE.jar
	
	!/org/springframework/boot/autoconfigure/web/ServerProperties$Servlet.class

It was loaded from the following location:

    file:/homedirectory/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.0.RELEASE/spring-boot-autoconfigure-2.1.0.RELEASE.jar**

**Comment by ryanjbaxter** [comment]
Spring cloud Finchley is not compatible with boot 2.1.x, you will need to use Spring Cloud Greenwich

**Comment by PriyaShetti** [comment]
Thank you
