### ISSUE TITLE
@spencergibb @ryanjbaxter Thank you very much! Now it is working properly! The problem was my configuration.

### ISSUE THREAD

**Issue by juedizor** [spring-cloud/spring-cloud-netflix#3346]
@spencergibb @ryanjbaxter Thank you very much! Now it is working properly! The problem was my configuration.

_Originally posted by @cleversonledur in https://github.com/spring-cloud/spring-cloud-netflix/issues/2530#issuecomment-359767408_

Do you have the project complete ?

**Comment by ryanjbaxter** [comment]
I am not sure why this issue was opened
