### ISSUE TITLE
Eureka server application 

### ISSUE THREAD

**Issue by srinivasvadla** [spring-cloud/spring-cloud-netflix#3348]
Team i was facing the issue with the rest endpoint when i hitting the URL i was getting the HTML page with login page 

Spring version i am using  is 2.1.0.RELEASE 
and cloud version Greenwich.RC2 i am new for this  Eureka 
 
Please  provide me a solution for this .
Thank you.

**Comment by ryanjbaxter** [comment]
Sounds like you might have Spring Security on the classpath?

**Comment by srinivasvadla** [comment]
No  Ryan Baxter   i am not maintaining any paths. 
if Spring Security on my classpath exists where we configure those ,let me remove if exists.

**Comment by dsyer** [comment]
@srinivasvadla it would probably help if you provided a sample project that showed the issue. It seems pretty certain that you have Spring Security on the classpath.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
