### ISSUE TITLE
Ribbon-Eureka useless if Eureka Client disabled?

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-netflix#335]
Most likely it's a very silly question (maybe I didn't get sth).

If you provide as a property 

```
eureka.client.enabled: false
```

then shouldn't 

```
ribbon.eureka.enabled
```

be automatically disabled too? 

I mean I shouldn't be able to use Ribbon if I'm disabling Eureka client. Or is it like a separation of using Eureka Client only for registering yourself in Eureka whereas you would still want to profit from Eureka via Ribbon?

**Comment by spencergibb** [comment]
Ribbon can be configured without eureka.  So, the ribbon-eureka client probably should be disabled, but not ribbon entirely.

**Comment by marcingrzejszczak** [comment]
I'll try to file a PR with a fix as soon as possible.

**Comment by spencergibb** [comment]
@marcingrzejszczak sweet!

**Comment by marcingrzejszczak** [comment]
Lol I don't think I filed the PR soon
