### ISSUE TITLE
Modify the host address

### ISSUE THREAD

**Issue by geemu** [spring-cloud/spring-cloud-netflix#3351]
How do I host the address, the request destination address is 127.0.0.1:80, but I need to forward the request to 127.0.0.2:88 or forward it to another address based on the calculation result.
I am now modifying the RouteHost in the pre filter, but it is invalid. what should I do. Edgware.sr4.

**Comment by ryanjbaxter** [comment]
I assume you are talking about Zuul?

These samples might be useful to you https://github.com/spring-cloud-samples/sample-zuul-filters

**Comment by geemu** [comment]
Thanks a lot, I have solved this problem by using the SimpleHostRoutingFilter to dynamically modify the host address to support grayscale publishing.
