### ISSUE TITLE
maven-gpg-plugin:1.6:sign (sign-artifacts) @ spring-cloud-netflix-hystrix-contract

### ISSUE THREAD

**Issue by wordsless** [spring-cloud/spring-cloud-netflix#3352]
When I execute scripts/build.sh to try to build the project, the logs 
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ spring-cloud-netflix-hystrix-contract ---
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.720 s
[INFO] Finished at: 2019-01-17T15:40:16+08:00
[INFO] Final Memory: 44M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project spring-cloud-netflix-hystrix-contract: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Running version check

**Comment by ryanjbaxter** [comment]
Most likely a problem in your local maven environment, that goal should be run by default

**Comment by wordsless** [comment]
I can build the project successfully with tow arguments, -Dmaven.test.skip=true and -Dgpg.skip=true. But I want a default building progress, without any arguments, just to run scripts/build.sh. what should I do ? How can I get the key to pass gpg verify ?

**Comment by spencergibb** [comment]
The gpg plugin in only active if the `central` maven profile is active. The `central` maven plugin is only active if the version contains `RELEASE` which a user shouldn't be building. If you are deploying a patched RELEASE to your local nexus repo, then skipping the gpg plugin is indeed the way to go.
