### ISSUE TITLE
How to refresh the ribbon rule?

### ISSUE THREAD

**Issue by mrvon2015** [spring-cloud/spring-cloud-netflix#3353]
`springboot-eureka-clent.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule`

if change
`springboot-eureka-clent.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RoundRobinRule`

how to refresh not reload

**Comment by mrvon2015** [comment]
thanks

**Comment by hardy4yooz** [comment]
@mrvon2015 
Did your problem has been solved ?
