### ISSUE TITLE
spring-cloud-starter-netflix-hystrix : Throwing HystrixTimeout Exception before timeout for the first request

### ISSUE THREAD

**Issue by sunjavax** [spring-cloud/spring-cloud-netflix#3354]
Hi,
Once application started, 1st request is falling into hystrix fallback method within/before the preConfigured timeout: (execution.isolation.thread.timeoutInMilliseconds : 12000). and throwing exception: com.netflix.hystrix.exception.HystrixTimeoutException: null.

But in our logs, we are also seeing success response from the actual requested service after this Fallback.

This is happening only for first request after application starting.

Following are our hystrix configurations
hystrix.default.execution.timeoutEnabled: true
**hystrix.default.threadTimeoutInMilliseconds: 12000**
hystrix.default.requestVolumeThreshold: 5
hystrix.default.errorThresholdPercentage: 50
hystrix.default.sleepWindowInMilliseconds: 5000
hystrix.default.rollingStatsTimeInMilliseconds: 10000
**hystrix.default.threadpool.default.coreSize: 10**

Can you please help us in this.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by sunjavax** [comment]
@ryanjbaxter , Sample project is available at - https://github.com/sunjavax/SbHytstrix.git.

**Comment by spencergibb** [comment]
Why are you doing this?
```
        ConfigurationManager.getConfigInstance().setProperty("hystrix.command." + hystrixCommandKey + ".execution.timeout.enabled", hystrixConfigService.getHxDefaultTimeoutEnabled());
```

**Comment by sunjavax** [comment]
hystrix.command.default.execution.timeout.enabled - This is for enabling the timeout for hystrix command execution.  And the default value is true: https://github.com/Netflix/Hystrix/wiki/configuration#execution.timeout.enabled
We tried setting value 'false', still we are getting this issue.

**Comment by ryanjbaxter** [comment]
I think @spencergibb meant why are you configuring hystrix that way, why not configure it in your application configuration?

I am also not able to reproduce the problem using your sample.

**Comment by sunjavax** [comment]
We are having multiple services in our application. for each service we are setting hystrix commands by passing servicename as command key and fallback method 

@HystrixCommand(commandKey = "getData", fallbackMethod = "getDataFallback") 
    public ResponseEntity<?> getData(String id) throws HttpServerErrorException {
        setHystrixProperties("getData");
        **return firstRestService.getData(id);**
    }

@ryanjbaxter , Yes it is inconsistent in the sample project.
- to reproduce, just add a debug point at >  'return firstRestService.getData(id)' and resume it. 
You can get timeout exception.
--
But in our actual application. it is happening consistently.

**Comment by spencergibb** [comment]
@sunjavax, unfortunately, that is not replicating the problem. The problem is what is causing the timeout exception. Setting a breakpoint and waiting will always cause a timeout and is something we can't fix.

**Comment by sunjavax** [comment]
This is reproducing just for sample project only. 
It is not required to wait, as soon as it reaches that breakpoint. It throws the exception. 
We set timeout 12000 and please verify the logs below. exception thrown in 1 sec. 
Logs:
2019-01-18 10:53:44.967  INFO 28600 --- [nio-9005-exec-2] c.d.s.s.controller.FirstController       : springboothystrix:getData- for id: 10
2019-01-18 **10:53:45**.118  INFO 28600 --- [-FirstService-1] c.d.s.s.service.FirstService             : setHystrixProperties.. for hystrixCommandKey: getData
2019-01-18 1**0:53:46**.139 ERROR 28600 --- [ HystrixTimer-1] c.d.s.s.service.FirstService             : falling back to Hystrix - getDataFallback Identifier: 10

com.netflix.hystrix.exception.HystrixTimeoutException: null

**Comment by spencergibb** [comment]
I'm sorry we need a way to reproduce without a breakpoint.

**Comment by sunjavax** [comment]
Sure, I will make it

**Comment by sunjavax** [comment]
Pushed new changes, can you please try once. Only for First Request hystrix throws timeout exception

**Comment by sunjavax** [comment]
Pushed new code into :  https://github.com/sunjavax/SbHytstrixApp
Only for first request we get timeout Exception

**Comment by sunjavax** [comment]
I have added Thread.sleep(1000) to mimic the delay.
We noticed a interrupt happened for the first call which triggered hystrix fallback (though it was reasoned as HystrixTimeout instead of interupt)
But My question is why this happens only for the 1st call consistently and not for any of the subsequent calls.
**Logs:**
2019-01-18 17:42:56.809  INFO 23208 --- [  restartedMain] c.d.s.s.SpringBootHystrixApplication     : Started SpringBootHystrixApplication in 4.757 seconds (JVM running for 5.339)
2019-01-18 17:43:10.932  INFO 23208 --- [nio-9005-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-01-18 17:43:10.932  INFO 23208 --- [nio-9005-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2019-01-18 17:43:10.946  INFO 23208 --- [nio-9005-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 14 ms
2019-01-18 17:43:10.978  INFO 23208 --- [nio-9005-exec-1] c.d.s.s.controller.FirstController       : springboothystrix:getData- for id: 10
2019-01-18 **17:43:11**.101  INFO 23208 --- [ystrixService-1] c.d.s.s.service.HystrixService           : setHystrixProperties.. for hystrixCommandKey: getData
2019-01-18 **17:43:12.**099 ERROR 23208 --- [ystrixService-1] c.d.s.s.service.FirstRestService         : Custom Exception......

java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method) [na:1.8.0_144]
.......
2019-01-18 **17:43:12**.104 ERROR 23208 --- [ HystrixTimer-1] c.d.s.s.service.HystrixService           : falling back to Hystrix - getDataFallback Identifier: 10

com.netflix.hystrix.exception.HystrixTimeoutException: null
.......................
2019-01-18 **17:43:15**.220  INFO 23208 --- [nio-9005-exec-2] c.d.s.s.controller.FirstController       : springboothystrix:getData- for id: 10
2019-01-18 17:43:15.221  INFO 23208 --- [ystrixService-2] c.d.s.s.service.HystrixService           : setHystrixProperties.. for hystrixCommandKey: getData
2019-01-18 17:43:16.415  INFO 23208 --- [ystrixService-2] c.d.s.s.service.FirstRestService         : Response Received from rest ......
{"type":"success","value":{"id":10,"quote":"Really loving Spring Boot, makes stand alone Spring apps easy."}}

**Comment by ryanjbaxter** [comment]
It is a timing problem, you are setting the Hystrix configuration properties when `getData` is called.  The first time it is called the the circuit breaker has already been created so all the defaults still apply.  The second time it is called (and every time after) you have already set the configuration properties via the first call.

In general though you should no be configuring Hystrix like this.  I still dont see why you cant set these properties via the default Hystrix configuration properties in your application configuration.

**Comment by sunjavax** [comment]
@ryanjbaxter ,
1. We can still reproduce this problem by NOT setting the Hystrix configuration properties when getData is called.  ( try commenting 'setHystrixProperties("getData"); inside getData(..) ).

2.There are multiple services like getData, getData1, 2, 3.... .And hystrix configurations are different for each service. Ex: hystrix timeout value is different for getData1 and getData2.
Hence  we are configuring Hystrix like this.

**Comment by sunjavax** [comment]
@ryanjbaxter. So is this not suggestible way of configuring for multiple services?

**Comment by ryanjbaxter** [comment]
> We can still reproduce this problem by NOT setting the Hystrix configuration properties when getData is called. ( try commenting 'setHystrixProperties("getData"); inside getData(..) and set thread time out to 700 i.e less than 1000 which is hystrix default value ).

If I do what you said above everything still works fine.  

Like I said above the most common way to do this is to configure it in application properties.

**Comment by sunjavax** [comment]
@ryanjbaxter 

This is our observations:
1. While invoking the rest/remote service.  we are setting/configuring hystrix properties like
`ConfigurationManager.getConfigInstance().setProperty("hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds", 12000); `
2. On first request to this service, hystrix command is taking 'default values' i.e timeout is 1000ms instead of configured value i.e 12000ms. And the remote service is responding after 1000ms hence we are getting 'Timeout Excpetion'
3. On subsequest requests to this service, hystrix taking configured values i.e 12000ms, So we are not seeing any exceptions.
As suggested, we made changes and configuring hystrix in application properties:
`
hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 5
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 50
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
hystrix.command.default.metrics.rollingStats.timeInMilliseconds: 10000
hystrix.threadpool.default.coreSize: 10
`
It is working fine with this approach but need to configure differently for different remote services 
Thank you for your support.

**Comment by spencergibb** [comment]
Change `default` to the values defined in the `commandKey` attribute to configure each one differently.
