### ISSUE TITLE
How to disable log out: aws.ConfigClusterResolver - Resolving eureka endpoints via configuration

### ISSUE THREAD

**Issue by gclsoft** [spring-cloud/spring-cloud-netflix#3365]
it log out every 5 minutes, how to just disable log out? My log out level is `INFO`, I don't want to change it.

**Comment by spencergibb** [comment]
What gets logged? You've provided very little information, can you be more detailed

**Comment by gclsoft** [comment]
```09:45:57.938 m [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.aws.ConfigClusterResolver - Resolving eureka endpoints via configuration
```
@spencergibb It's eureka check online.

**Comment by spencergibb** [comment]
That's in a `com.netflix` logger. We have no control over it. Setting a log level is the best you are going to get. Open an issue or PR at Netflix/eureka if you'd like.
```
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
```

**Comment by gclsoft** [comment]
`logging.level.com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver=WARN` is it right in the properties file?

**Comment by bilifuture** [comment]
good
