### ISSUE TITLE
LoadBalancerClient is not picking up secure url

### ISSUE THREAD

**Issue by beku8** [spring-cloud/spring-cloud-netflix#337]
I've following eureka.instance config: 
```
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${vcap.application.uris[0]}
    homePageUrl: https://${vcap.application.uris[0]}
    instanceId: ${vcap.application.instance_id}
    securePortEnabled: true
    nonSecurePortEnabled: false
```
which is deployed to PWS CloudFoundry, ```/configprops``` shows:
```
eurekaInstanceConfigBean: {
prefix: "eureka.instance",
properties: {
appGroupName: null,
nonSecurePortEnabled: false,
statusPageUrl: null,
initialStatus: "UP",
instanceEnabledOnit: false,
homePageUrl: "https://login-nd.cfapps.io",
securePort: 443,
securePortEnabled: true,
hostname: "login-nd.cfapps.io",
dataCenterInfo: {
name: "MyOwn"
},
appname: "login",
healthCheckUrlPath: "/health",
leaseExpirationDurationInSeconds: 90,
metadataMap: { },
preferIpAddress: false,
healthCheckUrl: null,
statusPageUrlPath: "/info",
virtualHostName: "login",
ipAddress: "10.254.0.26",
leaseRenewalIntervalInSeconds: 10,
homePageUrlPath: "/",
nonSecurePort: 80,
namespace: "eureka",
secureVirtualHostName: null,
secureHealthCheckUrl: null
}
}
```
which results in the eureka registry(```/eureka/apps```):
```
<application>
<name>LOGIN</name>
<instance>
<hostName>login-nd.cfapps.io</hostName>
<app>LOGIN</app>
<ipAddr>10.254.0.26</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="false">80</port>
<securePort enabled="true">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>10</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1430883647411</registrationTimestamp>
<lastRenewalTimestamp>1430883747423</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1430883647411</serviceUpTimestamp>
</leaseInfo>
<metadata class="java.util.Collections$EmptyMap"/>
<homePageUrl>https://login-nd.cfapps.io</homePageUrl>
<statusPageUrl>http://login-nd.cfapps.io:80/info</statusPageUrl>
<secureHealthCheckUrl>https://login-nd.cfapps.io:443/health</secureHealthCheckUrl>
<vipAddress>login</vipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1430883647411</lastUpdatedTimestamp>
<lastDirtyTimestamp>1430883637340</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
```

I would like use ```LoadBalancerClient```:

```
ServiceInstance instance = loadBalancerClient.choose("login");
instance.getUri(); // returns http://login-nd.cfapps.io:443
instance.isSecure() // returns false
```

is it a bug or am I missing a property to configure?

**Comment by dsyer** [comment]
Looks like a bug to me. PR welcome as usual.

**Comment by CanD42** [comment]
We just upgraded to Angel.SR3 release and have a similar problem with Feign clients and securePortEnabled=true:

    feign.RetryableException: Unexpected end of file from server executing GET http://users/user/1

when another microservice calls the user service. Configuration is as described on http://stackoverflow.com/questions/30622904/spring-cloud-ribbon-and-https 

Is this a related problem?

**Comment by todzheng** [comment]
set up according to above stackoverflow link enables Feign/Ribbon to send request with https,

ribbon.IsSecure=true
eureka.instance.secureVirtualHostName=${spring.application.name}

however, there is another issue here, where I want to ignore SSL certificate with the following config:

ribbon.CustomSSLSocketFactoryClassName=com.netflix.http4.ssl.AcceptAllSocketFactory

However, when RibbonClient is initialized by SpringLBClientFactory, it is using feign.Client.Default instance where sslContextFactory and hostnameVerifier are still null; although later on it picks up my config correctly but the client instance in RibbonClient is not updated with correct config (where I can clearly see the property is correct)

**Comment by CanD42** [comment]
We generate our own server certificates, so that's not an issue for us. The above setting fixed indeed the zulu proxy https forward. However, prefixing the Feign client with https like 

   @FeignClient("https://users")

has worked in version 1.0.0, but after upgrading to Angel.SR3 it's broken because it's generating http urls. Let's see if I can find the problem in LoadBalancerClient.

**Comment by CanD42** [comment]
What I can see is that
 
    com.netflix.loadbalancer.LoadBalancerContext.reconstructURIWithServer()

uses always the scheme of the original feign client definition like 

    @FeignClient("https://users") 

and not the actual eureka configuration of the service. However, I wanted to make it more dynamic via a configuration property so I can run it locally via http and on other servers via https: 

    @FeignClient("#{feign.url.scheme}://users")

but I get
 
    java.lang.IllegalStateException: Service id not legal hostname (#{feign.url.scheme}://users)

Would it make sense to create a feature request to be able to use SPEL in the FeignClient definition to specify the protocol dynamically?

**Comment by dsyer** [comment]
We could support placeholders there but not SpEL I think.

**Comment by CanD42** [comment]
Thanks Dave, I created https://github.com/spring-cloud/spring-cloud-netflix/issues/414

**Comment by brenuart** [comment]
Shouldn't the choice of the actual protocol left to Ribbon instead?
I mean, the `@FeignClient` definition should be there just to give a name to the client. It must have the form of a valid URI just because of the way this information is passed through the stack down to Ribbon - otherwise it has not to be an url.

If Ribbon finds two instances (from Eureka for instance), it could be told to select only the secured one or not. This could be achieved by filtering the ServerList for instance. Implementing the feature at the Ribbon level would benefit to all clients and not only Feign.

**Comment by CanD42** [comment]
You can use Feign without Ribbon so IMO it's good to have configuration options on every level. However, if ribbon.IsSecure=true is set I'd expect that ribbon looks up the secure instance only.

**Comment by steve-oakey** [comment]
Could this be a potential solution? This checks the `IClientConfig` for a service when making a request to see if `IsSecure` is set. I have made this change in `RibbonLoadBalancerClient` and 'RibbonLoadBalancer`. 

https://github.com/steve-oakey/spring-cloud-netflix/commit/c5e34f69f99b9d2ec59734a683cddb5c873b462c

**Comment by ouaibsky** [comment]
Hi, 
Solution provided by @steve-oakey  sounds good.
Any chance to get get it into a validated Pr ?
Thx
Christophe

**Comment by steve-oakey** [comment]
Will provide a PR later this evening.
