### ISSUE TITLE
Zuul throwing 401 error to connect to api gateway for post

### ISSUE THREAD

**Issue by monishgithub** [spring-cloud/spring-cloud-netflix#3384]
My node service is trying to connect to api gateway(infront of middleware) via zuul application. The api gateway call needs cert. The get calls to the api gateway via zuul works fine and gives back the response. But when a post is made the zuul gets 401 error while connecting to api gateway.

For GET call
    timestamp: 02/10/2019 07:09:44:0547 service:zuul-gateway level:INFO  class:ACCESS type:event body:2019-02-10T07:09:41.263	172.17.0.1	8443	GET	/apigateway/cfg/profile/getProfiles	200	3273680	2282	c88a02da-c76c-4a5f-9166-4b3de3435965	-	"localhost:1000"	"-"	"-"	"-"	"-"	"-"	"-"	"1.1 CQAAAN!IIiM-"	"application/json"}

For POST call
    timestamp: 02/10/2019 07:15:24:0524 service:zuul-gateway level:INFO  class:ACCESS type:event body:2019-02-10T07:15:23.619	172.17.0.1	8443	POST	/apigateway/cfg/users/user-info/query?userId=TEST&mode=VIEW	401	904892	94	df0df065-8ce1-41d5-b1a0-b4d37f28fa81	356	"localhost:1000"	"-"	"-"	"-"	"-"	"-"	"-"	"-"	"application/json"}

**Comment by ryanjbaxter** [comment]
A `401` is an unauthorized error not sure what that has to do with zuul

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by JavaTechnology9** [comment]
given only one starter called zuul, if i am trying to hit the this URL (http://localhost:5555/routes) getting an error
 "timestamp": "2020-05-16T13:46:46.368+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/routes"
`@SpringBootApplication
@EnableZuulProxy
public class MicroserviceZuulApplication {

	public static void main(String[] args) {
		SpringApplication.run(MicroserviceZuulApplication.class, args);
	}

}`

`<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>`
