### ISSUE TITLE
Zuul: Hystrix SEMAPHORE isolation blocks the client way far after the timeout

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#339]
I noticed ZUUL forces the execution isolation to SEMAPHORE instead of the THREAD default (as recommended by Netflix: https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.strategy).

A comment in `org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand` says:
> we want to default to semaphore-isolation since this wraps
> 2 others commands that are already thread isolated

But still I don't get it :-( What are those two other wrapped commands?

Configured this way, Zuul can only shed load but does not allow for timing out and let the client walk away. In short, even if the Hystrix timeout is set to 1000ms, clients will only be released once the call forwarded to the service down the chain returns (or timeouts because of a ReadTimeout for instance).

I tried to force THREAD isolation by overriding the configuration (per service unfortunately, since the default is forced in the code) and everything seems to work as expected. However, I'm not keen in doing this without proper understanding of the implications - certainly in regards of the comment found in the code and the defaults adopted by the Spring Cloud version of Zuul.

Can someone provide more information?
Thx

**Comment by spencergibb** [comment]
This could easily be refactored to be configurable. `ExecutionIsolationStrategy` is an enum and could be put in `ZuulProperties`.

**Comment by denyska** [comment]
Changes in HttpClientRibbonCommand that are part of 1.1.4 release cause NPE in this line `String contentLengthHeader = context.getRequest().getHeader("Content-Length");` if Hystrix configured with THREAD isolation by default.

I know that RestClientRibbonCommand suggests to use SEMAPHORE strategy, but should it still work with the THREAD isolation and all thread-local variables being resolved even before Command created?

I like that THREAD strategy can interrupt threads and I can keep response time upon agreed SLA for all coming requests.

**Comment by aivans** [comment]
Interested in this one also.

**Comment by stephlag** [comment]
As we have performance limitations using the semaphore approach, we would need this change.
I can report @spencergibb  [commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/d1651a48d62c3f2807239230c65f33224a5b7bf4) on the latest master if nobody else works on this issue.

**Comment by stephlag** [comment]
I reported [Spencer's commit](https://github.com/spring-cloud/spring-cloud-netflix/commit/d1651a48d62c3f2807239230c65f33224a5b7bf4) on my own branch. All tests are ok and there are no regression on the existing behaviour.
However the issue with Thread isolation is that Zuul RequestContext is stored in a ThreadLocal and therefore not available in the thread spawned by Hystrix.

**Comment by stephlag** [comment]
OK I managed to bypass RequestContext usage as it was only used to get content length which is already in RibbonContext.
