### ISSUE TITLE
when I include spring-cloud-netflix-eureka-client '2.1.0.RELEASE' version, spring boot 2.1.x version cannot replace custom's banner with banner.txt

### ISSUE THREAD

**Issue by haycco** [spring-cloud/spring-cloud-netflix#3397]
HI，
when I include **spring-cloud-netflix-eureka-client** '**2.1.0.RELEASE**' version, spring boot **2.1.x** version cannot replace custom's banner with banner.txt！

```
<dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
      <version>2.1.0.RELEASE</version>
</dependency>
```
when I start spring boot application for spring cloud eureka client that console cannot print custom's banner.txt content.
alaway is default.
I think is a bug!

spring cloud version is **Greenwich.RELEASE**

**Comment by spencergibb** [comment]
Eureka has nothing to do with a banner.txt.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by haycco** [comment]
@spencergibb Yes, Eureka has nothing to do with a banner.txt, but when the client service project import the spring-cloud-starter-netflix-eureka-client and the banner.txt not work.

**Comment by haycco** [comment]
@spencergibb Sorry, I made a mistake...
