### ISSUE TITLE
Inter micro-service communication between docker eureka clients is failing

### ISSUE THREAD

**Issue by havannavar** [spring-cloud/spring-cloud-netflix#3401]
I'm using docker and spring cloud Netflix Eureka server
Below are my details

- spring-cloud-starter-netflix-eureka-server (2.1.0.RELEASE)
- Docker (2.0.0.3)

Here are my application.properties for eureka server
```
server.port=8761
spring.application.name= eureka-server
eureka.instance.hostname=${HOST}
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.client.preferIpAddress =false
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka

```

```
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@SpringBootApplication
@EnableEurekaServer
public class StartEureka {

	public static void main(String[] args) {
		SpringApplication.run(StartEureka.class, args);

	}

}
```
My Docker run command is 
```
docker run --rm --name eureka_server -e HOST=macbook -i -t -p 8761:8761 eureka_docker
```
This works fine. 

My Client code is 

```
@SpringBootApplication
@EnableEurekaClient
public class BootEurekaClient {

	public static void main(String[] args) {
		SpringApplication.run(BootEurekaClient.class, args);
	}
}
```
and configuration (application.properties)

```
eureka.instance.hostname=${HOST}
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka
eureka.instance.preferIpAddress=false
spring.application.name=service_1
```
The same is configured for another client service 2 but only change is applica.name to service_2 and port as 9081

my docker run command for both the services are
```
docker run --rm --name eureka-service1 -e HOST= macbook -i -t -p 9080:9080 service1
```
The clients are registered to eureka server and I can see the  details in http://localhost:8761/ and http://localhost:8761/eureka/apps.

I'm able to invoke the api's of eureka clients as `http://macbook:9080/api/me` and `http://macbook:9081/api/profile` 

But I'm unable to connect to eureka clients as `http://service_1/api/me` and `http://service-2/api/profile` 

Can someone help me how to achieve the same ?

**Comment by ryanjbaxter** [comment]
> But I'm unable to connect to eureka clients as `http://service_1/api/me` and `http://service-2/api/profile`

How are you trying to connect to those urls?

**Comment by havannavar** [comment]
I

> > But I'm unable to connect to eureka clients as `http://service_1/api/me` and `http://service-2/api/profile`
> 
> How are you trying to connect to those urls?

I tried using postman, but no luck.
Do you want me to use this code ?

    ```
@Autowired
    private DiscoveryClient discoveryClient;

    @RequestMapping("/service-instances/{applicationName}")
    public List<ServiceInstance> serviceInstancesByApplicationName(
            @PathVariable String applicationName) {
        return this.discoveryClient.getInstances(applicationName);
    }
```

**Comment by spencergibb** [comment]
You've configured the eureka client to connect to itself rather than the server

```
eureka.instance.hostname=${HOST}
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka
```

Default zone should be the eureka server url

**Comment by havannavar** [comment]
> You've configured the eureka client to connect to itself rather than the server
> 
> ```
> eureka.instance.hostname=${HOST}
> eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka
> ```
> Default zone should be the eureka server url

Can you share an example what should be eureka server url, as I explained earlier, 
server is running @ `http://${HOST}:8761` and I can see Lise of registered apps @ `http://${HOST}:8761/eureka/apps`

**Comment by spencergibb** [comment]
It only works because server and client are both on `${HOST}`. You shouldn't use `${eureka.instance.hostname}` in defaultZone.

Postman and curl know nothing about services registered in eureka. You have to use a eureka client and something like `@Loadbalanced RestTemplate`.

**Comment by havannavar** [comment]
> It only works because server and client are both on `${HOST}`. You shouldn't use `${eureka.instance.hostname}` in defaultZone.
> 
> Postman and curl know nothing about services registered in eureka. You have to use a eureka client and something like `@Loadbalanced RestTemplate`.
Thank you for this note.

I'm little confused about defaultZone, can you share an example of what should be the value of 
`eureka.client.serviceUrl.defaultZone = ?`

**Comment by ryanjbaxter** [comment]
On the Eureka client `eureka.client.serviceUrl.defaultZone` needs to point to the URL of the Eureka server.  If the server and the client are running on the same host than your configuration the way it is above will work fine, but once you separate the two apps you are going to run into problems.

Postman does not know how to use Eureka or service discovery..  So if you make a request using postman to http://service it is going to return a 404.

**Comment by havannavar** [comment]
> On the Eureka client `eureka.client.serviceUrl.defaultZone` needs to point to the URL of the Eureka server. If the server and the client are running on the same host than your configuration the way it is above will work fine, but once you separate the two apps you are going to run into problems.
> 
> Postman does not know how to use Eureka or service discovery.. So if you make a request using postman to http://service it is going to return a 404.

Yes, I'm totally aware If server and client are in different machines. 
Below is the sample of `service_1` accessing `service_2`

```
        @Autowired
	private EurekaClient eurekaClient;
	
       @Autowired
	private final RestTemplate restTemplate;

	@RequestMapping("/me")
	public Map<String, Object> getApplications(HttpServletRequest request) {

		Application application = eurekaClient.getApplication("service_2");
		InstanceInfo instanceInfo = application.getInstances().get(0);
		String url = "http://" + instanceInfo.getHostName() + ":" + instanceInfo.getPort() + "/v1/profile";
		System.out.println("URL" + url);
		try {
			Map<String, Object> response = 	restTemplate.getForObject(url, Map.class)
			System.out.println("Result - status (" + response.getStatusCode() + ") has body: " + response.hasBody());
		} catch (Exception e) {
		}
	}
```
Hope this is fine.

**Comment by ryanjbaxter** [comment]
That code looks fine and should work as long as service 1 can resolve the hostname of service 2

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
