### ISSUE TITLE
TurbineStreamTests.contextLoads fails

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-netflix#3409]
https://github.com/spring-cloud/spring-cloud-netflix/commit/0791a02223e13e54ea0a90dc0e76816fb3778f3

**Comment by fdimauro** [comment]
Nice, comment out the test. Any idea when this will be working again. I can not get Turbine Stream to work.

**Comment by spencergibb** [comment]
Please stop commenting on other issues and open a new one

**Comment by ryanjbaxter** [comment]
@marcingrzejszczak @OlgaMaciaszek wondering if you can help out here.

When we run this test in Greenwich the `MessageVerifier` used by `StubRunnerExecutor` is `StreamStubMessages` and this test passes.  However in Hoxton the `MessageVerifier` is `SpringIntegrationStubMessages` and the test fails with `org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'hystrixStreamOutput' available`.  Do either of you know why that might be the case?
