### ISSUE TITLE
Remove dependencies to maintenance mode modules from non-maintenance mode modules

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-netflix#3415]
Some modules that are in maintenance mode (like spring-cloud-netflix-ribbon) are used as dependencies of non-maintenance mode modules (like spring-cloud-netflix-eureka-client).

**Comment by juergenzimmermann** [comment]
`spring-cloud-starter-consul-discovery` depends on `spring-cloud-starter-netflix-ribbon`.

**Comment by spencergibb** [comment]
@juergenzimmermann can you please open an issue in https://github.com/spring-cloud/spring-cloud-consul

**Comment by spencergibb** [comment]
It may be that the dependency may need to be optional, rather than removed.

**Comment by spencergibb** [comment]
https://github.com/Netflix/eureka/issues/1268
