### ISSUE TITLE
enable-self-preservation: false  doesn't work

### ISSUE THREAD

**Issue by Leehom23** [spring-cloud/spring-cloud-netflix#3419]
i use spring cloud 1.5.8. i want stop application when it stop which register on eureka server, so i set
**eureka.server.enable-self-preservation=false**  in my project. but it doesn't work. maybe about 
1.5 minute later ,application may remove by eureka server.

my config file is following:
`
`
`eureka:
  client:
    registry-fetch-interval-seconds: 5 
    eurekaServiceUrlPollIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://server1:8762/eureka/
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
`

**Comment by ryanjbaxter** [comment]
> i use spring cloud 1.5.8

There is no Spring Cloud 1.5.8

Why would you expect the service to not be removed from the eureka server?

**Comment by Leehom23** [comment]
> > i use spring cloud 1.5.8
> 
> There is no Spring Cloud 1.5.8
> 
> Why would you expect the service to not be removed from the eureka server?
Thank you for your reply.  sorry ,My project version is Dalston.RELEASE. The reason why i want to remove service from eureka server is that, we deploy 3 application in dockers,we hope when we stop 
application from docker ,then the server of eureka server list will down immediately so that we 
will truly know that the application is down.
but now ,when we stop an application from docker, the server in eureka list will down  about 10 or long minutes. when we start application again, it can not register on eureka server.

**Comment by ryanjbaxter** [comment]
It should not take 10 minutes for the application to be removed from Eureka with the default settings, it should be a couple of minutes at most.  Also if you gracefully shut down the Eureka client it will deregister itself immediately so that you wouldnt have to wait.  I am still not sure what this has to do with self preservation mode.

**Comment by Leehom23** [comment]
> It should not take 10 minutes for the application to be removed from Eureka with the default settings, it should be a couple of minutes at most. Also if you gracefully shut down the Eureka client it will deregister itself immediately so that you would't have to wait. I am still not sure what this has to do with self preservation mode.

ok . According to the above configuration, when the application is shut down, about 1.5 minute later, it will leave from eureka server list. you said that i can shut down an eureka server, i don't know if the application can be removed immediately. but Unfortunately，**we don't use eureka cluster.** so in the production mode, i can not try it. tomorrow, i will build an eureka cluster, and shut down one of the eureka , guess if the application can remove immediately.(i guess application may not remove immediately, other eureka server may keep alive with application )

**Comment by spencergibb** [comment]
He's not talking about eureka cluster, but when you shut down a eureka client, it should de-register itself from eureka server.

**Comment by Leehom23** [comment]
> He's not talking about eureka cluster, but when you shut down a eureka client, it should de-register itself from eureka server.
ok. thank u. i just want to have a try.

**Comment by Leehom23** [comment]
the problem also occur in cluster status. and today i am testing....

**Comment by ryanjbaxter** [comment]
We no longer support Dalston, you will need to upgrade to Edgware at least.

**Comment by Leehom23** [comment]
> We no longer support Dalston, you will need to upgrade to Edgware at least.

ok，thank you for your suggestion.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
