### ISSUE TITLE
Update documentation for turbine.clusterNameExpression

### ISSUE THREAD

**Issue by habuma** [spring-cloud/spring-cloud-netflix#343]
When using 'default' as a value, you must use a weird set of quoting to ensure that "default" is treated as a string and not as a SpEL identifier. That is, you must set turbine.clusterNameExpression to "'default'".

While this is inconvenient and (as it stands) the documentation needs to be fixed to reflect this oddity, perhaps it would be better to default turbine.clusterNameExpression to 'default' so that the user doesn't have to deal with the weird use of quotes.

**Comment by trisberg** [comment]
also, the metadata.cluster expression doesn't seem to work for pulling the cluster name from the metadataMap. Tried metadata[cluster] and that worked, so we need to change the docs for this as well I think.

**Comment by spencergibb** [comment]
I think the docs need to change, but I think there is a lot of confusion about `turbine.clusterNameExpression`.  I doesn't need to be set unless you are trying to get the value from `metadata[cluster]`.  The default is `appName` and should just work.

**Comment by asaikali** [comment]
Docs are super confusing on this topic would be good to get it cleaned up, lot of stackoverflow questions about the meaning of turbine.clusterNameExpression

**Comment by OlgaMaciaszek** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
