### ISSUE TITLE
Hostname and port for Netflix Eureka if an application deployed on Tomcat

### ISSUE THREAD

**Issue by MarcoCeccotti** [spring-cloud/spring-cloud-netflix#3436]
I'm working with Zuul Gateway with Netflix Eureka and I'm deploying applications on a server Tomcat. The problem is that the applications runs on a server Tomcat and the host and port saved on Eureka registry are not the correct ones, so I don't know how set Zuul routes to load balancing requests. Is there a way to set a specific hostname and port from application.properties of the application deployed?

**Comment by spencergibb** [comment]
`eureka.instance.hostname` and `eureka.instance.non-secure-port` should be set.

**Comment by MarcoCeccotti** [comment]
Thanks for the quick answer! tomorrow i'll test the code and i'll give you a feed.

**Comment by MarcoCeccotti** [comment]
I tried the configuration, but i was not able to find a solution with Zuul.

Auth-server has the following eureka properties:

spring.application.name = auth-server
eureka.instance.hostname = 10.10.0.101
eureka.instance.non-secure-port: 18888

so i decided to set this route on zuul:

zuul.routes.auth-server = /oauth/**
zuul.routes.auth-server.serviceId = auth-server

but when i try to do a request passing through zuul i get a 500 error response.
Do I miss something on zuul's route?

**Comment by spencergibb** [comment]
Looks fine. I have no idea why the 500

**Comment by MarcoCeccotti** [comment]
From stacktrace it says that it can't find any server for client: auth-server.

**Comment by MarcoCeccotti** [comment]
Don't know if is important but in auth-server properties i set

server.port = 8060

**Comment by spencergibb** [comment]
Why? You said you set 18888 above?

**Comment by MarcoCeccotti** [comment]
That's true, but i set that property for using the app on localhost. Should i remove it?

**Comment by MarcoCeccotti** [comment]
Ok now using postman and sending request to oauth/login it shows a white response (or a not response, don't know how call it) and the PostFilter says 404. So i tried to understand why i receive that response, and i see that if i try to do a direct call to the oauth server with 10.10.0.101:18888/oauth/login i receive the white response, if instead i make this kind of call 10.10.0.101:18888/auth-server/oauth/login i receive the access token response. So, given that the auth-server application is deployed on Tomcat with war name of auth-server the call needs to specify the war file name on the path.
Is there a way to say to Zuul how to manage this kind of requests?

**Comment by spencergibb** [comment]
You'd have to write a custom filter. Spring Cloud Gateway has built in filters that could handle this.

**Comment by MarcoCeccotti** [comment]
I thought the same thing but i really don't know how.

**Comment by MarcoCeccotti** [comment]
I mean, i have this class:

`package it.marco.gateway.filter;

import java.util.Arrays;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cloud.netflix.zuul.filters.support.FilterConstants;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;

import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.SignatureException;
import io.jsonwebtoken.UnsupportedJwtException;
import it.marco.cloud.common.http.Type;
import it.marco.cloud.common.http.Widget;
import it.marco.cloud.common.http.WrapperResponse;
import it.marco.cloud.common.security.token.TokenDecoder;
import it.marco.cloud.common.utils.AuthUtils;
import it.marco.cloud.common.utils.ZuulUtils;

@Component
public class PreFilter extends ZuulFilter {

	private Logger log = LoggerFactory.getLogger(this.getClass());

	private WrapperResponse wrapper = new WrapperResponse();
	
	private TokenDecoder tokenDecoder = new TokenDecoder();

	private String tokenHeader;
	
	private String tokenType;
	private String requestURI;
	private String reportHeader;
	
	private List<String> headerValues;

	@Override
	public String filterType() {
		return FilterConstants.PRE_TYPE;
	}

	@Override
	public int filterOrder() {
		return 1;
	}

	@Override
	public boolean shouldFilter() {
		return true;
	}

	@Override
    public Object run() {
		final RequestContext context = RequestContext.getCurrentContext();
        final HttpServletRequest request = context.getRequest();

        log.info(String.format("%s request from %s to %s through user-agent %s", request.getMethod(), request.getRequestURL().toString(), request.getRemoteAddr(), request.getHeader("user-agent")));
    	
    	if(context.get("serviceId") != null) {
    		setErrorResponse(context, null, Arrays.asList("Invalid gateway request"), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 502, Arrays.asList(HttpStatus.BAD_GATEWAY));
    		return null;
    	}

    	requestURI = request.getRequestURI();
    	
    	// chiamata a swagger (lascio gestire all'applicazione stessa se la richiesta è permessa o meno)
    	if(requestURI.contains("/api-docs") || requestURI.contains("/swagger-ui")) {
    		return null;
    	}
    	
    	headerValues = null; tokenType = null; tokenHeader = AuthUtils.AUTHORIZATION;
    	
    	if(requestURI.contains("/oauth")) { // call to auth-server
    		headerValues = Arrays.asList(ZuulUtils.API_KEY, ZuulUtils.API_SECRET, ZuulUtils.COMPANY_ID);
    		
    		if(requestURI.contains("/refresh")) {
    			tokenType = AuthUtils.REFRESH;
    			tokenHeader = AuthUtils.REFRESH_TOKEN;
    		}
    	} else { // call to other services
    		headerValues = Arrays.asList(ZuulUtils.COMPANY_ID, ZuulUtils.SOURCE_ID);
    		tokenType = AuthUtils.ACCESS;
    	}

    	if(!checkToken(context, request.getHeader(tokenHeader), tokenType)) return null;
    	checkHeader(context, request);
        
        return null;
	}
	
	/**
	 * Checks the header values from request
	 * @param context the current context
	 * @param request the request
	 */
	private void checkHeader(RequestContext context, HttpServletRequest request) {
		reportHeader = "";
		for(String value : headerValues) {
			if(request.getHeader(value) == null) {
				reportHeader += value + ", ";
			}
		}
		
		reportHeader = reportHeader.substring(0, Math.max(0, reportHeader.length() - 2));
    	
    	if(!reportHeader.equals("")) {
			setErrorResponse(context, null, Arrays.asList("Missing " + reportHeader + " on header."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
	    }
	}
	
	/**
	 * Checks if the token is intact, valid and not expired.
	 * @param context the context
	 * @param token the header containing the token
	 * @param type the type of token to check
	 * @return false if token is not intact or valid <br> true otherwise
	 */
	private boolean checkToken(RequestContext context, String tokenHeader, String type) {
		
		if(type == null) {
			return true;
		}
		
		if(tokenHeader == null) {
			setErrorResponse(context, null, Arrays.asList(type + " Token missing."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
			return false;
		}
		
		String token = "";
		
		switch(type) {
	        case AuthUtils.ACCESS:  if(!tokenHeader.contains(AuthUtils.BEARER_PREFIX) || tokenHeader.split(" ").length != 2) {
										setErrorResponse(context, null, Arrays.asList("Invalid " + type + " Token."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
										return false;
									}
	        
									token = tokenHeader.split(" ")[1];
									break;
	                 		
	        case AuthUtils.REFRESH:  if(tokenHeader.trim().equals("")) {
						 			 	setErrorResponse(context, null, Arrays.asList("Invalid " + type + " Token."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
						 			 	return false;
						 			 }
	        
							 		 token = tokenHeader;
							 		 break;
		}
		
		try {
			tokenDecoder.decodeJwt(token);
		} catch (ExpiredJwtException exp) {	
			setErrorResponse(context, null, Arrays.asList(type + " Token expired."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
			return false;
		} catch (SignatureException | UnsupportedJwtException | MalformedJwtException | IllegalArgumentException exc) {
			setErrorResponse(context, null, Arrays.asList("Generic error on " + type + " Token."), Arrays.asList(Type.ERROR), Arrays.asList(Widget.ALERT), Arrays.asList(""), 400, Arrays.asList(HttpStatus.BAD_REQUEST));
			return false;
		}
		
		return true;
	}
	
	/**
	 * Sets the error response. The request is not re-routed to the requested service. Body response is filled with a WrapperResponse.
	 * @param context the current context
	 * @param payload the payload of the response
	 * @param msg the message to view
	 * @param type the error type
	 * @param widget the error widget
	 * @param severity the error severity
	 * @param code the code error
	 * @param httpStatus the status of http response
	 */
	private void setErrorResponse(RequestContext context, Object payload, List<String> msg, List<Type> type, List<Widget> widget, List<String> severity, int code, List<HttpStatus> httpStatus) {
		context.setSendZuulResponse(false);
		context.getResponse().setContentType("application/json;charset=UTF-8");
		context.setResponseStatusCode(code);
		context.setResponseBody(wrapper.createResponse(payload, msg, type, widget, severity, httpStatus).jsonBuilder().toString());
	}
}`

the main part is in run() method, where i check if the request contains or not the "/oauth" string.
I can I use the same code to add "auth-server/" before /oauth/login? is it possible?

**Comment by spencergibb** [comment]
Yes you can do that in your filter.

**Comment by MarcoCeccotti** [comment]
Can you please send me a snippet or similar for my situation? i tryed and searched everything but i was not able to do that. I need to implement it for work until this week-end and i'm desperated.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud-samples/sample-zuul-filters/blob/master/src/main/java/org/springframework/cloud/samplezuulfilters/QueryParamPortPreFilter.java

**Comment by MarcoCeccotti** [comment]
Seems interesting. I'll try it as soon as i can. Thank you very very much!

**Comment by MarcoCeccotti** [comment]
I used this code:

`
String uri = "/auth-server" + request.getRequestURI();            // generates the String "/auth-server/oauth/login"
URI myUri = URI.create(uri);        // creates an URI object based on previous uri String

try {
    URL url = UriComponentsBuilder.fromUri(myUri)
                                                         .host("10.10.0.101")
                                                         .port(18888)
                                                         .build()
                                                         .toUri()
                                                         .toURL();
    context.setRouteHost(url);
} catch {
    ReflectionUtils.rethrowRuntimeExcpetion(e);
}
`

the problem is that when the code reaches the toURL() method it throws an IllegalArgumentException. Is my code correct?

the request from Postman is a POST type with empty body and none parameters.

**Comment by spencergibb** [comment]
Looks fine, what is the exception?

**Comment by MarcoCeccotti** [comment]
I changed my code and it worked, later i'll post it for others who had the same problem. And, actually, i did not resolve my main problem, or the using ribbon for applications deployed on Tomcat. The problem is still that on the request i need to specify the war file name, and i can't deploy two applications with the same name.
