### ISSUE TITLE
ServoMetricCollector should poll monitors at frequency defined by Pollers.getPollingIntervals()

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#345]
Servo monitors have the concept of "instant": they collect information for a given time interval and output a summarised value only when the interval is over.
With this approach, the poller is supposed to query monitors for their value at the same rate. Doing faster is useless since the value won't have changed. Doing slower results in lost of information.

The servo integration provided by Spring Cloud polls servo monitors every 5 seconds ( see `org.springframework.cloud.netflix.servo.ServoMetricCollector`) whereas monitors are configured with a 60s instant by default (see `com.netflix.servo.monitor.Pollers.DEFAULT_PERIODS`).

Proposition is to make the `ServoMetricCollector` aware of the actual polling interval by querying `Pollers.getPollingIntervals()` and consider *first* value in the array.

**Comment by spencergibb** [comment]
Closing this as servo integration has changed dramatically. @brenuart let me know if you think otherwise.

**Comment by brenuart** [comment]
I'm fine with that. We are also in the process of removing servo from our platform because of its many problems.
