### ISSUE TITLE
Spring Webjars and Security redirects

### ISSUE THREAD

**Issue by ELIASIVANCARRILLO** [spring-cloud/spring-cloud-netflix#3485]
Hi

I have a Spring boot application MVC (Thymeleaf) using Spring Security that runs fine with the default login page and inMemory users. But when I set the application to work behind a Zuul reverse-proxy using Eureka registry, it behaves and redirects in a strange way. For example: 
http://zuulapp_ip/myapp       redirects to       http://nonproxiedapp_ip/login

As I know I have to use x-forward-headers but they need to be intercepted before Spring Security filters so that when Spring security redirects to /login, it can do the redirect behind the Zuul context.

I am not using server.context-path because it makes myapp no to be found in the Eureka server (the app is registered but when invoking behind Zuul, it is not found).

Some help would be great. Thanks

**Comment by spencergibb** [comment]
If security is on the `nonproxiedapp_ip` and it knows nothing about the proxy, why would it redirect anywhere else?

**Comment by ELIASIVANCARRILLO** [comment]
Hi

Thanks for replying. It has to be through the proxy because we have a K8S orchestrator and the entrypoint is the Zuul app, wich has the Domain Name as well as the TLS certs.

Thanks

**Comment by ryanjbaxter** [comment]
Sure but if Spring Security has no idea that it needs to redirect back through the proxy it is going to try to redirect back to the app itself.

**Comment by ELIASIVANCARRILLO** [comment]
Exactly

The question here is how let Spring Security to know it is behing a Zuul filter. I tried using a HandlerInterceptor and changing the filter order but it did not work.

**Comment by ryanjbaxter** [comment]
That is a question for the Spring Security team as there is nothing special about Spring Cloud Zuul, the same would be true for any proxy.
