### ISSUE TITLE
upgrade eureka to 1.2.0

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#349]
https://github.com/Netflix/eureka/releases/tag/v1.1.152
Will require changes because json is no longer rendered using xstream.

**Comment by spencergibb** [comment]
https://github.com/Netflix/eureka/releases/tag/1.1.153
Add's DI support!

**Comment by brenuart** [comment]
Hi Spencer,
Have you already started working on this?
It would be nice to upgrade at least up to 1.1.156 (and possibly even more recent versions) to benefit from other bug fixes that could provide a better user experience. I'm thinking about:

- https://github.com/Netflix/eureka/issues/539
Not a big issue but it introduces extra communication between the client and the server which makes hard to understand what is happening.

- https://github.com/Netflix/eureka/issues/533
Again, not a show stopper. But with this fix, we can now rely on a public method to feed the UI and report accurate status.

- https://github.com/Netflix/eureka/commit/0db1f58de2681cbddee84e6cac7e432c34aefe8c
They introduced a way to trigger the InstanceInfo replication immediately without having to wait for the next "InstanceInfoReplicator" run. This could help answering questions like https://github.com/spring-cloud/spring-cloud-netflix/issues/377

In general, they seem to have refactored their code in a way that could make the integration into SpringBoot a bit more easier. Logging has been improved as well. Not perfect though, but apparently slightly better...

**Comment by brenuart** [comment]
Hmmm... was a bit too fast: YES you already started working on the issue ;-)
So, when do you plan to release a new version with these changes?

**Comment by spencergibb** [comment]
I'm working on refactoring using their new refactor for dependency injection, that might be a while, but upgrading will probably be pretty simple in and of itself

**Comment by spencergibb** [comment]
actually I forgot the change to use jackson for json will require some work, so not quite as simple.  Upgrading and refactor to use DI should be separate issues.

**Comment by spencergibb** [comment]
https://github.com/Netflix/eureka/releases/tag/v1.1.157 has @brenuart's `CacheRefreshedEvent` and some other DI improvements.  This will make the change from xstream to jackson less painful because we won't have to try and shoehorn custom events in.
