### ISSUE TITLE
"Spring Cloud Loadblanacer" adoption with Spring Eureka Client - Greenwich Release

### ISSUE THREAD

**Issue by abjimmypro** [spring-cloud/spring-cloud-netflix#3495]
Question: We are making changes to do "Greenwich" rollout and having a concern about adopting Ribbon as this is now in maintenance mode and we are using "spring-cloud-netflix-eureka-client" for discovery client and client side load balancer.
Do we have an update or recommendation for the production ready of using "Spring Cloud Loadbalancer" along with "Spring Eureka Client" instead of Ribbon Client loadbalancer?

https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available#spring-cloud-netflix-projects-entering-maintenance-mode

**Comment by abjimmypro** [comment]
any suggestion/comment would help.

**Comment by OlgaMaciaszek** [comment]
Hello, @abjimmypro thanks for this issue - it's a valid question. While doing the switch to Greenwich, you should probably stick with this implementation for now. If you are using reactive web starter, you should already switch to using `@LoadBalancerClient` abstraction in place of `@RibbonClient` wherever appropriate. If you are using webmvc starters, watch this issue for when to make the switch on abstraction level: https://github.com/spring-cloud/spring-cloud-commons/issues/491 .  When it comes to the underlying implementation, there's still more work to do on our side. Watch this issue for updates: https://github.com/spring-cloud/spring-cloud-commons/issues/553 . We will definitely keep maintaining the current stack until we can offer a production-ready replacement.
