### ISSUE TITLE
spring-cloud-netflix-hystrix-contract snapshots not deploying from jenkins

### ISSUE THREAD

**Issue by Rick-ye** [spring-cloud/spring-cloud-netflix#3497]
Failure to find xxx.jar/xxx in repo.spring.io ,look at the following.
And pom.xml error : the version is missing. Plugin execution not covered by lifecycle configuration and so on.

I try my best.but i can't. help me please;   Thanks!!!!

Unresolveable build extension: Plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.1.RELEASE or one of its dependencies could not be resolved: Failure to find org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.2.0.BUILD-SNAPSHOT in https://repo.spring.io/libs-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced @

**Comment by spencergibb** [comment]
This is likely a problem with your environment. Not sure what we can do.

**Comment by Rick-ye** [comment]
what is the problem with my enivronment.
my ide is STS. maven's version is 3.3.9. looks like my maven has some problem.
all the question is in the pom.xml

**Comment by spencergibb** [comment]
We don't support maven 3.3.9

**Comment by Rick-ye** [comment]
so what version do u support??

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/.mvn/wrapper/maven-wrapper.properties

3.5.x 

Is there a reason you aren't using the wrapper?

**Comment by Rick-ye** [comment]
yeah  looks like that reason.
i used the mvn eclipse:eclipse before. now i use maven 3.5.2 and ./mvnw eclipse:eclipse. looks like work

**Comment by Rick-ye** [comment]
Could not find artifact org.springframework.cloud:spring-cloud-netflix-hystrix-contract:jar:2.2.0.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/libs-snapshot-local)

again this problem

**Comment by Rick-ye** [comment]
find the question : there is no spring-cloud-netflix-hystrix-contract:2.2.0.BUILD-SNAPSHOT/ in https://repo.spring.io/libs-snapshot-local,only have 2.0.0.BUILD-SNAPSHOT and 1.4.0.BUILD-SNAPSHOT

**Comment by spencergibb** [comment]
It's there now.

**Comment by spencergibb** [comment]
We should also document how to build that module on the readme.

**Comment by ryanjbaxter** [comment]
Added deploy goal in https://github.com/spring-cloud/spring-cloud-jenkins-jobs/commit/e2cb807e6579bdc2ee15e40ae5f3cdae47d80ff8
