### ISSUE TITLE
UnsatisfiedDependencyException: missing SpringClientFactory

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#35]
http://stackoverflow.com/questions/26450251/having-an-issue-with-launching-spring-cloud-hystrix-dashboard-example

Trying to use spring-cloud-starter-hystrix-dashboard and @EnableHystrixDashboard

see https://github.com/spencergibb/communityanswers/tree/so26450251 for a sample application

The work around is to add `@EnableEurekaClient`

**Comment by hddm** [comment]
I am trying to only use ZuulProxy and there seems to be the same SpringClientFactory dependency problem in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/ZuulProxyConfiguration.java

**Comment by dsyer** [comment]
Ribbon is optional. Please open another issue if you think it should be even more optional.
