### ISSUE TITLE
Zuul Proxy forwarding

### ISSUE THREAD

**Issue by Raj1071** [spring-cloud/spring-cloud-netflix#3501]
How Zuul use ribbon for each microservices instance load balancing, does it realted to zuul proxy if not what is zuul proxy 
@ryanjbaxter sir please let me know how does load balancing happen using zuul how does zuul uses the ribbon?

**Comment by ryanjbaxter** [comment]
This is all explained in our documentation http://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#netflix-zuul-starter

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
