### ISSUE TITLE
System environment variable EUREKA_CLIENT_SERVICEURL_DEFAULTZONE does not work

### ISSUE THREAD

**Issue by emilnkrastev** [spring-cloud/spring-cloud-netflix#3502]
Hi,

I'm observing the following weird cases:
1.Running Eureka client with System environment variable EUREKA_CLIENT_SERVICEURL_DEFAULTZONE does not work, if there is no eureka.client.serviceUrl.defaultZone property in the application/bootstrap.yml. It still searches for the default discovery host - localhost:8761.

2.Running the eureka client app with -Deureka.client.serviceUrl.defaultZone or System env eureka.client.serviceUrl.defaultZone successfully overrides the default discovery host.

Why the System env variable EUREKA_CLIENT_SERVICEURL_DEFAULTZONE does not work? Is this expected behavior?

Example repository:
https://github.com/emilnkrastev/eureka-client

**Comment by ryanjbaxter** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/2541
