### ISSUE TITLE
will ribbon not be maintained by spring cloud?

### ISSUE THREAD

**Issue by wenweihu86** [spring-cloud/spring-cloud-netflix#3509]
will ribbon not be maintained by spring cloud?
I want to know ribbon future plans.

thank you

**Comment by spencergibb** [comment]
Ribbon is from netflix. See it's status here: https://github.com/Netflix/ribbon#project-status-on-maintenance

For the maintainence of the spring cloud netflix ribbon module, see here https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available#spring-cloud-netflix-projects-entering-maintenance-mode
