### ISSUE TITLE
How can I get the value of  @FeignClient in Aspect

### ISSUE THREAD

**Issue by JAXma1996** [spring-cloud/spring-cloud-netflix#3510]
Show code firstly ：
**UserProfileFeignClient** :
`@FeignClient(
    value = "userprofile-async-msa",
    configuration = {UserprofileFeignConfiguration.class}
)
public interface UserProfileFeignClient extends UserProfileAsyncService {
}
`
**UserProfileAsyncService**: 
`public interface UserProfileAsyncService {
//define  methods
    @RequestMapping(
        value = {"/v3/users/tags"},
        method = {RequestMethod.GET}
    )
    MsaResp<Map<String, Object>> queryUserTags(@RequestParam("imei") String var1, @RequestParam("tags") String var2);
}
`
**My Aspect PointCut** ：
`@Pointcut(value = "execution(* cn.jiguang.data.permission.feign.DmpAPIPermissionFeignClient.*(..))")
    public void userProfilePointCut(){
    }
`

Now I want get the value of @FeignClient on my Aspect. When i use jointPoint.getTarget() ,I can only get a proxy object.

**Comment by spencergibb** [comment]
Feign clients are proxies.

**Comment by JAXma1996** [comment]
> Feign clients are proxies.

Of cause I know。
