### ISSUE TITLE
what is the param app-group-name in Eureka use for?

### ISSUE THREAD

**Issue by dex268** [spring-cloud/spring-cloud-netflix#3512]
I am confused about the app-group-name param is for what.  Is it just a tag to identify groups which does not contribute to any load balance logic in ribbon?
I intend to implement custom Ribbon com.netflix.loadbalancer.ServerListFilter which use such param to  achieve logical separation with the same application name.

_Originally posted by @dex268 in https://github.com/spring-cloud/spring-cloud-netflix/issues/3141#issuecomment-485311845_

**Comment by ryanjbaxter** [comment]
I believe this question would better be asked in the Netflix Eureka project.  I don't think Spring Cloud Netflix does anything with `app-group-name`.
