### ISSUE TITLE
RefreshAutoConfiguration make JndiTemplate intialize failed.

### ISSUE THREAD

**Issue by chp008** [spring-cloud/spring-cloud-netflix#3516]

**Comment by spencergibb** [comment]
Please as description, along with versions used and how to recreate the problem.

**Comment by chp008** [comment]
Spring boot: 2.0.8.Release.
we have an applicationContext.xml to define the beans. 
<bean id="jnditemplate" class="jnditemplate">
  <property name="environment">
			<props>
				<prop key="java.naming.provider.url">${xxx.host.provider.url}</prop>
                        </props>
  </property>
</bean>
If we only use the spring boot, it would be fine.  the spring boot can be started up correctly. 
Since I want to introduce the feign. so I introduce the 
compile("org.springframework.cloud:spring-cloud-starter-openfeign")
Then when I start it up:
the application will say: the JndiTemplate create InitialContext is failed.  because the property passing into it is still ${xxxxx.xxx}
	protected Context createInitialContext() throws NamingException {
		Hashtable<?, ?> icEnv = null;
		Properties env = getEnvironment();
		if (env != null) {
			icEnv = new Hashtable<>(env.size());
			CollectionUtils.mergePropertiesIntoMap(env, icEnv);
		}
		return new InitialContext(icEnv);
	}
I checked that when the application started, the application context will invokeBeanDefinitionRegistryPostProcessors which will trigger the RefreshAutoConfiguration-> postProcessBeanDefinitionRegistry.  it will loop all the beans & create the bean   jnditemplate. but when it createInitialContext(), the enviroment passing into it contains the {xxx}.

If I disable it. it will work 
//@SpringBootApplication(exclude = { RefreshAutoConfiguration.class })

**Comment by spencergibb** [comment]
I need the version of spring cloud as well

**Comment by chp008** [comment]
I have updated it.

**Comment by spencergibb** [comment]
Do you only add the feign dependency or do you create a client?

**Comment by chp008** [comment]
I only add the feign dependency , I have not create any client.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by chp008** [comment]
This issue can be easily reproduce by the following step:
1: maven dependency
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
2: application.xml
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:aop="http://www.springframework.org/schema/aop" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:jee="http://www.springframework.org/schema/jee" xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:task="http://www.springframework.org/schema/task"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:cache="http://www.springframework.org/schema/cache" 
	xmlns:jms="http://www.springframework.org/schema/jms"
	xsi:schemaLocation="http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.2.xsd         http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd         http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd         http://www.springframework.org/schema/jee http://www.springframework.org/schema/jee/spring-jee-3.2.xsd         http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.2.xsd http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task-3.0.xsd http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache.xsd http://www.springframework.org/schema/jms http://www.springframework.org/schema/jms/spring-jms-2.5.xsd ">

 <context:property-placeholder order="1" location="classpath:database.properties"/>

 
 
 <bean id="JndiTemplate" class="org.springframework.jndi.JndiTemplate">
		<property name="environment">
			<props>
				<prop key="java.naming.factory.initial">${factory.initial}</prop>
			</props>
		</property>
	</bean>
	
   <bean id="ConnectionFactory" class="org.springframework.jndi.JndiObjectFactoryBean"  >
		<property name="jndiTemplate" ref="JndiTemplate" />
		<property name="jndiName" value="${connection.factory}" />
   </bean>
	
  <bean id="CachingConnectionFactory" class="org.springframework.jms.connection.CachingConnectionFactory" >
		<constructor-arg ref="ConnectionFactory" />
		<property name="reconnectOnException" value="true" />
		<property name="sessionCacheSize" value="1" />
  </bean>
</beans>`
3: properties:
factory.initial=org.apache.activemq.jndi.ActiveMQInitialContextFactory123
connection.factory=123test

if you look at the createInitialContext Method in the JNDITemplate, you can see the properties is not been parsed into the value in the properties.

**Comment by spencergibb** [comment]
If you'd like us to investigate please

> Can you provide a complete, minimal, verifiable sample that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by chp008** [comment]
please see my code here: https://github.com/chp008/issues/tree/issue_01
this issue is only happing in Finchley.RELEASE. it will not be an issue in Greenwich.RELEASE.
Reproduce:
set a debug here in JNDITemplate. to see the property value 
public void setEnvironment(@Nullable Properties environment) {
		this.environment = environment;
	}

**Comment by spencergibb** [comment]
Finchley is no longer supported. please upgrade
