### ISSUE TITLE
Spring Boot Actuator Endpoint ID for hystrix.stream shall be alphanumeric in Boot > 2.1

### ISSUE THREAD

**Issue by andreschaefer** [spring-cloud/spring-cloud-netflix#3524]
Enhancement

Spring Boot changed the actuator endpoint id policy in 2.1. 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#endpoint-id-names

A warning is logged according to the new policy. 
`o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'hystrix.stream' contains invalid characters, please migrate to a valid format.`

The ID of `org.springframework.cloud.netflix.hystrix.HystrixStreamEndpoint` and `org.springframework.cloud.netflix.hystrix.HystrixWebfluxEndpoint` shall be adjusted to align with the new policy.

**Comment by spencergibb** [comment]
Thanks, we know. I believe this is a duplicate.

**Comment by andreschaefer** [comment]
I was looking for it since I thought I'm most likely not the first recognizing it.
But I couldn't find any.

**Comment by ryanjbaxter** [comment]
Same problem just different project https://github.com/spring-cloud/spring-cloud-commons/issues/458

We should probably keep this open for now so we change it here as well.

**Comment by ryanjbaxter** [comment]
There is an issue open in Boot to help provide a solution https://github.com/spring-projects/spring-boot/issues/18148

**Comment by ryanjbaxter** [comment]
Closing this issue in favor of the spring-cloud-commons issue
