### ISSUE TITLE
zuul cause tomcat memory leak

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-cloud/spring-cloud-netflix#3538]
22-May-2019 13:11:45.192 SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [cloud-admin] created a ThreadLocal with key of type [com.netflix.zuul.context.RequestContext$1] (value [com.netflix.zuul.context.RequestContext$1@4c12ac25]) and a value of type [com.netflix.zuul.context.RequestContext] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by spencergibb** [comment]
This would need to change in zuul proper.
