### ISSUE TITLE
Eureka client registration failing (with different spring cloud version)

### ISSUE THREAD

**Issue by venkatesh010** [spring-cloud/spring-cloud-netflix#3539]
Hi,
Facing issues in using eureka client and eureka servers with different spring cloud version 

Eureka client 
Spring.cloud.version - Dalston.Release
Spring boot - 1.5.7.release

Eureka server
Spring.cloud.version - Greenwich.release
Spring boot - 2.1.3.release

Getting following errors:
Eureka Server : 
Facing 
DS: Registry lease doesn't exist, registering resource: <serviceId>

Eureka client :
Registration failed cannot execute request on any known server

Tried debug with property in yml still no exact cause shown

Any incompatibility between the two versions? 
Need suggestions?

**Comment by venkatesh010** [comment]
Can we have different versions of spring cloud and different version of spring-cloud-netflix-eureka-client dependency by doing exclusion in pom from starter and including independent dependencies ??

Tried that but it's not working
Application starts up without trying to register i.e. no eureka client detected

**Comment by OlgaMaciaszek** [comment]
Hi @venkatesh010 the Dalston release train is not supported anymore.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by venkatesh010** [comment]
Okay, i've found a workaround for it thanks
