### ISSUE TITLE
DefaultServoNamingStrategy considers dots as invalid character and replace them with an underscore

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#354]
The `DefaultServoNamingStrategy` introduced recently considers dots as invalid character and replace them with an underscore. This behaviour differs from the previous implementation where Servo metric names with dots were accepted as valid names.

Why is it so?

Suppose I want to write a `MonitoringServletFilter` similar to the one provided by SpringBoot but with Servo metrics instead. For a request to /admin/metrics, I will get:
````
# Metric produced by SB GaugeService
gauge.response.admin.metrics: 25,

# Metrics produced by Servo
gauge.servo.response_admin_metrics.max: 0,
gauge.servo.response_admin_metrics.min: 0,
gauge.servo.response_admin_metrics.count: 0,
gauge.servo.response_admin_metrics.totaltime: 0,
````

Looks strange and pretty annoying since it doesn't allow us to structure our servo metrics anymore.

**Comment by spencergibb** [comment]
mostly because it was in the sample fix you provided a link to.  Easy to change.  PR?

**Comment by brenuart** [comment]
Indeed. You are right... Haven't noticed it before.

At the end, it is a question of what default naming strategy you want to incorporate in your code base (people can override it anyway). However, I still believe people using Servo should be able to record metrics with dots in the names, just like with the standard Gauge or CounterServices.

Are you still ok with this?
If so, I'll submit a PR with a proposed fixed.

**Comment by spencergibb** [comment]
yup, go for it.
