### ISSUE TITLE
Eureka Server - Java 11

### ISSUE THREAD

**Issue by norricorp** [spring-cloud/spring-cloud-netflix#3541]
Continuation of #3391 which is closed.
Does the update in the docs for the extra dependencies with java 11 also require

> 		<dependency>
> 			<groupId>javax.activation</groupId>
> 			<artifactId>activation</artifactId>
> 			<version>1.1.1</version>
> 		</dependency>

I added the dependencies that are in the link but continued to get problems running embedded tomcat because of missing dependency
ERROR 12812 --- [ main] o.a.c.c.C.[Tomcat].[localhost].[/] : Exception starting filter [servletContainer]
java.lang.NoClassDefFoundError: javax/activation/DataSource
at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.(RuntimeBuiltinLeafInfoImpl.java:478) ~[jaxb-impl-2.3.0.jar!/:2.3.0]
etc etc etc

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by norricorp** [comment]
Created project https://github.com/norricorp/sb_eureka_java11
For commit 214e5b8, tomcat will not start - see java_output.txt for errors.
In commit 6012a13 added activation dependency in pom, now tomcat starts and can bring up eureka server in browser.

**Comment by spencergibb** [comment]
The commit you referenced had outdated information. The current documentation is correct https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#jdk-11-support

```
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>
```
is the only dependency you need.
