### ISSUE TITLE
Why not provide andThreadPoolKey in HystrixObservableCommand?

### ISSUE THREAD

**Issue by hooverhe** [spring-cloud/spring-cloud-netflix#3544]
HystrixObservableCommand doesn't provide the "public Setter andThreadPoolKey(HystrixThreadPoolKey threadPoolKey)" method in HystrixObservableCommand? But HystrixCommand provides it. Please refer the same issue : spring-cloud/spring-cloud-gateway#1080

**Comment by OlgaMaciaszek** [comment]
Hello, @hooverhe `HystrixObservableCommand` is from the package `com.netflix.hystrix`. It's not part of the Spring Cloud integration, but it's part of the core Hystrix library maintained by Netflix. You should report any issues related to it in [this repo](https://github.com/Netflix/Hystrix).
