### ISSUE TITLE
Proxying not working if endpoint is defined in a COntroller and for other HTTP methods Zuul is not proxying

### ISSUE THREAD

**Issue by amit2103** [spring-cloud/spring-cloud-netflix#3549]
I am using 2.1.1.RELEASE version
We have a Service lets say Service 1 which has two URLS for /order with PUT and POST http method
We have a gateway service which defines a endpoint /order in a controller and for any other HTTP methods calls is supposed to proxy to  Service 1. Now When I try to POST or PUT to orders via Zuul I am getting a 405 method not found error. When I delete the endpoint in the gateway service all proxying works fine, in fact for other URLS like /bar etc all proxying is working . I am guessing because of me defining an endpoint explicitly in a controller. Is there some work around for this ?

**Comment by spencergibb** [comment]
yeah, I'm sure you have some conflict. The controller will win.

**Comment by amit2103** [comment]
The controller only defines a GET method... No POST..NO PUT ..They are defined in the backend Service.
However when trying to call a POST , I am getting 405. Is there any work around ?

**Comment by spencergibb** [comment]
Do you know where the 405 is originating?

**Comment by amit2103** [comment]
It seems to be coming from the dispatcher servlet

**Comment by spencergibb** [comment]
In the gateway or service?

**Comment by amit2103** [comment]
In the gateway. It’s not hitting the service

**Comment by spencergibb** [comment]
Then it is winning, not sure what to say to that. You could change the mapping in the controller and use a `forward:/` url to the local controller and let zuul deal with the `/order` mapping. https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html#_strangulation_patterns_and_local_forwards

**Comment by amit2103** [comment]
So basically the gateway cannot have an /order endpoint ?

**Comment by spencergibb** [comment]
The dispatcher servlet has precedence. What else do you want me to say?

**Comment by amit2103** [comment]
Mono no matter that’s fine . I just wanted to be sure that without changing
URLs it won’t work that’s it.
