### ISSUE TITLE
Not able to add ClientFilter for eureka replication client

### ISSUE THREAD

**Issue by LittleBaiBai** [spring-cloud/spring-cloud-netflix#3554]
Since Netflix Eureka 1.9.10 (https://github.com/Netflix/eureka/releases/tag/v1.9.10), it's possible to add additional filters to an existing JerseyReplicationClient. 

To do so, `RefreshablePeerEurekaNodes` needs to override `createPeerEurekaNode()` and add additional filters once the JerseyReplicationClient is created.

**Comment by venkatesh-007** [comment]
@LittleBaiBai  can you elaborate this?
Any articles or info will be appreciated

**Comment by venkatesh-007** [comment]
@spencergibb  any workaround for this for older eureka versions
I've to use it with eureka-core-1.6.2, any way to fork JerseyReplicationClient implementation

**Comment by spencergibb** [comment]
No articles or info or any workarounds that I know of.

**Comment by LittleBaiBai** [comment]
@venkatesh-007 If you really need to use `eureka-core-1.6.2`, I believe you will have to do some unfortunate reflections like this:
```
	@Bean
	public PeerEurekaNodes peerEurekaNodes(PeerAwareInstanceRegistry registry,
										   ServerCodecs serverCodecs,
										   ApplicationInfoManager applicationInfoManager,
										   EurekaServerConfig eurekaServerConfig,
										   EurekaClientConfig eurekaClientConfig) {
		return new PeerEurekaNodes(registry, eurekaServerConfig,
			eurekaClientConfig, serverCodecs, applicationInfoManager) {
			@Override
			protected PeerEurekaNode createPeerEurekaNode(String peerEurekaNodeUrl) {
				PeerEurekaNode peerEurekaNode = super.createPeerEurekaNode(peerEurekaNodeUrl);
				JerseyReplicationClient replicationClient = getField(PeerEurekaNode.class,
					peerEurekaNode, "replicationClient");
				ApacheHttpClient4 jerseyApacheClient = getField(JerseyReplicationClient.class,
					replicationClient, "jerseyApacheClient");
				jerseyApacheClient.addFilter(new YourCustomClientFilter()));
				return peerEurekaNode;
			}
		};
	}
```

**Comment by venkatesh-007** [comment]
Thanks @LittleBaiBai
Also are there any disadvantages for running a eureka server(service registry) over http (non ssl) in production?

In case my requirement is to use it on a on-premise setup(on premise cloud or vsis)
Only disadvantage I thought of is any client can register to it(one of possible attacks by having many clients) but that can be prevented by blocking http port for others 

Does service discovery(eureka server) provides access to any resources of eureka clients apart from metadata(heathcheckUrl, statusCheckUrl etc given by eureka client)?
(I don't think it does) 

@spencergibb @ryanjbaxter @LittleBaiBai @dsyer, any views will be appreciated

**Comment by ryanjbaxter** [comment]
I don't believe so (unless the client is publishing something in its metadata)
