### ISSUE TITLE
为什么熔断策略、隔离策略无法全局配置，必须每个接口对应自己的熔断、隔离策略。设计的初衷是什么？

### ISSUE THREAD

**Issue by bestLibra** [spring-cloud/spring-cloud-netflix#3560]
为什么熔断策略、隔离策略无法全局配置，必须每个接口对应自己的熔断、隔离策略。设计的初衷是什么？

**Comment by spencergibb** [comment]
Can you please post an English translation?

**Comment by eacdy** [comment]
@bestLibra 
You Can config either globally or for just per hystrixcommand.
doc: https://github.com/Netflix/Hystrix/wiki/Configuration#thread-or-semaphore

eg.
If you Want to set isolation strategy to semaphore globally, try :
`hystrix.command.default.execution.isolation.strategy = semaphore`

If you want to config fine grain, try:
`hystrix.command.<HystrixCommandKey>.execution.isolation.strategy = semaphore`

You Can find HystrixCommandKey on Hystrix Dashboard.

**Comment by eacdy** [comment]
@spencergibb I've translated for him.
Why we cannot config the circuit strategy or isolation strategy globally?
Do we must set the strategy for each interface?
What's the original intention of the design?

**Comment by ryanjbaxter** [comment]
I dont understand you can configure the isolation strategy globally or on a per circuit breaker basis
