### ISSUE TITLE
Feign transforms querystring incorrectlly

### ISSUE THREAD

**Issue by dragon753** [spring-cloud/spring-cloud-netflix#3562]
I have a python api deployed with sidecar, which takes querystring parameters like this:
`id=1&current_page=1`

when I call this api with a Feign client using this method
`
@RequestMapping(value = "my_api", method = RequestMethod.GET)
    Response<?> getServers(@RequestParam("id") Integer userId,
                                         @RequestParam("current_page") Integer page);
`

the request the python api got is 
`id=1¤t_page=1`

not sure about other keywords.

**Comment by spencergibb** [comment]
That doesn't make much sense to me. We have tests for that.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by dragon753** [comment]
Please clode it, I cannot get the code of the sidecar project with which I get this issue, and cannot reproduce this this my own sidecar, thk for your time.
