### ISSUE TITLE
I want set non-secure-port to 80

### ISSUE THREAD

**Issue by jyzhangbo** [spring-cloud/spring-cloud-netflix#3569]
When I set the non-secure-port as 80,as the same time I set server.port = 8081,the result that the non-secure-port  is set as 8081.
How can I set the non-secure-port as 80 and server.port as 8081.

**Comment by ryanjbaxter** [comment]
Why are they not the same?

**Comment by jyzhangbo** [comment]
@ryanjbaxter  On my local machine,if I set eureka address as test environment, other machines in the test environment will access my locality, but the test environment is not accessible to my local area.So I want to set my local instance config to hostname of test service,other machines in the test environment won't visit my local place.
If I start one project on my local machine,I can set the server.port as 80,  but when I have multiple services to start,I must set the server.port difference。
I think that we have the nonSecurePort config,when we set it up separately,let it work.

**Comment by ryanjbaxter** [comment]
I think we assume that whatever `server.port` is set to, that is going to be the `non-secure-port` value.  I don't think there is a way to separate the two at the moment.
