### ISSUE TITLE
restTemplate for eureka client failed to change status

### ISSUE THREAD

**Issue by q605450469** [spring-cloud/spring-cloud-netflix#3571]
I use Eureka Client with RestTemplate instead of Jersey, and send a post request to change status by use the rest api. but i find it doesn't work. And I find the client code in `RestTemplateEurekaHttpClient`:
```
public EurekaHttpResponse<Void> statusUpdate(String appName, String id, InstanceStatus newStatus, InstanceInfo info) {
        String urlPath = this.serviceUrl + "apps/" + appName + '/' + id + "?status=" + newStatus.name() + "&lastDirtyTimestamp=" + info.getLastDirtyTimestamp().toString();
        ResponseEntity<Void> response = this.restTemplate.exchange(urlPath, HttpMethod.PUT, (HttpEntity)null, Void.class, new Object[0]);
        return EurekaHttpResponse.anEurekaHttpResponse(response.getStatusCodeValue()).headers(headersOf(response)).build();
    }
```

but the server-side code like this  `InstanceResource`:
```
@PUT
    @Path("status")
    public Response statusUpdate(@QueryParam("value") String newStatus, @HeaderParam("x-netflix-discovery-replication") String isReplication, @QueryParam("lastDirtyTimestamp") String lastDirtyTimestamp) {
        try {
            if (this.registry.getInstanceByAppAndId(this.app.getName(), this.id) == null) {
                logger.warn("Instance not found: {}/{}", this.app.getName(), this.id);
                return Response.status(Status.NOT_FOUND).build();
            } else {
                boolean isSuccess = this.registry.statusUpdate(this.app.getName(), this.id, InstanceStatus.valueOf(newStatus), lastDirtyTimestamp, "true".equals(isReplication));
                if (isSuccess) {
                    logger.info("Status updated: " + this.app.getName() + " - " + this.id + " - " + newStatus);
                    return Response.ok().build();
                } else {
                    logger.warn("Unable to update status: " + this.app.getName() + " - " + this.id + " - " + newStatus);
                    return Response.serverError().build();
                }
            }
        } catch (Throwable var5) {
            logger.error("Error updating instance {} for status {}", this.id, newStatus);
            return Response.serverError().build();
        }
    }
```
I debug the code and find the request like this:
```
http://127.0.0.1:8761/eureka/apps/TEST.SERVICE.LOCAL/127.0.0.1:test.service.local:8106?status=OUT_OF_SERVICE&lastDirtyTimestamp=1560997426052
```
Is this a bug？

**Comment by spencergibb** [comment]
Can we step back before analyzing code and tell us what you are trying to do and what goes wrong? Are you using RestTemplateEurekaHttpClient directly? If so you really should be using EurekaClient.

"Doesn't work" isn't an effective bug report.

**Comment by q605450469** [comment]
> Can we step back before analyzing code and tell us what you are trying to do and what goes wrong? Are you using RestTemplateEurekaHttpClient directly? If so you really should be using EurekaClient.
> 
> "Doesn't work" isn't an effective bug report.

Sorry, I may not have made myself clear. I mean I have a springCloud project, and  I remove the Jersey dependencies. And I want to change the status of my project in eureka from `up` to `out_of_service`. so I sent a post request to change it ,like this:
`curl -X POST -H "Content-Type: application/json" -d 'out_of_service' 'http://127.0.0.1:9999/service-registry/instance-status'`
in other project, it work, but in this project that removed the Jersey dependencies, it doesn't work.
the status is still `up` in eureka.
so I analyzing code try to find the answer. And I find the rest API actually invoke other rest API by eureka server provided.
InstanceResource.class in eureka-core.jar:
```
@PUT
    @Path("status")
    public Response statusUpdate(@QueryParam("value") String newStatus, @HeaderParam("x-netflix-discovery-replication") String isReplication, @QueryParam("lastDirtyTimestamp") String lastDirtyTimestamp) {
        try {
            if (this.registry.getInstanceByAppAndId(this.app.getName(), this.id) == null) {
                logger.warn("Instance not found: {}/{}", this.app.getName(), this.id);
                return Response.status(Status.NOT_FOUND).build();
            } else {
                boolean isSuccess = this.registry.statusUpdate(this.app.getName(), this.id, InstanceStatus.valueOf(newStatus), lastDirtyTimestamp, "true".equals(isReplication));
                if (isSuccess) {
                    logger.info("Status updated: " + this.app.getName() + " - " + this.id + " - " + newStatus);
                    return Response.ok().build();
                } else {
                    logger.warn("Unable to update status: " + this.app.getName() + " - " + this.id + " - " + newStatus);
                    return Response.serverError().build();
                }
            }
        } catch (Throwable var5) {
            logger.error("Error updating instance {} for status {}", this.id, newStatus);
            return Response.serverError().build();
        }
    }
```
And eureka client use Jersey invoke it by default. if eureka client exclude the Jersey dependencies, it will communicate with eureka server by restTemplate.But I find the request url is wrong when I use restTemlate invoke it. 
And the request is build by `RestTemplateEurekaHttpClient`:
```
public EurekaHttpResponse<Void> statusUpdate(String appName, String id, InstanceStatus newStatus, InstanceInfo info) {
        String urlPath = this.serviceUrl + "apps/" + appName + '/' + id + "?status=" + newStatus.name() + "&lastDirtyTimestamp=" + info.getLastDirtyTimestamp().toString();
        ResponseEntity<Void> response = this.restTemplate.exchange(urlPath, HttpMethod.PUT, (HttpEntity)null, Void.class, new Object[0]);
        return EurekaHttpResponse.anEurekaHttpResponse(response.getStatusCodeValue()).headers(headersOf(response)).build();
    }
```
so I want to reconfirm that is it a bug or I am using it the wrong way？

thanks.

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud?

**Comment by q605450469** [comment]
<spring-cloud.version>Edgware.SR1</spring-cloud.version>
<spring-cloud-starter-netflix-eureka-client>1.4.2.RELEASE</spring-cloud-starter-netflix-eureka-client>

**Comment by ryanjbaxter** [comment]
Please try Edgware.SR6

**Comment by q605450469** [comment]
still no good
I look up this class `RestTemplateEurekaHttpClient ` in all version, They all look the same.

**Comment by yuwzho** [comment]
The [eureka REST API](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations) gives the url like 
`PUT /eureka/v2/apps/appID/instanceID/status?value=OUT_OF_SERVICE` which works with Postman. While the client make the REST call as
`PUT /eureka/v2/apps/appID/instanceID?status=OUT_OF_SERVICE`

I am not sure why this API still returns 200 OK without any change in Eureka Server side
