### ISSUE TITLE
refresh zuul.host property not working

### ISSUE THREAD

**Issue by billnote** [spring-cloud/spring-cloud-netflix#3573]
Question:
refresh zuul.host property not working. 
first  change the “zuul.host.socket-timeout-millis” value, then I send request to zuul 
"/actuator/refresh". zuul return ok, but the value not working.

ENV:
Spring Boot: 2.0.5.RELEASE
Spring Cloud Version: Finchley.SR2

Possible Reason:
SimpleHostRoutingFilter.onPropertyChange  execute before then ConfigurationPropertiesRebinder.onApplicationEvent;
So SimpleHostRoutingFilter.this.hostProperties also has the old value. 
Is I missed some thing?

**Comment by ryanjbaxter** [comment]
Can Greenwich.SR2 and let us know if you can reproduce it?

**Comment by billnote** [comment]
Greenwich.SR2 does not have this problem, I will close this issues.
