### ISSUE TITLE
JDK 11 on Spring Cloud Netflix 2.1

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#3574]
Spring Boot supports JDK 11 since 2.1, so we probably need to add the jaxb dependency to the eureka starter in 2.1 (like in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-starter-netflix/spring-cloud-starter-netflix-eureka-server/pom.xml#L37).

See also #3541

**Comment by spencergibb** [comment]
Closed via 5741326cb5f2400d0721718a61303c4b83e7d594
