### ISSUE TITLE
How to change HttpClient to OkHttp in Zuul, and use OkHttp async?

### ISSUE THREAD

**Issue by Lovnx** [spring-cloud/spring-cloud-netflix#3583]
Spring Cloud version: Edgware.SR6

I tried to override OkHttpLoadBalancingClient.java

` @Override
    public OkHttpRibbonResponse execute(OkHttpRibbonRequest ribbonRequest,
                                        final IClientConfig configOverride) throws Exception {
        boolean secure = isSecure(configOverride);
        if (secure) {
            final URI secureUri = UriComponentsBuilder.fromUri(ribbonRequest.getUri())
                    .scheme("https").build().toUri();
            ribbonRequest = ribbonRequest.withNewUri(secureUri);
        }

        OkHttpClient httpClient = getOkHttpClient(configOverride, secure);
        final Request request = ribbonRequest.toRequest();
        final Response[] responses = {null};

        Call call =  httpClient.newCall(request);
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                responses[0] = response;
            }
        });

        return new OkHttpRibbonResponse(responses[0], ribbonRequest.getUri());
    }`

So, How does it work?

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#_zuul_http_client

**Comment by Lovnx** [comment]
I find key words form the doc you provide：
` If you would like to customize the Apache HTTP client or the OK HTTP client, provide a bean of type ClosableHttpClient or OkHttpClient`

but, how can I define a new OkHttpClient and add it to Spring life cycle?

**Comment by ryanjbaxter** [comment]
Create a bean that returns the type `OKHttpClient`.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
