### ISSUE TITLE
Dashboard: Multiple streams as in home netflix project

### ISSUE THREAD

**Issue by mediocaballero** [spring-cloud/spring-cloud-netflix#3586]
Hi!

I'd like to use the functionality of being able to show multiple streams in the same dashboard window, as was included in the original dashboard project here: https://github.com/Netflix/Hystrix/pull/959 but it's not supported here.

Was this intentionally removed from the spring-cloud fork or are the projects just not in sync? I could not find any info on which version of netflix hystrix does this match to, but I expected the spring-cloud project to be the one most updated and include everything from 1.5.18 and more...

Thanks and greetings!

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

I don't know why it wasn't included. Probably never ported? If you (or someone else) is willing to submit a PR, we'll review.
