### ISSUE TITLE
Spring-cloud-netflix-hystrix issue while Upgrading to Spring boot 2.1.5-RELEASE IN jdk 1.8

### ISSUE THREAD

**Issue by saurockSaurav** [spring-cloud/spring-cloud-netflix#3588]
<!--
Thanks for raising a Spring Cloud issue. What sort of issue are you raising?
An issue in Spring upgrade from 2.0.3 to 2.1.5

Question

I am facing spring-cloud-netflix-hystrix issue while upgrading Project from Spring boot 2.0.3 to 2.1.5 in JDK 1.8. For 2.0.3 project is using  "Finchley.RELEASE" spring-cloud-dependencies which works as expected. But when I upgrade to 2.1.5 and using "Greenwich.RELEASE" version, fall back method doesn't get invoked. I examined Spring documentation and also went through StackOver response, but could not get to resolve it. I am using JUnit to test the scenario. Can you provide some insight into this issue?

**Comment by ryanjbaxter** [comment]
Please try Greenwich.SR2.  If you can reproduce the problem then please provide a sample the demonstrates the issue.

**Comment by saurockSaurav** [comment]
@ryanjbaxter  thanks for the version. I did try with it but could not get fall back method to invoke. I have the method in the service layer and it's a GET Rest call.  Now from my JUnit Test case, I have mocked the response and delayed the thread to 2500ms. Now by the time, it calls the method ( at service layer) I am expecting Fall back method to be invoked.  Perhaps, if there is any one suffering from same issues, please share . Below is the project POM:
  	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<jacoco.version>0.8.2</jacoco.version>
	</properties>
 
 <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Greenwich.SR2</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement> 

	<dependencies>
	  <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        
        
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
                
        		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
		  <groupId>org.apache.httpcomponents</groupId>
		  <artifactId>httpcore</artifactId>
		  <scope>test</scope>
		</dependency>
		 <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>
				spring-cloud-starter-netflix-hystrix
			</artifactId>
		</dependency>

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by saurockSaurav** [comment]
@spencergibb @ryanjbaxter found the cause of the issue. @EnableAspectJAutoProxy wasn't being loaded in-correct way in the test class. Closing the ticket now. 
 
thanks,
