### ISSUE TITLE
Hystrix Dashboard with custom authorization header

### ISSUE THREAD

**Issue by sureshgali** [spring-cloud/spring-cloud-netflix#3589]
Enhancement:
Please add authorization to spring-cloud-netflix-hystrix-dashboard-2.0.0.release or later version.(initially added as part of pull request https://github.com/Netflix/Hystrix/pull/336)  

This adds supports for a custom authorization header to the dashboard. This allows the hystrix stream to be protected by HTTP basic authentication.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
