### ISSUE TITLE
How to not allow any service to register with eureka server ?

### ISSUE THREAD

**Issue by bsushant-athena** [spring-cloud/spring-cloud-netflix#3596]
We are seeing that if a service has `{` in the service name then the zuul routes fail and other services will not be able to access through the gateway.

We tried to add a route filter that throws 404 to the current context but that allowed service to register and later after some time removed from the registry.

So can someone tell me how to capture the service registration request and not allow that service to register with the eureka server based on some condition?

**Comment by spencergibb** [comment]
That's not currently possible

**Comment by bsushant-athena** [comment]
We tried to add a pre-filter as well and sending 404 if the condition matches. But even after adding below code the registration does not stop. Is there anything else I need to add ? @spencergibb 
/```
/sets the sendZuulResponse boolean (we do not involve zuul downstream, therefore we do not call IAM)
        ctx.setSendZuulResponse(false);
        //sets the response status code
        ctx.setResponseStatusCode(HttpServletResponse.SC_NOT_FOUND);
        //if this value if true then the response should be sent to the client.
        ctx.sendZuulResponse();
```

**Comment by bsushant-athena** [comment]
Is this a new feature request then? @spencergibb

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
