### ISSUE TITLE
Feign REST Client - Converts GET requests to POST

### ISSUE THREAD

**Issue by ph0bos** [spring-cloud/spring-cloud-netflix#36]
When implementing a Feign client as per (http://projects.spring.io/spring-cloud/spring-cloud.html#_declarative_rest_client_feign) using the following interface all GET requests to "getStore" are actually being attempted as POST requests resulting in an Unsupported Operation exception being thrown. 

The listPlatforms call is executed as a GET request and works as expected.

Interface;

```
public interface PlatformClient {
    @RequestMapping(method = RequestMethod.GET, value = "/platforms")
    List getPlatforms();

    @RequestMapping(method = RequestMethod.GET, value = "/platforms/{platformId}")
    Platform getStore(@PathVariable("platformId") String platformId);
}
```

Exception;
`Caused by: feign.FeignException: status 405 reading PlatformRestClient#getPlatform(String); content:`

**Comment by viktor-coreteka** [comment]
@spencergibb  in witch version?
RequestHeader doesnt work for me
I'm using springCloudVersion = 'Edgware.SR5'

**Comment by rohitdec01** [comment]
I am  not able to pass body in Get request while using Feign. If I am doing so it is still converting get request to post.
Do we have any work around on this. I just want to separate my header and body while calling the get method.
