### ISSUE TITLE
Eureka and Zookeeper SSL Configuration

### ISSUE THREAD

**Issue by anmoldutta007** [spring-cloud/spring-cloud-netflix#3602]
Hi

I have 2 services registered with Eureka Server. One of the service has SSL certificate installed.
The rest endpoints exposed are https://.....
I want to access these endpoints from the other service that is registered with the Eureka Server via Feign Client.
What all Changes do i need to make to my feign client configuration to achieve the same.

I have seen a lot of posts saying to create a TrustingSSlSocketFactory and then create a Client Bean using the same.

But i am not able to understand is that the right way to achieve this or is there some other way of doing the same.

Spring-Boot Version : 2.1.6.RELEASE
Spring Cloud Version: Greenwich.SR2

**Comment by ryanjbaxter** [comment]
See https://cloud.spring.io/spring-cloud-static/Greenwich.SR1/single/spring-cloud.html#_registering_a_secure_application

**Comment by anmoldutta007** [comment]
It worked after going through the link provided. Do we have similar something in case we are using zookeeper as discovery server?

**Comment by anmoldutta007** [comment]
Hi @ryanjbaxter  @spencergibb 

If we want to contact a service over https which is registered with zookeeper, we can provide that by specifying the ssl-port using the below property
spring.cloud.zookeeper.discovery.instance-ssl-port=${port number}

This seems to be working in the latest version
Spring-Boot Version : 2.1.6.RELEASE
Spring Cloud Version: Greenwich.SR2

But when i try the same with the dependencies mention below, it does not work, the sslPort still shows as null on zookeeper.
compile(group: 'org.springframework.boot', name: 'spring-boot-starter', version: '1.5.2.RELEASE')
compile(group: 'org.springframework.cloud', name: 'spring-cloud-starter', version: '1.2.0.RELEASE')
compile(group: 'org.springframework.cloud', name: 'spring-cloud-starter-zookeeper-all', version: '1.0.4.RELEASE')
compile(group: 'org.springframework.cloud', name: 'spring-cloud-zookeeper', version: '1.0.4.RELEASE')

Is that a bug in release 1.2.0 of spring cloud or is there another way of doing it.

**Comment by spencergibb** [comment]
Why are you managing versions independently? What version of the bom are you using?

**Comment by anmoldutta007** [comment]
I believe the person who created the build.gradle in our project did not use bom or may be that version of gradle did not support bom, so that may be the reason why he did not use that.

I could see see the dependencies which i mentioned in my build.gradle for spring cloud, boot and zookeeper. and i need to enable SSl with these versions only.

**Comment by spencergibb** [comment]
Gradle has always had bom support via the spring boot Gradle plugin.

**Comment by spencergibb** [comment]
Those versions are no longer supported. Edgware.SR6 is the last boot 1.5 supported version of spring cloud

**Comment by anmoldutta007** [comment]
But can you please let me know if this was a bug in that version of spring cloud , as even after specifying the property spring.cloud.zookeeper.discovery.instance-ssl-port=${port number}, the ssl port is null.

Or is there a workaround for that ?

**Comment by spencergibb** [comment]
No, we don't support it anymore. If you upgrade and are still experiencing issues we can take a look and open an issue in spring-cloud-zookeeper. According to https://github.com/spring-cloud/spring-cloud-zookeeper/commit/69701d33c8d6ab74341e77209d75fc06301bdf02, `instance-ssl-port` was added in v1.1.2.RELEASE of spring-cloud-zookeeper and you are using 1.0.x
