### ISSUE TITLE
Zuul ignoredServices

### ISSUE THREAD

**Issue by iammj6** [spring-cloud/spring-cloud-netflix#3606]
I did go through the below links for reference but it doesn't seem to help.
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#cookies-and-sensitive-headers
spring-cloud/spring-cloud-netflix#2904

What does it mean by 'To skip having a service automatically added, set zuul.ignored-services to a list of service ID patterns.'
In my api gateway service, i have set ignored-services:'*' and added only one service for routing as below:
spring:
application:
name: eureka-zuul
server:
port: 8761
eureka:
client:
registerWithEureka: true
fetchRegistry: true
serviceUrl:
defaultZone: http://localhost:8761/eureka
zuul:
ignoredServices: ' * '
prefix: /api
retryable: true
strip-prefix: false
routes:
movies:
path: /moviesservice/**
serviceId: movies-service
Does it mean any other service will not be routed by Zuul ? If thats the case, i haven't added route of another service 'RatingsService' in the yml, then why does below url work ?
http://eureka-zuul/api/ratings-service/ratings/listratings/1

When zuul.ribbon.eager.load is set to true, application context is loaded eagerly. But what does application context mean in this context ? Spring beans by default get initialized eagerly. Does application context mean the properties in application.yml ?

**Comment by spencergibb** [comment]
Spring Cloud can automatically add routes for services in eureka. This setting ignores certain services for auto creating routes

**Comment by iammj6** [comment]
I haven't added route configuration for another service and also specified ignoredService to all with '*' and how does http://eureka-zuul/api/ratings-service/ratings/listratings/1  work ? 
Irrespective of ignoredService:'*', the request is getting routed.

**Comment by spencergibb** [comment]
Ignored services literally only applies to automatic route creation from discovery, nothing else

**Comment by iammj6** [comment]
So when i mentioned in yml to ignore routing for Ratings service and consider it only for movies-service, then why does routing work for Ratings service. Appreciate if you could please throw some more light on it.

**Comment by spencergibb** [comment]
You don't show zuul discovery enabled, so I don't know, unless there's more configuration you're not showing

**Comment by iammj6** [comment]
Below is the complete yml. But i suppose it doesn't make any difference because catalog is a different service from which i am calling Ratings service with url as below:
http://eureka-zuul/api/ratings-service/ratings/listratings/1 

spring: 
  application:
    name: eureka-zuul
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  ignoredServices: '*'
  prefix: /api
  retryable: true
  strip-prefix: false
  routes: 
    movies: 
      path: /moviesservice/**
      serviceId: movies-service
    catalog: 
      path: /catalogservice/**
      url: http://localhost:8081
Eureka is registered with iteself and i have included zuul with eureka in the same module.

**Comment by spencergibb** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by iammj6** [comment]
I have uploaded my proj to https://github.com/iammj6/code-proj.git
Please do not refer the module Zuul, as i am not using that in my use case. It was initially created just for test.
http://localhost:8081/catalog/moviecatalog is what i use to test.

**Comment by spencergibb** [comment]
I don't understand. I want your zuul project. The zuul module is the only one with zuul

**Comment by iammj6** [comment]
Under eureka-server module's pom.xml you will see zuul dependency too. I have combined registry and zuul together. I have enabled EureakServer and ZuulProxy in the same module of eureka-server. You don't need to look at Zuul module.

**Comment by iammj6** [comment]
Any feedback please ?

**Comment by spencergibb** [comment]
combining eureka server with anything else is not advisable.
