### ISSUE TITLE
Servo: possible overlap in metric names during export

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#361]
See https://github.com/Netflix/servo/issues/322 for a complete description and follow-up.

In short: the current naming scheme used to build metric names from Servo metric doesn't consider the runtime `id` assigned to the monitor.
The current naming strategy is inspired by Servo's `GraphiteExporter` - hence linking to the issue in project Servo and waiting for their advices.

**Comment by spencergibb** [comment]
Is this still an issue?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
