### ISSUE TITLE
Zuul filtered header Set-Cookie from response

### ISSUE THREAD

**Issue by jgreznar** [spring-cloud/spring-cloud-netflix#3613]
I'm using sample Zuul reverse proxy. In this test case behind proxy is Jenkins.

### Configuration

My **application.yml**

https://github.com/jgreznar/spring-coud-test-proxy/blob/master/src/main/resources/application.yml

<img width="347" alt="image" src="https://user-images.githubusercontent.com/23076281/62116119-e9a35480-b2b9-11e9-9894-32673a7c77e8.png">

### Request header form Zuul to Jenkins

pragma: no-cache
cache-control: no-cache
origin: http://localhost:8080
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
content-type: application/x-www-form-urlencoded;charset=UTF-8
accept: text/javascript, text/html, application/xml, text/xml, */*
x-prototype-version: 1.7
x-requested-with: XMLHttpRequest
jenkins-crumb: 7e3bd53da890fe6dfcfb917a75ea64d7
referer: http://localhost:8080/
accept-encoding: gzip, deflate, br
accept-language: sk,en-US;q=0.9,en;q=0.8,cs;q=0.7
x-forwarded-host: localhost:8080
x-forwarded-proto: http
x-forwarded-port: 8080
x-forwarded-for: 0:0:0:0:0:0:0:1
Content-Length: 0
Connection: Keep-Alive

### Request from browser

GET / HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: sk,en-US;q=0.9,en;q=0.8,cs;q=0.7

### Response header form Jenkins to Zuul

HTTP/1.1 200 OK
Date: Tue, 30 Jul 2019 08:42:46 GMT
X-Content-Type-Options: nosniff
Content-Encoding: gzip
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache,no-store,must-revalidate
X-Hudson-Theme: default
Content-Type: text/html;charset=UTF-8
Set-Cookie: JSESSIONID.25d6af8e=oqngp81xg4toju0jdqdxfxhq;Path=/;HttpOnly
X-Hudson: 1.395
X-Jenkins: 2.60.3
X-Jenkins-Session: 324427ee
X-Hudson-CLI-Port: 50000
X-Jenkins-CLI-Port: 50000
X-Jenkins-CLI2-Port: 50000
X-Frame-Options: sameorigin
X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl5bUt5s7Vpoqh7juiPLgBEh6QuOIH1dv0/l2wq7iB0x1eMzTIaq825ROOnMX5lowTET9YD7kSZi7MnZANQ0kEJSF+cTUd+Gp2odoCsj5cZlKO2qE1erP8w3bN+dMnkg4WoGncQif07r7uzXrX6+kOsrD+ZJGDUWKy6BHl8TGa9fpAUnqCXJwE5Wg4tA0XF2rOhQ5Ri0H1GsCOdR7T9aVzlxdeooC8jbqhnhoxJK8Ytv7+gJfL69GtuyKJTo3inrrfXJi9a9hiSNeK+rmJCP2soKsNCPdjCwZnrSlTvcmUn3eBakT49eQSZ4RzuL6DqjCTu2HPN6mY8TVlV2rWaGxFwIDAQAB
Content-Length: 8358
Server: Jetty(9.2.z-SNAPSHOT)

### Response header in browser

HTTP/1.1 200
Date: Tue, 30 Jul 2019 08:42:46 GMT
X-Content-Type-Options: nosniff
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache,no-store,must-revalidate
X-Hudson-Theme: default
X-Hudson: 1.395
X-Jenkins: 2.60.3
X-Jenkins-Session: 324427ee
X-Hudson-CLI-Port: 50000
X-Jenkins-CLI-Port: 50000
X-Jenkins-CLI2-Port: 50000
X-Frame-Options: sameorigin
X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl5bUt5s7Vpoqh7juiPLgBEh6QuOIH1dv0/l2wq7iB0x1eMzTIaq825ROOnMX5lowTET9YD7kSZi7MnZANQ0kEJSF+cTUd+Gp2odoCsj5cZlKO2qE1erP8w3bN+dMnkg4WoGncQif07r7uzXrX6+kOsrD+ZJGDUWKy6BHl8TGa9fpAUnqCXJwE5Wg4tA0XF2rOhQ5Ri0H1GsCOdR7T9aVzlxdeooC8jbqhnhoxJK8Ytv7+gJfL69GtuyKJTo3inrrfXJi9a9hiSNeK+rmJCP2soKsNCPdjCwZnrSlTvcmUn3eBakT49eQSZ4RzuL6DqjCTu2HPN6mY8TVlV2rWaGxFwIDAQAB
Content-Encoding: gzip
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked

### Problem

Missing header Set-Cookie: 

Whole project is in https://github.com/jgreznar/spring-coud-test-proxy. Is there some problem with configuration ? Because i don't know where is the problem

Thank you

**Comment by spencergibb** [comment]
The sensitive headers option is to remove those headers. Set it to empty.
