### ISSUE TITLE
Need to write context-path, when call to other microservice

### ISSUE THREAD

**Issue by elkana-d** [spring-cloud/spring-cloud-netflix#3615]
When try get from send-sms service
 restTemplate.getForObject("http://send-sms/send-sms/Test", Object.class);

It's seems that the service-discovery not share the context-path.

**send-sms.properties**
spring.application.name=send-sms
server.servlet.context-path=/send-sms
server.port: 8060
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true

**Comment by spencergibb** [comment]
Service discovery doesn't know about context path. This is a duplicate. I'll find the issue later

**Comment by elkana-d** [comment]
Service discovery know a little.

Whenever I added
server.contextPath=/send-sms   (in addition to server.servlet.context-path=/send-sms)
and click on the send-sms service in Service discovery panel, 
a new tab opens with url = http://pc.mshome.net:8060/**send-sms**/actuator/info

**Comment by ryanjbaxter** [comment]
It might be in the metadata but the load balancer will not add it by default

**Comment by elkana-d** [comment]
There is some way the load balancer can get this information(contextPath of the service)?

**Comment by ryanjbaxter** [comment]
You can use the `DiscoveryClient` to get the metadata
