### ISSUE TITLE
Feign Annotations

### ISSUE THREAD

**Issue by aljacinto** [spring-cloud/spring-cloud-netflix#362]
If I have the annotations for the rest endpoints that I am calling, I can simply use that in my Feign client?  Just wondering because the Netflix Feign uses other annotations like RequestLine.

Thanks in advance
Alex

**Comment by spencergibb** [comment]
Not sure I understand what "If I have the annotations for the rest endpoints that I am calling" means, can you clarify?  We installed our own `feign.Contract` that uses the Spring MVC annotations.  To use feign's annotations you just need to create an `@Bean` of type `feign.Contract.Default`.

**Comment by aljacinto** [comment]
You answered my question, but to confirm...

If I create the rest endpoints that I am calling through spring mvc annotations, example:
```
    @RequestMapping(value = "/{hello}", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    String home(@PathVariable String greeting,
            @RequestParam(defaultValue = "World", value = "thing") String thing) {
        return greeting + thing;
    }
```
I can then simply copy and paste those lines in my Feign client.

```
@FeignClient("greeter")
public interface GreeterClient {
    // lines above
    @RequestMapping(value = "/{hello}", method = RequestMethod.GET, produces = "application/json")
    @ResponseBody
    String home(@PathVariable String greeting,
            @RequestParam(defaultValue = "World", value = "thing") String thing) {
        return greeting + thing;
    }
}
```

**Comment by spencergibb** [comment]
@aljacinto yes, you can.  Though `@ResponseBody` is not needed (it won't hurt, but doesn't do anything).
