### ISSUE TITLE
JAXB dependencies should be using jakarta JARs

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#3622]
In Spring Boot they switched to jakarta jars for the JAXB dependencies needed in Java 11. Should only be in the starters as well (I think that's true here).

**Comment by ryanjbaxter** [comment]
@dsyer does that cause any conflict when Java 8 is used (where the jars are already present)?

**Comment by spencergibb** [comment]
Not the api jars, the impls would

**Comment by ryanjbaxter** [comment]
Do we need both in the case of java 11?

**Comment by dsyer** [comment]
So far we seem to be Ok with the API only. It’s just the wrong jar. Might be good to look at the classpath for a sample though and check it looks sane.

**Comment by ryanjbaxter** [comment]
We actually already have a jaxb api in the starter
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-starter-netflix/spring-cloud-starter-netflix-eureka-server/pom.xml#L37

**Comment by dsyer** [comment]
Yes, but it’s the wrong one. It should be the Jakarta one (same as Boot).

**Comment by ryanjbaxter** [comment]
I must be missing something, looks like they are also using glassfish 
https://github.com/spring-projects/spring-boot/blob/ccf9b1b9343b0e97c9e5f713a4b0cd64f2e8d7e5/spring-boot-project/spring-boot-dependencies/pom.xml#L2227

**Comment by dsyer** [comment]
But see also: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml#L1248. And that’s the one in the starters (eg look at the the starter).

**Comment by dsyer** [comment]
Forget it. You’re right. We need the runtime for eureka (unlike
Jooq).
