### ISSUE TITLE
can zuul1 use the reactive webclient as the SimpleHostRoutingFilter's http client?

### ISSUE THREAD

**Issue by phantomedc** [spring-cloud/spring-cloud-netflix#3625]
I use zuul1 as a simple proxy server,it worked very well until the count of requests go high, could I change the default http client from apache http client to the reactive web client ,and how? 
thanks!

**Comment by spencergibb** [comment]
Not currently.

This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
