### ISSUE TITLE
Modifying request body for Multipart file request

### ISSUE THREAD

**Issue by syedhaider** [spring-cloud/spring-cloud-netflix#3630]
I am trying to intercept request through Zuul filter. My use case is to get the file in zuul filter and save it to filesystem for scanning then reload the file from file system and set into request again and route to internal endpoint. I am not getting the solution for it. Help is appreciated in this regards.

Thanks,
Syed

**Comment by OlgaMaciaszek** [comment]
As @ryanjbaxter suggested, please provide a code example that clarifies the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
