### ISSUE TITLE
Use of compactmap pulls in LGPL 3.0 license

### ISSUE THREAD

**Issue by gardengeek99** [spring-cloud/spring-cloud-netflix#3636]
There is an open issue in compactmap to change to Apache 2.0 licensing (https://github.com/vlsi/compactmap/issues/6).  Regardless, as of now, this causes spring-cloud-netflix to effectively be LGPL 3.0.

**Comment by spencergibb** [comment]
I'm having our team look at it.

It is a transitive dependency of netflix eureka-client.

https://www.difference.wiki/gpl-vs-lgpl/

https://fluendo.com/en/blog/post/gpl-vs-lgpl/

**Comment by vlsi** [comment]
Oh, that was unexpected.
I've updated the license for CompactMap to Apache-2.0, however, there are issues with Central (504, etc), so I don't know when I will be able to publish it.

**Comment by vlsi** [comment]
https://search.maven.org/artifact/com.github.vlsi.compactmap/compactmap/2.0/jar is there
