### ISSUE TITLE
An unauthorized access vulnerability issue

### ISSUE THREAD

**Issue by AIOKhacker** [spring-cloud/spring-cloud-netflix#3637]
产品漏洞
spring-cloud-netflix/Eureka

漏洞报告简述
一个未授权访问，导致配置的账户密码信息以及配置文件路径泄露，如果网站增加了账户验证，也会导致用户名泄露以及配置的文件信息泄露。该漏洞问题导致上千主机IP受影响

修复方式：
禁止访问权限，

from google translate
Product vulnerability
Spring-cloud-netflix/Eureka

Vulnerability report brief
An unauthorized access causes the configured account password information and the path of the configuration file to be leaked. If the website adds account verification, the user name will be leaked and the configured file information will be leaked. The vulnerability has caused thousands of host IPs to be affected

Repair method:
Prohibit access,

**Comment by OlgaMaciaszek** [comment]
@AIOKhacker Please create any issues in this repository in English only. If you want us to have a look at this issue, provide an English description.

**Comment by AIOKhacker** [comment]
ok.

We can find the directory /env, Add this directory to find a lot of sensitive information.

The account password information and the configuration file path of the configuration are leaked. If the website adds account verification, the user name will be leaked and the configured file information will be leaked.

Found through the search engine that 1000+ multiple servers are affected。

Example:

  http://47.94.160.67:8090/env

  http://115.159.237.168:10000/env

 

  http://101.64.233.40/env

```````````````````````````````

Code view：
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationTests.java
Line 76 code：
"http://localhost:" + this.port + BASE_PATH + "/env", HttpMethod.GET,








------------------ 原始邮件 ------------------
发件人: "Olga Maciaszek-Sharma"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 晚上7:56
收件人: "spring-cloud/spring-cloud-netflix"<spring-cloud-netflix@noreply.github.com>;
抄送: "伤心的金毛"<250192316@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [spring-cloud/spring-cloud-netflix] 一个未授权访问漏洞问题 (#3637)




@AIOKhacker Please create any issues in this repository in English only. If you want us to have a look at this issue, provide an English description.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by OlgaMaciaszek** [comment]
Hello, @AIOKhacker No, please edit the github issue instead.

**Comment by AIOKhacker** [comment]
> Hello, @AIOKhacker No, please edit the github issue instead.

Code view：
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationTests.java
Line 76 code：
"http://localhost:" + this.port + BASE_PATH + "/env", HttpMethod.GET,

We can find the directory /env, Add this directory to find a lot of sensitive information

**Comment by AIOKhacker** [comment]
Code view：
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationTests.java
Line 76 code：
"http://localhost:" + this.port + BASE_PATH + "/env", HttpMethod.GET,

We can find the directory /env, Add this directory to find a lot of sensitive information

**Comment by marcingrzejszczak** [comment]
Can you actually describe what you want to achieve our what the problem is? Which version of the project you're using and how exactly we can replicate a problem (if there's any problem)

**Comment by AIOKhacker** [comment]
1>
GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Connection: close
Upgrade-Insecure-Requests: 1

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
X-Application-Context: apollo-configservice:github:8080
Content-Type: text/html;charset=UTF-8
Content-Language: zh-CN
Date: Tue, 27 Aug 2019 12:17:04 GMT
Connection: close
Content-Length: 5573

2>
GET /env HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Connection: close
Upgrade-Insecure-Requests: 1

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: apollo-configservice:github:8080
Content-Type: application/json
Date: Tue, 27 Aug 2019 12:44:36 GMT
Connection: close
Content-Length: 12539

Increase directory / env。Leaking a lot of server information。Can be found through Content-Length。

**Comment by OlgaMaciaszek** [comment]
@AIOKhacker 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. Also, please write exactly:
1. What action you carry out
2. What happens
3. What you expect should happen instead

**Comment by AIOKhacker** [comment]
E.g：
http://38.21.227.203:8090/
Add a directory env
http://38.21.227.203:8090/env
This can lead to the disclosure of sensitive information.
so.We recommend that you should have permission control on the directory.

**Comment by AIOKhacker** [comment]
Is the problem being investigated？

**Comment by AIOKhacker** [comment]
http://115.159.237.168:10000
Does the website use your framework?
Look at it showing spring eureka

**Comment by AIOKhacker** [comment]
Okay, that's what I saw to feed back the question.Isn't this problem caused by your default installation?

**Comment by AIOKhacker** [comment]
Because I see a lot of servers affected.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
