### ISSUE TITLE
Zuul responding with old domain

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#364]
Not sure how this is happening.  I have changed the domain of our application.  I can't get Zuul to stop responding with the old domains information.  I did remove all cookies, local storage etc for the old domain.  Also tried a new browser and even tried a mobile browser which has never used the domain.

The route is set as a static IP since this is a non Spring boot application that Zuul is routing to.  I did verify everything in the applications config to have nothing to do with the old domain.

I have rebooted the Zuul.  Does Zuul interact with the DNS cache of the host?  Not sure how to make it forget about the old domain.

```
zuul.routes.vr-docs.path = /vr-docs/**

zuul.routes.vr-docs.url = http://171.21.26.210/vr-docs

zuul.routes.vr-docs.stripPrefix = true
```

```
{
  "method": "GET",
  "path": "/vr-docs",
  "headers": {
    "request": {
      "host": "correctdomain.com",
      "connection": "keep-alive",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36",
      "accept-encoding": "gzip, deflate, sdch",
      "accept-language": "en-US,en;q=0.8,es;q=0.6,fr;q=0.4"
    },
    "response": {
      "X-Application-Context": "vr-gateway:production",
      "Location": "http://olddomain.com/vr-docs/",
      "Date": "Tue, 26 May 2015 10:40:19 GMT",
      "Transfer-Encoding": "chunked",
      "status": "302"
    }
  }
}
```

**Comment by spencergibb** [comment]
sounds odd.  How could zuul know anything about the old domain unless there is still configuration pointing it there?

**Comment by ccit-spence** [comment]
That is why I am confused.  My understanding is that Zuul is stateless and only does its routing based on the route properties.

**Comment by ccit-spence** [comment]
The JSON is from a trace of the request on Zuul.

**Comment by spencergibb** [comment]
Have you restarted the OS?  Java does DNS caching, but if you restarted the java process, the only other place it could cache is the OS.

**Comment by ccit-spence** [comment]
I have restarted both Zuul and the application in question.  The app is Atlassian Confluence.

**Comment by spencergibb** [comment]
Doesn't that response come from the app itself?  So does confluence still have an old domain configured?

**Comment by ccit-spence** [comment]
I did verify that Confluence is configured with the correct domain.  I would think that since I am doing a trace on Zuul the response is from Zuul based on the properties.

**Comment by ccit-spence** [comment]
Ok, found the problem.  I feel stupid now.  Blamed the wrong thing.  It was the server.xml within Confluence. The proxy configuration was still set to the old domain.  Thanks for the help!

**Comment by spencergibb** [comment]
:wink:
