### ISSUE TITLE
Zuul stops to find services and forward requests when system jumps back in time

### ISSUE THREAD

**Issue by konths** [spring-cloud/spring-cloud-netflix#3640]
Zull stops to find services and forward requests when system jumps back in time i.e Eureka is started, services are registered and now due to ntp time sync, if the system jumps back in time, zuul is not able to identify the services and complains there are no servers available for the client.

Spring cloud version 1.3.6.RELEASE

**Comment by spencergibb** [comment]
A couple of things, Dalston, Edgware and Finchley are no longer supported.

If there is an issue going back in time it is a eureka issue, not sure what we could do about it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
