### ISSUE TITLE
The Provider Cannot Register to Eureka Server,How to Debug or Trace

### ISSUE THREAD

**Issue by wecloud2008** [spring-cloud/spring-cloud-netflix#3641]
Eureka Server some application.yml and EnableSpringBoot Class

application.yml
`server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/`

`package com.chtrak.microscs.scseureka;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication
public class ScsEurekaApplication {

    public static void main(String[] args) {
        SpringApplication.run(ScsEurekaApplication.class, args);
    }

}
`

Provider
`package com.chtrak.microscs.microscsitem;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;

@SpringBootApplication
@EnableEurekaClient
@EnableDiscoveryClient
public class MicroscsItemApplication {

    public static void main(String[] args) {
        SpringApplication.run(MicroscsItemApplication.class, args);
    }

}
`

`server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka`

Report

Application | AMIs | Availability Zones | Status
-- | -- | -- | --
No instances available

**Comment by spencergibb** [comment]
Your client has register with eureka false.

**Comment by wecloud2008** [comment]
@spencergibb

what do you meaning?

would you please explain it ?

thanks

**Comment by wecloud2008** [comment]
Closed.

Point:
Eureka Client NOT allow ADD
register-with-eureka: false 
fetch-registry: false
