### ISSUE TITLE
[Question][Eureka-Client][windows] Service name

### ISSUE THREAD

**Issue by ehhc** [spring-cloud/spring-cloud-netflix#3643]
Hi there,
currently I'm trying to reproduce a certain problem in my application and i found the following behavior of the Eureka Client which i don't understand:
When the service registers itself at the Eureka Server, if i understand the code correctly, it uses the first non-loopback address given in the hosts file (on windows) as an host address.

In don't understand why this is done. There could be various things given in the hostsfile and assuming the first non-loopback-entry to be an valid host name for _this_ host seems odd.

I mean: If i add the following line at the top of the hosts file: `123.456.78.910 pustekuchen` (given 123.456.78.910 is my current ip address), the current services tries to register using the hostname `pustekuchen`...

To state my problem more specific:
Docker added a line `123.456.78.910 host.docker.internal` (again assume 123.456.78.910 to be my real ip address) to the hostfile. Therefore all my services try to use this alias. Unfortunately (no idea why yet) it is very slow and all my feign-clients get timeouts before they can reach the other services.. All of that only because my services don't use `localhost` as a host name but the first entry in the hosts file...

**Comment by spencergibb** [comment]
It's just a default, you can always change it. There are also options to ignore networks and interfaces.

**Comment by ehhc** [comment]
Thanks for your answer. Since i spent most of the day figuring out that this behavior caused my problems, i want to understand the reasons of it. Are there any rationals explaining why talking the first non-loopback-address as a host name would be a good idea?

**Comment by spencergibb** [comment]
It's simply the only guess we can make. It works in many cases.

**Comment by ehhc** [comment]
Okay, thanks for taking the time to answer....
