### ISSUE TITLE
shouldUnregisterOnShutdown for spring-cloud-netflix-eureka-client 1x

### ISSUE THREAD

**Issue by andresoviedo** [spring-cloud/spring-cloud-netflix#3649]
**Question**

I saw In **spring-cloud-netflix-eureka-client** 2.x there is a property called `shouldUnregisterOnShutdown=true|false`

Is there any similar feature on v1.x ?

**Rationale**

I have a fixed number of spring micro-services in my cloud.

I would need my spring boot client applications do NOT unregister to eureka server when they are shutdown but to set status otherwise like 'DOWN' or 'OFFLINE'.

Apparently, spring boot-admin only "detect" status changes if the application is not unregistered then registered when going through Eureka Discovery Server.

**Comment by spencergibb** [comment]
I know very little about spring boot admin. Monitoring doesn't seem like a solid reason to not unregister when the app shuts down. At that point, couldn't you tell by the number of instances?

**Comment by andresoviedo** [comment]
I have opted to configure statically the monitored instances through `SimpleDiscoveryClient`

This way, the spring boot-admin keep tracks of status changes and send alerts only when it has to.
