### ISSUE TITLE
Zuul SimpleHostRoutingFilter isn't forwarding  GET method body. 

### ISSUE THREAD

**Issue by kundan1301** [spring-cloud/spring-cloud-netflix#3661]
Sometime we need body in http GET method as well.  I can see buildHttpRequest method of  SimpleHostRoutingFilter class is not sending body to backend host. Can you please tell this is intentional, If not I can fix it and send a PR.

**Comment by spencergibb** [comment]
It's not something supported by default https://stackoverflow.com/questions/12535016/apache-httpclient-get-with-body.

This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review a small pull request from you.

So, PRs welcome.

**Comment by kundan1301** [comment]
Yes, it's not supported by default. Let's not change the default behaviour but we can have a flag. Setting that flag will override default behaviour. We can do something like solution suggested in above stackoverflow answer. 

`import org.apache.http.client.methods.HttpEntityEnclosingRequestBase;

public class HttpGetWithEntity extends HttpEntityEnclosingRequestBase {
    public final static String METHOD_NAME = "GET";

    @Override
    public String getMethod() {
        return METHOD_NAME;
    }
}`
