### ISSUE TITLE
spring-cloud-starter-netflix-archaius using older artifact of commons-configuration

### ISSUE THREAD

**Issue by azarfaiz** [spring-cloud/spring-cloud-netflix#3662]
I am using "spring-cloud-starter-netflix-zuul(2.1.1.RELEASE)" which has a dependency on "spring-cloud-starter-netflix-archaius" which itself uses "commons-configuration" library (group id -> commons-configuration and artifact id -> commons-configuration)
Apache has moved the latest versions of the commons-configuration library to a different artifact (group id -> org.apache.commons and artifact id -> commons-configuration2) and its latest version is 2.6.
Are there any reasons why new artifact of the library is not adapted in "spring-cloud-starter-netflix-archaius"?

**Comment by spencergibb** [comment]
Archaius 1 has that specific dependency.
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
