### ISSUE TITLE
Update Ribbon version.

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#3664]
I found that ribbon has released 2.7.x, but Spring Cloud Netflix still uses 2.3.x.
Could you upgrade?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

**Comment by eacdy** [comment]
I know this.
But since we use ribbon as default load balancer even in Spring Cloud Hoxton , And Spring Cloud Commons's sub-module Spring Cloud Loadbalancer has only support a simple round-robin algorithm load balancer.
Don't you think keep maintain ribbon is a good approach?
Or, When we Can use Spring Cloud Loadbanancer alternative in production? For now, I don't think it Can be used in production. Cause it is tooooooooo simple, We need more load-balancer algorithm support.

**Comment by spencergibb** [comment]
If you read what I wrote, it says we won't do it, but will accept PRs. What feature is in the new version that you need?
