### ISSUE TITLE
ribbon global configuration ConnectTimeOut

### ISSUE THREAD

**Issue by IndiraFinish** [spring-cloud/spring-cloud-netflix#3668]
I wanted to configure multiple services globally over time, but only a single service is officially configured.

exanple:
`ribbon.ConnectTimeout=1500` it doesn't work.

can only like this 
`<clientName>.ribbon.ConnectTimeout=1500`

**Comment by ryanjbaxter** [comment]
saying it doesnt work is not very useful

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
