### ISSUE TITLE
Multiple Instances of Eureka Server in Kubernetes

### ISSUE THREAD

**Issue by arpitkh12** [spring-cloud/spring-cloud-netflix#3670]
How can I have multiple instance of Eureka Server in Kubernetes ? Want all clients to register to  all the pods of Eureka Server.

**Comment by spencergibb** [comment]
I'd actually question the need of eureka in kubernetes

**Comment by arpitkh12** [comment]
Agreed. It is an interim solution. Trying to use Spring Cloud Gateway with Kubernetes for Service Discovery. However, I haven't yet figured out any good examples on how to achieve it.
Would really appreciate if any example can be provided for the same. Particularly if they would be limited to Role and Role Binding for a particular namespace and not at Cluster level as its difficult to get ClusterRole and ClusterRoleBinding in an enterprise.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Comment by sandy-adi** [comment]
> I'd actually question the need of eureka in kubernetes

We are trying to run Zuul on Kubernetes as an API Gateway. We would like to use Eureka as the service discovery component for Zuul. I agree eureka is not needed for handling discovery within the kubernetes cluster.
