### ISSUE TITLE
Zuul multipart form data missing while upload more than 2 GB and time taking upto 15 mins

### ISSUE THREAD

**Issue by kmmurali2691** [spring-cloud/spring-cloud-netflix#3673]
I dont see any error. But request reached my controller after Zuul with empty multi part data.

Zuul is my gateway and it will send request to file share application. After 15 mins request forwarded to fileshare application with empty multipart data. I am using Springboot 2.0.

**Comment by kmmurali2691** [comment]
I dont see any error. But request reached my controller after Zuul with empty multi part data.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
