### ISSUE TITLE
Wrong Content-Encoding set when response is coming from `RequestContext::getResponseBody` and origin response is gzipped

### ISSUE THREAD

**Issue by jebeaudet** [spring-cloud/spring-cloud-netflix#3679]
Hi

When modifying the origin response and setting the client response as a String using `RequestContext::setResponseBody`, the `Content-Encoding` header gets wrongly set to what was set on the origin response. This caused a non-gzipped stream marked as gzip with the `Content-Encoding` header being sent back to the client.

I'll submit a PR shortly.

**Comment by spencergibb** [comment]
Closing in favor of #3680
