### ISSUE TITLE
IllegalArgumentException for '=' in query param using Ribbon load balancer with https

### ISSUE THREAD

**Issue by mage-ante** [spring-cloud/spring-cloud-netflix#3682]
Checked around and found that this is literally the same problem as issue [#1291](https://github.com/spring-cloud/spring-cloud-netflix/issues/1291), except that it happens for '=' instead of '+'. 

Is there a workaround for the meantime? Thanks!

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
