### ISSUE TITLE
Eureka server replication stucks in case of big amount of nodes

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-netflix#3683]
**Given:**
3 instances of org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:2.1.1.RELEASE (each 4 GB RAM, 2 CPU)
1000+ nodes 

**When:**
Eureka restarts (intentionally or unintentionally)

**Then:**
Eureka stucks during sync with other eureka nodes.
Busy threads graphic reaches its peak and eureka 
Eureka's CPU usage is 100% and clients got Timeout exceptions on connect. And it stucks forever.

**Expect:**
Eureka starts as normal and got synced with other nodes.

**Workaround:**
It starts OKAY only if I assign 8 GB RAM, 4 CPU per each node, which is enormous amount of resources.

**Some observations:**
Threads are getting blocked:
![image](https://user-images.githubusercontent.com/3741358/67770388-f8d3a300-fa5e-11e9-9355-4f58e45605e2.png)
CPU usage is at its high:
![image](https://user-images.githubusercontent.com/3741358/67770459-1acd2580-fa5f-11e9-84c2-d1da89fe5ec2.png)

**Possible root cause:**
During renewal process eureka tries to get property from source, this change was done in https://github.com/Netflix/eureka/pull/934
The code looks like:
https://github.com/Netflix/eureka/blame/master/eureka-core/src/main/java/com/netflix/eureka/resources/PeerReplicationResource.java#L152

It looks okay for the first glance but if we take a look on blocked threads we will see next:
```
"http-nio-8080-exec-112" - Thread t@274
   java.lang.Thread.State: BLOCKED
        at java.util.Hashtable.get(Hashtable.java:363)
        - waiting to lock <5f05dcfd> (a java.util.Properties) owned by "http-nio-8080-exec-48" t@209
        at org.springframework.core.env.MapPropertySource.getProperty(MapPropertySource.java:42)
        at .........
```
And in profiler we can see:
![image](https://user-images.githubusercontent.com/3741358/67770824-ceceb080-fa5f-11e9-9524-b830f6b58b22.png)

**Assumptions:**
Since under the hood some property source uses HashTable as storage, all renewals are being blocked and cannot be done in parallel. It causes timeouts on other eureka instances and they are retrying sync calls and process dives into infinite loop.

**Possible solutions:**
- remove property check as it was done only for fix "undo" 
- fix property source in spring framework to use ConcurrentHashMap
- use cache somewhere between layers

**Related tickets:**
https://github.com/Netflix/eureka/pull/934 - added check which blocks calls @troshko111
https://github.com/spring-cloud/spring-cloud-netflix/issues/3608 very similar case, FYI @qinxiongzhou

UPD:
Even if we get rid of spring property source call, eureka struggling syncing nodes between each other. 
Found related issue - https://github.com/Netflix/eureka/pull/1031 .

**Comment by troshko111** [comment]
@tdanylchuk please send a PR to Eureka, I'm fine with moving that config property read to an earlier time and caching in a field (assuming it won't change during the process lifespan), this looks ridiculous to me and makes no sense on a hot path.

**Comment by spencergibb** [comment]
Closing as this will be done upstream
