### ISSUE TITLE
The content fo a single HTML document should be on the left side of the page.

### ISSUE THREAD

**Issue by diguage** [spring-cloud/spring-cloud-netflix#3684]
<https://cloud.spring.io/spring-cloud-static/Greenwich.SR3/single/spring-cloud.html> 

I recommend that **the content fo a single HTML Spring Cloud document should be on the left side of the page.** It is more readable.

The Spring boot document is a good example.

<https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/>

![image](https://user-images.githubusercontent.com/2121467/68000836-949e2280-fc9c-11e9-8d9d-1efff365ea07.png)

**The content is fixed on the left side, following the scrolling of the document, and is expanded step by step.**

![image](https://user-images.githubusercontent.com/2121467/68000915-ec3c8e00-fc9c-11e9-84db-0082516c643c.png)

**Comment by spencergibb** [comment]
This was fixed in 2.2.x https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RELEASE/reference/html/
