### ISSUE TITLE
How to delay eureka client registration eureka server?

### ISSUE THREAD

**Issue by kinsey-jian** [spring-cloud/spring-cloud-netflix#3689]
In K8S, I have a Spring Boot application which is also a Eureka client. The normal behavior of the application is to register with Eureka server on start up as UP. I have a requirement that the application shouldn't register with the Eureka server until k8s readiness finished

**Comment by spencergibb** [comment]
Off the top of my head, set initial status to out of service then you're looking update it on some event

**Comment by kinsey-jian** [comment]
thanks
