### ISSUE TITLE
loadBalancer server cache status time properties not correct

### ISSUE THREAD

**Issue by DongJigong** [spring-cloud/spring-cloud-netflix#3690]
Bug report

![image](https://user-images.githubusercontent.com/8855265/68727995-f8abd980-0600-11ea-8af0-478d036a9aa7.png)
With the first time serverList update, server stats information accessTime and connectionTime is not update properly.

**Comment by OlgaMaciaszek** [comment]
There might be an issue with time settings on your machine. Try running `System.currentTimeMillis()` and see what you get; if your time settings are fine, please report an issue directly to https://github.com/Netflix/ribbon as this area belongs to the core library implementation and not Spring Cloud integration.
