### ISSUE TITLE
Spring boot integration Eureka error reporting

### ISSUE THREAD

**Issue by michaelSpica** [spring-cloud/spring-cloud-netflix#3694]
Spring boot integrates Eureka and reports an error: 『org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'javax.servlet.Filter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value=httpTraceFilter)}』
Spring boot version: 2.2.1.RELEASE
Spring cloud version: Greenwich.SR3

**Comment by spencergibb** [comment]
Boot 2.2.x is not compatible with Greenwich. Either downgrade boot to 2.1.x or use hoxton.RC2
