### ISSUE TITLE
Defaultzone property doesn't work without camel case

### ISSUE THREAD

**Issue by garg10may** [spring-cloud/spring-cloud-netflix#3695]
`eureka.client.serivce-url.default-zone=http://localhost:8761/eureka`

The above property doesn't work witthout camel case however other property does. More details. 

eureka.client.serivce-url.default-zone=http://localhost:8761/eureka

**Comment by spencergibb** [comment]
That's correct, default zone is a key in a map, not a property, so it is case sensitive.

**Comment by garg10may** [comment]
How it's identified whether it's a key in map or a property? Can this feature be documented, it doesn't seem intitutive.

**Comment by fkalisa** [comment]
@all I am working on this issue
