### ISSUE TITLE
EurekaServiceInstance Cannot be deserialize

### ISSUE THREAD

**Issue by cashZhang27** [spring-cloud/spring-cloud-netflix#3696]
**Describe the bug**
springcloud Hoxton.RC2
springboot 2.2.1.RELEASE

**Sample**
Cannot construct instance of `org.springframework.cloud.netflix.eureka.EurekaServiceInstance` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

**Comment by spencergibb** [comment]
It's not made for serialization. Please use Dto or transfer object

**Comment by cashZhang27** [comment]
SC LoadBalancer is using EurekaServiceInstance as deserialize entity

**Comment by spencergibb** [comment]
We're moving to in memory only for the cache so it won't need to be serialized

**Comment by cashZhang27** [comment]
I have serialization problems when I use redis reactive, you can try Webflux, data-redis-reaction, sc load balancer starter will report errors, EurekaServiceInstance  do not have default constructors

**Comment by spencergibb** [comment]
I understand, but next release redis won't be used to cache the load balancer instances

**Comment by cashZhang27** [comment]
thank you

**Comment by arke56** [comment]
Hi guys, did you have any solutions?
we the newest load balancer version (3.1.1) 

> I have serialization problems when I use redis reactive, you can try Webflux, data-redis-reaction, sc load balancer starter and Jackson2JsonRedisSerializer will report errors, EurekaServiceInstance do not have default constructors https://gitee.com/cashzhang27/test-java/tree/master/test-cloud/test-cloud-webflux is my demo project

Hi, did  you have any solutions? 
I found gateway(2.1.5.RELEASE) + load balancer(newest 3.3.1 version) always exists the problem. 
i try to upgrade eureka client to 2.1.6.Release, the problem not be resolved.  has you problem been solved?
