### ISSUE TITLE
upgrade zuul-core to 2.1.6

### ISSUE THREAD

**Issue by yilkam** [spring-cloud/spring-cloud-netflix#3697]
I noticed that is using an old and unsupported version of zuul-core 1.3.1 (Nov, 2017) which could be a security concern for Zuul users.
I suggest we upgrade zuul-core to the latest version 2.1.6 (Nov, 2019)

**Comment by spencergibb** [comment]
We are not supporting zuul 2, it is not backwards compatibe. We created spring cloud gateway instead.
