### ISSUE TITLE
Is there a way to get and set path variables from Zuul RequestContext or any way within preFilter class

### ISSUE THREAD

**Issue by RajChitta** [spring-cloud/spring-cloud-netflix#3699]
Does zuul  provide any methods either through Request Context or any other way to get and set path variables of the request?

e.g. :

The original request url is
http://my.domain/uri/acctNbr/balance

From this url, I want to get value of acctNbr (ex- 123456), manipulate/encrypt it and set back (as ex- abcgy0-=gyz-yubhgyt45-0==), into request url.

**Comment by spencergibb** [comment]
You can get the request from request context, then you can get the parameters

**Comment by RajChitta** [comment]
@spencergibb from request I was able to get query parameters but not path variables.
How can I get them from request ?

**Comment by spencergibb** [comment]
It's part of the request uri. It's a standard servlet http request at this point

**Comment by RajChitta** [comment]
@spencergibb yes request uri has those path parameters, do I need to parse that uri with custom logic  to get them?

**Comment by spencergibb** [comment]
Yes

**Comment by RajChitta** [comment]
@spencergibb Is there a better & generic solution rather than parsing manually with custom logic ?

**Comment by spencergibb** [comment]
No
