### ISSUE TITLE
o.a.h.i.e.RetryExec [hystrix-b-86] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://ip:port: The target server failed to respond

### ISSUE THREAD

**Issue by starrynight-1991** [spring-cloud/spring-cloud-netflix#3707]
Spring Cloud Version: Edgware.SR5
spring-cloud-netflix-core Version: 1.4.6.RELEASE

There are two services: A and B. service A calls service B through feign. After a large number of concurrent requests, service A calls service B again. The following error occurs: o.a.h.i.e.retryexec [hystrix-b-86] I / O exception (org. Apache. Http. Nohttpresponseexception) caused when processing request to {}- > http: / / IP: Port: the target server failed to respond.
View source code:
                @Bean
		@ConditionalOnMissingBean(HttpClientConnectionManager.class)
		public HttpClientConnectionManager connectionManager(
				ApacheHttpClientConnectionManagerFactory connectionManagerFactory,
				FeignHttpClientProperties httpClientProperties) {
			final HttpClientConnectionManager connectionManager = connectionManagerFactory
					.newConnectionManager(httpClientProperties.isDisableSslValidation(), httpClientProperties.getMaxConnections(),
							httpClientProperties.getMaxConnectionsPerRoute(),
							httpClientProperties.getTimeToLive(),
							httpClientProperties.getTimeToLiveUnit(), registryBuilder);
			this.connectionManagerTimer.schedule(new TimerTask() {
				@Override
				public void run() {
					connectionManager.closeExpiredConnections();
				}
			}, 30000, httpClientProperties.getConnectionTimerRepeat());
			return connectionManager;
		}
After executing connectionManager.closeexpiredconnections(), execute the code again: connectionManager.closeidleconnections (5, timeunit. Seconds), and no more errors will be reported.

**Comment by spencergibb** [comment]
Edgware is no longer supported. Please update to Greenwich or Hoxton and try again

**Comment by starrynight-1991** [comment]
ok
