### ISSUE TITLE
EurekaServer: wrongly claims self preservation is turned off when renewal threshold is low

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#371]
When the renewal rate is below to computed threshold, the Eureka server UI prints the following message in big red letters:

**RENEWALS ARE LESSER THAN THE THRESHOLD. THE SELF PRESERVATION MODE IS TURNED OFF.THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.**

The message is not 100% correct and misleading: self preservation mode IS actually turned on and the protection mode is currently activated - hence protecting instances from expiring because of network problem or other.

Looking at the UI templates it turns out the message is exactly the same as the one printed when the preservation mode is turned off...

**Comment by dsyer** [comment]
AFAIK we copied the UI code directly from Netflix. If you think there was a transcription error, please can you suggest a fix for it?

**Comment by brenuart** [comment]
I had a look at the code once again, from both the SpringCloud and Netflix repositories...
You are right, there is nothing wrong with the messages - and I'm not able to reproduce the (so-called) issue anymore. I don't get it :-( According to me, you can safely ignore and close this issue. Sorry.

**Comment by dsyer** [comment]
Thanks for looking again. I get a lot of questions about that message. AFAIK it is genuinely reflecting the state of the server, it's just that the state is not very interesting (so the message being red is distracting) if you have a standalone eureka server with only a few registrations.

**Comment by brenuart** [comment]
The message is clear only once you understand how the server is working. Unfortunately, you don't have much information to help you... not even in the logs :-(
To be honest, we had to change the UI at several places to make it clearer and help user to better understand it.

**Comment by dsyer** [comment]
Is there any reason you couldn't contribute some of those changes back to the project?

**Comment by brenuart** [comment]
We could. But some changes require awful hacks like reflection to access private fields, or copy/paste from Netflix methods which are private. So at the end we have something that becomes hard to maintain. We are not very proud of what we have done unfortunately...
Let me take some time to review what we did and see which parts could be contributed back to the project.

**Comment by dsyer** [comment]
Unfortunately, the current state of Eureka makes reflection hacks a necessity and there are plenty of them in Spring Cloud already. It's not something we are proud of either, but you aren't the only one, so please feel free to submit changes containing such hacks. It won't make things much worse and it could make them better.
