### ISSUE TITLE
OutOfMemory handling

### ISSUE THREAD

**Issue by lafual** [spring-cloud/spring-cloud-netflix#3711]
Hi,

I am running a Gateway with Eureka (Boot 2.2.2 HOXTON.RELEASE). On the Gateway I have an end-point which is checking all routes in real-time. 

The end point is as follows;

```
@GetMapping(value = "/applicationStatus", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
public Flux<MyApplication> getApplicationActuator() {
	WebClient webClient = loadBalanced.build();
	return webClient
		.get().uri("lb://SECURITY/applications")  // get a list of Routes
		.retrieve()
		.bodyToFlux(MyApplication.class)
		.filter(p -> p.isActive())
		.flatMap(myApplication ->
			loadBalanced.build()
				.get().uri("lb://" + myApplication.getName() + "/actuator/health")
				.retrieve()
				.bodyToMono(ActuatorStatus.class)
				.onErrorReturn(new ActuatorStatus("DOWN"))
				.map(as -> {
					myApplication.setStatus(as.getStatus());
					return myApplication;
				})
			.repeatWhen(interval -> Flux.interval(Duration.ofSeconds(4)))
		);
}
```

There are 7 routes which are queried every 4 seconds.

With only one browser running this endpoint, after sometime I got the following repetitively for > 12 hours, until I restarted the process;

```
2019-12-12 23:34:49.087 ERROR 2272 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Cannot fetch registry from server
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
2019-12-12 23:35:19.707 ERROR 2272 --- [DiscoveryClient-CacheRefreshExecutor-0] com.netflix.discovery.DiscoveryClient    : Cannot fetch registry from server
java.lang.OutOfMemoryError: Java heap space
```

Admittedly, I was running the Gateway with `-xmx64m` and have since upped to `-xmx128m`. Since then I haven't seen the problem.

However, my questions are;
1. Is it feasible to recommend an `xm` for the Gateway or does it depend on what I am doing (so _suck it and see_)
2. I believe that the `OutOfMemoryError` is not recoverable from a Java point of view. When my application gets to this point it reports the error repetitively. As a consequence, this process took 99% CPU on the server and starved every other process. On catching this error, shouldn't the code effectively fail and return -1 to the OS, so that the outer layer has a chance to deal with it and restart the JVM? As far as I can tell, the error never gets rippled to my code, so there is nothing I can do about it (apart from change `-xmx` again).
3. Shouldn't the above error give a stack trace, not just return the error? (just to clarify whether the error is rippled to my code or not).

**Comment by spencergibb** [comment]
My guess is this has more to do with eureka client (hence the move to s-c-netflix). Eureka client keeps a cache of all services locally.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
