### ISSUE TITLE
Different Guava transitive dependencies

### ISSUE THREAD

**Issue by paul-ovchinnikov** [spring-cloud/spring-cloud-netflix#3716]
There are some closed issues about guava, but problem is still here.
spring-cloud-starter-netflix-ribbon uses guava transitive dependencies of different versions. Therefore maven-enforcer-plugin fails for my projects.
Please consider to use maven-enforcer-plugin in netflix projects to make dependencies convergence up to date. Or update guava dependencies to one version or consider not to use guava.

There is guava transitive dependencies graph:
![guava-dependencies](https://user-images.githubusercontent.com/5802650/71064321-6bc8e280-21a1-11ea-8589-6a4a2a3c08d8.png)

You can see guava versions:
- 16.0
- 16.0.1
- 19.0
for Spring Cloud Netflix 2.1.4

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
