### ISSUE TITLE
can't shutdown tomcat

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-cloud/spring-cloud-netflix#3731]
after run script shutdown.sh , the tomcat application was not exit

**Comment by spencergibb** [comment]
If this has something to do with spring cloud Netflix please provide details and I'll consider reopening

**Comment by zhanglei-1987** [comment]
I guess the CloseableHttpClient not closed  when  the application was  shutdown ，after  analyze   java  stack

**Comment by zhanglei-1987** [comment]
HttpClientRibbonConfiguration

`@Bean
		@ConditionalOnMissingBean(HttpClientConnectionManager.class)
		public HttpClientConnectionManager httpClientConnectionManager(
				IClientConfig config,
				ApacheHttpClientConnectionManagerFactory connectionManagerFactory) {`

fixed

`@Bean(destoryMethod="shutdown")
		@ConditionalOnMissingBean(HttpClientConnectionManager.class)
		public HttpClientConnectionManager httpClientConnectionManager(
				IClientConfig config,
				ApacheHttpClientConnectionManagerFactory connectionManagerFactory) {`




`@Bean
		@ConditionalOnMissingBean(CloseableHttpClient.class)
		public CloseableHttpClient httpClient(ApacheHttpClientFactory httpClientFactory,
				HttpClientConnectionManager connectionManager, IClientConfig config) {`


fixed

`@Bean(destoryMethod="close")
		@ConditionalOnMissingBean(CloseableHttpClient.class)
		public CloseableHttpClient httpClient(ApacheHttpClientFactory httpClientFactory,
				HttpClientConnectionManager connectionManager, IClientConfig config) {`
