### ISSUE TITLE
ZuulProxyAutoConfiguration forms a circular dependency with itself

### ISSUE THREAD

**Issue by ewirch** [spring-cloud/spring-cloud-netflix#3733]
`ZuulProxyAutoConfiguration` requires:
```
@Autowired
private ServiceRouteMapper serviceRouteMapper;
```
and defines it at the same time:
```
@Bean
@ConditionalOnMissingBean(ServiceRouteMapper.class)
public ServiceRouteMapper serviceRouteMapper() {
	return new SimpleServiceRouteMapper();
}
```
this makes application start up fail, when circular references are disabled (`org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.setAllowCircularReferences(false)`).

**Comment by OlgaMaciaszek** [comment]
Hi @ewirch Thanks for reporting it. This, indeed, is the case. As SC Zuul is now in maintenance mode, I don't think we will be working on that, but feel free to provide a PR to fix ti.

**Comment by spencergibb** [comment]
It should be as simple as removing it as a field and adding it as a parameter to the beans that need it.
