### ISSUE TITLE
Feign Client + Eureka - Disable SSL Validation not working

### ISSUE THREAD

**Issue by apatelWU** [spring-cloud/spring-cloud-netflix#3747]
**Describe the bug**
Trying to make call to secured service using feign client by disabling the SSL validation.

**Sample Configuration**
Eureka Config:
![image](https://user-images.githubusercontent.com/58441106/74066251-ca9e2180-49c4-11ea-8e4f-f063891ed117.png)

Feign config to disable SSL validation:
![image](https://user-images.githubusercontent.com/58441106/74066287-dc7fc480-49c4-11ea-97e0-6a7b37f497d8.png)

Client Interface:
`@FeignClient(value = "ServceA",)
public interface ServiceAClient {

    @RequestMapping(method = RequestMethod.POST, value = "/test")
    GenericResponse<?> fireUserNotification(@RequestHeader("Authorization")String token,  @RequestBody String test);

}`

With above configuration, feign is able to resolve the host and port of ServiceA (https://127.0.0.1:8080/test) using eureka but it doesn't disable ssl validation resulting in following error:
`ERROR SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address 127.0.0.1 found (46076ms)`

Using url instead of service id, it is working as expected.

Also, tried to override the ssl socket factory and hostverifier using below code:
![image](https://user-images.githubusercontent.com/58441106/74066478-29639b00-49c5-11ea-9201-634ebdaa99cc.png)

which resulted in unknown host error due feign client not able to resolve host and port from eureka.

**Comment by spencergibb** [comment]
disabling ssl validation in feign has no bearing on ssl validation in the eureka client.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
