### ISSUE TITLE
Random port register in Eureka with port 0

### ISSUE THREAD

**Issue by jmglluch** [spring-cloud/spring-cloud-netflix#3748]
If I confire server.port=0 to set a random port, the component register in Eureka with port 0. Only visually, the registered uri is correct.

![image](https://user-images.githubusercontent.com/59025010/74524890-2d8d3c80-4f20-11ea-8c43-c76b721c0041.png)

I tried with the following combinations:

Spring-boot-starter-parent 2.1.12.release
Netflix-dependencies 2.1.5.release
Cloud-dependencies Greenwich.SR5

Spring-boot-starter-parent 2.2.4.release
Netflix-dependencies 2.2.1.release
Cloud-dependencies Hoxton.SR1

**Comment by OlgaMaciaszek** [comment]
What is the use case here? Usually, random ports are very useful for testing, but what is the scenario for using it with Service Discovery?

**Comment by OlgaMaciaszek** [comment]
Yes, this is not supported and a decision has been taken to only document a workaround. You can see the details (with the workaround) in https://github.com/spring-cloud/spring-cloud-netflix/issues/843.

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-netflix/issues/843.
