### ISSUE TITLE
EurekaServer UI: "Last 1000 cancelled leases" tab always empty

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#375]
The "Last 1000 cancelled leases" tab is always empty.
Cause is a wrong template variable in the `lastn.ftl` template. 

            <table id='lastNCanceled' class="table table-striped table-hover">
              <thead>
                <tr><th>Timestamp</th><th>Lease</th></tr>
              </thead>
              <tbody>
                <#if list5?has_content>
	                <#list lastNCanceled as entry>

Should be:

            <table id='lastNCanceled' class="table table-striped table-hover">
              <thead>
                <tr><th>Timestamp</th><th>Lease</th></tr>
              </thead>
              <tbody>
                <#if lastNCanceled?has_content>
	                <#list lastNCanceled as entry>

Hint: `<#if list5?has_content>` is wrong and should be replaced by `<#if lastNCanceled?has_content>`

**Comment by spencergibb** [comment]
thanks @brenuart!
