### ISSUE TITLE
scheduleRenewalThresholdUpdateTask didn't work!

### ISSUE THREAD

**Issue by Ollamo** [spring-cloud/spring-cloud-netflix#3750]
When client aborted , and it can't excute cancel method. the evitTask invoke it and remove it from registry, but the value of expectedNumberOfClientsSendingRenews  didn't decrease. So the value of numberOfRenewsPerMinThreshold  didn't decrease either. I think scheduleRenewalThresholdUpdateTask  is work for update the value I mentioned. But I found that scheduleRenewalThresholdUpdateTask get the num of application was wrong.The value always 0. 
So I think the value should be the map of the registry.

<img width="654" alt="截屏2020-02-23下午11 34 04" src="https://user-images.githubusercontent.com/18277822/75114890-090a3080-5695-11ea-9538-cea9d5fbee5d.png">

<img width="391" alt="截屏2020-02-23下午11 34 12" src="https://user-images.githubusercontent.com/18277822/75114899-1b846a00-5695-11ea-8fde-7e38b637314a.png">

**Comment by spencergibb** [comment]
Can you describe how to recreate this problem? What versions are you using?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Ollamo** [comment]
> Can you describe how to recreate this problem? What versions are you using?

2.1.4.RELEASE. I think that the task of updateRenewalThreshold did not work.Because the num of registeredapplications is always 0.

**Comment by spencergibb** [comment]
You're describing a very narrow problem that I have no context about. How is your application getting into this state and what problems does it cause.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
