### ISSUE TITLE
[Question]  Eureka and ZULL by applying https Issue.

### ISSUE THREAD

**Issue by heraldjun** [spring-cloud/spring-cloud-netflix#3751]
I am Spring boot 2.1.4 and Greenwich.RELEASE is in use.
I want to use Eureka and ZULL by applying https.
We would appreciate it if you could provide us with a guide on how to set it up.

When requesting https with zull, an error occurs below.

**Caused by zuul: javax.net.ssl.SSLPEERUnverifiedException: Certificate for <xx.xx.xx.xx> do not match any of the subject alternative names: [aaa.bb.cc]**

---------zuul
server:
  port: 20000
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.dat
    key-store-password: testtest
    key-store-type: PKCS12
    key-alias: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20002/eureka/
    fetchRegistry: true
    registerWithEureka: true  
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true     
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
ribbon:
  IsSecure: true
  IsHostnameValidationRequired: false
zuul:       
  sslHostnameValidationEnabled: false
  okhttp:
    enabled: true
  routes:      
    eventsearch:
      path: /event**/**
      serviceId: eventsearch-service
      stripPrefix: false
    .....

------ eureka
server:
  port: 20002     
eureka:
  server:
    enable-self-preservation: false
  client:    
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/  
  instance:
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}

**Comment by ryanjbaxter** [comment]
This is purely an issue with the JVM not trusting the certificate you are using.  You need to install the certificate into the JVM (or use a certificate the JVM trusts) and the issue will be resolved.
