### ISSUE TITLE
springcloud-eureka server’s version(1.3.1) lower than client(1.4.x)

### ISSUE THREAD

**Issue by kaoyahuigui2018** [spring-cloud/spring-cloud-netflix#3754]
We are planning to upgrade springboot1.5.6 to 2.x, which contains
springcloud-eureka will also be upgraded from 1.3.1 (eureka 1.6.2) to 1.4.x (eureka 1.9.2),
But now there are many different projects (non-springboot projects) registered on the eureka server, so we don't want to upgrade the eureka server and only upgrade the client. Is there any problem in this?

**Comment by spencergibb** [comment]
there shouldn't be

**Comment by spencergibb** [comment]
please don't comment the same thing on multiple issues.

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
