### ISSUE TITLE
the eureka client cannot found new instance

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-cloud/spring-cloud-netflix#3757]
When a new instance comes online, the server can see that the instance has been registered, but the newly registered service cannot be found on other clients

**Comment by spencergibb** [comment]
How long did you wait?

**Comment by zhanglei-1987** [comment]
> How long did you wait?

I set it to 5 seconds, but the other services never found the new instance

**Comment by spencergibb** [comment]
What did you set to 5 seconds?

**Comment by zhanglei-1987** [comment]
> What did you set to 5 seconds?

> What did you set to 5 seconds?


eureka.client.registry-fetch-interval-seconds = 5
eureka.instance.lease-expiration-duration-in-seconds = 5
eureka.instance.lease-renewal-interval-in-seconds = 5

**Comment by zhanglei-1987** [comment]
After I redefined EurekaDiscoveryClient, this problem was solved

`
@Bean
public EurekaDiscoveryClient discoveryClient(EurekaClient client, EurekaClientConfig clientConfig) {

	 return new EurekaDiscoveryClient(client, clientConfig);

}
`
