### ISSUE TITLE
Question - Zuul not handling JSESSIONID from downstream.

### ISSUE THREAD

**Issue by smitapadhy-84** [spring-cloud/spring-cloud-netflix#3758]
Hi,
   I have a downstream system which uses spring security to authenticate user using j_spring_security_check  and sends jsessionid via zuul to UI. On zuul I have set sensitiveHeaders as blank in order to pass the jsessionid to UI. 

However, in the subsequent requests from UI the cookie doesnt contain jsession id and hence the authentication fails in downstream. 

jsessionid is not accessible in both UI and zuul layer for any kind of workaround.

Please let me know how this can be handled via zuul.

Thanks in advance.

**Comment by OlgaMaciaszek** [comment]
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
