### ISSUE TITLE
spring-cloud-starter-netflix-eureka-client doesn't launch with STS / Spring Boot 2.2.6

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-cloud/spring-cloud-netflix#3762]
Windows 10 Pro x64
STS4
JDK 11.0.6
Spring Boot 2.2.6.RELEASE

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
			<version>2.2.2.RELEASE</version>
		</dependency>

With this dependency included, STS4 can't launch my app anymore. It was kind of flakey under 2.2.5, but the workaround was to run it in STS as a Java app, now that doesn't work anymore either. Always get the error:

Error: Could not find or load main class org.xxx.yyy.yyyApplication
Caused by: java.lang.ClassNotFoundException: org.xxx.yyy.yyyApplication

App launches find under command line and builds fine with mvnw clean install.

Not sure how to find any troubleshooting on the STS4 launch as it doesn't tell me anything besides that error even though it builds fine and connects to eureka fine.

The server starter runs fine under 2.2.5/2.2.6.

**Comment by spencergibb** [comment]
I don't see what this has to do with spring-cloud-netflix. If it works under maven, we have no specific integration with STS.

**Comment by SledgeHammer01** [comment]
> I don't see what this has to do with spring-cloud-netflix. If it works under maven, we have no specific integration with STS.

Hi Spenser, I understand there is no direct integration with STS. Is it possible there is some conflict with newer versions of Spring Boot or even with STS? If I remove the dependency, the app starts all day long. On the client side, there is ZERO code. I'm just setting eureka.client.service-url.defaultZone in the app properties. Not understanding why this specific dependency is causing issues.

**Comment by spencergibb** [comment]
what conflict? it's clear there is none with boot because it works in maven. STS? I have no idea.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by SledgeHammer01** [comment]
Closing this here... looking like a bug in STS / Eclipse after all :).
