### ISSUE TITLE
EurekaReactiveDiscoveryClient.getInstances() assumes vipAddress.

### ISSUE THREAD

**Issue by TucoBouch** [spring-cloud/spring-cloud-netflix#3763]

**Comment by spencergibb** [comment]
Transferred to spring-cloud-netflix as that is where the issue lies. There would have to be some decision made on how to do this as `getInstancesByVipAddress()` takes a boolean, so you would get secure or not.

**Comment by TucoBouch** [comment]
Ok thanks you
Yes actually, only false is passed to the method

**Comment by taban03** [comment]
Hello everyone,
is there a plan to fix this issue anytime soon? 
Thank you
