### ISSUE TITLE
The /pause endpoint should mark an instance as OUT_OF_SERVICE

### ISSUE THREAD

**Issue by heyjustin** [spring-cloud/spring-cloud-netflix#377]
I believe the intent of the code in the _stop()_ method of _EurekaDiscoveryClientConfiguration_ is to mark an instance as OUT_OF_SERVICE:
```
@Override
public void stop() {
    log.info("Unregistering application " + this.instanceConfig.getAppname()
            + " with eureka with status OUT_OF_SERVICE");
    if (ApplicationInfoManager.getInstance().getInfo() != null) {
        ApplicationInfoManager.getInstance().setInstanceStatus(
                InstanceStatus.OUT_OF_SERVICE);
    }
    this.running.set(false);
}
```

This variant of the  _stop_ method is never executed since the _EurekaDiscoveryClientConfiguration_ implements the _SmartLifecyle_ interface, which states (referring to the _stop(Runnable)_ method):
> The LifecycleProcessor will call only this variant of the stop method; i.e. Lifecycle.stop() will not be called for SmartLifecycle implementations unless explicitly delegated to within this method.

Therefore, a solution to this problem is the delegation to the stop method as follows:
```
@Override
public void stop(Runnable callback) {
	stop();
	callback.run();
}        
```

However, having done that, and tested it locally, the instance is still not marked at OUT_OF_SERVICE in Eureka, even though I see the following message in the log files:
```
INFO 6672 --- [scoveryClient-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_STATUS-APP/XXXXXX:status-app:PID-6672 - retransmit instance info with status OUT_OF_SERVICE
```

I will need to dig deeper to find out why not.

**Comment by heyjustin** [comment]
Ok, I've dug deeper....

When we pause an instance (using the /pause endpoint) this is the flow of events:

**On the instance**
1. The _InstanceStatus_ is marked as OUT_OF_SERVICE (assuming the fix mentioned above is made to _EurekaDiscoveryClientConfiguration_) and flagged as dirty.
2. This is picked up by the _InstanceInfoReplicator_, which calls _register()_ on the _DiscoveryClient_ 
3. This make a remote call to the eureka server with _Action.Register_, i.e. POSTs to http://eureka/apps/{appName} with the payload containing the _InstanceInfo_

**On the eureka server**
1. The REST call is consumed by the method _com.netflix.eureka.resources.ApplicationResource#addInstance_
2. This invokes _registry.register()_, passing in the _InstanceInfo_
3. The _PeerAwareInstanceRegistry_ delegates to its super class (_InstanceRegistry_) to perform the registration
4. In this method (_com.netflix.eureka.InstanceRegistry#register_), the following code is invoked:
```
// Set the status based on the overridden status rules
InstanceStatus overriddenInstanceStatus = getOverriddenInstanceStatus(
		r, existingLease, isReplication);
r.setStatusWithoutDirty(overriddenInstanceStatus);
```
(with r being the new _InstanceInfo_ - which carries the OUT_OF_SERVICE status)

5. In the _getOverriddenInstanceStatus_ method, there is a block of code which is executed if the command is **not** a replication command (ours is not).  The block effectively returns the status on the existing (previous) lease, which is UP in our case:
```
if (!isReplication) {
	InstanceStatus existingStatus = null;
	if (existingLease != null) {
		existingStatus = existingLease.getHolder().getStatus();
	}
	// Allow server to have its way when the status is UP or
	// OUT_OF_SERVICE
	if ((existingStatus != null)
		&& (InstanceStatus.OUT_OF_SERVICE.equals(existingStatus)
			|| InstanceStatus.UP.equals(existingStatus))) {
		logger.debug(
				"There is already an existing lease with status {}  for instance {}",
				existingLease.getHolder().getStatus().name(),
				existingLease.getHolder().getId());
		return existingLease.getHolder().getStatus();
	}
}
```

6. .... and this status is then used as the status of the instance which gets logged as
```
2015-06-06 12:13:17.044  INFO 420 --- [.0-8761-exec-10] com.netflix.eureka.InstanceRegistry      : Registered instance id XXX:status-app:PID-4376 with status UP
```

So, as far as I can see, there is no way to put an instance into OUT_OF_SERVICE unless you are using ASGs etc.  I'm wondering if the reverse holds true too.

I guess this is more of a question for the eureka team, but before I go there, have I interpreted this correctly?

(The original issue of the logic being in the wrong lifecycle method still stands)

**Comment by dsyer** [comment]
My reading of the comments in `InstanceRegistry` is that Eureka prefers to confirm an `OUT_OF_SERVICE` with a health check. We don't have a health indicator relating to application context "running" state, but we certainly could have one. What happens if you add a `HealthIndicator` that reports `OUT_OF_SERVICE` when the context is not running? Does the status flip on the next heartbeat in that case?

**Comment by heyjustin** [comment]
Hi Dave,

> Eureka prefers to confirm an OUT_OF_SERVICE with a health check

Does the eureka server ever call the health check handlers of the instances it is aware of?  My understanding is that it doesn't and that the health check url is only used by asgard (based on [the eureka wiki](https://github.com/Netflix/asgard/wiki/Eureka-Integration#instances-app-names-and-health-check-urls)).  

Perhaps I'm misunderstanding you.  I'll assume that you mean that the eureka client performs a health check and reports this to the server.

I'm looking at the code `HeartbeatThread` inner class in `com.netflix.discovery.DiscoveryClient`.  The execution of this thread (heartbeat) simply reports the status *as currently known* (`Action.Renew`) and does not consult a `com.netflix.appinfo.HealthCheckHandler`.  So I don't believe that I can report a different status using this mechanism.

However, the `com.netflix.discovery.DiscoveryClient.InstanceInfoReplicator` task which also runs at scheduled intervals does consult a `HealthCheckHandler` to determine and report the status.

So I added a `ApplicationContextStateHealthIndicator` health indicator which reports the health of the service as `OUT_OF_SERVICE` if the `ApplicationContext` is not running.

Also added a custom `HealthCheckHandler` which translates a `Status` returned from the `HealthIndicator` into a `InstanceInfo.InstanceStatus` and gets registered into the `DiscoveryClient` by `org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration#start`

I can confirm that the health endpoint is reporting the instance as `OUT_OF_SERVICE` after I execute the `/pause' operations.
The trouble is that although the status is being obtained from the health check handler as `OUT_OF_SERVICE`, the same logic (mentioned above) which overrides the status (`getOverriddenInstanceStatus`) is invoked and the status is reported as UP.

The sample project to illustrate this is here: [https://github.com/heyjustin/eureka-out-of-service](https://github.com/heyjustin/eureka-out-of-service)

**Comment by brenuart** [comment]
What happens if you call `instanceInfo.setOverriddenInstanceStatus(OUT_OF_SERVICE)` instead of `instanceInfo.setStatus(OUT_OF_SERVICE)`?
Don't forget to call `setIsDirty(true)` as well to mark the instance info dirty to trigger replication by  the `InstanceInfoReplicator` thread.

**Comment by heyjustin** [comment]
That works - the instance is marked as `OUT_OF_SERVICE` and this is reflected on the eureka dashboard, but... there doesn't seem to be a way to mark the instance as `UP` again (by invoking the /resume endpoint).  The scenario plays out as follows:

- At this point the eureka server has the instance marked as:
    - overridden status: `OUT_OF_SERVICE`
    - status:  `OUT_OF_SERVICE`
- The overridden status is also stored in the `overriddenInstanceStatusMap` against the instance key.

We then invoke the `/resume/` endpoint, which triggers the `start()` method in `EurekaDiscoveryClientConfiguration`

I've tried two things, neither of which work:

1. Set the status to `UP` in the `start` method of `EurekaDiscoveryClientConfiguration` (this is what the current code does)
2. Set the status to `UP` **and** set the override the status to `UP`.

The reason neither of these work is a result of the logic in the `com.netflix.eureka.InstanceRegistry#register` method, specifically this block of code:

```
if (!InstanceStatus.UNKNOWN.equals(r.getOverriddenStatus())) {
	logger.debug(
			"Found overridden status {} for instance {}. Checking to see if needs to be add to the "
			+ "overrides", r.getOverriddenStatus(), r.getId());
	if (!overriddenInstanceStatusMap.containsKey(r.getId())) {
		logger.info(
				"Not found overridden id {} and hence adding it",
				r.getId());
		overriddenInstanceStatusMap.put(r.getId(),
				r.getOverriddenStatus());
	}
}
InstanceStatus overriddenStatusFromMap = overriddenInstanceStatusMap.get(r.getId());
if (overriddenStatusFromMap != null) {
	logger.info(
			"Storing overridden status {} from map", overriddenStatusFromMap);
	r.setOverriddenStatus(overriddenStatusFromMap);
}
``` 

- The the `overriddenInstanceStatusMap` always contains the first override status.  i.e. `overriddenInstanceStatusMap` is not updated even if we set a new override status.
- The status fetched from the `overriddenInstanceStatusMap` map (`OUT_OF_SERVICE` in our case) is then used to set `r`'s overridden status.
- .. and then the method `com.netflix.eureka.InstanceRegistry#getOverriddenInstanceStatus` is invoked which returns this overridden status - which is used. 

(The above is slightly different if we set the override status to `UP` in the start method.  In this case on startup the override status is communicated as `UP` and we are stuck in this state for the same reason).

**Comment by heyjustin** [comment]
I'm wondering if I'm barking the the wrong tree by using the `InstanceInfoReplicator` to take an instance in and out of service.

The following comment in the `com.netflix.eureka.resources.InstanceResource#statusUpdate` method caught my eye and seems to confirm this somewhat:
```
Handles InstanceInfo.InstanceStatus updates.

The status updates are normally done for administrative purposes to change the instance status
between InstanceInfo.InstanceStatus.UP and InstanceInfo.InstanceStatus.OUT_OF_SERVICE to
select or remove instances for receiving traffic.
```

If I open up my REST client, the following PUT method do exactly what I'm looking for:

To take an instance out of service:
```
http://localhost:8761/eureka/apps/<app-name>/<app-id>/status?value=OUT_OF_SERVICE
```

To put an instance back in service:
```
http://localhost:8761/eureka/apps/<app-name>/<app-id>/status?value=UP
```

(Obviously replacing `<app-name>` and `<app-id>` with your specific information.)

I guess it would be useful to invoke this endpoint from the stop/(re)start() methods of the container's lifecycle.  I can't see that this endpoint is used anywhere inside the eureka client libraries, but I may be missing something....

Thoughts?

**Comment by dsyer** [comment]
Sounds sensible. If you try something and it works please send a PR.

**Comment by brenuart** [comment]
This is exactly what I had in mind either... According to me, the `InstanceInfo` class holds much more information than required by the client: this probably also contains stuff that should be owned by the server only. The `overriddenStatus` may be one of those properties.

The REST API (https://github.com/Netflix/eureka/wiki/Eureka-REST-operations) describes how to declare an instance out of service. If it is the way to go, it would also means that `setStatus` shouldn't be invoked by the client... Looks strange (and scary).

**Comment by brenuart** [comment]
Have a look at the comments in the `InstanceStatus` enum class:

        UP,             // Ready to receive traffic
        DOWN,           // Do not send traffic- healthcheck callback failed
        STARTING,       // Just about starting- initializations to be done - do not send traffic
        OUT_OF_SERVICE, // Intentionally shutdown for traffic
        UNKNOWN;

My understanding is when an instance wants to put itself "out of service", it should set its status to `DOWN`. The intend of `OUT_OF_SERVICE` is for external parties to override the instance status and divert traffic out of it.

I made a quick a dirty test, and things seems to be working as expected:
Set the instance status DOWN:

    ApplicationInfoManager.getInstance().getInfo().setStatus(InstanceStatus.DOWN);
    ApplicationInfoManager.getInstance().getInfo().setIsDirty(true);

Set the instance status back to UP:

    ApplicationInfoManager.getInstance().getInfo().setStatus(InstanceStatus.UP);
    ApplicationInfoManager.getInstance().getInfo().setIsDirty(true);

**Comment by heyjustin** [comment]
The change in the associated PR (#390) simply sets the status to DOWN when the `stop()` method is called.  I've tested this too and it provides the functionality that is required.  

> DOWN,           // Do not send traffic- healthcheck callback failed

The only (subtle) difference is that we aren't relying on a heathcheck callback *per se* to mark the instance as down, but rather the state of the application context.
