### ISSUE TITLE
 WARN 89361 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: expired lease for INVENTORY/192.168.203.14:inventory:8084 and Eureka client showing killed

### ISSUE THREAD

**Issue by satyamk328** [spring-cloud/spring-cloud-netflix#3774]
Hi

I am facing issue in eureka Server:
2020-04-11 00:21:32.472  WARN 89361 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : DS: Registry: expired lease for INVENTORY/192.168.203.14:inventory:8084

Eureka Client/Service error
**************************************
showing Killed and stop this services

Four to five service registered on eureka server. We are calling services through zuul proxy server. Below are the configuration file
Eureka SERVER
**************************************************************
server.address=localhost

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone= http://localhost:8088/eureka/
eureka.instance.ip-address=true
eureka.server.eviction-interval-timer-in-ms = 9000
eureka.server.renewalPercentThreshold=0.33
eureka.server.peer-node-connect-timeout-ms=60000
eureka.server.peer-node-read-timeout-ms=60000
eureka.server.max-threads-for-peer-replication=0
eureka.server.enable-self-preservation=false
eureka.instance.hostname=localhost  

logging.level.com.netflix=WARN
logging.level.org.springframework.web=WARN
logging.level.net.texala=WARN

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds= 10000
ribbon.MaxAutoRetries=1
ribbon.MaxAutoRetriesNextServer=1
ribbon.OkToRetryOnAllOperations=true
ribbob.ConnectTimeout=60000
ribbon.ReadTimeout=60000
Service Configuration
*************************************************************
eureka.client.enabled=true
eureka.client.healthcheck.enabled=true
eureka.client.region = default
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8088/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.appname=inventory

eureka.client.eurekaServiceUrlPollIntervalSeconds=60
eureka.instance.lease-renewal-interval-in-seconds = 30
eureka.instance.lease-expiration-duration-in-seconds = 90
eureka.instance.leaseRenewalIntervalInSeconds=30
eureka.instance.leaseExpirationDurationInSeconds=90
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
jetty.threadPool.maxThreads=10
jetty.threadPool.minThreads=2
jetty.threadPool.idleTimeout=60000

Zuul Proxy Configuration
************************************************************
eureka:
  instance:
    appname: zuul-proxy-server
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 60
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    enabled: true
    healthcheck:
      enabled: true
    region: default
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 60
    serviceUrl:
        defaultZone: http://localhost:8088/eureka/

jetty:
   threadPool:
        maxThreads: 10
        minThreads: 2
        idleTimeout: 60000

management:
 endpoints:
   web:
     exposure:
       include: '*'
     
zuul:
  host:    
      connect-timeout-millis: 60000
      socket-timeout-millis: 60000
  sensitiveHeaders: Cookie,Set-Cookie
  prefix:  /api
  routes:
      oauth:
      path: /oauth/**
      url: http://localhost:8081/oauth

ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
	
How to resolve this issue

**Comment by spencergibb** [comment]
are you having an actual problem? the exception you posted is just a warning.

**Comment by satyamk328** [comment]
I am facing in eureka server 
 [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry : DS: Registry: expired lease for service
and client services are showing message killed

**Comment by OlgaMaciaszek** [comment]
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by satyamk328** [comment]
I resolved this issue and added some configuration eureka server:

eureka.server.expected-client-renewal-interval-seconds=3
eureka.instance.lease-expiration-duration-in-seconds=90
eureka.server.eviction-interval-timer-in-ms=60000
eureka.server.renewal-percent-threshold=0.85
eureka.server.renewal-threshold-update-interval-ms=900000
