### ISSUE TITLE
can't expose prometheus metrics from spring boot apps registered with spring cloud eureka server

### ISSUE THREAD

**Issue by satworkz** [spring-cloud/spring-cloud-netflix#3791]
**Describe the bug**
I am trying to implement prometheus monitoring for spring boot apps but my spring boot apps are registered with spring cloud eureka server so I don't have an option to configure static ports for the apps in prometheus config, I can only configure scrapping for eureka server like below but not for the apps registered with eureka. Can anyone please suggest?

**Sample**
static_configs:
  - targets: ["http://mycompany.eurekaserver.net:8761"]

**Comment by spencergibb** [comment]
There's no integration with Prometheus and eureka that I know of
