### ISSUE TITLE
Eureka client cannot get service instance list when application is using external configuration service

### ISSUE THREAD

**Issue by wangzw** [spring-cloud/spring-cloud-netflix#3797]
**Describe the bug**
After upgrading to spring cloud Hoxton.SR4 and spring boot 2.2.7.RELEASE. Eureka client cannot get service instance list anymore.

**Sample**
The issue happened when application is configured to bootstrap from external configuration service. In such case, the application first bootstrap and a DiscoveryClient bean is created to locate configuration service from Eureka and retrieve external configuration. And then DiscoveryClient instance is shutdown and application restart from external configuration. But legacy DiscoveryClient instance is reused soon afterwards.

**Comment by wangzw** [comment]
https://github.com/wangzw/eureka-issue-3797 is a demo project to reproduce the issue.

**Comment by spencergibb** [comment]
Duplicates #3795

**Comment by wangzw** [comment]
> Duplicates #3795

Are you sure it's a duplicated issue with #3795? It is created on 26 Sep 2016 but I found this issue after upgrading spring cloud to Hoxton.SR4. It works well with Greenwich.SR5

**Comment by spencergibb** [comment]
Yes, we will no longer be creating discovery client in bootstrap

**Comment by wangzw** [comment]
> Yes, we will no longer be creating discovery client in bootstrap

Any reason why it works well with Greenwich.SR5, I spend two days but have not clues which commit introduce this regression and how to fix it. Our application stop working after upgrading. Any suggestion of workaround or fixing?

**Comment by spencergibb** [comment]
There's not a single reason. I don't know how you can work around this without the fix started in #3796

**Comment by wangzw** [comment]
So I guess that downgrading to Greenwich.SR5 is the only way before #3796 getting into release. 
Thanks.
