### ISSUE TITLE
Intermittent Zuul Broken Pipe Error | JSON response | size less than 2 MB

### ISSUE THREAD

**Issue by donpaulcj** [spring-cloud/spring-cloud-netflix#3799]
I am using Zuul proxy server. Zuul is routing around 20k requests per hour. For few requests ,java.io.IOException occurs within 8 seconds.

Error:

class=o.s.c.n.z.f.post.SendResponseFilter message="Error while sending response to client: java.io.IOException: Broken pipe"

Please find below timeout configuration

zuul: host: socket-timeout-millis: 90000 connect-timeout-millis: 90000

Response body size is less than 2 MB.

There was a solution proposed in github with **/zuul** prefix ([github broken pipe issue 2180](https://github.com/spring-cloud/spring-cloud-netflix/issues/2180)). But that link is no longer available. Thanks in advance for any clue for solved this

> class=o.s.c.n.z.f.post.SendResponseFilter message="Error while sending response to client: java.io.IOException: Broken pipe"

> class=o.s.c.n.z.filters.post.SendErrorFilter message="Error during filtering" com.netflix.zuul.exception.ZuulException: Filter threw Exception at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:227) ~[zuul-core-1.3.1.jar!/:1.3.1] at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) ~[zuul-core-1.3.1.jar!/:1.3.1] at

**Comment by spencergibb** [comment]
https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.2.0.RELEASE/reference/html/#uploading-files-through-zuul

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
