### ISSUE TITLE
Zuul prefix is not working with services registered with Eureka.

### ISSUE THREAD

**Issue by hrandika** [spring-cloud/spring-cloud-netflix#381]
Services registered with Euraka then get automaticaly registered with Zuul.
Ex: Mapped URL path [/user/**] onto handler of type
Here I have a 'user' service registred to eureka as well as the zuul itself.
What I wanted that service is mapped to /api/user from zuul. So I have added 

server:
  port: 8081
zuul:
  prefix:/api

in gateway.yml which is the configurations of zuul that get from configuration server. 
But the prefix is not working. have to go with 
localhost:8081/user
insted i want service to be mapped to
localhost:8081/api/user
anything I'm doing wrong?

**Comment by hrandika** [comment]
Got it working. Just need to add 
  strip-prefix: true 
.

**Comment by Syy0n** [comment]
Which version did you use? With Brixton.SR6 automatic route creation in zuul does not work

**Comment by spencergibb** [comment]
@Syy0n please open a new issue with steps to reproduce or a sample project if you think there is a bug rather than commenting on an issue closed more than a year ago.
