### ISSUE TITLE
hystrix-dashboard cannot display monitoring data normally due to jQuery upgrade in 2.2.3.RELEASE

### ISSUE THREAD

**Issue by SkyJourney** [spring-cloud/spring-cloud-netflix#3811]
In `spring-cloud-netflix-hystrix-dashboard:2.2.3.RELEASE`, We see that `jQuery` has been upgraded to `3.4.1` from `2.1.1`.

For `monitor.ftlh` line **111**, js code has not changed from the previous version. But from `jQuery3.x`, `.load(handler)` has been removed. This line of code will cause the console to report an error and will not be able to display any data but always display **Loading**.

plz fix it.

Maybe can use `$(window).on("load",function)`

**Comment by MadeInChina** [comment]
+1
```
jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at k.fn.init.k.fn.load (jquery.min.js:2)
    at monitor?stream=http%3A%2F%2F192.168.2.100%3A6000%2Faccounts%2Factuator%2Fhystrix.stream&title=192.168.2.100:110
```

**Comment by vudt93** [comment]
+1
Update version of Spring Cloud down to Finchley.SR4 would down the version of jquery to 2.1.1
Also down the version of Spring Boot to 2.0.5 for compatible dependency
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.SR4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>.

**Comment by MadeInChina** [comment]
[waiting for merge ](https://github.com/spring-cloud/spring-cloud-netflix/pull/3817)

**Comment by spencergibb** [comment]
Closing in favor of #3817
