### ISSUE TITLE
spring-cloud-starter-hystrix-dashboard  jquery3.4.1 usage error

### ISSUE THREAD

**Issue by weissxu** [spring-cloud/spring-cloud-netflix#3816]
**Describe the bug**
version:
`    <spring-cloud.version>Hoxton.SR5</spring-cloud.version>
    <hystrix-dashboard.version>2.2.3.RELEASE</hystrix-dashboard.version>`

Hoxton.SR5 with query version: 3.4.1，in file: monitor.ftlh，the usage of jquery as follow：
`$(window).load(function()`

right usage is :
`$(window).on("load",function()`

**Sample**
hystrix-dashboard loading, and can not go on..

**Comment by spencergibb** [comment]
closing in favor of #3817
