### ISSUE TITLE
EurekaHealthIndicator does not see updates if 

### ISSUE THREAD

**Issue by ldeschuyter** [spring-cloud/spring-cloud-netflix#3820]
Spring-cloud version 2.2.2.RELEASE

We use following relevant config
```
spring.cloud.config.discovery.enabled=true
eureka.client.enabled=true
eureka.client.healthcheck.enabled=true

```

We use the service-registry to discover de configserver. This means that an Eurekaclient is created when the application starts. It get shutdown afterwards by execution of the PostConstruct of `EurekaDiscoveryClientConfigServiceAutoConfiguration`. This will shutdown the refresh cycle so no updates get fetched.

The application continues to start and another Eurekaclient gets created. This means that there are 2 clients present in de Context. One who fetches the updates and one who doesn't.

It sometimes happens that when the `EurekaHealthIndicator` gets constructed the "shutdown-one" gets inserted and hence updates are not visible.

**Comment by spencergibb** [comment]
This is no longer the issue with 2.2.3

**Comment by ldeschuyter** [comment]
@spencergibb indeed I've upgraded to Hoxton.SR5 and it solved the problem. 

Thanks for the quick response!
