### ISSUE TITLE
FeignLoadBalancer can't set loadBalancerKey

### ISSUE THREAD

**Issue by SkillyZ** [spring-cloud/spring-cloud-netflix#3821]
I want to overwrite Ribbon IRule.
public Server choose(ILoadBalancer lb, Object key)
but I found 'key' is null.
how can I solve?

i know [issues/1272]( https://github.com/spring-cloud/spring-cloud-netflix/issues/1272)  solved。
but this is in the zuul `RequestContext.getCurrentContext().set(LOAD_BALANCER_KEY, "any value you want");
`
my question is how to set loadBalancerKey in the  FeignLoadBalancer？

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-openfeign/issues/359. Please don't cross-post.
