### ISSUE TITLE
Client rest end point '/actuator/service-registry/instance-status' not working any more after upgrade to Hoxton.SR5

### ISSUE THREAD

**Issue by hatzhang** [spring-cloud/spring-cloud-netflix#3826]
We are using client side rest end point  '/actuator/service-registry/instance-status'  to do blue/green deployment. Before we shutdown our service we make following request to acknowledge other services.
`   curl -X POST -H 'Content-Type: application/json'  -d 'OUT_OF_SERVICE' "http://localhost:8080/internal/actuator/service-registry/instance-status"`

When trying upgrade to  Hoxton.SR5, the end point not working any more.
`{"timestamp":"2020-06-24T14:20:55.013+08:00","status":404,"error":"Not Found","message":"No message available","path":"/actuator/service-registry/instance-status"}`

So what should we do?

**Comment by hatzhang** [comment]
can use the following instead:
`curl 'localhost:8080/internal/actuator/service-registry' -X POST -H 'Content-Type: application/json' -d '{"status":"UP"}'`
[Service-registry endpoint](https://github.com/spring-cloud/spring-cloud-commons/issues/310)

**Comment by dpzain** [comment]
I have a similar problem. i`ve  customed implements the registry by etcd;   But ServiceRegistryEndpoint （ '/service-registry/instance-status'） is not work!    always 404.what reason？
