### ISSUE TITLE
Using eureka dns discovery with spring.cloud.config.discovery.enabled=true doesn't resolve correct eureka address.

### ISSUE THREAD

**Issue by ankeway** [spring-cloud/spring-cloud-netflix#3827]
Spring Cloud HoxtonSR6 
Spring Boot 2.2.8.Release
Use eureka + scconfig， eureka base on DNS discovery
```
spring.cloud.config.discovery.enabled=true
use-dns-for-fetching-service-urls: true
eureka-server-d-n-s-name: xxxxxx.com
eureka-server-u-r-l-context: eureka
eureka-server-port: ${EUREKA_SERVER_PORT:30000}
```

spring-cloud-netflix-eureka-client-2.2.3.RELEASE.jar
```
spring.factories
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
org.springframework.cloud.netflix.eureka.config.EurekaConfigServerBootstrapConfiguration
```

DiscoveryClientConfigServiceBootstrapConfiguration.class is runing before EurekaClientAutoConfiguration.class
so  can't getConfigServerInstances from ConfigServerInstanceProvider.getConfigServerInstances

and console show
```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8761/eureka/apps/": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
```

Spring Cloud HoxtonSR5
Spring Boot 2.2.7.Release
also have same problem.

**Comment by spencergibb** [comment]
As of Hoxton.SR6 (#3796), `EurekaConfigServerBootstrapConfiguration` uses http to find config server rather than `EurekaClient`. `EurekaClientAutoConfiguration` is no longer used in bootstrap.

**Comment by ankeway** [comment]
> As of Hoxton.SR6 (#3796), `EurekaConfigServerBootstrapConfiguration` uses http to find config server rather than `EurekaClient`. `EurekaClientAutoConfiguration` is no longer used in bootstrap.

So，Eureka Base on DNS Discovery is no longer support to find scconfig instanance?  can only instead of http to solve this problem?

**Comment by spencergibb** [comment]
I used `EndpointUtils.getServiceUrlsFromConfig()` when I should have used `EndpointUtils..getDiscoveryServiceUrls()` which takes the above into account.
