### ISSUE TITLE
Could not customize the Sync interval  between Eureka peers after a service goes down

### ISSUE THREAD

**Issue by asharani-m** [spring-cloud/spring-cloud-netflix#3828]
Could not customize the Sync interval  between Eureka peers .When a service goes down It takes 10 min to for Peer1 to communicate the service down status with Peer2.
Setting **eureka.server.peer-eureka-status-refresh-time-interval-ms=1000**
Does not work for me . Any suggestion please ?

**Comment by spencergibb** [comment]
What version are you using? Please describe "doesn't work".

**Comment by asharani-m** [comment]
@spencergibb  
springCloudVersion - Hoxton.SR5

I was trying to reduce the Sync time between Eureka peers, when a service goes down and status is synced by Peer1 to Peer2
Tried with below config(with understanding that below is the correct config to be tweaked)
eureka.server.peer-eureka-status-refresh-time-interval-ms=1000

But , the update interval remained to be 10min (the default) .

**Comment by asharani-m** [comment]
@spencergibb  any inputs on this please?

**Comment by spencergibb** [comment]
try `peer-eureka-nodes-update-interval-ms`. That is what defaults to 10 minutes

**Comment by asharani-m** [comment]
@spencergibb  It works .Thanks
