### ISSUE TITLE
Consistent ordering for RibbonClients.defaultConfiguration's

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#383]
See conversation in #374

**Comment by brenuart** [comment]
I would love it if it could behave like with the "main" application context: you provide sensible defaults by auto configuration, and I can override them by injecting my own beans. You know, just like with the Auto Configuration... see what I mean?

I don't know the auto configuration stuff works behind the scenes, but to me all happens as if my beans simply hide/override the default ones. With that strategy, an error would be raised if I register more than one bean of a given type. Like with the "normal" context...

I even wonder if `@RibbonConfig` shouldn't simply be enhanced to allow ones to inject new beans of any types in the context. Let me take an exemple: I'd like to react on some application events in the parent context to act on the load balancer. Well, you can imagine all sorts of things... I'm just looking here for a way to add beans to the context created for the client.

**Comment by spencergibb** [comment]
I think that may be what is happening.  Changing the order didn't matter, it always picked your custom server list impl regardless of whether your default config was first or last (in `SpringClientFactory`).  I'll wait for @dsyer to comment, maybe this issue isn't needed.

**Comment by brenuart** [comment]
@spencergibb I had a look at your test case and it fails on my platform. Looks like the `RibbonClientDefaultConfigurationTestsConfig` configuration is not loaded at all.
Shouldn't you add it to the `TestConfig`?

	@EnableAutoConfiguration
	@Configuration
	@Import(RibbonClientDefaultConfigurationTestsConfig.class)
	public static class TestConfig {

	}

**Comment by spencergibb** [comment]
@brenuart I did commit a version that was broken b746ad5504c29ca55c009b16266266a4894a7234, but then committed a fix in 0f2fbf8e1cd4dddd6170610c3bd436cef85d382f

**Comment by brenuart** [comment]
Some feedback and share my experience...
I played a bit with this fix and it wasn't working. My mistake was to create a configuration bean with the same class name as yours:

    com.mycompany.boot.ribbon.EurekaRibbonClientConfiguration
    org.springframework.cloud.netflix.ribbon.eureka.EurekaRibbonClientConfiguration

When they are added to the application context, Spring gives them a name set after the class name. So they got both the same bean name. Since mine was added first, your bean definition overridden mine. This is shown by the following trace in the log output:

    ...s.b.factory.support.DefaultListableBeanFactory Overriding bean definition for bean 'eurekaRibbonClientConfiguration': replacing [Generic bean: class [com.mycompany.boot.ribbon.EurekaRibbonClientConfiguration] ...with [Generic bean: class [org.springframework.cloud.netflix.ribbon.eureka.EurekaRibbonClientConfiguration]; ...

Everything worked fine after I changed the class name of my config bean.
This shows that the order configurations are applied by the `SpringClientFactory` may have an importance.

**Comment by spencergibb** [comment]
Good to here.  Does this need to stay open?

**Comment by brenuart** [comment]
As far as I understand, the name collision scenario described here can happen in any application context - not only those created by the `SpringClientFactory`. So everything looks right with your fix. 

However, I wonder how I can guarantee my configuration bean will never be overridden "by mistake" by another coming from a third-party lib for instance. I'm worried...
