### ISSUE TITLE
Eureka Server Dashboard is not loading

### ISSUE THREAD

**Issue by amoljore751986** [spring-cloud/spring-cloud-netflix#3836]
**Local and Server setup**

application.properties
```
eureka.port=8010
server.port=${eureka.port}
spring.application.name=eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:${eureka.port}/eureka

spring.security.user.name=test
spring.security.user.password=T35T
```

When I try to load it from my local environment it works well, but when I deploy the JAR file on server it is not opening the dashboard, there are no errors on log and also all required ports are open.

Note : I am also trying to do 
`wget http://test:test@127.0.0.1:8010/eureka` 
OR `http://127.0.0.1:8010` 
OR `wget http://test:test@127.0.0.1:8010` 

on server it does not give me any response;  
but on my local environment it works.

Here is my eureka.pom file
[eureka.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/4912474/eureka.txt)

Can someone please help to understand if I am missing something here.

Thanks

**Comment by ryanjbaxter** [comment]
We need more information, what server are you deploying the jar file to?  What if you just run the jar file locally?  If you could provide the entire project that might be useful. There is nothing in the POM that looks suspicious.  Can you try turning on debug logging and seeing if that reveals anything?

**Comment by amoljore751986** [comment]
Thanks @ryanjbaxter , I think it just taking time load Eureka Dashboard on Linux server(18.4) (DigitalOcean). but worked fine after loading successfully and also registering the other MS with Eureka.

It take time for these countless processes : `c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms` : around 5 minutes on every restart, rest everything looks ok.

I will check resolve this secondary issue first : already added this property but still it takes time `eureka.server.enableSelfPreservation=false`.

I thin we can close this issue.
