### ISSUE TITLE
Zuul 2 as Proxy for WebSocket STOMP Spring Boot Full Duplex

### ISSUE THREAD

**Issue by macsharker6** [spring-cloud/spring-cloud-netflix#3838]
Hi,
  I would like to know if Zuul 2 (in detail I'am using the dependency:
**org.springframework.cloud:spring-cloud-starter-netflix-zuul:jar:2.1.2.RELEASE** that has org.springframework.cloud spring-cloud-netflix-zuul 2.1.2.RELEASE version)
can be used as a proxy for WebSocket service that use STOMP in full duplex communication. This proxy actually is using as Proxy for rest services and I would use the same for webSocket STOMP with Spring Boot. If is not possible for this version there is a version compatibility for this use? 

There is a version in which ZUUL can proxy WebSockets to another backend server in full duplex mode?

Regards.

**Comment by spencergibb** [comment]
We will not be adding support for zuul 2

**Comment by macsharker6** [comment]
@spencergibb  thanks for your answer. 
In your opinion, in a hybrid architecture (WEBSOCKET + HTTP) is it good practice to use 2 gateways: Zuul for HTTP communication and Spring Cloud Gateway for WEBSOCKET communication? Alternatively, in this scenario is it recommended to use only Spring Cloud Gateway? Greetings.
