### ISSUE TITLE
Eureka Server works with Maven but not with Gradle - Spring boot 2.3.1, Java 11

### ISSUE THREAD

**Issue by abitgen** [spring-cloud/spring-cloud-netflix#3842]
**Bug**
Eureka Server page opens when accessing localhost:8761 with maven build, the same app in gradle shows 404 WhiteLabel error page. Using Spring boot 2.3.1, Java 11

****
  1. Download  from Spring Initializer. with following configs

![image](https://user-images.githubusercontent.com/10978904/88267622-b63daf00-ccee-11ea-8633-2ac81f2277e1.png)

  2. Add `@EnableEurekaServer` in Main Class

  3. Add config in application.properties

```
spring.application.name=netflix-eureka-naming-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
```

  4. Run the application, access localhost:8761 -> throws 404

**Comment by spencergibb** [comment]
Can you explain how you are running the apps?

**Comment by abitgen** [comment]
I use Intellij idea and I directly run the main method.

**Comment by spencergibb** [comment]
I'm unable to reproduce the problem.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by abitgen** [comment]
Hi PFA the requested sample, I am using gradle 5.6.2 and intellij 2019.1
[discovery-service.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/4968108/discovery-service.zip)

**Comment by abitgen** [comment]
Tried with gradle 6.4.1 and kotlin compile version 11/ gradle 5.6.2 and kotlin compile version 1.8 today its working as expected. Don't understand what caused the issue in the first place. Closing it now.
