### ISSUE TITLE
Eureka: allow one to provide its own DiscoveryManagerInitializer

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#386]
The configuration class responsible for the creation of `DiscoveryManagerInitializer` is a PROTECTED inner class of `EurekaDiscoveryClientConfiguration`.

Since it is protected, I can't write the following when building my own auto configuration:

    @AutoConfigureBefore(EurekaDiscoveryClientConfiguration.DiscoveryManagerInitializerConfiguration.class)
    public class MyEurekaAutoConfiguration {
       @Bean
       @ConditionalOnMissingBean(DiscoveryManagerInitializer.class)
       public DiscoveryManagerInitializer discoveryManagerInitializer() {
           ....
       }
    }

Would it be possible to change `DiscoveryManagerInitializerConfiguration` class and make it public ?

**Comment by spencergibb** [comment]
We can do anything, the question is why do you want to?  What's the use case?

**Comment by spencergibb** [comment]
isn't creating a `@Bean` of type `DiscoveryManagerInitializer` enought?

**Comment by brenuart** [comment]
In our case, we override the init() method to log information about the Eureka configuration, coming from both the `EurekaInstanceConfig` and `EurekaClientConfig`. The `DiscoveryManagerInitializer` appeared to us to be the best candidate:
- invoked only if Eureka client is actually used
- invoked juste before Eureka client is initialised 

Creating a `@Bean` is enough - except that this code will be part of our internal library and want people to still be able to provide their own instance _if needed_. Just like what you did inside your own configuration class.

**Comment by spencergibb** [comment]
Again, they should still be able to provide their own @Bean.  I still don't see why our configuration needs to change.

**Comment by brenuart** [comment]
Ok. Let's see it differently: why did you add `@ConditionalOnMissingBean(DiscoveryManagerInitializer.class)` on your configuration?

**Comment by spencergibb** [comment]
To not create that bean if one is already provided

**Comment by brenuart** [comment]
;-)
Same in our case... We'd like not to create that bean if user of our lib already provided one. But if I add that condition on my method, then yours wins - juste because I wasn't able to tell Spring to consider my configuration before yours (because it is protected).
Did I miss something?

**Comment by spencergibb** [comment]
but if a user of your lib defines an `@Bean` of `DiscoveryManagerInitializer` neither the one from s-c-netflix or from your lib will be created.

**Comment by brenuart** [comment]
You may be right - I may have misunderstood how SpringBoot behaves in that case.
If true, then I don't see the purpose of the `@ConditionalOnMissingBean`. My understanding is that:

    @Bean
    public DiscoveryManagerInitializer discoveryManagerInitializer() {
    }

creates a bean whose name is `discoveryManagerInitializer`. If one wants to provide his own instance, it has to create it with the *same name*. However, if my factory method was declared as follows:

    @Bean
    @ConditionalOnMissingBean
    public DiscoveryManagerInitializer discoveryManagerInitializer() {
    }

then, it would be overridden if a bean of the same type is already provided, whatever its name. 
Is this correct?

**Comment by spencergibb** [comment]
I think that is right.  Regardless the apps initial configuration should win if the conditions are right.

**Comment by brenuart** [comment]
Ok, so if it works as described, not being able to annotate my method with `@ConditionalOnMissingBean` forces my users to name their own bean with exactly the same name.
Would have been better if they just had to provide a bean of the same type, but not a big problem.

If you still think you shouldn't change your configuration, feel free to close the issue and mark it as invalid.

Thanks for your help and time spent on it.

**Comment by brenuart** [comment]
Additional note: in their DI refactoring work, Netflix has deprecated the `DiscoveryManager` class. So the use of the `DiscoveryManagerInitializer` in SpringBoot is likely to disappear in future versions as well.
