### ISSUE TITLE
when eureka server return transfer-encoding:chunked, seems  eureka client can not parse data

### ISSUE THREAD

**Issue by leonSmiler** [spring-cloud/spring-cloud-netflix#3866]
i am using spring-version :
springbootversion= "2.0.9.RELEASE"
springcloudversion = 'Finchley.SR4'

when running a eureka server  with jetty , and  when service register to eureka server ,get error below:

2020-08-04_21:09:51.359 [INFO ] [DiscoveryClient-CacheRefreshExecutor-0] [c.netflix.discovery.DiscoveryClient] Getting all instance registry info from the eureka server
2020-08-04_21:09:51.363 [ERROR] [DiscoveryClient-CacheRefreshExecutor-0] [c.n.d.s.t.d.RedirectingEurekaHttpClient] Request execution error
com.sun.jersey.api.client.ClientHandlerException: java.util.zip.ZipException: Not in GZIP format

i found server side response with head: chunked

this cause only on my code intergate with spring -cloud . sample eureka -server ,eureke-client seems did not get this error

**Comment by spencergibb** [comment]
Those are old unsupported versions, please update to boot 2.3.x and spring cloud Hoxton.SR7 and try again.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
