### ISSUE TITLE
I think ZonePreferenceServerListFilter  is redundant

### ISSUE THREAD

**Issue by lzflzf** [spring-cloud/spring-cloud-netflix#3871]
version=1.3.1.RELEASE
groupId=org.springframework.cloud
artifactId=spring-cloud-starter-ribbon

com.netflix.ribbon#ribbon-loadbalancer;2.2.2

I think ZonePreferenceServerListFilter  is redundant and wrong 。When the zone is down , you should not select server from this zone ,but you do .

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
