### ISSUE TITLE
ServletTraceableRequest fails to create URI instance when query string contains special characters

### ISSUE THREAD

**Issue by Magnastraw** [spring-cloud/spring-cloud-netflix#3873]
Hello, I faced an issue when tried to forward request via zuul, which contains characters like {} or [] in query params

It can be easely reproduced with ribbon or simple routing filter and query parameter like 
`filter=[{"property":"name","operator":"like","value":"testName"}]`

Problem part: `spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/TraceProxyRequestHelper.java:157`
It can not instantiate URI if query is not encoded
I guess it's wrong behaviour, because zuul is proxy, and it should work with any kind of characters in queries

I found out that similar problem with implementation of TraceableRequest has been fixed here https://github.com/spring-projects/spring-boot/commit/60a4d67b138b73a1f442d1aa7dbd6f7302adf2c1# for actuator project
Can we make similar fix in spring zuul for ServletTraceableRequest? Can we backport it to 2.1/2.2 ?
I can create a PR for this problem

**Comment by spencergibb** [comment]
PRs welcome
