### ISSUE TITLE
Documentation: Update documentation for Getting started with Eureka

### ISSUE THREAD

**Issue by hangtwenty** [spring-cloud/spring-cloud-netflix#388]
I found I had to do the following undocumented steps to get started with Eureka, when following [this documentation](http://cloud.spring.io/spring-cloud-netflix/):

Add this import:
```
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
```

(Really, this "getting started" documentation should include all imports! Explicit is better than implicit, especially when you're a beginner!)

*And* use the  annotation, `@EnableDiscoveryClient` instead of `@EnableEurekaClient`. (Documentation refers to out of date name.)

SIDE NOTE ... Also no luck with the @EnableEurekaServer step... if that is going to be included, a complete example should be shown, instead of a quick sentence that doesn't demonstrate exactly how to do things.

Apologies if this is newb-ish, I am new to Java, Spring, _and_ Gradle!

**Comment by hangtwenty** [comment]
While we're at it... that note about the configuration that could be updated, to point to a non-local Eureka server, could perhaps be a little more specific too.

**Comment by spencergibb** [comment]
`@EnableEurekaClient` isn't out of date, it's just more _specific_.  Pull Requests are welcome.

**Comment by hangtwenty** [comment]
Ahh... This not an issue with Spring Cloud specifically. So, this is the first time I'm getting serious with Java, and definitely my first time with Spring. If there's any issue here, it's more of a UI issue. The improvement could make Spring more welcoming to  outsiders.

Opened this new ticket: https://github.com/spring-io/sagan/issues/568

Thanks :)
