### ISSUE TITLE
Custom reactive health indicator not being called in Eureka Client / Webflux app

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-cloud/spring-cloud-netflix#3888]
I was using Sidecar, but now am trying to move my micro-service to webflux.

Pom looks like:

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.3.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
			<version>2.2.5.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

```

I've tried ReactiveDiscoveryHealthIndicator, ReactiveHealthIndicator, ReactiveDiscoveryClientHealthIndicator. None seem to get used by Eureka.

If I go to http://myapp/actuator/health, ReactiveDiscoveryHealthIndicator::health() did get called, but Eureka doesn't seem to use that status.

json is showing:

```
{"status":"DOWN","components":{"discoveryComposite":{"description":"Remote status from Eureka server","status":"UP","components":{"eureka":{"description":"Remote status from Eureka server","status":"UP","details":{"applications":{"xxx-MYAPP":1}}}}},"diskSpace":{"status":"UP","details":{"total":1013309239296,"free":841340334080,"threshold":10485760,"exists":true}},"hystrix":{"status":"UP"},"ping":{"status":"UP"},"reactiveDiscoveryClients":{"status":"DOWN","components":{"xxx-MYAPP":{"status":"DOWN"}}},"refreshScope":{"status":"UP"}}}
```

Eureka UI is still showing the service as UP.

When I was using Sidecar in WebMvc, I was overriding LocalApplicationHealthIndicator.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaHealthCheckHandler.java does not support `ReactiveHealthIndicator` yet.

**Comment by joyita07** [comment]
Looking into this for GHC2020 OSD

**Comment by joyita07** [comment]
Created a PR for this: https://github.com/spring-cloud/spring-cloud-netflix/pull/3901

**Comment by OlgaMaciaszek** [comment]
Changes merged.
