### ISSUE TITLE
"Route specific" Hystrix config in Zuul Proxy?

### ISSUE THREAD

**Issue by abaculus** [spring-cloud/spring-cloud-netflix#389]
As I understand the Hystrix commands in Zuul Proxy are named:

`hystrix.HystrixCommand.RibbonCommand.<service-name>RibbonCommand`

This Hystrix config would apply to all requests to the specific service.

The issue is that in the same service we got several URLs in need of different Hystrix config (thread pool size, timeouts etc).

Is this possible to configure in Spring Cloud Netflix and if so how can I do it?

If not maybe one could accomplish this by prefixing <route-name> below with the <service-id> when creating the HystrixCommand?

Template config:

`zuul.routes.<route-name>.path=/my/url`
`zuul.routes.<route-name>.serviceId=<service-id>`

Example:

`zuul.routes.abrakadabra.path=/my/url`
`zuul.routes.abrakadabra.serviceId=MyService`

created the following command name:

`hystrix.HystrixCommand.RibbonCommand.abrakadabraMyServiceRibbonCommand` 

Maybe this relates somewhat to #250

**Comment by spencergibb** [comment]
Seems like a simple fix.  Maybe a configuration option like `zuul.prefixHystrixWithRoute` or something.

**Comment by abaculus** [comment]
Sounds nice! :+1:

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
