### ISSUE TITLE
Any plan to support Netflix Ribbon for Spring Cloud 2020

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-netflix#3896]
Hello Spring Cloud Team,

I just found Ribbon has been removed in 2020.M3, does it mean Ribbon would not be used as load balance component of Spring Cloud any more? We did lots of enhancements for Ribbon, so any solutions for us to use Ribbon in 2020 version? Can we exclude Spring Cloud LoadBalance and replace it with Ribbon? Thanks a lot

**Comment by spencergibb** [comment]
Almost 2 years ago we announced that certain spring cloud netflix modules works enter maintenance mode. https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now.

Ribbon itself has been in maintenance mode much longer than that.

Hoxton (where ribbon still has support) will be supported until at least mid 2021.

We've been working on bringing as many features as makes sense to Spring Cloud load balancer.

**Comment by spencergibb** [comment]
We announced we would be removing the modules December of last year. https://spring.io/blog/2019/12/23/spring-cloud-roadmap-and-hoxton-and-greenwich-maintenance-and-eol-announcements
