### ISSUE TITLE
Hytrix set timeout for specific endpoint of service with pattern

### ISSUE THREAD

**Issue by nguacon90** [spring-cloud/spring-cloud-netflix#3897]
In some cases, I want to configure timeout for specific of service with a pattern for example: /omc/order-report/export-excel. Because endpoint keep more times to processing and return file to client. Although, I should configure more timeout for endpoint not all service timeout. I can't find any way to configure it :).

So, I really want to a feature like this. Thanks.

**Comment by spencergibb** [comment]
See https://github.com/Netflix/Hystrix/wiki/Configuration

The `HystrixCommandKey` in that doc is the `service-id` configured for zuul

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
