### ISSUE TITLE
Eureka: HeartBeatEvent sent too early

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#391]
The `HeartBeatEvent` is sent every time a "SpringCloud commons" discovery client has refreshed its local cache - provided the used implementation supports such feature.

Netflix's Eureka `DiscoveryClient` doesn't have that feature natively. The current solution to detect/generate this event is to hook into the `Applications` class and see when its `version` attribute is modified. This is done by the `DataCenterAwareMarshallingStrategy` by means of its `SetVersionInterceptor`.

Unfortunately, Eureka hasn't yet finished its refresh when `applications.setVersion()` is invoked. So the heartbeat event is sent to early and information it carries does not yet reflect all the effects of the refresh.

The ideal solution is to have the Eureka client support this feature natively (see https://github.com/Netflix/eureka/issues/545). Possible options are:
- by sending an event on their `eventBus` for every refresh
- make some methods public or protected so we could sub-class and capture the event ourselves

Meanwhile, I looked for another solution that could do the job. The cache refresh is handled by the  `DiscoveryClient.fetch()` (private) method whose execution time is monitored by the `FETCH_REGISTRY_TIMER`. A possible approach is to hook into the used timer and generate the `HeartBeatEvent` every time the Timer records a new value.

This approach is an awful hack, and in that respect is not better than the current solution I agree. But it has the benefit of sending the event only when the refresh is actually completed.

@dsyer I noticed you are the author of the `DataCenterAwareMarshallingStrategy`. What is your opinion on this?

**Comment by dsyer** [comment]
"Anything that works" is my motto with Eureka. I also noticed that the heartbeat event is not always accurate (but always is eventually in my experience). Thanks again for the analysis.

**Comment by brenuart** [comment]
> "Anything that works" is my motto with Eureka. 
I understand... may be time for us to consider an alternative as well :-(

Anyway. What do you think should be done?
- Wait for Netflix to consider the feature request I posted on their side? But it may require some time, and will require to integrate their latest version... Which may not be easy as @spencergibb said (they moved to Jackson for marshalling)
- Or do you want me to send you a PR with our "Timer-based" approach?

**Comment by dsyer** [comment]
PR can't hurt. I don't think it's a bad idea to move hacks around as long as we don't break anything obvious.

**Comment by qiangdavidliu** [comment]
@brenuart a question on this topic and the spring cloud integration with Eureka. Eureka's registration path (of which heartbeat is a part) and read path (getting application data from the remote server) are relatively distinct usage. In fact you can configure the client to only do one or the other (though by default it does both).

Please correct me if I am wrong, but this issue mentions a heartBeatEvent (presumably related to heartbeats) and link it to reading data from the remote server, which are different things in the eureka architecture.

**Comment by brenuart** [comment]
In Eureka's world, the `Heartbeat` mechanism is part of the registration path: a client has to periodically send heart beats to the server to renew its lease before its expires. 

A Eureka client can also be configured to discover new instances: what you called the 'read path'. If so configured, the client periodically fetch registry information from the server and keep it in a local cache. This process is called "Cache Refresh".

Netflix's implementation of the Eureka client (`DiscoveryClient` class) doesn't provide a way to know when its local cache has been refreshed. This is valuable information for many other components like load balancers for instance (or SpringCloud ZUUL so it knows when to refresh its route table).

The SpringCloud integration managed to deduce that information by proxying some of Netflix's classes and intercept method calls (very fragile hack). When it appears that Eureka has refreshed its local cache, a `org.springframework.cloud.client.discovery.event.HeartbeatEvent` is sent (a SpringCloud event, not a Netflix/Eureka event).

As you see, names are confusing. Hence your question...

**Comment by brenuart** [comment]
@dsyer PR https://github.com/Netflix/eureka/pull/549 has been merged into Eureka code base.
Thanks to this PR, the Eureka DiscoveryClient now offers a clean way to get notified when it has refreshed its local cache. This can be done by means of their event bus, or by subclassing the DiscoveryClient (which is now a viable option since their DI-refactoring work).

I propose to wait until they release a new version including these changes - provided SpringCloud-Netflix can be upgraded to that new version. What do you think?

**Comment by dsyer** [comment]
That sounds good, assuming it's not a 2.x change (it's still 1.x the DI change, right)?

**Comment by brenuart** [comment]
Yes, all is in 1.x

**Comment by brenuart** [comment]
This issue should be fixed thanks to work @spencergibb is doing in PR https://github.com/spring-cloud/spring-cloud-netflix/pull/398

**Comment by brenuart** [comment]
Issue can be closed - see previous comment.
