### ISSUE TITLE
Error in EurekaInstance*Event.equals()

### ISSUE THREAD

**Issue by wcnnkh** [spring-cloud/spring-cloud-netflix#3918]
查看源码时发现在master分支上org/springframework/cloud/netflix/eureka/server/event/EurekaInstanceCanceledEvent.java、EurekaInstanceRegisteredEvent.java中equals存在无效的代码，如：replication == replication

**Comment by spencergibb** [comment]
From google translate

> When looking at the source code, it was found that there is invalid code in equals in org/springframework/cloud/netflix/eureka/server/event/EurekaInstanceCanceledEvent.java and EurekaInstanceRegisteredEvent.java on the master branch, such as: replication == replication
