### ISSUE TITLE
Add ability to configure URL decoding for ZuulHandlerMapping

### ISSUE THREAD

**Issue by bhattankit** [spring-cloud/spring-cloud-netflix#3922]
**Is your feature request related to a problem? Please describe.**
The feature request is related to an existing problem where ZuulHandlerMapping does not have a way to configure to disable the automatic URL decoding that currently happens in UrlPathHelper. ZuulHandlerMapping extends from AbstractHandlerMapping which allows the capability to override this behavior but ZuulHandlerMapping doesn't provide a way to do it. There is a zuul.decodeUrl property that we use today during routing and can be leveraged here.

The current default decoding causes an issue with URLs that have an encoded / (%2F) in the Path.

**Describe the solution you'd like**
Use the zuul.decodeUrl property (or a new one) in the ZuulHandlerMapping and then update the UrlPathHelper via AbstractHandlerMapping.setUrlDecode() based on this property.

**Describe alternatives you've considered**
An alternative could be override the ZuulHandlerMapping by each user for spring-cloud-netflix-zuul but the ZuulHandlerMapping doesn't have a Conditional on it. We can add that as an option as well.

**Additional context**

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

**Comment by bhattankit** [comment]
@spencergibb -- Will you be okay if I submitted a PR for this ?

**Comment by spencergibb** [comment]
Of course. As I already said:

>  we will also consider and review small pull requests from the community.

**Comment by bhattankit** [comment]
Sound good. Thank you @spencergibb. I will look to submit a PR.
