### ISSUE TITLE
Eureka: propagate HeartbeatEvent to child contexts

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#393]
The `EurekaClientAutoConfiguration` contains a mechanism to propagate `HeartbeatEvent` sent by the discovery client from the context its defined, to child contexts created for Ribbon clients (for instance).

Since events thrown by child contexts are propagated to their parent, a new `ParentHeartbeatEvent` is created instead and published into the child context (to avoid infinite loops).

This mechanism can later be used in child contexts to trigger the update of server list or load balancers.

However, when the new child context is created, a first check is made to see if its parent's ID is `bootstrap`. Why is it so? In my case, the parent ID appears to be composed of `<active profiles>:<instance id>` - so the check always fails and heartbeat events are never propagated to child contexts.

Is it on purpose?
Should I configure my application differently?

**Comment by brenuart** [comment]
I'm just wondering was just in case the `DiscoveryClient` got initialised during the bootstrap phase: when a configuration server is discovered through Eureka for instance...

If so, the same functionality might be very useful for child contexts created for the Ribbon clients.
Why not simply forward the event to "any" child context (with a decent protection against the infinite loop of course) ?

**Comment by spencergibb** [comment]
Yes, the case for `DiscoveryClient` getting initialized during bootstrap is to find config server via eureka.  Are you seeing problems?

**Comment by brenuart** [comment]
Consequences are that the type of event I should listen to depends on whether the discovery client was initialised during the bootstrap phase or not. Since this depends on the configuration of the application, my components have to listen for both, just in case...

If my components are declared in another child context (level 3: bootstrap - main app context - child context), then this pattern would require to define a `ParentParentHeartbeatEvent` that would be forwarded to the child context.

Here is a usage scenario: I'd like my Ribbon load balancer to listen for `HeartbeatEvent` and update its status accordingly. As you know, ribbon clients are created in child contexts - so possibly 1 or 2 levels below the context when the discovery client lives.

My feeling is a Spring `ApplicationEvent` shouldn't be used in this case. I'm wondering the "Observer" pattern wouldn't be better. I could register a listener with the `DiscoveryClient` (or a delegate of some sort) from whatever application context I live in - provided the DiscoveryClient is in one of the ancestors. 

Do see my point? What do you think?

**Comment by spencergibb** [comment]
@brenuart I'm not sure we want to support this type of pattern. Why do you need your ribbon loadbalancer to listen for `HeartbeatEvent`? What is your use case? Sorry for the delay in responding.

**Comment by brenuart** [comment]
We capture `HeartbeatEvent` to force an immediate refresh of the `DynamicServerListLoadBalancer` used by Ribbon. 

As you know, this load balancer normally refreshes its list of available server every 30s on a separate thread (push vs. pull). This introduces an extra delay in propagation of Eureka registration changes. Instead of waiting for the next refresh, we force it when Eureka tells us it got new data.

This makes also things easier to troubleshoot in production as we know the loadbalancer has the same data as what the eureka client says.

**Comment by spencergibb** [comment]
There is a setting to change the 30 seconds for ribbon refresh. Netflix designed ribbon and eureka NOT to be instant updatable to allow for network hiccups etc... Closing as won't fix.
