### ISSUE TITLE
Question with netflix 1.4.0, FeignClient created multiple BeanFactory and ApplicationContext

### ISSUE THREAD

**Issue by wenmingwei** [spring-cloud/spring-cloud-netflix#3931]
* version: 1.4.0.RELEASE, very old version
* Question:
> We are facing a performance issue during startup, after tracing, we found that
> * netflix feign created ApplicationContext and BeanFactory for each FeignClient with different name.
> * As we have more than 6000 beans in our service, multiple bean factory will trigger BeanFactoryUtils.beanNamesForTypeIncludingAncestors while resoling dependencies.
> * BeanFactoryUtils.beanNamesForTypeIncludingAncestors will scan every bean in our service.
> The result is, 6000 * 6000 / 2 times for bean type predication.

Any suggestion for the performance issue we are facing, Thank you.

**Comment by spencergibb** [comment]
That version is no longer supported. If you still have problems after you upgrade, let us know.
