### ISSUE TITLE
zuul feign hystrix ribbon take a long time when first time request

### ISSUE THREAD

**Issue by ffyyhh995511** [spring-cloud/spring-cloud-netflix#3932]
springboot version is 2.1.12.RELEASE.
spring-cloud version is Greenwich.SR5.
use eureka、zuul、feign、hystrix、ribbon、
i start one service to request another service, first time would take a long time, second time request is normal.
if online service has concurrent request. when update the service and restart. in this moment, will cause request time out. even if config read-time-out、 content-time-out more longer.
so  how to resolve this situation

the attach can reproduces the problem by send http://127.0.0.1:8769/api-two/order/listUserByOrder twice

[enterprise-cloud.zip](https://github.com/spring-cloud/spring-cloud-openfeign/files/5622611/enterprise-cloud.zip)

**Comment by OlgaMaciaszek** [comment]
Hi, @ffyyhh995511, `Greenwich` release train is no longer supported. Please try against `Hoxton.SR9` or `2020.0.0.M5`.

**Comment by ffyyhh995511** [comment]
does it cause by version? i think that something like configuration can resolve

**Comment by ffyyhh995511** [comment]
hi @OlgaMaciaszek , what should i do can fix this problem

**Comment by OlgaMaciaszek** [comment]
Please try against `Hoxton.SR9` or `2020.0.0.M5` and provide a sample with any of these release trains if it's still an issue.

**Comment by ffyyhh995511** [comment]
ok, let me try

**Comment by ffyyhh995511** [comment]
it does not work, i update to Hoxton.SR9 and springboot 2.3.5.RELEASE.
it took about 1 second that i send http://127.0.0.1:8769/api-two/order/listUserByOrder first time. but it took only 34 ms second time

you can reproduces the problem by clone https://github.com/ffyyhh995511/enterprise-cloud.git
you should start euraka 、service-one 、service-tow、 zuul in turn and send http://127.0.0.1:8769/api-two/order/listUserByOrder

**Comment by ffyyhh995511** [comment]
hi @OlgaMaciaszek
it does not work, i update to Hoxton.SR9 and springboot 2.3.5.RELEASE.
it took about 1 second that i send http://127.0.0.1:8769/api-two/order/listUserByOrder first time. but it took only 34 ms second time

you can reproduces the problem by clone https://github.com/ffyyhh995511/enterprise-cloud.git
you should start euraka 、service-one 、service-tow、 zuul in turn and send http://127.0.0.1:8769/api-two/order/listUserByOrder

**Comment by vinayak12** [comment]
I am facing same issue

**Comment by holy12345** [comment]
HI @ffyyhh995511 @vinayak12 
Do you see this param > `ribbon.eager-load.enabled` . I guess when you first time request coming then spring will load some bean and will cost some time , when second time request coming its will not happen.
pls try it.

@OlgaMaciaszek  any thoughts?

thanks

**Comment by ffyyhh995511** [comment]
@holy12345 yes. i config this param > ribbon.eager-load.enabled. but in concurrent request situation that will cause many requests be slow

**Comment by OlgaMaciaszek** [comment]
Will be closing this issue since Hystrix and Ribbon are no longer supported by Spring Cloud.
