### ISSUE TITLE
Self preservation method on eureka console

### ISSUE THREAD

**Issue by juferdinand** [spring-cloud/spring-cloud-netflix#3934]
**Describe the bug**
```
EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
```
Hello I get anytime this Message, also if my Service are alltime online and I don't know why it does not reset. After an Restart it's normal and I have this Message not anymore, but I wanna not anytime to restart after an update by my Applications, so give it an Feature which make this Fail away?

I tried everything, if more Informations needed like pom or something else tells me

Thanks & Greetings

Justin

**Comment by spencergibb** [comment]
See https://github.com/Netflix/eureka/wiki/Server-Self-Preservation-Mode

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by juferdinand** [comment]
It works for me thanks alot
