### ISSUE TITLE
Client side TLS does not work with eureka client and rest template

### ISSUE THREAD

**Issue by zmssp** [spring-cloud/spring-cloud-netflix#3935]
**Describe the bug**

In spring-cloud **SR8**, we can enable [**client side tls**](https://github.com/spring-cloud/spring-cloud-netflix/pull/3865/files?file-filters%5B%5D=.java) by setting eureka.client.tls.keystoretype, eureka.client.tls.keystore, eureka.client.tls.enabled. But it cannot work in **2020.0.0-m5**. 

After some investigation I found Spring cloud **2020.0.0-m5** **removes jersey client** with this [change](https://github.com/spring-cloud/spring-cloud-netflix/commit/14dbd35b5290328af87e94ab60af54ae59967c82). Then DiscoveryClient will use **RestTemplate**, while the [RestTemplateTransportClientFactories](https://github.com/spring-cloud/spring-cloud-netflix/blob/v3.0.0-M5/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/http/RestTemplateTransportClientFactories.java) does not accept sslContext.  And in SR8, DiscoveryClient will use JerseyClient, JersyClient can work with client tls perfectly.

I know I can mitigate this issue by adding jersey dependency in my project, but I am still wonder if it is a bug in RestTemplate

**Comment by spencergibb** [comment]
If you include the Jersey client dependencies it will work again

**Comment by zmssp** [comment]
Yes, I know, I can mitigate it by add Jersy client. I still wonder is it a bug in RestTemplate?  
To us, we wish our customer can use [Azure Spring Cloud](https://azure.microsoft.com/en-us/services/spring-cloud/) without code any change. 
So we do have a plan to support client tls in RestTemplate?
