### ISSUE TITLE
Eureka-Server and Microservice on Same External Tomcat web server

### ISSUE THREAD

**Issue by rajesh-giriyappa** [spring-cloud/spring-cloud-netflix#3942]
HI ,
Im trying to deploy Eureka-Server and Microservice into the single tomcat External web server.

When i try to deploy in order Eureka-Server than Microservice on the Tomcat there is no issue. Both are deployed successfully.

When I try to deploy Microservice first the Microservice Hangs on particular endpoint highlighted below

2020-12-18 16:29:36.955  INFO 12036 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2020-12-18 16:29:37.030 DEBUG 12036 --- [           main] o.s.web.client.RestTemplate              : HTTP **GET http://localhost:8080/service-registry-0.0.1-SNAPSHOT/eureka/apps/**
2020-12-18 16:29:37.206 DEBUG 12036 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]

This Endpoint trying to fetch the registry for all services registered (Unfortunately Eureka server is not up). As Tomcat Tries Application deployment in sequential Order.
Microservice is Deployed first and It is never intialized so its hung infinitely not allowing Eureka-Server App and other Apps to deploy.

How to Get over it ? Any Ideas and suggestions helpful..

**Comment by rajesh-giriyappa** [comment]
Both microservice , Eureka-server code is attached [https://github.com/rajesh-giriyappa/books/commit/48eec5e36e2081d755497fbf7c2d495df64f9835#diff-2d10ed796765f5726d3dafadb5a54584a25a960955d9369ce90f7dd0dca7dc61](url)

**Comment by rajesh-giriyappa** [comment]
Attaching the applications [https://github.com/rajesh-giriyappa/books/files/5715007/eureka-ms.zip](projects.zip) Used Tomcat 9 web server

**Comment by spencergibb** [comment]
We recommend running eureka server standalone

**Comment by rajesh-giriyappa** [comment]
HI Spencergibb,

Thanks for your reply.
Is it possible to add a circuit breaker to the Endpoint  http://localhost:8080/service-registry-0.0.1-SNAPSHOT/eureka/apps/

And when the Eureka Server comes up retry will eventually catch up with fetching Registry and Registering.

Its Just a thought 👍 

Regards,
Rajesh Giriyappa

**Comment by spencergibb** [comment]
No, those endpoints are from the upstream library that netflix maintains.

**Comment by rajesh-giriyappa** [comment]
Can we raise issue with netflix team?

**Comment by spencergibb** [comment]
You are welcome to
