### ISSUE TITLE
Eureka Instance Registration - management context path is missing in health check url

### ISSUE THREAD

**Issue by srempfer** [spring-cloud/spring-cloud-netflix#3947]
The EurekaInstanceConfigBean does not regard an explicit set management context path for the health check url.

`management.server.base-path=/abc`

Problem occurs in Spring Cloud 2020.0.0 / Spring Boot 2.4.1

For the now in  Spring Boot 2.4 deprecated property `management.server.servlet.context-path=/abc` it works.

Reason is that the old property is used to build the health check url.

https://github.com/spring-cloud/spring-cloud-netflix/blob/e181683a00549412f5e8f592a51d226f7a9fe91e/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L136

**Comment by FelipeAdorno** [comment]
@spencergibb Can I help with this? We need to maintain the compatibility with `management.server.servlet.context-path` right?

**Comment by spencergibb** [comment]
Sure, that would be welcome
