### ISSUE TITLE
the official website of spring cloud netflix

### ISSUE THREAD

**Issue by wenxueliu** [spring-cloud/spring-cloud-netflix#3950]
the github link of spring cloud netflix is located to cloud.spring.io/spring-cloud-netflix/, is it the spring cloud netflix offical?website?

**Comment by spencergibb** [comment]
Yes it is. Though many of the upstream projects are from https://github.com/Netflix

**Comment by wenxueliu** [comment]
I find cloud.spring.io/spring-cloud-netflix/ is linked to https://cloud.spring.io/spring-cloud-netflix/reference/html/,
It seems https://spring.io/projects/spring-cloud-netflix is more likely Spring Cloud Netflix official website. so which is official website?

besides, cloud.spring.io/spring-cloud-stream is linked to https://spring.io/projects/spring-cloud-stream,  there are different official website links for different spring cloud projects.

**Comment by spencergibb** [comment]
One is the documentation (cloud.spring.io or docs.spring.io), the other is a general project page (spring.io)
