### ISSUE TITLE
xxx.ribbon.listOfServers is ineffective in springcloud 2020.0.0

### ISSUE THREAD

**Issue by farsunset** [spring-cloud/spring-cloud-netflix#3963]
feign client xxx  config an hostname url. but is Ineffective in springcloud 2020.0.0
in Hoxiton is effective

at new version this config has changed?

**Comment by spencergibb** [comment]
I'm afraid this report is not very effective. Can you please add a descriptive title and provide more details?

**Comment by farsunset** [comment]
> I'm afraid this report is not very effective. Can you please add a descriptive title and provide more details?

if 

> I'm afraid this report is not very effective. Can you please add a descriptive title and provide more details?

sorry i forgot save title

**Comment by spencergibb** [comment]
Ribbon is no longer in 2020.0 https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

**Comment by farsunset** [comment]
> Ribbon is no longer in 2020.0 https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

Ok. What are the alternatives? how to assign url at application.yaml

**Comment by OlgaMaciaszek** [comment]
The alternative is Spring Cloud LoadBalancer. You can find thorough information on using it [in the docs](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#spring-cloud-loadbalancer).
