### ISSUE TITLE
If you start client with a port=0, it shows port 0 and doesnt show multiple instances

### ISSUE THREAD

**Issue by arikanorh** [spring-cloud/spring-cloud-netflix#3970]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

1. Set up  a eureka server
2. Set up a spring boot client 
3. Start client with port=0 
4. Open eureka UI 

It will show the port as 0 and if you spin  up miltiple services with port 0, eureka will only show 1

![image](https://user-images.githubusercontent.com/17791032/107879099-ed241e00-6ee7-11eb-9c46-100a7b4f3795.png)

**Comment by arikanorh** [comment]
I did some debugging and found the relevant registry code

![image](https://user-images.githubusercontent.com/17791032/107883962-36359b80-6f03-11eb-8e91-42bf44051d43.png)

The map that holds the key is using ```registrant.getId()``` which says the port is 0 but infact it is not as seen in the debugger port information

**Comment by spencergibb** [comment]
Duplicates #843
