### ISSUE TITLE
Incorrect jar for spring-cloud-starter-netflix-eureka-client:3.0.1 in maven repo

### ISSUE THREAD

**Issue by pstawinski** [spring-cloud/spring-cloud-netflix#3971]
**Describe the bug**

Jar available at https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-starter-netflix-eureka-client/3.0.1/jar is invalid: it contains no code, only `pom.xml` and `pom.properties` files. 

**Sample**
Download jar file from https://search.maven.org/artifact/org.springframework.cloud/spring-cloud-starter-netflix-eureka-client/3.0.1/jar and check the content.

**Comment by ryanjbaxter** [comment]
That is all the starter contains 
https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-starter-netflix-eureka-client

**Comment by pstawinski** [comment]
Thank you, you are right, it's all correct. I got confused... Sorry for taking your time.
