### ISSUE TITLE
Does the eureka client support registering the service's own state, such as the size of a business thread pool queue?

### ISSUE THREAD

**Issue by dbses** [spring-cloud/spring-cloud-netflix#3978]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OlgaMaciaszek** [comment]
You can check the information recorded for the instances in [this class](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java). You can add your own data to the service instance metadata.

**Comment by dbses** [comment]
> You can check the information recorded for the instances in [this class](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/InstanceInfo.java). You can add your own data to the service instance metadata.

But metadata is immutable. It can't see the real-time status of the service.
