### ISSUE TITLE
Add metrics for Euereka server events

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-netflix#3989]
Add metrics (Micrometer-based) listener for `EurekaInstanceRegisteredEvent`, `EurekaInstanceRenewedEvent`, `EurekaInstanceCanceledEvent`.
Part of Spring projects observability review.

**Comment by heowc** [comment]
hello. I recently did some related [PR](https://github.com/spring-cloud/spring-cloud-netflix/pull/4270).

Can I understand this issue as collecting the number of events over a certain period of time?

**Comment by OlgaMaciaszek** [comment]
Thanks, @heowc. I think your PR actually covers this issue. Closing with https://github.com/spring-cloud/spring-cloud-netflix/pull/4270.
