### ISSUE TITLE
migration from spring-cloud-netflix core to spring clound-netflix Zuul -- Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.XXXX.XXXXX.XXXXXX]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/cloud/commons/httpclient/HttpClientConfiguration.class] cannot be opened because it does not exist

### ISSUE THREAD

**Issue by HarshaVardhanAcharyAthaluri** [spring-cloud/spring-cloud-netflix#3991]
**Describe the bug**
to resolve security vulnerability migration from spring-cloud-netflix core to spring clound-netflix Zuul then i got error like  

Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.XXXX.XXXXX.XXXXXX]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/cloud/commons/httpclient/HttpClientConfiguration.class] cannot be opened because it does not exist
**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
