### ISSUE TITLE
Zuul  doesn't pass client certificate for 2 way ssl  backend calls

### ISSUE THREAD

**Issue by diygithubdiv** [spring-cloud/spring-cloud-netflix#3996]
We cant store keystore into java cacerts file. Instead we have separate keystore /truststore jks files using which we tried to create a ssl context and set it on http client bean for zuul application. It worked but gives performance issues - high response time in highly concurrent environment.  Any other alternative to tackle this ?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
