### ISSUE TITLE
Zuul proxy swallows exceptions

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#40]
As a client it's really hard to tell what went wrong if the proxy call fails (e.g. if the eureka registration just isn't there). You can tell from metrics/trace that something happened, but it would be nice for the consumer (e.g. browser to get some more immediate feedback). It might be sufficient just to mimic or re-use the Spring Boot default error page behaviour.

**Comment by rozhok** [comment]
Hey guys.
I have auth zuul filter. Auth logic is written inside filter. I want to break filter chain and return 403 response in case when auth failed. How to achieve this? If I threw exception in the filter, Zuul will swallow it and return 200 ok to client which is not good in my case.
