### ISSUE TITLE
zuul.servletPath=/  and zuul-health-check , can both be achieved?

### ISSUE THREAD

**Issue by PromiseChan** [spring-cloud/spring-cloud-netflix#4001]
Our calling chains:  Other App send post http request -> our zuul-gateway -> our microservice
Registry: Eureka
Spring-cloud: Dalston.SR5

zuul setting:
  zuul.servletPath=/
  eureka.instance.health-check-url = /health

When we process chinese garbled filename,  other apps do not want to change the  url. 
Updating the whole Spring-cloud  costs a lot.
Thus, we set zuul.servletPath=/ . However, the health-check-url in zuul  does not work. Is there any solution to both achieve these two settings?

Our temporary solution:
Modify the class FormHttpMessageConverter in Spring-MVC to encoding filename with utf-8

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
