### ISSUE TITLE
Feign/Ribbon does not respect the context

### ISSUE THREAD

**Issue by thekalinga** [spring-cloud/spring-cloud-netflix#401]
I have two different deployment models for our code using spring cloud (the current goal is to reduce maintenance costs).

1. Low footprint i.e deployment on a desktop grade machine. Single tomcat container seems to have better memory footprint than multiple embedded tomcats(one for each micro service)
2. Cloud version that would be utilize the real capability of full blown micro services world

In order to achieve (1), I am trying to deploy all microservices onto a single tomcat instance where the gateway would depend on the service that's deployed on the same instance, meaning the dependent service would be to non-root context.

The problem is that if the dependent service is deployed onto non-root context, feign/ribbon (not sure who) is not able to speak to the service.

The following example illustrates the problem

https://github.com/thekalinga/sample-cloud-app-no-discovery-war

If you access `http://localhost:81/greeting-default-context`, he is able to speak to the dependent service (which happens to be deployed to root `/` context on port `82`)

However if you try and access `http://localhost:81/greeting-non-default-context`, this tries to talk to another service that's deployed to a non-root context `/sample-service-non-default-context` on port `8080`, he is throwing 404.

**Comment by spencergibb** [comment]
So, ribbon and eureka have no concept of the http context, they know host:port.  My suggestion would be to set the `server.context-path` in the embedded tomcat mode so you __always__ access the app with context.  In your feign client you would do something like `@FeignClient("/mycontext/myapi")`.

**Comment by thekalinga** [comment]
Would you mind expanding on why the abstraction is `host:port` instead of lets say `baseUrl`, which seems to be cleaner abstraction at the same time nor make any assumption about where the app is deployed?

If its too much of change now, is it possible for me to set this relativeBaseUrl(/mycontext/myapi) in @FeignClient at startup instead of compiletime. I vaguely remember @dsyer skimming over similar topic (dynamic url mapping in spring boot for actuator/some other configurable urls from config)

**Comment by dsyer** [comment]
I think the Feign `RequestInterceptor` allow you to insert extra path elements in the URI. You can do that at runtime.

**Comment by thekalinga** [comment]
@spencergibb I'm able to use @RequestMapping at the remote stub(FeignClient) and apply the hack you mentioned. Thanks for that.

@dsyer Thanks I'll try that out

**Comment by silentFred** [comment]
It would be great if the cloud stack was context-aware. Running into so many issues with zuul, hystrix, eureka etc.

**Comment by ryanjbaxter** [comment]
@silentFred please open GitHub issues for the problems you are running into

**Comment by firefoxer1992** [comment]
I have different context-path in defferent environment.   
In dev environment,context-path is /dev ,and in test environment it's  /test.   
How could I use Feign to set different context-path as service customer?
The following code  is just Ok in dev environment，But in test environment it is error.
`@FeignClient(value="smkp/dev",fallback=InvoiceMsgHystrix.class)
public interface InvoiceMsgService {
	@RequestMapping(value = "/sentMsg", method = RequestMethod.POST)
	public JSONObject sentMsgToWeChat(JSONObject invoiceJson) ;
}`
How could I solve the problem?

**Comment by ryanjbaxter** [comment]
@firefoxer1992 please open a separate issue
