### ISSUE TITLE
SocketTimeout in zuul when use 2way TSL(mutual SSL)

### ISSUE THREAD

**Issue by dhirendrarawal** [spring-cloud/spring-cloud-netflix#4010]
**Describe the bug**
SocketTimeout in zuul after 10k request when use 2way TSL(mutual SSL)

I am connecting to Apigee virtual host from spring-boot application . For routing the request I am using zuul proxy in spring-boot application.

### Here is my route config
```
zuul.routes.test.path=/**
zuul.routes.test.url=https://abc.xyz.apigee.net.com
zuul.routes.test.sensitiveHeaders=
zuul.routes.test.strip-prefix=false

zuul.host.maxTotalConnections=200
zuul.host.maxPerRouteConnections=200
zuul.host.connect-timeout-millis=70000
zuul.host.socket-timeout-millis=70000
```
This Apigee virtual is backed by approx. 10 routers .

connection between Zuul proxy application and Apigee HTTPS and it is 2 waySSL or mutual SSL where Zuul application act as client and Apigee as server. To achieve 2way SSL I have override CloseableHttpClient .

While doing load test I have found SocketTimeout issue after sometime like 3 to 4 mins or number of transaction reach to around 10k.

```
com.netflix.zuul.exception.ZuulException: Forwarding error
        at org.springframework.cloud.netflix.zuul.filters.route.SimpleHostRoutingFilter.handleException(SimpleHostRoutingFilter.java:261)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to abc.xyz.apigee.net.com:443 [abc.xyz.apigee.net.com/xx.xxx.xxx.xx] failed: connect timed out
Caused by: java.net.SocketTimeoutException: connect timed out
```
If I disable client Auth(2waySSL) on Apigee then can't see this issue. Not sure what 2waySSL doing special here other then exchange of certs

**Comment by OlgaMaciaszek** [comment]
Closing as Zuul is no longer supported by Spring Cloud. We suggest switching to Spring Cloud Gateway instead.
