### ISSUE TITLE
About JSR303 transient dependency from spring cloud starter netflix eureka client

### ISSUE THREAD

**Issue by state303** [spring-cloud/spring-cloud-netflix#4013]
Hello and thank you all for the great project.

I came across to the question that why spring boot starter validation dependency is included in the client dependency.
I use it everyday and I have no problem with it being transient dependency.
However, sometimes it makes me confuse when it comes to dependency management per se..

I know that from 2.3.x, Spring Boot Starter Web removed the transient dependency for boot starter validation, but I am wondering if that would happen to cloud starter netflix eureka client as well.

I know this could be tedious at some degree, however, really wished to know, as I manage the projects, there are so many duplicated imports for the validation, like 6 out of 10. (And there seems to be no documentation of it, or maybe I missed it...?)

Waiting for the answer...

Kind regards,
Seunghyun Bosco Bae.

**Comment by OlgaMaciaszek** [comment]
Hi @state303 , this comes as a transitive dependency from SC LoadBalancer and SC Config Server. I don't believe we need it in SC LoadBalancer - have created [this issue](https://github.com/spring-cloud/spring-cloud-commons/issues/992). @spencergibb  could you verify when it comes to SC Config?

**Comment by spencergibb** [comment]
we use validation, without it, it would be a problem

**Comment by spring-cloud-issues** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
