### ISSUE TITLE
I am using encrypted Avro schema and deserialicing it while consuming , after Consuming the record from a topic i am sending it to a rest end point using FeignClient where i am getting this error .     

### ISSUE THREAD

**Issue by hubvarun** [spring-cloud/spring-cloud-netflix#4014]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hubvarun** [comment]
feign.codec.DecodeException: Type definition error: [simple type, class com.bottomline.fm.lts.model.financial.message.Institution]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.bottomline.fm.lts.model.financial.message.Institution` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information  at [Source: (PushbackInputStream); line: 21, column: 15] (through reference chain: com.bottomline.fm.lts.model.financial.message.base.FinancialMessageImpl["sender"])

**Comment by OlgaMaciaszek** [comment]
It seems you don't have appropriate constructors/ setters in your class for Jackson deserialisation. This is not a Spring Cloud issue at all.

**Comment by hubvarun** [comment]
> It seems you don't have appropriate constructors/ setters in your class for Jackson deserialisation. This is not a Spring Cloud issue at all.

Yes you are right. But the problem was I wasn't doing the Jackson deserialization. Which I refactored and it worked

**Comment by mohan-XD** [comment]
Hi @hubvarun,
I am facing a similar kind of issue, can you tell me how did you solve it?  

Error msg :
throws java.lang.Exception' threw exception; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Not an array: 

Caused by: org.apache.avro.AvroRuntimeException: Not an array:
