### ISSUE TITLE
Eureka: server ignores the "version" path param in REST requests

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#402]
As per Netflix's documentation (https://github.com/Netflix/eureka/wiki/Eureka-REST-operations), Eureka REST operations have the following form:

    /<context>/<version>/<REST operation>

For example:

    POST /eureka/v2/apps/appID
    DELETE /eureka/v2/apps/appID/instanceID
    ...

These examples will fail with SpringCloud's version of the Eureka server:  the _version_ path param CANNOT be specified. However, the following will work (same as above but without the _v2_ version):

    POST /eureka/apps/appID
    DELETE /eureka/apps/appID/instanceID
    ...

In fact, the server considers the first path element (i.e. _/eureka_) as the version argument when handling the request. Since "eureka" is not a valid/supported version (only _v1_ and _v2_ are supported currently), it defaults to version 2 and proceeds with the rest of the request.

REST handling is implemented via Jersey which is integrated via a servlet filter matching requests with pattern `/eureka/*`. When the request is handled over to Jersey, the `/eureka` prefix is not stripped and is therefore considered as the first path element by the Jersey resources. The Jersey resource corresponding to the above example is mapped as follows (see the `@Path` annotation):

    @Path("/{version}/apps")
    @Produces({"application/xml", "application/json"})
    public class ApplicationsResource {
        ...

This problem can be solved by integrating Jersey as a _servlet_ instead of a _servlet filter_.
However, this will force people to update their existing configuration to include the version in the server URL. Change from:

    (1) eureka.client.serviceUrl.defaultZone = http://myeurekaserver:8761/eureka/

to 

    (2) eureka.client.serviceUrl.defaultZone = http://myeurekaserver:8761/eureka/v2/

(Note: maybe we could add some transparent redirection from (1) to (2) in the eureka server if no version is specified)

At the end, the question is **whether or not SpringCloud's version of the Eureka server should expose the _version_ in the urls**. The client is v2-compatible and this is unlikely Netflix releases a version 3 on this code base (they are working on Eureka2 instead)...

What is your opinion?

**Comment by spencergibb** [comment]
That's a great question.

**Comment by brenuart** [comment]
So better to leave it asis and ignore the case?
It works after all...

**Comment by spencergibb** [comment]
Not sure, I'd like to hear @dsyer's opinion.  I was the one who put `/eureka` in the path.

**Comment by dsyer** [comment]
I suppose Eureka might eventually support requests from a v2 and a v3 client in the same service. The point is moot until it does, so I don't think I want to change the default now.

**Comment by brenuart** [comment]
Ok - maybe let me just put some comment describing the issue at the right place in the code to help if the problem appears. Ok?

**Comment by dsyer** [comment]
Sounds good

**Comment by lxiaodao** [comment]
@brenuart thanks, I also meet this problem.
