### ISSUE TITLE
No more EnableEurekaClient annotations?

### ISSUE THREAD

**Issue by mjs0514** [spring-cloud/spring-cloud-netflix#4022]
**Describe the bug**
spring-cloud-starter-netflix-eureka-client : 3.0.3.jar
<spring-cloud.version>2020.0.3</spring-cloud.version>

I know I need to annotate my SpringBootApplication with @EnableEurekaClient to make eureka client app.

However, even if this annotation is not attached, it is trying to register with the Eureka server just by including spring-cloud-starter-netflix-eureka-client in the dependency.

When you see the stack, EurekaAutoServiceRegistration automatically tries to register with the Eureka Server by SmartLifeCycle.

Is this the intended behavior? So what is the purpose of the EnableEurekaClient annotation?

Here I am sharing a [link](https://stackoverflow.com/questions/60349535/what-is-use-of-enableeurekaclient) with a question similar to mine.

please answer about my question.
thank you.

**Comment by OlgaMaciaszek** [comment]
Hello, @mjs0514. The `@EnableEurekaClient` annotation is not required anymore. Simply, adding `spring-cloud-starter-netflix-eureka-client` to dependencies will enable the client. If you want to disable it, the property value of `eureka.client.enabled` to `false`.
I have opened [an issue to update the doc](https://github.com/spring-cloud/spring-cloud-netflix/issues/4029)s and [an issue to remove it in the next major release](https://github.com/spring-cloud/spring-cloud-netflix/issues/4028).
