### ISSUE TITLE
MaxAutoRetries is not taking from the properties file

### ISSUE THREAD

**Issue by jeevanb214** [spring-cloud/spring-cloud-netflix#4042]
**Describe the bug**
Spring Boot version---2.3.0.RELEASE
Cloud Version -- Hoxton.SR4
java.version  --  8

--> I wantedly making my API to return 500 status code and making it retry by using the below properties, It is retrying but it retrying 12 times mostly.

**Sample**

properties:

service-name.ribbon.ConnectTimeout=90000
service-name.ribbon.ReadTimeout=140000
service-name.ribbon.MaxTotalHttpConnections: 1500
service-name.ribbon.MaxConnectionsPerHost: 500
service-name.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RetryRule
service-name.ribbon.MaxAutoRetriesNextServer=3
service-name.ribbon.ServerListRefreshInterval=2000
service-name.ribbon.OkToRetryOnAllOperations=true
service-name.ribbon.MaxAutoRetries=2
service-name.ribbon.retryableStatusCodes: 503, 408, 500
spring.cloud.loadbalancer.retry.enabled: true
zuul.retryable: true
zuul.routes.service-name.retryable: true

POM.xml

                <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>

Main Class

@EnableZuulProxy
@EnableEurekaClient
@SpringBootApplication
@EnableRetry
public class UProxyApplication {

	public static void main(String[] args) {
		SpringApplication.run(UProxyApplication.class, args);
	}

}

**Comment by OlgaMaciaszek** [comment]
Hello, @jeevanb214, Zuul is no longer supported. The `Hoxton` release train is also no longer supported. We recommend you switch to the `2020.x` release train (or wait for the GA release later this month to switch to the `2021.x` release train). And migrate from Zuul to Spring Cloud Gateway.
