### ISSUE TITLE
Benchmarking eureka service discovery performance

### ISSUE THREAD

**Issue by sahith** [spring-cloud/spring-cloud-netflix#4053]
Can someone point me to the documentation/blog where eureka performance is measured? In specific, I want to know the answer for the following questions

1. What is the response time from server when eureka client makes a read/write request?
2. How many service instances can be supported by Eureka?
3. How many concurrent requests can be supported from eureka client to server?
4. How much memory/CPU is consumed by Eureka host?
5. What are the network bandwidth constraints/limits of Eureka?

I believe above are the important questions to be answered and included in the documentation for comparing performance against other service discovery solutions out there.

**Comment by OlgaMaciaszek** [comment]
Hi @sahith since this question refers rather to the actual Eureka server and client implementations than the Spring Cloud integration for Eureka, it should probably be asked in [https://github.com/Netflix/eureka](https://github.com/Netflix/eureka).

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
