### ISSUE TITLE
Publish custom port to eureka service registry from eureka client

### ISSUE THREAD

**Issue by an0nh4x0r** [spring-cloud/spring-cloud-netflix#4056]
Eureka client by default publishes `${server.port}` to service registery i.e. eureka server. There needs to be a property where we can publish custom port to service registry 

There needs to be a property called `${eureka.instance.custom-port}` which can be used to set custom port which will then get published to the eureka server ... instead of `${server.port}`

In my organization , I've override a bean called [`eurekaInstanceConfigBean`](https://github.com/spring-cloud/spring-cloud-netflix/blob/main/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L125) basically at this line here [in class `EurekaClientAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-netflix/blob/main/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L133) I'm checking for custom port property and if it's present I'm using custom port instead of `${server.port}` and publishing that port instead. It works great for me

I would like to get this property support officially from the library

**Comment by an0nh4x0r** [comment]
My pull request got closed. :( 
non-secure-port does not work.

**Comment by OlgaMaciaszek** [comment]
Hello @an0nh4x0r, why do you need this functionality? Could you describe your use-case in more details?

**Comment by an0nh4x0r** [comment]
Hey @OlgaMaciaszek ... We have our own cloud in my company where we run custom built containers(not docker) ... We basically have two ports i.e. first inner port of which spring boot is running, second outer port through which traffic gets rerouted to this inner port in which spring boot app runs ... I have access to outer port number in container through enviornment variable ... I was looking for ways to publish this outer port to eureka service registery. In my company I see people who are using zookeeper as service registery have option to publish custom port to zookeeper ... I was looking to get same functionality natively from Eureka client.

**Comment by OlgaMaciaszek** [comment]
@an0nh4x0r thanks for the details. Will discuss it with the team and get back to you.

**Comment by OlgaMaciaszek** [comment]
@an0nh4x0r Actually, you should be able to set it using [these props](https://github.com/spring-cloud/spring-cloud-netflix/blob/e5ba2575e691498f564088a1ef13d11e71c9eded/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java#L72-L80). Let me know if this solves your issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
