### ISSUE TITLE
spring-cloud-starter-netflix-hystrix in spring cloud is abandoned？

### ISSUE THREAD

**Issue by lnsane** [spring-cloud/spring-cloud-netflix#4059]
i not found spring-cloud-starter-netflix-hystrix dependencies   in spring-cloud-netflix-dependencies  version is 3.1.0

why ?

**Comment by anbusampath** [comment]
> i not found spring-cloud-starter-netflix-hystrix dependencies in spring-cloud-netflix-dependencies version is 3.1.0
> 
> why ?

https://spring.io/blog/2018/12/12/spring-cloud-greenwich-rc1-available-now#spring-cloud-netflix-projects-entering-maintenance-mode
