### ISSUE TITLE
Zuul swallows 503 exceptions from upstream microservices

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-netflix#406]
Hey,

When an upstream microservice responds with let's say a 503 because of a throttling, Zuul's ribbonCommand will retry 1 more time. If that retry fails as well, the ribbonCommand fails, tries to find the fallback, and responds with a Forwarding error (500).

Because we'd like to tell the client whether it's a timeout or throttling or another issue, it would be useful to propagate the error through the gateway to the client, preferably as a nested cause of the Forwarding error.

What do you think about this?

**Comment by spencergibb** [comment]
I think that could be useful.

**Comment by rozhok** [comment]
btw, https://jmnarloch.wordpress.com/2015/09/16/spring-cloud-zuul-error-handling/

**Comment by spencergibb** [comment]
SO discussion http://stackoverflow.com/questions/35294218/zuul-ribbon-exception-always-returns-500-response/35301837#35301837

**Comment by spencergibb** [comment]
So `RestClient` specifically treats a 503 differently.

**Comment by rozhok** [comment]
@spencergibb so now zuul will forward 4xx errors properly? Cool, thanks.

**Comment by spencergibb** [comment]
@rozhok I'm unable to reproduce that. Any help there would be appreciated (sample project would be good).
