### ISSUE TITLE
method ReactiveHystrixCircuitBreaker.createCommand throw a runtime Exception: java.lang.NoClassDefFoundError: rx/RxReactiveStreams

### ISSUE THREAD

**Issue by feiquan666** [spring-cloud/spring-cloud-netflix#4063]
SpringCloud Version is ： Hoxton.SR12
SpringBoot Version is：2.3.12.RELEASE

My Gateway Moudle dependencies is:

<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

rx.RxReactiveStreams not found at runtime

![image](https://user-images.githubusercontent.com/42441073/150301622-bb623d9b-d812-43fb-8ef6-9e3ae6bba3a3.png)

I noticed version is 1.3.8 for rxjava，it has not definition class  #rx.RxReactiveStreams

**Comment by feiquan666** [comment]
The project address is:  [MyMicroservice](https://github.com/feiquan666/MyMicroservice)

you can clone it and start it。

try url：http://localhost:5002/api/test/web/hello/3  
headers :  
{
"Req-Sign": "check sign"
}

**Comment by OlgaMaciaszek** [comment]
Hello @feiquan666, the `Hoxton` release train is no longer supported. Please upgrade to `2021.x`. If the problem persists, please open a GH issue in the [Spring Cloud CircuitBreaker](https://github.com/spring-cloud/spring-cloud-circuitbreaker) repo.
