### ISSUE TITLE
Service discovery for RSocket

### ISSUE THREAD

**Issue by hsonawane** [spring-cloud/spring-cloud-netflix#4067]
Is it possible to use [spring-cloud-netflix] as service discovery for RSocket services? If not what are possible options.

**Comment by OlgaMaciaszek** [comment]
Hello @hsonawane, Spring Cloud Netflix provides support for Netflix/Eureka, which is an HTTP tool. You can use [RSocket Broker](https://github.com/rsocket-broker/rsocket-broker) and [RSocket Broker Client](https://github.com/rsocket-broker/rsocket-broker-client) for RSocket service discovery and routing. You can use [RSocket Broker Http Bridge](https://github.com/rsocket-broker/rsocket-broker-http-bridge) to route between HTTP and RSocket services.
