### ISSUE TITLE
Zuul - SimpleHostRoutingFilter forwards inbound request paths as unescaped

### ISSUE THREAD

**Issue by brandon-atkinson** [spring-cloud/spring-cloud-netflix#407]
This issue exhibits itself much like #347, but the fix in bd5d00c addressed it only in RibbonRoutingFilter. 

Example of issue:
inbound request path: /thirst%20mutilator
outbound request path: /thirst mutilator

The cause is similar, the routing filter will use the "requestURI" that the PreDecoratingFilter (or really any other filter) puts into the RequestContext. PreDecoratingFilter happens to put an unescaped path into requestURI.

This problem really exists because the PreDecoratingFilter unescapes the uri before putting it into the context. Is having an unescaped path in context.requestURI a requirement? 

I have forked locally to fix this in the SimpleHostRoutingFilter, definitely wouldn't mind submitting a PR.

**Comment by brandon-atkinson** [comment]
The reason this was not caught is that there was a single unit test which only ran requests through the ribbon path.

**Comment by dsyer** [comment]
PR more than welcome thanks.
