### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [spring-cloud/spring-cloud-netflix#4088]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `spring-cloud-netflix-eureka-client\pom.xml`, `org.springframework.boot:spring-boot-starter-security` scope should be `compile`  instead of `test`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by OlgaMaciaszek** [comment]
Not sure why it would be in compile. We do use the configuration and deps brought about by this starter in our tests.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
