### ISSUE TITLE
spring-cloud-netflix-eureka-server-3.1.2 frontend's navbar display wrong.

### ISSUE THREAD

**Issue by zhanming** [spring-cloud/spring-cloud-netflix#4091]
**Describe the bug**
artifact and version: spring-cloud-netflix-eureka-server-3.1.2

Since use webjars npm version and update jquery and bootstrap's version, there is something wrong with the front page's navbar.

1. In wro.xml, jquery path is not right.  
2. And because of update bootstrap's version to 5.1, some navbar's css class is not exists.

**Simple**

Just setup a basic eureka server, and take a look at http://localhost:8761 , and focus on navbar.

**Comment by ViliusS** [comment]
Should be fixed by https://github.com/spring-cloud/spring-cloud-netflix/pull/4096

**Comment by OlgaMaciaszek** [comment]
Fixed with the linked PR.
