### ISSUE TITLE
Unable to register Eureka client on SSL enabled Eureka server running on OpenShift Pod

### ISSUE THREAD

**Issue by ashuit87** [spring-cloud/spring-cloud-netflix#4106]
I have deployed my eureka server on openshift which has generated the ssl enabled(HTTPS) route, I am able to get the Eureka server page with that route but when I am trying to register my eureka client with the https eureka server serviceUrl(route) I am getting certificate error, Is there any way to customize the Eureka client to override the eureka client to call the custom RestTemplate class to bypass SSL or any other way to get it registered.

error: INFO 1 --- [main] c.n.d.s.t.d.RedirectingEurekaHttpClient : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='https://myserviceurl'}, exception=I/O error on GET request for "https://myserviceurl/": Certificate for doesn't match any of the subject alternative names: [myserviceurl]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for doesn't match any of the subject alternative names: [myserviceurlt] stacktrace=org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://myserviceurl": Certificate for doesn't match any of the subject alternative names: [myserviceurl]; nested exception is javax.net.ssl.SSLPeerUnverifiedException: Certificate for doesn't match any of the subject alternative names: [myserviceurl] at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) at org.springframework.cloud.netflix.eureka.http.RestTemplateEurekaHttpClient.getApplicationsInternal(RestTemplateEurekaHttpClient.java:145)

**Comment by ashuit87** [comment]
https://stackoverflow.com/questions/72948758/unable-to-register-eureka-client-on-ssl-enabled-eureka-server-on-openshift

**Comment by OlgaMaciaszek** [comment]
I'm not sure about your use case - I'd assume you either don't want to use certificates, so you disable SSL or you want to use them, in which case you enable SSL and need to have valid certificates on both sides. Please provide more information about your usecase.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
