### ISSUE TITLE
Document mixed eureka/non-eureka ribbon usage

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#411]

**Comment by ktong** [comment]
Any updates for this? I have a case need use both but cannot find how to config.

**Comment by C-Otto** [comment]
I'd also like this to be implemented.

When using Ribbon to provide a `RestTemplate` bean, all hosts are resolved using Eureka (if configured accordingly). This also means that requests to `https://api.somewhere.com` are handled in a way that Eureka is used to provide instances of `api.somewhere.com`, although this URL is absolute and not registered in Eureka.

It would be great to have Ribbon/Eureka fallback to standard `RestTemplate` functionality (DNS) for such URLs, either automatically or using some per-call/per-host configuration.

**Comment by OlgaMaciaszek** [comment]
Ribbon has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
