### ISSUE TITLE
Missing HTTP PATCH request method in Zuul RibbonRoutingFilter

### ISSUE THREAD

**Issue by sebastian-sch** [spring-cloud/spring-cloud-netflix#412]
Do you see any possibility that the ```RibbonRoutingFilter``` will support HTTP PATCH. 

The problem is, that the enum ```Verb``` from ```com.netflix.client.http.HttpRequest``` don't support HTTP PATCH. 

If it is not possible, perhaps it should be documented, which HTTP Verbs Ribbon & Zuul supports.

This issues is related to #307.

**Comment by zampettim** [comment]
This is going to be a problem for me as well, since I'm using Spring Data REST, and use of the PATCH method is the documented way to update resources without having to supply a fully populated object.

**Comment by hrandika** [comment]
This is coursing trouble to me too when one service want to update something in other service. Any way around this ?

**Comment by schoberwirt** [comment]
We use ApacheHTTP as the client for ribbon. 
Dependencies need to be pushed.
 <dependency>
      <groupId>com.netflix.feign</groupId>
      <artifactId>feign-httpclient</artifactId>
      <version>8.3.0</version>
    </dependency>

now you should be able to do sthg like.
Don't use okhttp if you also want to use newrelic. No introspection there.

 @Bean
 public Client feignRibbonClient() {
        return RibbonClient.builder().delegate(new ApacheHttpClient()).lbClientFactory(cachingLBClientFactory()).build();
 }

**Comment by zampettim** [comment]
@schoberwirt Where is the ```cachingLBClientFactory()``` coming from?

**Comment by zampettim** [comment]
Ok, here is what I had to do to get a FeignClient implemenation to work. I haven't tested in a Zuul case yet, but it should be similar. And that is next on my plate.

I had to up-rev the following dependencies.
Updated com.netflix.feign.{feign-core,feign-ribbon,feign-slf4j,feign-httpclient} to 8.5.0
I also had to add feign-httpclient to the dependencies.
That then forced the need to update org.apache.httpcomponents to account for missing methods.
So updated org.apache.httpcomponents.httpclient to 4.5 and updated apache.httpcomponents.httpcore to 4.4.1 (under the assumption that httpclient will work best with the latest httpcore.

Then I had to add the following to my Spring Application classes

    @Bean
    public Client feignRibbonClient() {
        return RibbonClient.builder().delegate(new ApacheHttpClient()).build();
    }

I let the RibbonClient use the default lbClientFactory instead of injecting my own. That allowed me to configure Feign to use Apache HTTP Client as the implementation, and thus get PATCH support.

**Comment by spencergibb** [comment]
Feign has been updated to 8.6.0, see #436

**Comment by spencergibb** [comment]
how would you all feel if `com.netflix.feign:feign-httpclient` was on the classpath to auto-configure its use, similar to how @zampettim has shown?

**Comment by hrandika** [comment]
@spencergibb that would be awesome. +1.

**Comment by spencergibb** [comment]
See #442

**Comment by spencergibb** [comment]
#443 is the beginning of allowing http client in zuul

**Comment by zampettim** [comment]
This all sounds great to me.

**Comment by hrandika** [comment]
@zampettim I have tried with Zuul still the patch method does not work.

**Comment by spencergibb** [comment]
@hrandika those things that @zampettim was showing relate only to feign, not to zuul.  I'm in the middle of working on it in #443.

**Comment by spencergibb** [comment]
inadvertently closed

**Comment by spencergibb** [comment]
The groundwork has been laid in b494e1d.

**Comment by ChristianLohmann** [comment]
Is there any progress in implementing  a concrete RibbonCommand/Factory which can finally handle PATCH requests? The lack of this blocks our project which heavily depends on spring cloud concepts with zuul enabled frontends and spring-data-rest enabled resource services. 
Otherwise i would implement it on my own but it is a bit difficult for me to understand what really happens there. 
There is a ```RibbonLoadbalancer``` in ```org.springframework.cloud.netflix.feign.ribbon``` which seems to be useful as client for the ```RibbonCommand```. But unfortunately it has package visible implementations of ```RibbonRequest``` and ```RibbonResponse``` as it was meant to be used only by Feign i doubt.
Should i create a new ```AbstractLoadBalancerAwareClient```?

**Comment by spencergibb** [comment]
There has been no progress.

**Comment by dinkarthakur** [comment]
Is there any progress on this issue. what is a way around for this problem?

**Comment by jordanjennings** [comment]
@dinkarthakur The change is available in Brixton M4 or snapshot, and you enable it by adding the following to a `@Configuration` class:

    @Bean
    public RibbonCommandFactory ribbonCommandFactory(SpringClientFactory clientFactory) {
        return new HttpClientRibbonCommandFactory(clientFactory);
    }

**Comment by dinkarthakur** [comment]
Still not able to make PATCH request

**Comment by jordanjennings** [comment]
@dinkarthakur It's working here with Brixton.SNAPSHOT and `@EnableZuulProxy`. Here's my complete class:

@SpringBootApplication
@EnableZuulProxy
public class ApiGatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(ApiGatewayApplication.class, args);
    }
    
    @Bean
    public RibbonCommandFactory ribbonCommandFactory(SpringClientFactory clientFactory) {
        return new HttpClientRibbonCommandFactory(clientFactory);
    }
}

I have Eureka running separately, and an application using Spring Data REST hooked in and PATCH method works as expected when routed via the api gateway.

Doing a bit of github stalking I see you have a sample repo with an edge server, adding the bean as shown above to this class should do it:

https://github.com/dinkarthakur/code-repo/blob/master/Infrastucture/Edge-Server/src/main/java/com/wiziq/infrastucture/edgeserver/EdgeServerApplication.java

**Comment by dinkarthakur** [comment]
Hi @jordanjennings  thanks for you solution. But it still not working i guess i'm doing something wrong . 
I added the Code you provided in the Zuul. but still when i hit the patch command im getting error
```
{
  "timestamp": 1454054236077,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "com.netflix.zuul.exception.ZuulException",
  "message": "Forwarding error"
}
```
also there is a query i want to make a patch request form one microservice to another using feign client. I tried to to that without any success but if i change PATCH to PUT same code works. Can you help me put regarding this PATCH issue

**Comment by digitaljoel** [comment]
While adding the RibbonCommandFactory Bean does allow for PATCH requests to go through as PATCH, my timeout configuration seems to be getting ignored.

**Comment by spencergibb** [comment]
The ribbon timeout settings would no longer apply, since it is no longer using the ribbon http client. @digitaljoel if you think there is some other bug, please open a new issue.

**Comment by digitaljoel** [comment]
Thanks for the quick reply @spencergibb sorry to zombie this thread.  Is there any documentation to be found regarding configuring timeout for the HttpClientRibbonCommand?

**Comment by spencergibb** [comment]
It's not documented ATM, https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RibbonLoadBalancingHttpClient.java

**Comment by digitaljoel** [comment]
Thanks. I will let this issue die again.

**Comment by bloodstars** [comment]
i use SimpleHostRoutingFilter instead, but the discovery work you need to do yourself
