### ISSUE TITLE
Add additional spring configuration metadata for predefined metadata-map keys

### ISSUE THREAD

**Issue by jizhuozhi** [spring-cloud/spring-cloud-netflix#4125]
**Is your feature request related to a problem? Please describe.**
When I'm configuring an instance, I need to know which keys in the metadata map are predefined and what they mean.
The predefined keys just like `weight`, `zone` and so on.
<img width="936" alt="Interactive actions" src="https://user-images.githubusercontent.com/31175030/194192148-1fb0479c-999d-4948-920b-cf451b1393b1.png">

**Describe the solution you'd like**
Add a code snippet in the `additional-spring-configuration-metadata.json` likes this in the Eureka
```json
{
    "properties": [
        ...
        {
             "defaultValue": "1",
             "name": "eureka.instance.metadata-map.weight",
             "description": "The weight of service instance for weighted load balancing.",
             "type": "java.lang.String",
             "sourceType": "org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean"
        }
    ]
}
```

**Describe alternatives you've considered**
Interactive actions allow me to better understand what I am doing and how to do. And configuration metadata can have type hinting, although this has no effect at runtime, it reduces the chance of us making configuration errors

**Comment by jizhuozhi** [comment]
Hello, @OlgaMaciaszek , PLAT. 
I think it is useful to given a list and type hinting for predefined metadata keys. There is no runtime cost, although the type of values are always `String`, but the IDE will known they are `Integer` or `Boolean` and so on.

**Comment by OlgaMaciaszek** [comment]
Thanks, @jizhuozhi. Will take a look this week.

**Comment by OlgaMaciaszek** [comment]
@jizhuozhi I agree that it could be helpful fine, however, that's not definitely a team priority at this point. Let me know if you would be interested in contributing it?

**Comment by jizhuozhi** [comment]
> @jizhuozhi I agree that it could be helpful fine, however, that's not definitely a team priority at this point. Let me know if you would be interested in contributing it?

Hello, @OlgaMaciaszek . I'm interested in it and  I'll be contributing it in the next few weeks :)
