### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hc/client5/http/classic/HttpClient

### ISSUE THREAD

**Issue by bsmahi** [spring-cloud/spring-cloud-netflix#4128]
Created a sample project using 
1. Spring Boot Version 3.0.0-SNAPSHOT,
2. Java Version 17
3. Spring Cloud Version as 2022.0.0-M5
4. Added the below repo id as well
```xml
<repository>
       <id>netflix-candidates</id>
       <name>Netflix Candidates</name>
       <url>https://artifactory-oss.prod.netflix.net/artifactory/maven-oss-candidates</url> 
       <snapshots>
	    <enabled>false</enabled>
       </snapshots>
</repository>
```
After adding the `spring-cloud-starter-netflix-eureka-client` artifactId, we are getting the below error while running the application
`java.lang.NoClassDefFoundError: org/apache/hc/client5/http/classic/HttpClient`

Have tried adding the below dependency, still no luck this time facing new error
```xml
<dependency>
    <groupId>org.apache.httpcomponents.client5</groupId>
    <artifactId>httpclient5</artifactId>
    <version>5.2-alpha1</version>
</dependency>
```
java.lang.NoSuchMethodError: 'void org.springframework.http.client.HttpComponentsClientHttpRequestFactory.setHttpClient(org.apache.http.client.HttpClient)

You're help is greatly appreciated

**Comment by spencergibb** [comment]
Spring Cloud 2022.0.0-M5 is not compatible with boot snapshots. Use 3.0.0-M5

**Comment by bsmahi** [comment]
Thanks @spencergibb for your time
