### ISSUE TITLE
How to change service path in Zuul route

### ISSUE THREAD

**Issue by nazrul-kabir** [spring-cloud/spring-cloud-netflix#4131]
I want to re-write my URL to map to a specific service path.
I want to route /orders** to /api/v1/** on the micro service. An example full endpoint could be /orders, and it would map to the microservice at this full endpoint /api/v1/function1.

I'm using Eureka Service Discovery, so I can't use uri. Here is my application.properties:

```
zuul.routes.orders.path=/orders/**
zuul.routes.orders.serviceId=order-service
zuul.routes.orders.stripPrefix= true
```

I tried using a custom path filter as mentioned [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/1893)

```
    @Override
    public Object run() {
        RequestContext context = RequestContext.getCurrentContext();
        Object originalRequestPath = context.get(REQUEST_URI_KEY);
        String modifiedRequestPath = "/api/microservicePath" + originalRequestPath;
        context.put(REQUEST_URI_KEY, modifiedRequestPath);

        return null;
    }
```

**Comment by OlgaMaciaszek** [comment]
Hello @nazrul-kabir. Spring Cloud Netflix Zuul has been out of support for quite some time now. We strongly recommend migrating over to Spring Cloud Gateway in order to avoid security issues.

**Comment by taasjord** [comment]
I did it just like that, with a custom path filter, with the only difference i supplied custom configuration properties to not hard code the path on the service. And I had a specific order on it:
```
// Must run after the pre-decoration filter
protected static final int FILTER_ORDER =  PRE_DECORATION_FILTER_ORDER + 1;
```

**Comment by moa-oma** [comment]
When I saw this, I gave up completely

**Comment by moa-oma** [comment]
Rewrite the RequestContext requestURI only using Filter before RibbonRoutingFilter

**Comment by OlgaMaciaszek** [comment]
Please do not use Spring Cloud Netflix Zuul. It has been out of maintenance for years now. You're exposing yourself to security vulnerabilities by using it. Please use Spring Cloud Gateway.
