### ISSUE TITLE
Migrate out of deprecated WebClient exchange() method

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-netflix#4133]

**Comment by ayushdubey755** [comment]
@OlgaMaciaszek Can I work on this issue? is there anything else should I know for the first time contributing to this project, I would love to work on it since I have previously used the spring framework and currently working on spring boot.

**Comment by OlgaMaciaszek** [comment]
Sure, @ayushdubey755. Go ahead.
