### ISSUE TITLE
EurekaClientHints not working with native

### ISSUE THREAD

**Issue by iromu** [spring-cloud/spring-cloud-netflix#4139]
**Describe the bug**

```
Spring Boot 3.0.0-RC2
<spring-cloud.version>2022.0.0-RC2</spring-cloud.version>
```

When running a native compiled app with Eureka enabled as client, the application fails to start with the following error:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servicesController': 
Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'compositeDiscoveryClient':
 Unsatisfied dependency expressed through method 'compositeDiscoveryClient' parameter 0: Error creating bean with name 
'discoveryClient': Unsatisfied dependency expressed through method 'discoveryClient' parameter 0: No qualifying bean of type 
'com.netflix.discovery.EurekaClient' available: expected at least 1 bean which qualifies as autowire candidate.
 Dependency annotations: {}
```

**Sample**
https://github.com/iromu/native-eureka-client/tree/3.0.x

**Comment by Jamby93** [comment]
Same issue here. tested on Spring Boot 3.0.1 Spring Cloud 2022.0.0, spring-cloud-starter-netflix-eureka-client 4.0.0.
Running the built jar with a JDK gives no error, but if it is run with `spring.aot.enabled=true` or the native image, it gives out the reported error.

**Comment by jesussaad** [comment]
same case of @Jamby93

**Comment by Jamby93** [comment]
Actually I ended up copy-pasting the beans definition from the [EurekaClientAutoConfiguration](https://github.com/spring-cloud/spring-cloud-netflix/blob/d34bae53c0167dd447f6cfb832987d261790ceba/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L255). I'm not exactly sure how the `@ConditionalOnRefreshScope`  behaves with native/AOT compilation, but at least in this way I got it working in native mode.
`       @Autowired
	private ApplicationContext context;

	@Autowired
	private AbstractDiscoveryClientOptionalArgs<?> optionalArgs;
	@Bean(destroyMethod = "shutdown")
	@ConditionalOnMissingBean(value = EurekaClient.class, search = SearchStrategy.CURRENT)
	public EurekaClient eurekaClient(ApplicationInfoManager manager, EurekaClientConfig config,
		TransportClientFactories<?> transportClientFactories) {
		return new CloudEurekaClient(manager, config, transportClientFactories, this.optionalArgs, this.context);
	}
	@Bean
	@ConditionalOnMissingBean(value = ApplicationInfoManager.class, search = SearchStrategy.CURRENT)
	public ApplicationInfoManager eurekaApplicationInfoManager(EurekaInstanceConfig config) {
		InstanceInfo instanceInfo = new InstanceInfoFactory().create(config);
		return new ApplicationInfoManager(config, instanceInfo);
	}
	@Bean
	@ConditionalOnMissingBean(value = EurekaRegistration.class, search = SearchStrategy.CURRENT)
	public EurekaRegistration eurekaRegistration(EurekaClient eurekaClient,
		CloudEurekaInstanceConfig instanceConfig, ApplicationInfoManager applicationInfoManager,
		@Autowired(required = false) ObjectProvider<HealthCheckHandler> healthCheckHandler) {
		return EurekaRegistration.builder(instanceConfig).with(applicationInfoManager).with(eurekaClient)
			.with(healthCheckHandler).build();
	}`

**Comment by aaronmaj** [comment]
Same case as @Jamby93 but the proposed workaround is not working for me

**Comment by stefanof95** [comment]
The solution provided by @Jamby93 works adding @Primary on eurekaRegistration bean (change bean name to avoid conflicts with spring eureka auto configuration)

**Comment by OlgaMaciaszek** [comment]
@iromu @stefanof95 @aaronmaj have you set `spring.cloud.refresh.enabled` to `false` as indicated [in the docs](https://docs.spring.io/spring-cloud-netflix/docs/4.0.1-SNAPSHOT/reference/html/#aot-and-native-image-support)? It should work OOTB then.

**Comment by dbamberghi** [comment]
> @iromu @stefanof95 @aaronmaj have you set `spring.cloud.refresh.enabled` to `false` as indicated [in the docs](https://docs.spring.io/spring-cloud-netflix/docs/4.0.1-SNAPSHOT/reference/html/#aot-and-native-image-support) in your projects? I can see it's not been set in the sample. It should work OOTB then.

``

**Comment by dbamberghi** [comment]
> @iromu @stefanof95 @aaronmaj have you set `spring.cloud.refresh.enabled` to `false` as indicated [in the docs](https://docs.spring.io/spring-cloud-netflix/docs/4.0.1-SNAPSHOT/reference/html/#aot-and-native-image-support) in your projects? I can see it's not been set in the sample. It should work OOTB then.

``

**Comment by dbamberghi** [comment]
> @iromu @stefanof95 @aaronmaj have you set `spring.cloud.refresh.enabled` to `false` as indicated [in the docs](https://docs.spring.io/spring-cloud-netflix/docs/4.0.1-SNAPSHOT/reference/html/#aot-and-native-image-support) in your projects? I can see it's not been set in the sample. It should work OOTB then.

After setting the indicated property, when launch the native program returns this error

`org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'serviceId' cannot be found on object of type 'org.springframework.cloud.netflix.eureka.EurekaServiceInstance' - maybe not public or not valid?
`

**Comment by OlgaMaciaszek** [comment]
I have run the linked sample (btw., Boot and Cloud versions are outdated in this sample, but it works anyway) as a native image after disabling refresh. The app ran without errors and I was also able to call both endpoints without facing any issues. 
@dbamberghi , if you are still experiencing issues, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by dbamberghi** [comment]
> I have run the linked sample (btw., Boot and Cloud versions are outdated in this sample, but it works anyway) as a native image after disabling refresh. The app ran without errors and I was also able to call both endpoints without facing any issues. @dbamberghi , if you are still experiencing issues, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

I started an instance of Eureka (again with springboot3). Compiled the project consisting of the Gateway module and Eureka client. A few seconds after start-up, the error message 'failed refresh' appears with the message posted above.

[project example](https://github.com/dbamberghi/demo-gateway.git)

Could this be a problem with the gateway module?

**Comment by OlgaMaciaszek** [comment]
Thanks, @dbamberghi - I was able to reproduce it. It seems to only happen with both EurekaClient and Gateway Route Locator on. Will provide a fix.
