### ISSUE TITLE
Support placeholders in @FeignClient definitions

### ISSUE THREAD

**Issue by CanD42** [spring-cloud/spring-cloud-netflix#414]
The com.netflix.loadbalancer.LoadBalancerContext takes the original protocol from the @FeignClient definition so if you want to use https you can specify that with (as discussed in https://github.com/spring-cloud/spring-cloud-netflix/issues/337)

    @FeignClient("https://users")

It would be very helpful to support placeholder here so that you can have different schemes in various landscapes: 

    @FeignClient("${feign.url.scheme}://users")

**Comment by beku8** [comment]
This feature would be nice, not just to resolve scheme, but for use cases like plug local app to cloud dev environment with prefixes etc.

**Comment by CanD42** [comment]
Any change to get this into the next release? Thanks

**Comment by czolek** [comment]
I have stumbled upon this issue myself and thought it would be very helpful to have this resolved. That's why I have implemented the fix (I call it a fix as it is clearly an omission and I categorise it as a bug).
I will submit a pull request in a day or two when I learn how the process work as I have never done so before.
I'll keep you posted.

**Comment by dsyer** [comment]
I believe you can set `ribbon.<service>.IsSecure` (or use `<service>=default` for all). Feign hasn't yet been spruced up to support the new `ServerIntrospector` abstraction (commit aa862673), but it probably should be. So I don't think placeholders is necessarily the way to solve this problem (however handy they would be).

**Comment by beku8** [comment]
@dsyer I would like to use this feature not to support ssl, but to add prefixes to the services. E.g I would set ```-Dfoo.servicePrefix=dev``` & feign would connect to ```dev_foo``` instead of ```foo``` etc.

**Comment by dsyer** [comment]
I don't think that's a great use case either. The whole point of service discovery is so you don't have to do this kind of thing.

**Comment by czolek** [comment]
I agree with Dave that placeholders have little use in service discovery. However they are quite useful when using `url` attribute without service discovery enabled. Also I found it troublesome not to be able to use placeholders in `@EnableFeignClients` `basePackages` attribute.
The use-case is that we are developing our own starter project which enables feign clients and by default registers some clients, interceptors etc. Users, of course, can provide their own clients and the idea is to provide an easy to use lib where clients location is specified via a property without the need to provide any additional configuration class. By default we scan at root level /**, but someone may wish to limit scan scope.
I won't argue that the whole idea is vital but it is just nice to have such an option.

**Comment by kflorence** [comment]
:+1 only because this seems like expected behavior and it would be beneficial to pull values from a config  -- otherwise, be cautious about disrupting behavior between environments.
