### ISSUE TITLE
Missing artifact com.netflix.eureka:eureka-client:jar:2.0.0-rc.4

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud/spring-cloud-netflix#4147]
**Describe the bug**
Does Netfilx Eureka has the version for 2.0.0-rc.4 in Spring Cloud 2022.0.0-RC2?

**Sample**
![图片](https://user-images.githubusercontent.com/42354711/206167365-363c053a-292f-4f65-9280-4c9e95fc7b10.png)

**Comment by OlgaMaciaszek** [comment]
Hello @HaojunRen. Since it's an RC, it's not available in Maven Central. If you'd like to use it, please add 

```
<repository>
      <id>netflix-candidates</id>
      <name>Netflix Candidates</name>
      <url>https://artifactory-oss.prod.netflix.net/artifactory/maven-oss-candidates</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
```
to your Maven pom file or make a corresponding change in your Gradle setup.
