### ISSUE TITLE
Eureka-client registers to naming-service before embed-tomcat(servlet container) is ready.

### ISSUE THREAD

**Issue by Melon-Seeds** [spring-cloud/spring-cloud-netflix#4149]
**Describe the bug**
I use tomcat as servlet container in springboot, and use eureka-server as the naming service.
the version is : spring-boot-2.0.3.RELEASE and spring-boot-2.5.?.RELEASE
I notice that when I turn on tomcat's min-spare-threads to a big number, see 100, I'll get many error requests when I restart the application. （in our production env）

Then I check the code inside and find that, **spring application registers to naming-service before it starts tomcat server(start the worker and accepter threads), that is to say, the application may be available(to other eureka clients) before tomcat gets ready**. Which confuse me ver much, why not start tomcat first?(when tomcat start, it will created minSpareThreads to its threadPool) Is there any reason?

**Sample**
first start a eureka-server:
![image](https://user-images.githubusercontent.com/25941510/207547739-6ad07be7-23d8-47b3-93a3-444cda60fe2a.png)
you can see these is no instances currently

then add a break point here:
![image](https://user-images.githubusercontent.com/25941510/207547979-076b8eb6-f1d1-4441-bd2d-6dd0eb3bc71c.png)
the path is : spring-boot-2.0.3.RELEASE-sources.jar!/org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext#finishRefresh

then debug the application and we stop here:
![image](https://user-images.githubusercontent.com/25941510/207548438-5774c3df-e082-4ba1-b784-334f535b0ac2.png)
from the console, you can see that this application has registered to eureka-server.

now we can find this in currently instances
![image](https://user-images.githubusercontent.com/25941510/207548774-e19360b7-32e1-488b-b4b0-b9d50f7c578a.png)

But in fact, we cannot visit this application cause its servlet container is not ready:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/25941510/207549544-65b61f52-ae59-4a83-99cd-f969c31bdcc2.png">

so I think it's a bug, application should not register to eureka-server before it's ready.

**Comment by spencergibb** [comment]
Those versions are no longer supported. Please try again with boot 2.7/spring cloud 2021.0.5 or boot 3.0/cloud 2022.0.1

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Melon-Seeds** [comment]
I apologize for my recent lack of communication. I've been quite busy due to personal matters such as being let go from my previous job, job hunting, and adjusting to a new work schedule and company culture.
Moving forward, I wanted to discuss the topic at hand. I have tried the new version you mentioned (Spring 2.7.9) and am happy to report that the issue I previously mentioned has been resolved.
 Attached are some screenshots from my testing.

Brekpoint:
> eureka-client-1.10.17-sources.jar!\com\netflix\discovery\DiscoveryClient.java

![1](https://user-images.githubusercontent.com/25941510/225687082-21b33bac-988a-4a4a-a88f-8f6ba6fb3626.png)


Version:
![2](https://user-images.githubusercontent.com/25941510/225687136-e733380b-e184-43ad-8d69-61d7792db46f.png)


erueka-console
![3](https://user-images.githubusercontent.com/25941510/225687169-2eb22f95-6ee2-4dba-9254-714476068233.png)


Servlet-container
![4](https://user-images.githubusercontent.com/25941510/225687203-28835081-2373-45fb-b992-b18a248b9a3e.png)



Finally, thanks for your reply!

**Comment by spencergibb** [comment]
Thanks for the update

**Comment by szw-yunie** [comment]
> Thanks for the update

However, I noticed that in the spring-cloud-netflix-eureka-client-3.1.4 source, EurekaAutoServiceRegistration's getPhase method returns 0, Less than WebServerStartStopLifecycle's getPhase method return value (Integer. MAX_VALUE - 1). This means that in some extreme cases, it is indeed possible for a service to register with eureka before it's serviceable.
