### ISSUE TITLE
Documentation minor Issue

### ISSUE THREAD

**Issue by satishppawar** [spring-cloud/spring-cloud-netflix#4156]
**Describe the bug**

In the documentation of Spring Cloud Netflix features, there is an issue

Feature should be

1. Service Registeration
2. Service Discovery

**Sample**

![image](https://user-images.githubusercontent.com/7584412/213967722-5eaef4f2-b980-445b-9d95-2e0af1be8118.png)

**Comment by MarianConstantinMarica** [comment]
Can I work on this issue?

**Comment by MarianConstantinMarica** [comment]
I put the pull request

**Comment by Saravana-PS** [comment]
I have raised the PR(#4166) for this issue.

**Comment by vishalsingh2972** [comment]
@satishppawar  could you assign this to me if it is still open?

**Comment by vishalsingh2972** [comment]
@spencergibb  could you assign this to me if it is still open?

**Comment by Tjs002** [comment]
@spencergibb can u review PR #4188?
