### ISSUE TITLE
spring-cloud-starter-netflix-zuul not work with spring-boot 3.0 and spring 6.0

### ISSUE THREAD

**Issue by fink-artem** [spring-cloud/spring-cloud-netflix#4158]
Hi.

I see that spring-cloud-starter-netflix-zuul does not support working with spring-boot 3.0. For example, ZuulHandlerMapping use javax.servlet.http.HttpServletRequest, but in new version spring it class should use jakarta.servlet.http package.

Is there any further support for zuul? On the internet I find tips to try spring-cloud-gateway. But it is reactive and it not work with spring security. I can't figure out how to set up proxying now.

Thanks in advance.

**Comment by OlgaMaciaszek** [comment]
Hello @fink-artem, Spring Cloud Netflix Zuul has been out of support for many years now. We recommend switching to using Spring Cloud Gateway.

**Comment by andreaslanderer** [comment]
> Hello @fink-artem, Spring Cloud Netflix Zuul has been out of support for many years now. We recommend switching to using Spring Cloud Gateway.

Hello Olga,

I have the same issue and I'd love to switch to Spring Cloud Gateway. Unfortunately, it does not support Spring MVC and we can not, and actually don't want to, rewrite our whole application. Any suggestions for us?

**Comment by OlgaMaciaszek** [comment]
CC @spencergibb

**Comment by spencergibb** [comment]
We plan on addressing spring MVC support later this year https://github.com/spring-cloud/spring-cloud-gateway/issues/36

**Comment by andreaslanderer** [comment]
@spencergibb thank you, great to hear that :-)

**Comment by VictorFerreiraS** [comment]
I'm doing a personal project using spring version 3.1 and having the same issue, just getting a 403 out of postman... hope there is a way to address that
