### ISSUE TITLE
Netflix Eureka Server dashboard not showing and not registering server

### ISSUE THREAD

**Issue by lapc18** [spring-cloud/spring-cloud-netflix#4169]
Hi;

I'm facing the same issue.

Here the details:

SpringBoot: 2.7..10
Java: 17

POM.xml:
`

4.0.0

org.springframework.boot
spring-boot-starter-parent
2.7.10

io.inab
e-market-eureka-server
0.0.1-SNAPSHOT
e-market-eureka-server
e-market-eureka-server project for Spring Boot

<java.version>17</java.version>
<spring-cloud.version>2021.0.6</spring-cloud.version>

org.springframework.boot
spring-boot-starter-actuator

org.springframework.cloud
spring-cloud-starter-gateway

org.springframework.cloud
spring-cloud-starter-netflix-eureka-server

org.springframework.boot
spring-boot-starter-tomcat
provided

org.springframework.boot
spring-boot-starter-test
test

org.springframework.cloud
spring-cloud-dependencies
${spring-cloud.version}
pom
import

<build>
	<plugins>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
		<plugin>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>2.10</version>
			<configuration>
				<useFile>false</useFile>
			</configuration>
		</plugin>
	</plugins>
</build>
`

application.properties:
server.port=8762 spring.application.name=eureka-server #eureka.instance.hostname=localhost eureka.client.registerWithEureka=false eureka.client.fetchRegistry=false spring.main.allow-bean-definition-overriding=true #spring.main.web-application-type=reactive eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/ spring.cloud.gateway.discovery.locator.enabled=true eureka.server.enable-self-preservation=false spring.freemarker.template-loader-path= classpath:/templates/ spring.freemarker.prefer-file-system-access= false

Application.java
@SpringBootApplication @EnableEurekaServer @EnableAutoConfiguration(exclude = EurekaServerAutoConfiguration.class) public class EMarketEurekaServerApplication { public static void main(String[] args) { SpringApplication.run(EMarketEurekaServerApplication.class, args); } }

GatewayConfiguration:
`@Configuration
@EnableAutoConfiguration()
public class GatewayConfiguration extends GatewayAutoConfiguration {

@Bean
public RouteLocator myRoutes(RouteLocatorBuilder builder) {
    return builder.routes()
            .route(p -> p
                    .path("/api/products/**")
                    .filters(f -> f.stripPrefix(1))
                    .uri("lb://products-microservice"))
            .build();
}

@Bean
public GatewayFilter gatewayFilterFilter() {
    return (exchange, chain) -> {
        // add custom filter logic here
        return chain.filter(exchange);
    };
}

@Bean
public ServerCodecConfigurer serverCodecConfigurer() {
    return ServerCodecConfigurer.create();
}
}`

LOGS:
`/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=54474:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/luispimentel.c/Inabio/clients/e-marketplace/e-market-server/e-market-eureka-server/target/classes:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.7.10/spring-boot-starter-actuator-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter/2.7.10/spring-boot-starter-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot/2.7.10/spring-boot-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-context/5.3.26/spring-context-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-aop/5.3.26/spring-aop-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-expression/5.3.26/spring-expression-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.7.10/spring-boot-autoconfigure-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.7.10/spring-boot-starter-logging-2.7.10.jar:/Users/luispimentel.c/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar:/Users/luispimentel.c/.m2/repository/ch/qos/logback/logback-core/1.2.11/logback-core-1.2.11.jar:/Users/luispimentel.c/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.2/log4j-to-slf4j-2.17.2.jar:/Users/luispimentel.c/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.2/log4j-api-2.17.2.jar:/Users/luispimentel.c/.m2/repository/org/slf4j/jul-to-slf4j/1.7.36/jul-to-slf4j-1.7.36.jar:/Users/luispimentel.c/.m2/repository/org/yaml/snakeyaml/1.30/snakeyaml-1.30.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.7.10/spring-boot-actuator-autoconfigure-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-actuator/2.7.10/spring-boot-actuator-2.7.10.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.13.5/jackson-databind-2.13.5.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.13.5/jackson-annotations-2.13.5.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.13.5/jackson-core-2.13.5.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.13.5/jackson-datatype-jsr310-2.13.5.jar:/Users/luispimentel.c/.m2/repository/io/micrometer/micrometer-core/1.9.9/micrometer-core-1.9.9.jar:/Users/luispimentel.c/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/luispimentel.c/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-starter-gateway/3.1.6/spring-cloud-starter-gateway-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-starter/3.1.6/spring-cloud-starter-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-context/3.1.6/spring-cloud-context-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/security/spring-security-crypto/5.7.7/spring-security-crypto-5.7.7.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-commons/3.1.6/spring-cloud-commons-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/security/spring-security-rsa/1.0.11.RELEASE/spring-security-rsa-1.0.11.RELEASE.jar:/Users/luispimentel.c/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.69/bcpkix-jdk15on-1.69.jar:/Users/luispimentel.c/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.69/bcprov-jdk15on-1.69.jar:/Users/luispimentel.c/.m2/repository/org/bouncycastle/bcutil-jdk15on/1.69/bcutil-jdk15on-1.69.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-gateway-server/3.1.6/spring-cloud-gateway-server-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.7.10/spring-boot-starter-validation-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/hibernate/validator/hibernate-validator/6.2.5.Final/hibernate-validator-6.2.5.Final.jar:/Users/luispimentel.c/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/Users/luispimentel.c/.m2/repository/org/jboss/logging/jboss-logging/3.4.3.Final/jboss-logging-3.4.3.Final.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/luispimentel.c/.m2/repository/io/projectreactor/addons/reactor-extra/3.4.10/reactor-extra-3.4.10.jar:/Users/luispimentel.c/.m2/repository/io/projectreactor/reactor-core/3.4.28/reactor-core-3.4.28.jar:/Users/luispimentel.c/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-webflux/2.7.10/spring-boot-starter-webflux-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.7.10/spring-boot-starter-json-2.7.10.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.13.5/jackson-datatype-jdk8-2.13.5.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.13.5/jackson-module-parameter-names-2.13.5.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-reactor-netty/2.7.10/spring-boot-starter-reactor-netty-2.7.10.jar:/Users/luispimentel.c/.m2/repository/io/projectreactor/netty/reactor-netty-http/1.0.30/reactor-netty-http-1.0.30.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-codec-http/4.1.90.Final/netty-codec-http-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-common/4.1.90.Final/netty-common-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-buffer/4.1.90.Final/netty-buffer-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-transport/4.1.90.Final/netty-transport-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-codec/4.1.90.Final/netty-codec-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-handler/4.1.90.Final/netty-handler-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-codec-http2/4.1.90.Final/netty-codec-http2-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-resolver-dns/4.1.90.Final/netty-resolver-dns-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-resolver/4.1.90.Final/netty-resolver-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-codec-dns/4.1.90.Final/netty-codec-dns-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.90.Final/netty-resolver-dns-native-macos-4.1.90.Final-osx-x86_64.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-resolver-dns-classes-macos/4.1.90.Final/netty-resolver-dns-classes-macos-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-transport-native-epoll/4.1.90.Final/netty-transport-native-epoll-4.1.90.Final-linux-x86_64.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.90.Final/netty-transport-native-unix-common-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.90.Final/netty-transport-classes-epoll-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/projectreactor/netty/reactor-netty-core/1.0.30/reactor-netty-core-1.0.30.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-handler-proxy/4.1.90.Final/netty-handler-proxy-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/io/netty/netty-codec-socks/4.1.90.Final/netty-codec-socks-4.1.90.Final.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-web/5.3.26/spring-web-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-beans/5.3.26/spring-beans-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-webflux/5.3.26/spring-webflux-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-starter-netflix-eureka-server/3.1.5/spring-cloud-starter-netflix-eureka-server-3.1.5.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-server/3.1.5/spring-cloud-netflix-eureka-server-3.1.5.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.7.10/spring-boot-starter-web-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-webmvc/5.3.26/spring-webmvc-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-freemarker/2.7.10/spring-boot-starter-freemarker-2.7.10.jar:/Users/luispimentel.c/.m2/repository/org/freemarker/freemarker/2.3.32/freemarker-2.3.32.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-context-support/5.3.26/spring-context-support-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-netflix-eureka-client/3.1.5/spring-cloud-netflix-eureka-client-3.1.5.jar:/Users/luispimentel.c/.m2/repository/com/netflix/eureka/eureka-client/1.10.17/eureka-client-1.10.17.jar:/Users/luispimentel.c/.m2/repository/com/netflix/netflix-commons/netflix-eventbus/0.3.0/netflix-eventbus-0.3.0.jar:/Users/luispimentel.c/.m2/repository/com/netflix/netflix-commons/netflix-infix/0.3.0/netflix-infix-0.3.0.jar:/Users/luispimentel.c/.m2/repository/commons-jxpath/commons-jxpath/1.3/commons-jxpath-1.3.jar:/Users/luispimentel.c/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar:/Users/luispimentel.c/.m2/repository/org/antlr/antlr-runtime/3.4/antlr-runtime-3.4.jar:/Users/luispimentel.c/.m2/repository/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar:/Users/luispimentel.c/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar:/Users/luispimentel.c/.m2/repository/com/google/code/gson/gson/2.9.1/gson-2.9.1.jar:/Users/luispimentel.c/.m2/repository/org/apache/commons/commons-math/2.2/commons-math-2.2.jar:/Users/luispimentel.c/.m2/repository/com/thoughtworks/xstream/xstream/1.4.18/xstream-1.4.18.jar:/Users/luispimentel.c/.m2/repository/io/github/x-stream/mxparser/1.2.2/mxparser-1.2.2.jar:/Users/luispimentel.c/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:/Users/luispimentel.c/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar:/Users/luispimentel.c/.m2/repository/com/netflix/servo/servo-core/0.12.21/servo-core-0.12.21.jar:/Users/luispimentel.c/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar:/Users/luispimentel.c/.m2/repository/com/sun/jersey/jersey-core/1.19.1/jersey-core-1.19.1.jar:/Users/luispimentel.c/.m2/repository/com/sun/jersey/contribs/jersey-apache-client4/1.19.1/jersey-apache-client4-1.19.1.jar:/Users/luispimentel.c/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar:/Users/luispimentel.c/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar:/Users/luispimentel.c/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/Users/luispimentel.c/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:/Users/luispimentel.c/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/luispimentel.c/.m2/repository/com/google/inject/guice/4.1.0/guice-4.1.0.jar:/Users/luispimentel.c/.m2/repository/org/codehaus/jettison/jettison/1.4.0/jettison-1.4.0.jar:/Users/luispimentel.c/.m2/repository/com/sun/jersey/jersey-servlet/1.19.4/jersey-servlet-1.19.4.jar:/Users/luispimentel.c/.m2/repository/com/sun/jersey/jersey-server/1.19.4/jersey-server-1.19.4.jar:/Users/luispimentel.c/.m2/repository/com/sun/jersey/jersey-client/1.19.4/jersey-client-1.19.4.jar:/Users/luispimentel.c/.m2/repository/com/netflix/eureka/eureka-core/1.10.17/eureka-core-1.10.17.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.2.1/woodstox-core-6.2.1.jar:/Users/luispimentel.c/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/luispimentel.c/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.13.5/jackson-dataformat-xml-2.13.5.jar:/Users/luispimentel.c/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-starter-loadbalancer/3.1.6/spring-cloud-starter-loadbalancer-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/cloud/spring-cloud-loadbalancer/3.1.6/spring-cloud-loadbalancer-3.1.6.jar:/Users/luispimentel.c/.m2/repository/org/springframework/boot/spring-boot-starter-cache/2.7.10/spring-boot-starter-cache-2.7.10.jar:/Users/luispimentel.c/.m2/repository/com/stoyanr/evictor/1.0.0/evictor-1.0.0.jar:/Users/luispimentel.c/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.8/jaxb-runtime-2.3.8.jar:/Users/luispimentel.c/.m2/repository/org/glassfish/jaxb/txw2/2.3.8/txw2-2.3.8.jar:/Users/luispimentel.c/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.12/istack-commons-runtime-3.0.12.jar:/Users/luispimentel.c/.m2/repository/com/sun/activation/jakarta.activation/1.2.2/jakarta.activation-1.2.2.jar:/Users/luispimentel.c/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/luispimentel.c/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.73/tomcat-embed-el-9.0.73.jar:/Users/luispimentel.c/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/Users/luispimentel.c/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar:/Users/luispimentel.c/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-core/5.3.26/spring-core-5.3.26.jar:/Users/luispimentel.c/.m2/repository/org/springframework/spring-jcl/5.3.26/spring-jcl-5.3.26.jar io.inab.emarketeurekaserver.EMarketEurekaServerApplication

. ____ _ __ _ _
/\ / ' __ _ () __ __ _ \ \ \
( ( )__ | '_ | '| | ' / ` | \ \ \
\/ )| |)| | | | | || (| | ) ) ) )
' || .__|| ||| |_, | / / / /
=========||==============|/=////
:: Spring Boot :: (v2.7.10)

2023-03-30 19:01:20.971 INFO 3458 --- [ main] i.i.e.EMarketEurekaServerApplication : Starting EMarketEurekaServerApplication using Java 19.0.1 on lapc18 with PID 3458 (/Users/luispimentel.c/Inabio/clients/e-marketplace/e-market-server/e-market-eureka-server/target/classes started by luispimentel.c in /Users/luispimentel.c/Inabio/clients/e-marketplace/e-market-server/e-market-eureka-server)
2023-03-30 19:01:20.975 INFO 3458 --- [ main] i.i.e.EMarketEurekaServerApplication : No active profile set, falling back to 1 default profile: "default"
2023-03-30 19:01:22.281 INFO 3458 --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory id=2adb29b9-1420-3755-829b-dcaf7efb5195
2023-03-30 19:01:22.363 INFO 3458 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-03-30 19:01:22.364 INFO 3458 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-03-30 19:01:22.366 INFO 3458 --- [ main] trationDelegate$BeanPostProcessorChecker : Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [After]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Before]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Between]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Cookie]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Header]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Host]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Method]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Path]
2023-03-30 19:01:23.198 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Query]
2023-03-30 19:01:23.199 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [ReadBody]
2023-03-30 19:01:23.199 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [RemoteAddr]
2023-03-30 19:01:23.199 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [XForwardedRemoteAddr]
2023-03-30 19:01:23.199 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [Weight]
2023-03-30 19:01:23.199 INFO 3458 --- [ main] o.s.c.g.r.RouteDefinitionRouteLocator : Loaded RoutePredicateFactory [CloudFoundryRouteService]
2023-03-30 19:01:23.649 INFO 3458 --- [ main] o.s.b.a.e.web.EndpointLinksResolver : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-03-30 19:01:23.914 INFO 3458 --- [ main] DiscoveryClientOptionalArgsConfiguration : Eureka HTTP Client uses Jersey
2023-03-30 19:01:24.008 WARN 3458 --- [ main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
2023-03-30 19:01:24.042 INFO 3458 --- [ main] o.s.c.n.eureka.InstanceInfoFactory : Setting initial instance status as: STARTING
2023-03-30 19:01:24.074 INFO 3458 --- [ main] com.netflix.discovery.DiscoveryClient : Initializing Eureka in region us-east-1
2023-03-30 19:01:24.075 INFO 3458 --- [ main] com.netflix.discovery.DiscoveryClient : Client configured to neither register nor query for data.
2023-03-30 19:01:24.084 INFO 3458 --- [ main] com.netflix.discovery.DiscoveryClient : Discovery Client initialized at timestamp 1680217284083 with initial instances count: 0
2023-03-30 19:01:24.089 INFO 3458 --- [ main] o.s.c.n.e.s.EurekaServiceRegistry : Registering application EUREKA-SERVER with eureka with status UP
2023-03-30 19:01:24.247 INFO 3458 --- [ main] o.s.b.web.embedded.netty.NettyWebServer : Netty started on port 8762
2023-03-30 19:01:24.248 INFO 3458 --- [ main] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8762
2023-03-30 19:01:24.281 INFO 3458 --- [ main] i.i.e.EMarketEurekaServerApplication : Started EMarketEurekaServerApplication in 3.816 seconds (JVM running for 4.343)
2023-03-30 19:04:56.666 INFO 3458 --- [ionShutdownHook] o.s.c.n.e.s.EurekaServiceRegistry : Unregistering application EUREKA-SERVER with eureka with status DOWN
2023-03-30 19:04:58.739 INFO 3458 --- [ionShutdownHook] com.netflix.discovery.DiscoveryClient : Shutting down DiscoveryClient ...
2023-03-30 19:04:58.824 INFO 3458 --- [ionShutdownHook] com.netflix.discovery.DiscoveryClient : Completed shut down of DiscoveryClient`

Web browser: when navigating to /eureka/ it shows Whithelable error page but not when navigating to /actuator
<img width="609" alt="image" src="https://user-images.githubusercontent.com/46631073/228986017-6a47432e-b0bd-4724-b3f7-152fb079e505.png">

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/46631073/228985984-48b6272b-7524-4924-9fe8-4e54d9a87a65.png">

If you need any other detail, please let me know.

Thank you in advance!

**Comment by Bizarrus** [comment]
Have the same issue.
