### ISSUE TITLE
Eureka - ServiceInstance w/ health URLS?

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#418]
Currently a `ServiceInstance` returned by the `DiscoveryClient` (and `EurekaDiscoveryClient`) has a limited amount of information. Would there be any interest in providing an extended interface of `ServiceInstance`, e.g. `DiscoveryServiceInstance` (or something more appropriate) that can return more information, such as the health and info URLs? 

If so, this may be more appropriate for *spring-cloud-commons* unless it makes sense to only include this information with `EurekaDiscoveryClient`. 

I understand that we could autowire the Netflix DiscoveryClient and use that, but it would be nice to keep the abstraction that Spring Cloud provides.

If there is interest, I am willing to contribute a proposed solution.

**Comment by spencergibb** [comment]
Similar to #419 as the different urls are meta-data.  Let's have a conversation about generic metadata at https://github.com/spring-cloud/spring-cloud-commons/issues/19
