### ISSUE TITLE
Client cannot access metadata of a service it discovers

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-netflix#419]
Hey,

The [spring cloud documentation](http://projects.spring.io/spring-cloud/spring-cloud.html#_eureka_metadata_for_instances_and_clients) states that additional metadata can be added to the instance registration in the eureka.instance.metadataMap, and this will be accessible in the remote clients.

However, I'm not sure how to access this metadata.

The method on the spring cloud's EurekaDiscoveryClient `List<ServiceInstance> getInstances(String serviceId)` returns `EurekaServiceInstance`s.

The problem I see is that the `InstanceInfo` inside `EurekaServiceInstance` isn't accessible directly and its property `Map<String, String> metadata` isn't accessible through a getter on the `InstanceInfo` class.

Could an immutable version of this map be exposed to the remote client so it can discover the extra information set by looking into this map?

**Comment by dsyer** [comment]
This is really a problem in Spring Cloud Commons (which is so far just being very conservative in what it exposes to clients). You can use the netflix native APIs to get the metadata (and that's what we do for our `ServerList*` stuff in the Spring Cloud ribbon support). But for sure we need something more flexible in commons.

**Comment by spencergibb** [comment]
There is [an issue](https://github.com/spring-cloud/spring-cloud-commons/issues/19) and [PR](https://github.com/spring-cloud/spring-cloud-commons/pull/41) in commons to support tags (a specific form of meta-data for consul).  Let's move the discussion there.  Maybe we need something more generic than what has been proposed?

**Comment by beku8** [comment]
Can't it just provide ```InstanceInfo getInstanceInfo()``` method on ```EurekaServiceInstance```? 
So we can just cast the ```ServiceInstance``` to ```EurekaServiceInstance```?

**Comment by spencergibb** [comment]
No, it has to work with Consul and zookeeper as well.

**Comment by cforce** [comment]
@andreasevers I am very interested to see an example code how you set and retrieve the values sucessfully. Do you have an example online you can link. Tx in advance
