### ISSUE TITLE
Making POST on 'refresh' permamently deregisters the service from Eureka

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-netflix#421]
I had been playing around with Cloud Config Server and trying to setup the automatic propagation of configuration to all of the services when I had noticed that whenever I invoke the RefreshEndpoint.refresh or make HTTP request to '/refresh' endpoint my service disapears from Eureka and never appers again until it's been restarted. Here is the complete log: 

https://gist.github.com/jmnarloch/fc1aa7fa303cb983e6c0

I think that in fact deregistering the service from Eureka in the first place is not entirely desired, although this is a bit separate issue.

**Comment by spencergibb** [comment]
there were some recent changes to making sure the app registered/deregistered properly with the lifecycle of the application context.  Calling `/refresh` must trigger some odd behavior.

**Comment by wbauern** [comment]
We are currently experiencing the same problem using version Angel.SR3.  

I was also wondering about the deregisters we are seeing.  If that is going to be the go ahead behavior how well will it work with a bus config refresh for a horizontally scaled out service? Will there be potential for lookup errors?

**Comment by spencergibb** [comment]
@wbauern No, this is labeled as a bug.

**Comment by jmnarloch** [comment]
I'm going to refrence the discusion that with had related to config-server, although this issue seams more accurate: https://github.com/spring-cloud/spring-cloud-config/issues/186

**Comment by trondgzi** [comment]
It seems to only happen when using `spring.cloud.config.discovery.enabled=true`. By looking at the log from @jmnarloch I see that he is also using discovery for locating the configserver.

When using `spring.cloud.config.uri` I can post to /refresh and /bus/refresh and the service remains registered in eureka.

Tested with Brixton

**Comment by dsyer** [comment]
I think the problem here (going back to 1.0) is that `DiscoveryClientConfigServiceBootstrapConfiguration` (which is enabled by `spring.cloud.config.discovery.enabled`) is `@EnableDiscoveryClient` and it gets re-loaded when you do a `/refresh` because we rebuild the bootstrap context. Eureka (being a singleton) doesn't like being initialized twice in the same JVM so it is probably throwing a wobbly somewhere. The solution might be to avoid re-loading `DiscoveryClientConfigServiceBootstrapConfiguration` on a refresh (since we already have a discovery client we can try and use it instead).

**Comment by dsyer** [comment]
I can see a problem in 1.1 (because it's caused by a change that was made for #349) which causes the app to be registered as DOWN after the config client has done its business (in discovery mode). This might be related to the 1.0 issue with /refresh.

**Comment by atulkulkarni18** [comment]
Seems this issue has got fixed in 1.1.0.M5, which has not got GAed. Any idea when would it get GAed, as this is a critical bug? If this is not planned immediately, then is consuming 1.1.0 SNAPSHOT a good choice for application which needs to be deployed in production? Please suggest the best possible option.

**Comment by spencergibb** [comment]
@atulkulkarni18 next week.

**Comment by atulkulkarni18** [comment]
Thanks @spencergibb for quick response. Would monitor http://cloud.spring.io/spring-cloud-netflix this week for 1.1.0 getting GAed.

**Comment by devlanp** [comment]
@dsyer I still the same issue in the version 1.1.3.RELEASE. Any quick fixes or workaround?

**Comment by dsyer** [comment]
1.1.3 is not the latest release (it's not even the latest 1.1.x release). Did you try upgrading?

**Comment by devlanp** [comment]
@dsyer  I was working on the JHipster project (3.x.x for microservice) which brings in 1.1.3.Release.

I have tried with version 1.1.7 Release as per: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter

Any other jars to be updated?

Feel free to correct me if I missed anything?

**Comment by dsyer** [comment]
It would be a lot easier if you would use the release train BOM (e.g. Camden.SR4, I think is the latest).

**Comment by devlanp** [comment]
@dsyer  Did that too. No luck. I feel I'm missing something. Attached the effective pom of the service.

FYI. I'm using 
cloud:
        config:
            server:
                native:
                    search-locations: file:./central-config
[pom.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/736929/pom.txt)

**Comment by dsyer** [comment]
I don't know what you are seeing but it isn't the same as this issue (it's closed and all the code is released). Please open a new issue with some detailed steps to reproduce (a sample app would be ideal).

**Comment by devlanp** [comment]
Sure @dsyer . #1652 already opened for same. Will post a sample app. Its a jhipster generated microservice. Thanks for you support.
