### ISSUE TITLE
Replication not working between eureka servers with spring security

### ISSUE THREAD

**Issue by KrishnamMANTHENA** [spring-cloud/spring-cloud-netflix#4212]
**Describe the bug**

We have two eureka server instances trying to register with each other by using **serviceUrl**.  We have enabled spring security and included user name and password in the **serviceUrl**. The replication of services used to work without any issue when using Spring Boot - 2.7.13 and Spring Cloud - 2021.0.7 versions.

After switching to Spring Boot - 3.1.4 and Spring Cloud - 2022.0.2, the replication of services is not working any more and spring security is redirecting the POST requests "/eureka/peerreplication/batch/" to the login page as authorization header is missing.

**Sample**
Attached headers that are sent with "/eureka/peerreplication/batch/" request. The left side headers are for spring boot 3 which is missing authorization header while right hand side headers are from spring boot 2 which is having authorization header.

![ds-replica-headers](https://github.com/spring-cloud/spring-cloud-netflix/assets/148441653/c99454d3-aad7-4f56-af61-4e6267e11db8)

**Comment by spencergibb** [comment]
Can you try with the latest versions of spring cloud 2022.0.4? 

If not, can you please take the time to provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) (something that we can unzip attached to this issue or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
