### ISSUE TITLE
ribbon.eureka.enabled is still mentioned as valid property

### ISSUE THREAD

**Issue by sergey-morenets** [spring-cloud/spring-cloud-netflix#4219]
**Describe the bug**

Hi 

Official Spring Cloud Netflix documentation still specifies **ribbon.eureka.enabled** property and states that it "Enables the use of Eureka with Ribbon".
However Ribbon support was removed from Spring Cloud a couple of years ago and I couldn't find any usage of this property in the code or explanation in the documentation. So I guess it should be removed from the documentation.

https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/appendix.html

**Comment by OlgaMaciaszek** [comment]
Thanks @sergey-morenets. Fixing it.
