### ISSUE TITLE
Why can't a Spring Cloud Feign client share the interface with an Spring Web Controller?

### ISSUE THREAD

**Issue by mariusneo** [spring-cloud/spring-cloud-netflix#422]
Given the following code sample

-- client library code

```java
@FeignClient("string-service")
public interface StringClient {

     @RequestMapping(method = RequestMethod.GET, value = "/microservicestring")
      public String home();
}


@Service
public class StringHystrixClient {

    private final SpringClient springClient;
//....

}
```

-- service library code

```java
@RestController
public class StringController implements StringClient {
    public String home(){
         return "World";
    }
}


@SpringBootApplication
@EnableHystrix
@EnableEurekaClient
@EnableFeignClients
public class StringApplication { ....}
```

If the service library references the client library, when the application gets started, through component scanning we will get to a state where in filling the dependencies from StringHystrixClient, the spring container will not know what to do because there are two beans implementing StringClient.

One solution to avoid this would be to not implement the StringClient in the StringController, but the code duplication from the interface and the rest controller would be error prone. Can somebody point out a more elegant solution to this problem?

**Comment by spencergibb** [comment]
Please don't cross post.  Closing via SO http://stackoverflow.com/questions/31293583/how-to-safely-have-a-restcontroller-class-implementing-an-interface-annotated-w
