### ISSUE TITLE
The API  '/serverinfo/statusoverrides' from class ServerInfoResource don't work.

### ISSUE THREAD

**Issue by suojinxing** [spring-cloud/spring-cloud-netflix#4247]
**Describe the bug**
Class ServerInfoResource provides a HTTP API looks like '/serverinfo/statusoverrides'.

The contents of the ServerInfoResource are as follows

```java
@Path("/serverinfo")
public class ServerInfoResource {
    @GET
    @Path("statusoverrides")
    public Response getOverrides() throws Exception {
         // omit...
    }
}
```

But when I use PostMan or other API-Tools send HTTP request. always reponse 404

The url is `http://localhost:8761/eureka/serverinfo/statusoverrides`

![image](https://github.com/spring-cloud/spring-cloud-netflix/assets/48473289/f5ed256d-01c8-432f-96f0-f73aa12c888b)

**Sample**

I review the source code. I think the EurekaServerAutoConfiguration inject a Bean by the method that name is 'jerseyFilterRegistration'. 

```java
@Bean
public FilterRegistrationBean<?> jerseyFilterRegistration(javax.ws.rs.core.Application eurekaJerseyApp) {
    FilterRegistrationBean<Filter> bean = new FilterRegistrationBean<Filter>();
    bean.setFilter(new ServletContainer(eurekaJerseyApp));
    bean.setOrder(Ordered.LOWEST_PRECEDENCE);
    bean.setUrlPatterns(Collections.singletonList(EurekaConstants.DEFAULT_PREFIX + "/*"));
    return bean;
}
```

It blocks all HTTP requests beginning with '/eureka'. 

But jersey does not have a rule matching ‘/eureka/serverinfo’.  jersey only has a rule match '/serverinfo'. 

So I can't request the API that ServerInfoResource provides anyway

![bug](https://github.com/spring-cloud/spring-cloud-netflix/assets/48473289/98cd81d1-bd60-486e-9f40-d7b863ab08be)

**Comment by OlgaMaciaszek** [comment]
Hello @suojinxing, that class is part of the https://github.com/Netflix/eureka project and not Spring Cloud Netflix.
