### ISSUE TITLE
When @ RequestPart and @ RequestParam are used together, the @ RequestParam parameter will be duplicated

### ISSUE THREAD

**Issue by jackding79** [spring-cloud/spring-cloud-netflix#4286]
```java
   for (Entry<String, String[]> entry : request.getParameterMap().entrySet()) {
			String key = entry.getKey();
			List<String> listOfAllParams = stream(request.getParameterMap().get(key))
					.collect(Collectors.toList());
			List<String> listOfOnlyQueryParams = queryParamsGroupedByName.get(key);
       
			if (listOfOnlyQueryParams != null
					&& !listOfOnlyQueryParams.containsAll(listOfAllParams)) {
				listOfAllParams.removeAll(listOfOnlyQueryParams);
				for (String value : listOfAllParams) {
					builder.add(key,
							new HttpEntity<>(value, newHttpHeaders(request, key)));
				}
			}
```
This is the `extractFromMultipartRequest` method in the `RequestContentDataExtractor` class, `listOfOnlyQueryParams` does not have a `URLDecoder`。

**Comment by OlgaMaciaszek** [comment]
Hello @jackding79 there does not seem to be `extractFromMultipartRequest` method or `RequestContentDataExtractor` class in the source code of Spring Cloud Netflix project for any versions currently under OSS maintenance. If you think this isn't accurate, please past a permalink to the method in the GitHub repository.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
