### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by breun** [spring-cloud/spring-cloud-netflix#4293]
On https://spring.io/projects/spring-cloud-netflix#learn there are some broken links:

* 4.1.3 links to https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/, which shows the documentation for version 4.0.4.
* 4.1.4-SNAPSHOT links to https://docs.spring.io/spring-cloud-netflix/docs/4.1.4-SNAPSHOT/reference/html/, which returns 404 Not Found.
* 4.0.6-SNAPSHOT links to https://docs.spring.io/spring-cloud-netflix/docs/4.0.6-SNAPSHOT/reference/html/, which returns 404 Not Found.
* 4.0.5 links to https://docs.spring.io/spring-cloud-netflix/docs/4.0.5/reference/html/, which returns 404 Not Found.

The link format for 4.1.x seems to be https://docs.spring.io/spring-cloud-netflix/reference/${version}, because these work:

* 4.1.3: https://docs.spring.io/spring-cloud-netflix/reference/4.1.3
* 4.1.4-SNAPSHOT: https://docs.spring.io/spring-cloud-netflix/reference/4.1.4-SNAPSHOT

I don't know what the correct links are for the 4.0.x versions.

**Comment by fa11enangel** [comment]
I've checked the documention. Not only links are broken, but the documentation is using outdated content:

There are not annotations anymore `@EnableEurekaClient` to enable service. See issue #4029

This URL is using wrong version: https://spring.io/projects/spring-cloud-netflix#overview
This URL has an updated version without annotations: https://cloud.spring.io/spring-cloud-netflix/reference/html/#netflix-eureka-client-starter

This is the current content version in this project: https://github.com/spring-cloud/spring-cloud-netflix/blob/main/docs/src/main/asciidoc/sagan-index.adoc

**Comment by OlgaMaciaszek** [comment]
Thanks @breun, @fa11enangel. We've been changing the way our docs are generated and the site content is created and possibly things got mixed up. Will straighten it up.

**Comment by OlgaMaciaszek** [comment]
Fixed.

**Comment by fa11enangel** [comment]
@OlgaMaciaszek if you check this URL https://spring.io/projects/spring-cloud-netflix#overview you see, that the example uses annotation `@EnableEurekaClient` to inject eureka client functionality in the Application class.

But this annonation `@EnableEurekaClient` was removed and doesn't exist anymore. You did the change in https://github.com/spring-cloud/spring-cloud-netflix/issues/4029 . 

Should I open a new bug for this?

**Comment by fa11enangel** [comment]
There is another mention in the description above example: 

> As long as Spring Cloud Netflix and Eureka Core are on the classpath any Spring Boot application with @EnableEurekaClient will try to contact a Eureka server
