### ISSUE TITLE
Incorrect Default Values in Eureka Appendix Documentation

### ISSUE THREAD

**Issue by 555cider** [spring-cloud/spring-cloud-netflix#4294]
I've discovered incorrect default values in the Eureka's [Common application properties](https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/appendix.html) documentation.

The documentation file is located at "docs/modules/ROOT/partials/_configprops.adoc". I've attached a corrected version of the file(
[_configprops.adoc.txt](https://github.com/user-attachments/files/16334889/_configprops.adoc.txt)) saved as .txt for uploading.

The corrected items are as follows:

| Name                                                        | Default (before) | Default (after) |
| ----------------------------------------------------------- | ---------------- | --------------- |
| eureka.client.eureka-service-url-poll-interval-seconds      | 0                | 300             |
| eureka.server.a-s-g-update-interval-ms                      | 0                | 300000          |
| eureka.server.a-s-g-cache-expiry-timeout-ms                 | 0                | 600000          |
| eureka.server.e-i-p-binding-retry-interval-ms               | 0                | 300000          |
| eureka.server.e-i-p-binding-retry-interval-ms-when-unbound  | 0                | 60000           |
| eureka.server.renewal-threshold-update-interval-ms          | 0                | 900000          |
| eureka.server.response-cache-update-interval-ms             | 0                | 30000           |
| eureka.server.route53-binding-retry-interval-ms             | 0                | 300000          |
| eureka.server.retention-time-in-m-s-in-delta-queue          | 0                | 180000          |
| eureka.server.delta-retention-timer-interval-in-ms          | 0                | 30000           |
| eureka.server.wait-time-in-ms-when-sync-empty               | 0                | 300000          |
| eureka.client.rest-template-timeout.connect-timeout         | 0                | 180000          |
| eureka.client.rest-template-timeout.connect-request-timeout | 0                | 180000          |
| eureka.client.rest-template-timeout.socket-timeout          | 0                | 180000          |
| eureka.client.rest-template-timeout.idle-timeout            | (absent)         | 1800000         |
| eureka.instance.secure-port-enabled                         | false            | null            |

`eureka.client.rest-template-timeout.idle-timeout` is missing from the original documentation. A description for this property is "Indicates how long a connection can be idle before it is evicted from the connection pool." The behavior of `eureka.instance.secure-port-enabled` set to null is unclear. In the declaration, it's not initialized with false.

**Comment by OlgaMaciaszek** [comment]
Hello @555cider, thanks for reporting the issue. The values in the docs are, in fact, incorrect. Would you like to create a Pull Request with your changes?

**Comment by OlgaMaciaszek** [comment]
Fixed.
