### ISSUE TITLE
When the Client does not have an application.properties file, Server Eureka does not recognize the default name

### ISSUE THREAD

**Issue by 7zism3** [spring-cloud/spring-cloud-netflix#4298]
I am setting up Eureka for the first time: I have 2 Clients registered with 1 Eureka server.
2 Clients only use the application.yml file, and do not use the configuration

```
eureka:
  instance:
    appname: xxx
```
Now the Eureka Server recognizes 2 Clients with the same name.
![image](https://github.com/user-attachments/assets/1d660377-b158-45cc-95d1-fcf842d00532)
![image](https://github.com/user-attachments/assets/cb1b771a-bcd4-4ba8-a48d-fd4a44466bc1)

If I add an empty application.properties file, Now the Eureka Server recognizes 2 Clients with different names, which are the names I declared in the application.yml file 

```
spring:
  application:
    name: xxx
```
![image](https://github.com/user-attachments/assets/41b30a17-28f0-43f5-9bbe-15c3e775779b)
![image](https://github.com/user-attachments/assets/f47b5eba-7b69-4ee8-a968-5855af42340c)

Please see the attached image for more information

I'm working around this by adding an empty application.properties file. But it's not pretty.

**Comment by OlgaMaciaszek** [comment]
Hello @7zism3, thanks for reporting the issue. Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
