### ISSUE TITLE
Maybe it's time to update the documentation?

### ISSUE THREAD

**Issue by yjrguxing** [spring-cloud/spring-cloud-netflix#4302]
When I tried to learn Eurake by reading the [documentation](https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/), I realized that a large portion of the documentation was outdated.

For example as When I want to build a Eurake server by referring to the documentation
`new SpringApplicationBuilder(Application.class).web(true).run(args)`

.web() parameters have been updated from boolean to WebApplicationType

This got me stuck at the first step of learning Eurake through the official documentation, so I had to learn it through other tutorial articles or videos

**Comment by OlgaMaciaszek** [comment]
Hi @yjrguxing, thanks for reporting the issue. I'll fix the thing you've pointed out. If you see any other incorrect information in the docs, please create an issue and we will fix it.
