### ISSUE TITLE
spring boot 3.3.2  missing servo metrics with jmx_prometheus_javaagent

### ISSUE THREAD

**Issue by huntkalio** [spring-cloud/spring-cloud-netflix#4303]
I use spring-cloud-netflix for eureka server，and  use jmx_prometheus_javaagent to get metric from JMX。
A）：spring boot 2.7.18  +  netflix-eureka-server-3.1.7
B）：spring boot 3.3.2  +  netflix-eureka-server-4.1.3

In A I can get many metric like： com_netflix_servo_localRegistrySize_value （from eurekaserver servo）；but in B there is nothing 。How can I get servo metrics after I upgrade spring boot version？

**Comment by huntkalio** [comment]
in A MBeans:
![A](https://github.com/user-attachments/assets/1e61e391-e7a5-4523-84ff-efe0588f6c69)


in B MBeans:

![B](https://github.com/user-attachments/assets/6b25713b-370d-4f82-875f-741cbf07ad1c)

**Comment by huntkalio** [comment]
I found spring-cloud-netflix 3.x use eureka 2.x which replace servo with spectator.Then I change to use spectator-reg-micrometer with micrometer-registry-prometheus in eurekaserver.

**Comment by OlgaMaciaszek** [comment]
These seems to refer to internal changes in https://github.com/Netflix projects and not something that Spring Cloud Netflix has reconfigured. Please inquire in that org about it.
