### ISSUE TITLE
Is Feign logging level property broken?

### ISSUE THREAD

**Issue by mkurutin** [spring-cloud/spring-cloud-netflix#431]
hi,
I'm trying to enable DEBUG level logs of Feign using this property:
`logging.level.feign=DEBUG`
It doesn't work though because of this code inside `FeignClientFactoryBean.java`:
```
protected <T> T loadBalance(Feign.Builder builder, Class<T> type, String schemeName) {
		builder.logger(new Slf4jLogger(type)); // TODO: how to have choice here?
		if (this.ribbonClient != null) {
			return builder.client(this.ribbonClient).target(type, schemeName);
		}
		else {
			return builder.target(LoadBalancingTarget.create(type, schemeName));
		}
	}
```
The first line of the method above changes the logger name to the name of a Feign client class. Right now I have to do something like `logging.level.feign.com.mycompany=DEBUG` to enable Feign logs.

Is it expected behavior?

**Comment by spencergibb** [comment]
Yes.  Are you seeing a specific problem? or is it just a lack of documentation?

**Comment by mkurutin** [comment]
I think I expected that `logging.level.feign=DEBUG` will work, as this is something consistent with the logging documentation you have. I didn't expect that to enable Feign framework logs I would need to specify a package name where the Feign client interface is located in my application.

**Comment by mkurutin** [comment]
I other words I would assume this implementation instead:
```
protected <T> T loadBalance(Feign.Builder builder, Class<T> type, String schemeName) {
        builder.logger(this.logger); // <------ the difference
        if (this.ribbonClient != null) {
            return builder.client(this.ribbonClient).target(type, schemeName);
        }
        else {
            return builder.target(LoadBalancingTarget.create(type, schemeName));
        }
    }
```

**Comment by spencergibb** [comment]
Ah, I see the confusion.  Usually when you create a logger for a class, you create it with the fully qualified class, so `com.mycompany.MyFeignInterface`.  That way you can tune logging at each logger level, ie (`com.mycompany` or `com.mycompany.MyFeignInterface`).  If we made the change you suggest, there would be no customizability.  #288 will support customizing each feign build similar to how we can with ribbon.  Why is `logging.level.com.mycompany=DEBUG` not ok?

**Comment by mkurutin** [comment]
Sure, I see your point of having a feature that allows to customize logging for each individual client. 
The only issue with `logging.level.com.mycompany=DEBUG` is that it works only if load balancing is enabled. If the client chooses not to configure client side load balancing, this feature doesn't work and `logging.level.feign=DEBUG` works instead. See the method above in the same class:
```
	protected Feign.Builder feign() {
		Feign.Builder builder = Feign.builder()
				// required values
				.logger(this.logger).encoder(this.encoder).decoder(this.decoder)
				.contract(this.contract);

		// optional values
		if (this.logLevel != null) {
			builder.logLevel(this.logLevel);
		}
...
```

My suggestion would be to have these two options working at the same time:
`logging.level.feign=DEBUG`
`logging.level.feign.com.mycompany.sensative.client=ERROR`

**Comment by mkurutin** [comment]
Sorry, didn't mean to close the issue.
