### ISSUE TITLE
Exception in thread "pool-3-thread-1" com.netflix.hystrix.exception.HystrixRuntimeException failed and no fallback available.

### ISSUE THREAD

**Issue by cunhaDev** [spring-cloud/spring-cloud-netflix#4322]

**Comment by spencergibb** [comment]
hystrix is no longer supported.

**Comment by OlgaMaciaszek** [comment]
Hello @cunhaDev, Spring Cloud Netflix Hystrix has been out of support for many years now, so it seems that either you're using an unsupported version or you're using Hystrix project directly (not with Spring Cloud) and that is maintained in a separate repo: https://github.com/Netflix/Hystrix. Please note that for any team to take a look at a bug, more details will be needed, including steps to reproduce, what you expected to happen and what actually happens, the entire stacktrace and, in most cases,  a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.
