### ISSUE TITLE
Eureka Server - Jersey filter put Spring Security Filter Chain with custom auto-configured security.

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-netflix#433]
The problem is as stated in the subject, the details are outlined here: http://stackoverflow.com/questions/31197290.

A sample repo reproducing the problem is located here: https://github.com/steve-oakey/eureka-security-example

The result is when I apply custom security via an externally auto-configured module, the filter order applied leaves the /eureka endpoint un-secured.

I mentioned that I am not sure where the problem is (Spring Boot or Eureka Server configuration), but I was hoping to get some ideas on how to fix. I am unsure how to debug from here and am willing to provide whatever information you need to assist. Thanks.

**Comment by jebeaudet** [comment]
I was having the same issue, I posted an answer on the SO thread, hope it'll solve your problem.

**Comment by spencergibb** [comment]
@steve-oakey does the SO answer fix your problem?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
