### ISSUE TITLE
Missing additional metadata for eureka.client.jersey.enabled

### ISSUE THREAD

**Issue by ZIRAKrezovic** [spring-cloud/spring-cloud-netflix#4342]
**Describe the bug**

I have dug out `eureka.client.jersey.enabled` config option to disable the long-standing Jersey conflict, by looking at https://github.com/spring-cloud/spring-cloud-netflix/blob/4.1.x/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/config/DiscoveryClientOptionalArgsConfiguration.java#L200

It would be nice if it was documented in https://github.com/spring-cloud/spring-cloud-netflix/blob/4.1.x/spring-cloud-netflix-eureka-client/src/main/resources/META-INF/additional-spring-configuration-metadata.json so IDEs like IntelliJ IDEA could suggest it while looking them up. Entry for config option from the same file, `eureka.client.webclient.enabled` exists.

![{4F0FDCB8-2E52-4C06-A70A-F60BCFAC5F5C}](https://github.com/user-attachments/assets/f16a4490-fc54-451c-bcfb-8c41888742a1)

![{8BC0D48E-BA62-47C4-A13D-BBB2425E1B26}](https://github.com/user-attachments/assets/11f1f28c-e355-4384-b390-3a7229bbd526)

**Comment by OlgaMaciaszek** [comment]
Right @ZIRAKrezovic, will add it.
