### ISSUE TITLE
Update feign version to 8.6.0 to support interface hierarchies

### ISSUE THREAD

**Issue by jmnarloch** [spring-cloud/spring-cloud-netflix#436]
What's is your opinion on enabling in Feign possibility to scan base interfaces for declared client methods?

Possible use case would be to have for instance some kind of base client contract for instance:
```
interface CrudClient {

  @RequestMapping(method = RequestMethod.POST, value = "/")
  void save()

  @RequestMapping(method = RequestMethod.PUT, value = "/")
  void update()

  ...
}
```

Thanks to that it would be possible to aggregate the common client methods in base interfaces and afterwards "re-use" them in concreate clients.

I'd already made a bit of research in this area and I know that the type ispection is being done in feign-core by ReflectiveFeign, although I'm willing to prepare the push request that would introduce support for this feature.

**Comment by spencergibb** [comment]
This is a feature that just landed in feign a few hours ago: https://github.com/Netflix/feign/pull/246

**Comment by jmnarloch** [comment]
It turns out that @adriancole already had done all the hard work to support this :) https://github.com/Netflix/feign/pull/246

@spencergibb What do you think about updating feign version to 8.6.0?

**Comment by jmnarloch** [comment]
Pull request on the way: https://github.com/spring-cloud/spring-cloud-netflix/pull/437

**Comment by jmnarloch** [comment]
Pull request has been merged so from now on it's possible to have inherited interfaces as a feign clients
