### ISSUE TITLE
How can i use Spring @Around on @FeignClient?

### ISSUE THREAD

**Issue by ozakilsc** [spring-cloud/spring-cloud-netflix#439]
hi, everybody, i have a interface like this:

```
@FeignClient
public interface CloudApi { }

public interface AliyunEcsApi extends CloudApi {
    @RequestLine("GET")
    ListRegionsResponse listRegions(final ListRegionsRequest listRegionsRequest);
}
```

and i wanna use Spring pointcut to do some business things before and after invoke feignClient method, so i use `@Around` to deal with this:

```
@Around("execution(public * clouds.apis.CloudApi+.*(..))")
    public Response doAround(ProceedingJoinPoint pjp) {
  ......codes here....
}
```

but it didnt work.
any ideas? or i got a wrong use?

**Comment by spencergibb** [comment]
I don't think you can because spring-cloud-netflix is already creating a proxy from your `CloudApi` interface.  It might help if you describe what you are trying to do as there are other ways to customize feign.

**Comment by dsyer** [comment]
The reason that doesn't work is simpler I think: there are no methods in the `CloudApi` interface. Does it work if you explicitly use the child class in the pointcut?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
