### ISSUE TITLE
Zuul proxy should not redirect to itself (if it is a registered service)

### ISSUE THREAD

**Issue by bsideup** [spring-cloud/spring-cloud-netflix#447]
With default settings zuul will register itself in Eureka, and it allows user to query zuul service, which means that following 1 query will generate N queries, where N is the number of "/zuul/" occurrences:

"http://zuul.corp.com/zuul/zuul/zuul/zuul/zuul/zuul/zuul/[/zuul...]/foo-service/hello"

In theory it could cause huge load on Zuul instance

Workaround:
Disable Zuul service registration in Eureka:
```yml
eureka:
  client:
    registerWithEureka: false
```

**Comment by dsyer** [comment]
A better workaround is to add "zuul" (or whatever the local service name is) to the list of ignored services:

```
zuul:
  ignoredServices: zuul
```

**Comment by dsyer** [comment]
Actually isn't it a bad idea to use "zuul" as a service id anyway (that's the location of the multipart endpoint http://projects.spring.io/spring-cloud/spring-cloud.html#_uploading_files_through_zuul)? What actually happens that you don't like?

**Comment by bsideup** [comment]
@dsyer as I said, such requests are recursive, and if someone bad will send requests with many "/zuul/zuul/" entries in URL it will create performance issue (for each http request it will send N requests where N is the number of "/zuul/" entries)

**Comment by dsyer** [comment]
Well it sounds like a pretty crazy thing to do (construct a uri with N path elements the same, just to see what it will do).

**Comment by bsideup** [comment]
@dsyer since Zuul is supposed to be opened for external world (for public APIs for example) it sounds like a performance hole, because anyone from outside could send such request with a lot of "/zuul/zuul/zuul/zuul" in URL.

**Comment by dsyer** [comment]
Why is that any worse than someone sending a request for /foo several times?

**Comment by bsideup** [comment]
@dsyer for DDoS you have to create a huge network of bots who will send this request. With this "feature" it's much easier to attack Zuul - you're just sending 1(!!!) request, and it's converted to hundreds recursive requests.

**Comment by haripalpatil** [comment]
Hi @spencergibb can we use have ZUUL and my other service in single JAR? so that my ZUUL and service run in same container.
