### ISSUE TITLE
Zuul and UI Services

### ISSUE THREAD

**Issue by ccit-spence** [spring-cloud/spring-cloud-netflix#449]
What is the best practice for UI services with Zuul.  One approach I have seen is adding some UI functionality to Zuul itself essentially providing a page with links to the other UI services.  

The problem with this approach is that you end up with a UI and Zuul within the same application.  While this may not seem to be a big deal, it does create a scenario where a simple UI change now means you need to take the Zuul instances down to add the changes.

That being said, what is the accepted approach for Zuul only being the gateway and all UI being handled by UI services?

Do you add a simple controller with a forward to the "/" UI Index service?  Can this be handled only within yaml / properties?

**Comment by spencergibb** [comment]
@ccit-spence Not sure there is a best practice.  You can put a UI in the same process as zuul or not.

`zuul.routes.myservice=/**` works for forwarding everything to `myservice`.  I've done it a number of times ([here](https://github.com/spencergibb/oscon2015/blob/master/zuul/src/main/resources/application.properties) and [here, multiple ui's fronted by zuul](https://github.com/spencergibb/myfeed)).

**Comment by ccit-spence** [comment]
@spencergibb Thanks for the quick response and the examples.
