### ISSUE TITLE
Secured Config Server in a Eureka First Bootstrap setup

### ISSUE THREAD

**Issue by ssljivic** [spring-cloud/spring-cloud-netflix#450]
Hi,

I am trying to setup Eureka First Bootstrap scenario, where my service gets the location of Config Server from Eureka server.

Config Server is configured to use HTTPS. However, when my service tries to read configuration file from config server, it is trying to access it over HTTP.

**Comment by ssljivic** [comment]
I resolved the issue by setting the full URL:

eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eurekahostname}:8443


However, this will not wok if dynamic port is used for config server. Placeholder ${eurekahostname} is replaced by Eureka client, but it looks like there is no such placeholder for port.

Any idea how to resolve this?

**Comment by dsyer** [comment]
f98a7d5bc585 should fix it in 1.0.x. I'll work on porting to master as well (merge will be hard).
