### ISSUE TITLE
Zuul: Resources not found (css, js, etc.) when trailing slash is missing

### ISSUE THREAD

**Issue by kaszuster** [spring-cloud/spring-cloud-netflix#454]
Hi everyone,

i'm am quite new to spring-cloud so maybe i have just overseen something.

My problem is, that when i call Zuul and redirect that request ("http://localhost:8080/search/") to an Angular App, everything works just fine. But when i change the call to "http://localhost:8080/search" (no trailing slash), no resources are found. 

The resources in the delivered HTML are references by something like "<script src="/js/app.js"></script>". 

I can't route all "/js" requests to a specific service, because all services have their own "/js/app.js".

I checked the "spring-security-angular-master/double" sample project and the same thing happens there too.

Any ideas how to change this behavior?

Thank you in advance,
Kamil

**Comment by ccit-spence** [comment]
@dsyer Isn't this a variation of the same problem I was having with the UI services?

**Comment by dsyer** [comment]
Sort of related I guess. Is it actually the same problem in fact and you just didn't notice the 302? Maybe the UI is actually not being loaded through Zuul at all (did you follow the HTTP traffic and see a 302 with an out of band URL for the home page?).

**Comment by kaszuster** [comment]
I don't have any 302, there are only 404. The request seems to be routed by Zuul because the log is printing:

**Request without trailing slash:** app.js is not requested at all.
```
2015-07-25 09:43:39.019  INFO 6632 --- [nio-8080-exec-9] o.s.c.n.zuul.filters.ProxyRouteLocator   : Finding route for path: /search
```
**Request with trailing slash:** app.js is requested and returned.
```
2015-07-25 09:43:54.187  INFO 6632 --- [nio-8080-exec-3] o.s.c.n.zuul.filters.ProxyRouteLocator   : Finding route for path: /search/
2015-07-25 09:43:54.287  INFO 6632 --- [nio-8080-exec-9] o.s.c.n.zuul.filters.ProxyRouteLocator   : Finding route for path: /search/app.css
```

Here is what i actually see in both cases:
![withoutslash](https://cloud.githubusercontent.com/assets/5543516/8888579/9047d21a-32b3-11e5-9541-768200cbddc2.PNG)
![withslash](https://cloud.githubusercontent.com/assets/5543516/8888580/9048bf68-32b3-11e5-9cc2-304fc05d3f79.PNG)

This is my zuul config, maybe this might help too:
```
zuul:
  ignoredServices: "*"
  routes:
    root_call:
      path: /
      serviceId: authentication
    authentication:
      path: /authentication/**
      serviceId: authentication
    search:
      path: /search/**
      serviceId: search
```

**Comment by dsyer** [comment]
That's actually kind of the opposite problem @ccit-spence has. You probably could fix it by changing the static resource URL paths in your home page?

I guess the proxy could be configured to send a 302 to "search/" as well, so you don't need to do that. That would be a new feature, and might solve @ccit-spence's problem too.

**Comment by kaszuster** [comment]
Changing the static resources path to something like "/search/app.css" solves the problem. Anyway, for  me this isn't a real fix, its more like a workaround. 

I wanted to hand the services (search, authentication, etc) to independent teams. I wanted them to start the app and work on it without the need of running the Zuul and Eureka instances. By changing the paths to something Zuul or service related i am no longer able to do that, because the service will not be able to find  e.g. "localhost:9193/search/app.css" (direct call to service) because it only know "localhost:9193/app.css".

Maybe i can run the service with "server.contextPath=/search" and configure Zuul not to strip prefixes. But still, feels much more like a hack than a solution :) 

Any other ideas?

**Comment by ccit-spence** [comment]
@kaszuster not really a solution for the problem. What I like to do for others to work on things is to have a set of docker containers for Zuul, Eureka, RabbitMQ, Redis etc that can be easily launched so that things are operational and they can do it from their machine.  You do end up needing to utilize profiles heavily to point things in the right direction.

**Comment by dsyer** [comment]
@kaszuster did you try that trick with the context path? It should work (if you tell zuul not to strip the path prefix). I thought that maybe just setting a base URL in the HTML would work too?

@ccit-spence I don't really know what you mean. If you have a proposal for a fix that works for you why not send a pull request?

**Comment by dsyer** [comment]
I just had a play with this app from my blog: https://github.com/dsyer/spring-security-angular/tree/master/double. It has a UI (actually 2) behind Zuul, and it works fine as long as the user just clicks on links. That's the same as your app @ccit-spence in some ways, but I don't get that weird 302 if I remove the trailing slash, I just get the wrong static resources (like @kaszuster). But it does work with the trailing slash, which isn't consistent with @kaszuster's experience as I understood it - can you spot the difference?

**Comment by kaszuster** [comment]
@dsyer didn't try the trick, yet, but i also didn't think about the base tag ... at the first glace it looks much easier to me :) tanks!

@dsyer No, you got me wrong :), its the way you explained it right now. Adding the trailing slash to all requests works just fine, no Problems at all. Same if the user uses links that are provided, because than i can make sure that all links have a trailing slash. The problem arises as soon as the uses calls a services **without** the trailing slash, just like in your example. 

You can argue that this is no big deal "just add trailing slashes to all links". But when you have a Zuul setup like the following:
```
zuul:
  ignoredServices: "*"
  routes:
    empty_calls:
      path: /
      serviceId: authentication
```
Calls to "localhost:8080" will never return the correct static resources. 

I also don't want to explain why a user has to add a trailing slash to all requests, because otherwise the webapp isn't working, i want it to be bulletproof :)

**Comment by dsyer** [comment]
How come @ccit-spence sees a 302 and we don't? Irrespective of that, for both of you simply sending a 302 to `/search/` from `/search` would solve the problem?

**Comment by kaszuster** [comment]
Did not see any 302 so far. 

I think it would, but i can't make sure, at least i do not know how to :). 

Wonder how calls to "localhost:8080" that are routed to a service (like the one in posted before) would be affected. But then again, i could point base to "localhost:8080/authentication/".

**Comment by ccit-spence** [comment]
@dsyer @kaszuster I will do some more testing tonight around the 302 and see what is different within my setup.

@dsyer The mention of the docker setup is just a workflow for working sith Spring Cloud without registering to the primary services.  Using containers to spin up Eureka, Zuul etc for local testing.  @kaszuster  Mentioned part of the reason for the issue was trying to have other people work without registering.

**Comment by ccit-spence** [comment]
@kaszuster After some help with @dsyer which amounts to he figured it out.  The redirects are coming from Tomcat. 

Within the ui service if you set the `spring.context-path = /somepath` and then in the Controller set the `@RequestMapping({"/path","/path/")` this will stop the 302 redirects being initiated by Tomcat.

I also tried this and it worked in my case.  Instead of the above set `spring.servlet-path = /*`  This worked for me in a simple ui service.  It could cause other problems depending on the complexity of the service.

**Comment by kaszuster** [comment]
@ccit-spence Sorry for the very late reply but i was on vacation :) 
I did pull your changes an ran "uitest" but the problem i explained is not solved by that solution. 

Today i implemented a static filter, that simply returns a 302 and a Location header (original uri + trailing slash) when no trailing slash is found in the uri. Now my Zuul instance redirects calls  for "localhost:8080/search" to "localhost:8080/search/".  For my problem is works like a charm. Thx @dsyer for the hint you gave me earlier.

**Comment by dsyer** [comment]
You don't have to do that if tomcat is configured correctly. Look at the section in the Boot user guide on the `RemoteIpValve`.

**Comment by swclhard** [comment]
Hi Dave,

What exactly do you mean by "configured correctly"? 

I tried to configure it by configuring the proxy as:

<pre>
zuul:
  add-proxy-headers: true
</pre>

and ui as with 

<pre>
remote-ip-header: x-forwarded-host
</pre>

But it does not work. "localhost:8080/ui" gets still redirected to localhost:8081/ui.

Is there an example project with zuul that show how to use x-forwarded?

**Comment by dsyer** [comment]
Isn't it `server.tomcat.remoteIpHeader`? The Spring Boot user guide is pretty categorical on this (and with 1.3 it is on by default).

**Comment by swclhard** [comment]
No, it is an application.yml. So it should be:

<pre>
server:
  context-path: /ui
  port: 8081
  tomcat:
    remote-ip-header: x-forwarded-host
</pre>

I did some debugging. It seems that the redirect is done before involving any filters and remote-ip-header gets not evaluated. Is it possible that it is not working, because both services are running at localhost?

It would be great to see an example on how to configure and use x-forward with spring boot. Maybe someone can extend the double example - https://github.com/dsyer/spring-security-angular/tree/master/double - to show how it works.

My current workaround is to use some url rewriting by org.tuckey:urlrewritefilter at the proxy site:

```xml
<urlrewrite>
	<rule>
		<name>Trailing Slash Problem</name>
		<from>^/ui$</from>
		<to type="redirect">/ui/</to>
	</rule>
</urlrewrite>
```

http://localhost:8080/ui will be redirected to http://localhost:8080/ui/.

Thanks for your feedback!

**Comment by FireBushtree** [comment]
@kaszuster  Hi, kaszuster. I got the same problem, after zuul, my site redirect to a angular site, can you tell me how to implement the static filter like you?

**Comment by kaszuster** [comment]
@FireBushtree I am on vacation again :) will be back in about three weeks. I will update this answer once I return (and dindnt forget). Implementing a filter is not hard, you can find lots of tutorials. You have to check the requested URL, manipulate the response if needed (set status code 302 and set a redirect URL). The filter should be at the very beginning of the filterchain. You can do this :)

**Comment by FireBushtree** [comment]
Thx @kaszuster , i have implemented the filter after your tip :), why can you always have a vacation, i'm so jealous. Have a nice vacation!
