### ISSUE TITLE
My app registers twice (with diff hostnames) with eureka

### ISSUE THREAD

**Issue by aclement** [spring-cloud/spring-cloud-netflix#463]
I am using the fortune-teller sample, but with some edits. My eureka related config in my service app is a bit like this:

    eureka:
      instance:
        hostname: ${vcap.application.uris[0]:localhost}
      client:
        service-url:
          defaultZone: ${eureka_uri:http://localhost:8761}/eureka/

And then a manifest.yml:

    env:
        eureka_uri: http://eureka-ftasc.cfapps.io

I am finding my eureka shows two entries for my app when it starts - both the route I want (XXX.cfapps.io - vcap.application.uris[0]) and a route to the 'internal' name: (18rd7dvvacq). If it is up, you can see the problem here: http://eureka-ftasc.cfapps.io/

Dave thought it might be related to this change: https://github.com/spring-cloud/spring-cloud-netflix/commit/9149319bd73f228896d52b733894447170e4f26f

**Comment by dsyer** [comment]
I have a fix for this I think based on not refreshing the hostname if the user has explicitly set it in config. Does that make sense?

**Comment by spencergibb** [comment]
@dsyer that's I was planning on doing something similar.
