### ISSUE TITLE
Feign Retryer is not configurable and overlaps with the ribbon retry.

### ISSUE THREAD

**Issue by LutzStrobel** [spring-cloud/spring-cloud-netflix#467]
I have a consumer service calling an provider service which is running with 2 instances.
The provider interface

```
  @FeignClient("example")
  public interface ExampleService {
     @RequestMapping(
        method = {RequestMethod.POST},
        value = {"/greeting/{nameToGreat}"}
      )
     String greeting(@PathVariable(value = "nameToGreat") String nameToGreat);
```

The ribbon configuration within the consumer service is as follows:

```
example.ribbon.OkToRetryOnAllOperations=false
example.ribbon.ReadTimeout=3999
example.ribbon.MaxAutoRetries=0
example.ribbon.MaxAutoRetriesNextServer=3
```

If there is a SocketTimeoutException during a call to the example service, I would not expect that there a retry to the next instance occurs, because POST requests are not idempotent.
But the real behavior is that there retries to the next instance occurs which causes creation of duplicate accounts aso.

In a debugging session I could see that a correct RequestSpecificRetryHandler with the ribbon config values from above will be created and as far I could see the method isRetriableException(...) of that handler returns false.

What can I do to find a solution?
Thanx
Lutz

**Comment by LutzStrobel** [comment]
Now I found that the FeignClient uses the default retryer which retries the failed requests on its own. 
I think this is not desired, because it overrules the configuration for the ribbon loadbalancer.
Maybe this is not a feature, is it?
Lutz

**Comment by spencergibb** [comment]
Perhaps the default should be an empty `Retryer`.

As a workaround, you can create a `Retryer` bean in a Feign Client Configuration.

**Comment by padilo** [comment]
Workaround works like a charm:
```java
  @Bean
  public Retryer retryer() {
    return new Retryer() {

      @Override
      public void continueOrPropagate(RetryableException e) {
        throw e;
      }

      @Override
      public Retryer clone() {
        return this;
      }
    };
  }
```

**Comment by srowatt** [comment]
There's a NEVER_RETRY implementation so you can do 

`@Bean
public Retryer retryer() {
return Retryer.NEVER_RETRY;
}`

**Comment by ryanjbaxter** [comment]
We can close this issue because all this retry logic was simplified in the latest Camden SRs and and Dalston snapshots and there is only one level of retry now.

**Comment by Theknickerbocker** [comment]
Can you explain what you mean by 'there is only one level of retry now'?

**Comment by spencergibb** [comment]
We've eliminated the feign retry with our ribbon retry
