### ISSUE TITLE
eureka.instance.preferIpAddress=true giving loopback address

### ISSUE THREAD

**Issue by Shabin** [spring-cloud/spring-cloud-netflix#468]
Setting <code>eureka.instance.preferIpAddress=true</code> in <code>application.yml</code> is giving 127.0.0.1 as the ip address. I cannot modify the configurations in the /etc/hosts file as I don't have access. Is there any way to resolve this?

In [<code>EurekaInstanceConfigBean</code>](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBean.java) class I see that ip address is obtained using <code>InetAddress.getLocalHost().getHostAddress()</code>. Why is [<code>NetworkInterface</code>](http://docs.oracle.com/javase/8/docs/api/java/net/NetworkInterface.html) not used for getting ip address?

**Comment by spencergibb** [comment]
When I try it, I get my real IP address. We actually use `NetworkInterface` [in s-c-zookeeper](https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-discovery/src/main/java/org/springframework/cloud/zookeeper/discovery/ZookeeperServiceDiscovery.java#L135-L154).  It basically picks the first non-loopback ipv4 address.  Would that be sufficient?  What would happen when there are multiple interfaces? @dsyer comments?

**Comment by spencergibb** [comment]
@Shabin you can probably work around this by extending `EurekaInstanceConfigBean` yourself, for now.

**Comment by Shabin** [comment]
Thanks for the workaround @spencergibb. I extended <code>EurekaInstanceConfigBean</code> and used the <code>getIpAddress()</code> method in s-c-zookeper for fetching the ip. This works fine for me.

I think it would be better to replace <code>InetAddress.getLocalHost().getHostAddress()</code> in <code>EurekaInstanceConfigBean</code>. May be if the <code>InetAddress.getLocalHost().getHostAddress()</code> is returning loopback, go with <code>NetworkInterface</code> code. Though I am not sure about the multiple interfaces part.
