### ISSUE TITLE
Eureka Client dependency conflict Jersey 1.x / Jersey 2.x

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-netflix#470]
We have to add the spring-boot-starter-jersey to put Jersyey 2.14 on the classpath. The mix of both versions lead to strange NoSuchMethodErrors during application startup! The only solution seems to be to use JAX-RX 1.x (Jersey 1) . How to deal with that?

https://github.com/Netflix/eureka/issues/600#issuecomment-126602889

**Comment by spencergibb** [comment]
If netflix is not planning on doing anything, there's not much we can do.

**Comment by foo4u** [comment]
Not sure what the issue with upgrading to javax.ws.rs 2.0.1. Why stick with the very outdated javax.ws.rs:jsr311-api:1.1.1?

**Comment by spencergibb** [comment]
We don't control the dependency, it's a [Netflix/eureka](https://github.com/Netflix/eureka) issue. They don't plan on upgrading in the near term.

**Comment by spencergibb** [comment]
Now that I made my last comment, looks like things are changing! See [this comment](https://github.com/Netflix/eureka/issues/600#issuecomment-144471067)

**Comment by foo4u** [comment]
Hi @spencergibb yes, I asked them directly about this. Good news. Let's keep an eye for that to hit master. :+1:

**Comment by cforce** [comment]
Yes, hope it happens soon too

**Comment by spencergibb** [comment]
I'm going to close this. We track eureka changes regularly.
