### ISSUE TITLE
Zuul settings ignore profiles in application.yml

### ISSUE THREAD

**Issue by mkaberman** [spring-cloud/spring-cloud-netflix#471]
In my Zuul's  application.ymI I am using two profiles: one for ssl connection and one for regular one and observing very strange behavior.
My configuration is:

        info:
          component: Zuul Server     
        spring:
          application:
            name: distribmgt-proxy
          profiles:
            active: ssl
        ---
        spring:
          profiles: ssl
          
        server:
          port: 8765
          ssl:
            key-store: classpath:keystore.jks
            key-store-password: password   
            
        zuul: 
          routes:
            discovery-service: 
              path: /distribmgt/discovery/**
              url: https://localhost:9000/
              
        eureka:
          instance:
            securePortEnabled: true
          client:
            serviceUrl:
              defaultZone: https://localhost:8761/eureka/            

        ---
        spring:
          profiles: default
        server:
          port: 8765
          
        eureka:
          instance:
            securePortEnabled: false
          client:
            serviceUrl:
              defaultZone: http://localhost:8761/eureka/   
            
        zuul: 
           routes:
            discovery-service: /distribmgt/discovery/**
               
When I tried to execute request against the my service (curl -k -i -X GET https://localhost:8765/distribmgt/discovery) I got an error identical to one in  https://github.com/spring-cloud/spring-cloud-netflix/issues/459
I tried to switch the profiles (put default profile first ), but it did not help, I still got the error. Then I switched Zuul routing in default profile from serviceId to bogus url guaranteed not to exist

        ---
        spring:
          profiles: default
        server:
          port: 8765
          
        eureka:
          instance:
            securePortEnabled: false
          client:
            serviceUrl:
              defaultZone: http://localhost:8761/eureka/   
         zuul: 
           routes:
             discovery-service: 
               path: /bogus/**
               url: http://localhost:4711/

I got correct response to my request. It meant that after removing serviceId based route Zuul settings from the correct profiles were used.

So it seems that if two sets of Zuul settings defined in two profiles: one uses serviceId and one URL  Zuul always picks serviceId  based settings regardless of the active profile. It does not really matter in what order the profiles are defined.

**Comment by mkaberman** [comment]
Please disregard. Something is wrong with my configuration. I wrote a test app trying to reproduce the problem standalone and everything seems to be working.

**Comment by mrmarbles** [comment]
@mkaberman Can you provide some more details about what you may have found here?  I'm experiencing the same issue trying to deploy an application to heroku.

**Comment by mkaberman** [comment]
@mrmarbles The issue seems to be caused by profile's "ssl" name. I searched in both Spring Cloud Netflix and Spring Boot source and couldn't find "ssl" profile defined anywhere, but once I renamed my profile in Zuul's application.yml from "ssl" to "ssl_enabled" everything started working.
