### ISSUE TITLE
Huge Memory Usage

### ISSUE THREAD

**Issue by hrandika** [spring-cloud/spring-cloud-netflix#473]
After running the sample applications, I have found that it requires more than 512 MB of RAM per application, Is this normal usage? Even with  -Xmx64m the process at least take 256 MB. Any things that can be done to use less RAM?

**Comment by spencergibb** [comment]
Which sample applications? Not sure.  Remember that `-Xmx` limits _just_ the heap size, not all memory allocated to the jvm.

**Comment by hrandika** [comment]
I have compiled and ran thisauthserver application 
https://github.com/spring-cloud-samples/authserver
And it use more than 600Mb
https://drive.google.com/file/d/0ByhZnwP2MfZ7UHpGNmlybEJfNE0/view?usp=sharing

**Comment by spencergibb** [comment]
So that app doesn't depend on spring-cloud-netflix, can you make an issue in that repo and reference this issue?

**Comment by hrandika** [comment]
I have posted in that repo too.Mean while I have found this example
https://github.com/kbastani/spring-cloud-microservice-example/tree/master/movies-ui

it uses

spring-cloud-starter
spring-cloud-starter-feign
spring-cloud-starter-zuul
spring-cloud-starter-eureka

and when i compile and run it use 1.6GB
Screen shot :
https://drive.google.com/file/d/0ByhZnwP2MfZ7TXZhcVktTktZOHc/view?usp=sharing
Sorry If i posted in wrong place. Kind a new to collaborative work.
