### ISSUE TITLE
Expose ribbon request metadata in actuator

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#474]
Slightly different than #296
Keep track of at least the outgoing service calls.  E.g. service x called service y z times.
Inbound calls would be nice to, but currently no way of determining calling service (maybe add a header: X-Originating-Service-Id).
We could use and aggregate this metadata to produce the data for https://github.com/4finance/micro-infra-view live.
![screen shot micro-infra-view](https://cloud.githubusercontent.com/assets/594085/9073950/86f7d43c-3ac2-11e5-83d1-59c7ed983771.png)

**Comment by spencergibb** [comment]
Thanks to @joshlong for the conversation on twitter that led to this issue.

**Comment by dsyer** [comment]
Nice idea. I'd like to make it Ribbon agnostic so that the same metrics can be used to describe messaging interactions. Maybe just put some new metrics in /metrics (`counter.services.http.<id>.outgoing` maybe)?

**Comment by ghostd** [comment]
@spencergibb @dsyer what do you think about tracking the outgoing calls by:
- (solution 1) adding a ClientHttpRequestInterceptor . The implementation would be added into the RestTemplate interceptors in  LoadBalancerAutoConfiguration (in addition of LoadBalancerInterceptor).
- (solution 2) modifying the LoadBalancerInterceptor to record the metrics (by injecting a CounterService)
- other solution?
That would be ribbon agnostic.

By the way, the service id seems to be the URI.getHost() result, so we will need to encode the dots and the colons (dots for domain and IPv4, colons for IPv6) to not break the pattern `counter.services.http.<id>.outgoing`

I could provide a PR... let me know

**Comment by spencergibb** [comment]
I'd probably go with solution 2. @jkschneider provided updated metrics here: https://github.com/spring-cloud/spring-cloud-netflix/tree/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
