### ISSUE TITLE
Request parm with no value being stripped

### ISSUE THREAD

**Issue by kcbaltz** [spring-cloud/spring-cloud-netflix#476]
I have a CXF web service that I'm trying to put behind a Zuul proxy. The URL to request the WSDL looks like (/api/foo?wsdl). When I request it through Zuul, it fails and it appears to be because Zuul isn't passing the ?wsdl because it doesn't have a value (e.g. ?wsdl=bar). This is with Zuul 1.0.28, the one we get from spring-cloud-starter-zuul:1.0.2.RELEASE.

**Comment by kcbaltz** [comment]
I found the problem is in the Netflix Zuul code, specifically HTTPRequestUtils.getQueryParams(). I'll submit a patch to that project.  

Meta-question:  should I leave this open until this project is pointing at the patched version of Zuul?

**Comment by spencergibb** [comment]
yeah, link to your PR

**Comment by kcbaltz** [comment]
https://github.com/Netflix/zuul/pull/142

**Comment by spencergibb** [comment]
This will be fixed when with the next zuul release. See #592

**Comment by nedenom** [comment]
It seems the fix in PR Netflix/zuul#142 no longer works in zuul-core 1.1.0 release (only in earlier snapshots of it).

With regard to this issue:
spring-cloud-starter-zuul:1.0.4.RELEASE with zuul-core-1.0.28 works (seems not using this func. in zuul-core).
spring-cloud-starter-zuul:1.0.4.RELEASE with zuul-core 1.1.0 does NOT work 
spring-cloud-starter-zuul:1.1.0.M1 does NOT work with  zuul-core-1.1.0  or zuul-core-1.0.28

I have a 1.1.0-SNAPSHOT of zuul-core from 3 oct, which works on all spring-cloud-starter-zuul versions.

**Comment by spencergibb** [comment]
Fixed via 1090f2817aca6bcfaea714973e76637fb7415bb3
