### ISSUE TITLE
Ribbon 2.0 Http client vs Feign

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#481]
https://github.com/Netflix/ribbon/tree/master/ribbon

We already support ribbon 2.0.

Ribbon 2.0's supports a fluent builder style and and annotation declarative approach ala Feign.

Should we deprecate feign? It would simplify the number of netflix packages we support.

**Comment by spencergibb** [comment]
Wouldn't need #441 since we already have ribbon customization.

**Comment by spencergibb** [comment]
@adriancole @mstine @dsyer 
Maybe it's retrofit 2 instead: https://speakerdeck.com/jakewharton/simple-http-with-retrofit-2-droidcon-nyc-2015

* Multiple converters possible (proto, json, etc...) in a single client.
* Discreet request and response interactions
* Multiple pluggable execution mechanisms (synchronous, Callback, Observable, etc...)
* Multipart support
* Future websocket support (2.1)

Unknown
* Custom annotation handling.

**Comment by spencergibb** [comment]
Arg, retrofit doesn't have pluggable clients, only okhttp: https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit/Retrofit.java#L101

**Comment by adriancole** [comment]
@spencergibb not sure it if helps, but okhttp can now implement apache's client:
https://github.com/square/okhttp/blob/master/okhttp-apache/src/main/java/com/squareup/okhttp/apache/OkApacheClient.java

**Comment by spencergibb** [comment]
@adriancole is this worth keeping open for discussion? Or should we close it and track what the framework async client might look like?

**Comment by adriancole** [comment]
close

**Comment by kakawait** [comment]
@spencergibb What about original question: 

> Ribbon 2.0 Http client vs Feign?

When reading https://github.com/Netflix/ribbon/tree/master/ribbon it true that Ribbon has a similar high-level abstraction as Feign. So what are the advantages to use Feign over Ribbon (directly)?

**Comment by aivans** [comment]
The Netflix guys mentioned during their presentation (http://www.infoq.com/presentations/spring-cloud-netflix) that Feign is not popular and not really maintained at Netflix.

**Comment by spencergibb** [comment]
@kakawait @aivans we're continuing with feign. Pivotal employs the maintainer of Feign @adriancole, so it's not going away anytime soon. We like feign because of it's abstraction away from an implementation like Ribbon. There may be work in spring-framework 5 that might cause us to come back to this.

**Comment by aivans** [comment]
Thanks Spencer

**Comment by kakawait** [comment]
@spencergibb pretty awesome. We are starting migrating some part of monolitics app to microservices on top of Netflix OSS and Spring cloud and we are using Feign because we found it abstraction really pleasant and fit ours needs. So I can continue to use it if pivotal still support Feign.

**Comment by adriancole** [comment]
Popular is relative to something else.. like ex feign is less popular than
a lot of things, probably most things. Its release at all was an accident
of deployment of denominator. When at netflix, I'm pretty sure I never
presented feign or blogged about it. It was mostly selfish, as I didn't
want 5 issues/day on how to use eclipse.

I'm grateful to Netflix for their years of support of feign: that support
wasn't advertising or curating internal use. Netflix support has been
hiring awesome people. Ex @rspieldenner and @diannemarsh who help keep
Feign's build/release going without asking for anything in return.

Through the years, I've been surprised at interest. Ex. I found out from
@joshlong at a no-fluff conference one night that it was actually in
spring! Before, I thought feign in spring was a mad-scientist experiment
from @spencergibb <https://github.com/spencergibb> and @dsyer.

Long story long is.. I don't think zombie projects are helpful, if I
thought feign was unnaturally alive, I'd probably help kill it. Feign's
life has never been defined by statements from Netflix, and that'd be sort
of un-netflix anyway. As long as people still want it, I'm sane
(relatively), and the project remains simple, I'm happy to continue to help
with Feign.

**Comment by spencergibb** [comment]
@adriancole we hope you stay sane(ish) working at pivotal! Thanks for the great work.

**Comment by kakawait** [comment]
Thank you @adriancole for everything! I think yes Feign is certainly less popular than Hystrix, Eureka or other Netflix OSS project. But with new mouvances for microservices and even more thanks to @joshlong that offering us some live demo of Spring Cloud Netflix including Feign. Feign can become more popular, but it just speculations...

I'm happy to use Feign at the moment! I will continue to use it so.

Just one point to validate is performance comparaison between pure Ribbon and Feign. Feign may slower due to abstraction but if just few nanoseconds :)

**Comment by adriancole** [comment]
subtle pull request changed the nature of retrofit interop. So long as the http client (aka call factory) uses okhttp/okio types, it can be swapped out now https://github.com/square/retrofit/pull/1394

**Comment by spencergibb** [comment]
@adriancole that's nice. I'll play with it and see what it might look like.

**Comment by joshlong** [comment]
hurray i love that this is real (and working w/ Sleuth!) 

:+1: 

thanks @adriancole for sanely and super not-selfishly developing Feign. it's the gift that keeps on giving! 

& thanks @kakawait - glad you dig the demos and i hope you do demos for people you care about too! :-)

**Comment by piotrgwiazda** [comment]
2 years later Feign is discontinued and Ribbon is in maintenance mode. What next?

**Comment by navaare** [comment]
@piotrgwiazda goo.gl/z1ZFoD

**Comment by urig** [comment]
@piotrgwiazda Feign discontinued? Where do you get that from?

**Comment by spencergibb** [comment]
Feign is not discontinued. It is now openfeign and run by community members
