### ISSUE TITLE
Zuul support for Server Name Indication (SNI)?

### ISSUE THREAD

**Issue by ChrisCurtin** [spring-cloud/spring-cloud-netflix#482]
Hi,

I see #333 updated the HttpClient version, does this mean the SNI support should work automatically when this is released?

We want to have dozens/hundreds of https sessions connect to a Zuul instance, then route to services. However all these sessions are to custom domains and we'd like to have Zuul handle the 'termination'.

Thanks,

Chris

**Comment by spencergibb** [comment]
#333 was closed and not merged.

**Comment by ChrisCurtin** [comment]
Thanks Spencer. Is there a plan to revisit the issue? #332 is still open, and I thought #333 was the fix.

If not, am I correct in thinking that Zuul isn't intended to be the https termination point?

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
