### ISSUE TITLE
IncompatibleClassChangeError when depends on Spring IO Platform.

### ISSUE THREAD

**Issue by cero-t** [spring-cloud/spring-cloud-netflix#484]
Hi,
I tried to run Eureka server with Spring Application depends on Spring IO platform,
then I got `IncompatibleClassChangeError` when registering services to Eureka server.

### Errors

`curl http://localhost:8761/eureka/apps/` causes `java.lang.IncompatibleClassChangeError`.

Stacktrace:
```
java.lang.IncompatibleClassChangeError: Class javax.ws.rs.core.Response$Status does not implement the requested interface javax.ws.rs.core.Response$StatusType
	at com.sun.jersey.spi.container.ContainerResponse.getStatus(ContainerResponse.java:571)
	at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.commitWrite(ContainerResponse.java:156)
	at com.sun.jersey.spi.container.ContainerResponse$CommittingOutputStream.write(ContainerResponse.java:127)
...
```

### Sources

Complete error reproducing example is here.
https://github.com/cero-t/eureka-example
Run the EurekaApplication and `curl http://localhost:8761/eureka/apps/` reproduce the error.

My pom.xml looks like:
```
    <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR3</version>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.spring.platform</groupId>
                <artifactId>platform-bom</artifactId>
                <version>1.1.3.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka-server</artifactId>
        </dependency>
    </dependencies>
```

My source codes
```java
@SpringBootApplication
@EnableEurekaServer
public class EurekaApplication {
    public static void main(String[] args) {
        SpringApplication.run(EurekaApplication.class, args);
    }
}

```

### Workaround

I know removing dependencyManagement tag can fix the problem. Still I want to develop my applications with Spring IO Platform.
Is there any good solutions?
I wish Spring Cloud will be included in Spring IO Platform.

Thx.

**Comment by cero-t** [comment]
I found workaround.
With following pom.xml can work well.
```xml
    <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-parent</artifactId>
        <version>Angel.SR3</version>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.spring.platform</groupId>
                <artifactId>platform-bom</artifactId>
                <version>1.1.3.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>javax.ws.rs</groupId>
                <artifactId>jsr311-api</artifactId>
                <version>1.1.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

The error is due to the version of jsr311-api.
Spring Cloud uses  jsr311-api `1.1.1` but Spring IO Platform includes `1.0`.

Thanks.

**Comment by cero-t** [comment]
I found the cause of this issue.

In the dependencyManagement,
Spring IO platform (1.x and 2.x) specifies ```jsr311-api 1.0```
spring-cloud-netflix (1.0.3.RELEASE) specifies ```jersey-core 1.13```
and they are imcompatible.

eureka-client depends ```jsr311-api 1.1.1``` and ```jersey-core 1.11```
but these versions are ignored due to the dependencyManagement.

Then is it possible spring-cloud-netflix specifies the version of jsr311-api?

**Comment by spencergibb** [comment]
There is already an issue in https://github.com/spring-io/platform/issues/232.

**Comment by wilkinsona** [comment]
I've just logged and fixed https://github.com/spring-io/platform/issues/233 that updates Spring IO Platform 2.0 to provide dependency management for JAX-RS 2.0, rather than 1.x.

**Comment by wgorder** [comment]
thanks @wilkinsona

**Comment by cero-t** [comment]
Thank you very much!
And I understand the current situation and policy.

**Comment by spencergibb** [comment]
See [this comment](https://github.com/spring-io/platform/issues/232#issuecomment-130242944) for reasons why I'm closing this.
