### ISSUE TITLE
Hystrix Stream - Can we make this a real Actuator endpoint?

### ISSUE THREAD

**Issue by joshuawhite929** [spring-cloud/spring-cloud-netflix#487]
I hope this is the right place for this... can we please make the hystrix stream a real actuator endpoint (meaning that it gets served with the other actuator endpoints)?  In my opinion, it would make it easier to manage and more consistent if the stream could be managed along with the other actuator endpoints.  For example, the actuator endpoints can be backwards facing and over http whereas the app can be forward facing and forced over https.  I have a separate request to address independent http/ssl configuration for the two different embedded servlet container instances.  Really, I am just looking for the ability to have this stream come through the actuator endpoints, not from within my core app.

**Comment by spencergibb** [comment]
It was an endpoint, but changed because of #187.  Maybe we could make it an option?

**Comment by joshuawhite929** [comment]
I am not clear if there is already a dependency on actuator, but if not, you might need to make it an option to keep it that way.

**Comment by spencergibb** [comment]
Closing as this appears to be [implemented](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCircuitBreakerConfiguration.java#L77-L80)
