### ISSUE TITLE
Zuul SimpleHostRoutingFilter duplicates application/x-www-form-urlencoded content type

### ISSUE THREAD

**Issue by trina97** [spring-cloud/spring-cloud-netflix#488]
We're using @EnableZuulProxy without Eureka and we think we found a bug.  

SUMMARY:

In some cases, Zuul appears to be duplicating the value of the content-type header before forwarding the request to backend services.  This duplication leads to unexpected behavior when our backend service tries to process the request (e.g., http responses of 400 bad request when we are expecting 200).

DETAILS:

Consider the case where a post request has a header with key "Content-Type" (case matters) and value "application/x-www-form-urlencoded".
In this case, the FormBodyWrapperFilter pre-filter adds a zuulRequestHeader to the request context with key "content-type" and value equal to the content type in the HttpServletRequest. 
Then, the SimpleHostRoutingFilter runs and calls the buildZuulRequestHeaders method of its ProxyRequestHelper in order to build the headers to forward to the backend service. This method adds both the "Content-Type" header from the HttpServletRequest AND the "content-type" header from the request context's zuulRequestHeaders.

**Comment by malaporte** [comment]
It seems that this bug has been recently fixed, see this commit: https://github.com/spring-cloud/spring-cloud-netflix/commit/ad86d48c6a125a9ad19ca9795967a9cecfc4f1b5.

It now uses a case insensitive map for headers.
