### ISSUE TITLE
PermGen Memory leak while deploying spring-cloud-netflix application on standalone tomcat

### ISSUE THREAD

**Issue by AsimBiswal** [spring-cloud/spring-cloud-netflix#495]
Tomcat fail to stop thread named ServoMonitorGetValueLimiter. 
A thread called ServoMonitorGetValueLimiter started by the the application which is never stopped. This thread is started by MonitorRegistryMetricPoller of com.netflix.servo . In fact service is failed to stop the thread. The object of this class is a component in ServoMetricCollector of org.springframework.cloud.netflix.servo to exposes servo metrics to the metric endpoint.
When application is undeployed it is unable to unregister the MBean also (com.netflix.servo). Hence it holds the class loader in memory causing permgen memory leak.

Same issue had been raised in Netflix/feign/ forum (https://github.com/Netflix/feign/issues/257) but closed with by adriancole with comment "will look at this in spring-cloud"

**Comment by adriancole** [comment]
This sounds familiar.

**Comment by adriancole** [comment]
here's the issue with context about the leak. https://github.com/Netflix/feign/issues/257

**Comment by adriancole** [comment]
This seems to have been worked around in v1.0.1 via 384fad6c408af582fd18cafbe41f3a2a685a4ed1. @AsimBiswal what version of spring-cloud-netflix are you using?

**Comment by dsyer** [comment]
I think it was fixed in 1.0.1 via https://github.com/spring-cloud/spring-cloud-netflix/commit/71d0a474 (same question arises).

**Comment by dsyer** [comment]
No response after 1 month. Assume closeable.
