### ISSUE TITLE
Feign request parameters are duplicated

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#496]
From http://stackoverflow.com/questions/32098906/spring-cloud-feign-client-duplicate-list-values

I have this interface mapping my rest client using Spring cloud Feign.
```
@FeignClient(url = "http://localhost:8080")
public interface RestClient {

    @RequestMapping(value = "?ids={ids}", method = GET)
    List<Posicao> get(@RequestParam(value = "ids") List ids);
}
```
I have a list in my parameters, calling the client I have this request:
```
restClient.get(Arrays.asList(1, 2));
http://localhost:8080/ids=1,2,1,2
```

It's duplicating the list values!

**Comment by spencergibb** [comment]
The request mapping should be `@RequestMapping(value = "/", method = GET)`.

**Comment by Dreampie** [comment]
@spencergibb 
```java
@FeignClient(url = "http://localhost:8080")
public interface RestClient {

    @RequestMapping(value = "/", method = GET)
    List<Posicao> get(@RequestParam(value = "ids") Long[] ids);
}

```
I got `MethodArgumentTypeMismatchException` error

**Comment by dsyer** [comment]
Is it a `List` or a `Long[]` on the server (looks like a mismatch to me)?

**Comment by Dreampie** [comment]
yes,all mismatch, it is a bug?
