### ISSUE TITLE
ZuulConfiguration - ZuulHandlerMapping - common interceptors from WebMvcConfigurationSupport are not added to ZuulHandlerMapping

### ISSUE THREAD

**Issue by joshuawhite929** [spring-cloud/spring-cloud-netflix#497]
WebMvcConfigurationSupport adds a common list of interceptors to the various HandlerMapping classes (RequestMappingHandlerMapping, viewControllerHandlerMapping, BeanNameUrlHandlerMapping, resourceHandlerMapping).  This occurs before these various handlers are initialized as they are added to the context (initialization happens when the context is set).

The ZuulHandlerMapping is created within the ZuulConfiguration.  As a result, none of the interceptors that have been setup for spring mvc are applied to it.  When the ZuulConfiguration class returns this HandlerMapping as a bean, there is now way to add interceptors to it as it is already initialized (look at the initInterceptors() method).

In the current state, the only way to make this work seems to be to redefine this bean, adding interceptors to it before initialization is done when adding it to the context.

**Comment by spencergibb** [comment]
@joshuawhite929 sorry for the delay. What functionality is missing by not having the interceptors?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
