### ISSUE TITLE
Upgrade to zuul 2

### ISSUE THREAD

**Issue by efenderbosch** [spring-cloud/spring-cloud-netflix#499]
We can't use the current versions of Eureka and Zuul due to their dependence on Jersey. (Long story.) They are being re-written to use RxNetty.

Also are there plans to move spring ribbon to use the RxNetty client in ribbon-transport vs the deprecated ribbon-httpclient?

The 2.x timeframe is still up in the air, but wondering if this is on the radar.

**Comment by spencergibb** [comment]
See #181 for eureka.  We'll turn this issue into zuul 2.

**Comment by spencergibb** [comment]
This is a non-trivial change.

**Comment by spencergibb** [comment]
I'm going to go ahead and close this, when zuul 2 becomes a thing (released, GA, production), we'll start tracking it.
