### ISSUE TITLE
Inject a HealthCheckHandler into DiscoveryClient

### ISSUE THREAD

**Issue by abaculus** [spring-cloud/spring-cloud-netflix#50]
Hi

Trying to figure out how to use the `HealthCheckHandler` and `HealthCheckHandlerProvider` in `DiscoveryClient` with Spring Cloud Netflix and Eureka.

My service registered with Eureka Server is always UP even though my `/health` reports: `{"status":"DOWN"}` and HTTP 500.

Cannot find that there's any connection between them?

Thanks!

**Comment by cforce** [comment]
I think this is now native configurable by setting:
eureka:
  client:
    healthcheck:
      enabled: true
