### ISSUE TITLE
Zuul Load Shedding 

### ISSUE THREAD

**Issue by SandeepSyntel** [spring-cloud/spring-cloud-netflix#502]
Zuul documentation says "Load Shedding - allocating capacity for each type of request and dropping requests that go over the limit" 

Can anyone help me on how to configure Load Shedding options with spring cloud? I don't see any documentation of it anywhere not even on Netflix Zuul page.

**Comment by spencergibb** [comment]
Load shedding is something Netflix does with zuul, but did not open source their solution.

**Comment by andChow** [comment]
Is the feature open?
