### ISSUE TITLE
SSL Certificate is not verified always

### ISSUE THREAD

**Issue by navarrogabriela** [spring-cloud/spring-cloud-netflix#506]
It should be an option to validate or not a certificate .

Right now the spring-cloud-netflix allows all certificate even if they are valid or not.

This piece of code is doing it(spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java):

``` java
SSLSocketFactory sf = new MySSLSocketFactory(trustStore);
sf.setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
```

This behaviour for production environment is not good.

**Comment by navarrogabriela** [comment]
@spencergibb do you think it's a good thing to work on? I think we can take this option from the user via command line and get it using System.getProperties() method. If nothing is passed, we can use the ALLOW_ALL_HOSTNAME_VERIFIER. What do you think?

**Comment by spencergibb** [comment]
No, it should be available via either archaius (which can be populated via spring-boot properties) or normal spring-boot properties.

**Comment by navarrogabriela** [comment]
@spencergibb could you elaborate a little bit more? I'm starting to work with this project now. The reason I'm proposing this change is because my team uses spring-cloud-netflix and we noticed this issue with the SSL certificate. But I'm a little lost when you say that it should be via archaius(like, should I do the changes on that project?? what should I change here to make it work?). Where are these spring-boot properties listed? If you could tell me where I can find these informations will be helpful too :)

**Comment by spencergibb** [comment]
I'm saying to use [spring boot configuration properties](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) to add a new configuration item.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
