### ISSUE TITLE
Hystrix-dashboard not working correctly, if a context path is set

### ISSUE THREAD

**Issue by RobWin** [spring-cloud/spring-cloud-netflix#51]
the hystrix-dashboard index.html is not working correctly, if a context path is set, because the following src url is not considering the context path:

```
<script src="/webjars/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
```

Same for the hystrix-monitor-dashboard.

**Comment by kmandeville** [comment]
FYI I'm having a problem with the hystrix dashboard in my Spring Boot 1.2.3 app (using 1.0.1.RELEASE of hystrix dashboard. The page loads, but the Monitor Stream button doesn't actually do anything. If I open the javascript console I see the following error: 

[Error] ReferenceError: Can't find variable: $
	sendToMonitor (hystrix, line 14)
	onclick (hystrix, line 50)

If I go direct to the hystrix.stream url, I see data and it's consistently streaming. Just seems like a javascript issue... please help!

**Comment by dsyer** [comment]
Please can you open a new issue, rather than commenting on one that is already closed?
