### ISSUE TITLE
X-Forwarded-Proto is missing in zuul client requests

### ISSUE THREAD

**Issue by MichaelF25** [spring-cloud/spring-cloud-netflix#514]
When using `@EnableZuulProxy` inside a spring boot application which itself is secured via SSL to act as a reverse proxy for other spring boot applications which are not secured, the client HTTP requests from zuul are missing the `X-Forwarded-Proto: https` HTTP header.

The HTTP headers `X-Forwarded-Host` and `X-Forwarded-Prefix` are present and their content is correct.

**Comment by spencergibb** [comment]
Closed via #515
