### ISSUE TITLE
Servo - possibility to disable

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#518]
Hi,

It would be nice to specify whether Servo should be enabled or disabled.

Thanks

**Comment by aivans** [comment]
Maybe the solution code is already available:
https://github.com/spring-cloud/spring-cloud-netflix/pull/517

**Comment by jkschneider** [comment]
You can set a property to disable it (e.g. `spring.autoconfigure.exclude: org.springframework.cloud.netflix.servo.ServoMetricsAutoConfiguration` in application.yml) or refer to it in `@EnableAutoConfiguration(excludes=org.springframework.cloud.netflix.servo.ServoMetricsAutoConfiguration.class)`

**Comment by aivans** [comment]
Cool, thanks. 
I guess this can be closed if not other , more elegant, solution will be provided.

**Comment by jkschneider** [comment]
Also, can disable with `spring.metrics.servo.enabled=false`
