### ISSUE TITLE
Ribbon/Eureka - Use InstanceInfo instead of EurekaInstanceConfig(Bean)

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#523]
Components should rely on `InstanceInfo` to access instance details instead of `EurekaInstanceConfigBean` (or `EurekaInstanceConfig` from Netflix). The use of the config(bean) should be limited to the factory used to create the actual/resulting `InstanceInfo`.

Places where the config(bean) is used and could be replaced by `InstanceInfo`:
- `org.springframework.cloud.netflix.ribbon.eureka.EurekaRibbonClientConfiguration`
- `org.springframework.cloud.netflix.eureka.EurekaDiscoveryClient`
- `org.springframework.cloud.netflix.eureka.EurekaDiscovertClientConfiguration`
- `org.springframework.cloud.netflix.config.EurekaClientConfigServerAutoConfiguration`

**Comment by spencergibb** [comment]
@brenuart Why do you think it should be limited to `InstanceInfo`?

**Comment by brenuart** [comment]
The point was to refer to the interface and not the implementation everywhere an `InstanceInfo` is needed. That's just best practice and allows one to provide its own implementation.

As far as I can tell, some work is already ongoing in trunk, no?

**Comment by spencergibb** [comment]
So now we only reference interfaces rather than the bean. That is done. I'm still unsure why referencing `InstanceInfo` is a 'best practice'.

**Comment by spencergibb** [comment]
@brenuart why is referencing `InstanceInfo` is a 'best practice'?

**Comment by brenuart** [comment]
Sorry for the late answer.

As far as I remember, `InstanceInfoFactory` is responsible of creating an `InstanceInfo` out of a `InstanceInfoConfig`. With this in mind, it looks safer to use `InstanceInfo` instead of the original config or you are implicitly making assumptions about what the factory is actually doing.

Suppose I register my own factory to cleanup hostname and force it to lower case...

**Comment by spencergibb** [comment]
We've made it a point to have the extension point be `EurekaInstanceConfig`. `InstanceInfo` is just a transfer object. I'd put any logic in a `EurekaInstanceConfig` impl.

**Comment by brenuart** [comment]
Ok. What's the point in exposing `InstanceInfoFactory`? As I understand, nobody should ever provide his own implementation then?

**Comment by spencergibb** [comment]
Just because there's a bean doesn't mean it's for anyone to implement.

**Comment by brenuart** [comment]
Indeed - but how can we (_us simple and stupid users of the framework_) know what are the valid extension points?
You can safely close this issue. I just wanted to highlight the many pitfalls we fall into and eventually help to make a more user-friendly framework.

**Comment by spencergibb** [comment]
@brenuart I know you are a power user and super smart. The sarcasm doesn't help. The answer is documentation, which is one of our weak points.
