### ISSUE TITLE
spring-cloud-starter-eureka pulls commons-logging:1.2 as transitive dependency

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#525]
`spring-cloud-starter-eureka` pulls `commons-logging:commons-logging:1.2` as transitive dependency. Path to dependency is:

    spring-cloud-starter-eureka
    + eureka-client
      + archaius-core
        + commons-configuration
          + commons-logging

In a SpringBoot environment, `commons-logging` should be excluded and is replaced by `org.slf4j:jcl-over-slf4j` (included by default). 

Side question: `commons-configuration` pulls version 1.2 of `commons-logging` and `jcl-over-slf4j` is supposed to mimic version 1.1.1 - will it cause a problem?

**Comment by spencergibb** [comment]
@brenuart Looks like this is no longer a problem in Brixton.BUILD-SNAPSHOT. 

```
+- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.1.0.BUILD-SNAPSHOT:compile
|  +- com.netflix.eureka:eureka-client:jar:1.2.5:compile
|  |  +- com.netflix.archaius:archaius-core:jar:0.6.5:runtime
|  |  |  \- commons-configuration:commons-configuration:jar:1.8:runtime
```

**Comment by brenuart** [comment]
Sorry, but we still have the dependency even with the latest BUILD-SNAPSHOT.
`commons-configuration:commons-configuration` has an explicit dependency on `commons-logging:commons-logging` and I don't see anywhere in the latest code where that dependency would be excluded.

```
  \- org.springframework.cloud:spring-cloud-starter-eureka:jar:1.1.0.BUILD-SNAPSHOT:compile
     +- org.springframework.cloud:spring-cloud-netflix-core:jar:1.1.0.BUILD-SNAPSHOT:compile
     +- com.netflix.eureka:eureka-client:jar:1.2.5:compile
     |  +- com.netflix.archaius:archaius-core:jar:0.7.1:runtime
     |  |  \- commons-configuration:commons-configuration:jar:1.8:runtime
     |  |     \- commons-logging:commons-logging:jar:1.1.3:runtime
```

**Comment by spencergibb** [comment]
You'll need to provide a project because I can't reproduce it.

**Comment by brenuart** [comment]
Sample project: https://gist.github.com/brenuart/c15b0986dd230289f372

Execute `mvn validate` to produce the problem.

**Comment by spencergibb** [comment]
Thanks for the sample, I see where we were different.
