### ISSUE TITLE
EurekaServer - XML/Json marshalling initialized twice

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#526]
In `org.springframework.cloud.netflix.eureka.server.EurekaServerInitializerConfiguration.start()`:

    ...
    XmlXStream
        .getInstance()
        .setMarshallingStrategy(
	    new DataCenterAwareMarshallingStrategy());
    DataCenterAwareJacksonCodec.init();
    ...

This initialisation has already been done when building the Eureka *Client* (see `org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration.init()`). The Eureka server requires an eureka client instance. So it is guaranteed the initialization has already been done.

Although replicating this init code here doesn't harm, it makes the things harder to maintain and is error prone.

**Comment by spencergibb** [comment]
Closed via 8f9acab3bdbebfcf5687ec601904ee4f718ae25d
