### ISSUE TITLE
EurekaServer - blitz4j dependency included but not required

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#527]
`spring-cloud-starter-eureka-server` pulls `com.netflix.blitz4j:blitz4j` but none of the Netflix dependencies used by the Eureka Server require it.

Netflix Blitz4J is a logging framework built on top of Log4j and is not used directly by Netflix's code. Code is written against Slf4J instead. Blitz4 is therefore not (absolutely) required - not more than other logging framework like Log4J2 or Logback.

Proposition is to:
- remove the dependency to Blitz4J from the eureka server starter pom
- remove Blitz4J initialisation code from the Eureka bootstrap mechanism

Blitz4J support should go into another project/module and should not be imposed/tied to the Eureka Server.

**Comment by brenuart** [comment]
A comment in `spring-cloud-netflix` POM says:

     <DependencyManagement>
        ...
 			
			<dependency>
				<groupId>com.netflix.blitz4j</groupId>
				<artifactId>blitz4j</artifactId>
				<version>1.36.0</version>
			</dependency>
     ....
     </DependencyManagement>

The dependency is indeed optional in Netflix's code but still required by SpringCloud's Eureka server integration.

**Comment by spencergibb** [comment]
@dsyer what do you think?

**Comment by dsyer** [comment]
AFAI recall it was mandatory when we started, or at least strongly favoured by netflix. If it's optional there's no need for us to make it mandatory.
