### ISSUE TITLE
Feign - How to set up my own default configuration?

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-netflix#528]
Hi,

I like the Feign Spring Cloud support, but I'd like to provide custom default configuration (basically using JAX-RS contract and add a RequestInterceptor). Eventually, I want it to be a part of my company's Spring Boot starter.

Right now I can't even override current Feign autoconfiguration.
Is it because apart from Feign autoconfiguration: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignAutoConfiguration.java, there is an @Import statement in @EnableFeignClients annotation:
@Import({ **FeignClientsConfiguration.class**, FeignClientsRegistrar.class }), which sets up SpringMvcContract and rest of the properties?

**Comment by spencergibb** [comment]
You should be able to create a bean type `Contract` like:

```	
@Bean
public Contract feignContract() {
	return new JAXRSContract();
}
```

**Comment by poznachowski** [comment]
I tried setting up the bean in several places (within @Component, @Configuration) with no luck.
No matter what I do, SpringMVCContract is always picked and used.

**Comment by jmnarloch** [comment]
Have you tried using @Primary annoatation?

```
@Primary
@Bean
public Contract feignContract() {
    return new JAXRSContract();
}
```

**Comment by poznachowski** [comment]
Just tried and still no luck :(

**Comment by jmnarloch** [comment]
I wanted to suggest last final sollution which basically would be based on excluding the FeignAutoConfiguration.class, something like:

```
@SpringBootApplication(exclude = FeignAutoConfiguration.class)
```
or
```
@EnableAutoConfiguration(exclude = FeignAutoConfiguration.class)
```

but this is not going to work since @EnableFeignClients does also include FeignClientsConfiguration

**Comment by poznachowski** [comment]
So, it seems that my initial assumption was right. Is that a bug ?

**Comment by spencergibb** [comment]
Please see the [Overriding Feign Defaults](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#overriding-feign-defaults) section that was recently added.
