### ISSUE TITLE
feign support of interface hierarchies ignores MVC annotation on type

### ISSUE THREAD

**Issue by dinocop** [spring-cloud/spring-cloud-netflix#537]
As part of https://github.com/spring-cloud/spring-cloud-netflix/issues/436 and https://github.com/Netflix/feign/pull/246 feign inheritance support has been implemented. This is a great and helpful feature when sharing interfaces (and API jars) between feign clients and Rest Controllers on the server side.

Unfortunately RequestMapping annotations on type level will be ignored. Example:

```java
@RequestMapping(value = "/root")
interface MyInterface {

  @RequestMapping(method = RequestMethod.POST, value = "/this")
  void doThis()

  @RequestMapping(method = RequestMethod.PUT, value = "/that")
  void doThat()

  ...
}
```

RestController in Spring MVC will make endpoints available under /root/this and /root/that. When extending a feign client from this interface like:

```java
@FeignClient("myService")
public interface FeignClient extends MyInterface {

}
```

the feign client proxy tries for example not to access method on "/root/this", but only on "/this". It looks like the @RequestMapping(value = "/root") will be ignored and not added to the URI. 

I tryed a couple of workarounds already, such as avoiding type level annotations. But without type level annotations I cannot have multiple interfaces and rest controllers in my service.

Would it be possible to take these type level annotations into consideration? Or did I get something wrong?

**Comment by spencergibb** [comment]
One of the reasons is that any bean with `@RequestMapping` on the class level, spring mvc tries to install as a controller.

**Comment by dinocop** [comment]
In the meantime I did find out that there is a way to handle this the same way as when using a context path. Instead of relying on the value of the @RequestMapping annotation on type level the value can be added as part of the @FeignClient annotation. In our example:
```java
@FeignClient("myService/root")
public interface FeignClient extends MyInterface {

}
```
Feign/Ribbon will request service from Eureka based on host+port for service "myService" and will add everything afterwards as part of the URL. So you need to know the context paths as well as the value of the type level @RequestMapping annotation of the extended interface. So finally the requests will go into "root/this" as expected.
