### ISSUE TITLE
Use of @EnableScheduling in hystrix-amqp can cause problems with other TaskScheduler beans

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud/spring-cloud-netflix#538]
I am working on a project that makes use of Spring's WebSocket support via `@EnableWebSocketMessageBroker`. Next, I decide to enable circuit breaker support by adding `@EnableCircuitBreaker`. When I try to run the app, it throws an exception:

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.2.5.RELEASE:run (default-cli) on project demo: An exception occured while running. null: InvocationTargetException: More than one TaskScheduler exists within the context. Remove all but one of the beans; or implement the SchedulingConfigurer interface and call ScheduledTaskRegistrar#setScheduler explicitly within the configureTasks() callback. No qualifying bean of type [org.springframework.scheduling.TaskScheduler] is defined: expected single matching bean but found 2: messageBrokerSockJsTaskScheduler,taskScheduler

The problem is that hystrix-amqp internally sets `@EnableScheduling` as seen [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/1.0.x/spring-cloud-netflix-hystrix-amqp/src/main/java/org/springframework/cloud/netflix/hystrix/amqp/HystrixStreamAutoConfiguration.java#L63). Enabling scheduling in this way creates a `taskScheduler` bean, which is expected by  `ScheduledAnnotationBeanPostProcessor`. However, only ONE `TaskScheduler` [is expected](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/scheduling/annotation/ScheduledAnnotationBeanPostProcessor.java#L193). This means that this situation can happen whenever there are any task scheduler beans declared, and in this case, because a `messageBrokerSockJsTaskScheduler` bean is also created for websocket support, we now have two beans, and the post processor throws an exception.

If I had set the `@EnableScheduling` annotation in my app, I could take responsibility at this point and configure the default scheduler, like the following:

```java
@Configuration
public class TaskSchedulingConfiguration implements SchedulingConfigurer {

	@Autowired
	private TaskScheduler taskScheduler;

	@Override
	public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
		taskRegistrar.setScheduler(this.taskScheduler);
	}
}
```

This is in fact, how I worked around this issue in my app. The problem is that I didn't set the `@EnableScheduling` annotation in my app, and it's presumptuous of me to decide which `TaskScheduler` to set as default, since I didn't configure either one of them. While this may be a potential solution for this issue within spring-cloud, a better solution may be to not use `@EnableScheduling`, and thus avoid the post processor magic.

I created a [demo project](https://github.com/royclarkson/too-many-taskscheduler-beans) to illustrate this issue.

Cc: @scottfrederick @mstine @rstoyanchev

**Comment by dsyer** [comment]
Since Spring 4.2 `ScheduledAnnotationBeanPostProcessor` fixes this by choosing a bean named `taskScheduler` if there is more than one. IMO it's nothing really directly to do with Spring Cloud anyway (since you would have the same issue essentially using Spring Integration with Spring Web Sockets).
