### ISSUE TITLE
Ability to stop filter chain on condition

### ISSUE THREAD

**Issue by hohwille** [spring-cloud/spring-cloud-netflix#541]
I want to add custom authorization to my zuul based app. I wrote a ```ZuulFilter``` that can evaluate the condition but the API design of Zuul does not seem to allow me to get control over the filter chain like in servlet API so I can send a 403 and stop further processing. If I used a regular servlet filter I can do it but how would I get this filter in the right position of the processing? And also I do not know if a requests is processed by Zuul at all in this place or if it goes to static or other content...

@rozhok asked for the same thing in #40.
It would be nice to get some hints. Unfortunately the documentation is also not helpful in this area.
Would I have to write a "static" ZuulFilter that always produces a 403 and have my authorization logic in shouldFilter()? I assume this will also not work. Any ideas?

**Comment by rozhok** [comment]
In my case I resolved this issue with passing custom header into downstream servers and dealing with auth there.

**Comment by hohwille** [comment]
Write a ZuulFilter with type "route" and filterOrder 1. Then if you want to handle the request e.g. by sending an error then also call this magic line:
```
RequestContext.getCurrentContext().setSendZuulResponse(false);
```

I am also closing. However, you might want to add this to your wiki/docs.
