### ISSUE TITLE
Zuul fails to pass along Matrix parameters

### ISSUE THREAD

**Issue by timtebeek** [spring-cloud/spring-cloud-netflix#542]
Hi all,

It appears as though Zuul is stripping matrix parameters from routed requests, making it impossible to access them in routed web apps.

I'm running a fairly minimal `Angel.SR3` `@EnableZuulProxy` app as proxy router, with a routed service that uses a `java.servlet.filter` to test:
```java
@Override
public void doFilter(final ServletRequest request, final ServletResponse response, final FilterChain chain) throws IOException, ServletException {
	HttpServletRequest httpRequest = (HttpServletRequest) request;
	String requestURI = httpRequest.getRequestURI();
	System.out.println(requestURI);
	// Continue filter chain
	chain.doFilter(request, response);
}
```
When I access this service directly with matrix parameters (e.g.: `http://localhost:8080/;foo=bar/test`) the correct URL is printed. But when I route these requests through Zuul, the matrix parameters never reach the backend service, and only a stripped url is printed.

I'd like to be able to use matrix parameters on routed backend services when using Zuul. What can I do to retain these after proxying?

**Comment by timtebeek** [comment]
Even using something like this has no effect:
```java
@Configuration
public class MatrixConfig extends DelegatingWebMvcConfiguration {
	@Override
	public RequestMappingHandlerMapping requestMappingHandlerMapping() {
		RequestMappingHandlerMapping requestMappingHandlerMapping = super.requestMappingHandlerMapping();
		requestMappingHandlerMapping.setRemoveSemicolonContent(false);
		return requestMappingHandlerMapping;
	}
}
```

**Comment by spencergibb** [comment]
You can now set `zuul.removeSemicolonContent=false` to support matrix variables. It is opt-in the same way it is in spring mvc.

**Comment by timtebeek** [comment]
Sounds great, thanks! I'll have to wait for the next milestone to put this in production, but it saves me the awkward handling  currently in place in both my routing proxy and my proxied web-app.

**Comment by spencergibb** [comment]
@timtebeek hopefully we'll have an RC1 next week.
