### ISSUE TITLE
Problem with the alternative “/zuul” path bypassing DispatcherServlet in Zuul

### ISSUE THREAD

**Issue by sesto** [spring-cloud/spring-cloud-netflix#546]
Recently, we have upgraded to the latest version of spring-cloud-netflix  release 1.0.3 from 1.0.0. By mere chance, after the upgrade our index resource calls mapped to `/zuul` have been directed straight to `ZuulServlet` instead of “normal” `DispatcherServlet – ZuulController - ZuulServlet`  path. Because the call through the `ZuulController` involves removal of `RequestContext` from `ThreadLocal`   in the `finally{} ` block of its request handling method and this does not happen in ZuulServlet (has empty `finally{}` block), we got a major problem of contaminating the thread pool with old `RequestContext` data. 

According to the docs, the alternative `/zuul` path is intended for the large files upload. Is this the only intended usage of the alternative path and all other calls should go via the old “normal” path?

Obvious solutions for our problem:
1.	Change `zuul.servletPath` property from the default `/zuul` to something else (the easiest).
2.	Change our index resource mapping (involves more work)

Which of the above would be preferable? 

Should `RequestContent` be removed from `ThreadLocal`  in the `finally{}` block of `ZuulServlet service()` method?

**Comment by dparshin** [comment]
@sesto in our case we decided to bypass DispatcherServlet and ZuulController. In order to remove RequestContext from ThreadLocal you just need to declare "native" zuul ContextLifecycleFilter bean:
```
        @Bean
        public ContextLifecycleFilter contextLifecycleFilter()
        {
            return new ContextLifecycleFilter();
        }
```

**Comment by sesto** [comment]
@dparshin Thanks for the proposed solution, going to try it

**Comment by sesto** [comment]
@dparshin well, indeed, adding `ContextLifecycleFilter` solves the problem of removing `RequestContext` from  `ThreadLocal` for direct `ZuulServelt` calls. But all other calls are still going via `ZuulController` and, thus, we should prefix them all with `/zuul` to direct to straight to `ZuulServlet`. I am not sure we want to do this. Is there any particular reason for your decision to bypass `DispatcherServlet` and `ZuulController`?

**Comment by dparshin** [comment]
@sesto we wanted to have more control in zuul filters, so we point `zuul.servletPath` to `/` and clean up context using `ContextLifecycleFilter`

**Comment by sesto** [comment]
@dparshin we tried to point `zuul.servletPath` to `/` as our initial approach and it worked. The problem, however, is that we couldn't make HAL Browser work with this setup. We use rest level 3 and find HAL Browser on zuul being a very handy tool. Do you use HAL browser?

**Comment by dparshin** [comment]
@sesto no, we don't use HAL browser, so it's not an issue for us.

**Comment by dsyer** [comment]
> Should RequestContent be removed from ThreadLocal in the finally{} block of ZuulServlet service() method?

Probably. In fact it looks like it already does (https://github.com/Netflix/zuul), but that code is not GA yet. Spring Cloud will upgrade as soon as we can after Zuul 1.0.29 is released.

Meanwhile, is it really a problem? It's not like there is an unbounded number of contexts (the thread pools are fixed). If it is I guess you could use a custom servlet `Filter` to clear the context.

**Comment by sesto** [comment]
@dsyer It is a problem. Due to the fixed thread pool, eventually, more and more threads have old `RequestContext` in their `ThreadLocals` leading to the contamination of new requests with old data.  Well, in theory, the old data should be overwritten but, apparently, this is not the case. 
Anyway, we have opted for changing the mapping of  `zuul.servletPath` and, thus, all our calls are going through `ZuulController`

**Comment by dsyer** [comment]
I'll bump zuul to an rc release while we wait for the GA. That should fix this.
