### ISSUE TITLE
Zuul unexpected modifying of 'Content-Type' header for multipart request

### ISSUE THREAD

**Issue by alexkhromov** [spring-cloud/spring-cloud-netflix#553]
Hello i am stuck at a problem with Zuul.

My service is responding for file upload. Before processing incoming request Zuul intercept it and makes his stuff. No any custom filters implemented for this request. And when request after  filtering comes to the service it has strange value for 'Content-Type' header. Now more detailed.

1. My client send next request ( example ):
![1](https://cloud.githubusercontent.com/assets/8264727/10084127/75ccd034-630a-11e5-9db6-b1e66af80377.png)
![2](https://cloud.githubusercontent.com/assets/8264727/10084194/cf572c76-630a-11e5-984c-34cea89249a6.png)

2. Zuul intercept it. Some actions happened in RibbonRoutingFilter.run() before forwarding.
request:
![3](https://cloud.githubusercontent.com/assets/8264727/10083039/3a5aa35a-6305-11e5-9833-518e7c7caa85.png)
![4](https://cloud.githubusercontent.com/assets/8264727/10083042/3daab61c-6305-11e5-9ad7-2ca0c54111bd.png)
Notice values for content type.
headers map that passed to forward():
![5](https://cloud.githubusercontent.com/assets/8264727/10083455/4a9518f2-6307-11e5-9ccf-3ab31fcf4e80.png)
requestEntity ( as a string in watches ) that passed to forward():
![6](https://cloud.githubusercontent.com/assets/8264727/10083691/459e916a-6308-11e5-964f-1257127f9a66.png)
Notice a boundary value at a requestEntity.

3. After zuul request comes to my service:
In debug mode i am interested in a value of 'Content-Type' header:
req.getHeader( "Content-Type" ) = "multipart/form-data;boundary=-kKHcv_upPd5oBKqCC7tS35Jd8soS0,multipart/form-data; boundary=---------------------------155711003027032"

So as i am expected multipart request server ( Tomcat or Jetty ) triggered to parse it when i try to get any parameter or part from request using a boundary value. And server parser ( MultiPartInputStreamParser for Jetty or MultipartStream for Tomcat  no matter ) retrive boundary value "kKHcv_upPd5oBKqCC7tS35Jd8soS0,multipart/form-data". Followed by this throws some exception like "Missing content for multipart request" for Jetty or something like this for Tomcat.

One more in debug mode i am try to read request body as a String object and i got same result as for requestEntity in a RibbonRoutingFilter.

So next questions and misunderstanding arise regarding this problem :
- Why additional header 'content-type' ( original request header is 'Content-Type' ) is appear in headers map?
- Why value of boundary from new one header is appear in request body as a part delimiter?
- Why values from 'Content-Type' and 'content-type' are glued in one string when it come to my service?

May be you can help me to resolve this problem.

P.S. Is it related to this issue https://github.com/spring-cloud/spring-cloud-netflix/issues/260 ?
I am using 1.0.0.RELEASE for spring-cloud-starter-parent ( same version for spring-cloud-netflix-core ). 

I am trying exclude spring-cloud-netflix-core from spring-cloud-starter-parent and add spring-cloud-netflix-core 1.1.0.M1 but it calls chain of changes for my project in pom.xml and finally i am totally lost. 

Thanks.

**Comment by dsyer** [comment]
Please try to at least use the most recent stable version. If you can try with 1.1 that would be ideal. To manage the dependencies I recommend you use a project generated from start.spring.io as a template.

**Comment by dsyer** [comment]
I think this might be a manifestation of #546.
