### ISSUE TITLE
Spring amqp fault tolerance VS spring cloud netflix Hystrix

### ISSUE THREAD

**Issue by GrapeBaBa** [spring-cloud/spring-cloud-netflix#558]
Hi team,

We are considering to use spring amqp for our message service, i saw spring amqp provider some features for fault tolerance and spring cloud Hystrix also provider similar features. I wonder know what is the difference and how to choose one or combine them together?

**Comment by spencergibb** [comment]
I know very little about spring-amqp fault tolerance, but Hystrix is an implementation of Circuit Breaker. It allows you to protect any Java code from failures cascading back up the call stack.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you'd like us to reopen the issue, please comment with the required information.
