### ISSUE TITLE
In-process integration test facilities for features that depend on Eureka

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#56]
It's hard to write integration tests that require eureka to be up and running.  Create some kind of facility that allows mock eureka functionality.  I would find this useful for testing the zuul proxy functionality for example.

Options:
- Use a static server list for ribbon.
- Somehow mock eureka classes (hard because of static instances): DiscoveryManager, DiscoveryClient, etc...)
- Run an embedded eureka server
- If Eureka were more abstract (`@EnableDiscoveryClient` rather than `@EnableEurekaClient`), then an alternate implementation could be injected. (Post 1.0?)

**Comment by Writtscher** [comment]
Hi, is this still on the roadmap? Could you please guide me in the right direction? I'd like to test Hystrix fallbacks and hide loadbalancer functionality to mock it. With standalone setup I inject mocks but this is not enough, I' sure there is a better way..

**Comment by spencergibb** [comment]
@Writtscher not in the near term. For the short term, we inject a [StaticServerList](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/StaticServerList.java) into ribbon configuration for testing. See [here](https://github.com/spring-cloud/spring-cloud-netflix/blob/810502c1f326fe9f56ae9b59e3c4dfaae0e1a869/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/feign/valid/FeignHttpClientTests.java#L175-L186) for an example.

**Comment by Writtscher** [comment]
@spencergibb  Ok. Thank you, this might help for now. I'll see whether I find a good solution. Keep up the awesome work.
