### ISSUE TITLE
Preventing OutOfMemory exception when processing POST requests

### ISSUE THREAD

**Issue by ViktorRiabinin** [spring-cloud/spring-cloud-netflix#563]
Class ProxyRequestHelper (package org.springframework.cloud.netflix.zuul.filters) contains *debugRequestEntity* method that puts entire request body into a String variable:
`String entity = IOUtils.toString(inputStream)`. 
Only first 4096 symbols are used though: 
`info.put("body", entity.length() <= 4096 ? entity : entity.substring(0, 4096)`.

If body of request is large (for example, it is used for file uploading) it may cause OutOfMemory exception.

*debugRequestEntity* method won't be called if request has 'Transfer-Encoding: chunked' header set. However, for example, Chrome browser won't allow setting this header.

Is there other way to disable this debugging method? By the way, what's the purpose of reading entire request body into a string?

**Comment by dsyer** [comment]
Most clients send "Transfer-Encoding: chunked" (including browsers unless you are using some plugins I guess). And the Zuul proxy has never been used with large POST bodies I guess in any other setting, so I never noticed this before. Should be fixed now.
