### ISSUE TITLE
Ribbon listOfServers configuration appears to be getting ignored

### ISSUE THREAD

**Issue by bijukunjummen** [spring-cloud/spring-cloud-netflix#564]
This may be a gap in my understanding. I tried using Ribbon with a configuration in application.yml file along these lines:

    someservice:
          ribbon:
              listOfServers: server1:80
              ReadTimeout: 5000
              MaxAutoRetries: 2

However I get back an error that `no ServiceInstance could be found for someservice`. This works however if were to explicitly set this flag:

    ribbon:
      eureka:
      enabled: false

Further, if I were to explicitly specify the Netflix `NIWSServerListClassName` the parameter seems to be getting ignored, for eg.

	someservice:
		ribbon:	
			NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList	
			listOfServers: server1:80
			ReadTimeout: 5000
			MaxAutoRetries: 2

Can you please help with what I may be missing.

**Comment by spencergibb** [comment]
Spring Cloud uses `@RibbonClient` to configure the types used by ribbon, like server list. If you have eureka on the classpath, by default it uses the eureka server list (hence your need for the flag to disable eureka).

To use a list of servers on just some ribbon clients, do the following in a java configuration class:

```
@Configuration
@RibbonClient(name = "someservice", configuration = LocalRibbonClientConfiguration.class)
class Application {
//...
}

class LocalRibbonClientConfiguration {
	@Bean
	public ServerList<Server> ribbonServerList() {
		return new ConfigurationBasedServerList(); 
		// or new StaticServerList<>(new Server("server1", 80));
	}
}
```

**Comment by bijukunjummen** [comment]
Ah, makes sense @spencergibb, the documentation may require a change then:

> You can configure some bits of a Ribbon client using external properties in <client>.ribbon.*, which is no different than using the Netflix APIs natively, except that you can use Spring Boot configuration files

**Comment by spencergibb** [comment]
Yup, see #411
