### ISSUE TITLE
Provide ability to choose preferred ip for eureka

### ISSUE THREAD

**Issue by droy314** [spring-cloud/spring-cloud-netflix#565]
EurekaInstanceConfigBean now uses the first non-loopback address to register with Eureka server. In environments where there are more than one network interfaces, this may cause problems. I've hit this problem on a local laptop where I have VirtualBox installed. VirtualBox installs a host-only network adapter. The IP address from this adapter is registered with the eureka server (on another machine).
This may not happen frequently environment but would happen on developers' environments.

I'll try to subclass the EurekaInstanceConfigBean to see if that works.

Long term, I believe issues 523 and 302 may solve this problem.

**Comment by dsyer** [comment]
So you are using `preferIpAddress=true` and trying to set the `ipAddress` manually?

BTW: you can use a custom bean of type `EurekaInstanceConfig` in snapshots (i.e. #302 is resolved I believe).

**Comment by droy314** [comment]
Yes. I've set the preferIpAddress=true. I have 2 network adapters - a WLAN (ip range in segment 192.168.0.xx) and an Ethernet adapter (host-only from VirtualBox with ip range 192.168.99.xx). Only the 192.168.0.xx IPs are available from other machines on the network.
When the application registers, sometimes it picks up the 192.168.99.xx ip for registration that is not reachable from other computers on the network).

I've created a custom EurekaInstanceConfigBean and added a `eureka.instance.preferIp4Segment` property where we can specify a custom IP segment (192.168.0 in my case). The config bean gets the InetAddress that matches this segment and returns, otherwise gets the first non-loopback address.

If you are interested, the code is at https://gist.github.com/droy314/85bd3936b207d60aee89

This code is based on 1.0.3.RELEASE but should be easily portable to the snapshots

**Comment by spencergibb** [comment]
The code to determine which network is now in spring-cloud-commons.

**Comment by brenuart** [comment]
Not sure it is 100% related to the issue, but below is another scenario that fails with 1.1.0.M1. Suppose a container environment like Docker. In this case, you want you Eureka client to register with its _public_ IP and not with its _private_ IP. In this case you would use the following configuration:

````
eureka.instance.prefer-ip-address= true
eureka.instance.ip-address= <publicIP>
````

Unfortunately, at some point the `ApplicationInfoManager` will complain about the hostname having changed:
````
com.netflix.appinfo.ApplicationInfoManager : The public hostname changed from : <publicIP> => <privateIP>
````

The `ApplicationInfoManager` compares the hostname provided by `EurekaInstanceConfig` and `InstanceInfo`. However, one should remember that `EurekaInstanceConfig.getHostname()` returns the hostname OR the IP address depending on whether `eureka.instance.prefer-ip-address` is true or false. If you opt for "prefer ip address", then the `ApplicationInfoManager` is likely to always detect a change...

**Comment by droy314** [comment]
Thanks all. I didn't realize that I could manually set the ipAddress directly with <code>eureka.instance.ipAddress</code>. The changes I made do not offer much benefit other than not requiring developers to check the IP after a reboot/startup. Let me know if you'd want this and I can merge with the snapshots.

@brenuart With docker I'm afraid the easiest approach I know is to set the host ip as environment variables when starting the container. I haven't seen the error with ApplicationInfoManager but I haven't tested with this approach a lot.
<code>
docker run -e EUREKA_INSTANCE_PREFER_IP=true -e EUREKA_INSTANCE_IPADDRESS=[docker host public ip]
</code>


I'm marking this issue closed
