### ISSUE TITLE
Enable custome implementation of Turbine InstanceDiscovery

### ISSUE THREAD

**Issue by micheal-swiggs** [spring-cloud/spring-cloud-netflix#566]
I'm trying to get turbine setup. However, in my setup I have multiple services running on the same physical box. So I want to be able to use `FileBasedInstanceDiscovery`. I have tried enabling this in `application.properties`. However, this doesn't work. I have also tried creating my own `InstanceDiscovery` implementation - this gets created but is never asked for peers. I'm wondering how I go about monitoring multiple services on the same physical box and how I enable my own implementation of InstanceDiscovery?

Here is my gradle build script:

    buildscript {
        ext {
            springBootVersion = '1.2.2.RELEASE'
        }
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        }
    }

    apply plugin: 'java'
    apply plugin: 'spring-boot'

    jar {
        baseName = 'turbine'
        version = '0.0.1-SNAPSHOT'
    }

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    repositories {
        mavenCentral()
        maven { url 'http://repo.spring.io/libs-milestone' }
    }

    dependencies {
        compile("org.springframework.boot:spring-boot-starter-web") {
            exclude module: 'spring-boot-starter-tomcat'
        }
        compile("org.springframework.boot:spring-boot-starter-jetty:1.2.5.RELEASE")
        compile("org.springframework.boot:spring-boot-starter-actuator")
        compile("org.springframework.cloud:spring-cloud-netflix:1.1.0.M1")
        compile('org.springframework.cloud:spring-cloud-starter-turbine:1.1.0.M1')
    }

Here is my `application.properties` and `application.yml`:

    turbine.aggregator.clusterConfig=myCluster
    turbine.instanceUrlSuffix.myCluster=/hystrix.stream
    turbine.ConfigPropertyBasedDiscovery.myCluster.instances=localhost:9097,localhost:9090
    InstanceDiscovery.impl=com.netflix.turbine.discovery.FileBasedInstanceDiscovery
    //InstanceDiscovery.impl=turbine.TurbineApplication.CustomInst
    info.component= Turbine

    turbine:
      clusterNameExpression: new String("default")

Here is my application class:

    package turbine;

    import org.springframework.boot.autoconfigure.SpringBootApplication;
    import org.springframework.boot.builder.SpringApplicationBuilder;
    import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
    import org.springframework.cloud.netflix.turbine.EnableTurbine;
    import org.springframework.context.annotation.Configuration;
    import com.netflix.turbine.discovery.ConfigPropertyBasedDiscovery;
    import com.netflix.turbine.discovery.InstanceDiscovery;
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.Primary;

    import com.netflix.turbine.discovery.Instance;
    import java.util.Collection;

    @SpringBootApplication
    @EnableTurbine
    public class TurbineApplication {

        public static void main(String[] args) {
            new SpringApplicationBuilder(TurbineApplication.class).run(args);
        }

        @Primary
        @Configuration
        @EnableConfigurationProperties
        static public class Config
        {
            @Primary
            @Bean
            public InstanceDiscovery iDiscover(){
                println ("(1) creating.");
                return new CustomInst();
            }
        }

        public static class CustomInst implements InstanceDiscovery {

            @Override
            public Collection<Instance> getInstanceList() throws Exception {

                println("(2) getting instance list.");
                return null;
            }
        }
    }

**Comment by spencergibb** [comment]
Creating a `@Bean` of `InstanceDiscovery` should work now. I didn't do anything with your question "I'm wondering how I go about monitoring multiple services on the same physical box".
