### ISSUE TITLE
Zuul not deleting all headers once request is finished.

### ISSUE THREAD

**Issue by micheal-swiggs** [spring-cloud/spring-cloud-netflix#567]
We had a strange bug. The origin headers and request headers on zuul's `RequestContext` was not clearing the origin response and zuul response headers. Over time the headers `X-Application-Context`, `Cache-Control`, `Date` and `Expires` became larger. Currently our 'fix' is to have a PreFilter clear the headers:

    public class PreFilter extends ZuulFilter
    {
        @Override
        public String filterType(){ return "pre"; }

        @Override
        public int filterOrder(){ return 1; }

        @Override
        public boolean shouldFilter(){ return true; }

        @Override
        public Object run()
        {
            RequestContext context = RequestContext.getCurrentContext();

            List<Pair<String,String>> oHeaders = context.getOriginResponseHeaders();
            if (oHeaders != null) {
                oHeaders.clear();
            }

            List<Pair<String, String>> rHeaders = context.getZuulResponseHeaders();
            if (rHeaders != null) {
                rHeaders.clear();
            }
            return null;
        }
    }

**Comment by dsyer** [comment]
I'm guessing you were using the `/zuul/**` routes? There's a bug in the `ZuulServlet` (it doesn't clear it's context, see #546), so this might be a manifestation of that.
