### ISSUE TITLE
Zuul's FormBodyWrapperFilter removing POST parameters.

### ISSUE THREAD

**Issue by micheal-swiggs** [spring-cloud/spring-cloud-netflix#568]
We are sending through a POST `text` parameter as x-www-form-urlencoded. However, this parameter is getting stripped. I was able to narrow this down to the `FormBodyWrapperFilter`.

**Comment by dsyer** [comment]
I see. Any more details? There are some tests that show it works at least in a small range of scenarios, so we'd need more details to investigate your issue. Plus, if you narrowed it down, how about fixing it?

**Comment by micheal-swiggs** [comment]
I was using the incorrect branch. Using the correct branch fixes this.
