### ISSUE TITLE
Eureka: ApplicationInfoManager overrides the ip-address set by config

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#573]
(Version: 1.1.0.M1)

Suppose a container environment like Docker. In this case, you want you Eureka client to register with its public IP and not with its private IP. In this case you would use the following configuration:
```
eureka.instance.prefer-ip-address= true
eureka.instance.ip-address= <publicIP>
```

Unfortunately, at some point the `ApplicationInfoManager` complains about the hostname having changed:
```
com.netflix.appinfo.ApplicationInfoManager : The public hostname changed from : <publicIP> => <privateIP>
```
The `ApplicationInfoManager` compares the hostname provided by `EurekaInstanceConfig` and `InstanceInfo`. However, one should remember that `EurekaInstanceConfig.getHostname()` returns the hostname OR the IP address depending on whether `eureka.instance.prefer-ip-address` is true or false. If you opt for "prefer ip address", then the `ApplicationInfoManager` is likely to always detect a change...

Note: description of this scenario was originally posted in https://github.com/spring-cloud/spring-cloud-netflix/issues/565 but was not the root cause of user's problem.

**Comment by pcornelissen** [comment]
I am suffering from this bug too, I can't force a given hostname or IP, because the ApplicationInfoManager decides to act differently. In the log I get:

ApplicationInfoManager       : The public hostname changed from : 127.0.0.1 => aa.zz.yy.xx

In this try I tried to force the IP by: -Deureka.instance.ip-address=127.0.0.1 -Dserver.address=127.0.0.1

**Comment by dlouzan** [comment]
We have also met this effect when configuring some Spring Boot apps in Docker containers under AWS; we can try to force the IP address that the Eureka client should use tor register itself using the eureka.instance.ip-address option, but as the internal Spring Boot app running inside the Docker instance does not see the public network interface (the port is forwarded from the host to the guest), the Eureka library will decide that as the forced IP does not exist, it should be overwritten by the internal IP of the guest.

If we create a dummy virtual interface in the guest with the public IP, then the IP is not overwritten.

**Comment by spencergibb** [comment]
`ApplicationInfoManager` calls `EurekaInstanceConfig.getHostName(true)` and compares the result with the cached hostname. I've fixed `getHostName(true)` to not refresh if the `EurekaInstanceConfig.ipAddress` was set via config.

**Comment by lokrajahuja** [comment]
Spencer, I see following code in eureka client jar 1.8.6
 /*
     * (non-Javadoc)
     *
     * @see com.netflix.appinfo.InstanceConfig#getHostName()
     */
    @Override
    public String getHostName(boolean refresh) {
        return hostInfo.second();
    }

here boolean refresh is getting passed in method parameter but it is not used in the function definition .
