### ISSUE TITLE
DiscoveryClient is automatically configured if spring-cloud-starter-eureka is used

### ISSUE THREAD

**Issue by olivergierke** [spring-cloud/spring-cloud-netflix#578]
I've tried to build an app that uses service discovery in a Spring profile only. I have added `spring-cloud-starter-eureka` as dependency and see a `DiscoveryClient` now being created by default (complaining about no Eureka instance being available).

It looks like this is related to `EurekaClientAutoConfiguration` being enabled by default (due to `@ConditionalOnProperty(value = "eureka.client.enabled", matchIfMissing = true)`. I could turn that off by setting the property to `false` but I was originally expecting the `DiscoveryClient` not being created unless I explicitly enable it using `@EnableDiscoveryClient`.

**Comment by aheusingfeld** [comment]
+1 on that!

**Comment by brenuart** [comment]
+1
