### ISSUE TITLE
zuul routes to multiple web path to multiple service id

### ISSUE THREAD

**Issue by karthikciti** [spring-cloud/spring-cloud-netflix#590]
Hi,
I want zuul routes like below but it did not work. basically if path1 resource request comes, should go to service 1, if path 2 resource request comes , should go to service 2. 

YAML configuration
-------------------------
```
zuul
     routes:
          service1 : /path1/**
          service2 : /path2/**
```
Example request and expected out come are below:
    Request to zuul: http:///localhost:8090/path1/apiproduct/api1
    service end point is : http://localhost:9089/path1/apiproduct/api1
    Request to zuul: http:///localhost:8090/path2/apiproduct/api2
    service end point is : http://localhost:9089/path2/apiproduct/api2

**Comment by spencergibb** [comment]
You need to set `zuul.stripPrefix=false`.
