### ISSUE TITLE
Ribbon/Zuul- Ratio based traffic

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud/spring-cloud-netflix#593]
Hi All,

I have requirement to distribute traffic based on ratio, example 30% traffic should go to APP V1.0 and remaining traffic to APP V2.0. How to achieve this requirement ? PLease help.

**Comment by pradeepkusingh** [comment]
may I get any help on this ?

**Comment by spencergibb** [comment]
The only way to do this right now is to deploy APP such that 30% is version one and the rest are version 2 and let ribbon handle it. Otherwise, you'd need to write a custom filter.

**Comment by pradeepkusingh** [comment]
Thanks Spencer, can you pelase provide little bit more details ?

**Comment by spencergibb** [comment]
Deploy 3 of version 1 and 7 of version 2. Ribbon and zuul do nothing to support this type of ratio.
