### ISSUE TITLE
spring-cloud-starter-eureka-server pulls commons-logging:commons-logging as transitive dependency

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#597]
`spring-cloud-starter-eureka` pulls `commons-logging:commons-logging:1.1.3` as transitive dependency. Path to dependency is:

```
spring-cloud-starter-eureka-server
+ spring-cloud-netflix-eureka-server
  + eureka-core
    + aws-java-sdk-core
       + commons-logging
```

In a SpringBoot environment, `commons-logging` should be excluded and is replaced by `org.slf4j:jcl-over-slf4j` (included by default).

**Comment by spencergibb** [comment]
@brenuart I am unable to reproduce this using http://start.spring.io/ on either Brixton M1 or SNAPSHOT. What version are you using and gradle or maven?

**Comment by Writtscher** [comment]
Same for me with version 1.0.0.RELEASE. The latest release version (1.0.3.RELEASE) does not include it anymore. For me at least.

**Comment by brenuart** [comment]
Same here. Problem was apparently due to stale BUILD-SNAPSHOT dependencies. 
Sorry about the noise :-(
@spencergibb you can close the issue and flag it invalid.
