### ISSUE TITLE
Improve documentation on Turbine server setup ??

### ISSUE THREAD

**Issue by Writtscher** [spring-cloud/spring-cloud-netflix#601]
I followed http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_turbine_amqp. But failed to get it running. I might be missing something. The documentation tells  to use the ```@EnableTurbineAmqp``` annotation. I assume this annotation is part of ```org.springframework.cloud:spring-cloud-starter-turbine-amqp```. If I add this annotation I get an ClassNotFoundException. The ```TurbineAmqpConfiguration.class``` is missing 
```
import com.netflix.turbine.aggregator.InstanceKey;
import com.netflix.turbine.aggregator.StreamAggregator;
import com.netflix.turbine.internal.JsonUtility;
```
and gives me a compile error there, even if I add the ```org.springframework.cloud:spring-cloud-netflix-turbin``` dependency.. Still compile errors..  The turbine sample https://github.com/spring-cloud-samples/turbine/blob/master/pom.xml is using a complete different approach. 

So I'm not able to get this running. Could you please guide me in the right direction? Am I missing something?

My turbine configuration looks like https://github.com/Writtscher/zoo/tree/master/zoo-turbine Nothing special there..

**Comment by spencergibb** [comment]
The sample is using a different approach because it is a snapshot using master of spring-cloud where you are using the GA version. 

This is what I would do for gradle to see if that fixes the class not found:
```
dependencies {
    compile('org.springframework.cloud:spring-cloud-starter-turbine-amqp')
}

dependencyManagement {
        imports { 
                mavenBom "org.springframework.cloud:spring-cloud-starter-parent:Angel.SR3" 
        }
}
```

**Comment by Writtscher** [comment]
Ok I see. I'll try that tomorrow and let you know whether it fixes the issues. Thanks for the fast response.

**Comment by Writtscher** [comment]
Ok I tried it, but same result. Same compile errors.

**Comment by Writtscher** [comment]
Well I got it running. I had to remove the mavenBom and specify the version, for each cloud dependency, myself. Then I ran into another issue:```ClassNotFoundException ... com.netflix.config.DeploymentContext...``` This is true because the ```org.springframework.cloud:spring-cloud-starter-hystrix-dashboard``` dependency pulls an older version of hystrix-archaius (0.4.X). The DeploymentContext is added in Version 0.5.X. 

Not sure what I'm doing wrong. I have just one dependency. :S

**Comment by spencergibb** [comment]
@Writtscher can you try with 1.0.4.BUILD-SNAPSHOT? I believe I have fixed this, but we haven't released it.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
