### ISSUE TITLE
Zuul Ribbon forwarding problem

### ISSUE THREAD

**Issue by staleks** [spring-cloud/spring-cloud-netflix#605]
Hi,

I have an issue with configuration of Zuul, Eureka Server and Spring Boot (microService) application.

Here is the error:
```
com.netflix.client.ClientException: Load balancer does not have available server for client: evidencija-cc
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:468) ~[ribbon-loadbalancer-2.1.0.jar:2.1.0]
```

My microService Spring Boot application is called "evidencija-cc".
And if I run it (port 8181) it works.

![zuul-001](https://cloud.githubusercontent.com/assets/1543466/10577825/5cbd2fea-766e-11e5-8a44-42225e739c31.png)

Alongside I have Eureka server, and my Spring-Boot application correctly shows in Eureka
![zuul-002](https://cloud.githubusercontent.com/assets/1543466/10577918/1ab5a9e6-766f-11e5-825d-3eeb6624cd03.png)
![zuul-003](https://cloud.githubusercontent.com/assets/1543466/10577922/20596306-766f-11e5-9793-17dac61c9546.png)

Finally there is Zuul application, that I want to use as API Gateway.

Here is the configuration (application.yml):
```
info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignored-services: "*"
  routes:
    evidencija-cc: /evidencija-cc/**
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
```

Zuul Application:
```
@SpringBootApplication
@EnableZuulProxy
@EnableDiscoveryClient
public class EvidencijaZuulApplication {
	
    public static void main(String[] args) {
        SpringApplication.run(EvidencijaZuulApplication.class, args);
    }

}
```

Now If I hit, following URL:
http://localhost:8765/evidencija-cc/countries/197
![zuul-004](https://cloud.githubusercontent.com/assets/1543466/10578033/d0ade560-766f-11e5-92ed-56900aa975ec.png)

I expect that Zuul do the routing, to http://localhost:8181/countries/197, which doesn't happen.

Instead I got mentioned error and response:
```
{
  "timestamp": 1445258591865,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "com.netflix.zuul.exception.ZuulException",
  "message": "Forwarding error"
}
```

I've read a lot of blogs these days, and all seams that this was easy to do, thus I must be doing something wrong, just don't know what?

Thank You

**Comment by staleks** [comment]
Furthermore, reading more and more blog posts, :) I've encounter this:

```
zuul:

  ignored-services: "*"
  routes:  
    evidencija-cc:
      path: /evidencija-cc/**
      url: http://localhost:8181/
```

and this works. 

But that implies that my service discovery, Zuul <- Eureka, is not OK. Still I would like to know why ?

Thnx

**Comment by Writtscher** [comment]
Did you wait until your eureka server knows about your zuul server? If you start your zuul Server and evendecija server then you should see two server registered (eureka admin page, after 30 seconds). Check your zuul server logs. There should be a hint that your zuul server knows about your evedencija server.

**Comment by staleks** [comment]
Hi Waldemar,

no I still do not see Zuul registered @ Eureka :(

But shouldn't I made changes in Java code in Spring Boot application of Zuul, and 
some changes in application.yml properties of Zuul? (to enable Zuul application to register @ Eureka).

To be honest I didn't find any blog resource saying that.

Thnx

**Comment by Writtscher** [comment]
Btw your configuration is wrong. Try:

```
routes:
  evedencija-cc : /evendencia-cc/**
```

Or

```
routes:
  evedencija-cc:
   path : /evendencia-cc/**
   serviceId: evedencija-cc
```

**Comment by staleks** [comment]
Why do you mean that configuration:

routes:
    evidencija-cc: /evidencija-cc/**

You can clearly see from attached images, that:
- Eureka shows that name of microService is "evidencija-cc"
- Zuul configuration is 
```
routes:
    evidencija-cc: /evidencija-cc/**
```
- Postman request is: http://localhost:8765/evidencija-cc/countries/197

and this doesn't work.

Your suggestion is to use "evidencia-cc", but I don't see how this is going to work?

**Comment by Writtscher** [comment]
You are right, your configuration is ok. My bad sorry. Can you try something? My Zuul server(https://github.com/Writtscher/zoo/tree/master/zoo-zuul) is working and my configuration looks as yours. Try to start Eureka then Evedencia-cc now wait until evendencia-cc is registered at eureka. Now start zuul and wait until it is also registered. Then try again.

**Comment by staleks** [comment]
Even better :)

I've assumed that your worked for you. So before I checkout and try, I've checked your pom.xml.
I'm using Gradle and I see that I was missing `eureka` dependencies :)

So I've added that, and now I see `Zuul Server` registered in Eureka and everything works like a charm.

Once again,  Waldemar, thank you for your help.

This issue can be closed

**Comment by Writtscher** [comment]
I'm glad that I could help. Have a look at http://callistaenterprise.se/blogg/teknik/2015/03/25/an-operations-model-for-microservices/. This could help you.

**Comment by jfrosch** [comment]
Fyi, I found another cause of this "ClientException: Load balancer does not have available server for client Xyz" issue is when an id in the routes doesn't match one the the application names.

I had a spring.application.name=FooService, but inadvertently declared a zuul.routes.foo-service. This resulted in a "ClientException: Load balancer does not have available server for client foo-service" message.
