### ISSUE TITLE
zuul filter example/sample

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud/spring-cloud-netflix#607]
I am trying to implement customer routing based on specific values in request body using zuul filter. do we have any simple example which I can refer to develop above ? Any help would be highly appreciated.

**Comment by pradeepkusingh** [comment]
Giibs, 

Can you please help here ?

**Comment by spencergibb** [comment]
I've pointed you at various examples on stackoverflow and in our own code. Not sure what else I can do.

**Comment by pradeepkusingh** [comment]
Thanks.

Thanks,
Pradeep Singh
Please excuse typos.
