### ISSUE TITLE
Request for input to javanica compile-time weaving

### ISSUE THREAD

**Issue by pagrus7** [spring-cloud/spring-cloud-netflix#616]
Javanica [issue 907](https://github.com/Netflix/Hystrix/issues/907) enables/fixes support for compile-time weaving. However, based on the discussion thread, the intended solution has implications, which I believe worth attention of downstream projects like spring-cloud-netflix.

* Javanica is going to distribute two different artifacts with similar content. 
One for runtime weaving and another one for compile-time weaving. Both have same classes, but one would be compiled with javac and another with ajc.

* For CTW version to work, it would require users to specify a system property, `-DweavingMode=compile`

* Per explanations, javanica becomes dependent on a specific aspectj version.

I'm evaluating spring-cloud-netflix for my project which favours CTW, and would like to keep using CTW. Please ignore this request if I'm overreacting and the changes above are non-issue for spring-cloud. Otherwise appreciate your input.

**Comment by spencergibb** [comment]
Not sure what implications this has for our project.

**Comment by pagrus7** [comment]
Well, I'm new to the spring-cloud-netflix codebase, so maybe all these are dumb questions:

* Which artifact will spring-cloud-netflix depend on - CTW or non-CTW? What happens if it is not the one user needs? Will user need to exclude one and include the other through the dependency management?

* Do spring-cloud-netflix users become locked into specific aspectj version b/c of javanica?

Hope they are, and there is nothing to worry about.

**Comment by spencergibb** [comment]
We depend on `com.netflix.hystrix:hystrix-javanica:1.4.18`. If the user wants compile time weaving, the can do as you suggest and exclude one and include the other. We let spring-boot manage the version of spring-aop and aspectj.

**Comment by tol** [comment]
Hi,

How can I get the hystrix-javanica-ctw?
I am tring this, but it didn't work...

    <dependency>
        <groupId>com.netflix.hystrix</groupId>
        <artifactId>hystrix-javanica-ctw</artifactId>
        <version>1.5.10</version>
    </dependency>

@pagrus7 
@spencergibb

**Comment by ryanjbaxter** [comment]
@tol please open a separate issue with a description of what you are trying to do, the problem you are running into, and if possible a sample reproducing the issue.
