### ISSUE TITLE
Support object parameters in feign

### ISSUE THREAD

**Issue by nickcodefresh** [spring-cloud/spring-cloud-netflix#617]
Does spring-cloud-netflix support POJO object parameters?

```
@RequestMapping(value = "/api/events", method = RequestMethod.GET,)
EventList getEvents(@ModelAttribute @Valid EventQuery eventQuery)
````

I don't think it does. Feign seems to map the EventQuery object to the body of the request.

**Comment by spencergibb** [comment]
It doesn't. See #609

**Comment by nickcodefresh** [comment]
They're different issues, no?

**Comment by spencergibb** [comment]
Yes, but similar in that they both want to support a spring parameter annotation.

**Comment by Dreampie** [comment]
https://github.com/Netflix/feign/issues/329#event-561389611
so，we can custom user encoding，like json... can you help?

**Comment by nickcodefresh** [comment]
Yes, that'll work
