### ISSUE TITLE
Adding to eureka metadata dynamically 

### ISSUE THREAD

**Issue by ljramones** [spring-cloud/spring-cloud-netflix#62]
I tried to add to the metadata of a service after it was created but I cannot see this data propagated in the discovery of it to other services.

I tried adding a auto wired dependency to

```
@Autowired
private EurekaInstanceConfigBean eurekaInstanceConfigBean;
```

Then later I got  

```
Map<String, String> metadata = eurekaInstanceConfigBean.getMetadataMap();
```

added my own metadata key, value pairs and did a 

```
eurekaInstanceConfigBean.setMetadataMap(metadata);
```

It does not seem to get propagated.  I assumed it was possible but is it?

The reason I am using it is that there are some properties associated with the service that I wanted to pass along and figured that add then this way would work.

**Comment by bill23-kim** [comment]
Is it okay to not call **setIsDirty()** on InstanceInfo?
