### ISSUE TITLE
Zuul and Web App Relative Paths Not Working.

### ISSUE THREAD

**Issue by jjparsons** [spring-cloud/spring-cloud-netflix#624]
I'm trying to use Zuul to serve web app's (ex. my console web app) using service discovery (serviceId's) in contrast to absolute paths like Dave Syer's example [here](https://github.com/dsyer/spring-security-angular/tree/master/double). Therefore, a request such as /console/** to Zuul should route to a console web app instances registered with the Eureka server. The Zuul route is currently configured to strip the prefix to simply / while the browser's base URL should still be /console agnostic of how you reach the web app.

Unfortunately the relative path's in the web app don't work via the gateway and only work via accessing the web app directly. For some reason the browser does not maintain the base URL (ie. /console) after resolving the index.html file.

Has anyone used service discovery to route requests to angular web app's using Zuul? Any ideas?

Web app files are located in the the following directory:
```
src/main/resources/static
```
Example web app resource:
```
<link rel="stylesheet" href="/../app/app.css">
```

Zuul config:
```
zuul.routes.console-webapp.path=/console/**
zuul.routes.console-webapp.serviceId=console-webapp
zuul.routes.console-webapp.stripPrefix=true
```

**Comment by spencergibb** [comment]
So `/../app/app.css` is not a relative path in general, it's relative to slash. When I hear "relative path", I think of paths that don't start with `/`.

I also don't understand this:

> For some reason the browser does not maintain the base URL (ie. /console) after resolving the index.html file.

Does the location change in the url bar?

This isn't unique to zuul, any app running behind a proxy that changes the path it expects will have this problem. The app has to get the context from somewhere and make appropriate requests.

**Comment by jjparsons** [comment]
Sorry, paths are relative, that was a typo:
```
<link rel="stylesheet" href="../app/app.css">
```
Correct, the location is still:
```
http://localhost:5000/console
```
However, requests to the static resources are:

```
http://localhost:5000/app/app.css
```
When they should be:
```
http://localhost:5000/console/app/app.css
```
Note, this have no effect:
```
<link rel="stylesheet" href="app/app.css">
```

**Comment by spencergibb** [comment]
None of what you mentioned is a problem with zuul. Does your app have a `base href` in it?

**Comment by jjparsons** [comment]
No, I'm not using HTML5 mode at all in Angular. Are you suggestions there is a ```base href``` that would fix the location/base URL issue? This is likely a client issue but you may run into this often if others take the same approach as me. I spent a few hours already researching and playing around with it.

**Comment by spencergibb** [comment]
It is a client issue. What could zuul do?

**Comment by jjparsons** [comment]
Well I assume it was a client issue but I didnt know for sure if Zuul was transforming the request. Have you ever accessed web apps using Zuul and relative paths?

**Comment by spencergibb** [comment]
I can change the request, but it can't fix a bad request coming from a client (ie /app/app.css -> /console/app/app.css). I've generally not used relative paths and have the html served by a template that fills in the base href.

**Comment by jjparsons** [comment]
Okay, I will try that and see if I can get it working. Ideally the client should work fine with a direct request or via proxy like Zuul. That's the goal to keep it clean. The gateway is handing CSRF for me as well and removing any CORS issues as you know. I will close the loop with you when I have further information.

**Comment by jjparsons** [comment]
I was serving the web app from src/main/resources/static to take advantage of the new dev tools (live reload). Unfortunately, this messes the base url (ex. /console). Serving the files from src/main/webapp/static solves the issue. live reload doesn't monitor this directory though so configuration will have to be included to monitor it for changes.

Therefore, Zuul works great for serving web app's by serviceId just like any other microservice. Please close.

**Comment by kaveenbalaji** [comment]
Apologies for replying to a closed thread. 
I am facing the same issue with the zuul-config (similar to the one mentioned above) and the base href set to zuul route path for a spring boot application serving angular 2 static content. In the above reply, you mentioned serving the files from webapp folder solves the issue. By default Spring boot recommends static content served under static/public folder under src/main/resources.  Can you let me know how to ensure static content served under the webapp folder in a spring boot web app ?
