### ISSUE TITLE
Lost "Spring eureka" logo and style css

### ISSUE THREAD

**Issue by dacofr** [spring-cloud/spring-cloud-netflix#627]
Hi,

when migrating from 1.1.0.M1 to 1.1.0.M2, we lost the logo and some header style, cf screenshot.

I think the problem is in wro.css file
1.1.0.M1 is about 6394 lines
1.1.0.M2 is about 6164 lines

Maybe header.less is not processed.

![image](https://cloud.githubusercontent.com/assets/1257842/10953762/1fa63410-834a-11e5-910f-19314c53dfbc.png)

**Comment by spencergibb** [comment]
I saw this yesterday as well. Fortunately it is just cosmetic.

**Comment by dacofr** [comment]
Indeed, it is not very serious. It's just confusing the first time :)

**Comment by spencergibb** [comment]
missing a huge segment :frowning:

**Comment by spencergibb** [comment]
It was because of spring-boot's change to use a different maven resource delimiter: http://docs.spring.io/spring-boot/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#using-boot-maven
