### ISSUE TITLE
magnifying-glass-icon*.png files license

### ISSUE THREAD

**Issue by vlna** [spring-cloud/spring-cloud-netflix#628]
Hi, files `magnifying-glass-icon*.png` looks like https://commons.wikimedia.org/wiki/File:Searchtool.svg

This file was originally LGPL licensed and LGPL should be followed, but I cannot confirm it was not provided under different licensing terms to spring-cloud-netflix project.

**Comment by spencergibb** [comment]
@vlna It's LGPL, not GPL. What would you expect to be done here?

**Comment by spencergibb** [comment]
If we do need to do something here are some public domain icons

- https://openclipart.org/detail/5450/magnifying-glass
- https://openclipart.org/detail/59167/magnifying-glass
- https://openclipart.org/detail/38965/search-find-zoom
- https://openclipart.org/detail/23907/magniflying-glass

**Comment by vlna** [comment]
Replacing image with Pulic Domain one is safest solution.

For LGPL licensed files I expect information about license, full text of license and source or source code offer (svg - if exists). Just reusing LGPL licensed files without following LGPL based obligations is clear LGPL violation.

**Comment by dsyer** [comment]
I replaced this image but I don't see it in the UI anywhere so I doubt anyone will notice.

**Comment by dsyer** [comment]
I had a hard job merging 1.0.x though (concluded it is impossible at this point). Cherry packed to 1.0.4 as well.

**Comment by jkschneider** [comment]
@dsyer fyi - corrected in Hystrix 1.4.22 with 
https://github.com/Netflix/Hystrix/commit/e279d2ca1dab947a0c6ebe7eedafdc94e13bb139

**Comment by dsyer** [comment]
Thanks @jkschneider.
