### ISSUE TITLE
hystrix throw exception cause no log output

### ISSUE THREAD

**Issue by devchenpy** [spring-cloud/spring-cloud-netflix#629]
Hi guys:

we use logback as the log appeder and hystrix as the circuit-breaker, we add the `@HystrixCommand` in the methods of the controllers, sometimes the controller throws the `HystrixRuntimeException` because of the request time out eg. Suddenly the log file is no log output , but the application still can handle work fine and deal with requests. the other instance in the spring cloud cluster without the exception works fine too. we also check the thread stack. they seems fine. we have no idea, the last log

![image](https://cloud.githubusercontent.com/assets/5657039/11029001/c3804ec4-86fe-11e5-8e95-e723a48ea3b7.png)

**Comment by spencergibb** [comment]
That image is impossibly small to read, care to paste the exception?

**Comment by devchenpy** [comment]
Sorry for that!
![hello](https://cloud.githubusercontent.com/assets/5657039/11113140/35f0474a-8955-11e5-82ac-ed26946fbb99.jpg)

**Comment by devchenpy** [comment]
@spencergibb

**Comment by spencergibb** [comment]
@devchenpy can you share a project that reproduces this?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
