### ISSUE TITLE
Branches are published in /libs-snapshot-local together with main stream

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#630]
Artifacts from branch `eureka-1.3.0` are published in `https://repo.spring.io/libs-snapshot-local` together with the main stream builds without using a different Maven GAV number.

As result, `BUILD-SNAPSHOT` dependencies may refer to artifacts from different, possibly incompatible,  branches.

For instance, build https://travis-ci.org/spring-cloud/spring-cloud-netflix/builds/89740201 is made from the `eureka-1.3.0` branch and produced `spring-cloud-netflix-core-1.1.0.BUILD-20151106.220959-148.jar`.
People working with `Brixton.BUILD-SNAPSHOT` will then get dependencies from the not yet merged `eureka-1.3.0` branch.

**Comment by brenuart** [comment]
Not sure about the actual cause, but the above mentioned build seems to have been triggered by a PR which the build system interpreted as an order to _deploy_ the artifacts.

**Comment by spencergibb** [comment]
The conditionals are confusing. it's not `if then`, it's `if or`. I still think it's the branch.

**Comment by spencergibb** [comment]
I'm likely to port [this](https://github.com/openzipkin/zipkin-java/blob/master/.travis.yml#L30-L38) so it's more specific.

**Comment by brenuart** [comment]
The thing is the artefacts from the `eureka-1.3.0` branch were published and our Eureka Server isn't building anymore because `... EurekaServerConfigBean` class is now gone.

**Comment by spencergibb** [comment]
I know there is a problem. I'm working on a fix. The comment about PR triggering a deploy is just incorrect. `EurekaServerConfigBean` isn't gone, it's moved from `-core` to `-server`.

**Comment by brenuart** [comment]
Yeah... but because of SNAPSHOT dependencies, our Nexus proxy didn't refresh the `-server` jar. 
Anyway, glad you are aware of the issue. Hope you can find something more reliable ;-)

**Comment by spencergibb** [comment]
The fix I pointed to will fix master. I'll have to rebase the branches, otherwise, they won't have the fix.

**Comment by brenuart** [comment]
Thanks
