### ISSUE TITLE
RestTemplateUrlTemplateCapturingAspect should only be applied if AspectJ is available

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#636]
RestTemplateUrlTemplateCapturingAspect should only be applied if AspectJ is available. Or maybe aspectj should be a mandatory dependency? Either way there are test failures in https://github.com/spring-cloud-samples/tests.

**Comment by jkschneider** [comment]
@dsyer Sorry for the trouble.  Collecting rest template metrics only in the presence of AspectJ auto proxying feels like the right solution.

**Comment by dsyer** [comment]
See also #637
