### ISSUE TITLE
Eureka: ApplicationInfoManager initialisation

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#638]
`EurekaClientAutoConfiguration.applicationInfoManager(EurekaInstanceConfig config,InstanceInfo instanceInfo)` creates an instance of `ApplicationInfoManager` with the supplied instance config and info.

Later, `DiscoveryClientConfiguration` forces the initialisation a second time by calling `ApplicationInfoManager.initComponent(InstanceInfo)` with the (apparently) same instance info.

A comment in `com.netflix.appinfo.ApplicationInfoManager` says:
> This class should be in singleton scope so do not create explicitly. Either use DI or use getInstance().initComponent() if not using DI

Here we are doing both. Is it on purpose?

(_Applicable to Brixton.M2_)

**Comment by spencergibb** [comment]
It no longer does.

https://github.com/spring-cloud/spring-cloud-netflix/search?utf8=%E2%9C%93&q=initComponent
