### ISSUE TITLE
Eureka: EurekaClientConfig.backupRegistryImpl not taken into account

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#640]
User defined backup registry implementation specified via the `eureka.client.backupRegistryImpl` configuration property is not taken into account.

The issue is caused by a bug introduced in recent Eureka `DiscoveryClient` releases (at least since `1.2.5`). The problem has been fixed a couple of days ago (https://github.com/Netflix/eureka/commit/2a91a1603907cc6de1ce2dc60199865f9b1e66b4) but is not part of any official release yet.

SpringCloud Netflix should therefore upgrade Eureka to a version higher than the current 1.3.4 whenever possible.

--

_Applies to Brixton.M2 and Brixton.BUILD-SNAPSHOT, therefore with `com.netflix.eureka:eureka-client` version `1.2.5` and `1.3.4`)_

**Comment by dsyer** [comment]
We are up to 1.4.1 now so I assume this is fixed.
