### ISSUE TITLE
Config Server - Dynamic proeprty refresh is taking 30 seconds

### ISSUE THREAD

**Issue by pradeepkusingh** [spring-cloud/spring-cloud-netflix#641]
Perf Test
Configuration = Cloud Foundry+ Spring Cloud
We have configured  ConfiServer and put or proeprty files in GITHUB, all controllers are coded with refreshScope annotations . while load test with 75 users , we have updated proeprty files  in git and try to refresh from browser to dynamically update all beans with new proeprty. It is taking 30-50  seconds and sometimes timeout with bad gateway error.  less user less time , more users mor time.

can you please exaplain us the behavior?

**Comment by spencergibb** [comment]
questions like this should probably go on stackoverflow. This is spring-cloud-netflix anyway, you want spring-cloud-config.

**Comment by pradeepkusingh** [comment]
aah my bad.
