### ISSUE TITLE
using eureka client healthcheck - DiscoveryCompositeHealthIndicator prevents status recover

### ISSUE THREAD

**Issue by robtha** [spring-cloud/spring-cloud-netflix#643]
I have enabled healthcheck for eureka. 
A custom HealthIndicator might change the status of the appliction to DOWN or OUT_OF_SERVICE which works fine and Eureka server shows the expected status.
If my application recovers to status UP, I am unable to send the correct status to the Eureka server.

EurekaHealthCheckHandler aggregates the states of all available HealtIndicators. This includes DiscoverCompositeHealthIndicator that holds the current status from the Eureka server (DOWN). 
Because the HealthAggregator will return the status with the lowest 'level' we will allways receive DOWN.

Is there a configuration option that I might have missed?

Output of health endpoint below shows that the custom HealthIndicator 'healdIndicator' is UP, but discoveryComposite.eureka stays DOWN

```json
{
    "description": "Remote status from Eureka server",
    "status": "DOWN",
    "healthIndicator": {
        "status": "UP"
    },
    "discoveryComposite": {
        "description": "Remote status from Eureka server",
        "status": "DOWN",
        "discoveryClient": {
            "description": "Spring Cloud Eureka Discovery Client",
            "status": "UP",
            "services": []
        },
        "eureka": {
            "description": "Remote status from Eureka server",
            "status": "DOWN",
            "applications": {
                "ECHO-SERVICE": 0
            }
        }
    },
    "diskSpace": {
        "status": "UP",
        "total": 147511238656,
        "free": 120203931648,
        "threshold": 10485760
    },
    "hystrix": {
        "status": "UP"
    }
}
```

**Comment by dpalinic** [comment]
This is easy to reproduce with bringing down RabbitMQ for example. Service will go down, but will never recover because "Remote status from Eureka server" id in DOWN state.
