### ISSUE TITLE
1.0.4.RELEASE not available in Maven Central?

### ISSUE THREAD

**Issue by dcoraboeuf** [spring-cloud/spring-cloud-netflix#645]
Hi,

I wanted to upgrade from Spring Cloud Netflix 1.0.3.RELEASE to 1.0.4.RELEASE, but it seems this version is not available in the Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.cloud%22%20AND%20a%3A%22spring-cloud-starter-hystrix-dashboard%22

Delivery problem or is that available now in another repository?

BR
Damien

**Comment by dcoraboeuf** [comment]
The 1.0.4 version is still not in the Maven Central :(

**Comment by dsyer** [comment]
Should be there now.

**Comment by dcoraboeuf** [comment]
Perfect. Thanks you.
