### ISSUE TITLE
Sharing interface between client and controller with async return values

### ISSUE THREAD

**Issue by kflorence** [spring-cloud/spring-cloud-netflix#646]
Apologies if I should be asking this elsewhere, but is there any way to share an interface between a client and a controller when the controller has asynchronous return values? For example, if using Spring MVC and the controller has a method that returns a `DeferredResult<FooResponse>`, the client would need only `FooResponse` thus breaking the contract defined in the interface.

**Comment by kflorence** [comment]
See also https://github.com/Netflix/feign/issues/24 -- the fact that Feign does not support async might not matter as long as there is some way we can unwrap the async value in the client.

**Comment by spencergibb** [comment]
The client isn't asynchronous. I'm not sure this makes sense.

**Comment by kflorence** [comment]
@spencergibb The client itself is not asynchronous, but I think it will be fairly common for the client to interact with a service that is (especially in Spring MVC) -- I think it's a pretty big downside to not be able to share the contract between the client and service just because the service uses asynchronous return values.

Our current workaround is to just put the client implementation of asynchronous service methods outside of our shared interface and changing the signature of the return value in the client.

**Comment by spencergibb** [comment]
@kflorence I don't think it's wise to share the interfaces. I opened #659 to discuss the possibility of deprecating and eventually removing the spring mvc annotation support, mostly to avoid the sharing.

**Comment by kflorence** [comment]
@spencergibb perhaps the sharing of interfaces is not the best solution, but I do think it is really advantageous to be able to share the same signatures/routes between both as it reduces the chance of human error bugs. Definitely open to other solutions/suggestions to the problem.

**Comment by spencergibb** [comment]
> I do think it is really advantageous to be able to share the same signatures/routes between both as it reduces the chance of human error bugs.

That's the rub, you can get close, bet never close enough, especially for something like async that the client knows nothing about.

**Comment by kflorence** [comment]
Feign might eventually support async, FYI.

**Comment by spencergibb** [comment]
@kflorence I know, I watch the feign repo and the maintainer is my teammate. Even if it does support it, I would hesitate to support `DeferredResult` on the client side.
