### ISSUE TITLE
[Scala] Feign @RequestParam with default argument value

### ISSUE THREAD

**Issue by kflorence** [spring-cloud/spring-cloud-netflix#649]
Feign doesn't seem to support default values for `@RequestParam`. For example, this fails:

```scala
  @RequestMapping(method = Array(GET), value = Array("/accounts/{accountId}/services/{serviceId}/bills"))
  def getBills(
    @PathVariable("accountId") accountId: Int,
    @PathVariable("serviceId") serviceId: Int,
    @RequestParam(value = "foo", required = false) foo: String = ""
  ): List[BillResponse]
```

With the following exception:

```
[error] CAUSED BY
[error]  java.lang.IllegalStateException: Method getBills$default$3 not annotated with HTTP method type (ex. GET, POST) (Util.java:112)
[error] feign.Util.checkState(Util.java:112)
[error] feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:94)
[error] org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:46)
[error] feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
[error] feign.hystrix.HystrixDelegatingContract.parseAndValidatateMetadata(HystrixDelegatingContract.java:24)
[error] feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
[error] feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:55)
[error] feign.Feign$Builder.target(Feign.java:179)
[error] feign.Feign$Builder.target(Feign.java:175)
```

But this succeeds:

```scala
  @RequestMapping(method = Array(GET), value = Array("/accounts/{accountId}/services/{serviceId}/bills"))
  def getBills(
    @PathVariable("accountId") accountId: Int,
    @PathVariable("serviceId") serviceId: Int,
    @RequestParam(value = "foo", required = false) foo: String
  ): List[BillResponse]
```

But then you have to call the client like so:

```scala
client.getBills(1, 2, null)
```

Is there any way to set a default value for the argument? We are using Scala if that is helpful.

**Comment by dsyer** [comment]
Default parameter values is a Scala feature, and Feign is a Java library, so I don't really know how they would interact. Does your `@RequestMapping` show up in Java byte code as an interface method? Feign itself has no concept of a default value either, so if this is going to work it would probably have to be a consequence of how Scala translates to Java byte code.

**Comment by kflorence** [comment]
@dsyer I am unsure of how to test that (`javap -c MyClass` or something similar?) -- reading http://docs.scala-lang.org/sips/completed/named-and-default-arguments.html it seems that Scala creates synthetic methods for every parameter with a default argument, perhaps this is what is confusing Feign into thinking these synthetic methods are actually endpoints which are missing HTTP method type annotation.

**Comment by kflorence** [comment]
I seem to have a workaround for Feign, although I will need to keep digging to apply a similar fix to `feign.hystrix` (currently getting `java.lang.NullPointerException: null (HystrixInvocationHandler.java:54)`). Anyways, I think I need some way of telling Feign what I actually want it to treat as endpoints instead of letting it try to guess itself. It seems to only filter out methods defined on the `Object` class and nothing else, which is a problem in Scala at least. Here's my current workaround.

## Define a new annotation

```java
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Mapping
public @interface FeignEndpoint {
}
```

## Exclude methods on the client that don't contain the annotation

```java
public class FeignClientContract extends SpringMvcContract {

  @Override
  public List<MethodMetadata> parseAndValidatateMetadata(Class<?> targetType) {
    checkState(targetType.getTypeParameters().length == 0, "Parameterized types unsupported: %s",
      targetType.getSimpleName());
    checkState(targetType.getInterfaces().length <= 1, "Only single inheritance supported: %s",
      targetType.getSimpleName());
    if (targetType.getInterfaces().length == 1) {
      checkState(targetType.getInterfaces()[0].getInterfaces().length == 0,
        "Only single-level inheritance supported: %s",
        targetType.getSimpleName());
    }
    Map<String, MethodMetadata> result = new LinkedHashMap<String, MethodMetadata>();
    for (Method method : targetType.getMethods()) {
      // Only include methods marked with FeignEndpoint annotation
      FeignEndpoint endpointAnnotation = method.getAnnotation(FeignEndpoint.class);
      if (endpointAnnotation == null) {
        continue;
      }
      if (method.getDeclaringClass() == Object.class) {
        continue;
      }
      MethodMetadata metadata = parseAndValidateMetadata(targetType, method);
      checkState(!result.containsKey(metadata.configKey()), "Overrides unsupported: %s",
        metadata.configKey());
      result.put(metadata.configKey(), metadata);
    }
    return new ArrayList<MethodMetadata>(result.values());
  }
}
```

## Apply this new configuration to the client

```scala
@Configuration
class FeignClientConfiguration {

  @Bean
  def contract: Contract = new FeignClientContract
}

@FeignClient(name = "http://foo", configuration = Array(classOf[FeignClientConfiguration]))
@RequestMapping(consumes = Array(APPLICATION_JSON_VALUE))
trait FooClient {

  @FeignEndpoint
  @RequestMapping(method = Array(GET), value = Array("/health"))
  def health: Map[String, String]
}
```

**Comment by kflorence** [comment]
Ah, looks like HystrixFeign inherits from `Contract.Default` https://github.com/Netflix/feign/blob/master/hystrix/src/main/java/feign/hystrix/HystrixFeign.java#L22 -- so I would need a way of providing my own contract similar to how you can provide one to Feign itself.

**Comment by spencergibb** [comment]
defining a `@Bean` of a `Contract` is the correct way to do that. Unless there's something for us to do, I'm going to close this as we won't likely do anything specific for scala.

**Comment by kflorence** [comment]
@spencergibb are you saying there is a way to provide a `@Bean` `Contract` that FeignHystrix will use? It doesn't seem to be using the same `Contract` that I have supplied to `@FeignClient` via configuration.

Also, I would love to see a less hacky way of filtering methods -- perhaps just moving that logic into its own method on the `Contract` so it can be overridden like the other methods.

**Comment by spencergibb** [comment]
@kflorence that is how we supply the `SpringMvcContract`.

> see a less hacky way of filtering methods
Not sure what that means.

**Comment by kflorence** [comment]
@spencergibb if you look at my example above, I basically had to copy the entire contents of the current `public List<MethodMetadata> parseAndValidatateMetadata(Class<?> targetType)` method so I could add some extra method filtering logic to get rid of methods without the annotation I applied to them. This is really brittle because if anything else in the upstream method were to change my code would break. If the filtering of methods were isolated, I could just modify that one part instead of the entire method.

As for the `Contract, is there some other way `HystrixFeign` is able to pick up the `Contract` that I have defined in my `FeignClientConfiguration` class above? The only link I see between Hystrix and Feign in regards to the contract is here: https://github.com/Netflix/feign/blob/master/hystrix/src/main/java/feign/hystrix/HystrixFeign.java#L22 -- where it is using `Contract.Default` -- not the one I have supplied via `@Bean`. I should mention I am using `1.1.0.M2` as some of this may have changed already. Also quite likely that I am missing something :)

**Comment by spencergibb** [comment]
You are 1.1.0.M3 is the latest: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientFactoryBean.java#L78-L83.

Calling something 'hacky' because we couldn't anticipate every way someone is going to try and use what we built isn't very constructive.

Pull requests are welcome.

**Comment by kflorence** [comment]
@spencergibb sorry for the misunderstanding, I was referring to my solution as hacky, not the spring-cloud-netflix code. If you think separating the method filtering logic would be useful to others I'd be happy to make a pull request for it.

**Comment by spencergibb** [comment]
NP. If you would benefit, others might as well, so PR away. Sign the [contributors agreement](https://support.springsource.com/spring_committer_signup) if you do.
