### ISSUE TITLE
Hystrix healthcheck NPE

### ISSUE THREAD

**Issue by gorelikov** [spring-cloud/spring-cloud-netflix#653]
Hello! I have received strange healthcheck answer: {..."hystrix":{"status": "DOWN","error": "java.lang.NullPointerException: null”}}
The main problem - i can’t reproduce this localy and I have not found any logs for healthindicator.
I saw it when one of circuit breakers was opened. But don't know exactly which one it was.
I think that spring-cloud/spring-cloud-netflix@5d3a0da can solve my problems. Maybe it can be cherry picked into 1.0.x.RELEASE ?
Does anybody have any other ideas about reasons of this NPE?

**Comment by spencergibb** [comment]
Closed via 4136e397dee662f75a582559d08030890549fd26
