### ISSUE TITLE
Unable to provide my own instance of EurekaServerConfigBean

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#657]
`EurekaServerConfigBean` is created via:

```
@EnableConfigurationProperties(EurekaServerConfigBean.class)
public class EurekaServerInitializerConfiguration ... {
```

Apparently, this kind of instantiation via the `@EnableConfigurationProperties` prevents users from creating their own instance the usual way:

```
@Bean
public EurekaServerConfigBean eurekaServerConfigBean() {
   ...
}
```

This constructs is often used to override and provide our own default values. Would it be possible for SpringCloud to switch to the `@Bean` method as well?

**Comment by spencergibb** [comment]
Sounds reasonable.
