### ISSUE TITLE
many compile errors

### ISSUE THREAD

**Issue by haroldjiang** [spring-cloud/spring-cloud-netflix#658]
downloaded the code under master of spring-cloud/spring-cloud-netflix/spring-cloud-netflix-core .
after imported to eclipse,there are many compile errors like xxx is not defined or xxx constructor is not defined.
is it because of some dependencies got the wrong version?
thanks in advance.

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-netflix#adding-project-lombok-agent

**Comment by haroldjiang** [comment]
thanks very much,it works now @spencergibb

**Comment by haroldjiang** [comment]
Below is some code snippet in SpringMvcContract.java
in this method:
        protected boolean processAnnotationsOnParameter(MethodMetadata data, Annotation[]    annotations, int paramIndex) {
there is the code:
               AnnotatedParameterProcessor processor =
					annotatedArgumentProcessors.get(parameterAnnotation.annotationType());
			isHttpAnnotation |= processor.processArgument(context, parameterAnnotation);

when i have a @FeignClient with method "void createUser(@RequestBody User user);"
annotatedArgumentProcessors will get a null processor because of annotatedArgumentProcessors get  initialized by getDefaultAnnotatedArgumentsProcessors which only used three defautlt processors by PathVariableParameterProcessor,RequestParamParameterProcessor,RequestHeaderParameterProcessor.

and the result is it will throw nullpointer exception.
is this a bug or just something i forget to config.
@spencergibb

**Comment by spencergibb** [comment]
feign doesn't support `@RequestBody`.

**Comment by haroldjiang** [comment]
thanks again
