### ISSUE TITLE
EurekaServer: custom PeerAwareInstanceRegistry implementation not picked up unless defined in "main" class

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#664]
For whatever reason I had to provide my own custom extension of `PeerAwareInstanceRegistry`. However, I found the following odd behaviour depending on _where_ in my code I add my `@Bean` factory method:

- If I add the `@Bean` factory method in a `@Configuration` class other than the main one (i.e. the one with the main method starting the Spring Boot application), the method is never called and the default InstanceRegistry implementation provided by SpringCloud is used;

- If I add the `@Bean` factory method to the _main_ class, the method is invoked and my custom InstanceRegistry is used.

I can't explain that. Is it normal SpringBoot behaviour? Is it caused by "something" in SpringCloud?

A sample application is available at https://github.com/brenuart/spring-boot-pastebin/tree/master/spring-cloud-netflix/issues/gh664:
- `gh664.success.Application` illustrates the first case
- `gh664.failure.Application` illustrates the second case

Running with `Brixtion.M3`

**Comment by spencergibb** [comment]
My guess it has to do with classpath scanning. `@EnableEurekaServer` imports a configuration directly. I suspect if you import your configuration in the failure case it will work. I don't see spring cloud doing anything that causes this specifically. The boot guys might know better. @dsyer @philwebb?

**Comment by philwebb** [comment]
I think the problem is that `eurekaServerBootstrap` is getting instantiated early due to the fact it implements `ServletContextListener`. The early instantiation is cascading a bunch of bean creations, including `PeerAwareInstanceRegistry`. Because the `ServletContextListener` search happens before component scanning the the `@Bean` in `MyConfig` isn't found.

It might be better if Spring Could could make `eurekaServerBootstrap` somehow lazily load the beans that it needs.

**Comment by spencergibb** [comment]
It would be easier to NOT extend `EurekaBootStrap`, it's mostly overridden now anyway. In fact there is only one method not overridden.

**Comment by spencergibb** [comment]
Thanks for the eyes @philwebb, no way I would have caught that.

**Comment by brenuart** [comment]
Reason why we had to override `EurekaBootstrap` is highlighted at https://github.com/spring-cloud/spring-cloud-netflix/issues/380 (provide our own "fixed" version of `InstanceRegistry`).
