### ISSUE TITLE
Rename starters to include `-netflix-`

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#665]
All the starters in the other projects include more context.

`spring-cloud-starter-consul-discovery`, or `spring-cloud-starter-zookeeper-config`.

I would only do this post Brixton, in the C release train.

**Comment by spencergibb** [comment]
Add the new starters in Dalston, remove old starters in Edgware

**Comment by daniellavoie** [comment]
I've started working on this issue. I'm having second though on `spring-cloud-starter-eureka`. When I started on Spring Cloud, I remember getting confused between `spring-cloud-starter-eureka` and `spring-cloud-starter-eureka-server`. 

How about renaming the client to `spring-cloud-starter-netflix-eureka-client` ? I know it's getting long... but we can't escape the`spring-cloud-starter-netflix-eureka-server`.

**Comment by spencergibb** [comment]
@daniellavoie, yeah that makes sense.

**Comment by daniellavoie** [comment]
Adjustment coming through ;) Made a first PR with the old name.

**Comment by spencergibb** [comment]
NP

**Comment by spencergibb** [comment]
@philwebb what does boot do when they rename/deprecate a starter? It would be nice to print a warning that the user is using a deprecated starter.

**Comment by philwebb** [comment]
We update the name and description. See https://github.com/spring-projects/spring-boot/commit/fc00e4cbe0d5a1f9f83e5148df2b36e8b11943f1 for an example.

**Comment by spencergibb** [comment]
Nice, so you do log a warning. Thanks @philwebb

**Comment by daniellavoie** [comment]
Just pushed a new version with the shiny `spring-cloud-starter-netflix-eureka-client`

**Comment by spencergibb** [comment]
@daniellavoie feign, shouldn't be `spring-cloud-starter-netflix-feign` since it's not netflix. Either keep it `spring-cloud-starter-feign` or `spring-cloud-starter-openfeign`. What do you think @adriancole.

**Comment by daniellavoie** [comment]
@spencergibb I understand you point but given this logic, feign should not be part of the spring-cloud-netflix project anymore then. Still, I'll rename it once @adriancole provides us his preference.

**Comment by brenuart** [comment]
`spring-cloud-starter-openfeign` looks good to me as it reflect the actual project name. If you google around `feign` alone then you will be directed to the former Netflix stuff...

My 2 cents...

**Comment by spencergibb** [comment]
@daniellavoie yup, it should move out of netflix. Maybe during 2.0.0.

**Comment by spencergibb** [comment]
I like `spring-cloud-starter-openfeign`

**Comment by daniellavoie** [comment]
What's the next next train after Edgware ? I'll deprecate the old starters with a new issue / PR.

**Comment by ryanjbaxter** [comment]
Finchley

**Comment by spencergibb** [comment]
@daniellavoie so it would be nice to have the deprecations in Edgware so they can be removed in Finchley.

**Comment by dsyer** [comment]
Re-opening. If we are deprecating in 1.4.0, shouldn't we remove in 2.0.0? Also, the turbine-amqp starter can probably be retired in 1.4.0 (it was only kept for backwards compatibility).

**Comment by spencergibb** [comment]
yes, we should remove them. Nice catch on jar vs pom packaging.

**Comment by ryanjbaxter** [comment]
@spencergibb @dsyer I think we should close this issue and open a separate issue for removing the starters in 2.0.0.  This issue was focused on renaming them in Edgware.  I think it will be cleaner if we have a separate issue for Finchley that removes them.

**Comment by ryanjbaxter** [comment]
Closing this issue, opened separate issues for the starters that need to be removed.
