### ISSUE TITLE
Hystrix pulls both "aspectjrt" AND "aspectjweaver" causing duplicate classes

### ISSUE THREAD

**Issue by brenuart** [spring-cloud/spring-cloud-netflix#666]
Hystrix pulls both `org.aspectj:aspectjrt` and `org.aspectj:aspectjweaver` causing duplicate classes on the classpath.

`aspectjweaver` is often used only at compile time and should therefore be declared with scope "provided" in the project but this is unfortunately not the case for Hystrix.

`aspectjrt` is included in `aspectjweaver`, therefore excluding the first from Hystrix dependencies should be ok.

**Comment by spencergibb** [comment]
did you bring this up with hystrix?

**Comment by brenuart** [comment]
Got this via `spring-cloud-starter-zuul`

**Comment by spencergibb** [comment]
I know we can mask the issue by excluding, but the actual problem is in hystrix-javanica, hence have you raised the issue there.

**Comment by brenuart** [comment]
I will raise the issue over the Hystrix project. Stay tuned.
In the meantime, we have excluded `aspectjrt` from our build.
