### ISSUE TITLE
org.springframework.cloud.client.discovery.DiscoveryClient can't get update from eureka

### ISSUE THREAD

**Issue by zhl-home1** [spring-cloud/spring-cloud-netflix#667]
I have 3 services 'A', 'B' and 'C' using same eureka config except application name.
Service 'A' use org.springframework.cloud.client.discovery.DiscoveryClient to find service 'B'.
If 'B' start and register to eureka before 'A', 'A' can find 'B'.
If 'B' start and register to eureka after 'A' , 'A' can't find 'B'.
I can see both of them on eureka:8761 page but com.netflix.discovery.shared.Applications.shuffleVirtualHostNameMap never update.

'C' is a gateway using zull, it can find service 'B' whether start before or after it.

spring-cloud Angel.SR4

**Comment by spencergibb** [comment]
Not enough information. How long did you wait before you tried again? It can take between 30-120 seconds before a new instance shows up. What is your configuration?

**Comment by zhl-home1** [comment]
I wait long enough, more than five minutes

**Comment by zhl-home1** [comment]
bootstrap.xml like this
eureka:
  client:
    serviceUrl:
      defaultZone: http://${ENV:dev}-home1-eureka:8761/eureka/
...

application.xml like this
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    nonSecurePort: 80
    metadataMap:
      instanceId: ${ENV:dev}-${spring.application.name}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${ENV:dev}-eureka:8761/eureka/
...

**Comment by spencergibb** [comment]
We don't support xml files for configuration. They need to be `.yml` extensions. Does the host `dev-eureka` resolve?

**Comment by zhl-home1** [comment]
sorry it is yml actually, my mistake.

**Comment by zhl-home1** [comment]
yes it resolve. DNS an network connection is ok.

**Comment by spencergibb** [comment]
Do you have sample project that recreates the problem?

**Comment by zhl-home1** [comment]
My project is complicated. I need some time to create a sample project.

**Comment by zhl-home1** [comment]
I just switch back to Angel.SR1 and the problem solved.
I use spring-cloud-netflix from very early version.
This issue is never appear until I upgrade form Angel.SR1 to Angel.SR4.

**Comment by zhl-home1** [comment]
Angel.SR1 to Angel.SR3 is ok, but Service 'A' can't see any service start after it, even itself.

I use spring-io-platform 1.1.4.RELEASE and spring-boot 1.2.6.RELEASE.

root project build.gradle:
...
imports {
    mavenBom "io.spring.platform:platform-bom:${springIoPlatformVersion}"
    mavenBom "org.springframework.cloud:spring-cloud-starter-parent:${springCloudVersion}"
  }
...

I override some old dependencies from platform-bom by using spring-boot-gradle-plugin and import spring-cloud-starter-parent after platform-bom.
May be it is dependency problem.

**Comment by dsyer** [comment]
Works for me. I used a client like this:

```
@SpringBootApplication
@EnableDiscoveryClient
@RestController
public class TwoApplication {

	@Autowired
	DiscoveryClient client;

	@RequestMapping("/")
	public List<String> home() {
		return client.getServices();
	}

	public static void main(String[] args) {
		SpringApplication.run(TwoApplication.class, args);
	}
}
```

with config (application.properties) containing only `server.port` and `spring.application.name`. Launched 2 instances with different config with a pause in between while the first one registered with Eureka and I could see it in its own catalog ("/"). The first one to launch didn't list the other in its catalog (or in "/health") as quickly as the second did, but it showed up after a couple of minutes.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
