### ISSUE TITLE
How do I get the response headers and status of a void method?

### ISSUE THREAD

**Issue by bas-velthuizen** [spring-cloud/spring-cloud-netflix#668]
I'm trying to use a Feign-client to attach to a Spring Data-REST RestRepository.

```java
@FeignClient("entity-das")
public interface EntityClient {

    @RequestMapping(value = "/entities", method = RequestMethod.GET, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    PagedResources<Resource<Entity>> listEntities(@RequestParam("page") Integer page, @RequestParam("size") Integer size, @RequestParam("sort") String sort);

    @RequestMapping(value = "/entities/{uuid}", params = {"uuid"}, method = RequestMethod.GET, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    Resource<Entity> getEntity(@PathVariable("uuid") String uuid);

    @RequestMapping(value = "/entities", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
    void createEntity(Entity entity);

    @RequestMapping(value = "/entities/{uuid}", method = RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE)
    void updateEntity(@PathVariable("uuid") String uuid, Entity entity);

    @RequestMapping(value = "/entities/{uuid}", method = RequestMethod.DELETE, consumes = MediaType.APPLICATION_JSON_VALUE)
    void deleteEntity(@PathVariable("uuid") String uuid);
}
```
I would like to retrieve the status code and location header from the response for the void methods, but with a void method there is no way to get to the headers/status.

Changing the method signature form ```void``` to ```ResponseEntity<Entity>``` works, as log as the method returns a body. 

Default, the POST, PUT and DELETE methods on the RestRepository do not return a body, but only a status and a location-header.
For the POST and PUT methods this can be changed by configuring the RestRepository with:

    restConfiguration.setReturnBodyOnCreate(true);
    restConfiguration.setReturnBodyOnUpdate(true);

Sadly this does not apply to the DELETE method. This one returns only a status code, but I do not know how to reach that. Changing the method signature from void to any of the following forms does not work:

* ```ResponseEntity<Entity>```
* ```ResponseEntity<Void>```
* ```ResponseEntity<?>```
* ```ResponseEntity<Object>```
* ```ResponseEntity<String>```

They all fail with a nullpointer exception because of the lack of response body.

Is there a way to retrieve the HTTP status code from a Feign method for a resource that returns no body?

**Comment by dsyer** [comment]
I think just `ResponseEntity` will work. Slightly ugly, so I'm sure we can make it work with `ResponseEntity<Void>`.

**Comment by dsyer** [comment]
Actually `ResponseEntity<Void>` works for me as well. Do you have a sample project that shows the issue?

**Comment by bas-velthuizen** [comment]
I forgot to say: We're using Spring Cloud Angel.SR3 release, and are thinking about going to upgrade to Angel.SR4. Would that change the behaviour?

I'll try to distill a minimal example project.

**Comment by dsyer** [comment]
I was testing with Brixton. I guess there might have been some changes, so try it there too please.

**Comment by bas-velthuizen** [comment]
Hi dsyer,

I've upgraded to Angel.SR4 and the problem has resolved itself.
Thank you for your answer and time.

Cheers,
Bas
