### ISSUE TITLE
ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter

### ISSUE THREAD

**Issue by teramawi** [spring-cloud/spring-cloud-netflix#677]
I'm currently facing an issue when using Spring Cloud in a basic setup for a eureka server with zuul proxy. The issue seems to be the same as described in the Tickets #60 and #516.
Im getting a `ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter` when calling the root path of the started application `http://localhost:8761/`:
[startup-with-exception-log.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48377/startup-with-exception-log.txt)

I last commented on #516 and was asked by @dsyer to create a new ticket with some additional information on the classpath.

My environment:

Info | Detail
---- | ---- 
Gradle | Version 2.9
Maven Bom | 1.0.4.RELEASE
OS | Windows 7 Pro 64bit
IDE | Eclipse Mars1 Release (4.5.1) Build id: 20150924-1200 
Cmd-Line | Git Bash for Windows v2.1  +  Windows-Commandline

Im **not** able to start a working eureka server 
* from Eclipse using Buildship-Plugin
* from Eclipse using Spring Gradle Plugin
* from Eclipse using Main Method
* from any CommandLine using ``gradlew bootRun``

But I **am** able to start a running eureka server when running the jar build by ``gradlew assemble``
I did some research yesterday and analyzed the classpaths used by eclipse buildship, spring gradle and bootRun and compared them with the dependencies in the lib-directory of the assembled jar.

There is no difference in the available libraries (testRuntime dependencies put aside) as you can see when comparing the following files :
[classpath-eclipse-buildship.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48369/classpath-eclipse-buildship.txt)
[classpath-eclipse-spring-gradle.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48370/classpath-eclipse-spring-gradle.txt)
[classpath-gradle-bootRun.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48371/classpath-gradle-bootRun.txt)
[dependencies-gradle-runtime-configuration.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48373/dependencies-gradle-runtime-configuration.txt)
[dependencies-jar-lib-directory.txt](https://github.com/spring-cloud/spring-cloud-netflix/files/48374/dependencies-jar-lib-directory.txt)

Can you please have a look into this?
If you need further information or if I can help with debugging, let me know.

**Comment by dsyer** [comment]
I can't see anything amiss there. Can you share a sample project please (preferably in github)?

**Comment by teramawi** [comment]
Sure, i prepered and forgot about it.
There you go: teramawi/service-gateway-demo

**Comment by dsyer** [comment]
Your app works for me with `./gradlew bootRun` (once I installed the wrapper properly - I think you omitted it by mistake).

It's slightly odd to use the Boot plugin at 1.3 and spring-cloud-netflix 1.0.4, but as it works for me I can't say that's the problem. Any chance you can try it on a proper operating system (e.g. in a VM)?

**Comment by teramawi** [comment]
Thanks for looking into it in detail. The gradle-wrapper indeed was missing as a colleague of mine realized as well.
I asked a colleague of mine to try it out as well and it worked flawless too. Looks like its my machine thats not working properly. 

I deleted gradle cache already and reloaded the wrapper as well but didnt get any change.
Im currently comparing the output of the actuator environment endpoint and will have a deeper look into this as I can't explain the problem.

Thanks again, ill update the issue if i can find the cause of this problem.
