### ISSUE TITLE
RequestInterceptors can still not be specific to a given feign client

### ISSUE THREAD

**Issue by snussbaumer** [spring-cloud/spring-cloud-netflix#683]
I switched to `Brixton.BUILD-SNAPSHOT` today in order to be able to have `RequestInterceptors` specific to a given feign client, as described in the doc and here : https://github.com/spring-cloud/spring-cloud-netflix/issues/288

Unfortunately as commented by @sbuettner on the aforementioned issue the part specific to RequestInterceptors does not look like it's working : It seems that RequestInterceptors are only retrieved from the application context but not from the @Configuration defined in the @FeignClient configuration property.

I think this comes from the following line : https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/FeignClientFactoryBean.java#L103 : 

```java
Map<String, RequestInterceptor> requestInterceptors = this.context.getBeansOfType(RequestInterceptor.class);
```

The context that is used is the application context not the one from the FeignClientFactory

I think the `FeignClientOverrideDefaultsTests`work because the `BarConfiguration` is also defined in the application context.

**Comment by spencergibb** [comment]
The test passes because it is testing `FeignClientFactory` directly. I've reproduced the problem and I'm working on a fix.

**Comment by snussbaumer** [comment]
I've tried again on my setup this morning, and everything works as expected now :smiley: 

Thanks for the fix !

**Comment by Infrag** [comment]
I think this problem is present in RC1 and RC2

**Comment by spencergibb** [comment]
@Infrag if you think there's still a problem, open a new issue with steps to reproduce and, if possible, a project that reproduces the problem.
