### ISSUE TITLE
Allow for more fine-grained Zuul route mapping

### ISSUE THREAD

**Issue by glammr1** [spring-cloud/spring-cloud-netflix#686]
I have a use case that requires route differentiation based on HTTP request method.  Ideally, I’d like to declare something like the following in my route configurations:

    zuul:
      ignoredServices: ‘*’
      routes:
        getSvc1:
          path: /rest/svcs
          serviceId: SVC-ID
          params:
            methods: GET
        postSvc1:
          path: /rest/svcs
          serviceId: SVC-TWO-ID
          params:
            methods: POST

In the above case, the idea is that an HTTP “GET” to /rest/svc would be forwarded to SVC-ID:/svc and an HTTP “POST” to /rest/svc would be forwarded to SVC-TWO-ID:/svc.

Motivation: support common REST API semantics layered on top of an architecture in which storage and retrieval are extremely asymmetric.  E.g. POST /rest/svcs would create an entry using a microservice designed for high data rate ingestion, and GET /rest/svcs would retrieve a subset of entries using one or more microservices designed to periodically summarize the raw data over different time intervals.  More concretely, the POST microservice would write data to something like HDFS; a periodic job would summarize the data in HDFS every 24 hours and write the summary data into a relational database; the GET microservice would then retrieve entry data from the relational database.

I can also see use cases for dynamic routing based on arbitrary data available in HttpServletRequest for reasons similar to the above.  E.g. GET /rest/svcs?startDate=today might route to the microservice responsible for today's data stored in a relational database, but GET /rest/svcs?startDate=01-Jan-1960 &endDate=01-Jan-1961 might route to a microservice that has to retrieve the data from Amazon Glacier or similar long-term storage.

**Comment by spencergibb** [comment]
Somewhat related to #285

**Comment by dsyer** [comment]
I'm not sure we want to make our proxy into a nginx or squid. It's supposed to be simple. I'm not opposed to adding strategies for customization, but this kind of feature out of the box seems like a step too far to me.

**Comment by glammr1** [comment]
Given that I just implemented the feature by adding a custom ZuulFilter that runs after PreDecorationFilter, I'm inclined to agree.  (Incidentally, it seems that #285 could be solved using the same mechanism.)

I'll close this issue.

**Comment by logbon72** [comment]
@glammr1 Sorry to reopen this issue. Can you please share an example of how you were able to achieve this sort of routing using ZuulFilter ?

**Comment by glammr1** [comment]
A good example project is located here:

https://github.com/Netflix/zuul/wiki/zuul-simple-webapp

A class that extends ZuulFilter and is a @Component should be picked up automatically by Spring Boot.
