### ISSUE TITLE
Zuul Proxy routes and service name convention

### ISSUE THREAD

**Issue by stephaneLeroy** [spring-cloud/spring-cloud-netflix#693]
Hello,

I have a need near issue #458 but slightly different. I would like to implements some convention between route and services that are dynamically discovered :

domain-servicename-v1 (registered id in discoveryClient) --> /v1/domain/servicename/**
or
rest-service-v1 --> /v1/rest-service

After some research in spring-cloud-netflix-core I think a good place to implements this enhancement is in ProxyRouteLocator[#around line 199](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRouteLocator.java#L197-214). The way routes are currently bind is a bit static and hard to override without duplicating ProxyRouteLocator code :

```java
String key = "/" + serviceId + "/**";
```

We could add some "overridable" logic here
```java
protected LinkedHashMap<String, ZuulRoute> locateRoutes() {
...
// Need to be done after static route code
String key = "/" + serviceToPathPolicy(serviceId) + "/**"
...
}
protected String serviceToPathPolicy(serviceId) {
   return this.policy(serviceId);
}
```
this.policy is a custom object that transform a service id in a path
rest-service-v1 -> v1/rest-service -> /v1/rest-service/**

I could provide a pull request if I'm not too wrong in the way to do this.

**Comment by dsyer** [comment]
I think a PR would go a long way. If it has this one implementation, plus the default, plus some tests, it is probably good to go.

**Comment by stephaneLeroy** [comment]
Ok thanks, I'll try to provide this soon
