### ISSUE TITLE
NPE in FeignClient call with inherited service definition

### ISSUE THREAD

**Issue by JuliusMischok** [spring-cloud/spring-cloud-netflix#708]
My issue looks very similar to #626, I'm defining an interface as suggested in http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign-inheritance to use it from the service implementation and caller. 

The projects have dependencies to `spring-cloud-starter`, `spring-cloud-starter-eureka-server` and `spring-cloud-starter-feign` with version 1.0.4.RELEASE.

My service definition is:

    public interface ServiceDefinition {
        @RequestMapping(method = RequestMethod.GET, value = "/hello/{id}")
        Name hello(@PathVariable("id") int id);
    }

The service implementation is:

    @RestController
    public class HelloWorldService implements ServiceDefinition {
        public Name hello(@PathVariable("id") int id) {
            // name lookup by id
        }
    }

According to the Spring Cloud link above my caller does the following:

    @FeignClient("service-name")
    public interface HelloWorldClient extends ServiceDefinition {}

A usage of an `@Autowired` instance of `HelloWorldClient` leads to an exception with the following stacktrace:

    2015-12-10 18:40:18.075 ERROR 14488 --- [nio-8082-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
    
    java.lang.NullPointerException: null
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
        at com.sun.proxy.$Proxy63.hello(Unknown Source)
        ...

Changeing `HelloWorldClient` to

    @FeignClient("service-name")
    public interface HelloWorldClient extends ServiceDefinition {
        @RequestMapping(method = RequestMethod.GET, value = "/hello/{id}")
        Name hello(@PathVariable("id") int id);
    }

"solves" the problem, the service call is executed correctly.

**Comment by spencergibb** [comment]
@JuliusMischok version 1.0.4 does not support http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign-inheritance. It is a new feature. The docs for 1.0.x are here http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html
