### ISSUE TITLE
[ Low importance ] How are ports handled? 

### ISSUE THREAD

**Issue by ericfrancis** [spring-cloud/spring-cloud-netflix#718]
I have been troubleshooting an app that uses `spring-cloud-netflix` proxying.

`application.properties`

    server.port=8443
    foo.bar.url=https://foo.bar.com:443/api/fooBar
    zuul.routes.foobar.path=/api/fooBar/**
    zuul.routes.foobar.url=${foo.bar.url}

In the url, I am specifying port `443`.
The app is listening on `8443`.
`Zuul` is forwarding the request to `https://foo.bar.com:8443/api/fooBar`.
Is this the default behavior of `Zuul`?

---

Originally asked on the `zuul` project: https://github.com/Netflix/zuul/issues/195

**Comment by spencergibb** [comment]
No need to [cross post](http://stackoverflow.com/questions/34399399/how-are-ports-handled).

**Comment by spencergibb** [comment]
I noticed you use the foobar key in two different cases: `foobar` & `fooBar`. Is that just a copy and paste error?

**Comment by spencergibb** [comment]
@ericfrancis when I forward to `https://example.com:443` it forwards to the correct port. How are you determining that the forward is going to `8443`? Maybe you could share a sample project that reproduces the problem.

**Comment by ericfrancis** [comment]
'foobar & fooBar.' Yep, just a copy paste error.

I'll share a sample project.

**Comment by spencergibb** [comment]
Closing for lack of feedback.
