### ISSUE TITLE
Content Type is defaulting to application/json

### ISSUE THREAD

**Issue by arun0009** [spring-cloud/spring-cloud-netflix#721]
When using zuul no matter what content type I set, it defaults to application/json. Also, we would like to add in parameter along with application/json., e.g. Content-Type: application/json;v=3. 

```
In the Extended BNF notation of RFC 822, a Content-Type header field value is defined as follows:

Content-Type := type "/" subtype *[";" parameter]
```

**Comment by spencergibb** [comment]
@arun0009 is this with the two routing filters disabled again?

**Comment by arun0009** [comment]
Yes. I see how you setting response headers within SimpleHostRoutingFilter. Closing this issue as it was a fix within my custom Filter. Thanks for your help!
