### ISSUE TITLE
Hystrix dashboard not working when changing "server.servlet-path" configuration

### ISSUE THREAD

**Issue by FrzMe** [spring-cloud/spring-cloud-netflix#725]
When changing the spring boot configuration parameter "server.servlet-path" to something different then "/" the Hystrix dashboard does not work because it is unable to load the file jquery.min.js from the url /webjars/jquery/2.1.1/jquery.min.js 

The servlet path needs to be prepended to the url for this to work correctly.

To reproduce the problem start with https://github.com/spring-cloud-samples/hystrix-dashboard add servlet-path=/spring to the application.yml and access the hystrix dashbaord at http://localhost/7979/hystrix/

**Comment by spencergibb** [comment]
@FrzMe I know it works setting `server.contextPath`, is that a valid workaround?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
