### ISSUE TITLE
Would like to use Hystrix with many independent deployments that have the same ApplicationContext.id, but this breaks the HystrixDashboard

### ISSUE THREAD

**Issue by TabberGit** [spring-cloud/spring-cloud-netflix#740]
In a nutshell, using Docker, for example, where our name, profile(s), and port are the same, when we try to use Hystrix & aggregate data through Turbine to display it to a Hystrix Dashboard, we get bad results due to the code in `org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask`

	private void addServiceData(JsonGenerator json, ServiceInstance localService)
			throws IOException {
		json.writeObjectFieldStart("origin");
		json.writeStringField("host", localService.getHost());
		json.writeNumberField("port", localService.getPort());
		json.writeStringField("serviceId", localService.getServiceId());
		if (this.properties.isSendId()) {
			json.writeStringField("id", this.context.getId());
		}
		json.writeEndObject();
	}

The 'id' field here ends up being the same for all deployments, yet it carries differing information payloads, and that messes up the aggration along the bus into Turbine & the Hystrix Dashboard.

Might I suggest making that a combination of the other three fields?

`localService.serviceId:localService.Host:localService.Port`?

Or, perhaps have a property that could be dropped in?

**Comment by dsyer** [comment]
The id might be defaulting to something insufficiently unique in your environment, but it's really up to you to set it (e.g. with `spring.application.index` if you use the out of the box listeners). The default is controlled in `ContextIdApplicationContextInitializer` from Spring Boot.

**Comment by TabberGit** [comment]
The `spring.application.index` is definitely a step in the right direction, however with say, deployed Docker containers, how will be easily able to assign unique `spring.application.index` values?  This seems to be a bit of a managerial point of failure.

**Comment by spencergibb** [comment]
@TabberGit see #131 if you set `hystrix.stream.amqp.send-id=false` to allow disabling of sending the context id as the metric id, Turbine AMQP then defaults to `serviceId:host:port`. Probably not documented.

**Comment by TabberGit** [comment]
@spencergibb I see where you're going with this, but with the latest `spring-cloud-netflix-hystrix-stream-1.1.0-BUILD-SNAPSHOT` code, it seems to have no effect.  I've put the following into application.yml:

     hystrix:
       stream:
         amqp:
           send-id: false

Somehow, the metrics are still being sent along the same way as previously.  I'm guessing you have code somewhere to try and modify the conditional `if(this.properties.isSendId())`, however this still comes in as true.

If this conditional did cause the `isSendId()` to return false, it would result in the following json, correct:

     origin: {
       host: <host>
       port: <port>
       serviceId: <serviceId>
     }

which would be unique per Eureka registration.

**Comment by spencergibb** [comment]
Sorry, the property name changed when we moved to spring-cloud-stream. `hystrix.stream.queue.send-id=false`.

**Comment by TabberGit** [comment]
Spencer, first off, thank you.  This is exactly the info I needed.

One last question before we close this, I don't quite understand how send-id is mappable to the sendId field.  In those `@ConfigurationProperties` definitions, are dashes used as a replacement for camel casing the field names?

**Comment by spencergibb** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding

So, can we close this?

**Comment by TabberGit** [comment]
Perfect.  Thank you.

Yes, close away.
