### ISSUE TITLE
Turbine Stream RxNetty Server is clashing Tomcat's port

### ISSUE THREAD

**Issue by joaoevangelista** [spring-cloud/spring-cloud-netflix#742]
Using Brixton.BUILD-SNAPSHOT as the day of this writing with tubine-stream dependency and `@EnableTurbineStream` the application starts but reports the Tomcat port is assigned to **-1**, some lines up we can see this log

`2015-12-26 15:17:40.560  INFO 9160 --- [  restartedMain] i.reactivex.netty.server.AbstractServer  : Rx server started at port: 8043`

The assigined port 8043 is the port setted on `server.port` properties, which must be used only by configuring the 'normal' http server (e.g. Tomcat, Undertow, Jetty)

At [TurbineStreamProperties](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-turbine-stream/src/main/java/org/springframework/cloud/netflix/turbine/stream/TurbineStreamProperties.java#L32) we can see the issue, where `server.port` get precendence. Should we use TurbineStream with Tomcat ? Or this is really a misleading configuration property to use ?

**Comment by dinkarthakur** [comment]
I'm also getting the same issue with Brixton.M4 and tubine-stream
It is not able to register with eureka and it remains in STARTING state.

**Comment by joaoevangelista** [comment]
By now setting the property `turbine.stream.port` to another port than `server.port` works for the issue about tomcat's port

I just think it's bad to fall back to `server.port` when the turbine property is not set.

**Comment by dinkarthakur** [comment]
thanks that solve the problem, 
i have another question regarding the turbine stream
if i add
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-netflix-hystrix-stream</artifactId>
</dependency>
```
to the zuul then in eureka dash board is show two instances and one remains always in STARTING state

**Comment by dsyer** [comment]
> I just think it's bad to fall back to server.port when the turbine property is not set.

Seems reasonable to me because there might not be a Tomcat (certainly the user has to choose to add it). If you want to change the default behaviour feel free to send a PR, but please don't change the fact that we fall back to `server.port` if nothing else is using it.
