### ISSUE TITLE
Hystrix automatically enabled when using FeignClients and cannot disable it

### ISSUE THREAD

**Issue by damienpolegato** [spring-cloud/spring-cloud-netflix#750]
I use Feign Clients, Eureka, Zuul with version Brixton.M4 of Spring Cloud. I didn't add @EnableHystrix and didn't add the starter pom but it seems Hystrix still get picked up by other dependencies. I depend on the following :

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-feign</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-ribbon</artifactId>
		</dependency>

Not sure if that is an issue or expected.

Also, according to Spring Cloud Feign doc, Hystrix can be disabled :
> If Hystrix is on the classpath, by default Feign will wrap all methods with a circuit breaker. Returning a com.netflix.hystrix.HystrixCommand is also available. This lets you use reactive patterns (with a call to .toObservable() or .observe() or asynchronous use (with a call to .queue()).
> 
> To disable Hystrix support for Feign, set feign.hystrix.enabled=false.

I did set the property to false in my application.properties but I still see HystrixFeign builder being picked up.

Again, not sure if that is an issue or something I didn't understand from in the docs.

Hope this helps.

**Comment by damienpolegato** [comment]
Hi,

I realized couple days later that I somehow ended up with all my my maven dependencies in my STS build path which may have caused that issue, I'll try again with a clean example and will update the result.

**Comment by marcingrzejszczak** [comment]
Hi!

As the docs say (http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#spring-cloud-feign-hystrix):

> To disable Hystrix support for Feign, set feign.hystrix.enabled=false 

You can disable Hystrix for Feign by using that property.

**Comment by spencergibb** [comment]
If you see an issue, let me know.

**Comment by damienpolegato** [comment]
Hi, no issues. Sorry I didn't get a chance to confirm that earlier.

**Comment by daniellavoie** [comment]
I actually came across the same problem. I'll double check my configuration setup, but it seems like the flag is ignored.

**Comment by hocklo** [comment]
Hi, 

Property feign.hystrix.enabled=false disable all hystrix executions in feign calls. For me this is an issue because in Angel releases by default was disabled and you activated with annotation @HystrixCommand.

Is possible active hystrix for some calls not for all of them?

I tryied the pattern feign.hystrix.<commandKey>.enabled=true (feign.hystrix.operation1.enabled=true) but doesn't work.

Regards!

**Comment by spencergibb** [comment]
@hocklo no. Disable them all and wrap with `@HystrixCommand`.

**Comment by hocklo** [comment]
@spencergibb I do it, but doesn't work. I used HystrixCommand in a feign call with feign.hystrix.enabled=false and hystrix doesn't activated.

**Comment by spencergibb** [comment]
You'll need to open a new issue and provide a project that recreates the problem.

**Comment by hocklo** [comment]
Okey thanks 4all!
