### ISSUE TITLE
bug in metadata name when adding externally in config

### ISSUE THREAD

**Issue by yairogen** [spring-cloud/spring-cloud-netflix#751]
I want to set a system_version key in eureka metadata.

If I set it like this:

```
eureka.instance.metadataMap.system_version=alpha
```

in eureka I see it with an extra redundant '_':

```xml
<metadata>
<system__version>alpha</system__version>
</metadata>
```

**Comment by dsyer** [comment]
That's an artifact of the XML serialization in Eureka. The JSON looks OK to me, and I guess if you deserialize it, you will get the right `Map` back?

**Comment by spencergibb** [comment]
Closing for lack of feedback.
