### ISSUE TITLE
Zuul Proxy integration testing

### ISSUE THREAD

**Issue by AlexejK** [spring-cloud/spring-cloud-netflix#757]
When working with Spring Boot its very easy to write extensive integration tests and mock remote service requests with MockRestServiceServer.

Is there a way to use similar approach to perform additional integration test on ZuulProxy? What I would like to achieve is being able to mock remote servers that ZuulProxy would forward to and validate that all of my ZuulFitlers behaved as expected. However, ZuulProxy is using RestClient from Netflix (deprecated it would seem?) which naturally does not use RestTemplate and I currently can't find a good way of mocking responses from remote services for proxied requests.

A simple scenario is:
I have a microservice that is responsible for handling API Session Key creation and then will act similar to an API Gateway. Forwarding is done with Zuul Proxy to underlying exposed services, and Zuul Filters will detect if Session key is valid or not. An integration test would therefore create a valid session and then forward to a fake endpoint, e.g 'integration/test'. 

Specifying that 'integration/test' is a new enpoint is possible by setting a configuration property on `@WebIntegrationTest`, I can successfully mock all servcies that are being handled via `RestTemplate` but not Zuul forwarding.

**Comment by spencergibb** [comment]
Anything that actually opens up a port like wiremock would work. I've also done it with services actually implemented in the zuul server itself (ie proxy to itself).
