### ISSUE TITLE
@RequestMapping "path" is not considered in Feign contract even though it's an alias for "value"

### ISSUE THREAD

**Issue by sshaghafi** [spring-cloud/spring-cloud-netflix#766]
The following client definition ends up ignoring the "path" argumet in RequestMapping, therefore causing a "java.lang.IllegalStateException: Body parameters cannot be used with form parameters.".

To correct this all you have to do is to change "path" to "value", but since those are aliases the implementation should example both.

```
    @FeignClient(url = "http://localhost:8181")
    interface PlatformClient {
        @RequestMapping(path = "/rest/some/{id}",
                method = RequestMethod.POST,
                produces = MediaType.APPLICATION_JSON_VALUE)
        void execute(@PathVariable(value = "id") String id, SomeObject data);
    }
```

**Comment by spencergibb** [comment]
Good catch.

**Comment by sshaghafi** [comment]
The issue is in `SpringMvcContract` line 90 of version 1.0.4, that only the "value" attribute of RequestMapping is examined.

**Comment by spencergibb** [comment]
We should use `AnnotatedElementUtils` to automatically resolve the aliases.

**Comment by zdRan** [comment]
Request body parameters should be placed in front. try
` void execute( SomeObject data,@PathVariable(value = "id") String id);`

**Comment by jzoe** [comment]
It works! @zdRan
