### ISSUE TITLE
Zuul routes and URL re-writing

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#77]
The customersui demo works really nicely for the stores links:

```
$ curl localhost:9900/stores
{
... // stores
      "_links" : {
        "self" : {
          "href" : "http://localhost:9900/stores/53ea7e2f5d4e248de1e13261"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 10843,
    "totalPages" : 543,
    "number" : 0
  }
}
```

Note that the URIs are re-written by the remote server because we have sent it the x-forwarded-from header (which is the host and port, not including any context path).

It's sort of accidental that /stores is the top-level business URL in the "stores" service, and that's the coincidence that makes it work smoothly. The Zuul route mapping is `/stores/** -> stores -> http://remotestores/stores/**`. 

The problems are that 
1. most remote systems would have useful content at / which is inaccessible
2. most would also have useful content at /something else (not /stores/**) which is also inaccessible
3. many would have a context path, so the home page is actually http://remotestores/foo
4. even for the customersui demo, links that are in a different remote server are not re-written by Spring Data REST, so /customers has direct links in it to the stores service (not to the proxy):

```
$ curl localhos:9900/customers
{
... // customers...
     "_links" : {
        "self" : {
          "href" : "http://localhost:9900/customers/1"
        },
        "stores-nearby" : {
          "href" : "http://stores.cfapps.io/stores/search/findByAddressLocationNear?location=51.462375599999994,-0.1524565&distance=50"
        }
      }
    } ]
  }
}
```

**Comment by ishara** [comment]
This changes breaking my HATEOAS links ,

server:
    contextPath: /WarName
zuul:
  addProxyHeaders: true
  routes:
    api:
      path: /virtual-rest-url/**
      url: http://localhost:8090/real-service/


Request - http://localhost:8080/WarName/virtual-rest-url/somne-action
Return Responce HATEOAS link
  Expected - http://localhost:8080/WarName/virtual-rest-url/somne-action2
  Actual -  http://localhost:8080/WarName/virtual-rest-url/real-service/somne-action2


Any idea ?

**Comment by dsyer** [comment]
This issue was closed nearly 3 years ago. Any problem you are having today might be solved by upgrading or, if that doesn't work, please post a complete sample in a new issue (or on gitter.im if you want to discuss it first).
