### ISSUE TITLE
Thread pools not shown on Hystrix dashboard

### ISSUE THREAD

**Issue by sslavic** [spring-cloud/spring-cloud-netflix#770]
In my SpringBootApplication with EnableZuulProxy, route definitions are referencing service IDs, eureka is disabled, and service IDs are mapped to static lists of servers. Hystrix dashboard shows Circuit metrics/state, but thread pools are "Loading" and eventually "Unable to connect to Thread Pool Metric Stream." message appears.

No custom thread pools have been defined/configured. I still expect default thread pool stats to appear.

Is there a configuration option or something else required to have thread pool metrics to appear on hystrix dashboard?

I'm using Spring Boot 1.3.1, Spring Cloud 1.1.0.M4

**Comment by spencergibb** [comment]
If all your hystrix commands are from zuul, there are no thread pools as it uses semaphore isolation.

**Comment by sslavic** [comment]
Thanks for heads up!
