### ISSUE TITLE
eureka port error

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#772]
![image](https://cloud.githubusercontent.com/assets/3667080/12352806/401d49a6-bbc4-11e5-9b8b-ff1c0a5b30f8.png)

**Comment by spencergibb** [comment]
Please provide more information than a picture. When filing a bug, please provide as much context as needed to reproduce the problem.

**Comment by matheen** [comment]
I am also getting the same error and this will work properly when I use 1.2.8 version of Spring Boot. Here is the scenario to recreate it

1. Create a Eureka server and deploy it with in the built in tomcat using 1.3.2.RELEASE version of boot (Used Spring Starter Project from STS). Check Eureka server is coming up in the default port (http://localhost:8761/)
2. Create one Service (running on 7878 port) and register in above server. I will register successfully. But when you click the service in Eureka server (below "Instances currently registered with Eureka"  and under Status column, it takes you to http://....:8080.

**Comment by dsyer** [comment]
Works for me. Did you use Spring Cloud Netflix 1.1.0.BUILD-SNAPSHOT?

**Comment by matheen** [comment]
Here are my Pom files

Client:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>

<groupId>com.matheen.uma.jpa</groupId>
<artifactId>uma.jpa</artifactId>
<version>0.0.1-SNAPSHOT</version>
<packaging>jar</packaging>

<name>uma-jpa-service</name>
<description>UMA with JPA</description>

<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.3.2.RELEASE</version>
<relativePath /> 
</parent>

<properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<java.version>1.8</java.version>
</properties>

<dependencies>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-eureka</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-web</artifactId>
</dependency>

<dependency>
<groupId>mysql</groupId>
<artifactId>mysql-connector-java</artifactId>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-test</artifactId>
<scope>test</scope>
</dependency>
</dependencies>

<dependencyManagement>
<dependencies>
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-parent</artifactId>
<version>Brixton.BUILD-SNAPSHOT</version>
<type>pom</type>
<scope>import</scope>
</dependency>
</dependencies>
</dependencyManagement>

<build>
<plugins>
<plugin>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-maven-plugin</artifactId>
</plugin>
</plugins>
</build>

<repositories>
<repository>
<id>spring-snapshots</id>
<name>Spring Snapshots</name>
<url>https://repo.spring.io/snapshot</url>
<snapshots>
<enabled>true</enabled>
</snapshots>
</repository>
<repository>
<id>spring-milestones</id>
<name>Spring Milestones</name>
<url>https://repo.spring.io/milestone</url>
<snapshots>
<enabled>false</enabled>
</snapshots>
</repository>
</repositories>

</project>


Server :

<?xml version="1.0" encoding="UTF-8"?> <project xmlns="
http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion> <groupId>com.matheen.eureka</groupId>
<artifactId>uma.eureka</artifactId> <version>0.0.1-SNAPSHOT</version>
<packaging>jar</packaging> <name>eureka-service</name> <description>Eureka
Server For UMA</description> <parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>1.3.2.RELEASE</version> <relativePath/>  </parent> <properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
<java.version>1.8</java.version> </properties> <dependencies> <dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-eureka-server</artifactId> </dependency>
<dependency> <groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-test</artifactId> <scope>test</scope>
</dependency> </dependencies> <dependencyManagement> <dependencies>
<dependency> <groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-parent</artifactId>
<version>Brixton.BUILD-SNAPSHOT</version> <type>pom</type>
<scope>import</scope> </dependency> </dependencies> </dependencyManagement>
<build> <plugins> <plugin> <groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-maven-plugin</artifactId> </plugin> </plugins>
</build> <repositories> <repository> <id>spring-snapshots</id> <name>Spring
Snapshots</name> <url>https://repo.spring.io/snapshot</url> <snapshots>
<enabled>true</enabled> </snapshots> </repository> <repository>
<id>spring-milestones</id> <name>Spring Milestones</name> <url>
https://repo.spring.io/milestone</url> <snapshots> <enabled>false</enabled>
</snapshots> </repository> </repositories> </project>

**Comment by dsyer** [comment]
Still works for me. Maybe you need to refresh your snapshots?

**Comment by matheen** [comment]
Thanks Dave. Yes after refresh of the Snapshots it is working. Thanks for
your help
