### ISSUE TITLE
Zuul - Large files upload fix does not work anymore since Brixton.M2

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#773]
Since Brixton.M2 the fix @dsyer introduced related to issue #254 does not work anymore.

Files are buffered in memory before being relayed to downstream service.

**Comment by dsyer** [comment]
Can you describe how to test this please? What did you do and what was the outcome? A sample app would help spot any obvious errors in your approach.

**Comment by aivans** [comment]
Just follow the docs created by yourself for the Large files upload through Zuul.

The issue seems to be related to this commit:
https://github.com/Netflix/zuul/commit/dd38704c3f1a37fd05da674497fae6a2c16c1e6d
"
- Change HttpServletRequestWrapper to buffer chunked as well as non-chunked request bodies.

-- And allow all request buffering to be disabled using a Servlet or ServletFilter init parameter.

"

**Comment by dsyer** [comment]
Did you try setting "buffer-requests=true" in the filter/servlet then?

**Comment by dsyer** [comment]
Actually, the default is false, and that should be what you need right?

**Comment by aivans** [comment]
I think there is a problem with SpringCloud.
Netflix changed behavior related to HttpServletRequestWrapper.
If the buffer-requests==false, they don't use the HttpServletRequestWrapper:
-In ZuulRunner:
```
    public void init(HttpServletRequest servletRequest, HttpServletResponse servletResponse) {

        RequestContext ctx = RequestContext.getCurrentContext();
        if (bufferRequests) {
            ctx.setRequest(new HttpServletRequestWrapper(servletRequest));
        } else {
            ctx.setRequest(servletRequest);
        }
```

But SpringCloud wraps the request in a:
```
Servlet30RequestWrapper extends HttpServletRequestWrapper
```

And at some point this happens (Stacktrace):
```
Servlet30RequestWrapper(HttpServletRequestWrapper).parseRequest() line: 136	
Servlet30RequestWrapper(HttpServletRequestWrapper).getParameter(String) line: 294	
DebugFilter.shouldFilter() line: 52	
DebugFilter(ZuulFilter).runFilter() line: 109	
FilterProcessor.processZuulFilter(ZuulFilter) line: 197	
FilterProcessor.runFilters(String) line: 161	
FilterProcessor.preRoute() line: 136	
ZuulRunner.preRoute() line: 105	
ZuulServlet.preRoute() line: 125	
ZuulServlet.service(ServletRequest, ServletResponse) line: 74	
```
The HttpServletRequestWrapper.parseRequest() gets called and basically the ```buffer-requests``` flag is ignored, and the "tru" flow kicks in in the parseRequest() method.

**Comment by aivans** [comment]
This looks quite tricky and quite coupled with Zuul internals.

**Comment by aivans** [comment]
Thank you  Dave, I'll test it tomorrow.

**Comment by aivans** [comment]
Hi Dave,

It works nicely.

I noticed a new behavior also.
The client does not need to set Transfer-Encoding chunked anymore. For the first time my JMeter tests are running, and it sends Content-Length.
So both Chunked and C-L styles work.

**Comment by dsyer** [comment]
Great. Thanks for the update.
