### ISSUE TITLE
How can custom feign request to send model data？

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-netflix#776]
```java
@FeignClient("xx")
interface UserService{
  
   @RequestMapping(value="/users",method=GET)
   public List<User> findBy(User user);
}

userService.findBy(user);
```

Too many parameters, hope packaged into model

**Comment by Koizumi85** [comment]
So you want, that the fields of the User class are put into your request as URL-Parameters?
Not 100% sure, but i don't think this is possible at the moment.

**Comment by Dreampie** [comment]
I want write a encoder to convert user to jsonString(user={userJson}) and send it to server,server convert it back to User.but I don't know how to resolve it

**Comment by Koizumi85** [comment]
Why not sending the JSON as a Post?
If you simply change the your code to 

```
@FeignClient("xx")
interface UserService{

   @RequestMapping(value="/users",method=POST)
   public List<User> findBy(User user);
}
```

this should work out of the box.

**Comment by Dreampie** [comment]
read data use GET，rest recomended

**Comment by Koizumi85** [comment]
Yes, but why would you need a complete user model for reading data... In most cases the user's id would be enough to load related stuff, or?

**Comment by Dreampie** [comment]
sometimes you must filter and page results，too many parameters

**Comment by Koizumi85** [comment]
Yes, indeed. Unfortunately i can't tell you how to write your own encoder to solve this (or if it is even possible)
But there is another issue which would solve your problem i think:
https://github.com/spring-cloud/spring-cloud-netflix/issues/609

So you could ask the author of this issue, what he think when he could finish the work on it.

**Comment by Dreampie** [comment]
yes，thanks

**Comment by spencergibb** [comment]
I believe object parameters are only supported in feign by default as the body of the request. You would need to write code to support that, or submit an issue to feign.
