### ISSUE TITLE
ZuulFilterInitializer not compatible with @HystrixCommand annotations

### ISSUE THREAD

**Issue by aditzel** [spring-cloud/spring-cloud-netflix#786]
When using the javanica HystrixCommand annotations with a custom ZuulFilter you get a classcast on line 58 of the filter initializer:

    registry.put(entry.getKey(), entry.getValue());

The filter that is registered if actually of type com.sun.proxy.Proxy, not com.netflix.zuul.ZuulFilter. This results in not being able to use annotation based hystrix commands.

Sample code available at: 

https://github.com/aditzel/zuul-javanica-hystrix-classcasterror

**Comment by dsyer** [comment]
You can use concrete type (subclass proxies) if you just set `spring.jmx.proxy-target-class=true`. I imagine that would fix it the immediate problem. But Zuul is highly thread bound so I expectr it will blow up in other ways unless you can stick to SEMAPHORE isolation.

**Comment by aditzel** [comment]
I tried using that property but the application still fails to load with a class cast exception.

**Comment by dsyer** [comment]
There isn't really enough information there to diagnose an actual problem, but it sounds like just a classpath issue probably (and unrelated to the original question). Did you check your dependencies? Stick to latest snapshots if you can.

**Comment by aditzel** [comment]
Turns out it's not a classpath issue. Since Javanica uses AspectJ you can get your application to proxy the target classes by adding this to one of your `@Configuration` classes.

```java
@EnableAspectJAutoProxy(proxyTargetClass=true)
```
