### ISSUE TITLE
DiscoveryClientConfigServiceBootstrapConfiguration not respecting defined home page while fetching Spring Config Server over Eureka

### ISSUE THREAD

**Issue by dpalinic** [spring-cloud/spring-cloud-netflix#787]
**Description**
In a scenario where services asks Config server for properties over Eureka, and Config server is not standalone jar, but it is war deployed on Tomcat with provided context, Eureka will return correct path to registered Config server, but DiscoveryClientConfigServiceBootstrapConfiguration will not respect that during the properties load. Instead of respecting home page url, it takes just host and threats it like final url for Config server. Result is for service unable to get the properties since Config server is not there (missing context path - home page path).

Setup:
- Eureka server
- Config server registered to Eureka server and deployed on external Tomcat with following port and context:
  - port: 8280
  - context: configuration-server
  - full url: `http://localhost:8280/configuration-server`
- Custom service called MediaService which asks for Config server through Eureka discovery

**Actual behavior**
MediaService tries to fetch properties from config server from url: `http://localhost:8280/`

**Expected behavior**
MediaService tries to fetch properties from config server from url: `http://localhost:8280/configuration-server`

**Where is the problem actually?**
Class: DiscoveryClientConfigServiceBootstrapConfiguration
Method: `private String getHomePage(InstanceInfo server)`
Line: 95

Following method is probably wrong because:
- in InstanceInfo argument, all information (like host, homepage etc.) is already received from Eureka in the line 71
- using just getUri(), homepage (context) is not respected

```java
private String getHomePage(InstanceInfo server) {
    List<ServiceInstance> instances = this.client
       .getInstances(this.config.getDiscovery().getServiceId());
    if (instances == null || instances.isEmpty()) {
        return server.getHomePageUrl();
    }
    return instances.get(0).getUri().toString() + "/";
}
```

It should be just this since server is already loaded with all instance information received from Eureka:
```java
private String getHomePage(InstanceInfo server) {
    return server.getHomePageUrl();
}
```

In that way, defined home page will be respected instead of trimming it like it is in current code.

**Comment by dpalinic** [comment]
I just figured out that I need to put following in the `bootstrap.yml` of the config server for this to work properly:
eureka:
  instance:
    metadataMap:
      configPath: /configuration-server

**Comment by dsyer** [comment]
So it's just a documentation issue?

**Comment by dpalinic** [comment]
Yes, documentation update to explain that `configPath` needs to be set in case of non-default context would be great.

Also, getHomePage method looks strange to me. It queries for list of instances again, but it already has instance to calculate homepage from (received through `server` method argument). There is a chance I didn't get the idea of what that code should do, but it looks strange to me to ask for a list of instances again...
