### ISSUE TITLE
"Demo" test fails

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-netflix#804]
It's not part of the regular CI build because the class name is not in `*Tests`, but it fails with an error in the HTTP client. Needs to get fixed I guess.

**Comment by dsyer** [comment]
The Demo is actually a copy of `FeignContentEncodingTest` (I think) which also fails and isn't included in CI builds because of its name. Needs fixing.

**Comment by marcingrzejszczak** [comment]
`FeignContentEncodingTest` passes properly and I'm pretty sure that it gets included:

taken from `spring-boot-starter-parent-1.3.2.RELEASE.pom`

```

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<configuration>
						<includes>
							<include>**/*Tests.java</include>
							<include>**/*Test.java</include>
						</includes>
						<excludes>
							<exclude>**/Abstract*.java</exclude>
						</excludes>
					</configuration>
				</plugin>
```
