### ISSUE TITLE
Feign Inheritance Support multiple produces

### ISSUE THREAD

**Issue by SirWayne** [spring-cloud/spring-cloud-netflix#808]
I want to use the feign inheritance support, but the the SpringMvcContract has a problem with multiple produces and consumers.

Example from http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign-inheritance:

``` java
public interface UserService {
@RequestMapping(method = RequestMethod.GET, value ="/users/{id}",  produces = { "application/hal+json", MediaType.APPLICATION_JSON_VALUE })
    User getUser(@PathVariable("id") long id);
}
```

``` java
@RestController
public class UserResource implements UserService {

}
```

``` java
@FeignClient("users")
public interface UserClient extends UserService {

}
```

``` java
Caused by: java.lang.IllegalStateException: Method userClient can only contain at most 1 produces field. Found: [application/hal+json, application/json]
    at feign.Util.checkState(Util.java:117)
    at org.springframework.cloud.netflix.feign.support.SpringMvcContract.checkAtMostOne(SpringMvcContract.java:113)
    at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseProduces(SpringMvcContract.java:195)
    at org.springframework.cloud.netflix.feign.support.SpringMvcContract.processAnnotationOnMethod(SpringMvcContract.java:103)
    at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:92)
    at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:61)
    at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
    at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:55)
    at feign.Feign$Builder.target(Feign.java:198)
    at feign.Feign$Builder.target(Feign.java:194)
    at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:142)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
    ... 25 more
```

It would be better to use the first producer or consumer

**Comment by spencergibb** [comment]
So the `produces` and `consumes` attributes are put in the `Accept` and `Content-type` headers respectively. We could probably support [multiple values](https://www.w3.org/Protocols/HTTP/HTRQ_Headers.html#z3) for `Accept`. I don't think it would be better to pick the first consumer though. That implies order is important where there really isn't. This is one of the dangers of sharing client and server side interfaces.

**Comment by michahirsch** [comment]
As I know, SpringMVC uses the order. For example if you don't fill out the `Accept` header in the request, Spring will return the body as `Content-Type` of the first value in the `produces` list. Maybe it would also be OK, to implement the behavior in your client by picking the right `consumes` and `produces` extending the `SpringMvcContract` class?

**Comment by spencergibb** [comment]
@dsyer @adriancole @marcingrzejszczak @mstine any thoughts?

**Comment by dsyer** [comment]
Isn't feign the inverse of a controller? So multiple "produces" translates to multiple Accept values (which is totally legal). I imagine users will not always get what they want still, especially if they are playing with fire (i.e. Using the same interface on client and server), but logically we can easily support it.

**Comment by spencergibb** [comment]
Yup, I'm fine with multiple Accept, what about picking the first consumes?

**Comment by cforce** [comment]
Would't it be possible to separate this two behaviours on server side by two segregated interfaces inheriting common anotation with consume/accept in the childs. For Feign then it's no choice necesarry

**Comment by adriancole** [comment]
apart from server-side interfaces generally making my brain hurt...

multiple header values should be supported in Feign. ex a contract could use `RequestTemplate.header(String name, String... values)`.

Content negotiation implies codec fanciness which is not out of the box in Feign. You'd likely need a delegating codec that switches on media type. Since media types can have parameters like charset, literally a switch might not work.

**Comment by tjuchniewicz** [comment]
I don't see any disadvantages of picking up the first produces or consumes in my environment. Currently I have to maintain such patch for my project.

Maybe before we agree how to implement this feature, using the best available approach, we can just drop verification code and pick up the first one? (like in [JAXRSContract](https://github.com/OpenFeign/feign/blob/e1ad7fc75d5abb8227e34db85d2f50034eb34c88/jaxrs/src/main/java/feign/jaxrs/JAXRSContract.java#L109))

**Comment by cforce** [comment]
I this fixed in Dlaston as @tjuchniewicz  desribed?

**Comment by spencergibb** [comment]
No @cforce
