### ISSUE TITLE
Update servo to 0.10.1

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#809]
See https://github.com/Netflix/eureka/issues/704

**Comment by brharrington** [comment]
I'm not sure if it still matters for spring, but 0.10.0 was the last version to support java 6. Everything after that expects java 8. If I recall correctly, that is why spring was using an older version.

**Comment by spencergibb** [comment]
ah, very much so at the moment.

**Comment by brharrington** [comment]
From the eureka ticket, it looks like there is a single small commit that is the main change of interest. We can look at cherry picking that commit and creating a 0.10.1 servo release.

**Comment by spencergibb** [comment]
That would be helpful!

**Comment by brharrington** [comment]
There is now a 0.10.1 servo release with a backport of Netflix/servo#362.

**Comment by spencergibb** [comment]
Thanks!
