### ISSUE TITLE
Zuul based proxy registers with port 0 in eureka starting with brixton M4

### ISSUE THREAD

**Issue by pcornelissen** [spring-cloud/spring-cloud-netflix#812]
There is still a problem with the eureka registration for applications that use @EnableZuulProxy. For non-zuul applications this was fixed by Dave in #789. I have two projects with zuul based gateways and both show the same symptoms. 

I have a showcase here:
https://github.com/orchit/spring-microservices-oauth/tree/enableOAuth

@marcingrzejszczak The startAll.sh is included there. (Make sure that you are on the enableOAuth branch!)

**Comment by pcornelissen** [comment]
```
#!/usr/bin/env bash

mvn clean package -U -DskipTests
export MODE=service
export PID_FOLDER=.
export LOG_FOLDER=.

(cd ./configserver/target; ./configserver-*.jar start)
#configserver needs to be up!
sleep 5

(cd ./registry/target; ./registry-*.jar start)

(cd ./apigateway/target; ./apigateway-*.jar start)

(cd ./authserver/target; ./authserver-*.jar start)
(cd ./commentsservice/target; ./commentsservice-*.jar start)

(cd ./portal/target; ./portal-*.jar start)

(cd ./taskservice/target; ./taskservice-*.jar start)

(cd ./userservice/target; ./userservice-*.jar start)

```

**Comment by marcingrzejszczak** [comment]
I'm on master and I have the same issue with snapshots. Actually I've managed without the script (I've just ran it manually)

**Comment by marcingrzejszczak** [comment]
hi @pcornelissen . I've been investigating the issue and it's really complex due to the asynchronous nature of resolving the used port. In Eureka v2 there should be a much better way to deal with this issue so for now I guess you'll have to provide a fixed port number,

**Comment by dsyer** [comment]
> you'll have to provide a fixed port number

Or not use bootstrap first (i.e. don't try to use eureka in the bootstrap phase).

**Comment by pcornelissen** [comment]
Well, as you can see in the example project the ports are fixed.
They are all defined in the corresponding bootstrap.yaml
and the config for eureka is pulled from the config server which is configured with its real hostname and port.

How can I avoid to use eureka in the bootstrap phase?

**Comment by dsyer** [comment]
If you use a fixed port you don't have to worry about the bootstrap. It's only with `server.port=0` that we can't change the registration.

**Comment by marcingrzejszczak** [comment]
You have a 0 port in the non secure port AFAIR

**Comment by pcornelissen** [comment]
Ahh, found it!
The port 0 was not set as management port for spring, but as 

eureka.instance.non-secure-port: 0

Because I copied it from my project where I had the management port randomized for the api gateway to limit the security implications as this service will be exposed to the internet.
Without this setting it worked. Why is there a separate setting for this anyway? Couldn't eureka get this from the standard spring properties like server.port?

**Comment by dsyer** [comment]
It does (server.port is the default).

**Comment by pcornelissen** [comment]
Ah ok, I am not sure why this setting is in my config anyway. I think I have copied it from a tutorial a while ago. I really should go through my code and try to remove all that garbage that accumulates over the last year...
