### ISSUE TITLE
Naming convention of health check properties should follow Spring Boot?

### ISSUE THREAD

**Issue by kongslund** [spring-cloud/spring-cloud-netflix#814]
In Spring Boot [the naming](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties) of a health check property `bar` for service `foo` is `management.health.foo.bar`, e.g. `management.health.mongo.enabled`.

For the Eureka client the [naming is](https://github.com/spring-cloud/spring-cloud-netflix/blob/c1e567afc7281055c98ef376c34dca3863790add/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClientConfiguration.java#L207) `eureka.client.healthcheck.enabled`.

Should it not follow Spring Boot's naming convention instead?

**Comment by dsyer** [comment]
Not really no. The `eureka.*` configuration properties are defined by NetflixOSS. There is some integration between the Spring Boot health indicators and the Eureka  concept of a health check, but they aren't really the same thing.
