### ISSUE TITLE
Eureka sets management port always to 8080 when server.port ist set but management.port is not set

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-netflix#817]
When I configure server.port (let's say 9090), but not management.port, the meaning for Spring Boot Actuators is: **Use the same port as server.port, that is: 9090.**

On the other hand, Eureka will register the health and info Endpoint  under port 8080 in this case, and not 9090.

I think it is the following line in EurekaClientAutoConfiguration:

`
@Value("${management.port:${MANAGEMENT_PORT:${PORT:8080}}}")
int managementPort;
`

That is, it obviously does not support the case where managementPort is null  (like ManagementServerProperties does), but always falls back to 8080.

Maybe this could be easily fixed by using "server.port" as the  fallback, when "managment.port" is not set.

**Comment by dsyer** [comment]
I think this is already fixed (https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L79).

**Comment by stefanocke** [comment]
Nice, thanks. Sorry for not looking at HEAD...
