### ISSUE TITLE
zuul proxy with default setting adding header values twice in response

### ISSUE THREAD

**Issue by aayushgupta** [spring-cloud/spring-cloud-netflix#819]
zuul configuration:
zuul.routes.splash.path=/splash/**
zuul.routes.splash.url=http://localhost:8080/myapp2/splash/

Below is the output of the curl command to hit a URL that is being proxied by zuul to be forwarded to 
another url.

```
STATE: DO => DO_DONE handle 0x600057370; line 1337 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057370; line 1464 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057370; line 1474 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: *
**< Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
< Access-Control-Max-Age: 1800**
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< X-Application-Context: mayapp1:dev:33
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
**< Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 1800**
< Date: Wed, 10 Feb 2016 21:45:45 GMT
< Vary: Accept-Encoding
< X-Application-Context: myapp2:dev
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
```

**Comment by dsyer** [comment]
Spring Cloud is not adding those `Access-Control-*` headers, so your app must be doing that itself independent of Zuul. Do you have a filter that does that unconditionally for instance?

**Comment by dsyer** [comment]
The `X-Application-Context` header is added by Spring Boot. You can switch it off by setting `management.add-application-context-header=false`.

**Comment by nodje** [comment]
I've posted an issue on https://github.com/spring-guides/tut-spring-security-and-angular-js/issues/73 regarding the same problem.

The header keys being duplicated are more evident in my case and in the Spring tutorial case.

**Comment by dsyer** [comment]
The Spring Security configuration for the proxy doesn't explicitly exclude the header writers, so they get added in the remote service and then again in the gateway. It's nothing to do with Zuul really.  You can switch it off like this:

```
@Override
protected void configure(HttpSecurity http) throws Exception {
  http.headers().disable()
  ...
}
```

**Comment by aayushgupta** [comment]
Thanks @dsyer .. i will test it.

**Comment by nodje** [comment]
Good catch, ``http.headers().disable()`` just does the job. 
Response headers are now clean.
Just ``X-Application-Context`` gets added by each application, but this can actually be helpful for debugging.
and ``management.add-application-context-header=false`` turns it off just as expected.
Cheers
