### ISSUE TITLE
SimpleHostRoutingFilter messes up empty query parameters

### ISSUE THREAD

**Issue by nbyl** [spring-cloud/spring-cloud-netflix#824]
When routes are configured using zuul-Properties the SimpleHostRoutingFilter messes up given empty query parameters. When a request is coming in looking like this
```
/resource?param
```
it will be forwarded to the receiving side like this:
```
/resource?param=
```
A pull request correcting this behaviour will follow later.

**Comment by nbyl** [comment]
This issue can be fixed merging the pull request #825.

**Comment by dsyer** [comment]
Duplicates #825
