### ISSUE TITLE
Zuul router re-writes POST body with query params for Content-Type x-www-form-urlencoded requests

### ISSUE THREAD

**Issue by tehjakey** [spring-cloud/spring-cloud-netflix#834]
I believe the zuul router should not modify the incoming request body before sending it to a downstream service.

I am using 'org.springframework.cloud:spring-cloud-starter-zuul:1.0.3.RELEASE'

To reproduce the issue...
**Given the following request to Zuul** 
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d 'somebody=bvalue1' "http://localhost:8080/api/v1/account/ticket?somequery=qvalue1"
```

**Then **the resulting call from Zuul to the dowstream service contains an unexpected body of "somequery=qvalue1&somebody=bvalue1"

Here's logging that shows the request Zuul sent to the downstream service.
```
2016-02-19 14:45:45.798 Request received:
POST /ticket?somequery=qvalue1 HTTP/1.1
User-Agent: curl/7.43.0
Accept: */*
Content-Type: application/x-www-form-urlencoded
x-forwarded-host: localhost:8080
x-forwarded-prefix: /api/v1/account
z-tx-id: af872608-ff5f-4c2c-9a98-489bdda727fe
Accept-Encoding: gzip
Content-Length: 34
Host: localhost:9999
Connection: Keep-Alive

somequery=qvalue1&somebody=bvalue1
```

I believe the behavior of re-writing the body is implemented in the method FormBodyWrapperFilter.FormBodyRequestWrapper::buildContentData()

**The example above has the following route config..**

```
routes: 
  account-services:
      path: /api/v1/account/**
      url: http://localhost:9999
```

**Comment by spencergibb** [comment]
This sounds familiar, have you tried it with `Brixton.M5` or a snapshot?

**Comment by tehjakey** [comment]
I have not, but I will give that a try.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
