### ISSUE TITLE
Eureka peer to peer server not replicating applications registered

### ISSUE THREAD

**Issue by ubalaji** [spring-cloud/spring-cloud-netflix#838]
I have peer1 and peer 2 configuration. Both Eureka instances starts and have not able to replicate applications registered. I am not sure why client applications can not be replicated. Both eureka instances are configured to run on same server and the client is located on another server. I see the following message on the Eureka (8761) instance and as you see the the last line indicates replication=false. I an not sure why replication set to false and also notice in the screen shots the registered replicas information displayed. Also at the same time it says it is unavailable as shown in screenshot. How do I enable replication?

I have seen many threads and reviewed documents, other shared knowledge and could not get them working.

Has anyone come across this issue and how did you trouble shoot.

2016-02-19 09:56:56.362 WARN 2548 --- [nio-8761-exec-9] c.n.e.registry.Abstract
InstanceRegistry : DS: Registry: lease doesn't exist, registering resource: EMP
LOYEETO-SERVICE - 10.77.0.140:ca8070c6e0344822b0eec204d67799d2

2016-02-19 09:56:56.362 WARN 2548 --- [nio-8761-exec-9] c.n.eureka.resources.In
stanceResource : Not Found (Renew): EMPLOYEETO-SERVICE - 10.77.0.140:ca8070c6
e0344822b0eec204d67799d2

2016-02-19 09:56:56.378 INFO 2548 --- [nio-8761-exec-5] c.n.e.registry.Abstract
InstanceRegistry : Registered instance EMPLOYEETO-SERVICE/10.77.0.140 with stat
us UP (replication=false)

![](https://cloud.githubusercontent.com/assets/17342164/13183943/1645e10c-d6ee-11e5-9ff5-104c55095370.png)

![](https://cloud.githubusercontent.com/assets/17342164/13184025/7efadfb8-d6ee-11e5-8082-988a71dafd90.png)

Thank you

**Comment by dsyer** [comment]
Can you link to a sample project that reproduces the issue please?

**Comment by ubalaji** [comment]
Please see the following configurations.

The following are peer1 and peer2 confogurations
---------------------------------
server:
  port: 8761

spring:
  profile: peer1
  
eureka:
  instance:
    hostname: peer1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://elm.VERIZON.COM:8762/eureka/
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

---------------------------------
server:
  port: 8761

spring:
  profile: peer1
  
eureka:
  instance:
    hostname: peer1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://elm.VERIZON.COM:8762/eureka/
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
---------------------------------
server:
  port: 8762

spring:
  profile: peer2
  
eureka:
  instance:
    hostname: peer2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://elm.VERIZON.COM:8761/eureka/
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

-------------------------------------------------

The following is the application configuration

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://113.128.163.42:8761/eureka/,http://113.128.163.42:8762/eureka/
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

**Comment by ubalaji** [comment]
HI Dave,

Also I downloaded eureka-master project and changed application.yml file. I have already posted peer1, peer2 and application configuration. Thanks

**Comment by dsyer** [comment]
Thanks. I edited your configs to add markdown formatting (please check that I didn't change anything). Please use markdown to format code snippets and logs.

**Comment by aivans** [comment]
```
serviceUrl:
      defaultZone: http://elm.VERIZON.COM:8762/eureka/
```
As far as I remember the port is not enough. You need different hostnames for 2 eureka instances running on the same machine on different ports.
My Windows workaround was to add two hostnames in the hosts file that point to localhost. Then you use these virtual hosts to in Eureka cluster setup.

Same here:
```
defaultZone: http://113.128.163.42:8761/eureka/,http://113.128.163.42:8762/eureka/
```

**Comment by ubalaji** [comment]
Thank you for taking time to look into the issue.

I have following entries in the hosts file located at c:\windows\system32\drivers\etc. Also in the eureka cluster configuration I am using  elm.VERIZON.COM as part of defaultZone. Please advise me if I misunderstood your comments.

127.0.0.1	peer1
127.0.0.1	peer2
localhost	peer1
localhost	peer2
localhost	elm.VERIZON.COM

**Comment by dsyer** [comment]
@aivans I don't think that's relevant if you have a unique `eureka.instance.metadataMap.instanceId` (and anyway the hostnames are different).

@ubalaji I think you need `spring.profiles` (with an "s") otherwise those apps are not going to be running as you expect. Plus I have found that I need a non-zero value for `eureka.server.registry-sync-retries` (the default is 0, which I think is a regression from Angel, so I might fix that here).

**Comment by aivans** [comment]
@dsyer When I initially evaluated Eureka for our case, I tried to run a bunch of services and a cluster of 2 Eureka servers on my laptop.
The Eureka Servers did not behave properly until I gave them different hostnames via hosts file. 
Now if @ubalaji has a different usa case here, my findings do not apply.

**Comment by ubalaji** [comment]
Thanks Dave, I am going to update yml file with profile**s** and also add registry-sync-retries: 3 and give a try.

**Comment by aivans** [comment]
@ubalaji 

This is my config when I tested months ago:
```
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2   
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
```

This is what you configure for the services also:
```
http://peer1:8761/eureka/,http://peer2:8762/eureka/
```

Hope it helps, I spent a couple of days on it back than.

**Comment by dsyer** [comment]
@aivans I think that will work, but I don't think you need a distinct hostname now (ad long as the instanceId is provided).

**Comment by aivans** [comment]
Ok, that would be even better

**Comment by ubalaji** [comment]
Thanks Adrian for sharing configuration.

Dave, I tried with Profiles and registry-sync-retries: 3 and still can't see services under registered services in peer2. Howeer, peer1 shows the services under the registered services. I have attached both screen shots.

peer1 screenshot:

![image](https://cloud.githubusercontent.com/assets/17342164/13227429/76b4cbac-d94b-11e5-8087-2a125aaa05a4.png)



Peer2 screenshot

![image](https://cloud.githubusercontent.com/assets/17342164/13227459/a231890a-d94b-11e5-8043-a255b6b18728.png)

Thank you

**Comment by ubalaji** [comment]
Also I see following in the peer1 log.As you see the last line has replication=false. I am wondering if this is indicating anything and curious to know why is it false?

2016-02-22 10:13:07.688  WARN 5896 --- [nio-8761-exec-1] c.n.e.registry.Abstract
InstanceRegistry  : DS: Registry: lease doesn't exist, registering resource: EMP
LOYEETO-SERVICE - 10.77.0.142:318bef9fc65e45cc949fb55599901d0a

2016-02-22 10:13:07.688  WARN 5896 --- [nio-8761-exec-1] c.n.eureka.resources.In
stanceResource    : Not Found (Renew): EMPLOYEETO-SERVICE - 10.77.0.142:318bef9f
c65e45cc949fb55599901d0a

2016-02-22 10:13:07.704  INFO 5896 --- [nio-8761-exec-2] c.n.e.registry.Abstract
InstanceRegistry  : Registered instance EMPLOYEETO-SERVICE/10.77.0.142 with stat
us UP (replication=false)

**Comment by ubalaji** [comment]
Also I noticed the following behavior. 

First I started peer1 and everything looks good and then started peer2. After peer 2 is up I see services replicating and after some time services are deleted from peer2. Please see the following log. Something causing to cancel instance and setting replication to false.

2016-02-22 10:52:47.183  WARN 5992 --- [tbeatExecutor-0] c.n.d.s.t.d.RetryableEu
rekaHttpClient    : Request execution failure
2016-02-22 10:52:47.198  INFO 5992 --- [tbeatExecutor-0] c.n.d.s.t.d.RetryableEu
rekaHttpClient    : Request execution succeeded on retry #1
2016-02-22 10:52:47.198  INFO 5992 --- [tbeatExecutor-0] com.netflix.discovery.D
iscoveryClient    : DiscoveryClient_PEER2/scsbwin-293416.ITTPA.EBIZ.VERIZON.COM:
peer2:8762 - Re-registering apps/PEER2
2016-02-22 10:52:47.198  INFO 5992 --- [tbeatExecutor-0] com.netflix.discovery.D
iscoveryClient    : DiscoveryClient_PEER2/scsbwin-293416.ITTPA.EBIZ.VERIZON.COM:
peer2:8762: registering service...
2016-02-22 10:52:47.261  INFO 5992 --- [tbeatExecutor-0] com.netflix.discovery.D
iscoveryClient    : DiscoveryClient_PEER2/scsbwin-293416.ITTPA.EBIZ.VERIZON.COM:
peer2:8762 - registration status: 204
2016-02-22 10:52:47.261  INFO 5992 --- [           main] s.b.c.e.t.TomcatEmbedde
dServletContainer : Tomcat started on port(s): 8762 (http)
2016-02-22 10:52:47.261  INFO 5992 --- [           main] c.n.e.EurekaDiscoveryCl
ientConfiguration : Updating port to 8762
2016-02-22 10:52:47.261  INFO 5992 --- [           main] eurekademo.EurekaApplic
ation             : Started EurekaApplication in 21.441 seconds (JVM running for
 29.528)
2016-02-22 10:52:47.667  INFO 5992 --- [nio-8762-exec-1] o.a.c.c.C.[Tomcat].[loc
alhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-02-22 10:52:47.667  INFO 5992 --- [nio-8762-exec-1] o.s.web.servlet.Dispatc
herServlet        : FrameworkServlet 'dispatcherServlet': initialization started

2016-02-22 10:52:47.683  INFO 5992 --- [nio-8762-exec-1] o.s.web.servlet.Dispatc
herServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 16 ms
2016-02-22 10:52:47.745  INFO 5992 --- [nio-8762-exec-1] c.n.e.registry.Abstract
InstanceRegistry  : Registered instance PEER2/scsbwin-293416.ITTPA.EBIZ.VERIZON.
COM:peer2:8762 with status UP (replication=false)
2016-02-22 10:52:47.761  INFO 5992 --- [nfoReplicator-0] com.netflix.discovery.D
iscoveryClient    : DiscoveryClient_PEER2/scsbwin-293416.ITTPA.EBIZ.VERIZON.COM:
peer2:8762 - registration status: 204
2016-02-22 10:54:47.148  INFO 5992 --- [a-EvictionTimer] c.n.e.registry.Abstract
InstanceRegistry  : Evicting 1 items (expired=1, evictionLimit=3)
2016-02-22 10:54:47.148  WARN 5992 --- [a-EvictionTimer] c.n.e.registry.Abstract
InstanceRegistry  : DS: Registry: expired lease for EMPLOYEETO-SERVICE/10.77.0.1
42
2016-02-22 10:54:47.195  INFO 5992 --- [a-EvictionTimer] c.n.e.registry.Abstract
InstanceRegistry  : Cancelled instance EMPLOYEETO-SERVICE/10.77.0.142 (replicati
on=false)

**Comment by ubalaji** [comment]
I looked at "last 1000 canceled leases" and "last 1000 newly registered leases" via web UI. It seems like for some reason peer1 canceling lease for the service and it got propagated to peer2. While doing so both peer1 and peer2 replication set to false. 

Later Peer1 newly registered same service and did not propagated to peer2.

The behavior is interesting and I am puzzled.

Thank you

**Comment by dsyer** [comment]
I think I tracked the missing registration down to a method that we override unnecessarily in Spring Cloud (https://github.com/spring-cloud/spring-cloud-netflix/blob/8957a40/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/InstanceRegistry.java#L79). Since we override this method the super isn't called and it is in that superclass method that the peer registration of non-eureka nodes occurs. It happens on a heartbeat, so everything is probably fine if we just do not override that method. Probably this is a change from 1.0.x (different Eureka dependency).

Bouncing registrations on startup is a separate issue (not sure if that's a problem or not really, but we do that in case the configuration changes the ports and paths).

**Comment by ubalaji** [comment]
Thanks Dave, I will give a try.

**Comment by ubalaji** [comment]
I have tested and see both peers are communicating and updating. However I noticed interesting behavior. I have client with two instances running. I see client trying to send both instances hearbeat. However I see Eureka server showing only one instance registered and showing. I have attached both client log and also screen shots of Eureka Server.

![image](https://cloud.githubusercontent.com/assets/17342164/13400827/73180464-debe-11e5-833f-94bdfd6caedd.png)Mon Feb 29 2016 08:29:16 GMT-0800 (Pacific Standard Time) [App/0] OUT 2016-02-29 16:29:16.585 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90 - Re-registering apps/EMPLOYEETO-SERVICE

Mon Feb 29 2016 08:29:16 GMT-0800 (Pacific Standard Time) [App/0] OUT 2016-02-29 16:29:16.586 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90: registering service...

Mon Feb 29 2016 08:29:16 GMT-0800 (Pacific Standard Time) [App/0] OUT 2016-02-29 16:29:16.602 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90 - registration status: 204

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.714 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc - Re-registering apps/EMPLOYEETO-SERVICE

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.715 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc: registering service...

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.729 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc - registration status: 204

**Comment by dsyer** [comment]
I'm not sure what that's supposed to show. Why is it interesting? Is it related to this issue (which is closed)?

**Comment by spencergibb** [comment]
He opened #862.

**Comment by asarkar** [comment]
@dsyer @aivans I'm trying to understand the relationship among the following, and how these affect Eureka clustering and failover. Is this documented someplace or should I open a ticket for this question?

```
eureka.instance.metadataMap.instanceId
eureka.instance.hostname
spring.application.name
```

**Comment by ryanjbaxter** [comment]
@asarkar please open a new issue

**Comment by asarkar** [comment]
@ryanjbaxter Done [1627](https://github.com/spring-cloud/spring-cloud-netflix/issues/1627)

**Comment by yangzii0920** [comment]
My finding is that, with these properties set up, peers can see each other as available-replicas:
1. spring.profiles
2. eureka.instance.hostname
3. eureka.client.register-with-eureka=true
4. eureka.client.serviceUrl.defaultZone

**Comment by mdchao2010** [comment]
leaseRenewalIntervalInSeconds: 3
leaseExpirationDurationInSeconds: 5

Set too small？？
