### ISSUE TITLE
Ribbon Feign and integration testing with WireMock

### ISSUE THREAD

**Issue by poznachowski** [spring-cloud/spring-cloud-netflix#839]
I have prepared an annotation marking the test should use WireMock for stubbing external dependecies: 
https://github.com/neoteric-eu/neo-starters/blob/master/neo-starter-test/src/main/java/com/neoteric/starter/test/wiremock/WireMockTest.java
and using corresponding listener to start up the WireMock server for each test class (with random port):
https://github.com/neoteric-eu/neo-starters/blob/master/neo-starter-test/src/main/java/com/neoteric/starter/test/wiremock/WireMockListener.java

It works for a single test class, but for test suite when in second test class different WireMock port is set, it fails. It looks like it is set up in RibbonClientConfiguration once at startup:
```
@Bean
	@ConditionalOnMissingBean
	public ILoadBalancer ribbonLoadBalancer(IClientConfig config,
			ServerList<Server> serverList, ServerListFilter<Server> serverListFilter,
			IRule rule, IPing ping) {
		ZoneAwareLoadBalancer<Server> balancer = LoadBalancerBuilder.newBuilder()
				.withClientConfig(config).withRule(rule).withPing(ping)
				.withServerListFilter(serverListFilter).withDynamicServerList(serverList)
				.buildDynamicServerListLoadBalancer();
		return balancer;
	}
```

Is it possible to change Ribbon client's port between test classes?

**Comment by spencergibb** [comment]
We do it all the time, but we get a new context for every test and we create a new ribbon client for every test.  https://github.com/spring-cloud/spring-cloud-netflix/search?utf8=%E2%9C%93&q=staticserverlist

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
