### ISSUE TITLE
Configuration problem with turbine

### ISSUE THREAD

**Issue by okarahan** [spring-cloud/spring-cloud-netflix#84]
I try to launch Turbine on my local environment, but did not succeeded. I use Spring Boot for my services and try to connect it with Turbine.

My service which has the @EnableHystrix annotation gives a stream at his hystrix.stream endpoint.

However my Turbine stream is empty. It discovers my service but I didnt know whats going wrong there. Can someone give a simple introduction, I didn't find a good documentation. I only followed these steps here:

http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html

In my stream from turbine I see alwys the following:

data: {"reportingHostsLast10Seconds":0,"name":"meta","type":"meta","timestamp":1417684659797}

My turbine is configured as the folllowing:

turbine.aggregator.clusterConfig=myService
turbine.appConfig=myService

Turbine detects that service in the log:

2014-12-04 10:18:17.384  INFO 2348 --- [        Timer-0] o.s.c.n.turbine.EurekaInstanceDiscovery  : Fetching instance list for apps: [myService]

The hystrix stream from myService works, but Turbine does not.

**Comment by wangxiaodong0120** [comment]
how to change turbine version if I use the dependencyManagement, need I change the all dependent package version?
Thanks

**Comment by ryanjbaxter** [comment]
@wangxiaodong0120 please open a separate issue for your question

**Comment by wangxiaodong0120** [comment]
Thanks @ryanjbaxter, I have searched the solution, :)
