### ISSUE TITLE
ServletDetectionFilter should be installed by ZuulConfiguration and not ZuulProxyConfiguration

### ISSUE THREAD

**Issue by joshiste** [spring-cloud/spring-cloud-netflix#844]
The `Servlet30WrapperFilter` depends on informations in the `RequestContext` set by the `ServletDetectionFilter`.
The problem is that `Servlet30WrapperFilter` is installed by the `ZuulConfiguration` but the `ServletDetectionFilter` by the `ZuulProxyConfiguration`. So you can end up with the first one only.

If the `ServletDetectionFilter` isn't installed, the request inputStream isn't buffered in zuul (cause it's not wrapped by the `Servlet30WrapperFilter`)  and the `ProxyRequestHelper#debugRequestEntity(..)` method consumes the request body and the body won't be forwarded.

Version was 1.1.0-BUILD-SNAPSHOT from today

**Comment by aivans** [comment]
Interesting

**Comment by aivans** [comment]
Quick questions: I understand that this change only helps those which use `@EnableZuulServer`?

**Comment by dsyer** [comment]
Yes, why?

**Comment by aivans** [comment]
Just  a clarification for myself. We are doing some tests now and was curios if I need to take the latest snapshot.

Thanks
