### ISSUE TITLE
Possible issue with multiple service registrations in Eureka with Docker referenced by Ribbon

### ISSUE THREAD

**Issue by TabberGit** [spring-cloud/spring-cloud-netflix#850]
In attempting to register more than a single service in a container in Eureka and use this via Ribbon, it seems that only the last container registered will get all of the traffic, rather than round-robining.  In the example we're using, the app is the example customer/stores app, and we're implementing multiple customer containers on separate ports.  We are using the 1.1.0.BUILD-SNAPSHOT version.  Here is how eureka/apps reports the registrations:

     <application>
        <name>CUSTOMERS</name>
        <instance>
           <instanceId>192.168.99.100:customers:9000</instanceId>
           <hostName>192.168.99.100</hostName>
           <app>CUSTOMERS</app>
           <ipAddr>192.168.99.100</ipAddr>
           <status>UP</status>
           <overriddenstatus>UNKNOWN</overriddenstatus>
           <port enabled="true">9000</port>
           <securePort enabled="false">443</securePort>
           <countryId>1</countryId>
           <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
              <name>MyOwn</name>
           </dataCenterInfo>
           <leaseInfo>
              <renewalIntervalInSecs>10</renewalIntervalInSecs>
              <durationInSecs>90</durationInSecs>
              <registrationTimestamp>1456274666814</registrationTimestamp>
              <lastRenewalTimestamp>1456275116594</lastRenewalTimestamp>
              <evictionTimestamp>0</evictionTimestamp>
              <serviceUpTimestamp>1456274666814</serviceUpTimestamp>
           </leaseInfo>
           <metadata class="java.util.Collections$EmptyMap"/>
           <homePageUrl>http://192.168.99.100:9000/</homePageUrl>
           <statusPageUrl>http://192.168.99.100:9000/info</statusPageUrl>
           <healthCheckUrl>http://192.168.99.100:9000/health</healthCheckUrl>
           <vipAddress>customers</vipAddress>
           <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
           <lastUpdatedTimestamp>1456274666814</lastUpdatedTimestamp>
           <lastDirtyTimestamp>1456274666548</lastDirtyTimestamp>
           <actionType>ADDED</actionType>
        </instance>
     </application>
     <application>
        <name>CUSTOMERS</name>
        <instance>
           <instanceId>192.168.99.100:customers:9001</instanceId>
           <hostName>192.168.99.100</hostName>
           <app>CUSTOMERS</app>
           <ipAddr>192.168.99.100</ipAddr>
           <status>UP</status>
           <overriddenstatus>UNKNOWN</overriddenstatus>
           <port enabled="true">9001</port>
           <securePort enabled="false">443</securePort>
           <countryId>1</countryId>
           <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
              <name>MyOwn</name>
           </dataCenterInfo>
           <leaseInfo>
              <renewalIntervalInSecs>10</renewalIntervalInSecs>
              <durationInSecs>90</durationInSecs>
              <registrationTimestamp>1456274666814</registrationTimestamp>
              <lastRenewalTimestamp>1456275116594</lastRenewalTimestamp>
              <evictionTimestamp>0</evictionTimestamp>
              <serviceUpTimestamp>1456274666814</serviceUpTimestamp>
           </leaseInfo>
           <metadata class="java.util.Collections$EmptyMap"/>
           <homePageUrl>http://192.168.99.100:9001/</homePageUrl>
           <statusPageUrl>http://192.168.99.100:9001/info</statusPageUrl>
           <healthCheckUrl>http://192.168.99.100:9001/health</healthCheckUrl>
           <vipAddress>customers</vipAddress>
           <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
           <lastUpdatedTimestamp>1456274666814</lastUpdatedTimestamp>
           <lastDirtyTimestamp>1456274666548</lastDirtyTimestamp>
           <actionType>ADDED</actionType>
        </instance>
     </application>

**Comment by dsyer** [comment]
Round robin is definitely the default. I guess we need to look at your client.

**Comment by TabberGit** [comment]
The client that's being used is the one from Spring's customer/stores demo.

The edge server is coming in with the definition of:

     zuul:
       routes:
         stores:
           path: /stores/**
           strip-prefix: false
         customers:
           path: /customers/**
           strip-prefix: false

I believe his should go after customers in eureka (by vipAddress?), and determine uniqueness based on instanceId?

The regular app itself is the thin groovy app that is out as:

     @EnableZuulProxy
     @EnableDiscoveryClient
     @Controller
     class Application extends WebMvcConfigurerAdapter {
       void addResourceHandlers(ResourceHandlerRegistry registry) {
         registry.addResourceHandler("/**").addResourceLocations('classpath:/', 'classpath:/dist/')
       }
       @RequestMapping("/")
       String home() { 
         return 'redirect:/index.html#/customers'
       }
     }

**Comment by TabberGit** [comment]
UPDATE!

This appears to have been a false alarm.  There was an additional service being registered against Eureka which suffered from 'cut & paste syndrome' and was given the same serviceId as one of the customers entries.  Evidently, this is a major wrench in the Eureka system and leads to some unexpected results.

I apologize for the bother.

**Comment by spencergibb** [comment]
@TabberGit good news. Yes there is no confidence that an application that registers with any particular serviceId. Spring Cloud Services (our commercial offering) has a solution for this. Consul 0.6+ also has ACL's that cover this.
