### ISSUE TITLE
Unavailable-replicas Peer to Peer setup 

### ISSUE THREAD

**Issue by ubalaji** [spring-cloud/spring-cloud-netflix#860]
I have peer to peer configuration and everything looks good. However the WEB UI screen showing both registered-replicas and unavailable-replicas. I have peer1 and peer2, both of them have same issue that showing registered-replicas as unavailable. Why is it unavailable and how can I make it available-replicas?

Please see the following screen shots.

![image](https://cloud.githubusercontent.com/assets/17342164/13399775/d138ce8e-deb9-11e5-9176-f21608e18f0d.png)

**Comment by dsyer** [comment]
I'm not sure I trust the UI on that. Are the replicas actually working?

**Comment by DirkLachowski** [comment]
@ubalaji That may be a config thing, have a look at http://stackoverflow.com/q/36284246/1686330
