### ISSUE TITLE
Not showing correct number of instances in peer to peeer setup

### ISSUE THREAD

**Issue by ubalaji** [spring-cloud/spring-cloud-netflix#862]
I have peer to peer server setup, tested and see both peers are communicating and updating. However I noticed interesting behavior. I have client with two instances running. I see client trying to send both instances hearbeat. However I see both Eureka servers showing only one instance registered and showing. I have attached both client log and also screen shots of Eureka Server.

![image](https://cloud.githubusercontent.com/assets/17342164/13401024/5027bb60-debf-11e5-86f1-597368f0c682.png)

16:29:16.585 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90 - Re-registering apps/EMPLOYEETO-SERVICE���

Mon Feb 29 2016 08:29:16 GMT-0800 (Pacific Standard Time) [App/0] OUT 2016-02-29 16:29:16.586 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90: registering service...���

Mon Feb 29 2016 08:29:16 GMT-0800 (Pacific Standard Time) [App/0] OUT 2016-02-29 16:29:16.602 INFO 33 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:43b5f6bc05874e11b3c91344e6fc5b90 - registration status: 204���

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.714 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc - Re-registering apps/EMPLOYEETO-SERVICE���

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.715 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc: registering service...���

Mon Feb 29 2016 08:29:25 GMT-0800 (Pacific Standard Time) [App/1] OUT 2016-02-29 16:29:25.729 INFO 34 --- [pool-2-thread-1] com.netflix.discovery.DiscoveryClient : DiscoveryClient_EMPLOYEETO-SERVICE/employeeto-service.cfsandbox.verizon.com:1895f037363c47cdabe53ea98b4b95fc - registration status: 204���

**Comment by spencergibb** [comment]
What version are you using? Can you show your configuration for `employeeto-service` (application.yml, etc...).

**Comment by ubalaji** [comment]
Please see the following information. 

spring:
  application:
    name: EmployeeTO-Service
  cloud:
    services:
      registrationMethod: route

server:
  port: 8082

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://113.128.163.42:8761/eureka/,http://113.128.163.42:8762/eureka/
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false

  profiles: dev

security:
  basic:
    enabled: false

My parent is as follows.

<parent>
    <groupId>io.pivotal.spring.cloud</groupId>
    <artifactId>spring-cloud-services-starter-parent</artifactId>
    <version>1.0.2.RELEASE</version>
    <relativePath/> 
  </parent>

**Comment by spencergibb** [comment]
Why are you using `pring-cloud-services-starter-parent`?

**Comment by ubalaji** [comment]
I am using cloud foundry environment. Their example program using spring-cloud-services-starter-parent and I do not have any UI part. Please advise if I need to try something else.

**Comment by spencergibb** [comment]
You should not be using `spring-cloud-services-starter-parent` unless you are using the Spring Cloud Services tile via Pivotal Cloud Foundry. Correct me if I'm wrong @mstine @scottfrederick @mheath. You should use your own parent (or the boot parent) and


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Angel.SR6</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by ubalaji** [comment]
We have spring boot applications deployed in the cloud foundry.The Erueka server is located outside cloud foundry and all spring boot applications trying to register with Eureka server. 

if I change registration method to direct then I could see multiple instances in the registry. The route method of registration is not showing correct number of instances.

**Comment by spencergibb** [comment]
If you are using route, there will only ever be 1 registered instance (the route). The `spring.cloud.services.registrationMethod` is not part of `spring-cloud-netflix`, so I'm going to close this.

**Comment by ubalaji** [comment]
I was confused because the log file from cloud foundry showing that heart beat sending for both instances.  However I do not see that in the registry. 

I do not see any error message while sending heartbeat and got return code 204. SO I ws hoping to see both instances. 

If this is the right behavior please close the issue. I really appreciate your time.

**Comment by spencergibb** [comment]
It is the correct behavior, and also not in this code base.

**Comment by ubalaji** [comment]
Do you know if code base Angel.SR6 would address this issue?

**Comment by spencergibb** [comment]
It's not an error and it's not in our code base.

**Comment by spencergibb** [comment]
The `route` method you are using from `io.pivotal.spring.cloud:spring-cloud-services-starter-parent` isn't part of this repo. It also forces each instance to register with the CF route, so essentially they all look like one instance to eureka. Multiple heartbeats is the side effect and is not a problem.
