### ISSUE TITLE
Zuul returns 200 OK if the route does not exist instead of 404

### ISSUE THREAD

**Issue by aivans** [spring-cloud/spring-cloud-netflix#865]
My config:
```
zuul:
  servletPath: /
  ignored-services: "*"
  routes:
    files:
      path: /aaa/**
      serviceId: aaa-service
      stripPrefix: false
```

I have a the ZuulServlet mapped on the home path.
Requests to `/aaa/` work fine.

I would expect requests to any other path (ex. /bbb) to return a 404 Not Found.

The actual response status code is 200 OK.

In `PreDecorationFilter` there is this code:
```
else {
			log.warn("No route found for uri: " + requestURI);
			ctx.set("forward.to", requestURI);
		}
```
The request is re-executed and somehow an empty response body is returned with 200OK

**Comment by spencergibb** [comment]
This was added specifically in cd30bea0c8bfd75bd27e74c5ff18f69bd0c0b532. 

> Also properly ignores ignored routes, so they can be handled locally
(rather than giving up and sending 404).

@dsyer will need to comment more.

**Comment by spencergibb** [comment]
Maybe a property like `zuul.forwardUnknownRoutes=false`?

**Comment by aivans** [comment]
I don't understand the uses cases where no route is found for a path, but the request is still handled somehow.

What i would do is this:
```
		else {
			log.warn("No route found for uri: " + requestURI);
//			ctx.set("forward.to", requestURI);
			prepareNoFoundResponse();
		}
		return null;
	}

	private void prepareNoFoundResponse() {
		log.info("Preparing 404 error");
		
		RequestContext ctx = RequestContext.getCurrentContext();
		ctx.set("error.status_code", new Integer(HttpStatus.NOT_FOUND.value()));
		ctx.set("error.message", HttpStatus.NOT_FOUND.getReasonPhrase());
		
	}
```
I would prepare an error for the SendErrorFilter.
The response looks like this:
```
{
    "timestamp": 1456914252667,
    "status": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```

**Comment by dsyer** [comment]
If we forward to a path that doesn't exist don't you get a 404 anyway? I think we need to understand where the 200 is coming from before we do anything else.

**Comment by aivans** [comment]
You get a 200 now.
Conceptually speaking, I would prefer to drive everything from the route config. If the path doesn't match a route, than there should be a 404.
Nothing stops the user from configuring an explicit `forward:` for the intended routes, rather than relying on a fallback.

**Comment by dsyer** [comment]
Yeah, but why is it a 200? If you forward to a non-existent resource I'd expect a 404.

**Comment by aivans** [comment]
Maybe from the Spring perspective there is a match.
My config is this:
```
zuul:
  servletPath: /

server:
  servletPath: /spring
```
In the logs I can see:
o.s.s.w.u.m.AntPathRequestMatcher [AntPathRequestMatcher.java:141] Request '/aaa' matched by universal pattern '/**'
On the '/**' ZuulServlet is mapped.

**Comment by aivans** [comment]
I'm trying one thing.
Maybe the forward needs to take to include the DispatcherServlet path, so other Controller behind the DispatcherServlet kicks in.

If the forward is to `dispatcherServletPath + requestUri` things change a bit:
```
2016-03-03 16:12:45,464 DEBUG [http-nio-8765-exec-1]o.s.w.s.m.a.ResponseStatusExceptionResolver [AbstractHandlerExceptionResolver.java:133] Resolving
 exception from handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], c
lass path resource [public/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@50b2a260]]]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST'
 not supported
2016-03-03 16:12:45,476 DEBUG [http-nio-8765-exec-1] o.s.w.s.m.s.DefaultHandlerExceptionResolver [AbstractHandlerExceptionResolver.java:133] Resolving
 exception from handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], c
lass path resource [public/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@50b2a260]]]: org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST'
 not supported
2016-03-03 16:12:45,489 WARN [http-nio-8765-exec-1] o.s.w.s.PageNotFound [DefaultHandlerExceptionResolver.java:208] Request method 'POST' not supporte
d
2016-03-03 16:12:45,495 DEBUG [http-nio-8765-exec-1] o.s.w.s.DispatcherServlet [DispatcherServlet.java:1034] Null ModelAndView returned to DispatcherS
ervlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2016-03-03 16:12:45,501 DEBUG [http-nio-8765-exec-1 o.s.w.s.DispatcherServlet [FrameworkServlet.java:998] Successfully completed request
```

The response is:
```
{
    "timestamp": 1457014365592,
    "status": 405,
    "error": "Method Not Allowed",
    "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
    "message": "Request method 'POST' not supported",
    "path": "/aaa"
}
```

**Comment by aivans** [comment]
By the way, the above request is a POST.

For a GET a 404 is returned:
```
{
    "timestamp": 1457016631924,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/aaa"
}
```

**Comment by aivans** [comment]
My conclusion so far:
- the redirect need to take into account the DispatcherServlet path (even for requests that come through ZuulServlet directly)
- the default behavior of handling a POST to an unconfigured path needs to be changed
Any ideas on how to change the POST behavior?

**Comment by aivans** [comment]
Same as this:
http://stackoverflow.com/questions/30103157/spring-boot-returning-405-instead-of-404-for-post-to-unknown-url

**Comment by aivans** [comment]
https://github.com/spring-projects/spring-boot/issues/4876

**Comment by aivans** [comment]
```
spring:
  mvc:
    static-path-pattern: /static/**
```
This "solves" the issue  and 404 is returned for POST.

Conclusion:
- Conceptually: do we want a catch all fall back in case the route is not found or we want every "forward:" to be configured
- In case we want the fallback, my PR is not valid anymore
- The `PreDecorationFilter` needs to take into account the Servlet that is executed initially and add the DispatcherServlet path before the `requestUri`
- the `spring.static-path-pattern` config needs to be changed. I am not an expert on the use for this config

**Comment by aivans** [comment]
guys, any thoughts?

**Comment by dsyer** [comment]
I liked having a fallback, but if it only works for GET that's a problem. I think the fact that ignored routes were caught by the fallback was a side effect of having the fallback, not a design constraint of the ignored routes, so that part of your patch is a distraction. I'd like it to just work as a fallback and I don't understand why Spring can't provide a 404 without any special configuration. I don't really have an opinion on the static path pattern (except that we don't want to be more opinionated about it than Spring Boot). I didn't understand the servlet path bit yet (I sense there is more to it).

**Comment by aivans** [comment]
@dsyer 
"I don't understand why Spring can't provide a 404 without any special configuration"
The explanation seems to be found here:
https://github.com/spring-projects/spring-boot/issues/4876#issuecomment-171232347

"I didn't understand the servlet path bit yet (I sense there is more to it)."
I am running all the requests through ZuulServlet directly, not through the DispatcherServlet.
But the error handling mechanisms  for example are supposed to be delegated to Spring through the DispatcherServlet.

Let's take an example.
My request path is `/aaa`. 
**Variant1**: Going through ZuulServlet. 
The PreDecorationFilter does not find the route and forwards as fallback to `requestUri` which is `/aaa`. The request comes back to the ZuulServlet and tries again to find a route for `/aaa`. This time the PreDecorationFilter doesn't run because it detects a forward:
```
	@Override
	public boolean shouldFilter() {
		RequestContext ctx = RequestContext.getCurrentContext();
		  return !ctx.containsKey("forward.to") // another filter has already forwarded
				&& !ctx.containsKey("serviceId"); // another filter has already determined
													// serviceId
	}
```
A 200 OK with empty response body is returned at this point from SendForwardFilter:
```
			if (dispatcher != null) {
				ctx.set(SEND_FORWARD_FILTER_RAN, true);
				if (!ctx.getResponse().isCommitted()) {
					dispatcher.forward(ctx.getRequest(), ctx.getResponse());
					ctx.getResponse().flushBuffer();
				}
			}
```

So what happened is that the forward should have gone to DispatcherServlet, not the ZuulServlet again. The DispatcherServlet would have triggered a 404 for GET and 405 for POST.

The solution would be to make sure the PreDecorationFilter sets the forward uri to contain the DispatcherServlet servletPath.

I think this is a good solution and who is not happy with 404 vs 405 would change the `spring.static-path-pattern` in their own application.

**Comment by dsyer** [comment]
In your example the `ZuulServlet` has a path of "/"? (I.e. not the default.)

So I can agree that maybe all we need to do is be smarter about the default forward path, but I don't think unconditionally sending it to the `DispatcherServlet` is going to be the right answer (what if you want to handle the response in a different servlet?

**Comment by aivans** [comment]
Yes, ZuulServlet is mapped to "/".
Hmm, I think we should have some convention or an opinionated approach.
Normally you would want to configure a `forward:`.
The catch all would be forwarded by default to the DispatcherServlet and an override mechanism could be provided also through some config. I would stick to DispatcherServlet in the current phase.

**Comment by dsyer** [comment]
Isn't it enough to just skip the fallback if the path starts with `ZuulServlet` path? The empty 200 is no use to anyone, and it can be avoided in that specific case.

**Comment by aivans** [comment]
No, it returns a 200 with empty body, which makes sense since the request was handled.

You need to prepare by hand an error for the SendErrorFilter.

**Comment by aivans** [comment]
It will be something like:
```
		else {
			log.warn("No route found for uri: " + requestURI);
			String prefix = "";
			if (!RequestUtils.isZuulServletRequest()) {
				ctx.set("forward.to", requestURI);
			} else {
				prepareNotFoundError();
			}
		}
```

**Comment by aivans** [comment]
Honestly now I prefer the catch all solution and make sure that the forward makes sure the Dispatcherservlet servletPath (or another configurable path) is added to the request uri.

The Design would be that regardless whether ZuulServlet or DispatcherServlet is used, the forward fallback and error handling is delegated to Spring MVC

**Comment by dsyer** [comment]
> makes sense since the request was handled

It didn't make sense to me. Oh well. And I don't agree that assuming Spring MVC can handle everything is cleaner (it's only the default behaviour of a Boot app and users can change that).

We do seem to be converging on agreement on one thing though: the fallback forward is a reasonable strategy. I think maybe if the forward has a prefix which is empty by default, except when the `ZuulServlet` is mapped to "/" (and we are using the servlet to handle the current request), we can converge on an implementation as well? The remaining question for me is what to do when the `ZuulServlet` is mapped to "/" and no route is found via that mapping. I think the correct answer is that we should send a 404. Is that what you said?

**Comment by aivans** [comment]
> We do seem to be converging on agreement on one thing though: the fallback forward is a reasonable strategy

Yes

> I think maybe if the forward has a prefix which is empty by default, except when the ZuulServlet is mapped to "/" (and we are using the servlet to handle the current request)

I think the prefix needs to default to the DispatcherServlet.servletPath.
It could be overridden through config in case it is desired that other Servlet handles the fallbacks.

- In case the DispatcherServlet.servletPath is / or /**, the prefix is empty. 

- In case request is handled by ZuulServlet, the code needs to make sure that the ZuulServlet servletPath is removed from requestUri before adding the prefix. If ZuulServlet itself is mapped on / than it doesn't matter anymore.

> The remaining question for me is what to do when the ZuulServlet is mapped to "/" and no route is found via that mapping. I think the correct answer is that we should send a 404. Is that what you said?

This is not relevant anymore because the fallback handles the situation. If no fallback is found by DispatcherServlet (or other configured Servlet), than a 404 for GET and 405 for POST will be sent. (405 is solved by that static `spring.static-path-pattern` config)

**Comment by aivans** [comment]
I can try a PR if you agree with the above.

**Comment by dsyer** [comment]
OK

**Comment by yamen23ali** [comment]
i don't know if this related,  we upgraded to spring boot 1.3.3 yesterday, and zuul is not really making any requests , its just returning 200 all the time with empty body !

If the requested service is up or not , it always returns 200 with empty body, if the path is wrong it returns 404 .

any ideas ?
