### ISSUE TITLE
Add X-Forwarded-Port as well as -Host header

### ISSUE THREAD

**Issue by istonikula** [spring-cloud/spring-cloud-netflix#872]
Moved to here from https://github.com/Netflix/zuul/issues/133
Context: one of the purposes of Zuul is to act as a reverse proxy, however a scenario that works as expected with minimal nginx reverse proxy config works differently when nginx is replaced with zuul: redirects from an app that sits behind the proxy end up to the client with references to the destination app, not the proxy.

I'm seeing something similar with minimal zuul config: an application using spring security (form login) that sits behind zuul proxy. Here are links to the projects:
- proxy:  https://github.com/istonikula/proxy
- app: https://github.com/istonikula/demo

Without the proxy, when navigating to http://localhost:8180/user1/rows the user is redirected to login page http://localhost:8180/login as expected.

With a simple nginx reverse proxy setup like this (nginx listening on port 8080, boilerplate omitted):
        location / {
            proxy_pass http://127.0.0.1:8180;
        }

the setup also behaves as I expect, i.e. when navigating to http://localhost:8080/user1/rows the user is redirected to login page http://localhost:8080/login.

However, if I replace nginx with the proxy project that uses zuul, navigating to http://localhost:8080/user1/rows is redirected to http://localhost:8180/login

**Comment by dsyer** [comment]
How did you implement the proxy? If you used `@EnableZuulProxy` then it should add the `X-Forwarded-*` headers by default (which is what nginx is doing). Generally it works for me out of the box, so I think you need to share more information (a sample project would be useful).

**Comment by istonikula** [comment]
The example projects (proxy and app) are already linked in the question above.

**Comment by dsyer** [comment]
Right, but that's partly just because your UI isn't configured to handle the forward headers (`server.use-forward-header=true` in a Spring Boot app). Useful Spring Boot docs link: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server. But even doing that won't get your app working as expected until we add the "X-Forwarded-Port" header in Zuul. We can do that, but even then you will find that the Tomcat (and other server) valve will not respect the "X-Forwarded-Prefix" header, so the redirect will only work if the proxy also forwards the /login redirect.

**Comment by dsyer** [comment]
Clarification of summary: Spring MVC can parse a port out of the `X-Forwarded-Host` but Tomcat (and other servers) do not, so we should add the `X-Forwarded-Port` as well.

**Comment by dsyer** [comment]
Further clarification: in your app it is the `LoginUrlAuthenticationEntryPoint` from Spring Security that sends the redirect. You could customize that (or ask them to fix it in Spring Security) so that it respects the proxy headers the same way as Spring MVC.

**Comment by istonikula** [comment]
Thanks @dsyer for the tips, I tried them out but eventually all my scenarios failed with some component (like spring-security as you already pointed out) or other being not aware of the X-Forwarded-* headers.

Taking into account that originally my app was not aware of any forwarded headers (server.use-forward-headers was false) and was still working with the very basic nginx reverse proxy setup, I'd be interested to know how to replicate this behavior with zuul, i.e. implement the functionality that nginx seems to provide out-of-the-box in the scenario above. Any tips on this? 

Something like this:
- url rewriting in the proxy for responses
- allowing cookies (i.e. clearing out default sensitive headers from demo route) to be passed from app via proxy to client, otherwise spring security login will not work behind the proxy

**Comment by dsyer** [comment]
Yeah, we could re-write the Location headers in responses. I imagine that's what nginx does.

**Comment by istonikula** [comment]
It seems that has been already been requested in https://github.com/spring-cloud/spring-cloud-netflix/issues/8 and the end result as I understand by the last comment by @spencergibb was that it's not going to happen.

**Comment by spencergibb** [comment]
@istonikula Our collective opinion can change. We can reopen #8.

**Comment by dsyer** [comment]
I think the problem with #8 was that it was post processing the response body. If it's just the location header we can look at how to do that (contributions welcome).

**Comment by miwoe** [comment]
Hi, I am facing same issues and wondering if there i no solution yet. Having Spring Security on Webapp which is redirecting from `<host>:</port>/` to `<host>:</port>/login`. As Zuul Server is redirecting from myproxy:8080/webapp/ to myapp:9324/, the Location header is "myapp:9324/login" and browser redirects to it. Doing same on a Apache proxy works..., but Apache sets host-Header also to myproxy and not myapp...

Is it possible that neither @EnableZuulProxy nor @EnableZuulServer (which should do the same but less) does not have any reverse proxy functionality?

Is there any example around where a Zuul/Eureka installation works with a Spring Secured (Oauth) webapp?

**Comment by dsyer** [comment]
@miwoe this issue is closed, and generally speaking the Zuul proxy works for most purposes, especially if the backends are Spring apps (but see also #959). I did suggest to maybe open a new issue above  specifically about location header re-writing, if you think it would help. We could continue the discussion there.
