### ISSUE TITLE
Turbine AMQP messages are not interoperable between Brixton and Angel

### ISSUE THREAD

**Issue by william-tran** [spring-cloud/spring-cloud-netflix#873]
Angel posts Hystrix metrics messages differently than in Brixton. In Angel the content-type is `application/json` and the message body is

```
"{\"origin\":{\"host\":\"my-angel-based-app-com\",\"port\":80…
```

In Brixton the content-type is `text/plain` and the message body is 

```
{"origin":{"host":"my-brixton-based-app-com","port":80,...
```

Even if you set up the exchanges, queues, and bindings in such a way as to receive messages from both Brixton and Angel apps, an Angel Turbine would only be able to understand metrics from Angel apps and likewise for Brixton.

**Comment by spencergibb** [comment]
/cc @dsyer @mstine 

Brixton turbine should be able to understand Angel messages.

Brixton turbine expects a String (hence `text/plain` makes sense). It then manually converts the String into a map.

Do we want `text/plain` json string going forward?

**Comment by dsyer** [comment]
I think I'd prefer to have `application/json` as the content type. I wonder if that would be enough to make them interoperable. I'll try it.
