### ISSUE TITLE
Some eureka configuration properties relaxed name matching incorrect

### ISSUE THREAD

**Issue by dlaidlaw** [spring-cloud/spring-cloud-netflix#878]
In attempting to configure the eureka service, setting some properties does not work. The ones I have found are:
- eureka.client.eureka-server-dnsname
- eureka.client.eureka-server-urlcontext

It looks like these are meant to map to the EurekaClientConfigBean, into the eurekaServerDNSName and eurekaServerURLContext variables, respectively.

This is not happening. It is probably because the relaxed name mapping cannot handle the caps in the DNSName and URLContext parts of those names.

Although the META-INF/spring-configuration-metadata.json specifies that the configuration properties should be named as above, what does work is setting these:
- eureka.client.eurekaServerDNSName
- eureka.client.eurekaServerURLContext

Either the META-INF/spring-configuration-metadata.json needs to be changed to match the reality, or the relaxed name matching needs to become slightly more relaxed.

**Comment by dsyer** [comment]
@snicoll will probably disagree, but I think the metadata should change. We can ask him if there's a way to change it just for these properties.

**Comment by snicoll** [comment]
We already discussed that in https://github.com/spring-projects/spring-boot/issues/5330 - Given what the meta-data will look like after this change, I'd highly recommend changing `DNS` and `DLQ` to their proper camel case counter part.

**Comment by dsyer** [comment]
Yeah, but we can't do that because this is an external interface (from NetflixOSS). If the metadata really can't change then users are just going to have to get used to ignoring it and camel casing manually.

**Comment by spencergibb** [comment]
Could we add some adapter methods that have the right casing?

**Comment by dsyer** [comment]
I guess we could. I don't know if that would be more confusing or less.

**Comment by dlaidlaw** [comment]
Why not just have the spring-boot project fix the relaxed name matcher? It seems to have problems anywhere you have a run of 2 or more caps in a method name. This is sure to come up in using other third-party products with spring-boot.

**Comment by dsyer** [comment]
That's what the spring boot issue above is all about.

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-projects/spring-boot/issues/5330
