### ISSUE TITLE
Atlas is using a ribbon enabled RestTemplate.

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#881]
Makes for an odd workaround.

http://stackoverflow.com/questions/35848053/spring-cloud-zuul-spectator-and-atlas-config

**Comment by dsyer** [comment]
Should be fixed in master right, because the atlas template will not be `@LoadBalanced`?

**Comment by spencergibb** [comment]
I guess it depends on the beans the user creates. I guess my question is, should atlas be dependent on a user created `RestTemplate`?

**Comment by dsyer** [comment]
Why would Atlas need any bean? Can't it create its own rest template?

**Comment by spencergibb** [comment]
That's what I was thinking, just create one.
