### ISSUE TITLE
No Resttemplate bean anymore (spring-boot 1.3.2 + Spring cloud Brixton-SNAPSHOT)

### ISSUE THREAD

**Issue by pcornelissen** [spring-cloud/spring-cloud-netflix#887]
Hi!

Somewhere between Friday and today it looks like something changed regarding the initialization of a resttemplate. 
I am not sure where it changed, but it looks like it s triggered by something in spring cloud as this is the only snapshot dependency in my project (and I need it due to fixes in brixton).

I have a few spring boot services that no longer start, because the resttemplate is no longer available.
Then I just added one to a configuration class, but this seems not to be enhanced by ribbon/eurekaclient, so it is not able to resolve eurekas symbolic service names :-(

I browsed a little bit to find a commit that might be responsible, but there are so many git repos and so many commits, so I gave up.

Do you have any clue or do I now add something to my code/pom that was not needed before?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#spring-resttemplate-as-a-load-balancer-client

We made a breaking change. Each application needs to create a `@LoadBalanced` `RestTemplate` that will have ribbon plugged in.

```
@Configuration
public class MyConfiguration {

    @LoadBalanced
    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }
}
```

**Comment by pcornelissen** [comment]
Thanks!
