### ISSUE TITLE
CORS Configuration for ZuulProxy

### ISSUE THREAD

**Issue by gpradeepkrishna** [spring-cloud/spring-cloud-netflix#888]
I attempted to setup CORS configurations for ZuulProxy using the steps detailed in https://spring.io/guides/gs/rest-service-cors/.

Unfortunately, CorsConfiguration setup using snippet below isn't getting picked up by ZuulHandlerMapping. However, the configurations are available in Spring's default Handler mappings. 

```java
@Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/greeting-javaconfig").allowedOrigins("http://localhost:9000");
            }
        };
    }
```

I was able to make it work by creating a bean that auto-wires ZuulHandlerMapping as well as RequestHandlerMapping and use post-contruct method to override CorsConfiguration in ZuulHandlerMapping.

```java
public class CorsReconfigurer {

	@Autowired
	private RequestMappingHandlerMapping requestMappingHandlerMapping;
	
	@Autowired
	private ZuulHandlerMapping zuulHandlerMapping;
	
	@PostConstruct
	public void postConstruct() {
		// ...
		zuulHandlerMapping.setCorsConfigurations(requestMappingHandlerMapping.getCorsConfigurations());
		// ...
	}
}
```

I hope there is a better way to handle CORS configuration in ZuulProxy. If not I believe this should be addressed in the near future.

**Comment by radubutnaru** [comment]
FYI, there is also the servlet filter option: [CorsFilter](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/filter/CorsFilter.html).

**Comment by gpradeepkrishna** [comment]
@radubutnaru - Thanks for the pointer, I was able to set up a functional CORS configuration using CorsFilter. Following is my snippet to make it work...  (Note: Lombok annotations used in below snippets)

```java
@Data
@ConfigurationProperties("cors")
public class CorsUrlMappings {
	private Map<String, CorsProperties> mappings = new HashMap<String, CorsProperties>();
	
	@Data
	public static class CorsProperties {
		private String[] allowedOrigins;
		private String[] allowedHeaders;
		private String[] allowedMethods;
		private String[] exposedHeaders;
		private int maxAge;
		private boolean allowCredentials;
	}
}
```

```java
@Bean
public CorsFilter corsFilter() {
	UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
	corsUrlMappings.getMappings().forEach((k,v) -> {
		CorsConfiguration corsConfiguration = new CorsConfiguration();
		corsConfiguration.setAllowCredentials(v.isAllowCredentials());
		if (v.getAllowedHeaders() != null) {
			corsConfiguration.setAllowedHeaders(Arrays.asList(v.getAllowedHeaders()));
		}

		if (v.getAllowedMethods() != null) {
			corsConfiguration.setAllowedMethods(Arrays.asList(v.getAllowedMethods()));
		}

		if (v.getAllowedOrigins() != null) {
			corsConfiguration.setAllowedOrigins(Arrays.asList(v.getAllowedOrigins()));
		}

		if (v.getExposedHeaders() != null) {
			corsConfiguration.setExposedHeaders(Arrays.asList(v.getExposedHeaders()));
		}
		source.registerCorsConfiguration(k, corsConfiguration);
	});
	return new CorsFilter(source);
}
```

Configurations were setup as shown below...
```yml
cors:
  mappings:
    /*:
      allowedOrigins: 
        - www.example.com
      allowedHeaders:
        - X-Requested-With
```

However, shouldn't ZuulProxy be able to handle CorsConfiguration via WebMvcConfigurerAdapter as well...?

**Comment by radubutnaru** [comment]
I can't answer that, in our scenario we are using the ZuulServlet as the default for all of our Zuul proxy routes, not the Spring DispatcherServlet. We are doing this as we have large file uploads in addition to  normal JSON-content requests, and we want to avoid Spring MVC's buffering of data. See [the relevant doc section](http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_uploading_files_through_zuul).

**Comment by gpradeepkrishna** [comment]
Good to know! If ZuulServlet is the default, the fault raised may not be relevant. I'm closing the issue then! 

@radubutnaru Thank you for your time.
