### ISSUE TITLE
Add support for placeholders to Feign spring-mvc annotations.

### ISSUE THREAD

**Issue by PedroAlvarado** [spring-cloud/spring-cloud-netflix#894]
I'd be awesome if spring-cloud-feign supported placeholders in spring-mvc annotations as shown below.

```
@FeignClient("foo")
public interface FooClient{
    @RequestMapping(value = "${my.special.placeholder}",
            method = RequestMethod.GET,
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity getSomeData(s);
}
```

**Comment by PedroAlvarado** [comment]
@spencergibb If you can give me a lead, I'd take a stab at implementing this feature.

**Comment by spencergibb** [comment]
I'd start looking at `SpringMvcContract.processAnnotationsOnParameter` and this commit 94d4bdfcc38cb9cc505fe249a0f79f4431b03f8d for how it was done on `@FeignClient`.

**Comment by sfat** [comment]
@PedroAlvarado you still want to work on this? If not, gonna make a PR for this guy
