### ISSUE TITLE
Multiple Ports per Host Monitor for Turbine CommonsInstanceDiscovery

### ISSUE THREAD

**Issue by cchatfield** [spring-cloud/spring-cloud-netflix#897]
Referencing: https://github.com/Netflix/Hystrix/issues/117

The EurekaInstance Discovery was updated to support multiple ports per host - https://github.com/spring-cloud/spring-cloud-netflix/commit/03a005033d5abb61dc220528076949e6e4d3416e.

Please update the CommonsInstanceDiscovery to support multiple ports for Consul users.

**Comment by spencergibb** [comment]
Also for Zookeeper users
