### ISSUE TITLE
@FeignClient annotated interface with fallback bean can not be autowired because it is not a unique bean

### ISSUE THREAD

**Issue by lreimer** [spring-cloud/spring-cloud-netflix#899]
I have a problem when auto wiring a feign client with a defined fallback class. Basically, the problem is that now there are two qualifying beans found in the context, the feign client and the fallback bean.

```java
@FeignClient(name = "store", fallback = StoreClientFallback.class)
public interface StoreClient {
}

@Component
public class StoreClientFallback implements StoreClient {}

@Controller
public class StoreController {
    private final StoreClient storeClient;

    // this here will not work
    @Autowired
    public StoreClient(StoreClient storeClient) { this.storeClient = storeClient; }
}
```

I have tried putting @Primary, @Qualifier("name") or a custom qualifier annotation on the feign interface and the constructor of the target bean. No success.

**Comment by cforce** [comment]
I can agree  on this. Did you already tried scoped proxy mode TARGET_CLASS (
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ScopedProxyMode.html#TARGET_CLASS
)

M.-Leander Reimer <notifications@github.com> schrieb am Fr., 11. März 2016
00:08:

**Comment by lreimer** [comment]
A little update on the issue. I have tried the ScopedProxyMode without any success.

Good news is: I tried the @Qualifier("fully.qualified.package.ClassName") annotation again, and it worked. In my real code I was using Lombok to generate the constructor before, and it just did not care about any qualifier. With a hand written constructor everything is fine now.

```java
@Controller
public class StoreController {
    private final StoreClient storeClient;

    // this here will work but is kind of ugly
    // you have to use the fully qualified class name
    @Autowired
    public StoreClient(@Qualifier("storeClient") StoreClient storeClient) { this.storeClient = storeClient; }
}
```

But this is still quite ugly having to use the fully qualified feign interface class name to perform a by name lookup and injection. I would rather prefer using a custom qualifier annotation on the feign interface and injection point or have support for @Primary on the feign annotation.

**Comment by spencergibb** [comment]
The problem is that you have two beans that implement `StoreClient`, so you'll could issues. I would agree that it should be easier than using the name. I have a test that does just what you do. Could you provide a sample that recreates the problem?

**Comment by lreimer** [comment]
Sure I can. I will prepare a test case in a separate branch of my fork. Hope this is OK for you.

**Comment by cforce** [comment]
There is a very similar problem with Type level @RequestMapping annotation on a Feignclient inherited  interface. See "Type level @RequestMapping annotation" in Blog https://jmnarloch.wordpress.com/2015/08/19/spring-cloud-designing-feign-client/

**Comment by ryanjbaxter** [comment]
@patience00 this is not useful enough for us to help.  If you are having a problem with Feign please open an issue here https://github.com/spring-cloud/spring-cloud-openfeign and provide a detailed description as well as a sample.
