### ISSUE TITLE
Refreshing scope for random port based service causes Ribbon issues

### ISSUE THREAD

**Issue by KramKroc** [spring-cloud/spring-cloud-netflix#900]
I've encountered an issue with @RefreshScope and it's behaviour. Two main queries:

1. When the refresh endpoint is invoked, the service effectively does a soft restart and unregisters, then re-registers with Eureka. I thought refreshing the scope would in the main be non-service affecting? Via the rest endpoint, is there a way to refresh a named bean (doc indicates this is so but I've been unable to do so) and would that too trigger a soft restart?
1. My service starts on a random port, i.e. I've set server.port to be 0 in my properties. The restart mentioned above changes initial value assigned to the server port, and changes it to be 0 for the purpose of registering with Eureka. This means the service is effectively uncontactable to any Ribbon/eureka aware load balancer.

See my sample project here which details (manual) test steps:

https://github.com/KramKroc/refreshscope

**Comment by dsyer** [comment]
It looks to me like you are manually setting the eureka (non-secure) port to "server.port" in your service's own YAML config. Isn't that the problem?

**Comment by KramKroc** [comment]
:+1: Great spot there @dsyer 

Are there any side affects to not defining that (non-secure) port? I removed it from the definition and there didn't appear to be.

**Comment by dsyer** [comment]
Not defining it seems to be the best option for you. I can't see why you'd want to do anything else really.
