### ISSUE TITLE
Eureka server url pattern cannot be changed

### ISSUE THREAD

**Issue by hsiliev** [spring-cloud/spring-cloud-netflix#913]
I have a setup with running Eureka server (https://github.com/Netflix/eureka) running on Tomcat with context path `/eureka` and several clients that use the `/eureka/v2` url path.

I want to replace the Eureka server with Spring Eureka, transparently to the existing clients (most of them are acutally node.js apps). 

I deployed the sample app on https://github.com/spring-cloud-samples/eureka, but found out that the api version is stripped from the url. For example there is `/eureka/apps` instead of `/eureka/v2/apps`.

AFAICT the /eureka path is hardcoded in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfiguration.java#L182

How can I use a different url path for eureka server? Is there a property I can specify to change it?

**Comment by sfat** [comment]
possible duplicate #402

**Comment by hsiliev** [comment]
Thanks for pointing the 402 issue out. I don't really care if the REST version is in the URL. However the existing clients get 404 if Eurika server cannot handle `/eureka/v2`. This also makes the current implementation not suitable as drop in replacement, whitout reconfiguring all clients or adding forwarding.

**Comment by spencergibb** [comment]
It is a dup of #402 and we closed it as won't fix.
