### ISSUE TITLE
Service discovery does not work when slash is missing in eureka client server url

### ISSUE THREAD

**Issue by alaczynski** [spring-cloud/spring-cloud-netflix#920]
When eureka client server url does not ends with slash (e.g. eureka.client.service-url.defaultZone=http://localhost:8761/eureka) then discovery client does not obtain services, however service is registered.

**Comment by dsyer** [comment]
I guess we could try and be more liberal there. the slash is mandatory, but we could add it if it is missing.

**Comment by sfat** [comment]
@dsyer I think this can be closed if you closed my PR regarding this issue
