### ISSUE TITLE
Ribbon-transport support

### ISSUE THREAD

**Issue by gt-tech** [spring-cloud/spring-cloud-netflix#922]
Are there plans to support the new ribbon-transport module from Spring-cloud ?
https://github.com/Netflix/ribbon/tree/master/ribbon-transport, RestClient is deprecated ...

**Comment by spencergibb** [comment]
Not yet.

**Comment by venilnoronha** [comment]
I want to give it a try. @spencergibb could you please give me a hint on this.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.
