### ISSUE TITLE
NPE in Feign Client when using ResponseEntity<CustomClass> as response object

### ISSUE THREAD

**Issue by leraei** [spring-cloud/spring-cloud-netflix#924]
I'm getting a NPW when using ResponseEntity<User> as my Response type.

`  Method threw 'java.lang.NullPointerException' exception. Cannot evaluate org.springframework.http.ResponseEntity.toString()`

I can access the returned object. But all values (status, body, header) are null. When testing the server via Insomnia Rest Client the response seems to be correct. So i assume the issue is somewhere in my configuration or in the client.

My dependencies are:

- org.springframework.boot:spring-boot-starter-web:1.3.3.RELEASE
- org.springframework.cloud:spring-cloud-starter-eureka:1.0.6.RELEASE
- org.springframework.cloud:spring-cloud-starter-feign:1.0.6.RELEASE
- com.netflix.feign:feign-gson:8.15.1

Interfaces:
```
@RequestMapping(value = "/v1/users/", produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
public interface RestService {
	@RequestMapping(method = RequestMethod.POST)
	@ResponseBody
	ResponseEntity<User> createUser(@RequestBody @Valid UserRequest userRequest);
}
}

@FeignClient("hello")
public interface FeignRestService extends RestService {}
```

Client:
```
		FeignRestService restClient = Feign.builder()
				.contract(new SpringMvcContract())
				.encoder(new GsonEncoder())
				.decoder(new GsonDecoder())
				.target(FeignRestService.class, "http://127.0.0.1:8001");
		ResponseEntity<User> responseEntity = restClient.createUser(new UserRequest("test@example.com", "password123"));
		return responseEntity.getBody().toString();
```

Server:
```
	@Override
	public ResponseEntity createUser(@RequestBody @Valid UserRequest userRequest) {
		User user = new User(userRequest.getEmail(), userRequest.getPassword());
		users.put(user.getId(), user);
//		return  ResponseEntity.status(HttpStatus.CREATED).body(user);
		return new ResponseEntity<User>(user, HttpStatus.CREATED);
	}
```

Model:
```
public class User {
	private String id;
	private String emailAddress;
	private String password;


	public User(String emailAddress, String password) {
		this.emailAddress = emailAddress;
		this.password = password;

		this.id = UUID.randomUUID().toString();
	}

//getter&setter
```

**Comment by spencergibb** [comment]
Using the feign builder directly leaves out support for `ResponseEntity` by using `GsonDecoder`. All you need to do is put `@EnableFeignClients` on a `@Configuration` class, use `@FeignClient` as you currently do and `@Autowire` `FeignRestService`.
