### ISSUE TITLE
Ribbon load balancer configurable in yml/properties file, and also support spring cloud config

### ISSUE THREAD

**Issue by iamzhout** [spring-cloud/spring-cloud-netflix#927]
Currently only [part of the ribbon configurations](https://github.com/Netflix/ribbon/wiki/Getting-Started) can take effect in configuration file, while not supporting [load balancer rules](https://github.com/Netflix/ribbon/wiki/Working-with-load-balancers), is it possible to also make these lb rules configurable and also support Spring Cloud Config? or is it possible to tell the way how to make the change, and I can work on this.

the items supposed to be supported including:
> NFLoadBalancerClassName
> NFLoadBalancerRuleClassName
> NFLoadBalancerPingClassName
> NIWSServerListClassName
> NIWSServerListFilterClassName

**Comment by OrangeDog** [comment]
+1
I'm hoping this just requires configuring archaius to delegate to the spring application environment.

**Comment by OrangeDog** [comment]
While we're there, it would be very useful if sping-cloud would support a default property prefix to be shared by all ribbon clients.

**Comment by OrangeDog** [comment]
Documentation claims that this already works:

> Spring Cloud has a Spring Environment Bridge so Archaius can read properties from the Spring Environment. This allows Spring Boot projects to use the normal configuration toolchain, while allowing them to configure the Netflix tools, for the most part, as documented.

Must be some other reason it's not working.

**Comment by spencergibb** [comment]
"for the most part" ;-) @jkschneider asked for this yesterday as well.

**Comment by iamzhout** [comment]
@spencergibb so does this mean you will have plan to support this recently?

**Comment by spencergibb** [comment]
@iamzhout it means we plan to support it sometime in the future.

**Comment by OrangeDog** [comment]
Is it because the `NFFooClassName` properties are only used if they are omitted from the builder, but `RibbonClientConfiguration#ribbonRestClient` ensures that they exist and are set?

**Comment by iamzhout** [comment]
@spencergibb Is there any update on this feature implementation plan? 
@OrangeDog I have checked, and seems it has no relation to  `RibbonClientConfiguration#ribbonRestClient`? as I am busy on other things recently, I will check this later.

**Comment by OrangeDog** [comment]
As an extreme, if you declare this:

    @Bean 
    public ILoadBalancer ribbonLoadBalancer(IClientConfig config) {
        return LoadBalanceBuilder.newBuilder()
            .withClientConfig(config)
            .buildLoadBalancerFromConfigWithReflection();
    }

Then it should use all properties you listed (and ignore the default beans).

**Comment by spencergibb** [comment]
Reopening to document

**Comment by spencergibb** [comment]
Closing as there is an open issue to document #1188
