### ISSUE TITLE
Feign (Hystrix?) converting GET to POST when using substitutions in headers

### ISSUE THREAD

**Issue by ChrisCurtin** [spring-cloud/spring-cloud-netflix#928]
Hi,

Using 1.0.6 and 1.1.0.RC this happens. 

Been playing with how to set an access token in a header with Feign. Tried lots of options, none of which are satisfactory. 

Scenario 1: hardcode the Authorization token in the @RequestMapping header value,  server sees GET with Authorization header, works. Except the token is hardcoded :)

Scenario 2: Pass the Access Token as RequestParam, not working since it isn't a header.
```
@FeignClient(name="Location", url="http://localhost:9090")

public interface LocationServiceClient {
    @RequestMapping(method= RequestMethod.GET, value = "/location/warehouse/{family_name}")
    WarehouseLocation getLocation(@RequestParam("access_token") String accessToken,
                                  @PathVariable("family_name") String familyName);
}
```

Scenario 3: use @Headers, nothing in the headers at all on the server

`@Headers("Authorization : {access_token}")`

Scenario 4: change @RequestParam to @Param and Hystrix changes the call to a POST and still no headers. It looks like the access_token is the body of the POST

Scenario 5: Using @Headers change access_token to a @PathParam and same POST problem

Scenario 6: give up on @Headers working, add the headers field to the @RequestMapping. Get the header correctly (!) but still a POST

```
@FeignClient(name="Location", url="http://localhost:9090")
public interface LocationServiceClient {
    @RequestMapping(method= RequestMethod.GET, value = "/location/warehouse/{family_name}",
   headers = "Authorization = Bearer {access_token}")
    @Headers("Authorization : {access_token}")
    WarehouseLocation getLocation(@PathVariable("access_token") String accessToken,
                                  @PathVariable("family_name") String familyName);
}
```

Scenario 7: same as 6, but change @PathVariable to @RequestParameter and get the header, get the GET but the access_token is attached as an URL parameter in addition to being in the header. Except the token is also on the URL now.

So it looks like @Headers never seems to work. headers on the @RequestMapping works, but doesn't remove the access_token from the list of values to be sent like family_name is, so Hystrix thinks this is a GET with a payload so changes it to a POST, which the API won't accept (returns 405).

Any ideas how to pass the access token ONLY as a header?

Thanks

Chris

**Comment by spencergibb** [comment]
Have you tried a `RequestInterceptor`? Feign changes to a POST when there is a body. I'm away from a computer, what @Header annotation are you using?

**Comment by ChrisCurtin** [comment]
Hi Spencer, I haven't tried RequestInterceptor, was hoping the @Headers would work. If I need to I'll try on Monday.

@Headers is from feign.headers

I've tried

@Headers("Authorization : {access_token}")
@Headers("Authorization : Bearer {access_token}")
@Headers("Authorization = {access_token}")
@Headers("Authorization = Bearer {access_token}")
@Headers("{access_token}")

And even
@Headers("Authorization :abc") 
to see if I could get ANYTHING to show up on the server with a header via @Headers. No luck.

The change to a POST appears to be because the access_token parameter passed to the Feign method isn't getting treated only as a header and removed from the set of parameters like the family_name in my example.

Thanks Chris

**Comment by spencergibb** [comment]
Feign annotations don't work, only Spring MVC annotations, isn't there a MVC header annotation (I'm not at a computer).

**Comment by ChrisCurtin** [comment]
Thanks Spencer, I built a RequestInterceptor and was able to add the headers in 1.0.7.RELEASE, but not 1.1.0.RC1.

I followed this example: http://blog.cordsen.de/post/123581098185/spring-cloud-feign-headers

In 1.0.7 the call to get the thread local (where the authentication string is stored) is in the same thread as the set, but in 1.1.0 it is in a separate thread in the Hystrix thread pool. 

Can you point to an example where 1.1.0 uses Feign/Hystrix and a RequestInterceptor?

**Comment by spencergibb** [comment]
In 1.1.0 we use hystrix by default which runs on a different thread, therefor the thread local will have problems. You can disabled feigns hystrix integration.

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by rohitdec01** [comment]
We can pass header.


@Component
public class AdapterRequestInterceptor implements RequestInterceptor {

	/* (non-Javadoc)
	 * @see feign.RequestInterceptor#apply(feign.RequestTemplate)
	 */
	@Override
	public void apply(RequestTemplate requestTemplate) {
		HttpHeaders headers = new HttpHeaders();
		headers.setAccept(Arrays.asList(new MediaType[] { MediaType.APPLICATION_JSON }));
		headers.setContentType(MediaType.APPLICATION_JSON);
		// Other header values -- from a dynamic function.
		

		addHeadersToRequest(headers, requestTemplate);
		System.out.println("Test");
	}

	/**
	 * @param headerParams
	 * @param requestBuilder
	 */
	private void addHeadersToRequest(HttpHeaders headerParams, RequestTemplate requestBuilder) {
		for (Map.Entry<String, List<String>> entry : headerParams.entrySet()) {
			String headerName = entry.getKey();
			for (String headerValue : entry.getValue()) {
				requestBuilder.header(headerName, headerValue);
			}
		}
	}

}
