### ISSUE TITLE
Dynamically override the host name properties of eureka server

### ISSUE THREAD

**Issue by maxiplay** [spring-cloud/spring-cloud-netflix#929]
Hello,

From a a eureka client, I want to dynamically override the host name properties of eureka server at startup using environnements variable.

The code used

    @Order(-1000)
    @Configuration
    public class ConfigRegistryOverrider {

	@Bean
	@ConditionalOnMissingBean(value = { EurekaClientConfig.class }, search = SearchStrategy.CURRENT)
	public EurekaClientConfig eurekaClientConfigBean() {
	
		
		EurekaClientConfigBean eurekaClientConfigBean = new EurekaClientConfigBean();
			
		Map<String, String> env = System.getenv();
		
		if (env.get("REGISTRY_SERVICE_HOST") != null) {
			
			String host = env.get("REGISTRY_SERVICE_HOST");
			Map<String, String> serviceUrls = new HashMap<>();
			serviceUrls.put("defaultZone", "http://"+host+":8761/eureka/");
			eurekaClientConfigBean.setServiceUrl(serviceUrls);
			
		}

		return eurekaClientConfigBean;
	}
}

I used a similar strategy with mongo and redis host customizing and there is no problem.

But with Eureka it seems there is a kind of @refreshScope that override my override at startup.

Could you help me ?

**Comment by spencergibb** [comment]
Why can't you do `eureka.client.serviceUrl.defaultZone: ${REGISTRY_SERVICE_HOST}` in application.yml? Can you explain the problems your seeing?

**Comment by maxiplay** [comment]
All I know is my EurekaClientConfigBean has been initialized before all. So it's ok. But my serviceUrls properties overriding seems to be changed after because 

	@Configuration
	@ConditionalOnMissingRefreshScope
	protected static class EurekaClientConfiguration {

in class EurekaClientAutoConfiguration has the original value from application.properties.

I suppose there is a "refresh" that re-read the application.properties for EurekaClientConfigBean but it's difficult to find.

After trying your proposition, yes it work now (even if I had to restart my windows computer in order to the environnement variable be taken in account, strange, perhaps the jvm). Your solution is more concise that me ^^. But developpers now have to set environnement variable during installation process to run on localhost. Accordingly to https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html, perhaps I can use a Profile-specific application properties to set localhost on local dev and make use of PropertySource order ?

**Comment by dsyer** [comment]
Indeed that should work. Or you can specify a default value fro when the env var is not set.
