### ISSUE TITLE
Add ability to provide custom RetryHandler in RibbonClientConfiguration

### ISSUE THREAD

**Issue by tkvangorder** [spring-cloud/spring-cloud-netflix#931]
I am trying to add an exception to the list of exceptions that will denote a circuit breaker error. If we get a host registered in Eureka that cannot be resolved via DNS,  we get an "UnknownHostException". I would like these exceptions to result in the server being pulled from the list of valid servers when using the AvailabilityFilteringRule

My retry handler looks like the following: 

```java
import java.net.UnknownHostException;

import com.netflix.niws.client.http.HttpClientLoadBalancerErrorHandler;

public class CustomRetryHandler extends HttpClientLoadBalancerErrorHandler {
	
	public CustomRetryHandler() {
		circuitRelated.add(UnknownHostException.class);
		retriable.add(UnknownHostException.class);
		
	}
}
```

I have had a hard time getting this custom handler injected into my ribbon client configuration. I was expecting to be able to just declare a bean in my ribbon client configuration: 

	@Bean
	public RetryHandler buildRetryHandler() {
		return new BuildRetryHandler();
	}

But looking at the RibbonClientConfiguration, I doesnt appear this will be used. I was able to get this working by overriding the RestClient bean...but this is messy because I also had to copy the "OverrideRestClient class:

```java
	@Bean
	public RestClient ribbonRestClient(IClientConfig config, ILoadBalancer loadBalancer,
			ServerIntrospector serverIntrospector, RetryHandler retryHandler) {
		RestClient client = new OverrideRestClient(config, serverIntrospector);
		client.setRetryHandler(retryHandler);
		client.setLoadBalancer(loadBalancer);
		Monitors.registerObject("Client_" + this.name, client);
		return client;
	}
```
 
It would be much nicer to just include this natively in the RibbonClientConfiguration, although I am not sure if this is the best way to get this working?

Thanks

**Comment by spencergibb** [comment]
Similar to #505

**Comment by spencergibb** [comment]
I say similar because it has to do with feign. It may turn out to be a duplicate.

**Comment by tkvangorder** [comment]
Thanks, I will take a closer look at that issue. This retry logic is specific to my work on getting the RestTemplate to retry automatically and insure its updating the server's statistics as part of each call. I have it mostly working and I have a unit test that is similar to your recently added unit test: [FeignRibbonClientRetryTests](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/feign/ribbon/FeignRibbonClientRetryTests.java)

**Comment by spencergibb** [comment]
Nice PR's welcome.

**Comment by tkvangorder** [comment]
Once I am confident  it is working, I will submit one.

**Comment by spencergibb** [comment]
Now that we've dropped an RC1 (bugfixes), not sure if this would make it to Brixton until a SR1. @dsyer is that correct?

**Comment by tkvangorder** [comment]
@spencergibb What do you think of this pull request? 

https://github.com/spring-cloud/spring-cloud-netflix/pull/933
