### ISSUE TITLE
RibbonClientConfiguration isn't very useful

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-netflix#935]
Maybe I'm missing something here.

AFAIKT if you have `@RibbonClient(name = "client-name", configuration = Config.class)` somewhere in component scan, then a `@LoadBalanced RestTemplate` will be created using first the beans from `Config.class` and then the beans from a `RibbonClientConfiguration` instance with the `name` magically set to `"client-name"`.

However, I can't find a case where this is useful unless I only want the defaults.
If I'm trying to provide an alternate bean for e.g. `ribbonRestClient` in `Config.class` I can't, because the dependent config and balancer beans haven't been defined yet.

Likewise, if I override as much as I need to construct e.g. a `ribbonLoadBalancer`, e.g. without creating an `IPing` bean, `RibbonClientConfiguration` pointlessly constructs one for me anyway afterwards.

It gets even harder to use when you have multiple services needing ribbon clients.
Are you supposed to just explicitly qualify every bean?

How was this intended to be used?
Is there a better way to be overriding single beans, or accessing the defaults in other configuration?
Can `RibbonClientConfiguration` just be disabled if I don't need its beans at all?

**Comment by spencergibb** [comment]
What version are you using? `RestTemplate` is no longer created by default in Brixton. You'll have to be more specific than you are. We have many tests and code that only override one or two of the defaults without any problem. You'll need to provide some samples of what you are doing, because `RibbonClientConfiguration` is very useful.

**Comment by OrangeDog** [comment]
I'm using spring-cloud-dependencies:Angel.SR6, there is no higher version of it available on Maven.
Should I be looking elsewhere?

What I was initially trying to do is just use a different JerseyClient to the default, but any attempt to change or post-configure one of the default beans seems to result in having to re-implement the whole thing.

**Comment by spencergibb** [comment]
Brixton.RC1 is out. I just ask about version to get perspective. I still don't understand how overriding one bean leads to "re-implement the whole thing" without seeing something.

**Comment by OrangeDog** [comment]
I can put together something more specific tomorrow.

For now, see my example config in #940 for an idea of what I'm doing.
There's no way to just override the ribbonRestClient bean, because none of the dependencies are available.

**Comment by spencergibb** [comment]
Ok, `@RibbonClient` needs to go on an `@Configuration` class (normally your boot app or another class that isn't referenced in `@RibbonClient`. The `name` attribute is what you reference in `RestTemplate.get*("http://<client-name>/...);`. You shouldn't have to create anything in `RibbonClientConfiguration` that you don't want to override, like `IClientConfig`. A sample project would be helpful.

**Comment by OrangeDog** [comment]
Hmm, but `@RibbonClient` already has `@Configuration` as a meta-annotation.
I assumed (and the docs didn't say otherwise) that there was no need for an extra configuration class.
I'll give your suggestion a go.

**Comment by OrangeDog** [comment]
OK, it works only if `@RibbonClient.configuration` does not reference a `@Configuration` class, or an inner class of a `@Configuration` class.

The latter condition especially tripped me up, as I was trying to keep things in the same file.
