### ISSUE TITLE
Documentation - Ribbon from RestTemplate to annotation driven config

### ISSUE THREAD

**Issue by JoranBergfeld** [spring-cloud/spring-cloud-netflix#937]
Hi, 

I'm strugling to find a way to migrate my project from an autowired and autoconfigured rest template to annotation driven configuration that is now supported by 1.1.0.RC. Is there some documentation as to how to go about this? 

Must admit, I'm fairly new to using spring-cloud-netflix, so I might have missed some documentation. 

Thanks!

**Comment by spencergibb** [comment]
Is this what you're looking for? https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#spring-resttemplate-as-a-load-balancer-client

**Comment by JoranBergfeld** [comment]
Oh yeah. That's great. Thanks! Will be reading that tomorrow.
