### ISSUE TITLE
Bad Spring Boot dependency in spring-cloud-starter-parent-Brixton.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by the4yeast** [spring-cloud/spring-cloud-netflix#938]
Looking at the docs (http://projects.spring.io/spring-cloud/), it looks like Brixton.BUILD-SNAPSHOT should use Spring Boot 1.3.3. 
However, the most recent SNAPSHOT (http://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-starter-parent/Brixton.BUILD-SNAPSHOT/spring-cloud-starter-parent-Brixton.BUILD-20160327.090548-43.pom) declares 1.3.2.

Is that intentional? It pretty much causes my Spring Boot dependencies to resolve to 1.3.2. I'm, not really a fan of the approach described in https://spring.io/blog/2015/11/25/migrating-spring-cloud-apps-from-spring-boot-1-2-to-1-3 and would like to avoid it.

**Comment by spencergibb** [comment]
That blog post needs a follow on now.  This is how you should declare you spring-cloud BOM import
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-dependencies</artifactId>
      <version>Brixton.RC1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

This frees you from a parent declaring a boot parent.

**Comment by the4yeast** [comment]
Thanks @spencergibb, that solves the issue.
