### ISSUE TITLE
Zuul URL parameter duplicated so single value becomes comma separated

### ISSUE THREAD

**Issue by bgawne** [spring-cloud/spring-cloud-netflix#941]
There is a definite bug in the spring-cloud/spring boot stack.
With spring boot 1.3.3.RELEASE and spring cloud Brixton.RC1 , with rest based springboot app and only eureka and the cloud-starter-config from spring cloud as dependencies, when I create a rest call which accepts parameters and comes in from via an HTTP POST , the parameter values are duplicated and concatenated with a comma. So for example, if I have a URL like : www.foo.com?A=1 then when it comes into the function inside the rest controller, the variable is passed in as "1,1".
It only does this with String parameters, ive checked others and there are no problems.

GET works properly, but POST and PUT both do this.

I am coming in routed through Zuul/Eureka with the Ribbon load balancer.

Any ideas how I can quickly fix this or where to look?

I tried writing a filter in zuul to fix, but everything is good when it reaches the filter (which I made last in the chain of "pre" filters), so its happening somewhere after prefilters run I guess.

Any advice would be much appreciated.

Brad

**Comment by dsyer** [comment]
Works for me. Can you share a sample please?

**Comment by vasilievip** [comment]
@bgawne please check:
https://github.com/spring-cloud/spring-cloud-netflix/issues/1080

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pusha1982** [comment]
I'm also getting string parameters duplicated in case of `MultipartRequest`:
I have POST request with few string parameters and one `MultipartFile `parameter. All string params are duplicated.
I've found that issue again comes from `FormBodyRequestWrapper` in `getInputStream` as mentioned in #1080 
If I move string parameters from body to query string and leave only `MultipartFile `in body, everything works fine.

**Comment by Sadarang** [comment]
Hi @spencergibb , @dsyer

I  am using zuul proxy for request routing so i have given -

zuul.routes.abc.path=/api/v1/datafromhana/**
zuul.routes.abc.url=${partner.hana.host.url}/lmn/VSSERVICE/abc/xyzjdas/Partner/GetCurrentCustomerList.xsjs?PartnerID=1101293

in properties file. but when i try to hit- http://domainname//api/v1/datafromhana/ it should idealy routed as it is to the given url, instead it is removing - "?PartnerID=1101293" and i am not able to get json data.

Please suggest the way to solve this issue.

**Comment by vijayshegokar** [comment]
I'm also facing the same issue.
