### ISSUE TITLE
Make zuul.sensitive-headers configurable globally rather than per-route

### ISSUE THREAD

**Issue by timtebeek** [spring-cloud/spring-cloud-netflix#944]
As mentioned [on stackoverflow](http://stackoverflow.com/questions/36359915/authorization-header-not-passed-by-zuulproxy-starting-with-brixton-rc1) and discussed [on Gitter](https://gitter.im/spring-cloud/spring-cloud?at=56fe9db6d478c81e2cbc38bc).

My setup is comprised of:
- Multiple resource servers that use JWTs to make access decisions based on token contents.
- Zuul proxy server that uses eureka to discover and route ~25 resource servers.
- Zuul proxy routes traffic for 9 clients, each having access to only some resources (so not a client in itself). (think: api.company.com)
- Zuul proxy server does not interact with passed tokens in any way (does not even have security dependencies).

Given that:
- Sensitive headers are dropped from both up and downstream zuulproxy requests.
- Sensitive headers are set to `Cookie,Set-Cookie,Authorization` by default.
- Sensitive headers are configurable only per route, and not globally.

Since RC1 my Zuul Proxy now strips the `Authorization` headers, meaning I have to manually define my routes to set `zuul.routes.myservice.sensitive-headers=Cookie,Set-Cookie` on each. Could this be adapted to allow `zuul.sensitive-headers` to be set globally, like we can do with `zuul.ignoredHeaders`?

**Comment by timtebeek** [comment]
@jebeaudet suggested a workaround for now that also seems to work:
```
@Component
// XXX While waiting for: https://github.com/spring-cloud/spring-cloud-netflix/issues/944
public class RelayTokenFilter extends ZuulFilter {
	@Override
	public Object run() {
		RequestContext ctx = RequestContext.getCurrentContext();

		// Alter ignored headers as per: https://gitter.im/spring-cloud/spring-cloud?at=56fea31f11ea211749c3ed22
		Set<String> headers = (Set<String>) ctx.get("ignoredHeaders");
		// We need our JWT tokens relayed to resource servers
		headers.remove("authorization");

		return null;
	}

	@Override
	public boolean shouldFilter() {
		return true;
	}

	@Override
	public String filterType() {
		return "pre";
	}

	@Override
	public int filterOrder() {
		return 10000;
	}
}
```

**Comment by spencergibb** [comment]
Started working on this. Question for @timtebeek and @dsyer should route specific sensitive headers override globals or merge? Now that I'm asking the question, I think it should be override, but want your opinions.

**Comment by spencergibb** [comment]
See PR #963

**Comment by dsyer** [comment]
+1 for override
