### ISSUE TITLE
Log warning when ServoMonitorCache reaches certain configurable size.

### ISSUE THREAD

**Issue by ramblingred** [spring-cloud/spring-cloud-netflix#947]
A couple of our Spring Cloud services have been dying with "GC Overhead Limit Reached" after a couple of days of running. Digging into the heap dump it appears the culprit is the way that RestTemplate/Servo is dynamically converting URIs into MonitorConfigs for ServoMonitorCache.

When DefaultMetricsTagProvider is building the "uri" metric tag it uses the full unique URI including any embedded path variables... This is then used register a brand new Monitor/MBean etc. In our case we are making hundreds of unique calls per minute to “/orders/{orderId}“ and each individual order registers a new entry and eventually we run out of memory.

I’m not really sure the best solution here. Without RestTemplate knowing the semantics of a given URI I don’t really see a safe way to automagically create a unique key based on the uri string alone. From my perspective this feature probably needs to be something you can manually override (enable?) by adding pattern matched URIs in the configs. Avoiding all URIs with a dynamic path isn't really an option for us… For the time being we have excluded the ServoMetricAutoConfiguration in our base YML. 

Let me know if I'm missing something... I'd be happy to take a stab at a PR if the suggestion above sounds viable.

Using Brixton.RC1 & SB 1.3.3.

**Comment by spencergibb** [comment]
Hmm, according to the code, the intent was to use the templated uri, so `/orders/{orderId}` in your case.

**Comment by spencergibb** [comment]
Running it, it indeed uses `/orders/1`.

**Comment by spencergibb** [comment]
wait, just may be user error on my side.

**Comment by spencergibb** [comment]
Changing my `RestTemplate` call to this:
```
restTemplate.getForObject("http://testeurekabrixtonclient/orders/{orderid}", String.class, orderid)
```

I see this in `/metrics`
```
gauge.servo.response.orders.orderid: 7
```

What are you seeing?

**Comment by ramblingred** [comment]
Ah! It looks like we were using RestTemplate with pre-built URIs and passing the whole thing as a string. So I guess RestTemplate _does_ know the semantics when you use it right. Fixed up code on my side and now the metrics look right. Thanks!

I'm wondering if there should be some sort of warning from the ServoMonitorCache in the case that it notices 1000+ keys (or whatever threshold) getting registered in the timerCache? This currently feels like a pretty subtle way to run yourself out of memory and it's not particularly intuitive to hunt the leak down. Thoughts?

**Comment by KramKroc** [comment]
@spencergibb @ramblingred guys, just encountered this issue. I've followed the thread but I'm struggling to understand what the correct format of the URI call should be.

@ramblingred would you be able to provide example of what was wrong previously and what you then changed it to?

**Comment by spencergibb** [comment]
@KramKroc use a templated rest template url. 

```
String orderid = "1";
restTemplate.getForObject("http://testeurekabrixtonclient/orders/{orderid}", String.class, orderid)
```
instead of 
```
restTemplate.getForObject("http://testeurekabrixtonclient/orders/1", String.class)
```

**Comment by KramKroc** [comment]
@spencergibb in our case, we are using getForEntity without any uri variables, does that complicate things from your experience, or how would we work around the issue in that case. For example:

`restTemplate.getForEntity("http://testeurekabrixtonclient/orders?orderId=1&sortOrder=reverse", Order.class)`

**Comment by spencergibb** [comment]
"without any uri variables" is the cause of this problem. You can use uri variables with `getForEntity`.

**Comment by tiny-dancer** [comment]
ah this one was a pesky annoyance for awhile.  although in general practice a parametized url is preferred, any chance we could throw in a more explicit fyi in the docs? (http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html) not sure if those docs on github, happy to open a pr if they are

**Comment by ryanjbaxter** [comment]
@tiny-dancer docs are located in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc

**Comment by wyzssw** [comment]
Disable ServoMetrics by add spring.metrics.servo.enabled=false to application.properties

**Comment by insoz** [comment]
> orelse you would suffer Memory Leak From ServoMonitorCache
I added this , but looks like it's not working , what i missing ?
