### ISSUE TITLE
Zuul ignores DELETE request body

### ISSUE THREAD

**Issue by MadMichael888** [spring-cloud/spring-cloud-netflix#949]
Hi,

I have a spring mvc controller which process DELETE request, the RequestBody of the request has a list of ids. It works fine when running alone. But once I put the service behind a zuul service, the DELETE request body is missing.

Has anyone encountered the same problem?

Thank you,
Mike

Here is the controller method:

	@RequestMapping(value = "/test", method = RequestMethod.DELETE)
	public ResponseEntity<Void> testDelete(@RequestBody POJO pojo) {
		log.info("Got delete request : {}", pojo);
		return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
	}

**Comment by MadMichael888** [comment]
The warning msg I got when running behind a zuul server is:
WARN  | 2016-04-05 12:41:23 | [XNIO-2 task-3] support.DefaultHandlerExceptionResolver (DefaultHandlerExceptionResolver.java:377) - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<java.lang.Void> com.test.controller.Controller.testDelete(com.test.POJO)

**Comment by spencergibb** [comment]
What version are you using?

**Comment by MadMichael888** [comment]
spring-cloud-starter-zuul version 1.1.0.M5
from spring-boot-starter-parent version: 1.3.3.RELEASE

Thanks,

**Comment by jmirc** [comment]
do you have any news on this? I have the same problem.
Thanks

**Comment by MadMichael888** [comment]
No, I had to work around it by putting the body info in url.

**Comment by spencergibb** [comment]
You can try using a `HttpClientRibbonCommandFactory` which doesn't use the old netflix `RestClient`.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/918#issuecomment-218014092 for details

**Comment by prontera** [comment]
I have encountered the same problem, but `HttpClientRibbonCommandFactory` does not help me to solve the "Delete Method" problem.

**Comment by spencergibb** [comment]
@prontera I do have a test that passes without a body https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/zuul/filters/route/apache/HttpClientRibbonCommandIntegrationTests.java#L90-L97

**Comment by prontera** [comment]
Great, it works fine without a body, but we want to process the DELETE request with request body in fact(e.g. list of id or anything else). 
May it be possible to process a HTTP request with body or available in future version.
Thanks a lot.

**Comment by ervansetiawan** [comment]
We do have the same problem. I know that there are a lot of interpretations and discussions regarding this but there are some use cases for us that makes DELETE with a request body a good solution. 

I am wondering if Zuul should take an un-opinionated stance on this and let the downstream service make a decision whether DELETE with request body should or should not be allowed.

**Comment by spencergibb** [comment]
Previously the ribbon http client failed if delete had a body. Since it is no longer the default, we can probably move this functionality to the specific client implementation.
