### ISSUE TITLE
Feign inheritance

### ISSUE THREAD

**Issue by tomhughesnice** [spring-cloud/spring-cloud-netflix#951]
I have been trying to get Spring cloud Feign inheritance working, but upon looking at the latest documentation http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-inheritance

I see the following note has been added.
> It is generally not advisable to share an interface between a server and a client. It introduces tight coupling, and also actually doesn’t work with Spring MVC in its current form (method parameter mapping is not inherited).

I saw Feign as a simple way to share the connection contract between a client and server app. I would just add the shared interface into another jar which the client and server would both depend upon.

But from the note it appears the functionality I desire is actively discouraged due to 'tight coupling'. Surely having a shared defined contract between client and server is a good thing as it will lead to less errors.

**Comment by spencergibb** [comment]
There are a couple of issues. First there is tight coupling, the client and server may need/want to change independently of each other. Second, some things, the client only cares about one representation ([json/form/etc...) where the server needs to know about all of them. @adriancole can articulate it better then I can :-). It's just our warning. If you come asking for features based on sharing, we're likely to say no without a compelling reason.

Beyond the comment and discussion, was there a problem doing what you wanted?

**Comment by tomhughesnice** [comment]
I understand your point but I think it too idealistic for me. I would prefer the safety of tight coupling with a shared contract to avoid programmer errors.

I am wondering what is what is the point in offering feign inheritance as an option? As it is not advised due to your previous comment, and it does not work anyway due to the current Spring MVC implementation.

**Comment by spencergibb** [comment]
We're not forcing you to not use inheritance as you want. The point was to share common methods (like CRUD) across clients.

**Comment by cforce** [comment]
I also see many advantages sharing it. It works with some restriction.
Checkout this
https://jmnarloch.wordpress.com/2015/08/19/spring-cloud-designing-feign-client/

Spencer Gibb <notifications@github.com> schrieb am Mi., 6. Apr. 2016 15:55:
