### ISSUE TITLE
Don't enable RibbonClientHttpRequestFactory by default

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-netflix#961]
This should be opt-in as Ribbon's `RestClient` is deprecated.

**Comment by tkvangorder** [comment]
One last thought on this: Isn't the use of RibbonClientHttpRequestFactory already an opt-in because you must annotate your rest template bean with `@LoadBalanced`? It seems redundant to also have to opt-in with an environment property as well. 

What is the behavior when the property `ribbon.http.client.enabled` is false but a RestTemplate has been annotated with `@LoadBalanced`? Is there a plan to use an alternate request factory that uses some other mechanism for load balancing?

**Comment by spencergibb** [comment]
@tkvangorder The commons [`LoadBalancerInterceptor`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java) kicks in. It uses the standard spring wired http client. `RibbonClientHttpRequestFactory` was mostly a request from Netflix. When I met with them last week, we decided it should be opt in.

**Comment by tkvangorder** [comment]
Gotcha, makes sense.

**Comment by vajda** [comment]
Is there any ClientHttpRequestFactory provided by default to use with restTemplate for service discovery (use of http://serviceId/something) instead of RibbonClientHttpRequestFactory?

**Comment by jkschneider** [comment]
@vajda Could you please clarify the question? `RibbonClientHttpRequestFactory` is what provides the functionality that allows you to use client names (e.g. serviceId) in your requests. Are you looking for a non-Ribbon alternative?

**Comment by spencergibb** [comment]
@vajda & @jkschneider We have two implementations:

1. The commons [`LoadBalancerInterceptor`](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/LoadBalancerInterceptor.java) just reconstructs the url and lets vanilla spring handle the http connection. This is the default. It is not a `ClientHttpRequestFactory` but a request interceptor.
2. The spring cloud netflix `RibbonClientHttpRequestFactory` which uses the netflix ribbon client to for http. This is not enabled by default. You must use `ribbon.http.client.enabled=true` to use it. This is the only `ClientHttpRequestFactory` we have.

**Comment by tkvangorder** [comment]
@spencergibb @jkschneider 

A question I have: Since the Netflix ribbon http client has been deprecated and the code hints at using the Netflix Netty client instead, are there any plans to add a RibbonNettyClientHttpRequestFactory when using the AsyncRestTemplate?

**Comment by spencergibb** [comment]
From what I understand, they don't use it either:

- https://github.com/Netflix/ribbon/issues/248#issuecomment-209131962
- https://github.com/Netflix/ribbon/issues/243

What I can see happening is a reactive http client coming in Spring 5 via Boot 2 that we would integrate with.

**Comment by tkvangorder** [comment]
Makes sense, thanks for the clarification.

**Comment by vajda** [comment]
@spencergibb Thanks for clarification.
