### ISSUE TITLE
Zuul filter to pass session id to backend services

### ISSUE THREAD

**Issue by ezraroi** [spring-cloud/spring-cloud-netflix#965]
Hi,
I am using Zuul as my API Gateway and it is in charge of making all authentication (using kerebros). I stored the user in Spring Session in a Redis database with Spring Session Module. 
I use HeaderHttpSessionStrategy to store the session id in the `x-auth-token` header. 
Is there a way to add that header to all requests that are going to the backend service?

If the header is not added  I will have to create a session and after this add the header myself in all other requests. If the header will be automatically added to all requests we will be able to spare the first request and the session created in first request will be used by the backend service also.

I wrote a filter that make it, is this the right way?

```java
public class SessionHeaderPasFilter extends ZuulFilter {

    private static Logger logger = LoggerFactory.getLogger(SessionHeaderPasFilter .class);
    private final String session_header;

    public TestFilter(String session_header) {
        this.session_header = session_header;
    }


    @Override
    public String filterType() {
        return "pre";
    }

    @Override
    public int filterOrder() {
        return 10;
    }

    @Override
    public boolean shouldFilter() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        return auth != null;
    }

    @Override
    public Object run() {
        HttpSession session = RequestContext.getCurrentContext().getRequest().getSession();
        if (session != null) {
            RequestContext.getCurrentContext().addZuulRequestHeader(session_header, session.getId());
        }
        return null;
    }
}
```

**Comment by spencergibb** [comment]
@ezraroi LGTM

**Comment by ezraroi** [comment]
Thanks

**Comment by sagarjadhav968** [comment]
thx
