### ISSUE TITLE
@FeignClient  -  root context path

### ISSUE THREAD

**Issue by tzebrowski** [spring-cloud/spring-cloud-netflix#966]
Hi,

 I have a case where the endpoint has root path defined at  the top level, on the interface, like below

```
@RequestMapping("/foo/")
public interface FooService{

@RequestMapping("/foo1/")
public void foo1();
.....
@RequestMapping("/foo100/")
public void foo100();
}
```
I have client interface which relays on @FeignClient which has similar definition
```
@RequestMapping("/foo/")
@FeignClient(name = "fooService")
public interface FooServiceClient{

@RequestMapping("/foo1/")
public void foo1();
.....
@RequestMapping("/foo100/")
public void foo100();
}
```
Definition also could look like as follows
```
@FeignClient(name = "fooService")
public interface  FooServiceClient extends FooService {}
```

The result of such feign client definition is that spring registers another endpoint on the client side with root  path /foo/foo1,/foo/foo2....

Another issue appears when we define fallback class which is inherited from the FooServiceClient.
Spring also tries to register another endpoint with the same definition as FooServiceClient service has.
```
@FeignClient(name = "fooService", fallback = FooServiceFallback .class)
public interface FooServiceClient extends FooService {
}

@Component
public class FooServiceFallback  implements FooServiceClient {
     
}
```

My question is whenever we can pass  root path to the @FeignClient in the different way, to avoid necessary endpoint registration?

**Comment by spencergibb** [comment]
We don't support putting `@RequestMapping` on the Feign interface. This is a limitation of Spring MVC in that beans that are annotated with `@RequestMapping` on the class are registered as beans even thought they aren't annotated with `@Component`.

**Comment by tzebrowski** [comment]
Ok. My question is rather, how I can pass root-path to the @FeignClient then. Let's assume that I would change the definition of FooService to the form as bellow

```
public interface FooService{

@RequestMapping("/foo1/")
public void foo1();
.....
@RequestMapping("/foo100/")
public void foo100();
}
```

```
@RequestMapping("/foo/")
public interface FooServiceImpl implements FooService{

public void foo1();
.....
public void foo100();
}
```
This change makes that service is available on the same address

/foo/foo1
....
/foo/foo100


When we back to our definition of FooServiceClient 
```
@FeignClient(name = "fooService", fallback = FooServiceFallback .class)
public interface FooServiceClient extends FooService {
}
```
we will see two changes

- /foo/foo1; ... ; /foo/foo100 endpoints will not registers on the client side
- FooServiceClient will stop working

The reason that it will stop working is that is dosent have root path to service.
Instead of calling /foo/foo1 ... /foo/foo100 it will try to call /foo1 ... /foo100.
In that case he knows nothing about root-path to the service and indicates that  fallback always be executed.

So my question is, how to pass this root-path to the @FeignClient then?

**Comment by spencergibb** [comment]
Repeat the root mapping.
```
@RequestMapping("/foo/foo100/")
public void foo100();
}
```

**Comment by tzebrowski** [comment]
This is an option, but:) then  I will have to repeat it for each method.
I purposely presented definition of FooService in that way

@RequestMapping("/foo1/")
public void foo1();
.....
@RequestMapping("/foo100/")
public void foo100();

For some reason I would not like to follow that way.
