### ISSUE TITLE
Question : Feign Client Retry every 5 seconds

### ISSUE THREAD

**Issue by royremi** [spring-cloud/spring-cloud-netflix#970]
I'm Using Brixton.RC1 and since I moved to there from M5 I have an issue with my feign client that always retry after 5 seconds. It was not there in Brixton.M5.

Is something changed?

I tried to put 
ribbon.ReadTimeOut=60000
ribbon.ConnectTimeOut=60000

but I have the impression that all of that is ignored by my code.

Someone can tell me what is wrong?

Thanks in advance

**Comment by dsyer** [comment]
Timeout settings have nothing to do with retry as far as I know. Do you have a simple sample app that demonstrates the problem?

**Comment by royremi** [comment]
[test.zip](https://github.com/spring-cloud/spring-cloud-netflix/files/224448/test.zip)

I did 2 small project, 1 client 1 server. 

If you run it, and look the log of server you will see than for 1 call you will receive at lease 5-6 times the same call. I probably miss something but absolutely not able to find what. Thanks for the help.

**Comment by royremi** [comment]
Is someone had chance to look at my problem and run my little test application.

What I don't want to retry every second but I try to set multiple variable and it's always ignore.

It's fine with Brixton.M5 but Not with RC1 and RC2.

Thanks

**Comment by dsyer** [comment]
I'm not sure what changed. It seems that the `ribbon.*` properties are not being used in the Feign client. I'll see if we can get it fixed for 1.1.0.

**Comment by royremi** [comment]
I think I found a work around.

I did a configuration class and add a new Request.Options

```
import feign.Request;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FeignConfiguration {
    @Value("${feign.connectTimeout:600000}")
    private int connectTimeout;

    @Value("${feign.readTimeOut:600000}")
    private int readTimeout;

    @Bean
    public Request.Options options() {
        return new Request.Options(connectTimeout, readTimeout);
    }
}
```
And I set that config class to the @FeignClien(name="MyService", configuration=FeignConfiguration.class)
It look to work fine

**Comment by dsyer** [comment]
You have to be careful with the spelling. "Timeout" is a single word, capitalized, in all the Netflix code. I don't know what changed since M5, but if you spell the property names correctly your app works for me. The names of the config properties are enumerated in `com.netflix.client.config.CommonClientConfigKey`. The Spring Cloud user guide spells them correctly in all the examples.
