### ISSUE TITLE
Zuul support for https proxy

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#988]
Basically want to check whether any way Zuul itself can be exposed via https(using SSL certs)
Does Zuul support the equivalent of following apache httpd configuration

```
ServerName XXX.com 
SSLEngine on 
 SSLProtocol -all +SSLv3 +TLSv1 
 SSLCipherSuite ALL:!aNULL:!ADH:!eNULL:!EXPORT:!SSLv2:!LOW:!3DES:!PSK:!MD5:!EXP:RC4+RSA:+HIGH:+MEDIUM

    SSLCertificateFile <cerfile>
    SSLCertificateKeyFile <pemfile>


    <Files ~ "\.(cgi|shtml|phtml|php3?)$">
            SSLOptions +StdEnvVars
    </Files>
    <Directory "/var/www/cgi-bin">
            SSLOptions +StdEnvVars
    </Directory>

    SetEnvIf User-Agent ".*MSIE.*" \
    nokeepalive ssl-unclean-shutdown \
    downgrade-1.0 force-response-1.0
```

**Comment by spencergibb** [comment]
Zuul as we deliver it is just a spring boot application. So the SSL configuration is on boot itself.

**Comment by rbkumar88** [comment]
Hi,

Thanks for the reply. SSL configuration can be set using Spring boot settings.
Currently, we have an enterprise F5 LTM which handles the incoming request and we have exposed urls via apache httpd configuration (say., XXX.com ,YYY.com etc.using same cert).

The basic idea/requirement here is not to use(hide) port numbers and implement the same using Zuul, so that we can access applications using https://XXX.com/service1/.....

Thanks
