### ISSUE TITLE
How to set zone for Eureka-Ribbon-Client-Configuration

### ISSUE THREAD

**Issue by stefanocke** [spring-cloud/spring-cloud-netflix#991]
When registering a service with Eureka, its zone can be set by the property eureka.instance.metadataMap.zone

When using Ribbon in this service, it is also necessary to tell Ribbon, which zone the service is in, since  for example the zone aware server list filters use it for zone affinity.

How can the zone be set for Ribbon?

In [EurekaRibbonClientConfiguration](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/ribbon/eureka/EurekaRibbonClientConfiguration.java#L109) I see only 2 ways:  

- the zone is approximated from the hostname
- the zone is the **first zone** from availibility-zones list.

So there seems to be no way, **how to explicitely set the zone if there are multiple zones**.  
(There is a comment in the code "You can set this with archaius.deployment. ..." but I have not found any example on how to do this. I tried to set  archaius.deployment.zone in application.yml but with no success)

IMHO, it would be more consistent to set the zone to eureka.instance.metadataMap.zone instead of using the first value from eureka.client.availibility-zones

It seem, in former times it was done like this: https://github.com/spring-cloud/spring-cloud-netflix/blob/884785b816a61a1bc196e4917109b0a13c6e0944/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/ribbon/eureka/EurekaRibbonInitializer.java#L43

Best Regards,
Stefan.

**Comment by dsyer** [comment]
Apparently the `archaius.deployment.*` config keys are deprecated and there never was one for zone anyway. The "deployment" keys are defined in the archaius [DeploymentContext](https://github.com/Netflix/archaius/blob/master/archaius-core/src/main/java/com/netflix/config/DeploymentContext.java#L26). So the config key for the zone is '@zone' (I believe you will need to quote that in a yaml file).

**Comment by dsyer** [comment]
We now use `eureka.instance.metadataMap.zone` as a default setting.

**Comment by stefanocke** [comment]
@dsyer 
Thank you so much for explanation and for the fix. It was indeed as easy as this in application.yml:

`"@zone": myzone`

And with your fix, I can remove that soon in favor of `eureka.instance.metadataMap.zone`.
