### ISSUE TITLE
Expose Zuul using multiple host names

### ISSUE THREAD

**Issue by rbkumar88** [spring-cloud/spring-cloud-netflix#996]
Is there any way we can expose the Zuul server itself with multiple host names(like HOST1.com,HOST2.com)
Say, From our F5 LTM, we want to route the requests to Zuul server(which acts as proxy for all our services). 

The issue is we want to access all applications/services using these host names.
https://HOST1.com/sampleapp
https://HOST2.com/sampleapp

Considering sampleapp is one of the routes in Zuul config.

**Comment by dsyer** [comment]
Isn't that a function of the front end load balancer? How can the Spring Cloud app do anything to influence it's own hostname?

**Comment by spencergibb** [comment]
@rbkumar88 do you want to route based on the hostname?

**Comment by rbkumar88** [comment]
Hi Spencer,

Yes this is what am looking for. So this is still an enhancement and not available I guess.? 

P.S.,It would be better if we can have Zuul exposed using multiple host names (as we do in apache httpd or nginx proxy). The #285 is for single host name I believe.

Thanks
Bharath

**Comment by spencergibb** [comment]
#285 is route to any service by hostname, so hosta -> servicea, hostb -> serviceb, etc... I'm still unsure what you are asking by `if we can have Zuul exposed using multiple host names`?

**Comment by rbkumar88** [comment]
In apache httpd reverse proxy, we can expose all the services (under it) using different virtual host name.
e.g., https://vhost1/app1,https://vhost1/app2,https://vhost2/app1,https://vhost2/app2 etc.

I would like to have Zuul do the same what httpd does today.
Also when I say host name, I mean virtual host name(XXX.YYY.com.,like..api.oracle.com or webservices.ms.com etc ), not the actual host name the application is mounted.

**Comment by spencergibb** [comment]
That's what #285 is for.
