### ISSUE TITLE
registerWithEureka flag has to be set to true explicitly if Eureka Client is configured in bootstrap context

### ISSUE THREAD

**Issue by maxromanovsky** [spring-cloud/spring-cloud-netflix#999]
If Eureka Client is configured in `bootstrap` context (case: discovery of config server via Eureka), then `eureka.client.registerWithEureka` has to be set explicitly to `true` in `application` configuration. Otherwise service is not registered with Eureka.

This is related to https://github.com/spring-cloud/spring-cloud-netflix/commit/093354e23130741e6e4493a931d8b3641f6c4971

**Comment by spencergibb** [comment]
@maxromanovsky running a client with `spring.cloud.config.discovery.enabled=true` registered just fine for me. Can you provide a project that recreates the situation?

**Comment by maxromanovsky** [comment]
@spencergibb 
I'm sorry. After the long investigation I realised that I forgot to add `@EnableEurekaClient` to my application :)

However, even without it app successfully connects to the Eureka in order to discover Config Server.
